PWGLF/NUCLEX/CMakeLists.txt, PWGLF/NUCLEX/Nuclei/AbsorptionRatios/AliAnalysisTaskHe3.cxx, PWGLF/NUCLEX/Nuclei/AbsorptionRatios/AliAnalysisTaskHe3.h, PWGLF/NUCLEX/PWGLFnuclexLinkDef.h
- Commented out any print (cout) statements
- Fixed a minor bug in the header.
- Added my Analysis to the CMakeList and LinkDef files.
=> Added my analysis files to CMakeList and LinkDef files so that they get compiled.

PWGCF/FEMTOSCOPY/FemtoDream/AliFemtoDreamTrack.cxx, PWGCF/FEMTOSCOPY/FemtoDream/AliFemtoDreamTrack.h
o plus a minor improvement in the computation of beta
=> Make TOF Beta accesible in the NanoAODs

PWGUD/UPC/AliAnalysisTaskForMCpPb.cxx, PWGUD/UPC/AliAnalysisTaskForMCpPb.h
Fixed efficiency issues in the MC.
=> PWGUD/UPC: Proper efficiencies.

PWGGA/GammaConvBase/AliCaloPhotonCuts.cxx
Energy Shift depends on Clusters > 1GeV
=> PWGGA: Shift PHOS Cluster Energies to Pi0 Mass

PWGGA/GammaConv/AliAnalysisTaskGammaCalo.cxx, PWGGA/GammaConv/AliAnalysisTaskGammaCalo.h, PWGGA/GammaConv/AliAnalysisTaskGammaConvCalo.cxx, PWGGA/GammaConv/AliAnalysisTaskGammaConvCalo.h, PWGGA/GammaConv/macros/AddTask_GammaCalo_pp.C, PWGGA/GammaConv/macros/AddTask_GammaConvCalo_pp.C
Energy Calibration Histograms for LightOutput added
=> Add ECalib Histograms to LightOutput when flag 5 is used

PWGLF/RESONANCES/PostProcessing/f0980/AliAnalysisTaskInclusivef0f2.cxx
=> [PWGLF] modify switch

PWGHF/vertexingHF/AliAnalysisVertexingHF.cxx
- do not recalculate primary vertex
- remove unnecessary copy+delete of object
- set selection bits also in case of filtering from ESDs
=> Cleanup of MakeCascade method 

PWGGA/GammaConv/AliAnalysisTaskGammaCalo.cxx
Missing Histogram Fill Condition added
=> PWGGA: Fixed missing  || fDoECalibOutput

PWGDQ/reducedTree/AliReducedVarManager.cxx, PWGDQ/reducedTree/AliReducedVarManager.h
- streamlined/generalized setting of efficiency maps for associated hadrons
- generalized setting of efficiency maps for J/psi candidates
- added J/psi and J/psi*hadron efficiency correction for correlation
=> PWGDQ/reducedTree: updates for efficiency correction

PWGHF/correlationHF/AliAnalysisTaskDHFeCorr.cxx, PWGHF/correlationHF/AliAnalysisTaskDHFeCorr.h
Dear all,
I updated how the PID is saved to better handle the reflections.
Best
Henrique
=> Update PID for reflections

PWGMM/UE/CMakeLists.txt, PWGMM/UE/PWGMMueLinkDef.h, PWGMM/UE/UeKNO/AddTaskMcKnoUe.C, PWGMM/UE/UeKNO/AliAnalysisTaskMcKnoUe.cxx, PWGMM/UE/UeKNO/AliAnalysisTaskMcKnoUe.h
MC closure test for Nch in transverse region.
=> analysis task for KNO scaling UE

PWGMM/UE/CMakeLists.txt, PWGMM/UE/PWGMMueLinkDef.h, PWGMM/UE/UeMpi/AddTaskMpiUE.C, PWGMM/UE/UeMpi/AliAnalysisTaskMpiUE.cxx, PWGMM/UE/UeMpi/AliAnalysisTaskMpiUE.h
Analysis task for the measurement of UE in p-Pb collisions
=> UE analysis for p-Pb, on behalf of Ahsan khan

PWGCF/Correlations/macros/jcorran/AddTaskRidge.C
=> [PWGCF] Change the AliDirList name

PWGDQ/reducedTree/AliCorrelationExtraction.cxx, PWGDQ/reducedTree/AliCorrelationExtraction.h
correction for trigger particle normalization
=> PWGDQ/reducedTree/AliCorrelationExtraction: efficiency correction

PWGGA/GammaConv/macros/AddTask_GammaCalo_pp.C, PWGGA/GammaConv/macros/AddTask_GammaConvCalo_pp.C
Add INT7 and PHI7 as independet cutcfg
=> PWGGA: Add INT7 and PHI7 as independet cutcfg

PWGMM/UE/UeKNO/AliAnalysisTaskMcKnoUe.cxx, PWGMM/UE/UeKNO/AliAnalysisTaskMcKnoUe.h
New histograms were added to perform the MC closure test
=> inclusion of corrections for UE ana

PWGGA/GammaConv/macros/AddTask_GammaConvDalitzV1_pp.C, PWGGA/GammaConvBase/AliDalitzAODESD.cxx, PWGGA/GammaConvBase/AliDalitzAODESD.h, PWGGA/GammaConvBase/AliDalitzElectronCuts.cxx
Extra function on stand by
Regards 
Ed
=> New config and Extra function

PWGLF/RESONANCES/macros/mini/AddTaskSigPM.C
small change in the event cuts affecting the triggers
=> small change in the event cuts affecting the triggers

PWGHF/correlationHF/AliAnalysisTaskDHFeCorr.cxx, PWGHF/correlationHF/AliAnalysisTaskDHFeCorr.h, PWGHF/correlationHF/macros/default_config_d_hfe.yaml
Dear all,
I have done some minor changes to ignore the vertex reconstruction (useful to run in Pb-Pb) and some other minor changes.
Best,
Henrique
=> Optimizations for Pb-Pb

PWGGA/GammaConv/macros/AddTask_GammaConvDalitzV1_pp.C
=> Test config

PWGGA/GammaConvBase/AliConvEventCuts.cxx
PWGGA: Add PHOS Trigger to AliConvEventCuts::MimicTrigger
=> PWGGA: Add PHOS Trigger to AliConvEventCuts::MimicTrigger

PWGCF/FEMTOSCOPY/FemtoDream/AliAnalysisTaskNanoPt.cxx, PWGCF/FEMTOSCOPY/FemtoDream/AliAnalysisTaskNanoPt.h, PWGCF/FEMTOSCOPY/macros/AddTaskNanoPt.C
Test code for MC in NanoAOD task for Proton-deuteron analysis added
=> Test Code for MC included

PWGCF/FLOW/GF/AliAnalysisTaskUniFlow.cxx
Fixed seg fault when running with #RFP as a centrality estimator
=> Fixed Nch problem

PWGDQ/dielectron/LMEE/AliAnalysisTaskReducedTreeDS.cxx, PWGDQ/dielectron/LMEE/AliAnalysisTaskReducedTreeDS.h
make pre-selection of tracks loose to see phiv cut performance
=> loose pre-selection of tracks

PWG/EMCAL/config/AliEmcalCorrectionConfiguration.yaml
After some problems were reported with the time calibration, we decided to revert back default settings to the original default values.
=> Reverting the default setting back to the original value

PWGCF/EBYE/CMakeLists.txt, PWGCF/EBYE/PWGCFebyeLinkDef.h, PWGCF/EBYE/StronglyIntensiveCorrelations/AddMyTaskStronglyIntensiveCorrTree.C, PWGCF/EBYE/StronglyIntensiveCorrelations/AliAnalysisTaskStronglyIntensiveCorrTree.cxx, PWGCF/EBYE/StronglyIntensiveCorrelations/AliAnalysisTaskStronglyIntensiveCorrTree.h
class to analysis FB correlations and strongly intensive quantities. 
Added header and body files with add task macro.
=> analysis code of stongly intensive and FB correlations

PWGLF/RESONANCES/macros/mini/AddTaskLambdaStarWithKinks.C
wrong path to the config file corrected
=> wrong path to the config file corrected

PWGGA/GammaConvBase/AliCaloPhotonCuts.cxx, PWGUD/UPC/AddTaskEtaCAWP.C, PWGUD/UPC/AliAnalysisTaskUpcEtaCAWP.cxx, PWGUD/UPC/AliAnalysisTaskUpcEtaCAWP.h
Added files to continue eta_C analysis performed by canson
=> Added AddTaskEtaCAWP.C and Eta_C analysis Files

PWGDQ/dielectron/core/AliAnalysisTaskEtaReconstruction.cxx, PWGDQ/dielectron/core/AliAnalysisTaskEtaReconstruction.h, PWGDQ/dielectron/core/AliDielectronMC.cxx, PWGDQ/dielectron/macrosLMEE/AddTask_feisenhut_EtaReconstruction.C, PWGDQ/dielectron/macrosLMEE/Config_feisenhut_EtaReconstruction.C, PWGDQ/dielectron/macrosLMEE/LMEECutLib_feisenhut.C
I reworked the two and four pairing of the EtaReconstruction Programm
Added Histograms 
Deleted a Comment that was pushed accidentally into AliDielectronMC.cxx
=> Rework of Two and Four Pairing, implemented SupportHistograms for all Cutsettings, deleted a comment

PWGHF/correlationHF/AliAnalysisTaskDHFeCorr.cxx, PWGHF/correlationHF/AliAnalysisTaskDHFeCorr.h
I have changed part of the code to ensure that the PID selection is applied i(f requested) and that the PID information for the default PID is saved in any case.
=> PID requirement

PWGCF/FEMTOSCOPY/FemtoDream/AliFemtoDreamCollConfig.cxx, PWGCF/FEMTOSCOPY/FemtoDream/AliFemtoDreamCollConfig.h, PWGCF/FEMTOSCOPY/FemtoDream/AliFemtoDreamCorrHists.cxx, PWGCF/FEMTOSCOPY/FemtoDream/AliFemtoDreamCorrHists.h, PWGCF/FEMTOSCOPY/FemtoDream/AliFemtoDreamHigherPairMath.cxx, PWGCF/FEMTOSCOPY/macros/AddTaskFemtoDreamPion.C, PWGCF/FEMTOSCOPY/macros/AddTaskNanoAODFemtoDreamPion.C
Plus changes to the AddTaskMacros for additional QA and the new feature.
=> Include new feature: kT vs k* 2D-hists for set multBins.

PWGLF/NUCLEX/Hypernuclei/KF2Body/AddHypertritonKFTree.C, PWGLF/NUCLEX/Hypernuclei/KF2Body/AliAnalysisTaskHypertritonKFTree.cxx, PWGLF/NUCLEX/Hypernuclei/KF2Body/AliAnalysisTaskHypertritonKFTree.h
Add new task for the reconstruction of hypertriton using KFParticle
=> Hypertriton reconstruction using KFParticle (2-body)

PWGUD/UPC/AliAnalysisTaskUpcRho0.cxx, PWGUD/UPC/AliAnalysisTaskUpcRho0.h
task is capable to run over C1ZED, trigger info for V0 was added
=> C1ZED trigger added

PWGDQ/dielectron/core/AliDielectronHelper.cxx, PWGDQ/dielectron/core/AliDielectronHelper.h, PWGDQ/dielectron/core/AliDielectronVarManager.cxx, PWGDQ/dielectron/core/AliDielectronVarManager.h
PWGDQ: LMee: event variables for spherocity calculation
=>  PWGDQ: LMEE: event variables for different Spherocity calculations

PWGLF/SPECTRA/Kinks/AliAnalysisKinkTaskPbPb2018.cxx, PWGLF/SPECTRA/Kinks/AliAnalysisKinkTaskPbPb2018.h
corrrection on the accepted triggers by this class + multiplicity distribution
=> corrrection on the accepted triggers by this class

PWGCF/EBYE/CMakeLists.txt, PWGCF/EBYE/PWGCFebyeLinkDef.h, PWGCF/EBYE/StronglyIntensiveCorrelations/AddMyTaskStronglyIntensiveCorrTree.C, PWGCF/EBYE/StronglyIntensiveCorrelations/AliAnalysisTaskStronglyIntensiveCorrTree.cxx, PWGCF/EBYE/StronglyIntensiveCorrelations/AliAnalysisTaskStronglyIntensiveCorrTree.h
add class and task to analysis strongly intensive quantities and FB corr
=> add class and task to analysis strongly intensive quantities and FB corr

PWGLF/NUCLEX/CMakeLists.txt, PWGLF/NUCLEX/Hypernuclei/KF2Body/AliAnalysisTaskHypertritonKFTree.h, PWGLF/NUCLEX/PWGLFnuclexLinkDef.h
This supersedes #12427, @SHornung1
=> Fix Hypertriton KF task inclusion

PWGDQ/dielectron/core/AliDielectronHelper.cxx, PWGDQ/dielectron/core/AliDielectronHelper.h
PWGDQ: LMee: spherocity calculation update
=> PWGDQ: LMEE: spherocity calculation update

PWGUD/UPC/AddTaskUPCforward.C, PWGUD/UPC/AliAnalysisTaskForMCpPb.cxx, PWGUD/UPC/AliAnalysisTaskForMCpPb.h, PWGUD/UPC/AliAnalysisTaskUPCforward.cxx, PWGUD/UPC/AliAnalysisTaskUPCforward.h, PWGUD/UPC/AliAnalysisTaskUPCforwardpPb.cxx
=> PWGUD/UPC: trigger efficiency for polarisation systematics.

PWGJE/FlavourJetTasks/AliAnalysisTaskHFJetIPQA.cxx, PWGJE/FlavourJetTasks/AliAnalysisTaskHFJetIPQA.h
- add function SelectV0Candidates that rejects V0s for tracks entering the tagging criteriums
- add function GetV0MCTrueCandidates to track true V0s in jet cones
- add function GetV0MCVeto to get Veto from MC for V0 rejection 
- change booleans for DoTCTagging and DoProbTagging to integers such that different settings can be run
=> AliAnalysisTaskHFJetIPQA: add V0 rejection

PWGMM/UE/UeKNO/AddTaskMcKnoUe.C, PWGMM/UE/UeKNO/AliAnalysisTaskMcKnoUe.cxx, PWGMM/UE/UeKNO/AliAnalysisTaskMcKnoUe.h
=> new function to set ptmin

PWGDQ/dielectron/LMEE/AliAnalysisTaskReducedTreeDS.cxx, PWGDQ/dielectron/LMEE/AliAnalysisTaskReducedTreeDS.h
add MC variables (secondary from material, secondary from weak decay)
=> add MC variables for secondary electrons

PWGDQ/dielectron/macrosLMEE/AddTask_acapon.C, PWGDQ/dielectron/macrosLMEE/Config_acapon.C
Low mass fine binning restricts mass range to mee < 50 MeV
=> Add super fine binning for low mass search

PWGGA/EMCALTasks/AliAnalysisTaskGammaHadron.cxx, PWGGA/EMCALTasks/AliAnalysisTaskGammaHadron.h
Adds updated pi0 windows (for GA trigger)
Adds abilitiy to choose window set and centrality dependence
=> Updates to pi0 windows

PWGCF/Correlations/JCORRAN/Pro/AliAnalysisTaskRidge.cxx
=> [PWGCF] Enlarge Jet bin definition

PWGLF/SPECTRA/MultEvShape/AliMESpidTask.cxx, PWGLF/SPECTRA/MultEvShape/AliMESpidTask.h, PWGLF/SPECTRA/MultEvShape/AliMEStrackInfo.cxx, PWGLF/SPECTRA/MultEvShape/run.C
AliMESpidTask.cxx .h - major modification to be used for unfolding
AliMEStrackInfo.cxx - modified TOF PID detector mask
run.C - updated AddTaskPIDResponse parameters for MC
=> Major task modifications for unfolding

PWGHF/treeHF/AliAnalysisTaskSEHFTreeCreator.cxx, PWGHF/treeHF/AliAnalysisTaskSEHFTreeCreator.h, PWGHF/treeHF/macros/AddTaskHFTreeCreator.C, PWGHF/vertexingHF/AliVertexingHFUtils.cxx, PWGHF/vertexingHF/AliVertexingHFUtils.h
* A general PreSelectITSUpgrade that acts on HF candidate before refilling using the MC info
* Some fixes/updates in TreeCreator task for the "features" of the new ITS2 Upgrade MC
=> PWGHF: Updates for new ITS2 Upgrade MC

PWGDQ/dielectron/core/AliAnalysisTaskEtaReconstruction.cxx, PWGDQ/dielectron/core/AliAnalysisTaskEtaReconstruction.h, PWGDQ/dielectron/macrosLMEE/AddTask_feisenhut_EtaReconstruction.C, PWGDQ/dielectron/macrosLMEE/Config_feisenhut_EtaReconstruction.C
implemented some additional mass cuts and reworked some cutsettigns
=>  PWGDQ EtaReconstruction: Some updates for mass cuts

PWGGA/GammaConv/macros/AddTask_GammaConvNeutralMesonPiPlPiMiNeutralMeson_CaloMode_pp.C, PWGGA/GammaConvBase/AliConversionMesonCuts.cxx
-- adapted inv mass cut to better fit with 7 TeV data
-- added configs for sys variations LHC11
=> PWGGA/GammaConv: adapted pi0 masscut for 7TeV + final nonlin & more

PWGUD/UPC/AddTaskUPCforward.C
Switched to output list for the LEGO train suffix.
=> PWGUD/UPC: Suffix to list, not to folder.

PWGDQ/dielectron/core/AliAnalysisTask_JPsi_EMCal.cxx, PWGDQ/dielectron/core/AliAnalysisTask_JPsi_EMCal.h, PWGDQ/dielectron/macrosJPSI/Config_JPsi_EMCal.C
including possibility to use DCAL trigger together with EMCal trigger, as a single detector
=> including DCAL trigger

PWGGA/EMCALTasks/AliAnalysisTaskGammaHadron.cxx, PWGGA/EMCALTasks/AliAnalysisTaskGammaHadron.h
Fixes mistake in mass window code
Cleans up mass window code
=> Fixes mistake in mass window code

PWGUD/UPC/AddTaskUPCforward.C
AliAnalysisTaskUPCforward* task = new AliAnalysisTaskUPCforward(Form("MyOutputContainer%s", suffix), _fSetSingleMuonPt);
IMPORTANT: tested
=> PWGUD/UPC: Fixed task's name in AddTask.

PWG/FLOW/Tasks/AliAnalysisTaskCMEV0PID.cxx
Added PID selection using TPC/TOF to my AnalysisTask
=> Added PID selection to AnalysisTask

PWGJE/EMCALJetTasks/UserTasks/AliAnalysisTaskEA.cxx, PWGJE/EMCALJetTasks/UserTasks/AliAnalysisTaskEA.h
the ouput has been too large  i  reduced number of output plots
(i willl fill histogram only for one rho estimator,  and i will not fill centrality histograms)
=> Reduction of number of output histograms

PWGLF/RESONANCES/macros/mini/AddTaskRare_pp13.C, PWGLF/RESONANCES/macros/mini/AddTaskResonanceFinder.C, PWGLF/RESONANCES/macros/mini/ConfigPhiPP13TeV_PID.C
modifications to my AddTask and Config macros, needed for studies of rare resonances, pentaquarks, and phi
=> modified macros for rare resonances and phi

PWGJE/doc/READMEunfolding.txt
As per our discussion, I briefly wrote up these questions so that we we would have a reference in AliDoc. Let me know if you'd like any additions or changes
@mfasDa @lcunquei
=> Add notes on unfolding normalization

PWGDQ/dielectron/core/AliDielectronHelper.cxx
PWGDQ: LMee: update Spherocity calculation
=> PWGDQ: LMEE: update Spherocity calculation

PWGCF/FEMTOSCOPY/AliFemto/AliFemtoEventReaderAOD.cxx
=> Fix bug: Eta<0.8 -> Abs(Eta)<0.8

PWGHF/vertexingHF/charmFlow/AliAnalysisTaskHFv1.cxx, PWGHF/vertexingHF/charmFlow/AliAnalysisTaskHFv1.h
The changes in the macro and corresponding header file were made in order to separate the data for the Dstar particle and Dstar anti-particle for further analysis of the v1.
=> V1adaptions

PWGJE/EMCALJetTasks/UserTasks/AliAnalysisTaskEmcalJetCorrection.cxx, PWGJE/EMCALJetTasks/UserTasks/AliAnalysisTaskEmcalJetCorrection.h
Make sure the tasks works with current version of ROOT/AliPhysics/python-modules.
=> ML-based background correction grid task

PWGCF/Correlations/DPhi/AliAnalysisTaskV0ChCorrelation.cxx, PWGCF/Correlations/macros/AddTaskV0ChCorrelationPrei.C
I have been separated two addTask for central and peripheral to run it separately on two wagons
=> Task V0-h central and peripheral

PWGHF/treeHF/AliAnalysisTaskSEHFTreeCreator.cxx, PWGHF/treeHF/AliAnalysisTaskSEHFTreeCreator.h, PWGHF/treeHF/AliHFTreeHandler.cxx, PWGHF/treeHF/AliHFTreeHandler.h, PWGHF/treeHF/AliHFTreeHandlerLc2V0bachelor.cxx, PWGHF/treeHF/macros/AddTaskHFTreeCreator.C
Adding kCentral and kSemiCentral brances
=> PWGHF: Add branch for triggers Pb-Pb

PWGCF/FEMTOSCOPY/macros/Train/malinina/Dec2019/KK_13TeV_dist/AddTaskFemtoKchHBT1090.C, PWGCF/FEMTOSCOPY/macros/Train/malinina/Dec2019/KK_13TeV_dist/ConfigFemtoAnalysis.C, PWGCF/FEMTOSCOPY/macros/Train/malinina/Dec2019/KK_13TeV_jets/AddTaskFemtoKchHBT1090.C, PWGCF/FEMTOSCOPY/macros/Train/malinina/Dec2019/KK_13TeV_jets/ConfigFemtoAnalysis.C, PWGCF/FEMTOSCOPY/macros/Train/malinina/Dec2019/pipi_13TeV_dist/AddTaskFemtoKchHBT1090.C, PWGCF/FEMTOSCOPY/macros/Train/malinina/Dec2019/pipi_13TeV_dist/ConfigFemtoAnalysis.C, PWGCF/FEMTOSCOPY/macros/Train/malinina/Dec2019/pipi_13TeV_jets/AddTaskFemtoKchHBT1090.C, PWGCF/FEMTOSCOPY/macros/Train/malinina/Dec2019/pipi_13TeV_jets/ConfigFemtoAnalysis.C
=> Lego Train Macros for Ludmila Dec19

PWGHF/vertexingHF/macros/AddTaskSignificance.C
i made small changes to make it works running on grid
=> modified AddTaskSignificance

PWGMM/UE/UeKNO/AliAnalysisTaskMcKnoUe.cxx, PWGMM/UE/UeKNO/AliAnalysisTaskMcKnoUe.h
some histograms were included, they are needed for the 2D unfolding
=> vtx correction

PWGLF/NUCLEX/CMakeLists.txt, PWGLF/NUCLEX/Hypernuclei/DoubleHypNuc/AddTask_jditzel_DoubleHypNucTree.C, PWGLF/NUCLEX/Hypernuclei/DoubleHypNuc/AliAnalysisTaskDoubleHypNucTree.cxx, PWGLF/NUCLEX/Hypernuclei/DoubleHypNuc/AliAnalysisTaskDoubleHypNucTree.h, PWGLF/NUCLEX/PWGLFnuclexLinkDef.h
Added Folder and Code for the DoubleHyperHydrogen4 Analysis by using several methods (e.g. V0 Finder). Also changed the CMakeLists.txt and PWGLFLinkDef.h for this purpose. AliPhysics was locally tested.
=> Code for the DoubleHyperHydrogen4 Analysis

PWGJE/EMCALJetTasks/UserTasks/AliAnalysisTaskEventExtractor.cxx
Also some minor modernizations to make iteration of particle and track
containers safer
=> Make eta limits configurable

PWGMM/UE/UeKNO/AliAnalysisTaskMcKnoUe.cxx, PWGMM/UE/UeKNO/AliAnalysisTaskMcKnoUe.h
New histograms are added in order to study different selection effects
=> trigger effect

PWGMM/UE/UeKNO/AliAnalysisTaskMcKnoUe.cxx
=> cut on vtxzMC

PWGCF/Correlations/DPhi/AliAnalysisTaskV0ChCorrelation.cxx, PWGCF/Correlations/DPhi/AliAnalysisTaskV0ChCorrelationpp.cxx, PWGCF/Correlations/macros/AddTaskV0ChCorrelationpp.C
in this task i have been fixed pt for pp  , and  for Pb_Pb ,i fixed  the binning  of  mixing
=> Task for pp and Pb_Pb

PWGGA/GammaConv/macros/AddTask_GammaCalo_pp.C, PWGGA/GammaConv/macros/AddTask_GammaConvNeutralMesonPiPlPiMiNeutralMeson_CaloMode_pp.C, PWGGA/GammaConv/macros/AddTask_GammaHeavyMeson_CaloMode_pp.C, PWGGA/GammaConvBase/AliCaloPhotonCuts.cxx
Also modified EDC NonLin settings for LowB p 13 TeV analysis.
Added two new train configs for eta->pi+pi-pi0 in pp 13 TeV
=> PWGGA/GammaConv: Added new train configs for EDC pp 13 TeV for pi0 and eta. 

PWGCF/FEMTOSCOPY/macros/Train/KpmHBT23/0010/AddTaskFemtoKchHBT0010.C, PWGCF/FEMTOSCOPY/macros/Train/KpmHBT23/0010/ConfigFemtoAnalysis.C, PWGCF/FEMTOSCOPY/macros/Train/KpmHBT23/1090/AddTaskFemtoKchHBT1090.C, PWGCF/FEMTOSCOPY/macros/Train/KpmHBT23/1090/ConfigFemtoAnalysis.C
=> Lego Train macro: Global Tracks K+K-

PWGHF/vertexingHF/AliAnalysisTaskSELc2V0bachelorTMVAApp.cxx, PWGHF/vertexingHF/AliAnalysisTaskSELc2V0bachelorTMVAApp.h, PWGHF/vertexingHF/macros/AddTaskLc2V0bachelor_TMVAApp.C
@chiarazampolli @andreaalici FYI
=> Possibility to use xml files loaded on CVMFS for BDT application (F. Jonkman)

PWGDQ/dielectron/macrosLMEE/AddTask_dsekihat_lowmass_PbPb_ESD.C, PWGDQ/dielectron/macrosLMEE/Config_dsekihat_lowmass_PbPb_ESD.C
add AddTask and Config macro for 2018 PbPb ESD
=> PWGDQ/LMEE add AddTask and Config macros

PWGCF/EBYE/BalanceFunctions/HFtest/AddTaskLcToD0MC.C, PWGCF/EBYE/BalanceFunctions/HFtest/AliAnalysisTaskLcToD0MC.cxx, PWGCF/EBYE/BalanceFunctions/HFtest/AliAnalysisTaskLcToD0MC.h, PWGCF/EBYE/BalanceFunctions/HFtest/runTaskLcToD0MC.C, PWGCF/EBYE/CMakeLists.txt, PWGCF/EBYE/PWGCFebyeLinkDef.h
this is a temporary place for testing purposes, will find later a better solution
=> Adding a test directory for the HF analysis

PWGCF/FEMTOSCOPY/macros/Train/KpmHBT23/0010/ConfigFemtoAnalysis.C, PWGCF/FEMTOSCOPY/macros/Train/KpmHBT23/1090/ConfigFemtoAnalysis.C
=> Lego Train KpmHBT23: GlobalTracks

PWGDQ/dielectron/core/AliDielectronHistos.cxx, PWGDQ/dielectron/core/AliDielectronHistos.h, PWGDQ/dielectron/core/AliDielectronVarManager.cxx, PWGDQ/dielectron/core/AliDielectronVarManager.h, PWGDQ/dielectron/macrosLMEE/AddTask_dsekihat_lowmass_PbPb_ESD.C, PWGDQ/dielectron/macrosLMEE/Config_dsekihat_lowmass_PbPb_ESD.C
add more variables in AliDielectronVarManager and flexibility to define THnSparse in AliDielectronHisto
=> PWGDQ/LMEE: add more variables in AliDielectronVarManager

PWGDQ/dielectron/core/AliDielectronVarManager.cxx, PWGDQ/dielectron/core/AliDielectronVarManager.h, PWGDQ/dielectron/macrosLMEE/Config_dsekihat_lowmass_PbPb_ESD.C
change ITS layer index for kNclsITS[1-6] just for consistency with other variables
=> PWGDQ/LMEE: change ITS layer index for kNclsITS[1-6]

PWGDQ/dielectron/core/AliDielectronVarManager.cxx, PWGDQ/dielectron/core/AliDielectronVarManager.h
add pileup variables for TPC (pileupZ and pileupM)
=> PWGDQ/LMEE: add TPC pileup variables

PWGLF/RESONANCES/PostProcessing/f0980/AliAnalysisTaskInclusivef0f2.cxx
=> [PWGLF] Add Pileup Cut switch

PWGDQ/dielectron/core/AliDielectronEventCuts.cxx, PWGDQ/dielectron/core/AliDielectronEventCuts.h
add V0-TPC pileup cuts and update bad time range cut of TPC PID
=> PWGDQ/LMEE: update event cuts

PWGDQ/dielectron/core/AliDielectronVarManager.h
=> PWGDQ/LMEE: get kNTPCclsEvent in ESD

PWGDQ/dielectron/core/AliDielectron.cxx, PWGDQ/dielectron/core/AliDielectron.h, PWGDQ/dielectron/core/AliDielectronPID.cxx, PWGDQ/dielectron/core/AliDielectronPID.h
support post PID calibration in pileup events
=> PWGDQ/LMEE: support post PID calib in pileup events

PWGCF/Correlations/DPhi/AliAnalysisTaskV0ChCorrelationpp.cxx, PWGCF/Correlations/DPhi/AliAnalysisTaskV0ChCorrelationpp.h, PWGCF/Correlations/macros/AddTaskV0ChCorrelationpp.C
I updated the task for pp to make it convenient  for sys
=> V0-h pp  updated task

PWGMM/UE/UeKNO/AliAnalysisTaskMcKnoUe.cxx
new correction factor has been added
=> fix misrec of leading particle

PWGDQ/dielectron/core/AliDielectron.cxx, PWGDQ/dielectron/core/AliDielectronPID.cxx, PWGDQ/dielectron/core/AliDielectronVarManager.h
add flexibilities to calibrate post-PID for all particle species
=> PWGDQ/LMEE: add flexibilities to calibrate PID for all particle species

PWGMM/UE/UeKNO/AliAnalysisTaskMcKnoUe.cxx, PWGMM/UE/UeKNO/AliAnalysisTaskMcKnoUe.h
=> data driven method for lead misrec effect

PWGDQ/dielectron/core/AliDielectronEventCuts.cxx, PWGDQ/dielectron/core/AliDielectronEventCuts.h
remove unnecessary hard-coded pileup cut
=> PWGDQ/LMEE: remove unnecessary hard-coded pileup cut

PWGDQ/dielectron/core/AliAnalysisTaskElectronEfficiencyV2.cxx, PWGDQ/dielectron/core/AliAnalysisTaskElectronEfficiencyV2.h
add temporary solution to compare generator name in LHC19f2 MC productions
=> PWGDQ/LMEE: add temporary solution to get genname in LHC19f2 MC

PWGMM/UE/UeKNO/AliAnalysisTaskMcKnoUe.cxx
fixing a bug: selection bias effect
=> selection bias effect

PWGGA/GammaConv/AliAnalysisTaskMaterialHistos.cxx, PWGGA/GammaConv/AliAnalysisTaskMaterialHistos.h, PWGGA/GammaConv/macros/userSpecific/AddTask_MBW.C
this needs to be fixed (other wise task will crash): AliAnalysisTaskMaterialHistos.cxx line 334
=> bug fix and removed unnecessary variables

PWGGA/CaloTrackCorrelations/macros/ConfigureCaloTrackCorrAnalysis.C
=> move setting of isolation cuts in different subtasks to a common method

PWGGA/GammaConv/macros/AddTask_GammaCalo_pp.C
In order to compare inJet and MB, I request the mail.
This is my first pull request. 
Best regards,
=> Add trainConfig 917

PWGMM/UE/UeKNO/AliAnalysisTaskMcKnoUe.cxx, PWGMM/UE/UeKNO/AliAnalysisTaskMcKnoUe.h
=> new histograms for data driven mis leading pT rec

PWGMM/UE/UeKNO/AliAnalysisTaskMcKnoUe.cxx, PWGMM/UE/UeKNO/AliAnalysisTaskMcKnoUe.h
The last correction factor has been implemented
=> new histos for evaluating the analysis strategy

PWGMM/UE/UeKNO/AliAnalysisTaskMcKnoUe.cxx
for mult RM, the binning was inverted. Now it should be ok.
=> minor change to mult response matrix

PWGCF/Correlations/DPhi/AliAnalysisTaskV0ChCorrelation.cxx, PWGCF/Correlations/DPhi/AliAnalysisTaskV0ChCorrelation.h, PWGCF/Correlations/DPhi/AliAnalysisTaskV0ChCorrelationpp.cxx, PWGCF/Correlations/macros/AddTaskV0ChCorrelation.C, PWGCF/Correlations/macros/AddTaskV0ChCorrelationPrei.C, PWGCF/Correlations/macros/AddTaskV0ChCorrelationpp.C
I updated the task  V0-Ch for pp and Pb_Pb to make it easy for sys and i changed the cuts for Vtx and mix
=> Updated task V0ch for pp and Pb_Pb

PWGCF/FEMTOSCOPY/FemtoDream/AliAnalysisTaskPOmegaPenne.cxx, PWGCF/FEMTOSCOPY/FemtoDream/AliAnalysisTaskPOmegaPenne.h, PWGCF/FEMTOSCOPY/macros/AddTaskPOmegaPenne.C
bin fix and object creation fix
=> fixing runtime problem

PWGHF/vertexingHF/AliAnalysisTaskSECharmHadronvnTMVA.cxx, PWGHF/vertexingHF/macros/AddTaskCharmHadronvnTMVA.C
Fixed possible breaks calling impar d0
=> Fixed possible breaks calling impar d0

PWGHF/jetsHF/AliAnalysisTaskIPCalib.cxx, PWGHF/jetsHF/AliAnalysisTaskIPCalib.h, PWGHF/jetsHF/macros/AddTaskIPCalib.C
We are trying to investigate a new method for correcting the IP in MC which follows the same procedure as [https://www.sciencedirect.com/science/article/pii/0168900295012877](url). These codes extract the necessary histograms for the fitting procedure.
=> New method for correcting the IP in MC

PWGCF/Correlations/JCORRAN/Pro/AliAnalysisTaskRidge.cxx
=> [PWGCF] Modify jet selection

PWGMM/UE/UeKNO/AliAnalysisTaskMcKnoUe.cxx
An independent pTleading binning was defined
=> wider pTleading bin

PWGLF/SPECTRA/ChargedHadrons/dNdPt/AlidNdPtTools.cxx
=> added option to ESD track cuts for excluding geometrical length cut

ML/AliExternalBDT.cxx, ML/CMakeLists.txt, PWGHF/vertexingHF/vHFML/CMakeLists.txt, PWGLF/NUCLEX/CMakeLists.txt
This pr requires an AliRoot tag compiled with alisw/alidist#1957
=> Adapt to the latest treelite version

PWGCF/Correlations/DPhi/AliAnalysisTaskV0ChCorrelation.cxx, PWGCF/Correlations/DPhi/AliAnalysisTaskV0ChCorrelation.h, PWGCF/Correlations/DPhi/AliAnalysisTaskV0ChCorrelationpp.cxx, PWGCF/Correlations/macros/AddTaskV0ChCorrelation.C, PWGCF/Correlations/macros/AddTaskV0ChCorrelationPrei.C
i have been modify the binning of cent, Vtx
=> Task pp and Pb_Pb

PWG/FLOW/Tasks/AliAnalysisTaskCVE.cxx, PWG/FLOW/Tasks/AliAnalysisTaskCVE.h, PWG/FLOW/Tasks/CMakeLists.txt, PWG/FLOW/Tasks/PWGflowTasksLinkDef.h, PWGCF/FLOW/macros/AddTaskCVE.C
Added AnalysisTask for Chiral Vortical study
=> Added AnalysisTask for Chiral Vortical study

PWGDQ/dielectron/macrosLMEE/AddTask_dsekihat_ElectronEfficiencyV2_PbPb.C, PWGDQ/dielectron/macrosLMEE/AddTask_dsekihat_lowmass_PbPb.C, PWGDQ/dielectron/macrosLMEE/Config_dsekihat_ElectronEfficiencyV2_PbPb.C
=> PWGDQ/LMEE: support both ROOT6 and 5

PWGDQ/dielectron/core/AliAnalysisTaskElectronEfficiencyV2.cxx, PWGDQ/dielectron/core/AliAnalysisTaskElectronEfficiencyV2.h, PWGDQ/dielectron/macrosLMEE/AddTask_dsekihat_ElectronEfficiencyV2_PbPb.C
add possibility to fill histograms with Mee,pTee,PhiV
=> PWGDQ/LMEE: add possibility to fill histograms with Mee,pTee,PhiV

PWGMM/UE/UeKNO/AliAnalysisTaskMcKnoUe.cxx
ptleading binning was corrected in one histogram
=> ptleading binning was corrected in one histogram

PWG/FLOW/Tasks/AliAnalysisTaskCVE.cxx, PWG/FLOW/Tasks/AliAnalysisTaskCVE.h, PWGCF/FLOW/macros/AddTaskCVE.C
Added Resolution Histrograms, Fix for inf Wgt (1.0/0)
=> Added Resolution Histrograms, Fix for inf Wgt (1.0/0)

PWGDQ/dielectron/macrosLMEE/AddTask_dsekihat_ElectronEfficiencyV2_PbPb.C, PWGDQ/dielectron/macrosLMEE/AddTask_dsekihat_lowmass_PbPb.C, PWGDQ/dielectron/macrosLMEE/Config_dsekihat_ElectronEfficiencyV2_PbPb.C, PWGDQ/dielectron/macrosLMEE/Config_dsekihat_lowmass_PbPb.C, PWGDQ/dielectron/macrosLMEE/LMEECutLib_dsekihat.C
=> PWGDQ/LMEE: update AddTask.C and Config.C

PWGHF/treeHF/AliAnalysisTaskSEHFTreeCreator.cxx, PWGHF/treeHF/AliAnalysisTaskSEHFTreeCreator.h, PWGHF/treeHF/AliHFTreeHandlerBstoDspi.cxx, PWGHF/treeHF/AliHFTreeHandlerBstoDspi.h
* Storing injected Ds (prompt or FD) with random HIJING pion for background shape studies
* Use Ds PreSelect function to speed up
* Add option for basic topological selection on Bs candidate to reduce output size TTrees
=> PWGHF: Update for ITS3 background shape studies

PWGGA/GammaConv/macros/AddTask_GammaCalo_pp.C, PWGGA/GammaConv/macros/AddTask_GammaConvCalo_pp.C, PWGGA/GammaConv/macros/AddTask_GammaConvNeutralMesonPiPlPiMiNeutralMeson_CaloMode_pp.C, PWGGA/GammaConv/macros/AddTask_GammaConvNeutralMesonPiPlPiMiNeutralMeson_MixedMode_pp.C
=> PWGGA: Split cutstrings to have separate trigger and mb for phos

PWGMM/UE/UeKNO/AddTaskMcKnoUe.C
=> minor change to AddTask

PWGDQ/dielectron/core/AliDielectronVarManager.h, PWGDQ/dielectron/macrosLMEE/LMEECutLib_dsekihat.C
update TPC pileup info for LHC18qr AOD pass2
=> PWGDQ/LMEE: update TPC pileup info for LHC18qr AOD pass2

PWGDQ/dielectron/core/AliAnalysisTaskElectronEfficiencyV2.cxx
=> PWGDQ/LMEE: quick fix of phiv binning

PWGDQ/dielectron/core/AliAnalysisTaskElectronEfficiencyV2.cxx, PWGDQ/dielectron/macrosLMEE/AddTask_dsekihat_ElectronEfficiencyV2_PbPb.C, PWGDQ/dielectron/macrosLMEE/Config_dsekihat_ElectronEfficiencyV2_PbPb.C, PWGDQ/dielectron/macrosLMEE/LMEECutLib_dsekihat.C
update AddTask and Config for MC, extend pT range of support histograms
=> PWGDQ/LMEE: update AddTask and Config for MC

PWGHF/vertexingHF/AliAnalysisTaskSECharmHadronvnTMVA.cxx, PWGHF/vertexingHF/AliAnalysisTaskSECharmHadronvnTMVA.h, PWGHF/vertexingHF/macros/AddTaskCharmHadronvnTMVA.C
Added selection cuts for 3050 non-prompt D v2
=> Added selection cuts for 3050 non-prompt D v2

PWGCF/FEMTOSCOPY/AliFemto/AliFemtoEventReaderAOD.cxx, PWGCF/FEMTOSCOPY/AliFemto/AliFemtoEventReaderAOD.h, PWGCF/FEMTOSCOPY/macros/Train/malinina/Jan2020/KK_13TeV_dist/AddTaskFemtoKchHBT1090.C, PWGCF/FEMTOSCOPY/macros/Train/malinina/Jan2020/KK_13TeV_dist/ConfigFemtoAnalysis.C, PWGCF/FEMTOSCOPY/macros/Train/malinina/Jan2020/KK_13TeV_jets/AddTaskFemtoKchHBT1090.C, PWGCF/FEMTOSCOPY/macros/Train/malinina/Jan2020/KK_13TeV_jets/ConfigFemtoAnalysis.C, PWGCF/FEMTOSCOPY/macros/Train/malinina/Jan2020/pipi_13TeV_dist/AddTaskFemtoKchHBT1090.C, PWGCF/FEMTOSCOPY/macros/Train/malinina/Jan2020/pipi_13TeV_dist/ConfigFemtoAnalysis.C, PWGCF/FEMTOSCOPY/macros/Train/malinina/Jan2020/pipi_13TeV_jets/AddTaskFemtoKchHBT1090.C, PWGCF/FEMTOSCOPY/macros/Train/malinina/Jan2020/pipi_13TeV_jets/ConfigFemtoAnalysis.C
=> Ludmila: add kRefComb08 to class AliFemtoEventReaderAOD

PWGMM/UE/UeKNO/AddTaskMcKnoUe.C, PWGMM/UE/UeKNO/AliAnalysisTaskMcKnoUe.cxx, PWGMM/UE/UeKNO/AliAnalysisTaskMcKnoUe.h
The analysis task allows the following options: MC closure test, MC analysis to get correction factors, and one option to run the analysis on real data.
=> new histograms for analysis of data were added

PWGJE/EMCALJetTasks/Tracks/AliAnalysisTaskEmcalSoftDropData.cxx, PWGJE/EMCALJetTasks/Tracks/AliAnalysisTaskEmcalSoftDropResponse.cxx, PWGJE/EMCALJetTasks/Tracks/AliAnalysisTaskEmcalSoftDropResponse.h
- Fix copy/paste error at particle level leading
to det. level binning used at part. level
- Add histograms and response matrices for
theta_g (=R_g/R)
=> Fix pt binning at part. level, add theta_g

PWGUD/UPC/AliAnalysisTaskUPCforwardMC.cxx
Reweighting procedure to change MC input shape from STARlight.
IMPORTANT: tested, functionalities also ok.
=> PWGUD/UPC: Reweighting procedure to change MC input shape.

PWGLF/RESONANCES/PostProcessing/f0980/AliAnalysisTaskInclusivef0f2.cxx
Add switch to use ZNA estimator
=> [PWGLF] Add ZNA estimator

PWGHF/treeHF/AliAnalysisTaskSEHFTreeCreator.cxx
Fix segmentation violation from AliVertexingHFUtils::IsTrackInjected when running on actual data
=> PWGHF: Fix to run upgrade analyses on data

PWGGA/GammaConv/macros/AddTask_GammaCalo_pp.C
i change the train configured from 950 to 954 due to incorrect mesoncut.
Best regard, Hanseo park
=> modified trainConfig 950_954

PWGLF/STRANGENESS/Cascades/Run2/AliAnalysisTaskStrangeCascadesDiscrete.cxx, PWGLF/STRANGENESS/Cascades/Run2/AliAnalysisTaskStrangeCascadesDiscrete.h, PWGLF/STRANGENESS/Cascades/Run2/macros/AddTaskStrangeCascadesDiscrete.C
- TTree is filled only once per event. Could not resolve this mistake by testing small amounts of data. Now output is lighter.
- Some variables are stored now as UShort_t instead of Char_t
=> small bugs with TTree fixed

PWG/FLOW/Tasks/AliAnalysisTaskCMEV0PID.cxx
Added Strict PID cut and DCA cuts
=> Added Strict PID cut and DCA cuts

PWGCF/Correlations/DPhi/Unfoldedhistos/AliAnalysisTaskCorrelationsStudies.cxx, PWGCF/Correlations/DPhi/Unfoldedhistos/AliCSPairAnalysis.cxx, PWGCF/Correlations/DPhi/Unfoldedhistos/AliCSPairAnalysis.h, PWGCF/Correlations/DPhi/Unfoldedhistos/AliDptDptCorrelations.cxx, PWGCF/Correlations/DPhi/Unfoldedhistos/AliDptDptCorrelations.h
Also providing flexibility in the number of phi bins
=> Better control of the histogram binning

PWGDQ/dielectron/macrosLMEE/AddTask_dsekihat_ElectronEfficiencyV2_PbPb.C, PWGDQ/dielectron/macrosLMEE/Config_dsekihat_ElectronEfficiencyV2_PbPb.C, PWGDQ/dielectron/macrosLMEE/Config_dsekihat_lowmass_PbPb.C, PWGDQ/dielectron/macrosLMEE/LMEECutLib_dsekihat.C
update AddTask, Config and LMEECutLib
=> PWGDQ/LMEE: update AddTask, Config and LMEECutLib

PWGDQ/dielectron/macrosLMEE/AddTask_dsekihat_ElectronEfficiencyV2_PbPb.C
=> PWGDQ/LMEE: quick fix to AddTask

PWGDQ/dielectron/macrosLMEE/AddTask_dsekihat_lowmass_PbPb.C
quick fix for obj name in AddTask
=> PWGDQ/LMEE: quick fix for obj name in AddTask

PWGCF/Correlations/DPhi/AliAnalysisTaskGeneralBF.cxx
=> remove pile-up cut for MC

PWGGA/GammaConv/AliAnalysisTaskGammaConvDalitzV1.cxx, PWGGA/GammaConv/AliAnalysisTaskGammaConvDalitzV1.h, PWGGA/GammaConv/macros/AddTask_GammaConvDalitzV1_pp.C
Hello, I add to commits based on using JetJet sampling, I use the function IsJetJetMCEventAccepted and weights on the histograms.
=> JetJet sampling and 9XX configs for LowB field

PWGLF/STRANGENESS/Cascades/Run2/AliAnalysisTaskStrangeCascadesDiscrete.cxx
Instead of two loops over the tracks, there is only one left.
=> reducing cpu times

PWGHF/treeHF/AliAnalysisTaskSEHFTreeCreator.cxx, PWGHF/treeHF/AliAnalysisTaskSEHFTreeCreator.h
To be able to run tests/for QA'ing purposes on the new ITS3 MC productions
=> PWGHF: ITS3 preselect for standard D mesons

PWGLF/RESONANCES/PostProcessing/Sigma1385/AliAnalysisTaskSigma1385PM.cxx, PWGLF/RESONANCES/PostProcessing/Sigma1385/AliAnalysisTaskSigma1385PM.h
1. Update AOD checking
2. Update Mixing procedure
=> Minor update of Mixing process

PWGLF/RESONANCES/PostProcessing/Sigma1385/AliAnalysisTaskSigma1385PM.cxx, PWGLF/RESONANCES/PostProcessing/Sigma1385/AliAnalysisTaskSigma1385PM.h
=> Update variable name

PWGDQ/dielectron/core/AliDielectronPID.cxx, PWGDQ/dielectron/core/AliDielectronPID.h, PWGDQ/dielectron/core/AliDielectronVarManager.h
fix to #12824. update protection for PID calibration
=> PWGDQ/LMEE: fix to #12824

PWGCF/Correlations/JCORRAN/Pro/AliAnalysisTaskRidge.cxx
=> [PWGCF] Change Jet Selection

PWGLF/RESONANCES/PostProcessing/Sigma1385/AliAnalysisTaskSigma1385PM.h
=> Fix streamer issue

PWGCF/Correlations/JCORRAN/Pro/AliAnalysisTaskRidge.cxx
=> [PWGLF] Correct Jet selection

PWGHF/vertexingHF/charmFlow/AliAnalysisTaskHFv1.cxx
Small adaption to the binning, upper limit and lower limit of the Dstar mass spectra
=> Rebinning mass Histogram Dstar

PWGDQ/dielectron/macrosLMEE/AddTask_dsekihat_ElectronEfficiencyV2_PbPb.C, PWGDQ/dielectron/macrosLMEE/AddTask_dsekihat_lowmass_PbPb.C
add output filename in AddTask
=> PWGDQ/LMEE: add output filename in AddTask

PWGDQ/dielectron/macrosLMEE/AddTask_dsekihat_ElectronEfficiencyV2_PbPb.C
=> PWGDQ/LMEE: change pTee binning for MC

PWGHF/vertexingHF/AliVertexingHFUtils.cxx
Was checking random tracks instead of the actual prongs
=> PWGHF: Fix for IsCandidateInjected

PWGHF/treeHF/AliAnalysisTaskSEHFTreeCreator.cxx, PWGHF/treeHF/AliAnalysisTaskSEHFTreeCreator.h, PWGHF/treeHF/macros/AddTaskHFTreeCreator.C
Splitting ITS3 analysis flag into three options for more freedom:
* Flag to say you run on ITS3 production for differences in CheckOrigin
* Flag to enable ITS3 PreSelect function
* Flag to store HIJING only background
=> PWGHF: Split ITS3 Upgrade Analysis flag

PWGCF/Correlations/JCORRAN/Pro/AliAnalysisTaskRidge.cxx
=> [PWGCF] Add QA for LJET

PWGUD/UPC/AliAnalysisTaskUpcRho0.cxx, PWGUD/UPC/AliAnalysisTaskUpcRho0.h
PID histograms separated according particles
=> new histograms for PID

PWG/FLOW/Tasks/AliAnalysisTaskCVE.cxx, PWG/FLOW/Tasks/AliAnalysisTaskCVE.h, PWGCF/FLOW/macros/AddTaskCVE.C
Updated: AddTask option for higher harmonic
=> Updated: AddTask option for higher harmonic

PWGLF/RESONANCES/PostProcessing/Sigma1385/AliAnalysisTaskSigma1385PM.cxx, PWGLF/RESONANCES/PostProcessing/Sigma1385/AliAnalysisTaskSigma1385PM.h
Pair cut for Sigma1385
Adopted as suggested by Evi
=> Add Assymcut option

PWGLF/RESONANCES/PostProcessing/Sigma1385/AliAnalysisTaskSigma1385PM.cxx
=> Update QA histogram binning and Eta cut of Lambda

PWGDQ/dielectron/core/AliAnalysisTaskEtaReconstruction.cxx, PWGDQ/dielectron/core/AliAnalysisTaskEtaReconstruction.h, PWGDQ/dielectron/macrosLMEE/AddTask_feisenhut_EtaReconstruction.C, PWGDQ/dielectron/macrosLMEE/Config_feisenhut_EtaReconstruction.C, PWGDQ/dielectron/macrosLMEE/LMEECutLib_feisenhut.C
I implemented the selection of V0s in order to use them in secondary pairing and use them as well in the four pairing. Also implemented cuts on AliDielectronPairs.
=> PWGDQ EtaReconstruction Implement pairing with V0s

PWGLF/RESONANCES/PostProcessing/Sigma1385/AliAnalysisTaskSigma1385PM.cxx
Will be conservative than before
=> Update logic for Lambda check

PWG/Tools/AliAnalysisTaskDummy.cxx, PWG/Tools/AliAnalysisTaskDummy.h, PWG/Tools/macros/AddTaskDummy.C
Improved dummy analysis task by adding configurable execution time per event
=> Modified AliAnalysisTaskDummy to wait a configurable time per event.

PWGJE/EMCALJetTasks/UserTasks/AliAnalysisTaskJetCoreEmcal.cxx, PWGJE/EMCALJetTasks/UserTasks/AliAnalysisTaskJetCoreEmcal.h
- add matching distance and detector level pt and phi for systematic studies
=> add optional variables in inclusive and recoil trees

PWGJE/EMCALJetTasks/CMakeLists.txt, PWGJE/EMCALJetTasks/PWGJEEMCALJetTasksLinkDef.h, PWGJE/EMCALJetTasks/UserTasks/AliAnalysisTaskJetDynamicalGrooming.cxx, PWGJE/EMCALJetTasks/UserTasks/AliAnalysisTaskJetDynamicalGrooming.h, PWGJE/EMCALJetTasks/macros/AddTaskJetDynamicalGrooming.C
Lots of cleanup to be done, but this is just the first pass
=> Add new substructure analysis task

PWGJE/EMCALJetTasks/UserTasks/AliAnalysisTaskJetDynamicalGrooming.cxx, PWGJE/EMCALJetTasks/UserTasks/AliAnalysisTaskJetDynamicalGrooming.h
Dynamical doesn't need the hard cutoff. This is one of the benefits of
the method
=> Move dynamical before hard cutoff, add # of splittings

PWG/FLOW/Tasks/AliAnalysisTaskTwoMultiCorrelations.cxx, PWG/FLOW/Tasks/AliAnalysisTaskTwoMultiCorrelations.h
> Add support to get the pT, eta and phi distributions at kine and reco levels for MC-Generator AODs
> Add support to use root file with weights on the local machine and the Grid.
> Major cleaning of the data members and the comments.
=> [PWGCF] Add support for particle weights.

PWGJE/EMCALJetTasks/UserTasks/AliAnalysisTaskJetDynamicalGrooming.cxx
Including:
- Fix labeling for det level quantities. A missing "," lead the last two
values to be truncated (but the data isn't corrupted - just disabled).
- Reduce verbosity of code.
- Remove unused code. Still more to be done.
=> Variety of minor bug fixes, task improvements

PWGMM/UE/CMakeLists.txt, PWGMM/UE/PWGMMueLinkDef.h, PWGMM/UE/UeKNO/AddTaskGenUeNchTS.C, PWGMM/UE/UeKNO/AliAnalysisTaskGenUeNchTS.cxx, PWGMM/UE/UeKNO/AliAnalysisTaskGenUeNchTS.h
New task for MCGen RT analysis
=> Task for MCGen RT analysis

PWGUD/UPC/AliAnalysisTaskUpcRho0.cxx
destructor was not properly implemented
=> histogram destructor removed

PWGGA/GammaConv/macros/AddTask_GammaConvCalo_pp.C, PWGGA/GammaConvBase/AliCaloPhotonCuts.cxx, PWGGA/GammaConvBase/AliConversionPhotonCuts.cxx, PWGGA/GammaConvBase/AliConversionPhotonCuts.h
update Nonlin for PCM-EDC pp 13 TeV
Adding plot to investigate trackPID vs pt
=> PWGGA/GammaConvBase/ 

PWGLF/RESONANCES/PostProcessing/Sigma1385/AliAnalysisTaskSigma1385PM.cxx, PWGLF/RESONANCES/PostProcessing/Sigma1385/AliAnalysisTaskSigma1385PM.h
=> Update Asymm cut to study multiplicity dependency

PWGCF/Correlations/DPhi/AliAnalysisTaskDiHadCorrelHighPt.cxx, PWGCF/Correlations/DPhi/AliAnalysisTaskDiHadCorrelHighPt.h
=> Changes in AliAnalysisTaskDiHadCorrelHighPt 

PWG/FLOW/Tasks/AliAnalysisTaskCVE.cxx, PWG/FLOW/Tasks/AliAnalysisTaskCVE.h, PWGCF/FLOW/macros/AddTaskCVE.C
Add nSigma Variation Opt. in AddTask
=> Add nSigma Variation Opt. in AddTask

PWGHF/vertexingHF/AliRDHFCutsXictoeleXifromAODtracks.cxx, PWGHF/vertexingHF/AliRDHFCutsXictoeleXifromAODtracks.h
Add the CrossedRows TPC and the Ratio CrossedRows/Findable cluster to the daughters
=> Add new 2 new cuts

PWGJE/EMCALJetTasks/UserTasks/AliAnalysisTaskNewJetSubstructure.cxx, PWGJE/EMCALJetTasks/UserTasks/AliAnalysisTaskNewJetSubstructure.h
forgot to increment class def
fixing momory leak
Adding in the studies to match subjets
=> adding in studies to match the subjets

PWGCF/FLOW/macros/AddTaskAccContForWeights.C
Add a modified AddTaskAccContForWeights.C based on PWGCF/EBYE/macros/AddTaskAccCont.C so that the distribution of e.g. pt, eta for each centrality bin can be plotted at one time properly
=> add AddTaskAccContForWeights.C for the purpose of calculating weights

PWGGA/GammaConv/AliAnalysisTaskClusterQA.cxx, PWGGA/GammaConv/AliAnalysisTaskClusterQA.h, PWGGA/GammaConvBase/AliCaloPhotonCuts.cxx, PWGGA/GammaConvBase/AliCaloPhotonCuts.h
The current function for the efficiency is a dummy and will be updated once the new cluster tree with dEdx information has run.
=> PWGGA/GammaConv: Implemented NCell cut efficiency for EMCal and added track dEdx to ClusterQA

PWGCF/FEMTOSCOPY/macros/AddTaskFemtoLoton.C, PWGCF/FEMTOSCOPY/macros/AddTaskFemtoXoton.C
=> Update of the detadphi cut

PWG/FLOW/Tasks/AliAnalysisTaskCVE.cxx
bugfix: fill PID histogram at proper place
=> bugfix: fill PID histogram at proper place

PWGJE/EMCALJetTasks/PWGJEEMCALJetTasksLinkDef.h, PWGJE/EMCALJetTasks/UserTasks/AliAnalysisTaskJetDynamicalGrooming.cxx, PWGJE/EMCALJetTasks/UserTasks/AliAnalysisTaskJetDynamicalGrooming.h
The task has been substantially simplified, with the aim of
calculating the rest of the splitting properties later from the store
splittings.
=> Store all splittings for substructure

PWGHF/treeHF/AliAnalysisTaskSEHFTreeCreator.cxx
Using extra PreSelect function for Lb -> Lc pi, also for Lc -> pKpi itself
=> PWGHF: Add ITS3 mass PreSelect also for Lc pKpi

PWGCF/FLOW/GF/AliAnalysisTaskGFWFlow.cxx
Removed redundant correlators, added v_5{2}, moved trigger check before event cuts, should run somewhat faster now
=> Adding v_5{2} to AliGFW task

PWGCF/FEMTOSCOPY/macros/Train/malinina/Feb2020/KK_13TeV_dist/AddTaskFemtoKchHBT1090.C, PWGCF/FEMTOSCOPY/macros/Train/malinina/Feb2020/KK_13TeV_dist/ConfigFemtoAnalysis.C
=> Lego Train macro KchKch pp13tev w/o Sph cut (Ludmila)

PWGMM/UE/CMakeLists.txt, PWGMM/UE/PWGMMueLinkDef.h, PWGMM/UE/UeKNO/AddTaskMcKno.C, PWGMM/UE/UeKNO/AliAnalysisTaskMcKno.cxx, PWGMM/UE/UeKNO/AliAnalysisTaskMcKno.h
New Analysis task for NchTS analysis is added.
=> Task for NchTS analysis

PWGLF/RESONANCES/PostProcessing/f0980/AliAnalysisTaskInclusivef0f2.cxx
Optimize the centrality cut in Pb-Pb
=> [PWGLF] Optimize the centrality cut in Pb-Pb

PWGCF/FEMTOSCOPY/FemtoDream/AliAnalysisTaskPOmegaPenne.cxx, PWGCF/FEMTOSCOPY/FemtoDream/AliAnalysisTaskPOmegaPenne.h, PWGCF/FEMTOSCOPY/macros/AddTaskPOmegaPenne.C
=> corrected xi

PWGCF/FEMTOSCOPY/FemtoDream/AliAnalysisTaskNanoAODSigma0Femto.cxx, PWGCF/FEMTOSCOPY/FemtoDream/AliFemtoDreamBaseDump.cxx, PWGCF/FEMTOSCOPY/FemtoDream/AliFemtoDreamBaseDump.h, PWGCF/FEMTOSCOPY/macros/AddTaskSigma0FemtoNanoAOD.C
Keep track of the analysis file in which there are pairs
=> Improvements for the dumpster

PWG/Tools/AliMCSpectraWeights.cxx, PWG/Tools/AliMCSpectraWeights.h
can be used now for pp and p-Pb
=> AliMCSpectraWeights: bug fixes for 2nd iteration;

PWGCF/Correlations/JCORRAN/Pro/AliAnalysisTaskRidge.cxx, PWGCF/Correlations/JCORRAN/Pro/AliAnalysisTaskRidge.h
Add V0M cut mode instead percentile
=> [PWGCF] Add V0M cut mode

PWGUD/UPC/AliAnalysisTaskADin2018.cxx, PWGUD/UPC/AliAnalysisTaskADin2018.h
Totally forgot to update the analysis task on AliPhysics.
Major update:
- added EMD analysis;
- AD trigger checks;
- improvements on the pt-distributions;
- V0C checks;
- NEW: AD's multiplicity check.
=> PWGUD/UPC: Major update.

PWGDQ/dielectron/macrosLMEE/AddTask_dsekihat_ElectronEfficiencyV2_PbPb.C
update AddTask for MC to avoid unnecessary alien_cp in task itself from every jobs.
=> PWGDQ/LMEE: update AddTask for MC

PWGDQ/dielectron/macrosLMEE/AddTask_dsekihat_ElectronEfficiencyV2_PbPb.C
quick fix to 13300, minor protection not to call alien_cp when file name is empty.
=> PWGDQ/LMEE: quick fix to 13300

PWGCF/Correlations/macros/pol_tree/AddTaskNtuplizer.C
modified along with AliAnalysisTaskNtuplizer
=> modified along with AliAnalysisTaskNtuplizer

PWGHF/vertexingHF/AliAnalysisTaskSEDvsMultiplicity_BDT.cxx, PWGHF/vertexingHF/AliAnalysisTaskSEDvsMultiplicity_BDT.h, PWGHF/vertexingHF/CMakeLists.txt, PWGHF/vertexingHF/PWGHFvertexingHFLinkDef.h, PWGHF/vertexingHF/macros/AddTaskDvsMultiplicity_BDT.C
=> Added DMult ntuplizer macros

PWGGA/GammaConv/macros/AddTask_GammaConvCalo_pp.C
- adding low b-field and exotic cluster variation for triggers
_I'm sorry fore the many small pull requests over the last few days_
=>  PWGGA/GammaConv/   adding low b-field and exotic cluster variation for triggers

PWGDQ/dielectron/macrosJPSI/AddTask_JPsi_EMCal.C
combined trigger for J/psi analysis using EMCal and DCal.
=>  adding combined trigger for EMCal and DCal

PWGLF/RESONANCES/PostProcessing/Sigma1385/AliAnalysisTaskSigma1385PM.cxx
=> Update for Additional MC Bkg study

PWG/FLOW/Tasks/AliAnalysisTaskCMW.cxx, PWG/FLOW/Tasks/AliAnalysisTaskCMW.h, PWG/FLOW/Tasks/CMakeLists.txt, PWG/FLOW/Tasks/PWGflowTasksLinkDef.h, PWGCF/FLOW/macros/AddTaskCMW.C
Added AnalysisTask for CMW with trivial Correction
=> Added AnalysisTask for CMW with trivial Correction

PWGDQ/dielectron/core/AliAnalysisTaskElectronEfficiencyV2.cxx, PWGDQ/dielectron/macrosLMEE/AddTask_dsekihat_ElectronEfficiencyV2_PbPb.C
revert AddTask macro for ML, add protection for cocktail weighting
=> PWGDQ/LMEE:  add protection for cocktail weighting

PWGHF/vertexingHF/AliAnalysisTaskSEXicZero2XiPifromKFP.cxx, PWGHF/vertexingHF/AliAnalysisTaskSEXicZero2XiPifromKFP.h, PWGHF/vertexingHF/AliRDHFCutsKFP.cxx, PWGHF/vertexingHF/AliRDHFCutsKFP.h, PWGHF/vertexingHF/macros/AddTaskXicZero2XiPiFromKFParticle.C
Add class and macro for Xic0->XiPi analysis by KFParticle
=> Add class and macro for Xic0->XiPi analysis by KFParticle

PWGMM/UE/UeKNO/AliAnalysisTaskMcKno.cxx, PWGMM/UE/UeKNO/AliAnalysisTaskMcKno.h
Inclusion of Multiplicity dependent analysis to the NchTS task
=> Inclusion of Multiplicity dependent analysis

PWGLF/RESONANCES/PostProcessing/Sigma1385/AliAnalysisTaskSigma1385PM.cxx
Add some information to MC Tree
=> Update for MC study bins

PWGDQ/dielectron/core/AliAnalysisTaskElectronEfficiencyV2.cxx, PWGDQ/dielectron/macrosLMEE/AddTask_dsekihat_ElectronEfficiencyV2_PbPb.C
=> PWGDQ/LMEE:  add proper protection for opening alien files

PWGHF/vertexingHF/AliAnalysisTaskSEXicPlus2XiPiPifromAODtracks.cxx, PWGHF/vertexingHF/AliAnalysisTaskSEXicPlus2XiPiPifromAODtracks.h, PWGHF/vertexingHF/AliRDHFCutsXicPlustoXiPiPifromAODtracks.cxx, PWGHF/vertexingHF/AliRDHFCutsXicPlustoXiPiPifromAODtracks.h, PWGHF/vertexingHF/macros/AddTaskXicPlus2XiPiPifromAODtracks.C
Hello,
could you please commit these modifications to the task for the XiCPlus analysis?
Many thanks
Grazia
=> Add THnsparse and histos for MC analysis for XicPlus

PWGMM/UE/UeKNO/AliAnalysisTaskMcKno.cxx, PWGMM/UE/UeKNO/AliAnalysisTaskMcKno.h
Fix for intialization issues in NchTS analysis task.
=> Fix for intialization issues

PWGGA/GammaConv/macros/AddTask_GammaCalo_pp.C
I want to add the EG1 and EG2 trigger for Jet QA.
=> Add EG1 and EG2 for JetQA

PWGCF/Correlations/DPhi/AliAnalysisTaskDiHadCorrelHighPt.cxx, PWGCF/Correlations/DPhi/AliAnalysisTaskDiHadCorrelHighPt.h
add option to test on pions for MC truth
=> Change in AliAnalysisTaskDiHadCorrelHighPt

PWGJE/FlavourJetTasks/AliAnalysisTaskHFJetIPQA.cxx, PWGJE/FlavourJetTasks/AliAnalysisTaskHFJetIPQA.h
- enable usage of one single IP theshold value for all track types 
- enable cuts on IP and IP significance
- add histograms for threshold effects from IP>0, IP>IPthresh
=> AliAnalysisTaskHFJetIPQA: add possibility to use fixed thresh cut

PWGDQ/dielectron/core/AliAnalysisTaskEtaReconstruction.cxx, PWGDQ/dielectron/macrosLMEE/Config_feisenhut_EtaReconstruction.C
Small changes to the PreFilter condition.
=> PWGDQ EtaReconstruction: fixed condition in order to use the prefilter

PWGMM/UE/UeKNO/AddTaskMcKno.C, PWGMM/UE/UeKNO/AliAnalysisTaskMcKno.cxx, PWGMM/UE/UeKNO/AliAnalysisTaskMcKno.h
Inclusion of Pb-Pb analysis in the NchTs analysis task
=> Inclusion of Pb-Pb analysis in the NchTs task

PWGCF/Correlations/DPhi/AliAnalysisTaskDiHadCorrelHighPt.cxx
correct names and debugging lines
=> Changes in AliAnalysisTaskDiHadCorrelHighPt.cxx

PWGCF/FEMTOSCOPY/FemtoDream/AliFemtoDreamBaseDump.cxx, PWGCF/FEMTOSCOPY/FemtoDream/AliFemtoDreamBaseDump.h
o nice idea, however needs too much resources
This reverts commit e32541f31681c74badf48de7b80440a20b018e19.
=> Revert "Dump also the path of the file to the DreamDump"

RUN3/AliAnalysisTaskAO2Dconverter.cxx, RUN3/AliAnalysisTaskAO2Dconverter.h
Updated extraction of MC information.
=> Updated extraction of MC information

PWGDQ/dielectron/macrosLMEE/Config_acapon.C, PWGDQ/dielectron/macrosLMEE/Config_acapon_Efficiency.C, PWGDQ/dielectron/macrosLMEE/LMEECutLib_acapon.C
- fITSshared cuts now auto assign nITS cut based on presence of SDD
=> Extend fITSshared cut variation range

PWGJE/EMCALJetTasks/UserTasks/AliAnalysisTaskJetDynamicalGrooming.cxx
Also added note about harmless calls for setting the rho name in
the case of pythia. I left it because I'm not entirely sure that it
never plays a role in PbPb.
=> Add pt hard information for pp

PWGDQ/dielectron/CMakeLists.txt, PWGDQ/dielectron/PWGDQdielectronLinkDef.h, PWGDQ/dielectron/core/AliAnalysisTaskTagAndProbe.cxx, PWGDQ/dielectron/core/AliAnalysisTaskTagAndProbe.h, PWGDQ/dielectron/macrosLMEE/AddTask_dsekihat_TAP_PbPb.C, PWGDQ/dielectron/macrosLMEE/Config_dsekihat_TAP_PbPb.C, PWGDQ/dielectron/macrosLMEE/LMEECutLib_dsekihat.C
add a task for data-driven efficiency with tag-and-probe method
=> PWGDQ/LMEE: add a task for data-driven efficiency with tag-and-probe method

PWG/FLOW/Tasks/AliAnalysisTaskCMW.cxx
code modified to remove nan in histogram filling
=> removing nan

PWGCF/Correlations/Base/AliAnalysisTaskNtuplizer.cxx
adding  V0 daughter branches with loose cuts for systematic uncertainty estimation
=>  V0 daughter branches with loose cuts (systematic)

PWGLF/RESONANCES/PostProcessing/f0980/AliAnalysisTaskInclusivef0f2.cxx, PWGLF/RESONANCES/PostProcessing/f0980/AliAnalysisTaskInclusivef0f2.h
Modification for centrality-weighting in MC
=> [PWGLF] Modification for MC study

PWGHF/treeHF/AliAnalysisTaskSEHFTreeCreator.cxx, PWGHF/vertexingHF/AliRDHFCutsLctopKpi.cxx
PreSelectMass modified for LctopKpi
=> PreSelectLctopKpi modified

PWGDQ/reducedTree/AliCorrelationExtraction.cxx, PWGDQ/reducedTree/AliCorrelationExtraction.h
for correlation signal extraction
=> PWGDQ/reducedTree/AliCorrelationExtraction: improved fitting method

PWGGA/GammaConv/macros/AddTask_GammaConvCalo_pp.C
Changing low B Rconv cuts to use EDC
=>  PWGGA/GammaConv  PCM-EDC

PWGGA/GammaConv/AliAnalysisTaskOmegaToPiZeroGamma.cxx, PWGGA/GammaConv/AliAnalysisTaskOmegaToPiZeroGamma.h, PWGGA/GammaConv/macros/AddTask_GammaCalo_pp.C, PWGGA/GammaConv/macros/AddTask_GammaConvNeutralMesonPiPlPiMiNeutralMeson_CaloMode_pp.C, PWGGA/GammaConv/macros/AddTask_OmegaToPiZeroGamma_pp.C, PWGGA/GammaConvBase/AliConversionMesonCuts.cxx, PWGGA/GammaConvBase/AliConversionMesonCuts.h
+Added more AOD support regarding MC histograms
+changed pT binning (to get to 100 GeV/c) and minv binning (less bins)
+Added photon selection as extension for the selection window cut
+Added train configs for photon selection
=> Update of OmegaToPi0Gamma Task

PWG/CaloTrackCorrBase/AliMCAnalysisUtils.cxx
but 2 photons opening angle is smaller than an EMCal cell
=> Tag MC cluster as merged meson decay if only one photon found 

PWGHF/treeHF/AliAnalysisTaskSEHFTreeCreator.cxx, PWGHF/treeHF/AliAnalysisTaskSEHFTreeCreator.h
=> Fix event id in HF tree creator

PWGDQ/reducedTree/AliCorrelationExtraction.cxx, PWGDQ/reducedTree/AliCorrelationExtraction.h
=> PWGDQ/reducedTree/AliCorrelationExtraction: fixed fitting method 

PWG/FLOW/Tasks/AliAnalysisTaskCVE.cxx
Update NUA histograms for Charge Hadrons
=> Update NUA for Charge Hadrons

PWGLF/NUCLEX/Exotica/LambdaN/AliAnalysisTaskLambdaNRun2.cxx
=> Bug correction

PWGDQ/dielectron/core/AliAnalysisTaskEtaReconstruction.cxx, PWGDQ/dielectron/macrosLMEE/Config_feisenhut_EtaReconstruction.C, PWGDQ/dielectron/macrosLMEE/LMEECutLib_feisenhut.C
Added an additional support histogram.
=> PWGDQ EtaReconstruction Added new support histogram

PWGHF/jetsHF/AliAnalysisTaskIPCalib.cxx
I changed the range of the IPs, so we can cover a large region for the fits.
=> Changing the range of the IPs histogram

PWGHF/hfe/AliAnalysisTaskHFEBESpectraEMC.cxx, PWGHF/hfe/AliAnalysisTaskHFEBESpectraEMC.h, PWGHF/hfe/macros/AddTaskHFEBESpectraEMC.C
Adding containers to run over EG1 and EG2 triggered events
=> Adding option to include EG1 and EG2

PWGHF/vertexingHF/AliAnalysisTaskSEDvsMultiplicity_BDT.cxx, PWGHF/vertexingHF/AliAnalysisTaskSEDvsMultiplicity_BDT.h, PWGHF/vertexingHF/macros/AddTaskDvsMultiplicity_BDT.C
=> Modified DvsMult BDT tasks

PWG/DevNanoAOD/AliNanoAODINELgt0setter.h
Add simple return function to the SetNanoAODTrack function.
=> Fix unimplemented method issue.

PWGHF/treeHF/AliAnalysisTaskSEHFTreeCreator.cxx, PWGHF/treeHF/AliAnalysisTaskSEHFTreeCreator.h, PWGHF/treeHF/AliHFTreeHandler.cxx, PWGHF/treeHF/AliHFTreeHandler.h, PWGHF/treeHF/AliHFTreeHandlerBplustoD0pi.cxx, PWGHF/treeHF/AliHFTreeHandlerBplustoD0pi.h, PWGHF/treeHF/AliHFTreeHandlerBstoDspi.cxx, PWGHF/treeHF/AliHFTreeHandlerBstoDspi.h, PWGHF/treeHF/AliHFTreeHandlerD0toKpi.cxx, PWGHF/treeHF/AliHFTreeHandlerD0toKpi.h, PWGHF/treeHF/AliHFTreeHandlerDplustoKpipi.cxx, PWGHF/treeHF/AliHFTreeHandlerDplustoKpipi.h, PWGHF/treeHF/AliHFTreeHandlerDstartoKpipi.cxx, PWGHF/treeHF/AliHFTreeHandlerDstartoKpipi.h, PWGHF/treeHF/AliHFTreeHandlerDstoKKpi.cxx, PWGHF/treeHF/AliHFTreeHandlerDstoKKpi.h, PWGHF/treeHF/AliHFTreeHandlerLbtoLcpi.cxx, PWGHF/treeHF/AliHFTreeHandlerLbtoLcpi.h, PWGHF/treeHF/AliHFTreeHandlerLc2V0bachelor.cxx, PWGHF/treeHF/AliHFTreeHandlerLc2V0bachelor.h, PWGHF/treeHF/AliHFTreeHandlerLctopKpi.cxx, PWGHF/treeHF/AliHFTreeHandlerLctopKpi.h, PWGHF/treeHF/AliJetTreeHandler.cxx, PWGHF/treeHF/AliJetTreeHandler.h, PWGHF/treeHF/AliParticleTreeHandler.cxx, PWGHF/treeHF/AliParticleTreeHandler.h, PWGHF/treeHF/AliTrackletTreeHandler.cxx, PWGHF/treeHF/AliTrackletTreeHandler.h
=> Fix strategy to identify univocally an event in a run for both MC and Data

PWGCF/Correlations/DPhi/AliAnalysisTaskV0ChCorrelation.cxx, PWGCF/Correlations/macros/AddTaskV0ChCorrelation.C, PWGCF/Correlations/macros/AddTaskV0ChCorrelationPrei.C, PWGCF/Correlations/macros/AddTaskV0ChCorrelationpp.C
=> more sys v0-h

PWGLF/RESONANCES/PostProcessing/Sigma1385/AliAnalysisTaskSigma1385PM.cxx, PWGLF/RESONANCES/PostProcessing/Xi1530/NanoCheck/AliAnalysisTaskNanoCheck.cxx
So that it can be used INEL,INELgt0 together
=> Update Multiplicity axis

PWGGA/GammaConv/AliAnalysisTaskSigmaPlToProtonPiZero.cxx, PWGGA/GammaConv/AliAnalysisTaskSigmaPlToProtonPiZero.h
fixing computer issue
https://github.com/alisw/AliPhysics/pull/13488
=> fixing computer issue

PWGLF/RESONANCES/PostProcessing/Sigma1385/AliAnalysisTaskSigma1385PM.cxx, PWGLF/RESONANCES/PostProcessing/Sigma1385/AliAnalysisTaskSigma1385PM.h, PWGLF/RESONANCES/PostProcessing/Xi1530/AliAnalysisTaskXi1530.cxx
=> Add option to use OnTheFlyV0

PWG/FLOW/Tasks/AliAnalysisTaskCVE.cxx
Pt range for Ach set to 0.2 to 10 GeV
=> Pt range for Ach set to 0.2 to 10 GeV

PWGDQ/dielectron/core/AliDielectronVarManager.cxx, PWGDQ/dielectron/core/AliDielectronVarManager.h
add variables for Ncls of SDD+SSD related to pileup
=> PWGDQ/LMEE: add variables for Ncls of SDD+SSD

PWGGA/CaloTrackCorrelations/AliAnaParticleIsolation.cxx, PWGGA/CaloTrackCorrelations/AliAnaPhoton.cxx
calculate primary isolation also for UE subtraction methods, start primary loop after partons
=> Reject primary particles with pT larger than pT hard, 

PWGDQ/dielectron/macrosLMEE/AddTask_dsekihat_lowmass_PbPb.C
=> update AddTask for MC

PWGJE/EMCALJetTasks/UserTasks/AliAnalysisTaskJetCoreEmcal.cxx, PWGJE/EMCALJetTasks/UserTasks/AliAnalysisTaskJetCoreEmcal.h
- add histograms to to study TT bias in rho
- add fine-binned pt vs dphi histogram to allow for 'shift' in rho if needed.
=> add rho histograms vs TT and fine-binned pt vs dphi histogram

PWGDQ/dielectron/core/AliAnalysisTaskTagAndProbe.cxx, PWGDQ/dielectron/macrosLMEE/Config_dsekihat_TAP_PbPb.C, PWGDQ/dielectron/macrosLMEE/Config_dsekihat_lowmass_PbPb.C, PWGDQ/dielectron/macrosLMEE/LMEECutLib_dsekihat.C
=> update Config for pileup

PWGCF/FEMTOSCOPY/FemtoDream/AliFemtoDreamTrackMCHist.cxx, PWGCF/FEMTOSCOPY/FemtoDream/AliFemtoDreamTrackMCHist.h, PWGCF/FEMTOSCOPY/macros/AddTaskFemtoDreamPion.C
-Change from Form to more robust TString::Format
-Adapt AddTask in order to accommodate cut variations
=> -Inlcude also Sigma+/- as feeddown candidates

PWGHF/vertexingHF/AliAnalysisTaskSEXicTopKpi.cxx, PWGHF/vertexingHF/AliAnalysisTaskSEXicTopKpi.h
Conservative and "dirty" solution to make the sparse merging easier
=> Flag to reduce PID binning in reco sparses introduced

RUN3/AliAnalysisTaskAO2Dconverter.cxx, RUN3/AliAnalysisTaskAO2Dconverter.h
Related pull request in O2:
https://github.com/AliceO2Group/AliceO2/pull/3089
=> Adding detailed information about TPC clusters

PWGGA/GammaConv/AliAnalysisTaskSigmaPlToProtonPiZero.cxx, PWGGA/GammaConv/AliAnalysisTaskSigmaPlToProtonPiZero.h
Changes to SigmaPlToProtonPiZero task
=>  PWGGA/GammaConv/AliAnalysisTaskSigmaPlToProtonPiZero

PWGCF/Correlations/DPhi/AliAnalysisTaskV0ChCorrelation.cxx, PWGCF/Correlations/macros/AddTaskV0ChCorrelation.C, PWGCF/Correlations/macros/AddTaskV0ChCorrelationPrei.C, PWGCF/Correlations/macros/AddTaskV0ChCorrelationpp.C
=> V0-h New task

PWGDQ/dielectron/core/AliAnalysisTaskEtaReconstruction.cxx, PWGDQ/dielectron/core/AliAnalysisTaskEtaReconstruction.h, PWGDQ/dielectron/macrosLMEE/AddTask_feisenhut_EtaReconstruction.C, PWGDQ/dielectron/macrosLMEE/Config_feisenhut_EtaReconstruction.C, PWGDQ/dielectron/macrosLMEE/LMEECutLib_feisenhut.C
I made some changes to the output of support histogram lists
and added a new primary pair cut to obeserve and cut on primary pairs observables.
=> PWGDQ EtaReconstruction New structure of support histogram and implemented primary pair cuts

PWG/EMCAL/EMCALtasks/AliAnalysisTaskEmcalTriggerSelection.cxx
From analysis output i found that the values were set slightly too high. I've reduced them by a few hundred MeV.
=> PWG/EMCAL: optimized trigger maker values for pPb8TeV

PWGHF/vertexingHF/AliAnalysisTaskSEXicZero2XiPifromKFP.cxx, PWGHF/vertexingHF/AliAnalysisTaskSEXicZero2XiPifromKFP.h, PWGHF/vertexingHF/AliRDHFCutsKFP.cxx, PWGHF/vertexingHF/CMakeLists.txt, PWGHF/vertexingHF/PWGHFvertexingHFLinkDef.h
Add classes AliRDHFCutsKFP.cxx and AliAnalysisTaskSEXicZero2XiPifromKFP.cxx into vertexingHF/CMakeLists.txt and vertexingHF/PWGHFvertexingHFLinkDef.h
=> Add classes which used KFParticle

PWG/FLOW/Tasks/AliAnalysisTaskCVE.cxx
Change Ach binning for Equal Event per bin
=> Change Ach binning for Equal Event per bin

PWGHF/hfe/AliAnalysisTaskHFEBESpectraEMC.cxx
Apply non-linearity correction from YAML + fix typos
=> Apply non-linearity correction from YAML + fix typo

PWGMM/UE/UeKNO/AddTaskMcKnoUe.C, PWGMM/UE/UeKNO/AliAnalysisTaskMcKnoUe.cxx, PWGMM/UE/UeKNO/AliAnalysisTaskMcKnoUe.h
The parametrization of the efficiency derived from EPOS LHC was added.
=> efficiency from epos lhc (UE analysis)

PWGCF/FEMTOSCOPY/macros/Train/malinina/Mar2020/KK_13TeV_dist/AddTaskFemtoKchHBT1090.C, PWGCF/FEMTOSCOPY/macros/Train/malinina/Mar2020/KK_13TeV_dist/ConfigFemtoAnalysis.C, PWGCF/FEMTOSCOPY/macros/Train/malinina/Mar2020/KK_13TeV_jets/AddTaskFemtoKchHBT1090.C, PWGCF/FEMTOSCOPY/macros/Train/malinina/Mar2020/KK_13TeV_jets/ConfigFemtoAnalysis.C, PWGCF/FEMTOSCOPY/macros/Train/malinina/Mar2020/pipi_13TeV_dist/AddTaskFemtoKchHBT1090.C, PWGCF/FEMTOSCOPY/macros/Train/malinina/Mar2020/pipi_13TeV_dist/ConfigFemtoAnalysis.C, PWGCF/FEMTOSCOPY/macros/Train/malinina/Mar2020/pipi_13TeV_jets/AddTaskFemtoKchHBT1090.C, PWGCF/FEMTOSCOPY/macros/Train/malinina/Mar2020/pipi_13TeV_jets/ConfigFemtoAnalysis.C
=> LegoTrain: Ludmila->SystErrWagons

PWG/DevNanoAOD/AliNanoAODINELgt0setter.h
Using AliNanoAODSimpleSetter, Inclue "cst" variable to the NanoAODHeader
=> Initialize the nano header properly

PWGDQ/dielectron/macrosLMEE/AddTask_acapon_Efficiency.C, PWGDQ/dielectron/macrosLMEE/Config_acapon.C, PWGDQ/dielectron/macrosLMEE/Config_acapon_Efficiency.C, PWGDQ/dielectron/macrosLMEE/LMEECutLib_acapon.C
=> Add 7TeV pp paper cut setting

PWGCF/FEMTOSCOPY/macros/Train/Romanenko/Mar2020_MC/KK_MC_3d_444/ConfigFemtoAnalysis.C, PWGCF/FEMTOSCOPY/macros/Train/Romanenko/Mar2020_MC/KK_MC_3d_656/ConfigFemtoAnalysis.C, PWGCF/FEMTOSCOPY/macros/Train/Romanenko/Mar2020_MC/KK_MC_3d_757/ConfigFemtoAnalysis.C, PWGCF/FEMTOSCOPY/macros/Train/Romanenko/Mar2020_MC/add/AddTaskFemto.C
=> LegoTrain For Gleb Romanenko

PWGMM/UE/UeKNO/AddTaskMcKno.C, PWGMM/UE/UeKNO/AliAnalysisTaskMcKno.cxx, PWGMM/UE/UeKNO/AliAnalysisTaskMcKno.h
Inclusion of Efficiency calculation in NchTS analysis. Flags for V0M cuts and pT leading cuts are also included.
=> Inclusion of Efficiency calculation in NchTS analysis

PWGCF/FEMTOSCOPY/AliFemtoUser/AliFemtoModelCorrFctn3DKKGR.cxx, PWGCF/FEMTOSCOPY/AliFemtoUser/AliFemtoModelCorrFctn3DKKGR.h, PWGCF/FEMTOSCOPY/AliFemtoUser/CMakeLists.txt, PWGCF/FEMTOSCOPY/AliFemtoUser/PWGCFfemtoscopyUserLinkDef.h
=> New class: AliFemtoModelCorrFctn3DKKGR - 3d momres (Gleb)

PWGHF/vertexingHF/AliRDHFCutsKFP.cxx, PWGHF/vertexingHF/AliRDHFCutsKFP.h
Add some members for cuts in "AliRDHFCutsKFP"
=> Add some members for cuts

PWGHF/jetsHF/AliAnalysisTaskEmcalJetBtagSV.cxx, PWGHF/jetsHF/AliAnalysisTaskEmcalJetBtagSV.h, PWGJE/EMCALJetTasks/UserTasks/AliAnalysisTaskEA.cxx, PWGJE/EMCALJetTasks/UserTasks/AliAnalysisTaskEA.h
hjet code: histograms of momentum asymmetry and hard jet counters
=> SV task: embedding of track perpendicular to SV candidate jet

PWGDQ/dielectron/core/AliAnalysisTask_JPsi_EMCal.cxx, PWGDQ/dielectron/core/AliAnalysisTask_JPsi_EMCal.h, PWGDQ/dielectron/macrosJPSI/AddTask_JPsi_EMCal.C, PWGDQ/dielectron/macrosJPSI/Config_JPsi_EMCal.C
changing the efficiency correction, applying weight normalized.
Flags added for emcal trigger studies.
=>  changing the efficiency correction, applying weight normalized. 

PWGHF/vertexingHF/AliAODRecoCascadeHF3Prong.h, PWGHF/vertexingHF/AliAnalysisTaskSEXicPlus2XiPiPifromAODtracks.cxx, PWGHF/vertexingHF/AliAnalysisTaskSEXicPlus2XiPiPifromAODtracks.h, PWGHF/vertexingHF/AliRDHFCutsXicPlustoXiPiPifromAODtracks.cxx, PWGHF/vertexingHF/AliRDHFCutsXicPlustoXiPiPifromAODtracks.h, PWGHF/vertexingHF/AliRDHFCutsXicZerotoXiPifromAODtracks.cxx, PWGHF/vertexingHF/AliRDHFCutsXicZerotoXiPifromAODtracks.h
Hello,
can these commits be merged in the master?
Many thanks!
Grazia
=> Update of XicPlus analysis

PWGPP/TPC/AliTPCcalibResidualPID_Modified.cxx, PWGPP/TPC/AliTPCcalibResidualPID_Modified.h, PWGPP/TPC/macros/AddTaskTPCcalibResidualPID_Modified.C
Modified version of the AliTPCcalbiResidualPID task, which generate the output for the TPCspline creation framework. A reduced Tree was introduced to the output with the necessary variables to speed up the spline creation.
=> Modified version of the AliTPCcalibResidualPID task.

PWGLF/STRANGENESS/CMakeLists.txt, PWGLF/STRANGENESS/Correlationpp/AddTaskCorrelationhhK0s.C, PWGLF/STRANGENESS/Correlationpp/AliAnalysisCorrelationEventCollection.cxx, PWGLF/STRANGENESS/Correlationpp/AliAnalysisCorrelationEventCollection.h, PWGLF/STRANGENESS/Correlationpp/AliAnalysisTaskCorrelationhhK0s.cxx, PWGLF/STRANGENESS/Correlationpp/AliAnalysisTaskCorrelationhhK0s.h, PWGLF/STRANGENESS/PWGLFSTRANGENESSLinkDef.h
=> First commit of K0h correlation in pp

PWGCF/FLOW/macros/AddTaskFlowQCFineCentBinning.C
Add AddTaskFlowQCFineCentBinning.C for calculating QC with fine centrality binning. Also, some selection cuts are added.
=> Add AddTaskFlowQCFineCentBinning.C

PWG/CaloTrackCorrBase/AliIsolationCut.cxx, PWG/CaloTrackCorrBase/AliIsolationCut.h
=> [PWGGA/CaloTrackCorr] additional centrality dependent histograms, variable binning for TH3 

PWGMM/UE/UeKNO/AliAnalysisTaskMcKno.cxx, PWGMM/UE/UeKNO/AliAnalysisTaskMcKno.h
Inclusion of DCA distributions and efficiency calcuation with particle composition in NshTS analysis
=> Inclusion of DCA distributions in NshTS analysis

PWGLF/STRANGENESS/Correlationpp/AliAnalysisTaskCorrelationhhK0s.cxx, PWGLF/STRANGENESS/Correlationpp/AliAnalysisTaskCorrelationhhK0s.h
=> update on out-of-bunch pileup

PWGHF/vertexingHF/macros/AddTaskXicZero2XiPiFromKFParticle.C
Add option for different type of cut object
=> Add option for different type of cut object

PWG/DevNanoAOD/tutorial/filterESD_Resonances.C
- Update vertexer configuration
- Add INELgt0 parameter
- Add default V0 cut for Nano filter
=> update for the lastes optimization

PWGGA/GammaConv/AliAnalysisTaskOmegaToPiZeroGamma.cxx, PWGGA/GammaConv/macros/AddTask_OmegaToPiZeroGamma_pp.C
+Added alpha cut variation train configs for pi0n and omega meson
-Removed some news & delete which were not necessary
=> Added alpha cut variation train configs

PWGHF/vertexingHF/macros/AnalyzeScOutput.C
- possibility to study different fit possibilities in data and MC
- comparison plots with other hadrons (eg: Lc, D0) and PYTHIA updated
- ingredients to study the yield, efficiency and cross section variation with cuts added
=> Macro for Lc(<-Sc) and Sc analysis updated

PWGCF/FEMTOSCOPY/macros/Train/malinina/Mar2020plp/KK_13TeV_dist/AddTaskFemtoKchHBT1090.C, PWGCF/FEMTOSCOPY/macros/Train/malinina/Mar2020plp/KK_13TeV_dist/ConfigFemtoAnalysis.C, PWGCF/FEMTOSCOPY/macros/Train/malinina/Mar2020plp/KK_13TeV_jets/AddTaskFemtoKchHBT1090.C, PWGCF/FEMTOSCOPY/macros/Train/malinina/Mar2020plp/KK_13TeV_jets/ConfigFemtoAnalysis.C, PWGCF/FEMTOSCOPY/macros/Train/malinina/Mar2020plp/pipi_13TeV_dist/AddTaskFemtoKchHBT1090.C, PWGCF/FEMTOSCOPY/macros/Train/malinina/Mar2020plp/pipi_13TeV_dist/ConfigFemtoAnalysis.C, PWGCF/FEMTOSCOPY/macros/Train/malinina/Mar2020plp/pipi_13TeV_jets/AddTaskFemtoKchHBT1090.C, PWGCF/FEMTOSCOPY/macros/Train/malinina/Mar2020plp/pipi_13TeV_jets/ConfigFemtoAnalysis.C
=> LegoTrain: pile-up cut for Ludmila

PWGCF/Correlations/DPhi/AliAnalysisTaskGeneralBF.cxx, PWGCF/Correlations/DPhi/AliAnalysisTaskGeneralBF.h
Also
- conditional execution of the momentum ordered pair track swaps
- discarding MC reco tracks with negative label
- fixes for anomalous int arithmetic
- lambda veto for MC generator level
=> Incorporated the rejection of injected signals on MC datasets

PWGCF/FEMTOSCOPY/macros/Train/KM/testgithub.txt
=> -- My test for github 20 mar 2020

PWGHF/correlationHF/AliAnalysisTaskDHFeCorr.cxx, PWGHF/correlationHF/AliAnalysisTaskDHFeCorr.h
Dear all,
I have performed some changes in the code to fix a problem in the tagging of HF particles in MC. I also included some other improvements in the code readability.
Best
Henrique
=> Fix MC origin flag

PWGHF/jetsHF/AliATDJetCorrDev.cxx, PWGHF/jetsHF/AliATDJetCorrDev.h, PWGHF/jetsHF/AliAnalysisTaskDJetCorrelations.cxx, PWGHF/jetsHF/AliAnalysisTaskDmesonsFilterCJ.cxx, PWGHF/jetsHF/AliAnalysisTaskDmesonsFilterCJ.h, PWGHF/jetsHF/CMakeLists.txt, PWGHF/jetsHF/PWGHFjetsHFLinkDef.h, PWGHF/jetsHF/macros/AddTaskDJetCorrDev.C
Substructure functionalities added for D-jets
=> DJetCorrelations developer copy created: task.cxx, task.h, macros/addtask.c.

PWGPP/TOF/trending/MakeTrendingTOFQAv2.C
=> Fix to the Event Time trending histograms in TOF QA

PWGCF/Correlations/DPhi/AliAnalysisTaskLongFluctuations2PC.cxx, PWGCF/Correlations/DPhi/AliAnalysisTaskLongFluctuations2PC.h, PWGCF/Correlations/DPhi/CMakeLists.txt, PWGCF/Correlations/DPhi/PWGCFCorrelationsDPhiLinkDef.h
We are adding Raquel's code on longitudinal correlation measurements to AliPhysics for the first time
=> Adding Raquel's code to AliPhysics

PWGMM/Lumi/vdM/VdmStability/AliAnalysisTaskVdmStability.cxx
Fixed bug in selection of INT7 events.
=> updated bug in int7-selection

PWGGA/GammaConv/macros/AddTask_GammaConvDalitzV1_pp.C
=> Study of low Magnetic field

PWGGA/GammaConv/AliAnalysisTaskOmegaToPiZeroGamma.cxx, PWGGA/GammaConv/AliAnalysisTaskOmegaToPiZeroGamma.h, PWGGA/GammaConv/macros/AddTask_OmegaToPiZeroGamma_pp.C
Added PHOS train configs
Fixed bug with not filling EtaPhi histogram for swapping background
Moved the include for std::set into the header
=> OmegaToPiZeroGamma added PHOS configs

PWGHF/correlationHF/AliAnalysisTaskSED0Correlations.cxx
=> Fix to D0-h correl class (wrong name of histogram in list)

PWGCF/Correlations/macros/AddTaskLongFluctuations2PC.C, PWGCF/Correlations/macros/AliAnalysisTaskLongFluctuations2PC.C
Adding task macro for Longitudinal 2 particle correlations
=> Adding task macro for Longitudinal 2 particle correlations 

PWGGA/GammaConv/AliAnalysisTaskGammaCalo.cxx, PWGGA/GammaConv/macros/AddTask_GammaCalo_pp.C, PWGGA/GammaConvBase/AliConvEventCuts.cxx
Additionally, a check if the JJ weight is nan was implemented.
=> PWGGA/GammaConv: Adjustments for pp 13TeV pT binning and light output

PWGCF/FEMTOSCOPY/macros/Train/malinina/Apr2020/KK_13TeV_dist/AddTaskFemtoKchHBT1090.C, PWGCF/FEMTOSCOPY/macros/Train/malinina/Apr2020/KK_13TeV_dist/ConfigFemtoAnalysis.C, PWGCF/FEMTOSCOPY/macros/Train/malinina/Apr2020/KK_13TeV_jets/AddTaskFemtoKchHBT1090.C, PWGCF/FEMTOSCOPY/macros/Train/malinina/Apr2020/KK_13TeV_jets/ConfigFemtoAnalysis.C, PWGCF/FEMTOSCOPY/macros/Train/malinina/Apr2020/pipi_13TeV_dist/AddTaskFemtoKchHBT1090.C, PWGCF/FEMTOSCOPY/macros/Train/malinina/Apr2020/pipi_13TeV_dist/ConfigFemtoAnalysis.C, PWGCF/FEMTOSCOPY/macros/Train/malinina/Apr2020/pipi_13TeV_jets/AddTaskFemtoKchHBT1090.C, PWGCF/FEMTOSCOPY/macros/Train/malinina/Apr2020/pipi_13TeV_jets/ConfigFemtoAnalysis.C
=> LegoTrain for Ludmila Apr2020

PWGDQ/dielectron/core/AliDielectronVarManager.cxx, PWGDQ/dielectron/core/AliDielectronVarManager.h, PWGDQ/dielectron/macrosLMEE/AddTask_hdegenhardt_minbiaspp.C, PWGDQ/dielectron/macrosLMEE/Config_hdegenhardt_pp.C
Including new variable related to DCA resolution in XY plane and Z and updating my own AddTask and Config files to run with these new variables
=> Including new variable related to DCA resolution and updating AddTask and Config files

PWGHF/correlationHF/AliAnalysisTaskDHFeCorr.cxx, PWGHF/correlationHF/AliAnalysisTaskDHFeCorr.h
Restore MC information for all HFE and selected tracks. Adds dir number to the events an improves a few parts of the code.
=> Fix for electron MC 

PWGCF/FEMTOSCOPY/AliFemtoUser/AliFemtoMJTrackCut.cxx, PWGCF/FEMTOSCOPY/AliFemtoUser/AliFemtoMJTrackCut.h, PWGCF/FEMTOSCOPY/macros/Train/PbPbProtonDeuteron/ConfigFemtoAnalysis.C
Added possibility to select deuterons with AliFemtoMJTrackCut using TPC Nsigma information
=> Deuteron selection in AliFemtoMJTrackCut

PWGHF/vertexingHF/AliAnalysisTaskSEXicZero2XiPifromKFP.cxx
Move fCounter (AliNormalisationCounter object) after primary vertex checking
=> Move fCounter after primary vertex checking

PWGHF/hfe/AliAnalysisTaskHFEBESpectraEMC.cxx, PWGHF/hfe/AliAnalysisTaskHFEBESpectraEMC.h, PWGHF/hfe/macros/AddTaskHFEBESpectraEMC.C
Adding option to change ITSNCls
=> Adding option to change ITSNCls

PWGHF/hfe/macros/AddTaskHFEBESpectraEMC.C
Changes to settings to run over EMCal trigger data
=> Modifying options for EMCal trigger

PWG/MCLEGO/CRMC/gen_eposlhc_lf_pp_2760GeV.sh
Added new file for the setting of c.m. energy to 2760 GeV
=> setting of c.m. energy to 2760 GeV

PWGGA/GammaConv/AliAnalysisTaskOmegaToPiZeroGamma.cxx, PWGGA/GammaConv/AliAnalysisTaskOmegaToPiZeroGamma.h
Also changed PhotonSelection functions to call by reference
=> Removed some news and deletes in CalculateOmegaCandidates

PWGMM/UE/AliAnalysisTaskMcKnoUe.cxx, PWGMM/UE/AliAnalysisTaskMcKnoUe.h
An issue with DCA distribution was fixed
=> fixing an issue with DCA distributions

PWGGA/GammaConv/macros/AddTask_GammaCalo_pp.C, PWGGA/GammaConv/macros/AddTask_GammaConvCalo_pp.C
=> Add Trigger Systematics

PWGMM/UE/UeKNO/AliAnalysisTaskMcKnoUe.cxx
fixing an issue of the DCA distributions
=> fixing an issue of the DCA distributions

PWGPP/AliAnalysisTaskFilteredTree.cxx
MC Pile-up information flag propagated to the V0 and track trees
=> PWGPP-584,ATO-465: adding pileup information to the V0 and track trees

PWGHF/jetsHF/AliATDJetCorrDev.cxx, PWGHF/jetsHF/AliATDJetCorrDev.h
Reverts alisw/AliPhysics#13976  - (1/3)
Current D-jets code is broken. And the issue cannot be located. So going back to the point of stable code. This is the first reversal of the three PRs created that supposedly broke the code.
=> Revert "theta, E added to THnSparse"

PWGPP/AliAnalysisTaskFilteredTree.cxx
* pile up MC true information added to tree
* adding GID to the efficiency trees to enable correlation with event properties
* using tsalis for the pt and mass  down-sampling - selectionPtMaskMC
* as used also in track trees
* default MC efficiency tree for all primaries
* added secondaries with minimal MC track lengt in TPC
=> PWGPP-584 ,ATO-465: MCEff tree - MC pileup+  Tsalis downsampling

PWGCF/Correlations/DPhi/AliAnalysisTaskV0ChCorrelation.cxx, PWGCF/Correlations/DPhi/AliAnalysisTaskV0ChCorrelationpp.cxx, PWGCF/Correlations/macros/AddTaskV0ChCorrelation.C, PWGCF/Correlations/macros/AddTaskV0ChCorrelationPrei.C, PWGCF/Correlations/macros/AddTaskV0ChCorrelationpp.C
=> V0-h pile up 

PWGPP/macros/pcalimonitorCSV.sh
```
source $AliPhysics_SRC/PWGPP/macros/pcalimonitorCSV.sh
dumpCSV   https://alimonitor.cern.ch/prod/jobs.jsp?t=20831 table.csv
printSummary JobID,RunNo,input_events,wall_time,outputsize,outputsize/input_events table
```
| line_numbers |         JobID |   RunNo | input_events |  wall_time |      outputsize | outputsize/input_events |
| ------------ | ------------- | ------- | ------------ | ---------- | --------------- | ----------------------- |
|            1 | 1.839.999.841 | 296.785 |    2.986.318 |   449,167… |  43.115.045.283 |             14.437,527… |
|            2 | 1.839.998.147 | 296.784 |    5.023.658 |   745,350… |  72.449.724.971 |             14.421,707… |
|            3 | 1.839.997.166 | 296.781 |    1.321.687 |   231,066… |  19.375.511.457 |             14.659,682… |
| …
=> PWGPP-584,ATO-465  small tool to query pcalimontor tables as JIRA table

PWGHF/vertexingHF/AliHFSystErr.cxx, PWGHF/vertexingHF/AliHFSystErr.h
@fcatalan92 
Systematic uncertainties for MC pT shape and non-prompt fraction still to be included
=> Add flag for data-driven analyses and add entries for non-prompt Ds, D+

PWGCF/FLOW/GF/AliAnalysisTaskGFWFlow.cxx, PWGCF/FLOW/GF/AliGFW.cxx
Adding correct treatment of overlapping region when working with PID
=> Working on AliGFW

PWG/FLOW/Tasks/AliAnalysisTaskTwoMultiCorrelations.cxx, PWG/FLOW/Tasks/AliAnalysisTaskTwoMultiCorrelations.h
* Additional cleaning of the code to have a "minimum output" mode.
=> [PWG-CF] Add setters to access the files with the particle weights

PWGMM/UE/UeKNO/AddTaskMcKno.C, PWGMM/UE/UeKNO/AliAnalysisTaskMcKno.cxx, PWGMM/UE/UeKNO/AliAnalysisTaskMcKno.h
Modified track cuts for NchTS calculation
=> Modification for systematic uncertainties calculation in NchTS analysis

PWGHF/hfe/macros/AddTaskHFEBESpectraEMC.C
Adding Central and SemiCentral trigger option for 2018 Pb-Pb data
=> Adding Cent and SemiCent trigger option

PWGHF/treeHF/AliAnalysisTaskSEHFTreeCreator.cxx, PWGHF/treeHF/AliAnalysisTaskSEHFTreeCreator.h
* EMCAL bits, classes and online
* DCAL bits, classes and online
=> Add CALO triggers

PWGHF/hfe/macros/AddTaskHFEBESpectraEMC.C
=> Moving some macro parameters

PWGDQ/dielectron/macrosLMEE/Config_hdegenhardt_pp.C
Alien path included for the new electron recalibration maps
=> Updating AddTask & Config files with new electron recalibration

PWGCF/FEMTOSCOPY/FemtoDream/AliAnalysisTaskGeorgiosNTuple.cxx, PWGCF/FEMTOSCOPY/FemtoDream/AliAnalysisTaskGeorgiosNTuple.h, PWGCF/FEMTOSCOPY/macros/AddTaskGeorgiosNTuple.C
Including CPA and Transverse Radius for the Lambdas; sharpening the cuts to reduce background
=> CPA and Vr for the Lambdas; no background

PWGDQ/dielectron/macrosLMEE/AddTask_dsekihat_lowmass_PbPb.C
=> PWGDQ/LMEE: update of AddTask

PWGCF/FEMTOSCOPY/macros/AddTaskFemtoNanoLD.C
o Change default cuts including strict DCA
o 1: with FB 256 instead of FB 128
o 2: in addition to 1 with ITS PID up to 1.4 GeV/c
=> FemtoNanoLD: change cuts, FB 256, ITS PID

PWGGA/GammaConv/AliAnalysisTaskGammaIsoTree.cxx, PWGGA/GammaConv/AliAnalysisTaskGammaIsoTree.h, PWGGA/GammaConv/AliConversionAodSkimTask.cxx, PWGGA/GammaConv/CMakeLists.txt, PWGGA/GammaConv/PWGGAGammaConvLinkDef.h, PWGGA/GammaConv/macros/AddTask_AodSkim.C, PWGGA/GammaConv/macros/AddTask_GammaIsoTree.C
- added task that creates a tree used to analyze isolated photons
- fixed a bug in the conversion skim task, that caused skimming for photons above phimax
=> PWGGA/GammaConv: added new IsoTree task & fixed bug in conversion skim

PWGMM/UE/UeKNO/AliAnalysisTaskMcKnoUe.cxx
=> fix the break segmentation(remove bad commit)

PWGJE/EMCALJetTasks/Tracks/AliAnalysisTaskEmcalSoftDropResponse.cxx
Residuals for zg, Rg, thetag and nsd monitored
vs part. level pt absolute and normalized by
the part level observable
=> Adding residuals for SoftDrop observables

PWGGA/GammaConv/AliAnalysisTaskOmegaToPiZeroGamma.cxx
- The check for secondaries takes a good amount of time and considering
that there does not seem to be many secondaries (~0.1%)
this is commented out for now
=> OmegaToPiZeroGamma no secondary check

PWGHF/jetsHF/AliAnalysisTaskDJetCorrelations.cxx, PWGHF/jetsHF/AliAnalysisTaskDmesonsFilterCJ.cxx, PWGHF/jetsHF/AliAnalysisTaskDmesonsFilterCJ.h
Reverts alisw/AliPhysics#13866  - (2/3)
Current D-jets code is broken. And the issue cannot be located. So going back to the point of stable code. This is the second reversal of three PRs that supposedly broke the code.
=> Revert "fix-Reverting the "fArrayDStartoD0pi"-renaming in DFilter task"

PWGHF/vertexingHF/AliAnalysisTaskSEXicZero2XiPifromKFP.cxx, PWGHF/vertexingHF/AliAnalysisTaskSEXicZero2XiPifromKFP.h, PWGHF/vertexingHF/macros/AddTaskXicZero2XiPiFromKFParticle.C
Add weight for systematic study of MC pt shape
=> Add weight for systematic study of MC pt shape

RUN3/AliAnalysisTaskAO2Dconverter.cxx, RUN3/AliAnalysisTaskAO2Dconverter.h
- All names made canonical (O2 var names correspond to f+branch name)
- Rename VZERO
- Trigger becomes BC table
- Primary key is BCID for most tables
=> Updating RUN3 converter to updated O2 data model

PWGMM/UE/CMakeLists.txt, PWGMM/UE/PWGMMueLinkDef.h, PWGMM/UE/UeKNO/AddTaskGenMcKno.C, PWGMM/UE/UeKNO/AliAnalysisTaskGenMcKno.cxx, PWGMM/UE/UeKNO/AliAnalysisTaskGenMcKno.h
This analysis task produces the histograms for the new RT analysis
=> new analysis task for NchT anslysis (MCgen)

PWGMM/UE/UeKNO/AliAnalysisTaskGenMcKno.cxx
Minor change in primary charged particle selection
=> minor change in particle selection

PWGDQ/dielectron/macrosLMEE/AddTask_dsekihat_lowmass_PbPb.C
=> PWGDQ/LMEE: update AddTask

PWGDQ/reducedTree/AliReducedVarManager.cxx, PWGDQ/reducedTree/AliReducedVarManager.h
Hi Ionut
Please have a look at this PR, it is the same as before, but changed a little about the function name as you suggested.
Cheers
Xiaozhi
=> Add the MC pT re-weight 

PWGLF/STRANGENESS/CMakeLists.txt, PWGLF/STRANGENESS/Correlationpp/AddTaskCorrelationhCasc.C, PWGLF/STRANGENESS/Correlationpp/AliAnalysisCorrelationEventCollection.cxx, PWGLF/STRANGENESS/Correlationpp/AliAnalysisCorrelationEventCollection.h, PWGLF/STRANGENESS/Correlationpp/AliAnalysisTaskCorrelationhCasc.cxx, PWGLF/STRANGENESS/Correlationpp/AliAnalysisTaskCorrelationhCasc.h, PWGLF/STRANGENESS/PWGLFSTRANGENESSLinkDef.h
=> Include h-cascade task

PWGCF/FLOW/macros/AddTaskCRC.C
modify AddTaskCRC.C file. Turn on CRC and CME
=> modify AddTaskCRC.C file. Turn on CRC and CME

PWGCF/FEMTOSCOPY/FemtoDream/AliAnalysisTaskNanoLD.cxx, PWGCF/FEMTOSCOPY/FemtoDream/AliAnalysisTaskNanoLD.h, PWGCF/FEMTOSCOPY/macros/AddTaskFemtoNanoLD.C
o Get mass squared from TOF beta for (anti)deuterons
o Remove ITS PID for the moment
o Add FB=768 for subwagon 2
=> FemtoNanoLD: get mass squared for deuterons

PWGMM/UE/UeKNO/AliAnalysisTaskMcKno.cxx, PWGMM/UE/UeKNO/AliAnalysisTaskMcKno.h
Modification for comparing the published minimum bias results (V0M-integrated).
=> Modification for comparison with published MB results

PWGCF/Correlations/DPhi/AliAnalysisTaskLongFluctuations2PC.cxx, PWGCF/Correlations/DPhi/AliAnalysisTaskLongFluctuations2PC.h, PWGCF/Correlations/macros/AddTaskLongFluctuations2PC.C
New pile-up cuts and a change in histogram format
=> Adding pile up cuts for Pb-Pb

PWGJE/EMCALJetTasks/Tracks/AliAnalysisTaskEmcalJetEnergyScale.cxx, PWGJE/EMCALJetTasks/Tracks/AliAnalysisTaskEmcalJetEnergySpectrum.cxx, PWGJE/EMCALJetTasks/Tracks/AliAnalysisTaskEmcalSoftDropData.cxx, PWGJE/EMCALJetTasks/Tracks/AliAnalysisTaskEmcalSoftDropResponse.cxx
Needed to cover full range for R=0.6 jets
=> Fix histogram range, adding constituent cluster QA histos

PWGHF/vertexingHF/charmFlow/AliHFQnVectorHandler.cxx
fix bug introduced in 4de26532b650e7e85a63c0c633b4dbe04b4ceb14
=> Fix bug in load of V0 Q-vector calibrations

PWGMM/UE/UeKNO/AddTaskMcKno.C, PWGMM/UE/UeKNO/AliAnalysisTaskMcKno.cxx, PWGMM/UE/UeKNO/AliAnalysisTaskMcKno.h
Modification for systematic uncertainties of NTS analysis
=> Modification for systematic uncertainties of NTS analysis

PWGGA/GammaConv/macros/AddTask_GammaCalo_pp.C
adding Cutstrings without timing cut to create timing effi for EDC
=> PWGGA/GammaConv  adding Cutstrings 

PWGCF/FEMTOSCOPY/AliFemtoUser/AliFemtoMJTrackCut.cxx, PWGCF/FEMTOSCOPY/AliFemtoUser/AliFemtoMJTrackCut.h
=> Pt-dependent DCA-Z cut in AliFemtoMJTrackCut

PWGLF/NUCLEX/Nuclei/NucleiPbPb/AliAnalysisTaskNucleiYield.cxx, PWGLF/NUCLEX/Nuclei/NucleiPbPb/AliAnalysisTaskNucleiYield.h
Thanks to @abalbino for his help
=> Initialise flag to 0 for rec nuclei

RUN3/AliAnalysisTaskAO2Dconverter.cxx
Adding eta and phi tracklets conversions to alpha, snp and tgl global track parameters to Run2 SPD tracklets to Run3 converter
=> Adding Run2 SPD tracklets to Run3 converter

PWGDQ/dielectron/CMakeLists.txt, PWGDQ/dielectron/LMEE/AliAnalysisTaskeeCor.cxx, PWGDQ/dielectron/LMEE/AliAnalysisTaskeeCor.h, PWGDQ/dielectron/PWGDQdielectronLinkDef.h, PWGDQ/dielectron/macrosLMEE/AddTask_hdegenhardt_eeCorMC.C
Included AddTask and AliAnalysisTask for angular correlations of dielectrons and DCAee for MC data (2016, 2017 and 2018 data - to be run on trains)
=> Included AddTask and AliAnalysisTask for MC analysis

PWGLF/RESONANCES/PostProcessing/f0980/AliAnalysisTaskInclusivef0f2.cxx
Updates on y_CMS more checking for PID variation
=> [PWGLF] Updates on y_CMS and other things..

PWGJE/EMCALJetTasks/UserTasks/AliAnalysisTaskEA.cxx, PWGJE/EMCALJetTasks/UserTasks/AliAnalysisTaskEA.h
Introducing new number jet counting histogram for random trigger
=> Breaking the FillHistogram function to several smaller functions

PWG/EMCAL/EMCALtasks/AliEmcalCorrectionCellCloneContainer.cxx, PWG/EMCAL/EMCALtasks/AliEmcalCorrectionCellCloneContainer.h, PWG/EMCAL/EMCALtasks/AliEmcalCorrectionClusterizer.cxx, PWG/EMCAL/EMCALtasks/CMakeLists.txt, PWG/EMCAL/EMCALtasks/PWGEMCALtasksLinkDef.h, PWG/EMCAL/config/AliEmcalCorrectionConfiguration.yaml
Needed for studies with multiple cross-talk emulation settings, but it can be used for example to check the effect of different calibrations in one go
=> New component to clone the cells branch on demand

PWGDQ/dielectron/macrosLMEE/AddTask_dsekihat_lowmass_PbPb.C
=> PWGDQ/LMEE: update AddTask for PID calib.

PWGHF/jetsHF/AliAnalysisTaskIPCalib.cxx, PWGHF/jetsHF/AliAnalysisTaskIPCalib.h, PWGHF/jetsHF/macros/AddTaskIPCalib.C
Applying correction factors on the IPs extracted from a function fitted to the sigma Vs pScat.
=> Applying correction factors on the IPs

PWGGA/CaloTrackCorrelations/yaml/EMCalCorrConfig_MC_ClV1_SeveralxTalk_ECellCut.yaml
EMCal correction framework.
V1 clusters, careful with MC label tagging, use only for not too old productions, mostly Run2 or change the remap/mc label configuration.
=> [PWGGA/CaloTrackCorr] Multiple xTalk execution example configuration

PWGCF/Correlations/JCORRAN/Pro/AliAnalysisTaskRidge.cxx, PWGCF/Correlations/JCORRAN/Pro/AliAnalysisTaskRidge.h, PWGCF/Correlations/macros/jcorran/AddTaskJJetSmallCone.C
=> [PWGCF] Update on the correction

PWGHF/vertexingHF/AliAnalysisTaskSEDmesonPIDSysProp.cxx, PWGHF/vertexingHF/macros/EstimateSingleTrackPIDsyst.C, PWGHF/vertexingHF/macros/config_singletrack_pid.yml
Improvements:
- usage of RDataFrames to speed up analysis
- add yaml configuration file to pass settings to the macro
- add initial method for TPC-TOF matching efficiency studies
=> Improve code for PID systematics from tagged single tracks 

PWGCF/FEMTOSCOPY/FemtoDream/AliFemtoDreamTrackCuts.cxx, PWGCF/FEMTOSCOPY/FemtoDream/AliFemtoDreamTrackCuts.h, PWGCF/FEMTOSCOPY/FemtoDream/AliFemtoDreamTrackHist.cxx, PWGCF/FEMTOSCOPY/FemtoDream/AliFemtoDreamTrackHist.h, PWGCF/FEMTOSCOPY/FemtoDream/AliFemtoDreamTrackMCHist.cxx, PWGCF/FEMTOSCOPY/FemtoDream/AliFemtoDreamTrackMCHist.h, PWGCF/FEMTOSCOPY/macros/AddTaskFemtoDreamPionVar.C
=> -Changes to the DCA Template MultRange.

PWGLF/RESONANCES/AliRsnMiniAnalysisTask.cxx
=> Skip ESD TriggerSelection when use Builtin AliEventCut

PWGPP/CalibMacros/AliOCDBtoolkit.sh, PWGPP/macros/pcalimonitorCSV.sh
* updated version of toolkit to dump, diff, compare, modified OCDB entries from shell script
````
[AliPhysics/latest] /data/NOTESdata/alice-tpc-notes/JIRA/ALIROOT-8420/test $> (source /home2/miranov/software/aliceGSI/AliPhysics///PWGPP/CalibMacros/AliOCDBtoolkit.sh  -h )
(source ${ALICE_PHYSICS}/PWGPP/CalibMacros/AliOCDBtoolkit.sh <action> <par0> <par1> ...
dumpOCDBXML       -  NEW help format
lambdaOCDB        -  NEW help format
dumpObject        -  NEW help format
rootFileConvert   -  ROOT->XML and back - does not work for template classes
ocdbMakeTable     -  NEW help format    - hash does not work  TODO
cdbMapInfo        -  New help format
diffObject        -  New help format
dumpOCDBDiffTable -  TODO
diffConfig        -  TODO
ocdbDiffTable     -  TODO
( source …
```
=> PWGPP-592 - modification of the OCDB dumps + using CLion bash convention

PWGHF/treeHF/AliAnalysisTaskSEHFTreeCreator.cxx, PWGHF/treeHF/AliAnalysisTaskSEHFTreeCreator.h, PWGHF/treeHF/AliHFJet.cxx, PWGHF/treeHF/AliHFJet.h, PWGHF/treeHF/AliHFJetFinder.cxx, PWGHF/treeHF/AliHFTreeHandler.cxx, PWGHF/treeHF/AliHFTreeHandler.h, PWGHF/treeHF/AliHFTreeHandlerInclusiveJet.cxx, PWGHF/treeHF/AliHFTreeHandlerInclusiveJet.h, PWGHF/treeHF/CMakeLists.txt, PWGHF/treeHF/PWGHFtreeHFLinkDef.h, PWGHF/treeHF/macros/AddTaskHFTreeCreator.C
=> adding inclusive jets

PWGGA/GammaConv/AliAnalysisTaskGammaCaloMerged.cxx, PWGGA/GammaConv/macros/AddTask_GammaCaloMerged_pp.C, PWGGA/GammaConvBase/AliCaloPhotonCuts.cxx
Modified handling for energy splitting for clusters with NLM > 1
=> PWGGA/GammaConv: Added NLM variations for MergedClusterTask

PWGLF/SPECTRA/CMakeLists.txt, PWGLF/SPECTRA/ChargedHadrons/dNdPt/AliAnalysisTaskSpectraDPhi.cxx, PWGLF/SPECTRA/ChargedHadrons/dNdPt/AliAnalysisTaskSpectraDPhi.h, PWGLF/SPECTRA/ChargedHadrons/dNdPt/macros/AddTaskSpectraDPhi.C, PWGLF/SPECTRA/PWGLFspectraLinkDef.h
New Analysis task to study pT spectra for different DeltaPhi bins
=> New Analysis task to study Dphi dependent pT spectra

PWGCF/FLOW/GF/AliAnalysisTaskGFWPIDFlow.cxx, PWGCF/FLOW/GF/AliAnalysisTaskGFWPIDFlow.h
Adding GFWMode 4, which is essentially mode 0, but using merged weights
=> Adding one more mode to GFWPID task -- using merged weights

PWGUD/UPC/AddPolarization.C, PWGUD/UPC/Polarization.cxx, PWGUD/UPC/Polarization.h
Analysis code to reproduce Simone's result on J/Psi Polarization, these macro only save muon tracks and the muon pair in terms of TLorenz Vector
=> Code to reproduce Simone's Result

PWGGA/GammaConv/AliAnalysisTaskConvCaloCalibration.cxx, PWGGA/GammaConv/AliAnalysisTaskEtaToPiPlPiMiGamma.cxx, PWGGA/GammaConv/AliAnalysisTaskGammaCalo.cxx, PWGGA/GammaConv/AliAnalysisTaskGammaCaloDalitzV1.cxx, PWGGA/GammaConv/AliAnalysisTaskGammaCaloIso.cxx, PWGGA/GammaConv/AliAnalysisTaskGammaCaloMerged.cxx, PWGGA/GammaConv/AliAnalysisTaskGammaCaloMix.cxx, PWGGA/GammaConv/AliAnalysisTaskGammaConvCalo.cxx, PWGGA/GammaConv/AliAnalysisTaskGammaConvCaloIso.cxx, PWGGA/GammaConv/AliAnalysisTaskGammaConvDalitzV1.cxx, PWGGA/GammaConv/AliAnalysisTaskGammaConvFlow.cxx, PWGGA/GammaConv/AliAnalysisTaskGammaConvV1.cxx, PWGGA/GammaConv/AliAnalysisTaskGammaIsoTree.cxx, PWGGA/GammaConv/AliAnalysisTaskGammaTriggerQA.cxx, PWGGA/GammaConv/AliAnalysisTaskHeavyNeutralMesonToGG.cxx, PWGGA/GammaConv/AliAnalysisTaskMaterialHistos.cxx, PWGGA/GammaConv/AliAnalysisTaskNeutralMesonToPiPlPiMiNeutralMeson.cxx, PWGGA/GammaConv/AliAnalysisTaskNeutralMesonToPiPlPiMiPiZero.cxx, PWGGA/GammaConv/AliAnalysisTaskOmegaToPiZeroGamma.cxx, PWGGA/GammaConv/AliAnalysisTaskSigmaPlToProtonPiZero.cxx, PWGGA/GammaConv/AliAnalysisTaskSigmaPlToProtonPiZeroAOD.cxx, PWGGA/GammaConv/AliAnalysisTaskTrackQA.cxx, PWGGA/GammaConvBase/AliConvEventCuts.cxx, PWGGA/GammaConvBase/AliConvEventCuts.h
tested with /alice/data/2018/LHC18r/000297481/pass3/AOD/001 (time
cut cuts some events) and /alice/data/2018/LHC18r/000297414/pass3/AOD/001
(no events being cut)
=> PWGGA/GammaConv Add timerange cut to AliConvEventCuts

PWGDQ/dielectron/core/AliAnalysisTaskEtaReconstruction.cxx, PWGDQ/dielectron/core/AliAnalysisTaskEtaReconstruction.h, PWGDQ/dielectron/macrosLMEE/Config_feisenhut_EtaReconstruction.C
Additional support histograms are added to the list of support histograms in order to distinguish the different PID dE/dx spectra
=> PWGDQ EtaReconstruction: Added full list of dE/dx Histograms, separated in each component

PWGJE/EMCALJetTasks/AliEmcalJetTask.cxx
When using constituent subtraction, the jet constituents should store
the subtracted constituents (when provided). This is the expected
behavior, and mirrors that of `AliEmcalJet::Track(int)`
@mfasDa Please take a look and let me know what you think. I stopped using these classes, but I hope this will others avoid the same issues that I had - it's easy to miss. I tested for charged constituents and it appears to work. However, I don't see a way to make an equivalent construction for charged constituents at the moment. I raise an exception rather than allow this to pass unnoticed. But suggestions are appreciated!
=> Store subtracted constituents in jet constituents

PWGCF/Correlations/DPhi/AliAnalysisTaskSEpPbCorrelationsJetV2.cxx, PWGCF/Correlations/DPhi/AliAnalysisTaskSEpPbCorrelationsJetV2.h, PWGCF/Correlations/DPhi/CMakeLists.txt, PWGCF/Correlations/DPhi/PWGCFCorrelationsDPhiLinkDef.h, PWGCF/Correlations/macros/pPbCorrelations/AddTaskpPbCorrelationsJetV2.C
Hi all,
This task is developed from Yuko's task: AliAnalysisTaskSEpPbCorrelationsYS.cxx
This task can calculate the TPC-FMD correlation in each TPC-TPC pairs, which aim to obtain the V2 of Jet particles in TPC-TPC correlations. The preliminary results were shown in Flow-PAG: https://indico.cern.ch/event/907906/contributions/3843813/attachments/2029228/3395754/ST20200429.pdf
Thanks!
Siyu Tang
=> Add new task: AliAnalysisTaskSEpPbCorrelationsJetV2

PWGCF/Correlations/JCORRAN/Pro/AliAnalysisTaskRidge.cxx, PWGCF/Correlations/JCORRAN/Pro/AliAnalysisTaskRidge.h, PWGCF/Correlations/macros/jcorran/AddTaskJJetSmallCone.C, PWGCF/Correlations/macros/jcorran/AddTaskRidge.C
Modification for the correction.
Modification for the small cone size.
=> [PWGCF] Modify the correction

PWGCF/Correlations/JCORRAN/Pro/AliAnalysisTaskRidge.cxx, PWGCF/Correlations/JCORRAN/Pro/AliAnalysisTaskRidge.h
=> [PWGCF] Add MC flag

PWGLF/QATasks/CMakeLists.txt, PWGLF/QATasks/PWGLFQATasksLinkDef.h
Commit for C. De Martin and A.Balbino
=> add task into cmake list

PWG/EMCAL/EMCALbase/AliEMCALRecoUtils.cxx, PWG/EMCAL/EMCALbase/AliEMCALRecoUtils.h
- Change TArray pointer class members to object
class members
- Use TArrayL64 for PAR event array instead of
c-style dynamic array
=> Make TArray class mebers object members

PWGCF/FEMTOSCOPY/AliFemtoUser/AliFemtoESDTrackCut.cxx
Improving the PID selection for deuterons.
=> changes in the code for deuterons - femtoscopy

RUN3/AliAnalysisTaskAO2Dconverter.cxx, RUN3/AliAnalysisTaskAO2Dconverter.h
From lbl back to label. Using UInt_t for fLabel and bit 15 of fLabelMask to keep the sign. Adding mccalolabel.
=> Updated MC labels.

PWGCF/FLOW/GF/AliAnalysisTaskGFWPIDFlow.cxx, PWGCF/FLOW/GF/AliAnalysisTaskGFWPIDFlow.h
I think this is what crashes train runs
=> Storing GFWMode and Trigger in the GFWPID task

PWGCF/FEMTOSCOPY/AliFemtoUser/AliFemtoESDTrackCut.cxx
improving selection - low pt deuterons
=> changes in the deuteron selection - femtoscopy

PWGJE/EMCALJetTasks/Tracks/AliAnalysisTaskEmcalRecalcPatchesRef.cxx, PWGJE/EMCALJetTasks/Tracks/AliAnalysisTaskEmcalRecalcPatchesRef.h
- Add histograms with downscale-corrected counts
- Take trigger threshods from OCDB instead of hard-coded thresholds
=> Downscale correction, Thresholds from CDB

PWGHF/vertexingHF/AliAnalysisTaskCharmDecayTracks.cxx, PWGHF/vertexingHF/AliAnalysisTaskCharmDecayTracks.h, PWGHF/vertexingHF/macros/AddTaskCharmDecayTracks.C
Main new feature: separation of prompt and feeddown in the tree.
Minor updates in histograms, add task logic and default values.
=> Updates in the task to produce tree of charm decay tracks

PWGMM/UE/CMakeLists.txt, PWGMM/UE/PWGMMueLinkDef.h, PWGMM/UE/UeDphi/AddTaskUeSpectraDphi.C, PWGMM/UE/UeDphi/AliAnalysisTaskUeSpectraDphi.cxx, PWGMM/UE/UeDphi/AliAnalysisTaskUeSpectraDphi.h
New TAsk for pT spectra for different Dphi bins
=> New TAsk for pT spectra for different Dphi bins

PWGGA/GammaConv/AliAnalysisTaskGammaCalo.cxx
modifying Calo timing effi tree for EMC and DCal analyses
=> PWGGA/GammaConv modifying Calo timing effi tree 

PWGCF/FEMTOSCOPY/macros/Train/KpKmpp13TeV/AddTaskFemto.C, PWGCF/FEMTOSCOPY/macros/Train/KpKmpp13TeV/ConfigFemtoAnalysis.C
=> Lego Train configuration file K+K- pp13TeV

PWGGA/PHOSTasks/PHOS_Tagging/AliAnalysisTaskTaggedPhotons.cxx, PWGGA/PHOSTasks/PHOS_Tagging/AliAnalysisTaskTaggedPhotons.h
Remove fluctuations in JJ events
=> Hadling JJ events added

PWGLF/RESONANCES/PostProcessing/f0980/AliAnalysisTaskInclusivef0f2.cxx
=> [PWGLF] update on pid

PWGHF/vertexingHF/AliRDHFCutsKFP.cxx, PWGHF/vertexingHF/AliRDHFCutsKFP.h
=> Add cuts for Lc analysis

PWGCF/FEMTOSCOPY/AliFemtoUser/AliFemtoCutMonitorParticlePtPDG.cxx
=> Update ftpcHist dEdx limits

PWG/muon/AliLMREvent.h
Added PileupFromSPDInMultBins information in AliLMREvent.h
=> PileupFromSPDInMultBins info in AliLMREvent

PWGCF/EBYE/BalanceFunctions/AliAnalysisTaskSignedBF.cxx, PWGCF/EBYE/BalanceFunctions/AliAnalysisTaskSignedBF.h, PWGCF/EBYE/CMakeLists.txt, PWGCF/EBYE/PWGCFebyeLinkDef.h
=> Adding the first version of the signed BF task

PWGCF/Correlations/JCORRAN/Pro/AliAnalysisTaskGenMCRidge.cxx, PWGCF/Correlations/JCORRAN/Pro/AliAnalysisTaskGenMCRidge.h, PWGCF/Correlations/macros/jcorran/AddTaskGenMCRidge.C
=> [PWGCF] code for on-the-fly mode

PWGJE/EMCALJetTasks/CMakeLists.txt, PWGJE/EMCALJetTasks/PWGJEEMCALJetTasksLinkDef.h, PWGJE/EMCALJetTasks/UserTasks/AliAnalysisTaskJetDynamicalGrooming.cxx, PWGJE/EMCALJetTasks/UserTasks/AliAnalysisTaskJetDynamicalGrooming.h, PWGJE/EMCALJetTasks/UserTasks/AliAnalysisTaskJetHardestKt.cxx, PWGJE/EMCALJetTasks/UserTasks/AliAnalysisTaskJetHardestKt.h, PWGJE/EMCALJetTasks/macros/AddTaskJetHardestKt.C
Cross check more general substructure task. Also includes some minor cleanup and tweaks
=> Simplied task for cross check

PWGGA/PHOSTasks/ClusterSelection/AliCaloTriggerMimicHelper.h
=> PWGGA: remove ! in //!

PWGPP/AliPIDtools.cxx
+ New AliRoot version with modified AliTPCPIDResponse  
will be needed for pileup correction
=> PWGPP-545, PWGPP-538 - replaced hardwired constants + using vertexInfoESD, for pile-up dEdx correction

PWGCF/Correlations/Base/AliAnalysisTaskNtuplizer.cxx
adding daughter charge information in tree
=> adding daughter charge information in tree

PWGCF/FEMTOSCOPY/macros/Train/malinina/May2020/KK_13TeV_dist/AddTaskFemtoKchHBT1090.C, PWGCF/FEMTOSCOPY/macros/Train/malinina/May2020/KK_13TeV_dist/ConfigFemtoAnalysis.C
=> Ludmila: Train: May2020

PWGHF/vertexingHF/vHFML/AliAnalysisTaskSEHFTreeCreatorApply.cxx, PWGHF/vertexingHF/vHFML/AliAnalysisTaskSEHFTreeCreatorApply.h, PWGHF/vertexingHF/vHFML/AliHFTreeHandlerApply.cxx, PWGHF/vertexingHF/vHFML/AliHFTreeHandlerApply.h, PWGHF/vertexingHF/vHFML/AliHFTreeHandlerApplyDstoKKpi.cxx, PWGHF/vertexingHF/vHFML/AliHFTreeHandlerApplyDstoKKpi.h, PWGHF/vertexingHF/vHFML/AliHFTreeHandlerApplyLc2V0bachelor.cxx, PWGHF/vertexingHF/vHFML/AliHFTreeHandlerApplyLc2V0bachelor.h
Propagating some recent fixes in the original TreeCreatorTask to the ML-application-on-GRID version
=> PWGHF: Updating HFTreeCreatorApply

PWGCF/Correlations/JCORRAN/Pro/AliAnalysisTaskGenMCRidge.cxx, PWGCF/Correlations/JCORRAN/Pro/AliAnalysisTaskGenMCRidge.h, PWGCF/Correlations/JCORRAN/Pro/CMakeLists.txt, PWGCF/Correlations/JCORRAN/Pro/PWGCFCorrelationsJCORRANProLinkDef.h, PWGCF/Correlations/macros/jcorran/AddTaskGenMCRidge.C
=> [PWGCF] code for the MCGEN legotrain

PWGLF/NUCLEX/Exotica/LambdaN/AliAnalysisTaskLambdaNRun2.cxx
commit for D. Pagano and J. Pazzini
=> small fix to run on MC

PWGHF/vertexingHF/AliAnalysisTaskSELc2V0bachelorTMVA.cxx
Fix a bug on selection of absolute value of K0S pdg code
=> Fix a bug on selection of absolute value of K0S pdg code

PWGCF/FEMTOSCOPY/AliFemtoUser/AliFemtoESDTrackCut.cxx, PWGCF/FEMTOSCOPY/AliFemtoUser/AliFemtoESDTrackCut.h
Corrections to the old set for the deuteron's identification and the first version of the function for the sideband analysis.
=> deuterons - a function for the sideband analysis

PWGCF/Correlations/DPhi/AliAnalysisTaskV0ChCorrelation.cxx, PWGCF/Correlations/DPhi/AliAnalysisTaskV0ChCorrelationpp.cxx
=> V0-h spectra

PWGMM/UE/CMakeLists.txt, PWGMM/UE/PWGMMueLinkDef.h, PWGMM/UE/UeKNO/AddTaskDataKno.C, PWGMM/UE/UeKNO/AliAnalysisTaskDataKno.cxx, PWGMM/UE/UeKNO/AliAnalysisTaskDataKno.h
Modified Task for RT analysis to solve memory issues in lego train
=> Modified Task for RT analysis

PWGCF/Correlations/JCORRAN/Pro/AliAnalysisTaskGenMCRidge.cxx
=> [PWGCF] add jet tagging

PWGCF/Correlations/JCORRAN/Pro/AliAnalysisTaskGenMCRidge.cxx
=> [PWGCF] updates on code

PWGPP/AliPIDtools.cxx, PWGPP/AliPIDtools.h
returnType==0 -  return expected  signal
returnType==1 -  return corrected signal
=> PWGPP-545, PWGPP-538 - adding returnType as an argument

PWGLF/NUCLEX/Nuclei/AbsorptionRatios/AliAnalysisTaskNuclei.cxx, PWGLF/NUCLEX/Nuclei/AbsorptionRatios/AliAnalysisTaskNuclei.h, PWGLF/NUCLEX/Nuclei/AbsorptionRatios/macros/AddHighMultNucleiTask.C
Tasks to analyse He4 and triton in HM pp. Particularly triton to cross check absorption of He3 with isospin partner.
=> Added Task for He4 & triton analyses

PWGCF/FEMTOSCOPY/macros/Train/malinina/May2020/KK_13TeV_dist/ConfigFemtoAnalysis.C
=> Ludmila: Update lego train May2020 ConfigFemtoAnalysis.C

PWGCF/FEMTOSCOPY/macros/Train/KpKmpp13TeV_FB128woS/AddTaskFemto.C, PWGCF/FEMTOSCOPY/macros/Train/KpKmpp13TeV_FB128woS/ConfigFemtoAnalysis.C
=> K+K- configuration FB128 w/0 S-cut

PWGCF/EBYE/BalanceFunctions/AliAnalysisTaskSignedBF.cxx, PWGCF/EBYE/BalanceFunctions/AliAnalysisTaskSignedBF.h, PWGCF/EBYE/macros/AddTaskSignedBF.C, PWGCF/EBYE/macros/runSignedBF.C
more development/polishing will come with time
=> Adding the first full implementation of the signed BF task

PWGGA/EMCALTasks/AliAnalysisTaskGammaHadron.cxx, PWGGA/EMCALTasks/AliAnalysisTaskGammaHadron.h
Correlations now work in MC, saving MC true vs bkg info
Add cluster rotation
updated hadron pt bins
=> pi0-h update: MC correlations and cluster pair rotation

PWGGA/EMCALTasks/AliAnalysisTaskGammaHadron.cxx
Make sideband regions stricter. Add 1/3 sideband option
=> Updates sideband definitions

PWGPP/ITS/AliMeanVertexPreprocessorOffline.cxx
1) more robust fits to vertex distributions
2) fix compilation warnings
3) improve canvases when using the drawing option
4) code cleanup
=> Updates in MeanVertex preprocessor

PWGCF/FEMTOSCOPY/FemtoDream/AliAnalysisTaskThreeBodyFemto.cxx, PWGCF/FEMTOSCOPY/FemtoDream/AliAnalysisTaskThreeBodyFemto.h
Moved triplet creation to a function, made it general - now can create triplets for any particles.
=> First triplet approach try

RUN3/AliAnalysisTaskAO2Dconverter.cxx, RUN3/AliAnalysisTaskAO2Dconverter.h
=> renaming TRDTOFpattern field

PWGCF/FEMTOSCOPY/AliFemtoUser/AliFemtoESDTrackCut.cxx
New parameters for the sideband analysis. Two possible sets of parameters for 2 and 3 sigmas in the TPC detector (+ now the pt range is wider than before).
=> deuterons - better parameters in sideband analysis

PWGHF/treeHF/AliHFTreeHandler.cxx, PWGHF/treeHF/AliHFTreeHandler.h, PWGHF/vertexingHF/vHFML/AliHFTreeHandlerApply.cxx, PWGHF/vertexingHF/vHFML/AliHFTreeHandlerApply.h
For PbPb `18 studies. Replacement of the geometrical cut
=> PWGHF: Add TPCclsPID in reduced track var Tree

PWGHF/vertexingHF/macros/AddTaskHFTreeCreatorApply.C
Add suffix to TDirectory, so task can be run multiple times in same train
=> PWGHF: Possibility to run multiple wagons in same train

PWGDQ/dielectron/macrosLMEE/AddTask_hdegenhardt_eeCorMC.C
Return task outside config loop
=> Fixing AddTask for MC sysUnc analysis

PWGCF/FEMTOSCOPY/AliFemtoUser/AliFemtoESDTrackCut.cxx
p dependent mass cut instead of one value
=> deuterons - improvement in the cut on mass

PWGGA/GammaConvBase/AliCaloPhotonCuts.cxx
Efficiency from electron testbeam (to be applied on data to reject random N_cell>1 clusters)
[NCellEffi.pdf](https://github.com/alisw/AliPhysics/files/4780034/NCellEffi.pdf)
Reformulated electron testbeam efficiency to be applied on MC (accepting cluster with N_cell=1)
[NCellEffi_P2_CorrHist.pdf](https://github.com/alisw/AliPhysics/files/4780035/NCellEffi_P2_CorrHist.pdf)
=> PWGGA/GammaConv: Updated EMCal NCell efficiency parametrizations

PWGCF/Correlations/DPhi/AliAnalysisTaskV0ChCorrelation.cxx, PWGCF/Correlations/DPhi/AliAnalysisTaskV0ChCorrelationpp.cxx
=> V0-h update

PWGCF/FLOW/GF/AliAnalysisTaskMeanPtV2Corr.cxx, PWGCF/FLOW/GF/AliAnalysisTaskMeanPtV2Corr.h
and also adding a TProfile to keep count of mean Nch in a bin
=> MeanPtV2 fluct. corr.: changed filter bit to 96 for comp. to ALICE

PWGCF/FEMTOSCOPY/FemtoDream/AliAnalysisTaskPOmegaPenne.cxx, PWGCF/FEMTOSCOPY/FemtoDream/AliAnalysisTaskPOmegaPenne.h, PWGCF/FEMTOSCOPY/macros/AddTaskPOmegaPenne.C
* first only Xi
* Anti Xi, Lambda and Anti Lambda following
=> Paircleaner on invariant mass

PWGJE/EMCALJetTasks/UserTasks/AliAnalysisTaskJetHardestKt.cxx, PWGJE/EMCALJetTasks/UserTasks/AliAnalysisTaskJetHardestKt.h
Based on the shared momentum fraction of the subjet
=> Trace location of unmatched subjets

PWGCF/FEMTOSCOPY/FemtoDream/AliAnalysisTaskPOmegaPenne.cxx, PWGCF/FEMTOSCOPY/FemtoDream/AliAnalysisTaskPOmegaPenne.h, PWGCF/FEMTOSCOPY/macros/AddTaskPOmegaPenne.C
=> wrapper for invMass of femtoBasepart, turned dEta dPhi plots back on

RUN3/AliAnalysisTaskAO2Dconverter.cxx, RUN3/AliAnalysisTaskAO2Dconverter.h
Sigmas on diagonal, rhos off-diagonal
=> Compressed representation of the cov. matrix.

PWGUD/UPC/AliAnalysisTaskADin2018.cxx, PWGUD/UPC/AliAnalysisTaskADin2018.h, PWGUD/UPC/AliAnalysisTaskForMCpPb.cxx, PWGUD/UPC/AliAnalysisTaskForMCpPb.h, PWGUD/UPC/AliAnalysisTaskUPCforwardMC.cxx, PWGUD/UPC/AliAnalysisTaskUPCforwardMC.h, PWGUD/UPC/AliAnalysisTaskUPCforwardpPb.cxx, PWGUD/UPC/AliAnalysisTaskUPCforwardpPb.h
=> PWGUD/UPC: Sidebands, reweighting, trigger, neutron emission improvements.

PWGCF/FEMTOSCOPY/FemtoDream/AliAnalysisTaskThreeBodyFemto.cxx, PWGCF/FEMTOSCOPY/FemtoDream/AliAnalysisTaskThreeBodyFemto.h
+ created arrays for histograms instead of creating billions of histograms
=> Q3 distribution in multiplicity bins

PWGJE/EMCALJetTasks/UserTasks/AliAnalysisTaskJetHardestKt.cxx
It turns out that the labels (not the global index or other values) are
propagated to the subtracted constituents, so we can use the labels for
matching
=> Match subjet constituent by label for hybrid-det matching

PWGCF/FEMTOSCOPY/FemtoDream/AliAnalysisTaskPOmegaPenne.cxx, PWGCF/FEMTOSCOPY/FemtoDream/AliAnalysisTaskPOmegaPenne.h, PWGCF/FEMTOSCOPY/macros/AddTaskPOmegaPenne.C
* Xi mass calculation
* inv mass paircleaner
=> revert to working train with corrected:

PWGCF/Correlations/DPhi/AliAnalysisTaskSEpPbCorrelationsJetV2.cxx, PWGCF/Correlations/DPhi/AliAnalysisTaskSEpPbCorrelationsJetV2.h, PWGCF/Correlations/macros/pPbCorrelations/AddTaskpPbCorrelationsJetV2.C
Hi,
Here is the update of AliAnalysisTaskSEpPbCorrelationsJetV2.cxx, which can reduce the size of output.
Thanks!
Siyu
=> Update to Jet V2

PWGGA/GammaConv/macros/AddTask_OmegaToPiZeroGamma_pp.C
- Added train configs for the AP-Like cut
=> PWGGA/GammaConv: OmegaToPiZeroTask - Added train configs for the AP-Like cut

PWGHF/vertexingHF/AliAnalysisTaskSED0Mass.cxx, PWGHF/vertexingHF/AliAnalysisTaskSED0Mass.h
I have added two new TH2F to control chi2nCls vs ptD for daughter tracks.
=> Add chi2nCls vs ptD control histo

PWGDQ/dielectron/macrosLMEE/AddTask_rbailhac_lowmass_PbPb.C
Macro to look at Pb-Pb 2018 data
=> Macro Pb--Pb

PWGUD/UPC/AliAnalysisTaskUPCforwardMC.cxx, PWGUD/UPC/AliAnalysisTaskUPCforwardMC.h
IMPORTANT: tested and plots verified to check that now everything is alright.
=> PWGUD/UPC: Polarisation Photon Energy check. Bug fixes.

PWGLF/SPECTRA/PiKaPr/TPCTOFCascades/AliAnalysisPIDCascadeTrack.cxx, PWGLF/SPECTRA/PiKaPr/TPCTOFCascades/AliAnalysisPIDCascadeTrack.h, PWGLF/SPECTRA/PiKaPr/TPCTOFCascades/AliAnalysisTaskTPCTOFCascade.cxx
I've just re-added the Electron PIDs to my previous track trees.
I also re-adjusted the cuts for the V0s.
The cascade cuts are re-adjusted in the vertexer instead.
=> Added ELectron PID to tracks, and updated cuts for V0s and Cascade

PWGDQ/dielectron/macrosLMEE/AddTask_rbailhac_lowmass_PbPb.C
=> Fix of the macro

PWGCF/Correlations/DPhi/AliAnalysisTaskSEpPbCorrelationsJetV2.cxx
Hi,
Here is a small modification of counting of trigger particles.
Thanks!
SIyu
=> update jet v2

PWGJE/EMCALJetTasks/Tracks/AliAnalysisEmcalTriggerSelectionHelper.cxx, PWGJE/EMCALJetTasks/Tracks/AliAnalysisEmcalTriggerSelectionHelper.h, PWGJE/EMCALJetTasks/Tracks/AliAnalysisTaskEmcalJetEnergyScale.cxx, PWGJE/EMCALJetTasks/Tracks/AliAnalysisTaskEmcalJetEnergySpectrum.cxx
- Add trigger clusters used in older data sets
(CENTNOPMD, ALL, ALLNOTRD)
- Add handling for EJE trigger (EMCAL jet trigger
in 8 TeV) as extra case.
=> Support for EMCAL triggers in pp 8 TeV

PWGDQ/dielectron/macrosLMEE/AddTask_rbailhac_ElectronEfficiencyV2_PbPb.C
=> Add macro efficiency

PWGDQ/dielectron/core/AliAnalysisTask_JPsi_EMCal.cxx, PWGDQ/dielectron/core/AliAnalysisTask_JPsi_EMCal.h, PWGDQ/dielectron/macrosJPSI/AddTask_JPsi_EMCal.C, PWGDQ/dielectron/macrosJPSI/Config_JPsi_EMCal.C
a flag to perform the spectrum analysis was added.
=> New flag to perform spectrum analysis

PWGDQ/dielectron/core/AliAnalysisTaskElectronEfficiencyV2.cxx, PWGDQ/dielectron/core/AliAnalysisTaskElectronEfficiencyV2.h, PWGDQ/dielectron/macrosLMEE/AddTask_dsekihat_ElectronEfficiencyV2_PbPb.C
add support for genID for pileup MC
=> PWGDQ/LMEE: add support for genID for pileup MC

PWGCF/FEMTOSCOPY/FemtoDream/AliAnalysisTaskPOmegaPenne.cxx, PWGCF/FEMTOSCOPY/FemtoDream/AliAnalysisTaskPOmegaPenne.h, PWGCF/FEMTOSCOPY/macros/AddTaskPOmegaPenne.C
* fixed MC for Xi
* removed checks for correct function values
* fixed histogram ranges and bin sizes
=> fixed weights for invariant mass PairCleaner

PWGDQ/dielectron/macrosLMEE/AddTask_rbailhac_ElectronEfficiencyV2_PbPb.C
=> Update macro for efficiency

PWGUD/UPC/AliAnalysisTaskUpcEtaCAWP.cxx, PWGUD/UPC/AliAnalysisTaskUpcEtaCAWP.h
Modified quality cuts and added channel
=> Update to AliAnalysisTaskUpcEtaCAWP.cxx

PWGHF/vertexingHF/AliAnalysisTaskSEXicZero2XiPifromKFP.cxx, PWGHF/vertexingHF/AliAnalysisTaskSEXicZero2XiPifromKFP.h, PWGHF/vertexingHF/AliRDHFCutsKFP.cxx, PWGHF/vertexingHF/AliRDHFCutsKFP.h
Update chi2topo, add DCA of primary pion, add feed-down flag
=> Update chi2topo, add DCA of primary pion, add feed-down flag

PWGDQ/dielectron/macrosLMEE/AddTask_rbailhac_ElectronEfficiencyV2_PbPb.C
=> Update macro for Pb-Pb

PWGJE/EMCALJetTasks/AliAnalysisTaskPWGJEQA.cxx
When I use "eventQA" of the AliAnalysisTaskPWGJEQA, I faced a segment fault.
=> modified:   PWGJE/EMCALJetTasks/AliAnalysisTaskPWGJEQA.cxx

PWGGA/GammaConv/AliAnalysisTaskSigmaPlToProtonPiZeroAOD.cxx
Reduced memory, added a DCA cut and implemented a rotation method for the estimation of the background
=> PWGGA/GammaConv: Reduced memory, added a DCA cut and implemented a rotation method

PWGHF/vertexingHF/AliAnalysisTaskSEXicZero2XiPifromKFP.cxx
=> Add chi2geo_Xic0 variable

PWGHF/vertexingHF/AliAnalysisTaskSEXicTopKpi.cxx
If the c-deuteron analysis flag is true then the TTree has some extra variables filled.
=> Added extra variables to tree for c-deuteron analysis

PWGDQ/dielectron/macrosLMEE/AddTask_rbailhac_lowmass_PbPb.C
Update the add macro for the data
=> Update add macro

PWGCF/FEMTOSCOPY/FemtoDream/AliAnalysisTaskNanoLD.cxx, PWGCF/FEMTOSCOPY/FemtoDream/AliAnalysisTaskNanoLD.h, PWGCF/FEMTOSCOPY/macros/AddTaskFemtoNanoLD.C
o Restrict (anti-)deuteron pT cuts to lower pT
o Add simple particle counter
=> FemtoNanoLD: change deuteron pT cuts, add counter

PWGGA/GammaConv/macros/AddTask_V0Reader.C, PWGGA/GammaConvBase/AliConvEventCuts.cxx
UPC triggers CCUP8 and CCUP9 added to the analysis.
=> Added UPC triggers

PWGHF/vertexingHF/AliAnalysisTaskSEXicZero2XiPifromKFP.cxx, PWGHF/vertexingHF/AliAnalysisTaskSEXicZero2XiPifromKFP.h, PWGHF/vertexingHF/AliRDHFCutsKFP.cxx, PWGHF/vertexingHF/AliRDHFCutsKFP.h, PWGHF/vertexingHF/macros/AddTaskXicZero2XiPiFromKFParticle.C
=> Add flag for Omegac0 analysis

PWGHF/vertexingHF/AliRDHFCutsLctoV0.cxx, PWGHF/vertexingHF/AliRDHFCutsLctoV0.h, PWGHF/vertexingHF/vHFML/AliAnalysisTaskSEHFTreeCreatorApply.cxx
Option to reduce a bit further the CPU time when running pK0s in PbPb '18
=> PWGHF: Add extra PreSelect for pK0s

PWGHF/vertexingHF/macros/AddTaskCFVertexingHF3ProngLc.C, PWGHF/vertexingHF/macros/AddTaskCFVertexingHF3ProngLc_Ntracklet.C
Restore old AddTask, 
add a new one with code for to correct the efficiency with the equalized tracklet distributions
=> Restore old AddTask, add a new one with Tracklet equalization

PWGCF/Correlations/DPhi/AliAnalysisTaskV0ChCorrelation.cxx, PWGCF/Correlations/DPhi/AliAnalysisTaskV0ChCorrelationpp.cxx
=> V0-h pile up

PWGGA/GammaConv/macros/AddTask_GammaCalo_pp.C
to evaluate of systematic errors about triggers which are EG1 and EG2
=> evaluation of systematic error about triggers which are EG1 and EG2

PWGHF/vertexingHF/AliAnalysisTaskSEImproveITS.h
Added a access to fIsPbPb2018 for finer phi-binning
=> Added a access to fIsPbPb2018 for finer phi-binning

PWGDQ/dielectron/macrosLMEE/AddTask_dsekihat_ElectronEfficiencyV2_PbPb.C, PWGDQ/dielectron/macrosLMEE/AddTask_dsekihat_lowmass_PbPb.C, PWGDQ/dielectron/macrosLMEE/Config_dsekihat_ElectronEfficiencyV2_PbPb.C, PWGDQ/dielectron/macrosLMEE/Config_dsekihat_lowmass_PbPb.C, PWGDQ/dielectron/macrosLMEE/LMEECutLib_dsekihat.C
update AddTask, Config, LMEECutLib
=> PWGDQ/LMEE: update AddTask, Config, LMEECutLib

PWGDQ/dielectron/macrosLMEE/AddTask_dsekihat_lowmass_PbPb.C
quick fix to dir path in AddTask
=> PWGDQ/LMEE: quick fix to dir path in AddTask

PWGGA/GammaConv/AliAnalysisTaskGammaCaloMerged.cxx, PWGGA/GammaConv/AliAnalysisTaskGammaCaloMerged.h, PWGGA/GammaConv/macros/AddTask_GammaCaloMerged_pp.C, PWGGA/GammaConv/macros/AddTask_GammaCalo_pp.C
Additionally added train configs for clusterizer studies
=> PWGGA/GammaConv: Added QA histos to merged cluster Task for M02 and M20 studies.

PWGDQ/dielectron/macrosLMEE/LMEECutLib_dsekihat.C
=> PWGDQ/LMEE: quick fix to LMEECutLib

PWGDQ/dielectron/macrosLMEE/AddTask_rbailhac_lowmass_PbPb.C
=> Fix for input of Config

PWGHF/treeHF/AliAnalysisTaskSEHFTreeCreator.cxx, PWGHF/treeHF/AliAnalysisTaskSEHFTreeCreator.h
Add event selection code from AliMultSelection to event tree
=> Update event tree

PWGUD/UPC/AddTaskUpc4Prongs.C, PWGUD/UPC/AliAnalysisTaskUpc4Prongs.cxx, PWGUD/UPC/AliAnalysisTaskUpc4Prongs.h, PWGUD/UPC/CMakeLists.txt, PWGUD/UPC/PWGUDupcLinkDef.h
Hi
I would like to use lego trains for my analysis, so I've prepared my tasks for it.
=> [PWGUD/UPC]: Add task for four prong analysis

PWGCF/Correlations/macros/AddTaskV0ChCorrelation.C, PWGCF/Correlations/macros/AddTaskV0ChCorrelationPrei.C, PWGCF/Correlations/macros/AddTaskV0ChCorrelationpp.C
=> update V0-h sys

PWGCF/FEMTOSCOPY/FemtoDream/AliAnalysisTaskNanoLD.cxx, PWGCF/FEMTOSCOPY/FemtoDream/AliAnalysisTaskNanoLD.h, PWGCF/FEMTOSCOPY/macros/AddTaskFemtoNanoLD.C
o Add protons and anti-protons, but not for CF
o These are used to clean pairs with lambdas and anti-lambdas
o Also add a switch for the proton-lambda pair cleaner
=> FemtoNanoLD: add (anti-)protons for pair cleaner

PWGUD/UPC/AddPolarizationJP.C, PWGUD/UPC/AliAnalysisTaskPolarizationTestJP.cxx, PWGUD/UPC/AliAnalysisTaskPolarizationTestJP.h
This is the analysis code to recreate the result based on original work by Simone
=> analyisis code to test polarization measurement by Simone

PWGDQ/dielectron/core/AliAnalysisTaskEtaReconstruction.cxx, PWGDQ/dielectron/core/AliAnalysisTaskEtaReconstruction.h, PWGDQ/dielectron/macrosLMEE/AddTask_feisenhut_EtaReconstruction.C, PWGDQ/dielectron/macrosLMEE/Config_feisenhut_EtaReconstruction.C
Some small changes for the task performance and added resolution histograms for secondaries.
=> PWGDQ EtaReconstruction SecondaryResolutionHists

PWGPP/AliAnalysisTaskFilteredTree.cxx, PWGPP/AliPIDtools.cxx, PWGPP/AliPIDtools.h
* AliPIDtools::UnitTest
* adding test of composed PID Probability
* AliPIDtools::ComputePIDProbabilityCombined 
* bug fix - initialize full array
* adding fake probability to combined PID before multiplying
=> PWGPP-545 - updates UnitTest, RegisterPIDAliases, ComputePIDProbabilityCombined

PWGMM/Lumi/vdM/VdmStability/AliAnalysisTaskVdmStability.cxx, PWGMM/Lumi/vdM/VdmStability/AliAnalysisTaskVdmStability.h
Including the number of vtx contributors variable
=> Including the number of vtx contributors variable

PWGUD/UPC/AddTaskUpc4Prongs.C, PWGUD/UPC/AliAnalysisTaskUpc4Prongs.cxx, PWGUD/UPC/AliAnalysisTaskUpc4Prongs.h
Hi, I've prepared the changes for my tasks. 
Please approve it.
Everything is ok from my side:
~~~bash
aliBuild build AliPhysics --defaults user-next-root6 -j 10
...
==> Building AliPhysics@master
==> AliPhysics is being built (use --debug for full output): ok
==> Build of AliPhysics successfully completed on `RUMLAB'.
Your software installation is at:
/home/bdrum/apps/alice/sw/ubuntu1804_x86-64
You can use this package by loading the environment:
alienv enter AliPhysics/latest-master-user-next-root6
==> Build directory for devel package AliPhysics:
/home/bdrum/apps/alice/sw/BUILD/AliPhysics-latest/AliPhysics
~~~
=> PWGUD/UPC: DCA corrections and removing redundant variables

PWGDQ/dielectron/macrosLMEE/AddTask_feisenhut_EtaReconstruction.C
=> Fixing misspelling in last PullRequest

PWGGA/GammaConv/AliAnalysisTaskGammaCalo.cxx, PWGGA/GammaConv/AliAnalysisTaskGammaCalo.h, PWGGA/GammaConv/AliAnalysisTaskGammaConvCalo.cxx, PWGGA/GammaConv/AliAnalysisTaskGammaConvCalo.h, PWGGA/GammaConv/macros/AddTask_GammaCalo_pp.C, PWGGA/GammaConv/macros/AddTask_GammaConvCalo_pp.C, PWGGA/PHOSTasks/ClusterSelection/AliCaloTriggerMimicHelper.cxx, PWGGA/PHOSTasks/ClusterSelection/AliCaloTriggerMimicHelper.h
Sorry I closed the last request by mistake;
1)    Added Histograms
2)    Dont use triggered events without L0 Trigger
3)    Demand Pi0 candidates to have cluster that triggered
=> PWGGA: Changes to PHOS Trigger

PWGCF/Correlations/JCORRAN/Pro/AliAnalysisTaskRidge.cxx
=> [PWGCF] add small acceptance mode

PWGGA/GammaConv/AliAnalysisTaskGammaCalo.cxx, PWGGA/GammaConv/AliAnalysisTaskGammaConvCalo.cxx, PWGGA/GammaConv/macros/AddTask_GammaCalo_pp.C, PWGGA/GammaConv/macros/AddTask_GammaConvCalo_pp.C
Add Cluster Cut analog to Omega Implementaion: Only if one Cluster has E > Threshold, Meson Candidate is used
=> PWGGA: Cluster Min E Cut on Meson

PWG/EMCAL/EMCALtasks/AliEmcalFastOrMonitorTask.cxx, PWG/EMCAL/EMCALtasks/AliEmcalFastOrMonitorTask.h, PWGJE/EMCALJetTasks/PWGJEEMCALJetTasksLinkDef.h, PWGJE/EMCALJetTasks/Tracks/AliAnalysisTaskEmcalOnlinePatchesRef.cxx, PWGJE/EMCALJetTasks/Tracks/AliAnalysisTaskEmcalOnlinePatchesRef.h, PWGJE/EMCALJetTasks/macros/AddTaskEmcalOnlinePatchesRef.C
- Move to PWGJE::EMCALJetTasks
- Add data grids for FastOR energy, FEE energy, nmasked
and map for fastors contributing to firing patches
- Change output histograms to THnSparses for patch
energy, patch residuals, fastor energy and fastor
residuals
=> Reorganize Online patch QA task

PWGCF/Correlations/macros/AddTaskV0ChCorrelation.C, PWGCF/Correlations/macros/AddTaskV0ChCorrelationPrei.C, PWGCF/Correlations/macros/AddTaskV0ChCorrelationpp.C
=>  sys Looser cut

PWGCF/FEMTOSCOPY/macros/Train/DEtaDPhi/2020/MCGen/QinvPTSumDist/BasiwWeight/ConfigFemtoAnalysis.C
=> AliFemto: modifications to config in MCgen_pp train

PWGLF/NUCLEX/Hypernuclei/Vertexer2Body/AliVertexerHyperTriton2Body.cxx, PWGLF/NUCLEX/Hypernuclei/Vertexer2Body/AliVertexerHyperTriton2Body.h
This reverts commit ba5350c8d6ba1ab49436e90ac0a260ecfe8574c7.
Revert "Fix charge convention in the vertexer"
This reverts commit 56ae2bde12a61ae3d428e9c62b46be438e88c586.
Revert "Support lambda decays"
This reverts commit 63ef0a80a7a06b869a2250d4c4c04320d53d7206.
=> Revert "Fix mass assignment"

PWGGA/GammaConv/AliAnalysisTRDEfficiency.cxx, PWGGA/GammaConv/AliAnalysisTRDEfficiency.h, PWGGA/GammaConv/macros/AddTask_TRDEfficiency.C
- Runs (only) on ESDs, thus has access to the sagitta value of TRD tracks.
- Generates photons on the fly using AliV0ReaderV1
- Can rate the matching of TRD tracks to the global track by using AliTRDonlineTrackMatching.
=> PWGGA/GammaConv: Modified AliAnalysisTRDEfficiency to work on ESDs

PWGLF/NUCLEX/Hypernuclei/Hyp2Body/AliAnalysisTaskHyperTriton2He3piML.cxx, PWGLF/NUCLEX/Hypernuclei/Vertexer2Body/AliVertexerHyperTriton2Body.cxx, PWGLF/NUCLEX/Hypernuclei/Vertexer2Body/AliVertexerHyperTriton2Body.h
Now it is possible to create of a tree of candidates lambda decaying in proton and pion with the same structure as for the hypertriton in 2body.
=> adapt to lambda

PWGGA/GammaConvBase/AliCaloPhotonCuts.cxx
- purpose is to check if the track to the charged component in the cluster exists. If no track exists, the track matching cannot work
=> PWGGA/GammaConv: Added a few cases to track matching efficiency histo

PWGCF/FEMTOSCOPY/FemtoDream/AliAnalysisTaskPOmegaPenne.cxx, PWGCF/FEMTOSCOPY/FemtoDream/AliAnalysisTaskPOmegaPenne.h
=> relative momentum check

PWGHF/vertexingHF/AliAnalysisTaskSED0BDT.cxx, PWGHF/vertexingHF/AliAnalysisTaskSED0BDT.h, PWGHF/vertexingHF/macros/AddTaskD0BDT.C
Modified 2step BDT task
- Dynamic no. of read-in BDT classifiers
- Fixed mismatched dim in classifier array for 2017 pp
=> Modified 2step BDT task

PWGHF/vertexingHF/AliCFTaskVertexingHF.cxx
fix segfault that was missed in last commit for RT case in CF task. (only kRT was affected by the issue, other options are safe)
=> fix segfault in kRT case

PWGDQ/dielectron/core/AliAnalysisTaskElectronEfficiencyV2.cxx
implement IsParticleFromOutOfBunchPileupCollision
=> PWGDQ/LMEE: implement IsParticleFromOutOfBunchPileupCollision

PWGGA/GammaConv/AliAnalysisTaskElectronStudies.cxx, PWGGA/GammaConv/AliAnalysisTaskElectronStudies.h, PWGGA/GammaConv/AliAnalysisTaskGammaIsoTree.cxx, PWGGA/GammaConv/AliAnalysisTaskGammaIsoTree.h, PWGGA/GammaConv/CMakeLists.txt, PWGGA/GammaConv/PWGGAGammaConvLinkDef.h, PWGGA/GammaConv/macros/AddTask_ElectronStudies.C, PWGGA/GammaConv/macros/AddTask_GammaIsoTree.C
introduction of task that can be used to evaluate electron tracking efficiencies and E/p resolution for data and MC
=> PWGGA/GammaConv: introduction of electron studies task

PWGGA/GammaConv/AliAnalysisTRDEfficiency.cxx, PWGGA/GammaConv/AliAnalysisTRDEfficiency.h, PWGGA/GammaConv/macros/AddTask_TRDEfficiency.C
To try to reduce memory leaks.
=> PWGGA/GammaConv: Changed static arrays to dynamic arrays.

PWGGA/GammaConv/AliAnalysisTaskElectronStudies.cxx, PWGGA/GammaConv/AliAnalysisTaskGammaIsoTree.cxx, PWGGA/GammaConv/AliAnalysisTaskGammaIsoTree.h, PWGGA/GammaConv/macros/AddTask_ElectronStudies.C, PWGGA/GammaConv/macros/AddTask_GammaIsoTree.C
- fixed m02 histos for GammaIsoTree
- added proper support for corrframework for electron task and gammaisotree
=> PWGGA/GammaConv: GammIsoTree fixed m02 histos +more

PWGCF/Correlations/macros/pPbCorrelations/AddTaskpPbCorrelationsJetV2.C
Hi,
Just update the Addtask.C macro to fix the bug within root6.
thanks!
Siyu Tang
=> update for root6

PWGJE/EMCALJetTasks/Tracks/AliAnalysisEmcalTriggerSelectionHelper.cxx, PWGJE/EMCALJetTasks/Tracks/AliAnalysisTaskEmcalTriggerBase.cxx
- Add -S- scheme instead of -B- scheme
- Reject TRD trigger classes containing INT7 string
=> Fix retrieving downscale factors for run1

PWGCF/FEMTOSCOPY/FemtoDream/AliAnalysisTaskGeorgiosNTuple.cxx, PWGCF/FEMTOSCOPY/FemtoDream/AliAnalysisTaskGeorgiosNTuple.h, PWGCF/FEMTOSCOPY/macros/AddTaskGeorgiosNTuple.C
Write the nTuple only if there are at least two Lambdas. Also removing the MC info to run over data
=> Disabeling MC and changing the selection for Lambda Lambda

PWG/FLOW/Tasks/AliAnalysisTaskCMW.cxx, PWG/FLOW/Tasks/AliAnalysisTaskCMW.h
Added Centrality Dependent MC and Circular PID cut for pion
=> Added Centrality Dependent MC and Circular PID cut for pion

PWGCF/Correlations/DPhi/AliAnalysisTaskDiHadCorrelHighPt.cxx
fixed phi dependence of efficiency
=> Changes in AliAnalysisTaskDiHadCorrelHighPt.cxx 

PWGGA/GammaConv/AliAnalysisTaskGammaCalo.cxx, PWGGA/GammaConv/AliAnalysisTaskGammaCalo.h
PWGGA: Use DDLs instead of modules for trigger rejection
=> PWGGA: Use DDLs instead of modules for trigger rejection

PWGGA/GammaConv/AliAnalysisTaskGammaCalo.cxx
Bugfix, as the start value is not 0 anymore
=> PWGGA: Bugfix, wwhen Histogram does not start at DDL 0

PWGCF/Correlations/DPhi/AliAnalysisTaskSEpPbCorrelationsJetV2.cxx, PWGCF/Correlations/DPhi/AliAnalysisTaskSEpPbCorrelationsJetV2.h, PWGCF/Correlations/macros/pPbCorrelations/AddTaskpPbCorrelationsJetV2.C
Hi,
Here is an update for jet v2 analysis.
Thanks a lot!
Siyu Tang
=> Update for Jet v2

PWGCF/Correlations/DPhi/AliAnalysisTaskGeneralBF.h, PWGCF/Correlations/macros/PIDBFDptDpt/AddTaskGeneralBF.C
update injected signal removal
=> update injected signal removal

PWGJE/EMCALJetTasks/Tracks/AliAnalysisTaskEmcalClustersRef.cxx, PWGJE/EMCALJetTasks/Tracks/AliAnalysisTaskEmcalClustersRef.h
Needed when running with downscale weight
=> Re-establish option for sumw2

PWGCF/FLOW/GF/AliAnalysisTaskMeanPtV2Corr.cxx, PWGCF/FLOW/GF/AliAnalysisTaskMeanPtV2Corr.h, PWGCF/FLOW/macros/AddTaskMeanPtV2Corr.C
Added external setters for pT and multiplicity bins
=> MeanPt - v2 correlation

PWGCF/Correlations/DPhi/AliAnalysisTaskDiHadCorrelHighPt.cxx
=> Change in AliAnalysisTaskDiHadCorrelHighPt.cxx 

PWGJE/EMCALJetTasks/Tracks/AliAnalysisTaskEmcalOnlinePatchesRef.cxx
- Patch selection returned by mistake true also in case the patch was rejected
- In FastOR loop reject positions inside the PHOS region
=> Fix patch selection

PWGLF/SPECTRA/PiKaPr/TPCTOFCascades/AliAnalysisPIDCascadeParticle.cxx, PWGLF/SPECTRA/PiKaPr/TPCTOFCascades/AliAnalysisPIDCascadeParticle.h, PWGLF/SPECTRA/PiKaPr/TPCTOFCascades/AliAnalysisTaskTPCTOFCascade.cxx
As the title says, just a small modification to handle the primary status.
=> Modifications to MCParticle class, to store IsPhysicalPrimary status.

PWGLF/SPECTRA/PiKaPr/TPC/rTPC/AliAnalysisTaskSpectraMC.cxx, PWGLF/SPECTRA/PiKaPr/TPC/rTPC/AliAnalysisTaskSpectraMC.h
The track selection now includes the missing 'GetTPCsignalN' cut which was used for the preliminaries. This changes the shape of the efficiencies
=> Updates on the track selection

PWGCF/FEMTOSCOPY/macros/AddTaskFemtoNanoLD.C
o Without TPC nSigma cut or without TOF nSigma cut
o Again back to std pair cleaner and no CPR
=> FemtoNanoLD: cut settings for deuteron purities

PWGHF/correlationHF/CMakeLists.txt, PWGHF/hfe/CMakeLists.txt, PWGHF/vertexingHF/AliAnalysisTaskSELc2pKs0fromKFP.cxx, PWGHF/vertexingHF/AliAnalysisTaskSELc2pKs0fromKFP.h, PWGHF/vertexingHF/AliAnalysisTaskSEXicZero2XiPifromKFP.cxx, PWGHF/vertexingHF/AliAnalysisTaskSEXicZero2XiPifromKFP.h, PWGHF/vertexingHF/AliVertexingHFUtils.cxx, PWGHF/vertexingHF/AliVertexingHFUtils.h, PWGHF/vertexingHF/CMakeLists.txt, PWGHF/vertexingHF/PWGHFvertexingHFLinkDef.h, PWGHF/vertexingHF/macros/AddTaskLc2pKs0FromKFParticle.C, PWGJE/EMCALJetTasks/CMakeLists.txt
Move KF functions to AliVertexingHFUtils and add class AliAnalysisTaskSEXicZero2XiPifromKFP and AddTaskLc2pKs0FromKFParticle.C
=> Move KF functions to AliVertexingHFUtils

PWGHF/vertexingHF/AliAnalysisTaskSEXic2eleXifromAODtracks.cxx, PWGHF/vertexingHF/AliAnalysisTaskSEXic2eleXifromAODtracks.h
Do the weights for prompt efficiency. And change 'f -> F'
=> Weighted procedure for prompt efficiency and 'f->F'

PWGCF/FEMTOSCOPY/FemtoDream/AliAnalysisTaskNanoPt.cxx, PWGCF/FEMTOSCOPY/macros/AddTaskNanoPt.C
got back to NSigman = 3 deuteron PID
=> adds a check for pair cleaner, switched off track cleaning, 

PWGLF/SPECTRA/PiKaPr/TPCTOFCascades/AliAnalysisPIDCascadeParticle.cxx
minor bugfix in addition to my previous modification of AliAnalysisPIDCascadeParticle.h and .cxx.
=> Minor bugfix: Forgot to expand constructor for the previous modification

PWGMM/Lumi/vdM/VdmStability/AddTask_ilofnes_Vdm.C, PWGMM/Lumi/vdM/VdmStability/AliAnalysisTaskVdmStability.cxx, PWGMM/Lumi/vdM/VdmStability/AliAnalysisTaskVdmStability.h
Added all of the stability histograms needed in the analysis. If any detected problem we can still check the TTrees.
=> Filling stability histograms

PWGCF/Correlations/DPhi/AliAnalysisTaskSEpPbCorrelationsJetV2.cxx
Hi ,
Here are the updates for Jet v2 analysis, where the TPC-TPC correlation was added. Thanks a lot!
Siyu
=> Update TPCTPC correlation

PWGCF/FEMTOSCOPY/FemtoDream/AliAnalysisTaskFemtoSMI.cxx, PWGCF/FEMTOSCOPY/FemtoDream/AliAnalysisTaskFemtoSMI.h, PWGCF/FEMTOSCOPY/macros/AddTaskFemtoSMI.C
I added the files "AddTaskFemtoSMI.C", "AliAnalysisTaskFemtoSMI.cxx", "AliAnalysisTaskFemtoSMI.h". They implement a new Proton-Lambda femtoscopy analysis built in the FemtoDream framework.
=> added files for FemtoSMI analysis

PWGCF/FEMTOSCOPY/FemtoDream/AliAnalysisTaskFemtoSMI.h, PWGCF/FEMTOSCOPY/FemtoDream/CMakeLists.txt, PWGCF/FEMTOSCOPY/FemtoDream/PWGCFFemtoDreamLinkDef.h
@miweberSMI @simons27 
this should do the trick
=> Missing CMakeList and LinkDef for PR 15228

PWGJE/EMCALJetTasks/Tracks/AliAnalysisEmcalTriggerSelectionHelper.cxx, PWGJE/EMCALJetTasks/Tracks/AliAnalysisTaskEmcalJetEnergyScale.cxx, PWGJE/EMCALJetTasks/Tracks/AliAnalysisTaskEmcalJetEnergySpectrum.cxx
- Add handling for EMC7 trigger (EMCAL jet trigger
in 8 TeV) as extra case.
=> Support for EMC7 trigger in pp 8 TeV

PWGHF/vertexingHF/AliAnalysisTaskSEXic0Semileptonic.cxx, PWGHF/vertexingHF/AliAnalysisTaskSEXic0Semileptonic.h
=> Xic0Semileptonic_debugWeight

PWGGA/PHOSTasks/ClusterSelection/AliCaloTriggerMimicHelper.cxx, PWGGA/PHOSTasks/ClusterSelection/AliCaloTriggerMimicHelper.h
Add Histograms: Triggered Clusters - Rows and Columns
=> PWGGA: Add Histograms: Triggered Clusters - Rows and Columns

PWGCF/FEMTOSCOPY/FemtoDream/AliAnalysisTaskGeorgiosNTuple.cxx, PWGCF/FEMTOSCOPY/FemtoDream/AliAnalysisTaskGeorgiosNTuple.h, PWGCF/FEMTOSCOPY/macros/AddTaskGeorgiosNTuple.C
And: reduction of TTree Branches which are not needed for that to reduce disk space usage
=> Wider cuts to include the background for purity estimation.

PWGLF/STRANGENESS/Cascades/Run2/AliAnalysisTaskStrangeCascadesDiscrete.cxx, PWGLF/STRANGENESS/Cascades/Run2/AliAnalysisTaskStrangeCascadesDiscrete.h, PWGLF/STRANGENESS/Cascades/Run2/macros/AddTaskStrangeCascadesDiscrete.C
1) small bugs fixed: chi2/ndf in TPC is now assigned correctly.
2) AliExternalTrackParams of charged daughters are saved now. It is essential, in order to correct for the energy loss using AliTrackerBase.
3) ITS hit info is stored as well. Previously - only ITS layer status was saved.
=> Updates and small bugs fixed

PWGCF/FEMTOSCOPY/macros/Train/KM/testgithub.txt
=> Test git hub 20 Aug 2020

PWGCF/Correlations/DPhi/AliAnalysisTaskSEpPbCorrelationsJetV2.cxx, PWGCF/Correlations/DPhi/AliAnalysisTaskSEpPbCorrelationsJetV2.h, PWGCF/Correlations/macros/pPbCorrelations/AddTaskpPbCorrelationsJetV2.C
Hi all,
Here is an update for more strict dphi cut in jet v2 analysis. 
Thanks a lot!
Siyu
=> Update for reducing dphi

PWGCF/FEMTOSCOPY/AliFemtoUser/AliFemtoModelCorrFctn3DKKGRQinv.cxx, PWGCF/FEMTOSCOPY/AliFemtoUser/AliFemtoModelCorrFctn3DKKGRQinv.h, PWGCF/FEMTOSCOPY/AliFemtoUser/CMakeLists.txt, PWGCF/FEMTOSCOPY/AliFemtoUser/PWGCFfemtoscopyUserLinkDef.h
=> AliFemtoModelCorrFctn3DKKGRQinv - new class Gleb Romanenko 21AUG2020

PWGCF/FLOW/GF/AliGFWWeights.cxx, PWGCF/FLOW/GF/AliGFWWeights.h
Also, weight histograms accept weights now
=> Minor changes in the initialisation of AliGFWWeights

PWGLF/RESONANCES/extra/AddAnalysisTaskEffMatrix.C, PWGLF/RESONANCES/extra/AliAnalysisTaskEffMatrix.cxx, PWGLF/RESONANCES/extra/AliAnalysisTaskEffMatrix.h, PWGLF/RESONANCES/extra/CMakeLists.txt, PWGLF/RESONANCES/extra/PWGLFrsnextraLinkDef.h
This PR adds an analysis task for resonance efficiencies and to produce efficiency matrices.
=> Task for resonance efficiency and matrices

PWGDQ/dielectron/core/AliAnalysisTask_JPsi_EMCal.cxx, PWGDQ/dielectron/macrosJPSI/Config_JPsi_EMCal.C
Changes to obtain J/psi spectrum uisng EMCal trigger.
=> J/psi spectrum using EMCal triggers: MC studies

PWGCF/FEMTOSCOPY/macros/AddTaskFemtoDreamPhiNanoAOD.C
@echizzal this should do the trick with the TPC radii
=> Enable phi at radii for p-phi task

PWGCF/Correlations/DPhi/AliAnalysisTaskSEpPbCorrelationsJetV2.cxx
Hi,
New updates for TPC-TPC correlation.
Thanks!
Siyu
=> Update for TPCTPC

PWGCF/FEMTOSCOPY/AliFemtoUser/AliFemtoModelGausLCMSFreezeOutGeneratorGR.cxx, PWGCF/FEMTOSCOPY/AliFemtoUser/AliFemtoModelGausLCMSFreezeOutGeneratorGR.h, PWGCF/FEMTOSCOPY/AliFemtoUser/CMakeLists.txt, PWGCF/FEMTOSCOPY/AliFemtoUser/PWGCFfemtoscopyUserLinkDef.h
=> AliFemtoModelGausLCMSFreezeOutGeneratorGR new class GR

PWGDQ/dielectron/core/AliDielectron.cxx, PWGDQ/dielectron/core/AliDielectron.h, PWGDQ/dielectron/core/AliDielectronVarManager.cxx, PWGDQ/dielectron/core/AliDielectronVarManager.h
add q vector for V0A/C inherited from Jpsi2ee
=> PWGDQ/LMEE: add q vector for V0A/C inherited from Jpsi2ee

PWGGA/GammaConv/AliAnalysisTaskElectronStudies.cxx, PWGGA/GammaConv/AliAnalysisTaskGammaIsoTree.cxx, PWGGA/GammaConv/AliAnalysisTaskGammaIsoTree.h
please wait for approval by Nico
=> PWGGA/GammaConv: GammaIsoTree major MC definition fixes

PWGHF/vertexingHF/vHFML/AliHFMLResponseLctoV0bachelor.cxx, PWGHF/vertexingHF/vHFML/AliHFMLResponseLctoV0bachelor.h, PWGHF/vertexingHF/vHFML/CMakeLists.txt
adding KFParticle variables to be used for ML respons in Lc->V0 analysis
=> add KF variables to ML response for Lc -> V0

PWGCF/FEMTOSCOPY/FemtoDream/AliAnalysisTaskFemtoSMI.cxx, PWGCF/FEMTOSCOPY/FemtoDream/AliAnalysisTaskFemtoSMI.h, PWGCF/FEMTOSCOPY/macros/AddTaskFemtoSMI.C
I added a private variable and according set-function to my class to allow for more flexibility with the trigger choice for analysis. Hard coded trigger selection in the AddTask was removed.
=> Added trigger selection

PWGLF/SPECTRA/PiKaPr/TPC/rTPC/AliAnalysisTaskSpectraRT.cxx, PWGLF/SPECTRA/PiKaPr/TPC/rTPC/AliAnalysisTaskSpectraRT.h
Parameters to calibrate the dEdx for the relativistic rise analysis were updated for the LHC16 data
=> Update on AnalysisTask

PWGPP/TPC/macros/PIDCalib/AddOADBFileTOPIDResponseOADB.C, PWGPP/TPC/macros/PIDCalib/AddOADBFileTOetaMaps.C, PWGPP/TPC/macros/PIDCalib/MakeTPCPIDResponseOADB.C, PWGPP/TPC/macros/PIDCalib/dumpEtaMaps.C, PWGPP/TPC/macros/PIDCalib/dumpPIDResponse.C, PWGPP/TPC/macros/PIDCalib/getdEdxGraph.C
As far as I saw since yesterdays tag we have the new AliRoot/v5-09-55-2 which includes the required modifications in AliTPCPIDResponse needed by the new splines. So it is fine to merge.
=> Splines and maps for LHC18q/r.pass3 without pileup correction 

PWGGA/CaloTrackCorrelations/AliAnaChargedParticles.cxx, PWGGA/CaloTrackCorrelations/AliAnaPhoton.cxx, PWGGA/CaloTrackCorrelations/macros/QA/AddTaskPi0IMGammaCorrQA.C
and improvement on QA analysis sub-tasks activation
=> [PWGGA/CaloTrackCorr] Fixes for call of uninitialized histograms related with centrality dependent analysis 

PWGHF/vertexingHF/macros/AddTaskCFVertexingHFLctoV0bachelorTMVA.C
fix assignment of pointer array (crashes in ROOT6)
=> fix pointer assignment in TMVA CF AddTask

PWGLF/NUCLEX/Utils/ChunkFilter/AddTask_FilterHe3.C, PWGLF/NUCLEX/Utils/ChunkFilter/AliAnalysisTaskFilterHe3.cxx, PWGLF/NUCLEX/Utils/ChunkFilter/AliAnalysisTaskFilterHe3.h
=> Triton case added

PWGLF/STRANGENESS/Cascades/Run2/AliAnalysisTaskStrangeCascadesDiscrete.cxx
Charge of cascade is saved correctly now.
=> Minor yet important correction

RUN3/AliAnalysisTaskAO2Dconverter.cxx
The cell type branch (Char_t) got as type "C" which
is interpreted as char array, instead it should have gotten
"B".
=> Fix type of EMCAL cells in trees

PWGLF/NUCLEX/Utils/O2vertexer/DCAFitterN.h, PWGLF/NUCLEX/Utils/O2vertexer/Track.h
=> Sync.O2 DCAFitterN

PWGDQ/dielectron/core/AliDielectronVarManager.h
update how to read root file for Qn
=> PWGDQ/LMEE: update how to read root file for Qn

PWGDQ/dielectron/core/AliAnalysisTaskEtaReconstruction.cxx
Enable commented code in order to check which kind of particles are not rejected by prefilter.
=> Enable debug code

PWGDQ/dielectron/core/AliDielectronVarManager.cxx, PWGDQ/dielectron/core/AliDielectronVarManager.h
=> PWGDQ/LMEE: add Q vector in TPC

PWGGA/GammaConvBase/AliCaloPhotonCuts.cxx, PWGGA/GammaConvBase/AliCaloPhotonCuts.h
Histos are only activated for fExtendedMatchAndQA == 3
=> PWGGA/GammaConv: Added time vs. energy histos for low and high gain clusters

PWGMM/UE/UeKNO/AddTaskMcKnoUeSyst.C
remove undeclared identifier from addtask
=> add undeclared identifier

PWGDQ/dielectron/core/AliDielectronVarManager.h
=> PWGDQ/LMEE: remove unnecessary print

PWGDQ/dielectron/core/AliDielectronVarManager.h
=> PWGDQ/LMEE: update TPC Qn

PWGDQ/dielectron/core/AliDielectronVarManager.h
quick fix to initialization of Q vector
=> PWGDQ/LMEE: quick fix to initialization of Q vector

PWG/CaloTrackCorrBase/AliCaloTrackReader.cxx, PWG/CaloTrackCorrBase/AliCaloTrackReader.h, PWGGA/CaloTrackCorrelations/AliAnaPhoton.cxx, PWGGA/CaloTrackCorrelations/AliAnaPhoton.h, PWGGA/CaloTrackCorrelations/macros/ConfigureAndGetEventTriggerMaskAndCaloTriggerString.C
plus control histogram on clusters in events with 0 tracks in central barrel
=> [PWGGA/CaloTrackCorr] Consider analysis with kCaloOnly and different triggers

PWGDQ/dielectron/core/AliDielectronVarManager.h
TPC Qn without division by width
=> PWGDQ/LMEE: TPC Qn without division by width

PWGHF/jetsHF/AliAnalysisTaskBJetTC.cxx, PWGHF/jetsHF/AliAnalysisTaskBJetTC.h
Adding a Histogram that will be used for estimating the degree of correlation between the IP and the SV method.
=> Adding histogram for estimating the correlation between IP and SV

PWGGA/GammaConv/macros/AddTask_OmegaToPiZeroGamma_pp.C
- added trainconfigs for rotation background with rotation around Pi0 for triggered data
=> PWGGA/GammaConv: OmegaToPiZero additional trainconfigs

PWGCF/FEMTOSCOPY/macros/Train/Gleb/FB_7_DCA_off/kk_502_0_40/ConfigFemtoAnalysis.C, PWGCF/FEMTOSCOPY/macros/Train/Gleb/FB_7_DCA_off/kk_502_40_90/ConfigFemtoAnalysis.C, PWGCF/FEMTOSCOPY/macros/Train/Gleb/FB_7_DCA_off/kk_502_70_90/ConfigFemtoAnalysis.C, PWGCF/FEMTOSCOPY/macros/Train/Gleb/PbPb_MC_3d/MC_443/ConfigFemtoAnalysis.C, PWGCF/FEMTOSCOPY/macros/Train/Gleb/PbPb_MC_3d/MC_444/ConfigFemtoAnalysis.C, PWGCF/FEMTOSCOPY/macros/Train/Gleb/PbPb_MC_3d/MC_544/ConfigFemtoAnalysis.C, PWGCF/FEMTOSCOPY/macros/Train/Gleb/PbPb_MC_3d/MC_656/ConfigFemtoAnalysis.C, PWGCF/FEMTOSCOPY/macros/Train/Gleb/PbPb_MC_3d/MC_757/ConfigFemtoAnalysis.C
=> Macros for Gleb Train FB_7_DCA_off PbPb_MC_3d

PWGGA/GammaConv/AliAnalysisTaskSigmaPlToProtonPiZeroAOD.cxx, PWGGA/GammaConv/AliAnalysisTaskSigmaPlToProtonPiZeroAOD.h, PWGGA/GammaConv/macros/AddTask_SigmaPlToProtonPiZeroAOD.C
Added some QA plots and changed the labelling of the true information. Furthermore optimized the rotationmethod by adding TGenPhaseSpace and increasing the number of swaps.
=> PWGGA/GammaConv:Added QA plots, optimized the rotationmethod and changed the labelling of the true information

PWGCF/FEMTOSCOPY/macros/Train/DEtaDPhi/2020/MCGen/QinvPTSumDist/LednickyCorrect/pions/ConfigFemtoAnalysis.C
=> AliFemto: withcing off strong int. for pi+pi+

PWGCF/FLOW/GF/AliAnalysisTaskNonlinearFlow.cxx, PWGCF/FLOW/GF/AliAnalysisTaskNonlinearFlow.h, PWGCF/FLOW/GF/CMakeLists.txt, PWGCF/FLOW/GF/PWGCFFLOWGFLinkDef.h, PWGCF/FLOW/macros/AddTaskNonlinearFlow.C
Add new task to analyze nonlinear flow
=> Add new task to analyze nonlinear flow

PWGDQ/dielectron/macrosLMEE/AddTask_rbailhac_ElectronEfficiencyV2_PbPb.C
=> fix ptee bin to be compatible

PWGHF/hfe/AliAnalysisTaskHFEBESpectraEMC.cxx, PWGHF/hfe/AliAnalysisTaskHFEBESpectraEMC.h, PWGHF/hfe/macros/AddTaskHFEBESpectraEMC.C
Changing THnsparse axis
- Removing Non-lin e/p 
- Adding additional axes for tagging electrons in MC
=> Adding MC-PDG flag to THnsparse

PWGHF/hfe/AliAnalysisTaskEHCorrel.cxx, PWGHF/hfe/AliAnalysisTaskEHCorrel.h, PWGHF/hfe/macros/AddTaskEHCorrel.C
Changes to fix a bug
Add a function to apply hadron eta cut
=> Setting to apply hadron eta cut

PWGDQ/dielectron/core/AliAnalysisTask_JPsi_EMCal.cxx, PWGDQ/dielectron/core/AliAnalysisTask_JPsi_EMCal.h
Adding new histograms for the spectrum analysis using EMCal trigger
=>  New histograms for TPC PID efficiency calculation

PWGCF/FEMTOSCOPY/macros/Train/JZ/mezonD/ConfigAnalysis.C
config for the analysis of the invariant mass of D mezons to run on trains
=> add config for analysis

PWGCF/FEMTOSCOPY/FemtoDream/AliFemtoDreamTrackCuts.h, PWGCF/FEMTOSCOPY/macros/AddTaskNanoPt.C
1) Adds default bool cutit = false for  fTOFInvMass in TOF Mass PID, 2) adds systematic changes for sidebands pd Analysis
=> 1) Adds default bool cutit = false for  fTOFInvMass in TOF Mass PID, 2) adds systematic changes for sidebands pd Analysis

PWGDQ/dielectron/core/AliAnalysisTask_JPsi_EMCal.cxx, PWGDQ/dielectron/core/AliAnalysisTask_JPsi_EMCal.h, PWGDQ/dielectron/macrosJPSI/Config_JPsi_EMCal.C
Removing Stack and TParticle from the task (which were used on ESD case only)
=> Removing Stack and TParticle from the task 

PWGGA/GammaConv/AliAnalysisTaskGammaCalo.cxx, PWGGA/GammaConv/AliAnalysisTaskGammaCalo.h, PWGGA/GammaConv/AliAnalysisTaskGammaConvCalo.cxx, PWGGA/GammaConv/AliAnalysisTaskGammaConvCalo.h
List of Histogram added just once
=> PWGGA: Bugfix: multiple Cutcfgs with PHOS Trigger

PWGCF/FLOW/macros/AddTaskNonlinearFlow.C
change the output file name in order that it can create correct output results when running on the train.
=> change the output file name

PWGHF/vertexingHF/AliAnalysisTaskSEDvsRT.cxx, PWGHF/vertexingHF/macros/AddTaskDvsRT.C
Correct small bug on the settings of the minimum pt for the leading track and filling of the control histogram
=> Correct set of minimum pt for the leading track

PWGCF/Correlations/JCORRAN/Pro/AliJCDijetAna.cxx, PWGCF/Correlations/JCORRAN/Pro/AliJCDijetHistos.cxx, PWGCF/Correlations/JCORRAN/Pro/AliJCDijetHistos.h, PWGCF/Correlations/JCORRAN/Pro/AliJCDijetTask.cxx
Also two new histograms related to checking this cut.
=> Fixed a bug related to jetpt > 4*pthard bin cut

PWGCF/Correlations/DPhi/AliAnalysisTaskV0ChCorrelation.cxx, PWGCF/Correlations/DPhi/AliAnalysisTaskV0ChCorrelationpp.cxx, PWGCF/Correlations/macros/AddTaskV0ChCorrelation.C, PWGCF/Correlations/macros/AddTaskV0ChCorrelationPrei.C, PWGCF/Correlations/macros/AddTaskV0ChCorrelationpp.C
New task only high pt to run on 2015 and 2018 data
=> New task high pt

PWGGA/GammaConv/AliAnalysisTaskOmegaToPiZeroGamma.cxx, PWGGA/GammaConv/AliAnalysisTaskOmegaToPiZeroGamma.h, PWGGA/GammaConvBase/AliConversionMesonCuts.cxx, PWGGA/GammaConvBase/AliConversionMesonCuts.h
- Changed the way rotation background is calculated for rotation around omega 
- Lowered the number of omega p_T bins to be more reasonable and use less memory
- Added OAC for omega mesons
=> PWGGA/GammaConv: OmegaToPiZeroTask - Changed the way rotation background is calculated

PWGHF/treeHF/AliAnalysisTaskSEHFTreeCreator.cxx, PWGHF/treeHF/AliAnalysisTaskSEHFTreeCreator.h, PWGHF/treeHF/AliHFTreeHandlerLbtoLcpi.cxx, PWGHF/treeHF/AliHFTreeHandlerLbtoLcpi.h
=> Adding code to prefilter the Lb to Lc pi candidates (Anastasis)

PWGHF/treeHF/AliAnalysisTaskSEHFTreeCreator.cxx, PWGHF/treeHF/AliHFTreeHandlerLbtoLcpi.cxx, PWGHF/treeHF/AliHFTreeHandlerLbtoLcpi.h
For possible extra selection on Lb variables and background shape study
Follow up of #15560 (8815034) and the reverting of this incomplete commit in #15574
=> PWGHF: Update Lb ITS Upgrade TTreeCreator

PWGCF/FLOW/GF/AliAnalysisTaskNonlinearFlow.cxx, PWGCF/FLOW/GF/AliAnalysisTaskNonlinearFlow.h
Shutdown weight to find why the job fails.
=> Shutdown weight

PWGGA/EMCALTasks/AliAnalysisTaskGammaHadron.cxx
Adds new pi0 mass windows for GA-triggered 15o
=> Adds new pi0 mass windows for pi0-h correlations

PWGCF/Correlations/macros/AddTaskDiHadCorrelHighPt.C
differentiate between InputContainers for different wagons
=> Changes in AddTaskDiHadCorrelHighPt.C

PWGCF/FEMTOSCOPY/macros/Train/JZ/mezonD/ConfigAnalysis.C
Fixed analysis of the invariant mass of D mezon
=> Add config for the analysis

PWGGA/GammaConv/AliAnalysisTaskGammaConvCalo.cxx, PWGGA/GammaConv/macros/AddTask_GammaConvCalo_pp.C, PWGGA/GammaConvBase/AliCaloPhotonCuts.cxx, PWGGA/GammaConvBase/AliCaloPhotonCuts.h
PWGGA/GammaConv adding variable to change m02 ncell threshhold
adding a few Cutsettings
=>  PWGGA/GammaConv adding variable to change m02 ncell threshhold

PWGCF/FEMTOSCOPY/FemtoDream/AliAnalysisTaskPOmegaPenne.cxx, PWGCF/FEMTOSCOPY/FemtoDream/AliAnalysisTaskPOmegaPenne.h, PWGCF/FEMTOSCOPY/macros/AddTaskPOmegaPenne.C
=> PairCleaning for Lam-Lam and for Lam-Xi CF

PWGGA/GammaConv/AliAnalysisTaskElectronStudies.cxx, PWGGA/GammaConv/AliAnalysisTaskElectronStudies.h, PWGGA/GammaConv/macros/AddTask_ElectronStudies.C
changed structure to event based and adjusted types for maximum space saving
=> PWGGA/GammaConv: changed ElectronStudies to event based tree

PWGGA/GammaConv/macros/AddTask_GammaConvDalitzV1_pp.C
=> RBins low B Field, with Two htis on ITS

PWGGA/GammaConv/AliAnalysisTaskElectronStudies.cxx, PWGGA/GammaConv/AliAnalysisTaskElectronStudies.h, PWGGA/GammaConv/AliAnalysisTaskGammaCalo.cxx, PWGGA/GammaConv/AliAnalysisTaskGammaCalo.h, PWGGA/GammaConv/macros/AddTask_ElectronStudies.C, PWGGA/GammaConv/macros/AddTask_GammaIsoTree.C, PWGGA/GammaConvBase/AliCaloPhotonCuts.cxx, PWGGA/GammaConvBase/AliCaloPhotonCuts.h
Note: the function to clean cluster labels is still in development and currently being tested
=> PWGGA/GammaConv: more changes to ElectronStudiesTree + first test version of CleanClusterLabels

PWGJE/EMCALJetTasks/Tracks/AliAnalysisTaskEmcalJetEnergyScale.cxx, PWGJE/EMCALJetTasks/Tracks/AliAnalysisTaskEmcalJetEnergyScale.h
- Adding histogram at detector level (purity) with bins
+ all det jets
+ tagged jets
+ part jet inside det-level acceptance
- Adding histogram at particle level (efficiency) with bins
+ all part jets
+ tagged jets
+ det jet inside part-level acceptance
=> Split jet finding efficiency in efficiency and purity

PWGCF/FEMTOSCOPY/macros/Train/Gleb/PbPb_MC_3d/MC_221/ConfigFemtoAnalysis.C, PWGCF/FEMTOSCOPY/macros/Train/Gleb/PbPb_MC_3d/MC_222/ConfigFemtoAnalysis.C, PWGCF/FEMTOSCOPY/macros/Train/Gleb/PbPb_MC_3d/MC_323/ConfigFemtoAnalysis.C, PWGCF/FEMTOSCOPY/macros/Train/Gleb/PbPb_MC_3d/MC_332/ConfigFemtoAnalysis.C, PWGCF/FEMTOSCOPY/macros/Train/Gleb/PbPb_MC_3d/MC_333/ConfigFemtoAnalysis.C, PWGCF/FEMTOSCOPY/macros/Train/Gleb/PbPb_MC_3d/MC_334/ConfigFemtoAnalysis.C, PWGCF/FEMTOSCOPY/macros/Train/Gleb/PbPb_MC_3d/MC_344/ConfigFemtoAnalysis.C, PWGCF/FEMTOSCOPY/macros/Train/Gleb/PbPb_MC_3d/MC_433/ConfigFemtoAnalysis.C, PWGCF/FEMTOSCOPY/macros/Train/Gleb/PbPb_MC_3d/MC_445/ConfigFemtoAnalysis.C, PWGCF/FEMTOSCOPY/macros/Train/Gleb/PbPb_MC_3d/MC_545/ConfigFemtoAnalysis.C, PWGCF/FEMTOSCOPY/macros/Train/Gleb/PbPb_MC_3d/MC_556/ConfigFemtoAnalysis.C, PWGCF/FEMTOSCOPY/macros/Train/Gleb/PbPb_MC_3d/MC_655/ConfigFemtoAnalysis.C, PWGCF/FEMTOSCOPY/macros/Train/Gleb/PbPb_MC_3d/MC_657/ConfigFemtoAnalysis.C
=> LegoTrain Glebs macros 25 sept 2020

PWGDQ/dielectron/core/AliDielectronMC.cxx, PWGDQ/dielectron/core/AliDielectronMC.h, PWGDQ/dielectron/core/AliDielectronSignalMC.h, PWGDQ/dielectron/core/AliDielectronVarManager.cxx, PWGDQ/dielectron/core/AliDielectronVarManager.h
Legpt in AliVarManager + FinalStateFromPileUp and FinalStateFromNoPileUp in AliDielectronSignalMC
=> Legpt in AliVarManager + FinalStateFromPileUp and FinalStateFromNoPileUp in AliDielectronSignalMC

PWGHF/vertexingHF/AliAnalysisTaskSELc2pKs0fromKFP.cxx
=> delete vHF after using it

PWGCF/Correlations/DPhi/AliAnalysisTaskSEpPbCorrelationsJetV2.cxx
Hi,
Here is an update for jet v2 analysis code. Please check it. Thanks!
Best regards,
Siyu
=> Put FMD cut in TPCTPC

PWGLF/RESONANCES/PostProcessing/f0980/AliAnalysisTaskInclusivef0f2.cxx, PWGLF/RESONANCES/PostProcessing/f0980/AliAnalysisTaskInclusivef0f2.h
Updates for TOF PID mis-match switch
=> [PWGLF] updates for TOF PID mis-match

PWG/MCLEGO/ALIGENMC/gen.sh, PWG/MCLEGO/AddMCGenAliGenMC.C
- Add steering macro configuring AliGenExtExec
- Energy, generator, packages, ... passed to
aligenmc as AliGenExtExec optional argument
- Add run script for aligenmc
- Number of events accessed via
SPLIT_MAX_INPUT_FILE_NUMBER
=> Add support for algenmc-based generators in MCgen train

RUN3/AliAnalysisTaskAO2Dconverter.cxx, RUN3/AliAnalysisTaskAO2Dconverter.h
=> reassigning flags and adding golden chi2

PWGGA/GammaConv/AliAnalysisTaskGammaCalo.cxx, PWGGA/GammaConv/AliAnalysisTaskGammaConvCalo.cxx, PWGGA/PHOSTasks/ClusterSelection/AliCaloTriggerMimicHelper.cxx, PWGGA/PHOSTasks/ClusterSelection/AliCaloTriggerMimicHelper.h
Also add information, which ddls were bad and reduce amount of histograms in trigger helper
=> PWGGA: Always use fHistoGoodMesonClusters, when phos trigger is used

PWGHF/hfe/AliAnalysisTaskHFEBESpectraEMC.cxx
Increasing the number of bins from 40 to 160 for E/p in the electron THnsparse
=> Increasing Nbins for E/p in Thnsparse

PWGLF/SPECTRA/ChargedHadrons/dNdPt/Framework/AliAnalysisTaskMKBase.cxx, PWGLF/SPECTRA/ChargedHadrons/dNdPt/Framework/AliAnalysisTaskMKBase.h, PWGLF/SPECTRA/ChargedHadrons/dNdPt/Framework/AliAnalysisTaskSpectraEtaPhi.cxx, PWGLF/SPECTRA/ChargedHadrons/dNdPt/Framework/AlidNdPtTools.h
=> Charged Particle Spectra

PWGHF/vertexingHF/AliAnalysisTaskSELc2pKs0fromKFP.cxx
remove AODv0 and AODcascade check
=> remove AODv0 and AODcascade check

PWGGA/GammaConv/AliAnalysisTaskElectronStudies.cxx, PWGGA/GammaConv/AliAnalysisTaskElectronStudies.h, PWGGA/GammaConv/AliAnalysisTaskGammaCalo.cxx, PWGGA/GammaConv/AliAnalysisTaskGammaCalo.h, PWGGA/GammaConvBase/AliCaloPhotonCuts.cxx
-  additional quantities added to ElectronStudies tree
- some fixes for running over ESD with GammaCalo task
=> PWGGA/GammaConv: additional quantities added to ElectronStudies tree

PWG/EMCAL/EMCALtasks/AliEmcalCorrectionTask.cxx, PWG/EMCAL/config/AliEmcalCorrectionConfiguration.yaml
- Added option to directly apply exotics as flagged by the ClusterExotics component on the clusters
=> PWG/EMCAL: Added option to apply exotics cut on clusters directly

PWGGA/GammaConv/macros/AddTask_GammaConvCalo_pp.C
changing PCM-EDC pp 13 Tev cuts MB, adding trigger cuts and changing lowb cuts
=> PWGGA/GammaConv changing PCM-EDC pp 13 Tev cuts

PWGPP/ZDC/macros/DrawPerformanceZDCQAMatch.C, PWGPP/ZDC/macros/DrawPerformanceZDCQAMatchTrends.C
Changes requested to avoid saving some files (plots) for productions where the ZDC is not switched on...
chiara
=> Changes requested by QA experts in ZDC QA trending code

PWGCF/FEMTOSCOPY/FemtoDream/AliAnalysisTaskPOmegaPenne.cxx, PWGCF/FEMTOSCOPY/FemtoDream/AliAnalysisTaskPOmegaPenne.h, PWGCF/FEMTOSCOPY/macros/AddTaskPOmegaPenne.C
*minor runtime fix in creating one vector each for userExec
=> removed second set of cuts

PWGJE/EMCALJetTasks/Tracks/AliAnalysisTaskEmcalJetSpectrumSDPart.cxx, PWGJE/EMCALJetTasks/macros/AddTaskEmcalJetSpectrumSDPart.C
=> Several fixes for the part. jet task in order to run on the MCgen train

PWGDQ/dielectron/core/AliAnalysisTaskTagAndProbe.cxx, PWGDQ/dielectron/core/AliAnalysisTaskTagAndProbe.h, PWGDQ/dielectron/macrosLMEE/AddTask_dsekihat_TAP_PbPb.C, PWGDQ/dielectron/macrosLMEE/Config_dsekihat_TAP_PbPb.C
=> PWGDQ/LMEE: update PID eff task with DDA

PWGDQ/dielectron/core/AliAnalysisTaskTagAndProbe.cxx, PWGDQ/dielectron/core/AliAnalysisTaskTagAndProbe.h
=> PWGDQ/LMEE: quick fix to used vars

PWGGA/GammaConv/AliAnalysisTaskGammaCalo.cxx, PWGGA/GammaConv/AliAnalysisTaskGammaConvCalo.cxx, PWGGA/PHOSTasks/ClusterSelection/AliCaloTriggerMimicHelper.cxx, PWGGA/PHOSTasks/ClusterSelection/AliCaloTriggerMimicHelper.h, PWGGA/PHOSTasks/ClusterSelection/AliPHOSTriggerUtils.h
ClusE vs Timing for each TRU
Distance for TRU patches
=> PWGGA: Add Histograms for trigger checks in PHOS

PWGCF/Correlations/DPhi/AliAnalysisTaskSEpPbCorrelationsJetV2.cxx, PWGCF/Correlations/DPhi/AliAnalysisTaskSEpPbCorrelationsJetV2.h, PWGCF/Correlations/macros/pPbCorrelations/AddTaskpPbCorrelationsJetV2.C
Hi,
Here is an update for 2-D fit of v2 distribution in Jet v2 analysis.
Thanks!
Siyu
=> Add 2D fit

PWGGA/GammaConv/AliAnalysisTaskGammaConvV1.cxx, PWGGA/GammaConvBase/AliConvEventCuts.cxx
for LHC20g10: add posibility to find MB header
at other posistion than 0
also add a few todos
=> PWGGA/GammaConv: add MB header for LHC20g10

PWGDQ/dielectron/core/AliAnalysisTaskTagAndProbe.cxx, PWGDQ/dielectron/core/AliAnalysisTaskTagAndProbe.h
=> PWGDQ/LMEE: reduce unnecessary histos

PWGDQ/dielectron/macrosLMEE/AddTask_dsekihat_Run3_benchmark.C, PWGDQ/dielectron/macrosLMEE/Config_dsekihat_Run3_benchmark.C, PWGDQ/dielectron/macrosLMEE/LMEECutLib_dsekihat_Run3_benchmark.C
=> PWGDQ/LMEE: add macros for Run3 benchmark

RUN3/AliAnalysisTaskAO2Dconverter.cxx, RUN3/AliAnalysisTaskAO2Dconverter.h
Introduction of time frames in Root sub-directories.
Cleanup and reordering.
=> Introduction of time frames in Root sub-directories.

PWGHF/vertexingHF/AliAnalysisTaskSEXicTopKpi.cxx, PWGHF/vertexingHF/AliAnalysisTaskSEXicTopKpi.h
Possibility to disable it (e.g. when running on upgrade MC)
=> Add flag for ev. selection in MC

PWGCF/FEMTOSCOPY/FemtoDream/AliAnalysisTaskPOmegaPenne.cxx, PWGCF/FEMTOSCOPY/FemtoDream/AliAnalysisTaskPOmegaPenne.h
* minor fix: more stats, less runtime
=> removed memory leak

PWGCF/Correlations/JCORRAN/Base/jtAnalysis/AliJDiHadronJtTask.cxx, PWGCF/Correlations/JCORRAN/Base/jtAnalysis/AliJDiHadronJtTask.h, PWGCF/Correlations/JCORRAN/Base/jtAnalysis/AliJJtAna.cxx, PWGCF/Correlations/JCORRAN/Base/jtAnalysis/AliJJtAna.h, PWGCF/Correlations/JCORRAN/Base/jtAnalysis/AliJJtAnalysis.cxx, PWGCF/Correlations/JCORRAN/Base/jtAnalysis/AliJJtAnalysis.h, PWGCF/Correlations/JCORRAN/Base/jtAnalysis/AliJJtCorrelations.cxx, PWGCF/Correlations/JCORRAN/Base/jtAnalysis/AliJJtCorrelations.h, PWGCF/Correlations/JCORRAN/Base/jtAnalysis/AliJJtHistograms.cxx, PWGCF/Correlations/JCORRAN/Base/jtAnalysis/AliJJtHistograms.h, PWGCF/Correlations/JCORRAN/Base/jtAnalysis/AliJJtTask.cxx, PWGCF/Correlations/JCORRAN/Base/jtAnalysis/AliJJtTask.h
This caused problem on the grid side when running. Local running was still ok.
=> Fixed a problem with folder specific includes.

PWGDQ/dielectron/core/AliAnalysisTaskTagAndProbe.cxx, PWGDQ/dielectron/core/AliAnalysisTaskTagAndProbe.h
=> PWGDQ/LMEE: update eID for TAP

PWGDQ/dielectron/macrosLMEE/AddTask_dsekihat_Run3_benchmark.C, PWGDQ/dielectron/macrosLMEE/Config_dsekihat_Run3_benchmark.C, PWGDQ/dielectron/macrosLMEE/LMEECutLib_dsekihat_Run3_benchmark.C
=> PWGDQ/LMEE: update for Run3 benchmark

PWGDQ/dielectron/macrosLMEE/AddTask_rbailhac_ElectronEfficiencyV2_PbPb.C, PWGDQ/dielectron/macrosLMEE/AddTask_rbailhac_lowmass_PbPb.C
Adapt for different pile-up rejection.
=> Adapt for different pile-up rejection

PWGHF/hfe/AliAnalysisTaskTPCCalBeauty.cxx, PWGHF/hfe/AliAnalysisTaskTPCCalBeauty.h, PWGHF/hfe/macros/AddTaskTPCCalBeauty.C
Also added 2D histo of DCAz versus DCAxy.
=> Added ability to change DCAxy, DCAz, and VtxZ cut

PWGDQ/dielectron/macrosLMEE/AddTask_rbailhac_ElectronEfficiencyV2_PbPb.C
Adapt macro to run with different event selection for pile-up
=> Adapt to run with different event selection for pile-up

PWGGA/GammaConv/AliAnalysisTaskGammaConvCalo.cxx, PWGGA/GammaConv/AliAnalysisTaskGammaConvCalo.h, PWGGA/PHOSTasks/ClusterSelection/AliCaloTriggerMimicHelper.cxx
=> PWGGA:  Add ClusGammaE Histograms for only triggered clusters
