PWGHF/jetsHF/AliAnalysisTaskBJetTC.cxx, PWGHF/jetsHF/AliAnalysisTaskBJetTC.h, PWGHF/jetsHF/AliAnalysisTaskIPCalib.cxx, PWGHF/jetsHF/AliAnalysisTaskIPCalib.h, PWGHF/jetsHF/macros/AddTaskBJetTC.C, PWGHF/jetsHF/macros/AddTaskIPCalib.C
A new method for correcting the IPs has been implemented into the b-jet tagging code. With changing the format of the code.
=> Implementing the IPs correction into the analysis code

PWGGA/CaloTrackCorrelations/AliAnaParticleIsolation.cxx, PWGGA/CaloTrackCorrelations/AliAnaParticleIsolation.h
Not needed since compressed on recent TH3 or can be executed calling isolation component with different cone settings via the configuration macro
=> [PWGGA/CaloTrackCorr] Remove old/obsolete code/options

PWGDQ/dielectron/macrosLMEE/Config_hdegenhardt_pp.C
For systematic uncertainties 3D histos are lighter than normal analysis with THnSparse histos. Fixing 3D histos for systematic uncertainties on DCA analysis
=> Fixing histo limits (DCA analysis)

PWG/EMCAL/EMCALtrigger/AliEmcalTriggerMakerKernel.cxx, PWG/EMCAL/EMCALtrigger/AliEmcalTriggerMakerKernel.h
Simulation of the energy-independent EMCAL
energy scale mismatch between data and MC
using constant mulitplicator applied to
the FEE amplitude when converting to FastOR
energy.
=> Add option for energy scale multiplicator

ML/AliMLResponse.cxx, ML/AliMLResponse.h
This should fix the issue spotted by @lvermunt where there are crashes for candidates with pT above the last value defined in the config file. Moreover, the candidates falling in the last defined bin were rejected.
@pfecchio @mpuccio @fgrosa Please double check.
=> Fix ML model choice in prediction

PWGJE/EMCALJetTasks/UserTasks/AliAnalysisTaskJetHardestKt.cxx
Without this change, a constituent could be counted twice during subjet
distance matching, which could cause the pt fraction to be greater than
1 (beyond just float rounding)
=> Avoid double counting of subjet constituents for matching

PWGJE/FlavourJetTasks/AliAnalysisTaskHFJetIPQA.cxx, PWGJE/FlavourJetTasks/AliAnalysisTaskHFJetIPQA.h, PWGJE/FlavourJetTasks/macros/AddTaskHFJetIPQA.C
Track Probability:
- widen definition of track probability to all tracks within jet
- introduce cut on maximum IP
- introduce handling of boundary effects
- enable reading of more than 3 IP templates
Basic Code:
- tidy up
- add print of all tree variables
- decrease array size in output tree
- rearrange initialisation of loop variables
=> AliAnalysisTaskHFJetIPQA: expand definition of track probability

PWGDQ/dielectron/core/AliAnalysisTaskEtaReconstruction.cxx, PWGDQ/dielectron/core/AliAnalysisTaskEtaReconstruction.h, PWGDQ/dielectron/macrosLMEE/AddTask_feisenhut_EtaReconstruction.C, PWGDQ/dielectron/macrosLMEE/Config_feisenhut_EtaReconstruction.C, PWGDQ/dielectron/macrosLMEE/LMEECutLib_feisenhut.C
, switch Dalitz or GammaGamma Methode
The commit consits of further cuts to identify secondaries from gamma conversions, as well a switch which is included to switch between the two implemented analysis methods (Dalitz / GammaGamma reconstruction)
=> PWGDQ EtaReconstruction implemented further secondary cuts

PWGHF/treeHF/AliHFTreeHandler.cxx, PWGHF/treeHF/AliHFTreeHandler.h
add two additional PID options for the tree 
1. Include Bayesian PID variables
2. Include Bayesian and Nsigma variables
Currently the implementation includes default priors, and combines information from the TPC and TOF to calculate the Bayesian probabilities for each track to be a proton, kaon or pion.
=> add option to include bayesian PID in tree

PWGHF/vertexingHF/AliRDHFCutsLctopKpi.cxx
Spotted this typo/bug in previous PR where I added the PreSelect function, but forgot to actually fix it
=> PWGHF: Typo fix in CombinedSoft PID strategy

PWGPP/AliPIDtools.cxx
```
singularity> grep "Invalid write " -A 5 /lustre/nyx/alice/users/xbai/work/SkimmedDataAna/Run18/TPCsplines/xxx.txt 
==13505== Invalid write of size 8 
==13505==    at 0x26ECEE7A: SetEventPileupProperties (AliTPCPIDResponse.h:247) 
==13505==    by 0x26ECEE7A: AliPIDtools::SetPileUpProperties(TVectorT<float> const&, TVectorT<float> const&, int, AliTPCPIDResponse*) (AliPIDtools.cxx:277) 
==13505==    by 0x26ECFFF6: AliPIDtools::GetExpectedTPCSignalV0(int, int, int, int, int) (AliPIDtools.cxx:245) 
```
=> PWGPP-538 - query  and SetPileUpProperties only in case of pileup  enabled

PWGJE/EMCALJetTasks/CMakeLists.txt, PWGJE/EMCALJetTasks/PWGJEEMCALJetTasksLinkDef.h, PWGJE/EMCALJetTasks/Tracks/AliAnalysisEmcalSoftdropHelper.cxx, PWGJE/EMCALJetTasks/Tracks/AliAnalysisEmcalSoftdropHelper.h, PWGJE/EMCALJetTasks/Tracks/AliAnalysisTaskEmcalSoftDropData.cxx, PWGJE/EMCALJetTasks/Tracks/AliAnalysisTaskEmcalSoftDropData.h, PWGJE/EMCALJetTasks/Tracks/AliAnalysisTaskEmcalSoftDropResponse.cxx, PWGJE/EMCALJetTasks/Tracks/AliAnalysisTaskEmcalSoftDropResponse.h
- Common base class to have code calculating the SoftDrop
parameters Zg, Rg, Nsd ... and include it via multiple
inheritance into classes for data and response (safe is safe)
- Use struct instead of vector for softdrop results and
softdrop params
- Outsource QA code that was inside MakeSoftdrop into
separate functions so that MakeSoftdrop does not rely
on dedicated class implementation and can be outsourced
- For casting from float to double in case of jet R use
safe implementation truncating after the 3rd decimal
digit (for jet R better precision is not needed)
- Force one overflow bin for Rg histograms instead of
having it implicitly due to imprecise cast.
=> Combine SoftDrop code into helper base class for data and response

PWGLF/STRANGENESS/HeavyIonsRun1Run2/AliAnalysisTaskStrVsMult.cxx, PWGLF/STRANGENESS/HeavyIonsRun1Run2/AliAnalysisTaskStrVsMult.h, PWGLF/STRANGENESS/HeavyIonsRun1Run2/macros/AddTaskStrVsMult.C
Fixes:
- correct charge selection for cascades 
- boundaries and standard values of the cut variation are fixed for some variables
- remove warning due to the initialization of the data member  fV0_kinkidx
=> Add trigger selection and other fixes

PWGPP/AliAnalysisTaskFilteredTree.cxx, PWGPP/AliAnalysisTaskFilteredTree.h, PWGPP/AliPIDtools.cxx, PWGPP/AliPIDtools.h, PWGPP/TPC/macros/performanceFiltered.C
PWGPP-538 - set event properties and correction mask (enum) in NSigma
PWGPP-538 - update doc
PWGPP-538 - reset PID correction mask
PWGPP-538 - set /reset switches
PWGPP-312 - use only selectionPTMask tracks
PWGPP-538 - set default aliases for PID AliAnalysisTaskFilteredTree::SetDefaultAliasesV0PID
=> PWGPP-538 - set event properties and correction mask (enum) in NSigma

RUN3/AliAnalysisTaskAO2Dconverter.cxx, RUN3/AliAnalysisTaskAO2Dconverter.h
This PR adds a centrality histogram while converting ESD to AO2D files. The histogram is written in the AO2D.root file in the container QAlist. The centrality method can be selected in the conversion task by calling SetCentralityMethod(const char *method), the default value being "V0M". The multiplicity task becomes mandatory in the conversion train.
=> Added centrality QA plot for AO2D conversion.

PWGPP/AliPIDtools.cxx, PWGPP/AliPIDtools.h
````
/// \param hash           - hash value of PID correction
/// \param detCode        - detector code (0-ITS, 1-TPC, 2-TRD, 3-TOF)  AliPIDResponse::enum EDetector
/// \param particleType   - see enum
/// \param source         - track index
/// \param corrMask       - correction bitMask - AliPIDTools:: enum TPCCorrFlag
/// \return
Float_t AliPIDtools::GetSignalDelta(Int_t hash, Int_t detCode, Int_t particleType, Int_t source, Int_t corrMask){
````
* in case of the tree and event tree not properly initialized - print meassage
* automatically set trees in case of change of input  trees
=> PWGPP-538 - Exception handling - adding test/checks of track and event GID

OADB/macros/BrowseAndFillPhysicsSelectionOADB.C
EMCAL jet trigger in 2012 spelled "EJE" instead of EJA.
EMC8-based triggers handled correctly.
=> Typo fix: for EMCAL jet trigger in EMC7 suite in 2012

PWGHF/vertexingHF/AliAnalysisTaskSEXicZero2XiPifromKFP.cxx
Fix a bug in definition of tree branch using option "F" instead of "f"
=> Fix a bug in definition of tree branch using option "F" instead of "f"

PWGHF/vertexingHF/macros/ComputeBtoDdecay.C
- pt dependent fragmentation fractions from LHCb measurement  - https://arxiv.org/pdf/1902.06794.pdf
- Uses fits defined in this paper to parameterise fragmentation fraction as a function of the beauty hadron pT, plus flat FF for pT<5
- minimum and maximum FF uncertainties are from the envelope of parameter variations
- includes option for 5 TeV for additional uncertainty taking into account possible difference in FF between 13 TeV and 5 TeV measurements
See D2H presentation for details: https://indico.cern.ch/event/922573/contributions/3925508/attachments/2066201/3467564/Fragmentation_Spectra_D2H.pdf
=> add pt-dependent Lb fragmentation

PWGPP/AliPIDtools.cxx, PWGPP/AliPIDtools.h
```
/// Return Compute probability
/// \param hash           - hash value of PID correction
/// \param detCode        - detector code (0-ITS, 1-TPC, 2-TRD, 3-TOF)  AliPIDResponse::enum EDetector
/// \param particleType   - see enum
/// \param source         - track index
/// \param corrMask       - correction bitMask - AliPIDTools:: enum TPCCorrFlag
/// \param norm           - include normalization to all species
/// \param fakeProb       -  user defined fake probability (normaly scales with mult*(1+1/pt))  - detector dependent
/// \return
Float_t AliPIDtools::ComputePIDProbability(Int_t hash, Int_t detCode, Int_t particleType, Int_t source, Int_t corrMask,Int_t norm,Float_t fakeProb){
````
=> PWGPP-545 - AliPIDtools::ComputePIDProbability with user defined  fake 

PWGPP/AliPIDtools.cxx, PWGPP/AliPIDtools.h
```
static Float_t ComputePIDProbabilityCombined(Int_t hash, Int_t detMask, Int_t particleType, Int_t source=-1, Int_t corrMask=-1,Int_t norm=1, Float_t fakeProb=0.01);
/// \param hash               - index of PID
/// \param detMask            - det mask as in AliPID
/// \param particleType       - particle type
/// \param source             -
/// \param corrMask           - corr mask for TPC only
/// \param norm               - flag - normalization
/// \param fakeProb           - fake probability  ( used for  normalization)
/// \return
```
* testing internal consistency of wrappers
* to be extended for V0 trees
* trees to be initialized before UnitTest
```
root [8] AliPIDtools::UnitTest()
I-UnitTest: AliPIDtools::GetTOFInfoAt(1,2)-tofNsigma.fElements[2]       Status=1
I-UnitTest: …
```
=> PWGPP-545 - AliPIDtools::UnitTest+AliPIDtools::ComputePIDProbabilityCombined

PWGPP/AliPIDtools.cxx
Used for clean sample preparation
Example query:
* Draw nSigma1_5 (TPC, Deuteron) as function of 1/momentum
* using cut on combined PID likelihood of ITS +TOF >0.1 (probC03_5>0.1)
and normalized PID ITS+TOF likelihood >0.6   (probCN03_5>0.6)
```
tree->Draw("nSigma1_5:1/esdTrack.fIp.P()>>his(40,0,4,100,-6,6)","ITSRefit&&esdTrack.fTPCsignalN>80&&probC03_5>0.1&&probCN03_5>0.6&&selectionPIDMask!=2","colz",40000)
```
=> PWGPP-545 - updates RegisterPIDAliases

PWGPP/AliAnalysisTaskFilteredTree.cxx, PWGPP/AliPIDtools.cxx
* possibility to calibrate TOF  and for ML
* before it was implemented only for the track trees
* or TOF we have to use NSigma stored in tree - can not used esdTrack
* previous  algorithm working only for the track tree not for V0 tree
* by mistake trackLength not intilized in V0s - fixed in  trackLegth fix above
=> PWGPP-545, ATO-465 - adding TOF track length to streamer also for V0s

PWG/EMCAL/EMCALtrigger/AliEmcalTriggerMakerKernel.cxx, PWG/EMCAL/EMCALtrigger/AliEmcalTriggerMakerKernel.h, PWG/EMCAL/READMEtrgfw.txt
Noise is simulated FastOR-by-FastOR and event-by-event,
applied only to fastOR signal calculated from smeared FEE
singal. Two models are available:
- constant noise
- gaussian noise
=> Add noise simulation to the trigger maker

PWGPP/AliAnalysisTaskFilteredTree.cxx, PWGPP/AliPIDtools.cxx, PWGPP/AliPIDtools.h, PWGPP/TPC/macros/performanceFiltered.C
* AliAnalysisTaskFilteredTree.cxx
* setting proper alias for expected dEdx
* AliPIDtools.cxx
* set default Probability to 0.2 in case detectors are not responding
* AliAnalysisTaskFilteredTree.cxx
* adding aliases to calculate alpha and sector position in middle of IROC
* performanceFiltered.C
* modifying defaultCut for matching studies - pt dependent NCR cut
```
TString defaultCutMatch="esdTrack.GetTPCClusterInfo(3,1)>110-abs(qPt)*10&&selectionPtMask>0&&normChi2TPC<4";
```
* adding histograms with dSectorM, alphaM for all existing 
* adding histograms with logTracks5 for matching histograms (missing before)
=> PWGPP-545, ATO-465, PWGPP-312 - adding dSectorM and AlphaM histograms (position at middle of IROC)

RUN3/AliAnalysisTaskAO2Dconverter.cxx
The logic is: if no cuts are requested, AcceptEvent is not called at all, otherwise it is called systematically. The result of AcceptEvent is directly used in case SetUseEventCuts or SetSkipPileup were set and the event does not pass cuts (or does not pass the pileup cut respectively). If SetSkipTPCPileup is set, the result of AcceptEvent is not used, but the QA histogram counting TPC pileup events is filled.
=> Avoid calling the event cuts if no cuts requested

PWGJE/EMCALJetTasks/Tracks/AliAnalysisTaskEmcalClustersRef.cxx, PWGJE/EMCALJetTasks/Tracks/AliAnalysisTaskEmcalTriggerBase.cxx, PWGJE/EMCALJetTasks/Tracks/AliAnalysisTaskEmcalTriggerBase.h
- Add trigger alsiases to trigger selection task
- Add handling for downscaling as max of EMCAL or DCAL
as max of the two (corresponding to max lumi)
- Fill max. cluster THnSparse for combined trigger only
once with the maximum of either EMCAL or DCAL trigger,
axis 1 shows in which subdetector the max has been found
- Fix energy comparison for max cluster selection
=> Add support for combined triggers (EMCAL or DCAL)

PWGPP/AliAnalysisTaskFilteredTree.cxx, PWGPP/AliPIDtools.cxx, PWGPP/AliPIDtools.h
define "likelihood" for clean PID selection in first round of calibration
(later ML technique plan be used)
* V0 likelihood
* defined in other place
* likelihod - combined PID for complementary track
* likelihood - combined PID for track except of detectro of interest
```
/// RegisterPIDAliasesV0 - to selec clean PID samples using V0 likelihood and PID selection on the leg
/// \param pidHash     - PID hash identifier
/// \param powerLike   - power for the V0 likelihood - default 0.6
/// \param powerLegN   - power leg for second track
/// \param powerLeg    - power leg for signal track
/// \param fakeRate    - fake rate query
/// \param suffix      - suffix to add
/// \return
Bool_t    AliPIDtools::RegisterPIDAliasesV0(Int_t pidHash, Float_t powerLike, Float_t powerLegN, Float_t powerLeg, …
```
=> PWGPP-545, ATO-465 -"naive likelihood" combining V0+ detector PID + AliPIDtools bug fix

PWGCF/FEMTOSCOPY/FemtoDream/AliAnalysisTaskNanoLD.cxx, PWGCF/FEMTOSCOPY/FemtoDream/AliAnalysisTaskNanoLD.h, PWGCF/FEMTOSCOPY/macros/AddTaskFemtoNanoLD.C
o Can now be completely deactivated (0), use default settings (1)
or include proton-lambda cleaning (2)
o in addition, activate close pair rejection for subwagon 2
=> FemtoNanoLD: add flexiblity for pair cleaner

PWGGA/GammaConvBase/AliConvEventCuts.h
These histos need to be streamed since they are being
initialized within AliConvEventCuts::InitCutHistograms
which appears to be run before the distribution on
grid nodes.
=> PWGGA/GammaConv: fix streaming property of two histos

PWGCF/FEMTOSCOPY/AliFemto/AliFemtoFsiWeightLednicky.F, PWGCF/FEMTOSCOPY/AliFemto/AliFemtoModelWeightGeneratorLednicky.cxx
Exchanging old FORTRAN code with new one obtained from Lednicky, including new code for baryons.
The obtained FORTRAN code was not swapped directly but also corrected to meet proper programming practices (e.g. proper assignment of values in arrays, corrections to COMMON blocks, etc.). 
Several tests of the code were performed. The code works well for kaons and protons, but strong FSI for pions produces strange shapes (only QS and Coulomb options should be used for pion-pion pairs).
Also, AliFemtoModelWeightGeneratorLednicky.cxx file was modified, so that it allows to set by hand particle types in the pair.
=> AliFemto: significant changes to FsiWeightLednicky fortran code

PWGGA/GammaConv/AliAnalysisTaskGammaIsoTree.cxx
introduced this check to catch photons that do not have a mother. This should normally not happen within Pythia, however it happens when running with DPMJet MC sometimes for some reason
=> PWGGA/GammaConv: GammaIsoTree added additional MC check

PWGPP/AliAnalysisTaskFilteredTree.cxx, PWGPP/AliAnalysisTaskFilteredTree.h, PWGPP/AliPIDtools.cxx, PWGPP/TPC/macros/performanceFiltered.C
* muon and pions above 200 MeV difficult to disentangle - makes species pion or muon
* used in tree queries in AliPIDtools
* using weight not need to keep back compatibility in functions
* original spectra should be possible to extract using weights stored in trees 
* procedure to extract original spectra to be crosschecked with MB trigger
=> ATO-465 - adding probability/weights to the tree - to recover  spectras without downsampling

PWGHF/vertexingHF/AliCFTaskVertexingHF.cxx
Clean up some pointer assignments within RT calculation function in AliCFTaskVertexingHF to avoid possible memory leaks with kRT option.
=> fix possible memory leaks in kRT option in D2H CF task

PWGJE/EMCALJetTasks/Tracks/AliAnalysisTaskEmcalClustersRef.cxx, PWGJE/EMCALJetTasks/Tracks/AliAnalysisTaskEmcalJetEnergySpectrum.cxx, PWGJE/EMCALJetTasks/Tracks/AliAnalysisTaskEmcalJetEnergySpectrum.h
In addition
- Remove duplicated trigger cluster enum
- Fix assignment of max cluster in case of EDCAL triggers
and only clusters in one of the two subdetectors
=> Add option for run1 runrange in trending plots

PWGHF/vertexingHF/AliCFTaskVertexingHF.cxx
Addresses memory leak in kRT case of AliCFTaskVertexingHF - some orphaned pointers that weren't being cleaned up properly during the CalculateRTVal() function.
=> Clean up more leaky pointers in AliCFTaskVHF

PWG/FLOW/Tasks/AliAnalysisTaskTwoMultiCorrelations.cxx, PWG/FLOW/Tasks/AliAnalysisTaskTwoMultiCorrelations.h, PWGCF/FLOW/macros/AddTaskTwoMultiCorrelations.C
* Modify the task to not need external input of the centrality bins, using arrays of histograms and profiles.
* Add some configuration profiles.
* Add the AddTask to use the LEGO trains.
* Add option to compute some multiparticle correlators with 8 and 10 particles.
=> [PWG-CF] Add arrays for centrality bins

RUN3/AliAnalysisTaskAO2Dconverter.cxx, RUN3/AliAnalysisTaskAO2Dconverter.h
- Corrected TList navigation in case of cocktail generator;
- Arrays fMother[2] and fDaughter[2] replaced by individual columns
fMother0,1 and fDaughter0,1;
- Additional column for the impact parameter from MC. Implemented for
headers that inherit from AliCollisionGeometry.
=> Changes in the MC collision and MC particle:

PWGHF/vertexingHF/vHFML/AliAnalysisTaskSEHFTreeCreatorApply.h
Bug/typo fix. 
When the event ID was large, the ID was stored differently in the event properties TTree and the reconstructed HF candidate TTree due to Int_t vs UInt_t. When matching both TTrees at Pandas dataframe level, this mismatch rejected ~50% of the candidates
(not sure about classdef)
=> PWGHF: Event ID bug fix TTreeCreatorApply

PWGGA/GammaConv/AliAnalysisTaskGammaIsoTree.cxx
This is a workaround to avoid crashes when the RhoTask is not found, which happens for some of LHC12 data periods. The crashes need to be further investigated, however rho is not really used at this stage so this workaround lets me at least get other output for now.
=> PWGGA/GammaConv: GammIsoTree workaround for RhoTask problem in data

PWGCF/FEMTOSCOPY/FemtoDream/AliAnalysisTaskGeorgiosNTuple.cxx
Changing the selection criteria to events with at least two Lambdas in order to study Lambda-Lambda correlations
=> Changing to Lambda Lambda

PWGLF/SPECTRA/ChargedHadrons/MultDepSpec/AliMultDepSpecAnalysisTask.h, PWGLF/SPECTRA/ChargedHadrons/MultDepSpec/AliMultDepSpecAnalysisTaskUE.cxx, PWGLF/SPECTRA/ChargedHadrons/MultDepSpec/AliMultDepSpecAnalysisTaskUE.h, PWGLF/SPECTRA/ChargedHadrons/MultDepSpec/macros/AddTask_mkrueger_MultDepSpecUE.C, PWGLF/SPECTRA/ChargedHadrons/MultDepSpec/macros/AddTask_mkrueger_MultDepSpecUEMC.C
This task adds the possibility to study the Underlying Event region in Events selected equivalently to the alimultdepspec base task.
- Find highest pT track (leading track) and define UE region relative to leading track in phi region
- Study the same observables defined in alimultdepspec base task
- Additionally look at leading track properties and study the difference between MC particle and track
=> PWGLF/SPECTRA: alimultdepspec UE functionality

PWGCF/FLOW/GF/AliAnalysisTaskMeanPtV2Corr.cxx, PWGCF/FLOW/GF/AliAnalysisTaskMeanPtV2Corr.h
Fixed setters for pt and multi bins (apparently, simple arrays cannot be stored). Also, added eta selection for mean pt
=> Work on AliAnalysisTaskMeanPtV2 

PWGLF/RESONANCES/AliRsnMiniAnalysisTask.cxx, PWGLF/RESONANCES/AliRsnMiniAnalysisTask.h, PWGLF/RESONANCES/macros/mini/AddAnalysisTaskLStar_PbPb2018.C
This PR adds to the RSN analysis package the possibility to use `TimeRangeCut` event cuts.
The use of this extra cut is driven by a flag that can be set by the user via `AliRsnMiniAnalysisTask::SetUseTimeRangeCut`.
The default is `kFALSE` and the cut is not applied.
This development is useful to add those runs (8 runs in LHC18r) that are flagged by the DPG as being bad for TPC PID.
> 8 runs, 296749, 296750, 296849, 296890, 297029, 297194, 297219, 297481 have been excluded from lists including TPC, because they are bad for TPC PID due to a problem in the gain in one or two sectors. This problem happens at the end of the run: by excluding the problematic time range, the remaining events can be used for PID analyses.
The Lambda(1520) add-analysis-task macro is updated to make use of this …
=> Rdev rsn timerangecut

PWGLF/RESONANCES/macros/mini/AddAnalysisTaskLStar_PbPb2018.C
If negative `nMix` use binned event mixing instead of the default continuous.
=> Update Lambda(1520) to allow for continuous/binned mixing

PWGLF/SPECTRA/PiKaPr/TPC/rTPC/AliAnalysisTaskSpectraRT.cxx, PWGLF/SPECTRA/PiKaPr/TPC/rTPC/AliAnalysisTaskSpectraRT.h
The nSigma of electrons was added to measure the contamination on thee kaons and protons at low pT
=> nSigma of electrons

PWGCF/FEMTOSCOPY/FemtoDream/AliAnalysisTaskGeorgiosNTuple.cxx, PWGCF/FEMTOSCOPY/FemtoDream/AliAnalysisTaskGeorgiosNTuple.h, PWGCF/FEMTOSCOPY/macros/AddTaskGeorgiosNTuple.C
- switch between MC and data via ifdef (currently MC is activated)
- exclusion of the mass, eta and phi branches to reduce disk space usage
=> Easy switch between MC and data and lowering disk space usage

PWGLF/RESONANCES/AliRsnMiniAnalysisTask.cxx, PWGLF/RESONANCES/AliRsnMiniOutput.cxx, PWGLF/RESONANCES/AliRsnMiniOutput.h, PWGLF/RESONANCES/macros/mini/ConfigLStar_PbPb2018.C
This PR updates the RSN analysis code in order to be able to cut particles coming from out-of-bunch pile-up in case of pile-up MC productions.
Nothing will change for users that do not take action, namely the current behaviour of not cutting particles from pile-up is preserved.
Selection of mothers not coming from pileup is driven by the `MOTHER_NO_PILEUP` label of the mini output definition.
Please, check the updated `ConfigLStar_PbPb2018.C` for example of use.
=> Rdev rsn pileup

PWGHF/vertexingHF/AliAnalysisTaskSELc2pKs0fromKFP.cxx, PWGHF/vertexingHF/AliAnalysisTaskSELc2pKs0fromKFP.h, PWGHF/vertexingHF/macros/AddTaskLc2pKs0FromKFParticle.C
Adds possibility to disable QA tree in the output of vertexingHF/AliAnalysisTaskSELc2pKs0FromKFParticle
=> add option to disable QA tree in output

OADB/AliAnalysisUtils.cxx
This is needed to properly tag pileup particles in productions with embedding+signal fitlering
=> Modify the way to identify particles produced in the transport for AODs

PWGGA/GammaConv/AliAnalysisTaskGammaConvV1.cxx
small fix for the case of signalRejection==4 and both
UseElecSharingCut() and UseToCloseV0sCut() disabled
=> PWGGA/GammaConv: fix for c6fff645377685feb08c268ce4ca62ba6707d637

PWGGA/GammaConv/AliAnalysisTaskElectronStudies.cxx, PWGGA/GammaConv/AliAnalysisTaskElectronStudies.h, PWGGA/GammaConv/AliAnalysisTaskGammaIsoTree.cxx, PWGGA/GammaConv/macros/AddTask_ElectronStudies.C, PWGGA/GammaConv/macros/AddTask_GammaIsoTree.C
ElectronStudies
- in order to be able to run the ElectronStudies on JJ and GJ MC, I switched to default track matching for a major speedup, which is handled by a separate calo cut object to avoid rejection of matched clusters in the normal custer cuts
- following suggestions I added M20 to output
GammaIsoStudies
- added Sumw2 for all histos
=> PWGGA/GammaConv: major speedup for ElectronStudies on JJ

PWG/EMCAL/EMCALtrigger/AliEmcalTriggerMakerKernel.cxx, PWG/EMCAL/EMCALtrigger/AliEmcalTriggerMakerKernel.h
Negative noise simulating baseline underfluctuations. In
case it is disabled negative noise values are set to 0.
=> Make usage of negative noise optional

RUN3/AliAnalysisTaskAO2Dconverter.cxx, RUN3/AliAnalysisTaskAO2Dconverter.h
- Add track position (eta,phi) at the EMCAL surface to the
track table. This is crucial for cluster-track matching
- Fix numbers for gain type based on CaloFlag definition
in the ALTRO: HG - 1, LG - 0
=> [EMCAL-625] Fix AOD tables for EMCAL

PWG/EMCAL/EMCALtrigger/AliEmcalTriggerMakerKernel.h, PWG/EMCAL/EMCALtrigger/AliEmcalTriggerMakerTask.cxx, PWG/EMCAL/EMCALtrigger/AliEmcalTriggerMakerTask.h
Change default configuration for MC so that noise is
always simulated with a sigma of 50 MeV
=> TriggerMaker: Enable noise by default in case of MC

PWG/EMCAL/EMCALtrigger/AliEmcalTriggerMakerKernel.cxx, PWG/EMCAL/EMCALtrigger/AliEmcalTriggerMakerKernel.h, PWG/EMCAL/EMCALtrigger/AliEmcalTriggerMakerTask.cxx, PWG/EMCAL/EMCALtrigger/AliEmcalTriggerMakerTask.h
- Load and enable FastOR mask by default
- Add messages for different configuration steps and
display them via std::cout (so they always appear in the
logs)
- Set license for trigger maker to BSD license
=> Trigger maker: Switch on loading FastOR mask by default

PWGCF/Correlations/JCORRAN/Pro/AliJCDijetAna.cxx, PWGCF/Correlations/JCORRAN/Pro/AliJCDijetAna.h, PWGCF/Correlations/JCORRAN/Pro/AliJCDijetHistos.cxx, PWGCF/Correlations/JCORRAN/Pro/AliJCDijetTask.cxx, PWGCF/Correlations/JCORRAN/Pro/AliJCDijetTask.h
Detector MC events with jets with pt>4*pt_hard are not processed. This
required a bit code reorganizing so that no histograms are filled before
this check is done.
=> Added a cut for MC events jets with pt>4*pt_hard

PWGCF/FEMTOSCOPY/FemtoDream/AliFemtoDreamControlSample.cxx, PWGCF/FEMTOSCOPY/FemtoDream/AliFemtoDreamCorrHists.cxx, PWGCF/FEMTOSCOPY/FemtoDream/AliFemtoDreamCorrHists.h, PWGCF/FEMTOSCOPY/FemtoDream/AliFemtoDreamHigherPairMath.cxx, PWGCF/FEMTOSCOPY/FemtoDream/AliFemtoDreamHigherPairMath.h, PWGCF/FEMTOSCOPY/FemtoDream/AliFemtoDreamZVtxMultContainer.cxx
o Put into new function to separate from 1D inclusive
pair inv.mass with measured masses
o Change the scale and binning of kstar vs inv.mass hists
=> FemtoDream: use PDG masses for kstar vs inv.mass

PWGHF/vertexingHF/AliAnalysisTaskSELc2pKs0fromKFP.cxx, PWGHF/vertexingHF/AliAnalysisTaskSELc2pKs0fromKFP.h
adding new variables to output tree for Lc->pK0S KFParticle class (cos-theta*, armenteros qT/alpha, combined Bayesian PID probability on bachelor proton)
=> add extra variables to Lc->pK0s KFP tree

PWGLF/SPECTRA/PiKaPr/TPCTOFCascades/AliAnalysisPIDCascadeTrack.cxx
Just forgot to include the new class members in the Reset() function.
This has now been fixed!
=> Quick bugfix for TPC variables

PWGJE/EMCALJetTasks/Tracks/AliAnalysisTaskEmcalSoftDropData.cxx, PWGJE/EMCALJetTasks/Tracks/AliAnalysisTaskEmcalSoftDropData.h
For each jet 1 entry is created in the softdrop histograms.
2D histograms need to be projected to the trigger cluster
bin. Change is necessary for trigger matching in
reconstructions w TRD in combined tracking.
=> Add trigger cluster information to the softdrop histograms

PWG/JETFW/AliJetContainer.cxx, PWG/JETFW/AliJetContainer.h
Function regenerating the collection name from the
settings in the jet container and the connected
constituent level containers (particles and clusters).
Intended to be called at runtime or after changes in the
wagon customization.
=> Add function updating the collection name

PWGLF/SPECTRA/PiKaPr/TPC/rTPC/AliAnalysisTaskSpectraRT.cxx
Added the dE/dx calibration parameters for the 2018 data. This is relevant for the rTPC analysis
=> Added dE/dx calibration parameters for 2018 data

PWGHF/vertexingHF/AliAnalysisTaskSEXicTopKpi.cxx, PWGHF/vertexingHF/AliAnalysisTaskSEXicTopKpi.h
- event selection in MC fixed: events having generated primary vertex with |vtx_z|<10cm rejected for both gen. and reco. candidates (main fix)
- enlarge the pT range from 16 GeV/c to 24 GeV/c for reconstructed pKpi candidates
- monitoring histograms for vtx_z added
- missing delete command for a dynamic array in the UserExec added
=> Fixes for XicTopKpi task

PWGUD/UPC/AliAnalysisTaskUpcFourPi.cxx
Added line 1337 "if (vCandidateCharged.Pt() <0.11)". Adding transverse momentum selection cut for charged pions.
=> Added a Pt selection cut for charged pions

PWGHF/vertexingHF/AliAnalysisTaskSEXicTopKpi.cxx
- requirement |vtx_z|<10cm left to store generated particles
- ev. selections applied before looking at reconstructed particles
=> Fix in MC event selection

PWGGA/GammaConv/AliAnalysisTaskElectronStudies.cxx, PWGGA/GammaConv/AliAnalysisTaskElectronStudies.h, PWGGA/GammaConv/AliAnalysisTaskGammaCalo.cxx, PWGGA/GammaConv/AliAnalysisTaskGammaCalo.h, PWGGA/GammaConv/macros/AddTask_ElectronStudies.C
- implemented merging studies for EMCal cluster merging into GammaCalo tasks to be able to study merging on GRID. Wirll only e run if mesonQA>=10, so no effect on normal running
- implemented functions that iteratively search for cluster contributions from given MC particles (and all daughters)
- Electron studies cut changes. Change of NonLin to latest and greatest 21 & enabled exotics cut
- implemented new track cuts and configs that mimic the cuts used in other electron analyses (mainly addition of DCA and frac clus TPC cut)
- added proper naming scheme for ElectronStudies tree
=> PWGGA/GammaConv: implemented merging studies in GammaCalo tasks 

PWGCF/FEMTOSCOPY/FemtoDream/AliAnalysisTaskPOmegaPenne.cxx, PWGCF/FEMTOSCOPY/FemtoDream/AliAnalysisTaskPOmegaPenne.h
Paircleaning fixes
*stop checking trackID if first particle is unselected
*corrected filling of mass histos of thrown out particles
*now NOT absolute value of difference to PDG mass
*better histo ranges
*runtime optimization with better creation of objects and position of if's in loop
=> Back to DecayAndDecay PC for LambdaXi and Paircleaning Fix always selecting Lambda by accident!

OADB/AliEventCuts.cxx, OADB/AliEventCuts.h
Implementation of looser out-of-bunch pileup cuts provided by @XiaozhiBai , see ATO-496
Usage:
fEventCut.SetRejectTPCPileupWithITSTPCnCluCorr(kTRUE); // enable default cut (removes all OOB pileup, ~32% of events)
fEventCut.SetRejectTPCPileupWithITSTPCnCluCorr(kTRUE,2); // looser cut  (removes 18% of the events with high multiplicity pileup)
fEventCut.SetRejectTPCPileupWithITSTPCnCluCorr(kTRUE,3); // even more looser cut (removes 18% of the events with high multiplicity pileup)
fEventCut.SetRejectTPCPileupWithITSTPCnCluCorr(kTRUE,4); // very loose (removes 6% of the events with high multiplicity pileup)
=> Options for looser OOB pileup cuts in Pb-Pb

PWGMM/Lumi/vdM/VdmStability/AddTask_ilofnes_Vdm.C, PWGMM/Lumi/vdM/VdmStability/AliAnalysisTaskVdmStability.cxx, PWGMM/Lumi/vdM/VdmStability/AliAnalysisTaskVdmStability.h
Really small changes applied. Now the TTrees will only be filled if someone wants to check something offline, otherwise it will not be filled. This will reduce the total output for quick and well known checks.
=> Fill TTrees Only if Set

PWGJE/EMCALJetTasks/CMakeLists.txt, PWGJE/EMCALJetTasks/PWGJEEMCALJetTasksLinkDef.h, PWGJE/EMCALJetTasks/Tracks/AliAnalysisTaskEmcalJetSpectrumSDPart.cxx, PWGJE/EMCALJetTasks/Tracks/AliAnalysisTaskEmcalJetSpectrumSDPart.h, PWGJE/EMCALJetTasks/macros/AddTaskEmcalJetSpectrumSDPart.cxx
Task intended for the usage on the MCGen train
- Jet spectrum
- Several QA plots (NEF, number of constituents, ...)
- SoftDrop: Zg, Rg, Nsd, Thetag
=> Add task for jet spectra and SoftDrop at particle level

PWG/MCLEGO/ALIGENMC/gen.sh, PWG/MCLEGO/AddMCGenAliGenMC.C
With this version the train framework can delegate
the simulation to aligenmc and read in results via the
HepMC file. Communication is tested and working.
=> Adopt gen scripts for aligenmc to local tests within the train framework

PWGHF/hfe/AliAnalysisTaskHFEMultiplicity.cxx, PWGHF/hfe/AliAnalysisTaskHFEMultiplicity.h, PWGHF/hfe/macros/AddTaskHFEMultiplicity.C
The task is updated for the latest TPC track cut recommendations (eg. ncrossrows) and also for the separate analysis of EMCal and DCal. The updated event histogram shows the number of events as a function of different event selection cuts and different triggered sample.
=> Update task with TPC tracks cuts and separate EMCal and DCal detector

PWGHF/vertexingHF/AliAnalysisTaskSEHFSystPID.cxx, PWGHF/vertexingHF/AliAnalysisTaskSEHFSystPID.h, PWGHF/vertexingHF/AliCFTaskVertexingHF.cxx, PWGHF/vertexingHF/AliCFTaskVertexingHF.h, PWGHF/vertexingHF/AliRDHFCuts.cxx, PWGHF/vertexingHF/AliRDHFCuts.h
- Add possibility to apply TPC OOB pileup cut based on ITS-TPC correlation
- Add information about different TPC OOB pileup cuts based on ITS-TPC correlation in PID tree
- Add possibility to keep only/reject MC events with simulated pileup
=> Implement OOB pileup selections

PWG/MCLEGO/ALIGENMC/gen.sh, PWG/MCLEGO/AddMCGenAliGenMC.C
The add macro for the generator is running on the
worker and must assume the environment is not set.
In this case the macro needs to get the number of
events from the analysis manager.
In addition added a little bit of documentation.
=> Fix handling of passing the number of events

PWGGA/GammaConv/AliAnalysisTaskGammaIsoTree.cxx, PWGGA/GammaConv/AliAnalysisTaskGammaIsoTree.h, PWGGA/GammaConv/macros/AddTask_GammaCalo_pp.C, PWGGA/GammaConv/macros/AddTask_GammaIsoTree.C, PWGGA/GammaConvBase/AliCaloPhotonCuts.cxx, PWGGA/GammaConvBase/AliConvEventCuts.cxx, PWGGA/GammaConvBase/AliConvEventCuts.h
- new definition for prompt, frag and decay photons in IsoTree tasks, using utils from AliMCAnalysisUtils by Gustavo
- added function to event cuts that allow to get header name for a given particle
- changed behavior of AliCaloPhotonCuts:
before, gen level photons are rejected if they have a photon mother. This, I believe, is not the behavior we want. In this way, one ends up with the initial photon of a chain, without any further corrections/modifications done by pythia. We want the final photon. I therefore changed it to reject photons with photon daughters. I believe thischange is not really significant when not working with GJ MC
=> PWGGA/GammaConv: GammaIsoTree refined prompt photon definition & more

RUN3/AliAnalysisTaskAO2Dconverter.cxx, RUN3/AliAnalysisTaskAO2Dconverter.h
Fixed final writing of the trees in the last TF_n folder created in AO2D.root during conversion.
=> Moved Finishing the TF in FinishTaskOutput.

PWG/MCLEGO/ALIGENMC/gen.sh
Environment command was not properly working for
cvmfs package but implemented as bypass for local
tests (no sourcing of login script, adding --no-refresh
option in order to prevent refreshing local workdir). This
is overcome by implementing two modes (local/cvmfs)
where the cvmfs mode is detected by "::" in the
package name
=> Fix loading of aligenmc grid package

.github/workflows/release.yml
This adds automatic Jenkins builds to the release-tagging workflow.
=> Automatically trigger Jenkins build

PWG/EMCAL/EMCALtasks/AliEmcalFastOrMonitorTask.cxx, PWG/EMCAL/EMCALtasks/AliEmcalFastOrMonitorTask.h
- use correct function (GetTime() instead of
GetCellTime())
- Explicitly state that the time cut is implemented in
nanoseconds and not in seconds by adding tag to
variable and function names, in order to avoid
confusion
- Add monitoring histograms for cell time before and
after cell time cut
- Make use of fCaloCells provided by
AliAnalysisTaskEmcal
=> Fix cell time cut in filling the summed cell grid

PWGJE/EMCALJetTasks/Tracks/AliAnalysisTaskEmcalSoftDropResponse.cxx, PWGJE/EMCALJetTasks/Tracks/AliAnalysisTaskEmcalSoftDropResponse.h
New histograms for zg, rg, thetag and nsd:
- Jet finding effiency (observable, part. pt, match status)
- Jet finding purity (observable, det. pt, match status)
- Part level 2D distributions (observable, pt)
Matching status distinguishes between
- No match (0)
- Match, but outside fiducial acceptance (1)
- Match, inside fiducial acceptance (2)
Jet finding purity implemented for pp and PbPb,
jet finding efficiency and part. level distributions
only for pp
=> Add histograms for jet finding efficiency and purity

PWG/EMCAL/EMCALtasks/AliEmcalCorrectionCellTimeCalib.cxx, PWGGA/GammaConv/AliAnalysisTaskGammaCalo.cxx, PWGGA/GammaConv/AliAnalysisTaskGammaCalo.h, PWGGA/GammaConvBase/AliCaloPhotonCuts.cxx
- added missing line for LowGainTimeCalib to properly deactivate it in case of Run1. Previously the time calibration completely failed if user has enable lowGainTimeCalib for Run1 data
- rest of commit are things for my cluster merging studies that are unrelated to timecalib
=> PWG/EMCal: low gain time calib fix for Run1

PWGJE/EMCALJetTasks/Tracks/AliAnalysisTaskEmcalSoftDropResponse.cxx
- Increase histogram range of the Residuals
histogram and split residuals histograms
for Rg and Thetag
- Move Jet finding efficiency histograms to
parent group in order to have tehm always
filled
=> Fixes in histograms for SoftDrop response

PWGGA/GammaConv/AliAnalysisTaskOmegaToPiZeroGamma.cxx, PWGGA/GammaConv/macros/AddTask_OmegaToPiZeroGamma_pp.C
- In the background calculations the variable gamma0 was redeclared and overwritten inside the last loop. This is now fixed renaming the correct calls of gamma0 to gamma2.
- Added many new train configs which mostly are copies of existing ones to be able to run the same cut string, but with different AddTask call options.
=> PWGGA/GammaConv: AliAnalysisTaskOmegaToPiZero - fixed bug in background calculation and added train configs

PWGMM/Lumi/vdM/VdmStability/AddTask_ilofnes_Vdm.C
Instead of a fixed set of nRuns, with this mod anyone will be available to run different run lists without the need to change the add task. The common number of runs used for stability is there, but if the option nRuns is set then the number of runs to fill the histograms will be modified accordingly.
=> Added a new way to set the total number of runs

PWGGA/GammaConv/AliAnalysisTaskElectronStudies.cxx, PWGGA/GammaConv/AliAnalysisTaskElectronStudies.h, PWGGA/GammaConv/AliAnalysisTaskGammaCalo.cxx, PWGGA/GammaConv/AliAnalysisTaskGammaCalo.h, PWGGA/GammaConv/config/PWGGA_CF_config.yaml, PWGGA/GammaConv/config/PWGGA_CF_config_MC.yaml
- fixed wrong types for momentum in ElectronStudies tree
- added support for eta meson in merging studies
- added yaml configs intended to be used as new default for CF of GA
=> PWGGA/GammaConv: ElectronStudies fixed types & added EMC CF default conf

PWG/EMCAL/EMCALtasks/AliEmcalCorrectionCellTimeCalib.cxx, PWG/EMCAL/config/AliEmcalCorrectionConfiguration.yaml
Default value is enabled, so the switch is there to
switch off time recalibration.
Load Phase calib also in case time calib is disabled
=> Add option for enable/disable time calib

PWGCF/FEMTOSCOPY/macros/AddTaskFemtoNanoLD.C
o For 3 subwagons, all with FB 256 for deuterons
o Std settings, no TPC PID, no TOF PID
=> FemtoNanoLD: use FB 256 for deuteron purities

PWG/EMCAL/EMCALbase/AliAnalysisTaskEmcalEmbeddingHelper.cxx, PWG/EMCAL/EMCALbase/AliAnalysisTaskEmcalEmbeddingHelper.h
Make sure that given a grid job only the MC files anchored to a run  that corresponds to the block run range of the input data file are used for the embedding.
Implemented only for analysis in trains running analysis per run.
=> Implement possibility to collect and embed signal MC files only for the data run block range used to anchor MC  

PWGHF/hfe/AliAnalysisTaskHFEBESpectraEMC.cxx, PWGHF/hfe/AliAnalysisTaskHFEBESpectraEMC.h, PWGHF/hfe/macros/AddTaskHFEBESpectraEMC.C
Changing the way cluster and track container names from the EMCal correction framework are passed to the task
=> Fixing bug related to passing container names

PWGPP/EvTrkSelection/AliAnalysisTrackingUncertaintiesAOT.cxx, PWGPP/EvTrkSelection/AliAnalysisTrackingUncertaintiesAOT.h
1. time-range cut for LHC18r period
2. out-of-bunch pile-up rejection according to ITS cluster vs. TPC cluster correlation
=> Add Pb-Pb 2018 event selections for ITS-TPC matching studies

ML/AliExternalBDT.cxx, ML/AliExternalBDT.h, ML/AliMLModelHandler.cxx, ML/AliMLModelHandler.h, ML/AliMLResponse.cxx, ML/AliMLResponse.h, PWGHF/vertexingHF/vHFML/AliHFMLResponse.cxx, PWGHF/vertexingHF/vHFML/AliHFMLResponse.h
Add several methods for multiclass model application: 
- `PredictMultiClass`
- `IseSelectedMultiClass` 
which work for both binary and multiclass models.
The old methods for binary models 
- `Predict`
- `IseSelected` 
are kept for retrocompatibility.
The yaml config file can be as the old ones, or can take a list of threshold cuts (`cuts` entry) instead of a single value. An optional entry can also be added (`cuts_opt`) to specify if they are "lower" or "upper" cuts, which can be also either a single value or a list in case of multiclass classification.
=> Add possibility to perform application for multi-class models

PWG/EMCAL/EMCALtasks/AliEmcalCorrectionClusterTrackMatcher.cxx, PWG/EMCAL/config/AliEmcalCorrectionConfiguration.yaml
Avoid unnecessary processing of tracks already discarded during AOD creation
For discussion
=> Add switchs to forced track extrapolation to the EMCal surface on AODs

PWGHF/treeHF/AliAnalysisTaskSEHFTreeCreator.cxx, PWGHF/treeHF/AliAnalysisTaskSEHFTreeCreator.h
* Added recommended protection for OOB pileup in new PbPb 18 MCs
* Fix event ID for MC by bringing it back to the (unique) version of QM19
=> PWGHF: Protection OOB pileup + fix EvID

PWGHF/vertexingHF/AliRDHFCutsLctoV0.cxx
Selection with AliESDtrackCuts object `fV0daughtersCuts` was performed "manually" in `AliRDHFCutsLctoV0::AreLctoV0DaughtersSelected()` for the most important selections (pT, eta, MinNTPCClusters, TPC refit, MinRatioCrossedRowsOverFindableClustersTPC, and kinks). 
For the PbPb analysis additional selections are needed (MinNCrossedRowsTPC, MinNumTPCClsForPID, MaxChi2PerClusterTPC). Added them with the standard procedure, using a call to `AliRDHFCuts::IsDaughterSelected()` which calls `AliESDtrackCuts::AcceptTrack()`. Kept the manual selections for safety reasons
=> PWGHF: Add missing track quality selections V0 daughters (Lc->pK0s)

PWGDQ/dimuons/AliAnalysisTaskTree_MCut.cxx, PWGDQ/dimuons/AliAnalysisTaskTree_MCut.h, PWGDQ/dimuons/macros/AddTaskTree_Grid_MCut.C
Files have been modified in order to allow the possibility to set a mass cut from an external macro (previously it was harcoded in the .cxx). In this way it will be possible to create trees with a given cut in the dimuon mass spectrum
=> update of previously existing files to allow a cut in the mass spectrum

PWGHF/vertexingHF/vHFML/AliAnalysisTaskSEHFTreeCreatorApply.cxx, PWGHF/vertexingHF/vHFML/AliHFTreeHandlerApply.cxx, PWGHF/vertexingHF/vHFML/AliHFTreeHandlerApply.h, PWGHF/vertexingHF/vHFML/AliHFTreeHandlerApplyDstoKKpi.cxx, PWGHF/vertexingHF/vHFML/AliHFTreeHandlerApplyDstoKKpi.h, PWGHF/vertexingHF/vHFML/AliHFTreeHandlerApplyLc2V0bachelor.cxx, PWGHF/vertexingHF/vHFML/AliHFTreeHandlerApplyLc2V0bachelor.h
Fix for extracted nsigma TOF stored in TTrees. There are two methods:
* `AliAODPidHF::GetnSigmaTOF()`
* `AliPIDResponse::NumberOfSigmasTOF()`
First one is adding a TOF mismatch cut (default 0.01) as extra condition for flagging bad TOF-PID tracks (standard procedure in HF). Second option isn't, leading to random nsigma TOF values in a huge range, which were given as input to the ML training. These candidates should have been flagged with nsigmaTOF = -999 instead. 
Switched now from 2nd to 1st method, fixing the issue
=> PWGHF: Adding TOF mismatch selection (TreeCreator)

PWGHF/vertexingHF/vHFML/AliHFTreeHandlerApply.cxx
PID post calibration is performed already in the newly used AliAODPidHF class, so we were double correcting now. Fix = only correct in task in case when the PID response class is used
=> PWGHF: Fix in case of PID post calibration PbPb

PWGHF/treeHF/AliAnalysisTaskSEHFTreeCreator.cxx, PWGHF/treeHF/AliHFTreeHandler.cxx, PWGHF/treeHF/AliHFTreeHandler.h, PWGHF/treeHF/AliHFTreeHandlerBplustoD0pi.cxx, PWGHF/treeHF/AliHFTreeHandlerBplustoD0pi.h, PWGHF/treeHF/AliHFTreeHandlerBstoDspi.cxx, PWGHF/treeHF/AliHFTreeHandlerBstoDspi.h, PWGHF/treeHF/AliHFTreeHandlerD0toKpi.cxx, PWGHF/treeHF/AliHFTreeHandlerD0toKpi.h, PWGHF/treeHF/AliHFTreeHandlerDplustoKpipi.cxx, PWGHF/treeHF/AliHFTreeHandlerDplustoKpipi.h, PWGHF/treeHF/AliHFTreeHandlerDstartoKpipi.cxx, PWGHF/treeHF/AliHFTreeHandlerDstartoKpipi.h, PWGHF/treeHF/AliHFTreeHandlerDstoKKpi.cxx, PWGHF/treeHF/AliHFTreeHandlerDstoKKpi.h, PWGHF/treeHF/AliHFTreeHandlerInclusiveJet.cxx, PWGHF/treeHF/AliHFTreeHandlerInclusiveJet.h, PWGHF/treeHF/AliHFTreeHandlerLbtoLcpi.cxx, PWGHF/treeHF/AliHFTreeHandlerLbtoLcpi.h, PWGHF/treeHF/AliHFTreeHandlerLc2V0bachelor.cxx, PWGHF/treeHF/AliHFTreeHandlerLc2V0bachelor.h, PWGHF/treeHF/AliHFTreeHandlerLctopKpi.cxx, PWGHF/treeHF/AliHFTreeHandlerLctopKpi.h
Fix for extracted nsigma TOF stored in TTrees. There are two methods:
* `AliAODPidHF::GetnSigmaTOF()`
* `AliPIDResponse::NumberOfSigmasTOF()`
First one is adding a TOF mismatch cut (default 0.01) as extra condition for flagging bad TOF-PID tracks (standard procedure in HF). Second option isn't, leading to random nsigma TOF values in a huge range, which were given as input to the ML training. These candidates should have been flagged with nsigmaTOF = -999 (and therefore masked in the training) instead.
Switched now from 2nd to 1st method, fixing the issue
=> PWGHF: Flagging candidates that don't pass TOF mismatch

PWGHF/vertexingHF/vHFML/AliAnalysisTaskSEHFTreeCreatorApply.cxx, PWGHF/vertexingHF/vHFML/AliAnalysisTaskSEHFTreeCreatorApply.h
Two additional methods:
* Only fill reconstructed TTrees with selected events
* Pseudorandom candidate rejection factor (as defined for other HF studies), to store less low pT candidates when creating sample for training only
=> PWGHF: Downsampling methods to reduce output size PbPb

PWG/EMCAL/EMCALbase/AliAnalysisTaskEmcal.cxx, PWG/EMCAL/EMCALbase/AliAnalysisTaskEmcal.h, PWGJE/EMCALJetTasks/Tracks/AliAnalysisTaskEmcalJetEnergyScale.cxx
Option is in particular of relevance when combining min. bias and pt-hard events, in order to remove events with pt-hard values in ranges where the jet-jet MC is used, in order to avoid double counting.
=> Add option to select events in a certain pt-hard range

PWGLF/NUCLEX/Exotica/Dibaryons/AddTaskDibaryons.C, PWGLF/NUCLEX/Exotica/Dibaryons/AliAnalysisTaskDibaryons.cxx, PWGLF/NUCLEX/Exotica/Dibaryons/AliAnalysisTaskDibaryons.h
- Add track cuts to reject V0 and Cascade candidates with daughter tracks stemming from pile-up events
- Fix mass window selection of anti-Lambda
=> PWGLF/NUCLEX: Add out-of-bunch pileup cuts for daughters of V0s and Cascades

PWG/FLOW/Tasks/AliAnalysisTaskForStudents.cxx, PWG/FLOW/Tasks/AliAnalysisTaskMultiparticleFemtoscopy.cxx, PWG/FLOW/Tasks/AliAnalysisTaskNBodyFemtoscopy.cxx, PWG/FLOW/Tasks/AliAnalysisTaskStudentsCM.cxx, PWG/FLOW/Tasks/AliAnalysisTaskStudentsML.cxx, PWG/FLOW/Tasks/AliAnalysisTaskStudentsMW.cxx, PWG/FLOW/Tasks/AliAnalysisTaskTwoMultiCorrelations.cxx
The output file was manually opened, overwriting the existing file with the same name. This creates problems in the final merging phase in train mode.
=> Fixed Terminate method in several FLOW tasks.

PWGGA/GammaConv/AliAnalysisTaskGammaConvV1.cxx, PWGGA/GammaConv/AliAnalysisTaskGammaConvV1.h, PWGGA/GammaConv/macros/AddTask_GammaConvV1_PbPb.C, PWGGA/GammaConv/macros/runTests_GammaConvROOT6.C, PWGGA/GammaConvBase/AliConvEventCuts.cxx, PWGGA/GammaConvBase/AliConvEventCuts.h, PWGGA/GammaConvBase/AliConversionPhotonCuts.cxx, PWGGA/GammaConvBase/AliConversionPhotonCuts.h
commit message yet to be updated
This change reduces the complexity of AliConversionPhotonCuts::
ProcessPhotonCandidates significantly. The semantics of the
sharedElectron and toCloseV0s cuts are slightly changed.
Before this change:
Say we have photons A B C. Then RejectToCloseV0s will cut photon A
if its too close to B. However, also C gets cut, if C is too close to A.
Even though A has already been thrown out.
For RejectSharedElectronV0s its the same: Say A and B have an electron track
in common -> A gets kicked out. Then C will still get kicked out,
if it is shares the positron track with A.
With this change, photon C does not get cut.
This affects typically 10% of photons for the shared electron
cut and sometimes one out of 200 photons for the tooclose cut.
Extensive automated tests …
=> PWGGA/GammaConv: refactor ProcessPhotonCandidates() take2

PWGGA/GammaConv/AliAnalysisTaskGammaCalo.cxx, PWGGA/GammaConv/AliAnalysisTaskGammaConvCalo.cxx, PWGGA/GammaConv/macros/AddTask_GammaCalo_pp.C, PWGGA/GammaConv/macros/AddTask_GammaConvCalo_pp.C, PWGGA/GammaConvBase/AliCaloPhotonCuts.cxx, PWGGA/GammaConvBase/AliConvEventCuts.cxx, PWGGA/GammaConvBase/AliConvEventCuts.h
PHOS trigger mimicking:
- PHOS trigger mimic helper only created if mimicing enabled in addtask
- enableTriggerMimicking==3 one leg of meson must be triggered
- enableTriggerMimicking==4 all meson candidates in triggered event
train config changes (pp 13 TeV):
- add configs to test PHOS standard with different mimicing settings in same train
- change pcm-edc lowB NL 01 -> 11
- adding additional RBin settings for pcm-edc lowB
=> PWGGA/GammaConv PHOS trigger mimicking and train config changes (pp 13 TeV)

PWGDQ/dielectron/core/AliDielectronTrackRotator.cxx
change track range to include events with only one positron and electron
=> PWGDQ: LMee: new Rotation method for background estimation: 

PWG/EMCAL/EMCALtasks/AliEmcalCorrectionClusterNonLinearity.cxx, PWG/EMCAL/EMCALtasks/AliEmcalCorrectionClusterNonLinearityMCAfterburner.cxx
The order of SetNonLinCorrEnergy() and fSetForceClusterE must be inverted to work correctly. Otherwise the correction is applied twice!
Also fixed that finetuning correction is also applied on DCal clusters.
=> PWG/EMCAL: fix for nonlinearity application

PWGDQ/dimuons/AliAnalysisTaskPbPbTree_MCut.cxx, PWGDQ/dimuons/AliAnalysisTaskPbPbTree_MCut.h, PWGDQ/dimuons/macros/AddTaskPbPbTree_Grid_MCut.C
Macro to produce PbPb trees for dimuon analysis. The information of polarization angles in the helicity, Collins-Soper and Event-Plane reference frames is also included.
=> Macro to produce PbPb trees for dimuon analysis

PWGLF/NUCLEX/Exotica/Dibaryons/AliAnalysisTaskDibaryons.cxx
- Reject miss-identified candidates in order to improve S/B of invariant mass distribution of V0 and cascade
- Fix eta cut for V0 daughter tracks and topological cut for cascade
=> PWGLF/NUCLEX: Add rejection of miss-identified candidates for V0 and cascade

PWGGA/GammaConvBase/AliConversionPhotonCuts.cxx
This fixes a runtime crash on linux architectures (see train 1625 GA_pp_AOD)
that does not occur on Mac.
=> PWGGA/GammaConv: Fix TooClose photon cut for Linux architectures

PWGCF/Correlations/Base/AliUEHist.cxx
This fix allows to sum entries with non-unitary weights, which may happen depending on what exactly a user asks for.
=> fix(PWGCF): changing counter type to double

PWGPP/ZDC/macros/DrawPerformanceZDCQAMatch.C
As reported by Elena and Piotr the ZDC QA trending macros were crashing (see log below). A fix has been committed and it should be ported to the release.
Thanks ch.
Error log:
Warning in <TEnvRec::ChangeValue>: duplicate entry <Unix.*.Root.DynamicPath=.:$(ROOT_DYN_PATH):> for level 0; ignored
Core dump enabled
Processing MakeTrendZDC.C("/home/aliqaoperator/autoQAperiod/alienQA/alice/data/2010/LHC10h/000139465/pass3/QA_merge_archive.zip#QAresults.root",139465)...
:::: Getting post-analysis info for run 139465
==============  Saving histograms for run 139465 ===============
==============  Saving trending quantities in tree for run 139465 ===============
(int)0
Warning in <TEnvRec::ChangeValue>: duplicate entry <Unix.*.Root.DynamicPath=.:$(ROOT_DYN_PATH):> for level 0; ignored
Core dump …
=> Fixing some possible problems in ZDC QA macro

PWGLF/NUCLEX/Exotica/Dibaryons/AliAnalysisTaskDibaryons.cxx, PWGLF/NUCLEX/Exotica/Dibaryons/AliAnalysisTaskDibaryons.h
- The max size of track array is set larger (2000->2500) for HM event
- The size of array is determined by new member variable
- p-Omega invariant mass calculation is fixed
=> PWGLF/NUCLEX: Fix the size of track array

PWGCF/FLOW/GF/AliAnalysisTaskMeanPtV2Corr.cxx, PWGCF/FLOW/GF/AliAnalysisTaskMeanPtV2Corr.h
-- TAxis *fV2dPtMultiAxis changed to TH1D *fV2dPtMulti, because TAxis don't have a merger (reduced the output when merging)
-- Added SetEtaV2Sep(...) that sets the minimum eta for v2 gap. Don't abuse it by setting multiple wagons with different gaps; implement them directly into the code instead to save CPU time!
=> MeanPtV2Corr: 

PWGJE/EMCALJetTasks/Tracks/AliAnalysisTaskEmcalSoftDropResponse.cxx
- Fill histograms at det and part. level before
matching criterion, in order to apply efficiency/
purity correction in closure test
- Split sample in response/no-response sample
for jet finding efficiency / purity histograms
=> Improved handling of closure test

PWGLF/NUCLEX/Exotica/Dibaryons/AliAnalysisTaskDibaryons.cxx, PWGLF/NUCLEX/Exotica/Dibaryons/AliAnalysisTaskDibaryons.h
- Fix pair rejection with shared tracks for AOD
- Track ID is reset in case of TPC-only tracks
- Add selection cuts for omega (tighter cuts)
- Candidates are stored in TClonesArray
=> PWGLF/NUCLEX: Fix rejection of pairs with shared tracks

PWGLF/NUCLEX/Exotica/Dibaryons/AliAnalysisTaskDibaryons.cxx
- The nσ is computed assuming different particle hypotheses (kaons, electrons and pions).
-  if the nσ value found to be smaller,  the track is rejected from proton candidates.
- New histograms (multiplicity, TOF β, etc...) are added.
=> PWGLF/NUCLEX: Reject other particle from proton candidates using PID info

PWGHF/hfe/AliAnalysisTaskEHCorrel.cxx
Adding the weight for pi0 and eta pT spectra for tagging efficiency calculation
=> Adding pi0 and eta weight for p-Pb

PWGCF/Correlations/DPhi/AliAnalysisTaskPhiCorrelations.cxx, PWGCF/Correlations/DPhi/AliAnalysisTaskPhiCorrelations.h
Clean-up of .h & .cxx files for AliAnalysisTaskPhiCorrelations class:
- Fix indentation issues
- Convert all tab characters to spaces
- Remove unnecessary whitespaces
- Keep curly brackets consistent across the files
- Adjust spaces to improve readability
=> chore(PWGCF): code clean-up in AliAnalysisTaskPhiCorrelations class

PWGJE/FlavourJetTasks/AliAnalysisTaskHFJetIPQA.cxx, PWGJE/FlavourJetTasks/AliAnalysisTaskHFJetIPQA.h
- delete obsolete functions
- put V0 acceptance cuts and pdg cuts in separate functions that can be used for MC veto and MC generated information
=> AliAnalysisTaskHFJetIPQA:: tidy up V0-jet tagger

PWGHF/vertexingHF/AliAnalysisTaskSEXicZero2XiPifromKFP.cxx
Use mass value of Omegac0 2.6952 instead of 2.6975 (default in PYTHIA6)
=> Use mass value of Omegac0 2.6952 instead of 2.6975 (default in PYTHIA6)

PWGPP/AliPIDtools.cxx
Sometimes Path was not expanded - empy string crated 
const char * aodbPath = gSystem->ExpandPathName("$ALICE_PHYSICS/OADB");
=> PWGPP-538, ATO-525 - use ExpandPath to get default AODB Path

PWGCF/FLOW/GF/AliAnalysisTaskMeanPtV2Corr.cxx, PWGCF/FLOW/GF/AliAnalysisTaskMeanPtV2Corr.h
Added external V0M binning setter. If max bin is above 90%, then V0M acceptance is automatically extended.
If the efficiency is missing for a given bin, then previous efficiency is picked up.
=> MeanPtVnCorr: added external V0M binning setter

RUN3/AliAnalysisTaskAO2Dconverter.cxx, RUN3/AliAnalysisTaskAO2Dconverter.h
Mimic run3 cell level compression type 1 and 2 (only amplitude
above threshold, no pre-clusterization)
=> Add settable threshold for EMCAL cell level compression

PWGDQ/dielectron/core/AliAnalysisTask_JPsi_EMCal.cxx, PWGDQ/dielectron/core/AliAnalysisTask_JPsi_EMCal.h, PWGDQ/dielectron/macrosJPSI/AddTask_JPsi_EMCal.C, PWGDQ/dielectron/macrosJPSI/Config_JPsi_EMCal.C
Added a data-driven calibration on TPCnsigma, due to the missing splines at high pT for 2017 data and part of the 2018 periods.
=>  Including TPC calibrations on 2017 and 2018 data for high pT analysis

PWGHF/vertexingHF/AliAODPidHF.cxx, PWGHF/vertexingHF/AliAnalysisTaskSEHFSystPID.cxx
Forcing the TOF the improvement in the TOF response with tune on data introduced in https://github.com/alisw/AliRoot/pull/1305 can be available also for already produced AODs
=> Force TOF tune on data for vertexingHF analyses

PWGHF/vertexingHF/AliAnalysisTaskSEXicTopKpi.cxx, PWGHF/vertexingHF/AliAnalysisTaskSEXicTopKpi.h
Possibility to avoid the THnSparses to be filled with standard PID selections when the case with Bayes PID is checked only for proton.
=> Possibility to make THnSparses lighter when exploring PID possibilities

PWG/EMCAL/config/AliEmcalCorrectionConfiguration.yaml
Modified the cross talk parameter grouping from the old version:
group 1: SM 3, 7
group 2: 1, 10, 11
group 3: 2
group 4: rest
to the new grouping:
group 1: SM 3, 7
group 2: 1, 10
group 3: 2, 11, 0, 6, 5, 4, 13, 16, 12
group 4: rest
For questions, please ask @FriederikeBock and @gconesab .
=> PWG/EMCAL: Changed default cross talk fractions

PWGGA/GammaConvBase/AliConversionMesonCuts.cxx
- Changed the 'z' background setting to only use TGPS and _not_ forbid similar decays since it yields better background description when looking at TGPS omega decays and not forbid similar decays compared to TGPS omega decays and _do_ forbid similar decays
=> PWGGA/GammaConvBase: Changed AliConversionMesonCuts - Background Setting 'z'

PWGPP/EMCAL/AliAnalysisTaskEMCALTimeCalib.cxx, PWGPP/EMCAL/AliAnalysisTaskEMCALTimeCalib.h
The time calibration code has been modified such that it can analyze Run1 data. I also implemented a new method for the extraction of the time calibration coefficients using a Gaussian fit to the time distribution for every cell.
=> Allowing the time calibration to run on Run1 data

PWGCF/FEMTOSCOPY/AliFemtoUser/AliFemtoESDTrackCut.cxx, PWGCF/FEMTOSCOPY/AliFemtoUser/AliFemtoESDTrackCut.h, PWGCF/FEMTOSCOPY/AliFemtoUser/AliFemtoWRzTrackCut.cxx, PWGCF/FEMTOSCOPY/AliFemtoUser/AliFemtoWRzTrackCut.h
Changes in AliFemtoESDTrackCut: cleaning up a little messy code for deuterons implemented in the past by me. Removing temporary options of method and some specific cases used for tests. Functions and options for deuterons that I have left in this class are sufficient for performing basic analysis with deuterons. I added/moved more specific features to AliFemtoWRzTrackCut.
Changes in  AliFemtoWRzTrackCut: this class I have created in the past but over time, become unnecessary. I decided to adapt it mainly for deuterons that I use in femto analysis. This class in comparison to  AliFemtoESDTrackCut contains some additional features: a base for the sideband analysis, a dEdx cut more apt to my future checks, and an exclusive n sigma selection. This class is under development and testing.
=> Nowa wiolata rz

PWG/CaloTrackCorrBase/AliIsolationCut.cxx, PWGGA/CaloTrackCorrelations/AliAnaParticleIsolation.cxx
is considered for UE in perperdicular cone
=> [PWGGA/CaloTrackCorr] Make sure in case of tracks in cone no cluster contribution 

PWGPP/TPC/macros/PIDCalib/MakeTPCPIDResponseOADB.C
To allow for forward and backward compatibility between root 5 and root
6, the sigma parametrization function is initialized now from a string
for the function definition and a TVectorD for the fit parameters.
As input, the parameters are expected to be provided in a root file,
e.g.
```
TFile*         /tmp/TF1_SigmaPar.root
KEY: TNamed   SigmaParametrization;1
sqrt(([0]**2)*x[0]+(([1]**2)*(x[5]*[5])*(x[0]/sqrt(1+x[1]**2))**[2])+x[5]*AliTPCPIDResponse::sigmadEdxPt(x[2],x[3],[3])**2+([4]*x[4])**2
+((x[6]*[6])**2)+(x[6]*(x[0]/sqrt(1+x[1]**2))*[7])**2)
KEY: TVectorT<double> SigmaParametrizationParams;1
KEY: TNamed   MultiplicityNormalization;1     10000
```
=> Modifications to initialize TF1 from string and TVectorD

PWGHF/vertexingHF/AliAnalysisTaskSEImproveITSCVMFS.h
- Useful setter to configure improver with alternative input files for a given data sample @cterrevo
=> PWGHF: Add setter for cvmfs path suffix in improver task

PWGJE/EMCALJetTasks/Tracks/AliAnalysisTaskEmcalClustersRef.cxx
Even though no longer used better remove the hard coded
settings for pPb 2013 in order to avoid unforced errors.
=> Remove offline trigger selection call in default function

PWGGA/EMCALTasks/AliAnalysisTaskGammaHadron.cxx, PWGGA/EMCALTasks/AliAnalysisTaskGammaHadron.h
Adds 3 more th3s to track pi0cands vs EP, Cent.
Allows event plane info to be found in separate centralities without separate wagons.
=> Adds 3 more th3s to track pi0cands vs EP, Cent

PWGGA/NtuplizerTask/GJNtuples/half.cpp, PWGGA/NtuplizerTask/GJNtuples/half.h
Replace deprecated random_shuffle by shuffle to be able to use C++17.
Do not use register in the declarations (deprecated).
=> Fixes for OSX Big Sur

PWGCF/FLOW/GF/AliAnalysisTaskMeanPtV2Corr.cxx
Apparently, multiple triggers in MC are allowed, but not in data
=> AliAnalysisTaskMeanPtV2Corr: changed trigger checks that would break MC runs

PWG/EMCAL/EMCALbase/AliAnalysisTaskEmcal.cxx, PWG/EMCAL/EMCALbase/AliAnalysisTaskEmcal.h, PWG/EMCAL/EMCALbase/AliEmcalPythiaFileHandler.cxx, PWG/EMCAL/EMCALbase/AliEmcalPythiaFileHandler.h, PWG/EMCAL/EMCALbase/CMakeLists.txt
In order to minimize the amount of calls to
the pyxsec(_hists).root files a singleton is
used to cache the cross section value and
just pass it instead of load it again, if the file
is the same.
The reading of the pythia cross section via
singleton class is implemented in
AliAanlysisTaskEmcal as second fast option,
default is kept with the standard option. The
fast option can be selected on request and
will replace the default method after a
transition period.
=> [PWGJE-23] Add singleton handling access to PYTHIA cross section file

PWGGA/GammaConv/AliAnalysisTaskGammaIsoTree.cxx, PWGGA/GammaConv/AliAnalysisTaskGammaIsoTree.h, PWGGA/GammaConv/macros/AddTask_GammaIsoTree.C, PWGGA/GammaConvBase/AliCaloPhotonCuts.cxx, PWGGA/GammaConvBase/AliCaloTrackMatcher.cxx, PWGGA/GammaConvBase/AliCaloTrackMatcher.h
- implemented fRunningMode=7 for AliCaloTrackMatcher which considers all hybrid tracks for track matching (which should be used after testing as default imo)
- current default mode 0 will only match hybrid tracks with SPD hits that have not been constrained to primary vertex (good global tracks) and will ignore other tracks of hybrid sample that can be selected in analysis
- fixed a minor bug that only affects cases where a TM cut is used which is not pt dependent. Some matches were not matched by accident
- fixed an issue that should only occur when choosing a very wide TM cut. If, for some reason, one track is matched to multiple clusters, there was an issue that the second matched cluster was thrown away and never considered as matched
- added warnings for fRunningMode = 7. Negative …
=> PWGGA/GammaConv: AliCaloTrackmatcher implemented new mode 7

PWG/EMCAL/EMCALbase/AliAnalysisTaskEmcal.cxx, PWG/EMCAL/EMCALbase/AliEmcalPythiaFileHandler.cxx
File type (ESD/AOD) determination must be done before
path handling to cross section file. In addion adding a
few AliDebugStream in both AliAnalysisTaskEmcal and
AliEmcalPythiaFileHandler.
=> [PWGJE-23] Fix determination of file type in file handler

PWGGA/GammaConv/AliAnalysisTaskNeutralMesonToPiPlPiMiNeutralMeson.cxx
this caused a seg. fault in some cases because the object in the TList was deleted because it got out of scope.
Now the object in the list is only deleted when list->Clear() is called
=> PWGGA/GammaConv: Prevent deletion of object in TList

PWG/EMCAL/EMCALtasks/AliAnalysisTaskEmcalTriggerSelection.cxx
- Adding L0 trigger (2 GeV) for MC pp 8 TeV
- Setting trigger aliases for L0 triggers with names
"EMCL0;EMC7;EMC8" and similar for DCAL
- Adding MC sample lhc17g6b anchored to pPb
8 TeV
=> feature-l0pp8TeV

PWGLF/NUCLEX/Nuclei/Nuclei_UE/AliAnalysisTaskDeuteronsRT.cxx
Added pt-dependent DCA_{xy} selection for leadinng track:
fESDtrackCuts_LeadingTrack -> SetMaxDCAToVertexXYPtDep("0.0105+0.0350/pt^1.1");
Added pseudorapidity and pt cuts in the selection of tracks to calculate transverse mult
fESDtrackCuts_TransverseMult -> SetEtaRange(-0.8,0.8);
fESDtrackCuts_TransverseMult -> SetPtRange(0.15,200);
=> added extra cuts for selection of leading track

CMakeLists.txt, PWGHF/correlationHF/CMakeLists.txt, PWGHF/hfe/CMakeLists.txt, PWGHF/vertexingHF/CMakeLists.txt, PWGHF/vertexingHF/vHFML/CMakeLists.txt, PWGJE/EMCALJetTasks/CMakeLists.txt, PWGLF/NUCLEX/CMakeLists.txt, cmake/FindKFParticle.cmake
Provinding FindKFParticle.cmake copied and
adpated from FindRooUnfold.cmake which finds
the KFParticle package based on KFParticle_ROOT
and export include path and library as cmake
properties. CMakeLists.txt in libraries which
make use of KFParticles are adapted, and
find_package(KFParticle) is added to the global
CMakeLists.txs
=> Handle dependency on KFParticle as a CMake module

PWG/EMCAL/EMCALbase/AliEmcalAODHybridTrackCuts.cxx, PWG/EMCAL/EMCALbase/AliEmcalTrackSelResultHybrid.h, PWG/EMCAL/EMCALbase/AliEmcalTrackSelectionAOD.cxx
Condition for category 2 hybrid track selection
had to be negated as the if condition counts
the errors and not the successes.
=> Fixing EMCAL track selection unit tests

PWGGA/GammaConv/macros/AddTask_GammaCaloMergedML_pp.C
I updated the AddTask for my own Analyses with two cutstrings that will become my default cut for trains.
=> PWGGA/GammaConv: Added two Cutstrings to the AddTask CaloMergedML

PWGCF/Correlations/Base/AliUEHistograms.h
This fixes the default behaviour of the FillCorrelations method in AliUEHistograms class:
- It doesn't use two-track cuts by default
- It causes that all two-tracks cuts are off in the AliAnalysisTaskPhiCorrelations task in steps 0-6 (MC true to MC reconstructed), even if the user asks for them (they are still there in steps > 6)
- It shouldn't affect any analysis based on the AliAnalysisTaskPhiCorrelations task if there are no two-track cuts defined by the user
=> PWGCF: set twoTrackCuts flag to false by default

PWGCF/Correlations/DPhi/AliAnalysisTaskPhiCorrelations.cxx
This changes some unused parameters of the FillCorrelations method used in the AliAnalysisTaskPhiCorrelations task:
- Mark them as 0 or -1 to show that they are not used at all in this configuration
- This should not influence the analysis at all but makes it easier to read the code
=> PWGCF: modify unused params

PWG/EMCAL/EMCALbase/AliEmcalPythiaFileHandler.cxx
ESD type determination needs to be done at the
beginning of the function, similar as done for AODs
as the path becomes modified later and the type
no longer is available.
=> [PWGJE-23] Fix ESD type determination

PWGGA/GammaConv/AliAnalysisTaskGammaIsoTree.cxx, PWGGA/GammaConv/AliAnalysisTaskGammaIsoTree.h, PWGGA/GammaConv/macros/AddTask_GammaIsoTree.C
- fixed loading of clusters which previously caused memory problems when running over multiple train configs in one train
- added trackingQA histos to check pPb with partial TPC coverage
- added primary track multiplicity to tree to study efficiency
- changed perp cone to include left _and_ right side in phi (previously only left), area is now 2xcone
=> PWGGA/GammaConv: GammaIsoTree fixed bug in cluster processing & more

PWG/EMCAL/EMCALbase/AliClusterContainer.cxx, PWG/EMCAL/EMCALbase/AliClusterContainer.h, PWG/EMCAL/EMCALbase/AliEMCALRecoUtils.cxx, PWG/EMCAL/EMCALbase/AliEMCALRecoUtils.h, PWG/EMCAL/EMCALtasks/AliEmcalCorrectionClusterLowEnergyEfficiency.cxx, PWG/EMCAL/EMCALtasks/AliEmcalCorrectionClusterLowEnergyEfficiency.h, PWG/EMCAL/EMCALtasks/CMakeLists.txt, PWG/EMCAL/EMCALtasks/PWGEMCALtasksLinkDef.h, PWG/EMCAL/READMEemcCorrections.txt, PWG/EMCAL/config/AliEmcalCorrectionConfiguration.yaml, PWGGA/GammaConv/macros/AddTask_GammaCalo_pp.C, PWGGA/GammaConv/macros/AddTask_GammaConvCalo_pp.C, PWGGA/GammaConvBase/AliCaloPhotonCuts.cxx
This new correction component corrects the mismatch between the fraction of 1 cell clusters in MC and data.
A larger fraction of 1 cell clusters are observed in MC. The new correction flags a fraction of the 1 cell clusters via the Chi2() variable, those cells are then treated as if they would have 2 cells and thus passing the exotics and M02/M20 cut.
- The correction can be added via the yaml file with: ClusterLowEnergyEfficiency
- The functions for the corrections are still under preparation. For now the functions: kGammaAndElec or kAllClusters should be considered
=> PWG/EMCAL: Adding correction component for low energetic clusters

PWGGA/GammaConv/AliAnalysisTaskGammaIsoTree.cxx, PWGGA/GammaConv/AliAnalysisTaskGammaIsoTree.h
- implemented a check that avoids a crash in very rare cases where cluster has no labels
- added some missing renaming from Left -> Perp to include both sides of cone
=> PWGGA/GammaConv: GammaIsoTree fix for rare case of missing label

PWGHF/vertexingHF/AliAnalysisTaskSELc2pKs0fromKFP.cxx, PWGHF/vertexingHF/AliAnalysisTaskSELc2pKs0fromKFP.h, PWGHF/vertexingHF/macros/AddTaskLc2pKs0FromKFParticle.C
- added Ntrk and Ntrk_corr (with zvtx correction procedure) to branches of output tree
- added flag to keep only the signal from MC in the output tree
- reordered initialisers to get rid of compilation warnings (minor)
=> additions to Lc->V0 KF analysis task

OADB/COMMON/MULTIPLICITY/AliMultEstimator.cxx, OADB/COMMON/MULTIPLICITY/AliMultEstimator.h, OADB/COMMON/MULTIPLICITY/AliMultInput.cxx, OADB/COMMON/MULTIPLICITY/AliMultInput.h, OADB/COMMON/MULTIPLICITY/AliMultSelection.h, OADB/COMMON/MULTIPLICITY/AliMultSelectionCalibrator.cxx, OADB/COMMON/MULTIPLICITY/AliMultSelectionCalibrator.h, OADB/COMMON/MULTIPLICITY/AliMultSelectionTask.cxx, OADB/COMMON/MULTIPLICITY/AliMultSelectionTask.h, OADB/COMMON/MULTIPLICITY/AliMultVariable.cxx, OADB/COMMON/MULTIPLICITY/AliMultVariable.h, OADB/COMMON/MULTIPLICITY/AliOADBMultSelection.cxx, OADB/COMMON/MULTIPLICITY/AliOADBMultSelection.h
This is a first commit of the changes to do automated vertex-Z calibrations with AliMultSelection for a re-calibration of pp and beyond. Further details can be seen in this [DPG AOT Events talk](https://indico.cern.ch/event/1012785/contributions/4250669/attachments/2201593/3723832/DDChinellato-VertexZ.pdf). 
This change has been extensively verified to have no impact on any of the operational OADBs in the framework and no OADB was touched so far. The point of this commit is to be able to run grid tests with customized wagons of AliMultSelection + brand-new OADBs with this functionality.
=> Changes for automatic vertex-Z calibration in MultSelection

PWG/EMCAL/EMCALbase/AliAnalysisTaskEmcal.cxx, PWG/EMCAL/EMCALbase/AliClusterContainer.cxx, PWG/EMCAL/EMCALbase/AliClusterContainer.h, PWG/EMCAL/EMCALbase/AliEmcalList.cxx, PWG/EMCAL/EMCALbase/AliEmcalList.h, PWG/EMCAL/EMCALbase/AliMCParticleContainer.cxx, PWG/EMCAL/EMCALbase/AliMCParticleContainer.h, PWG/EMCAL/EMCALbase/AliParticleContainer.cxx, PWG/EMCAL/EMCALbase/AliParticleContainer.h, PWG/EMCAL/EMCALbase/AliTrackContainer.cxx, PWG/EMCAL/EMCALbase/AliTrackContainer.h
Reasons:
- Source files are not always available
- Prevents splitting documentation over source
and header file
- Modern tools (i.e. Xcode, Visual Studio Code, ...)
can make use of the documentation in order to
provide hints to the user while coding, but only
the header files are checked for documentation
=> [Doxygen] Move documentation in classes in EMCALbase consistently into header files

PWGGA/GammaConv/AliAnalysisTaskElectronStudies.cxx, PWGGA/GammaConv/AliAnalysisTaskElectronStudies.h, PWGGA/GammaConv/AliAnalysisTaskGammaIsoTree.cxx, PWGGA/GammaConv/config/PWGGA_CF_config.yaml, PWGGA/GammaConv/macros/AddTask_ElectronStudies.C
- ElectronStudies: switched to runningmode=7 using all hybrid tracks for matching
- ElectronStudies: implemented proper matching of tracks from V0
- GammaIsoTree: fixed trackQA histos being filled at the wrong time
- CF Framework: data yaml file had slight inconsistency with data. Added    
remapMcAod: false
diffEAggregation: 0.0
=> PWGGA/GammaConv: ElectronStudies TM changes

PWG/EMCAL/EMCALtasks/AliAnalysisTaskEmcalTriggerNormalization.cxx, PWG/EMCAL/EMCALtasks/AliAnalysisTaskEmcalTriggerNormalization.h
- Add luminosity histogram filled for min. bias with
number of events and for EMCAL triggers with
downscale-corrected min. bias events * emcal
trigger downscale factor
- Check run-by-run whether EMCAL triggers were
active based on CTP configuration in the OCDB
and fill histograms for EMCAL triggers only if the
trigger was active
- Add histograms for trigger cluster counter based
on triggered events
=> Add luminosity histogram and trigger cluster counters

PWGCF/FEMTOSCOPY/FemtoDream/AliFemtoDreamCollConfig.cxx, PWGCF/FEMTOSCOPY/FemtoDream/AliFemtoDreamCollConfig.h, PWGCF/FEMTOSCOPY/FemtoDream/AliFemtoDreamControlSample.cxx, PWGCF/FEMTOSCOPY/FemtoDream/AliFemtoDreamControlSample.h, PWGCF/FEMTOSCOPY/FemtoDream/AliFemtoDreamHigherPairMath.cxx, PWGCF/FEMTOSCOPY/FemtoDream/AliFemtoDreamHigherPairMath.h, PWGCF/FEMTOSCOPY/FemtoDream/AliFemtoDreamZVtxMultContainer.cxx, PWGCF/FEMTOSCOPY/FemtoDream/AliFemtoDreamZVtxMultContainer.h
Hi there,
I have implemented a cut for the sum of the transverse momenta of the pair (pT1 + pT2). Only pairs within specified limits (limit1 < summed pT < limit2) will be used for the same-event distribution. The default values of the limits are: limit1 = 0.0 and limit2 = 999.0. These limits can be changed using "config->SetSummedPtCut(limit1,limit2)" in the AddTask.
regards
Michael
=> add a pT cut for the summed pTs of the pair

PWG/EMCAL/EMCALtasks/AliAnalysisTaskEmcalTriggerNormalization.cxx, PWG/EMCAL/EMCALtasks/AliAnalysisTaskEmcalTriggerNormalization.h
Define default configuration for various datasets
(pp 13 TeV, p-Pb at various energies and years,
...), and use run number to select proper
configuration.
=> Automatically configure trigger normalization task based on run numbers

PWG/EMCAL/EMCALbase/AliAnalysisTaskEmcal.cxx, PWG/EMCAL/EMCALbase/AliAnalysisTaskEmcal.h, PWGJE/EMCALJetTasks/Tracks/AliAnalysisTaskEmcalJetEnergySpectrum.cxx, PWGJE/EMCALJetTasks/Tracks/AliAnalysisTaskEmcalJetEnergySpectrum.h
- Add function to get the cross section weight in
AliAnalysisTaskEmcal for the current event (PYTHIA
or HepMC only)
- Add option in jet spectrum task to use the cross
section weight to reweight the spectra on-the-fly
=> Add function ot obtain cross section weight from event header to AliAnalysisTaskEmcal

PWGGA/GammaConv/AliAnalysisTaskOmegaToPiZeroGamma.cxx
- Added previously missing check in rotation method when combining a pi0 from an original cluster and a changed cluster with another original cluster, that the two original clusters are not the same.
=> PWGGA/GammaConv: OmegaToPiZeroGamma Rotation Method Hotfix

PWGGA/GammaConv/AliAnalysisTaskGammaCaloDalitzV1.cxx, PWGGA/GammaConv/AliAnalysisTaskGammaConvDalitzV1.cxx, PWGGA/GammaConv/AliAnalysisTaskGammaConvDalitzV1.h, PWGGA/GammaConv/macros/AddTask_GammaConvDalitzV1_pp.C, PWGGA/GammaConvBase/AliDalitzElectronCuts.cxx, PWGGA/GammaConvBase/AliDalitzElectronCuts.h
New implementation in the Psipair, Optimization at 5 and 8 %, plus histograms to study the invariant mass of the electron-positron coming from the primary vertex
=> New 3D PsiPair Cut

PWGLF/STRANGENESS/Ratios/AliAnalysisTaskStrangenessRatios.cxx, PWGLF/STRANGENESS/Ratios/AliAnalysisTaskStrangenessRatios.h
Not all the generated particles were filled into the tree (check performed locally on single AliAOD.root files). In addition the trees of Omega and Xi have been merged to reduce the output size especially on data (expected a 20% reduction) even if the present solution is not yet optimal (in my opinion)
=> solved problem on missing generated particles + merged trees of Omega and Xi

PWGGA/GammaConv/AliAnalysisTaskGammaIsoTree.cxx, PWGGA/GammaConv/AliAnalysisTaskGammaIsoTree.h, PWGGA/GammaConv/macros/AddTask_GammaIsoTree.C, PWGGA/GammaConvBase/AliConvEventCuts.cxx
- added geometrical correction to properly account for missing energy in cone when outside TPC acceptance
- added fixes to AliConvEventCuts to ensure that edge cases where  pthard is below lowest threshold get treated properly
=> PWGGA/GammaConv: GammaIsoTree added iso correction for cone outside TPC

PWGJE/EMCALJetTasks/Tracks/AliAnalysisTaskEmcalSoftDropData.cxx
Workaround which would be handled in a safer way
with std::optional from c++17, but since we are forced
to be compatible with ancient ROOT5 and cannot
profit from the various improvement coming from
c++17 this workaround is needed.
=> Stupid ROOT5

PWG/EMCAL/EMCALtasks/AliEmcalCorrectionClusterHadronicCorrection.cxx, PWG/EMCAL/EMCALtasks/AliEmcalCorrectionClusterHadronicCorrection.h, PWG/EMCAL/config/AliEmcalCorrectionConfiguration.yaml
Make parameters for cut function settable in order
to be able to vary them for systematics studies.
=> Make pt-dependent matching params in had corr. settable

PWGLF/NUCLEX/Nuclei/Nuclei_UE/AliAnalysisTaskDeuteronsRT.cxx, PWGLF/NUCLEX/Nuclei/Nuclei_UE/AliAnalysisTaskDeuteronsRT.h
Added extra dimension for PID systematics (TPC & TOF).
Added DCA_{xy} variations into track cuts
Successfully tested on the GRID.
=> Added cut variations for DCA_{xy} and PID

PWGGA/GammaConv/AliAnalysisTaskGammaConvDalitzV1.cxx, PWGGA/GammaConv/AliAnalysisTaskGammaConvDalitzV1.h, PWGGA/GammaConvBase/AliDalitzElectronCuts.cxx, PWGGA/GammaConvBase/AliDalitzElectronCuts.h
Correction to Background histograms in terms of the invariant mass of the electron-positron pair and correction to lineal dependence in PsiPair.
=> PWGGA/GammaConv: Fixing problem for a case 1 in PsiPair

PWG/EMCAL/EMCALtasks/AliAnalysisTaskEmcalTriggerNormalization.cxx
Cluster CALOFAST was missing, resulting in a segfault
when initializing the trigger cluster counters.
=> Add missing trigger cluster

PWG/EMCAL/EMCALtasks/AliAnalysisTaskEmcalTriggerNormalization.cxx
Trigger clusters were shifted by 1 (value vs ID),
therefore entries were appearing for shifted
labels. Corrected with this commit.
=> Correct shift for trigger cluster index

PWGHF/vertexingHF/AliHFSystErr.cxx, PWGHF/vertexingHF/AliHFSystErr.h
1. In the first commit as discussed and agreed with @fgrosa, the default name of AliHFSystErr object in the constructor is moved to "AliHFSystErr" that is the default used in all macros.
2. In the second commit the naming of D0 syst err has been fixed
=> Fixing naming of AliHFSystErr objects

PWG/EMCAL/EMCALtasks/AliAnalysisTaskEmcalTriggerNormalization.cxx, PWG/EMCAL/EMCALtasks/AliAnalysisTaskEmcalTriggerNormalization.h
- Bugfix in filling norm hist and cluster counter for
DMC7 and DG1 (missing "," in trigger class vector)
- Add mixed triggers to trigger downscale factor
cache if at least one trigger (EMCAL or DCAL) is
present. If both are found the downscale factor
is taken from the EMCAL side.
=> Bugfix for DMC7 and DG1 trigger + support for mixed trigger

PWG/FLOW/Base/AliFlowEventSimpleMakerOnTheFly.cxx
**Memory Leaks**
When pTracks are rejected from the sample, the pointer was not deleted. Especially for a low mean acceptance, this causes OOM issues when scaling to many collisions. This has been addressed.
**Optimization**
When pTracks are checked for acceptance, it is more efficient to do this straight after the relevant properties are set. In simulations performed with a low mean acceptance rate for some ranges of properties, this reduced execution time by orders of magnitude (e.g. ~1e5 seconds to ~2e3 seconds). Re-ordering some of the operations addresses this.
=> AliFlowEventSimpleMakerOnTheFly.cxx memory leak fix and optimization

PWGGA/GammaConvBase/AliConversionMesonCuts.cxx
- Firstly, now only checks the angle between the gamma cluster coming
from the omega and the two gamma clusters coming from the Pi0. The
OAC for the two Pi0 gamma clusters should be handled by the Pi0MesonCuts
when calling MesonIsSelected!
- Secondly, now only one angle needs to be smaller or bigger instead of
all angles to reject the omega candidate
Some blank changes are made automatically by my editor. Sorry for that.
=> PWGGA/GammaConvBase: Changed MesonIsSelectedPiZeroGammaOAC

PWGHF/vertexingHF/vHFML/AliAnalysisTaskSEHFTreeCreatorApply.cxx
In recent MCs I noticed crashes due to zero pointer V0. Added safety check
=> PWGHF: Add safety check for V0

PWGJE/EMCALJetTasks/UserTasks/AliAnalysisTaskEmcalJetEnergyFlow.cxx
Adjustment of the Eta selection on jet containers used in the JetEnergyFlow task found in: PWGJE/EMCalJet/UserTasks/AliAnalysisTaskEmcalJetEnergyFlow.cxx  in preparation for LEGO train runs.
=> Adjustment of the jet eta selection in AliAnalysisTaskEmcalJetEnergyFlow

PWGHF/hfe/AliAnalysisTaskEHCorrel.cxx, PWGHF/hfe/AliAnalysisTaskEHCorrel.h, PWGHF/hfe/AliAnalysisTaskHFEBESpectraEMC.cxx, PWGHF/hfe/macros/AddTaskEHCorrel.C
EH Correlation:
- Add switch to change DeltaPhi bins in THnsparse
- Add switch for MC to apply exotic cluster removal, EMCal cluster TOF cut only in data
HFEBEtask:
- Add switch for MC to apply exotic cluster removal, EMCal cluster TOF cut only in data
=> Adding option for DeltPhi bins, isMC

PWGHF/vertexingHF/AliAnalysisTaskHFSimpleVertices.cxx, PWGHF/vertexingHF/AliAnalysisTaskHFSimpleVertices.h
@vkucera Align code with O2 implementation https://github.com/AliceO2Group/AliceO2/pull/5832 and in the validation code https://github.com/AliceO2Group/Run3Analysisvalidation/pull/184
@fprino it fixes also a small detail in the methods to read arrays / matrices from JSON files that prevented to correctly read arrays and matrices not at the end of the JSON entry
=> Adapt single track cuts to be read from 2D matrices

PWGHF/jetsHF/AliHFJetsTaggingVertex.cxx
Just addition of a few deletions. With these leaks I am unable to run analysis on the LEGO train [(test syswatch.png)](http://alitrain.cern.ch/train-workdir/PWGHF/HFCJ_pp_MC/1128_20210326-0631/test/__ALL__/syswatch.png).
=> [PWGHF] Fix memory leaks in AliHFJetsTaggingVertex

PWGHF/vertexingHF/AliHFInvMassMultiTrialFit.cxx
Multitrial fitter crashed in case background only fit failed (when `Background()` in `Significance()` was called). Added safety check using return of fitter
=> PWGHF: Fix for multitrial fitter

PWGMM/UE/UeKNO/AliAnalysisTaskGenMcKno.cxx
This commit increases the multiplicity reach in the generation macro for Pb-Pb collisions.
=> Increase of multiplicity reach for Pb-Pb

RUN3/AliAnalysisTaskAO2Dconverter.cxx
Due to the non-standard way to handle the output file in the AO2D conversion task, we need to create an un-connected output container having as output file AO2D.root. This helps the system in the lego environment understand that this file needs to be registered, which is not the case when running the wagon standalone in a train.
=> Registering output container connected to AO2D.root file.

RUN3/AliAnalysisTaskAO2Dconverter.cxx
This change is to avoid that the parameter "Sign/pT" takes the value zero, which would cause division by zeros in the in the evaluation of pT.
=> Small Fix on MUON tracks AOD converter to RUN3 forward coordinate system

PWGGA/GammaConv/AliAnalysisTaskGammaIsoTree.cxx, PWGGA/GammaConv/AliAnalysisTaskGammaIsoTree.h, PWGGA/GammaConvBase/AliCaloPhotonCuts.cxx, PWGGA/GammaConvBase/AliCaloPhotonCuts.h, PWGGA/GammaConvBase/AliConvEventCuts.cxx, PWGGA/GammaConvBase/AliConvEventCuts.h
- added weights for new MC productions LHC21d2a, LHC21d2b and LHC21d2c which were obtained using local running
- added additional trackphi histogram to GammaIsoTree task
=> PWGGA/GammaConv: added weigths for LHC21d[a,b,c] MCs

PWG/EMCAL/EMCALtasks/AliAnalysisTaskEmcalTriggerSelection.cxx, PWGJE/EMCALJetTasks/Tracks/AliAnalysisTaskEmcalTriggerBase.cxx
Typo leading to misconfiguration when running on
J/Psi MC sample anchored to 2018 pp 13 TeV. Bug
introduced in AliPhysics/#17611
=> Add missing "," separating datasets

RUN3/AliAnalysisTaskAO2Dconverter.cxx
Modification to skip muon tracks which parameters are left to thir default values. These tracks don't correspond to real muon tracks and can cause crashes if converted.
=> Correction on MUON tracks AOD converter to RUN3 forward coordinate system

PWGLF/STRANGENESS/Ratios/AliAnalysisTaskStrangenessRatios.cxx, PWGLF/STRANGENESS/Ratios/AliAnalysisTaskStrangenessRatios.h
Several new cuts added:
- OOB pileup rejection for generated
- TPC rows, crossed rows / findable clusters
- |eta|<0.8
- isPhysicalPrimary
- rapidity cut on generated (as for reco)
=> added many cuts, more important: OOB pileup for generated

PWG/EMCAL/EMCALbase/AliEMCALRecoUtils.cxx, PWG/EMCAL/EMCALbase/AliEMCALRecoUtils.h, PWG/EMCAL/EMCALtasks/AliEmcalCorrectionClusterLowEnergyEfficiency.cxx, PWG/EMCAL/EMCALtasks/AliEmcalCorrectionClusterLowEnergyEfficiency.h, PWG/EMCAL/EMCALtasks/AliEmcalCorrectionClusterNonLinearityMCAfterburner.cxx, PWG/EMCAL/config/AliEmcalCorrectionConfiguration.yaml, PWGGA/GammaConv/macros/AddTask_GammaCalo_pp.C, PWGGA/GammaConv/macros/AddTask_GammaConvCalo_pp.C, PWGGA/GammaConvBase/AliCaloPhotonCuts.cxx
New function for NCell efficiency based on (PCM-EMC) pi0 tagged photon clusters. 
Added a switch for th NCell efficiency to apply it only on photon clusters if wanted.
Added special treatment for 1 cell clusters in the MC cluster energy fine tuning, because non-linearity for 1 cell clusters different than for >= 2 cell clusters.
In PWGGA/GammaConv: 
Modified configs for PCM-EMC and EMC to check implementation in CF vs in AliCaloPhotonCuts
Modified (and simplified) Non-Linearity for 1 cell clusters in AliCaloPhotonCuts
=> PWG/EMCAL: Added new function for NCell efficiency and modified energy fine tuning for 1 cell clusters

PWGGA/GammaConv/AliAnalysisTaskOmegaToPiZeroGamma.cxx, PWGGA/GammaConv/AliAnalysisTaskOmegaToPiZeroGamma.h, PWGGA/GammaConvBase/AliConversionMesonCuts.cxx, PWGGA/GammaConvBase/AliConversionMesonCuts.h
- Replaced the function which was used to determine the lower and upper bound for the angle between PiZero and Gamma with two separate functions
- Changed the corresponding function in AliConversionMesonCuts
=> PWGGA/GammaConv(Base): OmegaToPiZeroGamma - changed OAC Pi0 Gamma Function

PWG/FLOW/Tasks/AliAnalysisTaskMuPa.cxx
The compilation on MacOS was failing because of the missing "#include <unistd.h>". 
This compilation issue is fixed after including unistd.h in the .cxx of the task.
=> Add include unistd.h for compilation on MacOS

PWGHF/vertexingHF/AliAnalysisTaskSED0Mass.cxx, PWGHF/vertexingHF/AliAnalysisTaskSED0Mass.h
Adding flag to activate the splitting of candidates for R/S studies. The default of the flag is kFALSE.
It will fill the output for three cases separately:
- only D0
- only D0bar
- D0D0bar
=> Add flag and method for R/S study

PWGJE/EMCALJetTasks/AliFJWrapper.h
It seems to only occur with jemalloc (ie. on the grid)
@lhavener
=> Attempt to fix memory leak in event-wise CS

PWGJE/EMCALJetTasks/CMakeLists.txt, PWGJE/EMCALJetTasks/PWGJEEMCALJetTasksLinkDef.h, PWGJE/EMCALJetTasks/Tracks/AliAnalysisTaskEmcalRawSTU.cxx, PWGJE/EMCALJetTasks/Tracks/AliAnalysisTaskEmcalRawSTU.h, PWGJE/EMCALJetTasks/macros/AddTaskEmcalRawSTU.C
Mainly in order to check the acceptance of the
trigger at L1
- Purely rely on information in AliVCaloTrigger
- Monitor trigger classes and
combined/mixed/exclusive classes between
EMCAL and DCAL (no distinction between high
and low threshold)
=> Add simple analysis task monitoring the patch position of online patches from STU data

PWGDQ/reducedTree/AliReducedVarManager.cxx, PWGDQ/reducedTree/AliReducedVarManager.h
Adding efficiency weight in PWGDQ/reducedTree/AliReducedVarManagerin in order to enable propagating of leg PID efficiency to the pair level via standard J/psi MC
=> Adding efficiency weight in order to propagte leg PID efficiency to the pair level

PWG/EMCAL/EMCALtrigger/AliEmcalTriggerMakerTask.cxx
In case a DCAL TRU is masked in the STU the global
TRU index need to be used. The global TRU index  is
including TRUs in EMCAL STU region and virtual TRUs
in PHOS region. As luckly the only the EMCAL TRUs
were masked by mistake, and the DCAL 1/3rd
supermodules were dead in readout as well the bug
did not harm so far.
=> Fix masking of DCAL TRUs

PWG/EMCAL/CMakeLists.txt, PWG/EMCAL/Doxymodules.h, PWG/EMCAL/EMCALbase/AliEmcalAODHybridTrackCuts.h, PWG/EMCAL/EMCALbase/AliEmcalTrackSelResultPtr.h, PWG/EMCAL/EMCALbase/AliEmcalTrackSelectionAOD.h, PWG/EMCAL/EMCALtrigger/AliEmcalFastorMaskContainer.cxx, PWG/EMCAL/EMCALtrigger/AliEmcalFastorMaskContainer.h, PWG/EMCAL/EMCALtrigger/CMakeLists.txt, PWG/EMCAL/EMCALtrigger/PWGEMCALtriggerLinkDef.h, PWG/EMCAL/macros/TestAliEmcalFastorMaskContainer.C
- Mask can have status dead or bad
- FastORs handled via FastOr abs ID
- Container browsable, in this case a
2D col-row plot is created
- Corresponding unit tests added for
- In-memory set/get
- ROOT File-I/O
- Modify
- Clean
=> Add container class for offline trigger mask

PWG/EMCAL/EMCALtrigger/AliEmcalTriggerMakerKernel.h, PWG/EMCAL/EMCALtrigger/AliEmcalTriggerMakerTask.cxx, PWG/EMCAL/EMCALtrigger/AliEmcalTriggerMakerTask.h
Support for both types of trigger mask containers
(new trigger mask container and old TObjArray with
list of FastORs) implemented, however on in case of
the new trigger mask container it is possible to
distinguish bad from dead channels and therefore
allow to enable/disable them separately.
=> Add handling for offline trigger mask via trigger mask container

PWG/EMCAL/EMCALtrigger/AliEmcalFastorMaskContainer.cxx
Based on the implementation of
AliEMCALTriggerMapping access to the EMCAL
geometry is mandatory. The geometry is initialized
based on the name of the geometry, selecting for
run2 the standard geometry and for run1 the
geometry from 2013, as the TRU layout for the
existing supermodules has no effects on earlier
setups in run1 with partial geometry.
=> Fix browse function

PWGJE/EMCALJetTasks/AliAnalysisTaskJetChargeFlavourTemplates.cxx
since the charge on a particle level track are in units of 1/3 e instead of units of e. Thus correcting the mistake causing Particle level templates to be much broader.
=> Dividing the Charge Particle level tracks by 3 

PWG/EMCAL/EMCALbase/AliAnalysisTaskEmcal.cxx, PWG/EMCAL/EMCALbase/AliAnalysisTaskEmcal.h, PWGJE/EMCALJetTasks/Tracks/AliAnalysisTaskEmcalJetEnergySpectrum.cxx, PWGJE/EMCALJetTasks/Tracks/AliAnalysisTaskEmcalJetEnergySpectrum.h, PWGJE/EMCALJetTasks/Tracks/AliAnalysisTaskEmcalJetSpectrumSDPart.cxx, PWGJE/EMCALJetTasks/Tracks/AliAnalysisTaskEmcalJetSpectrumSDPart.h
Getter only implemented for pythia and HepMC-based
productions. Use getter also in the spectrum and
part. level task. In case of the jet analysis task the
user has to define whether apply cross section or
event weighting.
=> Add getter for event weight (weighted production) in AliAnalysisTaskEmcal

PWG/EMCAL/EMCALtrigger/AliEmcalTriggerMaskHandlerOCDB.cxx, PWG/EMCAL/EMCALtrigger/AliEmcalTriggerMaskHandlerOCDB.h
- Plotting masked channels as histogram
- For easy reading a grid separating FastORs,
TRUs and Supermodules is added as well. The
grid is shown based on run1 or run2 geometry
depending on the run number
=> Add plotting function for easy plotting of the L0 trigger mask for a given run

PWG/EMCAL/EMCALtrigger/AliEmcalTriggerMaskHandlerOCDB.cxx, PWG/EMCAL/EMCALtrigger/AliEmcalTriggerMaskHandlerOCDB.h
The mask for the 1/3rd supermodules is the same as
in run1, while the masking handler tried to apply the
run2 mapping. Fixed in the way that the mapping
handlers need an argument for the SM type, and in
case it is the 1/3 type the old mapping is applied.
=> Fix handling of the 1/3rd supermodules in run2

PWG/EMCAL/EMCALtrigger/AliEmcalTriggerMakerTask.cxx, PWG/EMCAL/EMCALtrigger/AliEmcalTriggerMakerTask.h, PWG/EMCAL/EMCALtrigger/AliEmcalTriggerMaskHandlerOCDB.cxx
Use mask handler for trigger mask reading from the
OCDB and remove builting trigger mask reading. With
this the same code can be used for visualization of the
trigger mask and utilization in the trigger maker, so
the trigger maker can make use of a well tested and
unit-testable code.
=> Use mask handler in trigger maker to read OCDB trigger mask

PWG/EMCAL/EMCALbase/AliEMCALRecoUtils.cxx, PWG/EMCAL/EMCALbase/AliEMCALRecoUtils.h, PWG/EMCAL/EMCALtasks/AliEmcalCorrectionCellEnergy.cxx, PWG/EMCAL/EMCALtasks/AliEmcalCorrectionCellEnergy.h, PWG/EMCAL/config/AliEmcalCorrectionConfiguration.yaml
This can be configured in the yaml file via "enableAdditionalScale" which is set to 1 (no modification) as default. This functionality is introduced to make checks for future cell calibrations, it is not supposed to be used for physics analyses!
=> PWG/EMCAL: Added possibility to modify/scale the cell energy

PWG/EMCAL/EMCALbase/AliEmcalList.cxx, PWG/EMCAL/EMCALbase/AliEmcalList.h
Exclude historgrams with tag "PtHard" from list of
scaling histograms (affects only tasks based on
AliAnalysisTaskEmcalLight. Also add getters for
the scaling histogram names for user access.
=> Adjust scaling histograms for AliAnalysisTaskEmcalLight

PWG/EMCAL/EMCALtrigger/AliEmcalTriggerMaskHandlerOCDB.cxx, PWG/EMCAL/EMCALtrigger/AliEmcalTriggerMaskHandlerOCDB.h
- Add draw funtion for mask at L1 similar to the draw
function for the mask at L0
- Don't delete the cache object, just set the pointer to
nullptr, because the handler does not have
ownership of the OCDB entry of the DCS config
=> Draw L1 mask and fix double delete

PWGHF/vertexingHF/AliRDHFCutsKFP.cxx, PWGHF/vertexingHF/AliRDHFCutsKFP.h
add functionality to AliRDHFCutsKFP to exclude daughter tracks from primary vertex
=> Add vertex recalculation to AliRDHFCutsKFP

PWGGA/GammaConv/AliAnalysisTaskGammaCaloMergedML.cxx
The trees of my analysis will now also be connected to the output for JJ MC-events, which was previously not the case.
=> PWGGA/GammaConv: Fixed output for JJ MC-Events in my Analysis

OADB/EMCAL/READMEoadb.txt
PAR information provided by Adam in file ReferenceSM_LHC2016j_PAR_v3.root as documented in the jira ticket
=> [EMCAL-632] OADB/EMCAL: Update of EMCALTimeL1PhaseCalib.root with PAR for run 256227 in LHC16j

PWGHF/vertexingHF/AliAnalysisTaskSELc2pKs0fromKFP.cxx
add functions to LcKF analysis task to allow recalculation of primary vertex with decay daughters subtracted, using method in AliRDHFCuts::RecalcOwnPrimaryVertex()
=> Add daughter subtraction to LcKF analysis task

RUN3/AliAnalysisTaskAO2Dconverter.cxx, RUN3/AliAnalysisTaskAO2Dconverter.h
A bitmap for the 10 muon chabers (each bit is equal to 1 if the chamber is fired) is saved into the AO2D. 
It propagates the information from AliESDMuonTrack::fMuonClusterMap
=> AliPhysics Run3 converter saves a bitmap with fired muon chambers

PWGHF/vertexingHF/AliHFSystErr.cxx
Update following systematic uncertainties:
- BR from 0.04% to 0.8%
- normalization from 4% to 2.2% (010) and 3.3% (3050)
for D0 -> K+pi, Pb-Pb (2018 pass3) analysis
=> Update D0 BR and norm. syst. unc. (2018 - PbPb pass3)

PWG/EMCAL/EMCALtasks/AliEmcalMCTrackSelector.cxx, PWG/EMCAL/EMCALtasks/AliEmcalMCTrackSelector.h, PWGJE/EMCALJetTasks/Tracks/AliAnalysisTaskEmcalJetEnergyScale.cxx, PWGJE/EMCALJetTasks/Tracks/AliAnalysisTaskEmcalSoftDropResponse.cxx
- Add phys. primary flag for pi0 and remove phys.
primary flag of daughter particles in MC track
selector
- Add monitoring histograms for Pi0, K0s and gamma
in response matrix tasks (pp-only)
=> Add option to treat Pi0s as stable particles

PWGHF/vertexingHF/AliHFSystErr.cxx
Update D*+ systematic uncertainties for analysis of 2018 Pb-Pb (pass3) data sample.
All sources have been updated excepted for Selection efficiency (i.e. cut variation).
@sjaelani is the author of the uncertainties
=> Update D*+ syst (Pb-Pb 2018 pass3)

PWGGA/GammaConv/AliAnalysisTaskOmegaToPiZeroGamma.cxx, PWGGA/GammaConv/macros/AddTask_OmegaToPiZeroGamma_pp.C
- Added cluster cut variations (train configs X9X1 till X9X6) for:
1. NonLin
2. timing
3. track matching
4. exotic cluster
5. Ncell
6. M02 max
- changed the ordering of some train configs, so they are grouped together in a more logical sense
- Increased Pi0 pT binning from 20 to 30 GeV/c as the max value
=> PWGGA/GammaConv: OmegaToPiZeroGamma - Added Cluster Cut Variations

PWGHF/vertexingHF/AliAnalysisTaskSELc2pKs0fromKFP.cxx
Add the Combined nSigma of the pion for the expected proton track to the reconstruction tree. This variable is meant as an exclusion cut for the proton based on the Pion PID combining the TPC and TOF detector.
=> Add Combined nSigma of pion for expected proton track as exclusion

PWGHF/vertexingHF/AliAnalysisTaskSELc2pKs0fromKFP.cxx
Fix name: nSigmaTPC_bach_pi was overwritten. It is meant to be nSigmaTOF_bach_pi.
=> Fix for overwriting nSigmaTPC_bach_pi. Set to nSigmaTOF_bach_pi.

RUN3/AliAnalysisTaskAO2Dconverter.cxx
This should fix FPEs observed in Grid conversion jobs.
=> Change condition in conversion task for avoid division by 0.

PWGHF/hfe/AliAnalysisTaskEHCorrel.cxx, PWGHF/hfe/AliAnalysisTaskEHCorrel.h, PWGHF/hfe/macros/AddTaskEHCorrel.C
Adding an option to remove out-of-bunch pileup particles in the MC generated particle stack
=> Add option to remove pile-up particles in MC Gen

PWGGA/GammaConvBase/AliCaloPhotonCuts.cxx
The previous parameters were calculated in a wrong way leading to wrong
parameters
=> PWGGA/GammaConv: Changed new NonLin parametriziation parameters

PWGLF/STRANGENESS/Ratios/AliAnalysisTaskStrangenessRatios.cxx
FYI @mpuccio I had to change this line because my compiler seems not to like narrowing conversions in initializer lists
=> fix narrowing conversion error

PWGDQ/dielectron/core/AliDielectronVarManager.h
included the charge sign in the definition to exclude the charge assymmetry between ULS and LS
=> PWGDQ:LMee: changed variable definition in VarMangager.h

PWGLF/RESONANCES/AliRsnCutMiniPair.cxx, PWGLF/RESONANCES/AliRsnCutMiniPair.h, PWGLF/RESONANCES/macros/mini/AddTaskF0.C
The commit includes option for pT cut on generated MC. This is necessary for f0 analysis in pp collisions at 5.02 TeV.
=> Option for pT cut on generated MC

PWGCF/FEMTOSCOPY/FemtoDream/AliAnalysisTaskGeorgiosNTuple.cxx, PWGCF/FEMTOSCOPY/FemtoDream/AliAnalysisTaskGeorgiosNTuple.h, PWGCF/FEMTOSCOPY/macros/AddTaskGeorgiosNTuple.C
Setting new open Cuts for systematic variations and releasing timing information for the Pion Track of the Xi candidates
=> Increasing statistics: More open cuts for systematics + timing condition relaxed

PWG/EMCAL/EMCALtasks/AliAnalysisTaskEmcalTriggerNormalization.cxx, PWG/EMCAL/EMCALtasks/AliAnalysisTaskEmcalTriggerNormalization.h
Correlation histograms are implemented for each
trigger cluster separately. Diagonal elements are
absolute event counters, off-diagonal elements
show the correlation with the trigger.
Mainly used to cross check downscale factors.
=> Add correlation histograms for trigger classes

PWG/EMCAL/EMCALbase/AliClusterContainer.cxx, PWG/EMCAL/EMCALbase/AliClusterContainer.h
- Cut by default 0 (= no cut)
- In case the 1-cell clusters are included the
cut is bypassed in case a 1-cell cluster is found
in the same way as for the exoticity cut and the
shower shape cut
- Be more explicit with parameter names in the
interface for better readability
=> feature-ncellcut

PWG/EMCAL/EMCALbase/AliEMCALRecoUtils.cxx, PWG/EMCAL/EMCALbase/AliEMCALRecoUtils.h, PWG/EMCAL/EMCALtasks/AliEmcalCorrectionClusterLowEnergyEfficiency.cxx, PWG/EMCAL/EMCALtasks/AliEmcalCorrectionClusterNonLinearityMCAfterburner.cxx, PWG/EMCAL/EMCALtasks/AliEmcalCorrectionClusterNonLinearityMCAfterburner.h
- Settings have to be used together with the new cell scale in data
- New fine tuning needed as cell scales in data changed (fine tuning is based on interpolation between PCM-EMC and EMC-EMC)
- Separate fine tuning for pp13TeV lowB periods
- New NCell efficiencies obtained with PCM-EMC tagged clusters and EMC-EMC tagged clusters. Pol2 and Gaussian param available for both cases. PCM-EMC with Gaussian should be default!
=> PWG/EMCal: Added new functions for NCell efficiency & Added new MC energy fine tuning

PWGHF/vertexingHF/upgrade/AliAnalysisTaskSEImproveITS3.cxx, PWGHF/vertexingHF/upgrade/AliAnalysisTaskSEImproveITS3.h
- add option to scale DCA by a constant factor (the track properties can in addition be smeared by the usual method - if wanting to just scale the DCA, the same 'improver' file should be given as both arguments to the add task)
- add option to only smear a fraction of tracks in case the DCA is being scaled
this functionality will be used for background studies in cases of low background for the ITS3
=> option to scale DCA for background studies

PWGJE/EMCALJetTasks/Tracks/AliAnalysisTaskEmcalJetEnergyScale.cxx
Part. - and det. level jet pt are weighted with its
corresponding NEF (1-NEF) in order to approximate
the neutral (charged) part of the  jet pt.
=> Add histograms assessing the charged and neutral components of the jet energy scale

PWGLF/RESONANCES/AliRsnCutSetDaughterParticle.cxx, PWGLF/RESONANCES/AliRsnCutSetDaughterParticle.h
Add the new PID scheme function, kTPCpidTOFveto into AliRsnCutSetDaughterParticle class.
The PID function requires acceptable TPC sigma and veto TOF sigma.
=> Add PID function kTPCpidTOFveto in AliRsnCutSetDaughterParticle

OADB/EMCAL/READMEoadb.txt, PWG/EMCAL/EMCALbase/AliEMCALRecoUtils.cxx, PWG/EMCAL/EMCALbase/AliEMCALRecoUtils.h, PWG/EMCAL/EMCALtasks/AliEmcalCorrectionClusterizer.cxx, PWGGA/GammaConv/AliAnalysisTaskElectronStudies.cxx, PWGGA/GammaConv/AliAnalysisTaskElectronStudies.h, PWGGA/GammaConv/macros/AddTask_ElectronStudies.C, PWGGA/GammaConv/macros/AddTask_GammaIsoTree.C
- implemented AliEMCALRecoUtils::ExtrapolateTrackToEMCalSurfaceExperimental which is an experimental function to propagate tracks to the EMCal surface and not used anywhere so far. The function is not validated, however, I think the name of the function containing "Experimental" should make clear enough that this can not be used without validation. The function uses PropagateTrackToBxByBzExperimental for track propagation, which properly takes into account different materials and does not assume Silicon as default for the material passed. Furthermore, the critical energy for electrons is calculated, after which Bremsstrahlung is the dominant source of energy loss. Furthermore, the calculation of density fluctuation corrections has been imroved
- added new configs for iso analysis to …
=> PWGGA/GammaConv+EMCal: EDC cuts for iso analysis & experimental track propagation

PWGHF/jetsHF/AliAnalysisTaskBJetTC.cxx
The X and Y of the embedding histogram was filled in a wrong way. It has been fixed with this commit.
=> Fixing the filling of a histogram

CMakeLists.txt
on cmake 3.20.5 there are problems if doxygen is already found. Just invalidate the already detected doxygen executable.
solution from https://gitlab.kitware.com/cmake/cmake/-/issues/18708
=> cmake:: fix doxygen finding on f34

PWGHF/vertexingHF/AliAnalysisTaskSEXicTopKpi.cxx, PWGHF/vertexingHF/AliAnalysisTaskSEXicTopKpi.h
- method to switch off the topological selections added
- method to switch off als othe PID selection after filtering added
- method to reject events without at least one identified proton, one identified kaon and one identified pion added, to spare CPU time
=> Some methods to work without top. selections added

PWGHF/vertexingHF/AliCFTaskVertexingHF.cxx
Use same track selections for the leading track used in the analysis task and correct the eta acceptance for the leading track
=> Correct track selections for leading track

PWGCF/FEMTOSCOPY/AliFemto/AliFemtoEventReaderNanoAOD.cxx, PWGCF/FEMTOSCOPY/AliFemto/AliFemtoSimpleAnalysisOnlyMixP1.cxx, PWGCF/FEMTOSCOPY/AliFemto/AliFemtoSimpleAnalysisOnlyMixP1.h, PWGCF/FEMTOSCOPY/AliFemto/AliFemtoVertexMultAnalysisOnlyMixP1.cxx, PWGCF/FEMTOSCOPY/AliFemto/AliFemtoVertexMultAnalysisOnlyMixP1.h, PWGCF/FEMTOSCOPY/AliFemto/CMakeLists.txt, PWGCF/FEMTOSCOPY/AliFemto/PWGCFfemtoscopyLinkDef.h, PWGCF/FEMTOSCOPY/AliFemtoUser/AliFemtoTrackCutPdtHe3.cxx, PWGCF/FEMTOSCOPY/AliFemtoUser/AliFemtoTrackCutPdtHe3.h, PWGCF/FEMTOSCOPY/AliFemtoUser/CMakeLists.txt, PWGCF/FEMTOSCOPY/AliFemtoUser/PWGCFfemtoscopyUserLinkDef.h
There are some files add to AliPhysics in order to analysis p-d/t/He3 Femtoscopy in Pb-Pb 5.02TeV.
In general, 3 new class added and made a relevant supplement to NanoAOD Reader.
1-> in "/PWGCF/FEMTOSCOPY/AliFemto/AliFemtoSimpleAnalysisOnlyMixP1.h(.cxx)";
-> in "/PWGCF/FEMTOSCOPY/AliFemto/AliFemtoVertexMultAnalysisOnlyMixP1.h(.cxx)";
These two class are made for special mix method, which only mix the first particle and save event as 
long as this event has the first particle.
2-> in "/PWGCF/FEMTOSCOPY/AliFemtoUser/AliFemtoTrackCutPdtHe3.h(.cxx)";
A very rough track cut for deuteron/triton/He3.
3-> in "/PWGCF/FEMTOSCOPY/AliFemto/AliFemtoEventReaderNanoAOD.cxx"
In old Reader, the storage of triton/He3 TPC/TOF NSigma is not implemented.
Therefore, only relevant information stored in NanoAOD …
=> Dong-Fang Wang(dowang) the first pull request.

PWGGA/GammaConv/AliAnalysisTaskGammaCaloMergedML.cxx, PWGGA/GammaConv/AliAnalysisTaskGammaCaloMergedML.h, PWGGA/GammaConv/macros/AddTask_GammaCaloMergedML_pp.C
I changed branches in the trees to be more efficient with regard to memory by using variable length arrays. The clusters can be reconstructed from the information in the trees later, instead of writing a 2d-array containing the cluster into a tree. Also added additional branches to extract more information about clusters.
=> PWGGA/GammaConv: Updated Analysistask to be more memory efficient

RUN3/AliAnalysisTaskAO2Dconverter.cxx
Type of fLnAmplitude was forgotten to be changed
to short in tree->Branch, only changed in the struct.
=> Fix type of the field fLnAmplitude

PWG/EMCAL/EMCALbase/AliEMCALRecoUtils.cxx, PWG/EMCAL/EMCALbase/AliEMCALRecoUtils.h, PWG/EMCAL/EMCALtasks/AliEmcalCorrectionCellEnergy.cxx, PWG/EMCAL/EMCALtasks/AliEmcalCorrectionCellEnergy.h, PWG/EMCAL/config/AliEmcalCorrectionConfiguration.yaml, PWGGA/GammaConvBase/AliCaloPhotonCuts.cxx, PWGGA/GammaConvBase/AliCaloPhotonCuts.h
When using the option enableLGDetermination: true   in the cell energy component of the CF, the information if a cell is low gain or high gain will be determined via the ADC value of a cell. This option should not be used for data where the information is already stored in the cells itself. 
It is meant to be used with run1 data where the LG/HG info is not stored yet in the cell information. Accuracy of this method was evaluated in local tests using run2 data and will be further tested with full statistics on the grid
=> PWG/EMCAL: optional LG/HG determination via ADC values in CF

RUN3/AliAnalysisTaskAO2Dconverter.cxx
There was a recent change for accepting events based on cuts on ESD event, not working for AOD. This fixes for the general ESD/AOD case.
=> AO2D converter fix for using event cuts for both ESD/AOD.

PWGGA/GammaConvBase/AliConvEventCuts.cxx
- Switched order of triggerSelection and centralitySelection. Before,
MCParticles could be filled even if event is not accepted by the
centrality selection because the trigger is not selected.
- commented line that resets variable isSelected to 1, even if it was
set to 0. In this way it bypasses the trigger overlap rejection
=> PWGGA/GammaConv: Slight modification to event selection

PWGCF/FLOW/GF/AliAnalysisTaskCorrForFlow.cxx
If also running PID, the event pool was updated before filling mixed event correlations for PID
=> Changed order

PWG/EMCAL/EMCALtrigger/AliEmcalTriggerLuminosity.cxx, PWG/EMCAL/EMCALtrigger/AliEmcalTriggerLuminosity.h, PWG/EMCAL/EMCALtrigger/CMakeLists.txt, PWG/EMCAL/EMCALtrigger/PWGEMCALtriggerLinkDef.h
Automatically calculating the integrated luminosty
for certain known collision systems from the standard
output of the normalization task.
=> Adding luminsity calculation tool for normatask output

PWGLF/NUCLEX/Nuclei/Nuclei_UE/AliAnalysisTaskDeuteronCoalescence.cxx, PWGLF/NUCLEX/Nuclei/Nuclei_UE/AliAnalysisTaskDeuteronCoalescence.h, PWGLF/NUCLEX/Nuclei/Nuclei_UE/addTaskDeuteronsCoalescence.C
Proton spectra from Pythia 8 are re-weighted to match the data in toward, transverse and away separately.
=> differential proton re-weighting

PWGGA/GammaConv/AliAnalysisTaskOmegaToPiZeroGamma.cxx, PWGGA/GammaConv/macros/AddTask_OmegaToPiZeroGamma_pp.C
- Reduced overhead for rotationbackground-methods
- Fixed number of photoncandidates needed for CalculateOmegaRotationBackground (from 4 to 5)
- Fixed number of Pi0Candidate needed for CalculatePi0RotationBackground (from none to 1)
=> PWGGA/GammaConv: AliAnalysisTaskOmegaToPiZeroGamma

PWG/FLOW/Tasks/AliAnalysisTaskEPCalib.cxx, PWG/FLOW/Tasks/AliAnalysisTaskEPCalib.h
This version changes the filled multiplicity in each V0 channel from TH1D to TPrifile, calculating the averaged (previous is the total multiplicity for the run) multiplicity for the run of the channel to do the Gain Equalization. 
In fact, the gain equalization process was misunderstood before.
=> ChangeMultiV0toProfile

PWGJE/EMCALJetTasks/UserTasks/AliAnalysisTaskIDFragmentationFunction.cxx, PWGJE/EMCALJetTasks/UserTasks/AliAnalysisTaskIDFragmentationFunction.h, PWGJE/EMCALJetTasks/UserTasks/AliHelperClassFastSimulation.cxx, PWGJE/EMCALJetTasks/UserTasks/AliHelperClassFastSimulation.h, PWGJE/EMCALJetTasks/UserTasks/AliPieceWisePoly.h
Fixes some warnings in AliHelperClassFastSimulation and AliPieceWisePoly and removes an unitialised data member in AliAnalysisTAskIDFragmentationFunction that lead to an bus error in grid analysis (and wasn't used anyway). Also adds header guard for AliPieceWisePoly.
=> Mtf branch fix warnings and errors for grid analysis

PWGJE/EMCALJetTasks/AliAnalysisTaskJetCharge.cxx, PWGJE/EMCALJetTasks/AliAnalysisTaskJetCharge.h, PWGJE/EMCALJetTasks/AliAnalysisTaskJetChargeFlavourTemplates.cxx, PWGJE/EMCALJetTasks/AliAnalysisTaskJetChargeFlavourTemplates.h
Removed the Majority of Histograms and simplified the Trees. The idea behind this is that TTrees will be used primarily for analysis in future in order to help with performing offline Analysis. Additionally, This should reduce the size of the output and memory usage to help with train outputs.
=> Improved output handelling

PWG/FLOW/Tasks/AliAnalysisTaskEPCalib.cxx
Histograms in AliContainer cannot be merged even if a single run has filled them well.
Now I change the storage strategy from AliContainer to a common output list.
=> Change AliContainer to fOutput

PWGCF/FLOW/GF/AliAnalysisTaskGFWFlow.cxx, PWGCF/FLOW/GF/AliAnalysisTaskMeanPtV2Corr.cxx, PWGCF/FLOW/GF/AliEffFDContainer.h, PWGCF/FLOW/GF/AliGFWCumulant.cxx, PWGCF/FLOW/GF/AliGFWCumulant.h, PWGCF/FLOW/GF/AliGFWCuts.cxx, PWGCF/FLOW/GF/AliGFWCuts.h, PWGCF/FLOW/macros/AddTaskGFWFlow.C
-- AliGFWCumulant: check if pt-bin exists before checking if it's filled
-- GFWCuts: taking pointer reference of the track instead of pointer
-- AliEffFDContainer: gets a fetchObj now to deal with the internal naming strategy
-- AliGFWFlow task: extended centrality range, etc.
=> Preparing GFWFlow task to run on 15o_p2 and 18qr_p3 + many small changes

PWGHF/vertexingHF/vHFML/AliAnalysisTaskSECharmHadronMLSelector.cxx, PWGHF/vertexingHF/vHFML/AliAnalysisTaskSECharmHadronMLSelector.h, PWGHF/vertexingHF/vHFML/AliAnalysisTaskSEDmesonTree.cxx, PWGHF/vertexingHF/vHFML/AliAnalysisTaskSEDmesonTree.h, PWGHF/vertexingHF/vHFML/AliAnalysisTaskSEDstarPolarization.cxx, PWGHF/vertexingHF/vHFML/AliAnalysisTaskSEDstarPolarization.h
- Fixed a typo AliAnalysisTaskSECharmHadronMLSelector task (D0 -> Dstar)
- Fixed an error in case the tasks would run over PbPb with the PreSelect function enabled
- Fixed an issue that entered for the SetOwnPrimaryVtx(), RecalcOwnPrimaryVtx(), UnsetOwnPrimaryVtx(), and CleanOwnPrimaryVtx() calls. The same strategy as in the AliRDHFCutsDStartoKpipi.cxx class should be adopted, where these functions are called for the D0-daughter of the Dstar candidate
@fgrosa, your tasks so please have a look if you are ok with it :)
=> PWGHF: Fixes new Dstar tasks

PWGJE/EMCALJetTasks/Tracks/AliAnalysisTaskEmcalJetEnergySpectrum.cxx
Only hybrid tracks will be selected for the background fluctuation estimation (DeltaPt).
=> Selecting only hybrid tracks

PWG/EMCAL/EMCALtasks/AliEmcalCorrectionClusterPositionCorrection.cxx, PWG/EMCAL/EMCALtasks/AliEmcalCorrectionClusterPositionCorrection.h, PWG/EMCAL/EMCALtasks/CMakeLists.txt, PWG/EMCAL/EMCALtasks/PWGEMCALtasksLinkDef.h, PWG/EMCAL/config/AliEmcalCorrectionConfiguration.yaml
- New correction component to correct the cluster position
- Shifts are evaluated by comparing the position of matched tracks to
the cluster
- Shifts are very small and will not affect most analyses, however for
pi0 reconstruction with PCM-EMCal, this correction is necessary as
otherwise the pi0 peak width differs in data and MC
- Correction can be applied to data or to MC
=> PWG/EMCal: Added correction component for cluster position correction

PWGCF/FEMTOSCOPY/AliFemtoUser/AliFemtoCutMonitorParticlePtPDG.cxx
Added checking for non-zero particle pdg code before filling histograms (line 215) to prevent presence of unidentified ("ghost") particles in the resulting histograms. Changing 'fPtPDG' monitoring histogram range (line 46) to add pT-distribution of unidentified particles (line 253).
=> resolving problem with ghost particles, Gleb Romanenko

PWG/EMCAL/EMCALtasks/AliEmcalCorrectionClusterPositionCorrection.h
- changed member variables to presistent as they need to be streamed to
keep the values assigned by the yaml file
=> PWG/EMCal: changed member presistence to keep values of variables

PWG/EMCAL/EMCALbase/AliAnalysisTaskEmcal.cxx, PWG/EMCAL/EMCALbase/AliAnalysisTaskEmcal.h
- Add field, setter and tester for weighted prod
- Include type weighed prod in ConfigureMCDataset
- Fill general histograms with weight (1 default, event
weight in case the production is configured as weighted
pythia
=> [ALIROOT-8678] Add support for weighted pythia productions

PWG/FLOW/Tasks/AliAnalysisTaskCMWESE.cxx
Subdivide the qn distribution bins ---- we need thinner qn distribution slices, to divide qn bins more precisely.
=> Change qn_cent Yaxis Bins

PWGHF/vertexingHF/AliAnalysisTaskSEXicPlusToXi2PifromKFP.cxx
Remove chi2 cut when constructing primary vertex with KF
=> Remove chi2 cut when constructing primary vertex with KF

PWGHF/vertexingHF/AliRDHFCutsDStartoKpipi.cxx, PWGHF/vertexingHF/AliRDHFCutsDStartoKpipi.h
* Added the possibility to require TPC **or** TOF for the PID nsigma selection, instead of TPC **and** TOF as was the default (and still is the default)
* Added the possibility to include the soft pion candidate track in the PID selection when PID info is available (turned off by default)
=> PWGHF: Additional possibilities PID Dstar

PWGJE/EMCALJetTasks/FlowVectorCorrections/macros/AddTaskFlowQnVectorCorrectionsToLegoTrainNewDetConfigPWGJE.C
To calibrate event plane value by running a train, I modified two lines of /PWGJE/EMCALJetTasks/FlowVectorCorrections/macros/AddTaskFlowQnVectorCorrectionsToLegoTrainNewDetConfigPWGJE.C
=> modify PWGJE FlowVector task for train run

PWGJE/EMCALJetTasks/UserTasks/AliAnalysisTaskJetExtractor.cxx, PWGJE/EMCALJetTasks/UserTasks/AliAnalysisTaskJetExtractor.h, PWGJE/EMCALJetTasks/UserTasks/AliAnalysisTaskJetQnVectors.cxx, PWGJE/EMCALJetTasks/UserTasks/AliAnalysisTaskJetQnVectors.h
Updated the JetExtractor task to include an option for using a fully calibrated event-plane angle.
=> AliAnalysisTaskJetExtractor: include calibrated event-plane angle

PWGCF/FLOW/GF/AliAnalysisTaskEffFDExample.cxx, PWGCF/FLOW/GF/AliEffFDContainer.cxx, PWGCF/FLOW/GF/AliEffFDContainer.h, PWGCF/FLOW/macros/AddTaskEffFDExample.C
DCAxy template fitting in this case doesn't make sense, so that's not done. Weights are taken from MCSpectraWeight task and provided in form of TH3D.
=> AliEffFD tasks now run also with AODs. 

PWGJE/EMCALJetTasks/UserTasks/AliAnalysisTaskJetExtractor.cxx, PWGJE/EMCALJetTasks/UserTasks/AliAnalysisTaskJetExtractor.h, PWGJE/EMCALJetTasks/UserTasks/AliAnalysisTaskJetQnVectors.cxx, PWGJE/EMCALJetTasks/UserTasks/AliAnalysisTaskJetQnVectors.h
Update to allow user to choose between V0M, V0A, and V0C for calculating q2, EPangle. Involves using SetQ2Detector flag. Default is V0M. Also includes relative EPangle for matched jets at detector level.
=> AliAnalysisTaskJetExtractor, AliAnalysisTaskJetQnVectors: allow user to select detector for measuring q2

PWGJE/EMCALJetTasks/UserTasks/AliAnalysisTaskIDFragmentationFunction.cxx, PWGJE/EMCALJetTasks/UserTasks/AliAnalysisTaskIDFragmentationFunction.h
Using InputEvent() when calling other classes where AliVEvent is sufficient
Make task run with ESDs and AODs, small code improvements
Use AliAnalysisTask centrality estimator
=> Adjust Jet ID Analysis to use AliVEvent if possible

PWGHF/vertexingHF/vHFML/AliHFMLVarHandler.cxx
The Bayes probability was always present in the TTree because of a "typo"
=> PWGHF: Fix PID option MLVarHandler

PWG/EMCAL/EMCALbase/AliAnalysisTaskEmcal.cxx, PWG/EMCAL/EMCALbase/AliAnalysisTaskEmcal.h, PWG/EMCAL/EMCALbase/AliEmcalList.cxx
Needed in case of EMCAL trigger selection being part of the
event selection
In addition exclude histograms with sum of weights from the
automatic scaling.
=> [ALIROOT-8678] Add histogram for sum of weights before event selection

PWGJE/EMCALJetTasks/UserTasks/AliAnalysisTaskJetQnVectors.cxx, PWGJE/EMCALJetTasks/UserTasks/AliJEQnVectorHandler.cxx
Enables use of calibration files stored in working directories.
=> AliAnalysisTaskJetQnVectors, AliJEQnVectorHandler: allow usage of calibration files not stored on EOS

PWG/FLOW/Tasks/AliAnalysisTaskAR.cxx
Protect against floating point exception (division by zero) in AliAnalysisTaskAR when there are not enough tracks for calculations after applying all cuts.
=> Fix AliAnalysisTaskAR

PWGJE/EMCALJetTasks/UserTasks/AliAnalysisTaskEmcalJetHUtils.cxx, PWGJE/EMCALJetTasks/UserTasks/AliAnalysisTaskEmcalJetHUtils.h
Adding in parameters for 2018 single track reconstruction efficiency + utilities to header (.h) and .cxx. Parameters are from fits to LHC18l8a4 HIJING simulations. Should work similar to 2015 and 2011 functionalities in previous version of code.
=> Adding 2018 single track reconstruction efficiency utility/params

PWGCF/FEMTOSCOPY/AliFemto/AliFemtoSimpleAnalysis.cxx, PWGCF/FEMTOSCOPY/AliFemto/AliFemtoSimpleAnalysis.h
Temporary because I will delete this change as soon as I calculate some trains with this function.
By default is not active (variable that switch it on is false)
The function changes variables that describe x, y and z of the track. I need it to calculate some special background for my analysis.
=> An additional (temporary) function to reverse position of one particle in the pair

PWGGA/GammaConv/AliAnalysisTaskGammaCalo.cxx, PWGGA/GammaConv/AliAnalysisTaskGammaCaloMerged.cxx, PWGGA/GammaConv/AliAnalysisTaskGammaConvCalo.cxx, PWGGA/GammaConv/AliAnalysisTaskGammaConvDalitzV1.cxx, PWGGA/GammaConv/AliAnalysisTaskGammaConvV1.cxx, PWGGA/GammaConvBase/AliConvEventCuts.cxx, PWGGA/GammaConvBase/AliConvEventCuts.h
- Select MC INEL>0 events (needed for multiplicity dep. studies)
- MC particles are only filled for events which are true INEL>0 events
(normally MC particles are filled for all INEL events)
- New function in ALiConvEventCuts handles this check
=> PWGGA/GammaConv: Added INEL>0 check on MC level

PWGGA/GammaConv/AliAnalysisTaskGammaCaloMerged.cxx, PWGGA/GammaConv/AliAnalysisTaskGammaCaloMerged.h
- splitted MC generated particles (pi0, eta, gamma) in:
generated in triggered + accepted events
generated in not triggered events
generated in events with no vertex
- Similar to what was done in Calo and ConvCalo task
=> PWGGA/GammaConv: Added signal loss correction to merged task

PWG/EMCAL/EMCALtasks/AliEmcalCorrectionCellTrackMatcherAndMIPSubtraction.cxx, PWG/EMCAL/EMCALtasks/AliEmcalCorrectionCellTrackMatcherAndMIPSubtraction.h, PWG/EMCAL/config/AliEmcalCorrectionConfiguration.yaml
- Control histogram to check how many cells are good matches and how
many are fake matches
- Added option to only run cell track matching for primaries (R < 5cm)
such that conversions can still be fully rejected. Electrons should
leave their full energy in the cluster instead of just the MIP
=> PWG/EMCAL: Added control histogram to cell track matcher

PWGGA/GammaConv/AliAnalysisTaskGammaCalo.cxx, PWGGA/GammaConv/AliAnalysisTaskGammaCalo.h, PWGGA/GammaConv/AliAnalysisTaskGammaCaloMerged.cxx, PWGGA/GammaConv/AliAnalysisTaskGammaConvCalo.cxx, PWGGA/GammaConv/AliAnalysisTaskGammaConvCalo.h
- Removed condition that MC generated histograms are only filled for
triggered events from GammaCalo, GammaConvCalo and CaloMerged tasks
- While this is fine for min. bias MCs, running a trigger mimicking is
not working with the current implementation
- To still be able to plot the signal loss correction, histograms for MC
generated particles from events which did not fire the trigger are still
filled in addition
=> PWGGA/GammaConv: Partially reverted Signal Loss changes

PWGGA/GammaConv/AliAnalysisTaskGammaCaloMerged.cxx, PWGGA/GammaConv/AliAnalysisTaskGammaCaloMerged.h
- In order to track how many particles were not seen by the trigger
- Needed in order to calculate the signal loss
=> PWGGA/GammaConv: Added notTriggered MC generated histo

RUN3/AliAnalysisTaskAO2Dconverter.cxx
PHOS cells were not marked. As EMCAL cells are processed
before PHOS the PHOS cells were assigned calo type 1 which
is the index for EMCAL cells, consequently PHOS cells were
appearing as EMCAL cells.
=> Mark PHOS cells as calo type 0

PWGGA/GammaConvBase/AliAODConversionPhoton.cxx, PWGGA/GammaConvBase/AliAODConversionPhoton.h
- Prevent fNeutralPionEnergyFraction to be called for index -1 which
causes a seg. fault
- This case seems to be very rare and only occured in 1 event in the
test
=> PWGGA/GammaConv: prevent array going out of bounds

PWG/EMCAL/EMCALbase/AliAnalysisTaskEmcal.cxx
Particularly important for MC-gen train to put weights in bin0.
=> Consistent use of pt-hard bin ID accross scaling histograms

PWGJE/EMCALJetTasks/UserTasks/AliAnalysisTaskEmcalJetHCorrelations.cxx, PWGJE/EMCALJetTasks/UserTasks/AliAnalysisTaskEmcalJetHCorrelations.h, PWGJE/EMCALJetTasks/UserTasks/AliAnalysisTaskEmcalJetHUtils.cxx, PWGJE/EMCALJetTasks/UserTasks/AliAnalysisTaskEmcalJetHUtils.h
Modified Files:
AliAnalysisTaskEmcalJetHCorrelations.h
AliAnalysisTaskEmcalJetHCorrelations.cxx
AliAnalysisTaskEmcalJetHUtils.h
AliAnalysisTaskEmcalJetHUtils.cxx
Description:
JetHCorrelations - Added an extra histogram for the raw pT track spectrum (so you don't have to project) - diagnostic
JetHUtils - Adding more accurate parameterization and parameters for 2018q s.t.r.e.
=> Adding raw track pT histo to JetHCorrelations, Adding corrected 2018 s.t.r.e. to JetHUtils

PWGJE/EMCALJetTasks/UserTasks/AliAnalysisTaskJetDynamicalGrooming.cxx, PWGJE/EMCALJetTasks/UserTasks/AliAnalysisTaskJetHardestKt.cxx
We don't want to use the pion mass hypothesis for CS since that's an
choice of the algorithm. All cases are now enumerated in the comments
=> Fix substructure mass hypothesis for constituent subtraction

PWGJE/EMCALJetTasks/UserTasks/AliAnalysisTaskJetDynamicalGrooming.cxx, PWGJE/EMCALJetTasks/UserTasks/AliAnalysisTaskJetHardestKt.cxx
Need to skip the pion mass hypothesis for both jet-wise and event-wise
CS, but was missing the check for the event-wise case
=> Further fixes for mass hypothesis for reclustering

PWGHF/vertexingHF/AliHFSystErr.cxx
lumi uncertainty wrongly took p-Pb value, fixed to pp@5 value
=> fix lumi uncertainty

PWGJE/EMCALJetTasks/UserTasks/AliAnalysisTaskMTFPID.cxx, PWGJE/EMCALJetTasks/UserTasks/AliAnalysisTaskMTFPID.h
Fix bug happening when copying analysis class like on grid to convolutedGaussFunction (does not get copied correctly). Initialise parameters in UserCreateOutputObjects
=> Fix bug for grid analysis for MTFPID

PWGDQ/dielectron/core/AliAnalysisTask_JPsi_EMCal.cxx
Increasing the number of bins in a plot to be used on the EMCal paper performance
=>  changing number os bins for InvMass plots for the EMCal paper

PWG/EMCAL/EMCALbase/AliMCParticleContainer.cxx, PWG/EMCAL/EMCALbase/AliMCParticleContainer.h
Cut implemented in
AliMCParticleContainer as it is relevant
only in case of simulation. The title string is only modified in case a cut
is set, in order to keep backward comp
for existing tasks.
=> Add option to cut separately on charged and neutral particle pt

PWG/EMCAL/EMCALbase/AliAnalysisTaskEmcal.cxx, PWG/EMCAL/EMCALbase/AliAnalysisTaskEmcal.h
Provide funtion "UserRunBeforeEventSelection" for
user code before event selection. Notably
this is used to fill part. level histograms
without bias from det. level event selection
=> Add virtual function for user code to be filled before event selection

PWGJE/EMCALJetTasks/UserTasks/AliAnalysisTaskJetQnVectors.cxx, PWGJE/EMCALJetTasks/UserTasks/AliAnalysisTaskJetQnVectors.h, PWGJE/EMCALJetTasks/UserTasks/AliJEQnVectorHandler.h
Allows JEQnVectorHandler to work for any harmonic, not just n = 2
Adds TPC Full, negative, positive to extractable event planes
Should not change anything for n=2 harmonic
=> Allows JEQnVectorHandler to work for any harmonic, not just n =2

PWGGA/EMCALTasks/AliAnalysisTaskGammaHadron.cxx, PWGGA/EMCALTasks/AliAnalysisTaskGammaHadron.h, PWGGA/EMCALTasks/CMakeLists.txt
Update Pi0/Gamma - hadron corr in PbPb to use JEQnVector task, useful for 2018qr
JEQnVector task is in PWGJE/EMCALTasks/UserTasks, CMake updated to access
=> Update Pi0/Gamma - hadron corr in PbPb to use JEQnVector task

PWGJE/EMCALJetTasks/UserTasks/AliAnalysisTaskEmcalJetHCorrelations.cxx, PWGJE/EMCALJetTasks/UserTasks/AliAnalysisTaskEmcalJetHCorrelations.h
Modified Files:
AliAnalysisTaskEmcalJetHCorrelations.h
AliAnalysisTaskEmcalJetHCorrelations.cxx
Description:
JetHCorrelations - Adding in functionality for code to talk to AliAnalysisTaskJetQnVectors which is the preferred EP calibration for the 2018 data set. Used EP pulled from V0C.
=> Adding in functionality for 2018 EP Calibration

PWG/EMCAL/EMCALbase/AliAnalysisTaskEmcal.cxx
Pythia JJ anchored to p-pPb 8.16 TeV
embedded into EPOS
=> Adding LHC18b9b

PWGJE/EMCALJetTasks/UserTasks/AliJEQnVectorHandler.cxx
Prevents a divide-by-zero when multiplicity in a subdetector is zero.
=> JEQnVector divide-by-zero fix

PWGCF/FLOW/GF/AliAnalysisTaskGFWFlow.cxx, PWGCF/FLOW/GF/AliAnalysisTaskGFWFlow.h, PWGCF/FLOW/GF/AliAnalysisTaskMeanPtV2Corr.cxx, PWGCF/FLOW/GF/AliAnalysisTaskMeanPtV2Corr.h, PWGCF/FLOW/GF/AliGFWFilter.cxx
MeanPtV2:
-- Removed the efficiency part (now done in separate code anyways)
-- Adapted AliGFWFilter. Minor differences in "closure" test due to:
-- TPC Cluster cut being > X as opposed to >= X. Changed to >= X now.
-- DCAxy cut 2010 vs 2011. GFWFilter uses 2011 as default
-- Still need to change the part that picks up efficiencies. This should use the same naming convention as NUAs
GFWFlow:
-- Work on on-fly mode. Previous commit would pass local/offline tests, but would crash when running on grid. Reverted back to the version that was running fine on trains
-- Added a flag that would allow to override the centrality value (and so impact parameter is not fetched) when running on-fly trains.
=> Major cleanup in MeanPtV2. Reverted GFWFlow to earlier date.

PWGJE/EMCALJetTasks/UserTasks/AliAnalysisTaskEmcalJetEnergyFlow.cxx, PWGJE/EMCALJetTasks/UserTasks/AliAnalysisTaskEmcalJetEnergyFlow.h, PWGJE/EMCALJetTasks/macros/AddTaskEmcalJetEnergyFlow.C
All the files associated with the jet energy flow analysis task have been updated to make the "step" of jet radius expansion defined by the user as an input configuration parameter. However the appropriate selection of jet finders and jet containers remains the responsibility of the analyser.
=> Update of the jet energy flow analysis task with an adjustable radial step

PWG/EMCAL/EMCALtasks/AliEmcalCorrectionCellEnergyCompression.cxx, PWG/EMCAL/EMCALtasks/AliEmcalCorrectionCellEnergyCompression.h, PWG/EMCAL/EMCALtasks/CMakeLists.txt, PWG/EMCAL/EMCALtasks/PWGEMCALtasksLinkDef.h, PWG/EMCAL/config/AliEmcalCorrectionConfiguration.yaml
- Component to try settings for a compression algorithm used in
O2/DataFormats/EMCAL/...Cell.cxx
- Cell energy/time gets multiplied with a certain resolution factor and
then gets transformed in an integer
- All values for resolution etc. can be set in the yaml file
=> PWG/EMCAL: Added Cell energy and time compression component

PWGJE/EMCALJetTasks/AliAnalysisTaskPWGJEQA.cxx, PWGJE/EMCALJetTasks/AliAnalysisTaskPWGJEQA.h
Removes generator index check that was erroneously applied to only MC-matched tracks. This prevented the task from being usable for MC productions with more than one generator (e.g Pileup + HIJING).
=> Removes unneeded generator index check for MC-matched tracks

PWGDQ/dielectron/LMEE/AliAnalysisTaskLMeeCocktailMC.cxx, PWGDQ/dielectron/core/AliAnalysisTaskElectronEfficiencyV2.cxx
Adjustment for ROOT6
(1) gSystem->Exec(Form("alien_cp %s file:./", fFileName.Data()));
(2) TFile::Cp(fFileName, TString::Format("file:%s", gSystem->BaseName(fFileName)));
(1) and (2) are equivalent, verified. ( (2) only works for root file )
=> Fix for alien_cp: Task LMeeCocktail and ElectronEfficiencyV2

PWGHF/vertexingHF/macros/AddTaskCFVertexingHF.C
Hi,
I would like to restore the version of AddTastCFVertexing.C from Jan24, since with the latest changes it seems that wagons can't be ran simultaneously in a same train.
Thanks,
Susanna
=> Restoring version from Jan24

PWGMM/UE/UeKNO/AliAnalysisTaskChargedVsRT.cxx
A lock was added so that the response matrix would have contributions of only primary and charged particles
=> To correct the response matrix

PWGHF/vertexingHF/AliAnalysisTaskSEXicPlus2XiPiPifromAODtracks.cxx, PWGHF/vertexingHF/AliAnalysisTaskSEXicPlus2XiPiPifromAODtracks.h, PWGHF/vertexingHF/macros/AddTaskXicPlus2XiPiPifromAODtracks.C
I modified the Event Selection parts to take the HM event into accounts. 
In previous version of code, at the beginning of the event selection stage, non-MB events are cut off, so I couldn't get HM triggered events much.
And I added one more counter to store the HM [0,100] events.
=> Modify the Event Selection parts and add a counter for HM[0,100]

PWGJE/EMCALJetTasks/Tracks/AliAnalysisEmcalSoftdropHelper.cxx, PWGJE/EMCALJetTasks/Tracks/AliAnalysisEmcalSoftdropHelper.h, PWGJE/EMCALJetTasks/Tracks/AliAnalysisTaskEmcalSoftDropData.cxx, PWGJE/EMCALJetTasks/Tracks/AliAnalysisTaskEmcalSoftDropData.h, PWGJE/EMCALJetTasks/Tracks/AliAnalysisTaskEmcalSoftDropResponse.cxx, PWGJE/EMCALJetTasks/Tracks/AliAnalysisTaskEmcalSoftDropResponse.h
Add cut on the pt of the track
constituents and on E of the
cluster constituents (optional)
applied before reclustering the
jet to extract the SD observables.
Cuts can be varied independently.
Affect only the SD params, not
the jet energy.
=> Add optional pt cut on charged and cluster constituents in SD

PWGJE/EMCALJetTasks/AliAnalysisTaskPWGJEQA.cxx, PWGJE/EMCALJetTasks/AliAnalysisTaskPWGJEQA.h
Adds switch for removing MC pileup using AliAnalysisUtils
This works as a better way of removing pileup than the generator index option.
Confirmed to work with MCs (with pileup) tagged to 15o pass2 and 18qr pass3
=> Adds switch for removing MC pileup using AliAnalysisUtils

PWGHF/vertexingHF/AliAnalysisTaskSEDvsEventShapes.cxx, PWGHF/vertexingHF/AliAnalysisTaskSEDvsEventShapes.h, PWGHF/vertexingHF/macros/AddTaskDvsEventShapes.C, PWGHF/vertexingHF/macros/QuantileUsingSplines.C
First Implementation of spherocity quantiles using Splines for the D mesons vs multiplicity analysis. Check attached macro to obtain the splines and run first the task without isS0Spline enabled in order to have the data to compute them.
=> Implementation of Spherocity Quantiles

PWGHF/treeHF/AliHFJetFinder.cxx, PWGHF/treeHF/AliHFJetFinder.h
Fix issue in the response matrix of Ds-jet.
In `AliHFJetFinder::FindMCJets`, the daughters of HF candidates are read and stored from AliAODMCParticle by GetNDaughters() and GetDaughterLabel(i). But in the source code of `AliAODMCParticle`, it only deals with __2 prongs__ decay case. So for Ds to KKpi, the daughters are phi meson and pion, which means the __Kaon pair is not removed from MC particle array in generator level.__
Comparison with local running on test datasets. Use __relative difference of jet pT between detector reco. and gen. level.
=> HFjet - find MC daughters recursively

PWG/EMCAL/EMCALbase/AliEMCALRecoUtils.cxx, PWG/EMCAL/EMCALbase/AliEMCALRecoUtils.h, PWG/EMCAL/EMCALtasks/AliEmcalCorrectionCellEnergy.cxx, PWG/EMCAL/EMCALtasks/AliEmcalCorrectionCellEnergy.h, PWG/EMCAL/config/AliEmcalCorrectionConfiguration.yaml
- Modules behind TRD support structure are more affected by energy loss
and photon conversions in material in front of them
- In energy calibration all cells were treated the same and were
calibrated to one value
- To test the effect of properly calibrating these cells to an expected
value (lower pi0 mass peak as heavily affected by conversions), this new
eta dependent scale is introduced.
- The scale factors are stored in the SMDependent scale factor vector as
the SM dependnt scale factors are not applied in that case
- Highly experimental and should not be used for analysis at this point!
=> PWG/EMCAL: Add option to apply Eta dependent cell scale

PWGGA/GammaConv/macros/AddTask_GammaConvCalo_pp.C, PWGGA/GammaConvBase/AliCaloPhotonCuts.cxx
- Cell scale was previously determined on nomB data/MC. Now we evaluated
the cell scale on lowB data directly. Therefore the NonLin correction
also has to change
- Experimental at this point. Dont use for physics analyses
=> PWGGA/GammaConv: Add NonLin for lowB with dedicated cell scale

PWG/EMCAL/EMCALtasks/AliEmcalCorrectionCellEmulateCrosstalk.cxx
Cross-talk emulation can assign energy to cells where the particle did not deposit energy. In such case, only the induced energy is assigned to the cell. Here one assigns to this new cell, the time and the MC label of the highest energy cell neighbour and in the same T-Card.
@FriederikeBock  and @jokonig, since I think you requested this, please have a look and let me know what you think before approving.
=> EMCal: Assign MC label and time to cells added by cross-talk emulator

PWG/EMCAL/EMCALtrigger/AliEmcalTriggerMakerTask.cxx
Condition overwrote custom settings of the OADB
container with "oadb", setting of specific OADB files
was therefore ignored.
In addition: Set default case for the OADB container
also for MC pp 13 TeV - this will have an effect only
in case the user specified loading the FastOR mask
of dead or bad FastORs explicitly. This will not be set
to default to the moment since it requires the trigger
maker and trigger selection task to run in data,
otherwise results will be inconsistent
=> Fix default OADB container in case of pp 13 TeV

PWGGA/GammaConv/AliAnalysisTaskGammaCalo.cxx, PWGGA/GammaConv/AliAnalysisTaskGammaCalo.h, PWGGA/GammaConv/AliAnalysisTaskGammaConvCalo.cxx, PWGGA/GammaConv/AliAnalysisTaskGammaConvCalo.h, PWGGA/GammaConv/AliAnalysisTaskGammaConvV1.cxx, PWGGA/GammaConv/AliAnalysisTaskGammaConvV1.h, PWGGA/GammaConv/macros/AddTask_GammaCalo_pp.C, PWGGA/GammaConv/macros/AddTask_GammaConvCalo_pp.C
- Outsource determination if particle is in Jet into dedicated function
in MesonCuts
- This change also affects that the same pi0 cannot be filled multiple
times into the same histogram (that was the case before if the same pi0
is inside multiple jet cones). Now its always filled for the closest
jet.
- Changed definition when a true pi0 is in a jet (before it was in jet
if it is in a true jet, now its in a reconstructed jet). This definition
is closer to data and therefore one can now really check how many pi0
in-Jet candidates are real pi0s.
- Added InitJet function to initialize all jet vectors just once per
event
- Added option for rotation background to GammaConv task
=> PWGGA/GammaConv: Various changes to in-Jet analysis

PWGGA/GammaConv/AliAnalysisTaskGammaPureMC.cxx, PWGGA/GammaConv/AliAnalysisTaskGammaPureMC.h
- Mode fDoMultStudies=2 now only selects INEL>0 events for mult studies.
INEL>0 means at least one primary charged particle in |eta|<1.
- This is needed as in data we select the INEL>0 event class
=> PWGGA/GammaConv: Added INEL>0 option to PureMC task

PWGCF/FEMTOSCOPY/macros/AddTaskFemtoNanoLKr.C
MinimalBooking of Kaons cuts set to false, to get the histograms and compute purity for systematics
TrackPosKaonCuts->SetMinimalBooking(false);
TrackNegKaonCuts->SetMinimalBooking(false);
=> Removed minimal booking of kaons tracks for syst purity

RUN3/AliAnalysisTaskAO2Dconverter.cxx, RUN3/AliAnalysisTaskAO2Dconverter.h
This PR fixes the list of mothers in the McParticle 001 format introduced in https://github.com/alisw/AliPhysics/pull/19655.
The conversion task now produces an empty array for particles with no mothers instead of an array of length 1 containing index -1.
The change consists of additional lines 1579-1580. The rest are just trailing spaces automatically removed by the editor.
@jgrosseo @pzhristov , please have a look.
=> Run 3 conversion: Do not store index -1 if no mothers

RUN3/AliAnalysisTaskAO2Dconverter.cxx, RUN3/AliAnalysisTaskAO2Dconverter.h
Check with GetInstance whether a geometry instance
has already been created for the current run, and only
if not call GetInstanceFromRunNumber to build the
geometry object.
=> Reduce verbosity from geometry initialization

RUN3/AliAnalysisTaskAO2Dconverter.cxx, RUN3/AliAnalysisTaskAO2Dconverter.h
Reduced trigger payload must be optional for run1 and
run2 data, otherwise it will be impossible masking bad
TRUs offline.
=> [EMCAL-783] Make reduced trigger payload optional

PWGHF/vertexingHF/AliRDHFCutsOmegactoeleOmegafromKFP.cxx
Apply |nSigma_TPC| < 5 to reduce output size
=> Preselection cut for e

PWGHF/hfe/AliAnalysisTaskEHCorrel.cxx, PWGHF/hfe/AliAnalysisTaskEHCorrel.h
- Adding functional form to apply track and EMCal cluster matching cut 
- Adding ME binning for 2018 data with 0-10% and 30-50% centrality
=> Add func for track-cls match; MEbins for 2018 data

PWGCF/Correlations/JCORRAN/Pro/AliJCDijetAna.cxx, PWGCF/Correlations/JCORRAN/Pro/AliJCDijetAna.h
Previously: Remove over 100 GeV tracks from event.
Now: Remove jets with over 100 GeV constituents.
=> Fixed the way 100 GeV track cut behaves

PWGCF/FLOW/GF/AliAnalysisTaskCorrForNonlinearFlow.cxx, PWGCF/FLOW/GF/AliAnalysisTaskCorrForNonlinearFlow.h
When using bootstrap, the memory consumption is large. We need to reduce the pt binning of trigger particles to 1 (0.2-3.0) to ensure the bootstrap works.
=> [PAG/Flow] flag to use bootstrap

OADB/EMCAL/READMEoadb.txt
Update of EMCALTimeCalib.root and EMCALTimeCalibMergedBCs.root extending run range for LHC17l to include run 276551
=> OADB/EMCAL: Update of time calib for missing run 276551 of LHC17l

PWGHF/vertexingHF/macros/AddTaskHFTreeCreatorApply.C, PWGHF/vertexingHF/vHFML/AliAnalysisTaskSEHFTreeCreatorApply.cxx, PWGHF/vertexingHF/vHFML/AliAnalysisTaskSEHFTreeCreatorApply.h, PWGHF/vertexingHF/vHFML/AliHFTreeHandlerApply.cxx, PWGHF/vertexingHF/vHFML/AliHFTreeHandlerApply.h, PWGHF/vertexingHF/vHFML/AliHFTreeHandlerApplyDstartoKpipi.cxx, PWGHF/vertexingHF/vHFML/AliHFTreeHandlerApplyDstartoKpipi.h, PWGHF/vertexingHF/vHFML/AliParticleTreeHandlerApply.cxx, PWGHF/vertexingHF/vHFML/AliParticleTreeHandlerApply.h, PWGHF/vertexingHF/vHFML/CMakeLists.txt, PWGHF/vertexingHF/vHFML/PWGHFvertexingHFMLLinkDef.h
Added Dstar and particle TTrees to TreeCreator to reproduce D*-[pi,K,p] femtoscopy analysis in FemtoDream.
=> PWGHF: Add Dstar and LF track for femto in treecreator

PWGGA/GammaConvBase/AliConvEventCuts.cxx
- Added protection to only call the mimicTrigger function in data in case a trigger is selected.
- Otherwise the trigger selection with the EMCALTriggerSelection task will crash for periods/events where there is no trigger present
=> PWGGA/GammaConv: Fix for trigger decision in data

.github/workflows/clean-test.yml, .github/workflows/release.yml
This PR adds explicit [permissions section](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#permissions) to workflows. This is a security best practice because by default workflows run with [extended set of permissions](https://docs.github.com/en/actions/security-guides/automatic-token-authentication#permissions-for-the-github_token) (except from `on: pull_request` [from external forks](https://securitylab.github.com/research/github-actions-preventing-pwn-requests/)). By specifying any permission explicitly all others are set to none. By using the principle of least privilege the damage a compromised workflow can do (because of an [injection](https://securitylab.github.com/research/github-actions-untrusted-input/) or compromised third party tool or …
=> GitHub Workflows security hardening

PWGCF/Correlations/macros/jcorran/AddTaskJFFlucJCMAPsMaster.C, PWGCF/Correlations/macros/jcorran/AddTaskJHOCFAMaster.C
Adding a new chi^2 cut that differ from the default cut with 30%, this cut will be used as trial for systematic uncertainty evaluation.
=> [PWG-CF]Adding new chi^2 cut

PWGLF/NUCLEX/Nuclei/Nuclei_UE/AliAnalysisTaskDeuteronsRT.cxx
Change for AliAnalysisTaskDeuteronsRT.cxx analysis task in order to change the extreme of binning in nsigmaTPC histograms (both data & systematics)
=> For UE analysis: nsigma TPC bin changed from (-5,5) to (-10, 10)

PWGCF/Correlations/KaonCorrelations/AliAnalysisTaskKaon2PC.cxx, PWGCF/Correlations/KaonCorrelations/AliAnalysisTaskKaon2PC.h
Added if statements to avoid the overcounting of shared daughters of neutral kaons in K0-K0 correlation functions, Removed a typo in the axis title of histogram fHistK0Phi.
=> Removed the overcounting of shared daughters of neutral kaons

PWG/EMCAL/EMCALtasks/AliAnalysisTaskEmcalTriggerSelection.cxx, PWG/EMCAL/EMCALtrigger/AliEmcalTriggerMakerKernel.cxx, PWG/EMCAL/EMCALtrigger/AliEmcalTriggerMakerKernel.h
L0 patches also use the timesums for the calculation of
the ADC value. The timesums are calculated at in the
TRU and sent to the STU. Since the timesums at L0 are
not available in the analysis objects the timesums at L1
serve as proxy. The only issue the user has to keep in
mind is that when shipping the timesums from the TRU
to the STU a bit shift from 12 to 10 bits is performed in
order to fit the timesums into the ALTRO format (10 bits).
When working with L1 timesums users need to divide
the L0 threshold by 4.
=> Use L1 timesums in the calulation of the L0 patch ADCs

PWGJE/EMCALJetTasks/UserTasks/AliAnalysisTaskEPCalibForJet.cxx
I faced a "Break" on the line to fill TProfile2D, when I use only the train.
So I tried to change the line. 
TProfile2D* tempProfile2DHist = (TProfile2D*) fHistManager.FindObject(histName);
-> TProfile2D* tempProfile2DHist = dynamic_cast<TProfile2D *>(fHistManager.FindObject(histName));
=> modify the way to use TProfile2D

PWGHF/hfe/AliAnalysisTaskEHCorrel.cxx, PWGHF/hfe/AliAnalysisTaskEHCorrel.h
Adding new functionalities to calculate pi0 and eta weight and tagging efficiency using 2018 Pb-Pb anchored HFe MC sample. 
- The order of MC generators in the MC header is different in the 2018 Pb-Pb anchored MC sample compared to older MC samples.
- Old order of embedded signals: MB, pi0, eta, cele/bele; New order: cele/bele, pi0, eta, MB 
- The ordering information is used to select particles from embedded pi0 and eta sample for tagging efficiency calculation
=> Add tagging effi functions for 2018 HF MC sample

PWGHF/vertexingHF/AliAnalysisTaskHFSimpleVertices.cxx, PWGHF/vertexingHF/AliAnalysisTaskHFSimpleVertices.h
@vkucera 
- Added possibility to use AliEventCuts to exactly match the event selections of the AO2Dconverter task (*). Disabled by default
- Fix issue with loading of trigger from json file: removal of leftover comma at end line
- Add some extra histograms for AliPhysics-O2 validation
- Update default V0+bachelor selections, to match the O2 task
(*) Note that the default AliEventCuts checks a hardcoded trigger (kINT7 for most data sets). This can lead to a "conflict" in (the unlikely) case a different trigger is set in the json file that is loaded by this task.
=> PWGHF: Include AliEventCuts in HFSimpleVertices

PWGCF/Correlations/JCORRAN/Pro/AliJCDijetAna.cxx, PWGCF/Correlations/JCORRAN/Pro/AliJCDijetAna.h, PWGCF/Correlations/JCORRAN/Pro/AliJCDijetHistos.cxx, PWGCF/Correlations/JCORRAN/Pro/AliJCDijetHistos.h, PWGCF/Correlations/JCORRAN/Pro/AliJCDijetTask.cxx
Previously the same det MC jet could match to a true jet multiple times. This is a problem in the very low true jet range, under 5 GeV. Now there is a limit that det mc jet can be matched only once. Added a couple of histograms as well.
=> Updated jet pt matching

PWGGA/GammaConv/AliAnalysisTaskConvJet.cxx, PWGGA/GammaConv/AliAnalysisTaskConvJet.h, PWGGA/GammaConv/AliAnalysisTaskMesonJetCorrelation.cxx, PWGGA/GammaConv/AliAnalysisTaskMesonJetCorrelation.h, PWGGA/GammaConv/CMakeLists.txt, PWGGA/GammaConv/PWGGAGammaConvLinkDef.h, PWGGA/GammaConv/macros/AddTask_MesonJetCorr_Calo.C, PWGGA/GammaConv/macros/AddTask_MesonJetCorr_Conv.C, PWGGA/GammaConv/macros/AddTask_MesonJetCorr_ConvCalo.C, PWGGA/GammaConvBase/AliConversionMesonCuts.cxx, PWGGA/GammaConvBase/AliConversionMesonCuts.h, PWGGA/GammaConvBase/AliGammaConvEventMixing.cxx, PWGGA/GammaConvBase/AliGammaConvEventMixing.h, PWGGA/GammaConvBase/AliResponseMatrixHelper.cxx, PWGGA/GammaConvBase/AliResponseMatrixHelper.h, PWGGA/GammaConvBase/CMakeLists.txt, PWGGA/GammaConvBase/PWGGAGammaConvBaseLinkDef.h
- task to get neutral meson in corellation with a particle jet
- Aim to produce the meson pt spectra (differentiatet for different jet pt) (using full 2d unfolding)
- Aim to get the fragmentation function for neutral mesons using full 2d unfolding
- Helper task for response matrix can be used for response matrix as well as for storing 2d histograms vs jet pT
- New mixing class for rotating events such that two events have one overlapping jet momentum vector. Should improve the mixed event distribution compared to classical mixed events in mixing classes
=> PWGGA/GammaConv: Add Neutral meson in-jet task

PWGHF/vertexingHF/AliAnalysisTaskHFSimpleVertices.cxx
Apply the event selections before the MC matching.
Now the event selection is applied before filling the generated candidates histograms (as in O2)
@lvermunt
=> PWGHF: Apply the event selections before the MC matching

PWGGA/GammaConv/AliAnalysisTaskMesonJetCorrelation.cxx, PWGGA/GammaConv/AliAnalysisTaskMesonJetCorrelation.h
- output list and other members are changed to persistent members as they need to be streamed (otherwise leads to empty output)
- add lines in ProcessPhotons to allow dEdx recalib
- swapped filling of meson pt response matrix (before jet pt and meson pt were the wrong way around)
=> PWGGA/GammaConv: Fixes for MesonJet task

PWGGA/GammaConv/AliAnalysisTaskMesonJetCorrelation.cxx, PWGGA/GammaConv/AliAnalysisTaskMesonJetCorrelation.h, PWGGA/GammaConvBase/AliGammaConvEventMixing.cxx, PWGGA/GammaConvBase/AliGammaConvEventMixing.h
- Switch to shared_ptr in mixed background calculation struct
- Fix rotation background that both rotated photons are checked and not only one (Which led to a peak in the background distribution)
=> PWGGA/GammaConv: Add cluster and conv. histograms to MesonJet task

PWGGA/GammaConv/AliAnalysisTaskGammaCalo.cxx, PWGGA/GammaConv/AliAnalysisTaskGammaConvCalo.cxx, PWGGA/GammaConv/AliAnalysisTaskGammaConvV1.cxx, PWGGA/GammaConv/AliAnalysisTaskGammaConvV1.h
Conversion task
- MC hists have to be filled for all events (even if no vertex was found or min bias trigger did not fire)
- Fill MC histos for events without vertex (this was previously not done correctly)
=> PWGGA/GammaConv: Fill MC hists for particles that are not triggered in

PWGGA/GammaConv/AliAnalysisTaskNeutralMesonToPiPlPiMiNeutralMeson.cxx, PWGGA/GammaConv/AliAnalysisTaskNeutralMesonToPiPlPiMiNeutralMeson.h
- Erorr in m_omega vs error in m_pi0 depent on opening angle to correct the omega masses in future analyses
- Added protection for true tree output since DPMJet can contain primary pi0's without a mother
=> PWGGA/GammaConv: Added 3d ouput histogram for omega mass correction

PWGCF/EBYE/NetLambda/AliAnalysisTaskNetLambdaIdent.cxx, PWGCF/EBYE/NetLambda/AliAnalysisTaskNetLambdaIdent.h
Added a check for rejecting on-the-fly V0s/cascades as well as the parameter CosPABachBar for data rejection.
=> Added on-the-fly check and CosPABachBar parameter to Cascades

PWGGA/GammaConv/AliAnalysisTaskNeutralMesonToPiPlPiMiNeutralMeson.cxx, PWGGA/GammaConv/AliAnalysisTaskNeutralMesonToPiPlPiMiNeutralMeson.h, PWGGA/GammaConv/macros/AddTask_GammaConvNeutralMesonPiPlPiMiNeutralMeson_CaloMode_PbPb.C, PWGGA/GammaConv/macros/AddTask_GammaConvNeutralMesonPiPlPiMiNeutralMeson_CaloMode_pPb.C, PWGGA/GammaConv/macros/AddTask_GammaConvNeutralMesonPiPlPiMiNeutralMeson_CaloMode_pp.C
- Added a 4th unsmearing option (No Corr, Fixedpz, Subpi0 and now SubLambda)
- This subtracts the error of the reconstructed pi0 multiplied by a factor lambda from a Toy MC
- This lambda comes as a function of alpha and has been verified by the 3d histogram from the previous commit
- Made all minv-pT histograms optional with a AddTask argument to reduce memory
- Corrected axis label from previous commit
=> PWGGA/GammaConv: Added opening-angle dependent omega unsmearing

PWGCF/Correlations/DPhi/Unfoldedhistos/AliCSEventCuts.cxx, PWGCF/Correlations/DPhi/Unfoldedhistos/AliCSEventCuts.h, PWGCF/Correlations/DPhi/Unfoldedhistos/AliCSTrackCuts.cxx, PWGCF/Correlations/DPhi/Unfoldedhistos/AliCSTrackCuts.h
Also for LHC18q&r the Chi2/TPC cluster limit changed to 2.5
=> Pileup rejection based on SDD+SSD clusters vs TPC clusters

PWGCF/FEMTOSCOPY/AliFemtoUser/AliAnalysisEfficiencyPbPbExclusivePID.cxx, PWGCF/FEMTOSCOPY/AliFemtoUser/AliAnalysisEfficiencyPbPbExclusivePID.h, PWGCF/FEMTOSCOPY/AliFemtoUser/AliAnalysisEfficiencyPbPbNodoublecount.cxx, PWGCF/FEMTOSCOPY/AliFemtoUser/AliAnalysisEfficiencyPbPbNodoublecount.h, PWGCF/FEMTOSCOPY/AliFemtoUser/CMakeLists.txt, PWGCF/FEMTOSCOPY/AliFemtoUser/PWGCFfemtoscopyUserLinkDef.h, PWGCF/FEMTOSCOPY/macros/AddTaskEfficiencyPbPbPID1.C, PWGCF/FEMTOSCOPY/macros/AddTaskEfficiencyPbPbPID2.C
New efficiency tasks to estimate systematic uncertainties with different PID methods using FB128 by default for pPb and PbPb collisions
=> Efficiency task for pPb and PbPb collisions

PWGGA/GammaConv/AliAnalysisTaskGammaCalo.cxx, PWGGA/GammaConv/AliAnalysisTaskGammaConvCalo.cxx, PWGGA/GammaConv/AliAnalysisTaskGammaConvV1.cxx
- MC particles were filled for events outside the nominal vertex. They should however not enter the efficiency calculation as this is handled in an event correction. This bug was introduced in AliPhysics/pull/21165
- MC particles should only be filled for events without a reconstructed z-vertex
=> PWGGA/GammaConv: Fix for filling MC particles

PWGGA/GammaConv/AliAnalysisTaskNeutralMesonToPiPlPiMiNeutralMeson.cxx, PWGGA/GammaConv/macros/AddTask_GammaConvNeutralMesonPiPlPiMiNeutralMeson_CaloMode_pPb.C, PWGGA/GammaConvBase/AliConversionMesonCuts.cxx
- Added cut on asymmetry (l) with -0.6 < alpha < CustomFuction
- Added cutstring using the new cut
- Changed lambda function from pol4 to pol2 following previous DPMJet train data
=> PWGGA/GammaConv: Added omega-asymmetry cut and changed lambda function

PWGGA/GammaConv/AliAnalysisTaskMesonJetCorrelation.cxx, PWGGA/GammaConv/AliAnalysisTaskMesonJetCorrelation.h
calculation
- Histogram for secondaries previously only for meson z and not pt
- Added histogram for meson finding efficiency inside true jets. Meson has to be found inside a true jet on rec. level
- Fixed warnings in MesonJetTask
=> PWGGA/GammaConv: Add histograms for secondaries and efficiency

PWGGA/GammaConv/AliAnalysisTaskMesonJetCorrelation.cxx, PWGGA/GammaConv/AliAnalysisTaskMesonJetCorrelation.h
- Response matrix should only contain smearing of meson and not from jet. Therefore, the momentum from the true jet is always taken for z_rec and z_true
=> PWGGA/GammaConv: Add reponse matrix for z with only smeared z

PWGJE/EMCALJetTasks/UserTasks/AliAnalysisTaskIDFragmentationFunction.cxx, PWGJE/EMCALJetTasks/UserTasks/AliAnalysisTaskIDFragmentationFunction.h, PWGJE/EMCALJetTasks/UserTasks/AliPieceWisePoly.cxx, PWGJE/EMCALJetTasks/UserTasks/AliPieceWisePoly.h, PWGJE/macros/AddTaskIDFragmentationFunction.C
Train fails because functions are not copied directly. Store them as variables so we dont have to deal with copying functions
=> Correctly store and pass fast simulation parameters

PWGLF/NUCLEX/Utils/O2vertexer/DCAFitterN.h, PWGLF/NUCLEX/Utils/O2vertexer/HelixHelper.h, PWGLF/NUCLEX/Utils/O2vertexer/MathUtils.h
PR to get the O2Vertexer in AliPhysics up to date with the current one in O2. In particular updates regarding the covariance matrix were missing in the AliPhysics version, making it difficult to validate analyses that apply selections based on this (e.g. D meson analyses in HF).
I tried to keep this PR as simple as possible (instead of propagating tens of new header files that O2 now has into AliPhysics). Regarding this I put some considerations below.
@mpuccio, @vkucera, let me know what you think.
Cheers, Luuk
----------------------------------
**Consideration w.r.t. current (01-11-22) O2 version**
General:
- I didn't split the MathUtils class, since this would require a lot of new header files to be propagated to AliPhysics. Instead I kept the original class (adding two additional …
=> Propagate updates from O2vertexer in O2 into AliPhysics

PWGGA/GammaConv/AliAnalysisTaskGammaConvV1.cxx, PWGGA/GammaConv/AliAnalysisTaskGammaConvV1.h, PWGGA/GammaConvBase/AliConvEventCuts.h
Up to now pointers to the aod mc track array were obtained only once for the first event of an instance of the analysis task. Since it is not guaranteed that the address of this track array stays constant over the lifetime of an analysis task this can produce unexpected behaviour.
With this change the pointer is reset for every event.
=> PWGGA/GammaConv Fix for unsafe pointer issue

PWGGA/GammaConv/AliAnalysisTaskNeutralMesonToPiPlPiMiNeutralMeson.cxx, PWGGA/GammaConv/AliAnalysisTaskNeutralMesonToPiPlPiMiNeutralMeson.h, PWGGA/GammaConv/macros/AddTask_GammaConvNeutralMesonPiPlPiMiNeutralMeson_MixedMode_PbPb.C, PWGGA/GammaConv/macros/AddTask_GammaConvNeutralMesonPiPlPiMiNeutralMeson_MixedMode_pPb.C, PWGGA/GammaConv/macros/AddTask_GammaConvNeutralMesonPiPlPiMiNeutralMeson_MixedMode_pp.C
- Trainconfig_UNSMEARING4 will activate the "NoCorrection"-Output but do an analytic unsmearing, assuming an unsmeared PCM photon and therefore shifting the cluster photon to ensure a correct pi0 mass
- Added 2 cutstrings for PCM-EMC to test the new unsmearing
- Bug fixes:
- Some pi0's dont have daughters (at least in DPMJet), possibly because of inelastic scattering -> Require > 0 daughters
- The requirements for the reconstrucable in the MCProcessing had some "typos"
- In Mixed AddTasks the argument weighting did not match the weightingPart later requested in the AddTasks
=> PWGGA/GammaConv: Implemented analytic pi0 unsmearing for PCMEMC + smaller bug fixes

PWG/EMCAL/EMCALtrigger/AliEmcalTriggerMakerKernel.cxx
When embedding there can few dummy cells that are not removed, this is just to avoid large log files
=> [EMCAL-772] Move error to debug to not trash logs in case of embedding

PWGHF/vertexingHF/AliAnalysisTaskHFSimpleVertices.cxx, PWGHF/vertexingHF/AliAnalysisTaskHFSimpleVertices.h
Removing the radius cut significantly reduces the discrepancy between AliPhysics and O2Physics secondary vertex histograms. Other radius cuts are already applied inside the DCAFitterN in both frameworks.
Arrays in the HFSimpleVertices class have fixed sizes that are smaller than the default configuration or JSON settings. At the class initialization, the values were written beyond the actual end of the arrays in the memory. This resulted in overwriting the memory of various flags and having spurious flag values. This PR increases the declared array sizes and adjusts the number of cut values.
=> PWGHF: Fix arrays overflow that causes bugs with flags + remove 2-vertex radius cuts absent in O2Physics

PWGJE/EMCALJetTasks/UserTasks/AliAnalysisTaskEmcalJetEnergyFlow.cxx, PWGJE/EMCALJetTasks/UserTasks/AliAnalysisTaskEmcalJetEnergyFlow.h
Adjusted the analysis task to only consider the cases where the jet pt is positive after background subtraction. Previously this existed only for the Dpt histogram in the data case but such a measure is now also foreseen for the MC to handle the embedded Pythia scenario. There is also a binning adjustment for the DR and jet area histograms.
=> Adding check for positive jet pt values in MC case

PWGGA/GammaConv/macros/AddTask_GammaCalo_pp.C
- At low pt, pi0 spectrum is affected by tight cut of M02 -> Opening cut to 0.7
- At high pt, the eta meson signal/background ratio significantly decreases if M02 cut is tightened
- Due to this, a energy dependent M02 cut is performed
=> PWGGA/GammaConv: Changed default upper M02 cut

PWGJE/EMCALJetTasks/UserTasks/AliJEQnVectorHandler.cxx, PWGJE/EMCALJetTasks/UserTasks/AliJEQnVectorHandler.h, PWGJE/EMCALJetTasks/macros/AddTaskJEQnVectors.C
Modifies the JEQnVector handler so that the calibration files are only loaded once, at job creation. OADBContainers are stored in task.
This removes an issue where the separate jobs running the task would individually attempt to download the event plane calibration files.
=> Critical improvement/fix to qnvector task

PWGGA/GammaConv/AliAnalysisTaskGammaCalo.cxx, PWGGA/GammaConv/AliAnalysisTaskGammaCaloMerged.cxx, PWGGA/GammaConv/AliAnalysisTaskGammaConvCalo.cxx, PWGGA/GammaConv/AliAnalysisTaskGammaConvV1.cxx, PWGGA/GammaConv/AliAnalysisTaskMesonJetCorrelation.cxx
- MC particles should be processed if for example, the wrong trigger was selected for the event. Currently, the number of generated particles was filled differently for different triggers. Triggered events had more counts as non-triggered due to the fact, that the non-triggered cases were captured, but others were not.
- Now, we fill the MC particles unless: The event did not have the correct centrality/multiplicity or if the vertex was outside +-10cm
=> PWGGA/GammaConv: Fix for processing MC particles

PWGJE/EMCALJetTasks/UserTasks/AliAnalysisTaskEmcalJetEnergyFlow.cxx
Fixing the response matrix calculation to use the correct detector level Dpt for the Pythia embedded case.
=> Update of the energy flow Response matrix for the embedded Pythia case

OADB/AliAnalysisUtils.cxx, OADB/AliAnalysisUtils.h
These helper methods allow to get the generated position of the trigger collision in case of simulations with pileup.
By using AliMCEvent::GetPrimaryVertexPosition, a position of (0,0,0) is obtained found for all events simulated with pileup (this was spotted for the general purpose Monte Carlo productions anchored to Pb-Pb). This is because the header of the cocktail generator does not store a primary vertex position, given that different pileup events occur in different position.
A modification in AliMCEvent (inside AliRoot) will also be committed in the next days.
=> Methods to retrieve generated vertex position in case of pileup

PWGHF/vertexingHF/AliAnalysisTaskSEXicPlus2XiPiPifromAODtracks.cxx, PWGHF/vertexingHF/AliAnalysisTaskSEXicPlus2XiPiPifromAODtracks.h
The 3D histogram storing the spectrum of generated particle is added to calculate the efficiency for the high multiplicity triggered event analysis.
And the classdef is increased as well.
=> Add an histogram for efficiency in HM analysis

PWGGA/GammaConv/AliAnalysisTaskConvJet.cxx, PWGGA/GammaConv/AliAnalysisTaskGammaCalo.cxx, PWGGA/GammaConv/AliAnalysisTaskGammaCalo.h, PWGGA/GammaConv/AliAnalysisTaskGammaConvCalo.cxx, PWGGA/GammaConv/AliAnalysisTaskGammaConvCalo.h, PWGGA/GammaConv/AliAnalysisTaskGammaConvV1.cxx, PWGGA/GammaConv/AliAnalysisTaskGammaConvV1.h, PWGGA/GammaConv/AliAnalysisTaskMesonJetCorrelation.cxx, PWGGA/GammaConv/AliAnalysisTaskMesonJetCorrelation.h, PWGGA/GammaConv/AliCutHandlerPCM.cxx, PWGGA/GammaConv/macros/AddTask_GammaCalo_pp.C, PWGGA/GammaConv/macros/AddTask_GammaConvCalo_pp.C, PWGGA/GammaConv/macros/AddTask_GammaConvV1_pp.C, PWGGA/GammaConv/macros/AddTask_MesonJetCorr_Calo.C, PWGGA/GammaConv/macros/AddTask_MesonJetCorr_Conv.C, PWGGA/GammaConv/macros/AddTask_MesonJetCorr_ConvCalo.C
finders
- To run the meson in jet analysis using different radii, the ConvJet task now can publish using different naming shemes, which are then beeing read in by the analysis task.
- Names are passed to the analysis task via the subwagon name, similar to the correction task setting (e.g. cutNr_JET:R02)
- Perp. cone was set to be only perpendicular in phi, not in eta
- Clean up histograms (move some to higher QA, lightOutput modes) to reduce memory consumption
=> PWGGA/GammaConv: Enable possibility to read input from different jet

PWGGA/GammaConv/AliAnalysisTaskGammaCalo.cxx, PWGGA/GammaConv/AliAnalysisTaskGammaCaloMerged.cxx, PWGGA/GammaConv/AliAnalysisTaskGammaCaloMerged.h, PWGGA/GammaConv/AliAnalysisTaskMesonJetCorrelation.cxx, PWGGA/GammaConv/AliCutHandlerPCM.cxx, PWGGA/GammaConv/macros/AddTask_GammaCaloMerged_pp.C, PWGGA/GammaConv/macros/AddTask_GammaCalo_pp.C, PWGGA/GammaConv/macros/AddTask_GammaConvCalo_pp.C, PWGGA/GammaConv/macros/AddTask_GammaConvV1_pp.C, PWGGA/GammaConv/macros/AddTask_MesonJetCorr_Calo.C, PWGGA/GammaConv/macros/AddTask_MesonJetCorr_Conv.C, PWGGA/GammaConv/macros/AddTask_MesonJetCorr_ConvCalo.C
MeonJet analysis
- In a previous commit, Jet container selection was enable via the subwagon via: trainNr_JET:containerName. However, the ":" character is not allowed on the train-page. Therefore it was now changed to trainNr_JETcontainerName
- Adjusted all AddTasks accordingly
- Added jet container selection for merged EMC task
=> PWGGA/GammaConv: Fix naming sheme for selecting jet containers in

PWGJE/EMCALJetTasks/UserTasks/AliAnalysisTaskJetExtractor.cxx, PWGJE/EMCALJetTasks/UserTasks/AliAnalysisTaskJetExtractor.h
Changes to AliAnalysisTaskJetExtractor.cxx and AliAnalysisTaskJetExtractor.h to allow for smaller tree outputs.
=> AliAnalysisTaskJetExtractor: option to further downsize output trees

PWGHF/vertexingHF/AliAnalysisTaskSEXic0SL.cxx
A runtime error was found during the test on an MC sample for pA:
this error did not come up when the code was tested on MC for pp
=> Xic0SL runtime error debug

PWGHF/vertexingHF/AliAnalysisTaskSEXicZero2XiPifromKFP.cxx, PWGHF/vertexingHF/AliNormalizationCounter.cxx
Fix bug with multiplicity evaluation in the function StoreEvent() and activate the multiplicity in the event counter for Xic0 -> Xi pi analysis
=> Fix bug in AliNormalizationCounter.cxx and activate the multiplicity in the event counter for Xic0 analysis

PWGJE/EMCALJetTasks/UserTasks/AliAnalysisTaskTrackSkim.cxx, PWGJE/EMCALJetTasks/UserTasks/AliAnalysisTaskTrackSkim.h
PWGJE: To keep track of the charge of a track with track skimming without the need to store a extra int per track we multiply the track pt by -1 for tracks with charge -1. This is only enabled after explicitly setting the correct flag.
=> PWGJE: Update to Track Skimming

PWGGA/GammaConv/AliAnalysisTaskGammaIsoTree.cxx, PWGGA/GammaConv/AliAnalysisTaskGammaIsoTree.h
- reduced size of photon isolation tree to avoid potential crashes when merging. Reduction is achieved by using float instead of double precision for the collision vertex and by only storing accepted events in data
=> [PWGGA/GammaConv] reduce size of isolation tree

PWGHF/vertexingHF/AliAnalysisTaskSEXic0SL.cxx, PWGHF/vertexingHF/AliAnalysisTaskSEXic0Semileptonic.cxx
Added QA plots for comparison between old <-> new frameworks, for online selection level
=> Xic0SL/Xic0Semileptonic online selection QA plot

PWGGA/GammaConv/AliPrimaryPionCuts.cxx, PWGGA/GammaConv/AliPrimaryPionCuts.h, PWGGA/GammaConv/macros/AddTask_GammaConvNeutralMesonPiPlPiMiNeutralMeson_ConvMode_pPb.C, PWGGA/GammaConvBase/AliConversionMesonCuts.cxx
- Added cutstrings to use TOF and restrict DCA for omega reconstruction
- Fixed TOF histogram labeling (->signal)
- Add pT dep. cut on the DCA_z for charged pions
- Fixed pi0 width for PCM pi0 mass cut
=> PWGGA/GammaConv: Fix pi0-mass range and add TOF and DCA cutstrings

PWG/EMCAL/EMCALbase/AliAnalysisTaskEmcal.cxx, PWG/EMCAL/EMCALbase/AliAnalysisTaskEmcal.h
Needed for service wagon which should run under
conditions as loose as possible to not create a bias
on consumer wagons which might have a different
(less strict) event selection
=> Optional no-event-selection mode

PWGCF/Correlations/JCORRAN/Pro/AliJCDijetAna.cxx, PWGCF/Correlations/JCORRAN/Pro/AliJCDijetAna.h, PWGCF/Correlations/JCORRAN/Pro/AliJCDijetHistos.cxx, PWGCF/Correlations/JCORRAN/Pro/AliJCDijetHistos.h, PWGCF/Correlations/JCORRAN/Pro/AliJCDijetTask.h, PWGJE/EMCALJetTasks/UserTasks/AliAnalysisTaskSVtaskMCFilter.cxx, PWGJE/EMCALJetTasks/UserTasks/AliAnalysisTaskSVtaskMCFilter.h
Reimplemented a function GetGenerator from AliVertexingHFUtils to the SVtaskMCFilter as the run would crash when using the function from HFUtils. I tried fixing the problem without copying it in numerous ways but unsuccesfully. Also added a histogram to the dijet code unrelated to this problem.
=> Fixed a library related bug at SVtaskMCFilter

PWGCF/FLOW/GF/AliAnalysisTaskGFWFlow.cxx, PWGCF/FLOW/GF/AliAnalysisTaskGFWFlow.h, PWGCF/FLOW/GF/AliGFWFilter.cxx, PWGCF/FLOW/GF/AliGFWFilter.h, PWGCF/FLOW/GF/AliGFWWeights.cxx, PWGCF/FLOW/GF/AliGFWWeights.h, PWGCF/FLOW/GF/CMakeLists.txt, PWGCF/FLOW/GF/GFWFlags.h, PWGCF/FLOW/GF/PWGCFFLOWGFLinkDef.h, PWGCF/FLOW/macros/AddTaskGFWFlow.C
--  Moving GFWFlags to a separate header for easier configuration.
--  NUAs are now stored in a TFile, and not as TList. The weight list is now generated on-fly in AddMacro, and only relevant weights are considered.
-- Set everything up to run a test for different NUA binning, as the standard NUAs are too heavy to be stored in a file.
-- AliGFWWeights has a deep copy constructor now
=> Overhaul of GFWFlow & friends, details in the comments:

PWGHF/vertexingHF/AliVertexingHFUtils.cxx
This is a test to reduce the bias obtained in the closure test of D mesons analyses. The D0 is the only neutral particle that we are including in the calculation, while D* and D+ are included already.
=> Added D0 in spherocity calculation

PWGHF/vertexingHF/AliAnalysisTaskSEXicPlusToXi2PifromKFP.cxx
Add PV infomration in the QA output tree (mass constraints for Lambda and Xi, topological constraints of Lambda to Xi, Xi to primary, Xi_c to primary).
=> Add PV infomration in the QA output tree

PWGMM/UE/UeKNO/AliAnalysisTaskFlatenicity.cxx
Signal loss and event loss events where wrongly added in the V0m classification histograms
=> Corrected classification for V0M for signal loss and event loss

PWGCF/FLOW/GF/AliAnalysisTaskDeform.cxx, PWGCF/FLOW/GF/AliAnalysisTaskDeform.h, PWGCF/FLOW/GF/AliAnalysisTaskGFWFlow.cxx, PWGCF/FLOW/GF/AliAnalysisTaskGFWFlow.h, PWGCF/FLOW/GF/AliAnalysisTaskGFWPIDFlow.cxx, PWGCF/FLOW/GF/AliAnalysisTaskGFWPIDFlow.h, PWGCF/FLOW/GF/AliAnalysisTaskJetQ.cxx, PWGCF/FLOW/GF/AliAnalysisTaskJetQ.h, PWGCF/FLOW/GF/AliAnalysisTaskMeanPtV2Corr.cxx, PWGCF/FLOW/GF/AliAnalysisTaskMeanPtV2Corr.h, PWGCF/FLOW/GF/AliGFW.cxx, PWGCF/FLOW/GF/AliGFW.h, PWGCF/FLOW/GF/AliGFWCumulant.cxx, PWGCF/FLOW/GF/AliGFWCumulant.h
Removed all dependences in the core of AliGFW from TComplex and TString. Cleaned up the code from deprecated methods. All tasks that are using the framework have been adjusted accordingly. The AliGFW is still working in ROOT types (Double_t, Int_t, etc.) for the sake of it, the types are included in AliGFWCumulant.h header. A completely root-free version is on my github (vvislavi/GFW_Core)
=> Migration of AliGFW away from root-specific classes

PWGCF/FEMTOSCOPY/AliFemtoUser/AliFemtoAnalysisPionPion.cxx
std::uniform_int_distribution requires integer type
via static_assert, char does not fullfil this. Using
uint8_t from stdint (same precision) with ASCII codes
of a and z, together with static_cast to char for random
string generation
=> Fix compilation under clang

PWGCF/Correlations/JCORRAN/Pro/AliJHFTagging.cxx, PWGCF/Correlations/JCORRAN/Pro/AliJHFTagging.h, PWGCF/Correlations/JCORRAN/Pro/CMakeLists.txt, PWGCF/Correlations/JCORRAN/Pro/PWGCFCorrelationsJCORRANProLinkDef.h, PWGCF/Correlations/macros/jcorran/AddTaskJHFTagging.C
A new calls for tagging the HF-jet has been implemented. It uses mainly two tagging algorithms, the IP and SV algorithms.
=> Adding a new task for HF-jet tagging

PWGGA/GammaConv/AliPrimaryPionCuts.cxx, PWGGA/GammaConv/AliPrimaryPionCuts.h, PWGGA/GammaConv/macros/AddTask_GammaConvNeutralMesonPiPlPiMiNeutralMeson_ConvMode_pPb.C
- Add rejection option, when TOF signal close to Kaon or Proton
- Add Cutstrings for TOF and DCA variations
=> PWGGA/GammaConv: Add TOF Kaon and Proton rejection option to omega task

PWGCF/FLOW/GF/AliAnalysisTaskDeform.cxx
Lead to breaking when trying to load weights.
=> Added missing MC flag. 

PWGHF/vertexingHF/AliVertexingHFUtils.cxx
Reverts alisw/AliPhysics#21889
The fix did not work, reverting to previous spherocity definition.
=> Revert "Added D0 in spherocity calculation"

PWGGA/GammaConv/AliAnalysisTaskConvJet.cxx, PWGGA/GammaConv/AliAnalysisTaskConvJet.h, PWGGA/GammaConv/AliAnalysisTaskMesonJetCorrelation.cxx, PWGGA/GammaConv/AliAnalysisTaskMesonJetCorrelation.h, PWGGA/GammaConvBase/AliResponseMatrixHelper.cxx, PWGGA/GammaConvBase/AliResponseMatrixHelper.h, PWGGA/GammaConvBase/PWGGAGammaConvBaseLinkDef.h
- Histograms added to study the meson production as function of jet pt, meson pt, and the radius between jet and meson
- As this needs an analyisis in three dimensions, a six dimensional unfolding matrix is needed. This is realized in a new NDimensional matrix handler
- Defintion of z changed from a simple division of the pts: z = ptMeson/ptJet to the scalar product of jet and meson momentum normalized to the squared lenght of the jet momentum. This allows the definition to be independent of the jet direction. As the Fragmentation should probe the momentum fraction of the meson to the jet, it should be in the reference frame of the jet
- px, py and pz of the true jet were added to the ConvJet task in order to properly calculate z
=> PWGGA/GammaConv: Add radius dependence to meson-jet corr.

PWG/EMCAL/EMCALbase/AliAnalysisTaskEmcal.cxx, PWG/EMCAL/EMCALtasks/AliEmcalCorrectionClusterizer.cxx, PWG/EMCAL/EMCALtasks/AliEmcalCorrectionTask.cxx, PWGGA/GammaConv/macros/AddTask_GammaCalo_pPb.C, PWGGA/GammaConv/macros/AddTask_GammaConvCalo_pPb.C, PWGGA/GammaConv/macros/AddTask_GammaConvV1_pPb.C
PWG/EMCal:
- switched by default to new centrality estimator for all EMCal central tasks
- modified warnings
- quited unnecessary warnings
PWGGA/GammaConv: 
- updated cuts for pPb: PCM, EMC, PCM-EMC to match latest greatest 13TeV cuts
=> PWG/EMCal: quited unnecessary warning, PWGGA/GammaConv: modified configs for PCM, PCM-EMC & EMC pPb

PWGJE/EMCALJetTasks/UserTasks/AliAnalysisTaskEmcalJetEnergyFlow.cxx, PWGJE/EMCALJetTasks/UserTasks/AliAnalysisTaskEmcalJetEnergyFlow.h, PWGJE/EMCALJetTasks/macros/AddTaskEmcalJetEnergyFlow.C
Update of the jet energy flow task to include the following changes:
a) Option to include a leading track pt cut for jets (set up as a class data member) b) Moving from absolute to relative jet energy response histograms c) Updated Dpt binning so that it is centered at zero d) Update of the mismatch histograms to absolute counts instead of ratio and be pt differential e) New RM type histogram for the mismatch cases
=> Update of the jet energy flow task to include the following changes

PWGGA/GammaConvBase/AliCaloPhotonCuts.cxx, PWGGA/GammaConvBase/AliCaloPhotonCuts.h, PWGGA/GammaConvBase/AliCaloTrackMatcher.cxx
- Track matching for PHOS in the AliCaloTrackMatcher imlied that phi is between 0 and 2pi. However the TVector3 returns phi in a range from -pi to pi.
- Therefore, phi values below 0 are now increased by 2pi to get the expected range.
- For QA purposes, a 2D hitmap is implemented in AliCaloPhotonCuts to show the position of matched clusters (if QA flag >=3)
=> PWGGA/GammaConv: Fix for PHOS track matching

PWGGA/GammaConv/macros/AddTask_GammaCalo_pPb.C, PWGGA/GammaConv/macros/AddTask_GammaConvCalo_pPb.C, PWGGA/GammaConvBase/AliCaloPhotonCuts.cxx
- for QA studies the outer PHOS modules are excluded, therefore new phi ranges are defined (4.55 - 5.24)
- added TrainConfigs for new cuts
=> PWGGA/GammaConv: New phi acceptance cuts for PHOS

PWGJE/EMCALJetTasks/UserTasks/AliAnalysisTaskEA.cxx, PWGJE/EMCALJetTasks/UserTasks/AliAnalysisTaskEA.h
New histograms needed for paper and thesis:
TH2D *fhPurity_InclusiveJets;
TH2D *fhNormalization_Purity;        
THnSparse *fhJetEnergy_Angle_Resol;
THnSparse *fhInclusiveRespMatrix_HM;
TH3D      *fhMissedEvents_HM;
Filip agreed with changes
=> Add histrograms required by IRC

PWGCF/FEMTOSCOPY/FemtoDream/AliAnalysisTaskOtonXx.cxx, PWGCF/FEMTOSCOPY/FemtoDream/AliAnalysisTaskOtonXx.h, PWGCF/FEMTOSCOPY/FemtoDream/AliFemtoDreamCascade.cxx, PWGCF/FEMTOSCOPY/FemtoDream/AliFemtoDreamTrackMCHist.cxx, PWGCF/FEMTOSCOPY/FemtoDream/AliFemtoDreamTrackMCHist.h, PWGCF/FEMTOSCOPY/macros/AddTaskOtonXx.C
-changes in AliFemtoDreamCascade to fix Common ancestors bug for Cascade
-Fix also annoying warning in MC hists by adding pion to the list of feed-down histograms for DCA (actually this was creating some memory problems when running pions in MC in Femto Dream!)
=> Add Common Ancestors for Cascade in FemtoDream

PWGGA/GammaConv/AliAnalysisTaskGammaCalo.cxx, PWGGA/GammaConv/AliAnalysisTaskGammaCalo.h, PWGGA/GammaConv/AliAnalysisTaskGammaConvCalo.cxx, PWGGA/GammaConv/AliAnalysisTaskGammaConvCalo.h, PWGGA/GammaConv/AliAnalysisTaskGammaConvV1.cxx, PWGGA/GammaConv/AliAnalysisTaskGammaConvV1.h, PWGGA/GammaConv/macros/AddTask_GammaCalo_pPb.C, PWGGA/GammaConv/macros/AddTask_GammaCalo_pp.C, PWGGA/GammaConv/macros/AddTask_GammaConvCalo_pPb.C, PWGGA/GammaConv/macros/AddTask_GammaConvCalo_pp.C, PWGGA/GammaConv/macros/AddTask_GammaConvV1_PbPb.C, PWGGA/GammaConv/macros/AddTask_GammaConvV1_pPb.C, PWGGA/GammaConv/macros/AddTask_GammaConvV1_pp.C, PWGGA/GammaConvBase/AliCaloPhotonCuts.cxx
- removed in jet analysis from GammaCalo, GammaConvCalo & GammaConvV1 task, full fledged implementation realized in a different task now AliAnalysisTaskMesonJetCorrelation* by @jokonig 
- fixed material weight handling in GammaConvCalo taks, weights were not correctly propagated to trees & truth info histos (errors incorrect after switching on material weights)
- removed scaling of pPb NL for NL: 01 & 5* for2013 & 2016 data
=> PWGGA/GammaConv: Removed in jet analysis from standard tasks & corrections for material weights in MC in Conv-Calo mode

PWGGA/GammaConv/macros/AddTask_GammaCalo_PbPb.C
- Add cut setting for rotation background with TM
- Add cut setting for mixed event without TM
- Add cut setting for mixed event with TM
- Without TM is for the usage of the cell track matcher and with track matching for when the cell track matcher is disabled
- Goals:
- Comaprison of rotation background with template fits and mixed event background
- Comparison of TM and Cell TM performance and agreement between data and MC
=> [PWGEM-13] PWGGA/GammaConv: Add EMC cut settings for PbPb

PWGGA/GammaConv/AliAnalysisTaskMesonJetCorrelation.cxx, PWGGA/GammaConv/AliAnalysisTaskMesonJetCorrelation.h, PWGGA/GammaConv/macros/AddTask_MesonJetCorr_Calo.C, PWGGA/GammaConv/macros/AddTask_MesonJetCorr_Conv.C, PWGGA/GammaConv/macros/AddTask_MesonJetCorr_ConvCalo.C, PWGGA/GammaConvBase/AliResponseMatrixHelper.cxx, PWGGA/GammaConvBase/AliResponseMatrixHelper.h
- For QA studies, the effect on the fragmentation function setting the pi0 as stable or unstable (so reconstructing the photons or the mesons directly). For this, the pi0s are set to stable in the jet tasks. To revert this change in the meson task, a new function is implemented that can be switched on.
- Fix in the binning of the resolution hists
- Some further optimizations for the NDimensional response matrix (still WIP)
=> PWGGA/GammaConv: Meson-Jet correlation: flag to set pi0 unstable

PWGGA/GammaConv/AliAnalysisTaskConvJet.cxx
- for MC, the jet task could only handle the mcparticles particle container. If one wants to use multiple particle container (for example setting the pi0 stable in one of them), this could not be handled by the conv jet task. Now, the string has only to contain the mcparticle name but can be mcparticleStablePi0 etc.
=> PWGGA/GammaConv: Change for jet task to handle different jet container

PWGHF/hfe/AliAnalysisTaskEHCorrel.cxx, PWGHF/hfe/AliAnalysisTaskEHCorrel.h, PWGHF/hfe/macros/AddTaskEHCorrel.C
Optimized AliAnalysisTaskEHCorrel task for Pb-Pb systematic studies; also edited task to accommodate LHC18q,r pass3 HFe Monte Carlo list. Edited AddTaskEHCorrel to include INT7 and CentTriggered events for Pb-Pb.
=> Optimized AliAnalysisTaskEHCorrel for Pb-Pb collisions for systematics

PWGHF/hfe/macros/AddTaskEHCorrel.C
Needed to include these functions in AddTask macro to switch on and off EMCal clusters, tracks, and had info for systematic runs
=> Fixed issue with switching EMCal clusters, tracks, and had info

PWGGA/GammaConv/AliAnalysisTaskConvJet.cxx, PWGGA/GammaConv/AliAnalysisTaskConvJet.h, PWGGA/GammaConv/AliAnalysisTaskMesonJetCorrelation.cxx, PWGGA/GammaConv/AliAnalysisTaskMesonJetCorrelation.h, PWGGA/GammaConv/macros/AddTask_MesonJetCorr_Calo.C, PWGGA/GammaConv/macros/AddTask_MesonJetCorr_Conv.C, PWGGA/GammaConv/macros/AddTask_MesonJetCorr_ConvCalo.C
- To better compare the mixed jet backgrund and the rotation background, an option is added where both background histograms are available in the same train (This saves CPU and memory in case one wants to compare them)
- Added QA flag for radius dependency studies
- Added new true jet histogram to monitor the number of particles of a true jet
=> PWGGA/GammaConv: Add additional option for mixed back

PWG/EMCAL/EMCALbase/AliEMCALRecoUtils.cxx, PWG/EMCAL/EMCALbase/AliEMCALRecoUtils.h, PWG/EMCAL/EMCALtasks/AliEmcalCorrectionCellEnergy.cxx, PWG/EMCAL/EMCALtasks/AliEmcalCorrectionCellEnergy.h, PWG/EMCAL/config/AliEmcalCorrectionConfiguration.yaml
- For run1, TRD modules with/witout TRD modules in front might need to be treated differently, as they have more/less material in front and as such more/less conversions etc.
- Instead of just having the eta dependent scale activated for run2, a total of 4 options for the cell scale is available now: 1 = default (Scales for Full, 2/3 and 1/3 SM), 2 = diff. scales for regions behind TRD support, 3 = Run1 scales behind SM with TRD in front and without, 4 = Same as 3 but additionally values for with and without TRD support structures
- These options can be set in the yaml file via fAdditionalScaleMode
- In order not to break existing analyses, the variable fUseAdditionalScale still has to be setto true if one wants to use a cell scale (and the variable has to stay a bool as its not evaluated …
=> PWG/EMCAL: Add option for cell scale for run1 w/wo TRD

PWGGA/GammaConv/AliAnalysisTaskMesonJetCorrelation.cxx, PWGGA/GammaConv/AliAnalysisTaskMesonJetCorrelation.h
- For events which are not triggered, the generator information still has to be processed to get the trigger efficiency correct
- Add histogram for jet pt for MC gen. jets for events that are not triggered
=> PWGGA/GammaConv: Add processing for true jets for not triggered events

PWGGA/GammaConv/AliAnalysisTaskMesonJetCorrelation.cxx
- Typo in definition of z: pz from meson was multiplied with py of jet when calculating the scalar product of the two vectors
=> PWGGA/GammaConv: Fix definition of z in MesonJetTask

PWGGA/GammaConv/AliAnalysisTaskMesonJetCorrelation.cxx, PWGGA/GammaConv/AliAnalysisTaskMesonJetCorrelation.h
- Histograms for the following cases: Both decay particles in jet, only one in jet, none in jet
- Also add histogram to monitor the case if it is not in the same jet
=> PWGGA/GammaConv: Add QA histograms for in-Jet study

PWGGA/GammaConv/AliAnalysisTaskMesonJetCorrelation.cxx, PWGGA/GammaConvBase/AliConvEventCuts.cxx
- In same way as for Pythia, check if a particle has more than x-times the momentum of the current generator pt hard of the event
- Add breaks in loop over mc-particles when event is rejected to save some cpu time
=> PWGGA/GammaConv: Add outlier rejection for Herwig JJ MC

PWGGA/GammaConv/AliAnalysisTaskConversionQA.cxx, PWGGA/GammaConv/AliAnalysisTaskConversionQA.h, PWGGA/GammaConv/macros/AddTask_PhotonQA.C
For low pt photons only a fraction as it used to be. Boarder between high and low pt can be modified.
=> PWGGA/GammaConv: Write all high pt photons to tree

PWG/EMCAL/EMCALtasks/AliEmcalCorrectionCellTrackMatcherAndMIPSubtraction.cxx, PWG/EMCAL/EMCALtasks/AliEmcalCorrectionCellTrackMatcherAndMIPSubtraction.h, PWG/EMCAL/config/AliEmcalCorrectionConfiguration.yaml, PWGGA/GammaConv/AliAnalysisTaskGammaCalo.cxx
- In the cell track matcher there is now the option `SubtractMultiple` which can be enabled. If this is enabled and a cell has less energy than the MIP energy of the matched particlethen a cell next to this one will be searched to subtract the remaining energy from this cell. The search direction is only in phi and prefers the direction the track is pointing. If this cell has no energy take the other one, if both have no energy than nothing will be done.
- Changed binning for the resolution histogram added in the PR #22452
=> [PWGEM-13] Add secondary cell energy subtraction for cell track matcher

PWGGA/GammaConv/AliAnalysisTaskConvJet.cxx, PWGGA/GammaConv/AliAnalysisTaskConvJet.h, PWGGA/GammaConv/AliAnalysisTaskMesonJetCorrelation.cxx, PWGGA/GammaConv/AliAnalysisTaskMesonJetCorrelation.h
- Fill histograms wit pt of true jet but only for true jets in the acceptance of reconstructed jets. This is to plot the acceptance and finding efficiency seperatly
=> PWGGA/GammaConv: Add acceptance check for jets

PWGGA/GammaConv/macros/AddTask_MesonJetCorr_Calo.C, PWGGA/GammaConv/macros/AddTask_MesonJetCorr_Conv.C, PWGGA/GammaConv/macros/AddTask_MesonJetCorr_ConvCalo.C, PWGGA/GammaConvBase/AliResponseMatrixHelper.cxx, PWGGA/GammaConvBase/AliResponseMatrixHelper.h
- Add cuts for: Mesons in eta<0.5 (for TPC fid acceptance
- Add cuts for EMCal fiducial acceptane with only the emcal trigger
- Add cuts with only the EMCal for mesons (excluding DCal))
- Add functionality to weight the response matrix according to a function (needed for unfolding studies)
=> PWGGA/GammaConv: MesonsInJets add cuts for different acceptance

PWGGA/GammaConv/AliAnalysisTaskMesonJetCorrelation.cxx, PWGGA/GammaConv/AliAnalysisTaskMesonJetCorrelation.h, PWGGA/GammaConv/macros/AddTask_MesonJetCorr_Calo.C, PWGGA/GammaConv/macros/AddTask_MesonJetCorr_Conv.C, PWGGA/GammaConv/macros/AddTask_MesonJetCorr_ConvCalo.C, PWGGA/GammaConvBase/AliConvEventCuts.cxx, PWGGA/GammaConvBase/AliResponseMatrixHelper.h
- Enable the possibility to only run z or pt histograms inside jets. This is needed as the eta cut and jet finder can be different for these quantities.
-Can be steered via new AddTask Argument and if 0, both z and pt will be run (as previously)
- Switch trigger to allow for correct trigger overlap rejection: New SpecialTrigger is added which clones the previous case 9 but does not have an automatic overlapp rejection for the gamma triggers
=> PWGGA/GammaConv: Add mode to run only pt or z inside jets

PWGGA/GammaConv/macros/AddTask_GammaCalo_PbPb.C
- Added new trainconfigs `950+` which are similar too the trainconfigs `750+`, only difference is that here the track matching is active , but only clusters that were matched with a track will be used instead of being rejected. This is for a study to find our how many tracks actually match a cluster and what the energy difference between cluster and actual photon is depending on the number of matched tracks.
=> PWGGA/GammaConv: Update AddTask_GammaCalo_PbPb.C

PWGGA/GammaConvBase/AliCaloPhotonCuts.cxx, PWGGA/GammaConvBase/AliCaloPhotonCuts.h
- Add new histogram `fHistClusterENMatchesConv` analog to `fHistClusterENMatchesNeutral` and `fHistClusterENMatchesCharged` for the cluster cases 4 and 5: 
4: Gamma conv cluster R < 180cm 
5: Gamma conv cluster R > 180cm 
This also means that `fHistClusterENMatchesCharged` now excludes conversion cluster! If this should be changed back again please write me!
=> PWGGA/GammaConvBase: Update AliCaloPhotonCuts.cxx

PWGGA/GammaConv/AliAnalysisTaskGammaConvCalo.cxx, PWGGA/GammaConv/AliAnalysisTaskGammaConvCalo.h, PWGGA/GammaConv/macros/AddTask_GammaCalo_PbPb.C
- Add a TH3D to monitor the invariant mass of true Pi0 as function of the cluster Energy and the number of matched primary tracks to this cluster. We saw in MC reco previously that there is basically no visible Pi0 peak when looking at more than 1 matched tracks indepented of centrality in PbPb 5TeV
- also aligend some comments in the AddTask_GammaCalo_PbPb.C
=> [PWGEM-13] PWGGA/GammaConv - Add True hist minv E Clus NPrimMatched

PWGCF/Correlations/KaonCorrelations/AliAnalysisTaskKaon2PC.cxx, PWGCF/Correlations/KaonCorrelations/AliAnalysisTaskKaon2PC.h
There was a small bug in the rejection procedure used in last commit. It is fixed here. Only primary tracks of neutral and charged kaons are used for correlation function measurement.
=> Kch and K0 resonance rejection

PWGGA/GammaConv/macros/AddTask_GammaCalo_pPb.C
Changed cut to evaluate the influence on nonlinearity discrepancy seen in PHOS Tender and PHOS Tender MC.
=> PWGGA: Changed M02 and NCell cut 

PWGCF/FEMTOSCOPY/AliFemto/AliFemtoEventReaderAOD.cxx
OOB pile-up method for the LHC18 dataset in the PbPb collision -> fixed
=> OOB pileup method for LHC18 PbPb

PWGGA/GammaConv/AliAnalysisTaskGammaPureMC.cxx, PWGGA/GammaConv/AliAnalysisTaskGammaPureMC.h, PWGGA/GammaConv/CMakeLists.txt, PWGGA/GammaConv/PWGGAGammaConvLinkDef.h, PWGGA/GammaConv/macros/AddTask_GammaPureMC.C, PWGGA/Hyperon/CMakeLists.txt
- In order to run MC predictions for the in-jet analysis, a jet finder and histograms for the pi0 and eta inside jets are implemented in the pure MC task
- Can be enabled via add task argument
- If add task argument set to 2, Pi0 and Eta are considered stable particles and are used in the jet finder instead of their decay products
=> PWGGA/GammaConv: Add in-jet histograms to pure MC task

PWGJE/EMCALJetTasks/UserTasks/AliAnalysisTaskEmcalJetEnergyFlow.cxx, PWGJE/EMCALJetTasks/UserTasks/AliAnalysisTaskEmcalJetEnergyFlow.h
Update on the application of the eta cut for the MC case in the Dpt calculation. In practice QA histograms have the same eta cut as detector level while the Response matrix is unrestricted
=> Eta cut update for MC plots

PWGGA/GammaConv/AliAnalysisTaskGammaCalo.cxx, PWGGA/GammaConv/AliAnalysisTaskGammaConvCalo.cxx
- In the current code, Pi0s are rejected if one of the clusters is not triggered.
- This leads to a discrepancy between the cluster and pi0 spectra of the triggered data as the clusters themselves dont have this requirement
- The code is commented to test if this fixes the discrepancies seen beween the pi0 spectra rejection factor and the cluster RF
=> PWGGA/GammaConv: Comment PHOS trigger rejection of pi0s

PWGGA/GammaConv/macros/AddTask_GammaIsoTree.C
due to an oversight three years ago the track pt cut was set to 100MeV instead of 150MeV
=> PWGGA/GammaConv: change track pt cut for isolation to 150MeV

PWGJE/EMCALJetTasks/UserTasks/AliAnalysisTaskEmcalJetHdEdxCorrelations.cxx
I think that somewhere a track does not have a valid second() (It's a bit unclear to me what this is, but it is the required input for the PID methods) In any case, I now check that my pointer to the output of this method is valid and skip it if it is not. Sorry for the lengthy debugging session.
=> Checking for valid pointer to VTrack

PWGJE/EMCALJetTasks/UserTasks/AliAnalysisTaskEmcalJetValidation.cxx
Hi @raymondEhlers and @Archita-Dash,
this PR only modifies the binning of the jet and track phi distributions.
This allows us to properly compare the results from AliPhysics to O2Physics within the JetValidation.
Best,
Johanna
=> [Run3JetValidation] modify binning according to tpc sectors

PWGGA/GammaConv/macros/AddTask_GammaConvCalo_PbPb.C, PWGGA/GammaConv/macros/AddTask_GammaConvCalo_pPb.C, PWGGA/GammaConv/macros/AddTask_GammaConvCalo_pp.C, PWGGA/GammaConv/macros/AddTask_GammaConvV1_PbPb.C
- Fixes an issue where giving a single FEPC file would result in an error message instead of just using that one file for all cuts.
=> [PWGEM-13] AddTask_GammaConv* - Fix single FEPC file option

PWGGA/PHOSTasks/ClusterSelection/AliPHOSTriggerUtils.cxx
- Trigger effiency curves are obtained by fitting ratio of cluster spectra from the L0-trigger flagged INT7 events to all INT7 events per ddl
- In this procedure, statistics is very limited.
- It was observed that the trigger efficiency in 2017 and 2018 in data is lower copared to MC simulations, the shape however fits
- Therefore, a global shift is introduced for the 2017 and 18 dataset to reduce the trigger efficiency to match the data
=> PWGGA/PHOS: Fine-tune trigger efficiency for pp 13 TeV

PWGGA/GammaConv/AliAnalysisTaskGammaCalo.cxx, PWGGA/GammaConvBase/AliCaloPhotonCuts.cxx
- Fix in GammaCalo task: Ppreviously the neutral overlap correction was not corretly applied, because it was only done when we would do the flat energy correction which should not be used together.
- Fix in CaloPhotonCuts: fParamMeanTrackPt values should be set for `fIsMC >= 1` with the MC values and not for `fIsMC > 1` which would only be for special MC like JJ MC. So before this fix normal MC used the same values as data, but we know that in MC the mean pT is lower than in data with HIJING.
=> [PWGEM] PWGGA: Fix neutral overlap correction:

PWGGA/GammaConv/AliAnalysisTaskGammaCalo.cxx
- Composition of pi0 and eta meson into clusters from photons and conversion was for now only enabled in normal min. bias MC
- For JJ MC this was not enabled due to heavy memory usage
- Enabled it now as statistics in min. bias MC not sufficient for PHOS studies above 20 GeV
=> PWGGA/GammaConv: Enable composition of pi0 and eta plots in JJ MC

PWGGA/GammaConv/AliAnalysisTaskGammaCalo.cxx
- In previous commit, histograms were enabled for JJ MC, however the weight per pthard bin was not applied for some histograms. This is fixed now
=> PWGGA/GammaConv: Fill histogram with weights for JJ MC

PWGJE/EMCALJetTasks/UserTasks/AliAnalysisTaskEmcalJetValidation.cxx
Hi @Archita-Dash ,
these are the small changes that helped increasing the similarity between AliPhysics and O2Physics.
- the track cut SetMaxFractionSharedTPCClusters does not exist in O2Physics and removing it increases the number of tracks in AliPhysics slightly (we still have less tracks in AliPhysics wrt. O2Physics).
- the pi mass in O2Physics is rounded to 0.139 now we do this in AliPhysics as well and only miss one jet in AliPhyisics wrt. O2Physics.
Cheerio,
Johanna
=> [JetValidationFramework] Fix pi mass and reduce track cuts

PWGGA/GammaConv/AliAnalysisTaskGammaCalo.cxx, PWGGA/GammaConv/AliAnalysisTaskGammaCalo.h, PWGGA/GammaConv/macros/AddTask_GammaCalo_pp.C, PWGGA/GammaConvBase/AliCaloPhotonCuts.cxx, PWGGA/GammaConvBase/AliCaloPhotonCuts.h
- Cut similar to PsiPair cut for PCM
- Calculate Angle with respect to z-direction
- For late conversion pairs angle should be 0. This is then used as a criterium to reject those clusters
=> PWGGA/GammaConv: Add late conversion rejection cuts for Calorimeters

PWGGA/GammaConv/macros/AddTask_GammaConvCalo_PbPb.C
- Add train configs for PbPb 5TeV with fine cent binning 10% seteps except 0-5 and 5-10 and with out TM, to check the Number of cells per cluster
=> [PWGEM-13] PWGGA/GammaConv: AddTask ConvCaloPbPb - Add train configs

PWGGA/GammaConv/macros/AddTask_GammaCaloMergedML_pp.C, PWGGA/GammaConv/macros/AddTask_GammaCaloMerged_PbPb.C, PWGGA/GammaConv/macros/AddTask_GammaCaloMerged_pPb.C, PWGGA/GammaConv/macros/AddTask_GammaCaloMerged_pp.C, PWGGA/GammaConv/macros/AddTask_GammaCaloMix_pp.C, PWGGA/GammaConv/macros/AddTask_GammaCalo_PbPb.C, PWGGA/GammaConv/macros/AddTask_GammaCalo_pPb.C, PWGGA/GammaConv/macros/AddTask_GammaCalo_pp.C, PWGGA/GammaConv/macros/AddTask_GammaConvCalo_PbPb.C, PWGGA/GammaConv/macros/AddTask_GammaConvCalo_pPb.C, PWGGA/GammaConv/macros/AddTask_GammaConvCalo_pp.C, PWGGA/GammaConv/macros/AddTask_GammaConvV1_PbPb.C, PWGGA/GammaConv/macros/AddTask_GammaConvV1_pPb.C, PWGGA/GammaConv/macros/AddTask_GammaConvV1_pp.C, PWGGA/GammaConv/macros/AddTask_MesonJetCorr_Calo.C, PWGGA/GammaConv/macros/AddTask_MesonJetCorr_Conv.C, PWGGA/GammaConv/macros/AddTask_MesonJetCorr_ConvCalo.C
Changed output file names of standard tasks to reduce load on lego-train pages:
- GammaCaloMergedML_* -> NmMML_*
- GammaCaloMerged_* -> NmM_*
- GammaCaloMix_* -> GCaMix_*
- GammaCalo_* -> GCa_*
- GammaConvCalo_* -> GCoCa_*
- GammaConvV1_* -> GCo_*
- MesonJetCorrelation_Calo_* -> MJC_Ca_*
- MesonJetCorrelation_ConvCalo_* -> MJC_CoCa_*
- MesonJetCorrelation_Conv_* -> MJC_Co_*
Without it operations on the lego train pages for the operators regarding adding file names had become impossible.
=> PWGGA/GammaConv: Shortening of root-output names

PWGJE/EMCALJetTasks/UserTasks/AliAnalysisTaskEmcalJetHdEdxCorrelations.cxx
It seems like occasionally my efficiencies are 0 in my mixed events causing the sparse to be unusable. This check and skips those cases. I don't think it will happen often(can't reproduce locally without hardcoding efficiency to 0) so the cout is probably ok even though it is bad code.
=> Handling weird efficiencies

PWGGA/GammaConv/AliAnalysisTaskGammaConvFlow.cxx, PWGGA/GammaConv/macros/AddTask_GammaConvFlow_PbPb2.C
- Adapted the V0ReaderTask to be similar to the PCM  tasks we use, where it gets the photonCutNumberV0Reader as input from the AddTask
- In AnalysisTask changes are just blanks for better overvie when trying to collapse code blocks ind IDEs
=> PWGGA: GammaConvFlow - adapated V0Reader usage from PCM task

cmake/FindRooUnfold.cmake
link_direcotries of the RooUnfold libdir
needed in order to trigger adding it
to RPATH
=> Fixing macOS RPATH for libRooUnfold

PWGLF/STRANGENESS/Cascades/Run2/AliAnalysisTaskStrangenessVsMultiplicityMCRun2.cxx, PWGLF/STRANGENESS/Cascades/Run2/AliAnalysisTaskStrangenessVsMultiplicityMCRun2.h
I need better resolution in HM range of fHistGeneratedPtVsYVsCentrality to compute efficiencies in highest multiplicity classes 0-0.01, 0.01-0.05 and 0.05-0.10%. This change only appears if the SetHM(kTRUE); is called, otherwise nothing changes.
=> Update for better resolution in HM range of generated particles

PWGCF/FEMTOSCOPY/EfficiencyTask/AliAnalysisTaskParticleEfficiencyMezonPhiDR.cxx
Something was overlooked, and resulted in one significant histogram to be empty
=> Fix to previous fix to eff

PWGCF/FEMTOSCOPY/AliFemtoUser/AliFemtoMJTrackCut.cxx, PWGCF/FEMTOSCOPY/AliFemtoUser/AliFemtoMJTrackCut.h
Modified the electron rejection cut to make it stricter. The default value is set to zero which rejects no electrons. Higher values of this parameter `fMaxNsigmaERejection` would reject more electrons.
=> Modifying electron rejection cut

PWGCF/FLOW/macros/AddTaskPtN.C
To avoid bug, I added empty lines after the macro AddTaskPtN.C
=> [PAG-Flow]Add empty lines after AddTaskPtN

PWGGA/GammaConv/AliAnalysisTaskGammaConvV1.cxx
This commit reduces the log file that is generated during the open-cut analysis from TPC recalibration
=>     PCM4ML: TPC recalib log fix

PWGGA/GammaConv/AliAnalysisTaskGammaIsoTree.cxx, PWGGA/GammaConv/AliAnalysisTaskGammaIsoTree.h
Previously, only MC information (i.e. PDG code) was only saved for leading contribution to each cluster. This is enough to identify signal photons but does not allow detailed studies, e.g. for cluster merging. Added an additional flag MCTagMore, which incorporates information from all cluster labels. After testing, this option could eventually replace the default MCTag.
=> PWGGA/GammaConv: added additional MC information for cluster

PWGGA/GammaConv/AliAnalysisTaskConvCaloCalibration.cxx, PWGGA/GammaConv/AliAnalysisTaskConvCaloCalibration.h, PWGGA/GammaConvBase/AliCaloPhotonCuts.cxx, PWGGA/GammaConvBase/AliCaloPhotonCuts.h
- Previous commit did not increment ClassDef, thus should fix it
- Also added spaces to some comments for AliAnalysisTaskConvCaloCalibration memebers which produced warnings before
PWGGA/GammaConv/AliAnalysisTaskConvCaloCalibration.cxx fix QAMesonFlag
- Fix a bug with the QAMesonFlag where a histogram is only initilized if its set, but was always accessed later.
=> PWGGA/GammaConv: AliCaloPhotonCuts - Increment ClassDef

PWGGA/GammaConvBase/AliCaloPhotonCuts.cxx
- Set `tempE` variable for 2nd iteration to E inside `CorrectEnergyForOverlap` if the energy is not at the threshold where it will be constant. Since the first iteration threshhold was lower than the energy threshold now, before this fix all values between the old threshhold and the new one would be set to the old treshold value
=> PWGGA/GammaConvBase/AliCaloPhotonCuts: Fix PbPb Nonlin like tempE

PWGGA/GammaConv/macros/AddTask_GammaCalo_PbPb.C, PWGGA/GammaConv/macros/AddTask_GammaConvCalo_PbPb.C, PWGGA/GammaConvBase/AliCaloPhotonCuts.cxx
- Added new LHC24a1 added signal MC to the GCoCa and GCa AddTasks to the injector header list
- Fixed `FindEnumForMCSet` implementation for `LHC24a1` since there are `LHC24a1a` and `LHC24a1b` it was changed to `namePeriod.BeginsWith("LHC24a1")` which was previously `namePeriod.ComparesTo("LHC24a1") == 0`.
=> PWGGA/GammaConv: Prepare (PCM-)EMC for LHC24a1 MC

PWG/EMCAL/EMCALbase/AliEMCALRecoUtils.cxx, PWG/EMCAL/EMCALbase/AliEMCALRecoUtils.h, PWG/EMCAL/EMCALtasks/AliEmcalCorrectionCellEnergy.cxx
- The absolute cell energy calibration is done in order to account for material in front of the detector, and hence not all cells should be calibrated to the nominal Pi0 mass. Effects due to the material are taken from MC simulations
- Previously, the Full, 2/3 and 1/3 SM types were calibrated seperatly, or the part where TRD support structures are visible had a different absolute calibration than the rest of the detector
- This new commit enables a column by column calibration, to refine the idea o calibrating the TRD support regions differntly
- This is only an esperimental setting! And is used to test calibration improvments for Run3
=> PWG/EMCAL: Add option for cell energy calibration per column

PWGGA/GammaConv/macros/AddTask_GammaCalo_PbPb.C, PWGGA/GammaConv/macros/AddTask_GammaConvCalo_PbPb.C, PWGGA/GammaConvBase/AliCaloPhotonCuts.cxx
- we need this change since we use the TM Cut also for secondaries
IMPORTANT: This will remove MIPSubtraction from the CaloPhotonCuts where it should not be used from anymore. MIPSubtraction should be used via the yaml config file for the EMCal Correction task.
=> PWGGA/GammaConv: - Changed CutSetting from no TM to standard PbPb TM

PWGJE/EMCALJetTasks/UserTasks/Cumulants.h
Obviously forward declarations are no longer allowed
if the object is used in templated class members as
template argument.
=> Fixes for c++20

PWGCF/FEMTOSCOPY/AliFemtoUser/AliFemtoPairCutMInv.cxx, PWGCF/FEMTOSCOPY/AliFemtoUser/AliFemtoPairCutMInv.h
The inheritance of AliFemtoPairCutMInv class is changed inorder to perform the rejection of phi meson resonance candidates using invariance mass cut.
=> Changing inheritance of AliFemtoPairCutMInv class

PWGCF/Correlations/JCORRAN/Pro/AliJHFTagging.cxx, PWGCF/Correlations/JCORRAN/Pro/AliJHFTagging.h, PWGCF/Correlations/macros/jcorran/AddTaskJHFTagging.C
The jet probability has been implemented to be used for the data-driven efficiency and purity estimation. With some histograms to be filled in order to make the resolution functions.
=> Adding histograms for data-driven efficiency estimation

PWGGA/GammaConv/AliAnalysisTaskGammaCalo.cxx, PWGGA/GammaConv/AliAnalysisTaskGammaCalo.h, PWGGA/GammaConv/AliAnalysisTaskGammaConvCalo.cxx, PWGGA/GammaConv/AliAnalysisTaskGammaConvCalo.h, PWGGA/GammaConv/macros/AddTask_GammaCalo_PbPb.C, PWGGA/GammaConv/macros/AddTask_GammaConvCalo_PbPb.C, PWGGA/GammaConvBase/AliCaloPhotonCuts.cxx, PWGGA/GammaConvBase/AliCaloPhotonCuts.h, PWGGA/GammaConvBase/AliConvEventCuts.cxx, PWGGA/GammaConvBase/AliConvEventCuts.h
- Add more options for injection header selection to `AddTask_GammaCalo_PbPb.C` and `AddTask_GammaConvCalo_PbPb.C`
- Add cluster timing cut for all MCs that are `kPbPb5T18HIJING`. This timing cut uses the width as in data, but also uses an offset, since we have seen an offset of 61.6 ns in all MCs anchored to LHC18qr
- Add a new NOC (neutral overlap correction) which was determined by fitting the mass^2 ratio of Pi0s in pp 13 TeV and PbPb 5.02 TeV with PCM-EMC as function of the cluster energy. The old NonLin like correction was fitted to EMC only data where the energy range was much smaller and the uncertainties made the fit very unstable. This should be a much better correction now.
- Add histogram `fHistoClusOverlapMBHeaderGammaPt` to AliAnalysisTaskGammaCalo, to track if cluster has …
=> PWGGA/GammaConv: EMC MC timing cut + new NOC

PWGGA/GammaConv/AliAnalysisTaskGammaConvV1.cxx, PWGGA/GammaConv/AliAnalysisTaskGammaConvV1.h
add two histos that allow for better comparison of meson true efficiencies between MC productions with differing pt shapes of generated particles
=> PWGGA/GammaConvV1: Add mc pt histo

PWGGA/GammaConv/macros/AddTask_GammaCalo_pp.C, PWGGA/GammaConv/macros/AddTask_GammaConvCalo_pp.C, PWGGA/GammaConvBase/AliCaloPhotonCuts.cxx
- For NonLin studies, add NonLin without cell sclae, but shift data and MC to the same mass position as if one would apply the cell scale
=> PWGGA/GammaConv: Add shifted NonLin without cell scale

PWGGA/GammaConv/AliAnalysisTaskGammaCalo.cxx, PWGGA/GammaConv/AliAnalysisTaskGammaConvCalo.cxx, PWGGA/GammaConv/macros/AddTask_GammaCalo_PbPb.C, PWGGA/GammaConv/macros/AddTask_GammaConvCalo_PbPb.C, PWGGA/GammaConvBase/AliCaloPhotonCuts.cxx, PWGGA/GammaConvBase/AliCaloPhotonCuts.h
- Add new NOC (Neutral Overlap Correction) trackmatching cut `x`
- Fix cluster headeroverlap histograms with MB header and reduce number of function calls of `IsParticleFromBGEvent` for GammaCalo and GammaConvCalo
- Add new train configs with new NOC to GammaCalo and GammaConvCalo
=> PWGGA/GammaConv: Add new NOC with Maxwell Boltzmann Fits

PWGGA/GammaConv/AliAnalysisTaskGammaConvCalo.cxx
- Swapped `currentEventGoodV0` and `previousGoodV0` when filling `fHistoMotherBackInvMassECalib` and `fHistoMotherBackInvMassECalibPCM` to match the expected type. This was wrong for mixing current clusters with previous conversion photons.
=> PWGGA/GammaConv: Fix `fHistoMotherBackInvMassECalib` for ConvCalo

PWGCF/FLOW/GF/AliAnalysisPtN.cxx, PWGCF/FLOW/GF/AliAnalysisPtN.h
I found that we should consider the difference it makes when filtering the 0-denominator of higer order pt. So I changed place to fill Nch-centrality histogram to make its entries consistent with pt, and add two histograms to test how Nch distribution change after filtering the 0-denominator.
=> [PAG-Flow] changed place to fill Nch-centrality histogram and add two histograms to test Nch distribution

PWGGA/GammaConv/AliAnalysisTaskConvJet.cxx, PWGGA/GammaConv/AliAnalysisTaskConvJet.h, PWGGA/GammaConv/macros/AddTask_GammaConvJet.C
- Cut out jets that are a certain distance to the border of the EMCal
- This is on order to study the effect if the jet is not fully on the EMCal (one of the leading uncertainties in the preliminary results)
- Cut can be set as an argument to the AddTask
- Cut is both eta and phi: If a cut of 0.4 is chosen, a jet with R=0.4 is guaranteed to be full on the EMCal (=fiducial acceptance).
=> PWGGA/GammaConv: MesonJetCorr: Add Jet acceptance restriction

PWGGA/GammaConv/AliAnalysisTaskGammaCalo.cxx, PWGGA/GammaConv/AliAnalysisTaskGammaCalo.h, PWGGA/GammaConv/AliAnalysisTaskGammaConvCalo.cxx, PWGGA/GammaConv/macros/AddTask_GammaCalo_PbPb.C, PWGGA/GammaConv/macros/AddTask_GammaConvCalo_PbPb.C
- changed minv and pT binning for PbPb 5.02 TeV for GCoCa and GCa
- excluded EventCutList, ClusterCutList and MesonCutList from Output if enableLightOutput > 1
=> PWGGA/GammaConv: Reduce Memory for PbPb

PWGGA/GammaConvBase/AliConvEventCuts.cxx
- The PR https://github.com/alisw/AliPhysics/pull/22412 introduced Herwig JJ MCs using the AliGenHepMCEventHeader in AliConvEventCuts
- Some EPOS JJ MCs have the same AliGenHepMCEventHeader and are subsequently flagged as Herwig JJ MCs and then dont enter the desired case (Pythia8jets embedded in EPOS for AODs)
=> PWGGA/GammaConv: Add protetction for HerwigJJ MC header

PWGGA/GammaConv/AliAnalysisTaskGammaCalo.cxx, PWGGA/GammaConv/AliAnalysisTaskGammaCalo.h, PWGGA/GammaConv/AliAnalysisTaskGammaConvCalo.cxx, PWGGA/GammaConv/AliAnalysisTaskGammaConvCalo.h, PWGGA/GammaConv/macros/AddTask_GammaCalo_PbPb.C, PWGGA/GammaConv/macros/AddTask_GammaConvCalo_PbPb.C, PWGGA/GammaConvBase/AliCaloPhotonCuts.cxx, PWGGA/GammaConvBase/AliCaloPhotonCuts.h
- Add new NOC correction to CaloPhotonCuts as cut `y` for trackmatching cuts
- Add new train configs for ConvCalo and Calo PbPb AddTasks to include the new NOC
- Add the histogram that was used to get this correction to ConvCalo
- Changed the histogram to be <E_clus-E_y>/E_y vs E_clus (was<E_clus-E_y>/E_y vs NMatched tracks vs p_T,clus)
=> PWGGA/GammaConv: ADd new NOC obtained from <E_clus-E_y>/E_y

PWG/EMCAL/EMCALbase/AliEMCALRecoUtils.cxx, PWG/EMCAL/EMCALbase/AliTrackContainer.cxx, PWG/EMCAL/EMCALtasks/AliAnalysisTaskEmcalTriggerPatchClusterMatch.cxx, PWG/EMCAL/EMCALtasks/AliEMCALClusterParams.cxx, PWG/EMCAL/EMCALtasks/AliEmcalAodTrackFilterTask.cxx, PWG/EMCAL/EMCALtasks/AliEmcalPatchFromCellMaker.cxx, PWG/EMCAL/EMCALtrigger/AliEmcalTriggerDecisionContainer.cxx, PWG/Tools/THistManager.h, PWG/Tools/yaml-cpp/include/yaml-cpp/node/detail/iterator.h, PWG/Tools/yaml-cpp/include/yaml-cpp/node/detail/node_iterator.h
This PR aims to fix all error messages that appear when building in debug mode and would hence prevent building in debug mode.
**PWG/EMCAL/EMCALbase/AliEMCALRecoUtils.cxx:**
- remove unsused variable `bool behindSupport = false;` PWG/EMCAL/EMCALbase/AliTrackContainer.cxx:
- comment out unsused varaible `// int nmatch(0);`
---
**PWG/EMCAL/EMCALtasks/AliAnalysisTaskEmcalTriggerPatchClusterMatch.cxx:**
- comment out unused variables `Int_t nG1 = 0, nG2 = 0, nJ1 = 0, nJ2 = 0, nL0 = 0;` 
---
**PWG/EMCAL/EMCALtasks/AliEmcalAodTrackFilterTask.cxx:**
- changed order of variables in constructor to match order in header file
- Fixed Warning message to get message via `"%s"` to be secure (Error: format string is not a string literal) 
---
**PWG/EMCAL/EMCALtasks/AliEMCALClusterParams.cxx:**
- remove …
=> Fix errors when building in debug mode

PWGCF/EBYE/IntermittencyAnalysis/AliAnalysisTaskNFactorialMoments.cxx, PWGCF/EBYE/macros/AddTaskNFactorialMoments.C
related to recent memory issues in CF lego trains, where PIDResponse is a dependency.
=> PWGCF: removing pidresponse as dep

PWGGA/PHOSTasks/CMakeLists.txt, PWGGA/PHOSTasks/PHOS_Run2/AliAnalysisPHOSNeutralMesonsAndPhotons.cxx, PWGGA/PHOSTasks/PHOS_Run2/AliAnalysisPHOSNeutralMesonsAndPhotons.h, PWGGA/PHOSTasks/PHOS_Run2/macros/AddTaskPHOSNeutralMesonsAndPhotons.C, PWGGA/PHOSTasks/PWGGAPHOSTasksLinkDef.h
This task largely based on AliAnalysisTaskPHOSPi0EtaToGammaGamma and contains:
- histograms for pi0, eta, photons analyses in Run 2;
- QA histograms for PID study, TOF cut study, trigger performance study;
- a major change compared to AliAnalysisTaskPHOSPi0EtaToGammaGamma: weighs (TOF/trigger) are applied to MC and not to data
=> PWGGA/PHOSTasks: added new task for neutral meson and photon analyses

PWGGA/PHOSTasks/PHOS_Run2/AliAnalysisPHOSNeutralMesonsAndPhotons.cxx, PWGGA/PHOSTasks/PHOS_Run2/AliAnalysisPHOSNeutralMesonsAndPhotons.h, PWGGA/PHOSTasks/PHOS_Run2/macros/AddTaskPHOSNeutralMesonsAndPhotons.C
Minor changes:
- added the reaction plane selection (for mixed events)
- added option for min bias PHOS clusters selection at low energies
- fixed PID criteria for PIDCutEff histos
- Mgg in PHOS M1 is lower than in other modules -> added option for energy correction in M1
=> PWGGA/PHOSTasks/PHOS_Run2: bugfix + added nonlin and weights for MC

PWGCF/FLOW/macros/AddTaskPtN.C
add NUE protection in the AddTask, avoid repeating creating the same container for subwagon running
=> add NUE protection for subwagon running

PWGGA/GammaConv/AliAnalysisTaskGammaCalo.cxx, PWGGA/GammaConv/AliAnalysisTaskGammaConvCalo.cxx
- Cluster QA flag > 0 now also enables the Cluster energy calib histograms instead of only the fDoECalib flag
- After changing the normalization for the cluster energy resolution from E_true to E_rec this commit changes the ranges for the resolution from (-1,+5) to (-5,+1)
=> PWGGA/GammaConv/TaskGamma(Conv)Calo: adjust flags for ECalib histos

PWGGA/GammaConv/AliAnalysisTaskGammaIsoTree.cxx, PWGGA/GammaConv/AliAnalysisTaskGammaIsoTree.h, PWGGA/GammaConv/macros/AddTask_GammaIsoTree.C
- Add two leafs that contain the mass when pairing the cluster closest to the pi0 and eta (Tagging)
- Add the central event selection when analyzing jets
- Add trainconfigs for 13TeV analyses
- Seperate the gen and rec pT cuts for jets from those for gammas
=> PWGGA/GammaConv: Modifications to the GammaIsoTree

PWGGA/GammaConv/AliAnalysisTaskGammaConvCalo.cxx, PWGGA/GammaConv/macros/AddTask_GammaCalo_PbPb.C, PWGGA/GammaConv/macros/AddTask_GammaConvCalo_PbPb.C, PWGGA/GammaConvBase/AliConvEventCuts.cxx
- To be able to only select MB header from the PbPb MCs we need the HeaderList which is given in the AddTask. This commit adds the HeaderList containing only Hijing (MB header) for the MC productions starting with `LHC18e1`, `LHC19h2` and `LHC18l8`. For the productions `LHC20j6`, `LHC20e3` and `LHC22b` Hijing and Pileup are added as HeaderList, since those productions contain simulated Pile Up.
- Some minor code style changes, especially changing the indentation of some comments so IDEs can properly collapse {} again...
=> PWGGA/GammaConv: AddTask G(Co)Ca - Add HeaderList for PbPb MCs

PWGGA/GammaConv/macros/AddTask_GammaConvV1_PbPb.C, PWGGA/GammaConvBase/AliConvEventCuts.cxx, PWGGA/GammaConvBase/AliConvEventCuts.h
As is, this change does not alter any functionality. It only adds one member function 'Float_t AliConvEventCuts::GetWeightForMesonNew...)' without ever calling it. The function allows to compute the pt weights from variant spectra in contrast to invariant spectra that were used up to now.  There will be another commit in short, that will add functionality for calling the function.
=> PWGGA/GammaConv: add functionality for calculating pT-weights in variant (=!invariant) mode

PWGGA/GammaConv/AliAnalysisTaskConvCaloCalibration.cxx, PWGGA/GammaConv/macros/AddTask_ConvCaloCalibration_CaloMode_pp.C, PWGGA/GammaConv/macros/AddTask_GammaConvCaloCalibration_MixedMode_pp.C, PWGGA/GammaConvBase/AliConversionMesonCuts.cxx
- Changed binning down to pt = 0
- Added configs with different minimum energy requirements
- Adjusted MesonQuality histogram to match the code (Previously, "out" component was not visible as MesonQuality was filled instead of "out")
=> PWGGA/GammaConv: Add configs for NonLin studies

PWGGA/GammaConv/macros/AddTask_ConvCaloCalibration_CaloMode_pp.C, PWGGA/GammaConv/macros/AddTask_GammaCalo_pp.C, PWGGA/GammaConvBase/AliCaloPhotonCuts.cxx, PWGGA/GammaConvBase/AliCaloPhotonCuts.h
- Cluster efficiency to match efficiencies between data and MC found with matched electrons
- Overloads the Dispersion cut: From cut ID 10 onwards (a in the cutstring), the efficiency for clusters is used
- TF1 is implemented that gives the difference between data and MC and randomly rejects clusters depending on their energy
- Experimental setting!! Dont use it for your analysis
=> PWGGA/GammaConv: Add option for cluster efficiency application

PWGGA/GammaConv/AliAnalysisTaskGammaCalo.cxx, PWGGA/GammaConv/AliAnalysisTaskGammaConvCalo.cxx
- Change x axis for V0 Mult histogram from (3000, 0, 30000) to (2000, 0, 40000) which is identical to the ConvV1 task. This change was necessary since we see mults larger than 30000.
=> PWGGA/GammaConv: TaskGamma(Conv)Calo - Increase PbPb V0 Mult max x

PWGGA/GammaConv/AliAnalysisTaskGammaCalo.cxx, PWGGA/GammaConv/AliAnalysisTaskGammaConvCalo.cxx
Currently particles which are coming from the MB header where marked as 2 from `IsParticleFromBGEvent`. For some reason particles that have 2 returned from that function which is only the case if they are MB AND ACCEPTED, they are marked as `fIsFromDesiredHeader = false`, so not from desired Header. This seems outdated, so I removed the case where particles from MB header are marked as `fIsFromDesiredHeader = false`
=> PWGGA/GammaConv: Fix particleFromBGEvent bug

PWGHF/treeHF/AliParticleTreeHandler.cxx, PWGHF/treeHF/AliParticleTreeHandler.h
Including MC particle ID information during tree production (for unfolding)
=> Adding MC id to tree_Particle and tree_Particle_gen in HF trees

PWGGA/GammaConv/macros/AddTask_ConvCaloCalibration_CaloMode_pp.C, PWGGA/GammaConvBase/AliCaloPhotonCuts.cxx, PWGGA/GammaConvBase/AliCaloPhotonCuts.h, PWGGA/GammaConvBase/AliGammaConvEventMixing.h
- Add M02 dependent histograms for detailed studies on the M02 cut
- Add electron mixing to estimate the background (fake matches) in data and MC
=> PWGGA/GammaConv: Additions to electron to cluster matching studies

PWGGA/GammaConv/macros/AddTask_GammaConvV1_PbPb.C
The effect of the bug was, that for the MBMC productions for LHCh15o and LHC18qr pt weighting could not be enabled because for these MCs we don't explicitly name the accepted particle headers (since we take all particles)
=> PWGGA/GammaConv: fix a pt weights related bug that I introduced with my latest commit.

PWGGA/GammaConv/AliAnalysisTaskConvCaloCalibration.cxx, PWGGA/GammaConv/AliAnalysisTaskConvCaloCalibration.h
- Width of the cluster might affect the rec. efficiency for clusters
- If clusters are wider, the seed threshold is not as easily reached as for narrower cluster
- To compare data and MC, two histograms are implemented: Fractional energy of leading cell of the cluster to the whole cluster, and the width of the cluster (standard deviation)
=> PWGGA/GammaConv: CalibTask: Add histograms for cluster width studies

PWGGA/GammaConv/AliAnalysisTaskGammaCalo.cxx, PWGGA/GammaConv/macros/AddTask_GammaCalo_pp.C
- Secondary track matching previously only worked if the first cut in the trainconfig had secondary TM enabled. This was changed and now it should work even if its not the first cut in the config
- Light output analogous to the GammaConvCalo task is implemented for the GammaCalo task, meaning that the Calo and Conv cuts are not producing histograms if light output set to > 1. This is needed for systematics, especially in the MC, as otherwise the memory consumption can get super high with many trainconfigs enabled
=> PWGGA/GammaConv: GammaCalo: Fix sec. track matching and enable more light output

PWGGA/GammaConv/AliAnalysisTaskGammaCalo.cxx, PWGGA/GammaConv/AliAnalysisTaskGammaCalo.h, PWGGA/GammaConv/macros/AddTask_GammaCalo_pp.C, PWGGA/GammaConvBase/AliConversionMesonCuts.cxx, PWGGA/GammaConvBase/AliConversionMesonCuts.h
- Cut away cluster pairs that have a mass in the pi0 mass region.
- This should allow to reduce the background in the eta measurement
- Can be activated in the MesonCuts with 2 new cuts added
=> PWGGA/GammaConv: Add option to apply prefilter (for eta meson)

PWGGA/GammaConv/macros/AddTask_GammaConvV1_PbPb.C
small fix. The issue was that even when the new pt weights method (= pt variantly calculated pt weights) was specified, the old was method was used.
=> PWGGA/GammaConv: fix for var. ptW in AddTask_GammaConvV1_PbPb.C

PWGGA/GammaConv/AliAnalysisTaskGammaConvV1.cxx, PWGGA/GammaConv/AliAnalysisTaskGammaConvV1.h, PWGGA/GammaConv/CMakeLists.txt, PWGGA/GammaConv/macros/AddTask_ConversionAODProduction.C, PWGGA/GammaConv/macros/AddTask_GammaConvV1_pp.C, PWGGA/GammaConvBase/AliConversionPhotonCuts.cxx, PWGGA/GammaConvBase/AliConversionPhotonCuts.h, PWGGA/GammaConvBase/AliV0ReaderV1.cxx, PWGGA/GammaConvBase/AliV0ReaderV1.h, PWGGA/GammaConvBase/CMakeLists.txt, RUN3/AliAnalysisTaskAO2Dconverter.cxx, RUN3/AliAnalysisTaskAO2Dconverter.h, RUN3/CMakeLists.txt
This commit (from @mhemmer-cern - super thanks!) adds a path for saving on-the-fly V0s in our converted AO2D. I'm marking this as draft for discussion and will still make a few minor changes (mccollisions version bump to 001, for instance) before marking ready for review.
=> Run 3 converter: addition of OTF V0s

PWGJE/EMCALJetTasks/AliEmcalJetUtilitySoftDrop.cxx, PWGJE/EMCALJetTasks/AliEmcalJetUtilitySoftDrop.h, PWGJE/EMCALJetTasks/AliFJWrapper.h, PWGJE/EMCALJetTasks/FJ_includes.h, PWGJE/EMCALJetTasks/UserTasks/AliAnalysisTaskIDFragmentationFunction.cxx, PWGJE/EMCALJetTasks/UserTasks/AliAnalysisTaskIDFragmentationFunction.h, PWGJE/macros/AddTaskIDFragmentationFunction.C
Replace SoftDrop in AliFJWrapper with RecursiveSoftDrop, standard value for recursive depth is N=1 which corresponds to standard soft drop. Add settings for recursive depth, zCut and beta in the soft drop functionality
Recursive Soft Drop with N=1 corresponds to standard soft drop: https://phab.hepforge.org/source/fastjetsvn/browse/contrib/contribs/RecursiveTools/trunk/README
=> Improve AliFJWrapper/Add Functionality To SoftDropUtility/Add to analysis task

PWGCF/FEMTOSCOPY/FemtoDream/CMakeLists.txt, PWGGA/CMakeLists.txt, PWGGA/Common/AliAODRelabelInterface.cxx, PWGGA/Common/AliAODRelabelInterface.h, PWGGA/Common/CMakeLists.txt, PWGGA/Common/PWGGACommonLinkDef.h, PWGGA/GammaConv/CMakeLists.txt, PWGGA/GammaConvBase/AliConversionPhotonCuts.cxx, PWGGA/GammaConvBase/AliConversionPhotonCuts.h, PWGGA/GammaConvBase/AliV0ReaderV1.cxx, PWGGA/GammaConvBase/AliV0ReaderV1.h, PWGGA/GammaConvBase/CMakeLists.txt, RUN3/AliAnalysisTaskAO2Dconverter.cxx, RUN3/AliAnalysisTaskAO2Dconverter.h
The `AliAnalysisTaskAO2DConverter` needed to know of `AliV0ReaderV1` and vice versa. This commit adds the class `AliAODRelabelInterface` which is a new base class that inherits itself from the `AliAnalysisTaskSE` class and that `AliV0ReaderV1` and `AliAnalysisTaskAO2DConverter` inherit from. This way both classes only need the one new class and do not need to know from each other. Inside PWGGA/GammaConvBase/AliConversionPhotonCuts both classes were also needed because there in the function `GetTrack` one needs to check if the V0s are already relabeled.
=> [RUN3, PWGGA] Fix circle dependency

PWG/DevNanoAOD/CMakeLists.txt, PWG/FLOW/Tasks/CMakeLists.txt, PWGDQ/dielectron/CMakeLists.txt, PWGGA/Hyperon/CMakeLists.txt, PWGGA/PHOSTasks/CMakeLists.txt, PWGHF/jetsHF/CMakeLists.txt
- Added `${AliPhysics_SOURCE_DIR}/PWGGA/Common` to the `include_directories` everywhere, where the `AliV0ReaderV1` is included, since the `AliV0ReaderV1` includes the new `AliAODRelabelInterface.h` which is in `PWGGA/Common`. This should fix the compile errors we saw after the merge of PR #23753
=> [PWG, PWGDQ, PWGGA, PWGHF] Fix CMakeLists.txt missing include directory

RUN3/AliAnalysisTaskAO2Dconverter.cxx, RUN3/AliAnalysisTaskAO2Dconverter.h
Hi @pzhristov @ddobrigk @jgrosseo this PR fixes some bugs in O2trackextra_v001, O2zdc_v001, and O2mccalolabel_v001:
- Go from fITSClusterMap to fITSClusterSizes in the trackestra table
- Fix the streaming of std::vector columns for the zdc and mccalolabel tables by adding the "_size" columns
This version of the converted data is correctly read by O2
=> RUN3: fix bumped table versions (O2trackextra, O2zdc, O2mccalolabel)

PWGGA/Common/AliAODRelabelInterface.h, RUN3/AliAnalysisTaskAO2Dconverter.h
@ddobrigk @pzhristov @jgrosseo I added an explicit default constructor to AliAODRelabelInterface since in the previous version this was missing and caused the default constructor of AliAnalysisTaskAO2DConverter to be implicitly deleted, see for instance the following lines from the log of a previous build https://ali-ci.cern.ch/alice-build-logs/alisw/AliPhysics/23768/0de7954073758b13fce18d20ee393042bd1c749d/build_AliPhysics_root6/fullLog.txt
```
In file included from input_line_9:12:
/sw/SOURCES/AliPhysics/23768-slc7_x86-64/0/RUN3/AliAnalysisTaskAO2Dconverter.h:74:3: warning: explicitly defaulted default constructor is implicitly deleted [-Wdefaulted-function-deleted]
AliAnalysisTaskAO2Dconverter() = default;
^
/sw/SOURCES/AliPhysics/23768-slc7_x86-64/0/RUN3/AliAnalysisTaskAO2Dconverter.h: …
```
=> RUN3: add default constructor to interface + increase class version

PWGJE/EMCALJetTasks/UserTasks/AliAnalysisTaskCascadesInJets.cxx, PWGJE/EMCALJetTasks/UserTasks/AliAnalysisTaskStrangenessInJets.cxx
solution for fastjet bg estimator fail in GeneratedMCParticles because of an empty bg subtractor
=> Change in MCGenerated function

RUN3/AliAnalysisTaskAO2Dconverter.cxx
- Renaming of the V0otfs table to Run2V0otfs to go hand in hand with the table name we want in the O2 framework.
=> [RUN3] Rename V0otfs to Run2V0otfs

RUN3/AliAnalysisTaskAO2Dconverter.cxx, RUN3/AliAnalysisTaskAO2Dconverter.h
This PR adds an experimental path to save PMD information. It is disabled by default and unless specifically requested, will not be saved. It is intended for larger-scale tests of a solution that has been verified to be functional already in local testing.
=> Run 3 converter: add PMD 

RUN3/AliAnalysisTaskAO2Dconverter.cxx, RUN3/AliAnalysisTaskAO2Dconverter.h
This commit bumps up the version of the BC table such that no BC 000 to 001 converter is necessary for it when analysing converted data from this point forward.
=> Run 3 converter: bump up BC version to 001

PWGGA/GammaConv/AliAnalysisTaskMesonJetCorrelation.cxx, PWGGA/GammaConv/AliAnalysisTaskMesonJetCorrelation.h, PWGGA/GammaConv/macros/AddTask_MesonJetCorr_Calo.C, PWGGA/GammaConvBase/AliGammaConvEventMixing.h, PWGGA/GammaConvBase/PWGGAGammaConvBaseLinkDef.h
- Particle abundancies in the MC do not represent the ones in data. Hence, the jet response matrix is weighted according to the differences in particle abundancies between MC and data
=> PWGGA/GammaConv: Add option to apply weighting to jet repsonse matrix

RUN3/AliAnalysisTaskAO2Dconverter.cxx, RUN3/AliAnalysisTaskAO2Dconverter.h
Adds previously absent fwd track labels in conformity to Run 3 data model (transparent)
=> Run 3 converter: add missing fwd track labels

PWGGA/GammaConv/AliAnalysisTaskMesonJetCorrelation.cxx, PWGGA/GammaConv/AliAnalysisTaskMesonJetCorrelation.h
- Histogram to check the weighting procedure (do the weighted particles really apprear less/more)
- Moved weighting into InitializeJets to save some CPU time and also to have access to the weights in the entire task
=> PWGGA/GammaConv: Add weighted histogram for particles inside jets

PWGGA/GammaConvBase/AliCaloPhotonCuts.cxx
- ToLower made it impossible to select cutstrings based on lower or upper case.
=> PWGGA/GammaConv: Fix to enable cutstring beyond z

PWGCF/Correlations/JCORRAN/Pro/CMakeLists.txt
AliPhysics builds normally without this library in the CMakeFiles, and removing it allows to run the AliAnalysisTaskSVtaskMCFilter which needs lib PWGHFvertexingHF
=> removed PWGHFvertexingHF library dependency

PWGGA/GammaConv/AliAnalysisTaskGammaCalo.cxx
- Bugfix for `fHistoTruePrimaryEtaRecPtMCPtVsMass`. `vecInvMassEta` got wrong values pushed back (minvPi0 instead of minvEta), which broke the invariant mass axis of this histo. This PR should fix this.
=> [PWGGA] AliAnalysisTaskGammaCalo.cxx - Bugfix for PR #23858

RUN3/AliAnalysisTaskAO2Dconverter.cxx, RUN3/AliAnalysisTaskAO2Dconverter.h
- Save hybrid tracks in AOD -> AO2D conversions
- Save event bit information in AOD -> AO2D conversions
- Implement flags to turn hybrid track and event bit saving on (the saving is off by default)
tagging also @ddobrigk
=> [RUN3] AOD conversion: save hybrid tracks, event bits

PWGGA/GammaConvBase/AliConvEventCuts.cxx, PWGGA/PWGGAUtils/utils_TH1.cxx, PWGGA/PWGGAUtils/utils_TH1.h
of utils_TH1::GlobalPieceWiseExponentialInterpolation() and set it as default when calculating weights from variant spectra.
=> PWGGA/GammaConv: ptWeights: add possibility to use  integral condition for fitting the local functions

PWGGA/GammaConv/macros/AddTask_GammaConvV1_PbPb.C
Initialize pt-weights only for centrality classes that are contained in the used MC production.
=> PWGGA/GammaConv: Small fix for pt-weights

PWGGA/GammaConvBase/AliConvEventCuts.cxx, PWGGA/GammaConvBase/GammaConvTH1ExponentialInterpolation.cxx, PWGGA/GammaConvBase/GammaConvUtilsTH1.cxx, PWGGA/GammaConvBase/GammaConvUtilsTH1.h
Make
- fUtils_TH1 live on stack of AliConvEventCuts
- all utils_TH1::TH1_ExponentialInterpolation live in map fMap_TH1_ExponentialInterpolation.
Still missing, if possible:
create native global TF1 objects on stack.
=> PWGGA/GammaConv: Exp inter move all to stack:  1/2

PWG/EMCAL/EMCALtasks/AliEmcalCorrectionCellEmulateCrosstalk.cxx
When inserting a new cell at the end of the cross talk the check to ensure that the same cell is not inducnig to itslef was wrong:
```c++
if ( iphii==0 && ietai == 0) continue;
```
It should be
```c++
if ( iphii == iphi && ietai == ieta) continue;
```
The impact of this bug is unknown. I guess it basically just means that before this fix the cell (0,0) was not allowed to induce energy into a new cell, which is a very specific edge case.
=>  PWG/EMCAL: Fix CrossTalk same cell check

PWGGA/GammaConv/macros/Add_MCGenPythia8_TuneX.C
- Previously, the option "longlived" was not used before
=> PWGGA/GammaConv: Add option for long-lived particle exclusion.

PWGGA/GammaConv/AliAnalysisTaskMesonJetCorrelation.cxx, PWGGA/GammaConv/AliAnalysisTaskMesonJetCorrelation.h
- Add Tracks instead of V0s
- Each track can only enter once
- Loose track cuts applied including to ask that track is not hybrid (as hybrids are already counted)
=> PWGGA/GammaConv: Refine method to add V0s in Jets

PWGGA/GammaConv/AliAnalysisTaskConvJet.cxx
- Now the direction of the v0 is taken instead of the daughter tracks. This helps in case only one of the tracks is accepted.
=> PWGGA/GammaConv: SLightly modify on how V0s are added to the jets
