- PWGCF/Correlations/JCORRAN/Pro/AliAnalysisTaskRidge.cxx
updates for corrected jet pt bin
> [PWGCF] updates for jet pt bin

- PWG/EMCAL/EMCALbase/AliAnalysisTaskEmcalEmbeddingHelper.cxx
@gconesab hopefully this will be clearer
> Make inaccessible files message more prominent

- PWGGA/GammaConvBase/AliConversionPhotonCuts.cxx
- PWGGA/GammaConvBase/AliConversionPhotonCuts.h
> PWGGA/GammaConv: Remove superflous fMinRDC member

- PWGCF/FEMTOSCOPY/FemtoDream/AliAnalysisTaskPOmegaPenne.cxx
- PWGCF/FEMTOSCOPY/FemtoDream/AliAnalysisTaskPOmegaPenne.h
- PWGCF/FEMTOSCOPY/macros/AddTaskPOmegaPenne.C
> CPA stats for each step of cleaning

- PWGMM/Lumi/vdM/VdmStability/AddTask_ilofnes_Vdm.C
- PWGMM/Lumi/vdM/VdmStability/AliAnalysisTaskVdmStability.cxx
- PWGMM/Lumi/vdM/VdmStability/AliAnalysisTaskVdmStability.h
New selection cut to study the effects w&w/o PU rejection to be able to compare to the Poisson correction applied in mu analyses
> Including New Case

- PWGLF/SPECTRA/ChargedHadrons/MultDepSpec/AliMultDepSpecAnalysisTask.cxx
- PWGLF/SPECTRA/ChargedHadrons/MultDepSpec/AliMultDepSpecAnalysisTask.h
- PWGLF/SPECTRA/ChargedHadrons/MultDepSpec/AliMultDepSpecAnalysisTaskUE.cxx
- PWGLF/SPECTRA/ChargedHadrons/MultDepSpec/AliMultDepSpecAnalysisTaskUE.h
- PWGLF/SPECTRA/ChargedHadrons/MultDepSpec/macros/AddTask_mkrueger_MultDepSpecUE.C
- PWGLF/SPECTRA/ChargedHadrons/MultDepSpec/macros/AddTask_mkrueger_MultDepSpecUEMC.C
- observables can now be studied in toward and away side (additionally to transverse side)
- multiplicity is now always counted in transverse side (UE)
> added toward/away side, mult is now always UE mult

- PWGHF/hfe/AliAnalysisTaskHFEBESpectraEMC.cxx
- PWGHF/hfe/AliAnalysisTaskHFEBESpectraEMC.h
- Updating TPC track cuts - TPCCrossed rows and ratio of TPCCrossrows over findable
- Adding additional pile-up event rejection
- Adding histograms for TPConly efficiency before EMC track match
> Add new pileup+track cuts, Add TPCnsig only effi

- PWGDQ/dielectron/LMEE/AliAnalysisTaskLMeeCocktailMC.cxx
- PWGDQ/dielectron/LMEE/AliAnalysisTaskLMeeCocktailMC.h
Make life easier for local test with new resolution maps
> Make life easier for local test with new resolution maps

- PWGLF/NUCLEX/Hypernuclei/KFHypertriton/AddHypertritonKFTree.C
Moved trees inside a container with different name depending on the set up of the add task
> Modification of AddTask to run with different set up in one LEGO train

- PWGCF/Correlations/DPhi/AliAnalysisTaskSEpPbCorrelationsJetV2.cxx
- PWGCF/Correlations/macros/pPbCorrelations/AddTaskpPbCorrelationsJetV2.C
Hi,
Here is an update for Jet v2 analysis code, where the asso pt information is added for trigger pair.
Thanks! 
Siyu
> Add asso-pt information

- PWGJE/EMCALJetTasks/Tracks/AliAnalysisTaskEmcalJetEnergyScale.cxx
JES vs NEF, ncharged, nneutral, ..., in bins of pt,part, for understanding of the shape of the JES
> Add histograms for debugging the JES

- PWGDQ/dielectron/core/AliAnalysisTaskTagAndProbe.cxx
- PWGDQ/dielectron/core/AliAnalysisTaskTagAndProbe.h
> PWGDQ/LMEE: support for ESD V0

- PWGCF/FEMTOSCOPY/FemtoDream/AliAnalysisTaskGeorgiosNTuple.h
- PWGCF/FEMTOSCOPY/macros/AddTaskGeorgiosNTuple.C
(without wider invariant Mass cuts)
> Create the NTuple with Montecarlo data for  LambdaLambda

- PWGJE/EMCALJetTasks/Tracks/AliAnalysisTaskEmcalSoftDropResponse.cxx
SoftDrop failure handling separated for det. level and
part. level:
- Failed handling at part. level treated as impurity in det.
level loop
- Failed handling at det. level treated as inefficiency in
part. level loop
Consequently increasing the number of tag bins from 3 to 4.
Only pairs of part. and det. level jets entering the
response matrix.
> Re-organization of failed part. level SoftDrop

- PWGPP/ZDC/macros/DrawPerformanceZDCQAMatch.C
As described in the subject these changes should fix the a problem causing a crash in ZDC QA.
Chiara
> Update to fix a problem with ZDC QA

- PWG/EMCAL/EMCALbase/AliAnalysisTaskEmcal.cxx
- PWG/EMCAL/EMCALbase/AliAnalysisTaskEmcal.h
- PWG/EMCAL/EMCALbase/AliEmcalMCPartonInfo.cxx
- PWG/EMCAL/EMCALbase/AliEmcalMCPartonInfo.h
- PWG/EMCAL/EMCALtasks/AliEmcalMCPartonInfoCreator.cxx
- PWGJE/EMCALJetTasks/AliAnalysisTaskPWGJEQA.cxx
- PWGJE/EMCALJetTasks/Tracks/AliAnalysisTaskEmcalJetEnergyScale.cxx
- Add lightweight data object that is owned by the MC parton container
- Enable getting parton info object in the AliAnalysisTaskEmcal if the container name is set
> Fixes for Herwig7 production

- PWGDQ/dielectron/core/AliAnalysisTask_JPsi_EMCal.cxx
- PWGDQ/dielectron/core/AliAnalysisTask_JPsi_EMCal.h
Added few new histos for the J/psi emcal analysis
>  few new histos to study tracks/clusters/electrons in period by period

- PWG/EMCAL/EMCALbase/AliAnalysisTaskEmcal.cxx
- PWG/EMCAL/EMCALbase/AliAnalysisTaskEmcal.h
- PWGJE/EMCALJetTasks/Tracks/AliAnalysisTaskEmcalJetEnergyScale.cxx
- PWGJE/EMCALJetTasks/Tracks/AliAnalysisTaskEmcalJetEnergyScale.h
- PWGJE/EMCALJetTasks/Tracks/AliAnalysisTaskEmcalJetEnergySpectrum.cxx
- PWGJE/EMCALJetTasks/Tracks/AliAnalysisTaskEmcalJetEnergySpectrum.h
- PWGJE/EMCALJetTasks/Tracks/AliAnalysisTaskEmcalSoftDropData.cxx
- PWGJE/EMCALJetTasks/Tracks/AliAnalysisTaskEmcalSoftDropData.h
- PWGJE/EMCALJetTasks/Tracks/AliAnalysisTaskEmcalSoftDropResponse.cxx
- PWGJE/EMCALJetTasks/Tracks/AliAnalysisTaskEmcalSoftDropResponse.h
Aim: Reduce amount of code in wagon configuration
> Add functions to configure tasks with single lines

- PWGGA/GammaConv/AliAnalysisTaskGammaCalo.cxx
- PWGGA/GammaConv/AliAnalysisTaskGammaCalo.h
- PWGGA/GammaConv/AliAnalysisTaskGammaConvCalo.cxx
- PWGGA/GammaConv/AliAnalysisTaskGammaConvCalo.h
- PWGGA/GammaConv/macros/AddTask_GammaCalo_pp.C
- PWGGA/GammaConv/macros/AddTask_GammaConvCalo_pp.C
- PWGGA/GammaConvBase/AliConvEventCuts.cxx
- PWGGA/PHOSTasks/ClusterSelection/AliCaloTriggerMimicHelper.cxx
- PWGGA/PHOSTasks/ClusterSelection/AliCaloTriggerMimicHelper.h
Sorry, but due to a rebase issue i got foreign commits in my request
> PWGGA: Add Histograms for Trigger Rejection to PHOS, Rebase Issue

- PWGDQ/dielectron/core/AliAnalysisTaskTagAndProbe.cxx
- PWGDQ/dielectron/core/AliAnalysisTaskTagAndProbe.h
> PWGDQ/LMEE: update eID in TAP

- PWGLF/NUCLEX/Nuclei/Absorption/AliAnalysisTaskDeuteronAbsorption.cxx
This reverts commit 677ec0ff7b7bd77a627671dfe79dc23c0dcc88d8.
> Revert "Fix timing cut bug"

- PWGHF/hfe/AliAnalysisTaskHFEBESpectraEMC.cxx
- PWGHF/hfe/AliAnalysisTaskHFEBESpectraEMC.h
- PWGHF/hfe/macros/AddTaskHFEBESpectraEMC.C
Adding option to select specific cluster container from EMC correction task
> Adding cluster container name for EMCCorrTask

- PWGGA/PHOSTasks/ClusterSelection/AliCaloTriggerMimicHelper.cxx
- PWGGA/PHOSTasks/ClusterSelection/AliCaloTriggerMimicHelper.h
for cluster to be good in trigger helper
> PWGGA: Set minimum amount of cells in phos

- PWGPP/ZDC/macros/DrawPerformanceZDCQAMatch.C
> Removing typos from macros for ZDC QA

- PWGJE/EMCALJetTasks/Tracks/AliAnalysisTaskEmcalSoftDropResponse.cxx
Acceptance must be evaluated after the SoftDrop
at other (part or det and vice versa) level, as having
the same acceptance type is not a strict requirement
for the analysis, while having the SoftDrop for both
part. and det. level jet is. Evaluating the SoftDrop after
the acceptance cut masks the acceptance status in
the efficiency and purity histogram in almost all cases
leading to efficiency and purity ~1
> Switch order of acceptance and SoftDrop requirement

- PWGCF/Correlations/JCORRAN/Pro/AliAnalysisTaskRidge.cxx
set fine mult bin for min bias
> [PWGCF] set fine mult bin

- PWGLF/NUCLEX/CMakeLists.txt
- PWGLF/NUCLEX/Exotica/Dibaryons/AddTaskDibaryons.C
- PWGLF/NUCLEX/Exotica/Dibaryons/AliAnalysisTaskDibaryons.cxx
- PWGLF/NUCLEX/Exotica/Dibaryons/AliAnalysisTaskDibaryons.h
- PWGLF/NUCLEX/PWGLFnuclexLinkDef.h
first commit for dibaryon searches
> PWGLF/NUCLEX/Exotica: first commit for dibaryon searches

- PWGLF/NUCLEX/Exotica/Dibaryons/AliAnalysisTaskDibaryons.cxx
The task are modified in order to estimate the backgrounds of dibaryon's invariant mass distributions, using sideband technique
> PWGLF/NUCLEX/Exotica/Dibaryons: Enable background estimation using sideband technique

- PWGLF/SPECTRA/PiKaPr/TPC/rTPC/AddTaskSpherocity.C
Adding a flag to select spherocity events in the [0,1] V0M multiplicity class
> Adding a flag

- PWGCF/Correlations/DPhi/AliAnalysisTaskV0ChCorrelationpp.cxx
- PWGCF/Correlations/macros/AddTaskV0ChCorrelation.C
- PWGCF/Correlations/macros/AddTaskV0ChCorrelationpp.C
> update sys v0-h

- PWGGA/GammaConv/AliAnalysisTaskGammaIsoTree.cxx
- PWGGA/GammaConv/AliAnalysisTaskGammaIsoTree.h
- added rho subtraction and limited acceptance for charged isolation
> PWGGA/GammaConv: GammaIsoTree added Rho subtraction & lim. acc.

- PWGDQ/dielectron/macrosLMEE/AddTask_LMeeCocktailMC.C
Allow to run more than one task on the same simulations
> Allow to run more than one task on the same simulations

- PWGCF/FLOW/GF/AliAnalysisTaskNonlinearFlow.cxx
> Fix bug for Nonlinear flow

- PWGCF/Correlations/DPhi/AliAnalysisTaskV0ChCorrelation.cxx
- PWGCF/Correlations/DPhi/AliAnalysisTaskV0ChCorrelationpp.cxx
- PWGCF/Correlations/macros/AddTaskV0ChCorrelation.C
- PWGCF/Correlations/macros/AddTaskV0ChCorrelationpp.C
> Sys updated

- PWGHF/vertexingHF/vHFML/AliAnalysisTaskSEHFTreeCreatorApply.cxx
Noticed a small copy-paste mistake in previous PR
> PWGHF: Fix if-statement OOB pileup protection

- PWGCF/FEMTOSCOPY/FemtoDream/AliAnalysisTaskCharmingFemto.cxx
- PWGCF/FEMTOSCOPY/FemtoDream/AliAnalysisTaskCharmingFemto.h
- PWGCF/FEMTOSCOPY/FemtoDream/CMakeLists.txt
- PWGCF/FEMTOSCOPY/FemtoDream/PWGCFFemtoDreamLinkDef.h
- PWGCF/FEMTOSCOPY/macros/AddTaskCharmingFemto.C
- Added selection of D+ candidates in a way that it will be easy to set different HF particles
- Included vertexingHFML library to CMakeList (works only with ROOT6 because of ML application)
> Add selection of D+ meson candidates

- PWGHF/vertexingHF/vHFML/AliAnalysisTaskSEHFTreeCreatorApply.cxx
- PWGHF/vertexingHF/vHFML/AliAnalysisTaskSEHFTreeCreatorApply.h
- PWGHF/vertexingHF/vHFML/AliHFTreeHandlerApplyLc2V0bachelor.cxx
- PWGHF/vertexingHF/vHFML/AliHFTreeHandlerApplyLc2V0bachelor.h
* Reduce the number of branches when running PbPb
* Fix for downsampling seed != 0
* Added PreSelect for ITS upgrade and general for Ds
* Fix for eventID in MC
> PWGHF: Improvements for running PbPb

- PWGLF/RESONANCES/PostProcessing/f0980/AliAnalysisTaskInclusivef0f2.cxx
- PWGLF/RESONANCES/PostProcessing/f0980/AliAnalysisTaskInclusivef0f2.h
> [PWGLF] updates for pt bin

- PWGHF/vertexingHF/vHFML/AliAnalysisTaskSEHFTreeCreatorApply.cxx
- PWGHF/vertexingHF/vHFML/AliAnalysisTaskSEHFTreeCreatorApply.h
- PWGHF/vertexingHF/vHFML/AliHFTreeHandlerApply.cxx
- PWGHF/vertexingHF/vHFML/AliHFTreeHandlerApply.h
- PWGHF/vertexingHF/vHFML/AliHFTreeHandlerApplyDstoKKpi.cxx
- PWGHF/vertexingHF/vHFML/AliHFTreeHandlerApplyLc2V0bachelor.cxx
* Fix evID for MC another time (bring GetEvID function back to working QM19 state)
* Reduce PbPb output size further by removing more unnecessary branches
> PWGHF: Fix EvID + reduce PbPb output size

- PWGCF/FEMTOSCOPY/FemtoDream/AliAnalysisTaskNanoLoton.cxx
- PWGCF/FEMTOSCOPY/FemtoDream/AliAnalysisTaskPOmegaPenne.cxx
- PWGCF/FEMTOSCOPY/FemtoDream/AliAnalysisTaskPOmegaPenne.h
- PWGCF/FEMTOSCOPY/FemtoDream/AliFemtoDreamPairCleaner.cxx
- PWGCF/FEMTOSCOPY/FemtoDream/AliFemtoDreamPairCleaner.h
clean shared tracks with random evaluation which one to keep
> added CleanDecayAtRandom

- PWGJE/EMCALJetTasks/AliAnalysisTaskJetCharge.cxx
- PWGJE/EMCALJetTasks/AliAnalysisTaskJetCharge.h
- PWGJE/EMCALJetTasks/AliAnalysisTaskJetChargeFlavourTemplates.cxx
- PWGJE/EMCALJetTasks/AliAnalysisTaskJetChargeFlavourTemplates.h
- PWGJE/EMCALJetTasks/CMakeLists.txt
- PWGJE/EMCALJetTasks/PWGJEEMCALJetTasksLinkDef.h
- PWGJE/EMCALJetTasks/macros/AddTaskJetCharge.C
- PWGJE/EMCALJetTasks/macros/AddTaskJetChargeFlavourTemplates.C
Added a new analysis task AliAnalysisTaskJetCharge which calculates the jet charge distributions for either pp or PbPb.
This has been added such that it can be run on the LEGO trains system.
Written by me, J Samuel Colburn. Originally uploaded on the 28th of October.
> New analysis task added to PWGJE: calculating Jet Charge

- PWGJE/EMCALJetTasks/Tracks/AliAnalysisEmcalSoftdropHelper.cxx
- PWGJE/EMCALJetTasks/Tracks/AliAnalysisTaskEmcalJetSpectrumSDPart.cxx
- Add cut on non-0 jet mass
- More elaborate error handling
and monitoring
> Protection for jets with 0 jet mass

- PWG/EMCAL/EMCALbase/AliEMCALRecoUtils.cxx
- PWG/EMCAL/EMCALbase/AliEMCALRecoUtils.h
(adapted from AliCalorimeterUtils) and use in method to recalculate shower shape with NxN selection
> [EMCal] Implement methods to calculate number of local maxima 

- PWGGA/CaloTrackCorrelations/AliAnaPhoton.cxx
- PWGGA/CaloTrackCorrelations/AliAnaPhoton.h
- PWGGA/CaloTrackCorrelations/macros/AddTaskCaloTrackCorrBase.C
Interesting for V2 clusterizer analysis
> [PWGGA/CaloTrackCorr] Compute shower shape on 5x5 region optionally

- PWGCF/Correlations/JCORRAN/Pro/AliAnalysisTaskGenMCRidge.cxx
> [PWGCF] add LM bins

- PWGHF/hfe/AliAnalysisTaskHFEMultiplicity.cxx
- PWGHF/hfe/AliAnalysisTaskHFEMultiplicity.h
- PWGHF/hfe/AliAnalysisTaskHFETPCTOFMultiplicity.cxx
- PWGHF/hfe/AliAnalysisTaskHFETPCTOFMultiplicity.h
- PWGHF/hfe/macros/AddTaskHFEMultiplicity.C
- PWGHF/hfe/macros/AddTaskHFETPCTOFMultiplicity.C
Added TPC ncrossrows track cuts and histograms for hfe efficiency calculation for different cuts.
> PWGHF/hfe: Update task for track cuts and adding new histograms

- PWGHF/vertexingHF/AliAnalysisTaskHFSimpleVertices.cxx
- PWGHF/vertexingHF/AliAnalysisTaskHFSimpleVertices.h
@fprino In addition to adding the D+ variable histograms, I uncommented also the lines to set the primary and secondary vertices for 3-prongs
> Add D+ variable histrograms to task for O2 comparisons

- PWGHF/vertexingHF/vHFML/AliAnalysisTaskSEDplus.cxx
- PWGHF/vertexingHF/vHFML/AliAnalysisTaskSEDplus.h
- PWGHF/vertexingHF/vHFML/AliHFMLVarHandlerDplustoKpipi.cxx
- PWGHF/vertexingHF/vHFML/AliHFMLVarHandlerDplustoKpipi.h
Add an optional flag to store the d0K x d0pi1 and d0K x d0pi2 variables in the tree
> Add product of prong impact pararameters in Dplus tree

- PWGGA/GammaConv/AliAnalysisTaskGammaConvCalo.cxx
- PWGGA/GammaConv/AliAnalysisTaskGammaConvCalo.h
+ adding myself to the header of the task
> PWGGA/GammaConv adding minv vs PCM photon energy

- PWGGA/GammaConv/AliAnalysisTaskOmegaToPiZeroGamma.cxx
- PWGGA/GammaConv/macros/AddTask_OmegaToPiZeroGamma_pp.C
- Updated author for AliAnalysisTaskOmegaToPiZeroGamma.cxx
- Updated author for AddTask_OmegaToPiZeroGamma_pp.C
> PWGGA/GammaConv: Updated author for OmegaToPiZeroGamma(Add)Task(pp)

- PWGDQ/dielectron/macrosLMEE/AddTask_hdegenhardt_eeCorMC.C
- PWGDQ/dielectron/macrosLMEE/Config_hdegenhardt_pp.C
Fixing wrong track cut on both data and MC
> Fixing wrong track cut

- PWGHF/vertexingHF/AliAnalysisTaskSELc2pKs0fromKFP.cxx
Add mass of Lc from AliAODRecoCascadeHF::InvMassLctoK0sP()
> Add mass of Lc from AliAODRecoCascadeHF::InvMassLctoK0sP()

- PWGLF/RESONANCES/extra/AddAnalysisTaskPhiCount.C
- PWGLF/RESONANCES/extra/AliAnalysisTaskPhiCount.cxx
- PWGLF/RESONANCES/extra/AliAnalysisTaskPhiCount.h
- PWGLF/RESONANCES/extra/CMakeLists.txt
- PWGLF/RESONANCES/extra/PWGLFrsnextraLinkDef.h
Analysis set-up to measure Phi-pairs production
> Added macros to do Phi-pair analysis

- PWGHF/vertexingHF/AliAnalysisTaskSEXicZero2XiPifromKFP.cxx
> Correct variables for weight

- PWGGA/GammaConv/AliAnalysisTaskGammaIsoTree.cxx
- PWGGA/GammaConv/AliAnalysisTaskGammaIsoTree.h
Changed definition for true photons, now including conversions
> PWGGA/GammaConv: GammaIsoTree photon truth definition

- PWGJE/EMCALJetTasks/Tracks/AliAnalysisTaskEmcalJetEnergySpectrum.cxx
- PWGJE/EMCALJetTasks/Tracks/AliAnalysisTaskEmcalJetEnergySpectrum.h
- Require physics selection to be kINT7
- Require trigger selection from AliEmcalTriggerSelectionTask
> Implement replay mode of EJE triggers in data

- PWGLF/NUCLEX/Nuclei/AbsorptionRatios/macros/AddHighMultNucleiTask.C
Updated Filterbit in AddHighMultNucleiTask
> Update AddHighMultNucleiTask.C : changed filterbit for track selection

- PWG/EMCAL/EMCALbase/AliAnalysisTaskEmcal.cxx
- PWGJE/EMCALJetTasks/Tracks/AliAnalysisEmcalSoftdropHelper.cxx
- PWGJE/EMCALJetTasks/Tracks/AliAnalysisEmcalSoftdropHelper.h
- PWGJE/EMCALJetTasks/Tracks/AliAnalysisTaskEmcalJetSpectrumSDPart.cxx
LHC20k1: Herwig, pp 13 TeV, 20 pt-hard bins,
anchored to LHC17h-r, configiured as HepMC
pt-hard dataset
> Add support for LHC20k1

- PWGDQ/dielectron/macrosLMEE/AddTask_dsekihat_ElectronEfficiencyV2_PbPb.C
- PWGDQ/dielectron/macrosLMEE/Config_dsekihat_ElectronEfficiencyV2_PbPb.C
- PWGDQ/dielectron/macrosLMEE/Config_dsekihat_lowmass_PbPb.C
- PWGDQ/dielectron/macrosLMEE/LMEECutLib_dsekihat.C
update AddTask and Config in MC
> PWGDQ/LMEE: update AddTask and Config in MC

- PWGDQ/dimuons/AliAnalysisTaskTree_MCut.cxx
- PWGDQ/dimuons/AliAnalysisTaskTree_MCut.h
- PWGDQ/dimuons/macros/AddTaskTree_Grid_MCut.C
1) save in the tree only the events which contain at least a dimuon with mass higher than a threshold
2) save also a TH1D containing the infos on the trigger statistics
> Two changes to improve tree creation

- PWGGA/GammaConv/AliAnalysisTaskOmegaToPiZeroGamma.cxx
- PWGGA/GammaConv/macros/AddTask_OmegaToPiZeroGamma_pp.C
- Changed background scheme for two cut settings to use TGPS
- Added check for gamma -> e -> gamma from Pi0/omega for true omegas
> PWGGA/GammaConv: OmegaToPiZeroGammaTask - changed background scheme for two cut settings

- PWGCF/FLOW/GF/AliAnalysisTaskNonlinearFlow.cxx
> fix bugs on weight

- PWGCF/FEMTOSCOPY/macros/Train/Gleb/Nov_2020/2kT/ConfigFemtoAnalysis.C
- PWGCF/FEMTOSCOPY/macros/Train/Gleb/Nov_2020/2kT_DCA_depend/ConfigFemtoAnalysis.C
- PWGCF/FEMTOSCOPY/macros/Train/Gleb/Nov_2020/4kT_DCA_depend_0040/ConfigFemtoAnalysis.C
- PWGCF/FEMTOSCOPY/macros/Train/Gleb/Nov_2020/MC_3d/MC_111/ConfigFemtoAnalysis.C
- PWGCF/FEMTOSCOPY/macros/Train/Gleb/Nov_2020/MC_3d/MC_212/ConfigFemtoAnalysis.C
- PWGCF/FEMTOSCOPY/macros/Train/Gleb/Nov_2020/MC_3d/MC_223/ConfigFemtoAnalysis.C
- PWGCF/FEMTOSCOPY/macros/Train/Gleb/Nov_2020/MC_3d/MC_233/ConfigFemtoAnalysis.C
- PWGCF/FEMTOSCOPY/macros/Train/Gleb/Nov_2020/MC_3d/MC_322/ConfigFemtoAnalysis.C
- PWGCF/FEMTOSCOPY/macros/Train/Gleb/Nov_2020/MC_3d/MC_434/ConfigFemtoAnalysis.C
- PWGCF/FEMTOSCOPY/macros/Train/Gleb/Nov_2020/MC_3d/MC_455/ConfigFemtoAnalysis.C
- PWGCF/FEMTOSCOPY/macros/Train/Gleb/Nov_2020/MC_3d/MC_546/ConfigFemtoAnalysis.C
- PWGCF/FEMTOSCOPY/macros/Train/Gleb/Nov_2020/MC_3d/MC_554/ConfigFemtoAnalysis.C
- PWGCF/FEMTOSCOPY/macros/Train/Gleb/Nov_2020/MC_3d/MC_555/ConfigFemtoAnalysis.C
- PWGCF/FEMTOSCOPY/macros/Train/Gleb/Nov_2020/MC_3d/MC_646/ConfigFemtoAnalysis.C
- PWGCF/FEMTOSCOPY/macros/Train/Gleb/Nov_2020/MC_3d/MC_667/ConfigFemtoAnalysis.C
- PWGCF/FEMTOSCOPY/macros/Train/Gleb/Nov_2020/MC_3d/MC_766/ConfigFemtoAnalysis.C
- PWGCF/FEMTOSCOPY/macros/Train/Gleb/Nov_2020/MC_3d/MC_767/ConfigFemtoAnalysis.C
- PWGCF/FEMTOSCOPY/macros/Train/Gleb/Nov_2020/MC_3d/MC_768/ConfigFemtoAnalysis.C
- PWGCF/FEMTOSCOPY/macros/Train/Gleb/Nov_2020/MC_3d/MC_868/ConfigFemtoAnalysis.C
> Lego train files for Gleb Nov_2020

- PWGGA/GammaConv/AliAnalysisTaskGammaConvDalitzV1.cxx
- PWGGA/GammaConv/AliAnalysisTaskGammaConvDalitzV1.h
- PWGGA/GammaConv/macros/AddTask_GammaConvDalitzV1_pp.C
- PWGGA/GammaConvBase/AliDalitzElectronCuts.cxx
- PWGGA/GammaConvBase/AliDalitzElectronCuts.h
Post Calibration in the electron postron pair for Dalitz
> Post Calibration

- PWGHF/vertexingHF/AliAnalysisTaskSELc2pKs0fromKFP.cxx
Add pt of Lc from AliAODRecoCascadeHF
> Add pt of Lc from AliAODRecoCascadeHF

- PWG/EMCAL/EMCALbase/AliAnalysisTaskEmcal.h
Recently data fields have been added, consequently
the ClassDef of the task should be increased.
> Increase ClassDef of the AliAnalysisTaskEmcal

- PWGHF/vertexingHF/AliAnalysisTaskSEOmegac2eleOmegafromAODtracks.cxx
- PWGHF/vertexingHF/AliAnalysisTaskSEOmegac2eleOmegafromAODtracks.h
- PWGHF/vertexingHF/AliRDHFCutsOmegactoeleOmegafromAODtracks.cxx
- PWGHF/vertexingHF/AliRDHFCutsOmegactoeleOmegafromAODtracks.h
- PWGHF/vertexingHF/macros/AddTaskOmegac2eleOmegafromAODtracks.C
Omegac in semi-leptonic decay channel study
> Omegac study

- PWGDQ/dielectron/core/AliAnalysisTaskTagAndProbe.cxx
- PWGDQ/dielectron/core/AliAnalysisTaskTagAndProbe.h
- PWGDQ/dielectron/macrosLMEE/AddTask_dsekihat_TAP_PbPb.C
> PWGDQ/LMEE: update TAP for MC PID

- PWGLF/STRANGENESS/HeavyIonsRun1Run2/AliAnalysisTaskStrVsMult.cxx
Added the OOB condition for MC truth (needed for embedded simulations with pileup)
> Fixed OOB pileup handeling for MC truth

- PWGJE/EMCALJetTasks/UserTasks/AliAnalysisTaskEA.cxx
- PWGJE/EMCALJetTasks/UserTasks/AliAnalysisTaskEA.h
Reduction of the number of output histograms plus
incorporation of histograms for 2D unfolding
> Reduction of the number of output histograms, 

- PWGCF/Correlations/DPhi/AliAnalysisTaskSEpPbCorrelationsJetV2.cxx
- PWGCF/Correlations/DPhi/AliAnalysisTaskSEpPbCorrelationsJetV2.h
- PWGCF/Correlations/macros/pPbCorrelations/AddTaskpPbCorrelationsJetV2.C
Hi,
Here is an update for adding MC analysis. Thanks!
Siyu Tang
> Add MC analysis

- PWGHF/vertexingHF/vHFML/AliAnalysisTaskSENonPromptLc.cxx
- PWGHF/vertexingHF/vHFML/AliAnalysisTaskSENonPromptLc.h
- PWGHF/vertexingHF/vHFML/AliHFMLVarHandlerLctopKpi.cxx
- PWGHF/vertexingHF/vHFML/AliHFMLVarHandlerLctopKpi.h
Store info about resonant decay type for Lc pKpi
> Resonant decays for Lc pKpi

- PWGHF/vertexingHF/AliAODPidHF.cxx
- PWGHF/vertexingHF/AliAODPidHF.h
- PWGHF/vertexingHF/AliAnalysisTaskSEHFSystPID.cxx
- PWGHF/vertexingHF/AliRDHFCuts.cxx
the correct post calibrations for pass1 and pass3 are applied automatically
> Revert pass1 TPC PID postcalibrations

- PWGPP/EMCAL/AliAnalysisTaskEMCALTimeCalib.cxx
- PWGPP/EMCAL/AliAnalysisTaskEMCALTimeCalib.h
Now we can extract the time calibration coefficients as a function of average cell energy.
> Adding Energy dependent Time calibration

- PWGLF/SPECTRA/PiKaPr/TPCTOFCascades/AliAnalysisPIDCascadeTrack.cxx
- PWGLF/SPECTRA/PiKaPr/TPCTOFCascades/AliAnalysisPIDCascadeTrack.h
- PWGLF/SPECTRA/PiKaPr/TPCTOFCascades/AliAnalysisTaskTPCTOFCascade.cxx
- PWGLF/SPECTRA/PiKaPr/TPCTOFCascades/AliAnalysisTaskTPCTOFCascade.h
Added functionality for geometrical cut + hybrid tracks
> Modifications to the the Trees for the Lund RT/S0 analyses.

- PWGCF/Correlations/DPhi/AliAnalysisTaskSEpPbCorrelationsJetV2.cxx
- PWGCF/Correlations/DPhi/AliAnalysisTaskSEpPbCorrelationsJetV2.h
- PWGCF/Correlations/macros/pPbCorrelations/AddTaskpPbCorrelationsJetV2.C
Hi,
This is still the update for jet v2 analysis, since this pull request was rejected without any error log yesterday. I submit it again, I wish it will be merged soon.
Thanks!
Siyu
> Add Unlike-sign Check for Jet V2

- PWGHF/treeHF/AliHFTreeHandler.cxx
- PWGHF/vertexingHF/vHFML/AliHFTreeHandlerApply.cxx
> Revert load of pass1 calibrations for pass1 Pb-Pb 

- PWGLF/SPECTRA/PiKaPr/ITSsa/AliAnalysisTaskSEITSsaSpectra.cxx
- PWGLF/SPECTRA/PiKaPr/ITSsa/AliAnalysisTaskSEITSsaSpectra.h
Old pieces of code removed since used only for internal checks. New cut on momentum to explore improvements in the Xe-Xe analysis
> removed old stuff + addition of selectable cut on momentum

- PWGDQ/dielectron/core/AliAnalysisTask_JPsi_EMCal.cxx
- PWGDQ/dielectron/core/AliAnalysisTask_JPsi_EMCal.h
- PWGDQ/dielectron/macrosJPSI/AddTask_JPsi_EMCal.C
- PWGDQ/dielectron/macrosJPSI/Config_JPsi_EMCal.C
Weights for efficiencies due to enhancement of J/psi at high pT
> New efficiencies histograms and weights for efficiencies

- PWGCF/Correlations/DPhi/AliAnalysisTaskSEpPbCorrelationsJetV2.cxx
Hi,
Here is an update for Jet v2 analysis, for estimating the secondary FMD effect.
Thanks a lot!
Siyu
> Add Primary FMD Information

- PWGGA/GammaConv/AliAnalysisTaskSigmaPlToProtonPiZeroAOD.cxx
- PWGGA/GammaConv/AliAnalysisTaskSigmaPlToProtonPiZeroAOD.h
- PWGGA/GammaConv/macros/AddTask_SigmaPlToProtonPiZeroAOD.C
- PWGGA/GammaConvBase/AliCaloSigmaCuts.cxx
- Added weights for the usage of JJ MCs
- Added some QA plots and changed binning of some histos
- Added train configs and Cut variations
- Corrected the identification of double counting
- Deleted unused variables and functions
> PWGGA/GammaConv: Updated SigmaPlToProtonPiZero for JJ MCs and corrected double counting

- PWGCF/FEMTOSCOPY/macros/Train/Gleb/Nov_2020/2kT_DCA_depend/ConfigFemtoAnalysis.C
- PWGCF/FEMTOSCOPY/macros/Train/Gleb/Nov_2020/4kT_DCA_depend_0040/ConfigFemtoAnalysis.C
> two configs for GLEB

- PWGJE/EMCALJetTasks/Tracks/AliAnalysisTaskEmcalSoftDropResponse.cxx
Fix untagged bin of fine part. level histogram (redundant)
> FIx filling of max. constituent histograms

- PWGCF/Correlations/DPhi/AliAnalysisTaskV0ChCorrelation.cxx
- PWGCF/Correlations/DPhi/AliAnalysisTaskV0ChCorrelationpp.cxx
> fix THnSparse intervals

- PWGCF/Correlations/DPhi/Unfoldedhistos/AliCSAnalysisCutsBase.cxx
- PWGCF/Correlations/DPhi/Unfoldedhistos/AliCSAnalysisCutsBase.h
- PWGCF/Correlations/macros/Unfoldedhistos/runCorrelationsStudiesConfigMacro.C
Incorporated support for LHC13e7, LHC15g4a and LHC15g5b productions
> Incorporated support for p-Pb MC periods

- PWGCF/FLOW/GF/AliAnalysisTaskNonlinearFlow.cxx
- PWGCF/FLOW/GF/AliAnalysisTaskNonlinearFlow.h
- PWGCF/FLOW/macros/AddTaskNonlinearFlow.C
Change way of reading weight. 
In the past I put the TFile to DataContainer. 
Now, it is changed to put the TList.
> Put the TList to DataContainer

- PWGLF/SPECTRA/PiKaPr/TPCTOFCascades/AliAnalysisTaskTPCTOFCascade.cxx
Just added manual TPC selection
> Small modification to hybrid tracks

- PWGJE/EMCALJetTasks/UserTasks/AliAnalysisTaskJetHardestKt.cxx
- PWGJE/EMCALJetTasks/UserTasks/AliAnalysisTaskJetHardestKt.h
Makes dynamical grooming methods available (ie. usable) and add method
for selecting jet core
> Generalize hardest kt grooming methods

- PWGDQ/dimuons/AliAnalysisTaskPbPbTree_MCut.cxx
Fixing some issues in the task for LEGO trains
> Fixing some issues in the task for LEGO trains

- PWGLF/RESONANCES/extra/AddAnalysisTaskPhiCount.C
- PWGLF/RESONANCES/extra/AliAnalysisTaskPhiCount.cxx
- PWGLF/RESONANCES/extra/AliAnalysisTaskPhiCount.h
Twitches to analysis files for a previous mistake
> Analysis updated

- PWGPP/EMCAL/AliAnalysisTaskEMCALTimeCalib.cxx
I forgot to remove the log message in the last commit.
> Remove annoying log message

- PWGHF/vertexingHF/AliAnalysisTaskSEXicZero2XiPifromKFP.cxx
Add flag for Omegac0 analysis in generation
> Add flag for Omegac0 analysis in generation

- PWGHF/vertexingHF/AliHFSystErr.cxx
> tracking syst update for pK0s analyses in p-Pb

- PWGDQ/dielectron/LMEE/AliAnalysisTaskBeauty.cxx
- PWGDQ/dielectron/LMEE/AliAnalysisTaskCharm.cxx
Fix for broken decay chains (Hermann)
> Fix for broken decay chains (avoid crash) (Hermann)

- PWGLF/NUCLEX/Exotica/Dibaryons/AddTaskDibaryons.C
- PWGLF/NUCLEX/Exotica/Dibaryons/AliAnalysisTaskDibaryons.cxx
- PWGLF/NUCLEX/Exotica/Dibaryons/AliAnalysisTaskDibaryons.h
- Add filter-bit selection for AOD in order to select TPC-only tracks
- Remove background estimation using sideband
> PWGLF/NUCLEX: Add filter-bit selection for AOD tracks

- PWGCF/FLOW/GF/AliAnalysisTaskMeanPtV2Corr.cxx
- PWGCF/FLOW/GF/AliAnalysisTaskMeanPtV2Corr.h
Work on AliAnalysisTaskMeanPtVnCorr. Decoupled eta cuts for Nch calculation, added V0M>90 selection, etc. Second attempt to commit, as it looks like either github or AliPhysics are bananas again
> Work on AliAnalysisTaskMeanPtVnCorr

- PWGHF/vertexingHF/upgrade/AliAnalysisTaskSECharmTriggerStudy.cxx
- PWGHF/vertexingHF/upgrade/AliAnalysisTaskSECharmTriggerStudy.h
- Add possibility to store gen info in histos
- and store tracks for correlation studies
> Implement some improvements for more complex studies

- PWGDQ/dimuons/AliAnalysisTaskPbPbTree_MCut.cxx
- PWGDQ/dimuons/AliAnalysisTaskPbPbTree_MCut.h
- PWGDQ/dimuons/CMakeLists.txt
Correcting the definitions for Helicity and Collins-Soper in Pb-Pb
> Correcting the definitions for Helicity and Collins-Soper in Pb-Pb

- PWGLF/NUCLEX/Exotica/Dibaryons/AliAnalysisTaskDibaryons.cxx
- Fixed to get proton DCAs from global track instead of TPC-only track
- Add invariant mass histograms of p-Omega and Omega-Omega
> PWGLF/NUCLEX: Get proton DCAs from global track

- PWGLF/RESONANCES/extra/AliAnalysisTaskPhiCount.cxx
> Update PhiPhi Analysis

- PWGCF/FEMTOSCOPY/macros/Train/malinina/Dec2020/pipi_13TeV_TTC/AddTaskFemtoKchHBT1090.C
- PWGCF/FEMTOSCOPY/macros/Train/malinina/Dec2020/pipi_13TeV_TTC/ConfigFemtoAnalysis.C
> Ludmila: Lego Train Dec2020

- PWGCF/FLOW/GF/AliAnalysisTaskNonlinearFlow.cxx
- PWGCF/FLOW/GF/AliAnalysisTaskNonlinearFlow.h
- PWGCF/FLOW/GF/CorrelationCalculator.cxx
- PWGCF/FLOW/GF/CorrelationCalculator.h
- PWGCF/FLOW/GF/PWGCFFLOWGFLinkDef.h
Make the PhysicsProfile and CorrelationCalculator inherit from TObject
initialize variables
add //! for pointer
> Make the PhysicsProfile and CorrelationCalculator inherit from TObject

- PWGCF/FLOW/GF/AliAnalysisTaskMeanPtV2Corr.cxx
- PWGCF/FLOW/GF/AliAnalysisTaskMeanPtV2Corr.h
- PWGCF/FLOW/macros/AddTaskMeanPtV2Corr.C
Last pull request failed a test b/c of a time-out when downloading Geant 4 (???????????????????????????????????????????)
Now, added v24 calculation in full eta (no subevents) and v2 vs. dpt correlation
> Another attempt to pull

- PWGHF/vertexingHF/AliAnalysisTaskSELc2pKs0fromKFP.cxx
> Save also MC background

- PWGDQ/dimuons/AliAnalysisTaskPbPbTree_MCut.cxx
- PWGDQ/dimuons/AliAnalysisTaskPbPbTree_MCut.h
Fixing minor issues and removing some useless prints
> Fixing minor issues and removing some useless prints

- PWGCF/FEMTOSCOPY/macros/Train/malinina/Dec2020NoSph/KK_13TeV_dist/AddTaskFemtoKchHBT1090.C
- PWGCF/FEMTOSCOPY/macros/Train/malinina/Dec2020NoSph/KK_13TeV_dist/ConfigFemtoAnalysis.C
- PWGCF/FEMTOSCOPY/macros/Train/malinina/Dec2020NoSph/pipi_13TeV_dist/AddTaskFemtoKchHBT1090.C
- PWGCF/FEMTOSCOPY/macros/Train/malinina/Dec2020NoSph/pipi_13TeV_dist/ConfigFemtoAnalysis.C
> Ludmila - Dec2020NoSph train

- PWGCF/FLOW/GF/AliAnalysisTaskMeanPtV2Corr.cxx
- PWGCF/FLOW/GF/AliAnalysisTaskMeanPtV2Corr.h
- PWGCF/FLOW/GF/AliGFWFlowContainer.cxx
- PWGCF/FLOW/GF/AliGFWFlowContainer.h
- PWGCF/FLOW/macros/AddTaskMeanPtV2Corr.C
Also, added OverrideBinsWithZero to AliGFWFlowContainer
Removed MC handler from AddTask macro
> AliAnalysisTaskMeanPtV2Corr now runs mpt on MC

- PWGCF/FLOW/GF/AliAnalysisTaskMeanPtV2Corr.cxx
- PWGCF/FLOW/GF/AliGFW.cxx
- PWGCF/FLOW/macros/AddTaskMeanPtV2Corr.C
Also, AliGFW now explicitly checks for a required number of tracks to calculate vn (previously, check would be done using weights
> MeanPtV2 does PCC with MC

- PWGLF/RESONANCES/extra/AliAnalysisTaskPhiCount.cxx
- PWGLF/RESONANCES/extra/AliAnalysisTaskPhiCount.h
> Memory usage fix

- PWGDQ/dimuons/AliAnalysisTaskPbPbTree_MCut.cxx
Fixing the definition of PhiHE and PhiCS
> Fixing the definition of PhiHE and PhiCS

- PWGGA/GammaConv/macros/AddTask_OmegaToPiZeroGamma_pp.C
- Added train config for rotation method with weighting
> PWGGA/GammaConv: OmegaToPiZeroGamma - Added train config for rotation method with weighting

- PWGCF/FEMTOSCOPY/AliFemto/AliFemtoEventReaderNanoAOD.cxx
- PWGCF/FEMTOSCOPY/AliFemto/AliFemtoEventReaderNanoAOD.h
extending AliFemtoNanoReader by deuterons
> changes for deuterons in the AliFemtoNanoReader

- PWGCF/FEMTOSCOPY/FemtoDream/AliAnalysisTaskGeorgiosNTuple.cxx
- PWGCF/FEMTOSCOPY/FemtoDream/AliAnalysisTaskGeorgiosNTuple.h
- PWGCF/FEMTOSCOPY/macros/AddTaskGeorgiosNTuple.C
Also reincluding Branches in the TTree to make that possible
> Opening of the Lambda and Xi Cuts for systematic variations

- PWGHF/vertexingHF/AliAnalysisTaskSELc2pKs0fromKFP.cxx
- PWGHF/vertexingHF/AliAnalysisTaskSELc2pKs0fromKFP.h
- PWGHF/vertexingHF/AliRDHFCutsKFP.cxx
- PWGHF/vertexingHF/AliRDHFCutsKFP.h
- PWGHF/vertexingHF/macros/AddTaskLc2pKs0FromKFParticle.C
> Add flag for Lc->Lpi

- AddTaskV0ChCorrelationpp.C
- AddTaskV0ChCorrelationppsys.C
- AddTaskV0ChCorrelationsys.C
> New Task for some change

- PWGHF/vertexingHF/AliAnalysisTaskSEDvsEventShapes.cxx
I left some run numbers. So I have added them.
> DvsEventshape class update

- PWGGA/EMCALTasks/AliAnalysisTaskEMCALIsoPhoton.cxx
- PWGGA/EMCALTasks/AliAnalysisTaskEMCALPhotonTagged.cxx
- PWGGA/EMCALTasks/AliAnalysisTaskEMCALTrackIsolation.cxx
- PWGGA/Hyperon/AliAnalysisTaskSigma0.cxx
- PWGGA/Hyperon/AliAnalysisTaskSigma0.h
- PWGGA/Hyperon/AliAnalysisTaskSigma0Spectra.cxx
- attempt at cleaning up warnings from PWGGA directory
- adjusted indentations in the process
> PWGGA/Hyperon & PWGGA/EMCALTasks: fix compiler warnings & indentation problems

- PWGCF/Correlations/DPhi/AliAnalysisTaskSEpPbCorrelationsJetV2.cxx
- PWGCF/Correlations/DPhi/AliAnalysisTaskSEpPbCorrelationsJetV2.h
- PWGCF/Correlations/macros/pPbCorrelations/AddTaskpPbCorrelationsJetV2.C
Hi,
Here is the update for TPC-FMD correlations in jet v2 analysis. Thanks!
Siyu
> Optimization for TPCFMD correlation

- PWGCF/FLOW/GF/AliAnalysisTaskMeanPtV2Corr.cxx
- PWGCF/FLOW/GF/AliAnalysisTaskMeanPtV2Corr.h
- PWGCF/FLOW/GF/AliGFWCuts.cxx
- PWGCF/FLOW/GF/AliGFWCuts.h
Currently, track cuts are for everything, but event cuts are _not_ for efficiency (still need to add event cuts for other modes
> Implemented AliGFWCuts into MeanPtV2 task.

- PWGHF/hfe/AliAnalysisTaskEHCorrel.cxx
- PWGHF/hfe/AliAnalysisTaskEHCorrel.h
- PWGHF/hfe/macros/AddTaskEHCorrel.C
Setting to apply different eta cut for electron track cut
> Add option to set electron track eta cut

- PWG/EMCAL/EMCALbase/AliAnalysisTaskEmcal.cxx
- PWG/EMCAL/EMCALbase/AliAnalysisTaskEmcal.h
- PWG/EMCAL/EMCALbase/AliEmcalTrackSelectionAOD.cxx
Adds new pt-hard binning category with 6 pt-hard bins
> Add support for LHC17h6e2 and LHC17h6f2

- PWGCF/FLOW/GF/AliAnalysisTaskMeanPtV2Corr.cxx
- PWGCF/FLOW/GF/AliAnalysisTaskMeanPtV2Corr.h
- PWGCF/FLOW/GF/AliGFWCuts.cxx
- PWGCF/FLOW/macros/AddTaskMeanPtV2Corr.C
Apparently, sometimes multi can go really wrong in MC
> MeanPtV2 task. Added a check for multi when filling dpt vs. v2 in MC

- PWGDQ/dielectron/core/AliDielectron.cxx
- PWGDQ/dielectron/core/AliDielectronPair.cxx
- PWGDQ/dielectron/core/AliDielectronPair.h
- PWGDQ/dielectron/core/AliDielectronTrackRotator.cxx
- PWGDQ/dielectron/core/AliDielectronTrackRotator.h
PWGDQ:LMee: modified rotation method for MC studies
> PWGDQ:LMee: modified rotation method for MC studies

- PWGGA/GammaConv/AliAnalysisTaskGammaIsoTree.cxx
- PWGGA/GammaConv/AliAnalysisTaskGammaIsoTree.h
- PWGGA/GammaConv/config/PWGGA_CF_config.yaml
- PWGGA/GammaConv/config/PWGGA_CF_config_MC.yaml
- PWGGA/GammaConvBase/AliConvEventCuts.cxx
- fixed to efficiency (inclusion of MC iso requirement also required for true rec)
- implemented histo to test ABCD method for purity as cross check
- implemented external jet finder for outlier rejection
- changed debug output in AliConvEventCuts
> PWGGA/GammaConv: iso analysis effi additions & ABCD method

- PWGPP/EMCAL/macros/AddTaskEMCALPi0Calibration.C
- PWGPP/EMCAL/macros/ConfigureEMCALRecoUtils.C
PWGPP/EMCAL: add switch on non linearity correction
> add switch on non linearity correction

- PWGHF/hfe/AliAnalysisTaskEHCorrel.cxx
- PWGHF/hfe/AliAnalysisTaskEHCorrel.h
- PWGHF/hfe/macros/AddTaskEHCorrel.C
A switch to perform mixed event correction and filling histograms
> Adding switch to do ME correction

- PWGGA/CaloTrackCorrelations/macros/AddTaskCaloTrackCorr.C
- PWGGA/CaloTrackCorrelations/macros/AddTaskCaloTrackPi0Flow.C
- PWGGA/CaloTrackCorrelations/macros/AddTaskClusterShape.C
- PWGGA/CaloTrackCorrelations/macros/AddTaskGammaHadronCorrelation.C
- PWGGA/CaloTrackCorrelations/macros/AddTaskGammaJetCorrelation.C
- PWGGA/CaloTrackCorrelations/macros/AddTaskIsoPhoton.C
- PWGGA/CaloTrackCorrelations/macros/AddTaskMergedPi0Selection.C
- PWGGA/CaloTrackCorrelations/macros/AddTaskPi0.C
- PWGGA/CaloTrackCorrelations/macros/QA/AddTaskCalorimeterQA.C
- PWGGA/CaloTrackCorrelations/macros/QA/AddTaskPi0IMGammaCorrQA.C
- PWGPP/EMCAL/macros/AddTaskEMCALClusterize.C
- PWGPP/EMCAL/macros/AddTaskEMCALPi0Calibration.C
- PWGPP/EMCAL/macros/AddTaskEMCALPi0CalibrationV2.C
- fixed Bool_t -> Int_t conversion for ConfigureEMCal 
- simplified E-calib addtask
> PWGPP/EMCAL & PWGGA/CaloCorrelations: adapted ConfigureEMCal

- PWGMM/Lumi/vdM/VdmStability/AddTask_ilofnes_Vdm.C
- PWGMM/Lumi/vdM/VdmStability/AliAnalysisTaskVdmStability.cxx
- PWGMM/Lumi/vdM/VdmStability/AliAnalysisTaskVdmStability.h
Fixing the PU rejection and timing cuts, also adding some more configurations to the stability study
> Fixing PU rejection and timing cuts

- PWGGA/GammaConv/AliPrimaryPionCuts.cxx
- PWGGA/GammaConv/macros/AddTask_GammaConvNeutralMesonPiPlPiMiNeutralMeson_CaloMode_pp.C
> PWGGA:  Add and change Cutstrings

- PWGHF/vertexingHF/AliAnalysisTaskSEXic0Semileptonic.cxx
- Modification applies to "PWGHF/vertexingHF/AliAnalysisTaskSEXic0Semileptonic.cxx"
- Added a couple of TH2 histograms (hNorm_multV0, hNorm_multSPD) to be used in the later normalization process
> TH2 added for HM trig normalization

- PWGCF/FLOW/GF/AliAnalysisTaskGFWFlow.cxx
- PWGCF/FLOW/GF/AliAnalysisTaskGFWFlow.h
- PWGCF/FLOW/GF/AliGFW.cxx
- PWGCF/FLOW/GF/AliGFW.h
Extended GFW to calculate N subevents. Optimized the code to NOT calculate the recurrent terms. Speeds up the calculation a lot. Have to still check if this extends to pt-differential
Added few setters to AliGFWFlow so that NUA can be produced for other systems too
> Work on AliGFW

- PWGHF/vertexingHF/vHFML/AliAnalysisTaskSENonPromptLc.cxx
- PWGHF/vertexingHF/vHFML/AliAnalysisTaskSENonPromptLc.h
It allows to obtain two fully independent samples from the same MC production
> Add option for downsampling

- PWGCF/FEMTOSCOPY/macros/AddTaskCharmingFemto.C
o also test close-pair rejection
> Remove sphericity selection for p-D femto

- PWGDQ/dielectron/macrosLMEE/AddTask_rbailhac_ElectronEfficiencyV2_PbPb.C
Add PID MC post calibration possibility
> Add PID MC post calibration

- PWGDQ/dielectron/core/AliAnalysisTaskElectronEfficiencyV2.cxx
- PWGDQ/dielectron/core/AliAnalysisTaskElectronEfficiencyV2.h
To weight MC in order to have a flat centrality distribution
> Fix centrality weighting

- PWGDQ/dielectron/core/AliAnalysisTask_JPsi_EMCal.cxx
- PWGDQ/dielectron/core/AliAnalysisTask_JPsi_EMCal.h
- PWGDQ/dielectron/macrosJPSI/Config_JPsi_EMCal.C
Config file with wrong parameters order now is fixed.
>  fixing bug on the order of the parameter

- PWGLF/RESONANCES/AliRsnMiniPair.cxx
- PWGLF/RESONANCES/AliRsnMiniPair.h
- PWGLF/RESONANCES/AliRsnMiniValue.cxx
- PWGLF/RESONANCES/AliRsnMiniValue.h
> two functions are added to calculate phi angle of dacay daughter of phi meson

- PWGGA/EMCALTasks/AliAnalysisTaskGammaHadron.cxx
- PWGGA/EMCALTasks/AliAnalysisTaskGammaHadron.h
Adds tracking of pi0 candidate and charged track angles
w.r.t. 3rd and 4th order event planes.
> pi0 and hadron angles with respect to 3rd, 4th order event planes

- PWGDQ/dielectron/core/AliAnalysisTaskElectronEfficiencyV2.cxx
- PWGDQ/dielectron/core/AliAnalysisTaskElectronEfficiencyV2.h
> Update for centrality

- PWGGA/GammaConv/AliAnalysisTaskGammaIsoTree.cxx
- PWGGA/GammaConv/AliAnalysisTaskGammaIsoTree.h
- PWGGA/GammaConv/macros/AddTask_GammaIsoTree.C
sorry for the second pull request, somehow forcing the changes into the previous one did not work... This now includes both commits
> PWGGA/GammaConv: light isolated photon tree

- PWGHF/vertexingHF/AliAnalysisTaskHFSimpleVertices.cxx
- PWGHF/vertexingHF/AliAnalysisTaskHFSimpleVertices.h
Add Jpsi to ee task with selection cut in aliPhysics
> PWGHF: Jpsi to e+e- task and candidate selection for HF

- PWGGA/GammaConv/AliAnalysisTaskOmegaToPiZeroGamma.cxx
- PWGGA/GammaConv/macros/AddTask_OmegaToPiZeroGamma_pp.C
- Changed fixed rotation angle from 90° to (90+-5)° to reduce a possible bias.
- Added two new Trainconfigs
> PWGGA/GammaConv: OmegaToPiZeroGamma - Adjusted Rotation Method 

- PWGJE/EMCALJetTasks/UserTasks/AliAnalysisTaskLundPlane.cxx
> wider bins for the triggered analysis

- PWGDQ/dielectron/macrosLMEE/AddTask_dsekihat_ElectronEfficiencyV2_PbPb.C
> PWGDQ/LMEE: add PID calib in MC

- PWGHF/vertexingHF/AliAnalysisTaskSELc2pKs0fromKFP.cxx
add nSigmaCombined, d_len_V0, and cosPA_V0 to Lc2V0 KF analysis task
> add variables for Lc2V0 KF analysis

- PWG/EMCAL/EMCALtrigger/AliEmcalTriggerMakerKernel.cxx
For trigger bits and ampitudes: If the entry is 0 or negative the
value for the current trigger should be ignored, as the grids are
in any case initialized with 0.
> Protection against duplicate entries in the AliVCaloTriggers

- PWGHF/hfe/AliAnalysisTaskEHCorrel.cxx
- PWGHF/hfe/macros/AddTaskEHCorrel.C
Correct the position of pPb flag definition
Minor edits to Addtask macro
> Minor edits

- PWGLF/RESONANCES/PostProcessing/f0980/AliAnalysisTaskInclusivef0f2.cxx
> [PWGLF] add INEL mode

- PWGLF/RESONANCES/PostProcessing/Xi1530/AliAnalysisTaskXi1530.cxx
Update Multiplicity bins for MC studies
> Update Multiplicity bins

- PWGCF/EBYE/CMakeLists.txt
- PWGCF/EBYE/PWGCFebyeLinkDef.h
Adding new task FBCorrelationsWithPID to PWGCFebyeLinkDef.h and CMakeLists.txt
> Adding new task FBCorrelationsWithPID to PWGCFebyeLinkDef.h and CMakeLists.txt

- PWGUD/UPC/AddTaskUpc4Pi.C
- PWGUD/UPC/AliAnalysisTaskUpc4Pi.cxx
- PWGUD/UPC/AliAnalysisTaskUpc4Pi.h
This is the new task to run on PbPb ESD data and look for 4 Pions events written by Sasha Bylinkin.
Tested in GRID successfully.
> Analysis to produce root Tree with 4 Pions

- RUN3/AliAnalysisTaskAO2Dconverter.cxx
- RUN3/AliAnalysisTaskAO2Dconverter.h
Some optimisation of the filtering in the Select method might be needed.
The current version is used in the Run2 AOD filtering.
> Initial version of kinematics filtering (from AliAnalysisTaskMCParticleFilter)

- PWGUD/UPC/CMakeLists.txt
- PWGUD/UPC/PWGUDupcLinkDef.h
In one pull request.
I will close the 2 others.
> LinkDef.h and CMake for 4Pi together

- PWGGA/GammaConv/AliAnalysisTaskGammaCaloMerged.cxx
- PWGGA/GammaConv/AliAnalysisTaskGammaCaloMerged.h
- PWGGA/GammaConv/macros/AddTask_GammaCaloMerged_pp.C
- PWGGA/GammaConv/macros/AddTask_GammaCalo_pp.C
- PWGGA/GammaConvBase/AliConvEventCuts.cxx
- Also modified mult dependent train configs for GammaCalo task
- Corrected centrality binning for high mult trigger setting
> PWGGA/GammaConv: Added probability of in-Jet analysis to merged cluster task

- PWGGA/GammaConv/macros/AddTask_GammaCalo_pp.C
> To remove the background to PHOS using new rotation method

- PWGHF/vertexingHF/AliAnalysisTaskSED0BDT.cxx
locally we don't include nlxy in training
> keep consistent with local training

- PWGJE/EMCALJetTasks/UserTasks/AliAnalysisTaskEmcalJetPerformance.cxx
> PWGJE/EMCALJetTasks/UserTasks/AliAnalysisTaskEmcalJetPerformance.cxx: finer binning for JetHistograms/hPtLeadingVsPt

- PWGCF/FEMTOSCOPY/macros/Train/malinina/Jan2021/KK_13TeV_NoSp/AddTaskFemtoKchHBT1090.C
- PWGCF/FEMTOSCOPY/macros/Train/malinina/Jan2021/KK_13TeV_NoSp/ConfigFemtoAnalysis.C
- PWGCF/FEMTOSCOPY/macros/Train/malinina/Jan2021/KK_13TeV_dist/AddTaskFemtoKchHBT1090.C
- PWGCF/FEMTOSCOPY/macros/Train/malinina/Jan2021/KK_13TeV_dist/ConfigFemtoAnalysis.C
- PWGCF/FEMTOSCOPY/macros/Train/malinina/Jan2021/KK_13TeV_jets/AddTaskFemtoKchHBT1090.C
- PWGCF/FEMTOSCOPY/macros/Train/malinina/Jan2021/KK_13TeV_jets/ConfigFemtoAnalysis.C
- PWGCF/FEMTOSCOPY/macros/Train/malinina/Jan2021/pipi_13TeV_NoSp/AddTaskFemtoKchHBT1090.C
- PWGCF/FEMTOSCOPY/macros/Train/malinina/Jan2021/pipi_13TeV_NoSp/ConfigFemtoAnalysis.C
- PWGCF/FEMTOSCOPY/macros/Train/malinina/Jan2021/pipi_13TeV_SuperJets/AddTaskFemtoKchHBT1090.C
- PWGCF/FEMTOSCOPY/macros/Train/malinina/Jan2021/pipi_13TeV_SuperJets/ConfigFemtoAnalysis.C
- PWGCF/FEMTOSCOPY/macros/Train/malinina/Jan2021/pipi_13TeV_dist/AddTaskFemtoKchHBT1090.C
- PWGCF/FEMTOSCOPY/macros/Train/malinina/Jan2021/pipi_13TeV_dist/ConfigFemtoAnalysis.C
- PWGCF/FEMTOSCOPY/macros/Train/malinina/Jan2021/pipi_13TeV_jets/AddTaskFemtoKchHBT1090.C
- PWGCF/FEMTOSCOPY/macros/Train/malinina/Jan2021/pipi_13TeV_jets/ConfigFemtoAnalysis.C
> Ludmila Malinina filtermask 96 Jan2021

- PWGDQ/dielectron/macrosLMEE/AddTask_dsekihat_ElectronEfficiencyV2_PbPb.C
- PWGDQ/dielectron/macrosLMEE/AddTask_dsekihat_lowmass_PbPb.C
- PWGDQ/dielectron/macrosLMEE/Config_dsekihat_ElectronEfficiencyV2_PbPb.C
- PWGDQ/dielectron/macrosLMEE/Config_dsekihat_lowmass_PbPb.C
- PWGDQ/dielectron/macrosLMEE/LMEECutLib_dsekihat.C
> PWGDQ/LMEE: update AddTask and Config

- PWGDQ/dielectron/macrosLMEE/AddTask_rbailhac_ElectronEfficiencyV2_PbPb.C
- PWGDQ/dielectron/macrosLMEE/AddTask_rbailhac_lowmass_PbPb.C
Change to run on 2015 pass1 with postcalibration from Carsten
> Change to run on 2015 pass1 with postcalibration from Carsten

- PWGHF/vertexingHF/vHFML/AliAnalysisTaskSEHFTreeCreatorApply.cxx
- PWGHF/vertexingHF/vHFML/AliAnalysisTaskSEHFTreeCreatorApply.h
To have possibility to reweight efficiency
> PWGHF: Re-introduce mult vars for PbPb

- PWGDQ/dielectron/macrosLMEE/AddTask_rbailhac_ElectronEfficiencyV2_PbPb.C
- PWGDQ/dielectron/macrosLMEE/AddTask_rbailhac_lowmass_PbPb.C
> Fix copy of config

- PWGGA/GammaConv/AliAnalysisTaskGammaIsoTree.cxx
- PWGGA/GammaConv/AliAnalysisTaskGammaIsoTree.h
- PWGGA/GammaConv/macros/AddTask_GammaIsoTree.C
* mainly improvements for performance, removed old track matchers not needed, streamlined elements stored during runtime etc. * * fixed bug that causes neutral particles to be counted for MCIso perp cone
> PWGGA/GammaConv: iso tree SM performance improvements & fixes

- PWGGA/GammaConv/AliAnalysisTaskSigmaPlToProtonPiZeroAOD.cxx
- PWGGA/GammaConv/AliAnalysisTaskSigmaPlToProtonPiZeroAOD.h
- PWGGA/GammaConv/macros/AddTask_SigmaPlToProtonPiZeroAOD.C
- PWGGA/GammaConvBase/AliCaloSigmaCuts.cxx
- PWGGA/GammaConvBase/AliCaloSigmaCuts.h
- Created new functions for the estimation of the correlated background.
- Added new QA plot for the estimation of the correlated background
- Split the function TrackIsSelected in two functions to get the DCA Plots without DCA cut and with track cuts.
- Created QA plots in the sigma cut class.
- Added new train configs
> PWGGA: Added new QA plots and train configs. Created new functions for the estimation of the correlated background.

- PWGCF/Correlations/DPhi/AliAnalysisTaskSEPbPbCorrelationsJetV2.cxx
- PWGCF/Correlations/DPhi/AliAnalysisTaskSEPbPbCorrelationsJetV2.h
- PWGCF/Correlations/DPhi/CMakeLists.txt
- PWGCF/Correlations/DPhi/PWGCFCorrelationsDPhiLinkDef.h
- PWGCF/Correlations/macros/AddAnalysisTaskPbPbCorrelationsJetV2.C
Hi all,
Here is the new task for the analysis of Jet v2 analysis in PbPb. Please check it. Thanks a lot!
Siyu
> Add Task to analysis Jetv2 in PbPb

- PWGCF/FEMTOSCOPY/AliFemtoUser/AliFemtoESDTrackCut.cxx
- PWGCF/FEMTOSCOPY/AliFemtoUser/AliFemtoWRzTrackCut.cxx
different tpcnsigma cut  for tests
> changes for deuterons in AliFemto, different TPCnsigma cut

- PWGLF/NUCLEX/Hypernuclei/KFHypertriton/AddHypertritonKFTree.C
- PWGLF/NUCLEX/Hypernuclei/KFHypertriton/AliAnalysisTaskHypertritonKFTree.cxx
- PWGLF/NUCLEX/Hypernuclei/KFHypertriton/AliAnalysisTaskHypertritonKFTree.h
- activated storing of secondary vertex coordinates also for data
- correct y axis of pT-difference plot
- moved EventCuts Class QA histograms inside the area which can be turned off via doQA switch
- added and moved some documentation/comments
> Update hypertriton task employing the KFParticle package

- PWGDQ/dielectron/core/AliAnalysisTaskElectronEfficiencyV2.cxx
- PWGDQ/dielectron/core/AliAnalysisTaskElectronEfficiencyV2.h
add flexibility for a phiv cut in ElectronEfficiencyV2
> PWGDQ/LMEE: add flexibility for a phiv cut in ElectronEfficiencyV2

- PWGCF/Correlations/DPhi/AliAnalysisTaskSEPbPbCorrelationsJetV2.cxx
- PWGCF/Correlations/DPhi/AliAnalysisTaskSEPbPbCorrelationsJetV2.h
- PWGCF/Correlations/macros/AddTaskPbPbCorrelationsJetV2.C
Hi all,
Here is an update for jet v2 analysis in Pb-Pb collisions, please check it. Thanks a lot!
Siyu
> Update for Jet v2 in PbPb

- PWGHF/vertexingHF/AliHFSystErr.cxx
- PWGHF/vertexingHF/AliHFSystErr.h
Systematics for D0 in pp@13TeV in fine bins
> D0 syst updated for SigmaC paper

- PWGHF/vertexingHF/AliHFSystErr.cxx
- Raw yield extraction: no more sigma+-20% cases
- PID: valuies from coarser bin analysis confirmed
> Small updates in Lc->pKpi systematics in pp at 13 TeV

- PWG/EMCAL/EMCALtasks/AliAnalysisTaskEmcalTriggerSelection.cxx
- PWG/EMCAL/EMCALtasks/AliAnalysisTaskEmcalTriggerSelection.h
- PWG/EMCAL/EMCALtrigger/AliEmcalTriggerSelection.cxx
- PWG/EMCAL/EMCALtrigger/AliEmcalTriggerSelection.h
- PWG/EMCAL/EMCALtrigger/AliEmcalTriggerSelectionCuts.cxx
- PWG/EMCAL/EMCALtrigger/AliEmcalTriggerSelectionCuts.h
- Only relevant for PbPb collisions were trigger was
running in median mode
- Not currently enabled
> Add background subtraction to trigger decision maker

- PWGCF/FLOW/GF/AliAnalysisTaskMeanPtV2Corr.cxx
- PWGCF/FLOW/GF/AliAnalysisTaskMeanPtV2Corr.h
- PWGCF/FLOW/macros/AddTaskGFWFlow.C
- PWGCF/FLOW/macros/AddTaskMeanPtV2Corr.C
MeanPtV2 now fully compliant with AliGFWCuts and ready for full systematics
> MeanPtV2 now fully compliant with AliGFWCuts and ready for full systematics

- PWGDQ/dielectron/macrosLMEE/AddTask_dsekihat_ElectronEfficiencyV2_PbPb.C
> PWGDQ/LMEE: change mee,pTee binning in MC

- PWG/Tools/AliMCSpectraWeights.cxx
- PWG/Tools/AliMCSpectraWeights.h
- PWGLF/SPECTRA/ChargedHadrons/AliMCSpectraWeights/AliMCWeightsTask.cxx
- PWGLF/SPECTRA/ChargedHadrons/AliMCSpectraWeights/AliMCWeightsTask.h
Also included debug cout for performance checks; disabled via preprocessor macros.
> Fixed adding handler in AliMCWeightTask

- PWGUD/UPC/AliAnalysisTaskUpc4Pi.cxx
- PWGUD/UPC/AliAnalysisTaskUpc4Pi.h
Fixed bugs in the code that were causing fails of Lego Train
> Train bugs fixed

- PWGDQ/dielectron/core/AliDielectron.cxx
- PWGDQ/dielectron/core/AliDielectronTrackRotator.cxx
- PWGDQ/dielectron/core/AliDielectronTrackRotator.h
modified rotation method with option to use VTracks
> PWGDQ:LMee: modified rotation method with option to use VTracks

- PWGDQ/dielectron/macrosLMEE/AddTask_rbailhac_lowmass_PbPb.C
PostCalibration of pions, kaons and protons for 2015
> PostCalibration of pions, kaons and protons for 2015

- PWGCF/Correlations/DPhi/AliAnalysisTaskSEPbPbCorrelationsJetV2.cxx
- PWGCF/Correlations/DPhi/AliAnalysisTaskSEPbPbCorrelationsJetV2.h
- PWGCF/Correlations/macros/AddTaskPbPbCorrelationsJetV2.C
Hi all,
Here is an update for jet v2 analysis, please check it. Thanks!
> Update for Jet v2 analysis

- PWGHF/hfe/macros/AddTaskHFEBESpectraEMC.C
> Adding comment

- PWGDQ/dielectron/LMEE/AliAnalysisTaskCharm.cxx
- PWGDQ/dielectron/LMEE/AliAnalysisTaskCharm.h
> eta an pt range variable

- OADB/COMMON/MULTIPLICITY/macros/calibration/CalibratePeriodPP_ZDC.C
> Add pp calibration macro for zdc analysis

- PWGCF/Correlations/DPhi/AliAnalysisTaskSEPbPbCorrelationsJetV2.cxx
- PWGCF/Correlations/DPhi/AliAnalysisTaskSEPbPbCorrelationsJetV2.h
- PWGCF/Correlations/macros/AddTaskPbPbCorrelationsJetV2.C
Hi ,
Here is an update for Jet v2 analysis, please check it.
Thanks a lot!
Siyu
> Fix a bug on centrality

- PWGCF/FEMTOSCOPY/AliFemtoUser/AliFemtoWRzTrackCut.cxx
A new option of the selection of deuterons.
> Changes for deuterons in AliFemto -- pid selection

- PWGCF/Correlations/DPhi/AliAnalysisTaskSEpPbCorrelationsJetV2.cxx
- PWGCF/Correlations/DPhi/AliAnalysisTaskSEpPbCorrelationsJetV2.h
- PWGCF/Correlations/macros/pPbCorrelations/AddTaskpPbCorrelationsJetV2.C
Hi,
Here is an update  for Jet v2 analysis in p-Pb. Please check it.
Thanks!
Siyu
> Add MC analysis in Jet v2 p-Pb

- PWGGA/GammaConv/macros/AddTask_GammaCalo_pp.C
- PWGGA/GammaConv/macros/AddTask_GammaConvCalo_pp.C
when running multiple wagons with the same calotriggermimichelper
>  PWGGA/GammaConv/ fix bug for phos trigger mimic 

- PWGDQ/dielectron/core/AliAnalysisTaskTagAndProbe.cxx
- PWGDQ/dielectron/core/AliAnalysisTaskTagAndProbe.h
> PWGDQ/LMEE: update tag and probe for DDA

- PWGDQ/dielectron/LMEE/AliAnalysisTaskBeauty.cxx
- PWGDQ/dielectron/LMEE/AliAnalysisTaskBeauty.h
flexible eta and pt range for beauty
> flexible eta and pt range for beauty

- PWGCF/FEMTOSCOPY/CMakeLists.txt
- PWGCF/FEMTOSCOPY/K0pAnalysis/AliAnalysisK0SPEventCollection.cxx
- PWGCF/FEMTOSCOPY/K0pAnalysis/AliAnalysisK0SPEventCollection.h
- PWGCF/FEMTOSCOPY/K0pAnalysis/AliAnalysisTaskK0SPFemto.cxx
- PWGCF/FEMTOSCOPY/K0pAnalysis/AliAnalysisTaskK0SPFemto.h
- PWGCF/FEMTOSCOPY/K0pAnalysis/CMakeLists.txt
- PWGCF/FEMTOSCOPY/K0pAnalysis/PWGCFK0pAnalysisLinkDef.h
- PWGCF/FEMTOSCOPY/macros/AddMyTaskK0SP.C
> Including the k0p task

- PWGCF/Correlations/DPhi/AliAnalysisTaskSEPbPbCorrelationsJetV2.cxx
- PWGCF/Correlations/DPhi/AliAnalysisTaskSEPbPbCorrelationsJetV2.h
Hi,
Here is an update for Jet v2 analysis in Pb-Pb. Please check it.
Thanks!
Siyu
> Update the jet v2 analysis in Pb-Pb

- PWGJE/EMCALJetTasks/UserTasks/AliAnalysisTaskJetCoreEmcal.cxx
- PWGJE/EMCALJetTasks/UserTasks/AliAnalysisTaskJetCoreEmcal.h
also remove shift histograms which are now not needed and slow task down
> add option to create delta pt histograms

- PWGHF/hfe/AliAnalysisTaskEHCorrel.cxx
Change partner electron TPC track cuts to match that of hadron TPC track cuts
> Changing partner electron trk cuts to match hadron

- PWGCF/FEMTOSCOPY/AliFemtoUser/AliFemtoESDTrackCutMinusJets.cxx
- PWGCF/FEMTOSCOPY/AliFemtoUser/AliFemtoESDTrackCutMinusJets.h
- PWGCF/FEMTOSCOPY/AliFemtoUser/CMakeLists.txt
- PWGCF/FEMTOSCOPY/AliFemtoUser/PWGCFfemtoscopyUserLinkDef.h
> Ludmila: AliFemtoESDTrackCutMinusJets 24-Feb-2021

- PWGHF/vertexingHF/AliAnalysisTaskSELc2pKs0fromKFP.cxx
- PWGHF/vertexingHF/AliAnalysisTaskSELc2pKs0fromKFP.h
- PWGHF/vertexingHF/macros/AddTaskLc2pKs0FromKFParticle.C
add default weight functions for pPb to KF analysis task, to be used for systematics
> add pT weight functions for LcKF analysis task

- PWGDQ/dielectron/core/AliAnalysisTaskElectronEfficiencyV2.cxx
- PWGDQ/dielectron/core/AliAnalysisTaskElectronEfficiencyV2.h
- PWGDQ/dielectron/macrosLMEE/AddTask_rbailhac_ElectronEfficiencyV2_PbPb.C
Fix for legotrain (Not reading files each job)
> Fix for legotrain (Not reading files each job)

- PWGGA/GammaConv/AliAnalysisTaskSigmaPlToProtonPiZeroAOD.cxx
- PWGGA/GammaConv/AliAnalysisTaskSigmaPlToProtonPiZeroAOD.h
- PWGGA/GammaConv/macros/AddTask_SigmaPlToProtonPiZeroAOD.C
- enlarged the true signal by adding anti sigma and added fabs to all if statements ( sigma and proton)
- added a function to select protons from lambdas and their DCA
- added some QA plots
- changed the binning of some plots
- added some train configs
> PWGGA/GammaConv: Enlarged the true signal by adding anti sigma and added some QA plots.

- PWGCF/FEMTOSCOPY/AliFemtoUser/AliFemtoModelCorrFctn3DKKGR.cxx
- PWGCF/FEMTOSCOPY/AliFemtoUser/AliFemtoModelCorrFctn3DKKGR.h
- PWGCF/FEMTOSCOPY/AliFemtoUser/CMakeLists.txt
- PWGCF/FEMTOSCOPY/AliFemtoUser/PWGCFfemtoscopyUserLinkDef.h
- PWGCF/FEMTOSCOPY/macros/Train/Gleb/Feb2021/pipi_13TeV_SuperJets/AddTaskFemtoKchHBT1090.C
- PWGCF/FEMTOSCOPY/macros/Train/Gleb/Feb2021/pipi_13TeV_SuperJets/ConfigFemtoAnalysis.C
> Gleb: AliFemtoModelCorrFctn3DKKGR class and macro

- PWGCF/Correlations/DPhi/AliAnalysisTaskSEPbPbCorrelationsJetV2.cxx
- PWGCF/Correlations/macros/AddTaskPbPbCorrelationsJetV2.C
Hi,
Here is an update for jet v2 analysis in Pb-Pb, please check them!
Thanks!
Siyu
> Update for Jet v2 analysis in Pb-Pb

- PWGDQ/dielectron/core/AliAnalysisTaskTagAndProbe.cxx
- PWGDQ/dielectron/core/AliAnalysisTaskTagAndProbe.h
- PWGDQ/dielectron/macrosLMEE/AddTask_dsekihat_TAP_PbPb.C
> PWGDQ/LMEE: update TAP for MC

- PWGHF/jetsHF/AliAnalysisHFjetTagHFE.cxx
- PWGHF/jetsHF/AliAnalysisHFjetTagHFE.h
included SPD tracklet vs. Zvertex
> included SPD tracklet vs. Zvertex

- ML/AliExternalBDT.cxx
- ML/AliMLModelHandler.cxx
* Possibility to use storage on CVMFS to reduce pressure on network from HF application jobs
* Possibility to directly use precompiled models to avoid copying+compilation step as well
> Include possibility for CVMFS paths to Treelite utility

- PWGCF/FEMTOSCOPY/AliFemtoUser/AliFemtoModelCorrFctn3DKKGR1.cxx
- PWGCF/FEMTOSCOPY/AliFemtoUser/AliFemtoModelCorrFctn3DKKGR1.h
- PWGCF/FEMTOSCOPY/AliFemtoUser/CMakeLists.txt
- PWGCF/FEMTOSCOPY/AliFemtoUser/PWGCFfemtoscopyUserLinkDef.h
> Gleb: AliFemtoModelCorrFctn3DKKGR1 class

- PWGLF/SPECTRA/CMakeLists.txt
- PWGLF/SPECTRA/ChargedHadrons/MultDepSpec/AliMultDepSpecAnalysisTaskOLD.cxx
- PWGLF/SPECTRA/ChargedHadrons/MultDepSpec/AliMultDepSpecAnalysisTaskOLD.h
- PWGLF/SPECTRA/ChargedHadrons/MultDepSpec/AliMultDepSpecAnalysisTaskUE.cxx
- PWGLF/SPECTRA/ChargedHadrons/MultDepSpec/AliMultDepSpecAnalysisTaskUE.h
- PWGLF/SPECTRA/ChargedHadrons/MultDepSpec/macros/AddTask_mkrueger_MultDepSpecOLD.C
- PWGLF/SPECTRA/ChargedHadrons/MultDepSpec/macros/AddTask_mkrueger_MultDepSpecOLDMC.C
- PWGLF/SPECTRA/PWGLFspectraLinkDef.h
- N_ch is again measured in respective area
- added sum pT of whole event and of respective area
- added mult of whole event vs mult of respective area
> N_ch is measured in respective area

- PWGCF/FEMTOSCOPY/macros/Train/Gleb/Feb_2021/MC_443/ConfigFemtoAnalysis.C
- PWGCF/FEMTOSCOPY/macros/Train/Gleb/Feb_2021/MC_544/ConfigFemtoAnalysis.C
- PWGCF/FEMTOSCOPY/macros/Train/Gleb/Feb_2021/MC_555/ConfigFemtoAnalysis.C
- PWGCF/FEMTOSCOPY/macros/Train/Gleb/Feb_2021/MC_657/ConfigFemtoAnalysis.C
- PWGCF/FEMTOSCOPY/macros/Train/Gleb/Feb_2021/MC_757/ConfigFemtoAnalysis.C
> Gleb: Feb_2021 directory with macros

- PWGHF/vertexingHF/AliAnalysisTaskCheckHFMCProd.cxx
- PWGHF/vertexingHF/AliAnalysisTaskCheckHFMCProd.h
- PWGHF/vertexingHF/macros/AddHFMCCheck.C
With this implementation, this task can run on AODs as well as ESDs
> PWGHF: Add support for running on AODs

- PWGDQ/dimuons/AliAnalysisTaskQuarkoniumTreeMC.cxx
- PWGDQ/dimuons/AliAnalysisTaskQuarkoniumTreeMC.h
- PWGDQ/dimuons/CMakeLists.txt
- PWGDQ/dimuons/PWGDQdimuonsLinkDef.h
- PWGDQ/dimuons/macros/AddTaskQuarkoniumTreeMC_Grid.C
PWGDQ: add tasks to create tree from charmonium MC productions. It works for both JPsi or Psi2S.
> PWGDQ: Add tasks to create tree from charmonium MC productions

- PWGLF/NUCLEX/Nuclei/Nuclei_UE/AliAnalysisTaskDeuteronsRT.cxx
Fixed calculation of DeltaPhi: 
Double_t delta_phi = (180.0/TMath::Pi())*TVector2::Phi_0_2pi (phi_trk-phi_ref);
> fixed calculation of delta_phi

- PWGDQ/dielectron/core/AliAnalysisTaskTagAndProbe.cxx
> PWGDQ/LMEE: quick fix to tap

- PWGDQ/dielectron/core/AliAnalysisTaskElectronEfficiencyV2.cxx
- PWGDQ/dielectron/core/AliAnalysisTaskElectronEfficiencyV2.h
- PWGDQ/dielectron/macrosLMEE/AddTask_rbailhac_ElectronEfficiencyV2_PbPb.C
Opening angle cut in the acceptance cut
> Opening angle cut in the acceptance

- PWGHF/vertexingHF/AliAnalysisTaskSELc2pKs0fromKFP.cxx
- PWGHF/vertexingHF/AliAnalysisTaskSEXicZero2XiPifromKFP.cxx
- PWGHF/vertexingHF/AliAnalysisTaskSEXicZero2XiPifromKFP.h
- PWGHF/vertexingHF/macros/AddTaskXicZero2XiPiFromKFParticle.C
Add pt weights in the generation tree and correct pt weights in the reconstruction tree
> Add pt weights in the generation tree and correct pt weights in the reconstruction tree

- RUN3/AliAnalysisTaskAO2Dconverter.cxx
- RUN3/AliAnalysisTaskAO2Dconverter.h
- BC for all triggers
- Collisions if there was a vertex
- Store also vertexer Z and 3D
Updating extra run 2 tables
> Splitting BC and Collision writing

- PWGHF/jetsHF/AliAnalysisHFjetTagHFE.cxx
- PWGHF/jetsHF/AliAnalysisHFjetTagHFE.h
- PWGHF/jetsHF/macros/AddTaskHFjetTagHFE.C
> Corrected SPD tracklet

- PWGUD/UPC/AddTaskUpc4Pi.C
- PWGUD/UPC/AliAnalysisTaskUpc4Pi.cxx
- PWGUD/UPC/AliAnalysisTaskUpc4Pi.h
and some minor changes for the analysis
> reduced trees to improve merging output

- PWGDQ/dielectron/LMEE/AliAnalysisTaskBeauty.cxx
- PWGDQ/dielectron/LMEE/AliAnalysisTaskCharm.cxx
- PWGDQ/dielectron/LMEE/AliAnalysisTaskLMeeCocktailMC.cxx
- PWGDQ/dielectron/LMEE/AliAnalysisTaskLMeeCocktailMC.h
- PWGDQ/dielectron/LMEE/AliCocktailSmearing.cxx
- PWGDQ/dielectron/LMEE/AliCocktailSmearing.h
- PWGDQ/dielectron/macrosLMEE/AddTaskBeauty.C
- PWGDQ/dielectron/macrosLMEE/AddTaskCharm.C
- PWGDQ/dielectron/macrosLMEE/AddTask_LMeeCocktailMC.C
Add possibility to weight with an efficiency
> Add possibility to weight with an efficiency

- PWGDQ/dimuons/AliAnalysisTaskQuarkoniumTreeMC.cxx
- PWGDQ/dimuons/macros/AddTaskQuarkoniumTreeMC_Grid.C
code modified to run on AliAOD.root. Furthermore the run number is no more an argument in the AddTask
> PWGDQ: Files modified in order to read AliAOD.root instead of AliAOD.Muons.root

- PWGHF/vertexingHF/AliAnalysisTaskSEXicZero2XiPifromKFP.cxx
- PWGHF/vertexingHF/AliAnalysisTaskSEXicZero2XiPifromKFP.h
- PWGHF/vertexingHF/AliRDHFCutsKFP.cxx
- PWGHF/vertexingHF/AliRDHFCutsKFP.h
- PWGHF/vertexingHF/macros/AddTaskXicZero2XiPiFromKFParticle.C
Add weights in AliRDHFCutsKFP and update variables in AliAnalysisTaskSEXicZero2XiPifromKFP
> Add weights in AliRDHFCutsKFP and update variables in AliAnalysisTaskSEXicZero2XiPifromKFP

- PWGCF/FLOW/GF/AliAnalysisTaskNonlinearFlow.cxx
- PWGCF/FLOW/GF/AliAnalysisTaskNonlinearFlow.h
- PWGCF/FLOW/GF/CorrelationCalculator.cxx
- PWGCF/FLOW/GF/CorrelationCalculator.h
Add many observables:
v_5{2}, v_6{2} gap=1.0
v_4,22, v5,32 gap scan and 3-sub
> [PAG/Flow] Add observables

- PWGCF/FEMTOSCOPY/AliFemtoUser/AliFemtoWRzTrackCut.cxx
- PWGCF/FEMTOSCOPY/AliFemtoUser/AliFemtoWRzTrackCut.h
Small changes in the class that I created in the past for my deuterons analysis. Fixing small bugs.. The change in a test setting..
> Nowa wiolata rz

- PWGDQ/dielectron/LMEE/AliAnalysisTaskLMeeCocktailMC.cxx
Fix mixed up between pt and p in LF cocktail
> Fix mixed up between pt and p in LF cocktail

- PWGHF/vertexingHF/AliHFSystErr.cxx
- PWGHF/vertexingHF/AliHFSystErr.h
Added the systematic uncertainties for the Lc->pK0S analysis in pPb at 5.02TeV using BDTs including low pT interval below 1GeV/c
> Added syst. unc. for Lc->pK0S pPb 5TeV BDT, low pT analysis

- PWGGA/GammaConv/macros/AddTask_OmegaToPiZeroGamma_pp.C
- Cell time, NL, Exotic cluster cut and M02_Max changed for 13 TeV train configs
> PWGGA/GammaConv: Changed Cluster Cuts for OmegaToPiZeroGamma Task

- PWGDQ/dimuons/AliAnalysisTaskQuarkoniumTreeMC.cxx
PWGDQ: Add a check on the daughter particles to be sure they are muons (skipping the gamma in case of a radiative decay)
> PWGDQ: Add a check on the daughter particles to be sure they are muons 

- PWGCF/Correlations/JCORRAN/Pro/AliJCDijetAna.cxx
- PWGCF/Correlations/JCORRAN/Pro/AliJCDijetHistos.cxx
- PWGCF/Correlations/JCORRAN/Pro/AliJCDijetHistos.h
- PWGCF/Correlations/JCORRAN/Pro/AliJCDijetTask.cxx
The MC event header is now able to try to use several different mc headers.
> Updated MC event header behaviour + new histos

- PWGHF/vertexingHF/vHFML/AliAnalysisTaskSEDplus.cxx
- PWGHF/vertexingHF/vHFML/AliAnalysisTaskSEDs.cxx
> Move ptB position in Ds and Dplus sparses

- PWGHF/vertexingHF/AliAnalysisTaskSEDvsMultiplicity.cxx
Done in order to increase pt range in analyses vs mult
> Increased pT limits for hPtVsMassVsMult histograms

- PWGDQ/dielectron/LMEE/AliAnalysisTaskBeauty.cxx
- PWGDQ/dielectron/LMEE/AliAnalysisTaskCharm.cxx
- PWGDQ/dielectron/macrosLMEE/AddTask_rbailhac_ElectronEfficiencyV2_PbPb.C
Fix for rapidity in HF cocktail + name in efficiency task
> Fix for rapidity in HF cocktail + name in efficiency task

- PWGHF/vertexingHF/AliAnalysisTaskSEXic2eleXifromAODtracks.cxx
- PWGHF/vertexingHF/AliAnalysisTaskSEXic2eleXifromAODtracks.h
correct tag for prompt and feed-down efficiency
> Using AliVertexingHFUtils method to tag MC efficiency

- PWGHF/vertexingHF/AliAnalysisTaskHFSimpleVertices.cxx
- PWGHF/vertexingHF/AliAnalysisTaskHFSimpleVertices.h
> Add Dplus cuts + Sync filling of vertex histograms with O2

- PWGHF/vertexingHF/AliAnalysisTaskSEHFSystPID.cxx
- PWGHF/vertexingHF/AliRDHFCuts.cxx
Moved in AliRoot from https://github.com/alisw/AliRoot/releases/tag/v5-09-57c
> PWGHF: Remove reset of TOF tune on data

- PWGHF/vertexingHF/AliAnalysisTaskSEXicZero2XiPifromKFP.cxx
Add variables of chi2topo_Omegac0ToPV and PA_Omegac0ToPV
> Add variables of chi2topo_Omegac0ToPV and PA_Omegac0ToPV

- PWGJE/EMCALJetTasks/Tracks/AliAnalysisTaskEmcalClustersRef.cxx
- PWGJE/EMCALJetTasks/Tracks/AliAnalysisTaskEmcalClustersRef.h
Only done for MC events. Needed for weighted
productions.
> Fill cluster histograms with cross section weight from event header

- PWGCF/FEMTOSCOPY/FemtoDream/AliAnalysisTaskLD.cxx
- PWGCF/FEMTOSCOPY/FemtoDream/AliAnalysisTaskLD.h
- PWGCF/FEMTOSCOPY/FemtoDream/CMakeLists.txt
- PWGCF/FEMTOSCOPY/FemtoDream/PWGCFFemtoDreamLinkDef.h
- PWGCF/FEMTOSCOPY/macros/AddTaskFemtoNanoLD.C
o Up to now only NanoAOD version available
o Now this new task is for AODs, but along the lines of the Nano task
o Using same AddTask, which has been adopted
> AOD version of Femto task for Lambda-deuteron

- PWGUD/UPC/AliAnalysisTaskUPCforward.cxx
- PWGUD/UPC/AliAnalysisTaskUPCforward.h
Updated phi and tildephi ranges for polarisation analysis.
IMPORTANT: tested and behaviour checked.
> [PWGUD/UPC] Update phi ranges polarisation.

- PWGMM/UE/UeKNO/AliAnalysisTaskGenMcKno.cxx
- PWGMM/UE/UeKNO/AliAnalysisTaskGenMcKno.h
Few modifications in the existing MC generation macro for IAA studies.
> MC studies for IAA

- PWGCF/Correlations/DPhi/AliAnalysisTaskSEPbPbCorrelationsJetV2.cxx
- PWGCF/Correlations/DPhi/AliAnalysisTaskSEPbPbCorrelationsJetV2.h
- PWGCF/Correlations/macros/AddTaskPbPbCorrelationsJetV2.C
Hi,
Here is a further update on Jet v2 in PbPb 5.02 TeV collisions. Please check it.
Thanks!
Siyu
> Update for PbPb Jet v2

- PWGHF/vertexingHF/AliHFSystErr.cxx
Update systematic uncertainties for LcTopK0S in pPb at 5TeV for BDT analysis at low pT
> Update systematic uncertainties for LcTopK0S in pPb at 5TeV BDT lowpT

- PWGDQ/dielectron/macrosLMEE/AddTask_rbailhac_ElectronEfficiencyV2_PbPb.C
- PWGDQ/dielectron/macrosLMEE/AddTask_rbailhac_lowmass_PbPb.C
Version to be able to run different add task together
> Version to be able to run different add task together

- PWGHF/vertexingHF/AliAnalysisTaskSEOmegac2eleOmegafromAODtracks.cxx
- PWGHF/vertexingHF/AliAnalysisTaskSEOmegac2eleOmegafromAODtracks.h
- PWGHF/vertexingHF/AliRDHFCutsOmegactoeleOmegafromAODtracks.cxx
- PWGHF/vertexingHF/AliRDHFCutsOmegactoeleOmegafromAODtracks.h
Optimization of Omegac0 electronic decay channel analysis
> Optimization of Omegac0 electronic decay channel analysis

- PWGLF/STRANGENESS/Ratios/AliAnalysisTaskStrangenessRatios.cxx
- PWGLF/STRANGENESS/Ratios/AliAnalysisTaskStrangenessRatios.h
> added boolean to distinguish between Omega and Xi

- PWGDQ/dielectron/macrosLMEE/AddTaskBeauty.C
- PWGDQ/dielectron/macrosLMEE/AddTaskCharm.C
- PWGDQ/dielectron/macrosLMEE/AddTask_rbailhac_lowmass_PbPb.C
> Fix to run more than one task

- PWGHF/vertexingHF/vHFML/AliHFMLVarHandler.cxx
- PWGHF/vertexingHF/vHFML/AliHFMLVarHandler.h
> Add option to fill tree with Nsigma, NsigmaComb, and bayes PID

- PWGDQ/dielectron/LMEE/AliAnalysisTaskLMeeCocktailMC.cxx
- PWGDQ/dielectron/LMEE/AliAnalysisTaskLMeeCocktailMC.h
> Fix for files in alien

- PWG/EMCAL/EMCALbase/AliAnalysisTaskEmcal.cxx
- PWG/EMCAL/EMCALbase/AliAnalysisTaskEmcal.h
In addition add static function creating the MCEventHandler
> Fix loading of MC headers from cocktail headers (ESD case)

- PWGGA/GammaConv/AliAnalysisTaskOmegaToPiZeroGamma.cxx
- All Pi0 Pt bins should now have 200 bins and go from 0 to 20 GeV/c
- Also changed the isSignal flag to kFALSE when calling MesonIsSelected() for background Pi0s
>  PWGGA/GammaConv: OmegaToPiZeroGamma - Fixed Pi0 pT Binning differences

- PWGCF/Correlations/JCORRAN/Pro/AliAnalysisTaskRidge.cxx
- PWGCF/Correlations/macros/jcorran/AddTaskRidge.C
> [PWGCF] updates for pPb

- PWGJE/EMCALJetTasks/CMakeLists.txt
- PWGJE/EMCALJetTasks/PWGJEEMCALJetTasksLinkDef.h
- PWGJE/EMCALJetTasks/UserTasks/AliAnalysisTaskEmcalJetHdEdxCorrelations.cxx
- PWGJE/EMCALJetTasks/UserTasks/AliAnalysisTaskEmcalJetHdEdxCorrelations.h
- PWGJE/EMCALJetTasks/UserTasks/AliAnalysisTaskEmcalJetHdEdxPerformance.cxx
- PWGJE/EMCALJetTasks/UserTasks/AliAnalysisTaskEmcalJetHdEdxPerformance.h
- PWGJE/EMCALJetTasks/macros/AddTaskEmcalJetHdEdxCorrelations.C
- PWGJE/EMCALJetTasks/macros/AddTaskEmcalJetHdEdxPerformance.C
This is a very slight modification of AliAnalysisTaskEmcalJetHCorrelations.
> Adding pi, K, p identified jet-hadron correlations analysis.

- PWGHF/vertexingHF/AliHFInvMassFitter.cxx
Added automatic conversion to MeV for mean and sigma labels shown in the fitter canvas output (blue labels)
> Added automatic conversion to MeV for mean and sigma

- PWGJE/EMCALJetTasks/CMakeLists.txt
- PWGJE/EMCALJetTasks/PWGJEEMCALJetTasksLinkDef.h
- PWGJE/EMCALJetTasks/UserTasks/AliAnalysisTaskEmcalJetEnergyFlow.cxx
- PWGJE/EMCALJetTasks/UserTasks/AliAnalysisTaskEmcalJetEnergyFlow.h
- PWGJE/EMCALJetTasks/macros/AddTaskEmcalJetEnergyFlow.C
- PWGJE/EMCALJetTasks/macros/runEMCalJetSampleTask.C
With this PR, I want to add my analysis task named AliAnalysisTaskEmcalJetEnergyFlow within the directory of PWGJE/EMCALJetTasks/UserTasks.
> Addition of User task AliAnalysisTaskEmcalJetEnergyFlow

- PWGCF/FEMTOSCOPY/macros/AddTaskFemtoNanoLD.C
o Fix cut on ITS PID
o Change the pT range of (anti)deuterons to high purity only
> Femto Lambda-deuteron: fix ITS PID, change pt

- PWGCF/Correlations/macros/jcorran/AddCustomMCGenPythia8Shoving.C
added a possibility to adjust shoving pt cut
> Changes in AddCustomMCGenPythia8Shoving.C

- PWGMM/Lumi/vdM/VdmStability/AliAnalysisTaskVdmStability.cxx
- PWGMM/Lumi/vdM/VdmStability/AliAnalysisTaskVdmStability.h
It was added the EMCAL, MUON and DIMUON triggers to the analysis. The code was also cleaned so any other necessary modification in the future should be easier (to add/remove/modify selection cuts).
> New Fired Triggers Added

- PWG/EMCAL/EMCALtrigger/AliEmcalTriggerMakerTask.cxx
Masked FastOR location must be specified with
"oadb"
> Add handling to load trigger offline masked FastORs from the OADB

- PWGJE/EMCALJetTasks/UserTasks/AliAnalysisTaskEA.cxx
Code author Filip Krizek has approved changes to the task
> Add limit on constituents pT of a particle level jet

- PWGGA/GammaConv/AliAnalysisTaskGammaConvDalitzV1.cxx
- PWGGA/GammaConv/AliAnalysisTaskGammaConvDalitzV1.h
- PWGGA/GammaConvBase/AliDalitzElectronCuts.cxx
- PWGGA/GammaConvBase/AliDalitzElectronCuts.h
Size of the cast arrays fixed with member persistence
> PWGGA/GamaConv/: Size of the cast arrays (ROOT Streamer)

- PWGHF/vertexingHF/vHFML/AliAnalysisTaskSEHFTreeCreatorApply.cxx
Remove code that disabled PID post-calibration in cutobject
> PWGHF: Fix PID post-calibration in task

- PWGCF/Correlations/DPhi/AliAnalysisTaskSEPbPbCorrelationsJetV2.cxx
- PWGCF/Correlations/DPhi/AliAnalysisTaskSEPbPbCorrelationsJetV2.h
- PWGCF/Correlations/macros/AddTaskPbPbCorrelationsJetV2.C
Hi all,
Here is an update for jet analysis in Pb-Pb, for analyzing the syst. uncertainty. Please approve it.
Thanks a lot!
Siyu
> Update for syst. uncertainty of Jet v2 in Pb-Pb

- PWGHF/vertexingHF/ConfigVertexingHF.C
- PWGHF/vertexingHF/ConfigVertexingHF_DplustoK0s_DstoK0s.C
- PWGHF/vertexingHF/ConfigVertexingHF_Pb_AllCent.C
- PWGHF/vertexingHF/ConfigVertexingHF_Pb_AllCent_NoLS.C
- PWGHF/vertexingHF/ConfigVertexingHF_Pb_AllCent_NoLS_16var.C
- PWGHF/vertexingHF/ConfigVertexingHF_Pb_AllCent_NoLS_NoDstar.C
- PWGHF/vertexingHF/ConfigVertexingHF_Pb_AllCent_NoLS_NoDstar_16var.C
- PWGHF/vertexingHF/ConfigVertexingHF_Pb_AllCent_NoLS_PIDLc.C
- PWGHF/vertexingHF/ConfigVertexingHF_Pb_AllCent_NoLS_PIDLc_PtDepSel_LcMinpt1_DsMinPt15_2018opt.C
- PWGHF/vertexingHF/ConfigVertexingHF_Pb_AllCent_NoLS_PIDLc_PtDepSel_LcMinpt1_DsMinPt15_2018opt_Central.C
- PWGHF/vertexingHF/ConfigVertexingHF_Pb_AllCent_NoLS_PIDLc_PtDepSel_LcMinpt1_DsMinPt15_2018opt_SemiCentral.C
- PWGHF/vertexingHF/ConfigVertexingHF_Pb_AllCent_NoLS_PIDLc_PtDepSel_LooseIP.C
- PWGHF/vertexingHF/ConfigVertexingHF_Pb_AllCent_NoLS_PIDLc_PtDepSel_LooseIP_Central.C
- PWGHF/vertexingHF/ConfigVertexingHF_Pb_AllCent_NoLS_PIDLc_PtDepSel_LooseIP_SemiCentral.C
- PWGHF/vertexingHF/ConfigVertexingHF_Pb_Cent2080.C
- PWGHF/vertexingHF/ConfigVertexingHF_TrackRel.C
- PWGHF/vertexingHF/ConfigVertexingHF_highmult.C
- PWGHF/vertexingHF/ConfigVertexingHF_pPb.C
- PWGHF/vertexingHF/ConfigVertexingHF_pPbRHF.C
- PWGHF/vertexingHF/ConfigVertexingHF_pPbRHF_DplustoK0s_DstoK0s.C
- PWGHF/vertexingHF/ConfigVertexingHF_pp_LambdaC.C
- PWGHF/vertexingHF/upgrade/ConfigVertexingHF_Pb_ITS3.C
- PWGHF/vertexingHF/upgrade/ConfigVertexingHF_Pb_Upgrade2018.C
> Add min radius and max radius cuts for V0 candidates

- PWGCF/EBYE/LongAsymmetry/AliAnalysisTaskLegendreCoef.cxx
- PWGCF/EBYE/LongAsymmetry/AliAnalysisTaskLegendreCoef.h
- PWGCF/EBYE/LongAsymmetry/macros/AddTaskLegendreCoef.C
- PWGCF/EBYE/LongAsymmetry/runLocal.C
Longitudinal fluctuations with legendre coefficients
> direct background for legendre coefficients 

- PWGDQ/dimuons/AliAnalysisTaskQuarkoniumTreeEmbedding.cxx
- PWGDQ/dimuons/AliAnalysisTaskQuarkoniumTreeEmbedding.h
- PWGDQ/dimuons/CMakeLists.txt
- PWGDQ/dimuons/PWGDQdimuonsLinkDef.h
- PWGDQ/dimuons/macros/AddTaskQuarkoniumTreeEmbedding.C
PWGDQ: task to create a tree containing muon/dimuon infos from MC embedding
Works with JPsi and Psi2S
> PWGDQ: task to create a tree containing muon/dimuon infos from MC embedding

- PWGPP/AliESDtools.cxx
@chiarazampolli could you check if this solves the problem also for you?
> Fix: function must return what it declares

- PWGGA/GammaConv/macros/AddTask_OmegaToPiZeroGamma_pp.C
- changed the unused alpha cut variation to an OAC variation
> PWGGA/GammaConv: OmegaToPiZeroGamma - Changed omega alpha cut vari to OAC vari

- PWGHF/hfe/AliAnalysisTaskEHCorrel.cxx
- PWGHF/hfe/AliAnalysisTaskHFEBESpectraEMC.cxx
- PWGHF/hfe/macros/configs/PbPb/userConfigurationEMCele_PbPb.yaml
- PWGHF/hfe/macros/configs/PbPb/userConfigurationEMCele_PbPb_MC.yaml
- PWGHF/hfe/macros/configs/pPb/userConfigurationEMCele_pp_pPb.yaml
- PWGHF/hfe/macros/configs/pPb/userConfigurationEMCele_pp_pPb_MC.yaml
- PWGHF/hfe/macros/configs/pp/userConfigurationEMCele_pp_pPb.yaml
- PWGHF/hfe/macros/configs/pp/userConfigurationEMCele_pp_pPb_MC.yaml
Applying EMCal cluster time cut
Remove exotic cluster
> Apply EMC cls timecut and remove exotic clusters

- PWGHF/vertexingHF/AliAnalysisTaskSELc2V0bachelorTMVAApp.cxx
- PWGHF/vertexingHF/AliAnalysisTaskSELc2V0bachelorTMVAApp.h
- PWGHF/vertexingHF/AliRDHFCutsLctoV0.cxx
...and a histogram 3D to study the signd0 effect, with optimized binning.
> Not using squared value for cut on RadiusV0

- PWGCF/FEMTOSCOPY/AliFemto/AliFemtoEventReaderAOD.cxx
- PWGCF/FEMTOSCOPY/AliFemto/AliFemtoEventReaderAOD.h
> Update AliFemtoEventReaderAOD for Ludmila Alpril 2021

- PWGDQ/dielectron/core/AliAnalysisTask_JPsi_EMCal.cxx
- PWGDQ/dielectron/core/AliAnalysisTask_JPsi_EMCal.h
>  including trigger simulation as a function of leg pT

- PWGCF/Correlations/JCORRAN/Pro/AliAnalysisTaskRidge.cxx
> [PWGCF] updates for pttrig to p1

- PWGDQ/dimuons/AliAnalysisTaskPbPbTree_SingleMuons.cxx
- PWGDQ/dimuons/AliAnalysisTaskPbPbTree_SingleMuons.h
- PWGDQ/dimuons/CMakeLists.txt
- PWGDQ/dimuons/PWGDQdimuonsLinkDef.h
- PWGDQ/dimuons/macros/AddTaskPbPbTree_SingleMuons.C
Task to create a tree containing only single muons kinematics (to be used for event mixing)
> Task to create a tree containing only single muons kinematics

- PWGCF/Correlations/DPhi/AliAnalysisTaskSEpPbCorrelationsJetV2.cxx
Hi all,
An update about binning changes in Jet analysis of p-Pb. Please approve it.
Thanks!
Siyu
> Update the bins of trigger pT

- PWGGA/GammaConv/AliAnalysisTaskGammaIsoTree.cxx
- PWGGA/GammaConv/AliAnalysisTaskGammaIsoTree.h
- PWGGA/GammaConvBase/AliConvEventCuts.cxx
- some minor changes to GammaIsoTree
- added CENT and noTRD to trigger correlation histo in AliConvEventCuts
> PWGGA/GammaConv: added woTRD to trigger correlation histo

- PWGDQ/dielectron/macrosLMEE/AddTask_rbailhac_lowmass_PbPb.C
Further check for mixing pools
> Further check for mixing pools

- PWGDQ/dimuons/AliAnalysisTaskPbPbTree_SingleMuons.cxx
- PWGDQ/dimuons/AliAnalysisTaskPbPbTree_SingleMuons.h
- PWGDQ/dimuons/macros/AddTaskPbPbTree_SingleMuons.C
PWGDQ: add TLorentzVectors with muon kinematics as a branch of the tree. To be used for event mixing code
> PWGDQ: add TLorentzVectors with muon kinematics as a branch of the tree

- RUN3/AliAnalysisTaskAO2Dconverter.cxx
- RUN3/AliAnalysisTaskAO2Dconverter.h
- Create dedicated table for HMPID in a separate tree
> Add HMPID to AO2D conversion

- PWGCF/Correlations/DPhi/AliAnalysisTaskSEPbPbCorrelationsJetV2.cxx
- PWGCF/Correlations/DPhi/AliAnalysisTaskSEPbPbCorrelationsJetV2.h
- PWGCF/Correlations/DPhi/AliAnalysisTaskSEpPbCorrelationsJetV2Kine.cxx
- PWGCF/Correlations/DPhi/AliAnalysisTaskSEpPbCorrelationsJetV2Kine.h
- PWGCF/Correlations/DPhi/CMakeLists.txt
- PWGCF/Correlations/DPhi/PWGCFCorrelationsDPhiLinkDef.h
- PWGCF/Correlations/macros/AddTaskPbPbCorrelationsJetV2.C
- PWGCF/Correlations/macros/pPbCorrelations/AddTaskSEpPbCorrelationsJetV2Kine.C
Hi all,
Here is a new task for analyze the MC kinematics productions. Please approve it.
Siyu
> Add task to analysis the MC jet v2

- PWGHF/vertexingHF/AliAnalysisTaskHFSimpleVertices.cxx
> Fix name of pTBins.

- PWGCF/FEMTOSCOPY/FemtoDream/AliAnalysisTaskGeorgiosNTuple.h
- PWGCF/FEMTOSCOPY/macros/AddTaskGeorgiosNTuple.C
> Open Lambda CPA Cuts for template fits

- PWGHF/vertexingHF/AliAnalysisTaskSELc2V0bachelorTMVAApp.cxx
Should definitely be made smarter...
> Fix variable list

- PWGHF/vertexingHF/AliAnalysisTaskSEOmegac2eleOmegafromAODtracks.cxx
It would be better to use the rapidity information.
> Filled variable changed

- PWGCF/Correlations/DPhi/AliAnalysisTaskSEPbPbCorrelationsJetV2.cxx
- PWGCF/Correlations/DPhi/AliAnalysisTaskSEPbPbCorrelationsJetV2.h
- PWGCF/Correlations/DPhi/AliAnalysisTaskSEpPbCorrelationsJetV2Kine.cxx
- PWGCF/Correlations/macros/AddTaskPbPbCorrelationsJetV2.C
Hi all,
Here is an update for Jet v2 analysis in Pb-Pb. Please approve it.
Thanks a lot!
Siyu
> Add CL1 estimator

- PWGHF/vertexingHF/AliHFSystErr.cxx
Update systematics from preliminary values to ones of paper proposal. Another iteration still intended
> PWGHF: Update Lc PbPb syst

- PWGHF/vertexingHF/AliAnalysisTaskSELc2V0bachelorTMVAApp.cxx
- PWGHF/vertexingHF/AliAnalysisTaskSELc2V0bachelorTMVAApp.h
Plus some reshuffling of initizlization, to remove warnings in compilation.
> remove hardcoded list of variables used for training

- PWGMM/UE/UeKNO/AliAnalysisTaskGenMcKno.cxx
Increasing axis limit in the histograms
> Updates for generations of Pb-Pb collisions

- PWGDQ/dielectron/LMEE/AliAnalysisTaskeeCor.cxx
- PWGDQ/dielectron/LMEE/AliAnalysisTaskeeCor.h
After several tests between tasks I found a better way to select HF electrons. This commit is to fix this and also remove (and understand with histograms) one unsafe cut that have been used in this task.
> fixing HF selection

- PWGDQ/dielectron/macrosLMEE/AddTask_dsekihat_ElectronEfficiencyV2_PbPb.C
> PWGDQ/LMEE: quick fix to AddTask in MC

- PWGMM/UE/UeKNO/AddTaskMcKno.C
- PWGMM/UE/UeKNO/AliAnalysisTaskMcKno.cxx
- PWGMM/UE/UeKNO/AliAnalysisTaskMcKno.h
Hybrid Track Cuts for Nch in Transverse Region and pT Spectra
> Implementation of Hybrid Track Cuts

- PWGDQ/dimuons/AliAnalysisTaskPbPbTree_SingleMuons.cxx
- PWGDQ/dimuons/AliAnalysisTaskPbPbTree_SingleMuons.h
Store the array of muon tracks as TLorentzVectors in a TObjArray
> PWGDQ: Store the muon tracks as TLorentzVector in a TObjArray

- PWGDQ/dielectron/core/AliAnalysisTask_JPsi_EMCal.cxx
- PWGDQ/dielectron/core/AliAnalysisTask_JPsi_EMCal.h
QA histos added to the task
Additional check on the trigger efficiency at J/psi pT pair also added
>  added a few QA histos

- PWGDQ/dielectron/macrosLMEE/AddTask_dsekihat_ElectronEfficiencyV2_PbPb.C
- PWGDQ/dielectron/macrosLMEE/AddTask_dsekihat_lowmass_PbPb.C
change order of loading macro in AddTask.C
> PWGDQ/LMEE: change order of loading macro in AddTask.C

- PWGDQ/dimuons/AliAnalysisTaskPbPbTree_SingleMuons.cxx
PWGDQ: replace TLorenzVector with TParticle
> PWGDQ: replace TLorenzVector with TParticle

- PWGDQ/dielectron/macrosLMEE/AddTask_dsekihat_lowmass_PbPb.C
quick fix to macro name in AddTask
> PWGDQ/LMEE: quick fix to macro name in AddTask

- PWGDQ/dielectron/macrosLMEE/AddTask_dsekihat_ElectronEfficiencyV2_PbPb.C
- PWGDQ/dielectron/macrosLMEE/AddTask_dsekihat_lowmass_PbPb.C
> PWGDQ/LMEE: avoid multiple load macro

- PWGCF/Correlations/DPhi/AliAnalysisTaskSEpPbCorrelationsJetV2Kine.cxx
- PWGCF/Correlations/macros/pPbCorrelations/AddTaskSEpPbCorrelationsJetV2Kine.C
Hi all,
Please help to approve this commit.
Thanks a lot!
Siyu
> Update for Jetv2 pPb MC

- PWGDQ/dielectron/macrosLMEE/AddTask_dsekihat_ElectronEfficiencyV2_PbPb.C
- PWGDQ/dielectron/macrosLMEE/AddTask_dsekihat_lowmass_PbPb.C
change default value for path name
> PWGDQ/LMEE: change default value for path name

- PWGGA/GammaConv/AliAnalysisTaskGammaConvDalitzV1.cxx
- PWGGA/GammaConv/AliAnalysisTaskGammaConvDalitzV1.h
The previous commit I add in the wrong section a few histograms
> PWGGA/GammaConv Fixing histograms

- PWG/EMCAL/EMCALtasks/AliAnalysisTaskEmcalTriggerSelection.cxx
- PWG/EMCAL/EMCALtrigger/AliEmcalTriggerSelectionCuts.cxx
- PWG/EMCAL/EMCALtrigger/AliEmcalTriggerSelectionCuts.h
In case of online patches the STU decision for a given
trigger patch is required in addition to energy / ADC
above threshold
> Add option to do trigger selection based on online patches

- PWGCF/Correlations/DPhi/AliAnalysisTaskSEpPbCorrelationsJetV2.cxx
- PWGCF/Correlations/DPhi/AliAnalysisTaskSEpPbCorrelationsJetV2.h
- PWGCF/Correlations/macros/pPbCorrelations/AddTaskpPbCorrelationsJetV2.C
Hi all,
Here is an update to the code, to make it more clear.
Siyu
> Update for jet v2 pPb

- PWGCF/Correlations/DPhi/AliAnalysisTaskSEpPbCorrelationsJetV2.cxx
Dear all,
Here is a mirror update for jet v2 in p-Pb. Please approve it.
Thanks!
Siyu
> Update for binning of Jet V2

- PWGJE/EMCALJetTasks/Tracks/AliAnalysisTaskEmcalClustersRef.cxx
- PWGJE/EMCALJetTasks/Tracks/AliAnalysisTaskEmcalClustersRef.h
Note: For Max. clusters the selection is done based on
E also for the histograms filled with ET.
> Add cluster histograms which are filled with ET instead of energy

- PWGCF/FEMTOSCOPY/macros/Train/malinina/Apr2021/pipi_13TeV_SuperJets/AddTaskFemtoKchHBT1090.C
- PWGCF/FEMTOSCOPY/macros/Train/malinina/Apr2021/pipi_13TeV_SuperJets/ConfigFemtoAnalysis.C
- PWGCF/FEMTOSCOPY/macros/Train/malinina/Apr2021/pipi_13TeV_dist/AddTaskFemtoKchHBT1090.C
- PWGCF/FEMTOSCOPY/macros/Train/malinina/Apr2021/pipi_13TeV_dist/ConfigFemtoAnalysis.C
- PWGCF/FEMTOSCOPY/macros/Train/malinina/Apr2021/pipi_13TeV_jets/AddTaskFemtoKchHBT1090.C
- PWGCF/FEMTOSCOPY/macros/Train/malinina/Apr2021/pipi_13TeV_jets/ConfigFemtoAnalysis.C
> lego train: Ludmila Apr2021

- PWGHF/vertexingHF/AliAnalysisTaskSEOmegac2eleOmegafromAODtracks.cxx
MC matching  for cascade and electron
> MC matchting for cascade and e

- PWGCF/Correlations/JCORRAN/Pro/AliAnalysisTaskRidge.cxx
> [PWGCF] updates for flow

- PWGMM/UE/UeKNO/AddTaskMcKno.C
- PWGMM/UE/UeKNO/AliAnalysisTaskMcKno.cxx
- PWGMM/UE/UeKNO/AliAnalysisTaskMcKno.h
Hybrid track cuts for Nch in TS and pT spectra
> Implementation of hybrid track cuts 

- PWGDQ/dielectron/core/AliAnalysisTask_JPsi_EMCal.cxx
- PWGDQ/dielectron/core/AliAnalysisTask_JPsi_EMCal.h
> trigger efficiency as a function of ET

- PWGUD/UPC/AliAnalysisTaskUpc4Pi.cxx
- PWGUD/UPC/AliAnalysisTaskUpc4Pi.h
Following the comments from Boris and Valery.
> TPC selection moved to trees

- PWGJE/EMCALJetTasks/AliAnalysisTaskJetChargeFlavourTemplates.cxx
- PWGJE/EMCALJetTasks/AliAnalysisTaskJetChargeFlavourTemplates.h
Updated the Template function to also report particle and detector level jets and a connection between the two, Additionally now the Values of K used and the Mother fraction used can be set in the Steering macro.
> Updated the Jet Charge Template function to include generator level calculation

- PWGHF/hfe/AliAnalysisTaskEHCorrel.cxx
Adding eta cut for di-had correlations
> Adding eta cut for di-had correlations

- PWGDQ/dimuons/AliAnalysisTaskPbPbTree_SingleMuons.cxx
Correct the sign assignment to muons
> PWGDQ: correct muon sign + small fixes

- PWGHF/vertexingHF/AliRDHFCutsD0toKpiBDT.cxx
- PWGHF/vertexingHF/AliRDHFCutsD0toKpiBDT.h
- PWGHF/vertexingHF/CMakeLists.txt
- PWGHF/vertexingHF/PWGHFvertexingHFLinkDef.h
- PWGHF/vertexingHF/vHFBDT/CMakeLists.txt
New RDHFCutsD0toKpiBDT class inherited from RDHFCutsD0toKpi
> Added RDHFCutsD0toKpiBDT

- PWGGA/GammaConv/AliAnalysisTaskGammaConvCalo.cxx
- PWGGA/GammaConv/macros/AddTask_GammaConvCalo_pp.C
Fixing seg fault for fIsMC > 1 while fDoECalibOutput < 2
modify trigger sys variations
>  PWGGA/GammaConv/ pp 13 TeV ConvCalo

- PWGJE/EMCALJetTasks/UserTasks/AliAnalysisTaskEmcalJetHdEdxCorrelations.cxx
Minor edit to my task to reduce memory consumption.
> Reducing sparse axes

- PWGCF/Correlations/JCORRAN/Pro/AliAnalysisTaskRidge.cxx
> [PWGCF] updates for multiplicity

- PWGGA/GammaConv/AliAnalysisTaskGammaCaloMerged.cxx
- PWGGA/GammaConv/AliAnalysisTaskGammaCaloMerged.h
- PWGGA/GammaConv/macros/AddTask_GammaCaloMerged_pp.C
- PWGGA/GammaConv/macros/AddTask_GammaCalo_pp.C
- PWGGA/GammaConvBase/AliConvEventCuts.cxx
Added electron contribution estimation for merged pion analysis (data driven background estimation)
> PWGGA/GammaConv: Modified cuts for multiplicity dep. analysis for pp 13 TeV

- PWGDQ/dimuons/AliAnalysisTaskQuarkoniumTreeEmbedding.cxx
- PWGDQ/dimuons/AliAnalysisTaskQuarkoniumTreeEmbedding.h
PWGDQ: add new muon and dimuon variables to the MC embedding tree
> PWGDQ: add new muon and dimuon variables to the MC embedding tree

- PWGGA/GammaConv/AliAnalysisTaskGammaCalo.cxx
- PWGGA/GammaConv/AliAnalysisTaskGammaConvCalo.cxx
Include additional cases to the additional True meson search
>  PWGGA/GammaConv/    AliAnalysisTaskGamma.. Calo & ConvCalo

- RUN3/AliAnalysisTaskAO2Dconverter.cxx
Added code for conversion PHOS L0 and L1 trigger to AO2D
> PHOS trigger added

- PWGCF/Correlations/JCORRAN/Pro/AliAnalysisTaskRidge.cxx
- PWGCF/Correlations/JCORRAN/Pro/AliAnalysisTaskRidge.h
> [PWGCF] updates for pPb efficiency

- PWGLF/STRANGENESS/CMakeLists.txt
- PWGLF/STRANGENESS/Cascades/Run2/AliTaskLeadingMC.cxx
- PWGLF/STRANGENESS/Cascades/Run2/AliTaskLeadingMC.h
- PWGLF/STRANGENESS/Cascades/Run2/macros/AddTaskLeadingMC.C
- PWGLF/STRANGENESS/PWGLFSTRANGENESSLinkDef.h
> Add effective energy (ZDC) analysis in MC

- PWGLF/STRANGENESS/CMakeLists.txt
- PWGLF/STRANGENESS/Cascades/Run2/AliAnalysisTaskStrangeCascadesTriggerAODRun2.cxx
- PWGLF/STRANGENESS/Cascades/Run2/AliAnalysisTaskStrangeCascadesTriggerAODRun2.h
- PWGLF/STRANGENESS/Cascades/Run2/macros/AddTaskStrangeCascadesTriggerAODRun2.C
- PWGLF/STRANGENESS/PWGLFSTRANGENESSLinkDef.h
Add a new task to study cascade-V0s/resonances/primaries correlations on an event-by-event basis
> Add new task to study cascade-V0s/resonances/primaries correlations

- PWGHF/vertexingHF/AliHFSystErr.cxx
- PWGHF/vertexingHF/AliHFSystErr.h
Systematic uncertainty entry for non-prompt Ds to KKpi in PbPb collisions (2018) at 5 TeV with ML analyses
> Systematic uncertainty entry for non-prompt Ds with ML

- PWGGA/GammaConv/macros/AddTask_GammaCalo_pp.C
- PWGGA/GammaConv/macros/AddTask_GammaConvCalo_pp.C
Adjust PCM-PHOS and PHOS Cutvariations
Modify sys variations
>  PWGGA/GammaConv Changing Cuts

- PWGMM/UE/CMakeLists.txt
- PWGMM/UE/PWGMMueLinkDef.h
- PWGMM/UE/UeKNO/AddTaskChargedVsRT.C
- PWGMM/UE/UeKNO/AliAnalysisTaskChargedVsRT.cxx
- PWGMM/UE/UeKNO/AliAnalysisTaskChargedVsRT.h
Analysis task with hybrid track cuts implementing some arrays
> Analysis task for charged particles vs RT

- PWGHF/vertexingHF/AliAnalysisTaskHFSimpleVertices.cxx
- PWGHF/vertexingHF/AliAnalysisTaskHFSimpleVertices.h
@ginnocen @vkucera @fprino this PR implements the equivalent of AliceO2Group/AliceO2#6016
> Add Physics selection read from json

- PWGCF/FEMTOSCOPY/FemtoDream/AliFemtoDreamCorrHists.cxx
- PWGCF/FEMTOSCOPY/macros/AddTaskCharmingFemto.C
- apparently too large for Root to be written out
> [FemtoDream] Reduce size of the mom. res. histograms

- PWGMM/UE/UeKNO/AliAnalysisTaskChargedVsRT.cxx
- PWGMM/UE/UeKNO/AliAnalysisTaskChargedVsRT.h
Modifications to reduce memory consumption in the analysis task
> To reduce memory leak

- RUN3/AliAnalysisTaskAO2Dconverter.cxx
- If no TOF is available set negative time
- Set name/title arrays for easier diff
> RUN3 conversion: If no TOF is available set negative time

- PWGCF/FEMTOSCOPY/AliFemto/AliFemtoEventReaderAOD.cxx
- PWGCF/FEMTOSCOPY/AliFemto/AliFemtoEventReaderAOD.h
> AliFemtoEventReaderAOD update for Ludmila

- PWG/EMCAL/EMCALtrigger/AliEmcalTriggerMaskHandlerOCDB.cxx
- PWG/EMCAL/EMCALtrigger/AliEmcalTriggerMaskHandlerOCDB.h
- PWG/EMCAL/EMCALtrigger/CMakeLists.txt
- PWG/EMCAL/EMCALtrigger/PWGEMCALtriggerLinkDef.h
Providing trigger mask from OCDB at L0 and L1
- as list of FastOR abs. ID
- as list of position in the EMCAL space
> Mask hander providing EMCAL trigger mask in various formats from OCDB

- PWGMM/Lumi/vdM/VdmStability/AddTask_ilofnes_Vdm.C
- PWGMM/Lumi/vdM/VdmStability/AliAnalysisTaskVdmStability.cxx
- PWGMM/Lumi/vdM/VdmStability/AliAnalysisTaskVdmStability.h
The AddTask was modified to allow the user to give the input to timing cuts.
> New AddTask configuration

- PWGJE/EMCALJetTasks/Tracks/AliAnalysisTaskEmcalJetSpectrumSDPart.cxx
- PWGJE/EMCALJetTasks/Tracks/AliAnalysisTaskEmcalJetSpectrumSDPart.h
Needed for weighted pythia productions
> Add option to fill histograms with the cross section weight

- PWGCF/FEMTOSCOPY/macros/Train/malinina/May2021/pipi_13TeV_Jets/AddTaskFemtoKchHBT1090.C
- PWGCF/FEMTOSCOPY/macros/Train/malinina/May2021/pipi_13TeV_Jets/ConfigFemtoAnalysis.C
- PWGCF/FEMTOSCOPY/macros/Train/malinina/May2021/pipi_13TeV_SuperJets/AddTaskFemtoKchHBT1090.C
- PWGCF/FEMTOSCOPY/macros/Train/malinina/May2021/pipi_13TeV_SuperJets/ConfigFemtoAnalysis.C
> Train macros May2021 for Ludmila

- PWGDQ/dielectron/macrosLMEE/AddTaskCharm.C
> Fix CNM charm

- PWGCF/FLOW/GF/AliAnalysisTaskMeanPtV2Corr.cxx
- PWGCF/FLOW/GF/AliAnalysisTaskMeanPtV2Corr.h
Also, messed up something in the last commits, fixing now
> MeanPtV2: correlation parameters are now members of analysis task

- PWGMM/UE/UeKNO/AddTaskChargedVsRT.C
- PWGMM/UE/UeKNO/AliAnalysisTaskChargedVsRT.cxx
- PWGMM/UE/UeKNO/AliAnalysisTaskChargedVsRT.h
w/ 2015 track cuts or hybrid track cuts
> Selecting 2015 track cuts

- PWGHF/vertexingHF/AliCFTaskVertexingHF.cxx
- PWGHF/vertexingHF/AliCFTaskVertexingHF.h
Lc pt Weights Pythia Mode2 pp@13TeV
> Lc pt Weights PythiaMode2 pp@13TeV

- PWGCF/Correlations/macros/jcorran/AddTaskJHOCFAMaster.C
- PWGCF/Correlations/macros/jcorran/AddTaskJHOCFAMaster10h.C
and added flexible arguments for the systematics
> (PWG-CF) Fixed call to the correction map

- PWGHF/vertexingHF/AliHFSystErr.cxx
Update of the D0 systematic uncertainties in Pb-Pb 2018 (pass3):
- raw yield
- selection efficiency (cut variation)
- MC pt-shape
- tracking efficiency
- PID efficiency
The results have been presented in the D2H meeting of 4th June 2021 (https://indico.cern.ch/event/1043402/)
> Syst. unc. PbPb D0 (topological analysis) - final (pass3)

- PWGHF/vertexingHF/AliAnalysisTaskSEHFSystPID.h
To allow for flexible modification of track cuts
> function to get ESD track cuts

- PWGGA/GammaConv/AliAnalysisTaskGammaCaloMergedML.cxx
- PWGGA/GammaConv/AliAnalysisTaskGammaCaloMergedML.h
- PWGGA/GammaConv/macros/AddTask_GammaCaloMergedML_pp.C
I reorganized how my trees are written into the root-file. Additionally I added several branches to the trees for additional information. All other changes concern mostly removing now unnecessary test cases and unused variables.
> PWGGA/GammaConv: Modification of my Task GammaCaloMergedML

- PWGCF/Correlations/DPhi/AliAnalysisTaskSEpPbCorrelationsJetV2Kine.cxx
- PWGCF/Correlations/macros/pPbCorrelations/AddTaskSEpPbCorrelationsJetV2Kine.C
Dear all,
Here is an update of jet particle v2 in AMPT p-Pb, please approve it.
Thanks!
Siyu
> Update of jet particle v2 in p-Pb of AMPT

- PWGLF/STRANGENESS/Cascades/Run2/AliAnalysisTaskStrangenessVsMultiplicityEEMCRun2.cxx
- PWGLF/STRANGENESS/Cascades/Run2/AliAnalysisTaskStrangenessVsMultiplicityEEMCRun2.h
- PWGLF/STRANGENESS/Cascades/Run2/AliAnalysisTaskStrangenessVsMultiplicityEERun2.cxx
- PWGLF/STRANGENESS/Cascades/Run2/AliAnalysisTaskStrangenessVsMultiplicityEERun2.h
> Get new ZDC estimators from OADBs + add Nch

- PWGCF/Correlations/JCORRAN/Pro/AliAnalysisTaskEmcalJetDijetMass.cxx
- PWGCF/Correlations/JCORRAN/Pro/AliAnalysisTaskEmcalJetDijetMass.h
- PWGCF/Correlations/JCORRAN/Pro/AliJCDijetAna.cxx
- PWGCF/Correlations/JCORRAN/Pro/AliJCDijetTask.cxx
- PWGCF/Correlations/macros/jcorran/AddTaskEmcalJetDijetMass.C
> Advanced dijet mass analysis for emcal framework.

- PWGCF/Correlations/macros/AddCustomMCGenPythia8QuarkGluonJet.C
> Change in PWGCF/Correlations/macros/AddCustomMCGenPythia8QuarkGluonJet.C

- PWGCF/Correlations/DPhi/AliAnalysisTaskSEpPbCorrelationsJetV2Kine.cxx
- PWGCF/Correlations/DPhi/AliAnalysisTaskSEpPbCorrelationsJetV2Kine.h
- PWGCF/Correlations/macros/pPbCorrelations/AddTaskSEpPbCorrelationsJetV2Kine.C
Hi all,
Here is an update of Jet v2 analysis code in AMPT. Please approve it. 
Thanks!!!
Siyu
> Update for Jet v2 in AMPT

- PWGJE/EMCALJetTasks/UserTasks/AliAnalysisTaskEmcalJetEnergyFlow.cxx
- PWGJE/EMCALJetTasks/UserTasks/AliAnalysisTaskEmcalJetEnergyFlow.h
The following changes are included:
a) The IsMCprod data member is properly initialized and assigned the value from the add task method so that it can handle the analysis of MC as well as data.
b) Small fixes in the if conditions of the Response matrix creation to avoid errors due to array indices
c) Added 1 debug/printout option.
> Small update and cleanup of AliAnalysisTaskEmcalJetEnergyFlow task

- PWGHF/vertexingHF/AliAnalysisTaskHFSimpleVertices.cxx
- PWGHF/vertexingHF/AliAnalysisTaskHFSimpleVertices.h
> Fix pt-bin finding for cut application

- PWGCF/Correlations/DPhi/AliAnalysisTaskSEpPbCorrelationsJetV2Kine.cxx
- PWGCF/Correlations/macros/pPbCorrelations/AddTaskSEpPbCorrelationsJetV2Kine.C
Hi all,
Here is an update of this analyis to deal with the memory consumption. Please approve it soon. Thanks a lot!
Siyu
> Update for AMPT jet-particle v2

- PWGGA/GammaConv/AliAnalysisTaskGammaCalo.cxx
- PWGGA/GammaConv/AliAnalysisTaskGammaConvCalo.cxx
- PWGGA/GammaConv/macros/AddTask_GammaCaloMerged_pp.C
- PWGGA/GammaConv/macros/AddTask_GammaCalo_pp.C
- PWGGA/GammaConv/macros/AddTask_GammaConvCalo_pp.C
- PWGGA/GammaConvBase/AliConvEventCuts.cxx
- PWGGA/GammaConvBase/AliConvEventCuts.h
- Fixed floating point exception in inJet mixed background calculation
> PWGGA/GammaConv: Added trains configs and histo for pp multiplicity studies

- PWGMM/UE/UeKNO/AliAnalysisTaskMcKnoUe.cxx
- change event trigger for run1 and run2
> change event trigger for run1 and run2

- PWGCF/Correlations/macros/AddMCGenPythia8ShovingAndColorRopes.C
Pythia with shoving and flavour ropes
> new macro for MC gen train

- PWGGA/GammaConv/macros/AddTask_GammaCaloMergedML_pp.C
Updated the Addtask of my analysis to get output for non-generic MC-events.
> PWGGA/GammaConv: Fixed the AddTask of GammaCaloMergedML to work with JJ-MC-Events

- PWGHF/vertexingHF/AliAnalysisTaskSEXicPlusToXi2PifromKFP.cxx
- PWGHF/vertexingHF/AliAnalysisTaskSEXicPlusToXi2PifromKFP.h
Correct the way of 3-prongs combination
> Correct the way of 3-prongs combination

- PWGLF/STRANGENESS/CMakeLists.txt
- PWGLF/STRANGENESS/Cascades/Run2/AliAnalysisTaskStrangeCascadesTriggerAODRun2MC.cxx
- PWGLF/STRANGENESS/Cascades/Run2/AliAnalysisTaskStrangeCascadesTriggerAODRun2MC.h
- PWGLF/STRANGENESS/Cascades/Run2/macros/AddTaskStrangeCascadesTriggerAODRun2MC.C
- PWGLF/STRANGENESS/PWGLFSTRANGENESSLinkDef.h
Add the MC version of the AliAnalysisTaskStrangeCascadesTriggerAODRun2, to compare reconstructed and MC info, and extract correction factors for cascades/V0s/resonances/primaries
> Add MC version of StrangeCascadesTriggerAODRun2 task

- PWGGA/GammaConv/macros/AddTask_GammaConvDalitzV1_pp.C
- PWGGA/GammaConvBase/AliDalitzElectronCuts.cxx
Fixing errors: Abs() and new cuts
> PWGGA/GammaConv - Errors in Optimization

- PWGHF/vertexingHF/AliAnalysisTaskSEXicPlusToXi2PifromKFP.cxx
- PWGHF/vertexingHF/AliAnalysisTaskSEXicZero2XiPifromKFP.cxx
correct QA check after non-linear mass constraint
> correct QA check after non-linear mass constraint

- PWGHF/vertexingHF/upgrade/AliAnalysisTaskSECharmTriggerStudy.h
> Change type for momentum component to increase precision

- PWGGA/GammaConv/macros/AddTask_GammaCaloMerged_pp.C
- PWGGA/GammaConv/macros/AddTask_GammaCalo_pp.C
- multiplicity differential cuts added (also including EMC triggered data)
- cuts for EMC and DMC triggers updated
> PWGGA/GammaConv: Added and modified train configs for pp 13TeV EMC and mEMC

- PWGHF/vertexingHF/AliRDHFCutsKFP.cxx
- PWGHF/vertexingHF/AliRDHFCutsKFP.h
Change fPtMinPiFromXic0 to fPtMinPiFromPrimary and add variables for Xicc++
> Change fPtMinPiFromXic0 to fPtMinPiFromPrimary and add variables for Xicc++

- PWGGA/GammaConv/macros/AddTask_GammaConvDalitzV1_pp.C
Correction in hits in the ITS and Psipair cut
> PWGGA/GammaConv - Improved in R Bins

- PWGHF/vertexingHF/AliAnalysisTaskSEXiccPPToXicPlusPiPlusfromKFP.cxx
- PWGHF/vertexingHF/AliAnalysisTaskSEXiccPPToXicPlusPiPlusfromKFP.h
- PWGHF/vertexingHF/CMakeLists.txt
- PWGHF/vertexingHF/PWGHFvertexingHFLinkDef.h
- PWGHF/vertexingHF/macros/AddTaskXiccPPToXicPlusPiPlusFromKFParticle.C
Add Xicc++ analysis task with KF
> Add Xicc++ analysis task with KF

- PWGHF/vertexingHF/AliAnalysisTaskSEDvsRT.cxx
- PWGHF/vertexingHF/AliAnalysisTaskSEDvsRT.h
add histo to calculate the average multiplicity in the transverse region
> add histo to calculate the average multiplicity in the transverse region

- PWGGA/GammaConv/macros/AddTask_GammaConvCalo_pp.C
- PWGGA/GammaConvBase/AliConversionMesonCuts.cxx
- PWGGA/GammaConvBase/AliConversionMesonCuts.h
changes for MC pcm gamma smearing
enable bremsstrahlung without gaus smearing
>  PWGGA/GammaConv pcm gamma E smearing

- PWGLF/RESONANCES/macros/mini/AddTaskF0.C
- PWGLF/RESONANCES/macros/mini/ConfigF0.C
This commit now includes the update for systematics on track quality cuts in f0 analysis.
> Update for systematics on track quality cuts in f0 analysis

- PWGDQ/dielectron/core/AliDielectronVarManager.cxx
- PWGDQ/dielectron/core/AliDielectronVarManager.h
Add signed and geometrical mean version.
> PWGDQ:LMee: Inclusion of modified DCAee variables

- PWGCF/Correlations/DPhi/AliAnalysisTaskSEpPbCorrelationsJetV2.cxx
- PWGCF/Correlations/macros/pPbCorrelations/AddTaskpPbCorrelationsJetV2.C
Dear all,
Here is an update on jet-particle v2 analysis, where the FMDA-FMDC correlation is added. Please approve it. Thanks!!
Siyu
> Update on Jet-particle v2 task

- PWGCF/FEMTOSCOPY/macros/AddTaskAnyCharmingFemto.C
> Add default pion selections

- PWGGA/GammaConv/AliAnalysisTaskGammaConvDalitzV1.cxx
Light version update: !fDolightversion options v2
> PWGGA/GammaConv -Light version update

- PWG/EMCAL/EMCALbase/AliEMCALRecoUtils.cxx
- PWG/EMCAL/EMCALbase/AliEMCALRecoUtils.h
- PWG/EMCAL/EMCALtasks/AliEmcalCorrectionCellEnergy.cxx
- PWG/EMCAL/EMCALtasks/AliEmcalCorrectionCellEnergy.h
- PWG/EMCAL/config/AliEmcalCorrectionConfiguration.yaml
- Now the cell scale it can have different values depending on the SM type (full, 2/3 and 1/3)
> PWG/EMCal: Modified additional cell scale (now SM dependent)

- PWGLF/STRANGENESS/CMakeLists.txt
- PWGLF/STRANGENESS/PWGLFSTRANGENESSLinkDef.h
- PWGLF/STRANGENESS/StrPDF/AliAnalysisTaskV0multspec.cxx
- PWGLF/STRANGENESS/StrPDF/AliAnalysisTaskV0multspec.h
- PWGLF/STRANGENESS/StrPDF/macros/AddTaskV0multspec.C
New task to extract e-by-e V0 yields to determine full PDF for strange particle production
> Beta version of analysis task for full strangeness PDF determination

- PWGHF/vertexingHF/AliCFTaskVertexingHF.cxx
- PWGHF/vertexingHF/AliCFTaskVertexingHF.h
- PWGHF/vertexingHF/macros/AddTaskCFVertexingHF.C
- PWGHF/vertexingHF/macros/AddTaskCFVertexingHF3Prong.C
correct CF bin limits for the RT case and add the setter for the aver… age multiplicity in the trnasverse region
> correct CF bin limits for the RT case and add the setter

- PWGGA/GammaConv/macros/AddTask_GammaCalo_pp.C
- PWGGA/GammaConv/macros/AddTask_GammaConvCalo_pp.C
- PWGGA/GammaConvBase/AliCaloPhotonCuts.cxx
new NonLins are TestBeamShaper with different scales for data and
TestBeam without fine tuning for MC.
> PWGGA/GammaConv: Added new NonLin settings and respective train configs

- PWGLF/STRANGENESS/PWGLFSTRANGENESSLinkDef.h
Added  structs V0filler and Cascfiller structs to LinkDef
> Add V0 and Casc fillers to LinkDef

- PWGLF/RESONANCES/macros/mini/AddTaskF0.C
- PWGLF/RESONANCES/macros/mini/ConfigF0.C
This commit adds option to control the pT binning from the AddTask.
> Updates on pT binning for f0 analysis

- PWGDQ/dielectron/core/AliDielectronVarManager.cxx
- PWGDQ/dielectron/core/AliDielectronVarManager.h
> PWGDQ:LMee: Inclusion of modified DCAee variables: fix

- PWGLF/STRANGENESS/StrPDF/AliAnalysisTaskV0multspec.h
Fixed fpart and fAddCasc persistence
> Fixed fpart and fAddCasc persistence

- PWGGA/GammaConv/macros/AddTask_OmegaToPiZeroGamma_pp.C
- There can be no train config with both mixed event and rotation method in one. Fixed this.
> PWGGA/GammaConv/macros: OmegaToPiZeroGamma AddTask - Fixed Train Configs

- PWGHF/correlationHF/AliAnalysisHFEHCorrOnFlySim.cxx
- PWGHF/correlationHF/AliAnalysisHFEHCorrOnFlySim.h
- PWGHF/correlationHF/CMakeLists.txt
- PWGHF/correlationHF/PWGHFcorrelationHFLinkDef.h
- PWGHF/correlationHF/macros/AddTaskHFEHCorrOnFlySim.C
Task to perform HFE-h correlation MonteCarlo studies on fly. Derived from AliAnalysisHFCorrOnFlySim task.
> Task to perform HFE-h MC studies

- PWGDQ/dielectron/core/AliDielectronVarManager.cxx
- PWGDQ/dielectron/core/AliDielectronVarManager.h
- PWGDQ/dielectron/macrosLMEE/AddTask_rbailhac_lowmass_PbPb.C
Add variable: Abs(phi_{ee}-phi_{e}), accoplanarity + possibility in macro to correct track per track for the efficiency
> Add variable: Abs(phi_{ee}-phi_{e}), accoplanarity 

- PWG/Tools/AliMCSpectraWeights.cxx
- PWG/Tools/AliMCSpectraWeights.h
- PWGLF/SPECTRA/ChargedHadrons/AliMCSpectraWeights/AddTask_MCWeights.C
- PWGLF/SPECTRA/ChargedHadrons/AliMCSpectraWeights/AliMCWeightsTask.cxx
- PWGLF/SPECTRA/ChargedHadrons/AliMCSpectraWeights/AliMCWeightsTask.h
included Lambda in first train iteration for MC simulation
updated default input paths for pp and PbPb
> Updated particle-composition correction task

- PWGJE/EMCALJetTasks/AliAnalysisTaskJetCharge.cxx
- PWGJE/EMCALJetTasks/AliAnalysisTaskJetChargeFlavourTemplates.cxx
- PWGJE/EMCALJetTasks/AliAnalysisTaskJetChargeFlavourTemplates.h
I have altered the binning of the jet charge histograms and added a response matrix for each flavour to optimise for unfolding.
> optimising for unfolding

- PWGGA/GammaConv/macros/AddTask_ConvCaloCalibration_CaloMode_pp.C
- PWGGA/GammaConv/macros/AddTask_GammaCalo_pp.C
- PWGGA/GammaConv/macros/AddTask_GammaConvCaloCalibration_MixedMode_pp.C
- PWGGA/GammaConv/macros/AddTask_GammaConvCalo_pp.C
- PWGGA/GammaConvBase/AliCaloPhotonCuts.cxx
- Added one finetuning obtained with PCM-EMC and one with EMC-EMC
- Additionally added respective train configs for EMC and PCMEMC
> PWGGA/GammaConv: Added NonLin finetunings to be used with new cell scale

- PWGGA/GammaConv/AliAnalysisTaskConvCaloCalibration.cxx
- PWGGA/GammaConv/AliAnalysisTaskConvCaloCalibration.h
- PWGGA/GammaConv/macros/AddTask_ConvCaloCalibration_CaloMode_pp.C
- PWGGA/GammaConv/macros/AddTask_GammaCalo_pp.C
- PWGGA/GammaConv/macros/AddTask_GammaConvCaloCalibration_MixedMode_pp.C
- PWGGA/GammaConv/macros/AddTask_GammaConvCalo_pp.C
- new train configs for EMCal NonLin studies
> PWGGA/GammaConv: Added background rotation method to Calibration task and added train configs

- PWGGA/GammaConv/macros/AddTask_GammaConvDalitzV1_pp.C
- PWGGA/GammaConvBase/AliDalitzElectronCuts.cxx
- PWGGA/GammaConvBase/AliDalitzElectronCuts.h
Using light outputs from Adrian in the Event, Meson, ConvPhotos Cuts, and implementation in Dalitz Electrons.
> PWGGA/GammaConv - LightOutputv3

- PWGHF/hfe/AliAnalysisTaskEHCorrel.cxx
Remove in-bunch pileup events in MC
> Remove in-bunch pileup events in MC

- PWGCF/Correlations/DPhi/Unfoldedhistos/Ali2PCorrelations.cxx
- PWGCF/Correlations/DPhi/Unfoldedhistos/Ali2PCorrelations.h
Because it impacts the performance of the task the change will be reverted once the tests are carried out
> Testing the impact of the aliasing

- PWGHF/correlationHF/AliAnalysisHFEHCorrOnFlySim.cxx
Loop over mother to go back further to separate electrons from D and B decays
> Loop over mother to separate D and B decay ele

- PWGGA/GammaConv/macros/AddTask_ConvCaloCalibration_CaloMode_pp.C
- PWGGA/GammaConv/macros/AddTask_GammaCalo_pp.C
- PWGGA/GammaConv/macros/AddTask_GammaConvCaloCalibration_MixedMode_pp.C
- PWGGA/GammaConv/macros/AddTask_GammaConvCalo_pp.C
- PWGGA/GammaConvBase/AliCaloPhotonCuts.cxx
These functions are supposed to be used together with the new cell scale
Functions for EMC-EMC and PCM-EMC are added as well as an interpolation
between these two
Corresponding train configs were added too
> PWGGA/GammaConv: Added new NonLinearity functions

- PWGGA/GammaConv/macros/AddTask_GammaConvCalo_pp.C
- PWGGA/GammaConvBase/AliConversionMesonCuts.cxx
Changes to pcmphos lowb cuts, RBins and smearing
>  PWGGA/GammaConv 

- PWGGA/GammaConv/macros/AddTask_GammaCalo_pp.C
Configs for EMCal trigger studies with updated NonLin
> PWGGA/GammaConv: Added train configs including new NonLinearity

- PWGLF/RESONANCES/macros/mini/AddTaskF0.C
bug fix on trigger selection for AOD in f0 analysis
> bug fix on trigger selection for AOD

- PWGGA/GammaConvBase/AliCaloPhotonCuts.cxx
- PWGGA/GammaConvBase/AliCaloPhotonCuts.h
pPb 8TeV pass2 general-purpose MC
> PWGGA/GammaConv: added LHC20f11d pass2 MB MC to afterburners

- PWG/EMCAL/EMCALtasks/AliAnalysisTaskEmcalTriggerSelection.cxx
- added pPb 8 TeV pass2 MCs to triggerselection (MB, JJLow, JJHigh and GJ)
> PWG/EMCAL: added new pPb8TeV MC to triggerselection

- PWGHF/vertexingHF/AliAnalysisTaskHFSimpleVertices.cxx
- PWGHF/vertexingHF/AliAnalysisTaskHFSimpleVertices.h
This PR makes the code equivalent to the O2 counterpart https://github.com/AliceO2Group/AliceO2/pull/6392
> Implement pT-differential skim selections

- PWGLF/STRANGENESS/CMakeLists.txt
- PWGLF/STRANGENESS/Cascades/Run2/AliAnalysisTaskMCPredictions.cxx
- PWGLF/STRANGENESS/Cascades/Run2/AliAnalysisTaskMCPredictions.h
@arossi81 this implementation includes another 13 particles with a promptness check using 
`AliVertexingHFUtils::CheckOrigin(lMCevent, lMCPart, kTRUE)==0`
Not sure if I understood the usage of the method so well, so please jump up in case I did it wrong :-D Thanks a lot!!!
> Add prompt HF

- PWGLF/SPECTRA/ChargedHadrons/MultDepSpec/AliMultDepSpecAnalysisTaskOLD.cxx
- PWGLF/SPECTRA/ChargedHadrons/MultDepSpec/AliMultDepSpecAnalysisTaskOLD.h
- PWGLF/SPECTRA/ChargedHadrons/MultDepSpec/AliMultDepSpecAnalysisTaskUE.cxx
- PWGLF/SPECTRA/ChargedHadrons/MultDepSpec/AliMultDepSpecAnalysisTaskUE.h
- Added direct calculation of <sump_T> and <N_acc> in regions
- Added MC Truth information for correlation observables
> improvement on sum pT and multiplicity correlation

- PWGGA/GammaConv/AliAnalysisTaskConvCaloCalibration.cxx
- PWGGA/GammaConv/AliAnalysisTaskConvCaloCalibration.h
- PWGGA/GammaConv/macros/AddTask_ConvCaloCalibration_CaloMode_pp.C
- PWGGA/GammaConvBase/AliCaloPhotonCuts.cxx
- histograms for M02 and exotic studies
- also added some new train configs
> PWGGA/GammaConv: Added new histograms to calo calibration task

- PWGLF/STRANGENESS/Cascades/Run2/AliAnalysisTaskStrangeCascadesTriggerAODRun2.cxx
- PWGLF/STRANGENESS/Cascades/Run2/AliAnalysisTaskStrangeCascadesTriggerAODRun2.h
- PWGLF/STRANGENESS/Cascades/Run2/macros/AddTaskStrangeCascadesTriggerAODRun2.C
- Add rotation along z to estimate the combinatorial background of the resonances
- Change the name of the tree fTreeRsnMixed in fTreeRsnBkg
- Add two branches in the tree fTreeCascade
- Fix typos
> Add rotation for resonances + change some names + fix typos

- PWGGA/GammaConv/AliAnalysisTaskConvCaloTree.cxx
- PWGGA/GammaConv/AliAnalysisTaskConvCaloTree.h
- PWGGA/GammaConv/macros/AddTask_ConvCaloTree.C
- F+ and exoticity was added
- Track matcher added to add task
> PWGGA/GammaConv: Added variables to tree task

- PWGCF/Correlations/DPhi/AliAnalysisTaskSEpPbCorrelationsJetV2.cxx
Dear all,
Here is an update for bin size of FMDA-FMDC correlation. Please approve it. Thanks!
Siyu
> Update the bin size

- PWGGA/GammaConv/AliAnalysisTaskGammaCaloMerged.cxx
- PWGGA/GammaConv/AliAnalysisTaskGammaCaloMerged.h
- check if cluster/particle passes the Jet criterium was moved to a
dedicated function
- Histograms for missed (clus in true but not in rec) and fake (clus in
rec. but not in true Jet) added
> PWGGA/GammaConv: Simplified Merged cluster task for inJet analyses

- PWGHF/vertexingHF/AliAnalysisTaskSEDvsRT.cxx
- PWGHF/vertexingHF/AliAnalysisTaskSEDvsRT.h
Corrected the process of region determination (now it uses AND instead of OR)
Added few QA histograms for cross-checking the results
> Change to the region determination

- PWGGA/GammaConv/macros/AddTask_GammaCalo_pp.C
- PWGGA/GammaConv/macros/AddTask_GammaConvCalo_pp.C
- PWGGA/GammaConvBase/AliCaloPhotonCuts.cxx
- New functions obtained with EMC-EMC pi0 tagged clusters
- Pol2 and Gaussian Parametrization used
- Added additional fine tuning to new EMCal standard case (99)
> PWGGA/GammaConv: Added new NCell efficiency functions, modified finetuning

- PWGCF/FEMTOSCOPY/FemtoDream/AliAnalysisTaskThreeBodyFemtoAOD.cxx
- PWGCF/FEMTOSCOPY/FemtoDream/AliAnalysisTaskThreeBodyFemtoAOD.h
- PWGCF/FEMTOSCOPY/macros/AddTaskThreeBodyFemto.C
Additional QA histograms included, third limit for sampling added, track cleaning included in trigger
> Updated 3Body Trigger

- PWGLF/STRANGENESS/Cascades/Run2/AliAnalysisTaskStrangeCascadesTriggerAODRun2.cxx
Fix rotation to compute combinatorial background on resonances 
- rotation was done but not save
> Fix rotation on resonances

- PWGCF/FEMTOSCOPY/macros/AddTaskFemtoDreamLambdaPhiNanoAOD.C
I apologize for the silly mistake but the compilation of AliPhysics went fine and I spotted it today.
> Missing ; in LambdaPhi AddTask but compilation not fail

- PWGJE/EMCALJetTasks/AliAnalysisTaskJetCharge.cxx
- PWGJE/EMCALJetTasks/AliAnalysisTaskJetChargeFlavourTemplates.cxx
in order to help with the unfolding progress which struggles with empty/low statistics bins.
> The range of the histograms has been reduced to reduce the number of empty bins

- PWGGA/GammaConv/macros/AddTask_GammaCalo_pp.C
- PWGGA/GammaConv/macros/AddTask_GammaConvCalo_pp.C
- PWGGA/GammaConvBase/AliCaloPhotonCuts.cxx
- NL 01 is now modified for EMCal to be used with new NCell scale in
Correction Framework!
- rearanged and deleted some NCell cuts
- Modified respective train configs for PCMEMC and EMC
> PWGGA/GammaConv: Changed NL 01 case to new default, rearanged NCell efficiency functions

- PWGJE/EMCALJetTasks/UserTasks/AliAnalysisTaskJetCoreEmcal.cxx
- PWGJE/EMCALJetTasks/UserTasks/AliAnalysisTaskJetCoreEmcal.h
- add THnSparse to allow for more entries in response
- 3d histogram of d phi vs pt vs rho shift for systematic studies
- allow to reject a fraction of entries for the response tree (will be useful to fill for QA)
> add histogrammed response, rho shift variations and tree rejection factor

- PWGJE/EMCALJetTasks/CMakeLists.txt
- PWGJE/EMCALJetTasks/PWGJEEMCALJetTasksLinkDef.h
- PWGJE/EMCALJetTasks/UserTasks/AliAnalysisTaskTrackSkim.cxx
- PWGJE/EMCALJetTasks/UserTasks/AliAnalysisTaskTrackSkim.h
- PWGJE/EMCALJetTasks/macros/AddTaskTrackSkim.C
Basic track based skim for offline jet analyses
> Standalone track skim for jet analyses

- PWGGA/GammaConv/AliAnalysisTaskGammaCaloMerged.cxx
- PWGGA/GammaConv/macros/AddTask_GammaConvCalo_pp.C
- fixedw rong train config nr. in Add Task GammaConvCalo
> PWGGA/GammaConv: Fixed range of for loop in Jet setction in merged cluster task

- PWG/EMCAL/EMCALtasks/AliAnalysisTaskEmcalTriggerNormalization.cxx
Extra loop over the mixed triggers (OR of EMCLA or
DCAL trigger) became obsolate once the downscale
factors were added to the standard cache and
therefore treated as normal trigger class, however the
extra loop was not removed, leading to a double
counting of the trigger class when filling the
luminosity counting. Extra loop is removed in order to
prevent the double counting - mixed triggers will
always be treated as standard trigger class.
> Fix double counting of mixed triggers

- PWGGA/GammaConv/macros/AddTask_GammaCalo_pp.C
- PWGGA/GammaConv/macros/AddTask_GammaConvCaloCalibration_MixedMode_pp.C
- PWGGA/GammaConv/macros/AddTask_GammaConvCalo_pp.C
- configs for PCM-EMC and EMC for for exotic studies
- lowB configs for PCM-EMC added to calculate NCell efficiency
> PWGGA/GammaConv: Added configs for exotics and lowB studies

- RUN3/AliAnalysisTaskAO2Dconverter.cxx
This PR goes with https://github.com/AliceO2Group/AliceO2/pull/6567 with the extension in the O2 introduced in https://github.com/AliceO2Group/AliceO2/pull/6753
> Clean FPE hack in AO2D writing

- PWGGA/GammaConv/macros/AddTask_GammaCalo_pp.C
- PWGGA/GammaConv/macros/AddTask_GammaConvCalo_pp.C
- PWGGA/GammaConvBase/AliCaloPhotonCuts.cxx
- seperate parametrizations are needed for low B-field
- for now, only gaussian parametrization implemented
- Added respective train configs for EMCal and PCM-EMCal
> PWGGA/GammaConv: Added new NCell efficiency function for lowB field

- PWGGA/GammaConv/macros/AddTask_GammaCalo_pp.C
- PWGGA/GammaConvBase/AliCaloPhotonCuts.cxx
- seg fault caused by missing MC label of cluster (cluster->GetLabel(0)
returning -999). catched this case with if condition
- Updated train configs without track matching for cell TM studies
> PWGGA/GammaConv: fixed seg. fault in Photon cuts and added train configs

- PWGCF/FEMTOSCOPY/macros/AddTaskFemtoNanoLD.C
o 2 subwagons: w/o (0) and with (1) ITS PID
> Femto L-d: back to full pT, change QA config

- PWGGA/GammaConv/macros/AddTask_GammaConvCalo_pp.C
- configs for INT7, EG2 and EG1 trigger
- using correction based on PCMEMC tagged cluster (gaussian param) on
gamma clusters
> PWGGA/GammaConv: Addded train configs for PCM-EMC with NCell effi

- PWGCF/FLOW/GF/AliAnalysisTaskMeanPtV2Corr.cxx
- PWGCF/FLOW/GF/AliAnalysisTaskMeanPtV2Corr.h
- PWGCF/FLOW/GF/AliCkContainer.cxx
- PWGCF/FLOW/GF/AliCkContainer.h
- PWGCF/FLOW/GF/AliGFW.cxx
- PWGCF/FLOW/GF/AliGFW.h
- PWGCF/FLOW/GF/AliGFWCumulant.cxx
- PWGCF/FLOW/GF/AliGFWCumulant.h
- PWGCF/FLOW/GF/AliGFWCuts.cxx
- PWGCF/FLOW/GF/AliGFWCuts.h
- PWGCF/FLOW/GF/AliGFWFlowContainer.cxx
- PWGCF/FLOW/GF/AliGFWFlowContainer.h
- PWGCF/FLOW/GF/AliGFWWeights.cxx
- PWGCF/FLOW/GF/AliGFWWeights.h
- PWGCF/FLOW/GF/AliProfileBS.cxx
- PWGCF/FLOW/GF/AliProfileBS.h
- PWGCF/FLOW/GF/AliProfileSubset.cxx
- PWGCF/FLOW/GF/AliProfileSubset.h
Also, adding disclaimers to my classes
> MeanPtV2: New efficiencies now do systematics too. 

- PWGHF/vertexingHF/vHFML/AliAnalysisTaskSEDmesonTree.cxx
change the branch name from "Charm2Prong" to "D0toKpi"
> fix branch name of D0toKpi

- PWGGA/GammaConv/macros/AddTask_GammaConvNeutralMesonPiPlPiMiNeutralMeson_CaloMode_pp.C
- PWGGA/GammaConv/macros/AddTask_GammaConvNeutralMesonPiPlPiMiNeutralMeson_MixedMode_pp.C
- PWGGA/GammaConvBase/AliCaloPhotonCuts.cxx
- PWGGA/GammaConvBase/AliConvEventCuts.cxx
- PWGGA/GammaConvBase/AliConvEventCuts.h
- GJ MC anchored to LHC18 with preliminary weights (obtained from local running)
- train configs for omega/etaPrime added with latest EMCal calibrations
> PWGGA/GammaConv: Added GJ MC to Photon/Event Cuts and added train configs

- PWGLF/RESONANCES/macros/mini/AddTaskLStarPP7TeVRunI.C
- PWGLF/RESONANCES/macros/mini/ConfigLStarPP7TeVRunI.C
macros dedicated for Lambda(1520) multiplicity dependent analysis in Run I data.
> AddTAsk and Config commit by vikash

- PWGUD/UPC/nanoAOD/AddTaskCentralTau.C
- PWGUD/UPC/nanoAOD/AliAnalysisTaskCentralTau.cxx
- PWGUD/UPC/nanoAOD/AliAnalysisTaskCentralTau.h
A task to select UPC events with ditau production
> Central tau task

- PWGCF/FEMTOSCOPY/macros/AddTaskFemtoNanoLD.C
o 2 subwagons: d pT range 0.4-2 (0) and 2-4 (1)
> Femto L-d: change pT ranges, both with ITS PID

- PWGDQ/dielectron/macrosLMEE/AddTask_jjung_efficiency.C
fixed a copy error in my personal efficiency AddTask
> DQ:LMee: Update to personal AddTask

- PWGGA/GammaConv/macros/AddTask_GammaCalo_pp.C
- PWGGA/GammaConv/macros/AddTask_GammaConvCalo_pp.C
- configs for EMCal and PCM-EMCal
> PWGGA/GammaConv: Add configs with old and with new fine tuning for consistency check

- PWGCF/Correlations/macros/jcorran/AddTaskJFFlucMapMaster.C
> Corrected period variable

- PWGCF/FEMTOSCOPY/AliFemto/AliFemtoEventReaderNanoAOD.cxx
remocing TPC signal from NanoAOD reader (no information in NanoAOD)
> removing TPC signal from AliFemtoNanoAODReader

- PWGHF/vertexingHF/AliAnalysisTaskSESemileptonicOmegac0KFP.cxx
- PWGHF/vertexingHF/AliAnalysisTaskSESemileptonicOmegac0KFP.h
- PWGHF/vertexingHF/AliRDHFCutsOmegactoeleOmegafromKFP.cxx
- PWGHF/vertexingHF/AliRDHFCutsOmegactoeleOmegafromKFP.h
- PWGHF/vertexingHF/macros/AddTaskOmegac2eleOmegafromKFP.C
Implement the KFParticle technique in the analysis of Omegac0->e+Omega
> New task code for Omegac0->e+Omega with KFP

- PWGUD/UPC/AddTaskJPsi_DG.C
- PWGUD/UPC/AliAnalysisTaskJPsi_DG.cxx
- PWGUD/UPC/AliAnalysisTaskJPsi_DG.h
Macro to analyse central UPC events. For the analysis of incoherent JPsi photoproduction.
> Analysis of UPC events, central JPsi 2018, incoherent

- PWGLF/SPECTRA/MultEvShape/AliMESppColTask.cxx
Comparison for event mixing number of events in pool
> Comparison for event mixing number of events in pool

- PWGCF/FEMTOSCOPY/AliFemto/AliFemtoEventReaderNanoAOD.cxx
removing TPC signal from NanoAOD reader
> AliFemto: removing TPC signal from NanoAOD reader

- PWGHF/vertexingHF/AliAnalysisTaskSESemileptonicOmegac0KFP.cxx
- PWGHF/vertexingHF/AliAnalysisTaskSESemileptonicOmegac0KFP.h
- PWGHF/vertexingHF/AliRDHFCutsOmegactoeleOmegafromKFP.cxx
- PWGHF/vertexingHF/CMakeLists.txt
- PWGHF/vertexingHF/PWGHFvertexingHFLinkDef.h
- PWGHF/vertexingHF/macros/AddTaskOmegac2eleOmegafromKFP.C
Add Omegac0_KFP new class in CMake and also LinkDf.
Add ct_Omegac0, and also remove some cuts which will be replaced by KFP_cuts
> Omegac0_KFP new class optimization

- PWGHF/hfe/AliAnalysisTaskBEpp13TeV.cxx
- PWGHF/hfe/AliAnalysisTaskBEpp13TeV.h
- PWGHF/hfe/macros/AddTaskBEpp13TeV.C
Add beauty analysis codes and macros for pp 13TeV
> Add beauty codes in pp 13TeV

- PWGLF/SPECTRA/ChargedHadrons/MultDepSpec/AliMultDepSpecAnalysisTaskUE.cxx
- PWGLF/SPECTRA/ChargedHadrons/MultDepSpec/AliMultDepSpecAnalysisTaskUE.h
- added histogram leading track pT vs leading track phi
- added histograms mult vs sum pT and total mult vs mean sum pT
- changed binning of leading pT axis
> added histogram lead pT vs lead phi

- PWGHF/hfe/CMakeLists.txt
- PWGHF/hfe/PWGHFhfeLinkDef.h
Add BE_pp13TeV name for train usage
> Add BE_pp13TeV

- PWGGA/CaloTrackCorrelations/macros/ConfigureCaloTrackCorrAnalysis.C
also,  comment out DCal 1/3 SM acceptance cut for 2016
> Add string to open acceptance cuts for isolation

- PWGGA/GammaConv/macros/AddTask_GammaConvDalitzV1_pp.C
> PWGGA/GammaConv/ Systematic Update 13TeV and 5TeV2017

- PWGDQ/dielectron/macrosLMEE/AddTask_jjung_efficiency.C
Added several fixes to load additional inputs
> DQ:LMee: Update to personal AddTask for efficiencies

- PWGUD/UPC/AliAnalysisTaskJPsiMC_DG.cxx
- PWGUD/UPC/AliAnalysisTaskJPsiMC_DG.h
- PWGUD/UPC/AliAnalysisTaskJPsi_DG.cxx
- PWGUD/UPC/AliAnalysisTaskJPsi_DG.h
> JPsi_DG: store vertex info, JPsiMC_DG: 2D pt histogram

- PWGCF/Correlations/DPhi/AliAnalysisTaskSEpPbCorrelationsJetV2Kine.cxx
- PWGCF/Correlations/DPhi/AliAnalysisTaskSEpPbCorrelationsJetV2Kine.h
- PWGCF/Correlations/macros/pPbCorrelations/AddTaskSEpPbCorrelationsJetV2Kine.C
Dear all,
Here is an update for code of jet v2, please approve it.
Thanks!
Siyu
> Updates for jet v2

- PWG/FLOW/Tasks/AliAnalysisTaskGammaDeltaPID.cxx
- PWG/FLOW/Tasks/AliAnalysisTaskGammaDeltaPID.h
- PWG/FLOW/Tasks/CMakeLists.txt
- PWG/FLOW/Tasks/PWGflowTasksLinkDef.h
- PWGCF/FLOW/macros/AddTaskGammaDeltaPID.C
Added Task For CME(pid) and Lambda-x correlation analysis
> Added Task For CME(pid) and Lambda-x correlation analysis

- RUN3/AliAnalysisTaskAO2Dconverter.cxx
- RUN3/AliAnalysisTaskAO2Dconverter.h
RUN3 converter modified. MIDBitMap and MIDBoards added to the tFwdTrack tree
> MID words: bitmap and local boards

- RUN3/AliAnalysisTaskAO2Dconverter.cxx
- RUN3/AliAnalysisTaskAO2Dconverter.h
- Updated calotrigger table
- Adapt EMCAL trigger table to STU format in run3
> Updated calotrigger table amd implement for EMCAL

- PWGCF/FEMTOSCOPY/macros/AddTaskFemtoNanoLD.C
o 2 subwagons: nSigma = 2.5 (0) and 2.0 (1)
o Both with deuteron pT range: 0.4 - 2.0
> Femto L-d: change nSigma ranges for deuteron PID

- PWG/FLOW/Tasks/AliAnalysisTaskGammaDeltaPID.cxx
- PWG/FLOW/Tasks/AliAnalysisTaskGammaDeltaPID.h
- PWGCF/FLOW/macros/AddTaskGammaDeltaPID.C
Fix class name in AddTask and added q-vector for ESE
> Fix class name in AddTask and added q-vector for ESE

- PWGLF/RESONANCES/macros/mini/AddTaskGlueball.C
- PWGLF/RESONANCES/macros/mini/ConfigGlueball.C
Add AddTaskGlueball.C and ConfigGlueball.C macros in PWGLF/RESONANCE/macros/mini. The macros look for glueball signal in KK pair.
> Add glueball hunting task in PWGLF/RESONANCE

- PWGGA/GammaConv/macros/AddTask_GammaConvCalo_pp.C
- PWGGA/GammaConv/macros/AddTask_GammaConvNeutralMesonPiPlPiMiNeutralMeson_CaloMode_pp.C
- PWGGA/GammaConv/macros/AddTask_GammaConvNeutralMesonPiPlPiMiNeutralMeson_MixedMode_pp.C
- Added PCM-EMC configs with different alpha cuts for smearing study
> PWGGA/GammaConv: Added configs for Omega analysis with new NCell efficiency

- PWGHF/hfe/AliAnalysisTaskBEpp13TeV.cxx
- PWGHF/hfe/AliAnalysisTaskBEpp13TeV.h
> implement MC part

- RUN3/AliAnalysisTaskAO2Dconverter.cxx
- RUN3/AliAnalysisTaskAO2Dconverter.h
To sync changes by https://github.com/AliceO2Group/AliceO2/pull/6924
> Update RUN3 converter according to O2 fwdtrack AOD table

- PWGGA/GammaConv/macros/AddTask_GammaConvV1_pp.C
- configs for smearing studies, triggers needed for high pT enhancment
> PWGGA/GammaConv: Added configs for PCM for various triggers

- PWGGA/GammaConv/AliAnalysisTaskGammaConvV1.cxx
- PWGGA/GammaConv/macros/AddTask_GammaConvV1_pp.C
- Filling smearing calib histo for each photon and not only for one
> PWGGA/GammaConv: Added configs for smearing study with alpha cut

- RUN3/AliAnalysisTaskAO2Dconverter.cxx
- RUN3/AliAnalysisTaskAO2Dconverter.h
- ensure 1:1 compatibility with the trackTime and tofSignal
> Remove tofSignal in AO2D converter

- PWGMM/UE/UeKNO/AliAnalysisTaskChargedVsRT.cxx
Two lines were added to the program in order to avoid memory leak.
> Corrections related with memory leak

- PWGGA/GammaConv/macros/AddTask_GammaConvDalitzV1_pp.C
New cuts for V0M and SPD slices in multiplicity for 5 TeV and 13TeV (Nominal and low magnetic field)
> PWGGA/GammaConv/macros/ V0M and SPD multiplicity

- PWGGA/GammaConv/AliAnalysisTaskGammaCaloMerged.cxx
- PWGGA/GammaConv/AliAnalysisTaskGammaCaloMerged.h
- PWGGA/GammaConv/macros/AddTask_GammaCaloMerged_pp.C
- PWGGA/GammaConv/macros/AddTask_GammaCalo_pp.C
- PWGGA/GammaConv/macros/AddTask_GammaConvDalitzV1_pp.C
- PWGGA/GammaConvBase/AliConversionMesonCuts.cxx
- PWGGA/GammaConvBase/AliConversionMesonCuts.h
- New configs for mult dependent analysis for combined 13 TeV analysis
- Moved isParticleInJet function to Meson cuts such that it can be used from every task
> PWGGA/GammaConv: Modified mult dependen configs for 13 TeV, modified inJet function

- PWGGA/GammaConv/macros/AddTask_GammaConvV1_pp.C
- configs include INT7 and high mult triggers
> PWGGA/GammaConv: PCM: Added mult dependent configs for pp13 TeV

- PWGLF/SPECTRA/MultEvShape/AddMEStender.C
- PWGLF/SPECTRA/MultEvShape/AliMEStender.cxx
- PWGLF/SPECTRA/MultEvShape/AliMEStender.h
Second parameter of AddMEStender:
configuration 0 => 7 TeV
configuration 1 => 13 TeV (to be checked and expanded)
> Added a parameter for tender configuration selection

- PWGGA/GammaConv/macros/AddTask_GammaConvV1_pp.C
- PWGGA/GammaConvBase/AliConversionMesonCuts.cxx
- PWGGA/GammaConvBase/AliConversionMesonCuts.h
- based on difference between data and MC from Gaussian+Exp fit
> PWGGA/GammaConv: Added new PCM photon smearing

- PWG/FLOW/Tasks/AliAnalysisTaskGammaDeltaPID.cxx
- PWG/FLOW/Tasks/AliAnalysisTaskGammaDeltaPID.h
- PWGCF/FLOW/macros/AddTaskGammaDeltaPID.C
Add V0 Gain Correction and TPC<Q> recentering
> Add V0 Gain Correction and TPC<Q> recentering

- PWGLF/NUCLEX/CMakeLists.txt
- PWGLF/NUCLEX/Nuclei/Nuclei_UE/AliAnalysisTaskDeuteronCoalescence.cxx
- PWGLF/NUCLEX/Nuclei/Nuclei_UE/AliAnalysisTaskDeuteronCoalescence.h
- PWGLF/NUCLEX/Nuclei/Nuclei_UE/addTaskDeuteronsCoalescence.C
- PWGLF/NUCLEX/PWGLFnuclexLinkDef.h
Simulation of deuteron formation by coalescence in pp collisions.
> Deuteron coalescence simulation in pp collisions

- PWGGA/GammaConv/macros/AddTask_GammaConvCalo_pp.C
- PWGGA/GammaConv/macros/AddTask_GammaConvV1_pp.C
- PWGGA/GammaConvBase/AliConversionMesonCuts.cxx
- Added protection that sigma for gaussian component does not get below 0
> PWGGA/GammaConv: Added configs for PCM smearing

- PWGHF/hfe/AliAnalysisTaskBEpp13TeV.cxx
- PWGHF/hfe/AliAnalysisTaskBEpp13TeV.h
- PWGHF/hfe/macros/AddTaskBEpp13TeV.C
> Add MC correction part

- PWGHF/vertexingHF/AliAnalysisTaskSEXicZero2XiPifromKFP.cxx
- PWGHF/vertexingHF/AliAnalysisTaskSEXicZero2XiPifromKFP.h
Add a flag branch in the output tree for unlike- and like-sign pairs
> Add a flag branch in the output tree for unlike- and like-sign pairs

- PWG/FLOW/Tasks/AliAnalysisTaskGammaDeltaPID.cxx
- PWG/FLOW/Tasks/AliAnalysisTaskGammaDeltaPID.h
- PWGCF/FLOW/macros/AddTaskGammaDeltaPID.C
Added V0 <Q> recentering in place
> Add V0 <Q> recentering in place

- PWG/EMCAL/EMCALtasks/AliAnalysisTaskEmcalTriggerNormalization.cxx
- PWG/EMCAL/EMCALtasks/AliAnalysisTaskEmcalTriggerNormalization.h
Those can be used in the post processing to
select the method for the dataset and the
reference cross section.
> Add histograms for year and collision system

- PWGHF/vertexingHF/AliAnalysisTaskSEXic0Semileptonic.cxx
- PWGHF/vertexingHF/AliAnalysisTaskSEXic0Semileptonic.h
- PWGHF/vertexingHF/macros/AddTaskXic0Semileptonic.C
Modify the pile-up rejection for HM analysis
> Modify the pile-up rejection for HM analysis

- PWGLF/SPECTRA/PiKaPr/TPCTOFCascades/AliAnalysisPIDCascade.h
- PWGLF/SPECTRA/PiKaPr/TPCTOFCascades/AliAnalysisPIDCascadeEvent.h
- PWGLF/SPECTRA/PiKaPr/TPCTOFCascades/AliAnalysisPIDCascadeParticle.h
- PWGLF/SPECTRA/PiKaPr/TPCTOFCascades/AliAnalysisPIDCascadeTrack.h
- PWGLF/SPECTRA/PiKaPr/TPCTOFCascades/AliAnalysisTaskTPCTOFCascade.cxx
- PWGLF/SPECTRA/PiKaPr/TPCTOFCascades/AliAnalysisTaskTPCTOFCascade.h
Implementation of raw V0A/V0C signals, to measure the asymmetry at forward/backward rapidity
> New Modification of Lund trees

- PWGLF/NUCLEX/Hypernuclei/Hyp2Body/AliAnalysisTaskHypTritEventTree.cxx
Added MC settings for HSE for 2016 p-Pb at 8.16 TeV
> Added MC settings for HSE

- PWGLF/SPECTRA/PiKaPr/TPCTOFCascades/AliAnalysisPIDCascadeEvent.cxx
- PWGLF/SPECTRA/PiKaPr/TPCTOFCascades/AliAnalysisPIDCascadeEvent.h
- PWGLF/SPECTRA/PiKaPr/TPCTOFCascades/AliAnalysisTaskTPCTOFCascade.cxx
The local train test is now able to compile.
> Bugfix to Cascade Trees, now with V0A/V0C selection

- PWGGA/GammaConv/macros/AddTask_GammaCalo_pp.C
- PWGGA/GammaConvBase/AliCaloPhotonCuts.cxx
- Additionally changed default rotatino background to mode s, as it
describes the background for the eta better due to better description of
the EMCal geometry
> PWGGA/GammaConv: Added M02 dependent cuts for 13TeV

- PWGJE/EMCALJetTasks/UserTasks/AliAnalysisTaskEmcalJetEnergyFlow.cxx
Fix the missing centrality definition (without typos this time) for the hJetDeltaPt_R histogram
> Minor fix of the histogram name of DeltaPt to include centrality

- PWGHF/vertexingHF/AliAnalysisTaskSESemileptonicOmegac0KFP.cxx
- PWGHF/vertexingHF/AliRDHFCutsOmegactoeleOmegafromKFP.cxx
To check the KFP performance on the resolution of Omega mass
> Add new variables in fTree_Omegac0

- PWG/FLOW/Tasks/AliAnalysisTaskCMWESE.cxx
- PWG/FLOW/Tasks/AliAnalysisTaskCMWESE.h
- PWGCF/FLOW/macros/AddTaskCMWESE.C
CMW ESE with 3-order estimation
> Q3ESEforCMW

- PWGJE/EMCALJetTasks/UserTasks/AliAnalysisTaskIDFragmentationFunction.h
- PWGJE/macros/AddTaskPID.C
Update ClassImp for IdFragmentation function, add parameter doEfficiency for AddTaskPID
> Multi-Template Fit: Small updates

- PWGGA/EMCALTasks/AliAnalysisTaskGammaHadron.cxx
- PWGGA/EMCALTasks/AliAnalysisTaskGammaHadron.h
Added more controls for event mixing settings, renamed variable
Disabled lengthy event pool printout except in debug mode
> Event mixing controls and reduced printout

- PWGCF/Correlations/JCORRAN/Base/AliAnalysisTaskHOCFA.cxx
- PWGCF/Correlations/JCORRAN/Base/AliAnalysisTaskHOCFA.h
- PWGCF/Correlations/JCORRAN/Base/AliJHOCFATask.cxx
- PWGCF/Correlations/JCORRAN/Base/AliJHOCFATask.h
- PWGCF/Correlations/macros/jcorran/AddTaskJHOCFAMaster.C
- PWGCF/Correlations/macros/jcorran/AddTaskJHOCFAMaster10h.C
> [PWGCF] Update for the error propagation terms

- PWGHF/vertexingHF/AliAnalysisTaskSEXicPlusToXi2PifromKFP.cxx
The values of pt of pion from cascade and mass of Omega are not filled. Now fixed.
> The values of pt of pion from cascade and mass of Omega are not filled. Now fixed.

- PWGJE/EMCALJetTasks/CMakeLists.txt
- PWGJE/EMCALJetTasks/PWGJEEMCALJetTasksLinkDef.h
- PWGJE/EMCALJetTasks/UserTasks/AliAnalysisTaskJetExtractor.cxx
- PWGJE/EMCALJetTasks/UserTasks/AliAnalysisTaskJetExtractor.h
- PWGJE/EMCALJetTasks/UserTasks/AliAnalysisTaskJetQnVectors.cxx
- PWGJE/EMCALJetTasks/UserTasks/AliAnalysisTaskJetQnVectors.h
- PWGJE/EMCALJetTasks/UserTasks/AliJEQnVectorHandler.cxx
- PWGJE/EMCALJetTasks/UserTasks/AliJEQnVectorHandler.h
- PWGJE/EMCALJetTasks/macros/AddTaskJEQnVectors.C
Addition of AliJEQnVectorHandler.cxx, AliAnalysisTaskJetQnVectors.cxx, and AddTaskJEQnVectors.C to calculate Qn vectors in jet events. Modification of AliAnalysisTaskJetExtractor.cxx to access q2 vectors.
> Creation of tasks for using event-shape engineering with jets

- PWGCF/Correlations/KaonCorrelations/AliAnalysisTaskKaon2PC.cxx
- PWGCF/Correlations/KaonCorrelations/AliAnalysisTaskKaon2PC.h
Updated the code with Eta histograms (11 hosts)
> Eta and Phi Histograms 

- PWGUD/UPC/AddTaskUpcPhi0.C
- PWGUD/UPC/AliAnalysisTaskUpcPhi0.cxx
- PWGUD/UPC/AliAnalysisTaskUpcPhi0.h
new task to be run on LEGO train system
> add new Task to analyze K+K- in UPC

- PWGCF/Correlations/JCORRAN/Base/AliAnalysisTaskHOCFA.cxx
This bug is present only for macOS users. On Ubuntu it is fine. Maybe it would be better to include tests also for macOS, as for O2.
> Fix bug that braks compilation on macOS

- PWGUD/UPC/CMakeLists.txt
- PWGUD/UPC/PWGUDupcLinkDef.h
add AliAnalysisTaskUpcPhi0 to the library
> add AliAnalysisTaskUpcPhi0 to the library

- PWG/FLOW/Tasks/AliAnalysisTaskEPCalib.cxx
- PWG/FLOW/Tasks/AliAnalysisTaskEPCalib.h
V0 Calib for LHC11h_2 with 2nd-order
> AddV0Calibfor11h

- PWGCF/FLOW/GF/AliAnalysisTaskFlowPPTask.cxx
- PWGCF/FLOW/GF/AliAnalysisTaskFlowPPTask.h
- PWGCF/FLOW/GF/CMakeLists.txt
- PWGCF/FLOW/GF/PWGCFFLOWGFLinkDef.h
- PWGCF/FLOW/macros/AddFlowPPTask.C
Calculate Vn{m} and SC(m,n) in 13TeV p-p
> [PAG-Flow]Add pp flow analysis code

- PWGJE/EMCALJetTasks/Tracks/AliAnalysisTaskEmcalJetEnergyScale.cxx
- PWGJE/EMCALJetTasks/Tracks/AliAnalysisTaskEmcalJetEnergySpectrum.cxx
- PWGJE/EMCALJetTasks/macros/AddTaskEmcalJetEnergySpectrumBkgSub.C
The analysis code was crushing because some objects were not found.
> Fixing a problem with objects not found

- PWGLF/RESONANCES/AliRsnMiniAnalysisTask.cxx
This commit updates the spherocity calculation for AOD datasets. The track cuts for spherocity calculation are now similar for both AOD and ESD datasets.
> Update in spherocity calculation for AOD datasets

- PWGCF/FEMTOSCOPY/AliFemtoUser/AliFemtoCorrFctnpdtHe3.cxx
- PWGCF/FEMTOSCOPY/AliFemtoUser/AliFemtoCorrFctnpdtHe3.h
- PWGCF/FEMTOSCOPY/AliFemtoUser/AliFemtoTrackCutPdtHe3.cxx
- PWGCF/FEMTOSCOPY/AliFemtoUser/CMakeLists.txt
- PWGCF/FEMTOSCOPY/AliFemtoUser/PWGCFfemtoscopyUserLinkDef.h
in order to study proton pT dependent, create a new class to record it.
> dowang pdtHe3 cf(k*) vs proton pt

- PWGLF/RESONANCES/macros/mini/AddTaskKStarPlusMinusRun2sp_bin_new_AOD.C
- PWGLF/RESONANCES/macros/mini/ConfigKStarPlusMinusRun2sp_bin_new_AOD.C
Added Features:
(1). Root6 compatible
(2). Compatible with AOD datasets
> Spherocity analysis of charged kstar using AOD datasets

- PWGJE/EMCALJetTasks/CMakeLists.txt
- PWGJE/EMCALJetTasks/FlowVectorCorrections/AliAnalysisTaskFlowVectorCorrectionsPWGJE.cxx
- PWGJE/EMCALJetTasks/FlowVectorCorrections/AliAnalysisTaskFlowVectorCorrectionsPWGJE.h
- PWGJE/EMCALJetTasks/FlowVectorCorrections/macros/AddTaskFlowQnVectorCorrectionsNewDetConfigPWGJE.C
- PWGJE/EMCALJetTasks/FlowVectorCorrections/macros/AddTaskFlowQnVectorCorrectionsToLegoTrainNewDetConfigPWGJE.C
- PWGJE/EMCALJetTasks/FlowVectorCorrections/macros/loadRunOptionsPWGJE.C
- PWGJE/EMCALJetTasks/FlowVectorCorrections/macros/runAnalysis.C
- PWGJE/EMCALJetTasks/FlowVectorCorrections/macros/runAnalysis.H
- PWGJE/EMCALJetTasks/FlowVectorCorrections/macros/runAnalysisPWGJE.H
- PWGJE/EMCALJetTasks/FlowVectorCorrections/macros/runoptionsPWGJE.txt
- PWGJE/EMCALJetTasks/PWGJEEMCALJetTasksLinkDef.h
This pull request asks to add the AliAnalysisTaskFlowVectorCorrectionsPWGJE class to perform event plane calibration for jet analyses (e.g. Jet vn measurements) with the standard event selections that are implemented in the AliEventCuts class
> First commit of AliAnalysisTaskFlowVectorCorrectionsPWGJE class 

- PWG/FLOW/Tasks/AliAnalysisTaskCMWESE.cxx
- PWG/FLOW/Tasks/AliAnalysisTaskCMWESE.h
- PWGCF/FLOW/macros/AddTaskCMWESE.C
This code adds the process for extracting the slope between v24 Vs. Ach, as well as the differential v22 spectrum as QA.
Also adds information of LHC11h for the same work.
> Add v24 slope and diff v22 vs pt to CMWESE code

- PWGHF/vertexingHF/vHFML/AliAnalysisTaskSEDmesonTree.cxx
> Increase number of bins of centrality axis

- PWGCF/FEMTOSCOPY/macros/AddTaskProtonProtonKaons.C
I added the Sphericity Cuts in my AddTask for the three-body proton-proton-kaon analysis
> Added Sphericity Cuts in AddTaskProtonProtonKaons.C

- PWGCF/FEMTOSCOPY/AliFemtoUser/AliFemtoCorrFctnpdtHe3.cxx
- PWGCF/FEMTOSCOPY/AliFemtoUser/AliFemtoTrackCutPdtHe3.cxx
- PWGCF/FEMTOSCOPY/AliFemtoUser/AliFemtoTrackCutPdtHe3.h
this function is to control where should be TPC+TOF & delete cout in AliFemtoCorrFctnpdtHe3.cxx
> dowang add control function and delete cout

- PWGHF/vertexingHF/AliAnalysisTaskSESemileptonicOmegac0KFP.cxx
- PWGHF/vertexingHF/AliRDHFCutsOmegactoeleOmegafromAODtracks.cxx
- PWGHF/vertexingHF/AliRDHFCutsOmegactoeleOmegafromKFP.cxx
- PWGHF/vertexingHF/macros/AddTaskOmegac2eleOmegafromKFP.C
1) Apple to apple for the two Omegac0 classes - - to check the compatibility of 2 results  
2) Add flag for fTree_Electron
3) Add variables in fTree_Omegac0 - - to check the KFParticle performance on the cascade
> Apple to apple for two Omegac0 classes

- PWGHF/vertexingHF/AliAnalysisTaskSEXicPlusToXi2PifromKFP.cxx
- PWGHF/vertexingHF/AliAnalysisTaskSEXicPlusToXi2PifromKFP.h
- PWGHF/vertexingHF/macros/AddTaskXicPlusToXi2PiFromKFParticle.C
Add QA tree to study the resolution of PV and SV
> Add QA tree to study the resolution of PV and SV

- PWGJE/EMCALJetTasks/UserTasks/AliAnalysisTaskIDFragmentationFunction.cxx
- PWGJE/EMCALJetTasks/UserTasks/AliAnalysisTaskIDFragmentationFunction.h
- PWGJE/macros/AddTaskIDFragmentationFunction.C
- PWGJE/macros/AddTaskPID.C
- PWGJE/macros/PID/AliTPCPIDmathFit.cxx
- PWGJE/macros/PID/PID.C
- PWGJE/macros/PID/runPID.C
- PWGJE/macros/PID/runPIDiterative.C
- PWGJE/macros/PID/runPIDiterative.sh
MTF: Update add macros
MTF: Use correct indentation
MTF: Adding some helper tasks
MTF: Fix PID macros for ROOT6
MTF: Fix call of incrementEventCounter after pile-up check
> General improvements for analysisTask and subsequent analysis

- PWGHF/vertexingHF/AliAnalysisTaskSEXicPlusToXi2PifromKFP.cxx
- PWGHF/vertexingHF/AliAnalysisTaskSEXicPlusToXi2PifromKFP.h
Add unique event ID for both Data and MC
> Add unique event ID for both Data and MC

- PWGCF/FEMTOSCOPY/macros/AddTaskProtonProtonKaons.C
I added the cuts of the Kaons by Ramona and Oton in my AddTaskProtonProtonKaons.C
> Add cuts by Ramona and Oton

- PWGHF/vertexingHF/vHFML/AliAnalysisTaskSECharmHadronMLSelector.cxx
Fixed bug for future runs on PbPb with Preselect enabled (overlooked this in previous PR)
> PWGHF: Fix for Dstar structure

- PWGJE/EMCALJetTasks/AliAnalysisTaskRhoPerpCone.cxx
- PWGJE/EMCALJetTasks/AliAnalysisTaskRhoPerpCone.h
- PWGJE/EMCALJetTasks/CMakeLists.txt
- PWGJE/EMCALJetTasks/PWGJEEMCALJetTasksLinkDef.h
- PWGJE/EMCALJetTasks/macros/AddTaskRhoPerpCone.C
We implemented a new code for subtraction the background from jets using the perpendicular cone method.
> Background subtraction using the perp cone method

- PWGCF/FEMTOSCOPY/FemtoDream/AliAnalysisTaskCharmingFemto.cxx
- PWGCF/FEMTOSCOPY/FemtoDream/AliAnalysisTaskCharmingFemto.h
- PWGCF/FEMTOSCOPY/FemtoDream/AliFemtoDreamBasePart.cxx
- PWGCF/FEMTOSCOPY/macros/AddTaskAnyCharmingFemto.C
> PWGCF: Include Dstar in CharmingFemto task

- PWGJE/EMCALJetTasks/AliAnalysisTaskRhoPerpCone.cxx
- PWGJE/EMCALJetTasks/Tracks/AliAnalysisTaskEmcalJetEnergySpectrum.cxx
Applying track cuts automatically when selecting them using "GetNextAcceptParticle()".
> Applying cuts automatically when selecting tracks

- PWGLF/RESONANCES/AliRsnEventCuts.h
- PWGLF/RESONANCES/macros/mini/AddTaskSigmaStarpp5TeV.C
- PWGLF/RESONANCES/macros/mini/ConfigSigmaStarpp5TeV.C
include the event cuts for pp Run 2 to AliRsnEvent cuts+AddTask and config file for sigma star in pp at 5 TeV
> include the event cuts for pp Run 2 to AliRsnEvent cuts+AddTask and config file for sigma star in pp at 5 TeV

- PWGJE/EMCALJetTasks/Tracks/AliAnalysisTaskEmcalJetEnergyScale.cxx
- Add histograms for jet finding efficiency and purity
as well as particle level spectrum for closure and non-
closure sample
- Apply spliting of closure and non-closure sample at
event and not at jet level
> Add histograms for closure test

- PWGHF/vertexingHF/AliAnalysisTaskSEXicPlusToXi2PifromKFP.cxx
- PWGHF/vertexingHF/AliAnalysisTaskSEXicPlusToXi2PifromKFP.h
Split MC background sources (-2: Xic+ -> Xi*0pi+ -> Xi-pi+pi+); Add pointing angle and chi2_topo point back to recalculated primary vertex
> Split MC background sources (-2: Xic+ -> Xi*0pi+ -> Xi-pi+pi+); Add pointing angle and chi2_topo point back to recalculated primary vertex

- PWGHF/vertexingHF/vHFML/AliAnalysisTaskSECharmHadronMLSelector.cxx
- Fixed a bug that I introduced when cleaning before opening PR #18988 (used before defined) 
- Added @fgrosa PbPb fix also for this task
> PWGHF: Fix issue Dstar MLSelector

- PWGHF/hfe/AliAnalysisTaskHFEBESpectraEMC.cxx
- PWGHF/hfe/AliAnalysisTaskHFEBESpectraEMC.h
Add function form for TPC-EMCal track matching
> "Adding functional form for track matching"

- PWGCF/FLOW/GF/AliAnalysisTaskNonlinearFlow.cxx
- PWGCF/FLOW/GF/AliAnalysisTaskNonlinearFlow.h
+ Corrected / Uncorrected nTracks
+ Pileup cuts
> [PAG-Flow] Add new features 

- PWGDQ/dielectron/core/AliAnalysisTaskElectronEfficiencyV2.cxx
- PWGDQ/dielectron/core/AliAnalysisTaskElectronEfficiencyV2.h
add protection for not calling oob pileup for rec.
> PWGDQ/LMEE: add protection for not calling oob pileup for rec.

- PWGDQ/dielectron/macrosLMEE/AddTask_dsekihat_lowmass_PbPb.C
- PWGDQ/dielectron/macrosLMEE/Config_dsekihat_lowmass_PbPb.C
> PWGDQ/LMEE: update of AddTask.C

- PWGLF/RESONANCES/PostProcessing/Xi1530/AliAnalysisTaskXi1530.cxx
- PWGLF/RESONANCES/PostProcessing/Xi1530/AliAnalysisTaskXi1530.h
> revert changes

- PWGLF/STRANGENESS/Cascades/Run2/AliAnalysisTaskStrangenessVsMultVsEffEnergyAODMCRun2.cxx
- PWGLF/STRANGENESS/Cascades/Run2/AliAnalysisTaskStrangenessVsMultVsEffEnergyAODMCRun2.h
- PWGLF/STRANGENESS/Cascades/Run2/AliAnalysisTaskStrangenessVsMultVsEffEnergyAODRun2.cxx
- PWGLF/STRANGENESS/Cascades/Run2/AliAnalysisTaskStrangenessVsMultVsEffEnergyAODRun2.h
- PWGLF/STRANGENESS/Cascades/Run2/macros/AddTaskStrangenessVsMultVsEffEnergyAODMCRun2.C
- PWGLF/STRANGENESS/Cascades/Run2/macros/AddTaskStrangenessVsMultVsEffEnergyAODRun2.C
> Add AOD tasks for effective energy analysis

- PWG/FLOW/Tasks/AliAnalysisTaskCMWESE.cxx
- PWG/FLOW/Tasks/AliAnalysisTaskCMWESE.h
- PWGCF/FLOW/macros/AddTaskCMWESE.C
This version aims to prompt the code to solve the following problems:
1, Add more switches to separate code into different parts containing different functions like : Int Cov with ESE, V24 Vs. Ach, Diff V22, etc.
2, Reduce output files size for V24 Vs. Ach
3, Prompt some input parameters
> Add some switches, prompt code

- PWGCF/Correlations/JCORRAN/Pro/AliAnalysisTaskRidge.cxx
- PWGCF/Correlations/JCORRAN/Pro/AliAnalysisTaskRidge.h
> [PWGCF] update for bin

- PWGHF/vertexingHF/AliAnalysisTaskSESemileptonicOmegac0KFP.cxx
- PWGHF/vertexingHF/AliAnalysisTaskSESemileptonicOmegac0KFP.h
1) Add new variables in fTree_Omegac0
2) One typo is fixed in the MatchToMCOmegac0 function
3) Condition changes to store the WS information also
> One more check about KFP QA.   One typo is fixed

- PWGDQ/dielectron/core/AliAnalysisTaskElectronEfficiencyV2.cxx
- PWGDQ/dielectron/core/AliAnalysisTaskElectronEfficiencyV2.h
fix for pT weighting based on mother particle
> PWGDQ/LMEE: fix for pT weighting based on mother particle

- PWGLF/RESONANCES/macros/mini/AddTaskSigmaStarpp5TeV.C
correct path of the config file for sigma star pp at 5 TeV analysis
> correct path of the config file

- PWGDQ/dielectron/core/AliDielectronMC.cxx
add MC signal for heavier mesons
> PWGDQ/LMEE: add MC signal for heavier mesons

- PWGDQ/dielectron/core/AliAnalysisTaskElectronEfficiencyV2.cxx
- PWGDQ/dielectron/core/AliAnalysisTaskElectronEfficiencyV2.h
This reverts commit 96d1c677a7d4ca560dab6db283299799cd972798.
> Revert "PWGDQ/LMEE: fix for pT weighting based on mother particle"

- PWG/FLOW/Tasks/AliAnalysisTaskGammaDeltaPID.cxx
- PWG/FLOW/Tasks/AliAnalysisTaskGammaDeltaPID.h
- PWGCF/FLOW/macros/AddTaskLambdaPIDCorr.C
1. Fixed bugs: Aligned iterators
2. Add QAs for PID Flow in lambda's part
> Add PID flow for QA and fix bugs of removing autoCorrelation for Lambda's part.

- PWGLF/RESONANCES/PostProcessing/Xi1530/AliAnalysisTaskXi1530PbPb.cxx
> Update QA Histo

- PWGCF/FLOW/GF/AliAnalysisTaskNonlinearFlow.cxx
> [PAG-Flow] modify TPC pileup cuts

- PWGCF/Correlations/JCORRAN/Pro/AliAnalysisTaskRidge.cxx
> [PWGCF] bug fix

- PWGDQ/dielectron/core/AliAnalysisTaskElectronEfficiencyV2.cxx
- PWGDQ/dielectron/core/AliAnalysisTaskElectronEfficiencyV2.h
update on ElectronEfficiencyV2 for oob pileup
> PWGDQ/LMEE: update on ElectronEfficiencyV2 for oob pileup

- PWGDQ/dielectron/macrosLMEE/AddTask_rbailhac_ElectronEfficiencyV2_PbPb.C
Remove the ID in the add macro
> Remove the ID in the add macro

- PWGDQ/dielectron/macrosLMEE/AddTask_dsekihat_ElectronEfficiencyV2_PbPb.C
> PWGDQ/LMEE: update AddTask.C

- PWG/FLOW/Tasks/AliAnalysisTaskCMWESEsyst.cxx
- PWG/FLOW/Tasks/AliAnalysisTaskCMWESEsyst.h
- PWG/FLOW/Tasks/CMakeLists.txt
- PWG/FLOW/Tasks/PWGflowTasksLinkDef.h
- PWGCF/FLOW/macros/AddTaskCMWESEsyst.C
Since adding v24 into CMW ESE code has met many errors, even cannot pass lego train test. We reduce the code only to calculate the CMWESE effect for 11h and 10h. 
Systematic loop produced in code file labeled by "syst".
> Code only for CMWESE

- PWGCF/FEMTOSCOPY/macros/Train/KM/testgithub.txt
> Konstantin test o1 dec 2021 ++

- PWG/EMCAL/EMCALtasks/AliEmcalCorrectionClusterPositionCorrection.cxx
- Remove condition that task can only run on MC events
> PWG/EMCal: fix in new cluster position correction task

- PWGCF/Correlations/JCORRAN/Pro/AliAnalysisTaskRidge.cxx
- PWGCF/Correlations/JCORRAN/Pro/AliAnalysisTaskRidge.h
> [PWGCF] updates for subsample

- PWGDQ/dielectron/core/AliAnalysisTaskTagAndProbe.cxx
- PWGDQ/dielectron/core/AliAnalysisTaskTagAndProbe.h
- PWGDQ/dielectron/macrosLMEE/AddTask_dsekihat_TAP_PbPb.C
- PWGDQ/dielectron/macrosLMEE/Config_dsekihat_TAP_PbPb.C
> PWGDQ/LMEE: update on TAP

- PWGGA/CaloTrackCorrelations/AliAnaParticleHadronCorrelation.cxx
- PWGGA/CaloTrackCorrelations/AliAnaParticleHadronCorrelation.h
- PWGGA/CaloTrackCorrelations/macros/ConfigureCaloTrackCorrAnalysis.C
- Add option for pt dependent M02 cut in correlation analysis, 
- Filter out MC tracks/clusters in mixed event in case of embedding
> [PWGGA/CaloTrackCorr] Pt dep M02 cut and embedded tracks filter on mixed event

- PWGCF/Correlations/JCORRAN/Pro/AliAnalysisTaskRidge.cxx
> [PWGCF] updates for subsampling

- PWG/FLOW/Tasks/AliAnalysisTaskCMWESEsyst.cxx
- PWG/FLOW/Tasks/AliAnalysisTaskCMWESEsyst.h
- PWGCF/FLOW/macros/AddTaskCMWESEsyst.C
Prompt the syst estimation in this code.
Only for changed sources, not including default calculation anymore.
> syst Source estimation for CMWESE

- PWGLF/STRANGENESS/Cascades/Run2/AliAnalysisTaskStrangenessVsMultVsEffEnergyAODRun2.cxx
> Fill Event Tree after Nch extraction

- PWGCF/FEMTOSCOPY/macros/AddTaskFemtoNanoLD.C
o Final cuts for (anti)deuterons, e.g. 0.5<pT<1.4, no ITS PID
> Femto L-d: final (anti)deuteron cuts

- PWGCF/Correlations/macros/jcorran/AddTaskRidge.C
> [PWGCF] update efficiency

- PWGDQ/dielectron/core/AliAnalysisTaskTagAndProbe.cxx
- PWGDQ/dielectron/core/AliAnalysisTaskTagAndProbe.h
- PWGDQ/dielectron/macrosLMEE/AddTask_dsekihat_TAP_PbPb.C
- PWGDQ/dielectron/macrosLMEE/Config_dsekihat_TAP_PbPb.C
> PWGDQ/LMEE: update TAP and AddTask.C

- PWGHF/vertexingHF/AliAnalysisTaskSEXicPlusToXi2PifromKFP.cxx
- PWGHF/vertexingHF/AliAnalysisTaskSEXicPlusToXi2PifromKFP.h
Add diamond constraint for PV; test PV recalculation without adding Xic+ into PV; add number of contributors in the tree
> Add diamond constraint for PV; test PV recalculation without adding Xic+ into PV; add number of contributors in the tree

- PWGMM/UE/UeKNO/AliAnalysisTaskChargedVsRT.cxx
With this correction it is available to run with real data
> Correction to run with data

- PWGLF/STRANGENESS/Cascades/Run2/AliAnalysisTaskStrangenessVsMultVsEffEnergyAODRun2.cxx
> Fix access to momentum from inner TPC wall (for protons)

- PWG/EMCAL/EMCALtasks/AliEmcalFastOrMonitorTask.cxx
PWG/EMCAL/EMCALtasks - Adapting AliEmcalFastOrMonitorTask.cxx to instead use 1D bad channel maps
> PWG/EMCAL/EMCALtasks - 1D maps for AliEmcalFastOrMonitorTask.cxx

- PWGJE/EMCALJetTasks/AliAnalysisTaskRhoPerpCone.cxx
Changing the rho perp cone method such that it can draws two perp cones one on the right and one on the left, and estimated the background density as the average.
> Drawing perp cones on the right and left

- PWGJE/EMCALJetTasks/FlowVectorCorrections/macros/AddTaskFlowQnVectorCorrectionsNewDetConfigPWGJE.C
- PWGJE/EMCALJetTasks/FlowVectorCorrections/macros/CreateAlienHandler.C
- PWGJE/EMCALJetTasks/FlowVectorCorrections/macros/loadRunOptionsPWGJE.C
- PWGJE/EMCALJetTasks/FlowVectorCorrections/macros/runoptionsPWGJE.txt
I modified some missing lines of the codes to calibrate event plane value in PWGJE
> modify some missing lines of Event Plane measurement task in PWGJE

- PWG/FLOW/Tasks/AliAnalysisTaskCMWESEsyst.cxx
- PWG/FLOW/Tasks/AliAnalysisTaskCMWESEsyst.h
This code added to :
1. fix little bug
2. add default measurement because the previous run for default 10h show wrong results(maybe from the input files)
> fix little bug & add default calculation

- PWGMM/UE/UeKNO/AliAnalysisTaskChargedVsRT.cxx
Correction in order to fill a histogram associated with efficiency by acceptance
> To fill a histogram

- PWGJE/EMCALJetTasks/macros/AddTaskSVtaskMCFilter.C
I fixed the MC filter task so it works now with root6.
> Making the MC filter task work with root6

- PWGCF/Correlations/DPhi/AliAnalysisTaskLambdaK0s.cxx
- PWGCF/Correlations/DPhi/AliAnalysisTaskLambdaK0s.h
- PWGCF/Correlations/DPhi/CMakeLists.txt
- PWGCF/Correlations/DPhi/PWGCFCorrelationsDPhiLinkDef.h
- PWGCF/Correlations/macros/AddTaskLambdaK0s.C
New task for  Lambda over K0s Ratio
> new Task LK0s

- PWG/FLOW/Tasks/AliAnalysisTaskCMWESE.cxx
- PWGCF/FLOW/GF/AliAnalysisTaskCMWESETrkSyst.cxx
- PWGCF/FLOW/GF/AliAnalysisTaskCMWESETrkSyst.h
- PWGCF/FLOW/GF/CMakeLists.txt
- PWGCF/FLOW/GF/PWGCFFLOWGFLinkDef.h
- PWGCF/FLOW/macros/AddTaskCMWESETrkSyst.C
Add new class to estimate track-wise systematics:
source 1, FB
source 2, MC model
As I need to use AliGFWWeight and AliGFWCut classes, I add this code to PWGCF/FLOW/GF/ folder.
Also fix a bug of previous code.
> Add code to do track-wise systematic estimation for CMWESE

- PWGJE/EMCALJetTasks/UserTasks/AliAnalysisTaskJetExtractor.cxx
- PWGJE/EMCALJetTasks/UserTasks/AliAnalysisTaskJetExtractor.h
Update to include the jet event-plane angle for the matched jet at truth level.
> AliAnalysisTaskJetExtractor: include matched Jet_EPangle at truth level

- PWGCF/FLOW/GF/AliAnalysisTaskCMWESETrkSyst.cxx
- PWGCF/FLOW/macros/AddTaskCMWESETrkSyst.C
This pull adds input files paths which are needed for 10h track wise systematic estimation for CMWESE
> [PWG-CF]Add Input Files Path

- PWGDQ/dielectron/core/AliAnalysisTaskTagAndProbe.cxx
> PWGDQ/LMEE: update on TAP for MC

- PWGCF/Correlations/JCORRAN/Pro/AliAnalysisTaskRidge.cxx
- PWGCF/Correlations/macros/jcorran/AddTaskRidge.C
updates for loading efficiency
> [PWGCF] updates for loading efficiency

- PWGCF/FLOW/GF/AliAnalysisTaskEffFDExample.cxx
- PWGCF/FLOW/GF/AliAnalysisTaskEffFDExample.h
- PWGCF/FLOW/GF/AliEffFDContainer.cxx
- PWGCF/FLOW/GF/AliEffFDContainer.h
- PWGCF/FLOW/macros/AddTaskEffFDExample.C
Flags follow standard GFWFilter prescription
> AliEffFD example task: adding flags for AOD systematics

- PWGJE/EMCALJetTasks/Tracks/AliAnalysisTaskEmcalJetEnergySpectrum.cxx
- PWGJE/EMCALJetTasks/Tracks/AliAnalysisTaskEmcalJetEnergySpectrum.h
PWGJE/EMCALJetTasks/Tracks adding 1D emcal cluster histo into AliAnalysisTaskEmcalJetEnergySpectrum
> PWGJE/EMCALJetTasks/Tracks adding 1D emcal cluster histo into AliAnalysisTaskEmcalJetEnergySpectrum

- PWG/FLOW/Tasks/AliAnalysisTaskCMXQA.cxx
- PWG/FLOW/Tasks/AliAnalysisTaskCMXQA.h
- PWG/FLOW/Tasks/CMakeLists.txt
- PWG/FLOW/Tasks/PWGflowTasksLinkDef.h
- PWGCF/FLOW/macros/AddTaskCMXQA.C
Added QA Task for PID CME/CMW analysis
> Added QA Task for PID CME/CMW analysis

- PWGDQ/dielectron/LMEE/AliAnalysisTaskBeauty.cxx
- PWGDQ/dielectron/LMEE/AliAnalysisTaskBeauty.h
- PWGDQ/dielectron/LMEE/AliAnalysisTaskCharm.cxx
- PWGDQ/dielectron/LMEE/AliAnalysisTaskCharm.h
- PWGDQ/dielectron/LMEE/AliAnalysisTaskLMeeCocktailMC.cxx
- PWGDQ/dielectron/LMEE/AliAnalysisTaskLMeeCocktailMC.h
- PWGDQ/dielectron/macrosLMEE/AddTaskBeauty.C
- PWGDQ/dielectron/macrosLMEE/AddTaskCharm.C
- PWGDQ/dielectron/macrosLMEE/AddTask_LMeeCocktailMC.C
Updated bbbar cocktail calculation for ULS
Added/Updated opening angle cut in cocktail calculation
> DQ:LMee: Update to cocktail calculation

- PWGDQ/dielectron/core/AliDielectron.cxx
- PWGDQ/dielectron/core/AliDielectron.h
- PWGDQ/dielectron/core/AliDielectronPID.cxx
- PWGDQ/dielectron/core/AliDielectronPID.h
- PWGDQ/dielectron/core/AliDielectronVarManager.cxx
- PWGDQ/dielectron/core/AliDielectronVarManager.h
add deuteron PID
update TPCRP
add a flag to use TOFbeta in stead of kDetPidOk
> PWGDQ/LMEE: add deuteron PID

- PWGDQ/dielectron/core/AliDielectronPID.cxx
> PWGDQ/LMEE: change min. value of TOFbeta

- PWGDQ/dielectron/core/AliAnalysisTaskTagAndProbe.cxx
> PWGDQ/LMEE: update TAP

- PWGDQ/dielectron/core/AliDielectron.cxx
- PWGDQ/dielectron/core/AliDielectron.h
- PWGDQ/dielectron/core/AliDielectronPID.cxx
- PWGDQ/dielectron/core/AliDielectronPID.h
> PWGDQ/LMEE: revert TOF PID

- PWGDQ/dielectron/core/AliAnalysisTaskTagAndProbe.cxx
quick fix to track selection in V0
> PWGDQ/LMEE: quick fix to track selection in V0

- PWGCF/FLOW/macros/AddTaskCMXQA.C
Fixed Taskname in AddTaskMacro
> Fixed Taskname in AddTaskMacro

- PWGJE/EMCALJetTasks/UserTasks/AliAnalysisTaskJetExtractor.cxx
- PWGJE/EMCALJetTasks/UserTasks/AliAnalysisTaskJetExtractor.h
Addition of "LightTreeMode" flag to allow for reduced output size.
> AliAnalysisTaskJetExtractor: Light Tree Mode

- PWGDQ/dielectron/core/AliDielectronTrackCuts.h
add an AODfilterbit for kTrkGlobal
> PWGDQ/LMEE: add an AODfilterbit for kTrkGlobal

- PWGLF/STRANGENESS/CMakeLists.txt
- PWGLF/STRANGENESS/Cascades/Run2/AliAnalysisTaskStrangeCascadesTriggerAODRun2.cxx
- PWGLF/STRANGENESS/Cascades/Run2/AliAnalysisTaskStrangeCascadesTriggerAODRun2.h
- PWGLF/STRANGENESS/Cascades/Run2/AliAnalysisTaskStrangeCascadesTriggerAODRun2MC.cxx
- PWGLF/STRANGENESS/Cascades/Run2/AliAnalysisTaskStrangeCascadesTriggerAODRun2MC.h
- PWGLF/STRANGENESS/Cascades/Run2/AliCascadeContainer.cxx
- PWGLF/STRANGENESS/Cascades/Run2/AliCascadeContainer.h
- PWGLF/STRANGENESS/Cascades/Run2/AliEventContainer.cxx
- PWGLF/STRANGENESS/Cascades/Run2/AliEventContainer.h
- PWGLF/STRANGENESS/Cascades/Run2/AliMCCascadeContainer.cxx
- PWGLF/STRANGENESS/Cascades/Run2/AliMCCascadeContainer.h
- PWGLF/STRANGENESS/Cascades/Run2/AliMCEventContainer.cxx
- PWGLF/STRANGENESS/Cascades/Run2/AliMCEventContainer.h
- PWGLF/STRANGENESS/Cascades/Run2/AliMCGenParticleContainer.cxx
- PWGLF/STRANGENESS/Cascades/Run2/AliMCGenParticleContainer.h
- PWGLF/STRANGENESS/Cascades/Run2/AliMCTrackInfoContainer.cxx
- PWGLF/STRANGENESS/Cascades/Run2/AliMCTrackInfoContainer.h
- PWGLF/STRANGENESS/Cascades/Run2/AliMCV0Container.cxx
- PWGLF/STRANGENESS/Cascades/Run2/AliMCV0Container.h
- PWGLF/STRANGENESS/Cascades/Run2/AliTrackInfoContainer.cxx
- PWGLF/STRANGENESS/Cascades/Run2/AliTrackInfoContainer.h
- PWGLF/STRANGENESS/Cascades/Run2/AliV0Container.cxx
- PWGLF/STRANGENESS/Cascades/Run2/AliV0Container.h
- PWGLF/STRANGENESS/Cascades/Run2/macros/AddTaskStrangeCascadesTriggerAODRun2.C
- PWGLF/STRANGENESS/Cascades/Run2/macros/AddTaskStrangeCascadesTriggerAODRun2MC.C
- PWGLF/STRANGENESS/PWGLFSTRANGENESSLinkDef.h
Add new classes to facilitate event-by-event analysis in real and MC data : 
- 1 to contain event info (AliEventContainer and AliMCEventContainer),
- 1 to contain cascade info (AliCascadeContainer and AliMCCascadeContainer),
- 1 to contain V0 info (AliV0Container and AliMCV0Container),
- 1 to contain Track info (AliTrackInfoContainer and AliTrackInfoContainer),
- 1 to contain generated particle info (AliMCGenParticleContainer).
These classes have been implemented in the associated analysis tasks, namely AliAnalysisTaskStrangeCascadesTriggerAODRun2 and AliAnalysisTaskStrangeCascadesTriggerAODRun2MC.
> Add new classes to facilitate event-by-event analysis

- PWGDQ/dielectron/core/AliAnalysisTaskTagAndProbe.cxx
- PWGDQ/dielectron/core/AliAnalysisTaskTagAndProbe.h
> PWGDQ/LMEE: update TAP for pairing

- PWGDQ/dielectron/core/AliAnalysisTaskTagAndProbe.cxx
- PWGDQ/dielectron/core/AliDielectronVarCuts.cxx
- PWGDQ/dielectron/core/AliDielectronVarCuts.h
add flexibility for TF1-based cut in AliDielectronVarCuts
quick fix to TAP
> PWGDQ/LMEE: add flexibility for TF1-based cut in AliDielectronVarCuts

- PWG/FLOW/Tasks/AliAnalysisTaskCMWESE.cxx
- PWG/FLOW/Tasks/AliAnalysisTaskCMWESE.h
- PWGCF/FLOW/macros/AddTaskCMWESE.C
This version of code for CMWESE aims to:
1, Tune AddTask.C to utilize subwagon function in train
2, Aim to do the calculation for event-wise systematic sources : vz cut and pile up
> Event Wise Syst Estimation with Subwagons

- PWGDQ/dielectron/core/AliAnalysisTaskTagAndProbe.cxx
> PWGDQ/LMEE: update TAP for PID calib

- PWG/FLOW/Tasks/AliAnalysisTaskEPCalib.cxx
- PWG/FLOW/Tasks/AliAnalysisTaskEPCalib.h
- PWGCF/FLOW/macros/AddTaskEPCalib.C
This version of the code is edited for NUA weight with different track cuts. Prepared for track-wise systematic in CMWESE analysis.
> [PWG-CF] CMWESE Fill for NUAweight

- PWGDQ/dielectron/core/AliDielectronVarManager.h
> PWGDQ/LMEE: update on EP in VarManager

- PWGLF/NUCLEX/Hypernuclei/Hyp2Body/HypTritYield/Sigma_Baryons/AddTaskSigmaPlus.C
- PWGLF/NUCLEX/Hypernuclei/Hyp2Body/HypTritYield/Sigma_Baryons/AliAnalysisTaskSigmaPlus.cxx
- PWGLF/NUCLEX/Hypernuclei/Hyp2Body/HypTritYield/Sigma_Baryons/AliAnalysisTaskSigmaPlus.h
Added additional features and branches
> Added additional features and branches

- PWGCF/FEMTOSCOPY/AliFemto/AliFemtoV0TrackCut.cxx
- PWGCF/FEMTOSCOPY/AliFemto/AliFemtoV0TrackCut.h
Added Rapidity  for V0 Track Cut
> NewV0TrackCut

- PWGCF/FLOW/GF/AliEffFDContainer.cxx
- PWGCF/FLOW/GF/AliEffFDContainer.h
- PWGCF/FLOW/GF/AliGFWFilterTask.cxx
- PWGCF/FLOW/macros/AddTaskEffFDExample.C
-- Helper functions in EffFDContainer, also renamed some output
-- Typo fix in GFWFilter that caused train to crash for certain periods
-- AddTask macro names task with a custom name
> GFWFilter, EffFDContainer, AddTaskEffFDExample

- PWGLF/NUCLEX/Nuclei/Nuclei_UE/AliAnalysisTaskDeuteronCoalescence.cxx
- PWGLF/NUCLEX/Nuclei/Nuclei_UE/AliAnalysisTaskDeuteronCoalescence.h
> ESDs -> AODs

- PWGCF/Correlations/DPhi/AliEPDependentDiHadronOnTheFlyMCTask.cxx
- PWGCF/Correlations/DPhi/AliEPDependentDiHadronOnTheFlyMCTask.h
- PWGCF/Correlations/DPhi/CMakeLists.txt
- PWGCF/Correlations/DPhi/PWGCFCorrelationsDPhiLinkDef.h
This pull request is on behalf of Darius Keijdener. He has prepared this task for studies with generator-only events, in particular with AMPT, using the MC kine train.
> New task for delta-phi correlations wrt event plan for MCKine train

- PWGCF/Correlations/JCORRAN/Pro/AliAnalysisTaskRidge.cxx
- PWGCF/Correlations/JCORRAN/Pro/AliAnalysisTaskRidge.h
> [PWGCF] fix bug in bin definition

- PWGJE/EMCALJetTasks/UserTasks/AliAnalysisTaskJetQnVectors.cxx
- PWGJE/EMCALJetTasks/UserTasks/AliAnalysisTaskJetQnVectors.h
Change accepted formatting for spline files from TLists to TDirectoryFiles
> AliAnalysisTaskJetQnVectors: change accepted formatting for spline files

- PWGHF/vertexingHF/vHFML/AliAnalysisTaskSENonPromptLc.cxx
> Reject Lc->pK0s candidates made with V0 on-the-fly reconstructed

- PWG/FLOW/Tasks/AliAnalysisTaskCMWESE.cxx
- PWGCF/FLOW/macros/AddTaskCMWESE.C
Add the path for NUA files, for track-wise syst estimation: chi2cut, Nhits, FB, etc.
> [PWG-CF] CMW ESE with Trk Wise Syst

- PWGMM/UE/UeKNO/AliAnalysisTaskChargedVsRT.cxx
- PWGMM/UE/UeKNO/AliAnalysisTaskChargedVsRT.h
With this fraction in the code we include a PDG -lambda-
> To include a PDG

- PWGJE/EMCALJetTasks/UserTasks/AliAnalysisTaskIDFragmentationFunction.cxx
- PWGJE/macros/AddTaskESDFilterPWGJETrain.C
+ Small log improvement in AliAnalysisTAskIDFragmentationFunction
> Make AddTaskESDFilterPWGJETrain ROOT6 ready

- PWGCF/Correlations/DPhi/AliAnalysisTaskLambdaK0s.cxx
> set_trigger

- PWGCF/EBYE/ParticleYieldRatioCorrelations/AliAnalysisTaskParticleYieldRatioCorrelations.cxx
- PWGCF/EBYE/ParticleYieldRatioCorrelations/AliAnalysisTaskParticleYieldRatioCorrelationsEfficiency.cxx
Added a reset for variable "sort" into generated particles loop
> Added sort reset

- PWGCF/FLOW/GF/AliAnalysisTaskCreateNUA.cxx
- PWGCF/FLOW/GF/AliAnalysisTaskCreateNUA.h
- PWGCF/FLOW/GF/CMakeLists.txt
- PWGCF/FLOW/GF/PWGCFFLOWGFLinkDef.h
- PWGCF/FLOW/macros/AddTaskCreateNUA.C
the merge process pause...
Try again
> [PAG-Flow]Add NUA task

- PWGCF/Correlations/JCORRAN/Pro/AliAnalysisTaskRidge.cxx
> [PWGCF] correction for bug

- PWGHF/vertexingHF/AliHFSystErr.cxx
fix syst for 13TeV analysis (coarse bin mb, lm, hm)
> fix binning 13TeV D0 syst coarse

- PWGJE/EMCALJetTasks/PWGJEEMCALJetTasksLinkDef.h
- PWGJE/EMCALJetTasks/Tracks/AliAnalysisTaskEmcalJetEnergyScale.cxx
- PWGJE/EMCALJetTasks/Tracks/AliAnalysisTaskEmcalJetEnergyScale.h
- Extract AngularityHandler to separate class
- Set ClassDebugLevel for AngularityHandler and
AngularityBin
- Add streaming operators for debugging
- Increase debug levels in AliAnalysisTaskEmcalJetEnergyScale
> Fix streaming of angularity handler

- PWGLF/RESONANCES/macros/mini/AddTaskResonanceFinder.C
4 different mass states with different PDG numbers need to be analyzed, I am including a variable that, when it is on during MC, will cycle through all necessary mass states and PDG numbers
> Add system to cycle between masses and PDGs for Ps MC Analysis

- PWGGA/GammaConv/macros/AddTask_GammaCalo_pp.C
- PWGGA/GammaConvBase/AliCaloPhotonCuts.cxx
for EMCal
- Added nomB NonLinearity setting that can be applied to nomB and lowB
MC, added respective config in AddTask
> PWGGA/GammaConv: Added configs with different cluster energy thresholds

- PWGHF/vertexingHF/AliAnalysisTaskSEOmegac2eleOmegafromAODtracks.cxx
Using the absolute track label;
Adding one condition about the numbers of daughters of cascade
> track label, number of casc daughters

- PWGJE/EMCALJetTasks/UserTasks/AliAnalysisTaskIDFragmentationFunction.cxx
- PWGJE/EMCALJetTasks/UserTasks/AliAnalysisTaskIDFragmentationFunction.h
- PWGJE/macros/AddTaskIDFragmentationFunction.C
+ setting -1 as default eventClass
> Update logging mechanism in AliAnalysisTaskIDFragmentationFunction

- PWGGA/GammaConvBase/AliCaloPhotonCuts.cxx
- PWGGA/GammaConvBase/AliCaloPhotonCuts.h
- PWGGA/GammaConvBase/AliConvEventCuts.cxx
- PWGGA/GammaConvBase/AliConvEventCuts.h
- switching from int* to std::vector<int>. For int* a seg fault was
observed
> PWGGA/GammaConv: Added MC production LHC21j8a (noB)

- PWGLF/RESONANCES/macros/mini/AddTaskResonanceFinder.C
variable Ps was left blank, causing errors. Now has assigned value.
> Edit error in variable value assignment

- PWGCF/Correlations/JCORRAN/Pro/AliAnalysisTaskRidge.cxx
- PWGCF/Correlations/JCORRAN/Pro/AliAnalysisTaskRidge.h
- PWGCF/Correlations/macros/jcorran/AddTaskRidge.C
correction for loading efficiency
> [PWGCF] load efficiency

- PWGCF/Correlations/DPhi/AliAnalysisTaskV0ChCorrelationsys.cxx
> more trigg

- PWG/FLOW/Tasks/AliAnalysisTaskAR.cxx
Fix error prone method for initalizing vectors of symmetric cumulants.
> Fix: fix GetPointers Method

- PWGLF/STRANGENESS/CMakeLists.txt
- PWGLF/STRANGENESS/Cascades/Run2/AliAnalysisTaskMCPredictionsEE.cxx
- PWGLF/STRANGENESS/Cascades/Run2/AliAnalysisTaskMCPredictionsEE.h
- PWGLF/STRANGENESS/Cascades/Run2/macros/AddTaskMCPredictionsEE.C
- PWGLF/STRANGENESS/PWGLFSTRANGENESSLinkDef.h
Tasl to run the Strangeness vs Effective Energy studies on FastMC lego trains
> add task for strangeness vs effective energy for MC predictions

- PWGCF/Correlations/JCORRAN/Pro/AliAnalysisTaskRidge.cxx
- PWGCF/Correlations/JCORRAN/Pro/AliAnalysisTaskRidge.h
no subsampling inside the same run
> [PWGCF] no subsampling inside the same run

- PWGGA/GammaConv/macros/AddTask_GammaConvNeutralMesonPiPlPiMiNeutralMeson_ConvMode_pPb.C
-Added argument doWeightingPart as it was not declared and task was crashing
> PWGGA/GammaConv: Added config for pPb 5TeV omega PCM

- PWGJE/EMCALJetTasks/CMakeLists.txt
- PWGJE/EMCALJetTasks/PWGJEEMCALJetTasksLinkDef.h
- PWGJE/EMCALJetTasks/UserTasks/AliAnalysisTaskIDFragmentationFunction.cxx
- PWGJE/EMCALJetTasks/UserTasks/AliAnalysisTaskIDFragmentationFunction.h
- PWGJE/EMCALJetTasks/UserTasks/AliAnalysisTaskMTFPID.cxx
- PWGJE/EMCALJetTasks/UserTasks/AliAnalysisTaskMTFPID.h
- PWGJE/EMCALJetTasks/UserTasks/AliHelperClassFastSimulation.cxx
- PWGJE/macros/AddTaskMTFPID.C
and move namesuffix to end of parameter list in AddTask
> Rename task AliAnalysisTaskPID => AliAnalysisTaskMTFPID
