alisw/AliPhysics

PWGMM/UE/UeKNO/AliAnalysisTaskChargedVsRT.cxx
PWGMM/UE/UeKNO/AliAnalysisTaskChargedVsRT.h

Correct an error related with the histogram of the rest of the charged particles

Correct an error of a histogram 

---

PWGCF/FEMTOSCOPY/FemtoDream/AliAnalysisTaskOtonkd.cxx
PWGCF/FEMTOSCOPY/FemtoDream/AliAnalysisTaskOtonkd.h
PWGCF/FEMTOSCOPY/macros/AddTaskOtonkd.C

Also: Added variations in nSigmas for deuterons and kaons

Added Flag to restore FemtoDream pairing for kd analysis.

---

PWG/EMCAL/EMCALtasks/AliEmcalCorrectionCellEmulateCrosstalk.cxx
PWG/EMCAL/EMCALtasks/AliEmcalCorrectionCellEmulateCrosstalk.h
PWG/EMCAL/config/AliEmcalCorrectionConfiguration.yaml

Implement different absolute min E fraction for central pseudorapidity

---

PWGDQ/dielectron/macrosLMEE/AddTask_rbailhac_lowmass_PbPb.C

Add the possibility to run with a different centrality estimator on the data

Give the possibility to run with a different centrality estimator

---

PWGCF/EBYE/BalanceFunctions/AliAnalysisTaskSignedBFMC.cxx
PWGCF/EBYE/BalanceFunctions/AliAnalysisTaskSignedBFMC.h
PWGCF/EBYE/CMakeLists.txt
PWGCF/EBYE/PWGCFebyeLinkDef.h
PWGCF/EBYE/macros/AddTaskSignedBFMC.C

Added SignedBF with MC (on the fly)

Added SignedBF with MC (on the fly)

---

PWGCF/Correlations/DPhi/AliEPDependentDiHadronOnTheFlyMCTask.cxx
PWGCF/Correlations/DPhi/AliEPDependentDiHadronOnTheFlyMCTask.h

Added code to apply pseudorapidity selection on the MC particles

Add eta selection to EP Dphi task for on-the-fly MC train

---

PWGDQ/dielectron/LMEE/AliAnalysisTaskBeauty.cxx
PWGDQ/dielectron/LMEE/AliAnalysisTaskBeauty.h
PWGDQ/dielectron/LMEE/AliAnalysisTaskCharm.cxx
PWGDQ/dielectron/LMEE/AliAnalysisTaskCharm.h
PWGDQ/dielectron/macrosLMEE/AddTaskBeauty.C
PWGDQ/dielectron/macrosLMEE/AddTaskCharm.C

update charm and beauty cocktail for re-weighting by RAA of hfe

PWGDQ/LMEE: update charm and beauty cocktail for re-weighting by RAA of hfe

---

PWGDQ/dielectron/LMEE/AliAnalysisTaskBeauty.cxx
PWGDQ/dielectron/LMEE/AliAnalysisTaskBeauty.h
PWGDQ/dielectron/LMEE/AliAnalysisTaskCharm.cxx
PWGDQ/dielectron/LMEE/AliAnalysisTaskCharm.h
PWGDQ/dielectron/macrosLMEE/AddTaskBeauty.C
PWGDQ/dielectron/macrosLMEE/AddTaskCharm.C

Update to include the possibility with function

---

PWG/MCLEGO/AddMCGenAmptPbPb.C

Add Option For Randomising RP in AMPT MC on the fly

Add Option For Randomising RP in AMPT MC on the fly

---

PWGCF/Correlations/JCORRAN/Pro/AliJCDijetHistos.cxx
PWGCF/Correlations/JCORRAN/Pro/AliJCDijetTask.cxx

There was a small possibility of the bin finding not working so that has been fixed.

Binning bugfix

---

PWGMM/UE/UeKNO/AliAnalysisTaskMcKnoUeSystem.cxx
PWGMM/UE/UeKNO/AliAnalysisTaskMcKnoUeSystem.h

tracking efficiency for TPC only

add spectra for tracking efficiency for TPC only

---

PWGLF/STRANGENESS/Cascades/Run2/AliAnalysisTaskStrangeCascadesTriggerAODRun2.cxx
PWGLF/STRANGENESS/Cascades/Run2/AliAnalysisTaskStrangeCascadesTriggerAODRun2.h
PWGLF/STRANGENESS/Cascades/Run2/AliAnalysisTaskStrangeCascadesTriggerAODRun2MC.cxx
PWGLF/STRANGENESS/Cascades/Run2/AliAnalysisTaskStrangeCascadesTriggerAODRun2MC.h
PWGLF/STRANGENESS/Cascades/Run2/AliCascadeContainer.cxx
PWGLF/STRANGENESS/Cascades/Run2/AliEventContainer.cxx
PWGLF/STRANGENESS/Cascades/Run2/AliEventContainer.h
PWGLF/STRANGENESS/Cascades/Run2/AliMCCascadeContainer.cxx
PWGLF/STRANGENESS/Cascades/Run2/AliMCEventContainer.cxx
PWGLF/STRANGENESS/Cascades/Run2/AliMCEventContainer.h
PWGLF/STRANGENESS/Cascades/Run2/AliMCTrackInfoContainer.cxx
PWGLF/STRANGENESS/Cascades/Run2/AliMCV0Container.cxx
PWGLF/STRANGENESS/Cascades/Run2/AliTrackInfoContainer.cxx
PWGLF/STRANGENESS/Cascades/Run2/AliV0Container.cxx

Fix missing infos (event counting, vertex quality info, missing kink info in AOD) and add minor fixes

Fix missing infos

---

PWGLF/NUCLEX/Nuclei/NucleiPbPb/AliAnalysisTaskNucleiYield.h

Add pT rejection also in He3 trees

---

PWGCF/FEMTOSCOPY/FemtoDream/AliAnalysisTaskOtonkd.cxx

K-d analysis. Changes in MC truth info.

---

PWGHF/vertexingHF/AliHFSystErr.cxx
PWGHF/vertexingHF/AliHFSystErr.h

The following PR is to commit the systematic uncertainties presented and approved during the D2H meeting (11th Feb. 2022).

Add syst. unc. non-prompt Lc(->pKpi) pp 13 TeV

---

PWGMM/UE/UeKNO/AliAnalysisTaskMcKnoUeSystem.cxx

fixing tracking efficiency for TPC only

---

.gitignore
PWGUD/UPC/AliAnalysisTaskLumiStabi.cxx
PWGUD/UPC/AliAnalysisTaskLumiStabi.h

Task upgraded to be able to pick up V0M centrality percentiles with new Anchor Point

V0M efficiency

---

PWGGA/GammaConv/AliAnalysisTaskGammaCaloMerged.cxx
PWGGA/GammaConv/macros/AddTask_GammaCalo_pp.C
PWGGA/GammaConvBase/AliCaloPhotonCuts.cxx
PWGGA/GammaConvBase/AliCaloPhotonCuts.h

- Done for detailed cell track matching studies
- Added safety case in merged task as their were cases where a cluster
ha dno labels (has to be debugged why that is)

PWGGA/GammaConv: Added possibility to only select track matched clusters

---

PWGGA/PHOSTasks/CMakeLists.txt
PWGGA/PHOSTasks/PHOS_Nbar/AddTaskPHOSSigmaBar.C
PWGGA/PHOSTasks/PHOS_Nbar/AliAnalysisSigmaBarCharged.cxx
PWGGA/PHOSTasks/PHOS_Nbar/AliAnalysisSigmaBarCharged.h
PWGGA/PHOSTasks/PWGGAPHOSTasksLinkDef.h

Class for Sigma->nbar+pi+ added

---

PWGMM/UE/UeKNO/AddTaskKnoUeChecks.C
PWGMM/UE/UeKNO/AliAnalysisTaskKnoUeChecks.cxx
PWGMM/UE/UeKNO/AliAnalysisTaskKnoUeChecks.h

data driven test for nch in TSminmax

---

PWG/EMCAL/EMCALtrigger/AliEmcalTriggerLuminosity.cxx
PWG/EMCAL/EMCALtrigger/AliEmcalTriggerLuminosity.h

The uncertainty is calculated based on
the difference using the observed
downscaling instead of the expected
downscaling.
In additinon users must specify the
unit in which the integrated luminosity
is expressed. Internally the integrated
luminosity is handled in pb-1.

Add implementation of the uncertainty on the integrated luminosity

---

PWGCF/FEMTOSCOPY/FemtoDream/AliAnalysisTaskGeorgiosNTuple.cxx
PWGCF/FEMTOSCOPY/FemtoDream/AliAnalysisTaskGeorgiosNTuple.h
PWGCF/FEMTOSCOPY/macros/AddTaskGeorgiosNTuple.C

correct implementation of the FemtoDream pair cleaner and back to standard selection cuts

Crosschecks

---

PWGHF/vertexingHF/AliAnalysisTaskSEXic2eleXifromAODtracks.cxx
PWGHF/vertexingHF/AliRDHFCutsXictoeleXifromAODtracks.cxx
PWGHF/vertexingHF/AliRDHFCutsXictoeleXifromAODtracks.h

To have a look the effect from low limit pair mass cut, which was observed in D2H talk recently

Add low limit mass cut for eXi pairs

---

PWGPP/EvTrkSelection/AliAnalysisTrackingUncertaintiesAOT.cxx
PWGPP/EvTrkSelection/AliAnalysisTrackingUncertaintiesAOT.h

Added to the THnSparse output four parameters of primary vertex: transverse and longitudinal resolution, chi-square, longitudinal position.

Added primary vtx parameters output

---

PWGCF/EBYE/BalanceFunctions/AliAnalysisTaskSignedBFMC.cxx

Fix Keywords to run on MC on the Fly

Fix Keywords to run on MC on the Fly

---

PWGMM/UE/CMakeLists.txt
PWGMM/UE/PWGMMueLinkDef.h

compilation file for data-driven test

compilation file for analysis of data-driven test

---

PWGGA/GammaConv/AliAnalysisTaskOmegaToPiZeroGamma.cxx
PWGGA/GammaConv/macros/AddTask_OmegaToPiZeroGamma_pp.C
PWGGA/GammaConvBase/AliConversionMesonCuts.cxx

- updated EMCal cluster cut (01 NonLin and no NCell cut)
- also fixed the GetUniqueID() call for ESDs

PWGGA/GammaConv: OmegaToPiZero - Updated EMCal cluster cuts

---

PWGCF/Correlations/macros/pPbCorrelations/AddTaskSEpPbCorrelationsJetV2Kine.C

Hi,
This is an update of the task of jet v2. The name of container is updated to avoid the error in lego-train.
Please approve it. Thanks!
Siyu

Update the name of container

---

PWGCF/EBYE/Fluctuations/AliAnalysisTaskNFMs.cxx
PWGCF/EBYE/Fluctuations/AliAnalysisTaskNFMs.h

Codes for implementing Intermittency analysis (calculation of NFMs)

Codes for calculation of Norm factorial moments

---

PWGCF/Correlations/macros/pPbCorrelations/AddTaskSEpPbCorrelationsJetV2Kine.C

Dear all,
Here is a complementary update of PR #19804. Please approve it.
Thank you very much!
Siyu

Update the jet v2 AMPT

---

PWGJE/EMCALJetTasks/UserTasks/AliAnalysisTaskJetExtractor.cxx
PWGJE/EMCALJetTasks/UserTasks/AliAnalysisTaskJetExtractor.h
PWGJE/EMCALJetTasks/UserTasks/AliAnalysisTaskJetQnVectors.cxx
PWGJE/EMCALJetTasks/UserTasks/AliAnalysisTaskJetQnVectors.h
PWGJE/EMCALJetTasks/UserTasks/AliJEQnVectorHandler.cxx
PWGJE/EMCALJetTasks/UserTasks/AliJEQnVectorHandler.h
PWGJE/EMCALJetTasks/macros/AddTaskJEQnVectors.C

JetExtractor, JetQnVectors Updates, AliJEQnVectorHandler: Allow for LHC18q+r to be run simultaneously. Addition of branch for Q2 cross-check with 2nd detector.

updates to Jet-ESE task

---

PWG/FLOW/Tasks/AliAnalysisTaskEPCalib.cxx
PWG/FLOW/Tasks/AliAnalysisTaskEPCalib.h
PWGCF/FLOW/macros/AddTaskCMWESE.C
PWGCF/FLOW/macros/AddTaskEPCalib.C

This version aims to add path for 15o_syst, 10h_syst and 18q/r filling <Qx>, <Qy>

Add EPCalib Path

---

PWGPP/EvTrkSelection/AliAnalysisTrackingUncertaintiesAOT.cxx
PWGPP/EvTrkSelection/AliAnalysisTrackingUncertaintiesAOT.h

Added four histos to keep the distribution of primary vtx parameters included in the thnsparse. Modified the range of few thnsparse axes to take into account the range of different centralities.

Modified output

---

PWGUD/UPC/AliAnalysisTaskUpcPhi0.cxx
PWGUD/UPC/AliAnalysisTaskUpcPhi0.h

add new features and branches to K+K- analysis task

new updates to K+K- analysis task - PWGUD/UPC/AliAnalysisTaskUpcPhi0

---

PWGJE/EMCALJetTasks/UserTasks/AliAnalysisTaskJetDynamicalGrooming.cxx
PWGJE/EMCALJetTasks/UserTasks/AliAnalysisTaskJetDynamicalGrooming.h
PWGJE/EMCALJetTasks/UserTasks/AliAnalysisTaskJetHardestKt.cxx
PWGJE/EMCALJetTasks/UserTasks/AliAnalysisTaskJetHardestKt.h

Was supposed to be assuming the charged pion mass, but instead was using
the PID mass hypothesis. Note that this isn't a problem in the main jet
finding - it's only for the reclustering

Fix mass hypothesis for jet substructure

---

PWGJE/EMCALJetTasks/UserTasks/AliAnalysisTaskJetExtractor.cxx
PWGJE/EMCALJetTasks/UserTasks/AliAnalysisTaskJetExtractor.h
PWGJE/EMCALJetTasks/UserTasks/AliAnalysisTaskJetQnVectors.cxx
PWGJE/EMCALJetTasks/UserTasks/AliAnalysisTaskJetQnVectors.h

AliAnalysisTaskJetExtractor and AliAnalysisTaskJetQnVectors

Jet ESE Tasks: addition of flag for pileup rejection

---

PWGPP/EvTrkSelection/AliAnalysisTrackingUncertaintiesAOT.cxx
PWGPP/EvTrkSelection/AliAnalysisTrackingUncertaintiesAOT.h

Added 1d histos for vtx quality checks and the same variables to the TpcItsMatch list.

Output upgrade

---

PWG/FLOW/Tasks/AliAnalysisTaskCMWESE.cxx
PWG/FLOW/Tasks/AliAnalysisTaskCMWESE.h
PWG/FLOW/Tasks/AliAnalysisTaskEPCalib.cxx
PWGCF/FLOW/macros/AddTaskCMWESE.C
PWGCF/FLOW/macros/AddTaskEPCalib.C

This version aims to :
1, fix a little bug on fill Qx/y mean for LHC18r
2, calculate 15o CMWESE with the weight of centrality

[PWG-CF] Fix a little bug and add wCent

---

PWGCF/Correlations/DPhi/AliEPDependentDiHadronOnTheFlyMCTask.cxx
PWGCF/Correlations/DPhi/AliEPDependentDiHadronOnTheFlyMCTask.h

Small improvement in the task of Darius

Add single particle histogram (Darius)

---

PWGDQ/dielectron/core/AliAnalysisTaskTagAndProbe.cxx

PWGDQ/LMEE: change binning in TAP

---

PWGGA/GammaConv/macros/AddTask_GammaIsoTree.C

- removing afterburner nonlin correction from tree (will be applied offline when processing tree)

PWGGA/GammaConv: removing nonlin from iso photon tree 

---

PWG/FLOW/Tasks/AliAnalysisTaskCMWESE.cxx
PWG/FLOW/Tasks/AliAnalysisTaskCMWESE.h
PWGCF/FLOW/macros/AddTaskCMWESE.C

This version of code added a new method to estimate pile-up systematic variation

[PWG-CF] Pile-up Syst with new approch

---

PWGDQ/dielectron/macrosLMEE/AddTask_dsekihat_ElectronEfficiencyV2_PbPb.C
PWGDQ/dielectron/macrosLMEE/AddTask_dsekihat_TAP_PbPb.C
PWGDQ/dielectron/macrosLMEE/AddTask_dsekihat_lowmass_PbPb.C

update AddTask.C for new xjalien

PWGDQ/LMEE: update AddTask.C for new xjalien

---

PWGCF/Correlations/DPhi/AliAnalysisTaskR2P2Base.cxx
PWGCF/Correlations/macros/dptdptcorrelations/AddTaskR2P2Base.C

1. Corrected DCA cut in .cxx file.
2. Modified baseName in AddTask

Modified R2 and P2

---

PWGJE/EMCALJetTasks/UserTasks/AliAnalysisTaskJetQnVectors.cxx
PWGJE/EMCALJetTasks/UserTasks/AliAnalysisTaskJetQnVectors.h

AliAnalysisTaskJetQnVectors: detector resolution plots

---

PWGCF/Correlations/JCORRAN/Pro/AliJCDijetAna.cxx
PWGCF/Correlations/JCORRAN/Pro/AliJCDijetTask.cxx
PWGCF/Correlations/JCORRAN/Pro/AliJCDijetTask.h

This can be turned on or off by a flag in the addtask macro

Added AliEventCut as a possible event selection.

---

PWGUD/UPC/AliAnalysisTaskLumiStabi.cxx
PWGUD/UPC/AliAnalysisTaskLumiStabi.h

New Anchor Point for LHC18qr OADB file

V0M efficiency calculation

---

PWGPP/TPC/macros/PIDCalib/MakeTPCPIDResponseOADB.C
PWGPP/TPC/macros/PIDCalib/getdEdxGraph.C

TPC: Add splines and eta maps for LHC16d.pass2 offline and HLT clusters

---

PWGCF/EBYE/BalanceFunctions/AliAnalysisTaskSignedBFMC.cxx
PWGCF/EBYE/BalanceFunctions/AliAnalysisTaskSignedBFMC.h

Add EP estimation and Resolution in AMPT MCFly

Add EP estimation and Resolution in AMPT MCFly

---

PWGLF/RESONANCES/AliRsnMiniPair.cxx
PWGLF/RESONANCES/AliRsnMiniPair.h
PWGLF/RESONANCES/AliRsnMiniValue.cxx
PWGLF/RESONANCES/AliRsnMiniValue.h

Added CS frame in the calculations.

Colin Soper reference frame added Arvind & Jacek

---

PWGJE/EMCALJetTasks/UserTasks/AliAnalysisTaskJetQnVectors.cxx
PWGJE/EMCALJetTasks/UserTasks/AliAnalysisTaskJetQnVectors.h

addition of 3D histograms for detector resolution calculation

AliAnalysisTaskJetQnVectors: TH3Fs for resolution calculation

---

PWGGA/GammaConv/macros/AddTask_GammaConvDalitzV1_pp.C

Systematic and New configs for multiplicity ranges of 0-1%, 50-100% and 0-100%

PWGGA/GammaConv/macros  Dalitz

---

PWGMM/UE/UeKNO/AddTaskMcKnoUeSystem.C
PWGMM/UE/UeKNO/AliAnalysisTaskMcKnoUeSystem.cxx
PWGMM/UE/UeKNO/AliAnalysisTaskMcKnoUeSystem.h

fixing the requirement of SPD

---

PWG/FLOW/Tasks/AliAnalysisTaskCMWESE.cxx
PWG/FLOW/Tasks/AliAnalysisTaskCMWESE.h
PWGCF/FLOW/macros/AddTaskCMWESE.C

This version of code aims to CME-ESE analysis for 18q/r peroid.

CMWESE for LHC18q/r

---

PWGHF/vertexingHF/macros/AddTaskHFTreeCreatorApply.C
PWGHF/vertexingHF/vHFML/AliAnalysisTaskSEHFTreeCreatorApply.cxx
PWGHF/vertexingHF/vHFML/AliAnalysisTaskSEHFTreeCreatorApply.h
PWGHF/vertexingHF/vHFML/AliHFMLResponseLctoV0bachelor.cxx
PWGHF/vertexingHF/vHFML/AliHFMLResponseLctoV0bachelor.h
PWGHF/vertexingHF/vHFML/AliHFTreeHandlerApplyLc2V0bachelor.cxx
PWGHF/vertexingHF/vHFML/AliHFTreeHandlerApplyLc2V0bachelor.h

Based on code from 15o PbPb analysis. Required for Referee comment

PWGHF: Introduce Lc->pK0s background from mixed events

---

PWGHF/vertexingHF/macros/AddTaskHFTreeCreatorApply.C
PWGHF/vertexingHF/vHFML/AliAnalysisTaskSEHFTreeCreatorApply.cxx

PID object was not initialised when running mixed-event stand alone. Fixed + added warnings

PWGHF: Fix to run mixed event stand-alone

---

PWGHF/vertexingHF/AliAnalysisTaskSEOmegacZero2XiPifromKFP.cxx
PWGHF/vertexingHF/AliAnalysisTaskSEOmegacZero2XiPifromKFP.h
PWGHF/vertexingHF/CMakeLists.txt
PWGHF/vertexingHF/PWGHFvertexingHFLinkDef.h
PWGHF/vertexingHF/macros/AddTaskOmegacZero2XiPiFromKFParticle.C

AnalysisTask and AddTask for the analysis of omegac0 decaying into XiPi (new decay channel)

First Version Omegac0 analysis 2XiPi

---

PWGCF/EBYE/BalanceFunctions/AliAnalysisTaskSignedBFMC.cxx
PWGCF/EBYE/BalanceFunctions/AliAnalysisTaskSignedBFMC.h
PWGCF/EBYE/macros/AddTaskSignedBFMC.C

Add Setter to choose b/w EP and RP in MCFly

Add Setter to choose b/w EP and RP in MCFly

---

PWG/EMCAL/EMCALbase/AliMCParticleContainer.cxx
PWGJE/EMCALJetTasks/Tracks/AliAnalysisTaskEmcalJetEnergyScale.cxx
PWGJE/EMCALJetTasks/Tracks/AliAnalysisTaskEmcalJetEnergyScale.h

Updates for running with part. level pt cuts for charged and neutral

---

PWGHF/vertexingHF/AliAnalysisTaskSEXicPlus2XiPiPifromAODtracks.cxx
PWGHF/vertexingHF/AliAnalysisTaskSEXicPlus2XiPiPifromAODtracks.h
PWGHF/vertexingHF/macros/AddTaskXicPlus2XiPiPifromAODtracks.C

Add the following parts for HM analysis
- HMV0 and HMSPD Trigger 
- Histogram in event selection steps to check trigger and centrality for each events
- HMTrigOn option to enable (or disable) the HM trigger in AddTask macro

Add trigger part for HM analysis

---

PWGLF/SPECTRA/MultEvShape/AliMEStenderV2.cxx

Fix compilation issue for macOS:
`variable-sized object may not be initialized`

Fix variable-size array initialisation

---

PWGLF/RESONANCES/PostProcessing/f0980/AddTaskInclusivef0f2.C
PWGLF/RESONANCES/PostProcessing/f0980/AliAnalysisTaskInclusivef0f2.cxx
PWGLF/RESONANCES/PostProcessing/f0980/AliAnalysisTaskInclusivef0f2.h

[PWGLF] updates for EP analysis

---

PWGGA/GammaConv/AliAnalysisTaskGammaIsoTree.cxx
PWGGA/GammaConv/AliAnalysisTaskGammaIsoTree.h
PWGGA/GammaConv/macros/AddTask_GammaIsoTree.C

- added information about distance to bad channel to isolated photon tree
- cut will from now on be applied offline

PWGGA/GammaConv: added distance to BC information to GammaIsoTree

---

PWGHF/hfe/AliAnalysisTaskHFEBESpectraEMC.cxx
PWGHF/hfe/AliAnalysisTaskHFEBESpectraEMC.h

Adding a histogram of EMCal Cluster energy vs pT of the track for electron candidates

Adding histo ClsE vs pT of inclusive electrons

---

PWGCF/FLOW/macros/AddTaskCMWESE.C

[PWG-CF]Add 18r Path

---

PWGGA/EMCALTasks/AliAnalysisTaskGammaHadron.cxx
PWGGA/EMCALTasks/AliAnalysisTaskGammaHadron.h

Lowers hard-coded 2 GeV cut in Pi0-candidate mode
Adds one more QA histogram

Lowers hard-coded 2 GeV cut in Pi0-candidate mode

---

PWGPP/EvTrkSelection/AliAnalysisTrackingUncertaintiesAOT.cxx
PWGPP/EvTrkSelection/AliAnalysisTrackingUncertaintiesAOT.h

Added a switch to add primary vertex quality variables.

Primary vtx variables optional

---

PWG/FLOW/Tasks/AliAnalysisTaskLambdaProtonCVE.cxx
PWG/FLOW/Tasks/AliAnalysisTaskLambdaProtonCVE.h
PWGCF/FLOW/macros/AddTaskLambdaProtonCVE.C

Add Support for 18q/r ZDC Plane and fix a small bug.

Add 18q/r ZDC Plane

---

PWGGA/EMCALTasks/AliAnalysisTaskGammaHadron.cxx
PWGGA/EMCALTasks/AliAnalysisTaskGammaHadron.h

Adds new EP correlation mode, analysis with v1

Adds new EP correlation mode, analysis with v1

---

PWGCF/Correlations/DPhi/AliAnalysisTaskSEpPbCorrelationsJetV2Kine.cxx
PWGCF/Correlations/DPhi/AliAnalysisTaskSEpPbCorrelationsJetV2Kine.h
PWGCF/Correlations/macros/pPbCorrelations/AddTaskSEpPbCorrelationsJetV2Kine.C

Hi all,
I create the pull requests again, since the old one is closed due to the problem of PR system.
Please approve it. Thanks!
Siyu

Extent the eta range

---

PWGCF/FEMTOSCOPY/macros/Train/Femto_WRZ/eff/AliAnalysisTaskParticleEffWRZ.C
PWGCF/FEMTOSCOPY/macros/Train/Femto_WRZ/eff/AliAnalysisTaskParticleEffWRZ.h

efficiency test in the train

---

PWGGA/GammaConv/AliAnalysisTaskGammaConvV1.cxx
PWGGA/GammaConv/AliAnalysisTaskGammaConvV1.h

Added TH1D fHistoMCPi0WOWeightinJetinAccPt and fill it.
Also made sure that fHistoEventwJets is not left empty when fIsMC = 0.

Added a TH1D needed for analysis of neutral meson inside jets

---

PWG/CaloTrackCorrBase/AliCaloTrackReader.cxx
PWG/CaloTrackCorrBase/AliCaloTrackReader.h
PWGGA/CaloTrackCorrelations/AliAnaParticleIsolation.cxx
PWGGA/CaloTrackCorrelations/AliAnaParticleIsolation.h
PWGGA/CaloTrackCorrelations/AliAnaPhoton.cxx
PWGGA/CaloTrackCorrelations/AliAnaPhoton.h

and TriggerMaker bits for cluster and isolation

[CaloTrackCorr] Additional control histogram with trigger bit correlation

---

PWG/FLOW/Tasks/AliAnalysisTaskCMWESE.cxx
PWGCF/FLOW/macros/AddTaskCMWESE.C

Fix a little bug in the code of CMWESE for 18r.

[PWG-CF] Fix a bug for 18r

---

PWGLF/RESONANCES/PostProcessing/f0980/AliAnalysisTaskInclusivef0f2.cxx

[PWGLF] turning off print

---

PWGDQ/reducedTree/macros/AddTask_TrainTreeAnalysis.C

Add "file:" before the local file path when using the alien_cp.

A small fix about the file path of alien_cp

---

PWGLF/RESONANCES/PostProcessing/f0980/AliAnalysisTaskInclusivef0f2.cxx

[PWGLF] reduction of bin numbers

---

PWGHF/vertexingHF/AliAnalysisTaskSEXicPlus2XiPiPifromAODtracks.cxx
PWGHF/vertexingHF/AliAnalysisTaskSEXicPlus2XiPiPifromAODtracks.h
PWGHF/vertexingHF/macros/AddTaskXicPlus2XiPiPifromAODtracks.C

I add some event variables in the tree for off-line tree analysis.
In the AddTask, I add the HMSPD trigger.

Add the event variables in the tree

---

PWGDQ/dielectron/LMEE/AliAnalysisTaskLMeeCocktailMC.cxx
PWGDQ/dielectron/LMEE/AliAnalysisTaskLMeeCocktailMC.h
PWGDQ/dielectron/macrosLMEE/AddTask_LMeeCocktailMC.C

- pi0 dip investigation
-- comment around L772:
// Not sure about this cut. From GammaConv group. Harmless a priori.
if (!(fabs(particle->E()-particle->Pz())>0.)) continue;
-- check rapidity cut on mother particle

PWGDQ/LMEE:Added option, to apply rapidity cut on mother particle

---

PWGCF/FEMTOSCOPY/macros/AddTaskFemtoNanoLKr.C

config->SetPtQA(true);
config->SetMassQA(true); config->SetExtendedQAPairs(pairQA); 
Commented

Comments for Systematics

---

PWGCF/FEMTOSCOPY/AliFemto/AliAnalysisTaskFemto.cxx
PWGCF/FEMTOSCOPY/AliFemto/AliFemtoBasicEventCut.cxx
PWGCF/FEMTOSCOPY/AliFemto/AliFemtoCutMonitorEventMult.cxx
PWGCF/FEMTOSCOPY/AliFemto/AliFemtoCutMonitorEventMult.h
PWGCF/FEMTOSCOPY/AliFemto/AliFemtoEvent.h
PWGCF/FEMTOSCOPY/AliFemto/AliFemtoEventReaderAOD.cxx
PWGCF/FEMTOSCOPY/AliFemto/AliFemtoEventReaderAOD.h
PWGCF/FEMTOSCOPY/AliFemto/AliFemtoSimpleAnalysisOnlyMixP1.cxx

**Nothing changed** in AliAnalysisTaskFemto.cxx & AliFemtoBasicEventCut.cxx !!!

dowang[PWGCF] fix store type of run number & add run number QA

---

PWGHF/vertexingHF/AliAnalysisTaskSESemileptonicOmegac0KFP.cxx
PWGHF/vertexingHF/AliAnalysisTaskSESemileptonicOmegac0KFP.h

1) Change TObjArray to TVector for electrons

New ME method is used now

---

PWGHF/vertexingHF/AliCFTaskVertexingHF.cxx
PWGHF/vertexingHF/AliCFTaskVertexingHF.h

Hi,
I'm creating again a pull request related to the D0 pt weights in pp @ 13 TeV with PYTHIA8 and FONLL, after discarding Laszlo's latest commits in AliCFTaskVertexingHF.cxx/h and fixing a bug.
Thanks

 D0 pT weights @ 13 TeV with PYTHIA 8 and FONLL - bug fixed

---

PWGCF/FLOW/GF/AliAnalysisTaskMeanPtV2Corr.cxx
PWGCF/FLOW/macros/AddTaskMeanPtV2Corr.C

Apparently TFiles struggle to be connected as task inputs.

MeanPtV2: moved from TFile to TList for efficiency inputs. 

---

PWG/FLOW/Tasks/AliAnalysisTaskCMWESE.cxx
PWG/FLOW/Tasks/AliAnalysisTaskCMWESE.h
PWG/FLOW/Tasks/AliAnalysisTaskEPCalib.cxx
PWGCF/FLOW/macros/AddTaskCMWESE.C
PWGCF/FLOW/macros/AddTaskEPCalib.C

This version aims to do the event-wise syst. estimation and  fill the NUA input files for 18q/r

[PWG-CF] CMWESE 18 Syst

---

PWGGA/EMCALTasks/AliAnalysisTaskGammaHadron.cxx
PWGGA/EMCALTasks/AliAnalysisTaskGammaHadron.h

Add option for changing event plane source to V0A or V0M

Add option for changing event plane source to V0A or V0M

---

PWGHF/vertexingHF/vHFML/AliAnalysisTaskSEHFTreeCreatorApply.cxx

PWGHF: Fix for mixed event

---

PWGHF/vertexingHF/AliAnalysisTaskSESemileptonicOmegac0KFP.cxx

1) Fix double entry in TVector
2) isdca should be kFALSE

some changes for ME

---

PWGCF/Correlations/JCORRAN/Pro/AliJCDijetAna.cxx
PWGCF/Correlations/JCORRAN/Pro/AliJCDijetAna.h
PWGCF/Correlations/JCORRAN/Pro/AliJCDijetHistos.cxx
PWGCF/Correlations/JCORRAN/Pro/AliJCDijetHistos.h
PWGCF/Correlations/JCORRAN/Pro/AliJCDijetTask.cxx

Added a possibility to weight certain functions.

---

PWGMM/UE/UeKNO/AliAnalysisTaskChargedVsRT.cxx
PWGMM/UE/UeKNO/AliAnalysisTaskChargedVsRT.h

The filling of the response matrix was modified to exclude neutral particles

To correct response matrix

---

PWGLF/RESONANCES/PostProcessing/f0980/AliAnalysisTaskInclusivef0f2.cxx

[PWGLF] reduction of memory usage

---

PWGHF/vertexingHF/AliAnalysisTaskSEXicPlus2XiPiPifromAODtracks.cxx
PWGHF/vertexingHF/macros/AddTaskXicPlus2XiPiPifromAODtracks.C

I added the trigger flags in analysis tree and event tree to check the fired trigger of events.
And made the event information to be stored in corresponding counters which I added before.

Add Trigger flags in tree and Store the events in counter

---

PWGCF/EBYE/MultPt/AliAnalysisMultPt.cxx
PWGCF/EBYE/MultPt/AliAnalysisMultPt.h
PWGCF/EBYE/MultPt/macros/AddMultPt.C

Cuts added

---

PWGLF/RESONANCES/PostProcessing/f0980/AliAnalysisTaskInclusivef0f2.cxx

[PWGLF] reduce memory usage

---

PWGLF/RESONANCES/PostProcessing/f0980/AliAnalysisTaskInclusivef0f2.cxx

[PWGLF] fix a bug 

---

PWG/FLOW/Tasks/AliAnalysisTaskCMWESE.cxx
PWG/FLOW/Tasks/AliAnalysisTaskEPCalib.cxx

This version of the code is to fix a little bug when entering into the calculation of dca.

[PWG-CF] fix a little Bug

---

PWGCF/Correlations/DPhi/AliAnalysisTaskCorrelGen.cxx
PWGCF/Correlations/DPhi/AliAnalysisTaskCorrelGen.h
PWGCF/Correlations/DPhi/CMakeLists.txt
PWGCF/Correlations/DPhi/PWGCFCorrelationsDPhiLinkDef.h
PWGCF/Correlations/macros/AddTaskCorrelGen.C

TaskGendih

---

PWGLF/RESONANCES/PostProcessing/f0980/AliAnalysisTaskInclusivef0f2.cxx

[PWGLF] no systematics mode

---

PWGGA/EMCALTasks/AliAnalysisTaskGammaHadron.cxx
PWGGA/EMCALTasks/macros/AddTaskGammaHadron.C

Update macro for current alien_cp behavior
Lower minimum cluster energy range in Pi0Cand THnSparse

Update macro for current alien_cp behavior

---

PWGLF/RESONANCES/PostProcessing/f0980/AliAnalysisTaskInclusivef0f2.cxx

[PWGLF] add different switches

---

PWG/FLOW/Tasks/AliAnalysisTaskCMWESE.cxx
PWG/FLOW/Tasks/AliAnalysisTaskCMWESE.h
PWGCF/FLOW/macros/AddTaskCMWESE.C

This version of code has 2 updates:
1. Add input files paths for track-wise NUA
2. Add pt/Eta vs. Ach plots

[PWG-CF] Syst input file path

---

PWGGA/EMCALTasks/macros/AddTaskGammaHadron.C

Fixes an error in the error message

Fixes an error in the error message

---

PWGDQ/dielectron/core/AliDielectronVarManager.h

Removing warning generated for each MC AOD track

remove superfluous warning messages to decrease log size

---

PWGLF/NUCLEX/Exotica/Dibaryons/AliAnalysisTaskMSDibaryons.cxx

This is the test for pull request.
This sauce file is for H and N-Omega dibaryons reconstructions.

Multi-strange dibaryon for pp, pPb data

---

PWGMM/UE/UeKNO/AliAnalysisTaskChargedVsRT.cxx
PWGMM/UE/UeKNO/AliAnalysisTaskChargedVsRT.h

Added a flag to avoid noises in the distribution of true multiplicity

To correct true multiplicity distribution

---

PWGHF/vertexingHF/AliAnalysisTaskSESemileptonicOmegac0KFP.cxx
PWGHF/vertexingHF/AliRDHFCutsOmegactoeleOmegafromKFP.cxx

1) Add new branches in ME tree
2) Release cuts in AliRDHF.. task, which will be optimized in ML step

Preparation for ML

---

PWGCF/EBYE/MeanPtFluctuations_PbPb5020GeV2018/AliAnalysisMeanPtdata.cxx
PWGCF/EBYE/MeanPtFluctuations_PbPb5020GeV2018/AliAnalysisMeanPtdata.h
PWGCF/EBYE/macros/AddTaskMptFluct.C

Minor changes in the authorship

Update on Mean pT fluctuation class and macro in 5.02 TeV

---

PWGLF/SPECTRA/CMakeLists.txt
PWGLF/SPECTRA/PWGLFspectraLinkDef.h
PWGLF/SPECTRA/PiKaPr/TPCTOF/AliAnalysisTaskAntiProtons_vs_Rapidity_Data.cxx
PWGLF/SPECTRA/PiKaPr/TPCTOF/AliAnalysisTaskAntiProtons_vs_Rapidity_Data.h
PWGLF/SPECTRA/PiKaPr/TPCTOF/AliAnalysisTaskAntiProtons_vs_Rapidity_Simu.cxx
PWGLF/SPECTRA/PiKaPr/TPCTOF/AliAnalysisTaskAntiProtons_vs_Rapidity_Simu.h

Analysis task used to measure antiproton spectra vs. rapidity

Antiprotons vs. y

---

PWG/FLOW/Tasks/AliAnalysisTaskGammaDeltaPID.cxx

Bug-fix: uncomment TPC Q vector recentering

Bug-fix: uncomment TPC Q vector recentering

---

PWGGA/GammaConv/AliAnalysisTaskGammaCalo.cxx
PWGGA/GammaConv/AliAnalysisTaskGammaCalo.h

- removing unnecessary clear() and reinitialization of vectors
- Storing matched rec. and true jet in map in order to acces them later

PWGGA/GammaConv: Adding rotation background to in-Jet analysis

---

PWGGA/EMCALTasks/AliAnalysisTaskGammaHadron.cxx
PWGGA/EMCALTasks/AliAnalysisTaskGammaHadron.h

Fixes event mixing crash bug related to the event plane angle and a missing check.
Adds 18qrP1 efficiency correction
Adds QnScale vs Angle hists

Fixes event mixing crash bug, updates efficiency

---

PWGPP/TPC/AliTPCPIDBase.cxx
PWGPP/TPC/AliTPCPIDEtaQA.cxx
PWGPP/TPC/AliTPCPIDEtaQA.h
PWGPP/TPC/AliTPCcalibResidualPID.cxx
PWGPP/TPC/macros/AddTaskTPCPIDEtaQA.C
PWGPP/TPC/macros/AddTaskTPCPIDEtaTree.C

Make PID classes (AliTPCcalibResidualPID, TPCPIDEtaQA, TPCPIDEtaTree) and its macros ROOT6 ready, small code improvements

Make PID classes ready for ROOT6

---

PWGJE/EMCALJetTasks/AliAnalysisTaskJetChargeFlavourTemplates.cxx
PWGJE/EMCALJetTasks/AliAnalysisTaskJetChargeFlavourTemplates.h

2 new Techniques for determing jet PDG Code,
Original technique + Pt Selection
Geomatric parton Cut

Added a New Technique for determining he intial parton of the jet

---

PWGGA/GammaConv/AliAnalysisTaskGammaPureMC.cxx
PWGGA/GammaConv/AliAnalysisTaskGammaPureMC.h
PWGGA/GammaConv/macros/AddTask_GammaPureMC.C

- Histograms added for possibility of multiplicity dependent studies on
MC generator.
- Mult estimation using primary charged particles in V0 acceptance

PWGGA/GammaConv: Adding histograms for part. pt vs V0 mult

---

PWGHF/vertexingHF/AliAnalysisTaskSEXicTopKpi.cxx

Pleas enter the commit message for your changes. Lines starting

Extending two 4prong sparse axes.

---

PWGGA/GammaConv/AliAnalysisTaskGammaPureMC.cxx
PWGGA/GammaConv/AliAnalysisTaskGammaPureMC.h

filled and not only for specific decay channel
- Added condition that it has to be in eta < 0.8 and particle has to be
primary.

PWGGA/GammaConv: Moved mult dependent histos such that they are always

---

PWGLF/RESONANCES/PostProcessing/f0980/AliAnalysisTaskInclusivef0f2.cxx

[PWGLF] fix bug

---

PWGCF/Correlations/DPhi/AliAnalysisTaskSEpPbCorrelationsJetV2Kine.cxx
PWGCF/Correlations/macros/pPbCorrelations/AddTaskSEpPbCorrelationsJetV2Kine.C

Dear all,
Please help to approve this update, which is for the update related to the jet v2 analysis of AMPT production.
Thanks a lot!
Siyu

Update for jet v2 AMPT

---

PWGCF/Correlations/DPhi/AliAnalysisTaskSEpPbCorrelationsJetV2Kine.cxx
PWGCF/Correlations/DPhi/AliAnalysisTaskSEpPbCorrelationsJetV2Kine.h

Dear all,
Here is a further updates about the rapidity shift in AMPT analysis. Please approve it.
Thanks!
Siyu

Update rapidity shift

---

PWGCF/Correlations/macros/AddTaskV0ChCorrelationppsys.C
PWGCF/Correlations/macros/AddTaskV0ChCorrelationsys.C

Transition to ROOT6

---

PWG/FLOW/Tasks/AliAnalysisTaskCMWESE.cxx

Updated 2 lines for the trigger check in central and semicentral ranges for 18q/18r datasets.

[PWG-CG] Trigger Check

---

PWGGA/GammaConv/AliAnalysisTaskGammaConvCalo.cxx

- index was from rec. jet whereas the vector was for true jets

PWGGA/GammaConv: Fixed vector out of range

---

PWGDQ/dielectron/macrosLMEE/AddTask_jjung_efficiency.C

Fixing issues in my AddTask foe efficiencies

PWGEM:LMee: Update personal AddTasks

---

PWGMM/UE/UeKNO/AddTaskChargedVsRT.C
PWGMM/UE/UeKNO/AliAnalysisTaskChargedVsRT.cxx
PWGMM/UE/UeKNO/AliAnalysisTaskChargedVsRT.h

A new parameter was added in order to modify the binning of PbPb collisions.

To modify the binning of PbPb collisions

---

PWG/FLOW/Tasks/AliAnalysisTaskCMWESE.cxx
PWGCF/FLOW/macros/AddTaskCMWESE.C

This version tuned the path for syst for CMWESE analysis.

[PWG-CF] Tune Path for Syst

---

PWGCF/FLOW/GF/AliAnalysisTaskCorrForFlowFMD.cxx
PWGCF/FLOW/GF/AliAnalysisTaskCorrForFlowFMD.h

For generated AMPT with FMD (LHC19h12)

Lorentz boost

---

PWGLF/RESONANCES/macros/mini/AddTaskResonanceFinder.C

adding values for certain cuts to be able to pass them as parameters on the train

Add values for Ps analysis systematics

---

PWGGA/EMCALTasks/AliAnalysisTaskGammaHadron.cxx
PWGGA/EMCALTasks/AliAnalysisTaskGammaHadron.h

Done by moving loading of QnVectors to IsEventSelected

Removes events where q2 vector = 0 exactly

---

PWGHF/correlationHF/AliAnalysisTaskSELambdacCorrelations.cxx

Mass axis range has been modified. Also modified for the case that only ML selected candidates will perform correlation analysis.

correction on correlation calculation

---

PWGDQ/dielectron/LMEE/AliAnalysisTaskBeauty.cxx
PWGDQ/dielectron/LMEE/AliAnalysisTaskCharm.cxx

Opening angle check for HF

---

PWGGA/GammaConv/macros/AddTask_GammaCalo_pp.C
PWGGA/GammaConvBase/AliConvEventCuts.cxx
PWGGA/GammaConvBase/AliConvEventCuts.h

- Needed for EMCal efficiency studies as function of charged particle
multiplicity

PWGGA/GammaConv: Added option to slice in EMCal cluster multiplicity

---

PWGUD/UPC/nanoAOD/AliAnalysisTaskCentralTau.cxx

STG offline decision check routine was moved in the task resulting in fixing a bug

Central Tau analysis

---

PWGUD/UPC/nanoAOD/AliAnalysisTaskCentralTau.h

just increasing class number...

CentralTau task

---

PWGLF/RESONANCES/macros/mini/AddTaskResonanceFinder.C

make sure input parameter for proton PID doesn't conflict with MC parameter

update variable for systematic parameters

---

PWGGA/EMCALTasks/AliAnalysisTaskGammaHadron.cxx
PWGGA/EMCALTasks/AliAnalysisTaskGammaHadron.h

Adds tracking efficiency correction for 15o pass2

Adds tracking efficiency correction for 15o pass2

---

PWGJE/EMCALJetTasks/UserTasks/AliAnalysisTaskMTFPID.cxx
PWGJE/EMCALJetTasks/UserTasks/AliAnalysisTaskMTFPID.h
PWGJE/macros/AddTaskMTFPID.C

Adding possibility to differentiate multiplicity systematic variation by momentum threshold.

MTF: Improvement for mult systematics

---

PWGCF/EBYE/MultPt/AliAnalysisMultPt.cxx
PWGCF/EBYE/MultPt/AliAnalysisMultPt.h
PWGCF/EBYE/MultPt/macros/AddMultPt.C

Void functions added 

---

PWGCF/Correlations/KaonCorrelations/AliAnalysisTaskKaon2PC.cxx
PWGCF/Correlations/KaonCorrelations/AliAnalysisTaskKaon2PC.h

Fixed a bug related to the initialization of histograms. Testing to see if the train test would be successful.

fixed a bug and testing if the train test would be successful

---

PWGLF/RESONANCES/macros/mini/ConfigLStar_PbPb2018.C

I have modified the loop for enabling MC invariant mass in single and mixed events on line 120.

Update ConfigLStar_PbPb2018 task

---

PWGHF/vertexingHF/AliAnalysisTaskHFSimpleVertices.cxx
PWGHF/vertexingHF/AliAnalysisTaskHFSimpleVertices.h

- Fix binning, acceptance cut, Lc MC
- Fix info messages
- Fix compilation errors
- Format with `clang-format`

PWGHF: Fix HFSimpleVertices

---

PWGMM/UE/UeKNO/AliAnalysisTaskChargedVsRT.h

Update on systematic uncertainty calculation for Nch vs RT

---

PWGHF/vertexingHF/AliAnalysisTaskSEXicPlus2XiPiPifromAODtracks.cxx

I masked out the event tree to reduce the output file size.
For now, It is somehow hard-corded, but I will fix it soon.

Modify the event tree

---

PWG/FLOW/Tasks/AliAnalysisTaskCMWESE.cxx

A little change for the cut for pile-up syst.

[PWG-CF]Tight Pile Up

---

PWG/JETFW/AliJetContainer.cxx
PWGJE/EMCALJetTasks/AliAnalysisTaskRho.cxx

- Load rho values automatically if container links are
specified
- Raise error message in case no jet container is linked
in the rho task

Automatized rho handling in JetContainer

---

PWGJE/EMCALJetTasks/CMakeLists.txt
PWGJE/EMCALJetTasks/PWGJEEMCALJetTasksLinkDef.h
PWGJE/EMCALJetTasks/UserTasks/AliAnalysisTaskEmcalJetProperties.cxx
PWGJE/EMCALJetTasks/UserTasks/AliAnalysisTaskEmcalJetProperties.h
PWGJE/EMCALJetTasks/macros/AddTaskEmcalJetProperties.C

This PR contains a jet properties analysis task from Debjani @bdebjani

Initial commit of jet properties task from Debjani

---

PWGGA/EMCALTasks/AliAnalysisTaskGammaHadron.cxx
PWGGA/EMCALTasks/AliAnalysisTaskGammaHadron.h

Adds flag to disable centrality cuts in MC. Necessary for particular MCs in PbPb periods.

Adds flag to disable centrality cuts in MC

---

PWGHF/hfe/AliAnalysisTaskCaloHFEpp.cxx

open eta cut to calculate Z->ee mass

AliAnalysisTaskCaloHFEpp.cxx

---

PWGLF/SPECTRA/MultEvShape/AliMESeventInfo.cxx
PWGLF/SPECTRA/MultEvShape/AliMESpidTask.cxx
PWGLF/SPECTRA/MultEvShape/AliMESppColTask.cxx
PWGLF/SPECTRA/MultEvShape/AliMEStender.cxx
PWGLF/SPECTRA/MultEvShape/AliMEStender.h
PWGLF/SPECTRA/MultEvShape/AliMEStrackInfo.cxx
PWGLF/SPECTRA/MultEvShape/AliMEStrackInfo.h
PWGLF/SPECTRA/MultEvShape/run.C

Added the possibility to run with both MB and HM triggers

Major modifications for 13TeV running

---

PWG/EMCAL/EMCALtasks/AliEmcalRejectMCBackground.cxx
PWG/EMCAL/EMCALtasks/AliEmcalRejectMCBackground.h
PWG/EMCAL/macros/AddTaskRejectMCBackground.C

PWG/EMCAL: Adding macro for MC Rejection for EPOS/other background

PWG/EMCAL: Adding MC Rejection for EPOS/other background

---

PWGMM/UE/UeKNO/AddTaskChargedVsRT.C
PWGMM/UE/UeKNO/AliAnalysisTaskChargedVsRT.cxx
PWGMM/UE/UeKNO/AliAnalysisTaskChargedVsRT.h

The choice of V0 for multiplicity estimation for p-Pb collisions was modified.

To modify the choice of V0

---

PWGHF/vertexingHF/vHFML/AliAnalysisTaskSEDs.cxx
PWGHF/vertexingHF/vHFML/AliHFMLVarHandlerDstoKKpi.cxx
PWGHF/vertexingHF/vHFML/AliHFMLVarHandlerDstoKKpi.h

@stefanopolitano please have a look

Add tag for D+ -> Kpipi in Ds tree

---

PWG/EMCAL/EMCALtasks/AliEmcalRejectMCBackground.cxx
PWG/EMCAL/EMCALtasks/AliEmcalRejectMCBackground.h
PWG/EMCAL/EMCALtasks/CMakeLists.txt
PWG/EMCAL/EMCALtasks/PWGEMCALtasksLinkDef.h

PWG/EMCAL/EMCALtasks Edits to MC BG sub and add to CMakeLists and LinkDef

PWG/EMCAL/EMCALtasks Edits to MC BG sub and add to CMakeLists and LinkDef

---

PWGCF/Correlations/JCORRAN/Pro/AliJCDijetTask.cxx
PWGCF/Correlations/JCORRAN/Pro/AliJCDijetTask.h

Now the code can reject detector MC and still run true MC (or vice
versa) if the event selection happens to indicate so, and previously
it was not possible.

Modified how the code uses event selection

---

PWGCF/Correlations/JCORRAN/Pro/AliJCDijetTask.cxx
PWGCF/Correlations/JCORRAN/Pro/AliJCDijetTask.h

If we find jet pt>4*pt_hard we want to discard the whole event,
including the true MC.

A minor fix for event selection

---

PWGDQ/dielectron/CMakeLists.txt
PWGDQ/dielectron/LMEE/AliAnalysisTaskOmegaDielectron_AccEff.cxx
PWGDQ/dielectron/LMEE/AliAnalysisTaskOmegaDielectron_AccEff.h
PWGDQ/dielectron/PWGDQdielectronLinkDef.h
PWGDQ/dielectron/macrosLMEE/AddMyTask_mwaelde_AcceptanceEfficiency.C

A new task to analyse omega production in the dielectron channel.

Add Omega task for dielectrons

---

PWG/EMCAL/EMCALtasks/AliEmcalMCTrackSelector.cxx
PWG/EMCAL/EMCALtasks/AliEmcalMCTrackSelector.h
PWG/EMCAL/EMCALtasks/AliEmcalRejectMCBackground.cxx
PWG/EMCAL/EMCALtasks/AliEmcalRejectMCBackground.h
PWG/EMCAL/macros/AddTaskMCTrackSelector.C
PWG/EMCAL/macros/AddTaskRejectMCBackground.C

PWG/EMCAL Adding option for pre-specified track container in AliEmcalMCTrackSelector

PWG/EMCAL Adding option for pre-specified track container in AliEmcalMCTrackSelector

---

PWGGA/EMCALTasks/AliAnalysisTaskGammaHadron.cxx
PWGGA/EMCALTasks/AliAnalysisTaskGammaHadron.h

Adds trigger string based requirement for EMCal triggers. Allows selection of EG1, DG1, etc in data without EmcalTriggerDecision maker.

Adds trigger string based requirement for EMCal triggers

---

PWGHF/vertexingHF/AliAnalysisTaskSEXicPlus2XiPiPifromAODtracks.cxx
PWGHF/vertexingHF/AliAnalysisTaskSEXicPlus2XiPiPifromAODtracks.h
PWGHF/vertexingHF/macros/AddTaskXicPlus2XiPiPifromAODtracks.C

Minor debug of defining the output
Add the option to switch on and off the event tree
Add the histograms to check the cut variables in offline tree analysis stage

Add cut variables histograms and option for writing the event info.

---

PWGGA/EMCALTasks/AliAnalysisTaskGammaHadron.cxx
PWGGA/EMCALTasks/AliAnalysisTaskGammaHadron.h

Adds two options for removing pileup, and another histogram

Adds two options for removing pileup, and another histogram

---

PWGHF/vertexingHF/macros/AddTaskXicPlus2XiPiPifromAODtracks.C

Minor debug on addtask

---

PWGCF/Correlations/KaonCorrelations/AliAnalysisTaskKaon2PC.cxx
PWGCF/Correlations/KaonCorrelations/AliAnalysisTaskKaon2PC.h

Removed two histograms no longer needed, Improved K0 signal,Added fClusters histogram.

Updated the codes

---

PWGHF/vertexingHF/AliAnalysisTaskSEXicPlus2XiPiPifromAODtracks.cxx

Minor bug on the writing the tree for MC part is fixed.

Fixed Minor bug on MC loop

---

PWGJE/EMCALJetTasks/UserTasks/AliAnalysisTaskEPCalibForJet.cxx
PWGJE/EMCALJetTasks/UserTasks/AliAnalysisTaskEPCalibForJet.h

Now I am facing a strange error on the train run. So I return my task to most simple one

test starange train error

---

PWGCF/FEMTOSCOPY/AliFemtoUser/AliAnalysisTaskParticleEffDY.cxx

Improved EfficiencyTaks for different FilterBits

Upgrade EffTask

---

PWGCF/FLOW/GF/AliAnalysisTaskNonlinearFlow.cxx

+ Add Two particle correlation with Gap0
+ Change XeXe Cuts
+ Change centrality binning

[PAG-Flow] Modifications

---

PWGJE/PWGJE/AliAnalysisTaskJetFFMoments.cxx

[PWGJE] AliAnalysisTaskJetFFMoments: fixing race condition when running on

---

PWGLF/NUCLEX/Exotica/Dibaryons/AddTaskMSDibaryons.C
PWGLF/NUCLEX/Exotica/Dibaryons/AliAnalysisTaskMSDibaryons.cxx
PWGLF/NUCLEX/Exotica/Dibaryons/AliAnalysisTaskMSDibaryons.h

Train test for PbPb 

---

PWGJE/EMCALJetTasks/Tracks/AliAnalysisTaskEmcalJetEnergyScale.cxx

PWGJE/EMCALJetTasks/Tracks Adding protection from zero division

PWGJE/EMCALJetTasks/Tracks Adding protection from zero division

---

PWGGA/GammaConv/AliAnalysisTaskGammaConvCalo.cxx
PWGGA/GammaConv/macros/AddTask_GammaCalo_pp.C
PWGGA/GammaConv/macros/AddTask_GammaConvCalo_pp.C
PWGGA/GammaConvBase/AliConversionMesonCuts.cxx
PWGGA/GammaConvBase/AliConversionMesonCuts.h

implementing a meson categorization w.r.t the particle with the hight pt (leading) in the event
Added MesonLeadTrackSelection function to test it additionaly to is meson selected.
It was not possible to include it in IsMesonSelected because no event is availible here for data

 PWGGA/GammaConv :  leading particle study

---

PWGGA/GammaConv/macros/AddTask_GammaCalo_pp.C

- leading particle study implemented here: https://github.com/alisw/AliPhysics/pull/21008

PWGGA/GammaConv: Added cuts for leading particle study

---

PWGCF/FLOW/GF/AliAnalysisTaskCorrForNonlinearFlow.cxx
PWGCF/FLOW/GF/AliAnalysisTaskCorrForNonlinearFlow.h

To ensure a correct normalization

[PAG-Flow] Change pt dependent Trigger particle number to Mult dependent

---

PWGGA/GammaConv/AliAnalysisTaskGammaIsoTree.cxx
PWGGA/GammaConv/macros/AddTask_GammaIsoTree.C
PWGGA/GammaConvBase/AliCaloPhotonCuts.cxx

- added saving of true MC info even if not true photon
- looser TM window to allow for further selection offline

PWGGA/GammaConv: change of TM and MC tags for iso tree task

---

PWGCF/FEMTOSCOPY/macros/AddTaskFemtoNanoLKr.C

Uncommented lines: 
if (suffix == "0") {
config->SetPtQA(true);
config->SetMassQA(true);
config->SetkTBinning(true);
config->SetMultBinning(true);
config->SetmTBinning(true);
}

QA plots added for AN

---

PWGGA/GammaConvBase/AliConversionMesonCuts.cxx

Fix AliConversionMesonCuts::MesonLeadTrackSelectionBase for light out put without mesonQA switched on

 PWGGA/GammaConv Fix AliConversionMesonCuts::MesonLeadTrackSelectionBase

---

PWGPP/TPC/macros/PIDCalib/MakeTPCPIDResponseOADB.C

* update LHC16d HLT  pass2
* add 16e,f,g,(hi),j,(op) pass2
* add 16k,l pass3

TPC: Add/update splines and eta maps for LHC16X

---

PWGCF/FEMTOSCOPY/macros/Train/pPbKKfemto/exp/conf/NMixEv/NMixEv10/ConfigFemtoAnalysis.C
PWGCF/FEMTOSCOPY/macros/Train/pPbKKfemto/exp/conf/NMixEv/NMixEv3/ConfigFemtoAnalysis.C
PWGCF/FEMTOSCOPY/macros/Train/pPbKKfemto/exp/conf/NMixEv/NMixEv7/ConfigFemtoAnalysis.C
PWGCF/FEMTOSCOPY/macros/Train/pPbKKfemto/exp/conf/TTC/TTC_2/ConfigFemtoAnalysis.C
PWGCF/FEMTOSCOPY/macros/Train/pPbKKfemto/exp/conf/TTC/TTC_6/ConfigFemtoAnalysis.C
PWGCF/FEMTOSCOPY/macros/Train/pPbKKfemto/exp/conf/zvertex/zvertex11/ConfigFemtoAnalysis.C
PWGCF/FEMTOSCOPY/macros/Train/pPbKKfemto/exp/conf/zvertex/zvertex9/ConfigFemtoAnalysis.C

‘3D_configs’

---

PWGGA/GammaConv/AliAnalysisTaskGammaCalo.cxx
PWGGA/GammaConvBase/AliConvEventCuts.cxx
PWGGA/GammaConvBase/AliConvEventCuts.h

- Added period enum for LHC17 5TeV Phojet MC

PWGGA/GammaConv: Add possibility to do leading track pt study in Calo task

---

PWGCF/FLOW/GF/AliAnalysisTaskJetQ.cxx
PWGCF/FLOW/GF/AliAnalysisTaskJetQ.h
PWGCF/FLOW/GF/AliGFW.cxx
PWGCF/FLOW/GF/AliGFW.h

AliGFW: Added functionality to consider a given pt bin as "reference" so one can easier calculate things such as v[x]. Added all possible pt-configurations for 2PC in JetQ task.

Extending functionality of AliGFW

---

PWGLF/RESONANCES/PostProcessing/f0980/AliAnalysisTaskInclusivef0f2.cxx

[PWGLF] add low pt mode

---

PWGCF/EBYE/NetLambda/AliAnalysisTaskNetLambdaIdent.cxx
PWGCF/EBYE/NetLambda/AliAnalysisTaskNetLambdaIdent.h
PWGCF/EBYE/PWGCFebyeLinkDef.h

Adding cascades to AliAnalysisTaskNetLambdaIdent.cxx.

Adding cascades to Net Lambda tree.

---

PWGDQ/dielectron/LMEE/AliAnalysisTaskCharm.cxx
PWGDQ/dielectron/macrosLMEE/AddTaskCharm.C

Update the analysis task of charm to be able to weight as a product (and not a mean) the CNM(RAA) of D mesons

Update the analysis task of charm 

---

PWGHF/vertexingHF/AliAnalysisTaskHFSimpleVertices.cxx

Propagated from https://github.com/AliceO2Group/O2Physics/pull/941

PWGHF: Fix names of Ds skimming arrays

---

PWGCF/FLOW/GF/AliAnalysisTaskNonlinearFlow.cxx
PWGCF/FLOW/GF/AliAnalysisTaskNonlinearFlow.h

+ Add centrality cut (for pp V0M < 0.1)
+ Add QA for DCA, TPC2perCluster
+ Fix AliGFWCuts for LHC17n

[PAG-Flow] Changes as following:

---

PWGHF/vertexingHF/AliAnalysisTaskHFSimpleVertices.cxx
PWGHF/vertexingHF/AliAnalysisTaskHFSimpleVertices.h

- Adding Lc daughters impact parameters histos.
- Simplification of the Lc selection code. Now it is consistent with the O2 workflow.

PWGHF: Adding Lc histos and simplification of the Lc selection code

---

PWGJE/EMCALJetTasks/UserTasks/AliAnalysisTaskIDFragmentationFunction.cxx
PWGJE/EMCALJetTasks/UserTasks/AliAnalysisTaskIDFragmentationFunction.h
PWGJE/macros/AddTaskIDFragmentationFunction.C

Fixes a bug in the systematic variation, add some logging, fix some bugs in the AddTask

MTF: fix lowpt enhancement

---

PWG/EMCAL/EMCALtasks/AliEmcalRejectMCBackground.cxx

PWG/EMCAL/EMCALtasks/AliEmcalRejectMCBackground.cxx Adding additional handling for pythia headers

PWG/EMCAL/EMCALtasks/AliEmcalRejectMCBackground.cxx Adding additional handling for pythia headers

---

PWGGA/GammaConv/macros/AddTask_MesonJetCorr_Calo.C
PWGGA/GammaConv/macros/AddTask_MesonJetCorr_Conv.C
PWGGA/GammaConv/macros/AddTask_MesonJetCorr_ConvCalo.C

- 'No newline at the end of file' failed the AddTask on the grid

PWGGA/GammaConv: Formatting fix in MesonJet Add tasks

---

PWGLF/RESONANCES/extra/AddTaskAODTrackPair.C
PWGLF/RESONANCES/extra/AliAnalysisTaskAODTrackPair.cxx

Fixed the bugs to select event mixing pool.

Modified bugs related to event mixing pool

---

PWGGA/GammaConv/AliAnalysisTaskMesonJetCorrelation.cxx
PWGGA/GammaConv/AliAnalysisTaskMesonJetCorrelation.h
PWGGA/GammaConv/macros/AddTask_MesonJetCorr_Calo.C
PWGGA/GammaConv/macros/AddTask_MesonJetCorr_Conv.C
PWGGA/GammaConv/macros/AddTask_MesonJetCorr_ConvCalo.C
PWGGA/GammaConvBase/AliGammaConvEventMixing.cxx
PWGGA/GammaConvBase/AliGammaConvEventMixing.h
PWGGA/GammaConvBase/AliResponseMatrixHelper.h

- Event mixing background class now using smart pointers
- Delete clusters etc. created with new
- Enable flag to use THnSparse
- Fix train configs for rotation and mixed evt. (configs were swapped)

PWGGA/GammaConv: Fix memory leak in MesonJetCorr

---

PWGHF/vertexingHF/AliAnalysisTaskHFSimpleVertices.cxx

Analogous change to what Luigi did for Lc in https://github.com/alisw/AliPhysics/pull/21124

PWGHF: Simplify D0 selection to match O2Physics

---

PWGHF/vertexingHF/AliAnalysisTaskHFSimpleVertices.cxx

... follow up to https://github.com/alisw/AliPhysics/pull/21168

PWGHF: Remove double filling of 2 prong 2-vertex histograms

---

PWGMM/UE/UeKNO/AliAnalysisTaskFlatenicity.cxx
PWGMM/UE/UeKNO/AliAnalysisTaskFlatenicity.h

adding new histos

---

PWGGA/GammaConv/AliAnalysisTaskMesonJetCorrelation.cxx
PWGGA/GammaConv/AliAnalysisTaskMesonJetCorrelation.h
PWGGA/GammaConvBase/AliResponseMatrixHelper.cxx
PWGGA/GammaConvBase/AliResponseMatrixHelper.h

- Added histograms related to JJ-MC weights monitoring
- True meson inv mass vs. pt and z as function of jet pt
- Add histograms for accepted mesons (inv mass vs. pt/z)

PWGGA/GammaConv: Extend true meson histograms as function of jet pt

---

PWGCF/Correlations/KaonCorrelations/AliAnalysisTaskKaon2PC.cxx
PWGCF/Correlations/KaonCorrelations/AliAnalysisTaskKaon2PC.h

Added phi and pt distributions for the neutral kaon particles and also for the pion daughters of each reconstructed kaons. Also, using a wider pT range. (0.2 to 0.5 --> 0.2 to 1.0)

Updated the code with QA histograms

---

PWGLF/RESONANCES/PostProcessing/f0980/AliAnalysisTaskInclusivef0f2.cxx

[PWGLF] updates on UPC mode

---

PWG/EMCAL/EMCALtasks/AliEmcalRejectMCBackground.cxx

PWG/EMCAL/EMCALtasks/AliEmcalRejectMCBackground.cxx Fixing memory leak in track and cluster loops.

PWG/EMCAL/EMCALtasks/AliEmcalRejectMCBackground.cxx Fixing memory leak in track and cluster loops.

---

PWGGA/GammaConv/AliAnalysisTaskMesonJetCorrelation.cxx
PWGGA/GammaConv/AliAnalysisTaskMesonJetCorrelation.h
PWGGA/GammaConvBase/AliResponseMatrixHelper.cxx
PWGGA/GammaConvBase/AliResponseMatrixHelper.h

- New true histograms for secondaries
- Rearange response matrix helper
- New histograms for true jets
- Add histogram for mesons as function of pt (in addition to zT)

PWGGA/GammaConv: Add true histograms for meson jet correlation task

---

PWGJE/EMCALJetTasks/UserTasks/AliAnalysisTaskEmcalJetHdEdxCorrelations.cxx

Updating my task to output PID from TPC

Adding NSigma dims to ThNSparse

---

PWGCF/EBYE/MeanPtFluctuations/pp13TeV_MB/AliAnalysisMeanPt.cxx
PWGCF/EBYE/MeanPtFluctuations/pp13TeV_MB/AliAnalysisMeanPt.h
PWGCF/EBYE/MeanPtFluctuations/pp13TeV_MB/macro/AddMeanPt.C
PWGCF/EBYE/macros/test/try1.txt

The task for Mean pT Fluctuations in minimum bias pp collisions at 13 TeV energy.

Mean pT Fluctuations in 13 TeV pp data

---

PWGLF/NUCLEX/Exotica/Dibaryons/AddTaskMSDibaryons.C
PWGLF/NUCLEX/Exotica/Dibaryons/AliAnalysisTaskMSDibaryons.cxx
PWGLF/NUCLEX/Exotica/Dibaryons/AliAnalysisTaskMSDibaryons.h

Train test

---

PWGCF/Correlations/JCORRAN/Pro/AliJCDijetAna.cxx
PWGCF/Correlations/JCORRAN/Pro/AliJCDijetAna.h
PWGCF/Correlations/JCORRAN/Pro/AliJCDijetHistos.cxx
PWGCF/Correlations/JCORRAN/Pro/AliJCDijetHistos.h
PWGCF/Correlations/JCORRAN/Pro/AliJCDijetTask.cxx
PWGCF/Correlations/JCORRAN/Pro/AliJCDijetTask.h

Now if there is an overlap of several true jets with a single detector jet, the detector jet is not matched multiple times.

Tuned the jet pt match algo and added pythia info

---

PWGHF/vertexingHF/AliHFSystErr.cxx
PWGHF/vertexingHF/AliHFSystErr.h

Adding systematics on Dstar analysis in pp at 13 TeV full sample 2016, 2017, and 2018 combined.

Adding Dstar systematics in pp collisions at 13TeV full sample analysis

---

PWGGA/CaloTrackCorrelations/AliAnaParticleIsolation.cxx
PWGGA/CaloTrackCorrelations/macros/AddTaskCaloTrackCorrBase.C
PWGGA/CaloTrackCorrelations/macros/ConfigureCaloTrackCorrAnalysis.C

to lighten train extra configurations plus histogram creation fixes for particular settings

[PWGGA/CaloTrackCorr] Additional string dependent configurations 

---

PWGCF/FEMTOSCOPY/AliFemtoUser/AliFemtoPairCutRadialDistanceDR.cxx
PWGCF/FEMTOSCOPY/AliFemtoUser/AliFemtoPairCutRadialDistanceDR.h
PWGCF/FEMTOSCOPY/AliFemtoUser/CMakeLists.txt
PWGCF/FEMTOSCOPY/AliFemtoUser/PWGCFfemtoscopyUserLinkDef.h

The track of two particles are calculated throughout the TPC volume every 20 cm from 85 cm to 245 cm

Two track cuts using a radial distance of 20cm

---

PWGGA/GammaConv/AliAnalysisTaskNeutralMesonToPiPlPiMiNeutralMeson.cxx
PWGGA/GammaConv/macros/AddTask_GammaConvNeutralMesonPiPlPiMiNeutralMeson_ConvMode_pPb.C
PWGGA/GammaConv/macros/AddTask_GammaConvNeutralMesonPiPlPiMiNeutralMeson_MixedMode_pPb.C

- Added MBWs to pPb Mixed Mode
- Fixed typo in pPb Conv AddTaskName
- Added cutstrings to constrain pi0 mass in PCM-EMC

PWGGA/GammaConv: Enabled MBWs for pPb MixedMode + added cutstrings

---

PWGDQ/dielectron/LMEE/AliAnalysisTaskLMeeCocktailMC.cxx
PWGDQ/dielectron/LMEE/AliAnalysisTaskLMeeCocktailMC.h

Use fDoRapidityCut to give the possiblity to cut on the rapidity of the dielectron pair

Use fDoRapidityCut to give the possiblity to cut on the rapidity 

---

PWGDQ/dielectron/macrosLMEE/AddTask_jjung_lowmass.C

Removed hardcoded triggermask and added option to set it instead.

PWGDQ:LMee: Update personal AddTask

---

PWGGA/GammaConv/AliAnalysisTaskGammaCalo.cxx
PWGGA/GammaConv/AliAnalysisTaskGammaCalo.h
PWGGA/GammaConv/AliAnalysisTaskMesonJetCorrelation.cxx
PWGGA/GammaConv/macros/AddTask_MesonJetCorr_Calo.C
PWGGA/GammaConv/macros/AddTask_MesonJetCorr_Conv.C
PWGGA/GammaConv/macros/AddTask_MesonJetCorr_ConvCalo.C

- For INEL>0 analyses one has to keep track of the number of triggered events (MC condition) to calculate the trigger efficiency.
- Added cuts for in-jet analysis with jet trigger

PWGGA/GammaConv: Add event histogram for MC triggered events

---

PWGLF/RESONANCES/PostProcessing/f0980/AliAnalysisTaskInclusivef0f2.cxx

add UPC feasibility study mode with TOF

[PWGLF] add UPC feasibility study mode with TOF

---

PWGDQ/dielectron/LMEE/AliAnalysisTaskOmegaDielectron_AccEff.cxx
PWGDQ/dielectron/LMEE/AliAnalysisTaskOmegaDielectron_AccEff.h

Add single electron efficiency to omega task

Add single electron efficiency

---

PWGCF/FEMTOSCOPY/macros/AddTaskFemtoNanoLKr.C

Added the following lines:
closeRejection[2] = true;  ///pos kaon- lambda
closeRejection[3] = true;  ///pos kaon- antilambda
closeRejection[4] = true;  ///neg kaon-neg kaon
closeRejection[5] = true;  ///neg kaon-lambda
closeRejection[6] = true;  ///neg kaon-antilambda
config->SetPhiEtaBinnign(true);
config->SetDeltaEtaMax(0.012);
config->SetDeltaPhiMax(0.012);

Close_Pair_Rejection_improved

---

PWGDQ/dielectron/LMEE/AliAnalysisTaskOmegaDielectron_AccEff.cxx

adjust cuts to publication

---

PWGHF/vertexingHF/AliHFInvMassMultiTrialFit.cxx
PWGHF/vertexingHF/AliHFInvMassMultiTrialFit.h

Required for latest ROOT versions, see https://github.com/alisw/AliPhysics/pull/19219

PWGHF: Add possibility to use FitResult::IsValid() flag

---

PWGMM/UE/FlatenicityLambdaK0s/AliAnalysisTaskFlatenicityLambdaK0s.cxx
PWGMM/UE/FlatenicityLambdaK0s/AliAnalysisTaskFlatenicityLambdaK0s.h

The codes are modified to store the kinematic information of K0s, Lambda and AntiLambda particles, along with flatenicity.

Updated to store flatenicity and strange particle kinematic informations

---

PWGDQ/dielectron/LMEE/AliAnalysisTaskOmegaDielectron_AccEff.cxx

adjust cuts to publication 
-Chi2 per ITS cluster 4.5->5.5
-Min ratio TPC cross row over findable 0.8->0.6

adjust cuts to publication 2.0

---

PWGCF/Correlations/macros/jcorran/AddTaskJFFlucJCMAPsMaster.C
PWGCF/Correlations/macros/jcorran/AddTaskJHOCFAMaster.C

Adding two more cuts for chi² to have a lower boundary

[PWG-CF]Adding new chi^2 cut with lower bound

---

PWGJE/EMCALJetTasks/UserTasks/AliAnalysisTaskEmcalJetEnergyFlow.cxx

Small fix one of the jet energy response histograms to include the corrected pt for background contributions.

Small fix one of the jet energy response histograms. 

---

PWGJE/EMCALJetTasks/UserTasks/AliAnalysisTaskRawJetWithEP.cxx
PWGJE/EMCALJetTasks/UserTasks/AliAnalysisTaskRawJetWithEP.h

Now, my trains have error caused by memory. To reduce memory, I deleted histograms.

reduce histograms to decreace memory for train

---

PWGHF/correlationHF/AliHFMLResponseLambdactopKpi.cxx

New Set of Variables introduced for Lc-hadron correlations

PWGHF-C: Fix_Lch variables

---

PWGJE/EMCALJetTasks/AliAnalysisTaskJetChargeFlavourPb.cxx
PWGJE/EMCALJetTasks/AliAnalysisTaskJetChargeFlavourPb.h

And floating Point exception to attempt to add stabililty to the task on legotrains

Updated the analysisTask to try to avoid uncommon seg error

---

PWGDQ/dimuons/CMakeLists.txt
PWGDQ/dimuons/PWGDQdimuonsLinkDef.h
PWGDQ/dimuons/Psi2Spolarization/AddTaskPsi2Spolarization.C
PWGDQ/dimuons/Psi2Spolarization/AliAnalysisTaskPsi2Spolarization.cxx
PWGDQ/dimuons/Psi2Spolarization/AliAnalysisTaskPsi2Spolarization.h

Here is a first task for psi2S polarization analysis

First task for Psi2S polarization

---

PWGCF/FLOW/GF/AliAnalysisTaskCorrForFlowMaster.cxx
PWGCF/FLOW/GF/AliAnalysisTaskCorrForFlowMaster.h

Optimized trig and asso filling - runtime decreased

[FLOW-PAG] Optimized filling

---

PWGCF/FLOW/macros/AddCorrForFlowTaskMaster.C

Added newline at the end for the compiler

[FLOW-PAG ] Added newline for LEGO train

---

PWGMM/UE/FlatenicityLambdaK0s/AddTaskFlatenicityLambdaK0s.C
PWGMM/UE/FlatenicityLambdaK0s/AliAnalysisTaskFlatenicityLambdaK0s.cxx
PWGMM/UE/FlatenicityLambdaK0s/AliAnalysisTaskFlatenicityLambdaK0s.h

The task is modified with some bug fixes that are related to more production of antiLambda compared to lambda particles, and required event selection cuts are added.

Bug fix and event selection cuts added

---

PWGJE/EMCALJetTasks/UserTasks/AliAnalysisTaskSVtaskMCFilter.cxx
PWGJE/EMCALJetTasks/UserTasks/AliAnalysisTaskSVtaskMCFilter.h
PWGJE/EMCALJetTasks/macros/AddTaskSVtaskMCFilter.C

PWGJE/EMCALJetTasks SVtaskMCFilter - Adding functionality for clusters. Should not impact existing wagon configs.

PWGJE/EMCALJetTasks SVtaskMCFilter - Adding functionality for clusters. Should not impact existing wagon configs.

---

PWGJE/EMCALJetTasks/UserTasks/AliAnalysisTaskRawJetWithEP.cxx
PWGJE/EMCALJetTasks/UserTasks/AliAnalysisTaskRawJetWithEP.h

Now I am facing the error 137 in only train. It happens only in 90% of trains.
So now I want to check the reason one-by-one.

memory leak check

---

PWGGA/GammaConv/macros/AddTask_GammaConvNeutralMesonPiPlPiMiNeutralMeson_CaloMode_pPb.C

- Added cutstrings for MB, EG1 and EG2
- Standard cuts and cutvariations
- Added pT-dep selection window argument (copied from pp)

PWGGA/GammaConv: Add Cutstrings and one argument to pPb Omega AddTask

---

PWGJE/EMCALJetTasks/UserTasks/AliAnalysisTaskEmcalJetEnergyFlow.cxx

This is a small fix since the histogram was already created in the previous version but not filled.

Fill the small Dpt histogram in the case of analysing data.

---

PWGHF/vertexingHF/AliAnalysisTaskSESemileptonicOmegac0KFP.cxx
PWGHF/vertexingHF/AliAnalysisTaskSESemileptonicOmegac0KFP.h

1）Add DCA and DecayLength info in TTree
2) Simplify the MakeAnaOmegacZeroFromCasc() function

Add new branches & simplify code

---

PWGHF/vertexingHF/AliAnalysisTaskSEXicPlusToXi2PifromKFP.cxx
PWGHF/vertexingHF/AliAnalysisTaskSEXicPlusToXi2PifromKFP.h
PWGHF/vertexingHF/macros/AddTaskXicPlusToXi2PiFromKFParticle.C

Add QA tree to investigate mass and topological constraint

Add QA tree to investigate mass and topological constraint

---

PWGCF/FEMTOSCOPY/macros/AddTaskFemtoNanoLKr.C

Oton cuts with different pT range

---

PWGJE/EMCALJetTasks/UserTasks/AliAnalysisTaskJetQnVectors.cxx
PWGJE/EMCALJetTasks/UserTasks/AliAnalysisTaskJetQnVectors.h
PWGJE/EMCALJetTasks/UserTasks/AliJEQnVectorHandler.cxx
PWGJE/EMCALJetTasks/macros/AddTaskJEQnVectors.C

Now calibration files are loaded during add task for TaskJetQnVectors

Now calibration files are loaded during add task for TaskJetQnVectors

---

PWGJE/EMCALJetTasks/Tracks/AliAnalysisTaskEmcalJetEnergySpectrum.cxx

PWGJE/EMCALJetTasks/Tracks/AliAnalysisTaskEmcalJetEnergySpectrum.cxx Adding + and - track histos

PWGJE/EMCALJetTasks/Tracks/AliAnalysisTaskEmcalJetEnergySpectrum.cxx Adding + and - track histos

---

PWGJE/EMCALJetTasks/UserTasks/AliJEQnVectorHandler.cxx
PWGJE/EMCALJetTasks/UserTasks/AliJEQnVectorHandler.h

Replaces the OADB vector arrays with TObjArrays so they can be streamed properly.

Fix JEQvector calibration streaming issue.

---

PWG/CaloTrackCorrBase/AliAnaCaloTrackCorrBaseClass.h
PWG/CaloTrackCorrBase/AliAnaWeights.cxx
PWG/CaloTrackCorrBase/AliAnaWeights.h
PWGGA/CaloTrackCorrelations/AliAnaParticleIsolation.cxx
PWGGA/CaloTrackCorrelations/AliAnaPhoton.cxx
PWGGA/CaloTrackCorrelations/AliAnaPi0.cxx

charged particle Raa applied as weight on primary particle pT, decay photons go back to primary pi0 or eta

[PWGGA/CaloTrackCorr] Add possibility to weight histograms with Raa

---

PWGLF/SPECTRA/PiKaPr/TPCTOF/AliAnalysisTaskAntiProtons_vs_RT_pPb.cxx
PWGLF/SPECTRA/PiKaPr/TPCTOF/AliAnalysisTaskAntiProtons_vs_RT_pPb.h
PWGLF/SPECTRA/PiKaPr/TPCTOF/addTaskAntiProtons_vs_RT_pPb.C

Added new task and addTask macro for antiprotons analysis vs RT in p-Pb collisions, both for data and MC.

Antiprotons vs RT in p-Pb

---

PWG/EMCAL/EMCALtasks/AliEmcalFilterAODMCHeaders.cxx

PWG/EMCAL/EMCALtasks/AliEmcalFilterAODMCHeaders.cxx Fix header rejection bool. LinkMothers() additions.

PWG/EMCAL/EMCALtasks/AliEmcalFilterAODMCHeaders.cxx Fix header rejection bool. LinkMothers() additions.

---

PWGCF/Correlations/DPhi/Unfoldedhistos/AliCSAnalysisCutsBase.cxx
PWGCF/Correlations/DPhi/Unfoldedhistos/AliCSAnalysisCutsBase.h
PWGCF/Correlations/DPhi/Unfoldedhistos/AliCSEventCuts.cxx
PWGCF/Correlations/DPhi/Unfoldedhistos/AliCSPIDCuts.cxx
PWGCF/Correlations/DPhi/Unfoldedhistos/AliCSPIDCuts.h
PWGCF/Correlations/DPhi/Unfoldedhistos/AliCSTrackCuts.cxx
PWGCF/Correlations/DPhi/Unfoldedhistos/AliCSTrackCuts.h
PWGCF/Correlations/DPhi/Unfoldedhistos/AliCSTrackCutsBase.h
PWGCF/Correlations/DPhi/Unfoldedhistos/AliCSTrackSelection.cxx

Also rationalizing the TPC clusters cut on top of AOD FBs

Considering the DCA cut variations on top of AOD FBs

---

PWGCF/Correlations/DPhi/Unfoldedhistos/AliCSPIDCuts.cxx
PWGCF/Correlations/DPhi/Unfoldedhistos/AliCSPIDCuts.h
PWGCF/Correlations/DPhi/Unfoldedhistos/AliCSTrackCuts.cxx
PWGCF/Correlations/DPhi/Unfoldedhistos/AliCSTrackSelection.cxx

Now it is possible to apply several criteria to each species

Re-engineering the PID cut complex

---

PWGGA/PHOSTasks/PHOS_gamma/AddTaskPHOSPbPbQARun2.C
PWGGA/PHOSTasks/PHOS_gamma/AliAnalysisTaskPHOSPbPbQARun2.cxx
PWGGA/PHOSTasks/PHOS_gamma/AliAnalysisTaskPHOSPbPbQARun2.h

Photons tests2

---

PWGJE/EMCALJetTasks/AliAnalysisTaskJetCharge.cxx
PWGJE/EMCALJetTasks/AliAnalysisTaskJetCharge.h
PWGJE/EMCALJetTasks/AliAnalysisTaskJetChargeFlavourPb.cxx
PWGJE/EMCALJetTasks/AliAnalysisTaskJetChargeFlavourPb.h

to see if seperation from background effects gluon yields

Added Alternative output for jet charge at Higher Track cut 

---

PWGGA/GammaConv/macros/AddTask_GammaConvNeutralMesonPiPlPiMiNeutralMeson_MixedMode_pp.C

Additonal Cutstring for PCMPHOS.
Adjusted used R Bins.

Add Material Budget Change, remove r bin for pcmphos

---

PWGGA/GammaConv/macros/AddTask_GammaConvNeutralMesonPiPlPiMiNeutralMeson_CaloMode_pp.C
PWGGA/GammaConv/macros/AddTask_GammaConvNeutralMesonPiPlPiMiNeutralMeson_MixedMode_pp.C
PWGGA/GammaConvBase/AliConversionMesonCuts.cxx

PWGGA: Add Cut for min Gamma

---

PWGLF/SPECTRA/PiKaPr/TPCTOF/AddTaskAntiProtons_vs_RT_pPb.C
PWGLF/SPECTRA/PiKaPr/TPCTOF/AliAnalysisTaskAntiProtons_vs_RT_pPb.cxx

Add task: 
- renamed due to compatibily issue
- changed path for the recalibration maps with definitive ones
Class: 
- Added pseudorapidity cut
- Modified bins for pseudorapidity and pT_TPC

Rename&modified add task, added eta cut and modified bins in cxx

---

PWGJE/EMCALJetTasks/UserTasks/AliAnalysisTaskJetCoreEmcal.cxx
PWGJE/EMCALJetTasks/UserTasks/AliAnalysisTaskJetCoreEmcal.h

add histogram to state what event plane bin the trigger belongs to, and leading track info for recoil jets, for IRC checks

add event plane trigger and jet leading track information

---

PWGLF/STRANGENESS/Cascades/Run2/AliAnalysisTaskStrangenessVsMultiplicityRun2.cxx
PWGLF/STRANGENESS/Cascades/Run2/AliAnalysisTaskStrangenessVsMultiplicityRun2.h

Add an option to save the AliExternalTrackParameters of tracks reconstructed using the TPC only

Add the possibility to save the TPC track parameters

---

PWGGA/GammaConv/AliAnalysisTaskNeutralMesonToPiPlPiMiNeutralMeson.cxx

- Introduced parameters from combination of pp & pPb trains/MCs

PWGGA/GammaConv: Adjusted PCM-EMCal Lambda correction parameters

---

PWGMM/Mult/AliSPDpPbAnalysisTask.cxx
PWGMM/Mult/AliSPDpPbAnalysisTask.h
PWGMM/Mult/AliSPDpPbAnalysisTaskData.cxx
PWGMM/Mult/AliSPDpPbAnalysisTaskData.h
PWGMM/Mult/CMakeLists.txt
PWGMM/Mult/PWGMMMultLinkDef.h

Inclusing data and simulation script files of AliSPDpPbAnalysisTask and updating cmakelists

Include SPD tracklet multiplicity analysis for p-Pb

---

PWGJE/EMCALJetTasks/UserTasks/AliAnalysisTaskRawJetWithEP.cxx
PWGJE/EMCALJetTasks/UserTasks/AliAnalysisTaskRawJetWithEP.h

I changed many lines to solve train problem

changed many lines for train problem

---

PWGCF/FLOW/GF/AliAnalysisTaskCorrForFlowMaster.cxx

Corrected the logic in the source file

[FLOW-PAG] Optimized anti-correlation

---

PWGMM/UE/UeKNO/AliAnalysisTaskFlatenicity.cxx
PWGMM/UE/UeKNO/AliAnalysisTaskFlatenicity.h

Added histograms hPtBefore hPtAfter to compare number of filtered events and find out the signal loss by filters.

Added histograms for signal loss correction

---

PWGDQ/dielectron/LMEE/AliAnalysisTaskOmegaDielectron_AccEff.cxx

update to finer binning of the histograms
to be able to compare

update to finer binning of the histograms

---

PWGHF/vertexingHF/AliAnalysisTaskSEXicPlus2XiPiPifromAODtracks.cxx

To reduce the output file size, some unused histograms were commented out.

Masked out the unused histograms

---

PWGJE/EMCALJetTasks/UserTasks/AliAnalysisTaskEmcalJetHdEdxCorrelations.cxx
PWGJE/EMCALJetTasks/UserTasks/AliAnalysisTaskEmcalJetHdEdxCorrelations.h

New EP measurement in  2018 method JetQnVectors.

Adding new EP and fixing PID for now

---

PWGJE/EMCALJetTasks/UserTasks/AliAnalysisTaskEmcalJetHdEdxCorrelations.cxx

I'm not sure if this is the right way to apply these filter bits. I had a hard time finding documentation on these particular filter bits. Let me know if I made a mistake.

Adding TOF nsigma and an AOD filter bit 96, 16, 768

---

PWGCF/Correlations/macros/AddTaskLambdaK0s.C

Centrality arguments initialization and path optimization of efficiency  for AddTaskLambdaK0s Task

Centrality arguments initialization, and path optimization of efficiency

---

PWGHF/vertexingHF/vHFML/AliAnalysisTaskSEDmesonTree.cxx
PWGHF/vertexingHF/vHFML/AliAnalysisTaskSEDmesonTree.h

@fgrosa This should be enough to perform the resonance checks

Add possibility to compute efficiency of linear pre-selections

---

PWGHF/vertexingHF/vHFML/AliAnalysisTaskSEDmesonTree.cxx

Fix number of axis

---

PWGHF/vertexingHF/AliAnalysisTaskSEXic0SL.cxx
PWGHF/vertexingHF/macros/AddTaskXic0Semileptonic.C

Local test snapshots for:
a. Reproducing the bug
b. Output AnalysisResults.root after the debug (3 AddTaks ran simultaneously)

Xic0Semileptonic/Xic0SL debug for Lego train run

---

PWGHF/vertexingHF/macros/AddTaskXic0Semileptonic.C

Commented out debug message printing part for Lego train run

Xic0Semileptonic: disabled debug message

---

PWGJE/EMCALJetTasks/UserTasks/AliAnalysisTaskEmcalJetHdEdxCorrelations.cxx

Adding some conditional blocks for dealing with pp analysis.

Adding pp analysis

---

PWGCF/FEMTOSCOPY/FemtoDream/CMakeLists.txt
PWGHF/correlationHF/CMakeLists.txt
PWGHF/hfe/CMakeLists.txt
PWGHF/vertexingHF/AliAnalysisTaskHFSimpleVertices.cxx
PWGHF/vertexingHF/AliAnalysisTaskHFSimpleVertices.h
PWGHF/vertexingHF/CMakeLists.txt
PWGHF/vertexingHF/vHFML/CMakeLists.txt
PWGLF/QATasks/CMakeLists.txt
PWGLF/STRANGENESS/CMakeLists.txt

updating AliPhysics
PWGHF: Adding Jet finding for Run3Validation HF framework

Adding Jets to code for HF Validation for Run 3

---

PWGHF/vertexingHF/vHFML/AliAnalysisTaskSEDmesonTree.cxx
PWGHF/vertexingHF/vHFML/AliAnalysisTaskSEDmesonTree.h

Add possibility to turn off rapidity and acc. checks for gen. MC

---

PWGGA/GammaConv/macros/AddTask_GammaCalo_pPb.C
PWGGA/GammaConv/macros/AddTask_GammaConvCalo_pPb.C

PWGGA/GammaConv: Timing cut variations

---

PWGLF/RESONANCES/CMakeLists.txt
PWGLF/RESONANCES/PWGLFresonancesLinkDef.h
PWGLF/RESONANCES/PostProcessing/Xi1820/AddTaskXi1820BH.C
PWGLF/RESONANCES/PostProcessing/Xi1820/AliAnalysisTaskXi1820BH.cxx
PWGLF/RESONANCES/PostProcessing/Xi1820/AliAnalysisTaskXi1820BH.h

Compact Analysis class for testing

---

PWGHF/correlationHF/AliAnalysisTaskSELambdacCorrelations.cxx
PWGHF/correlationHF/AliHFAssociatedTrackCuts.cxx
PWGHF/correlationHF/AliHFAssociatedTrackCuts.h
PWGHF/correlationHF/AliHFCorrelator.cxx
PWGHF/correlationHF/AliHFCorrelator.h

- Adding Soft-Pion removal to SE analysis (HFCorrelator.cxx)
- Minor changes in the LambdaC-h analysis task

PWGHF-C: Lc-h, fix soft pion subtraction

---

PWGDQ/dielectron/macrosLMEE/AddTask_mwaelde_AcceptanceEfficiency.C

Name to be able to run several tasks together

Name to be able to run several tasks together

---

PWGMM/UE/FlatenicityLambdaK0s/AddTaskFlatenicityLambdaK0s.C
PWGMM/UE/FlatenicityLambdaK0s/AliAnalysisTaskFlatenicityLambdaK0s.cxx
PWGMM/UE/FlatenicityLambdaK0s/AliAnalysisTaskFlatenicityLambdaK0s.h

The analysis code is updated with the physics selection cuts and some required event cuts.

Physics selection and event selection cuts added

---

PWGHF/vertexingHF/vHFML/AliAnalysisTaskSEDmesonTree.cxx
PWGHF/vertexingHF/vHFML/AliAnalysisTaskSEDmesonTree.h

Use rapidity instead of eta for check

---

PWG/FLOW/Tasks/AliAnalysisTaskCVEPIDCME.cxx
PWG/FLOW/Tasks/AliAnalysisTaskCVEPIDCME.h
PWG/FLOW/Tasks/CMakeLists.txt
PWG/FLOW/Tasks/PWGflowTasksLinkDef.h
PWGCF/FLOW/macros/AddTaskCVEPIDCME.C

This version has supported search on CVE. 
Can be easily extended to PID CME study.

Add a new class to study CVE and PID CME

---

PWGUD/UPC/AliAnalysisTaskUpcPhi0.cxx
PWGUD/UPC/AliAnalysisTaskUpcPhi0.h

update dikaon analysis cuts

---

PWGGA/GammaConv/macros/AddTask_GammaIsoTree.C

added systematic variation for isolated photon analysis to estimate impact of SPD pileup cut

PWGGA/GammaConv: added sys variation iso photons

---

PWGJE/EMCALJetTasks/UserTasks/AliAnalysisTaskRawJetWithEP.cxx
PWGJE/EMCALJetTasks/UserTasks/AliAnalysisTaskRawJetWithEP.h

1. I add printout to specify the actual crush line.
2. I add setter to switch active functions to find error function.
3. I modified some histogram setting (not relate this train problem)

add print out lines to specify the reason of the train problem.

---

PWGCF/Correlations/JCORRAN/Pro/AliJCDijetAna.cxx

Now the closest in deltaR is matched instead of highest pt to mimic other similar analysis.

Changed single jet matching behaviour

---

PWGJE/EMCALJetTasks/UserTasks/AliAnalysisTaskRawJetWithEP.cxx

I found some reference histograms by previous pull request.
But still remain the crush, so I add more printout lines.

Add pointer check and printout lines to specify the train problem.

---

PWGDQ/dielectron/core/AliAnalysisTaskElectronEfficiencyV2.cxx

Apply smearing for rec pairs using MC particle

---

PWGJE/EMCALJetTasks/UserTasks/AliAnalysisTaskRawJetWithEP.cxx

I add return lines. I noticed the error function does not end by return line even though it is Bool_t.

Modified error of Event plane fanction for train problem

---

PWGCF/FEMTOSCOPY/AliFemtoUser/AliFemtoWRzTrackCut.cxx
PWGCF/FEMTOSCOPY/AliFemtoUser/AliFemtoWRzTrackCut.h

New variation of deuteron's settings to crosscheck purty

new settings of the selection

---

PWGJE/EMCALJetTasks/UserTasks/AliAnalysisTaskV0sInJetsEmcal.cxx
PWGJE/EMCALJetTasks/UserTasks/AliAnalysisTaskV0sInJetsEmcal.h

XiMinus analysis added

---

PWGHF/vertexingHF/AliAnalysisTaskHFSimpleVertices.cxx

Set vertexer useAbsDCA option from json

---

PWGCF/FEMTOSCOPY/AliFemtoUser/AliAnalysisTaskParticleEffDY.cxx
PWGCF/FEMTOSCOPY/AliFemtoUser/AliAnalysisTaskParticleEffDY.h

Efficiency task to count the number of events loss after cuts on four multiplicity classes

EfficiencyTaskOnfourMult

---

PWGCF/FLOW/GF/AliAnalysisTaskGFWFlow.cxx
PWGCF/FLOW/GF/AliAnalysisTaskGFWFlow.h
PWGCF/FLOW/macros/AddTaskGFWFlow.C

--> Still need to check if TFile will work on trains. On the other hand, that's the idea of this commit

NUA weights are now stored in a plane TFile rather than in a TList

---

PWGHF/vertexingHF/AliAnalysisTaskHFSimpleVertices.cxx

To sync with the O2Physics histogram

PWGHF: Run 3 validation: Adjust binning of fHistPrimVertContr

---

PWGCF/FEMTOSCOPY/AliFemtoUser/AliAnalysisTaskParticleEffDY.cxx

Counting events lost after cuts on four multiplicities only for pions

EfficiencyUpdateFourMult

---

PWGGA/GammaConv/AliAnalysisTaskMesonJetCorrelation.cxx
PWGGA/GammaConv/AliAnalysisTaskMesonJetCorrelation.h
PWGGA/GammaConv/macros/AddTask_MesonJetCorr_Conv.C
PWGGA/GammaConv/macros/AddTask_MesonJetCorr_ConvCalo.C

- Add Material budged weights to all histos
- Fixed issue with MC triggeres. else if instead of just if is needed as otherwise generator histograms are being filled twice if not the correct trigger is selected

PWGGA/GammaConv: Added option for material weights in Meson Jet task

---

PWGHF/vertexingHF/AliAnalysisTaskSEDvsEventShapes.cxx
PWGHF/vertexingHF/AliAnalysisTaskSEDvsEventShapes.h
PWGHF/vertexingHF/macros/AddTaskDvsEventShapes.C

This edit allows the user to compute directly the analysis INEL > 0 in the minimum bias multiplicity interval 1 - 199

Added MB multiplicity INEL > 0 to S0 Quantiles

---

PWGHF/vertexingHF/AliAnalysisTaskSEXicZero2XiPifromKFP.cxx
PWGHF/vertexingHF/AliAnalysisTaskSEXicZero2XiPifromKFP.h
PWGHF/vertexingHF/AliRDHFCutsKFP.cxx
PWGHF/vertexingHF/AliRDHFCutsKFP.h
PWGHF/vertexingHF/macros/AddTaskXicZero2XiPiFromKFParticle.C
PWGHF/vertexingHF/macros/AddTaskXicZeroToXiPiFromKFParticleForPbPb.C
PWGHF/vertexingHF/vHFML/AliHFMLXicZeroToXiPifromKFP.cxx
PWGHF/vertexingHF/vHFML/AliHFMLXicZeroToXiPifromKFP.h

Add flag to store like-sign pairs; remove "weights" and add "pt_gen" in rec. tree; Add more pre-selections and MLmap into Xic0 Pb-Pb analysis task

Add flag to store like-sign pairs; remove "weights" and add "pt_gen" in rec. tree; Add more pre-selections and MLmap into Xic0 Pb-Pb analysis task

---

PWGHF/vertexingHF/macros/AddTaskXicZeroToXiPiFromKFParticleForPbPb.C
PWGHF/vertexingHF/vHFML/AliHFMLXicZeroToXiPifromKFP.cxx
PWGHF/vertexingHF/vHFML/AliHFMLXicZeroToXiPifromKFP.h

Remove event tree in analysis class and add suffix of centrality and pT for output name in AddTask

Remove event tree in analysis class and add suffix of centrality and pT for output name in AddTask

---

PWGHF/vertexingHF/macros/AddTaskXicZeroToXiPiFromKFParticleForPbPb.C

Fix the issue of suffix for output name in AddTask

Fix the issue of suffix for output name in AddTask

---

PWGDQ/dielectron/CMakeLists.txt
PWGDQ/dielectron/LMEE/AliAnalysisTaskMLTreeMaker2018.cxx
PWGDQ/dielectron/LMEE/AliAnalysisTaskMLTreeMaker2018.h
PWGDQ/dielectron/PWGDQdielectronLinkDef.h
PWGDQ/dielectron/macrosLMEE/AddTaskMLTreeMaker2018.C

Added new ML tree task based on version implemented by the vienna group and the efficiency task for pair and MC signal selection.

PWGEM:LMee: Adding new task to create trees for ML inputs

---

PWGCF/Correlations/DPhi/AliAnalysisTaskLambdaHadronRatio.cxx
PWGCF/Correlations/DPhi/AliAnalysisTaskLambdaHadronRatio.h
PWGCF/Correlations/DPhi/PWGCFCorrelationsDPhiLinkDef.h
PWGCF/Correlations/macros/AddLambdaHadronRatioTask.C

Adding my Lambda/Hadron ratio analysis task so I can run trains during these trying times (aka HP2023 preparation)

Added LambdaHadronRatio task (and corresponding AddTask macro)

---

PWGGA/Hyperon/AliAnalysisTaskSigmaPCMPHOS.cxx
PWGGA/Hyperon/AliAnalysisTaskSigmaPCMPHOS.h
PWGGA/Hyperon/macros/AddAnalysisTaskSigmaPCMPHOS.C

Updated Sigma0 analysis code as required for our analysis.

update Sigma0 analysis code 

---

PWGDQ/dielectron/macrosLMEE/AddTaskMLTreeMaker2018.C

PWGEM:LMee: Correct syntax in AddTask

---

PWGGA/GammaConv/AliAnalysisTaskConvJet.cxx
PWGGA/GammaConv/AliAnalysisTaskConvJet.h
PWGGA/GammaConv/AliAnalysisTaskMesonJetCorrelation.cxx
PWGGA/GammaConv/AliAnalysisTaskMesonJetCorrelation.h

clusters and tracks
- To be used for debugging and jet triger studies

PWGGA/GammaConv: Add histos for neutral energy fraction and number of

---

PWGDQ/dielectron/LMEE/AliAnalysisTaskMLTreeMaker2018.cxx
PWGDQ/dielectron/macrosLMEE/AddTaskMLTreeMaker2018.C

Removed comma in AddTask
Fixed capital letter in AnalysisTask
Fixed XYZ of first Track in AnalysisTask

PWGEM:LMee: Fixing some typos

---

PWGCF/FEMTOSCOPY/AliFemtoUser/AliAnalysisTaskParticleEffDYM0.cxx
PWGCF/FEMTOSCOPY/AliFemtoUser/AliAnalysisTaskParticleEffDYM0.h
PWGCF/FEMTOSCOPY/AliFemtoUser/AliAnalysisTaskParticleEffDYM1.cxx
PWGCF/FEMTOSCOPY/AliFemtoUser/AliAnalysisTaskParticleEffDYM1.h
PWGCF/FEMTOSCOPY/AliFemtoUser/AliAnalysisTaskParticleEffDYM2.cxx
PWGCF/FEMTOSCOPY/AliFemtoUser/AliAnalysisTaskParticleEffDYM2.h
PWGCF/FEMTOSCOPY/AliFemtoUser/AliAnalysisTaskParticleEffDYM3.cxx
PWGCF/FEMTOSCOPY/AliFemtoUser/AliAnalysisTaskParticleEffDYM3.h
PWGCF/FEMTOSCOPY/macros/AddTaskEffDYM0.C
PWGCF/FEMTOSCOPY/macros/AddTaskEffDYM1.C
PWGCF/FEMTOSCOPY/macros/AddTaskEffDYM2.C
PWGCF/FEMTOSCOPY/macros/AddTaskEffDYM3.C

Efficiency Task on four multiplicities

EfficiencyTaskOnFourMultiplicity

---

PWGCF/FEMTOSCOPY/macros/Train/KM/AddTaskFemto.C
PWGCF/FEMTOSCOPY/macros/Train/KM/ConfigFemtoAnalysis.C

+test
just a test two .C files from Konstantin

Konstantin add to Train/KM two files 09.03.23

---

PWGCF/Correlations/KaonCorrelations/AliAnalysisTaskKaon2PC.cxx
PWGCF/Correlations/KaonCorrelations/AliAnalysisTaskKaon2PC.h

*Cleaned the code before adding the MC part
*Added functions for filling correlations
*Changed the filter bit from 272 to 96
*Removed kpos-kpos and kneg-kneg correlation functions as the focus is on kpos-kneg and k0-kch correlations as if now.

cleaned the code before adding MC part

---

PWGDQ/dimuons/Psi2Spolarization/AddTaskPsi2Spolarization.C

I have tried to fix the issue with physics selection for which the train was not running.

physics selection fix

---

PWGJE/EMCALJetTasks/UserTasks/AliAnalysisTaskRawJetWithEP.cxx
PWGJE/EMCALJetTasks/UserTasks/AliAnalysisTaskRawJetWithEP.h

I found the train jobs make crush at the line of the reading fRho.
So I changed the way to read fRho.

Change the way to read Rho vale to solve train problem

---

PWGCF/Correlations/JCORRAN/Pro/AliJCDijetAna.cxx
PWGCF/Correlations/JCORRAN/Pro/AliJCDijetAna.h
PWGCF/Correlations/JCORRAN/Pro/AliJCDijetHistos.cxx
PWGCF/Correlations/JCORRAN/Pro/AliJCDijetHistos.h
PWGCF/Correlations/JCORRAN/Pro/AliJCDijetTask.cxx
PWGCF/Correlations/JCORRAN/Pro/AliJCDijetTask.h

Also retained the original for dijet studies etc. Added some histograms for the study of deltaM behaviour in different mass bins.

Fixed eta cut behaviour to reflect other analysis

---

PWGJE/EMCALJetTasks/UserTasks/AliAnalysisTaskRawJetWithEP.cxx

Last change make another crush at test train. It successes my mac and lxplus, but local train fail. 
The crush message does not say specific reason.

Change the number of loop to initialize array

---

PWGCF/FEMTOSCOPY/macros/Train/KM/pPb502/001/ConfigFemtoAnalysis.C
PWGCF/FEMTOSCOPY/macros/Train/KM/pPb502/002/ConfigFemtoAnalysis.C

Konstantin: add config macros/Train/KM/pPb502/001

---

PWGCF/FEMTOSCOPY/macros/Train/KM/pPb502/003/ConfigFemtoAnalysis.C

++-- add new config.: K+K- pPb5.02tev

---

PWGCF/FEMTOSCOPY/AliFemtoUser/AliAnalysisTaskParticleEffDYM0.h
PWGCF/FEMTOSCOPY/AliFemtoUser/AliAnalysisTaskParticleEffDYM1.h
PWGCF/FEMTOSCOPY/AliFemtoUser/AliAnalysisTaskParticleEffDYM2.h
PWGCF/FEMTOSCOPY/AliFemtoUser/AliAnalysisTaskParticleEffDYM3.h

Changes that fix the issues of my last commit

EffTasksDifferentMultiplicities

---

PWGJE/EMCALJetTasks/UserTasks/AliAnalysisTaskEPCalibForJet.cxx
PWGJE/EMCALJetTasks/UserTasks/AliAnalysisTaskEPCalibForJet.h
PWGJE/EMCALJetTasks/UserTasks/AliAnalysisTaskEmbeddingJetWithEP.cxx
PWGJE/EMCALJetTasks/UserTasks/AliAnalysisTaskEmbeddingJetWithEP.h
PWGJE/EMCALJetTasks/UserTasks/AliAnalysisTaskRawJetWithEP.cxx
PWGJE/EMCALJetTasks/UserTasks/AliAnalysisTaskRawJetWithEP.h
PWGJE/EMCALJetTasks/macros/AddTaskEPCalibForJet.C
PWGJE/EMCALJetTasks/macros/AddTaskEmbeddingJetWithEP.C

Add different Qn calibration way for three kinds tasks (AliAnalysisTaskEPCalibForJet, AliAnalysisTaskRawJetWithEP, AliAnalysisTaskEmbeddingJetWithEP)

apply different Qn calibration way for 3kinds tasks

---

PWGHF/vertexingHF/AliAnalysisTaskSEXic0SL.cxx

Corrected one line which causes sample bias during efficiency calculation

Minor debug on AliAnalysisTaskSEXic0SL

---

PWGJE/EMCALJetTasks/UserTasks/AliAnalysisTaskEmcalJetValidation.cxx

In this commit, some of the hybrid track cuts have been modified to match with the corresponding global track cuts implemented in O2 task for the Jet Validation Framework (which is in progress: [AliceO2Group/O2Physics#2315](https://github.com/AliceO2Group/O2Physics/pull/2315/commits) ).

Updated track cuts for Jet O2 Validation

---

PWGJE/EMCALJetTasks/UserTasks/AliAnalysisTaskEmcalJetEnergyFlow.cxx

Fix of memory leak in the calculation of the mismatches fraction introduced in the last update.

Fix of memory leak in the calculation of the mismatches fraction

---

PWGCF/FEMTOSCOPY/macros/Train/KM/pPb502/004/ConfigFemtoAnalysis.C

Konstantin: add 004/ConfigFemtoAnalysis.C to LEGO

---

PWGDQ/dimuons/Psi2Spolarization/AliAnalysisTaskPsi2Spolarization.cxx

Update of physics selection cuts

Update of physics selection cuts

---

PWGCF/FEMTOSCOPY/AliFemtoUser/AliFemtoCorrFctnMezonPhi.cxx

Changed some previously overlooked lines to make code work as intended

Small fixes to code

---

PWGJE/EMCALJetTasks/UserTasks/AliAnalysisTaskNewJetSubstructure.cxx

The power here is set by the variable fPowerAlgo. For nominal C/A reclustering, fPowerAlgo would be set to 0.

[PWGJE/EMCALJetTasks/]: Change to generalized kT reclustering.

---

PWGMM/UE/UeKNO/AliAnalysisTaskFlatenicity.cxx
PWGMM/UE/UeKNO/AliAnalysisTaskFlatenicity.h

Cuts updated to values indicated by Omar.   Some duplicated cuts now disabled
Added my implementation of Signal and Event Loss calculation for flatenicity classes.  Needed to generate values to implement Closure test.   Will be later compared with implementation that Omar has to provide.

Cuts updated. Added signal and Event Loss for Flatenicity

---

PWGJE/EMCALJetTasks/UserTasks/AliAnalysisTaskNewJetSubstructure.cxx
PWGJE/EMCALJetTasks/UserTasks/AliAnalysisTaskNewJetSubstructure.h

Inclusion of ability to use event-plane angle calibrations in substructure task. (Some spacing alignment was also done.)

AliAnalysisTaskNewJetSubstructure - inclusion of EP calibrations

---

PWGCF/FLOW/GF/AliAnalysisTaskCorrForFlowFMD.cxx

jet veto implementation

---

PWGHF/vertexingHF/AliAnalysisTaskSEXicPlusToXi2PifromKFP.cxx
PWGHF/vertexingHF/AliAnalysisTaskSEXicZero2XiPifromKFP.cxx
PWGHF/vertexingHF/vHFML/AliHFMLXicZeroToXiPifromKFP.cxx

Update TOF PID using AliAODPidHF

Update TOF PID using AliAODPidHF

---

PWGCF/Correlations/KaonCorrelations/AliAnalysisTaskKaon2PC.cxx
PWGCF/Correlations/KaonCorrelations/AliAnalysisTaskKaon2PC.h

Added event mixing background for K+K- correlation, Track selection cut for charged kaon with TOF info, Centrality changed to 20-30%

Updated code with K+K- background

---

PWGJE/EMCALJetTasks/UserTasks/AliAnalysisTaskNewJetSubstructure.cxx
PWGJE/EMCALJetTasks/UserTasks/AliAnalysisTaskNewJetSubstructure.h

Addition of flag for pileup cuts in substructure task. Also some spacing alignment.

AliAnalysisTaskNewJetSubstructure - add flag for pileup cuts

---

PWGCF/Correlations/KaonCorrelations/AliAnalysisTaskKaon2PC.cxx
PWGCF/Correlations/KaonCorrelations/AliAnalysisTaskKaon2PC.h

Turned on the calculation of K0s-Kch and K+K- correlations

Updated the event mixing algorithm

---

PWGDQ/dielectron/LMEE/AliAnalysisTaskOmegaDielectron_AccEff.h
PWGDQ/dielectron/macrosLMEE/AddTask_mwaelde_AcceptanceEfficiency.C

update streamer and add macro parameter

update streamer and add macro parameter

---

PWGCF/Correlations/KaonCorrelations/AliAnalysisTaskKaon2PC.cxx
PWGCF/Correlations/KaonCorrelations/AliAnalysisTaskKaon2PC.h

Initialization of fmcEvent was missing which caused the train test to fail.

Fixed a bug

---

PWGCF/FLOW/GF/AliAnalysisTaskCorrForFlowFMD.cxx
PWGCF/FLOW/GF/AliAnalysisTaskCorrForFlowFMD.h

check mass bias in all configurations

check mass bias in all configurations

---

PWGCF/Correlations/JCORRAN/Base/AliAnalysisSPCRun2.h
PWGCF/Correlations/macros/jcorran/AddTaskJSPCMasterRun2.C

Different correlations are split into different tasks to reduce the run time.

(PWGCF) Split for diff SPC

---

PWGCF/FLOW/GF/AliAnalysisTaskDeform.cxx

Added flag so weights are not erroneously applied when calculating weights

Fixed breaking when producing weights

---

PWGCF/FLOW/GF/AliAnalysisTaskCorrForFlowFMD.cxx

fixing the mass biasing counters in AliAnalysisTaskCorrForFlowFMD.cxx

fixing the mass biasing counters in AliAnalysisTaskCorrForFlowFMD.cxx

---

PWGJE/EMCALJetTasks/UserTasks/AliAnalysisTaskNewJetSubstructure.cxx
PWGJE/EMCALJetTasks/UserTasks/AliAnalysisTaskNewJetSubstructure.h

Addition of event-plane angle matching at truth-level. Some spacing adjustments.

AliAnalysisTaskNewJetSubstructure: addition of EP angle matching 

---

PWGCF/FEMTOSCOPY/AliFemto/AliFemtoSimpleAnalysis.cxx
PWGCF/FEMTOSCOPY/AliFemto/AliFemtoSimpleAnalysis.h
PWGCF/FEMTOSCOPY/AliFemtoUser/AliFemtoCutMonitorPairMomRes.cxx
PWGCF/FEMTOSCOPY/AliFemtoUser/AliFemtoCutMonitorPairMomRes.h

changes for easier use of mixing event for some monitor plots 
adding new plots to momentum resolution class
removing old changes that were just for temporary checks

changes for easier way to include mixing events in some monitor plots

---

PWGJE/EMCALJetTasks/UserTasks/AliAnalysisTaskNewJetSubstructure.cxx

addition of comments for documentation

AliAnalysisTaskNewJetSubstructure: addition of documentation

---

PWGCF/Correlations/DPhi/Unfoldedhistos/Ali2PCorrelations.cxx
PWGCF/Correlations/DPhi/Unfoldedhistos/AliAnalysisTaskCorrelationsStudies.cxx
PWGCF/Correlations/DPhi/Unfoldedhistos/AliCSTrackSelection.cxx
PWGCF/Correlations/DPhi/Unfoldedhistos/AliCSTrackSelection.h
PWGCF/Correlations/DPhi/Unfoldedhistos/AliTwoParticleCorrelationsBase.cxx
PWGCF/Correlations/DPhi/Unfoldedhistos/AliTwoParticleCorrelationsBase.h

Also fixing a bug which accepted 6% more generated particles than it should

Incorporating the identified two particle correlations

---

PWGCF/FLOW/GF/AliAnalysisTaskCorrForFlowFMD.cxx
PWGCF/FLOW/GF/AliAnalysisTaskCorrForFlowFMD.h

updating jetveto configuration

updating jetveto configuration

---

PWGHF/vertexingHF/AliAnalysisTaskSEXic0SL.cxx
PWGHF/vertexingHF/AliAnalysisTaskSEXic0SL.h

- Addressed pileup rejection in MC for pass2 migration
- Updated tree structure to properly separate each decay mode

Xic0SL tree update for decay mode separation

---

PWGGA/GammaConv/macros/AddTask_GammaCalo_pPb.C
PWGGA/GammaConvBase/AliCaloPhotonCuts.cxx
PWGGA/GammaConvBase/AliConversionMesonCuts.cxx

Different eta configurations were changed for PHOS. Another rapidity cut for PHOS was introduced.

PWGGA/GammaConv: Acceptance Studies PHOS

---

PWGDQ/dielectron/LMEE/AliAnalysisTaskGammaPythia.cxx
PWGDQ/dielectron/LMEE/AliAnalysisTaskGammaPythia.h
PWGDQ/dielectron/macrosLMEE/AddMCGen_Pythia8_13TeV_Monash.C
PWGDQ/dielectron/macrosLMEE/AddTask_GammaPythia.C

- bug fix and added histograms to see gamma pt vs multiplicity  
- added event histogram MB and HM separately 
- added monitor plot to check PDG of particle, mother particle, grand mother particle
- cleanup histograms

Update Pythia8 Gamma study

---

PWGCF/FLOW/GF/AliAnalysisTaskDeform.cxx
PWGCF/FLOW/GF/AliAnalysisTaskDeform.h
PWGCF/FLOW/GF/AliGFWCuts.cxx

Changed cut 3 in AliGFWCuts back to 4sigma in DCAxy

Added setter to enable FB768 dcaxy cut

---

PWGGA/GammaConvBase/AliResponseMatrixHelper.cxx
PWGGA/GammaConvBase/AliResponseMatrixHelper.h

- This fixes an issue when getting the index of the respective 2D histogram
- Add to get a single 2D response matrix from the full ND response matrix

PWGGA/GammaConv: Fix for NDimensinoal matrix handler

---

PWGDQ/dielectron/LMEE/AliAnalysisTaskGammaPythia.cxx
PWGDQ/dielectron/LMEE/AliAnalysisTaskGammaPythia.h
PWGDQ/dielectron/macrosLMEE/AddTask_GammaPythia.C

- single add task setting, single multiplicity class

Added flexibility to choose multiplicty (min & max)

---

PWGHF/vertexingHF/AliAnalysisTaskSEDvsEventShapes.cxx
PWGHF/vertexingHF/AliAnalysisTaskSEDvsEventShapes.h
PWGHF/vertexingHF/macros/AddTaskDvsEventShapes.C

Edited multiple parts, skimming past quantile commit and added total THnSparse for Spline creation (and testing)

Cleaned code + implementation of tot. events THnSparse within fid. acc. 

---

PWGHF/vertexingHF/AliAnalysisTaskSEXicPlus2XiPiPifromAODtracks.cxx
PWGHF/vertexingHF/AliAnalysisTaskSEXicPlus2XiPiPifromAODtracks.h
PWGHF/vertexingHF/macros/AddTaskXicPlus2XiPiPifromAODtracks.C

The histograms for efficiency calculations were added.

Add histograms for efficiency

---

PWGJE/EMCALJetTasks/UserTasks/AliAnalysisTaskNewJetSubstructure.cxx
PWGJE/EMCALJetTasks/UserTasks/AliAnalysisTaskNewJetSubstructure.h

Flag to save Lund plane hists. Additionally, edit to kinematic efficiency hists.

AliAnalysisTaskNewJetSubstructure - flag to save Lund hists

---

PWGJE/EMCALJetTasks/UserTasks/AliAnalysisTaskNewJetSubstructure.cxx

Only provide hist definitions when flag turned on in attempt to be more memory friendly.

AliAnalysisTaskNewJetSubstructure - hists not defined when flag is off

---

PWGHF/vertexingHF/AliAnalysisTaskSESemileptonicOmegac0KFP.cxx

Add TPC variables in TTree, which will be used for offline systematic study.

Add TPC variables in TTree

---

PWGJE/EMCALJetTasks/UserTasks/AliAnalysisTaskNewJetSubstructure.cxx

Move pTthreshold cut to interface with kinematic efficiency histograms.

AliAnalysisTaskNewJetSubstructure - update to pTthreshold

---

PWGHF/vertexingHF/AliAnalysisTaskSEXic0SL.cxx
PWGHF/vertexingHF/AliAnalysisTaskSEXic0SL.h

Minor debugging to avoid segfault during the pA run

Xic0SL: debugged the part causing segfault for pA

---

PWGHF/vertexingHF/AliAnalysisTaskSESemileptonicOmegac0KFP.cxx

a mistake is fixed for the ratios

change Data type to Float_t

---

PWGCF/FEMTOSCOPY/macros/Train/KM/pPb502/MC/001/ConfigFemtoAnalysis.C
PWGCF/FEMTOSCOPY/macros/Train/KM/pPb502/MC/AddTaskFemto.C

Konstanin: configuration for MC pPb K+K- wagon 001

---

PWGHF/vertexingHF/vHFML/AliHFMLXicZeroToXiPifromKFP.cxx

Donot search up to quark when matching to MC

Donot search up to quark when matching to MC

---

PWGHF/vertexingHF/vHFML/AliHFMLXicZeroToXiPifromKFP.cxx
PWGHF/vertexingHF/vHFML/AliHFMLXicZeroToXiPifromKFP.h

Add combined TPC and TOF nsigma

Add combined TPC and TOF nsigma

---

PWGGA/GammaConv/macros/AddTask_GammaCalo_PbPb.C

- in the PR #22305 three train configs had the same name

[PWGEM-13] PWGGA/GammaConv: Fix same config name from PR #22305

---

PWGJE/EMCALJetTasks/UserTasks/AliAnalysisTaskNewJetSubstructure.cxx
PWGJE/EMCALJetTasks/UserTasks/AliAnalysisTaskNewJetSubstructure.h

In addition some small spacing issues were fixed in order to make the code more readable.

[PWGJE/EMCALJetTasks/UserTasks/]: Add formation time to jet substructure task.

---

PWGJE/EMCALJetTasks/UserTasks/AliAnalysisJetHadro.cxx
PWGJE/EMCALJetTasks/UserTasks/AliAnalysisJetHadro.h
PWGJE/EMCALJetTasks/macros/AddTask_siweyhmi_JetHadro.C

I tested building AliPhysics with these changes locally, and it was successful.

added more options to downsize output, MC capabilities

---

PWGHF/hfe/macros/AddTaskEHCorrel.C

Fixed issue with selecting MB and cent trigger candidates. This should only select cent trigger for now.

Fixed issue with event selection

---

PWGHF/vertexingHF/AliAnalysisTaskSEXic0SL.cxx

To respond Lego train segfault issue

Xic0SL: increased max. array size

---

PWGJE/EMCALJetTasks/UserTasks/AliAnalysisTaskEmcalJetHdEdxCorrelations.cxx

Adding z-vertex to sparse
Limiting z vertext to +-10

Fixed mismatched bracket

---

PWG/EMCAL/EMCALbase/AliAnalysisTaskEmcal.cxx
PWG/EMCAL/EMCALtasks/AliAnalysisTaskEmcalTriggerSelection.cxx
PWG/EMCAL/EMCALtasks/AliEmcalCorrectionClusterNonLinearityMCAfterburner.cxx

PWG/EMCAL Adding pPb 8.16 TeV production LHC23d7a/b to configuration options.

PWG/EMCAL Adding pPb 8.16 TeV production LHC23d7a/b to configuration options.

---

PWGHF/hfe/AliAnalysisTaskEHCorrel.cxx

Improved some optimization within the task involving the hadron selection cut.

Optimized task in hadron cut

---

PWGHF/vertexingHF/AliAnalysisTaskSEDvsEventShapes.cxx

There were issues due the size of the THnSparse. This became clear only when running on the full dataset with the latest addition.

Improved memory issue due to THnSparse

---

PWGLF/SPECTRA/MultEvShape/AliMESppColTask.cxx

Combined Multiplicity and Sphericity Event Shape analysis; merged the last multiplicity bins to match the 7TeV analysis

Merged the last multiplicity bins to match the 7TeV analysis

---

PWGCF/EBYE/IntermittencyAnalysis/AliAnalysisTaskNFactorialMoments.cxx
PWGCF/EBYE/IntermittencyAnalysis/AliAnalysisTaskNFactorialMoments.h
PWGCF/EBYE/macros/AddTaskNFactorialMoments.C

- Added the cluster cuts for AODs
- QA histograms
- An option to use other Mmax value

Adding Clusters cuts

---

PWGGA/GammaConv/AliAnalysisTaskMesonJetCorrelation.cxx
PWGGA/GammaConv/macros/AddTask_MesonJetCorr_Calo.C
PWGGA/GammaConv/macros/AddTask_MesonJetCorr_Conv.C
PWGGA/GammaConv/macros/AddTask_MesonJetCorr_ConvCalo.C
PWGGA/GammaConvBase/AliConversionMesonCuts.cxx
PWGGA/GammaConvBase/AliConversionMesonCuts.h

- For QA studies, a mode where decay particles have to be inside a jet is added
- sets the DoOutOfJet flag to 5 in MesonCuts
- Cut configs are added to the add task

PWGGA/GammaConv: Add in-jet mode where decay particles have to be in jet

---

PWGJE/EMCALJetTasks/UserTasks/AliAnalysisJetHadro.cxx
PWGJE/EMCALJetTasks/UserTasks/AliAnalysisJetHadro.h

added jet area cut, fixed small output option, changed z vertex cut and pileup cuts

added jet area cut, fixed small output, changed z vertex and pileup cuts

---

PWGMM/Mult/AliSPDppAnalysisTaskData.cxx
PWGMM/Mult/AliSPDppAnalysisTaskData.h
PWGMM/Mult/AliSPDppAnalysisTaskSim.cxx
PWGMM/Mult/AliSPDppAnalysisTaskSim.h
PWGMM/Mult/macros/AddTaskSPDppData.C
PWGMM/Mult/macros/AddTaskSPDppSim.C

Uploading 2 analysis for data and for simulation to generate a multiplicity distribution for INEL events in pp collisions

Multiplicity Analysis at mid rapidity for pp @ 13TeV using Tracklets

---

PWGHF/hfe/AliAnalysisTaskBEpp13TeV.cxx
PWGHF/hfe/AliAnalysisTaskBEpp13TeV.h
PWGHF/hfe/macros/AddTaskBEpp13TeV.C

Implement multiplicity profile for multiplicity dependence study

Implement multiplicity profile

---

PWGMM/Mult/AliSPDppAnalysisTaskData.cxx
PWGMM/Mult/AliSPDppAnalysisTaskData.h
PWGMM/Mult/AliSPDppAnalysisTaskSim.cxx
PWGMM/Mult/AliSPDppAnalysisTaskSim.h
PWGMM/Mult/CMakeLists.txt
PWGMM/Mult/PWGMMMultLinkDef.h
PWGMM/Mult/macros/AddTaskSPDppData.C
PWGMM/Mult/macros/AddTaskSPDppSim.C

Standard event cuts were added and histograms to determine the multiplicity of inel>0 events

Tracklet Multiplicity analysis including standard event cuts including inel and inel>0

---

PWGGA/GammaConv/AliAnalysisTaskMesonJetCorrelation.cxx
PWGGA/GammaConv/AliAnalysisTaskMesonJetCorrelation.h
PWGGA/GammaConv/macros/AddTask_MesonJetCorr_Calo.C
PWGGA/GammaConv/macros/AddTask_MesonJetCorr_ConvCalo.C

- configs for EMC and PCM-EMC added (PCM will follow) for systamtcs
- Additional Herwig JJ MC outlier rejection added (experimental in that stage). For this, all events are rejected where a true jet with 1.5 times the pt hard is found

PWGGA/GammaConv: Add jet-meson configs for Systsmatics

---

PWGHF/hfe/AliAnalysisTaskEHCorrel.cxx

Included alternative mixed event centrality binning to test ME systematics.

Edit for mixed event systematics

---

PWGHF/vertexingHF/AliAnalysisTaskSEXicPlus2XiPiPifromAODtracks.cxx
PWGHF/vertexingHF/AliAnalysisTaskSEXicPlus2XiPiPifromAODtracks.h
PWGHF/vertexingHF/macros/AddTaskXicPlus2XiPiPifromAODtracks.C

Fix location of the counters and add some counters for check
Add a tree for generated level Xic variables

Modify counters and add generated level variables

---

PWGGA/GammaConv/AliAnalysisTaskNeutralMesonToPiPlPiMiNeutralMeson.cxx
PWGGA/GammaConv/macros/AddTask_GammaConvNeutralMesonPiPlPiMiNeutralMeson_CaloMode_PbPb.C
PWGGA/GammaConv/macros/AddTask_GammaConvNeutralMesonPiPlPiMiNeutralMeson_ConvMode_PbPb.C

- Cutstring for omega PbPb in EMCal and PCM AddTask added
- Add MBWs in PbPb PCM AddTask
- Fix memory leak in omega task (delete new pointer)

PWGGA/GammaConv: Add omega PbPb cutstrings and bug fixed

---

PWGHF/vertexingHF/AliAnalysisTaskSESemileptonicOmegac0KFP.cxx
PWGHF/vertexingHF/AliAnalysisTaskSESemileptonicOmegac0KFP.h
PWGHF/vertexingHF/macros/AddTaskOmegac2eleOmegafromKFP.C

This commit is used for the MC closure test: do bkg subtraction in MC, which is the same as data approach

MC closure test (do bkg subtraction in MC)

---

PWGJE/EMCALJetTasks/Tracks/AliAnalysisTaskEmcalJetEnergySpectrum.cxx
PWGJE/EMCALJetTasks/Tracks/AliAnalysisTaskEmcalJetEnergySpectrum.h

PWGJE/EMCALJetTasks/Tracks/AliAnalysisTaskEmcalJetEnergySpectrum - Addding pT differential delta-pT histogram

PWGJE/EMCALJetTasks/Tracks/AliAnalysisTaskEmcalJetEnergySpectrum - Addding pT differential delta-pT histogram

---

PWGHF/vertexingHF/AliAnalysisTaskSEXic0SL.cxx
PWGHF/vertexingHF/AliAnalysisTaskSEXic0SL.h

nSPDTracklets added for reweighting

---

PWGCF/EBYE/IntermittencyAnalysis/AliAnalysisTaskNFactorialMoments.cxx
PWGCF/EBYE/IntermittencyAnalysis/AliAnalysisTaskNFactorialMoments.h
PWGCF/EBYE/macros/AddTaskNFactorialMoments.C

hi, added:
- closure based on the profile plot of shared fraction vs pt, rather than a direct cut on shared fraction and related QA histograms
- bfield systematics
- and some other changes
thanks

optimizing code for closure

---

PWGJE/EMCALJetTasks/UserTasks/AliAnalysisJetHadro.cxx
PWGJE/EMCALJetTasks/UserTasks/AliAnalysisJetHadro.h

To reduce the output enough to save all the inclusive stats

changed to histogram output

---

PWGCF/EBYE/macros/AddTaskNFactorialMoments.C

- just adding one parameter to the AddTask, so that I will be use subwagons on the legotrain system

NFM for subwagons

---

PWGCF/Correlations/KaonCorrelations/AliAnalysisTaskKaon2PC.cxx
PWGCF/Correlations/KaonCorrelations/AliAnalysisTaskKaon2PC.h

Combined pT dependent PID using TPC and TOF added, MC generated and reconstructed correlations added, Trigger updated

Updated code

---

PWGCF/EBYE/IntermittencyAnalysis/AliAnalysisTaskNFactorialMoments.cxx
PWGCF/EBYE/macros/AddTaskNFactorialMoments.C

minor fix for subwagons and centrality calculation

minor fix NFMs

---

PWGGA/GammaConv/AliAnalysisTaskMesonJetCorrelation.cxx
PWGGA/GammaConv/AliAnalysisTaskMesonJetCorrelation.h
PWGGA/GammaConv/macros/AddTask_MesonJetCorr_Calo.C
PWGGA/GammaConv/macros/AddTask_MesonJetCorr_Conv.C
PWGGA/GammaConv/macros/AddTask_MesonJetCorr_ConvCalo.C

- New histogram to check the eta and phi acceptance for MC level jets
- New cuts with larger eta range for FF studies

PWGGA/GammaConv: Add histograms for eta+phi for true jets

---

PWGHF/vertexingHF/AliAnalysisTaskSEXicPlus2XiPiPifromAODtracks.cxx
PWGHF/vertexingHF/AliAnalysisTaskSEXicPlus2XiPiPifromAODtracks.h

Minor debug on loop over generated level Xic candidates tree

Minor modificaion in GenLevTree

---

PWGCF/Correlations/KaonCorrelations/AliAnalysisTaskKaon2PC.cxx
PWGCF/Correlations/KaonCorrelations/AliAnalysisTaskKaon2PC.h

Updated the code with more event counters and switch for nsigma cuts

More event counters added, loose nsigma cuts

---

PWG/EMCAL/EMCALtrigger/AliEmcalTriggerAlias.cxx
PWG/EMCAL/EMCALtrigger/AliEmcalTriggerAlias.h
PWG/EMCAL/EMCALtrigger/AliEmcalTriggerDecisionContainer.cxx
PWG/EMCAL/EMCALtrigger/AliEmcalTriggerDecisionContainer.h

Add option to combine triggers in option
- all: All triggers required to be present in event for
positive decision
- any: Any trigger required to be present in event for
positive decision

Add combination of triggers

---

PWGCF/Correlations/KaonCorrelations/AliAnalysisTaskKaon2PC.cxx
PWGCF/Correlations/KaonCorrelations/AliAnalysisTaskKaon2PC.h

pT dependent PID combining TPC and TOF nSigma, looser cuts to increase the statistics in reconstructed data.

pT dependent PID added

---

PWGCF/FEMTOSCOPY/AliFemto/AliAnalysisTaskFemto.cxx

…issue (somehow alifemto wagons even if are different generate the same output if are run together). TEST

A small change of the femto code that may help to fix a wagon overwritting issue

---

PWGGA/GammaConv/AliAnalysisTaskGammaConvCalo.cxx

- This fixes the name of the new hisotgram introduced in PR #22629

[PWGEM-13] PWGGA?GammaConv Fix histo name

---

PWGCF/EBYE/IntermittencyAnalysis/AliAnalysisTaskNFactorialMoments.cxx
PWGCF/EBYE/IntermittencyAnalysis/AliAnalysisTaskNFactorialMoments.h
PWGCF/EBYE/macros/AddTaskNFactorialMoments.C

- Added PID information related to TOF and TPC, so that a PID based analysis can be started.

PIDIntermittencyAnalysis

---

PWGCF/Correlations/KaonCorrelations/AliAnalysisTaskKaon2PC.cxx
PWGCF/Correlations/KaonCorrelations/AliAnalysisTaskKaon2PC.h

updated the phi resonance rejection in k+k- correlation.

update to phi rejection

---

PWGCF/Correlations/KaonCorrelations/AliAnalysisTaskKaon2PC.cxx

cut to remove the resonances of k0s is added. (k0s always have a mother particle)

reject resonances of k0s

---

PWGHF/hfe/AliAnalysisTaskBEpp13TeV.cxx
PWGHF/hfe/AliAnalysisTaskBEpp13TeV.h
PWGHF/hfe/macros/AddTaskBEpp13TeV.C

Code clean up for multiplicity dependence study

Code clean up

---

PWGCF/Correlations/KaonCorrelations/AliAnalysisTaskKaon2PC.cxx
PWGCF/Correlations/KaonCorrelations/AliAnalysisTaskKaon2PC.h

pt distribution of tracks after resonance rejection is added

update to resonance rejection

---

PWGCF/FEMTOSCOPY/AliFemtoUser/AliAnalysisTaskEfficiencyPbPb_DR.cxx
PWGCF/FEMTOSCOPY/AliFemtoUser/AliAnalysisTaskEfficiencyPbPb_DR.h
PWGCF/FEMTOSCOPY/AliFemtoUser/CMakeLists.txt
PWGCF/FEMTOSCOPY/AliFemtoUser/PWGCFfemtoscopyUserLinkDef.h
PWGCF/FEMTOSCOPY/macros/AddTaskEffPbPb_DR.C

Efficiency task for Pb-Pb collision using FB128

EfficiencyPbPb

---

PWGGA/PHOSTasks/PHOS_Nbar/AddTaskPHOSSigmaBar.C
PWGGA/PHOSTasks/PHOS_Nbar/AliAnalysisSigmaBarCharged.cxx
PWGGA/PHOSTasks/PHOS_Nbar/AliAnalysisSigmaBarCharged.h

Update SigmaBar code

---

PWGMM/UE/UeKNO/AddMyTaskDeutFlucpp.C
PWGMM/UE/UeKNO/AliAnalysisTaskDeutFlucpp.cxx
PWGMM/UE/UeKNO/AliAnalysisTaskDeutFlucpp.h

This pull request includes few updates to enable analyses with MC.

Update for MC

---

PWGHF/vertexingHF/AliVertexingHFUtils.cxx
PWGHF/vertexingHF/AliVertexingHFUtils.h
PWGHF/vertexingHF/vHFML/AliHFMLXicZeroToXiPifromKFP.cxx

Add calculation of opening angle for KF in AliVertexingHFUtils and add opening angle of Xi to pion for Xic0 Pb-Pb analysis

Add calculation of opening angle for KF in AliVertexingHFUtils

---

PWGCF/FEMTOSCOPY/EfficiencyTask/AliAnalysisTaskParticleEfficiencyMezonPhiDR.cxx
PWGCF/FEMTOSCOPY/EfficiencyTask/AliAnalysisTaskParticleEfficiencyMezonPhiDR.h
PWGCF/FEMTOSCOPY/macros/AddTaskEfficiencyMezonPhiDR.C

Separate task to calculate eff of mezon phi production with custom cuts to match femto analysis

Mezon Phi Eff for custom cuts

---

PWGCF/FEMTOSCOPY/AliFemtoUser/AliAnalysisTaskParticleEffWRZ.cxx
PWGCF/FEMTOSCOPY/AliFemtoUser/AliFemtoWRzTrackCut.cxx
PWGCF/FEMTOSCOPY/AliFemtoUser/AliFemtoWRzTrackCut.h

minor changes in my task 

---

PWGHF/hfe/AliAnalysisTaskBEpp13TeV.cxx
PWGHF/hfe/AliAnalysisTaskBEpp13TeV.h
PWGHF/hfe/macros/AddTaskBEpp13TeV.C

There was an error while it's running on train. It was tested on grid and confirmed it runs without error.

Issue fixed

---

PWGHF/vertexingHF/vHFML/AliHFMLXicZeroToXiPifromKFP.cxx

Add new and p_T dependent, based on 30-50% data and MC, 6% for 2-4 GeV/c and 3% for 4-12 GeV/c

Add new and p_T-dependent preselections

---

PWGMM/UE/UeKNO/AliAnalysisTaskDeutFlucpp.cxx
PWGMM/UE/UeKNO/AliAnalysisTaskDeutFlucpp.h

This commit does few minor updates related to MC.

minor update

---

PWGCF/FEMTOSCOPY/EfficiencyTask/AliAnalysisTaskParticleEfficiencyMezonPhiDR.cxx
PWGCF/FEMTOSCOPY/EfficiencyTask/CMakeLists.txt
PWGCF/FEMTOSCOPY/EfficiencyTask/PWGCFEfficiencyTaskLinkDef.h
PWGCF/FEMTOSCOPY/macros/AddTaskEfficiencyMezonPhiDR.C

Updated version of code for eff of mezon phi with custom cuts

Updated code for eff of mezon phi

---

PWGGA/GammaConv/AliAnalysisTaskGammaConvFlow.cxx
PWGGA/GammaConv/AliAnalysisTaskGammaConvFlow.h
PWGGA/GammaConv/macros/AddTask_GammaConvFlow_PbPb2.C

- Addtask was not running:
- Declared `void AddSPmethod` before AddTask to enable calling it inside the AddTask!
- Changed `isMC` from bool to int to update the event handling insinde the task itself
- Changed outputfile name from `GammaConvV1_` to `GammaConvFlow_` so it can be run together with the GammaConvV1 task without issues.
- Added some PbPb 2018 train configs
- Updated EventHistogram handling and added without weights version for MC

PWGGA/GammaConv: GammaConvFlow - Updated AddTask

---

PWGGA/GammaConv/AliAnalysisTaskGammaPureMC.cxx
PWGGA/GammaConv/AliAnalysisTaskGammaPureMC.h
PWGGA/GammaConv/macros/AddTask_GammaPureMC.C

- Output mothers of pi0s, etas and omegas
- Output yield of primordial (not from decay) pi0s, etas and omegas

PWGGA/GammaConv: Add feed-down analysis option to PureMC studies

---

PWGGA/GammaConv/macros/AddTask_GammaConvCalo_PbPb.C
PWGGA/GammaConv/macros/AddTask_GammaConvCalo_pPb.C
PWGGA/GammaConv/macros/AddTask_GammaConvCalo_pp.C

- Add the new dEdx recalib option `enableElecDeDxPostCalibration==2` to the GammaConvCalo AddTasks as was done before to the GammaConv AddTask by Stephan.

[PWGEM-13] PWGGA/GammaConv: AddTask_GammaConvCalo - Add dEdx recalib

---

PWGLF/RESONANCES/PostProcessing/f0980/AliAnalysisTaskInclusivef0f2.cxx
PWGLF/RESONANCES/PostProcessing/f0980/AliAnalysisTaskInclusivef0f2.h

[PWGLF] updates for qa plot

---

PWGLF/RESONANCES/macros/mini/ConfigPhiPP13TeV_PID.C

Modify the selection with no pileup

---

PWGLF/STRANGENESS/Cascades/Run2/AliAnalysisTaskStrangenessVsMultiplicityMCRun2.cxx

Reverts alisw/AliPhysics#22756 following a request from @dkaratov

Revert "Update AliAnalysisTaskStrangenessVsMultiplicityMCRun2.cxx"

---

PWGJE/EMCALJetTasks/UserTasks/AliAnalysisJetHadro.cxx
PWGJE/EMCALJetTasks/UserTasks/AliAnalysisJetHadro.h

First iteration adding in TOF PID information, including nsigma and beta distributions.

added TOF nsigma and beta distributions

---

PWGCF/FEMTOSCOPY/macros/Train/KM/pPb502/005/ConfigFemtoAnalysis.C

pi+pi- pPb 5.02 Config --> for Elena tests

---

PWGHF/vertexingHF/AliAnalysisTaskSEXicPlus2XiPiPifromAODtracks.cxx

Modify the generated level tree

Fix generated level tree

---

PWGHF/hfe/AliAnalysisTaskBEpp13TeV.cxx
PWGHF/hfe/AliAnalysisTaskBEpp13TeV.h
PWGHF/hfe/macros/AddTaskBEpp13TeV.C

Modify the multiplicity correction period by period, and code clean-up

Mult correction period by period

---

PWGGA/GammaConv/macros/AddTask_GammaCalo_pp.C
PWGGA/GammaConv/macros/AddTask_GammaConvCalo_pp.C

- For material budged uncertainty study of EMCal

PWGGA/GammaConv: Add cuts with and without TRD in front

---

PWGHF/hfe/macros/AddTaskBEpp13TeV.C

Modified a few lines that make errors in the train

Error Modification

---

PWGHF/hfe/AliAnalysisTaskWHMult.cxx

fixed # of cluster

---

PWGCF/Correlations/JCORRAN/Base/AliAnalysisSPCRun2.cxx
PWGCF/Correlations/JCORRAN/Base/AliAnalysisSPCRun2.h
PWGCF/Correlations/JCORRAN/Base/AliJCatalystTask.cxx
PWGCF/Correlations/JCORRAN/Base/AliJCatalystTask.h
PWGCF/Correlations/macros/jcorran/AddTaskJSPCMasterRun2.C

Number of bins were reduced for all QA histogram to better control memory consumption.

(PWGCF): Memory optimization & jTree added

---

PWGCF/FEMTOSCOPY/macros/Train/KM/pPb502/006/ConfigFemtoAnalysis.C

pipi pPb 5.02 Config --> for Elena tests 3d

---

PWGCF/FEMTOSCOPY/macros/AddTaskOtonXx.C

Xi-pi/K femto: Allow tune mixing for FemtoDream Pairing checks and MC resolution matrix

---

PWGCF/FEMTOSCOPY/macros/Train/KM/pPb502/007/ConfigFemtoAnalysis.C

pipi pPb5.02 3d -3,3 GeV/c

---

PWGGA/GammaConv/macros/AddTask_GammaConvCalo_PbPb.C

- Add new traincofnigs for ConvCalo for PbPb 2018qr with no TM

[PWGEM-13] PWGGA/GammaConv: Add Trainconfig for PbPb 2018qr

---

PWGLF/STRANGENESS/Cascades/Run2/AliAnalysisTaskStrangenessVsMultiplicityMCRun2.cxx
PWGLF/STRANGENESS/Cascades/Run2/AliAnalysisTaskStrangenessVsMultiplicityRun2.cxx
PWGLF/STRANGENESS/Cascades/Run2/AliCascadeResult.cxx
PWGLF/STRANGENESS/Cascades/Run2/AliCascadeResult.h
PWGLF/STRANGENESS/Cascades/Run2/AliV0Result.cxx
PWGLF/STRANGENESS/Cascades/Run2/AliV0Result.h
PWGLF/STRANGENESS/Cascades/Run2/AliVWeakResult.h

Configurable centrality estimator in results class

---

PWGHF/vertexingHF/AliAnalysisTaskSEXicPlus2XiPiPifromAODtracks.cxx
PWGHF/vertexingHF/AliAnalysisTaskSEXicPlus2XiPiPifromAODtracks.h

Modification in gen lev tree to see the different distribution of Ntracklet

Add variable to check tracklet distribution

---

PWGCF/FEMTOSCOPY/macros/Train/KM/pPb502/008/ConfigFemtoAnalysis.C

K+K+(K-K-) pPb 5.02 Config --> for Elena tests

---

PWGCF/FEMTOSCOPY/macros/Train/KM/pPb502/009/ConfigFemtoAnalysis.C

Wagon 009 ++,-- as,u

---

PWGCF/FEMTOSCOPY/macros/Train/KM/pPb502/008/ConfigFemtoAnalysis.C

KM->13_70 and other as 007

---

PWGCF/FEMTOSCOPY/macros/Train/KM/pPb502/009/ConfigFemtoAnalysis.C

009 ---> KM KK

---

PWGCF/FEMTOSCOPY/macros/Train/KM/pPb502/010/ConfigFemtoAnalysis.C

010-->KM pipi 02_05 05_10

---

PWG/EMCAL/EMCALtasks/AliEmcalAodTrackFilterTask.cxx
PWG/EMCAL/EMCALtasks/AliEmcalAodTrackFilterTask.h

This update contains:
a) An option for pt-dependent tracking efficiency reduction based on a yaml configuration. This update was ported based on the AliEmcalJet task 
b)Minor bugfixes of previous versions

Update of AOD track filter

---

PWGLF/STRANGENESS/Cascades/Run2/AliAnalysisTaskMCPredictions2pc.cxx
PWGLF/STRANGENESS/Cascades/Run2/AliAnalysisTaskMCPredictions2pc.h

Work by Kai Cui - thanks a lot!

Add 5th dimension with trigger pT

---

PWGCF/FEMTOSCOPY/macros/Train/KM/pPb502/011/ConfigFemtoAnalysis.C

::: KM 011->KK 02_05_10

---

PWGLF/RESONANCES/PostProcessing/f0980/AliAnalysisTaskInclusivef0f2.cxx

[PWGLF] remove obsolete histograms

---

cmake/FindROOT.cmake

ROOT switched from MAJOR.MINOR/PATCH to MAJOR.MINOR.PATCH.

Update FindROOT.cmake to work with ROOT 6.30.XX

---

PWGCF/FEMTOSCOPY/macros/Train/KM/pPb502/002a/ConfigFemtoAnalysis.C

002a --> 3d -3,+3

---

PWGHF/hfe/macros/AddTaskBEpp13TeV.C

Change the weight configuration for the number of tracklet equalization.

change weight configuration

---

PWGJE/EMCALJetTasks/UserTasks/AliAnalysisTaskEmcalJetValidation.cxx
PWGJE/EMCALJetTasks/UserTasks/AliAnalysisTaskEmcalJetValidation.h

- the track QA histos bininngs are modified to match with those of in O2Physics validation task
- VtxZ histogram renamed to a more standard name
- redundant lines of code and comments are now removed

fixed trackQA binning+ removed redundant comments

---

PWGGA/PHOSTasks/PHOS_Run2/macros/AddTaskPHOSPi0EtaToGammaGamma_PbPb_5TeV.C

Parameter char *sub_name is added to AddTaskPHOSPi0EtaToGammaGamma_PbPb_5TeV in order to run subwagons on the analysis-train

PWGGA/PHOS: parameter for subwagons is added

---

PWGCF/EBYE/IntermittencyAnalysis/AliAnalysisTaskNFactorialMoments.cxx
PWGCF/EBYE/IntermittencyAnalysis/AliAnalysisTaskNFactorialMoments.h
PWGCF/EBYE/macros/AddTaskNFactorialMoments.C

- Removed a couple of statements that caused removal of extra tracks.
- Removed everything related to PID analysis, and will create a new PR with new code for proton intermittency.
-  Cleaned up the code

PIDbug fix

---

PWGJE/EMCALJetTasks/UserTasks/AliAnalysisTaskEmcalJetHdEdxCorrelations.cxx
PWGJE/EMCALJetTasks/UserTasks/AliAnalysisTaskEmcalJetHdEdxCorrelations.h

As well as passing the AliVTrack object to the AliEventPool so I can get the TOF PID info in mixed events.

Adding protections against inf and nan to make Mixed Events finite.

---

PWGCF/EBYE/IntermittencyAnalysis/AliAnalysisTaskNFactorialMoments.cxx
PWGCF/EBYE/IntermittencyAnalysis/AliAnalysisTaskNFactorialMoments.h
PWGCF/EBYE/macros/AddTaskNFactorialMoments.C

fixed an issue that caused the lego runs to crash for this task

fixforlego

---

PWGJE/EMCALJetTasks/UserTasks/AliAnalysisTaskEmcalJetHdEdxCorrelations.cxx

I think I have finally fixed my mixed event woes. 

---

PWGCF/FEMTOSCOPY/macros/Train/KM/pPb502/MC/002/ConfigFemtoAnalysis.C

KM -> MC pPb 002

---

PWGHF/hfe/AliAnalysisTaskBEpp13TeV.cxx

Weight values for Ntrklet distribution were wrongly called from weight histogram

Bug modification

---

PWGCF/FEMTOSCOPY/FemtoDream/AliAnalysisTaskFemtoDreamRho.cxx
PWGCF/FEMTOSCOPY/FemtoDream/AliAnalysisTaskFemtoDreamRho.h
PWGCF/FEMTOSCOPY/FemtoDream/AliFemtoDreamv0Cuts.h
PWGCF/FEMTOSCOPY/macros/AddTaskFemtoDreamRho.C

I needed to code some additional getter fct. in the DreamBase class. This will *NOT* impact default behaviour.

Femto: Add MC Truth selection and ancestor analysis.

---

PWGCF/FEMTOSCOPY/macros/Train/KM/pPb502/MC/002/ConfigFemtoAnalysis.C

MC pPb5.02 --> 002 ConfigFemtoAnalysis.C

---

PWGCF/Correlations/JCORRAN/Pro/AliJHFTagging.cxx
PWGCF/Correlations/JCORRAN/Pro/AliJHFTagging.h

A bug has been fixed. And histograms for counting the number of candidates have been added.

Adding more histograms and bug fix

---

PWGGA/GammaConv/AliAnalysisTaskGammaIsoTree.cxx
PWGGA/GammaConv/AliAnalysisTaskGammaIsoTree.h
PWGGA/GammaConv/macros/AddTask_GammaIsoTree.C

- Add Jet option in AddTask and AnalysisTask for gamma-jet correlation studies
- Add true and reconstructed jet momenta leafs to the tree

PWGGA/GammaConv: Add Jet output to isolated gamma tree

---

PWGGA/GammaConv/macros/AddTask_GammaCalo_PbPb.C
PWGGA/GammaConv/macros/AddTask_GammaConvCalo_PbPb.C
PWGGA/GammaConvBase/AliCaloPhotonCuts.cxx

- Added added signal train configs
- Made single cent bin train configs for better running on the MC for EMC and PCM-EMC
- Adjusted RejectExtraSignalCut for MC for EMC

[PWGEM-13] PWGGA/GammaConv: Addition of AddedSignal for EMCal

---

PWGCF/FLOW/GF/AliAnalysisPtN.cxx
PWGCF/FLOW/GF/AliAnalysisPtN.h
PWGCF/FLOW/GF/CMakeLists.txt
PWGCF/FLOW/GF/PWGCFFLOWGFLinkDef.h
PWGCF/FLOW/macros/AddTaskPtN.C

Added AliAnalysisPtN to calculate mean pt and higher order pt fluctuations with respect to Nch. This task will be further on contributed to the research in speed of sound in QGP.

New code to analyse mean pt and pt fluctuations with respect to N charged particles

---

PWGCF/FEMTOSCOPY/macros/Train/KM/pPb502/MC/003/ConfigFemtoAnalysis.C

KM==> 003 MC pPb502

---

PWGCF/FEMTOSCOPY/macros/Train/KM/pPb502/MC/003a/ConfigFemtoAnalysis.C

Konstantin->CF_pPb_MC->003a

---

PWGCF/Correlations/DPhi/AliAnalysisTaskR2P2spheroDiffpT.cxx
PWGCF/Correlations/DPhi/AliAnalysisTaskR2P2spheroDiffpT.h
PWGCF/Correlations/DPhi/CMakeLists.txt
PWGCF/Correlations/DPhi/PWGCFCorrelationsDPhiLinkDef.h
PWGCF/Correlations/macros/dptdptcorrelations/AddTaskR2P2spheroDiffpT.C

These new set of macros are added to study R2 and P2 correlation functions in different pt ranges

R2 & P2 with different pt ranges

---

PWGHF/vertexingHF/AliAnalysisTaskSESemileptonicOmegac0KFP.cxx

Add  a new branch in the Tree

---

PWGCF/FEMTOSCOPY/AliFemto/AliFemtoV0TrackCut.cxx

Added Armenteros-podolanski quality cut in the V0 reconstruction class `AliFemtoV0TrackCut`

Added Armenteros-podolanski Quality Cut in the V0 Reconstruction Class

---

PWGCF/FEMTOSCOPY/AliFemto/AliFemtoV0TrackCut.cxx
PWGCF/FEMTOSCOPY/AliFemto/AliFemtoV0TrackCut.h

Added cut on Lifetime of K0s Reconstruction and a switch for turning on/off the armenteros-podolonski cut in the class `AliFemtoV0TrackCut`

Added cut on Lifetime of K0s Reconstruction

---

PWGGA/GammaConv/macros/AddTask_GammaConvCalo_pPb.C

- introduced by previous commit https://github.com/alisw/AliPhysics/pull/22785

PWGGA/GammaConv: Fix undefined variable in pPb ConvCalo AddTask

---

PWGGA/GammaConv/macros/AddTask_GammaCalo_PbPb.C
PWGGA/GammaConv/macros/AddTask_GammaConvCalo_PbPb.C

- Add functionality to use pT weighting for added signal MC for LHC18q anchored MC

[PWGEM-13] PWGGA/GammaConv: (Conv)Calo AddTask - Add pT weighting

---

PWGCF/EBYE/IntermittencyAnalysis/AliAnalysisTaskNFactorialMoments.cxx
PWGCF/EBYE/macros/AddTaskNFactorialMoments.C

- adding a systematic check related to DCA

CF: systematic

---

PWGGA/GammaConv/macros/AddTask_ConvCaloCalibration_CaloMode_PbPb.C
PWGGA/GammaConvBase/AliCaloPhotonCuts.cxx
PWGGA/GammaConvBase/AliCaloPhotonCuts.h

- Added new AddTask AddTask_ConvCaloCalibration_CaloMode_PbPb.C to run and calibrate cluster energy in PbPb
- Added train configs to AddTask_ConvCaloCalibration_CaloMode_pp.C as comparison for the PbPb train configs

PWGGA/GammaConv: Add AddTask for ConvCaloCalib for PbPb

---

PWGCF/FLOW/GF/AliAnalysisPtN.cxx

Fixed typos in the boostrap part in AliAnalysisPtN.cxx

[PAG-Flow] Fixed typos in the boostrap part in AliAnalysisPtN.cxx

---

PWGHF/hfe/AliAnalysisTaskBEpp13TeV.cxx
PWGHF/hfe/AliAnalysisTaskBEpp13TeV.h

split the number of multiplicity bins

split the number of multiplicity bins

---

PWGCF/FEMTOSCOPY/AliFemto/AliAnalysisTaskFemto.cxx
PWGCF/FEMTOSCOPY/AliFemto/AliAnalysisTaskFemto.h
PWGCF/FEMTOSCOPY/AliFemto/AliFemtoEventReaderAOD.cxx
PWGCF/FEMTOSCOPY/AliFemto/AliFemtoEventReaderAOD.h
PWGCF/FEMTOSCOPY/AliFemto/AliFemtoV0.cxx
PWGCF/FEMTOSCOPY/AliFemto/AliFemtoV0.h
PWGCF/FEMTOSCOPY/AliFemtoUser/AliFemtoCorrFctnDEtaDPhiSimpleWithCorrections.cxx
PWGCF/FEMTOSCOPY/AliFemtoUser/AliFemtoCorrFctnDEtaDPhiSimpleWithCorrections.h

Adding K0s correction in AliFemto code

applying correction for K0s in femto code

---

PWGCF/FLOW/GF/AliAnalysisPtN.cxx
PWGCF/FLOW/GF/AliAnalysisPtN.h

Added histograms of 2 and 3 order pt fluctuation with respect to centrality.

[PAG-Flow]add histograms of 2 and 3 order pt fluctuation--centrality

---

PWGCF/EBYE/DiffPTF/AliAnalysisTaskDiffPtFluc_MCnoESD_correction.cxx

Checking efficiency correction: putiting weights in histogram

---

PWGCF/FLOW/GF/AliAnalysisTaskCorrForFlowMaster.h

Added setter for Cent. calibration for on the fly sim

Added setter for Cent. calibration

---

PWGGA/GammaConv/macros/AddTask_GammaCalo_PbPb.C
PWGGA/GammaConv/macros/AddTask_GammaConvCalo_PbPb.C

- Add the new InjectionHeaders that were made for the added signal MC LHC24a1 for EMCal:
- `"Injector (pi0e)"` to `"Injector (pi0i)"`
- `"Injector (etab)"` to `"Injector (etaf)"`

PWGGA/GammaConv: Add new EMC Injection Header to AddTasks

---

PWGHF/vertexingHF/AliAnalysisTaskSEXic0SL.cxx

For Xic0 -> eXi analysis' multiplicity reweighting study

Updated nSPDTracklet method

---

PWGCF/EBYE/IntermittencyAnalysis/AliAnalysisTaskNFactorialMoments.cxx
PWGCF/EBYE/IntermittencyAnalysis/AliAnalysisTaskNFactorialMoments.h
PWGCF/EBYE/macros/AddTaskNFactorialMoments.C

-   dEta, dPhi checks
-    fixed memory issues on lego

Checks related to pT ordering

---

PWGCF/Correlations/DPhi/AliAnalysisTaskHadronPhiCorr.cxx
PWGCF/Correlations/DPhi/AliAnalysisTaskHadronPhiCorr.h

Added flag to remove in-bunch pileup events and pileup tracks for running over EPOS prod.

Added flag for MC pileup removal

---

PWGGA/GammaConv/AliAnalysisTaskConvCaloCalibration.cxx
PWGGA/GammaConv/macros/AddTask_GammaCalo_pp.C
PWGGA/GammaConvBase/AliCaloPhotonCuts.cxx
PWGGA/GammaConvBase/AliCaloPhotonCuts.h

- Add histogram for p of electrons matched to emcal. This allows calculation of cluster finding efficiency in data

PWGGA/GammaConv: Add Histo for calib task to obtain efficiency

---

PWGCF/FLOW/GF/AliAnalysisPtN.cxx
PWGCF/FLOW/GF/AliAnalysisPtN.h

add Pt fluctuation to 4th order

[PAG-Flow] add Pt fluctuation to 4th order

---

PWGGA/PHOSTasks/PHOS_Run2/AliAnalysisTaskPHOSPi0EtaToGammaGamma.cxx
PWGGA/PHOSTasks/PHOS_Run2/macros/AddTaskPHOSPi0EtaToGammaGamma_PbPb_5TeV.C

- Added options for analyses with kCentral/kSemiCentral/kMB triggers in AddTask macro
- The same is done for the corresponding AliAnalysis code

PWGGA/PHOSTasks/PHOS_Run2 added kCentral/kSemiCentral trigger

---

PWGCF/FEMTOSCOPY/macros/Train/KM/pPb502/MC/ER_DPMJET_MR_MTX/ConfigFemtoAnalysis.C

KM->ER_DPMJET_MR_MTX

---

PWGCF/FLOW/GF/AliAnalysisTaskCorrForFlowFMD.cxx

Apply Efficiency with FMDA-FMDC correlation
Apply Nch cut for MC truth data

Apply Nch Cut for MCTruth data

---

PWGGA/GammaConv/macros/AddTask_GammaCalo_pp.C
PWGGA/GammaConv/macros/AddTask_GammaConvCalo_pp.C
PWGGA/GammaConvBase/AliCaloPhotonCuts.cxx

- An unexpected difference between the results with  and without cell sale has been found also for no NCell cut. To understand this difference, new configs are added for further comparisons

PWGGA/GammaConv: Add configs for EMC Non-Lin without cell scale

---

PWGCF/FLOW/GF/AliAnalysisPtN.cxx

fixed the bug of calculating 3 and 4th order weight cumulants

[PAG-Flow]fixed a bug in 3 and 4 order pt fluctuation

---

PWGGA/GammaConv/macros/AddTask_GammaCalo_PbPb.C
PWGGA/GammaConv/macros/AddTask_GammaConvCalo_PbPb.C

- Resorted the 2018 train configs for AddTask_GammaCalo_PbPb.C and AddTask_GammaConvCalo_PbPb.C. starting from 1000.

PWGGA/GammaConv: AddTask Gamma(Conv)Calo_PbPb sorted 2018 train configs

---

PWGLF/RESONANCES/PostProcessing/K1/AddTaskK1.C
PWGLF/RESONANCES/PostProcessing/K1/AliAnalysisTaskK1.cxx
PWGLF/RESONANCES/PostProcessing/K1/AliAnalysisTaskK1.h

The bug was fixed (I missed the `fill`) and I separated the MC tree.

LF: Add fill tree option

---

PWGGA/GammaConv/macros/AddTask_GammaCalo_PbPb.C
PWGGA/GammaConv/macros/AddTask_GammaConvCalo_PbPb.C

- Added trainconfigs for LHC15o PbPb similar to the LHC18qr traincnofigs except no trigger for 0-10 and 30-50% centralities

PWGGA/GammaConv: Gamma(Conv)Calo Add PbPb 2015 configs

---

PWGCF/FEMTOSCOPY/FemtoDream/AliAnalysisTaskFemtoDreamRho.cxx
PWGCF/FEMTOSCOPY/FemtoDream/AliAnalysisTaskFemtoDreamRho.h
PWGCF/FEMTOSCOPY/FemtoDream/AliFemtoDreamv0Cuts.cxx
PWGCF/FEMTOSCOPY/FemtoDream/AliFemtoDreamv0Cuts.h
PWGCF/FEMTOSCOPY/FemtoDream/AliFemtoDreamv0Hist.cxx
PWGCF/FEMTOSCOPY/FemtoDream/AliFemtoDreamv0Hist.h
PWGCF/FEMTOSCOPY/macros/AddTaskFemtoDreamRho.C

- Add QA for 2B Cfs
- Allow pT selection of rhos for optimisation
- Add option for much finer pT binning of M(V0) vs pT
- Update Addtask

- Correct projection Cfs

---

PWGGA/GammaConv/AliAnalysisTaskGammaCalo.cxx
PWGGA/GammaConv/AliAnalysisTaskGammaConvCalo.cxx
PWGGA/GammaConvBase/AliCaloPhotonCuts.cxx

- Add the LHC206j6 to the CaloPhotonCuts for the kPbPb5T15HIJING enum inside `FindEnumForMCSet`

PWGGA/GammaConvBase: Add LHC20j MCs to CaloPhotonCuts

---

PWGGA/GammaConv/AliAnalysisTaskGammaConvV1.cxx

minor bug fix in positive track dEdx variable of meson TTrees for PCM machine learning

PCM4ML: bug fix for TPC dEdx

---

PWGJE/EMCALJetTasks/CMakeLists.txt
PWGJE/EMCALJetTasks/PWGJEEMCALJetTasksLinkDef.h
PWGJE/EMCALJetTasks/UserTasks/AliAnalysisTaskStrangenessInJets.cxx
PWGJE/EMCALJetTasks/UserTasks/AliAnalysisTaskStrangenessInJets.h
PWGJE/EMCALJetTasks/macros/AddTaskStrangenessInJets.C

New task (modification of the AliAnalysisTaskV0sInJetsEmcal.cxx) for the strange particles (V0s) in jets analysis, where V0s are added to the fastjet (instead of their daughter tracks) and in the result V0 particle pt is a part of the final jet pt.

New task for the V0s in jets analysis with V0 as part of the jet

---

PWGCF/FEMTOSCOPY/AliFemtoUser/AliAnalysisTaskEffK0ss.cxx
PWGCF/FEMTOSCOPY/AliFemtoUser/AliAnalysisTaskEffK0ss.h

Added a few setters in the header to make the systematics check easier, using V0M instead of RefMult as centrality estimator, changed some binning

update to k0sKch efficiency task

---

PWGCF/FLOW/GF/AliAnalysisTaskCorrForFlowEta.cxx
PWGCF/FLOW/GF/AliAnalysisTaskCorrForFlowEta.h

Added missing setter in AliAnalysisTaskCorrForFlowEta.h

New Setter in AliAnalysisTaskCorrForFlowEta

---

PWGCF/FLOW/GF/AliAnalysisTaskCorrForFlowEta.cxx
PWGCF/FLOW/GF/AliAnalysisTaskCorrForFlowEta.h
PWGCF/FLOW/GF/AliAnalysisTaskCorrForFlowMaster.h

Added extra "event bias" cut on track pairs in CorrForFlowEta and removed redundant dependency in CorrForFlowEta and CorrForFlowMaster.

Update to AliAnalysisTaskCorrForFlowMaster and AliAnalysisTaskCorrForFlowEta

---

PWGJE/EMCALJetTasks/CMakeLists.txt
PWGJE/EMCALJetTasks/PWGJEEMCALJetTasksLinkDef.h
PWGJE/EMCALJetTasks/UserTasks/AliAnalysisJetHadro.cxx
PWGJE/EMCALJetTasks/UserTasks/AliAnalysisTaskJetHadroAOD.cxx
PWGJE/EMCALJetTasks/UserTasks/AliAnalysisTaskJetHadroAOD.h
PWGJE/EMCALJetTasks/macros/AddTaskJetHadroAOD.C

Removed unneeded parts of ESD code, added AOD code to make future unfolding easier, added more TOF expected and mismatch histograms.

Less ESD code, added AOD code, more TOF histograms

---

PWG/FLOW/Tasks/AliAnalysisTaskChargeV1.cxx
PWGCF/FLOW/macros/AddTaskChargeV1.C

The running data has been changed from 18q to 18r.

Change the running data

---

PWGCF/FLOW/GF/AliAnalysisTaskGFWFlow.cxx

Fix a bug resulting the weight can't be found properly.

Fix the WeightList bug

---

PWGCF/FLOW/GF/AliAnalysisTaskCorrForFlowFMD.cxx
PWGCF/FLOW/GF/AliAnalysisTaskCorrForFlowFMD.h
PWGCF/FLOW/macros/AddCorrForFlowTaskFMD.C

Copy the "getMCEvent()" function from the marco which uses "the PYTHIA8 with rope" data for the on-the-fly system
Added some switches to call the function

On-The-Fly-Code for PYTHIA8 with rope 

---

PWGJE/EMCALJetTasks/UserTasks/AliAnalysisTaskJetHadroAOD.cxx
PWGJE/EMCALJetTasks/UserTasks/AliAnalysisTaskJetHadroAOD.h

Fixed pointer initialization to work with JE trains. The passed variable histogram binning wasn't working either, so changed to hard-coded binning.

Fixes for JE trains

---

PWGCF/FLOW/macros/AddTaskChargeV1.C

Added NUA and NUE for TPC plane

Add NUA and NUE

---

PWGGA/GammaConv/macros/AddTask_GammaConvCalo_PbPb.C

- train config 2565 was there two times, this is now fixed by properly changing one to 2566

PWGGA/GammaConv: AddTaskGammaConvCalo_PbPb.C fix config 2566

---

PWGCF/FEMTOSCOPY/AliFemto/AliFemtoCutMonitorV0.cxx

changing the binning of k0s invariant mass histogram.

change binning of a histogram

---

PWGCF/FLOW/GF/AliAnalysisTaskCorrForFlowFMDOnthefly.cxx
PWGCF/FLOW/GF/AliAnalysisTaskCorrForFlowFMDOnthefly.h
PWGCF/FLOW/GF/CMakeLists.txt
PWGCF/FLOW/GF/PWGCFFLOWGFLinkDef.h
PWGCF/FLOW/macros/AddCorrForFlowTaskFMDOnthefly.C

We create a new class for corr flow measurement with FMD for on-the-fly trains. In order to avoid the conflict between data and on-the-fly setup.

Create a new class for corr flow with FMD for on-the-fly trains 

---

PWGJE/EMCALJetTasks/CMakeLists.txt
PWGJE/EMCALJetTasks/PWGJEEMCALJetTasksLinkDef.h
PWGJE/EMCALJetTasks/UserTasks/AliAnalysisTaskEmcalPIDinJet.cxx
PWGJE/EMCALJetTasks/UserTasks/AliAnalysisTaskEmcalPIDinJet.h
PWGJE/EMCALJetTasks/macros/AddTaskEmcalPIDinJet.C

task for PID in jets by K. Sato
Detail to see his presentation in JSUB PAG meeting March 12th

PID in jets task by K. Sato

---

PWGCF/FLOW/GF/AliAnalysisPtN.cxx
PWGCF/FLOW/GF/AliAnalysisPtN.h
PWGCF/FLOW/macros/AddTaskPtN.C

Changes made to the code, so that it can change different cuts, filterbits and triggers.

add changes for different cuts and triggers

---

PWGJE/EMCALJetTasks/Tracks/AliAnalysisTaskEmcalJetEnergyScale.cxx
PWGJE/EMCALJetTasks/Tracks/AliAnalysisTaskEmcalJetEnergyScale.h

corresponding histograms for efficiency and
purity for 2D unfolding

Add spectrum response matrix vs. NEF and

---

PWGCF/FLOW/macros/AddTaskPtN.C

fix error of ; exception

---

PWGCF/FEMTOSCOPY/AliFemto/AliFemtoCutMonitorV0.cxx
PWGCF/FEMTOSCOPY/AliFemto/AliFemtoCutMonitorV0.h

Histogram for filling the invariant mass of K0s Vs pT is added.

add invmassVspT for K0s

---

PWGGA/GammaConv/AliAnalysisTaskMesonJetCorrelation.cxx
PWGGA/GammaConv/AliAnalysisTaskMesonJetCorrelation.h

- Histograms to connect multiplicity and jet production
- Cleaned code with clang-format

PWGGA/GammaConv: Add jet vs. multiplicity histograms

---

PWGJE/EMCALJetTasks/UserTasks/AliAnalysisJetHadro.cxx
PWGJE/EMCALJetTasks/UserTasks/AliAnalysisJetHadro.h
PWGJE/EMCALJetTasks/UserTasks/AliAnalysisTaskJetHadroAOD.cxx

Deleting a pointer after its use in a loop and updating the ESD task with previous AOD changes

Memory fixes for JetHadro AOD and ESD tasks

---

PWG/EMCAL/EMCALtrigger/AliEmcalTriggerLuminosity.cxx

PWG/EMCAL/EMCALtrigger/AliEmcalTriggerLuminosity.cxx -- Fixing broken directory check

PWG/EMCAL/EMCALtrigger/AliEmcalTriggerLuminosity.cxx -- Fixing broken directory check

---

PWGCF/FEMTOSCOPY/FemtoDream/AliAnalysisTaskFemtoDreamRho.cxx
PWGCF/FEMTOSCOPY/FemtoDream/AliAnalysisTaskFemtoDreamRho.h
PWGCF/FEMTOSCOPY/FemtoDream/AliFemtoDreamCollConfig.cxx
PWGCF/FEMTOSCOPY/FemtoDream/AliFemtoDreamCollConfig.h
PWGCF/FEMTOSCOPY/FemtoDream/AliFemtoDreamCorrHists.cxx
PWGCF/FEMTOSCOPY/FemtoDream/AliFemtoDreamCorrHists.h
PWGCF/FEMTOSCOPY/FemtoDream/AliFemtoDreamHigherPairMath.cxx
PWGCF/FEMTOSCOPY/FemtoDream/AliFemtoDreamHigherPairMath.h
PWGCF/FEMTOSCOPY/macros/AddTaskFemtoDreamRho.C

... and modify the MC for closure test.
... adopt clang formatting for central classes.
... update AddTask.

Include the Minv vs k* functionality for V0.

---

PWGCF/FEMTOSCOPY/AliFemtoUser/AliFemtoCutMonitorPairMomRes.cxx
PWGCF/FEMTOSCOPY/AliFemtoUser/AliFemtoCutMonitorPairMomRes.h

editing my old histogram and adding similar monitor histograms

new monitor histograms

---

PWG/FLOW/Tasks/AliAnalysisTaskChargeV1.cxx
PWG/FLOW/Tasks/AliAnalysisTaskChargeV1.h
PWGCF/FLOW/macros/AddTaskChargeV1.C

remove extra part and add trigger

remove extra part and add trigger

---

PWGLF/NUCLEX/Exotica/Dibaryons/AddTaskpOmegaDibaryon.C
PWGLF/NUCLEX/Exotica/Dibaryons/AliAnalysisTaskpOmegaDibaryon.cxx
PWGLF/NUCLEX/Exotica/Dibaryons/AliAnalysisTaskpOmegaDibaryon.h

This is test for merging the codes about p-omega dibaryon.

p-omega dibaryon in pb-pb

---

PWGCF/FEMTOSCOPY/FemtoDream/AliAnalysisTaskLambdaPion.h
PWGCF/FEMTOSCOPY/macros/AddTaskFemtoLambdaPion.C

Revert "Clean the code and use the correct systematic variations"
This reverts commit e8e4fc4ccaa29dee3ed032af1848de2082fe1f53.
Remove unused parameters
Update systematics and fix pt selection of pions

[Fix] Solve error due to QA pair settings and fix pt selection of pions

---

PWGGA/GammaConv/AliAnalysisTaskGammaCalo.cxx
PWGGA/GammaConv/AliAnalysisTaskGammaConvCalo.cxx

- Remove the `NMatchedTracks` and `NMatchedPrimTracks` variables which are no longer used

PWGGA/GammaConv: AliAnalysisTaskGammaCalo.cxx - Remove NMatchedTracks

---

PWGJE/EMCALJetTasks/Tracks/AliAnalysisTaskEmcalJetEnergySpectrum.cxx

PWGJE/EMCALJetTasks/Tracks/AliAnalysisTaskEmcalJetEnergySpectrum.cxx Fixing position of cluster histo filling

PWGJE/EMCALJetTasks/Tracks/AliAnalysisTaskEmcalJetEnergySpectrum.cxx Fixing position of cluster histo filling

---

PWGGA/GammaConv/macros/AddTask_GammaIsoTree.C

- Add possible additionalFileEnding to the container names to enable running of multiple Jet settings in the same Train

PWGGA/GammaConv: Change IsoGammaTree container name

---

PWGCF/FLOW/GF/AliAnalysisPtN.cxx
PWGCF/FLOW/GF/AliAnalysisPtN.h

changed the code so it can use different efficiency correction for different systematic check

add systflag for efficiency correction

---

PWGJE/EMCALJetTasks/CMakeLists.txt
PWGJE/EMCALJetTasks/PWGJEEMCALJetTasksLinkDef.h
PWGJE/EMCALJetTasks/UserTasks/AliAnalysisTaskJetAngCorrelations.cxx
PWGJE/EMCALJetTasks/UserTasks/AliAnalysisTaskJetAngCorrelations.h
PWGJE/EMCALJetTasks/macros/AddTaskJetAngCorrelations.C

to PWGJE/EMCALJetTasks/UserTasks/

Add jet angular correlations task

---

PWGCF/FLOW/GF/AliAnalysisPtN.cxx
PWGCF/FLOW/GF/AliAnalysisPtN.h

Added some QA plots to the track cuts

add QA plots to track cuts

---

PWGHF/hfe/AliAnalysisTaskBEpp13TeV.cxx

Change pT binning

---

PWGCF/Correlations/macros/jcorran/AddTaskJFFlucJCAnalysis.C

Add task macro added for LHC18qr.

(PWGCF): JFFlucAnalysis adpated for 18qr data

---

PWGCF/FLOW/GF/AliAnalysisTaskGFWFlow.cxx
PWGCF/FLOW/GF/AliAnalysisTaskGFWFlow.h
PWGCF/FLOW/macros/AddTaskGFWFlow.C

Fix the bugs which prevented weights from being generated for per run, and which prevented the codes from be run on the train.

Fixing the bugs on producing weights and running on the train

---

PWGGA/GammaConv/AliAnalysisTaskGammaCalo.cxx
PWGGA/GammaConv/AliAnalysisTaskGammaConvCalo.cxx
PWGGA/GammaConvBase/AliCaloPhotonCuts.cxx

- Some small code cleanup, just indentation of comments adjusted.

PWGGA/GammaConv: Code cleanup v1

---

PWGJE/EMCALJetTasks/AliAnalysisTaskScale.cxx
PWGJE/EMCALJetTasks/AliAnalysisTaskScale.h
PWGJE/EMCALJetTasks/Tracks/AliAnalysisTaskEmcalJetEnergySpectrum.cxx
PWGJE/EMCALJetTasks/Tracks/AliAnalysisTaskEmcalJetEnergySpectrum.h

PWGJE/EMCALJetTasks/AliAnalysisTaskScale Adding 3xEMC and manual set of EMCal max phi

PWGJE/EMCALJetTasks/AliAnalysisTaskScale Adding 3xEMC and manual set of EMCal max phi

---

PWGJE/EMCALJetTasks/AliAnalysisTaskScale.cxx
PWGJE/EMCALJetTasks/AliAnalysisTaskScale.h

PWGJE/EMCALJetTasks/AliAnalysisTaskScale Adding crosscheck histos, skipping clusterless events, limit tracks to emcal eta

PWGJE/EMCALJetTasks/AliAnalysisTaskScale Adding crosscheck histos, skipping clusterless events, limit tracks to emcal eta

---

PWGCF/Correlations/JCORRAN/Base/AliJFFlucAnalysis.cxx
PWGCF/Correlations/JCORRAN/Base/AliJFFlucJCTask.cxx
PWGCF/Correlations/macros/jcorran/AddTaskJFFlucJCAnalysis.C

AliJFFlucAnalysis wasn't synced with JCatalystTask -> JCatalyst event cuts weren't propagated to AliJFFlucAnalysis properly.

(PWGCF:) sync to JCatalyst added

---

PWGGA/GammaConv/macros/AddTask_ConvCaloCalibration_CaloMode_pp.C
PWGGA/GammaConvBase/AliCaloPhotonCuts.cxx
PWGGA/GammaConvBase/AliCaloPhotonCuts.h

- New histo with electron track that is verified to hit a good cell for cluster finding efficiency studies

PWGGA/GammaConv: Add configs for cluster efficiency and new histo

---

PWGGA/GammaConv/AliAnalysisTaskConvCaloCalibration.cxx
PWGGA/GammaConv/macros/AddTask_ConvCaloCalibration_CaloMode_pp.C
PWGGA/GammaConv/macros/AddTask_GammaCalo_pp.C
PWGGA/GammaConv/macros/AddTask_GammaConvCalo_pp.C
PWGGA/GammaConvBase/AliCaloPhotonCuts.cxx
PWGGA/GammaConvBase/AliCaloPhotonCuts.h
PWGGA/GammaConvBase/AliDalitzElectronCuts.cxx

- Changes like done in AliPrimaryPionCuts

PWGGA/GammaConv: Change condition for TOF in PrimaryElectron selector

---

PWGJE/EMCALJetTasks/CMakeLists.txt
PWGJE/EMCALJetTasks/PWGJEEMCALJetTasksLinkDef.h
PWGJE/EMCALJetTasks/UserTasks/AliAnalysisTaskCascadesInJets.cxx
PWGJE/EMCALJetTasks/UserTasks/AliAnalysisTaskCascadesInJets.h
PWGJE/EMCALJetTasks/macros/AddTaskCascadesInJets.C

The new task for cascades, in principle, is the same as the StrangenessInJets task but analyzes cascades.

New task for Xi and Omega analysis in jets

---

PWGCF/FEMTOSCOPY/macros/Train/KM/pPb502/MC/005/ConfigFemtoAnalysis.C

Kaon MC purity in pPb5.02T

---

PWGCF/FEMTOSCOPY/macros/Train/KM/PbPb502/MC/001/ConfigFemtoAnalysis.C

Purity MC K PbPb 5.02T v.001

---

PWG/FLOW/Tasks/AliAnalysisTaskChargeV1.cxx
PWG/FLOW/Tasks/AliAnalysisTaskChargeV1.h
PWGCF/FLOW/macros/AddTaskChargeV1.C

add v0 plane

---

PWGCF/FEMTOSCOPY/macros/Train/KM/PbPb502/MC/002/ConfigFemtoAnalysis.C

Purity K MC PbPb502 pT:0.14-2.0

---

PWGGA/GammaConv/macros/AddTask_GammaCalo_PbPb.C
PWGGA/GammaConv/macros/AddTask_GammaConvCalo_PbPb.C

- Add new trainconfigs for cent and semi cent (triggered for 18qr and not triggered for 15o)

PWGGA/GammaConv: Add QA trainconfigs for PbPb cent and semicent

---

PWGGA/GammaConv/macros/AddTask_GammaCalo_PbPb.C
PWGGA/GammaConv/macros/AddTask_GammaConvCalo_PbPb.C

- Add trainconfigs using predefined MC track mult for cents.
- Add trainconfig for MC from 0-15% to see the influence of the 5% and if this could help with staistics

PWGGA/GammaConv: Add more PbPb QA train configs

---

PWGGA/GammaConv/macros/AddTask_ConvCaloCalibration_CaloMode_pp.C
PWGGA/GammaConv/macros/AddTask_GammaCalo_pp.C
PWGGA/GammaConvBase/AliCaloPhotonCuts.cxx
PWGGA/GammaConvBase/AliCaloPhotonCuts.h

- New histograms allowing detailed MC information on the track purity
- Add new functions and option to only apply the cluster efficiency to EM (electrons and photons) clusters
- Add new configs to check application of cluster efficiency

PWGGA/GammaConv: Add histograms and configs for cluster eff. study

---

PWGJE/EMCALJetTasks/AliAnalysisTaskScale.cxx
PWGJE/EMCALJetTasks/AliAnalysisTaskScale.h

PWGJE/EMCALJetTasks/AliAnalysisTaskScale Correct for periodicity

PWGJE/EMCALJetTasks/AliAnalysisTaskScale Correct for periodicity

---

PWGGA/GammaConv/AliAnalysisTaskConvCaloTree.cxx
PWGGA/GammaConv/AliAnalysisTaskConvCaloTree.h
PWGGA/GammaConv/macros/AddTask_ConvCaloTree.C

- Save more MC information to perform full analysis
- Add event histogram
- Add variables for detector level jets and true jets

PWGGA/GammaConv: Add variables to tree task

---

PWGJE/EMCALJetTasks/UserTasks/AliAnalysisTaskJetHadroAOD.cxx
PWGJE/EMCALJetTasks/UserTasks/AliAnalysisTaskJetHadroAOD.h
PWGJE/EMCALJetTasks/macros/AddTaskJetHadroAOD.C

added the MC corrections of
- tracking efficiency truth den for pi,K,p
- tracking efficiency reco num for pi,K,p
- matching efficiency reco num for pi,K,p
- data primary fraction DCAxy distributions for pi, p
- MC primary fraction DCAxy distributions for pi, p for primary, secondary from weak decays, secondary from material
for both inclusive and jets 
added the UE perpendicular and random cone options to fill in lieu of inclusive for later subtraction and comparison

added the MC corrections and UE particle-level subtraction

---

PWGGA/GammaConv/AliAnalysisTaskConvCaloCalibration.cxx
PWGGA/GammaConv/AliAnalysisTaskConvCaloCalibration.h
PWGGA/GammaConvBase/AliCaloPhotonCuts.cxx

- take absolute value of the MC track label as the negative track label is just a copy?
- Add histogram for V0 momentum

PWGGA/GammaConv: CalibTask: Adjust assosiation of true tracks to rec tracks

---

PWGJE/EMCALJetTasks/AliAnalysisTaskScale.cxx
PWGJE/EMCALJetTasks/AliAnalysisTaskScale.h
PWGJE/EMCALJetTasks/macros/AddTaskScale.C

PWGJE/EMCALJetTasks/AliAnalysisTaskScale Change AddTask for AOD use

PWGJE/EMCALJetTasks/AliAnalysisTaskScale Change AddTask for AOD use

---

PWGJE/EMCALJetTasks/UserTasks/AliAnalysisTaskIDFragmentationFunction.cxx
PWGJE/EMCALJetTasks/UserTasks/AliAnalysisTaskIDFragmentationFunction.h

check perpendicular cone for collision with reconstructed jet

PWGJE: Improve getting underlying event, 

---

PWGGA/PHOSTasks/PHOS_Run2/AliAnalysisTaskPHOSEmbedding.cxx
PWGGA/PHOSTasks/PHOS_Run2/AliAnalysisTaskPHOSEmbeddingEfficiency.cxx
PWGGA/PHOSTasks/PHOS_Run2/AliAnalysisTaskPHOSPi0EtaToGammaGamma.cxx
PWGGA/PHOSTasks/PHOS_Run2/macros/AddTaskPHOSEmbeddedDiffObjectCreator.C

- added histos for Mgg distributions in real and mixed events (both for the general analysis task and embedding)
- added PHOS M4Exclude option for embedding

Added Mgg histos + minor changes

---

PWGJE/EMCALJetTasks/UserTasks/AliAnalysisTaskJetHadroAOD.cxx
PWGJE/EMCALJetTasks/UserTasks/AliAnalysisTaskJetHadroAOD.h

Added capabilities for hybrid, reco, and truth jets
Adding jet matching
Saved all information needed as histograms to calculate UE bias scaling factor
Saved all JES and JER info
Saved distributions of pi,k,p as fxn of jet pT

Added code to use embedding framework

---

PWG/JETFW/AliEmcalJet.h
PWG/JETFW/AliJetContainer.h
PWGJE/EMCALJetTasks/AliEmcalJetTask.cxx

Study of the impact of edge effects in the EMCAL

Add option to select jets with reduced EMCAL fiducial accpetance

---

PWGCF/EBYE/CMakeLists.txt
PWGCF/EBYE/MeanPtFluctuations/pp13TeV_MB/AliAnalysisMCMeanPt.cxx
PWGCF/EBYE/MeanPtFluctuations/pp13TeV_MB/AliAnalysisMCMeanPt.h
PWGCF/EBYE/MeanPtFluctuations/pp13TeV_MB/AliAnalysisMeanPtFluc.cxx
PWGCF/EBYE/MeanPtFluctuations/pp13TeV_MB/AliAnalysisMeanPtFluc.h
PWGCF/EBYE/PWGCFebyeLinkDef.h
PWGCF/EBYE/macros/AddMCMeanPt.C
PWGCF/EBYE/macros/AddMeanPtFluc.C

Task for same multiplicity classes in different p_T ranges

Modified for Mulitplicity selections

---

PWGCF/FEMTOSCOPY/macros/Train/KM/PbPb502/Data/PurDatPb502_001/ConfigFemtoAnalysis.C

PurDatPb502_001 -> PURITY Pb-Pb 5.02

---

PWGCF/Correlations/DPhi/AliAnalysisTaskK0HadronRatio.cxx
PWGCF/Correlations/DPhi/AliAnalysisTaskK0HadronRatio.h
PWGCF/Correlations/DPhi/CMakeLists.txt
PWGCF/Correlations/DPhi/PWGCFCorrelationsDPhiLinkDef.h
PWGCF/Correlations/macros/AddK0HadronRatioTask.C

This PR contains my (somewhat) new analysis task for investigating the K0/h ratio in jets and UE using azimuthal correlations.

Added K0/h analysis task (Run 2)

---

PWGCF/FEMTOSCOPY/macros/Train/KM/PbPb502/Data/PurDatPb502_002/ConfigFemtoAnalysis.C

PurDatPb502_002->Gleb ConfigFemtoAnalysis.C w/o mostprob.

---

PWGGA/GammaConv/macros/AddTask_GammaCalo_PbPb.C
PWGGA/GammaConv/macros/AddTask_GammaConvCalo_PbPb.C

- Add Trainconfigs for standard neutral meson analysis for 15o and 18qr

PWGGA/GammaConv: Add Trainconfigs for ConvCalo

---

PWGGA/GammaConv/AliAnalysisTaskPi0v2Calo.cxx
PWGGA/GammaConv/AliAnalysisTaskPi0v2Calo.h
PWGGA/GammaConv/CMakeLists.txt
PWGGA/GammaConv/PWGGAGammaConvLinkDef.h
PWGGA/GammaConv/macros/AddTask_Pi0v2Calo_PbPb.C

- Cloned and trimmed the AliAnalysisTaskGammaCalo and combined it with AliPhysics/PWG/FLOW/Tasks/AliAnalysisTaskPi0EtaV2.cxx which was presented in the PAG meeting 20.12.2023 https://indico.cern.ch/event/1360237/ by Jie Wan to create a task to calculate the Pi0 v2 in LHC15o and LHC18qr

PWGGA/GammaConv: Created new Pi0/Eta v2 task for EMCal

---

PWGGA/PHOSTasks/PHOS_Run2/AliAnalysisTaskPHOSEmbeddedDiffObjectCreator.cxx
PWGGA/PHOSTasks/PHOS_Run2/AliAnalysisTaskPHOSEmbedding.cxx
PWGGA/PHOSTasks/PHOS_Run2/AliAnalysisTaskPHOSEmbeddingEfficiency.cxx
PWGGA/PHOSTasks/PHOS_Run2/AliAnalysisTaskPHOSPi0EtaToGammaGamma.cxx
PWGGA/PHOSTasks/PHOS_Run2/AliAnalysisTaskPHOSPi0EtaToGammaGamma.h
PWGGA/PHOSTasks/PHOS_Run2/AliAnalysisTaskPHOSSingleSim.cxx

- Changed binning of mixed events container: added bins on the centrality and reaction plane
- Added Mgg histos for embedding and MC

PWGGA/PHOSTasks: Changed mixed events selection + added Mgg histos

---

PWGCF/FEMTOSCOPY/macros/Train/KM/PbPb502/Data/PurDatPb502_003/ConfigFemtoAnalysis.C

PurDatPb502_003

---

PWGHF/correlationHF/AliAnalysisTaskHadronElectronAnalysis.cxx
PWGHF/correlationHF/AliAnalysisTaskHadronElectronAnalysis.h
PWGHF/correlationHF/CMakeLists.txt
PWGHF/correlationHF/PWGHFcorrelationHFLinkDef.h
PWGHF/correlationHF/macros/AddHadronElectronAnalysisTask.C

I added my analysis task(doing hadron-heavy flavor electron angular correlations) to the github repository.

Adding Analysis Task to the github repository

---

PWGJE/EMCALJetTasks/UserTasks/AliAnalysisTaskCascadesInJets.cxx
PWGJE/EMCALJetTasks/UserTasks/AliAnalysisTaskStrangenessInJets.cxx

exclusion of leading V0s from the cut

leading pt cut change

---

PWGJE/EMCALJetTasks/UserTasks/AliAnalysisTaskCascadesInJets.cxx
PWGJE/EMCALJetTasks/UserTasks/AliAnalysisTaskStrangenessInJets.cxx

Daughter pT instead of V0s in the leading cut

changes in leading track pT cut

---

PWGGA/GammaConvBase/AliConversionPhotonCuts.cxx

PWGGA/GammaConv add TOF cut option to AliConversionPhotonCuts.cxx

---

PWGGA/GammaConv/macros/AddTask_GammaConvV1_PbPb.C

add trainconfigs for systematics

PWGGA/GammaConv:  AddTask_GammaConvV1_PbPb.C systematics

---

PWGLF/NUCLEX/Exotica/Dibaryons/AddTaskpOmegaDibaryon.C

For analysis with semi-central events

Change to analysis for semi-central events

---

PWGGA/GammaConv/macros/AddTask_GammaConvV1_PbPb.C

add mc trainconfigs for systematics

PWGGA/GammaConv: Update AddTask_GammaConvV1_PbPb.C

---

RUN3/AliAnalysisTaskAO2Dconverter.cxx
RUN3/AliAnalysisTaskAO2Dconverter.h

@mpuccio @jgrosseo @ddobrigk @pzhristov here is the addition of the TPC pid clusters info in the track extra table, similarly to what is planned for run 3

RUN 3: add number of findable minus PID TPC clusters in converter

---

PWGJE/EMCALJetTasks/Tracks/AliAnalysisTaskEmcalJetEnergySpectrum.cxx

PWGJE/EMCALJetTasks/Tracks/AliAnalysisTaskEmcalJetEnergySpectrum Adding full jet compatibility for delta-pT distribution

PWGJE/EMCALJetTasks/Tracks/AliAnalysisTaskEmcalJetEnergySpectrum Adding full jet compatibility for delta-pT distribution

---

PWGGA/GammaConv/macros/AddTask_GammaConvV1_PbPb.C

PWGGA/GammaConv: AddTask_GammaConvV1_PbPb.C

---

RUN3/AliAnalysisTaskAO2Dconverter.cxx
RUN3/AliAnalysisTaskAO2Dconverter.h

Run 3 converter: option to disable EMCAL cells / clean logs

---

RUN3/AliAnalysisTaskAO2Dconverter.cxx

- The actual relablleing of the AODConversionGammas got lost in one of the PRs to fix the cyclic dependency. This should restore that functionality again.
- Fixed setting of collision system type for ConverionCuts from always being PbPb to variable `fCollSystem` which can be set using `SetCollSystem` in the AddTask.

[RUN3] Fix missing relabling function

---

PWGJE/EMCALJetTasks/CMakeLists.txt
PWGJE/EMCALJetTasks/PWGJEEMCALJetTasksLinkDef.h
PWGJE/EMCALJetTasks/UserTasks/AliAnalysisTaskJetsEECpbpb.cxx
PWGJE/EMCALJetTasks/UserTasks/AliAnalysisTaskJetsEECpbpb.h
PWGJE/EMCALJetTasks/macros/AddTaskJetsEECpbpb.C

Code for raw data. Commented out code is in development for embedding usage.

Code for ENC in pbpb data

---

PWGJE/EMCALJetTasks/UserTasks/AliAnalysisTaskSVtaskMCFilter.cxx
PWGJE/EMCALJetTasks/UserTasks/AliAnalysisTaskSVtaskMCFilter.h
PWGJE/EMCALJetTasks/macros/AddTaskSVtaskMCFilter.C

EPOS is still the default filtered gen in the task, added the option to instead filter HIJING if one sets the last setting to true.

Edited SVtaskMCFilter to be able to filter HIJING part of MC tracks

---

PWGCF/FEMTOSCOPY/macros/Train/KM/pPb502/012/ConfigFemtoAnalysis.C

KM 012->KK 13_DEC_2024 SPHER 0.7-1

---

RUN3/AliAnalysisTaskAO2Dconverter.cxx
RUN3/AliAnalysisTaskAO2Dconverter.h

This PR adds a few options (default: disabled) for the Run 3 converter for hyperloop tests.

Run 3 converter: test experimental options (default: disabled)

---

RUN3/AliAnalysisTaskAO2Dconverter.cxx
RUN3/AliAnalysisTaskAO2Dconverter.h

Run 3 conv: add ev sel extras

---

PWGGA/GammaConv/AliAnalysisTaskMesonJetCorrelation.cxx
PWGGA/GammaConv/AliAnalysisTaskMesonJetCorrelation.h
PWGGA/GammaConv/AliCutHandlerPCM.cxx
PWGGA/GammaConv/AliCutHandlerPCM.h
PWGGA/GammaConv/macros/AddTask_MesonJetCorr_Calo.C

- Add option for different weightings:
- 1) Add weight from every particle
- 2) Only add weights from particles with a weight factor different from 1

PWGGA/GammaConv: Modify weighting for jet particle abundance

---

PWGJE/EMCALJetTasks/UserTasks/AliAnalysisTaskJetHadroAOD.cxx
PWGJE/EMCALJetTasks/UserTasks/AliAnalysisTaskJetHadroAOD.h
PWGJE/EMCALJetTasks/macros/AddTaskJetHadroAOD.C

To be able to run trains with tags of Oct 6th and later for comparison to O2 Task

[PWGJE] JetHadro pp changes and make trees optional

---

PWGCF/FEMTOSCOPY/macros/Train/KM/pPb502/004j/ConfigFemtoAnalysis.C
PWGCF/FEMTOSCOPY/macros/Train/KM/pPb502/004s/ConfigFemtoAnalysis.C
PWGCF/FEMTOSCOPY/macros/Train/KM/pPb502/012/ConfigFemtoAnalysis.C

[012, 004s, 004j wagons 20 dec 2024 -> fix bug]

---

PWGCF/FEMTOSCOPY/macros/Train/KM/pPb502/004j/ConfigFemtoAnalysis.C
PWGCF/FEMTOSCOPY/macros/Train/KM/pPb502/004s/ConfigFemtoAnalysis.C
PWGCF/FEMTOSCOPY/macros/Train/KM/pPb502/012/ConfigFemtoAnalysis.C

[K+K- 004s 004j and pipi 012] 22 Dec 2024

---

PWGGA/GammaConv/AliAnalysisTaskMesonJetCorrelation.cxx
PWGGA/GammaConv/AliAnalysisTaskMesonJetCorrelation.h

- Furthermore added IsPhysicalPrimary condiftion for tracking efficiency study

PWGGA/GammaConv: Add resoltion histo for tracks inside of jets

---

PWGCF/FEMTOSCOPY/macros/Train/KM/pPb502/004j/ConfigFemtoAnalysis.C
PWGCF/FEMTOSCOPY/macros/Train/KM/pPb502/004s/ConfigFemtoAnalysis.C
PWGCF/FEMTOSCOPY/macros/Train/KM/pPb502/012/ConfigFemtoAnalysis.C

[012 004s 004j 24-dec-2024]

---

PWGCF/FLOW/CME/AliAnalysisTaskPIDCME.cxx
PWGCF/FLOW/CME/AliAnalysisTaskPIDCME.h
PWGCF/FLOW/CME/CMakeLists.txt
PWGCF/FLOW/CME/PWGCFflowCMELinkDef.h
PWGCF/FLOW/macros/AddTaskPIDCME.C

Add PIDCME Run2 code as a base for run3 O2Physics

commit PIDCME code

---

PWGCF/FLOW/CME/AliAnalysisTaskPIDCME.cxx
PWGCF/FLOW/CME/AliAnalysisTaskPIDCME.h
PWGCF/FLOW/macros/AddTaskPIDCME.C

update for PIDCME code 

---

PWGGA/GammaConv/AliAnalysisTaskConvCaloCalibration.cxx
PWGGA/GammaConv/AliAnalysisTaskConvCaloCalibration.h
PWGGA/GammaConv/macros/AddTask_ConvCaloCalibration_CaloMode_pp.C
PWGGA/GammaConv/macros/AddTask_GammaCalo_pp.C
PWGGA/GammaConv/macros/AddTask_GammaConvCaloCalibration_MixedMode_pp.C
PWGGA/GammaConvBase/AliCaloPhotonCuts.cxx

- Add some new cut modes to the ncell cut to study as function of clusterizer thresholds

PWGGA/GammaConv: Add new histograms for NCell study

---

PWGHF/vertexingHF/AliAnalysisTaskSEXicZero2XiPifromKFP.cxx
PWGHF/vertexingHF/AliAnalysisTaskSEXicZero2XiPifromKFP.h

Check the fraction with and without matching to the decay of Xi->Lambda+pi and Lambda->p+pi

Check the fraction with and without matching to the decay of Xi->Lambda+pi and Lambda->p+pi

---

PWGCF/FEMTOSCOPY/macros/Train/KM/pPb502/012j/ConfigFemtoAnalysis.C
PWGCF/FEMTOSCOPY/macros/Train/KM/pPb502/012s/ConfigFemtoAnalysis.C

[K+K-] S_T pPb Jan24 2025

---

PWGGA/GammaConv/AliAnalysisTaskGammaConvCalo.cxx

- Fix for https://github.com/alisw/AliPhysics/pull/23855

PWGGA/GammaConv: Add response matrices to output list

---

PWGCF/FEMTOSCOPY/macros/Train/KM/pPb502/013/ConfigFemtoAnalysis.C
PWGCF/FEMTOSCOPY/macros/Train/KM/pPb502/013j/ConfigFemtoAnalysis.C
PWGCF/FEMTOSCOPY/macros/Train/KM/pPb502/013s/ConfigFemtoAnalysis.C

git commit # [K+K-] S_T pPb [FB 8]

---

PWGJE/EMCALJetTasks/UserTasks/AliAnalysisTaskJetHadroAOD.cxx
PWGJE/EMCALJetTasks/UserTasks/AliAnalysisTaskJetHadroAOD.h
PWGJE/EMCALJetTasks/macros/AddTaskJetHadroAOD.C

Made rho=0 for 2017 data and added event histos for MC rec and truth jets

[PWGJE] changes for pp MC jet hadrochem

---

PWGGA/GammaConv/AliAnalysisTaskGammaJetsPureMC.cxx
PWGGA/GammaConv/AliAnalysisTaskGammaJetsPureMC.h
PWGGA/GammaConv/CMakeLists.txt
PWGGA/GammaConv/PWGGAGammaConvLinkDef.h
PWGGA/GammaConv/macros/AddTask_GammaJetsPureMC.C

- Task produces jet spectra and particles inside of jets
- Toy MC implemented to get a response matrix. Aim is to study the influence of different particle compositions in diffeent generators

PWGGA/GammaConv: Add pure MC task for jet studies on generator level

---

PWGGA/GammaConv/macros/AddTask_GammaCalo_PbPb.C

- 7000 for 0-30 and 70-90 with TM for secondaries
- 7001 for 30-70% with TM for secondaries
- 7100 for 0-30 and 70-90 without TM
- 7101 for 30-70% without TM

[PWGGA] AddTask_GammaCalo_PbPb - Add MC train config for 10% steps

---

PWGJE/EMCALJetTasks/UserTasks/AliAnalysisTaskEmcalHfeTagging.cxx
PWGJE/EMCALJetTasks/UserTasks/AliAnalysisTaskEmcalHfeTagging.h

Multiple update and fixes to the analysis: removed old observables, revert DCal changes, more options for MC tests, etc.

PWGJE: Updates to HFE tagging jet analysis

---

PWGJE/EMCALJetTasks/UserTasks/AliAnalysisTaskCascadesInJets.cxx
PWGJE/EMCALJetTasks/UserTasks/AliAnalysisTaskCascadesInJets.h
PWGJE/EMCALJetTasks/UserTasks/AliAnalysisTaskStrangenessInJets.cxx
PWGJE/EMCALJetTasks/UserTasks/AliAnalysisTaskStrangenessInJets.h

Addition of jet matching to the MC analysis

Changes in the MC analysis

---

PWGJE/EMCALJetTasks/UserTasks/AliAnalysisTaskCascadesInJets.cxx
PWGJE/EMCALJetTasks/UserTasks/AliAnalysisTaskCascadesInJets.h
PWGJE/EMCALJetTasks/UserTasks/AliAnalysisTaskStrangenessInJets.cxx
PWGJE/EMCALJetTasks/UserTasks/AliAnalysisTaskStrangenessInJets.h

Check if V0 daughter is in the hybrid track cont

Added check for V0 daughters is hybrid track

---

PWGCF/FEMTOSCOPY/AliFemtoUser/AliFemtoKpm45TrackCut.cxx
PWGCF/FEMTOSCOPY/AliFemtoUser/AliFemtoKpm45TrackCut.h

AliFemtoKpm45TrackCut add mutable fMomemtumTOF45

---

PWGCF/FEMTOSCOPY/AliFemtoUser/AliFemtoKpm45TrackCut.cxx
PWGCF/FEMTOSCOPY/AliFemtoUser/AliFemtoKpm45TrackCut.h

March4: added mutable fMomentumTOF45

---

PWGHF/correlationHF/AliAnalysisTaskHadronElectronAnalysis.cxx
PWGHF/correlationHF/AliAnalysisTaskHadronElectronAnalysis.h
PWGHF/correlationHF/macros/AddHadronElectronAnalysisTask.C

This is for my analysis investigating charm production in the quark gluon plasma via angular correlations of hadrons-heavy flavor electrons. I added TOF cut option in the addtask and four distributions to mix and match the various cut options of SPDKBoth and SPKAny and with or without a TOF Cut.

PR for updating code

---

PWGCF/FEMTOSCOPY/macros/Train/KM/pPb502/014/ConfigFemtoAnalysis.C

Add low limit of TOF using fMomentumTOF45 0.405

---

PWGCF/FEMTOSCOPY/AliFemtoUser/AliFemtoKpm45TrackCut.cxx
PWGCF/FEMTOSCOPY/AliFemtoUser/AliFemtoKpm45TrackCut.h
PWGCF/FEMTOSCOPY/macros/Train/KM/pPb502/014/ConfigFemtoAnalysis.C

fPminTOF45

---

PWGJE/EMCALJetTasks/UserTasks/AliAnalysisTaskV0sInJetsEmcal.cxx
PWGJE/EMCALJetTasks/UserTasks/AliAnalysisTaskV0sInJetsEmcal.h
PWGJE/EMCALJetTasks/macros/AddTaskV0sInJetsEmcal.C

Histograms and small changes in the analysis with geometrical V0-jet association

Added histograms

---

RUN3/AliAnalysisTaskAO2Dconverter.cxx

- Save event bits stored in MultSelection during AOD -> AO2D conversions
tagging also @ddobrigk

[RUN3] AOD conversion: save MultSelection event bits

---

PWGGA/GammaConv/AliAnalysisTaskGammaConvV1.cxx

added axis captions to MC_Pi0_<InAccel>_Pt and related Eta histograms

PWGGA/GammaConv Add axis titles to  MC prim Eta Pi0  histograms.

---

PWGCF/FLOW/macros/AddTaskPIDCME.C

update Systematic options in AddTask.C

update Systematic options in AddTask.C

---

PWGGA/GammaConv/AliAnalysisTaskGammaConvV1.cxx
PWGGA/GammaConv/macros/AddTask_GammaConvV1_PbPb.C
PWGGA/GammaConvBase/AliConvEventCuts.cxx
PWGGA/GammaConvBase/AliConvEventCuts.h
PWGGA/GammaConvBase/AliConversionMesonCuts.cxx
PWGGA/PWGGAUtils/CMakeLists.txt
PWGGA/PWGGAUtils/utils_TH1.cxx
PWGGA/PWGGAUtils/utils_TH1.h

in addition: 
- add some comments to related functions in AliAnalysisTask_GammaConvV1.cxx
- remove some wrong comments in AliConversionMesonCuts.cxx

PWGGA/GammaConv: Add option to use piecewise exponential interpolation when evaluating MC gen histos for pt-weights

---

PWGCF/FEMTOSCOPY/macros/Train/KM/pPb502/015/ConfigFemtoAnalysis.C
PWGCF/FEMTOSCOPY/macros/Train/KM/pPb502/015j/ConfigFemtoAnalysis.C
PWGCF/FEMTOSCOPY/macros/Train/KM/pPb502/015s/ConfigFemtoAnalysis.C

pPb 5.02 KchKch all,spherical,jetty

---

PWGLF/RESONANCES/macros/mini/AddTaskRare_pp13.C

Update the systematic variable for v0dauther dca cut from `0.7` to `0.07`

AddTaskRare_pp13 - Update systematic variable

---

PWGCF/FEMTOSCOPY/macros/Train/KM/pPb502/015_fb8/ConfigFemtoAnalysis.C
PWGCF/FEMTOSCOPY/macros/Train/KM/pPb502/015j_fb8/ConfigFemtoAnalysis.C
PWGCF/FEMTOSCOPY/macros/Train/KM/pPb502/015s_fb8/ConfigFemtoAnalysis.C

pPb502 KchKch vs ST for fb8

---

PWGCF/FEMTOSCOPY/macros/Train/KM/pPb502/016_fb8/ConfigFemtoAnalysis.C
PWGCF/FEMTOSCOPY/macros/Train/KM/pPb502/016j_fb8/ConfigFemtoAnalysis.C
PWGCF/FEMTOSCOPY/macros/Train/KM/pPb502/016s_fb8/ConfigFemtoAnalysis.C

K+K- pPb502 fb8 SetNsigmaTPC400_450(1.0)

---

PWGGA/GammaConv/macros/AddTask_GammaConvV1_PbPb.C
PWGGA/GammaConvBase/AliConvEventCuts.cxx
PWGGA/GammaConvBase/AliConvEventCuts.h
PWGGA/PWGGAUtils/CMakeLists.txt
PWGGA/PWGGAUtils/TH1_ExponentialInterpolation.cxx
PWGGA/PWGGAUtils/TH1_ExponentialInterpolation.h
PWGGA/PWGGAUtils/utils_TH1.cxx
PWGGA/PWGGAUtils/utils_TH1.h

PWGGA/GammaConv/PWGGAUtils: enhance expontial splines

---

PWGCF/FLOW/CME/AliAnalysisTaskCVEPIDCMEDiff.cxx
PWGCF/FLOW/CME/AliAnalysisTaskCVEPIDCMEDiff.h
PWGCF/FLOW/CME/PWGCFflowCMELinkDef.h

Fix the streamer issues based on the https://alice-doc.github.io/alice-analysis-tutorial/analysis/streamer.html.

Fix dictionary generation and class serialisation issues.

---

PWGGA/GammaConv/AliAnalysisTaskMesonJetCorrelation.cxx
PWGGA/GammaConv/AliAnalysisTaskMesonJetCorrelation.h
PWGGA/GammaConv/macros/AddTask_MesonJetCorr_K0Lambda.C
PWGGA/GammaConvBase/AliConvK0LambdaCuts.cxx
PWGGA/GammaConvBase/AliConvK0LambdaCuts.h
PWGGA/GammaConvBase/CMakeLists.txt
PWGGA/GammaConvBase/PWGGAGammaConvBaseLinkDef.h

- Add option for checks with K0s and Lambdas
- Add cut class for K0s and Lambda
- Add dedicated AddTask

PWGGA/GammaConv: Add more mesons to MesonInJet task

---

PWGGA/GammaConv/AliAnalysisTaskMesonJetCorrelation.cxx
PWGGA/GammaConv/AliAnalysisTaskMesonJetCorrelation.h
PWGGA/GammaConv/macros/AddTask_MesonJetCorr_K0Lambda.C
PWGGA/GammaConvBase/AliConvK0LambdaCuts.cxx
PWGGA/GammaConvBase/AliConvK0LambdaCuts.h

- Further optimize cuts for K0+Lambda in-jets
- Make it possible to run Lambda+Anti-Lambda (or in general multiple particles) at once

PWGGA/GammaConv: Adjustments to in-jet task

---

PWGLF/NUCLEX/Exotica/Dibaryons/AliAnalysisTaskpOmegaDibaryon.cxx

for semi-central events

---

PWGJE/EMCALJetTasks/UserTasks/AliAnalysisTaskEmcalHfeTagging.cxx
PWGJE/EMCALJetTasks/UserTasks/AliAnalysisTaskEmcalHfeTagging.h

Fix for all histograms to be added to output object and new secondary histograms. Minor organization and clean-up

PWGJE: Output fix and new secondary histograms

---

PWGJE/macros/AddTaskJetCluster.C

Updated version of AddTaskJetCluster to fix ROOT 6 compatibility.

[PWGJE] AddTaskJetCluster: Fix ROOT6 compatibility
