alisw/AliPhysics

- PWGLF/FORWARD/analysis2/AliCentralCorrectionManager.cxx
- PWGLF/FORWARD/analysis2/AliForwardCorrectionManager.cxx
- PWGPP/EVCHAR/FlowVectorCorrections/QnCorrectionsInterface/AliAnalysisTaskFlowVectorCorrections.cxx
use for the following large files:
- spd_corrections.root
used in PWGLF/FORWARD/analysis2/AliCentralCorrectionManager.cxx
- fmd_corrections.root
used in PWGLF/FORWARD/analysis2/AliForwardCorrectionManager.cxx
- event plane calibration (framework_v2)
used in PWGPP/EVCHAR/FlowVectorCorrections/QnCorrectionsInterface/AliAnalysisTaskFlowVectorCorrections.cxx
> Use AliDataFile for large files

- PWGDQ/reducedTree/AliAnalysisTaskReducedTreeMaker.cxx
- PWGDQ/reducedTree/AliReducedBaseTrack.h
Added AOD filterbit information to `AliReducedBaseTrack::fQualityFlags` starting at BIT(15).
AOD filter bit 0 corresponds to 15
AOD filter bit 10 corresponds to 25
> Added AOD filterbit information to AliReducedBaseTrack

- PWG/EMCAL/EMCALtasks/AliEmcalCorrectionClusterizer.cxx
A difference was identified between "tender" clusterizer and new correction framework clusterizer (based on ClusterizeFast): the centralized clusterizer seems to set cluster ID always to 0 -- this commit fixes it, setting the ID as done in the tender.
> fix cluster id assignment

- PWGCF/Correlations/DPhi/AliAnalysisTaskPhiCorrelations.cxx
This commit allows the user to forbid/allow certain correlations when giving custom particles A/B. Before, the mixing is done wrong in certain situations (self correlations could occur).
> Custom unique particle ID based on label property

- PWGLF/SPECTRA/PiKaPr/TOF/PbPb502/task/AliAnTOFtrack.cxx
- PWGLF/SPECTRA/PiKaPr/TOF/PbPb502/task/AliAnalysisTaskTOFSpectra.cxx
- PWGLF/SPECTRA/PiKaPr/TOF/PbPb502/task/AliAnalysisTaskTOFSpectra.h
Improved task with finer binning.
Added extra protection for counter.
> TOF 5TeV PiKaPr analysis update

- PWGHF/hfe/AliAnalysisTaskHFEpACorrelation.cxx
- PWGHF/hfe/AliAnalysisTaskHFEpACorrelation.h
- PWGHF/hfe/macros/AddTaskHFEpACorrelation.C
- PWGHF/hfe/macros/configs/pPb/ConfigHFEpACorrelation.C
Hi,
I added the histograms to check the TPC Splines as function of momentum (p), the invariant mass plots as function of pT bins and changed the default multiplicity to use the ZNA. It is still possible to use V0A in case it is needed.
> TPC PID studies and Mult Update

- PWGJE/EMCALJetTasks/Tracks/AliAnalysisTaskEmcalTriggerBase.cxx
- PWGJE/EMCALJetTasks/Tracks/AliAnalysisTaskEmcalTriggerBase.h
- Add handling for INT8 and EMC8 trigger suite in the
trigger selection and in the list of supported triggers
- Add option to require L0 for L1
- Fix handling of single threshold L1
+ EGA mapped to EG1
+ EJE mapped to EJ1
+ E[J|G]2 triggers stay empty
> Support for T0-based triggers pp 8 TeV

- PWG/EMCAL/EMCALtasks/AliEmcalCorrectionTask.cxx
- PWG/EMCAL/EMCALtasks/AliEmcalCorrectionTask.h
Implement suggestion from the EMCal Question and Answer meeting on 23
March 2017 to provide a comparison function for YAML configuration
files. Thanks Constantin for the suggestion!
Also removed the run period setter function announced two weeks ago.
> EMCal CorrFW: Compare configs, remove run period

- PWGLF/RESONANCES/AliRsnMiniEvent.h
- PWGLF/RESONANCES/macros/mini/qa/AddTaskRsnQA.C
- PWGLF/RESONANCES/macros/mini/qa/ConfigRsnQA.C
Two changes for the Resonance package:
1) make pointers to event object transient members by using "//!", which should fix runtime memory problems in LEGO trains of the Resonances analysis task;
2) a new config and AddTask are created for the new Rsn analysisQA.
> Fix for memory usage for Rsn analysis task + new Rsn QA config

- PWGJE/EMCALJetTasks/Tracks/AliEmcalAnalysisFactory.cxx
- PWGJE/EMCALJetTasks/Tracks/AliEmcalAnalysisFactory.h
Functions generating ESD track cuts objects for
the track cuts variation are added. Cuts are
based on the default cut settings, each varying
only one cut at the time. Cut string always
consist of a certain tag for the cut and a
4-digit cut value where then last digit represents
the first decimal digit.
> Implememt functions setting track cuts variation

- PWGCF/Correlations/ThreePart/CMakeLists.txt
Reverts errors as warnings, as it seems to be unstable wrt compiler versions atm. Will investigate locally.
> Revert errors as warnings (for now)

- PWG/Tools/AliBasicParticle.cxx
- PWG/Tools/AliBasicParticle.h
- PWGCF/Correlations/Base/AliUEHistograms.cxx
- PWGCF/Correlations/Base/AliUEHistograms.h
- PWGCF/Correlations/DPhi/AliAnalysisTaskPhiCorrelations.cxx
- PWGCF/Correlations/DPhi/AliAnalysisTaskPhiCorrelations.h
This commit only (directly) affects the usage of custom particles in AliAnalysisTaskPhiCorrelations.
It is to allow the task to use an imported event pool correctly. Without, the tracks from an imported pool are mixed with tracks from the same events.
> Implement event counter in AliBasicParticle to allow using of all-event pool for mixed event

- PWGLF/NUCLEX/Nuclei/DeuteronpA/AddTaskTPCTOFpA.C
This is to run the deuteron pA analysis a last time on the LEGO train before publishing it. Previously the physicsSelection was disabled for testing purposes.
> preparing analysis deuteron pA for publication validation train run

- PWGPP/macros/MakeTrendingPIDQA.C
This commit implements a feature needed in the AnalysisQA by PWG-LF: canvases can be ssaven in a format which can be specified in one of the arguments of the macro.
> Add posiibility to save output in eps format, for PWG-LF QA

- PWGGA/EMCALTasks/macros/AddTaskEMCALPhotonIsolation.C
With the previous commit i introduced a small bug,I added two colons instead of one as a binary operand in the composition of the output container for the AliAnalysisTaskEMCALPhotonIsolation.. 
I am really sorry but not even the CTest spotted it.
> Fixing a double colon which should have been a single colon 

- PWGHF/vertexingHF/AliHFMultiTrials.cxx
A small fix to avoid warnings when running this code in ROOT6.
> Small fix for ROOT6

- PWGPP/EvTrkSelection/AliCFSingleTrackEfficiencyTask.cxx
- PWGPP/EvTrkSelection/AliCFSingleTrackEfficiencyTask.h
- PWGPP/EvTrkSelection/macros/AddSingleTrackEfficiencyTaskPbPb.C
- PWGPP/EvTrkSelection/macros/AddSingleTrackEfficiencyTaskpp.C
New option in the single track efficiency task
> Option to use the generated pt,eta,phi for the reconstructed tracks

- PWGPP/AD/AliAnalysisTaskADQA.cxx
- PWGUD/DIFFRACTIVE/CEPdevel/AliAnalysisTaskCEP.cxx
- PWGUD/DIFFRACTIVE/CEPdevel/AliAnalysisTaskCEP.h
- PWGUD/DIFFRACTIVE/CEPdevel/AliCEPBase.h
- PWGUD/DIFFRACTIVE/CEPdevel/AliCEPUtils.cxx
- PWGUD/DIFFRACTIVE/CEPdevel/AliCEPUtils.h
Histograms are added to the output of AliAnalysisTaskCEP containing the B[B,G]Flag information of the AD and V0 detectors
> added histograms with AD and VZero BBFlag information

- PWGLF/STRANGENESS/Cascades/Run2/AliAnalysisTaskStrangenessVsMultiplicityMCRun2.cxx
- PWGLF/STRANGENESS/Cascades/Run2/AliAnalysisTaskStrangenessVsMultiplicityMCRun2.h
- PWGLF/STRANGENESS/Cascades/Run2/AliAnalysisTaskStrangenessVsMultiplicityRun2.cxx
- PWGLF/STRANGENESS/Cascades/Run2/AliAnalysisTaskStrangenessVsMultiplicityRun2.h
Removed redundant branches added previously with TOF info for pileup studies in pp collisions.
Matching the branches added for Data and MC analysis codes.
> Adjusting branches with TOF info for pileup studies in pp.

- PWG/EMCAL/EMCALbase/AliEmcalContainerUtils.h
- PWG/EMCAL/EMCALtasks/AliEmcalCorrectionClusterizer.cxx
- PWG/EMCAL/EMCALtasks/AliEmcalCorrectionClusterizer.h
- PWG/EMCAL/EMCALtasks/AliEmcalCorrectionTask.cxx
- PWG/EMCAL/EMCALtasks/AliEmcalCorrectionTask.h
- PWG/EMCAL/config/AliEmcalCorrectionConfiguration.yaml
Changes include:
- Adding timing information to the clusterizer (Note: You need to enable
histogram creation for the timer to run!)
- Clarify error when cells are missing
- Set the centrality estimator in the correction task
- Comment on the units of the clusterizer min cell and seed energies
> EMCal CorrFW: Small improvements and fixes

- PWG/Tools/AliBasicParticle.h
- PWGCF/Correlations/Base/AliUEHistograms.cxx
- PWGCF/Correlations/DPhi/AliAnalysisTaskPhiCorrelations.cxx
- PWGCF/Correlations/DPhi/AliAnalysisTaskPhiCorrelations.h
This is a bug fix. Before, the unique event ID was only unique on a per-task level.
With this commit, the event ID is taken from the header. In addition, the ID is now correctly set for cloned tracks.
> Unique event ID correctly evaluated and propagated to tracks

- PWGPP/ITS/AliAnalysisTaskITSTrackingCheck.cxx
- PWGPP/ITS/AliAnalysisTaskITSsaTracks.cxx
- PWGPP/ITS/AliAnalysisTaskSEImpParRes.cxx
- PWGPP/ITS/AliAnalysisTaskSEImpParResSparse.cxx
Modification needed to access the generated particles in case of mc-to-mc embedding
> Replace usage of AliStack with AliMCEvent in ITS QA tasks

- PWGCF/FEMTOSCOPY/AliFemto/AliFemtoEventReaderAOD.cxx
- PWGCF/FEMTOSCOPY/AliFemto/AliFemtoXi.cxx
- PWGCF/FEMTOSCOPY/AliFemto/AliFemtoXi.h
- PWGCF/FEMTOSCOPY/AliFemto/AliFemtoXiTrackCut.cxx
- PWGCF/FEMTOSCOPY/AliFemto/AliFemtoXiTrackCut.h
- PWGCF/FEMTOSCOPY/AliFemtoUser/AliFemtoAnalysisLambdaKaon.cxx
- PWGCF/FEMTOSCOPY/AliFemtoUser/AliFemtoAnalysisLambdaKaon.h
PWGCF: AliFemtoXi, AliFemtoXiTrackCut, AliFemtoEventReaderAOD: Added new attribute fCosPointingAngleV0toXi, i.e. the V0's pointing angle to the Xi's decay vertex.  In a Xi analysis, this is more useful than the V0s pointing angle to the primary vertex.
> PWGCF: AliFemtoXi, AliFemtoXiTrackCut, AliFemtoEventReaderAOD

- PWGHF/vertexingHF/AliAnalysisTaskDmesonMCPerform.cxx
- PWGHF/vertexingHF/AliAnalysisTaskDmesonMCPerform.h
- PWGHF/vertexingHF/CMakeLists.txt
- PWGHF/vertexingHF/PWGHFvertexingHFLinkDef.h
- PWGHF/vertexingHF/macros/AddTaskDmesonMCPerform.C
This is a first implementation of a task which could be used in the AnalysisQA train for MC productions and in the MC release validation.
Checks that the deltaAODs are properly filled and fills simple performance plots for D-meson signals (decay vertex resolution, invariant mass resolution, pointing angle and decay length distributions, reconstruction efficiencies)
> New task for D-meson performance studies on MC

- PWGHF/jetsHF/AliDJetRawYieldUncertainty.cxx
- PWGHF/jetsHF/AliDJetRawYieldUncertainty.h
- PWGHF/jetsHF/macros/ExtractDJetRawYieldUncertainty.C
- PWGHF/vertexingHF/AliHFMassFitter.cxx
- PWGHF/vertexingHF/AliHFMassFitterVAR.cxx
- PWGHF/vertexingHF/AliHFMassFitterVAR.h
- PWGHF/vertexingHF/AliHFMultiTrials.cxx
- PWGHF/vertexingHF/AliHFMultiTrials.h
These PR contains a number of commits:
- Fix an issue with invalid memory access when the results of the mass fit are drawn in the canvas and the mass fitter is deleted
- Fix various potential (and actual) memory leaks
- Fix indentation
> Updates for the HF multi-trial class and the D-tagged jet raw yield uncertainty

- PWGHF/hfe/AliAnalysisTaskHFEemcQA.cxx
- PWGHF/hfe/AliAnalysisTaskHFEemcQA.h
Change the array name to access corrected EMCAL cluster and track array.
Add histograms to plot non-linearity corrected EMCAL cluster energy.
> Change array name, add histograms

- PWG/EMCAL/EMCALbase/AliAnalysisTaskEmcalEmbeddingHelper.cxx
- PWG/EMCAL/EMCALbase/AliAnalysisTaskEmcalEmbeddingHelper.h
Includes:
- Moving initialization to the run macro or wagon (like the EMCal Correction Task)
- Improved methods to find files in AliEn to embed
- Print methods for the Embedding Helper
> EMCal Embed: Improve finding files and init

- PWGHF/vertexingHF/AliAnalysisTaskSEHFQA.cxx
- PWGHF/vertexingHF/AliAnalysisTaskSEHFQA.h
- Fix missing initialisation of 2 data members
- Add an additional histogram monitoring SPD primary vertex after event selection
> Monitor SPD primary vertex before and after event selection

- PWGLF/QATasks/post/PostProcessQAMultistrange.C
A parenthesis was missed to close the pdf in the last page.
> Small correction to produce a working pdf output

- PWGPP/TPC/AliPerformanceDCA.cxx
- PWGPP/TPC/AliPerformanceDCA.h
- PWGPP/TPC/AliPerformanceDEdx.cxx
- PWGPP/TPC/AliPerformanceDEdx.h
- PWGPP/TPC/AliPerformanceEff.cxx
- PWGPP/TPC/AliPerformanceMC.cxx
- PWGPP/TPC/AliPerformanceMC.h
- PWGPP/TPC/AliPerformanceMatch.cxx
- PWGPP/TPC/AliPerformanceMatch.h
- PWGPP/TPC/AliPerformancePtCalib.h
- PWGPP/TPC/AliPerformancePtCalibMC.cxx
- PWGPP/TPC/AliPerformancePtCalibMC.h
- PWGPP/TPC/AliPerformanceRes.cxx
- PWGPP/TPC/AliPerformanceRes.h
- PWGPP/TPC/AliPerformanceTPC.cxx
- PWGPP/TPC/AliPerformanceTPC.h
- PWGPP/TRD/AliTRDinfoGen.cxx
- PWGPP/global/AliAnalysisTaskVertexESD.cxx
1) Make sure tasks are using full AliMCEvent to query MC info and not the AliStack of signal event only (ignoring underlying event).
2) Cosmetic fix to avoid querying TClonesArray of SPD pile-up vertices w/o making sure that there are entries.
> Fixes to make TRD and TPC QA tasks compatible with embedded MC

- PWGDQ/reducedTree/AliAnalysisTaskReducedTreeMaker.cxx
fgEvent in `AliDielectronVarManager` was not set.
Therefore DCA wasn't calculated for all AOD filter bits in the ReducedTreemaker.
Fixed by adding `AliDielectronVarManager::SetEvent(event)`.
> Fixed issue of DCA in AOD analysis.

- PWGDQ/reducedTree/AliAnalysisTaskReducedTreeMaker.cxx
Fixed eventplaneinfo not being correctly written to file after previous commit #440.
`AliDielectronVarManager::SetEvent(event);`fills values into `fgData`
`AliDielectronVarManager::GetValue(...)` gets the values from `fgData`
> Fixed AliReducedEventPlaneInfo not being written to tree.

- PWGJE/EMCALJetTasks/CMakeLists.txt
- PWGJE/EMCALJetTasks/PWGJEEMCALJetTasksLinkDef.h
Compile classes depending on fastjet only if fastjet is found
> Fix for fastjet dependence introduced in 06cd0021f1e6c4eeaa7c0d648472704246b465d9

- PWG/EMCAL/EMCALbase/AliAnalysisTaskEmcal.cxx
- PWG/EMCAL/EMCALbase/AliAnalysisTaskEmcal.h
- PWGJE/EMCALJetTasks/Tracks/AliAnalysisTaskChargedParticlesRefMC.cxx
Currenly in rare cases incorrect pt-hard bins are
filled when running on the grid. The incorrect pt-hard
bins are neighboring bins (in case of determination
by the pt-hard value) or bin number 0 (in case of
determination using the absolute file path.
- Storing globally defined (from file path) pt-hard
bin in addition to locally defined (from pt-hard
value in the header)
- Adding histograms sensitive to the pt-hard binning
- Correlation between pt-hard value and local bin
- Correlation between pt-hard value and global bin
- Correlation between global and local bin
- Change type of pt-hard variable from double to float
(implicit conversion from lower precision to high
precision floating point number enforcing comparison
using double precision) as pt-hard value is stored
only with single …
> Debugging issue with incorrect pt-hard bins

- PWGCF/FEMTOSCOPY/macros/Train/LambdaKaonFemto/ConfigFemtoAnalysis.C
- PWGCF/FEMTOSCOPY/macros/Train/LambdaKaonFemto/ConfigFemtoAnalysisSystematics.C
- PWGCF/FEMTOSCOPY/macros/Train/LambdaKaonFemto/ConfigFemtoAnalysisSystematics2.C
PWGCF: Train/LambdaKaonFemto/ConfigFemtoAnalysis... altered config files so no filter bit set for kProtPiM, kAProtPiP, and kPiPPiM analyses
> PWGCF: Train/LambdaKaonFemto/ConfigFemtoAnalysis... altered config files

- PWG/EMCAL/EMCALtasks/AliEmcalCorrectionTask.cxx
Protect against overwriting configuration files (perhaps from multiple
correction tasks using the same config filename) by adding a UUID
to the start of the file name.
@jdmulligan
> EMCal CorrFW: Protect against overwriting config

- PWG/EMCAL/EMCALbase/AliAnalysisTaskEmcal.cxx
- PWG/EMCAL/EMCALbase/AliAnalysisTaskEmcal.h
- Consistently move documentation to the HEADER file
- Add brief descriptor for functions as well
- Replace manual description of enum types as function arguments by ref
- Mark deprecated functions as deprecated
- Improve and exdend description of some of the core framework functions
> Modifications for doxygen of AliAnalysisTaskEmcal

- PWGLF/STRANGENESS/CMakeLists.txt
- PWGLF/STRANGENESS/Cascades/Run2/AliAnalysisTaskStrangenessVsMultiplicityMCRun2.cxx
- PWGLF/STRANGENESS/Cascades/Run2/AliAnalysisTaskStrangenessVsMultiplicityMCRun2.h
- PWGLF/STRANGENESS/Cascades/Run2/AliAnalysisTaskStrangenessVsMultiplicityRun2.cxx
- PWGLF/STRANGENESS/Cascades/Run2/AliAnalysisTaskStrangenessVsMultiplicityRun2.h
New branches added to store V0A and V0C amplitudes and FMD hits in the overlap regions with V0.
> Added branches to store FMD and V0 info for OOB pileup studies

- PWGPP/EMCAL/AliAnalysisTaskEmcalAlig.cxx
- PWGPP/EMCAL/AliAnalysisTaskEmcalAlig.h
- PWGPP/EMCAL/CMakeLists.txt
- PWGPP/EMCAL/PWGPPEMCALLinkDef.h
- PWGPP/EMCAL/macros/AddTaskEmcalAlig.C
Hi,
This new class redo the propagation for electrons. The residual is recalculated. The default method propagates only until the EMCal Surface and it is also saved for comparison. It is necessary to check in details the alignment of EMCal and DCal.
> New class for EMCal alignment

- PWGPP/TPC/CalibMacros/ProcessOutputCheb.C
@chiarazampolli, @fprino, could you please transfer updated PWGPP/TPC/CalibMacros/ProcessOutputCheb.C to ALIDPG, the processing does not change but the log message was wrong (if the distortion object was missing, it was complaining about missing correction object)
> Fix in log message (does not affect processing)

- PWGHF/vertexingHF/AliAnalysisTaskSEB0toDStarPi.cxx
- PWGHF/vertexingHF/AliAnalysisTaskSEB0toDStarPi.h
- PWGHF/vertexingHF/AliRDHFCutsB0toDStarPi.cxx
- PWGHF/vertexingHF/AliRDHFCutsB0toDStarPi.h
- PWGHF/vertexingHF/CMakeLists.txt
- PWGHF/vertexingHF/PWGHFvertexingHFLinkDef.h
This is the code for the analysis task for the full hadronically reconstructed B0 which decays to a DStar and a Pion, the DStar decays to a D0 and a Pion, and the D0 decays to a Kaon and a Pion.
The corresponding AliRDHFCuts file for this analysis task is also added.
> Analysis task for B0 to DStar+Pi to D0+Pi+Pi to K+Pi+Pi+Pi

- PWGCF/FLOW/macros/AddTaskZDCGainEq.C
Removed  'mgr->InitAnalysis()' from AddTask macro which was prohibiting from running multiple wagons in same train. 
Also changed return type from 'void' to class pointer so that "__R_ADDTASK__" option is available for sub-wagon configuration.
> Fixed AddTaskZDCGainEq for multiple wagon

- PWG/FLOW/Tasks/AliAnalysisTaskZDCEP.cxx
- PWG/FLOW/Tasks/AliAnalysisTaskZDCEP.h
- PWG/FLOW/Tasks/CMakeLists.txt
- PWG/FLOW/Tasks/PWGflowTasksLinkDef.h
- PWGCF/FLOW/macros/AddTaskZDCEP.C
Add new task (AliAnalysisTaskZDCEP.*) and corresponding "adding macro" (AddTaskZDCEP.C).
Provides calibrated ZDC Q-vectors for LHC15o (PbPb 5.02 TeV).
Output format: AliFlowEvent. To get ZDC Q-vectors use AliFlowEvent::GetZDC2Qsub().
Calibration files currently in private folder: /alice/cern.ch/user/j/jmargutt/ (to be fixed!)
> add new task for ZDC event plane in LHC15o

- PWGPP/AD/AliAnalysisTaskADCalib.cxx
This produces AD/Calib/Saturation objects which do not have the problem found in [ALIROOT-7218](https://alice.its.cern.ch/jira/browse/ALIROOT-7218)
> TF1::BypassStreamer corrected

- PWG/Cocktail/AliGenEMCocktailV2.cxx
- PWG/Cocktail/AliGenEMCocktailV2.h
- PWG/Cocktail/AliGenEMlibV2.cxx
- PWG/Cocktail/AliGenEMlibV2.h
- PWG/Cocktail/macros/AddMCEMCocktailV2.C
- PWGGA/GammaConv/AliAnalysisTaskGammaCocktailMC.cxx
- PWGGA/GammaConv/AliAnalysisTaskGammaCocktailMC.h
- PWGGA/GammaConv/AliAnalysisTaskHadronicCocktailMC.cxx
- PWGGA/GammaConv/AliAnalysisTaskHadronicCocktailMC.h
implemented option to use rapidity weighting in EM cocktail generation from input files,
settings will be stored by the corresponding analysis tasks AliAnalysisTaskGammaCocktail and AliAnalysisTaskHadronicCocktail
> PWG/Cocktail and PWGGA/GammaConv: updates for EM cocktail generation

- PWGPP/EMCAL/CMakeLists.txt
The loading of libraries fails and this commit fixes the issue.
> PWGPPEMCAL depends on PWGEMCALbase

- PWGJE/EMCALJetTasks/AliJetResponseMaker.cxx
AliEmcalJet::Track(i) calls AliEmcalJet::TrackAt(i), so calling
AliEmcalJet::Track(AliEmcalJet::TrackAt(i)) is redundant and
causes an index out of bounds. This occurred here a few times
since the calls to the two functions were separated.
> EMCal Embed: Fix jet constituent index

- PWGGA/EMCALTasks/AliAnalysisTaskEMCALPhotonIsolation.cxx
- PWGGA/EMCALTasks/macros/AddTaskEMCALPhotonIsolation.C
Phi acceptance values are still to be fixed: sometimes the EMCal phi range (minPhi, maxPhi) is (1.398, pi) or (1.4, 3.15), whereas in a more accurate way it is set as (5/9)*pi. Those three cases give slightly different maxPhi-minPhi values.
Some minor code aesthetics is also done in this commit.
> Task: standardisation of acceptance values + fix of the UE area calculation. AddTask: removal of two comments previously written.

- PWGPP/ITS/AliAnalysisTaskSEImpParResSparse.cxx
Variable declaration repetition fixed in the UserExec().
> Bug fix in PWGPP/ITS/AliAnalysisTaskSEImpParResSparse.cxx

- PWGHF/vertexingHF/AliAnalysisTaskSEHFQA.cxx
- PWGHF/vertexingHF/AliAnalysisTaskSEHFQA.h
Possibility to monitor the ITS cluster distributions for ITS-SA tracks with:
- no SPD request
- SPD kAny
- SPDin
- SPDout
> Monitor ITS-SA tracks versus SPD hits

- PWGPP/AliMCTreeTools.cxx
- PWGPP/AliMCTreeTools.h
WARNING : this code is for fast visualization and prototyping NOT FOR PRODUCTION SOFTWARE
* Goals was flexibility not speed
* Speed can be achieved caching information in friend tree using  
```
AliTreePlayer::MakeCacheTree
```
* GetParticle properties at vertex (using ESd tree)
* e.g to compare reconstructed track momenta and MC momenta  ( mentioned in PWGPP-205)
```
esdTree->Draw("Tracks[].fIp.Pt()/AliMCTreeTools::GetValueAt(Entry$,abs(Tracks[].fLabel),0,0,0,8,1,0)","(Tracks[].fTPCncls)>80&&Tracks[].fITSncls>3","")
```
* Find TPC space point porperty using closest MC information  ( mentioned in ATO-168)
* used for loop finder as a ground cluster/tracklet true
* fast as used  togeter with AliTreePalyer::MakeCacheTree(TTree * tree, TString varList, TString outFile, TString outTree, TCut …
> PWGPP-205,ATO-168: Add:Class to query MC info in TTree

- PWG/HMTF/AliAnalysisTaskHMTFMCMultEst.cxx
- PWG/HMTF/AliAnalysisTaskHMTFMCMultEst.h
- PWG/HMTF/AliEventClassifierBase.cxx
- PWG/HMTF/AliEventClassifierBase.h
- PWG/HMTF/AliEventClassifierMult.cxx
- PWG/HMTF/AliEventClassifierMult.h
- PWG/HMTF/AliEventClassifierSphericity.cxx
- system information can be supplied to the AliAnalysisTaskHMTFMCMultEst class via the public member functin 'SetGlobalSystem'
- system information is then passed on to the event classifier classes for which system is relevant, e.g. multiplicity (so that appropriate bounds can be set)
- change is fully backward compatible: if not set, pp is used, which forces the task to use the 'standard' defaults, so no user intervention is necessary
>  added system information (pp, pPb, PbPb) to event classifier base class

- PWGCF/FEMTOSCOPY/AliFemto/AliFemtoEventReaderAOD.cxx
- PWGCF/FEMTOSCOPY/AliFemto/AliFemtoV0.cxx
- PWGCF/FEMTOSCOPY/AliFemto/AliFemtoXi.cxx
- PWGCF/FEMTOSCOPY/AliFemto/AliFemtoXi.h
- PWGCF/FEMTOSCOPY/AliFemto/AliFemtoXiTrackPairCut.cxx
- PWGCF/FEMTOSCOPY/AliFemto/AliFemtoXiTrackPairCut.h
- PWGCF/FEMTOSCOPY/AliFemtoUser/AliFemtoV0PurityBgdEstimator.cxx
PWGCF:  AliFemtoXi: Included nominal TPC info for bachelor pions.  AliFemtoXiTrackPairCut: began to make more sophisticated pair cuts.  AliFemtoEventReaderAOD: included methods to set the nominal TPC attributes for the bachelor pions
> PWGCF:  AliFemtoXi: Included nominal TPC info for bachelor pions.

- PWGHF/vertexingHF/AliRDHFCuts.cxx
- PWGHF/vertexingHF/AliRDHFCuts.h
This modification adds the possibility to reject events with large nsigma difference between SPD and track vertices. It also modified the tagging of events with large distance between the SPD and track vertices, which are now tagged as "bad vertex" and treated in the event normalization counter as events without vertex.
> Add possibility to cut on nsigma distance between SPD and track vertices

- PWGHF/hfe/AliAnalysisTaskHFEpACorrelation.cxx
- PWGHF/hfe/AliAnalysisTaskHFEpACorrelation.h
- PWGHF/hfe/macros/AddTaskHFEpACorrelation.C
The changes split Run 1 and Run 2 tagging efficiency calculations. Run 1 is kept exactly how it was (if was just moved to a function) in case any future check is needed. The Run 2 one uses only the electrons from the enhanced pi0 and eta. 
The function to compare the spectra with and without enhanced signal is implemented too. The weights are stored in a TH1F that can be defined in the AddTask.
> Tagging efficiency for HFe-h correlations

- PWGUD/UPC/AliAnalysisTaskUpcEtaC.cxx
- PWGUD/UPC/AliAnalysisTaskUpcEtaC.h
This is a temporary version with histograms to explore new PID options, test a new PID option. An error resetting the counter for the number of good tracks (nGoodTracks) in the K0s channel was implemented. The PID criteria are relaxed a little to allow one track with missing TOF information. Pt and Minv 1D histograms are changed to PtVsMinv 2D histograms to facilitate analyzing in different Pt ranges.
> Added histos for new PID, PtVsMinv 2D histos, reset K0s trk counter

- PWGCF/FEMTOSCOPY/AliFemto/AliFemtoEventReaderAOD.cxx
- PWGCF/FEMTOSCOPY/AliFemtoUser/AliFemtoAnalysisLambdaKaon.cxx
- PWGCF/FEMTOSCOPY/AliFemtoUser/AliFemtoAnalysisLambdaKaon.h
PWGCF: AliFemtoEventReaderAOD: Began work on hidden info for MC Cascades.  For now, in the AliFemtoHiddenInfo object, the V0 will be stored as the positive daughter, and the bachelor pion will be stored as the negative daughter.  In the future, either AliFemtoHiddenInfo will be expanded to allow of Xi storage, or a new daughter class will be built.
> PWGCF: AliFemtoEventReaderAOD: Began work on hidden info for MC Cascades

- PWGJE/EMCALJetTasks/Tracks/AliAnalysisTaskEmcalTriggerBase.cxx
- Bug was introdued in commit 21e76b1,
dealing with the preparation for pp 8 TeV
- EMCAL-triggered events were only selected if they
were at the same time a level0 trigger due to
incorrect logical or condition
> Fixing logics bug in selection of EMCAL triggers

- PWGHF/hfe/AliAnalysisTaskHFEpACorrelation.cxx
I forgot to add the protection in case it is running in data. So the task was crashing in data.
> Remove efficiency calculation when running in data

- PWGGA/EMCALTasks/macros/AddTaskEMCALPhotonIsolation.C
This was previously set in the run macro (or in a wagon) on the current instance of the task. Now the two parameters bTMClusterRejection and bTMClusterRejectionInCone are used directly inside the AddTask.
Calling SetTMClusterRejection()/InCone() in the run macro (or wagon) overwrites this new inside-AddTask setting so that nothing changes for a user who does not change his/her run macro (or wagon).
> Setting SetTMClusterRejection() according to fTMClusterRejected (instead of fixed value), outside and inside the isolation cone

- PWGGA/EMCALTasks/AliAnalysisTaskEMCALPhotonIsolation.cxx
selecting clusters with Shower shape bigger than that typical of Exotic clusters to store information useful for the computation of the Trigger Rejection Factor.
> adding a condition on the shape of clusters to a filling of an histogram

- PWGUD/DIFFRACTIVE/CEPdevel/AliAnalysisTaskCEP.cxx
- PWGUD/DIFFRACTIVE/CEPdevel/AliCEPUtils.cxx
- PWGUD/DIFFRACTIVE/CEPdevel/AliCEPUtils.h
For LHC16[o,p] data the automatic initialisation of AliEventCuts is not enabled yet, as temporary solution AliEventCuts is disabled in AliAnalysisTaskCEP for run numbers > 260187, hence LHC16[o,p] data
> Make AliAnalysisTaskCEP to run on LHC16[o,p] data

- PWGLF/QATasks/post/PostProcessQAMultistrange.C
Adding the possibility to read the container filled only with reconstructed candidates associate to the MC truth in case of MC production check
> Add reading of container with association

- PWGUD/DIFFRACTIVE/CEPdevel/AliCEPUtils.cxx
With the old initialisation of GetStandardITSTPCTrackCuts2010 the daughter of V0s did not pass the track selection. With this modification V0 daughters pass the cut.
> Allow daughters of V0s to pass track cuts

- PWGPP/TRD/TRDPID/macros/AddTaskTRDPIDTree.C
The TRDPIDTree Output gets a name which depends one the chosen Trigger. So multiple Triggers can be used in one train.
> Files get a name, that depend on the used trigger

- PWGHF/hfe/AliAnalysisTaskHFEpACorrelation.cxx
- PWGHF/hfe/AliAnalysisTaskHFEpACorrelation.h
I added the"pure" background tagging efficiency (excluding the enhancement from the production) to crosscheck if the weighting is calculated correctly.
> Background tagging efficiencies update

- PWG/FLOW/Base/AliFlowAnalysisWithSimpleSP.cxx
- PWG/FLOW/Base/AliFlowCommonHist.cxx
- PWG/FLOW/Base/AliFlowCommonHist.h
The motivation behind these changes is that the AliFlowCommonHist object only stores QA histograms for the 2nd order symmetry axes of events, regardless of the flow harmonic of interest. In the case of event plane calibrations that are harmonic dependent (e.g. the common V0 calibration in the flow event class) the info in these QA plots is therefore not necessarily reliable. This does not affect any results, but it's better to have histograms that make sense in QA output.
The changes are fully backward compatible - as long as you do not change anything in your own code, the behavior of the class does not change. If desired, the harmonic can be set via the constructor of the AliFlowCommonHist class.
If you suspect that code change affects your analysis, please send me a mail.
> adding flow harmonic as private member to the AliFlowCommonHist class

- PWGPP/ZDC/macros/DrawPerformanceZDCQAMatch.C
- PWGPP/ZDC/macros/DrawPerformanceZDCQAMatchTrends.C
- PWGPP/ZDC/macros/MakeTrendZDC.C
This commit contains the fixes for few problems related to the fact that the ZDC offline QA histograms were changed but not synchronized with the trending tools.
> Updating QA trending macros for ZDC

- PWGJE/EMCALJetTasks/Tracks/AliEmcalAnalysisFactory.cxx
Require cut string not to contain "Constrained" in case of
the TPC chi2 variation, fixing incorrect assignment of
misconfigured second cut object
> Fix variation for TPC chi2 constrained vs global cut

- PWGGA/EMCALTasks/AliAnalysisTaskEMCALPhotonIsolation.cxx
- PWGGA/EMCALTasks/AliAnalysisTaskEMCALPhotonIsolation.h
- PWGGA/EMCALTasks/macros/AddTaskEMCALPhotonIsolation.C
The EMCal (eta,phi) limits used for selection of clusters, isolation and UE studies are now based on the detector geometry corresponding to the analysed run (using the geometry instance fGeom defined in AliAnalysisTaskEmcal).
A new data member (fPeriod) and a new function member (SetPeriod()) are defined in order to retrieve the LHC period passed as the first argument of AddTaskEMCALPhotonIsolation.C. This allows to deal with the EMCal max phi for 2012-2013 runs, 20° higher in fGeom than in reality (the two last SMs at the time were already integrated in EMCal but not activated).
> Implementation of geometry-based (eta,phi) boundaries

- PWGJE/EMCALJetTasks/Tracks/AliAnalysisTaskEmcalClustersRef.cxx
Usage of operator!= for finding the cell ID in set prevented
any cell from being selected.
> Fix EMCAL cell multiplicity calculation

- PWGUD/DIFFRACTIVE/CEPdevel/AliCEPUtils.cxx
- PWGUD/DIFFRACTIVE/CEPdevel/CEPEventBuffer.h
These changes provide methods to retrieve the past-future protection flags of V0 and AD
> Added methods in CEPEventBuffer to retrieve PFB[B,G]Flags[V0,AD]

- PWG/EMCAL/EMCALbase/AliAnalysisTaskEmcalEmbeddingHelper.cxx
- PWG/EMCAL/EMCALbase/AliAnalysisTaskEmcalEmbeddingHelper.h
- PWG/EMCAL/EMCALbase/AliEmcalEmbeddingQA.cxx
Includes:
- Ability to remove outliers based on jets in the pythia header and the pt hard
- Rejection reason histogram to clarify why events were rejected
- Update pt hard binning of histograms to match up with other tasks (the extra bin was unnecessary)
> EMCal Embed: MC outliers removal, store rejection reasons

- PWGCF/FEMTOSCOPY/AliFemto/AliFemtoV0TrackCut.cxx
- PWGCF/FEMTOSCOPY/AliFemto/AliFemtoV0TrackCut.h
- PWGCF/FEMTOSCOPY/AliFemtoUser/AliFemtoAnalysisLambdaKaon.cxx
- PWGCF/FEMTOSCOPY/AliFemtoUser/AliFemtoAnalysisLambdaKaon.h
- PWGCF/FEMTOSCOPY/AliFemtoUser/AliFemtoV0TrackCutNSigmaFilter.cxx
- PWGCF/FEMTOSCOPY/AliFemtoUser/AliFemtoXiTrackCutNSigmaFilter.cxx
- PWGCF/FEMTOSCOPY/macros/Train/LambdaKaonFemto/ConfigFemtoAnalysis.C
- PWGCF/FEMTOSCOPY/macros/Train/LambdaKaonFemto/ConfigFemtoAnalysisSystematics.C
- PWGCF/FEMTOSCOPY/macros/Train/LambdaKaonFemto/ConfigFemtoAnalysisSystematics2.C
Included switch to ignore on-fly-status value of the V0.  NOTE IMPORTANT: If you set this to true, be sure to call AliFemtoSimpleAnalysis::SetV0SharedDaughterCut(true) otherwise, in many cases, you will receive multiple copies of the same V0.
> PWGCF: AliFemtoV0TrackCut:  Switch to ignore on-fly-status value of the V0

- PWGHF/hfe/AliAnalysisTaskHFEpACorrelation.cxx
- PWGHF/hfe/AliAnalysisTaskHFEpACorrelation.h
- PWGHF/hfe/macros/AddTaskHFEpACorrelation.C
When the Hijing + enhanced pi0 and eta spectra are merged, the total shape is harder to fit. It is easier to use histograms with very fine binning, since the statistics at high momentum is good due to the enhancement.
> Use histograms for weights

- PWGPP/ITS/AliMeanVertexPreprocessorOffline.cxx
- PWGPP/ITS/AliMeanVertexPreprocessorOffline.h
Due to the HM trigger selection a bias in the evaluation of the Z coordinate in CPass0 was found. These values are now taken from CPass1 and the correspondent OCDB objects are updated (both GRP/Calib/MeanVertex and GRP/Calib/MeanVertexSPD).
> Z coordinate values taken from CPass1

- PWGPP/AliAnalysisTaskFilteredTree.cxx
- PWGPP/AliAnalysisTaskFilteredTree.h
- PWGPP/TPC/macros/comparePerformanceMaps.C
- PWGPP/TPC/macros/performanceFiltered.C
* ADD: default aliases for high pt trees
* ADD: alias for delta of all parameters
* Updated aliases for track diffs. Default diff for combined constrained tracks
* Adopt naming convention for performance trees
* Performance parameterizaition for all tracking variables, pulls  + co-variance matrices
* Performance parameterizaition for selected qa vaiables
* Ncl (ITS,TPC,TRD)
* Ncl efficciency per layer (TPC)
* Normalized chi2 (ITS,TPC,TRD)
* Adjust qahis and normal histogram binning
* Add: grouping of the performance maps with same granularity 
* <qpt,tgl>
* <qpt,tgl,alphaV>
* <qpt,tgl,dalphaQ>
> PWGPP-1, PWGPP-312 - Performance paraemterization

- PWG/EMCAL/EMCALbase/AliAnalysisTaskEmcalEmbeddingHelper.cxx
When looping around at the end of a file list, the pythia cross section
filenames vector went out-of-range when before the TChain catches that
it has finished the last file. The range is now explicitly checked and
an error is thrown that should match up with the end of file list error.
> EMCal Embed: Fix vector out-of-range

- PWGPP/ITS/AliMeanVertexPreprocessorOffline.cxx
- PWGPP/benchmark/benchmark.sh
* Get non-AliEn specific variable from the environment (as agreed with the DPG)
* Exit with a fatal error if CPASSMODE is not set or does not have a correct val
* Fix wrong indentation and stray whitespaces
* Get rid of `Form` on strings with nothing to form
> Fix env vars usage in MeanVertexPreprocessor

- PWGPP/TOF/trending/MakeTrendingTOFQAv2.C
- Removed the SetOwner method of the container List for internal management of trending plots
> Fixed deletion of input objects in TOF QA trending macro

- PWGDQ/dielectron/core/AliDielectron.cxx
Old code recreated histogram in new scope and was therefore not able to use histogram outside this scope
> Fixed usage of histograms for runwise TPC PID correction

- PWG/EMCAL/EMCALbase/AliAnalysisTaskEmcalEmbeddingHelper.cxx
- PWG/EMCAL/EMCALbase/AliAnalysisTaskEmcalEmbeddingHelper.h
The xSec hist is a TProfile, so we should _NOT_ scale it by the
number of entries - it is already the mean xSec/event!
The corresponding entries for the xSec and nTrials were renamed to
clarify. Note that the nTrials is _still_ scaled by the number of
entries because it is _not_ a TProfile!
> EMCal Embed: Fix pythia scaling

- PWG/FLOW/Base/AliFlowAnalysisCRC.cxx
- PWG/FLOW/Base/AliFlowAnalysisCRC.h
add second iteration in Q-vector re-centering vs vtx, with two options:
1) same strategy as before (fits to vx and vy)
2) direct subctration to 3D plot (summing pos and neg magnet polarities)
> add a second iteration to ZDC Q-vector re-centering vs vtx

- PWG/FLOW/Base/AliFlowAnalysisCRC.cxx
- PWG/FLOW/Base/AliFlowAnalysisCRC.h
add TProfiles to store NUAs (both ZDCs and TPC) as a function of:
1) reference mutiplicity
2) total energy in the ZDCs (Ecom)
3) primary vertex position (vtx) vs Ecom
4) fraction of events in the run vs vtx
> extend correlations NUA

- PWGHF/vertexingHF/AliAnalysisTaskSEDStarSpectra.cxx
- PWGHF/vertexingHF/AliAnalysisTaskSEDStarSpectra.h
In this commit, the code is made usable with any amount of pt-bins in the cuts and fully responding to that. A change for the settings of the D0-mass window was needed to allow all possible pt-bin settings. 
Furthermore an optimization of the task is done in terms of replacing the time-consuming findhistogram method by a list of pointer pointing to the necessary histograms.
> Improvements in Dstar spectra task wrt faster run + usability for n-ptbins

- PWGPP/AliAnalysisTaskFilteredTree.cxx
- PWGPP/AliAnalysisTaskFilteredTree.h
- PWGPP/TPC/macros/comparePerformanceMaps.C
- PWGPP/TPC/macros/performanceFiltered.C
* add nearest ITSonly track
* Currently low efficiency TPC+ITS->ITS standalone . To be debugged
*  used for matching efficiency studies for primaries
* constrained track delta
*  matchin eff
* Reducing number of bins per histogram to stay below 4 GBy (memory leak in AliESDV0 fixed in AliRoot)
* In order to save memory in THn - residuals and co-variance matrix are scaled by sqrt(1+(k/p)**2)
* renomalizing deltas and covariance matrix histogram range needed can be reduced
* Adding matching flag histograms
* another default cuts - therefore one more loop over data
* Adding map  for projection of the last dimension for all Nd hitograms
> PWGPP-1,PWGPP-312 - Update performance parameterization code

- CMakeLists.txt
The ctest runs a series of load-libraries commands that are stored in the root history.
Since there are lots of libraries, the user history basically goes outside the buffer.
The patch disable the root history before loading the libraries.
> Disable root history when performing ctest

- PWGHF/vertexingHF/AliAnalysisTaskSEHFQA.cxx
The content of the 'TOF time' histogram, dedicated to Kaon studies, was filled with proton informations.
> Fix particle species hypothesis in TOF time histogram

- PWGGA/GammaConv/macros/AddTask_PHOSTender_PCMconfig.C
- Added boolean to AddTask_PHOSTender_PCMconfig.C to disable the nonlinearity correction from the PHOS group
- This bool must be set to kFALSE if a NL correction from AliCaloPhotonCuts.cxx should be applied
> PWGGA/GammaConv: Added switch to use external NonLinearity for PHOS

- PWG/FLOW/Base/AliFlowAnalysisCRC.cxx
- PWG/FLOW/Base/AliFlowAnalysisCRC.h
change TProfiles to store Q-vector components vs reference multiplicity:
finer binning in centrality (1%), run-by-run
> update ZDC Q-vector re-centering

- PWGHF/vertexingHF/charmFlow/AliAnalysisTaskHFv1.cxx
store directly even (uQA+uQC) and odd (uQA-uQC) components of v1:
higher signal expected --> better fits to inv.mass. distribution
> store separately even and odd components

- PWG/FLOW/Base/AliFlowAnalysisCRC.cxx
- PWG/FLOW/Base/AliFlowAnalysisCRC.h
store & subtract average reference multiplicity vs centrality (1%); to be used to do re-centering in wide centrality bins
> update reference multiplicity

- PWGDQ/dielectron/JPSI/AliDielectronSignalExt.cxx
- PWGDQ/dielectron/core/AliDielectronEventCuts.cxx
- PWGDQ/dielectron/core/AliDielectronEventCuts.h
- PWGDQ/dielectron/macrosJPSI/multiplicity13TeV/plotRel.C
- PWGDQ/dielectron/macrosJPSI/multiplicity13TeV/pythia8.C
The 1st commit should fix the issue of memory corruption when creating trees on the GRID. 
In the 2nd one I add the macros for the simulation of J/psi vs. multiplicity from pythia8.
In the 3rd one, the bin error in case of zero entries in a bin is set to the value of 0.5 * TMath::ChisquareQuantile(0.6827,2) in case of event mixing or trach rotation. For LS this was done already some time ago.
> Three commits

- PWGHF/vertexingHF/macros/HFPtSpectrumRaa.C
The bracket placement meant that the selection of the energy and centrality for p-Pb collisions when creating the AliHFSystErr object did not work correctly. It should be working now. I also added the option to select the BDT analysis.
> fix to allow correct energy and centrality selection 

- PWGGA/EMCALTasks/macros/AddTaskEMCALPhotonIsolation.C
The L1triggerName parameter is now named triggerName and allows to pass "MB" as argument. The output container naming process is simplified by implementing triggerName according to its value (with '\_Trigger\_').
> Modifying the L1triggerName parameter name and options + simplifying the container naming

- PWGCF/Correlations/DPhi/AliAnalysisTaskCorPIDTOFQA.cxx
- PWGCF/Correlations/DPhi/AliAnalysisTaskCorPIDTOFQA.h
KET scaling is added so that comparisons of deuteron correlations can better be made with hadron-hadron and proton-hadron correlations
> added transverse kinetic energy scaling

- PWGDQ/dielectron/core/AliDielectron.cxx
The previous sequence had the problem, that the QnNormalisation was set after the EventCuts were applied. Which caused VarCuts on the EventPlane not be applied correctly, if a normalisation is needed
> PWGDQ AliDielectron changed sequence for setting QnNormalisation

- PWGPP/CMakeLists.txt
- PWGPP/TOF/AddTOFAnalysisTaskCalibPass0.C
- PWGPP/TOF/AddTOFAnalysisTaskCalibTree.C
Tasks AliTOFAnalysisTaskCalibTree & AliTOFAnalysisTaskCalibPass0 had been migrated to AliPhysics after AliRoot/AliPhysics split, but AddTask macros were orphaned in AliRoot (& not added to any CMakeLists, so inaccessible from LEGO train system). This patch migrates the missing macros to where they should be.
> Migrate TOF calibration AddTasks from AliRoot to AliPhysics

- PWGGA/EMCALTasks/AliAnalysisTaskEMCALPhotonIsolation.cxx
The two isolation/UE methods PtIsoTrackOrthCones() and PtIsoTrackFullTPC() were using the TPC-only track container instead of the Hybrid one dedicated to analysis.
In addition, the track containers are now called by their name and no longer by their index (as recommended in the EMCal framework documentation).
> Fix in the analysis tracks type for OrthCones and FullTPC methods

- PWGLF/QATasks/AliAnalysisTaskQAMultistrange.cxx
The variables loaded in the histograms were not incremented in the loop over the generated particles. Fixed
> Generated cascade multiplicity plots bug fixed

- PWGDQ/reducedTree/AliAnalysisTaskReducedTreeMaker.cxx
- PWGDQ/reducedTree/AliReducedEventInfo.cxx
- PWGDQ/reducedTree/AliReducedEventInfo.h
- PWGDQ/reducedTree/AliReducedTrackInfo.cxx
- PWGDQ/reducedTree/AliReducedTrackInfo.h
In order to use KFParticle offline it is necessary to store the 
track parameters and covariance matrix for each electron track,
therefore these parameters are included in AliReducedTrackInfo,
besides the covariance matrix of the event vertex is needed to 
use the topological constraint of the KFParticle
> Additional info to do improved vertexing with KFParticle

- PWGDQ/dielectron/LMEE/AliAnalysisTaskMLTreeMaker.cxx
- PWGDQ/dielectron/LMEE/AliAnalysisTaskMLTreeMaker.h
- PWGDQ/dielectron/macrosLMEE/AddTaskMLTreeMaker.C
- MLtreemaker now uses AliDielectron cut classes to be consistent with nanoAOD cuts
- vertex positions are now also written to tree for no MC events
- chi2Global was replaced by chi2GlobalPerNDF
treemaker cuts and nanoAOD filter cuts were checked to be consistent
> MLtreemaker update

- PWGHF/vertexingHF/macros/ComputeAcceptance.C
- Add D meson pt-shapes as obtained from FONLL and PYTHIA at 13 TeV. They have been added as histograms (TH1D) instead of function (TF1) since no fit functions have been found to efficiently match the low- and high-pt part of the spectra.
- Increase the number of point of TF1 to make sure that the sharp peak region is well described (as advised in TF1::GetRandom).
- Avoid new/delete of the TLorentzVector inside the loop to speed-up the task
> Add 13 TeV pt-shape histograms to the toy MC

- PWGCF/FEMTOSCOPY/AliFemto/AliFemtoEventReaderAOD.cxx
- PWGCF/FEMTOSCOPY/AliFemto/AliFemtoXi.cxx
- PWGCF/FEMTOSCOPY/AliFemto/AliFemtoXi.h
- PWGCF/FEMTOSCOPY/AliFemto/AliFemtoXiTrackCut.cxx
- PWGCF/FEMTOSCOPY/AliFemto/AliFemtoXiTrackCut.h
- PWGCF/FEMTOSCOPY/AliFemtoUser/AliFemtoAnalysisLambdaKaon.cxx
- PWGCF/FEMTOSCOPY/AliFemtoUser/AliFemtoAnalysisLambdaKaon.h
- PWGCF/FEMTOSCOPY/AliFemtoUser/AliFemtoXiTrackCutNSigmaFilter.cxx
PWGCF: AliFemtoEventReaderAOD: Included method to set fRadiusXi in AliFemtoXi class (fiducial volume radius, parallels fRadiusV0 in AliFemtoV0 class).  Also added attributes/methods in AliFemtoXi and AliFemtoXiTrackCut classes to handle this new information.
> PWGCF: AliFemtoEventReaderAOD: Included method to set fRadiusXi in AliFemtoXi 

- PWGGA/GammaConv/AliCaloPhotonCuts.cxx
- PWGGA/GammaConv/AliConvEventCuts.cxx
- PWGGA/GammaConv/AliConvEventCuts.h
- PWGGA/GammaConv/AliConversionCuts.cxx
- PWGGA/GammaConv/AliConversionMesonCuts.cxx
- PWGGA/GammaConv/AliConversionPhotonCuts.cxx
- PWGGA/GammaConv/AliDalitzElectronCuts.cxx
- PWGGA/GammaConv/AliPrimaryPionCuts.cxx
- PWGGA/GammaConv/AliV0CutsStrange.cxx
initializers are now able to handle alphanumeric characters, i.e. usual digits 0-9 and characters a-z, which are translated into digits 10-35
> PWGGA/GammaConv: adapted cut string initializers for use of alphanumeric

- PWG/EMCAL/EMCALtasks/AliEmcalCorrectionClusterHadronicCorrection.cxx
- PWG/EMCAL/EMCALtasks/AliEmcalCorrectionClusterTrackMatcher.cxx
- PWG/EMCAL/EMCALtasks/AliEmcalCorrectionClusterizer.cxx
- PWG/EMCAL/EMCALtasks/AliEmcalCorrectionClusterizer.h
- PWG/EMCAL/EMCALtasks/AliEmcalCorrectionTask.cxx
- PWG/EMCAL/EMCALtasks/AliHadCorrTask.cxx
- PWG/EMCAL/config/AliEmcalCorrectionConfiguration.yaml
Fixes include:
- Standardize embedding options in the EMCal Correction Framework
- Fix old typos
- Resolve TRefArray errors in cluster-track matcher
See the commits for further information.
Also includes:
- Removing obsolete code to avoid confusion
> EMCal CorrFW + Embed: Various small fixes

- PWGCF/EBYE/Fluctuations/AliEbyEPidEfficiencyContamination.cxx
Total momentum cut imposed, rapidity cut removed. This change (temporary) is made to compare results with Identity method.
> total momentum cut imposed, rapidity cut removed

- PWGDQ/dielectron/LMEE/AliAnalysisTaskSimpleTreeMaker.cxx
Number of accepted tracks did not agree with QA histogram value.
TPC clustering track cuts now applied before QA histogram kinematic cuts bin is filled!
> QA histogram bug fix

- PWGGA/EMCALTasks/AliAnalysisTaskEMCALPhotonIsolation.cxx
To compute an (in)efficiency for randomly rejecting neutral clusters I modified the filling of one histograms to have the distance "cluster-*closest* track" as a function of the transverse energy of the cluster.
> Modifying filling of one histogram

- PWGHF/vertexingHF/macros/ComputeAcceptance.C
The AliPhysics path was referring to the old path, before AliBuild.
> Update default AliPhysics path in the toy MC macro

- PWGHF/hfe/AliSelectNonHFE.cxx
- PWGHF/hfe/AliSelectNonHFE.h
Hi,
In order to use the new cuts in the p-Pb analysis I have made a small flag to disable ITS and TPC refit. I need this commit to be able to run trains for systematics. The change doesn't modify the default behaviour of the task (fRequireITSAndTPCRefit = kTRUE).  So unless you explicit request, no other user is affected. Since this is a common task, I would suggest that someone else that also use it review the changes. I am tagging some people that I know use the task @crisjahnke @deepathoms.
> Add possibility to disable ITS and TPC Refit

- PWGLF/FORWARD/analysis2/AliBaseMCTrackDensity.cxx
- PWGLF/FORWARD/analysis2/AliBaseMCTrackDensity.h
With embedded MC one should always use AliMCEvent rather than AliStack
> Use MCEvent instead of AliStack

- PWGHF/hfe/AliAnalysisTaskHFEpACorrelation.cxx
- PWGHF/hfe/macros/AddTaskHFEpACorrelation.C
The cuts are now only TPCOnlyTracks and |TPC Nsgima| < 3. There is also a small change in the AddTask to check the bin size effect.
> Remove strong tracks cuts on the partner

- PWGHF/vertexingHF/AliAODPidHF.cxx
- PWGPP/TPC/AliPerfAnalyzeInvPt.cxx
- PWGPP/TPC/AliPerfAnalyzeInvPt.h
Root6 expects reference to function f(double *, double*) that returns double.
> Fixes for TF1 in Root6

- PWGLF/STRANGENESS/Cascades/AliAnalysisTaskCheckCascadepp.cxx
- PWGLF/STRANGENESS/Cascades/AliAnalysisTaskCheckCascadepp.h
- PWGLF/STRANGENESS/Cascades/AliAnalysisTaskCheckPerformanceCascadepp.cxx
- PWGLF/STRANGENESS/Cascades/AliAnalysisTaskCheckPerformanceCascadepp.h
- PWGLF/STRANGENESS/Cascades/macros/AddTaskCheckCascadepp.C
- PWGLF/STRANGENESS/Cascades/macros/AddTaskCheckPerformanceCascadepp.C
The track quality selection based on TPC cluster has been changed from the simple request on on the number of TPC cluster (GetTPCNcls) to the double request:
— Number of TPC crossed Rows > 70
— TPC Crossed Rows / Findable Ratio > 0.8
> change cut on numb. TPC clusters

- PWGGA/EMCALTasks/AliAnalysisTaskEMCALPhotonIsolation.cxx
A major bug in the isolation/UE methods is here fixed. Clusters and tracks presumably belonging to the UE eta band were selected between eta boundaries instead of phi boundaries. This was already done correctly for tracks only methods (in TPC acceptance).
> Fix in the clusters/tracks selection for UE

- PWGGA/GammaConv/AliCaloPhotonCuts.cxx
- PWGGA/GammaConv/AliCaloPhotonCuts.h
- PWGGA/GammaConv/AliConvEventCuts.cxx
- PWGGA/GammaConv/AliConvEventCuts.h
- PWGGA/GammaConv/AliConversionCuts.cxx
- PWGGA/GammaConv/AliConversionCuts.h
- PWGGA/GammaConv/AliConversionMesonCuts.cxx
- PWGGA/GammaConv/AliConversionMesonCuts.h
- PWGGA/GammaConv/AliConversionPhotonCuts.cxx
- PWGGA/GammaConv/AliConversionPhotonCuts.h
- PWGGA/GammaConv/AliDalitzElectronCuts.cxx
- PWGGA/GammaConv/AliDalitzElectronCuts.h
- PWGGA/GammaConv/AliPrimaryPionCuts.cxx
- PWGGA/GammaConv/AliPrimaryPionCuts.h
- PWGGA/GammaConv/AliV0CutsStrange.cxx
- PWGGA/GammaConv/AliV0CutsStrange.h
the return of the cut strings was adapted (previously returned integer values for each cut and not letters of the original cut string)
> PWGGA/GammaConv: bugfix for updated cutstrings

- PWGGA/GammaConv/AliConvEventCuts.cxx
- PWGGA/GammaConv/AliConvEventCuts.h
-added enum lhc16rst to AliConvEventCuts
-added lhc16qt to new framework (AliMultSelection) 
-now centrality histogram should be filled properly for those periods
-use V0M instead of V0A to get centrality (not consistent for Run1 pPb )
--might be better to use p-Pb -> V0A and Pb-p -> V0C ?, think later.
> Get centrality for Run2 pPb

- PWGGA/CaloTrackCorrelations/AliAnaParticleIsolation.cxx
- PWGGA/CaloTrackCorrelations/AliAnaParticleIsolation.h
I've duplicate histograms of sum pT vs M02 to be able to compute the purity after there is a UE subtraction done in the isolation cone
> Add histograms needed to estimate the purity after ue subtraction

- PWGCF/Correlations/DPhi/AliAnalysisTaskCorPIDTOFQA.cxx
- PWGCF/Correlations/DPhi/AliAnalysisTaskCorPIDTOFQA.h
A small edit with about 10 lines of code altered.  Fixes a bug in the way deuteron KET was
calculated which allows easy and immediate comparison to other species.
> fixed bug in deuteron KET scaling

- PWGPP/ITS/AliAnalysisTaskSEImpParResSparse.cxx
- PWGPP/ITS/AliAnalysisTaskSEImpParResSparse.h
Adding 2 THnSparse for d0 pulls (in rphi and z) vs pt, phi, B, charge. Adding also the possibility to use reconstructed primary vertex when running with MC option enabled.
> Adding THnSparses and recovertex option for MC

- PWGCF/FEMTOSCOPY/AliFemto/AliFemtoModelWeightGenerator.h
- PWGCF/FEMTOSCOPY/AliFemto/AliFemtoModelWeightGeneratorBasic.cxx
- PWGCF/FEMTOSCOPY/AliFemto/AliFemtoModelWeightGeneratorBasic.h
This commit adds an internal flag `fPrintEmptyParticleNotification` to the AliFemtoModelWeightGenerator which, if false, will prevent printing a notification to stdout every time a weight is requested for a particle pair whose momentum/emergy/mass adds to zero (an "empty" pair).
This also adds and fixes some documentation and improves formatting of the files.
> PWGCF: AliFemtoModelWeightGenerator - Added flag & improved documentation

- PWGCF/FEMTOSCOPY/macros/Train/PionPionFemto/ConfigFemtoAnalysisRun2.C
- PWGCF/FEMTOSCOPY/macros/Train/PionPionFemto/ConfigMomentumResolutionAnalysis.C
AliFemtoWeightGeneratorBasic now will not print notifications about empty particle pairs.
> PWGCF: PionPionFemto macros - Used new option to quiet the WeightGenerator

- PWGDQ/dielectron/LMEE/AliAnalysisTaskSimpleTreeMaker.cxx
Debugging information was still being plotted into QA histogram. 
Now removed.
> Removed creation of MC debugging information

- PWGGA/GammaConv/AliCaloPhotonCuts.cxx
This pull request allows using the already determined nonlinearity correction from the pp 5 TeV pass3 Pythia8 Monte Carlo (LHC16k5a) on the new pass4 Monte Carlo (LHC17e2).
> PWGGA/GammaConv: Added pp 5 TeV pass3 nonlinearity to pass4 MC

- PWGGA/GammaConv/AliAnalysisTaskGammaPureMC.cxx
- PWGGA/GammaConv/AliAnalysisTaskGammaPureMC.h
- Acceptance check just return true or false depending on whether
particle is in the acceptance
- Ploton acceptance stored in bitmaps, comparisons replaced by TESTBITs
- PDG codes defied within enum, use constants defined there everywhere
in the code instead of PDG code numbers
> Make task a bit more readable

- PWGGA/EMCALTasks/AliAnalysisTaskEMCALPi0GammaCorr.cxx
- PWGGA/EMCALTasks/AliAnalysisTaskEMCALPi0GammaCorr.h
- PWGGA/EMCALTasks/macros/AddTaskEMCALPi0GammaCorr.C
adding  AliAnalysisTaskEMCALPi0GammaCorr. This code is based on previous EMCAL-based pi0 and gamma correlation analysis codes but it does uses THnSparse instead of multiple TH1s.
> adding AliAnalysisTaskEMCALPi0GammaCorr

- PWGGA/EMCALTasks/AliAnalysisTaskEMCALPhotonIsolation.cxx
- PWGGA/EMCALTasks/AliAnalysisTaskEMCALPhotonIsolation.h
- PWGGA/EMCALTasks/macros/AddTaskEMCALPhotonIsolation.C
In order to reduce the resource consumption, histograms which correspond to a given isolation/UE method are declared only if needed (i.e. when the isolation/UE method flag is set accordingly).
A new flag is introduced to further lighten the output: kFALSE by default, nothing changes.
> Adding a flag to lighten the task output

- PWGLF/SPECTRA/PiKaPr/TPCTOFfits/AliAnalysisTaskTPCTOFPID.cxx
- PWGLF/SPECTRA/PiKaPr/TPCTOFfits/AliAnalysisTaskTPCTOFPID.h
Added ITSTPC2011Sys cuts -- loose 2011 cuts for systematics estimation. Also, reduced gamma inv mass range even further (15 MeV) to reduce the size (1st commit) and added the missing ; (2nd commit)
> Adding trackcuts for systematics

- PWGGA/GammaConv/AliConversionPhotonCuts.cxx
- PWGGA/GammaConv/macros/AddTask_GammaConvV1_pp.C
- PWGGA/GammaConv/macros/AddTask_GammaConvV1_pp2.C
- PWGGA/GammaConv/macros/AddTask_MaterialHistos_pp.C
This pull request adds two new cutvariations in pseudorapidity as well as new configs in the GammaConv AddTasks.
A second part of this request is the addition of two configs for the Material Budget tasks that will be used for pileup crosschecks.
> PWGGA/GammaConv: Added new cut variations and configs for pp + configs for material task

- PWGGA/GammaConv/macros/Add_MCGenPythia8_TuneX.C
- Forward declaration of function CreatePythia8Gen missing,
therefore function was not found
- For yet unclear reason AliPythia8::Instance() and
new AliGenPythiaPlus ... must be executed in different
lines, otherwise it ends in "illegal instruction"
> Fixes needed for ROOT6

- PWGPP/MUON/lite/trigEffQA.C
A problem was encountered during the release validation.
Commits reverted:
* Order file list with increasing run number
* Improve protection for division by 0
* Allow to delay initialisation
* Zoom pad on double click
> MUON QA: revert changes since v5-09-08

- PWGHF/jetsHF/AliAnalysisTaskJetExtractorHF.cxx
For other generators than PYTHIA, it is possible to have less particles on the stacks than 8. This is now taken into account.
> Compatibility for parton type from stack for other generators than PYTHIA

- PWGDQ/dielectron/core/AliDielectronVarManager.h
Was only filled for ESDs. Is now also filled for AODs
> Added ITS shared cluster for AOD tracks

- PWG/MCLEGO/AMPT/gen_ampt.sh
- PWG/MCLEGO/AMPT/input.ampt
- gen_ampt.sh: runs AMPT and the ampt-to-hepmc parser
- input.ampt: AMPT input config file
note: the input.ampt file is the default file that is shipped with AMPT. this needs to be changed, but this initial commit is just for testing to see if everything runs
> add LEGO train scripts and config files to make stand alone AMPT available

- PWGUD/UPC/AliAnalysisTaskUpcEtaC.cxx
- PWGUD/UPC/AliAnalysisTaskUpcEtaC.h
EtaC decay channels to 3(Pi+Pi-) and to RhoRho(->Pi+Pi-Pi+Pi-)  final states. A typo in the K0s channel was fixed (vK0sKaon should have been vK0sPion). The ranges for some of histograms to test possible new PID methods were changed so the values would show up better.
> Added Rho0 & 3PiPi channels, K0s typo fixed, test PID histo ranges fixed

- PWGGA/EMCALTasks/AliAnalysisTaskEMCALPhotonIsolation.cxx
Each isolation/UE method now follows the same scheme for clusters and tracks while testing the position of the current cluster/track with respect to the cluster of interest.
Two different radii are introduced (radiusClust and radiusTrack) instead of the single radius variable.
A condition is added on the cluster position in order to skip clusters outside the considered acceptance.
Several missing initialisations are added and reordered for clarity.
> Homogenising the isolation/UE methods + fixing missing initialisations

- PWGDQ/dielectron/core/AliDielectronHF.cxx
Before the Ev1+Ev2- was not used with the enum, but should be used.
> PWGDQ HF ME added Ev1+Ev2- to kSeMeOSonly selection

- PWGPP/CalibMacros/CPass1/AddTOFAnalysisTaskCalibTree.C
- PWGPP/TOF/AliTOFAnalysisTaskCalibTree.cxx
- PWGPP/TOF/AliTOFAnalysisTaskCalibTree.h
Adds option to save the delta-X and delta-Z coordinates in a lighter version of the output tree (in discussion with @preghenella), for studies to check calibration as function of position of hit in the pad. Also fixes handling of streamed pointers/arrays in header/destructor, which will potentially help protect against possible memory leaks.
Mode to save coordinates (and therefore tree with some removed branches for optimisation) is handled by an added flag in the AddTask macro; default behaviour is unaffected.
> Implementation of hit coordinates in TOF calibration task

- PWGUD/UPC/AliAnalysisTaskUpcEtaC.cxx
- PWGUD/UPC/AliAnalysisTaskUpcEtaC.h
Increased the PID array sizes (fPIDTPCMuon[i], etc.) from i=4 to i=7 to make sure it can safely handle the 6 particle 3(Pi+Pi-) channel without a seg fault.
> Increased PID array size for 6 particle (3PiPi) channel

- PWGCF/Correlations/DPhi/AliAnalysisTaskCorPIDTOFQA.cxx
- PWGCF/Correlations/DPhi/AliAnalysisTaskCorPIDTOFQA.h
- PWGCF/Correlations/DPhi/AliAnalysisTaskCorPIDTOFdeut.cxx
- PWGCF/Correlations/DPhi/AliAnalysisTaskCorPIDTOFdeut.h
- PWGCF/Correlations/DPhi/AliAnalysisTaskCorPIDTOFhadr.cxx
- PWGCF/Correlations/DPhi/AliAnalysisTaskCorPIDTOFhadr.h
- PWGCF/Correlations/DPhi/AliAnalysisTaskCorPIDTOFprot.cxx
- PWGCF/Correlations/DPhi/AliAnalysisTaskCorPIDTOFprot.h
- PWGCF/Correlations/DPhi/CMakeLists.txt
- PWGCF/Correlations/DPhi/PWGCFCorrelationsDPhiLinkDef.h
- PWGCF/Correlations/macros/dphicorrelations/AddMyTaskCorPIDTOFdeut.C
- PWGCF/Correlations/macros/dphicorrelations/AddMyTaskCorPIDTOFhadr.C
- PWGCF/Correlations/macros/dphicorrelations/AddMyTaskCorPIDTOFprot.C
For improved efficiency, separate wagons will be used for different species.  At present these include deuterons, protons, and hadrons.
> correspondence analysis separated for identified deuteron, proton, and un-id hadron

- PWGGA/GammaConv/AliCaloPhotonCuts.cxx
- PWGGA/GammaConv/AliConversionPhotonCuts.cxx
- PWGGA/GammaConv/macros/AddTask_GammaConvV1_pp.C
- PWGGA/GammaConv/macros/AddTask_GammaConvV1_pp2.C
This pull request adds the first iteration of LHC17e2 nonlinearity parameters for the EMCal measurement. (PCM-EMCal parameters are not yet done)
In addition, three minimum photon pT cuts were introduced to AliConversionPhotonCuts.cxx to study the low pT behaviour of such cuts.
The cut variations are accompanied by a trainconfig in AddTask_GammaConvV1_pp.C.
> PWGGA/GammaConv: Added nonlin for EMC LHC17e2 and min gamma cut variations for PCM

- PWGGA/GammaConv/AliCaloPhotonCuts.h
- PWGGA/GammaConv/AliConvEventCuts.h
- PWGGA/GammaConv/AliConversionMesonCuts.h
- PWGGA/GammaConv/AliConversionPhotonCuts.h
- PWGGA/GammaConv/AliV0ReaderV1.cxx
- PWGGA/GammaConv/AliV0ReaderV1.h
2 commits:
- [Trivial] Remove "using namespace std" from several header files: The using directive is not needed within the header files and might lead to unwanted effects
- Add stl iterator for AliV0ReaderV1: This allows range-based iterations and stl algorithms (in case operator< and operator== will be defined). This commit just adds functions and does not modify existing ones.
- Make getter functions which do not modify objects const in AliV0ReaderV1: This is needed for the iterator commit as the iterator works on a const AliV0ReaderV1
> Hotfix namespacestd

- PWGHF/vertexingHF/AliHFSystErr.cxx
combine it with cut variation sys.unc, however, at 0-10%, only few bins has larger uncertainty on it(maximum 7%), at 60-80%, all within the uncertainty about cut variation
> update D0 sys.unc about improver task

- PWGGA/GammaConv/AliConversionCutHandler.cxx
- PWGGA/GammaConv/AliConversionCutHandler.h
- PWGGA/GammaConv/CMakeLists.txt
Factorize out the cut handler from the macro AddTask_GammaConvV1_pp.C
to a separate class so that it can be shared among various AddTasks.
> PWGGA/GammaConv: Factorize out CutHandlerConv to separate class

- PWG/EMCAL/EMCALbase/AliClusterContainer.cxx
- PWG/EMCAL/EMCALbase/AliClusterContainer.h
This behavior is needed for embedding for jet analyses.
Tested locally that default behavior is unchanged.
> add option to accept only phos clusters, and reject emcal clusters

- PWGGA/GammaConv/AliConvEventCuts.cxx
- PWGGA/GammaConv/AliConvEventCuts.h
- PWGGA/GammaConv/doxymodules.h
Add doxygen class header with description of cut observables.
This will help the users to decode the cut string, allthough description
of the value to be set for a given cut is still missing.
In addition:
- Create doxygen group for GammaConv
- Move existing member declarations to doxygen
> PWGGA/GammaConv: Simple doxygenize

- PWG/EMCAL/EMCALtasks/AliEmcalCorrectionClusterizer.cxx
In the clusterizer, recalculations for shower shape and distance to bad channels currently loops through all caloClusters, not just EMCal clusters. For some users this causes a crash. For those users for which the code does not crash, the corrections for EMCal clusters work as expected (but PHOS clusters could be affected). This commit ensures that these calibrations are only performed on EMCal clusters.
@raymondEhlers @efranzis
> ensure clusterizer only calibrates EMCal clusters

- PWGJE/EMCALJetTasks/UserTasks/AliAnalysisTaskJetUEStudies.cxx
root6 does not globally import namespace std.
std:: needs to be added in order to compile.
> Add missing std::

- PWGDQ/dielectron/core/AliDielectronVarManager.h
The Qn variables were not set to -999 as default in all cases, now for AODs they are set to this default value, if a QnManager exists. For NanoAODs they are only not set to -999 if there is no qnlist and neither kQnTPCrpH2 nor kQnV0rpH2 is required (to protect analyses not using the qnframework, from overhead).
> PWGDQ  VarManager QnEp secure default values -999

- PWGUD/UPC/AliAnalysisTaskUpcEtaC.cxx
- PWGUD/UPC/AliAnalysisTaskUpcEtaC.h
vPion[] and similar arrays, trackPt[] and similar arrays, fIsVertexContributor[], etc. were increased from 5 to 7. The loop for adding labels to fHistNeventsEtaC3PiPiChannel was decreased from 13 to 9. In the 3PiPi Channel for dealing with missing TOF PID info nPions == 3 was changed to nPions == 5 since this channel is a 6 particle final state.
> Fixed a few array sizes for 6 particle channel

- PWGGA/GammaConv/AliConversionPhotonCuts.cxx
- PWGGA/GammaConv/macros/AddTask_GammaConvV1_PbPb.C
The negation (==0) was supposed to fix a problem in the filling the ITS and TOF histograms. As far as I can see, it has instead the effect of rejecting almost everything (in PbPb). The filling problem will be further investigated.
> PWGGA/GammaConv: taken out negation from if for filling TOF/ITS histos

- PWGGA/GammaConv/AliConversionPhotonCuts.cxx
- PWGGA/GammaConv/AliConversionPhotonCuts.h
- PWGGA/GammaConv/macros/AddTask_GammaConvV1_pp.C
- PWGGA/GammaConv/macros/AddTask_GammaConvV1_pp2.C
This pull request adds several new pT cut variations on the electron and photon level in AliConversionPhotonCuts.cxx.
For running and testing of these variations, several trainconfigs have been added.
> PWGGA/GammaConv: Added more pT cut variations and trainconfigs for PCM 7 and 8 TeV

- PWGDQ/dielectron/core/AliDielectronHF.cxx
- PWGDQ/dielectron/macrosJPSI/AddTask_pdill_JPsi.C
If one runs on MC but did not add DielectronMCsignals the AliDielectronHF::Init() ended in a seg fault. Now an AliFatal is called giving a useful message where the error comes from.
> PWGDQ safety check for HF-Framework and MC analysis

- PWGHF/vertexingHF/AliHFSystErr.cxx
New PID systematics:
* 2% between 2 and 12 GeV/c (StrongPID)
* 0% between 12 and 24 GeV/c (ConservativePID)
Smoothening of [8-12] cut variation systematics
Note: the normalisation syst. is set to 3.7% as for D* and D0 w/o vertexing, while it set to 2% for D+ and D0 standard.
> Update Ds systematics (PID + Cut variations)

- PWGGA/GammaConv/AliV0ReaderV1.cxx
operator!= was implemented as operator==, leading
to a crash in case no photon was reconstructed, and
to a misbehaving otherwise.
> PWGGA/GammaConv: Fix operator!=

- PWGDQ/dielectron/core/AliDielectronVarManager.h
Shared cluster variable was not filled for AODs now it is.
> PWGDQ VarManager added ITSsharedClsFraction for AODs

- PWGGA/GammaConv/AliAnalysisTaskGammaPureMC.cxx
- PWGGA/GammaConv/AliAnalysisTaskK0toPi0Pi0.cxx
- PWGGA/GammaConv/AliAnalysisTaskK0toPi0Pi0.h
- PWGGA/GammaConv/AliCaloPhotonCuts.cxx
- PWGGA/GammaConv/AliCaloPhotonCuts.h
- PWGGA/GammaConv/AliConvEventCuts.h
- PWGGA/GammaConv/AliConversionPhotonCuts.h
- PWGGA/GammaConv/CMakeLists.txt
- PWGGA/GammaConv/PWGGAGammaConvLinkDef.h
- PWGGA/GammaConv/macros/AddTask_K0toPi0Pi0.C
-Doing conversion and calo photon selection.
-Building Pi0 candidates for all three methods separately.
-K0 candidates still disabled.
-Task configured with loose cuts for the V0 reader and default event gamma conv and calo cuts for 2012 pp.
-Adding new class in the build.
> PWGGA/GammaConv: Add task for K0 to two Pi0s.

- PWGCF/Correlations/DPhi/AliAnalysisTaskCorPIDTOFQA.cxx
- PWGCF/Correlations/DPhi/AliAnalysisTaskCorPIDTOFQA.h
this code compares events with both a high-pt track and deuteron, to events with a high-pt track and proton, and high-pt track and unidentified hadron.  Two thresholds are used for the high-pt trigger: 5, 10 GeV/c.
> reverse correspondance process with high-pt trig and IDparticle associate

- PWGPP/scripts/test/utilities.test.sh
- PWGPP/scripts/utilities.sh
* patch utilities.sh:parseConfig
* add test/utilities.test.sh:test_parseConfig
```
( source $AliPhysics_SRC/PWGPP/scripts/test/utilities.test.sh; test_parseConfig)
[2017-07-07 07:00:06 CEST] [lxbk0198] [INFO] test_parseConfig.Begin
[2017-07-07 07:00:06 CEST] [lxbk0198] [INFO] test_parseConfig parseConfig -v 1 -s 100 -q xxx  -testInput highPt -prefetch 1 test.root
[2017-07-07 07:00:06 CEST] [lxbk0198] [SUCCESS] -v= 1 = 1
[2017-07-07 07:00:06 CEST] [lxbk0198] [SUCCESS] -s= 100 = 100
[2017-07-07 07:00:06 CEST] [lxbk0198] [SUCCESS] testInput=highPt
[2017-07-07 07:00:06 CEST] [lxbk0198] [INFO] test_parseConfig.End
```
> PWGPP-350 - allow POSIX option parsing

- PWGHF/hfe/AliAnalysisTaskHFEpACorrelation.cxx
I am increasing the event mixing statistics to reduce the statistical errors at large delta eta bins.
> Increase Event Mixing statistics

- PWGHF/jetsHF/AliAnalysisTaskHFJetIPQA.cxx
- PWGHF/jetsHF/AliAnalysisTaskHFJetIPQA.h
- PWGHF/jetsHF/macros/AddTaskHFJetIPQA.C
- Updated pt hard  weights for LHC15g6c/d/e 
- Reintroduced jet probability functionality and tagging at JetProbability = 0.5/0.6/0.7/0.8/0.9/0.95
- Reintroduced jet pt histograms for efficiency calculation no-tag + jp-tagged
> UpdatedPtHardWeights and JetProbability functions

- PWGGA/EMCALTasks/AliAnalysisTaskEMCALPhotonIsolation.cxx
- PWGGA/EMCALTasks/AliAnalysisTaskEMCALPhotonIsolation.h
This reverts commit 09077e43c600e18e7e05ba832ead08e36b4b77ce which was faulty for multiple histograms. Looking for another way to implement the inclusive track pT spectrum.
> Revert "Adding a histogram for inclusive track pT spectrum"

- PWGGA/GammaConv/AliAnalysisTaskK0toPi0Pi0.cxx
Copy/Paste error in iteration over second leg: Instead
of calling operator ++ and != on the iterator over the
second leg it was done on the first leg, leading to
undefined behaviour.
> PWGGA/GammaConf: Fix in iterator over second leg

- PWGJE/EMCALJetTasks/Tracks/AliAnalysisTaskEmcalTriggerJets.cxx
- PWGJE/EMCALJetTasks/Tracks/AliAnalysisTaskEmcalTriggerJets.h
PID histograms are usually sparsely filled, so THnSparses are
more appropriate in order to reduce the memory consumption, in
particular when having a large amount of histograms.
> Change PID histograms to THnSpare

- PWGCF/Correlations/C2/AliAnalysisC2Settings.cxx
- PWGCF/Correlations/C2/AliAnalysisC2Settings.h
- PWGCF/Correlations/C2/AliAnalysisTaskC2.cxx
- PWGCF/Correlations/C2/AliAnalysisTaskValidation.cxx
This reduces the number of times the bin indices have to be calculated for the pair histogram, which is a very costly operation. Also, this PR enables the usage of the V0 for cross checks
> Fill by index and v0

- PWGDQ/dielectron/core/AliDielectronHelper.cxx
- PWGDQ/dielectron/core/AliDielectronVarManager.cxx
- PWGDQ/dielectron/core/AliDielectronVarManager.h
Excluded the usage of AliDielectronVarCuts from AliDielectronHelper::GetITSTPCMatchEff to solve the issues that the required-map (AliDielectronVarManager::fgFillMap) got lost due to the destruction of the VarCuts object.
Additionally added the new variable counting TPC tracks with kITSout (filled since AliRoot 7310)
> PWGDQ AliDielectronHelper fixed GetITSTPCMatchEff

- PWG/CALO/AliCaloNonLinearity.cxx
- PWG/CALO/AliCaloNonLinearity.h
In order to reduce the computation time of the energy correction, the string comparison to obtain the period enum is removed. Instead the GetCorrectedEnergy function now directly gets the enum as input parameter.
> PWG/CALO: changed GetCorrectedEnergy last argument to period enum

- PWGGA/GammaConv/AliAnalysisTaskK0toPi0Pi0.cxx
- Separate histograms for event quality (v0 reader) and
event cuts (task)
- Reject also events with non-0 event quality
> PWGGA/GammaConv: More monitoring and fix in event selection

- PWGGA/GammaConv/macros/AddTask_K0toPi0Pi0.C
Setting energy cut to 0 in order to run with strongly relaxed tender
settings (300 MeV/50 MeV).
> PWGGA/GammaConv: Setting cluster energy cut to 0

- PWGHF/jetsHF/AliAnalysisTaskEmcalJetBtagSV.cxx
- PWGHF/jetsHF/AliAnalysisTaskEmcalJetBtagSV.h
- PWGHF/jetsHF/AliHFJetsContainer.cxx
- PWGHF/jetsHF/AliHFJetsContainer.h
- PWGHF/jetsHF/AliHFJetsContainerVertex.cxx
- PWGHF/jetsHF/AliHFJetsContainerVertex.h
- PWGHF/jetsHF/macros/AddTaskEmcalJetBtagSV.C
1) Replaced the dummy kCFmult field in the tagged jet container with kCFcent, and fill this from the BJet tagging class with ZNA multiplicy percentile as centrality estimator.
2) Added a simple random cone method to estimate the background fluctuation (deltaPt). Created corresponding histo to fill. Incluced a switch into the class definition and also a switch 
Bool_t doRndmCone =  kFALSE into the macros/AddTaskEmcalJetBtagSV.C.
> DeltaPT and centrality added

- PWG/FLOW/Base/AliFlowAnalysisCRC.cxx
- PWG/FLOW/Base/AliFlowAnalysisCRC.h
various updates:
1) fix bug in ZDC Qvec cut (ZNA Q-vector saved with flipped x-component)
2) add tprofiles for cn{4} vs primary vertex position
3) reduce bin number of various histograms to reduce memory consumption
> bug fix in ZDC Qvec distribution cut

- PWGGA/GammaConv/macros/AddTask_GammaCocktailMC.C
- PWGGA/GammaConv/macros/AddTask_HadronicCocktailMC.C
The rapidity string that is given as argument to the AddTasks must now be for example "80" instead of "0.8" as the rapidity gets divided by 100 in the task itself. This allows us to use the subwagon feature on the grid.
> PWGGA/GammaConv: Added cocktail task subwagon feature via division of rapidity

- PWGCF/FEMTOSCOPY/AliFemto/AliFemtoEventReaderAOD.cxx
- PWGCF/FEMTOSCOPY/AliFemto/AliFemtoTrack.cxx
- PWGCF/FEMTOSCOPY/AliFemto/AliFemtoTrack.h
- PWGCF/FEMTOSCOPY/AliFemto/AliFemtoV0.cxx
- PWGCF/FEMTOSCOPY/AliFemto/AliFemtoV0.h
- PWGCF/FEMTOSCOPY/AliFemtoUser/AliFemtoCorrFctnDEtaDPhiTHn.cxx
- PWGCF/FEMTOSCOPY/AliFemtoUser/AliFemtoCorrFctnDEtaDPhiTHn.h
- PWGCF/FEMTOSCOPY/AliFemtoUser/CMakeLists.txt
- PWGCF/FEMTOSCOPY/AliFemtoUser/PWGCFfemtoscopyUserLinkDef.h
- PWGCF/FEMTOSCOPY/macros/Train/DEtaDPhi/2017/THn/NoCorr/ConfigFemtoAnalysis.C
New correlation function in AliFemto, which calculates deta-dphi using 6D histograms S(deta,dphi,pT1,pT2,centrality,z-vtx) + B(deta,dphi,pT1,pT2,centrality,z-vtx) and Ntrig histogram allowing to applying different normalization.
Works for AOD only (for now).
> DEtaDPhi: Change of corr. fun. calculation, use of THn histograms

- PWGGA/GammaConv/AliCaloPhotonCuts.cxx
The updated nonlinearity parameters for LHC16k5a and LHC17e2 were obtained using both MonteCarlos merged and comparing them to the pass4 data.
> PWGGA/GammaConv: pp 5 TeV nonlinearity parameter update

- PWGCF/FEMTOSCOPY/AliFemtoUser/AliFemtoCorrFctnDEtaDPhiTHn.cxx
New correlation function in AliFemto, which calculates deta-dphi using 6D histograms S(deta,dphi,pT1,pT2,centrality,z-vtx) + B(deta,dphi,pT1,pT2,centrality,z-vtx) and Ntrig histogram allowing to applying different normalization.
Works for AOD only (for now).
> Fix of double/int conversion

- PWGHF/vertexingHF/AliAnalysisTaskSELc2V0bachelor.cxx
- PWGHF/vertexingHF/AliAnalysisTaskSELc2V0bachelor.h
- PWGHF/vertexingHF/AliRDHFCutsLctoV0.cxx
- PWGHF/vertexingHF/AliRDHFCutsLctoV0.h
- PWGHF/vertexingHF/ConfigVertexingHF.C
- PWGHF/vertexingHF/ConfigVertexingHF_DplustoK0s_DstoK0s.C
- PWGHF/vertexingHF/ConfigVertexingHF_Pb_AllCent.C
- PWGHF/vertexingHF/ConfigVertexingHF_Pb_AllCent_NoLS.C
- PWGHF/vertexingHF/ConfigVertexingHF_Pb_AllCent_NoLS_16var.C
- PWGHF/vertexingHF/ConfigVertexingHF_Pb_AllCent_NoLS_NoDstar.C
- PWGHF/vertexingHF/ConfigVertexingHF_Pb_AllCent_NoLS_NoDstar_16var.C
- PWGHF/vertexingHF/ConfigVertexingHF_Pb_AllCent_NoLS_PIDLc.C
- PWGHF/vertexingHF/ConfigVertexingHF_Pb_AllCent_NoLS_PIDLc_PtDepSel_LooseIP.C
- PWGHF/vertexingHF/ConfigVertexingHF_Pb_AllCent_NoLS_PIDLc_PtDepSel_LooseIP_Central.C
- PWGHF/vertexingHF/ConfigVertexingHF_Pb_AllCent_NoLS_PIDLc_PtDepSel_LooseIP_SemiCentral.C
- PWGHF/vertexingHF/ConfigVertexingHF_Pb_Cent2080.C
- PWGHF/vertexingHF/ConfigVertexingHF_TrackRel.C
- PWGHF/vertexingHF/ConfigVertexingHF_highmult.C
- PWGHF/vertexingHF/ConfigVertexingHF_pPb.C
- PWGHF/vertexingHF/ConfigVertexingHF_pPbRHF.C
- PWGHF/vertexingHF/ConfigVertexingHF_pPbRHF_DplustoK0s_DstoK0s.C
- PWGHF/vertexingHF/ConfigVertexingHF_pp_LambdaC.C
- PWGHF/vertexingHF/macros/makeTFile4CutsLctoV0bachelor.C
Dear all,
I made the following modifications to the codes to analyze Lc->pK0s in PbPb. 
I contacted the original authors (Annalisa,Elisa) of the codes and they agreed that I make modifications to the codes.  
AliRDHFCutsLctoV0.cxx(h)
- Added 4 variables to the array of cut variables
- If the cut values are not in reasonable ranges, the cuts are not applied at all. This is intended to avoid any impacts on the past analyses.
- Added functions to calculate the variables
- Added one more option for PID
makeTFile4CutsLctoV0bachelor.C
- Added the 4 variables accordingly
AliAnalysisTaskSELc2V0bachelor.cxx(h)
- Added AOD protection against AOD-dAOD mismatch
- Added histograms for the variables
ConfigVertexingHF_****.C
- The number of cut variables and the cut arrays are updated accordingly. 
Best …
> Lc2V0 bachelor code updates for PbPb

- PWGGA/EMCALTasks/AliAnalysisTaskEMCALPhotonIsolation.cxx
- PWGGA/EMCALTasks/AliAnalysisTaskEMCALPhotonIsolation.h
This histogram will be used to study the cluster shower shape per supermodule, integrated over the whole cluster energy range for now (could be detailed per energy bin later).
> Adding a histogram to study the cluster shower shape per SM

- PWGGA/EMCALTasks/AliAnalysisTaskEMCALPhotonIsolation.cxx
- PWGGA/EMCALTasks/AliAnalysisTaskEMCALPhotonIsolation.h
- PWGGA/EMCALTasks/macros/AddTaskEMCALPhotonIsolation.C
This commit adds the possibility to set a fiducial cut which is different than the isolation cone radius (`fIsoConeRadius`). By default, it is set at the same value than `fIsoConeRadius`, i.e. 0.4.
> Adding a parameter for a variable fiducial cut

- PWGCF/FEMTOSCOPY/AliFemtoUser/AliFemtoCorrFctnDEtaDPhiTHn.cxx
- PWGCF/FEMTOSCOPY/AliFemtoUser/AliFemtoCorrFctnDEtaDPhiTHn.h
- PWGCF/FEMTOSCOPY/AliFemtoUser/AliFemtoCutMonitorParticleNumber.cxx
- PWGCF/FEMTOSCOPY/AliFemtoUser/AliFemtoCutMonitorParticleNumber.h
- PWGCF/FEMTOSCOPY/AliFemtoUser/CMakeLists.txt
- PWGCF/FEMTOSCOPY/AliFemtoUser/PWGCFfemtoscopyUserLinkDef.h
- PWGCF/FEMTOSCOPY/macros/Train/DEtaDPhi/2017/THn/NoCorr/ConfigFemtoAnalysis.C
New correlation function in AliFemto, which calculates deta-dphi using 6D histograms S(deta,dphi,pT1,pT2,centrality,z-vtx) + B(deta,dphi,pT1,pT2,centrality,z-vtx) and Ntrig histogram allowing to applying different normalization.
Works for AOD only (for now).
Update of calculation of Ntrig histogram.
> AliFemto: update for Ntrig calculation in DEtaDPhi

- PWGHF/vertexingHF/AliAnalysisTaskSELc2V0bachelor.cxx
- PWGHF/vertexingHF/AliRDHFCutsLctoV0.cxx
- PWGHF/vertexingHF/AliRDHFCutsLctoV0.h
Dear all,
The calculation of the proton emission angle was performed in the Lc rest frame, but it is changed to the pK0s pair rest frame. The old method assumes the mass of Lc even when the pair has an invariant mass far away from the Lc peak. 
Best regards,
Yosuke
> Updates of CosThetaStar for Lc->pK0s analysis

- PWGDQ/dielectron/core/AliDielectronMC.cxx
- PWGDQ/dielectron/core/AliDielectronMC.h
- PWGDQ/dielectron/core/AliDielectronVarManager.cxx
- PWGDQ/dielectron/core/AliDielectronVarManager.h
The handling of AOD MC in the dielectron framework is tricky. Up to now the tracks are compared via their label on the stack. This is not working for AODs therefore a few changes are made. The handling for ESDs is unaffected by this patch.
> PWGDQ: Changed handling for AOD MC

- PWGJE/EMCALJetTasks/Tracks/AliAnalysisTaskEmcalJetSubstructureTree.cxx
- PWGJE/EMCALJetTasks/Tracks/AliAnalysisTaskEmcalJetSubstructureTree.h
Output from the task has shown to be unreadable offline with
conventional tools. Therefore
- Write jet tree to separate file
- Replace output struct with array, split to separate branches per entry
> Different output handling for jet tree

- PWGDQ/reducedTree/AliReducedAnalysisJpsi2ee.cxx
Bugfix: Keep all JPsi on the reconstructed MC level to be consistent with generated level
> Fix: Don't reject B to JPsi in MC

- PWGHF/vertexingHF/AliAnalysisTaskSEImproveITS.cxx
- PWGHF/vertexingHF/AliAnalysisTaskSEImproveITS.h
FillRecoCand called before the smearing of the track parameters. Possibility enable/disable the update of the cov matrix also for PbPb (F. Prino)
> Enable/disable the update of the cov matrix also for PbPb (F. Prino)

- PWGGA/GammaConv/AliGammaConversionAODBGHandler.cxx
The array fBGProbability in AliGammaConversionAODBGHandler was filled without considering the range of the array. A lookup array was created to avoid segfaults.
> fixed filling of fBGProbability in AliGammaConversionAODBGHandler

- OADB/AliPhysicsSelection.cxx
- OADB/AliPhysicsSelection.h
Fixes issues with #1897.
No changes in logic, just standard TPRegexp for regular expressions instead of custom pcre wrapper.
> TPRegexp instead of PCREWrap in AliPhysicsSelection

- PWGDQ/dielectron/core/AliAnalysisTaskElectronEfficiency.cxx
- PWGDQ/dielectron/core/AliAnalysisTaskElectronEfficiency.h
- PWGDQ/dielectron/core/AliDielectronVarManager.h
- PWGDQ/dielectron/macrosLMEE/AddTask_caklein_ElectronEfficiency.C
There is now the option to reject TOF mismatch when computing the efficiency with the AliAnalysisTaskElectronEfficiency task.
Addition of ITS dEdx and shared cluster map for every ITS layer in VarManager.h
Cheers
Carsten
> PWGDQ: Added TOFmismatch calculation in efficiency task + ITS related variables in VarManager

- PWGCF/Correlations/JCORRAN/Pro/AliJJetJtAnalysis.cxx
- PWGCF/Correlations/JCORRAN/Pro/AliJJetJtAnalysis.h
- PWGCF/Correlations/JCORRAN/Pro/AliJJetJtTask.cxx
- PWGCF/Correlations/JCORRAN/Pro/AliJJetJtTask.h
- PWGCF/Correlations/JCORRAN/Pro/AliJJetTask.cxx
- PWGCF/Correlations/macros/jcorran/cardAlice_pp.input
-Fix bug that caused crashes on pp trains, missing AliAnalysisUtils
-Fix bug where dijet mass response matrix would be tried to access for data events and not only for MC
-Leading track jT now finds the correct leading track of jet
-Disable histograms with log(jT) binning by default and add option to enable them
> Bug fixes and updates to AliJJetJtAnalysis

- PWGUD/UPC/AliAnalysisTaskUpcEtaC.cxx
- PWGUD/UPC/AliAnalysisTaskUpcEtaC.h
All K0short channel using V0s, the 2Rho, 4Pion, and 6Pion channel code is gone from this version except creating the histograms for the K0short channel. This version is simply to look at the K0s channel without using V0s.
> Temporary version for K0short channel without using V0s

- PWGPP/EMCAL/TiCMacros/MakeReferenceFinalPass.C
- PWGPP/EMCAL/TiCMacros/MakeReferencePass1.C
- PWGPP/EMCAL/TiCMacros/MakeReferenceSM.C
- PWGPP/EMCAL/TiCMacros/copyFiles.sh
- PWGPP/EMCAL/doxymodules.h
Changes: 
- doxymodules.h - added 4 macros
- copyFiles.sh - to copy files from LEGO train
- MakeReferencePass1.C - to make input for L1 phase calculation for each run
- MakeReferenceSM.C - to calculate L1 phases
- MakeReferenceFinalPass.C - to calculate time offsets in 2nd and 3rd step
> EMCal Time calibration macros

- PWGDQ/dielectron/core/AliDielectronHelper.cxx
- PWGDQ/dielectron/core/AliDielectronHelper.h
- PWGDQ/dielectron/core/AliDielectronQnEPcorrection.cxx
- PWGDQ/dielectron/core/AliDielectronVarManager.cxx
- PWGDQ/dielectron/core/AliDielectronVarManager.h
Added the V0C as ep estimator for the in- and out of plane TPC-ITS matching efficiency calculation. Small fix and optimisation for the ac removal in the flow calculation part.
> PWGDQ ITS TPC match eff + ep part optimisation

- PWGCF/Correlations/DPhi/AliAnalysisTaskCorPIDTOFdiprot.cxx
high-pt trigger tracks have their TOF requirement removed for more uniform phi acceptance.
> removed TOF requirement for high-pt trigger

- PWGJE/EMCALJetTasks/Tracks/AliAnalysisTaskEmcalJetSubstructureTree.cxx
- TPC acceptance in case the task runs purely with MC-true information
(maily of relevance for the MCgen trains)
- EMCAL fiducial acceptance in case both reconstructed and true information
are used (regular MC LEGO trains, on normal productions)
> Optimize acceptance for particle level jets

- PWG/EMCAL/EMCALbase/AliEmcalContainerIndexMap.h
Together with the -Werror of EMCal this fix is needed in case one turns on more warnings. The implementation has to follow the order of data members in the definition.
Hi EMCal! 
I turned on -Wall in AliPhysics [1] and compilation stops in the EMCal part. While I don't know yet how useful -Wall will be, it would be great to have the compilation succeed and see the warnings from the whole AliPhysics. Below [2] the warning, full log here: http://www.physi.uni-heidelberg.de/~hbeck/EMCalLog.txt
Cheers,
Hans
[1] Turned on -Wall like this:
```bash
diff --git a/CMakeLists.txt b/CMakeLists.txt
index 5551c18a8b..e566fc0cb0 100644
--- a/CMakeLists.txt
+++ b/CMakeLists.txt
@@ -136,6 +136,12 @@ else()
set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -std=c++14")
endif()
+  # Switch on warnings
+ …
```
> EMCal: Fix reorder warning in AliEmcalContainerIndexMap.h

- PWGGA/GammaConv/macros/AddTask_GammaConvNeutralMesonPiPlPiMiPiZero_CaloMode_pPb.C
- PWGGA/GammaConv/macros/AddTask_GammaConvNeutralMesonPiPlPiMiPiZero_CaloMode_pp.C
- PWGGA/GammaConv/macros/AddTask_GammaConvNeutralMesonPiPlPiMiPiZero_ConvMode_pPb.C
- PWGGA/GammaConv/macros/AddTask_GammaConvNeutralMesonPiPlPiMiPiZero_ConvMode_pp.C
- PWGGA/GammaConv/macros/AddTask_GammaConvNeutralMesonPiPlPiMiPiZero_MixedMode_pPb.C
- PWGGA/GammaConv/macros/AddTask_GammaConvNeutralMesonPiPlPiMiPiZero_MixedMode_pp.C
- AddTasks of NeutralMesonToPiPlPiMiPiZero now hand the periodName to V0Reader to avoid crashes while running on MC on the grid
> PWGGA/GammaConv: fix in neutral meson analysis AddTask

- PWGCF/Correlations/C2/AliAnalysisTaskValidation.cxx
- PWGCF/Correlations/C2/AliAnalysisTaskValidation.h
A static function on this task replaces the AddTask macro. This help
keeping everything in one plasce and ensures a tight integration and
most importantly compile time checks! The latter is what one misses
out when using the ungodly .C macros.
> Use static function to set up task (instead of AddTask)

- PWGGA/GammaConv/AliAnalysisTaskNeutralMesonToPiPlPiMiPiZero.cxx
- changed Int_t to UInt_t when comparing with .size() in NeutralMesonPiPlPiMiPiZero task to avoid compilation warnings
> /PWGGA/GammaConv: changed Int_t to UInt_t in NeutralMeson task

- PWGLF/SPECTRA/PiKaPr/TPCTOFfits/AliAnalysisPIDEvent.cxx
- PWGLF/SPECTRA/PiKaPr/TPCTOFfits/AliAnalysisPIDTrack.cxx
- PWGLF/SPECTRA/PiKaPr/TPCTOFfits/AliAnalysisPIDTrack.h
- PWGLF/SPECTRA/PiKaPr/TPCTOFfits/AliAnalysisTaskTPCTOFPID.cxx
Added fChi2TPCConstrainedVsGlobal to AliAnalysisPIDTrack for primary selection (including getters and setters). Changed the default PIDEvent flag to 29.
> Adding Chi2TPCConstrainedVsGlobal to AliAnalysisPIDTrack

- PWG/EMCAL/EMCALbase/AliAnalysisTaskEmcalEmbeddingHelper.h
Hi @aaniin,
I think that this should fix the warnings that you noted in #2158. I tried compiling with -Wall and didn't see any issues with it, but I would appreciate it if you could confirm that it resolves them! Thanks for spotting them!
Best,
Raymond
> EMCal Embed: Fix warnings

- PWGHF/vertexingHF/AliAnalysisTaskSEDs.cxx
Fixed three logical mass window comparisons. The mathematical 0.1 < 0.2 < 0.3 does not translate into a c++ 0.1 < 0.2 < 0.3, which in a boolean usage like if(0.1<0.2<0.3) evaluates to false: 0.1<0.2 evaluates to a boolean true which turns into a 1. The final comparison 1<0.3 is not true. Triggered by compiling AliPhysics with -Wall.
> Fix parentheses AliAnalysisTaskSEDs

- PWG/EMCAL/EMCALtrigger/AliEmcalTriggerMaker.cxx
- PWG/EMCAL/EMCALtrigger/AliEmcalTriggerMakerTask.cxx
Fix double-initialization (aggregate + list-initilization)
for several initializations of std::array. Fixing last
leftovers from #2193
> Last round of warnings (found by clang)

- PWGCF/FEMTOSCOPY/AliFemtoUser/AliFemtoCutMonitorEventNumber.h
Typo in header guard, revealed by compiler warning
> Fix header guard in AliFemto

- PWGPP/EVCHAR/AliTrackletAlg.cxx
This changes behavior of the task! Code intends to compare doubles but integer abs is used.
```c++
/Users/hbeck/alice/alibuild/sw/SOURCES/AliPhysics/0/0/PWGPP/EVCHAR/AliTrackletAlg.cxx:1195:50: warning: 
using integer absolute value function 'abs' when argument is of floating
point type [-Wabsolute-value]
if (TMath::Abs(mass)>fCutMassK0 || (massErr>0&&(abs(mass)>massEr...
^
/Users/hbeck/alice/alibuild/sw/SOURCES/AliPhysics/0/0/PWGPP/EVCHAR/AliTrackletAlg.cxx:1195:50: note: 
use function 'std::abs' instead
if (TMath::Abs(mass)>fCutMassK0 || (massErr>0&&(abs(mass)>massEr...
^~~
std::abs
```
> Change integer abs -> TMath::Abs on double in AliTrackletAlg

- PWGPP/HMPID/AliHMPIDTaskQA.cxx
This changes the behavior of the task! Clearly, the code intends to compare doubles (explicit type) but the integer abs() is used.
> Fix abs -> TMath::Abs in AliHMPIDTaskQA

- PWGGA/PHOSTasks/CMakeLists.txt
- PWGGA/PHOSTasks/PHOS_Run2/AliAnalysisTaskPHOSObjectCreator.cxx
- PWGGA/PHOSTasks/PHOS_Run2/AliAnalysisTaskPHOSObjectCreator.h
- PWGGA/PHOSTasks/PHOS_Run2/AliAnalysisTaskPHOSPi0EtaToGammaGamma.cxx
- PWGGA/PHOSTasks/PHOS_Run2/AliAnalysisTaskPHOSPi0EtaToGammaGamma.h
- PWGGA/PHOSTasks/PHOS_Run2/AliPHOSClusterCuts.cxx
- PWGGA/PHOSTasks/PHOS_Run2/AliPHOSClusterCuts.h
- PWGGA/PHOSTasks/PHOS_Run2/AliPHOSEventCuts.cxx
- PWGGA/PHOSTasks/PHOS_Run2/AliPHOSEventCuts.h
- PWGGA/PHOSTasks/PHOS_Run2/AliPHOSJetJetMC.cxx
- PWGGA/PHOSTasks/PHOS_Run2/AliPHOSJetJetMC.h
- PWGGA/PHOSTasks/PHOS_Run2/AliPHOSTriggerHelper.cxx
- PWGGA/PHOSTasks/PHOS_Run2/AliPHOSTriggerHelper.h
- PWGGA/PHOSTasks/PHOS_Run2/macros/AddTaskPHOSObjectCreator.C
- PWGGA/PHOSTasks/PHOS_Run2/macros/AddTaskPHOSPi0EtaToGammaGamma.C
- PWGGA/PHOSTasks/PWGGAPHOSTasksLinkDef.h
Macros to analyze Run2 PHOS data are uploaded. These macros support pp/PbPb/pPb data.
An array which contains PHOS clusters is created by PHOSObjectCreator at first.
Then, this array is analyzed by Pi0EtaToGammaGamma.
Event selection is done by AliPHOSEventCuts, and clusters are selected by AliPHOSClusterCuts.
> add PHOS_Run2 macros

- PWGLF/RESONANCES/extra/AliRsnTOFT0maker.cxx
- PWGLF/RESONANCES/extra/AliRsnTOFT0maker.h
No longer valid ISO C++. Generates lots fo warnings since header is included in many places.
> Fix char* -> const char* in AliRsnTOFT0maker.h

- OADB/AliPhysicsSelection.cxx
Removed unused value in AliPhysicsSelection. The function used to obtain this value is const, thus the function call itself has also no effect.
@BerserkerTroll @cbourjau @ekryshen please look. This commit does not change behavior of the task, but the warning that some value is unused might also mean that one forgot to use it.
```c++
DEBUG:AliPhysics:0: /Users/hbeck/alice/alibuild/sw/SOURCES/AliPhysics/0/0/OADB/AliPhysicsSelection.cxx:466:15: warning: unused variable 'thresholdInner' [-Wunused-variable]
DEBUG:AliPhysics:0:         Int_t thresholdInner = tri->GetAlgoParamValueLI("0SH1",0); // algorithm name and param index 0
DEBUG:AliPhysics:0:               ^
```
Cheers,
Hans
> Removed unused value AliPhysicsSelection

- PWGDQ/reducedTree/AliAnalysisTaskReducedEventProcessor.cxx
- PWGDQ/reducedTree/AliAnalysisTaskReducedEventProcessor.h
- PWGDQ/reducedTree/AliAnalysisTaskReducedTreeMaker.cxx
- PWGDQ/reducedTree/AliReducedAnalysisFilterTrees.cxx
- PWGDQ/reducedTree/AliReducedAnalysisFilterTrees.h
- PWGDQ/reducedTree/AliReducedAnalysisJpsi2ee.cxx
- PWGDQ/reducedTree/AliReducedAnalysisJpsi2ee.h
- PWGDQ/reducedTree/AliReducedAnalysisTaskSE.cxx
- PWGDQ/reducedTree/AliReducedAnalysisTaskSE.h
- PWGDQ/reducedTree/AliReducedAnalysisTest.cxx
- PWGDQ/reducedTree/AliReducedBaseEvent.cxx
- PWGDQ/reducedTree/AliReducedBaseEvent.h
- PWGDQ/reducedTree/AliReducedBaseTrack.cxx
- PWGDQ/reducedTree/AliReducedBaseTrack.h
- PWGDQ/reducedTree/AliReducedEventInfo.cxx
- PWGDQ/reducedTree/AliReducedEventInfo.h
- PWGDQ/reducedTree/AliReducedPairInfo.cxx
- PWGDQ/reducedTree/AliReducedPairInfo.h
- PWGDQ/reducedTree/AliReducedTrackInfo.cxx
- PWGDQ/reducedTree/AliReducedTrackInfo.h
- PWGDQ/reducedTree/CMakeLists.txt
- PWGDQ/reducedTree/PWGDQreducedTreeLinkDef.h
1) AliReducedBaseTrack
* TrackID data member moved from the derived AliReducedTrackInfo to this class
2) AliReduceTrackInfo
* TrackID data member removed (see item 1)
* Implemented copy constructor
3) AliReducedPairInfo
* Added a few setters for data members
* Added const strings to define decay channel names
4) AliReducedBaseEvent
* Added method to copy event header from another event
* added a new friend class (AliReducedAnalysisFilterTrees)
5) AliReducedEventInfo
* Added method to copy event header from another event
* added a new friend class (AliReducedAnalysisFilterTrees)
6) AliAnalysisTaskReducedEventProcessor and AliReducedAnalysisTaskSE
* Implemented functionality to allow writing of a filtered event
7) AliReducedAnalysisJpsi2ee
* the event counter data member is droped as it was …
> Many changes, see below

- PWGGA/GammaConv/AliCaloPhotonCuts.cxx
Missing isMC>0 included for cases 17 and 27 to be able to also run it on data.
> PWGGA/GammaConv: Fix for running Nonlin case 17/27 on data

- PWG/FLOW/Tasks/AliAnalysisTaskPiKpK0Lamba.h
The data member flagPsi42A was never set by a call to SetFlagPsi42A
```c++
DEBUG:AliPhysics:0: In file included from /Users/hbeck/alice/alibuild/sw/SOURCES/AliPhysics/0/0/PWG/FLOW/Tasks/AliAnalysisTaskPiKpK0Lamba.cxx:1:
DEBUG:AliPhysics:0: /Users/hbeck/alice/alibuild/sw/SOURCES/AliPhysics/0/0/PWG/FLOW/Tasks/AliAnalysisTaskPiKpK0Lamba.h:64:67: warning: explicitly assigning value of variable of type 'Bool_t' (aka 'bool') to itself [-Wself-assign]
DEBUG:AliPhysics:0:         virtual void  SetFlagPsi42A(Bool_t flagPsi42A){flagPsi42A = flagPsi42A;}
DEBUG:AliPhysics:0:                                                        ~~~~~~~~~~ ^ ~~~~~~~~~~
```
Can be easily tested by a simple tst.C
```c++
#include <cstdio>
class A{
public:
A():B(0){};
void SetB(int B){B=B;} …
```
> Fix self assignment AliAnalysisTaskPiKpK0Lamba

- PWGLF/NUCLEX/Hypernuclei/Hyp2Body/AliAnalysisTaskHypTritEventTree.h
@strogolo what do you think?
```c++
/Users/hbeck/alice/alibuild/sw/SOURCES/AliPhysics/0/0/PWGLF/NUCLEX/Hypernuclei/Hyp2Body/AliAnalysisTaskHypTritEventTree.h:42:55: warning: 
variable 'i' is uninitialized when used here [-Wuninitialized]
void SetParamsHe(Double_t params[6]) { for(Int_t i; i < 6; i++) fBethe...
^
/Users/hbeck/alice/alibuild/sw/SOURCES/AliPhysics/0/0/PWGLF/NUCLEX/Hypernuclei/Hyp2Body/AliAnalysisTaskHypTritEventTree.h:42:53: note: 
initialize the variable 'i' to silence this warning
void SetParamsHe(Double_t params[6]) { for(Int_t i; i < 6; i++) fBethe...
^
= 0
/Users/hbeck/alice/alibuild/sw/SOURCES/AliPhysics/0/0/PWGLF/NUCLEX/Hypernuclei/Hyp2Body/AliAnalysisTaskHypTritEventTree.h:43:54: warning: 
variable 'i' is uninitialized when used here …
```
> Initialize i=0 in for loop twice AliAnalysisTaskHypTritEventTree

- PWGHF/hfe/AliHFEV0cuts.cxx
Fixes compiler warnings
/Users/hbeck/alice/alibuild/sw/SOURCES/AliPhysics/0/0/PWGHF/hfe/AliHFEV0cuts.cxx:1623:14: warning: explicitly assigning value of variable of type 'Double_t' (aka 'double') to itself [-Wself-assign]
xpoint =  xpoint;
~~~~~~ ^  ~~~~~~
/Users/hbeck/alice/alibuild/sw/SOURCES/AliPhysics/0/0/PWGHF/hfe/AliHFEV0cuts.cxx:1624:14: warning: explicitly assigning value of variable of type 'Double_t' (aka 'double') to itself [-Wself-assign]
ypoint =  ypoint;
~~~~~~ ^  ~~~~~~
/Users/hbeck/alice/alibuild/sw/SOURCES/AliPhysics/0/0/PWGHF/hfe/AliHFEV0cuts.cxx:1629:14: warning: explicitly assigning value of variable of type 'Double_t' (aka 'double') to itself [-Wself-assign]
xpoint =  xpoint;
~~~~~~ ^  ~~~~~~
/Users/hbeck/alice/alibuild/sw/SOURCES/AliPhysics/0/0/PWGHF/hfe/AliHFEV0cuts. …
> Fix self assignment HFE cuts

- PWGHF/correlationHF/AliHFCorrFitSystematics.h
@arossi81 @fcolamar What do you think?
```c++
/Users/hbeck/alice/alibuild/sw/SOURCES/AliPhysics/0/0/PWGHF/correlationHF/AliHFCorrFitSystematics.h:70:120: warning: 
variable 'i' is uninitialized when used here [-Wuninitialized]
...v2had, Int_t nbins, std::vector<Double_t>& v2Dbins) {fv2had = v2had; for(Int_t i;i<nbins;i++...
^
/Users/hbeck/alice/alibuild/sw/SOURCES/AliPhysics/0/0/PWGHF/correlationHF/AliHFCorrFitSystematics.h:70:119: note: 
initialize the variable 'i' to silence this warning
...Int_t nbins, std::vector<Double_t>& v2Dbins) {fv2had = v2had; for(Int_t i;i<nbins;i++) fv2Dm...
^
= 0
```
> Init i=0 in for loop AliHFCorrFitSystematics

- PWG/muon/AliAnalysisMuMuMinv.cxx
Hello muon people!
This commit doesn't change any behavior, just silences a warning, allowing to focus on other, serious warnings. 
Cheers,
Hans
```c++
/Users/hbeck/alice/alibuild/sw/SOURCES/AliPhysics/0/0/PWG/muon/AliAnalysisMuMuMinv.cxx:48:1: warning: field 'fmcptcutmax' will be initialized after field 'fPtFuncOld' [-Wreorder]
fmcptcutmax(12.0),
^
```
> Fix simple reorder in AliAnalysisMuMuMinv

- PWGLF/SPECTRA/Kinks/AliAnalysisTaskKinksFilimon.cxx
Old code raises compiler warnings:
```c++
/Users/hbeck/alice/alibuild/sw/SOURCES/AliPhysics/0/0/PWGLF/SPECTRA/Kinks/AliAnalysisTaskKinksFilimon.cxx:170:108: warning: unused variable 'hLoY' [-Wunused-var
iable]
Float_t hLoPt = fHistPtYTemplate->GetXaxis()->GetXmin(), hHiPt = fHistPtYTemplate->GetXaxis()->GetXmax(), hLoY = fHistPtYTemplate->GetYaxis()->GetXmin(), hHiY = fHistPtYTemplate->GetYaxis()->GetXmax()/*, hLoEta = -1.5, hHiEta = 1.5*/;//, fLowX=0.6, fHighX=1.8;
^
/Users/hbeck/alice/alibuild/sw/SOURCES/AliPhysics/0/0/PWGLF/SPECTRA/Kinks/AliAnalysisTaskKinksFilimon.cxx:170:156: warning: unused variable 'hHiY' [-Wunused-variable]
Float_t hLoPt = fHistPtYTemplate->GetXaxis()->GetXmin(), hHiPt = fHistPtYTemplate->GetXaxis()->GetXmax(), hLoY = fHistPtYTemplate->GetYaxis()->GetXmin(), hHiY …
```
> Commented unused variables AliAnalysisTaskKinksFilimon

- PWGLF/SPECTRA/Kinks/AliESDkinkCuts.cxx
Old code gives a compiler warning:
```c++
/Users/hbeck/alice/alibuild/sw/SOURCES/AliPhysics/0/0/PWGLF/SPECTRA/Kinks/AliESDkinkCuts.cxx:100:12: warning: unused variable 'maxDecAngKmu' [-Wunused-variable]
Double_t maxDecAngKmu = fMaxDecayAngleCurveKmu->Eval(mother3MomentumAtKinkVtx.Mag(), 0., 0., 0.);
^
/Users/hbeck/alice/alibuild/sw/SOURCES/AliPhysics/0/0/PWGLF/SPECTRA/Kinks/AliESDkinkCuts.cxx:97:13: warning: unused variable 'invariantMassKmu' [-Wunused-variab
le]
Float_t invariantMassKmu = (energyDaughterMu+transferedMom.Mag())*(energyDaughterMu+transferedMom.Mag())-mother3MomentumAtKinkVtx.Mag()*mother3MomentumAtKin
kVtx.Mag();
^
2 warnings generated.
```
> Commented unused variable AliESDkinkCuts

- PWGLF/SPECTRA/PiKaPr/TOF/pp7/AliAnalysisCombinedHadronSpectra2MC.cxx
Hello LF people!
The old logic in AliAnalysisCombinedHadronSpectra2MC is correct but over-complicates the problem and raises a warning. Simplified the logic, please have a look at the new logic.
Task was last touched by Riccardo Russo 3 years ago. Warnings below.
Cheers,
Hans
```c++
/Users/hbeck/alice/alibuild/sw/SOURCES/AliPhysics/0/0/PWGLF/SPECTRA/PiKaPr/TOF/pp7/AliAnalysisCombinedHadronSpectra2MC.cxx:1018:9: warning: logical not is only 
applied to the left hand side of this comparison [-Wlogical-not-parentheses]
if (!(track->GetStatus()&AliESDtrack::kTOFout)==0) {fTOFout=1;}else {fTOFout=0;}
^                                         ~~
/Users/hbeck/alice/alibuild/sw/SOURCES/AliPhysics/0/0/PWGLF/SPECTRA/PiKaPr/TOF/pp7/AliAnalysisCombinedHadronSpectra2MC.cxx:1018:9: note: add …
```
> Fix logic & unused var warnings AliAnalysisCombinedHadronSpectra2MC

- PWGGA/GammaConv/AliV0ReaderStrange.cxx
Dear @dmuhlhei, 
Can you look at this PR? Simply fixes a small warning when compiling AliPhysics with -Wall.
Cheers,
Hans
```c++
/Users/hbeck/alice/alibuild/sw/SOURCES/AliPhysics/0/0/PWGGA/GammaConv/AliV0ReaderStrange.cxx:49:3: warning: field 'fVectorFoundGammas' will be initialized after
field 'fConversionGammas' [-Wreorder]
fVectorFoundGammas(0),
^
1 warning generated.
```
> Fix reorder AliV0ReaderStrange

- PWGGA/GammaConv/AliV0ReaderV1.cxx
@FriederikeBock can you have a look at this PR for AliV0ReaderV1? Just a few harmless warnings.
```c++
/Users/hbeck/alice/alibuild/sw/SOURCES/AliPhysics/0/0/PWGGA/GammaConv/AliV0ReaderV1.cxx:88:3: warning: field 'kUseAODConversionPhoton' will be initialized after field 'kAddv0sInESDFilter' [-Wreorder]
kUseAODConversionPhoton(kTRUE),
^
/Users/hbeck/alice/alibuild/sw/SOURCES/AliPhysics/0/0/PWGGA/GammaConv/AliV0ReaderV1.cxx:150:3: warning: field 'fMCFileChecked' will be initialized after field 'fPCMv0BitField' [-Wreorder]
fMCFileChecked(kFALSE),
^
/Users/hbeck/alice/alibuild/sw/SOURCES/AliPhysics/0/0/PWGGA/GammaConv/AliV0ReaderV1.cxx:1715:12: warning: unused variable 'Branch_R' [-Wunused-variable]
TBranch *Branch_R = fImpactParamTree->Branch("R",&R,"R/F");
^ …
```
> Remove unused pointer, fix reorder warning AliV0ReaderV1

- PWGGA/GammaConv/AliV0CutsStrange.cxx
Dear @dmuhlhei,
Another small reorder fix. Can you have a look? 
Cheers!
Hans
```c++
/Users/hbeck/alice/alibuild/sw/SOURCES/AliPhysics/0/0/PWGGA/GammaConv/AliV0CutsStrange.cxx:49:3: warning: field 'fIsQA' will be initialized after field 'fV0Read
erStrangeName' [-Wreorder]
fIsQA(kFALSE),
^
/Users/hbeck/alice/alibuild/sw/SOURCES/AliPhysics/0/0/PWGGA/GammaConv/AliV0CutsStrange.cxx:53:3: warning: field 'fPreSelCut' will be initialized after field 'fU
seOnFlyV0Finder' [-Wreorder]
fPreSelCut(kFALSE),
^
/Users/hbeck/alice/alibuild/sw/SOURCES/AliPhysics/0/0/PWGGA/GammaConv/AliV0CutsStrange.cxx:56:3: warning: field 'fMinClsTPC' will be initialized after field 'fMinClsTPCToF' [-Wreorder]
fMinClsTPC(0.),
^
/Users/hbeck/alice/alibuild/sw/SOURCES/AliPhysics/0/0/PWGGA/GammaConv/AliV0CutsStrange.cxx:57:3 …
```
> Fix reorder AliV0CutsStrange

- PWGGA/GammaConv/AliV0ReaderV1.h
gcc implements the class std::iterator to have a non-virtual
destructor. Consequently classes inheriting from std::iterator
will raise the Weffc warning. Inheriting from std::iterator
however is a popular and easy way to make a class std::iterable,
and the way chosen in this approach. As the std::iterator doesn't
allocate memory, the warning is still vaid but harmless, and
as it cannot be handled by any implementation it should be treated
as a false positive. Therefore Weffc will be disabled for gcc
for AliVOReaderV1 in a similar way is it is done for the iterator
of ROOT's TMap.
> Disable Weffc for gcc for AliV0ReaderV1

- PWGJE/EMCALJetTasks/AliEmcalJetByJetCorrection.cxx
Hello JE,
This PR fixes three small harmless warnings in the code of Chiara and Marta.
Cheers,
Hans
```c++
/Users/hbeck/alice/alibuild/sw/SOURCES/AliPhysics/0/0/PWGJE/EMCALJetTasks/AliEmcalJetByJetCorrection.cxx:63:3: warning: field 'fNMissedTracks' will be initialized after field 'fRndm' [-Wreorder]
fNMissedTracks(-1),
^
/Users/hbeck/alice/alibuild/sw/SOURCES/AliPhysics/0/0/PWGJE/EMCALJetTasks/AliEmcalJetByJetCorrection.cxx:121:3: warning: field 'fhNmissing' will be initialized after field 'fRndm' [-Wreorder]
fhNmissing(other.fhNmissing),
^
/Users/hbeck/alice/alibuild/sw/SOURCES/AliPhysics/0/0/PWGJE/EMCALJetTasks/AliEmcalJetByJetCorrection.cxx:244:18: warning: unused variable 'binEff' [-Wunused-variable]
Double_t binEff = fhEfficiency->GetBinContent(bin);
^
3 warnings generated.
```
> AliEmcalJetByJetCorrection fix reorder&unused value

- PWGGA/EMCALTasks/AliAnalysisTaskEMCALPhotonIsolation.cxx
- PWGGA/EMCALTasks/AliAnalysisTaskEMCALPhotonIsolation.h
- PWGGA/EMCALTasks/macros/AddTaskEMCALPhotonIsolation.C
Option that only analyses events with with L1 recalculated trigger patches (from TriggerMakerTask) over 2012 threshold added.
Needed to use trigger bad map.
triggername must contain EGArecalc or L1recalc, and periodstr must contain 12, to use this option
> option to use 2012 trigger bad map added

- CORRFW/AliCFDataGrid.cxx
Function was calling itself infinitely
Revealed by a compiler warning.
> Fix AliCFDataGrid::Copy

- PWGUD/DIFFRACTIVE/CEPdevel/AliCEPUtils.cxx
- PWGUD/UPC/AliAnalysisTaskUpcEtaC.cxx
- PWGUD/UPC/AliAnalysisTaskUpcTree.cxx
- PWGUD/UPC/nanoAOD/AliAnalysisTaskFilterUPCNanoAOD.cxx
`/Users/chm/alice/sw/SOURCES/AliPhysics/0/0/PWGUD/DIFFRACTIVE/CEPdevel/AliCEPUtils.cxx:793:23: warning: equality comparison result unused
[-Wunused-comparison]
if (ii == 0) side == AliTriggerAnalysis::kASide;
~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/chm/alice/sw/SOURCES/AliPhysics/0/0/PWGUD/DIFFRACTIVE/CEPdevel/AliCEPUtils.cxx:793:23: note: use '=' to turn this equality comparison
into an assignment
if (ii == 0) side == AliTriggerAnalysis::kASide;
^~
=
/Users/chm/alice/sw/SOURCES/AliPhysics/0/0/PWGUD/DIFFRACTIVE/CEPdevel/AliCEPUtils.cxx:794:23: warning: equality comparison result unused
[-Wunused-comparison]
if (ii == 1) side == AliTriggerAnalysis::kCSide;
~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/chm/alice/sw/SOURCES/AliPhysics/0/0/PWGUD/DIFFRACTIVE/CEPdevel/AliCEPUtils.cxx:794:23: …
> fixes for compiler warnings

- PWGPP/TRD/AliTRDcheckPID.cxx
Fixes a compiler warning
```c++
/Users/hbeck/alice/alibuild/sw/SOURCES/AliPhysics/0/0/PWGPP/TRD/AliTRDcheckPID.cxx:1209:7: warning: 
expression result unused [-Wunused-value]
(TH1F*)h1->DrawClone(kFIRST ? "c" : "samec");
^      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 warning generated.
```
> Fix unused value AliTRDcheckPID

- PWGJE/FlavourJetTasks/AliAnalysisTaskFlavourJetCorrelations.cxx
Hello JE,
@btrzecia can you look at this PR which fixes three small warnings?
Cheers,
Hans
```c++
/Users/hbeck/alice/alibuild/sw/SOURCES/AliPhysics/0/0/PWGJE/FlavourJetTasks/AliAnalysisTaskFlavourJetCorrelations.cxx:75:1: warning: field 'fAnalyseDBkg' will be initialized after field 'fBuildRM' [-Wreorder]
fAnalyseDBkg(kFALSE),
^
/Users/hbeck/alice/alibuild/sw/SOURCES/AliPhysics/0/0/PWGJE/FlavourJetTasks/AliAnalysisTaskFlavourJetCorrelations.cxx:119:1: warning: field 'fAnalyseDBkg' will be initialized after field 'fBuildRM' [-Wreorder]
fAnalyseDBkg(kFALSE),
^
/Users/hbeck/alice/alibuild/sw/SOURCES/AliPhysics/0/0/PWGJE/FlavourJetTasks/AliAnalysisTaskFlavourJetCorrelations.cxx:589:14: warning: unused variable 'DEtaGen' [-Wunused-variable]
Double_t DEtaGen = Dgen->Eta();
^
3 warnings …
```
> Fix reorder, comment out unused value FlavourJetCorrelations

- PWGGA/EMCALTasks/AliAnalysisTaskEMCALPhotonIsolation.cxx
- PWGGA/EMCALTasks/AliAnalysisTaskEMCALPhotonIsolation.h
This implementation aims at providing a cluster position-dependent cone area calculation in case the user wants to set a fiducial cut lower than the isolation cone radius, which may result in a truncated cone and therefore a lower area.
Different cases are considered (EMCal corners and borders).
A first test is implemented in `EtIsoClusEtaBand()`.
> Introducing a method for computing isolation cone area in case of fiducial cut lower than the cone radius

- PWGPP/BeamGasMonitoring/AliAnalysisBGMonitorQATrain.cxx
Fixed reorder, unused variable, memory leak, and printing a string in AliAnalysisBGMonitorQATrain
triggered by compiler warnings:
```c++
DEBUG:AliPhysics:0: /Users/hbeck/alice/alibuild/sw/SOURCES/AliPhysics/0/0/PWGPP/BeamGasMonitoring/AliAnalysisBGMonitorQATrain.cxx:61:1: warning: field 'nbunch' will be initialized after field 'nV0A' [-Wreorder]
DEBUG:AliPhysics:0: nbunch(0),
DEBUG:AliPhysics:0: ^
DEBUG:AliPhysics:0: /Users/hbeck/alice/alibuild/sw/SOURCES/AliPhysics/0/0/PWGPP/BeamGasMonitoring/AliAnalysisBGMonitorQATrain.cxx:82:1: warning: field 'nbunch' will be initialized after field 'nV0A' [-Wreorder]
DEBUG:AliPhysics:0: nbunch(0),
DEBUG:AliPhysics:0: ^
DEBUG:AliPhysics:0: /Users/hbeck/alice/alibuild/sw/SOURCES/AliPhysics/0/0/PWGPP/BeamGasMonitoring/AliAnalysisBGMonitorQATrain.cxx:230:1 …
```
> Fix reorder, unused var, leak, string BGMonitorQATrain

- PWG/MCLEGO/CMakeLists.txt
- PWG/MCLEGO/Therminator2/events.ini
- PWG/MCLEGO/Therminator2/gen_therm2.sh
I added a default configuration file and a gen_therm2.sh script which should enable running MCLEGO trains with Therminator2 and parsing them to HepMC.
> Added base for MCLEGO trains with Therminator2

- PWG/EMCAL/EMCALbase/AliAnalysisTaskEmcal.cxx
- PWG/EMCAL/EMCALbase/AliEmcalContainer.h
The position of the primary vertex has to be set per event. Instead it was
handled in SetArray, which is only called in ExecOnce. A setter function for
the primary vertex was added, and it is called automatically in AliAnalysisTaskEmcal
in function run. Affects momentum vector calculation for neutral constituents in
AliEmcalJetTask (jetfinder task of the EMCAL jet framework).
(see https://alice.its.cern.ch/jira/browse/ALPHY-81 for more details)
> [ALPHY-81] Fix primary vertex position handling in cluster container

- PWGJE/EMCALJetTasks/Tracks/AliAnalysisTaskEmcalJetSubstructureTree.cxx
- PWGJE/EMCALJetTasks/Tracks/AliAnalysisTaskEmcalJetSubstructureTree.h
- PWGJE/EMCALJetTasks/macros/AddTaskEmcalJetSubstructureTree.C
- In case of energy for neutral constituents, moving
from raw energy to energy corrected for the hadronic component
- Prepare for charged jets:
+ Making cluster container optional
+ Adding case for charged jets in the Add function
> Changing to corrected energy, prepare for charged jets

- PWGDQ/dielectron/core/AliDielectronVarManager.h
Hello dielectron people,
Can you look at this PR? It fixes a small warning when compiling AliPhysics with -Wall, see below.
Cheers,
Hans
```c++
/Users/hbeck/alice/alibuild/sw/SOURCES/AliPhysics/0/0/PWGDQ/dielectron/core/AliDielectronVarManager.h:2520:15: warning: unused variable 'qVecQnFramework' [-Wunused-variable]
TVector2 *qVecQnFramework;
^
```
> Commented out unused variable AliDielectronVarManager

- CMakeLists.txt
Added -Wall -Wno-missing-braces warning to AliPhysics. Missing braces is
included in Wall in clang but not in gcc>=4.8.
Hello @pzhristov @dberzano @rbertens @mfasDa @raymondEhlers @loizides @aiola @ddobrigk @cbourjau !
This PR is meant as a place to discuss the possibility of adding the -Wall warning to AliPhysics. The compiler warnings can help in catching some unintended behavior in our physics analyses. Looking at the warnings of -Wall, most warnings are harmless reordering but a substantial amount of warnings points out code which does not do what it is intended to do. 
A counterargument is the additional work load on coders, fixing harmless reorder warnings. I'd like to argue that making coders aware of such issues is a benefit on its own and the few harmful cases we catch outweigh …
> Add -Wall to AliPhysics

- CMakeLists.txt
> Add CMake option to treat warnings as errors

- PWGJE/EMCALJetTasks/UserTasks/AliAnalysisTaskPID.cxx
Changes behavior of task!
Old code was always assigning array at index -1. For what the old code did:
https://stackoverflow.com/questions/29933444/c-multi-dimensional-array-comma-index-address
> A comma operator is a binary operator which evaluates all the comma separated expressions completing its side effects and discards it until the last expression in the list. 
```c++
sers/hbeck/alice/alibuild/sw/SOURCES/AliPhysics/0/0/PWGJE/EMCALJetTasks/UserTasks/AliAnalysisTaskPID.cxx:1379:58: warning: 
expression result unused [-Wunused-value]
valuesGenYield[GetIndexOfChargeAxisGenYield(), -1, -1] = chargeMC;
^~
/Users/hbeck/alice/alibuild/sw/SOURCES/AliPhysics/0/0/PWGJE/EMCALJetTasks/UserTasks/AliAnalysisTaskPID.cxx:1379:11: warning: 
array index -1 is before the …
```
> Fix array index access AliAnalysisTaskPID

- PWGJE/FlavourJetTasks/AliAnalysisTaskEmcalJetHF.cxx
Hello!
This PR fixes a few warnings when compiling AliPhysics with -Wall. @AndrewCastro, you want to comment?
Cheers,
Hans
```c++
/Users/hbeck/alice/alibuild/sw/SOURCES/AliPhysics/0/0/PWGJE/FlavourJetTasks/AliAnalysisTaskEmcalJetHF.cxx:82:1: warning: field 'fInvmassCut' will be initialized after field 'fHistManager' [-Wreorder]
fInvmassCut(),
^
/Users/hbeck/alice/alibuild/sw/SOURCES/AliPhysics/0/0/PWGJE/FlavourJetTasks/AliAnalysisTaskEmcalJetHF.cxx:116:1: warning: field 'fInvmassCut' will be initialized after field 'fHistManager' [-Wreorder]
fInvmassCut(0),
^
/Users/hbeck/alice/alibuild/sw/SOURCES/AliPhysics/0/0/PWGJE/FlavourJetTasks/AliAnalysisTaskEmcalJetHF.cxx:532:34: warning: unused variable 'clustMatchHadCorr' [-Wunused-variable]
Double_t clustMatchHadCorr = …
```
> Comment out unused variables EmcalJetHF

- PWGCF/Correlations/Base/AliTwoPlusOneContainer.cxx
Prevents code from using uninitialized data member. Revealed by a compiler warning:
```c++
/Users/hbeck/alice/alibuild/sw/SOURCES/AliPhysics/0/0/PWGCF/Correlations/Base/AliTwoPlusOneContainer.cxx:101:10: warning: 
base class 'TNamed' is uninitialized when used here to access
'TNamed::fName' [-Wuninitialized]
TNamed(fName, fTitle),
^
/Users/hbeck/alice/alibuild/sw/SOURCES/AliPhysics/0/0/PWGCF/Correlations/Base/AliTwoPlusOneContainer.cxx:101:17: warning: 
base class 'TNamed' is uninitialized when used here to access
'TNamed::fTitle' [-Wuninitialized]
TNamed(fName, fTitle),
^
2 warnings generated.
```
@mazimm what do you think?
> Fix copy ctor AliTwoPlusOneContainer

- PWGCF/Correlations/Base/AliAnalysisTaskCFTree.cxx
The & operator has lower precedence than ==. Added parentheses such that the filter bit "mask" selects on filter bits. 
@qgp can you have a look? 
Warning: this changes the behavior of the task! (For good, I hope.)
Generates a warning with gcc when using -Wall flag, see here:
http://www.physi.uni-heidelberg.de/~hbeck/Wall-log.txt
Clang has even nicer diagnostics on this one:
```c++
tst.C:6:12: warning: & has lower precedence than ==; == will be evaluated first
[-Wparentheses]
if (mask & fTrackFilterBit == 0){
^~~~~~~~~~~~~~~~~~~~~~
tst.C:6:12: note: place parentheses around the '==' expression to silence this
warning
if (mask & fTrackFilterBit == 0){
^
(                   )
tst.C:6:12: note: place parentheses around the & expression to evaluate it first
if (mask & fTrackFilterBit == 0){
^ …
```
> Fix filter bit track cut in CFTree

- PWGGA/GammaConv/AliCaloPhotonCuts.cxx
- PWGGA/GammaConv/AliCaloPhotonCuts.h
- AliCaloPhotonCuts: added MC period enums for LHC17g8{b,c}
- AliCaloPhotonCuts: hard coded esdTrackCuts, because aliroot's version spams warnings which inflate the log file
> PWGGA/GammaConv: added MC period enums

- PWGDQ/dielectron/CMakeLists.txt
- PWGDQ/dielectron/PWGDQdielectronLinkDef.h
- PWGDQ/dielectron/core/AliAnalysisTaskMultiDielectron.cxx
- PWGDQ/dielectron/core/AliAnalysisTaskMultiDielectron.h
- PWGDQ/dielectron/core/AliDielectron.cxx
- PWGDQ/dielectron/core/AliDielectron.h
- PWGDQ/dielectron/core/AliDielectronEvtVsTrkHist.cxx
- PWGDQ/dielectron/core/AliDielectronEvtVsTrkHist.h
- PWGDQ/dielectron/core/AliDielectronHistos.cxx
- PWGDQ/dielectron/core/AliDielectronVarManager.cxx
- PWGDQ/dielectron/core/AliDielectronVarManager.h
New class in the dq-framework, to create histograms plotting event variables versus track variables. Currently only the ITS-TPC matching efficiency is implemented but further options can now more or less easily be added. Although one always has to implement the recalculation of the event variable.
> PWGDQ new class for Event vs Track histograms

- PWG/FLOW/Base/AliFlowAnalysisCRC.cxx
- PWG/FLOW/Base/AliFlowAnalysisCRC.h
- PWGCF/FLOW/macros/AddTaskCRC.C
store separately Qn{2} and Qn{4} using RPs from either positive, negative or any rapidity
> separate rapidity regions for RPs

- PWG/CaloTrackCorrBase/AliCalorimeterUtils.h
Forward IsDistanceToBadChannelRecalculated to data member
```c++
DEBUG:AliPhysics:0: /Users/hbeck/alice/alibuild/sw/SOURCES/AliPhysics/0/0/PWG/CaloTrackCorrBase/AliCalorimeterUtils.h:150:60: warning: all paths through this function will call itself [-Winfinite-recursion]
DEBUG:AliPhysics:0:   Bool_t        IsDistanceToBadChannelRecalculated() const { return  IsDistanceToBadChannelRecalculated()             ; }
DEBUG:AliPhysics:0:                                                            ^
```
> Fix infinite loop AliCalorimeterUtils

- PWGGA/GammaConv/AliConvEventCuts.cxx
modify scaling factor of JetJet LHC16h3 due to transcription error.
> PWGGA/GammaConv:Modified weights for LHC16h3 due to transcription error

- PWGDQ/dielectron/core/AliDielectronMC.cxx
Like to check the pdg of the associated MC track in the function AliDielectronMC::IsMCTruth take the abs(label) of the reconstructed track to get its corresponding MC track.
> Use Abs(label) to take the MC track

- OADB/AliCentralitySelectionTask.cxx
Code is good as is, but generates warning.
@atoia what do you think?
> Fix integer abs -> TMath::Abs AliCentralitySelectionTask

- PWGDQ/dielectron/core/AliDielectronMC.cxx
Missing protection in the AliDielectronMC::IsJpsiPrimary function.
This did not show up until now since the track were anyway rejected by the HaveSameMother condition rejecting track with negative label. After the change in HaveSameMother this is crashing.
Add the protection on the two daughters for the AliDielectronPair in IsJpsiPrimary. In this way, this function does not change at all, even after the change in HaveSameMother.
(Sorry)
> Missing protection in the IsJPsiPrimary function 

- PWGDQ/dielectron/core/AliDielectron.cxx
- PWGDQ/dielectron/core/AliDielectronEvtVsTrkHist.cxx
Naming of V0C as epDetector was wrong. Fixed some warnings due to wrong initialisation ordering and unused variables.
> PWGDQ EvtVsTrkHist small bug fix for V0C eventplane

- PWGCF/FEMTOSCOPY/AliFemtoUser/AliFemtoConfigObject.cxx
To compile on OS X, needs <numeric> included for accumulate.
Some fixes for root 6 are also needed, but the implementation is not yet clear to me - see [here](https://github.com/alisw/AliPhysics/pull/2525#issuecomment-328223744)
> Fix OS X compilation

- PWGCF/FEMTOSCOPY/AliFemtoUser/AliFemtoConfigObject.cxx
Explicitly add TBuffer include. Thanks @akubera for the suggestion! I should have looked more closely at the includes and the TBuffer header to see what the problem was.
Note that you also need #2544 to compile with ROOT 6 at the moment.
> Fix ROOT 6 compilation

- PWGJE/EMCALJetTasks/UserTasks/AliAnalysisTaskEmcalJetShapesMC.h
Function was given a return type of float, but doesn't return a value.
This changes the return to void.
@lcunquei - Can you please confirm that this is the desired way to change this?
> Remove return value to fix root 6 compilation

- PWG/JETFW/AliEmcalJet.cxx
- PWG/JETFW/AliEmcalJet.h
- PWG/JETFW/AliJetContainer.cxx
Updates the classes to avoid passing the wrong TClonesArray when using
multiple EMCal containers and accessing track and cluster constituents.
Note that these changes basically remove the dependence of
AliJetContainer on particle and cluster containers. They could likely
be removed in the future.
For more information, see the JIRA ticket [ALPHY-77](https://alice.its.cern.ch/jira/browse/ALPHY-77). The changes have been validated on the sample tasks and the jet shapes analysis. Further, there were no objections on the JIRA ticket.
> [ALPHY-77] EMCal Embed: Update jet base classes

- PWG/TRD/AliAnalysisTaskTRDtriggerCheck.cxx
- PWG/TRD/AliTRDTriggerAnalysis.cxx
In Run-2, the wake-up trigger was not used anymore for the TRD triggers, so the trigger string changed and does not contain "WU" anymore, but in this class it was still used, so it could not be used for Run-2 data.
> Update TRD classes for Run-2 analyses

- PWGGA/EMCALTasks/AliAnalysisTaskEMCALPhotonIsolation.cxx
- PWGGA/EMCALTasks/AliAnalysisTaskEMCALPhotonIsolation.h
- PWGGA/EMCALTasks/macros/AddTaskEMCALPhotonIsolation.C
This new switch is temporarily set to `kTRUE` in order to test a new feature. In future this should become a new parameter of the task but this will require some cleanup since we currently are at the maximal number of parameters (40).
> Adding a switch for the candidate-based cone area computation

- PWGUD/UPC/AliAnalysisTaskUpcEtaC.cxx
- PWGUD/UPC/AliAnalysisTaskUpcEtaC.h
This is modified from two versions ago. K0s channel uses V0s and all decay channels are included. The BoostCut function was added to look at daughters of Kstars and Rho0s in the parent rest frame. Code was added to the Kstar and Rho0 channels to apply cuts. Histograms of values in the parent rest frame before and after the cut were also added.
> Added BoostCut function and apply a helicity cut for vector mesons

- PWGDQ/dielectron/core/AliDielectron.cxx
- PWGDQ/dielectron/core/AliDielectronEvtVsTrkHist.cxx
- PWGDQ/dielectron/core/AliDielectronEvtVsTrkHist.h
- PWGDQ/dielectron/core/AliDielectronHelper.cxx
Matching efficiency is now calculated more ALICE common as nTracksITS/nTracksTPC. Some more cuts are applied on the track sample to get a more realistic result for the Jpsi track sample.
> PWGDQ fixes in match eff calc for EvtVsTrk class

- PWGHF/correlationHF/AliAnalysisTaskDStarCorrelations.cxx
(different deltaEta bin width in signal and SB THnSparse)
> Minor bug fix in D*-h task when using small-sized THnSparse

- PWGHF/hfe/AliAnalysisTaskTPCCalBeauty.cxx
Two typos - change the size of an array and un-comment the line to fill a THnSparse.
> Typos & uncomment critical line in code.

- PWGPP/EMCAL/AliAnalysisTaskEMCALTimeCalib.cxx
- PWGPP/EMCAL/macros/AddTaskEMCALTimeCalibration.C
- PWGPP/EMCAL/macros/runEMCALTimeCalibTask.C
1. Fix the manually inserting of BC map in AddTask and local macro. No need to add one specific line when running lego trains.
2. BC map loaded from OADB can change run-by-run and is not fixed at the beginning of processing in lego trains.
> Correction in Bad Channel map access

- PWGJE/EMCALJetTasks/AliEmcalJetTask.cxx
All trivial modifications to fix warnings from -Wall, including:
- Initialization order
- Unused variables
> Fix warnings in the jet finder

- PWG/EMCAL/EMCALbase/AliAnalysisTaskEmcal.cxx
- PWG/EMCAL/EMCALbase/AliAnalysisTaskEmcalLight.cxx
- PWG/EMCAL/EMCALbase/AliEmcalContainer.cxx
- PWG/EMCAL/EMCALbase/AliEmcalContainer.h
- PWG/EMCAL/EMCALbase/AliEmcalContainerUtils.cxx
- PWG/EMCAL/EMCALbase/AliEmcalContainerUtils.h
- PWG/EMCAL/EMCALbase/AliTrackContainer.cxx
- PWG/EMCAL/EMCALbase/AliTrackContainer.h
- PWG/EMCAL/EMCALtasks/AliEmcalCorrectionTask.cxx
- PWG/JETFW/AliAnalysisTaskEmcalJet.cxx
- PWG/JETFW/AliAnalysisTaskEmcalJetLight.cxx
- PWGJE/EMCALJetTasks/UserTasks/AliTrackContainerV0.cxx
- PWGJE/EMCALJetTasks/UserTasks/AliTrackContainerV0.h
Replaces the previous fix in 098573b2 with an solution that also works
seamlessly for embedding.
Further discussion is available at the [JIRA Ticket](https://alice.its.cern.ch/jira/browse/ALPHY-81).
> [ALPHY-81] EMCal: Alternative cluster vertex fix

- OADB/AliEventCuts.cxx
- OADB/AliEventCuts.h
The normalisation histogram code has been simplified by putting some
commonly used bitmask as general enum of AliEventCuts.
This modification allows the user to extract these information using the
new `bool AliEventCuts::CheckNormalisationMask(AliEventCuts::NormMask mask)`
method.
> Simplify normalisation histogram code

- PWGGA/CaloTrackCorrelations/AliAnaPi0.cxx
- PWGGA/CaloTrackCorrelations/AliAnaPi0.h
Additional histograms in MC. Subcategories in:
1. conversions; three TH2F histograms with invariant mass of reconstructed and validated pi0 or eta meson decaying to two photons where one or two photons are coming from conversions or no photon is coming from conversion vs pT.
2. strangeness; separate histogram TH2F for K0S, K0L, K+-, K* and Lambda
> Additional histos in MC, strangeness and conversions

- PWGHF/vertexingHF/AliAnalysisTaskSEDs.cxx
- PWGHF/vertexingHF/AliAnalysisTaskSEDs.h
- New method, FillMCAccHistos, to MC-related THnSparse at AcceptanceStep level. The method is similar to FillMCGenAccHistos, which fill MC-related THnSparse at Gen+Acc level.
- Remove 'Double_t massPhi' variable, already defined above in the code.
- Comment unused variable 'Double_t normdl'
> Add possibility to fill THnSparse at AccStep level

- PWG/EMCAL/EMCALbase/AliEmcalESDTrackCutsGenerator.cxx
Mapping hybrid-/TPConly-trackcuts for pPb 2015 to the run1
cuts.
> Adding settings for pPb 2016

- PWGDQ/dielectron/core/AliDielectron.cxx
- PWGDQ/dielectron/core/AliDielectronEvtVsTrkHist.cxx
Repositioned the filling of the EvtVsTrk object in the AliDielectron class. Now it is filled after the current event had to pass the event cuts, setted by the user.
> PWGDQ EvtVsTrk now only evts aft evt cuts are used

- PWGGA/EMCALTasks/AliAnalysisTaskEMCALPhotonIsolation.cxx
- PWGGA/EMCALTasks/AliAnalysisTaskEMCALPhotonIsolation.h
- PWGGA/EMCALTasks/macros/AddTaskEMCALPhotonIsolation.C
This commit allows to plot phi-dependent distributions which consider the various EMCal phi limits across years (i.e. different geometries). The same thing has to be done for the eta coordinate.
> Setting the phi range and binning period-dependent

- PWGGA/EMCALTasks/AliAnalysisTaskEMCALPhotonIsolation.cxx
This commit introduces the DCal geometry inside the task. For now, only the fiducial selection of clusters is modified and precautions have been taken in order not to affect the EMCal-only (run 1) analyses.
> Starting the DCal implementation

- PWG/EMCAL/EMCALbase/AliClusterContainer.cxx
- PWG/EMCAL/EMCALbase/AliClusterContainer.h
By default range is set to +/- infinity using
constants in cfloat.
> Adding possibility to cut on M02 for EMCAL clusters

- PWGCF/Correlations/JCORRAN/Base/AliJFFlucAnalysis.cxx
Due to the implementation of the casting operators and
arithmetic operators with int/float types in TComplex,
there is an ambiguity on whether to use
- operator- from TComplex with TComplex and int
- operator- from int with TComplex implicitly casted to int
In order to fix the ambiguity the complex value needs to
be explicitly defined, or the integer can be converted to
complex using the value as real part of the complex number.
The proposed solution does the subtraction on complex level.
Needed for ROOT6 builds.
> Fixing operator ambiguity

- OADB/AliEventCuts.cxx
- OADB/AliEventCuts.h
The selection of good AOD vertex is on by default, but it can be switched off by the user.
> Make AOD vertex selection optional + fix integer overflow

- PWG/EMCAL/EMCALbase/AliEmcalList.h
Getter is needed to check whether scaled merging is activated
from outside.
> Add getter checking the scaling setting

- PWGHF/vertexingHF/AliAnalysisTaskSELc2V0bachelorTMVA.cxx
Run number range for LHC16l in AliAnalysisTaskSELc2V0bachelorTMVA::GetEstimatorHistogram() was incorrect, meaning that in LHC16l the multiplicity distribution was not being corrected at runtime. This patch should fix it.
> fix run number range for LHC16l in Lc->V0 TMVA task

- PWGCF/FEMTOSCOPY/AliFemto/AliFemtoBPLCMS3DCorrFctn.cxx
- PWGCF/FEMTOSCOPY/AliFemto/AliFemtoBPLCMS3DCorrFctnKK.cxx
- PWGCF/FEMTOSCOPY/AliFemto/AliFemtoBasicEventCut.cxx
- PWGCF/FEMTOSCOPY/AliFemto/AliFemtoBasicTrackCut.cxx
- PWGCF/FEMTOSCOPY/AliFemto/AliFemtoBetaTPairCut.cxx
- PWGCF/FEMTOSCOPY/AliFemto/AliFemtoCorrFctn3DLCMSSym.cxx
- PWGCF/FEMTOSCOPY/AliFemto/AliFemtoCorrFctnDPhiStarDEta.cxx
- PWGCF/FEMTOSCOPY/AliFemto/AliFemtoCorrFctnNonIdDR.cxx
- PWGCF/FEMTOSCOPY/AliFemto/AliFemtoCutMonitorEventMult.cxx
- PWGCF/FEMTOSCOPY/AliFemto/AliFemtoDeltaPtPairCut.cxx
- PWGCF/FEMTOSCOPY/AliFemto/AliFemtoSimpleAnalysis.cxx
- PWGCF/FEMTOSCOPY/AliFemto/AliFemtoV0PairCut.cxx
- PWGCF/FEMTOSCOPY/AliFemto/AliFemtoV0TrackPairCut.cxx
- PWGCF/FEMTOSCOPY/AliFemto/AliFemtoVertexAnalysis.cxx
- PWGCF/FEMTOSCOPY/AliFemto/AliFemtoVertexMultAnalysis.cxx
- PWGCF/FEMTOSCOPY/AliFemto/AliFemtoXiPairCut.cxx
- PWGCF/FEMTOSCOPY/AliFemto/AliFemtoXiTrackPairCut.cxx
- PWGCF/FEMTOSCOPY/AliFemto/AliFemtoXiV0PairCut.cxx
- PWGCF/FEMTOSCOPY/AliFemtoUser/AliFemtoConfigObject.h
- PWGCF/FEMTOSCOPY/AliFemtoUser/AliFemtoCorrFctnKStar.cxx
- PWGCF/FEMTOSCOPY/AliFemtoUser/AliFemtoEventCutCentrality.cxx
- PWGCF/FEMTOSCOPY/AliFemtoUser/AliFemtoModelCorrFctnDEtaDPhiStar.cxx
- PWGCF/FEMTOSCOPY/AliFemtoUser/AliFemtoModelCorrFctnKStar.cxx
- PWGCF/FEMTOSCOPY/AliFemtoUser/AliFemtoModelCorrFctnQinv.cxx
- PWGCF/FEMTOSCOPY/AliFemtoUser/AliFemtoModelCorrFctnTrueQ3D.cxx
- PWGCF/FEMTOSCOPY/AliFemtoUser/AliFemtoPairCutPt.cxx
- PWGCF/FEMTOSCOPY/AliFemtoUser/AliFemtoShareQualityPairCut.cxx
- PWGCF/FEMTOSCOPY/AliFemtoUser/AliFemtoV0PurityBgdEstimator.cxx
- PWGCF/FEMTOSCOPY/AliFemtoUser/AliFemtoV0TrackCutNSigmaFilter.cxx
- PWGCF/FEMTOSCOPY/AliFemtoUser/AliFemtoXiTrackCutNSigmaFilter.cxx
Similar ambiguity issue introduced by Xcode 9 as in AliRoot PR 417 (https://github.com/alisw/AliRoot/pull/417). 
@akubera: Due to the ambiguity the constructor generation in AliFemtoConfigObject doesn't work for TString, as an explicit cast is needed in order to resolve the ambiguity. The constructor is added manually.
> Fixes needed for compilation with Xcode 9

- PWGHF/hfe/AliAnalysisTaskHFEpACorrelation.cxx
- PWGHF/hfe/AliAnalysisTaskHFEpACorrelation.h
- PWGHF/hfe/macros/AddTaskHFEpACorrelation.C
The correlation is now done in 7 Zvtx bins for each centrality bin.
> Add correlation in Zvtx bins

- PWG/FLOW/Base/AliFlowAnalysisCRC.cxx
- PWG/FLOW/Base/AliFlowAnalysisCRC.h
add histograms to store multi-particle cumulants a la generic framework in wide pt bins (0.2-0.5,0.5-1.,1.-50.)
change variables in QA plots for multi-particle cumulants: store cumulants vs phi and eta
> change kine cuts for multi-particle cumulants

- PWGHF/vertexingHF/charmFlow/AliAnalysisTaskSEHFvn.cxx
- PWGHF/vertexingHF/charmFlow/AliAnalysisTaskSEHFvn.h
Before this fix for the first candidate its daughter tracks were removed from the q2, for the second candidate its daughter and those of the first candidate were removed and so on. With this fix, for each candidate only its daughter tracks are removed from the q2.
> Fixed removal of dau tracks of the single candidate from q2 and added mass selection

- PWGDQ/dielectron/LMEE/AliAnalysisTaskSimpleTreeMaker.cxx
No PID performed when creating V0 data sets.
Run number and multiplicity values now added to V0 data sets.
Minor formatting changes.
> Removed PID for V0 data sets

- PWGGA/EMCALTasks/AliAnalysisTaskEMCALDirGamma.cxx
- PWGGA/EMCALTasks/AliAnalysisTaskEMCALPi0PbPb.cxx
Just to avoid patching already copy-pasted code for the fix in the B-field initialization: it is better to use the source method which is already fixed.
> use ESDrun->InitMagnetic field instead of copy/paste

- PWGDQ/reducedTree/AliReducedVarManager.cxx
- PWGDQ/reducedTree/AliReducedVarManager.h
With commit ac1137d3eed6391080e9111f35a77e199b08c919, a bug was introduced causing that the uncorrected multiplicity estimators could not be addressed in the old way anymore. This is restored now. The corrected estimators can be obtained via GetCorrectedMultiplicity( Int_t estimator , Int_t correction , Int_t reference , Int_t smearing  ) (correction for vertex and run number possible, min, max or mean as reference, Poisson smearing on or off)
> fix multiplicity estimators

- PWGHF/correlationHF/AliAnalysisTaskSED0Correlations.cxx
- PWGHF/correlationHF/AliAnalysisTaskSED0Correlations.h
- PWGHF/correlationHF/macros/AddTaskD0Correlations.C
Mainly for:
- Purity studies (and systematics) vs centrality
- MC closure test vs centrality
> Updated D0-h task: allow applying Ntrkl weights to MC events

- PWG/EMCAL/EMCALtasks/AliAnalysisTaskEmcalTriggerSelection.cxx
- PWG/EMCAL/EMCALtasks/AliAnalysisTaskEmcalTriggerSelection.h
- PWG/EMCAL/EMCALtasks/PWGEMCALtasksLinkDef.h
- PWG/EMCAL/EMCALtrigger/AliEmcalTriggerDecision.cxx
- PWG/EMCAL/EMCALtrigger/AliEmcalTriggerDecision.h
- PWG/EMCAL/EMCALtrigger/AliEmcalTriggerDecisionContainer.cxx
- PWG/EMCAL/EMCALtrigger/AliEmcalTriggerDecisionContainer.h
- PWG/EMCAL/EMCALtrigger/AliEmcalTriggerSelection.cxx
- PWG/EMCAL/EMCALtrigger/AliEmcalTriggerSelection.h
- PWG/EMCAL/EMCALtrigger/AliEmcalTriggerSelectionCuts.cxx
- PWG/EMCAL/EMCALtrigger/AliEmcalTriggerSelectionCuts.h
- PWG/EMCAL/EMCALtrigger/PWGEMCALtriggerLinkDef.h
- PWG/EMCAL/macros/AddEmcalTriggerSelectionTask.C
- PWGJE/EMCALJetTasks/Tracks/AliAnalysisTaskEmcalJetSubstructureTree.cxx
The trigger selection framework is used to select an emcal triggered event
based on trigger patch information (of particluar need for MC, but also
of interest for data for cleanup).
Changes:
- Move to PWG::EMCAL
- Move doxygen documentation to header
- Add acceptance type to trigger selection in order to distinguish EMCAL/DCAL acceptance
- Move classes of task in the namespacen PWG::EMCAL
- Create add macro for the task
- Make Autoconfiguration methods based on period string (currently 2016-only)
- Add option to cut on smeared energy
- Add handling for recalc patches
> Revive trigger selection framework

- PWG/EMCAL/EMCALtasks/AliEmcalCorrectionComponent.cxx
- PWG/EMCAL/EMCALtasks/AliEmcalCorrectionComponent.h
- PWG/EMCAL/EMCALtasks/AliEmcalCorrectionTask.cxx
- PWG/EMCAL/EMCALtasks/AliEmcalCorrectionTask.h
- PWG/Tools/AliYAMLConfiguration.cxx
- PWG/Tools/AliYAMLConfiguration.h
- PWG/Tools/CMakeLists.txt
- PWG/Tools/PWGToolsLinkDef.h
Introduces a new configuration class, AliYAMLConfiguration, that provides an interface which allows users to read and write values in YAML files. It is refactored and generalized from the functionality in the EMCal Corrections Framework.
Given the generalization, it was moved to PWG/Tools, with the hope that it can benefit other users. Documentation on usage is available in the class header.
It has been tested and validated on ROOT 5 and 6 on macOS (thanks @jdmulligan for help testing!), but given the use of templates, it may cause errors with gcc, so it may take a few iterations.
> Introduce a new YAML configuration class

- PWG/Tools/AliYAMLConfiguration.cxx
- PWG/Tools/AliYAMLConfiguration.h
Two minor bug fixes:
- Handle corner case in retrieving a specialized property
- Fix argument order for writing a configuration
@aiola - The corner case fixed here is subtle, but without the fix, it makes a common embedding configuration difficult, so could you please merge this before the tag? Thanks!
> Small bug fixes for AliYAMLConfiguration

- PWGDQ/dielectron/core/AliDielectron.cxx
- PWGDQ/dielectron/core/AliDielectronEvtVsTrkHist.cxx
- PWGDQ/dielectron/core/AliDielectronHelper.cxx
- PWGDQ/dielectron/core/AliDielectronHelper.h
- PWGDQ/dielectron/core/AliDielectronVarManager.cxx
- PWGDQ/dielectron/core/AliDielectronVarManager.h
Small Warning fix in AliDielectronEvtVsTrkHistos, fixed GetNch and GetNmothers in AliDielectronHelper for AODs (was broken due to fix updates for the new AliStack usage), changed the way the VarManager gets the values from GetNch and GetNmothers, now only one loop instead of eight is used to calculate the values.
> PWGDQ fix MC AOD + reorder GetNch in Helper

- PWG/JETFW/AliEmcalJet.cxx
Fix a ClusterAt() -> Cluster() in AliEmcalJet which I missed in a recent
change. Note that it only would have caused problems for EMCal
embedding, so it didn't adversely affect anyone's results.
> JETFW: Fix cluster constituent access

- PWG/EMCAL/EMCALtasks/AliAnalysisTaskEmcalTriggerSelection.cxx
- PWG/EMCAL/EMCALtasks/AliAnalysisTaskEmcalTriggerSelection.h
- PWGJE/EMCALJetTasks/CMakeLists.txt
- PWGJE/EMCALJetTasks/PWGJEEMCALJetTasksLinkDef.h
- PWGJE/EMCALJetTasks/Tracks/AliAnalysisTaskEmcalTriggerSelectionTest.cxx
- PWGJE/EMCALJetTasks/Tracks/AliAnalysisTaskEmcalTriggerSelectionTest.h
- PWGJE/EMCALJetTasks/macros/AddTaskEmcalTriggerSelectionTest.C
Currently monitoring cluster energy (non-lin-corr) for
all L1 triggers supported in run2
> Implement test task for trigger selection framework

- PWGDQ/dielectron/core/AliDielectronHelper.cxx
- PWGDQ/dielectron/core/AliDielectronVarManager.h
With the last commit two debug printf sneaked into the master, they are removed now.
> PWGDQ removed printf creating large logs

- PWG/Tools/AliYAMLConfiguration.cxx
- PWG/Tools/AliYAMLConfiguration.h
Avoid unnecessary copying of strings by using references (originally
mentioned in #2788 - thanks @mfasDa ). Also fix warning related to signed vs unsigned
comparison
> Avoid unnecessary copying and fix warnings

- PWG/EMCAL/EMCALtasks/AliEmcalCorrectionTask.cxx
- PWG/EMCAL/EMCALtasks/AliEmcalCorrectionTask.h
- PWG/EMCAL/READMEemcCorrections.txt
- PWG/EMCAL/macros/ConfigureEmcalCorrectionTaskOnLEGOTrain.C
New function to retrieve an existing correction task so that it can be
configured further in a different wagon on the LEGO train.
To achieve this, a dummy task is created when the configure task is
called because AliAnalysisAlien requires that all wagons add a task.
Then, when Initialize(true) is called on the correction task, the dummy
task is removed.
cc: @mfasDa , @jdmulligan , @aiola
> EMCal CorrFW: Add additional config on LEGO train

- PWGPP/EMCAL/macros/AddTaskEMCALAlig.C
The AddTask is case sensitive in the LEGO train system, so it is needed to match the exact name on the AddTask.
> Fix AddTask

- PWGHF/vertexingHF/AliAnalysisTaskSEHFQA.cxx
- PWGHF/vertexingHF/AliAnalysisTaskSEHFQA.h
Add histograms monitoring the primary vertex position for selected events with D mesons.
- When running on MC: histograms are filled if the event contains a true D meson (from MC truth).
- When running on Data: histograms are filled if the the D candidate pass through all the selection cuts (topo+PID) and if its reconstructed invariant mass is within +/- 40 MeV/c2 around the PDG value. Currently, it works only for D+ and D0.
> Primary vertex position for selected events with D mesons

- PWG/DevNanoAOD/AliAnalysisNanoAODCutsJet.cxx
- PWG/DevNanoAOD/AliAnalysisNanoAODCutsJet.h
- PWG/DevNanoAOD/CMakeLists.txt
- PWG/DevNanoAOD/PWGDevNanoAODLinkDef.h
- PWG/EMCAL/EMCALbase/AliAnalysisTaskEmcal.cxx
- PWGJE/EMCALJetTasks/AliNanoAODArrayMaker.cxx
- PWGJE/EMCALJetTasks/AliNanoAODArrayMaker.h
- PWGJE/EMCALJetTasks/CMakeLists.txt
- PWGJE/EMCALJetTasks/PWGJEEMCALJetTasksLinkDef.h
- PWGJE/EMCALJetTasks/macros/AddTaskArrayMaker.C
Hi all,
this pull request is a code change from Markus (Zimmermann) to allow my jet task (inheriting from the EMCalJet base task) to run on NanoAODs.
The work was done by Markus and his summer student Lucia, I am just supporting him from the EMCalJet/testing point-of-view and by spreading the word in the PWG.
This patch lays the ground also for other tasks inheriting from the EMCalJet base task to be in principle compatible to NanoAODs. More information on this will follow soon.
The changes in the underlying EMCalJet framework are just minor, so we foresee no problems.
> changes for the NanoAOD production of the PWGJEEMCAL tasks

- PWGUD/DIFFRACTIVE/CEPdevel/AliAnalysisTaskCEP.cxx
- PWGUD/DIFFRACTIVE/CEPdevel/AliAnalysisTaskCEP.h
- PWGUD/DIFFRACTIVE/CEPdevel/AliCEPBase.h
- PWGUD/DIFFRACTIVE/CEPdevel/AliCEPUtils.cxx
- PWGUD/DIFFRACTIVE/CEPdevel/CEPEventBuffer.cxx
- PWGUD/DIFFRACTIVE/CEPdevel/CEPEventBuffer.h
output include now:
. number of triggered OFO and IFO
. number of offline triggered SPD chips
. track has at least 1 SPD hit
. track passes standard TPCOnly track cuts
> include additional event and track information in output of AliAnalysisTaskCEP

- PWG/EMCAL/EMCALtasks/AliEmcalCorrectionTask.cxx
The update to the YAML configuration class didn't set the proper
conditions for retrieving the names with a required configuration. This
only showed up when specialized components were utilized.
@jdmulligan This fixes the embedding framework
> EMCal CorrFW: Fix specialized configurations

- PWGHF/hfe/AliHFEminiEvent.cxx
- PWGHF/hfe/AliHFEminiEvent.h
- PWGHF/hfe/AliHFEminiEventCreator.cxx
- PWGHF/hfe/AliHFEminiEventCreator.h
- PWGHF/hfe/AliHFEminiTrack.h
- PWGHF/hfe/CMakeLists.txt
- PWGHF/hfe/PWGHFhfeLinkDef.h
The compilation error due to class AliHFEminiTrack (forward declaration error) is now fixed.
> Bug fixed for AliHFEminiTrack.h

- PWGUD/DIFFRACTIVE/legotrain/AliAnalysisTaskDG.h
When an enum is used for specifying the length in std::fill_n it does not compile on mac yosemite, because enums cannot be incremented
> fix for max yosemite (2)

- PWG/EMCAL/EMCALbase/AliEmcalContainerUtils.cxx
- PWG/EMCAL/EMCALbase/AliEmcalContainerUtils.h
Adds a simple helper function which builds on the other "usedefault"
functionality, making the (often true) assumption that the file type can
be determined from an existing analysis manager
> EMCal FW: Add container usedefault utility

- PWGJE/EMCALJetTasks/macros/AddTaskEmcalJetHCorrelations.C
Update of my personal task.
The compiled AddTask was modified without modifying the corresponding pass
through call for the LEGO train.
> Match AddTask with compiled version

- PWGLF/RESONANCES/macros/mini/AddTaskF0.C
- PWGLF/RESONANCES/macros/mini/ConfigF0.C
Added switch for multiplicity selection in the AddTask.
Set 2011 standard quality cuts as default for run2 analysis.
Some minor cleanup and comments added.
> Updated event cuts for pp 5 TeV analysis and cleanup of the pA ones.

- PWGGA/EMCALTasks/AliAnalysisTaskGammaHadron.cxx
- PWGGA/EMCALTasks/AliAnalysisTaskGammaHadron.h
Add function to apply cuts for pi0 ID, including mass window function.
Add variable asymmetry cut.
Minor changes.
I think I changed some indentation too.
> Adding PiZero selection to Pi0-Hadron corr

- PWG/EMCAL/EMCALbase/AliMCParticleContainer.cxx
- PWG/EMCAL/EMCALbase/AliParticleContainer.cxx
- PWG/EMCAL/EMCALbase/AliTrackContainer.cxx
- PWG/JETFW/AliAnalysisTaskEmcalJet.cxx
The titles were not getting the current minimum pt setting correctly.
Separating the definition and assignment seems to resolve the issue.
This is particularly important as the titles are relied upon to find
jet collections.
Also updates the branches print out
> EMCAL: Fix EMCal container titles

- PWGUD/UPC/AliAnalysisTaskUpcEtaC.cxx
- PWGUD/UPC/AliAnalysisTaskUpcEtaC.h
Add EtaVsMinv histos for all channels with no Pt cut, Pt<0.4 GeV/c and Pt<0.1 GeV/c. Changed the K0s histo names to the same format as all the other channels. Changed one output histo name from "2KstarPtKMinus" to "f2KstarPtKMinus." For all channels, for new cuts in the next version, I added "SumPzVsMinvEtaC," "ScalarSumP" and "VectorSumPt" histos for future cuts and code to compute these quantities and also to count the number of tracks with Pt>0.4 GeV/c.
> Add EtaVsMinv histos, updated K0s histo names

- PWGHF/jetsHF/AliAnalysisTaskHFJetIPQA.cxx
Sorry for the followup patch. In the first version i accidentally "commented" not only the old  correlation study plots but also the new ones
> Disable unused histograms

- PWG/EMCAL/READMEemcCorrections.txt
The doxygen docs were truncated because doxygen cannot handle an anchor
unless there is one at each level. For example, if the header depth is
4, then there must be an anchor at depth 1, 2, _and_ 3. If not, it will
fail and truncated the document
> EMCal CorrFW: Fix doxygen truncation

- PWG/Tools/AliYAMLConfiguration.cxx
- PWG/Tools/AliYAMLConfiguration.h
The long description did not show up properly due to the
PWG::Tools namespace not being specified in the class description
> Fix doxygen docs for YAML config

- PWG/EMCAL/EMCALbase/AliEmcalTrackSelectionESD.cxx
- PWGJE/EMCALJetTasks/Tracks/AliAnalysisTaskEmcalJetSubstructureTree.cxx
- Add ITS stand alone track cuts to the AliEmcalTrackSelectionESD
- Move from hard coded container names to container names handled
by the EMCAL analysis factory in the jetsubstructuretree task
> Prepare jetfinding with ITS pure stand alone tracks

- PWGLF/STRANGENESS/Cascades/Run2/AliAnalysisTaskStrangenessVsMultiplicityRun2.cxx
- PWGLF/STRANGENESS/Cascades/Run2/AliAnalysisTaskStrangenessVsMultiplicityRun2.h
Added a new branch to the ttrees with the distance in BCs to the closest interaction around (past/future) the current event.
> Added IR info to ttrees for OOB pileup study

- PWG/EMCAL/macros/AddTaskEMCALTender.C
- TENDER/TenderSupplies/AliEMCALTenderSupply.cxx
- TENDER/TenderSupplies/AliEMCALTenderSupply.h
With this small addition, it is now possible to load a custom bad channel map for testing purposes. The previous feature to set a different path for all calibrations remains unchanged with this update.
> PWG/EMCAL and OADB/EMCAL: custom bad channel map feature added to EMCtender

- PWGGA/EMCALTasks/AliAnalysisTaskEMCALPhotonIsolation.cxx
In order to improve the efficiency calculation around the EG2/EG1 overlap energy, the cluster spectra with these two triggers were fitted by a gaussian around the trigger energy.
The mean values and sigmas were retrieved and implemented in the `MCSimTrigger()` method. Some cleaning has also been done.
> Refining the MCSimTrigger() method

- PWGHF/vertexingHF/AliCFTaskVertexingHF.cxx
- PWGHF/vertexingHF/AliCFTaskVertexingHF.h
- PWGHF/vertexingHF/AliCFVertexingHF2Prong.cxx
- PWGHF/vertexingHF/AliCFVertexingHFLctoV0bachelor.cxx
- PWGHF/vertexingHF/macros/AddTaskCFVertexingHF.C
- PWGHF/vertexingHF/macros/AddTaskCFVertexingHFLctoV0bachelor.C
Dear all,
These are changes to the D2H CF framework (not my private codes) as described below. Also, please wait for pushing until Andrea R gives green light. He told me he will have a look via e-mail. 
As we mentioned in the PWGHF, the large output size of CF tasks are creating merging problems on LEGO trains already for 2015 data. I (after the discussion with Alessandro, Andrea F, Andrea R, Francesco) made two changes : 
i) Addition of a falcon mode that is lighter than Snail and Cheetah
ii) Option to fill only (MCLimAcc, MCAcc, RecoPPR, RecoPID)
Currently, the changes are made only for Lc and D0. I am planning to proceed as follows:
1) upload the attached code to git (D0 and Lc->pK0s only. Using the falcon mode for other mesons/baryons results in AliFatal with an appropriate message.) …
> Changes to CF (Lc,D0) tasks: i) new Falcon mode ii) fill less steps

- PWGJE/EMCALJetTasks/UserTasks/AliAnalysisTaskSoftDrop.cxx
Add missing std:: to vector<fastjet::PseudoJet>
> Fix broken compilation under ROOT6 introduced in #3091

- PWGJE/macros/AddTaskPWG4HighPtTrackQA.C
- Add missing forward declaration, remove default parameters
from implementation
- Use TMacro instead of gROOT->LoadMacro
> Fixes for ROOT6

- PWGJE/PWGJE/AliPWG4HighPtTrackQA.cxx
Method to fill number of trials and pt-hard
was missing for AODs. The detection whether
the task is running on AODs is based on the
result of the MCEvent() function and does
not access the MC handler directly as in the
current implementation for ESDs.
> Fix filling number of trials for the case of AODs

- PWGHF/hfe/AliHFEminiEventCreator.cxx
TTree split level reverted back to the original value (from 99 to 0)
> slipt level of the tree reverted to previous value

- PWGJE/PWGJE/AliPWG4HighPtTrackQA.cxx
- PWGJE/macros/AddTaskPWG4HighPtTrackQA.C
The case of both hybrid tracks (2 bits set) was handled
improperly: By using TestFilterMask the check is done
for equalty (which means AOD tracks must have both
bits set in order to be accepted), which is impossible
for hybrid tracks (can only be of one type). Changed to
TestFilterBits, which selects tracks in case any of the
bits is set.
In addition adding new datasets from run2 to the configuration.
> Fix handling of filtermask

- PWGPP/CalibMacros/CPass1/AddTOFAnalysisTaskCalibTree.C
- PWGPP/TOF/AliTOFAnalysisTaskCalibTree.cxx
- PWGPP/TOF/AliTOFAnalysisTaskCalibTree.h
Adds new flags to AliTOFAnalysisTaskCalibTree for the quality of a hit (used in case of fSaveCoordinates, not in default invocation of task in calib train).
Also updates setting of time resolution in AddTask (updates default value to 60ps, and replaces redundant "GetTOFT0maker()->SetTimeResolution()" with "task->SetTimeResolution()" (as the value set in the TOFT0maker is anyway overwritten by fTimeResolution in the task::InitEvent() function).
> Add quality flags to TOF calibration tree task

- PWGPP/macros/AddTaskFilteredTree.C
* Needed to adjust downscaling for different generators resp, triggered samples
* MC - e,g for AliGenPerformance down-scaling factor 10 for low pt tracks instead of default factor 10^5 for minimum bias simulation
* Real data - for triggered data sample also factor ~ 10-100 instead of default 10^5
````
if (gSystem->Getenv("AliAnalysisTaskFilteredTree_SetLowPtTrackDownscalingF")) {
+    Float_t downscale=TString(gSystem->Getenv("AliAnalysisTaskFilteredTree_SetLowPtTrackDownscalingF")).Atof();
+    task->SetLowPtTrackDownscaligF(downscale);
+    printf("AliAnalysisTaskFilteredTree_SetLowPtTrackDownscalingF: From env. variable\t%f\n", downscale);
+  }
+  if (gSystem->Getenv("AliAnalysisTaskFilteredTree_SetLowPtV0DownscalingF")) {
+    Float_t …
```
> ATO-245: Possibility to change default downscale from env.varaible

- PWGCF/Correlations/DPhi/AliAnalysisTaskCorPIDTOFQA.cxx
- PWGCF/Correlations/DPhi/AliAnalysisTaskCorPIDTOFQA.h
In intend to use this skim to carefully test the results of DCA cut selection.  This course follows ANA-3952.
> relaxed DCA cut for fine-tuned analysis

- PWGHF/vertexingHF/AliAnalysisTaskSELc2V0bachelor.cxx
- PWGHF/vertexingHF/AliAnalysisTaskSELc2V0bachelor.h
- PWGHF/vertexingHF/AliRDHFCutsLctoV0.cxx
- PWGHF/vertexingHF/AliRDHFCutsLctoV0.h
Dear all, 
Background spectra generation with event-mixing and track-rotation techniques using AliAODTrack and AliAODv0 objects are implemented for Lc->pK0s analysis in Pb-Pb. 
Best regards,
Yosuke
> Implement (i) mixed event (ii) track rotation from track and v0

- PWGJE/EMCALJetTasks/CMakeLists.txt
- PWGJE/EMCALJetTasks/PWGJEEMCALJetTasksLinkDef.h
- PWGJE/EMCALJetTasks/UserTasks/AliEmcalJetTaggerTaskFast.cxx
- PWGJE/EMCALJetTasks/UserTasks/AliEmcalJetTaggerTaskFast.h
- PWGJE/EMCALJetTasks/macros/AddTaskEmcalJetTaggerFast.C
Re-implement AliAnalysisTaskEmcalJetTagger with
replacing the brute-force algorithm used for
geometric matching with a KD-tree based approach
(based on TKDTree).Also Remimplementation of the
true tag matching: Only 1 loop over base jets,
comparing match index in the arrays. Match function
is made atomic - only matching is handled, extra
parts like init and reset are moved to Run.
Some more fixes:
- Add new class to build
- Move from hand-made debug to AliDebug
- Factory function for adding the task and corresponding
macro added
> Implemeting jet tagger based on KD-trees

- PWGUD/UPC/AliAnalysisTaskUpcEtaC.cxx
- PWGUD/UPC/AliAnalysisTaskUpcEtaC.h
Looser PID now allows up to two tracks to be missing TOF info (3 tracks for 3PiPi case). Added new Dalitz plots for K0s, 4k and 4pi channels. Fixed a typo in 4k channel (nPion should have been nKaon). Fixed a logic error in K0s PID. The logic in that channel didn't always allow 1 track missing TOF info so it wasn't wrong just not as loose PID as I wanted before.
> Allow 2 tracks missing TOF info, new Dalitz plots, fix 4k channel

- PWGGA/EMCALTasks/macros/AddTaskEMCALPhotonIsolation.C
The change is necessary to run more then one instance of AliAnalysisTaskEMCALPhotonIsolation in one train over different cluster selections.
> Add cluster container name to output container

- PWG/EMCAL/EMCALtasks/AliEmcalCorrectionComponent.cxx
Add option to set "usedefault" in addition to "default" for setting the
MC pass. Remember not to see the pass for data!
> EMCal CorrFW: Additional pass option

- PWGCF/Correlations/DPhi/CMakeLists.txt
- PWGCF/Correlations/DPhi/PWGCFCorrelationsDPhiLinkDef.h
- PWGCF/Correlations/DPhi/Unfoldedhistos/AliAnalysisTaskCorrelationsStudies.cxx
- PWGCF/Correlations/DPhi/Unfoldedhistos/AliAnalysisTaskCorrelationsStudies.h
- PWGCF/Correlations/DPhi/Unfoldedhistos/AliCSAnalysisCutsBase.cxx
- PWGCF/Correlations/DPhi/Unfoldedhistos/AliCSAnalysisCutsBase.h
- PWGCF/Correlations/DPhi/Unfoldedhistos/AliCSEventCuts.cxx
- PWGCF/Correlations/DPhi/Unfoldedhistos/AliCSEventCuts.h
- PWGCF/Correlations/DPhi/Unfoldedhistos/AliCSPIDCuts.cxx
- PWGCF/Correlations/DPhi/Unfoldedhistos/AliCSPIDCuts.h
- PWGCF/Correlations/DPhi/Unfoldedhistos/AliCSPairAnalysis.cxx
- PWGCF/Correlations/DPhi/Unfoldedhistos/AliCSPairAnalysis.h
- PWGCF/Correlations/DPhi/Unfoldedhistos/AliCSTrackCuts.cxx
- PWGCF/Correlations/DPhi/Unfoldedhistos/AliCSTrackCuts.h
- PWGCF/Correlations/DPhi/Unfoldedhistos/AliCSTrackCutsBase.cxx
- PWGCF/Correlations/DPhi/Unfoldedhistos/AliCSTrackCutsBase.h
- PWGCF/Correlations/DPhi/Unfoldedhistos/AliCSTrackMaps.cxx
- PWGCF/Correlations/DPhi/Unfoldedhistos/AliCSTrackMaps.h
- PWGCF/Correlations/DPhi/Unfoldedhistos/AliCSTrackSelection.cxx
- PWGCF/Correlations/DPhi/Unfoldedhistos/AliCSTrackSelection.h
- PWGCF/Correlations/DPhi/Unfoldedhistos/AliDptDptCorrelations.cxx
- PWGCF/Correlations/DPhi/Unfoldedhistos/AliDptDptCorrelations.h
- PWGCF/Correlations/macros/Unfoldedhistos/AddCorrelationsStudiesTask.C
- PWGCF/Correlations/macros/Unfoldedhistos/CreateAlienHandler.C
- PWGCF/Correlations/macros/Unfoldedhistos/runCorrelationsStudiesConfigMacro.C
- PWGCF/Correlations/macros/Unfoldedhistos/runCorrelationsStudiesConfigMacro.H
- PWGCF/Correlations/macros/Unfoldedhistos/runCorrelationsStudiesTask.C
Two-particle number and transverse momentum correlations based in unfolded (eta1, eta2, phi1, phi2) data collection. Adapted to ESD and AOD format and automatically configured according to data taking period. Fully doxygen documented.
> Incorporated unfolded two-particle correlations

- PWGCF/FEMTOSCOPY/AliFemtoUser/AliFemtoConfigObject.cxx
There are two fixes included for two different issues.
- The boolean values are not correctly parsed: 'true' or 'false' are correctly taken as boolean but the parsing point is not progressed after taking them and an exception is thrown
- It is imposed a useless additional comma at the end of the map components if there are spaces before the right bracket: as an example, 
`"{type: \'AliFemtoAnalysisPionPion\' }"` throws an exception
`"{type: \'AliFemtoAnalysisPionPion\', }"` gets accepted
`"{type: \'AliFemtoAnalysisPionPion\'}"` gets accepted
> Wrong json string parsing

- PWGPP/EMCAL/AliAnalysisTaskEMCALAlig.cxx
- PWGPP/EMCAL/AliAnalysisTaskEMCALAlig.h
- PWGPP/EMCAL/PWGPPEMCALLinkDef.h
I have changed the output to trees instead of histograms. The total number of electrons is relatively small (for example ~270k electrons for 16k), so the tree output is still quite small. 
I need to change this to investigate if there is some pT (or any of the other cuts applied) in the matching residuals.
> Change output to tree

- PWG/FLOW/Tasks/AliAnalysisTaskZDCEP.cxx
- PWG/FLOW/Tasks/AliAnalysisTaskZDCEP.h
- PWGCF/FLOW/macros/AddTaskZDCEP.C
add various QA plots in a dedicated output container ("ZDCQA")
tested to be backward compatible
> add QA plots to ZDC EventPlane task

- PWG/EMCAL/EMCALtrigger/AliEmcalTriggerMakerTask.cxx
In case trigger maker has not been configured do not
set fLocalInitialized to false, as it will result in
running ExecOnce again for the next event, but rather
break the Run loop.
> Fix handling of unconfigured trigger maker

- PWGPP/EMCAL/AliAnalysisTaskEMCALAlig.cxx
- PWGPP/EMCAL/AliAnalysisTaskEMCALAlig.h
- PWGPP/EMCAL/macros/AddTaskEMCALAlig.C
I have updated the variable names to match the style as requested in #3338.
I have also changed the trees as a separate container, but they are always saved with the name declared in the task rather than the container name (is this the expected behaviour?). I have changed the names by adding a suffix. If there is a better way to do that, please let me know. But I need that the trees have different names in case I run more than one wagon at the same time.
Thanks!
> Update variable names and trees

- PWGPP/EVS/runLevelEventStatQA.C
Before, script ended, when T-mask class was not in a run. Now, when T-mask class is not in a run, the script will only skip the lines, which treat T-mask classes.
> T-mask treatment modified - better debugging

- PWGCF/Correlations/DPhi/Unfoldedhistos/AliDptDptCorrelations.cxx
- PWGCF/Correlations/macros/Unfoldedhistos/AddCorrelationsStudiesTask.C
Container names collide with other tasks container names which could cause troubles in LEGO train scenarios.
Also allow for more stringent z vertex cuts at the data collection level.
> Fix for colliding containers names

- PWGPP/ITS/AliMeanVertexPreprocessorOffline.cxx
Additionally, in case of cpass1 the updated object will take the range of run
for which the CalibObject is extrcted in case the object being updated is default one
> fix in fall-back to ITSSA vtx in absence of TRKvtx

- PWG/JETFW/AliJetContainer.cxx
- PWGJE/EMCALJetTasks/AliEmcalJetTask.cxx
- PWGJE/EMCALJetTasks/Tracks/AliAnalysisTaskEmcalJetSubstructureTree.cxx
- PWGJE/EMCALJetTasks/Tracks/AliAnalysisTaskEmcalJetSubstructureTree.h
- PWGJE/EMCALJetTasks/UserTasks/AliAnalysisTaskEmcalJetTagger.cxx
- Adapt jet container to generate proper name also for particle level neutral jets
- Add verbosity about jet branch names to AliEmcalJetTask
- Add AliDebugs to AliAnalysisTaskEmcalJetTagger
- Handle cases of failure of the Softdrop algorithm due to jets with single constituents only
> Fix handling of neutral jets

- PWG/FLOW/Tasks/AliAnalysisTaskZDCEP.cxx
- PWG/FLOW/Tasks/AliAnalysisTaskZDCEP.h
- PWGCF/FLOW/macros/AddTaskZDCEP.C
Change the ZDC Event Plane task to run over the muon_calo_pass1 dataset.
Customize the choice of the trigger.
> update ZDC EP task for muon_calo_pass1

- PWG/CaloTrackCorrBase/AliCaloTrackReader.cxx
- PWG/CaloTrackCorrBase/AliCaloTrackReader.h
- PWGGA/CaloTrackCorrelations/macros/AddTaskClusterShape.C
- PWGPP/EMCAL/AliAnalysisTaskEMCALClusterize.cxx
- PWGPP/EMCAL/AliAnalysisTaskEMCALClusterize.h
Allow in the clusterization task the creation of different cell branches  with different corrections like induced TCard correlations, so that the analysis with different corrections can be done in the same train job without disturbing each other.
Add access methods to such branches in the CaloTrack frame.
> Create a different cell branch with respect std one

- PWGHF/jetsHF/AliHFJetsContainer.cxx
- PWGHF/jetsHF/macros/AddTaskEmcalJetBtagSV.C
AliHFJetsContainer: number of mult bins decreased from 100 to 10 to shrink the output size.
AddTaskEmCalJetBtagSV: allow to set verbosity level in function call
> 10 cent bins to shrink output

- PWGGA/EMCALTasks/AliAnalysisTaskEMCALPhotonIsolation.cxx
- PWGGA/EMCALTasks/AliAnalysisTaskEMCALPhotonIsolation.h
Reordering of several data members in the `.h` and removal of several unused variables in `AnalyzeMC()` in the `.cxx`.
> Fixing compiler warnings

- PWGGA/EMCALTasks/AliAnalysisTaskEMCALPhotonIsolation.cxx
The `MCSimTrigger()` method is moved after the MC truth analysis so that the generated level histograms are no longer affected by the simulated trigger.
> Moving the L1 trigger mimicking and making some cleaning

- PWG/EMCAL/EMCALtasks/AliEmcalCorrectionComponent.h
- PWG/EMCAL/EMCALtasks/AliEmcalCorrectionTask.cxx
- PWG/EMCAL/EMCALtasks/AliEmcalCorrectionTask.h
Helper function which enables users to more easily access a
particular component, allowing them to access data such as the bad
channel map from an outside task.
@jdmulligan - I'm adding this helper function requested by @nschmidtALICE to access the EMCal RecoUtils (and therefore the bad channel map) from an outside task. Let me know if you have any thoughts!
> EMCal CorrFW: Helper for accessing component

- PWGCF/Correlations/DPhi/Unfoldedhistos/AliCSPairAnalysis.cxx
- PWGCF/Correlations/DPhi/Unfoldedhistos/AliDptDptCorrelations.cxx
- PWGCF/Correlations/DPhi/Unfoldedhistos/AliDptDptCorrelations.h
Today the results size is reduced by only incorporating half of the symmetrized data. 
For some particular tests the results should not be symmetrized so, the possibility of symmetrize data is made optional via a configuration parameter.
> Make optional the symmetrization for results size reduction

- PWG/FLOW/Tasks/AliAnalysisTaskZDCEP.cxx
- PWG/FLOW/Tasks/AliAnalysisTaskZDCEP.h
add extra Q-vector re-centering step: vs run number, centrality and z_vtx (only for muon_calo_pass1)
> update ZDC Event Plane task

- PWGJE/EMCALJetTasks/Tracks/AliEmcalAnalysisFactory.cxx
Hybrid definition targets on AODs mainly used in order to distinguish between with/without ITS-refit tracks in 2010. Hybrid definition is applied during filtering and cannot be expanded later (i.e. distinction will have no effect when using the 2011 hybrid definition)
> Adding various hybrid definitions for AODs

- PWG/FLOW/Tasks/AliAnalysisTaskCMEV0.cxx
- PWG/FLOW/Tasks/AliAnalysisTaskCMEV0.h
- PWGCF/FLOW/macros/AddTaskCMEV0.C
Bug fix for TPC Q-Vect (Remove |Qn| = 0 events).
> Bug fix for TPC Q-Vect

- PWGDQ/dielectron/core/AliDielectronMC.cxx
- PWGDQ/dielectron/core/AliDielectronMC.h
- PWGDQ/dielectron/core/AliDielectronVarManager.h
The approach in the DielectronMC class was to split a lot of functions in ESD and AOD cases in the function, with new functionalities of the classes this is no longer neccessary. Additionally functions where a split is needed to use the full power of the AliAODMCParticle are now splitted and triggered by the object argument.
> PWGDQ DielectronMC streamlined AliAODMCParticle usage

- PWGPP/TOF/AliTOFAnalysisTaskCalibTree.cxx
patch to ensure re-initialising fHitFlags[] to 0 for each event (previously was being kept from event to event).
[NB I don't know why git decided to flag the entire file as "changed", but the relevant edit is line 267]
> fix memory safety of fHitFlags in AliTOFAnalysisTaskCalibTree

- PWG/MCLEGO/Therminator2/gen_therm2.sh
Fixing an issue with Therminator2 packages not loading when executing the gen_therm2.sh script.
> Adding package loading for Therminator2 MC generation script

- PWG/EMCAL/EMCALbase/AliEmcalTrackSelectionAOD.cxx
- PWG/EMCAL/EMCALbase/AliTrackContainer.cxx
Pointer to local variable in loop over the track selections was passed to the combined track selection (introduced when fixing the compilation under ROOT5 when moving from std::vector to TObjArray).  Copy introduced and TObjArray made owner of the track selection result pointers. Eventually going to TClonesArray for more efficient memory handling.
> Fix passing track selection result

- PWGDQ/reducedTree/AliMixingHandler.cxx
- PWGDQ/reducedTree/AliMixingHandler.h
1) Allow more then 3 event observables to be used simultaneously for event categories
2) removed the hardcoded centrality, vertex, event plane categories
> Event mixing handler major update

- PWG/EMCAL/EMCALbase/AliEmcalTrackSelResultCombined.cxx
- PWG/EMCAL/EMCALbase/AliEmcalTrackSelResultCombined.h
- PWG/EMCAL/EMCALbase/AliEmcalTrackSelResultPtr.cxx
- PWG/EMCAL/EMCALbase/AliEmcalTrackSelResultPtr.h
- PWG/EMCAL/EMCALbase/AliEmcalTrackSelection.cxx
- PWG/EMCAL/EMCALbase/AliEmcalTrackSelectionAOD.cxx
- PWG/EMCAL/EMCALbase/AliEmcalTrackSelectionESD.cxx
- Move to TClonesArray for the combined track results
in order to reduce dynamic memory allocation
- Fixing memory leak (SetOwner missing for TObjArray
in both functions GetAcceptedTracks)
- Make storage suicide object: Once the ref count is 0
the storage deletes itself automatically, not handled
anymore by the pointers referencing it.
> TClonesArray / Fix memory leak

- PWG/EMCAL/EMCALbase/AliEmcalTrackSelResultPtr.cxx
Should have been part of the previous commit when changing storage handler to self-destruction, was lost somehow. Essential part of the reference counting.
> Add missing self-destruction

- PWG/EMCAL/EMCALbase/AliEmcalTrackSelection.cxx
- PWG/EMCAL/EMCALbase/AliEmcalTrackSelection.h
As discussed in #3612 GetAcceptedTracks should rather return
the selection status for all tracks in order to avoid gaps
in the track container.
> GetAcceptedTracks returning selection result for all tracks

- PWGCF/FEMTOSCOPY/AliFemtoUser/AliFemtoConfigObject.cxx
- PWGCF/FEMTOSCOPY/AliFemtoUser/AliFemtoConfigObject.h
- PWGCF/FEMTOSCOPY/AliFemtoUser/PWGCFfemtoscopyUserLinkDef.h
- Added new `list_begin(), list_end()` & `map_begin(), map_end()` methods for easy iteration over containers in for loops
- Added `items_in_list()` & `items_in_map()` methods for easy iteration in C++11 foreach loops
- Also cleaned and "standardized" more of the parsing code
> PWGCF: AliFemtoConfigObject - Improved iteration methods

- PWGCF/FEMTOSCOPY/AliFemtoUser/AliFemtoConfigObject.cxx
- PWGCF/FEMTOSCOPY/AliFemtoUser/AliFemtoConfigObject.h
* Added missing move-constructor method
* Added `Parse` method with explicit types for `const char*`, `TString`, & `TObjString`
* Removed use of `auto` which might have broken macros running on ROOT5
> PWGCF: AliFemtoConfigObject - Added Parse methods for more string types + move constructor

- PWG/EMCAL/EMCALbase/AliTrackContainer.cxx
- PWG/EMCAL/EMCALbase/AliTrackContainer.h
- PWGJE/EMCALJetTasks/macros/AddTaskEmcalQGTagging.C
- PWGJE/EMCALJetTasks/macros/AddTaskRhoMass.C
Fixing issue that GetAcceptedTracks returns also non-accepted tracks, introduced in #3702 (extra check needed as the track selection now returns the selection status of all tracks and not only the accepted tracks).
In addition two macros were made ROOT6-aware (mismatch in types + missing default arguments).
> Fix for GetAcceptedTracks + fixes of Add-macros for ROOT6

- TENDER/TenderSupplies/AliPHOSTenderSupply.cxx
- TENDER/TenderSupplies/AliPHOSTenderSupply.h
One member variable Int_t fRDN which is dummy run number to enable us to analyze single particle simulation have been introduced. As PHOS OCDB does not change in Run2, this modification allows us to analyze single particle simulation (for example LHC17i7[a,b,c][1,2]) for all period by reading proper OADB which one wants to use in PHOSTender.
> implement dummy run number to enable analysis of single particle simulation

- test/load_library/LoadLib.C
During the library load tests the system libraries path has to
be incorporated for them to be properly loaded.
> AliPhysics libraries might need system libraries

- CORRFW/AliCFGridSparse.cxx
In my analysis code I'm using many AliCFcontainer objects.
When changing the range for an axis, the method SetRangeUser prints on the screen a sentence like:
W-AliCFGridSparse::SetRangeUser: fCFContCascadeCuts_minnTPCcls70_vtxlim10.0-0.0_minptdghtrk0.0_etacutdghtrk0.8_revertex_nTPCcls70_SelStep0 new range: 0.0 < Dca(cascade daughters) (cm) < 2.0
As you can see only the first decimal digit is displayed. 
I need more digits to be displayed, to check the value of the cut applied.
> Increase digits in the output string SetRangeUser

- PWG/EMCAL/EMCALtasks/AliEmcalCorrectionClusterHadronicCorrection.cxx
- PWG/EMCAL/EMCALtasks/AliEmcalCorrectionClusterHadronicCorrection.h
Creates a mapping for tracks to their corresponding container in the
hadronic correction when running with AODs. AOD clusters only
provide pointers to tracks, so this map is necessary to select the
proper container, which allows the proper track
selection to be applied to each track. This is important if the
containers have different track selection conditions (as might happen
in, for example, embedding pp data into PbPb).
I've verified using the correction framework testing tools and comparison script
that this change doesn't modify the behavior of the correction when not
using embedding.
> EMCal CorrFW: Track to container map for had corr

- PWGGA/GammaConv/AliAnalysisTaskGammaCalo.cxx
- PWGGA/GammaConv/AliAnalysisTaskGammaCalo.h
- PWGGA/GammaConv/AliAnalysisTaskGammaCaloMerged.cxx
- PWGGA/GammaConv/AliAnalysisTaskGammaCaloMerged.h
- PWGGA/GammaConv/AliAnalysisTaskGammaConvCalo.cxx
- PWGGA/GammaConv/AliAnalysisTaskGammaConvCalo.h
- PWGGA/GammaConv/AliCaloPhotonCuts.cxx
- PWGGA/GammaConv/AliCaloPhotonCuts.h
- PWGGA/GammaConv/AliCaloTrackMatcher.cxx
- PWGGA/GammaConv/AliCaloTrackMatcher.h
- PWGGA/GammaConv/AliConvEventCuts.cxx
- PWGGA/GammaConv/AliConvEventCuts.h
- PWGGA/GammaConv/config/PWGGA_CF_config.yaml
- PWGGA/GammaConv/config/PWGGA_CF_config_MC.yaml
- PWGGA/GammaConv/macros/AddTask_GammaCaloMerged_pp.C
- PWGGA/GammaConv/macros/AddTask_GammaCalo_pPb.C
- PWGGA/GammaConv/macros/AddTask_GammaCalo_pp.C
- PWGGA/GammaConv/macros/AddTask_GammaConvCalo_pp.C
This pull request handles the full implementation of the correction framework in the conversion group tasks. 
Using the correction framework will require adding two AliEmcalCorrectionTasks. One with the name "defaultSetting" in order to properly obtain calibrated cells and another one named i.e. "S500A100". Possible configurations can be found in the yaml file. 
Furthermore, it is possible to use several clusterizers by simply adding more CorrectionTasks.
The clusters from the different settings can then be accessed via the last argument in our AddTasks (additionalTrainConfig) by setting it to i.e. "402_CFS500A100". The "CF" in front of the setting is required as it will otherwise not work.
> PWGGA/GammaConv: Full implementation of Correction Framework in tasks

- PWGCF/Correlations/macros/Unfoldedhistos/AddCorrelationsStudiesTask.C
It seems that the standard include paths are not ready at
AddTask macro execution time in train scenarios. They are in local
train test scenario!
> Rolling back the includes inclusion in AddTask macro

- PWGCF/FEMTOSCOPY/AliFemto/AliFemtoAnalysisAzimuthal.cxx
- PWGCF/FEMTOSCOPY/AliFemto/AliFemtoBaryoniaAnalysis.cxx
- PWGCF/FEMTOSCOPY/AliFemto/AliFemtoCutMonitorParticlePID.cxx
- PWGCF/FEMTOSCOPY/AliFemto/AliFemtoCutMonitorParticlePID.h
- PWGCF/FEMTOSCOPY/AliFemto/AliFemtoEventAnalysis.cxx
- PWGCF/FEMTOSCOPY/AliFemto/AliFemtoLikeSignAnalysis.cxx
- PWGCF/FEMTOSCOPY/AliFemto/AliFemtoSimpleAnalysis.cxx
- PWGCF/FEMTOSCOPY/AliFemtoUser/PWGCFfemtoscopyUserLinkDef.h
* "extern" uses of `FillHbtParticleCollection` are now const-correct
* `AliFemtoCutMonitorParticlePID::fIfUsePt` is initialized to false
* `std::pair<double, double>` removed from linkdef
> PWGCF: Fixed a missing symbol, uninitialized member, and redundent linkdef rule

- PWG/EMCAL/EMCALtasks/AliAnalysisTaskEmcalTriggerSelection.cxx
- PWGJE/EMCALJetTasks/Tracks/AliAnalysisTaskEmcalJetSubstructureTree.cxx
- PWGJE/EMCALJetTasks/Tracks/AliAnalysisTaskEmcalJetSubstructureTree.h
- In trigger selection task fix jet thresholds for 2016 pp
LHC16h-k
- In substructure tree task run MC trigger selection only
when an EMCAL trigger is in the selection string
-  In substructure tree task move from TString to std::string
/ std::stringstream (works a bit better with lldb/gdb)
> Fixes for EMCAL MC trigger selection

- PWGGA/GammaConv/macros/AddTask_GammaCaloMerged_pPb.C
- PWGGA/GammaConv/macros/AddTask_GammaCaloMerged_pp.C
- PWGGA/GammaConv/macros/AddTask_GammaCalo_PbPb.C
- PWGGA/GammaConv/macros/AddTask_GammaCalo_pPb.C
- PWGGA/GammaConv/macros/AddTask_GammaCalo_pp.C
- PWGGA/GammaConv/macros/AddTask_GammaConvCalo_PbPb.C
- PWGGA/GammaConv/macros/AddTask_GammaConvCalo_pPb.C
- PWGGA/GammaConv/macros/AddTask_GammaConvCalo_pp.C
This pull request modifies the calo addtasks to change the output filename if the correction framework is used. Filenames will be changes like this:
GammaCalo_402.root -> GammaCalo_402_S500A100.root
The same renaming is also done for the TList inside the root file.
> PWGGA/GammaConv: Modified Calo AddTasks to adjust output filename

- PWG/EMCAL/EMCALtrigger/AliEmcalTriggerDecisionContainer.h
- PWGJE/EMCALJetTasks/Tracks/AliAnalysisTaskEmcalJetSubstructureTree.cxx
- PWGJE/EMCALJetTasks/Tracks/AliAnalysisTaskEmcalJetSubstructureTree.h
List objects must overwrite Clear, otherwise TNamed::Clear is called (by the analysis manager or input handler) which resets the name of the list object.
In addition name of the trigger decision container in user task configurable.
> Prevent container name to be reset

- PWG/MCLEGO/CMakeLists.txt
- PWG/MCLEGO/Therminator2/apply_custom_config.py
- PWG/MCLEGO/Therminator2/gen_therm2.sh
This pull request adds the possibility to configure Therminator2 using custom parameters. It uses a python script to scan environment variables and set the key=value pairs in configuration files according to them.
The script works by scanning the configuration files line by line. When it finds a parameter_name=value pair, it checks if the corresponding THERM2_PARAMS_<parameter_name> env variable is set. If yes, the default value in the line is substituted for env variable value.
The scanning is first done on the general [events.ini](https://github.com/alisw/therminator/blob/alice/v2.0.3/events.ini) file. Then, according to the selected model, a proper .ini file in [fomodel](https://github.com/alisw/therminator/tree/alice/v2.0.3/fomodel) directory is changed.
An example of using the …
> Therminator2 parameters configuration

- PWGDQ/dielectron/core/AliAnalysisTaskElectronEfficiency.cxx
- PWGDQ/dielectron/core/AliAnalysisTaskElectronEfficiency.h
Give the possibility to calculate the single electron efficiency for electrons which does not form with their partner an invariant mass below fLimitmee. Per default this check if off so that nothing is changing for the users, if it does not see fCheckmee == kTRUE in his config file.
> Further check for the single electron efficiency

- PWGDQ/reducedTree/AliReducedAnalysisJpsi2ee.cxx
- PWGDQ/reducedTree/AliReducedAnalysisJpsi2eeCorrelations.cxx
- PWGDQ/reducedTree/macros/runAnalysisTrain.C
- fix in analysis task for use of trees w/o second track array
- slight modification of writing of histograms from tree to analysis output file
> PWGDQ/reducedTree: fix for use of old trees

- PWGGA/GammaConv/macros/AddTask_GammaCaloMerged_pPb.C
- PWGGA/GammaConv/macros/AddTask_GammaCaloMerged_pp.C
- PWGGA/GammaConv/macros/AddTask_GammaCalo_PbPb.C
- PWGGA/GammaConv/macros/AddTask_GammaCalo_pPb.C
- PWGGA/GammaConv/macros/AddTask_GammaCalo_pp.C
- PWGGA/GammaConv/macros/AddTask_GammaConvCalo_PbPb.C
- PWGGA/GammaConv/macros/AddTask_GammaConvCalo_pPb.C
- PWGGA/GammaConv/macros/AddTask_GammaConvCalo_pp.C
Naming scheme changed from this:
GammaConvCalo_301_S500A100.root
-> GammaConvCalo_301_S500A100
GammaConvCalo_301_S400A75.root
-> GammaConvCalo_301_S400A75
to this:
GammaConvCalo_301.root
-> GammaConvCalo_301_S500A100
-> GammaConvCalo_301_S400A75
Therefore the output filename stays the same whereas the different correction framework configurations are only added to the TList names inside of the file.
> PWGGA/GammaConv: Changed output file naming for correction framework files

- PWGDQ/reducedTree/AliAnalysisTaskReducedTreeMaker.cxx
- PWGDQ/reducedTree/AliMixingHandler.cxx
- PWGDQ/reducedTree/AliMixingHandler.h
- PWGDQ/reducedTree/AliReducedAnalysisJpsi2ee.cxx
- PWGDQ/reducedTree/AliReducedAnalysisJpsi2ee.h
- PWGDQ/reducedTree/AliReducedBaseTrack.cxx
- PWGDQ/reducedTree/AliReducedBaseTrack.h
- PWGDQ/reducedTree/AliReducedTrackCut.cxx
- PWGDQ/reducedTree/AliReducedTrackCut.h
- PWGDQ/reducedTree/AliReducedTrackInfo.h
- PWGDQ/reducedTree/AliReducedVarManager.cxx
- PWGDQ/reducedTree/AliResonanceFits.cxx
- PWGDQ/reducedTree/AliResonanceFits.h
- PWGDQ/reducedTree/macros/AddTask_iarsene_dstXeXe.C
- PWGDQ/reducedTree/macros/AddTask_iarsene_jpsi2ee_XeXe.C
- PWGDQ/reducedTree/macros/AddTask_iarsene_testTask.C
- PWGDQ/reducedTree/macros/runAnalysisTrain.C
AliReducedBaseTrack
Added a boolean flag to mark the track as pure MC truth particle
AliReducedTrackCut
Added possibility to cut on the MC flags of AliReducedBaseTrack
AliReducedTrackInfo
Small fix
AliReducedAnalysisJpsi2ee
Major update of Monte Carlo information handling which allows the study of multiple simultanoues
MC signals with their kine cuts and which can be set dynamically in the AddTask
AliMixingHandler
Small fix to allow adding variable binning also as doubles
AliAnalysisTaskReducedTreeMaker
Small fix to set the new boolean flag implemented for the base track;
The MC match map for signals is also written for reconstructed tracks
AliResonanceFits
Implemented setter for the MC signal shape;
Implemented getters to retrieve output information and histograms
AliReducedVarManager …
> Several changes

- PWGUD/DIFFRACTIVE/CEPdevel/AliAnalysisTaskCEP.cxx
- PWGUD/DIFFRACTIVE/CEPdevel/AliAnalysisTaskCEP.h
- PWGUD/DIFFRACTIVE/CEPdevel/AliCEPBase.h
- PWGUD/DIFFRACTIVE/CEPdevel/AliCEPUtils.cxx
- PWGUD/DIFFRACTIVE/CEPdevel/CEPEventBuffer.cxx
- PWGUD/DIFFRACTIVE/CEPdevel/CEPEventBuffer.h
- PWGUD/DIFFRACTIVE/CEPdevel/CEPTrackBuffer.cxx
- PWGUD/DIFFRACTIVE/CEPdevel/CEPTrackBuffer.h
the additional SPD parameters allow to study the SPD behaviour in detail, like ...
. ITS hits in all layers
. tracklets
. singles
. tracks associated with tracklets
. track used for vertex determination
> Aditional SPD information in CEPEventBuffer and CEPTrackBuffer

- PWG/EMCAL/EMCALtrigger/AliEmcalTriggerDecision.cxx
- PWG/EMCAL/EMCALtrigger/AliEmcalTriggerDecision.h
- PWG/EMCAL/EMCALtrigger/AliEmcalTriggerDecisionContainer.cxx
The promise that a TList will not delete objects
where it is not owner of seems to be invalid in
ROOT v6-12-04 as it tried to delete obeject in
a list where SetOwner was explicitly set to false.
When calling Clear it has to be protected with
the option "nodelete".
> Fix multiple-deletes for TList in ROOT v6-12-04

- PWGLF/RESONANCES/AliRsnCut.cxx
- PWGLF/RESONANCES/AliRsnCut.h
- PWGLF/RESONANCES/AliRsnCutEventUtils.cxx
- PWGLF/RESONANCES/AliRsnCutPID.cxx
- PWGLF/RESONANCES/AliRsnCutTrue.cxx
- PWGLF/RESONANCES/AliRsnCutTrue.h
- PWGLF/RESONANCES/AliRsnDaughter.cxx
- PWGLF/RESONANCES/AliRsnDaughter.h
- PWGLF/RESONANCES/AliRsnDaughterDef.h
- PWGLF/RESONANCES/AliRsnLoopDaughter.cxx
- PWGLF/RESONANCES/AliRsnLoopPair.cxx
- PWGLF/RESONANCES/AliRsnMiniOutput.h
- PWGLF/RESONANCES/AliRsnMiniPair.h
- PWGLF/RESONANCES/AliRsnMiniParticle.h
- PWGLF/RESONANCES/AliRsnPairDef.cxx
- PWGLF/RESONANCES/AliRsnPairDef.h
Consistently use Long_t everywhere for PDG code.
Also added fix for few compilation warnings.
> Bug fix: define PDGcode variables as Long_t instead of Short_t. 

- PWGDQ/dielectron/core/AliAnalysisTaskElectronEfficiency.cxx
Fix the selection of electrons and positrons in the invariant mass cut functions
> Fixing a bug in the selection of electrons and positrons

- PWGJE/EMCALJetTasks/Tracks/AliAnalysisTaskEmcalJetSubstructureTree.cxx
- PWGJE/EMCALJetTasks/Tracks/AliAnalysisTaskEmcalJetSubstructureTree.h
For jet substructure jets must have at least 1 constituent
for reclustering, consequently reclustering fails if one
only looks at charged / neutral constituents and has none
of that type's constituents. A preselection makes sure the
jet has at least one allowed constituent.
> Pre-select jets based on number of constituents

- PWGHF/jetsHF/AliAnalysisTaskHFJetIPQA.cxx
- PWGHF/jetsHF/AliAnalysisTaskHFJetIPQA.h
- PWGHF/jetsHF/macros/AddTaskHFJetIPQA.C
Add a switch to verify the extracted n1, n2, n3 correlation coefficents via fully stored information as opposed to the th2d
approach that might be affected by the binning
> Added tree option for correlations

- PWGLF/SPECTRA/PiKaPr/ITSsa/AliAnalysisTaskSEITSsaSpectra.h
Modification to permit the changing of the default settings of AliEventCuts event selection from the RunTask without modifying the task.
> AliEventCuts pointer accessible from outside

- PWGHF/jetsHF/AliAnalysisTaskJetExtractorHF.cxx
This code fixes a bug that potentially leads to seg. fault if the the particle has no mother.
> Additional check if particle has mother

- PWG/EMCAL/EMCALtasks/AliEmcalCorrectionCellCombineCollections.cxx
- PWG/EMCAL/EMCALtasks/AliEmcalCorrectionCellCombineCollections.h
- PWG/EMCAL/config/AliEmcalCorrectionConfiguration.yaml
There were some indexing bugs which prevented the cell collections from
being combined successfully. Those were fixed, with new functionality
added to verify they were successfully combined.
Note that the length of the combined array should always been the same
length as the combination of the lengths of the cell objects, but that
doesn't mean that the arrays are the same. This can only be verified by
checking each cell by hand.
cc: @jdmulligan
> EMCal Embed: Fix combining cell collections

- PWGJE/EMCALJetTasks/Tracks/AliAnalysisTaskEmcalJetSubstructureTree.cxx
- PWGJE/EMCALJetTasks/Tracks/AliAnalysisTaskEmcalJetSubstructureTree.h
With the trigger seleciton in addion to the
online trigger result a patch above threshold
is require. This is used to cleanup noisy
triggers and to overcome the configuration issue in LHC16l.
> Add option to use trigger selection for data

- PWGUD/UPC/AliAnalysisTaskUpcEtaC.cxx
For channels with a composite intermediate particle [2k*(892), 1k*(892), 2Rho0, K0s] I implemented a trick to improve the mass resolution of the EtaC candidate. For example, for the 1k* channel I now compute m[EtaC]=m[1k*k+pi-] - m[1k*]_candidate + m[1k*]_PDG. The uncertainty in the intermediate k* mass (due to width of k* peak) widens the Eta c peak. In this calculation that uncertainty of the k* mass cancels out to first order improving the mass resolution of the EtaC candidates.
> Implemented mass resolution improvement for some channels

- PWG/EMCAL/EMCALbase/AliAnalysisTaskEmcal.cxx
- PWG/EMCAL/EMCALtrigger/AliEmcalTriggerMakerTask.cxx
- PWGJE/EMCALJetTasks/Tracks/AliAnalysisTaskEmcalTriggerBase.cxx
It turned out that the double-delete issue with ROOT v6-12-04
appears for objects, in particular inheriting from TCollection,
which are bound to a TFile but not delete in the task destructor.
Once deleting them in the destructor the crash disappears.
This affects the destruction at the end of the ROOT session and
works as long as there is only one task writing to the same output
file. As soon as there is a second instance of a task (same task
or different) writing to the same output file the segfault reappears.
> [WIP] Fix needed to overcome double-delete issue with ROOT v6-12-04

- PWGPP/TOF/AddTaskTOFqaID.C
- PWGPP/TOF/AliAnalysisTaskTOFqaID.cxx
- PWGPP/TOF/AliAnalysisTaskTOFqaID.h
- PWGPP/TOF/trending/DrawTrendingTOFQA.C
- PWGPP/TOF/trending/MakeTrendingTOFQAv2.C
Added histograms for matching efficiency vs phi_TPCouter vs eta.
Consequently remove 1D plot for eta.
Few other improvements:
- streamline code for trd lists
- define histo ranges and binning as const members
- added method to sefine variable binning in pt
- fixed cosmetics for histogram axis labels
> Added histograms for matching efficiency vs phi_TPCouter vs eta.

- PWGCF/Correlations/JCORRAN/Pro/AliJJetJtAnalysis.cxx
- PWGCF/Correlations/JCORRAN/Pro/AliJJetJtAnalysis.h
Fixes a problem where background was incorrectly calculated for full jets when background region is outside EMCAL acceptance
> Background calculation check always against charged jets in jT analysis

- PWGHF/vertexingHF/AliAnalysisTaskSEImproveITS.cxx
Update all parameters ("standard" and "constrained") of ESD tracks after the smearing. Impact parameters are also updated.
> update standard ESD parameters after the smearing

- PWG/EMCAL/EMCALbase/AliClusterContainer.cxx
Please do not approve yet.
This commit fixes a bug in PR #2680: https://github.com/alisw/AliPhysics/commit/3374c97df3cd20a7d3623c4efaaa877e4c6a3ec7. The constant DBL_MIN gives the minimum positive float, not -infinity. This had the effect of rejecting clusters with M02=0 (which can amount to up to ~10% of clusters, depending on thresholds etc.). 
This affects EMCal analyses that do not apply an M02 cut (and which use cluster containers). In particular, full jet analyses by default do not apply an M02 cut. Analyzers should be aware that between Sep 21 and now, an M02 cut at M02=0 was applied by the cluster container, and that results should be re-run with the fix.
Note: A separate discussion should determine whether a small-M02 cut _should_ be applied in jet analyses, but at present the …
> Fix bug in cluster container that removes M02=0 clusters

- PWGJE/EMCALJetTasks/Tracks/AliAnalysisTaskEmcalJetConstituentQA.cxx
Move observable histograms to THnSparse addressing correlations:
- THnSparse per jet with ptjet, NEF, ncharged, nneutral
- THnSparse per charged with jetpt, NEF, ncharged, nneutral, ptch, z
- THnSparse per neutral with jetpt, NEF, ncharged, nneutral, Ehcorr,
Enlcorr, z
> Use THnSparse to correlate constituents observables

- PWGDQ/dielectron/LMEE/AliAnalysisTaskMLTreeMaker.cxx
- PWGDQ/dielectron/LMEE/AliAnalysisTaskMLTreeMaker.h
- PWGDQ/dielectron/core/AliDielectronTrackCuts.h
-  using cuts of cut based PbPb analysis in MLTreeMaker
-  adding AODFilterBit: kGlobalNoDCA=16 to AliDielectronTrackCuts (currently used in cut based PbPb analysis)
> Implementing Dielectron Framework Cuts to MLTreeMaker

- PWG/EMCAL/EMCALbase/AliClusterContainer.cxx
- PWG/EMCAL/READMEemcCorrections.txt
- PWG/JETFW/AliEmcalJet.h
The first `//` is eaten by doxygen in the EMCal corrections readme for
no apparent reason (as the exact same type of code is shown directly
below without the `//` being lost), so they are doubled up to ensure
that the comment is displayed properly.
Also fixes a few typos.
@jdmulligan - This fixes the issue that I commented on (although it's a rather ridiculous fix). Let me know if you have another idea - otherwise I will commit this
> Fix doxygen typos and issues

- PWGGA/PHOSTasks/PHOS_LHC16_pp/macros/AddAnalysisTaskPP.C
- PWGGA/PHOSTasks/PHOS_LHC16_pp/macros/AddTenderTaskCustomParameters.C
PHOS tender should be added to the separate wagon in lego trains. A new macro is needed to setup custom map of bad channels (will be useful for LHC17 QA analysis) and ZS threshold.
> Separate PHOSTender configuration from PHOS_LHC16_pp analysis setup

- PWG/FLOW/Tasks/AliFlowEventCuts.h
Keep V0C, V0A enums at end of list for back compatibility
> Keep V0C, V0A enums at end of list for back compatibility

- PWG/EMCAL/EMCALtasks/PWGEMCALtasksLinkDef.h
Add dictionary entry for AOD track to particle container map introduced
in a0e3356
> EMCal CorrFW: Fix dictionary warning

- PWGJE/EMCALJetTasks/Tracks/AliAnalysisTaskEmcalJetSubstructureTree.cxx
- PWGJE/EMCALJetTasks/Tracks/AliAnalysisTaskEmcalJetSubstructureTree.h
**Work in progress - don't merge**
Flat array no longer used. Instead the data is organized
in structures (partially using the structures used as
return data for the SoftDrop/N-subjettiness). Each
structure has a function LinJetTreeBranch to link its
variables to a branch in the output tree. The structures
are dynamic data members of the class, allocated in
UserCreateOutputObjects and deleted in the constructor.
> [WIP] Modular jet substructure tree

- PWG/EMCAL/EMCALtasks/AliEmcalCorrectionClusterNonLinearity.cxx
Typo introduced by 65da1fc95aaf9672ec1e27282875dd881b5a2144. The timing
label was fixed in the cell time calibration component, but missed in
the cluster non-linearity
> EMCal CorrFW: Fix typo

- PWG/Tools/AliYAMLConfiguration.h
Otherwise, TString cannot be encoded or decoded for use with
AliYAMLConfiguration
> Allow yaml-cpp to convert TStrings

- PWG/EMCAL/EMCALtasks/AliEmcalCorrectionCellEmulateCrosstalk.cxx
- PWG/EMCAL/EMCALtasks/AliEmcalCorrectionCellEmulateCrosstalk.h
- PWG/EMCAL/EMCALtasks/CMakeLists.txt
- PWG/EMCAL/EMCALtasks/PWGEMCALtasksLinkDef.h
- PWG/EMCAL/config/AliEmcalCorrectionConfiguration.yaml
Please do not approve yet.
@gconesab, @raymondEhlers: Here is an initial draft of the crosstalk emulation correction component. I didn't test it at all besides that it compiles and doesn't crash while running. That being said, the component is integrated into the correction framework and will run if you enable it in your user yaml file (see available configuration options and defaults in AliEmcalCorrectionConfiguration.yaml). The main function is Run().
A few notes:
- I removed all of the code about digits, and attempted to directly write new cells. I added two new functions AddInducedEnergiesToExistingCells() and AddInducedEnergiesToNewCells() to do this. Gustavo, I am not super familiar with how your code works, so please take a look here to see if it has the right idea. You should also …
> draft of crosstalk emulation correction component

- PWG/EMCAL/EMCALtasks/AliEmcalCorrectionCellCombineCollections.cxx
- PWG/EMCAL/EMCALtasks/AliEmcalCorrectionClusterNonLinearity.h
- PWG/EMCAL/EMCALtasks/AliEmcalCorrectionClusterizer.h
- PWG/EMCAL/EMCALtasks/AliEmcalCorrectionComponent.h
- PWG/EMCAL/EMCALtasks/AliEmcalCorrectionTask.cxx
- PWG/EMCAL/EMCALtasks/AliEmcalCorrectionTask.h
- PWG/EMCAL/READMEemcCorrections.txt
- PWG/EMCAL/READMEemcCorrectionsChange.txt
The YAML namespace is automatically linked at every mention of YAML,
which is desired, so it is disabled with "YAML" -> "%YAML" (the %
prevents linking)
> EMCal CorrFW: Update docs to avoid link to YAML NS

- PWG/EMCAL/EMCALtasks/AliEmcalCorrectionCellBadChannel.cxx
- PWG/EMCAL/EMCALtasks/AliEmcalCorrectionCellEmulateCrosstalk.cxx
- PWG/EMCAL/EMCALtasks/AliEmcalCorrectionCellEnergy.cxx
- PWG/EMCAL/EMCALtasks/AliEmcalCorrectionCellTimeCalib.cxx
- PWG/EMCAL/EMCALtasks/AliEmcalCorrectionClusterExotics.cxx
- PWG/EMCAL/EMCALtasks/AliEmcalCorrectionClusterHadronicCorrection.cxx
- PWG/EMCAL/EMCALtasks/AliEmcalCorrectionClusterNonLinearity.cxx
- PWG/EMCAL/EMCALtasks/AliEmcalCorrectionClusterTrackMatcher.cxx
- PWG/EMCAL/EMCALtasks/AliEmcalCorrectionComponent.cxx
This field is present for every component, so it should be handled in
the base class initialization instead of in each component
cc: @jdmulligan
> EMCal CorrFW: Move create histo init to base class

- PWG/EMCAL/EMCALbase/AliEmcalAODHybridTrackCuts.cxx
- PWG/EMCAL/EMCALbase/AliEmcalESDHybridTrackCuts.cxx
- PWG/EMCAL/EMCALbase/AliEmcalESDTrackCutsGenerator.cxx
- PWG/EMCAL/EMCALbase/AliEmcalESDTrackCutsGenerator.h
- PWG/EMCAL/EMCALbase/AliEmcalTrackSelectionESD.cxx
- PWG/EMCAL/EMCALbase/PWGEMCALbaseLinkDef.h
Hybrid tracks were selected but the payload
defining the hybrid track type was not attached
to the track selection result ptr. In this case
the track container is not able to distinguish
the hybrid track type and will reject all tracks.
The hybrid type is now attached in case the track
was selected as hybrid track.
The track cuts generator was up to now not using the
new hybrid cuts wrapper but instead defined hybrid
cuts as set of ESD cuts. Also in this case the payload
defining the hybrid track type was missing and the
distinction in the track container was imposible. The
different hybrid track types are however already
implemented, and selecting one of the types gives the
expected result. The track cuts generator was modified
to ues the hybrid cuts wrapper with the proper hybrid …
> Fix hybrid track selection on ESDs

- PWGPP/macros/AddTaskImpParResSparse.C
kNone option for SPD requirements in the ESD track cuts configuration added
> Adding kNone option for ESD track cuts configuration

- PWG/EMCAL/EMCALtasks/AliEmcalCorrectionCellEmulateCrosstalk.cxx
- PWG/EMCAL/EMCALtasks/AliEmcalCorrectionCellEmulateCrosstalk.h
- PWG/EMCAL/config/AliEmcalCorrectionConfiguration.yaml
As promised in #4178, this PR allows array initialization for the new crosstalk correction. This configuration was a bit more complicated than usual, but a little templates magic makes it work and should be fairly intuitive. I tried to document it and configure it as you have in your .C, but both should be checked more closely. Please let me know if it is unclear.
cc: @gconesab , @jdmulligan
> EMCal CorrFW: Add config for crosstalk task

- PWG/EMCAL/EMCALtasks/AliEmcalCorrectionCellEmulateCrosstalk.cxx
- PWG/EMCAL/EMCALtasks/AliEmcalCorrectionCellEmulateCrosstalk.h
- PWG/EMCAL/config/AliEmcalCorrectionConfiguration.yaml
- Fix major bug, reset of temporal arrays with induced energy per channel at the end of the event
- Minor fixes like double semicolon and printf instead of AliInfo when print parameters is requested
- Add author mail
-Set default value for energy conservation as true
> Final corrections to Cross Talk emulation component

- PWG/EMCAL/EMCALbase/AliAnalysisTaskEmcal.cxx
- PWG/EMCAL/EMCALbase/AliAnalysisTaskEmcal.h
- PWG/EMCAL/EMCALbase/AliAnalysisTaskEmcalEmbeddingHelper.cxx
- PWG/EMCAL/EMCALbase/AliAnalysisTaskEmcalEmbeddingHelper.h
- PWG/EMCAL/EMCALbase/CMakeLists.txt
- PWG/EMCAL/EMCALtasks/AliEmcalCorrectionTask.cxx
- PWG/EMCAL/EMCALtasks/AliEmcalCorrectionTask.h
- PWG/EMCAL/READMEemcEmbedding.txt
- PWG/EMCAL/config/AliEmcalCorrectionConfiguration.yaml
__Work in Progress! Please do not commit!__
Previously, good embedded events were lost when the internal event
was outside of, for example, the desired centrality range. Now,
the user should check for
`AliAnalysisTaskEmcalEmbeddingHelper::GetIstance()->IsGoodEvent()`
to ensure that the internal event passes event selection and that
the embedded event was embedded successfully. If the internal event
did not pass event selection, the embedded event is saved for the
next internal event.
The code should be ready for code review, but it is still undergoing some
testing. @aiola - Would you mind reviewing this code? I think this simple solution is
fine, but I would appreciate another set of eyes which is familiar with the embedding
framework!
> [WIP] EMCal Embed: Internal event selection

- PWGPP/TPC/macros/AddTaskPerformanceTPCdEdxQA.C
ROOT 5 does not like `const char *` even if it is the right thing to do
> Make a TPC QA macro compatible with ROOT5/6

- PWG/EMCAL/EMCALbase/AliAnalysisTaskEmcalEmbeddingHelper.cxx
- PWG/EMCAL/EMCALbase/AliAnalysisTaskEmcalEmbeddingHelper.h
When file access was checked in SetupInputFiles(), it would cause
unnecessary load to the grid due to AccessPathName calling a command in
xalienfs (`gapi_stat()`), which then performed an `ls -l` on every
single directory. If we instead move it to Initialize(), such checks
will only have to be performed once.
cc: @jdmulligan
> EMCal Embed: Move file access check to Initialize

- PWG/EMCAL/EMCALbase/AliAnalysisTaskEmcalEmbeddingHelper.cxx
- PWG/EMCAL/EMCALbase/AliAnalysisTaskEmcalEmbeddingHelper.h
- PWG/EMCAL/READMEemcEmbedding.txt
Allows the embedding helper to be almost entirely configured from YAML.
Also adds documentation on usage of YAML with the embedding helper
@jdmulligan
> EMCal Embed: Add yaml config and docs

- PWGLF/STRANGENESS/Cascades/Run2/AliAnalysisTaskStrangenessVsMultiplicityMCRun2.cxx
- PWGLF/STRANGENESS/Cascades/Run2/AliAnalysisTaskStrangenessVsMultiplicityMCRun2.h
- PWGLF/STRANGENESS/Cascades/Run2/AliAnalysisTaskStrangenessVsMultiplicityRun2.cxx
- PWGLF/STRANGENESS/Cascades/Run2/AliAnalysisTaskStrangenessVsMultiplicityRun2.h
New branches added to keep the information of TOF signal for each daughter track for both V0s and Cascades.
> Added branches to store TOF signal for V0s and Cascades daughters

- OADB/EMCAL/READMEoadb.txt
This is a necessary update of the README file for the emcal OADB. The instructions for local download were not properly described before.
The file has also been renamed.
> OADB/EMCAL: Update of README for OADB

- PWG/EMCAL/EMCALbase/AliAnalysisTaskEmcal.cxx
Using always pt-hard bin from filename in histograms relevant for
merging. Reason: Insufficient precision in variable used for the
pt-hard value (float) leading to migration into the lower bin for
pt-hard values close to the bin limits, for which weights in the
reweighting get screwed up.
> Use always pt-hard bin from filename

- OADB/EMCAL/READMEoadb.txt
- PWG/EMCAL/READMEcorefw.txt
- doxygen/Doxyfile.in
Linking doxypage with description about accessing the EMCAL
OADB under the EMCAL core framework.
> Including desciption about EMCAL OADB in doxygen

- PWGPP/CalibMacros/CPass0/AddTaskT0Calib.C
- PWGPP/CalibMacros/CPass0/AddTaskTPCCalib.C
- PWGPP/CalibMacros/CPass0/AddTaskTRDCalib.C
- PWGPP/CalibMacros/CPass0/ConfigCalibTrain.C
To be able to work with ROOT6, some fixes to the AddTaskXXX macros were needed. They are typically sort of bug fixes.
> Several fixes for ROOT6

- PWGDQ/dielectron/LMEE/AliAnalysisTaskMLTreeMaker.cxx
- PWGDQ/dielectron/macrosLMEE/Config_miweber_LMEE_PbPb_woCutLib.C
implement cuts used for NanoAOD filtering, need to be applied in AnalysisTaks when running on MC (MC is not NanoAOD)
> implement cuts used for NanoAOD filtering

- PWG/EMCAL/EMCALbase/AliEmcalList.cxx
In the automatic scaling, do not scale the following histograms:
fHistTrials, fHistXsection, fHistEvents, fHistTrialsAfterSel, fHistXsectionAfterSel, fHistEventsAfterSel.
They might be needed for QA purposes.
> Automatic pthard scaling: Do not scale further QA histograms

- PWGUD/UPC/AliAnalysisTaskTOFTrigger.cxx
if N tracks cross a TOF maxi-pad, TEfficiency is filled N times as before
> restored old behavior

- PWGJE/EMCALJetTasks/UserTasks/AliAnalysisTaskEmcalJetHCorrelations.cxx
- PWGJE/EMCALJetTasks/UserTasks/AliAnalysisTaskEmcalJetHCorrelations.h
The requirement of a minimum amount of shared momentum fraction
is in addition to already requiring jets to match geometrically
NOTE: This first iteration will currently only work with
embedding real pp data.
> Allow minimum shared momentum fraction

- PWGHF/vertexingHF/AliRDHFCuts.cxx
- PWGHF/vertexingHF/AliRDHFCuts.h
Possibility to configure the multi-vertexer (MV) in the RDHF cut objects. So far the MV settings were always the same, namely the one tuned for p-Pb 2013 (https://twiki.cern.ch/twiki/bin/view/ALICE/AliDPGtoolsPileup), and could not be changed.
**Important points:**
The default value of the Chi2/ndf data member 'fMaxVtxRedChi2', useful for the MV but not used in D2H framework (_as far as I can see!_), has been changed from 1e6 to 5 (the default MV value).
Could you confirm that the change of the fMaxVtxRedChi2 default value will not affect our analyses? Otherwise an additional data member, dedicated to the MV, could be created.
Cheers,
Julien
> Possibility to change the multi-vertexer settings

- PWGLF/SPECTRA/ChargedHadrons/dNdPt/AlidNdPtTrackDumpTask.cxx
- PWGPP/AliAnalysisTaskFilteredTree.cxx
- PWGPP/AliTrackComparisonESD.cxx
- PWGPP/TPC/AliMaterialBudget.cxx
- PWGPP/TPC/AliPerformanceRes.cxx
- PWGPP/TPC/AliPerformanceTPC.cxx
- PWGPP/TRD/AliTRDinfoGen.cxx
The friend and esd tracks have no one to one mapping in the offline ESDs, the correct way of
obtaining the friend for given esdTrack is esdTrack->GetFriendTrack().
Direct acces via esdFriendEvent->GetTrack(i) is not guaranteed to return the friend for esdTrack i
> Obtain friendTrack via esdTrack only

- PWGCF/FEMTOSCOPY/AliFemtoUser/AliFemtoAnalysisPionPion.cxx
- PWGCF/FEMTOSCOPY/AliFemtoUser/AliFemtoAnalysisPionPion.h
* Fixed incorrect names in `assert` statements
* Static "default" cut-configuration parameters removed in favor of constructor initialization
> PWGCF: AliFemtoAnalysisPionPion - Name errors and dead code

- PWGLF/STRANGENESS/Cascades/Run2/AliAnalysisTaskStrEffStudy.cxx
- PWGLF/STRANGENESS/Cascades/Run2/AliAnalysisTaskStrEffStudy.h
Included new branches in the TTrees for V0s and Cascades in order to store the measured TOF signal for the daughter tracks.
> Added branches to store TOF signal for the daughter tracks

- PWGCF/FEMTOSCOPY/AliFemto/AliFemtoBasicEventCut.h
- PWGCF/FEMTOSCOPY/AliFemto/AliFemtoEventCut.h
- PWGCF/FEMTOSCOPY/AliFemto/AliFemtoEventCutEstimators.cxx
- PWGCF/FEMTOSCOPY/AliFemto/AliFemtoEventCutEstimators.h
- PWGCF/FEMTOSCOPY/AliFemto/AliFemtoSphericityEventCut.cxx
- PWGCF/FEMTOSCOPY/AliFemto/AliFemtoSphericityEventCut.h
- PWGCF/FEMTOSCOPY/AliFemto/AliFemtoSpherocityEventCut.h
- PWGCF/FEMTOSCOPY/AliFemtoUser/AliFemtoEventCutCentrality.h
- PWGCF/FEMTOSCOPY/AliFemtoUser/AliFemtoQAEventCut.cxx
- PWGCF/FEMTOSCOPY/AliFemtoUser/AliFemtoQAEventCut.h
* Copy-constructors take a *constant* reference to the original object
* The `Clone()` method is marked virtual and constant and returns a standard `AliFemtoEventCut` pointer rather than the subclass
* Trailing whitespace remove automatically
> PWGCF: AliFemtoEventCut - Standarized `Clone` method

- PWGUD/UPC/AddTaskUpcEtaC.C
- PWGUD/UPC/AliAnalysisTaskUpcEtaC.cxx
- PWGUD/UPC/AliAnalysisTaskUpcEtaC.h
This version has a lower ZDC energy cut (<1190) and some new ZDC histograms. It is a version with the helicity cut turned off and looser PID (allowing up two two tracks to be missing TOF information).
> Added lower ZDC energy cut (0n0n) and new ZDC histograms

- PWG/JETFW/AliJetContainer.cxx
- PWGJE/EMCALJetTasks/CMakeLists.txt
- PWGJE/EMCALJetTasks/PWGJEEMCALJetTasksLinkDef.h
- PWGJE/EMCALJetTasks/UserTasks/AliAnalysisTaskEmcalJetHBase.cxx
- PWGJE/EMCALJetTasks/UserTasks/AliAnalysisTaskEmcalJetHBase.h
- PWGJE/EMCALJetTasks/UserTasks/AliAnalysisTaskEmcalJetHCorrelations.cxx
- PWGJE/EMCALJetTasks/UserTasks/AliAnalysisTaskEmcalJetHCorrelations.h
- PWGJE/EMCALJetTasks/UserTasks/AliAnalysisTaskEmcalJetHPerformance.cxx
- PWGJE/EMCALJetTasks/UserTasks/AliAnalysisTaskEmcalJetHPerformance.h
- PWGJE/EMCALJetTasks/UserTasks/AliAnalysisTaskEmcalJetHUtils.cxx
- PWGJE/EMCALJetTasks/UserTasks/AliAnalysisTaskEmcalJetHUtils.h
- PWGJE/EMCALJetTasks/macros/AddTaskEmcalJetHCorrelations.C
Includes:
- Move Correlations task to PWGJE::EMCALJetTasks
- Preserve axis order in the Performance task (following the order that they are defined in YAML)
- Performance task bug fixes
- Move to custom retrieval of leading hadron momentum to ensure that the proper cluster momentum is selected
- Add documentation on cluster energy (it only retrieves the raw E()) to leading hadron momentum function in the Jet FW
> Improvements to jet-hadron correlations and performance tasks

- PWGJE/EMCALJetTasks/UserTasks/AliAnalysisTaskEmcalJetHUtils.cxx
It still included the desired header eventually, but also added an
undesired dependence on fastjet
> Fix includes typo

- PWGJE/EMCALJetTasks/UserTasks/AliAnalysisTaskEmcalJetTagger.cxx
- PWGJE/EMCALJetTasks/UserTasks/AliEmcalJetTaggerTaskFast.cxx
The tasks use `AliEmcalJet::TrackAt(int index, TClonesArray * tracks)`,
with the particles accessed via the particle container attached to the
jet container. This will cause harmless warnings (the proper particle
is _always_ returned) as explained in the docs of `AliEmcalJet` and
of the embedding framework. However, the tasks should be updated to
silence these warnings under the new embedding framework.
This update causes no change in functionality.
Two compiler warnings for unused variables are also fixed.
@lcunquei , @mfasDa I'm switching over to these classes to better handle jet matching and cut on the shared momentum fraction. This modification is trivial, but allows the use of these classes without warnings under the new embedding framework. If possible, I'd like to get this into …
> EMCal Embed: Update jet taggers

- PWGCF/FEMTOSCOPY/PLamAnalysisPP/AddTaskPLFemto.C
- PWGCF/FEMTOSCOPY/PLamAnalysisPP/AliAnalysisTaskPLFemto.cxx
- PWGCF/FEMTOSCOPY/PLamAnalysisPP/AliAnalysisTaskPLFemto.h
- PWGCF/FEMTOSCOPY/PLamAnalysisPP/AliFemtoCutValues.cxx
- PWGCF/FEMTOSCOPY/PLamAnalysisPP/AliFemtoCutValues.h
- PWGCF/FEMTOSCOPY/PLamAnalysisPP/AliFemtoLambdaEvent.cxx
- PWGCF/FEMTOSCOPY/PLamAnalysisPP/AliFemtoLambdaEvent.h
- PWGCF/FEMTOSCOPY/PLamAnalysisPP/AliFemtoLambdaEventCollection2.cxx
- PWGCF/FEMTOSCOPY/PLamAnalysisPP/AliFemtoLambdaEventCollection2.h
- PWGCF/FEMTOSCOPY/PLamAnalysisPP/AliFemtoLambdaParticle.cxx
- PWGCF/FEMTOSCOPY/PLamAnalysisPP/AliFemtoLambdaParticle.h
- PWGCF/FEMTOSCOPY/PLamAnalysisPP/AliFemtoProtonParticle.cxx
- PWGCF/FEMTOSCOPY/PLamAnalysisPP/AliFemtoProtonParticle.h
- PWGCF/FEMTOSCOPY/PLamAnalysisPP/AliFemtoXiParticle.cxx
- PWGCF/FEMTOSCOPY/PLamAnalysisPP/AliFemtoXiParticle.h
- PWGCF/FEMTOSCOPY/PLamAnalysisPP/CMakeLists.txt
- PWGCF/FEMTOSCOPY/PLamAnalysisPP/PWGCFPLamAnalysisPPLinkDef.h
- PWGCF/FEMTOSCOPY/macros/AddTaskPLFemtoRun2.C
o Run1 part left intact, can be configured with the SetRun1 flag
o Usage of AliEventCuts for event selection
o Inclusion of high multiplicity events possible
o Multiplicity binning for the correlation function
o Pile-up rejection for the V0 daughters
> Update Run1 Proton-Lambda femto analysis code for Run2 analysis

- PWGUD/UPC/AliAnalysisTaskUpcEtaC.cxx
Changed to look at XnXn. After looking at full statistics from previous run there was a better value for the ZDC energy limits.
> Version for ZDC study (XnXn) and changed ZDC limits after full stats

- PWGJE/EMCALJetTasks/CMakeLists.txt
- PWGJE/EMCALJetTasks/PWGJEEMCALJetTasksLinkDef.h
- PWGJE/EMCALJetTasks/Tracks/AliAnalysisTaskEmcalJetEnergyScale.cxx
- PWGJE/EMCALJetTasks/Tracks/AliAnalysisTaskEmcalJetEnergyScale.h
- PWGJE/EMCALJetTasks/macros/AddTaskEmcalJetEnergyScale.C
Add lightweight task for jet energy scale filling only two
THnSparses
- correlation between part and det jet pt
- difference between part and det jet pt
Det NEF included in task for NEF cuts.
For configuration the task needs
- Jet type (charged, full, neutral)
- Jet radius
- Trigger (INT7 or EMCAL jet trigger)
> [JES] Add lightweight task for jet energy scale

- PWG/JETFW/AliEmcalJet.cxx
- PWGJE/EMCALJetTasks/Tracks/AliAnalysisTaskEmcalJetSubstructureTree.cxx
- PWGJE/EMCALJetTasks/Tracks/AliAnalysisTaskEmcalJetSubstructureTree.h
Use const auto & in range-based for loop in order to
prevent copying which would result in a pointer to a
local variable.
Fixing #4499
> [Bugfix] Handling of return address for leading constituents

- PWG/JETFW/AliJetContainer.cxx
- PWGJE/EMCALJetTasks/UserTasks/AliAnalysisTaskEmcalJetHPerformance.cxx
- PWGJE/EMCALJetTasks/UserTasks/AliAnalysisTaskEmcalJetHUtils.cxx
Update method committed in #4499 since the standard method was fixed
in #4522. Also update docs in the jet container to better describe
various options to retrieve the leading hadron momentum.
Thanks @mfasDa for the fix!
> Update leading hadron calculation and docs

- PWG/EMCAL/EMCALtasks/PWGEMCALtasksLinkDef.h
Add dictionary entry for pair of AOD track and particle container.
Introduced in a0e3356 and partially fixed in 8de9429.
> EMCal CorrFW: Fix additional dictionary warning

- PWGUD/UPC/AliAnalysisTaskUpcEtaC.cxx
New version for ZDC study using 1500 as the ZDC energy threshold for 0n. In this version ZDCAenergy <1500 and ZDCCenergy < 1500 to select 0n0n.
> Version with new 0nX0n selection (Ezdc < 1500)

- PWG/EMCAL/EMCALbase/AliClusterContainer.cxx
- PWG/EMCAL/EMCALbase/AliClusterContainer.h
- PWG/EMCAL/EMCALbase/AliEmcalContainerUtils.cxx
- PWG/EMCAL/EMCALbase/AliEmcalContainerUtils.h
- PWG/EMCAL/EMCALbase/AliTrackContainer.cxx
- PWG/EMCAL/EMCALbase/AliTrackContainer.h
- PWG/EMCAL/EMCALtasks/AliEmcalCorrectionTask.cxx
- PWG/EMCAL/EMCALtasks/AliEmcalCorrectionTask.h
String to enum maps are used for accessing them in YAML configuration
files. The following maps are refactored to allow for more general use:
- Cluster default energy
- Track selection
Additionally, a map is added for physics selection, allowing easier
configuration of tasks.
I plan to commit this right before the tag, but code review is appreciated!
> EMCal CorrFW, YAML: Refactor, add string to enum maps

- OADB/COMMON/MULTIPLICITY/AliMultSelectionTask.cxx
Additional info about the production name and whether the calibration OADB exists for the run being analyzed were included in the title of the QA fHistEventCounter histogram for future reference.
> Included additional info in QA histogram title for reference

- PWG/EMCAL/EMCALtasks/AliAnalysisTaskEmcalTriggerSelection.cxx
- PWG/EMCAL/EMCALtasks/AliAnalysisTaskEmcalTriggerSelection.h
Add 2012 triggers and a predefined list of supported dataset.
Include 2017 and 2018 pp in the run2 pp definition.
Improve documentation of the task.
> [feature,doxygen] Add pp 2012 triggers + document task

- PWGCF/FEMTOSCOPY/FemtoDream/AliFemtoDreamCorrHists.cxx
- PWGCF/FEMTOSCOPY/FemtoDream/AliFemtoDreamTrack.cxx
- PWGCF/FEMTOSCOPY/FemtoDream/AliFemtoDreamv0.cxx
- PWGCF/FEMTOSCOPY/macros/AddTaskFemtoContributionSplitting.C
- PWGCF/FEMTOSCOPY/macros/AddTaskFemtoDream.C
- PWGCF/FEMTOSCOPY/macros/AddTaskFemtoDreamSysVar.C
Wrong order of initialization in the CorrHists caused undefined behaviour. Improvement of the handeling of the too small global track array size, only a warning will be thrown and the task will still run. The track and v0 candidates are rejected then.
> Global Track Array Changes and Minimal Booking

- PWGJE/EMCALJetTasks/Tracks/AliAnalysisTaskEmcalClustersRef.cxx
- PWGJE/EMCALJetTasks/Tracks/AliAnalysisTaskEmcalClustersRef.h
-  Get selected patches from the trigger selection
task (must always run)
- Make correlation cluster energy - tag patch
energy: From multiple patches matched to a
cluster the leading patch is selected
> [Feature] Add cluster-patch tagging

- PWGGA/PHOSTasks/CaloCellQA/AliAnalysisTaskCaloCellsQA.h
Now it's impossible to update `AliCaloCellsQA` without copying the existing code. The `private` hides the variables so they can't be accessed in derived (child) classes.
> Change access specifier to access AliCaloCellsQA field in derived classes

- PWGPP/TOF/AddTaskTOFqaID.C
Hello,
There was a mistake in building the name of the output. This is from the attempt to fix the previous version of the macro.
@njacazio , @fbellini : can you check how you wanted to use the "partName"? I have a proposal commented out in the macro, which I am not committing as I might then break the post-processing. Please, change if needed, now the output will be called as before.
Chiara
> Fixing output name

- PWG/EMCAL/EMCALtasks/AliAnalysisTaskEmcalTriggerSelection.cxx
- PWGJE/EMCALJetTasks/Tracks/AliAnalysisTaskEmcalClustersRef.cxx
Small bugs (improper call of config function for periods)
prevented configuration of the matching period after the
recent update for pp 2012 and 2017/18.
In addition further cross check for for availability of
trigger decision objects in cluster task
> [Hotfix] Fix auto-configuration for periods

- PWG/MCLEGO/Herwig/LHC-MB.tmpl
- PWG/MCLEGO/Herwig/generate_matchbox_from_template.py
Matchbox files contain several keys which need to be handled on-
the-fly (number of events, random seed). The easiest solution
to configure matchbox file from static and dynamic settings is
treating Matchbox.in files as JINJA templates with the JINJA
conventions and use a small python script called in gen_herwig.C
to create the Matchbox.in file from the Matchbox.tmpl file.
For configuration settings the python script assumes the AliDPG
naming convention (global variables, starting with CONFIG_).
Attention: The script should be called on the workers. Requires
the python package JINJA to be installed on the grid sides. The
commit here represents only an example at the current stage and
might not work on every grid site.
> Herwig: Automatic matchbox file generation from template with JINJA

- OADB/EMCAL/READMEoadb.txt
Please use the different global variable to access the OADB files as with OADB_PATH several people ran into problems with the PhysicsSelection.
Please use:
ALICE_DATA=/path/to/my/local/oadb
instead of:
OADB_PATH=/path/to/my/local/oadb/OADB
> OADB/EMCAL: IMPORTANT change to OADB instructions for EOS

- PWG/EMCAL/EMCALtasks/AliEmcalCorrectionCellEnergy.cxx
- TENDER/TenderSupplies/AliEMCALTenderSupply.cxx
It has been observed that the tender and the correction framework
leak ~100 MB once a run is changed, leading to problems for jobs
processing multiple runs. 70% of the leaking is produced from
loading of the temperature recalibration. As the temperature
recalibration is not used in run2 initializing the recalibration
factors is disabled in order to prevent opening the OADB file untill
the memory leak in the OADB container is fixed.
> [EMCAL-135] Disable temperature recalib due to memory leak

- PWGDQ/dielectron/LMEE/AliAnalysisTaskSimpleTreeMaker.cxx
Multiplicity branch was accidentally removed during restructure.
> Added missing multiplcitiy branch

- PWGGA/CaloTrackCorrelations/macros/AddTaskCaloTrackCorrBase.C
- PWGGA/CaloTrackCorrelations/macros/AddTaskMultipleTrackCutIsoConeAnalysis.C
- PWGGA/CaloTrackCorrelations/macros/ConfigureCaloTrackCorrAnalysis.C
Separate the base task reader and calo utils configurations from the analysis task configuration, allow multiple cut analysis with the same global list of analysis configuration
> Make AddTask for CaloTrackCorr a bit more modular, simplify multiple cut analysis with first example

- PWGDQ/dielectron/core/AliDielectronVarManager.cxx
- PWGDQ/dielectron/core/AliDielectronVarManager.h
A shift in the labeling was introduce due to one label to much commented out. This push fixes it
> PWGDQ VarManager small fix in labeling of vars

- PWGCF/FEMTOSCOPY/AliFemto/AliFemtoConfigObject.cxx
- PWGCF/FEMTOSCOPY/AliFemto/AliFemtoConfigObject.h
* Using "using" for defining associated types
* Fixed warning by removing unused variable
> PWGCF: AliFemtoConfigObject - Using "using" for defining associated types

- PWGPP/TOF/trending/MakeTrendingTOFQAv2.C
- Reordered instructions to compute efficiency
- so to fix the Matching efficiency plot vs Eta (double divide)
> fixed TOF QA matching eff. vs Eta plot

- PWGLF/RESONANCES/AliRsnCutSetDaughterParticle.cxx
- PWGLF/RESONANCES/AliRsnCutSetDaughterParticle.h
- PWGLF/RESONANCES/macros/mini/AddTaskPhiXeXe.C
- PWGLF/RESONANCES/macros/mini/ConfigPhiXeXe.C
- Added new PID cuts (TPC-TOF, TPC-TOFveto and TPC-TOFveto + electron rejection)
- Updated macros, including changes for ROOT6
> New cuts for phi analysis in XeXe and updated macros

- PWGGA/PHOSTasks/CMakeLists.txt
- PWGGA/PHOSTasks/PHOS_LHC16_pp/AliPP13KaonToPionRatioMC.cxx
- PWGGA/PHOSTasks/PHOS_LHC16_pp/AliPP13KaonToPionRatioMC.h
- PWGGA/PHOSTasks/PHOS_LHC16_pp/macros/AddAnalysisTaskPP.C
- PWGGA/PHOSTasks/PWGGAPHOSTasksLinkDef.h
It also fixes typos in class names for PHOS neutral mesons analysis @ 13 TeV
> Remove absolute values on pdg labels

- PWGCF/FEMTOSCOPY/macros/AddTaskFemtoDreamPileUpCheck.C
The last attempt did not yield any further insight apart from the fact that the correlated v0 background is most pronounced at low pT. Therefore now test different pT cuts to see the impact on the v0 purity and the Lambda-Lambda correlation function
> Test pile-up rejection - study pT dependence

- OADB/EMCAL/READMEoadb.txt
The OADB files for EMCal are now updated on EOS with a fix necessary to remove a memory leak from AliOADBContainer. Details about this can be found on JIRA EMCAL-135 and the PR 4792.
New BC maps for LHC17i,l were added and additional bad channels were added to the BC maps of LHC16hijlqt.
> [EMCAL-135] OADB/EMCAL: fix of AliOADBContainers and new maps for LHC16hijlqt and LHC17il

- PWG/EMCAL/EMCALtasks/AliEmcalCorrectionCellEnergy.cxx
- PWG/EMCAL/EMCALtasks/AliEmcalCorrectionCellTimeCalib.cxx
- PWG/EMCAL/EMCALtasks/AliEmcalCorrectionComponent.cxx
Addressing memory leak discussed in EMCAL-135: InitFromFile
of AliOADBContainer dropped in favour of automatic lifetime
management of the OADB containers using std::unique_ptr.
Depends on the fix in AliOADBContainer setting the ownership
of the object and the fix in AliEMALRecoUtils taking the
ownership of calibration data.
> [EMCAL-135] Use std::unique_ptr to handle lifetime of OADB containers

- PWG/EMCAL/READMEemcCorrections.txt
Note that intermediate LEGO train tests can fail is using a configure
wagon. Such tests failing is not necessarily a problem - the results
that matter are the full train test.
@jdmulligan - Just so you're aware and can point people to it if necessary
> EMCal CorrFW: Documentation update

- JETAN/JETAN/AliJetReaderHeader.cxx
- JETAN/JETAN/AliJetReaderHeader.h
- PWGGA/PHOSTasks/PHOS_NeutralMeson/AliAnalysisTaskPHOSNeutralMeson.cxx
- PWGHF/hfe/AliAnalysisTaskEHCorrel.cxx
- PWGHF/hfe/AliAnalysisTaskEHCorrel.h
- PWGHF/hfe/AliAnalysisTaskEMCalHFEpA.cxx
- PWGHF/hfe/AliAnalysisTaskEMCalHFEpA.h
- PWGHF/hfe/AliAnalysisTaskElecHadronCorrel.cxx
- PWGHF/hfe/AliAnalysisTaskElecHadronCorrel.h
- PWGHF/hfe/AliAnalysisTaskElecHadronCorrel_Run1.cxx
- PWGHF/hfe/AliAnalysisTaskElecHadronCorrel_Run1.h
- PWGHF/hfe/AliAnalysisTaskFlowTPCEMCalEP.cxx
- PWGHF/hfe/AliAnalysisTaskFlowTPCEMCalEP.h
- PWGHF/hfe/AliAnalysisTaskFlowTPCEMCalQCSP.cxx
- PWGHF/hfe/AliAnalysisTaskFlowTPCEMCalQCSP.h
- PWGHF/hfe/AliAnalysisTaskHFECal.cxx
- PWGHF/hfe/AliAnalysisTaskHFECal.h
- PWGHF/hfe/AliAnalysisTaskHFEEfficiency.cxx
- PWGHF/hfe/AliAnalysisTaskHFEEfficiency.h
- PWGHF/hfe/AliAnalysisTaskHFEMultiplicity.cxx
- PWGHF/hfe/AliAnalysisTaskHFEMultiplicity.h
- PWGHF/hfe/AliAnalysisTaskHFEpACorrelation.cxx
- PWGHF/hfe/AliAnalysisTaskHFEpACorrelation.h
- PWGHF/hfe/AliAnalysisTaskHaHFECorrel.cxx
- PWGHF/hfe/AliAnalysisTaskHaHFECorrel.h
In view of moving AliEMCALRecoUtils from AliRoot to AliPhysics I spotted that the classes in this commit include AliEMCALRecoUtils but do not use it at all. Please consider approving this since it should not affect at all any of those tasks.
> Remove unnecessary dependencies on AliEMCALRecoUtils

- PWG/EMCAL/EMCALbase/AliEMCALRecoUtils.cxx
These `imc` indexes as `Int_t` would cause compiler error when using g++-6.3
> EMCAL - Fixed unsigned integer comparison error

- PWGLF/CommonUtils/MConthefly/AliAnalysisTaskSimSpectraLF.cxx
Before K*+- set as a physical primary particle(which was incorrect). The histogram is not filled up when K*+- set as isPhysPrim. So I changed it as done for phi and K*0 particles.
> Fix: K*+- set as not a physical primary particle 

- PWGPP/EvTrkSelection/AliAnalysisTrackingUncertaintiesAOT.h
- PWGPP/macros/AddTaskTrackingUncertAOT.C
A Set method has been added in .h and AddTask to use TPConly tracks for DCA distributions
> Setter for tpconly added

- PWGJE/EMCALJetTasks/UserTasks/AliAnalysisTaskRecoilJetYield.cxx
- PWGJE/EMCALJetTasks/UserTasks/AliAnalysisTaskRecoilJetYield.h
- PWGJE/EMCALJetTasks/UserTasks/AliAnalysisTaskRecursiveSoftDrop.cxx
- PWGJE/EMCALJetTasks/UserTasks/AliAnalysisTaskRecursiveSoftDrop.h
- Added a minimum subjet pT cut off when grooming using recursive parents in recoil shapes task
- Added an extra branch to recursive tree task that stores the parent pT of each splitting to calculate scale of kT
> Added subjet pT cut to RecoilShapes and branch to Recursive task

- PWGHF/vertexingHF/AliHFSystErr.cxx
- PWGHF/vertexingHF/AliHFSystErr.h
Added systematics estimation for Lc->pK0S STD analysis for 2016 p-Pb data.
Errors related to cut, PID and multiplicity variations are dummy for now
and equivalent to the RunI estimate.
Final estimate will come soon.
> Added sys. err. for Lc2pK0S STD for 2016 p-Pb data

- PWGLF/SPECTRA/PiKaPr/ITSsa/AliAnalysisTaskSEITSsaSpectra.cxx
- PWGLF/SPECTRA/PiKaPr/ITSsa/AliAnalysisTaskSEITSsaSpectra.h
PID parametrization for low magnetic field configuration. New parameters for PHOBOS parametrization. Pions and electrons use the old parametrization for nominal field.
> new PID parametrization for low magnetic field configuration

- PWG/EMCAL/EMCALtrigger/AliEmcalTriggerMakerTask.cxx
- PWG/EMCAL/EMCALtrigger/AliEmcalTriggerMakerTask.h
Tests indicate that the abs fastor indexing works with
the STU convention while the DCS uses the TRU indexing.
In order to mask FastORs correctly based on the trigger
DCS config from OCDB the TRU indexing needs to be
remapped, otherwise masked FastORs appear in the wrong
position.
> [EMCAL-51] Remap TRU index to STU convention

- PWGLF/SPECTRA/PiKaPr/ITSsa/AliAnalysisTaskSEITSsaSpectra.cxx
correct beta*gamma cut for pions and electrons. Correction of the bug.
> correct beta*gamma cut for pions and electrons

- PWGDQ/dielectron/macrosLMEE/Config_acapon_ElectronEfficiency.C
Generated cuts opened up for creation of smearing histograms
> Opened up single track cuts

- PWG/EMCAL/EMCALtasks/AliAodSkimTask.cxx
- PWG/EMCAL/EMCALtasks/AliAodSkimTask.h
Avoid copying objects that are being referenced via TRef. Instead either clone or move them from one to the other array. The latter was easily achieved use AbsorbObjects member of TClonesArray.
This is work related to EMCAL-142
> Fix for proper tref handling

- PWGJE/EMCALJetTasks/Tracks/AliAnalysisTaskEmcalRecalcPatchesRef.cxx
- PWGJE/EMCALJetTasks/Tracks/AliAnalysisTaskEmcalTriggerBase.cxx
- PWGJE/EMCALJetTasks/Tracks/AliAnalysisTaskEmcalTriggerBase.h
Optionally support events without INT trigger as exotic
case (no INTx or EMCx in trigger string). Such cases are
only of relevance for PHYSICS_2 runs or quiet beam runs.
By default disabled, due to memory constraints.
> [EMCAL-172] Exotic case for runs without INT trigger

- PWG/EMCAL/EMCALtrigger/AliEmcalTriggerMakerTask.cxx
- PWG/EMCAL/EMCALtrigger/AliEmcalTriggerMakerTask.h
- PWGJE/EMCALJetTasks/Tracks/AliAnalysisTaskEmcalRecalcPatchesRef.cxx
- PWGJE/EMCALJetTasks/Tracks/AliAnalysisTaskEmcalTriggerBase.cxx
- Do not perform event selection in the trigger maker
as it is a service task
- Fix DCAL L0 trigger string in trigger base task
- Adopt recalc patch task to handle no INT triggers
- A few AliDebugs
> [EMCAL-174] Support for no-INT events on patch side

- PWGJE/EMCALJetTasks/AliAnalysisTaskEmcalJetQA.cxx
- PWGJE/EMCALJetTasks/AliAnalysisTaskEmcalJetQA.h
This reverts commit 67fc5a40349fecc4ab6d29072a5f5755298d8361.
In fact the hist manager should be streamed. Fixed now.
> Revert "Fix missing ! in the field comment"

- PWGPP/EMCAL/OADBMacros/CreateEMCAL_OADB_CalibReference.C
- PWGPP/EMCAL/OADBMacros/CreateEMCAL_OADB_RunByRunTemperatureECalibCorrection.C
- PWGPP/EMCAL/OADBMacros/UpdateEMCAL_OADB_BadChannels.C
- PWGPP/EMCAL/OADBMacros/UpdateEMCAL_OADB_Recalib.C
- PWGPP/EMCAL/OADBMacros/UpdateEMCAL_OADB_RunByRunTimeCalib.C
- PWGPP/EMCAL/OADBMacros/UpdateEMCAL_OADB_TimeCalib.C
This PR contains the current macros I use for the creation of the OADB files. The most important addition is the ownership test at the end of each macro.
The BC map macro was rewritten from ground up and is now much more user friendly and powerful.
> PWGPP/EMCAL: update of OADB macros including OADBContainer fix

- PWGHF/vertexingHF/charmFlow/AliAnalysisTaskSEHFvn.cxx
- PWGHF/vertexingHF/charmFlow/AliAnalysisTaskSEHFvn.h
Added possibility to select D0 from Dstart, starting from D0 candidates and combining them with soft pions. Soft pions can be selected using standard selections for soft pions (3 points in ITS, pt > 0.1 GeV/c, ITS refit, SPD kAny) or requiring the TPC (filterbit 4).
> Added alternative logic for D0 from Dstar analysis

- PWGHF/vertexingHF/charmFlow/AliAnalysisTaskSEHFvn.cxx
1) Moved soft pion AliESDtrackCuts from class contructor to LocalInit() 
2) Fixed error in selection of Dstar inv mass for D0 from Dstar analysis (Dstar invariant mass interval to tag D0 from Dstar)
> Moved soft pion AliESDtrackCuts in LocalInit() and fixed error in selection of Dstar inv mass

- PWGPP/EMCAL/AliAnalysisTaskEMCALAlig.cxx
- PWGPP/EMCAL/AliAnalysisTaskEMCALAlig.h
In this commit I have changed:
- The propagation of the tracks is done by AliTrackerBase instead of AliEMCALRecoUtils. With this change I hope to achieve better precision on the edges of the EMCAL.
- Now the tree saves only XYZ positions of the track using the method above and the XYZ positions of the cluster. This saves space and may allow a more complete study. The phi and eta can of course be calculated straightforward.
- The default matcher is removed (saves a bit of space), since it is clearly not good enough for this study.
- The trees now have informations about the Z of the primary vertex
- A flag (is_in_fid_region) that looks if the cluster is or not in the edge was added.
- Check the distance to the bad channels and saves it to the tree (@gconesab can check if the implementation …
> Improve alignment information

- PWG/EMCAL/EMCALbase/AliAnalysisTaskEmcalLight.cxx
- PWG/EMCAL/EMCALbase/AliAnalysisTaskEmcalLight.h
- PWGJE/EMCALJetTasks/PWGJEEMCALJetTasksLinkDef.h
- PWGJE/EMCALJetTasks/UserTasks/AliAnalysisTaskEmcalJetTree.cxx
- PWGJE/EMCALJetTasks/UserTasks/AliAnalysisTaskEmcalJetTree.h
- PWGJE/FlavourJetTasks/AliAnalysisTaskDmesonJets.cxx
- PWGJE/FlavourJetTasks/AliAnalysisTaskDmesonJets.h
- PWGJE/FlavourJetTasks/AliAnalysisTaskDmesonJetsDetectorResponse.cxx
- PWGJE/FlavourJetTasks/PWGJEFlavourJetTasksLinkDef.h
This PR implements the event weight in the output for 3 tasks:
- The base class AliAnalysisTaskEmcalLight
- The inclusive jet analysis AliAnalysisTaskEmcalJetTree
- The D-meson tagged jet analysis AliAnalysisTaskDmesonJets
> Event weight information in the output

- PWGGA/GammaConv/AliConvEventCuts.cxx
- PWGGA/GammaConv/macros/AddTask_PHOSTender_PCMconfig.C
- added Zero suppression for run2 PHOS tender
- added trigger thresholds for run2 to trigger mimicking function for EMC (tentative values)
> PWGGA/GammaConv: modified setting for PCM version of PHOSTender and added trigger mimicking for run2 data for EMC

- PWGJE/EMCALJetTasks/Tracks/AliAnalysisTaskEmcalClustersRef.cxx
- PWGJE/EMCALJetTasks/Tracks/AliAnalysisTaskEmcalClustersRef.h
Converting cluster hists to THnSparse (resulting in
two THnSparses per trigger) with 6 dimensions,
adding trigger cluster (0 - ANY, 1 - CENT, 2 - CENTNOTRD,
3 - CALO, 4 - CALOFAST, 5+ - Mixed clusters). Event counters
removed and replaced by event counters for trigger cluster.
> [EMCAL-180] Including trigger cluster in hists

- PWG/EMCAL/EMCALtrigger/AliEmcalTriggerMakerTask.cxx
- PWG/EMCAL/EMCALtrigger/AliEmcalTriggerMakerTask.h
TRUs in the small supermodules still follow the linear
mapping between channels and bits in reg mask, used
in run1 and not the mapping used for the TRUs  in the
other supermodules (EMCAL full or DCAL 2/3rd). The mask
handler is created accordingly based on the TRU index
based on the L0 convention.
> [EMCAL-51] Fix mapping for small supermodules in run2

- PWGHF/vertexingHF/AliAnalysisTaskCombinHF.cxx
- PWGHF/vertexingHF/AliAnalysisTaskCombinHF.h
Modified track rotation and mixed event for Ds considering it as 2 prong, using phi and pion instead of kaons and pion:
1) for track rotation the pion is rotated and the phi (kaon pair) not
2) for mixed event the pion is taken from an event and the phi (kaon pair) from another one
> Modified track rotation and mixed event for Ds using pi and phi

- PWGJE/EMCALJetTasks/Tracks/AliAnalysisTaskEmcalClustersRef.cxx
- PWGJE/EMCALJetTasks/Tracks/AliAnalysisTaskEmcalClustersRef.h
- PWGJE/EMCALJetTasks/Tracks/AliAnalysisTaskEmcalRecalcPatchesRef.cxx
- PWGJE/EMCALJetTasks/Tracks/AliAnalysisTaskEmcalRecalcPatchesRef.h
Require or exclude coincidence of a trigger with a certain
list of triggers. Needed in order to check overlap of the
jet trigger with the gamma trigger.
> [EMCAL-56, EMCAL-180] Exclude/Require trigger coincidence

- PWGJE/EMCALJetTasks/CMakeLists.txt
- PWGJE/EMCALJetTasks/PWGJEEMCALJetTasksLinkDef.h
- PWGJE/EMCALJetTasks/Tracks/AliAnalysisTaskEmcalPatchMultCorr.cxx
- PWGJE/EMCALJetTasks/Tracks/AliAnalysisTaskEmcalPatchMultCorr.h
- PWGJE/EMCALJetTasks/macros/AddTaskEmcalPatchMultCorr.C
In order to investigate the weird turnon behaviour at the
EG1 threshold in EJ1 events observed in LHC16k the
correlation between the multiplcities of firing (above
threshold) EJ1 and EG1 patches, as well as the number of
isolated (no overlap with firing JE patch) gamma patches
is monitored, assuming the turnon behaviour comes from
additional background.
> [EMCAL-180] Adding task for patch multiplicity correlation

- PWGJE/EMCALJetTasks/CMakeLists.txt
- PWGJE/EMCALJetTasks/PWGJEEMCALJetTasksLinkDef.h
- PWGJE/EMCALJetTasks/Tracks/AliAnalysisTaskEmcalTriggerCorrelation.cxx
- PWGJE/EMCALJetTasks/Tracks/AliAnalysisTaskEmcalTriggerCorrelation.h
- PWGJE/EMCALJetTasks/macros/AddTaskEmcalTriggerCorrelation.C
The trigger correlation is already monitored in the base
task AliAnalysisTaskEmcalTriggerBase which is abstract.
This task inherits from AliAnalysisTaskEmcalTriggerBase
and only implements the abstract functions as empty
functions in order to make the task non-abstract.
> New simple task for trigger correlation

- PWGJE/EMCALJetTasks/Tracks/AliAnalysisTaskEmcalJetEnergyScale.cxx
- PWGJE/EMCALJetTasks/Tracks/AliAnalysisTaskEmcalJetEnergyScale.h
- PWGJE/EMCALJetTasks/macros/AddTaskEmcalJetEnergyScale.C
As observed in a different task ROOT5 has problems with
with c++11 keywords default and delete in function
specification even when circumventing for ROOTCINT.
Therefore c++11 part is removed (temporarily).
Furthermore CINT seems to have problems with the macro
interpretation in case the macro doesn't end with an empty
line. Therefore an empty line is added at the end of the
add macro.
> Remove c++11 keywords from header, fix add macro

- PWGJE/EMCALJetTasks/Tracks/AliAnalysisTaskEmcalJetEnergyScale.cxx
- PWGJE/EMCALJetTasks/Tracks/AliAnalysisTaskEmcalJetEnergyScale.h
- PWGJE/EMCALJetTasks/Tracks/AliAnalysisTaskEmcalJetEnergySpectrum.cxx
- Only handle trigger clusters on data, fall back to ANY
for MC
- Add cluster energy cuts for cluster container in
energy scale task in order to fix the jet container
names
- Add histos with accepted and matched particle level
jets for efficiency x acceptance
- Energy scale task forced to use analysis utils
- Add some debug printouts and display name of the
jet containers in generation process
> Fixes in spectrum and energy scale task

- PWGPP/EMCAL/AliAnalysisTaskEMCALClusterize.cxx
before feeding the clusterizer. This selection is already done there. Let those cells still be in the list of cells. In line with what is done in the EMCal correction framework
> remove low E cell and out of time cell selection

- PWGPP/AliTaskCDBconnect.cxx
- PWGPP/macros/main_runFilteringTask.C
localOCDBaccessConfig.C should be executed after both an OCDB default storage
and run number are set
> Filtering task: load local OCDB at the right time

- PWGJE/EMCALJetTasks/macros/AddTaskPSHFE.C
Removed import statements from AddTaskPSHFE so as to run on the lego train without errors.
> removed import statements from addtask macro

- PWG/CaloTrackCorrBase/AliCaloTrackReader.cxx
- PWG/CaloTrackCorrBase/AliMCAnalysisUtils.cxx
- PWG/CaloTrackCorrBase/AliMCAnalysisUtils.h
- PWGGA/CaloTrackCorrelations/AliAnaCalorimeterQA.cxx
- PWGGA/CaloTrackCorrelations/AliAnaClusterShapeCorrelStudies.cxx
- PWGGA/CaloTrackCorrelations/AliAnaElectron.cxx
- PWGGA/CaloTrackCorrelations/AliAnaInsideClusterInvariantMass.cxx
- PWGGA/CaloTrackCorrelations/AliAnaParticleIsolation.cxx
- PWGGA/CaloTrackCorrelations/AliAnaPhoton.cxx
- PWGGA/CaloTrackCorrelations/AliAnaPi0EbE.cxx
Add new method in AliMCAnalysisUtils to get the Pythia event header. It returns also the header name and process and a string dedicated to gamma-jet or jet-jet processes
This new method is used in the reader when checking outlier pT hard events.
In case of cocktail generators where a multiple pythia generator is included, a string to tag the direct photons from a particular pythia event can be set.
> Tag properly pythia direct photons for version 8 and cocktail MCs with pythia

- PWGCF/Correlations/DPhi/AliAnalysisTaskPhiCorrelations.cxx
This commit is to fix a change in behavior that was introduced with commit 4403510 (https://github.com/alisw/AliRoot/commit/4403510cda26490ba19991968de7b3206c84743b#diff-34966647f689d13061df3e7a1dc2b3a3)
With the above mentioned commit, AliEventPoolManager has a built-in event limiting feature.
To restore the original (desired) behavior, the AliEventPoolManager needs to be initialized with a poolsize of -1.
> Fix pool size in correlation task

- OADB/AliTriggerAnalysis.cxx
This commit is a follow up of https://github.com/alisw/AliRoot/pull/678.
It also unifies the treatment of HV dips between the different event types (ESD, AOD, MC).
> Reactivate TPC HV dip detection for all data

- TENDER/TenderSupplies/AliPHOSTenderSupply.h
This modification allows to use TestCPV function from external codes.
This will simplify to compute distance between a cluster and a track in mixed event.
> move TestCPV from protected to public

- PWGDQ/reducedTree/AliAnalysisTaskReducedTreeMaker.cxx
do not fulfill criterias to be written in the trees, but are selected for writing randomly.
> Small change in the tree maker, to mark in fEventTag those events which

- PWG/EMCAL/READMEemcEmbedding.txt
- PWGJE/EMCALJetTasks/AliEmcalJetTask.cxx
- PWGJE/EMCALJetTasks/AliEmcalJetTask.h
- PWGJE/doc/READMEjetfw.txt
Hi @raymondEhlers, All,
Please take a look at my implementation of pT-dependent artificial track efficiency in jet finding. This builds on the previous implementation of a constant artificial track efficiency, e.g. SetTrackEfficiency(0.98) to account for the ~2% reduced efficiency in PbPb compared to pp. The idea with this commit is that the user can now provide a pT-dependent efficiency via a file containing a TF1 by calling the function LoadTrackEfficiencyFunction() in the AddTask customization. The TF1 should be a parameterization of the "additional" track efficiency you want to apply, typically (PbPb track efficiency / pp track efficiency).
I tested that the feature has no effect if disabled (which is default), and that if a constant efficiency is supplied (either via …
> implement pT-dependent artificial track efficiency feature in jet finding

- TENDER/TenderSupplies/AliPHOSTenderSupply.h
This will allow to simply track matching procedure in mixed event by external analysis tasks.
> move FindTrackMatching from protected to public

- PWGGA/EMCALTasks/AliAnalysisTaskEMCALPhotonIsolation.cxx
- PWGGA/EMCALTasks/AliAnalysisTaskEMCALPhotonIsolation.h
- Adding a function to set a cluster E_T dependent charged-particle veto (CPV) with parametrisation from https://alice-notes.web.cern.ch/node/813 + a histogram with CPV residuals vs. cluster E_T
- Introducing two histograms to follow the event and cluster statistics along cut flow
- Reducing the event number histogram binning to 1 (instead of 1 filled bin + 99 empty bins before)
- Fixing the candidate cluster (eta, phi) map histogram filling
> Several implementations (mainly variable CPV)

- PWGJE/EMCALJetTasks/AliEmcalJetTask.cxx
- PWGJE/EMCALJetTasks/AliEmcalJetTask.h
In local test it turned out that the double delete introduced in #5541 is due to the tracking efficiency function. I comment out this part for the moment in order to unblock jet trains, leaving it up to @jdmulligan to find a better solution.
> Temporarily disable pt-dependent tracking efficiency
