alisw/AliPhysics

PWGLF/SPECTRA/MultEvShape/AliMESeventInfo.cxx, PWGLF/SPECTRA/MultEvShape/AliMESpidTask.cxx
Task optimization; fixed a couple of warnings in AliMESeventInfo
=> Fixed event shape initialization; switch to dir plus

PWG/FLOW/Tasks/AliAnalysisTaskCMEV0.cxx, PWG/FLOW/Tasks/AliAnalysisTaskCMEV0PID.cxx, PWG/FLOW/Tasks/AliAnalysisTaskCMEV0PID.h, PWGCF/FLOW/macros/AddTaskCMEV0.C, PWGCF/FLOW/macros/AddTaskCMEV0PID.C
Add Options for pPb system, Add QA hist
=>  Add Options for pPb system, Add QA hist

PWGDQ/dielectron/LMEE/AliAnalysisTaskSimpleTreeMaker.cxx, PWGDQ/dielectron/LMEE/AliAnalysisTaskSimpleTreeMaker.h
Complete rework of class. Now using standard TTree->Fill() function, instead of TTreeStreamer class. 
Analysis TTree creation output unchanged. 
V0 TTrees fixed (correctly looping over each charged particle)
Generator TTree creation option added. Create TTree will all generated electrons for efficiency correction.
Select which TTree via flags in AddTask.
=> Added analysis, V0 or gen. Tree functionality

PWG/FLOW/Tasks/AliAnalysisTaskCMEV0.cxx, PWG/FLOW/Tasks/AliAnalysisTaskCMEV0.h, PWGCF/FLOW/macros/AddTaskCMEV0.C
Add higher/mixed harmonic Correlator and vs RefMult histograms
=> Add higher/mixed harmonic Correlator and vs RefMult histograms

PWGGA/EMCALTasks/AliAnalysisTaskGammaHadron.cxx, PWGGA/EMCALTasks/AliAnalysisTaskGammaHadron.h
Add mode to use fixed mass mean,sigma (per analysis pT bin)
Also, adding self to author line :)
=> Add mode to use fixed mass mean, sigma 

PWGGA/PHOSTasks/PHOS_Run2/macros/AddTaskPHOSPi0EtaToGammaGamma_pp_5TeV_LHC17pq.C, PWGGA/PHOSTasks/PHOS_Run2/macros/AddTaskPHOSSingleSim.C
update pi0 and eta weighting in single simulation
=> update pi0 and eta weighting in single simulation

PWGCF/FEMTOSCOPY/macros/AddTaskFemtoDream.C, PWGCF/FEMTOSCOPY/macros/AddTaskFemtoDreamSysVar.C
add task macro didn't work with trains due to the includes on top - root includes should work ?!
=> removal of the includes at the beginning, since these crash my train

PWGJE/EMCALJetTasks/UserTasks/AliAnalysisTaskEmcalJetHPerformance.cxx, PWGJE/EMCALJetTasks/UserTasks/AliAnalysisTaskEmcalJetHUtils.cxx
The functions in AliEmcalJet do not use the proper energy in the
momentum calculation of the leading cluster. Thus, the jet constituents
should be used. Due to a bug in retrieving the leading cluster and
particle, they are calculated in the utils class instead
=> Update leading hadron calculation method

PWGCF/Correlations/DPhi/Unfoldedhistos/AliAnalysisTaskCorrelationsStudies.cxx, PWGCF/Correlations/DPhi/Unfoldedhistos/AliDptDptCorrelations.cxx, PWGCF/Correlations/DPhi/Unfoldedhistos/AliDptDptCorrelations.h
Wrong binning configuration. A fix will follow.
=> Revert "Incorporated resonances/conversions rejection functionality"

PWGCF/Correlations/DPhi/Unfoldedhistos/AliAnalysisTaskCorrelationsStudies.cxx, PWGCF/Correlations/DPhi/Unfoldedhistos/AliDptDptCorrelations.cxx, PWGCF/Correlations/DPhi/Unfoldedhistos/AliDptDptCorrelations.h
With the wrong binning configuration issue fixed.
=> Incorporated resonances/conversions rejection functionality

PWGCF/EBYE/Fluctuations/AliEbyEPidEfficiencyContamination.cxx, PWGCF/EBYE/Fluctuations/AliEbyEPidEfficiencyContamination.h
AliEventCuts used for pileup event rejection in Run 2 data
=> AliEventCuts class used for pileup cut

OADB/EMCAL/READMEoadb.txt
Just a short update of the bookkeeping file.
=> OADB/EMCAL: Update of Readme with LHC17m BC maps

PWGGA/PHOSTasks/PHOS_Run2/AliAnalysisTaskPHOSPi0EtaToGammaGamma.cxx, PWGGA/PHOSTasks/PHOS_Run2/AliAnalysisTaskPHOSPi0EtaToGammaGamma.h, PWGGA/PHOSTasks/PHOS_Run2/macros/AddTaskPHOSPi0EtaToGammaGamma_pp_5TeV_LHC17pq.C
add a function to measure PHOS trigger efficiency in MB.
=> add a function to measure PHOS trigger efficiency in MB

PWGCF/FEMTOSCOPY/PLamAnalysisPP/AliAnalysisTaskPLFemto.cxx, PWGCF/FEMTOSCOPY/PLamAnalysisPP/AliAnalysisTaskPLFemto.h, PWGCF/FEMTOSCOPY/PLamAnalysisPP/AliFemtoCutValues.h, PWGCF/FEMTOSCOPY/PLamAnalysisPP/AliFemtoLambdaParticle.h, PWGCF/FEMTOSCOPY/PLamAnalysisPP/AliFemtoProtonParticle.h, PWGCF/FEMTOSCOPY/PLamAnalysisPP/AliFemtoXiParticle.h, PWGCF/FEMTOSCOPY/macros/AddTaskPLFemtoRun2.C
o Lightweight option to initialize only a subset of the histograms
o Employ smaller data types
=> Improve memory behaviour of AliAnalysisTaskPLFemto

PWGCF/FEMTOSCOPY/FemtoDream/AliAnalysisTaskFemtoDream.cxx, PWGCF/FEMTOSCOPY/FemtoDream/AliAnalysisTaskFemtoDream.h, PWGCF/FEMTOSCOPY/FemtoDream/AliFemtoDreamAnalysis.cxx, PWGCF/FEMTOSCOPY/FemtoDream/AliFemtoDreamAnalysis.h, PWGCF/FEMTOSCOPY/FemtoDream/AliFemtoDreamCascadeCuts.cxx, PWGCF/FEMTOSCOPY/FemtoDream/AliFemtoDreamCascadeCuts.h, PWGCF/FEMTOSCOPY/FemtoDream/AliFemtoDreamCorrHists.cxx, PWGCF/FEMTOSCOPY/FemtoDream/AliFemtoDreamCorrHists.h, PWGCF/FEMTOSCOPY/FemtoDream/AliFemtoDreamEventCuts.cxx, PWGCF/FEMTOSCOPY/FemtoDream/AliFemtoDreamEventCuts.h, PWGCF/FEMTOSCOPY/FemtoDream/AliFemtoDreamEventHist.cxx, PWGCF/FEMTOSCOPY/FemtoDream/AliFemtoDreamPairCleaner.cxx, PWGCF/FEMTOSCOPY/FemtoDream/AliFemtoDreamPairCleaner.h, PWGCF/FEMTOSCOPY/FemtoDream/AliFemtoDreamPartCollection.cxx, PWGCF/FEMTOSCOPY/FemtoDream/AliFemtoDreamPartCollection.h, PWGCF/FEMTOSCOPY/FemtoDream/AliFemtoDreamTrackCuts.cxx, PWGCF/FEMTOSCOPY/FemtoDream/AliFemtoDreamTrackCuts.h, PWGCF/FEMTOSCOPY/FemtoDream/AliFemtoDreamv0Cuts.cxx, PWGCF/FEMTOSCOPY/FemtoDream/AliFemtoDreamv0Cuts.h, PWGCF/FEMTOSCOPY/macros/AddTaskFemtoContributionSplitting.C, PWGCF/FEMTOSCOPY/macros/AddTaskFemtoDream.C, PWGCF/FEMTOSCOPY/macros/AddTaskFemtoDreamSysVar.C
A minimal booking implementation all over the task for memory optimization, where several bugs had to be fixed. Additionally a bug in the multiplicity dependent binning of the same event and mixed event distribution was fixed.
=> Bugfixes and Minimal booking 

PWGUD/DIFFRACTIVE/CEPdevel/AliCEPUtils.cxx
=> removed lengthy printout

PWG/FLOW/Tasks/AliAnalysisTaskCMEV0PID.cxx, PWG/FLOW/Tasks/AliAnalysisTaskCMEV0PID.h
=> Add NUA framwork for PID CME

PWGCF/FEMTOSCOPY/FemtoDream/AliFemtoDreamCascadeCuts.cxx
=> Xi mass ranges

PWGJE/EMCALJetTasks/Tracks/AliAnalysisTaskEmcalJetConstituentQA.cxx
Monitor several cluster observables (number of cells,
fraction leading, M02) for clusters with high (>0.95)
z.
=> [Histo] Monitor cluster constituents with high z

PWGCF/Correlations/DPhi/AliAnalysisTaskPIDBFDptDpt.cxx
added option to get pure particles in MCAODreco
=> added option to get pure particles in MCAODreco

PWGPP/ITS/AliAnalysisTaskSEImpParResSparse.cxx, PWGPP/ITS/AliAnalysisTaskSEImpParResSparse.h
Adding possibility to use generated pt and select physical primaries when running on Monte Carlo
=> Possibility to use generated pT and physical primaries

PWGHF/hfe/AliAnalysisTaskTPCCalBeauty.cxx
Added D meson pT weight to the Lambda_c as a check
=> Added D meson pT weight to the Lambda_c as a check

PWGPP/EVCHAR/FlowVectorCorrections/QnCorrections/AliQnCorrectionsInputGainEqualization.cxx, PWGPP/EVCHAR/FlowVectorCorrections/QnCorrections/AliQnCorrectionsProfile3DCorrelations.cxx, PWGPP/EVCHAR/FlowVectorCorrections/QnCorrections/AliQnCorrectionsProfileComponents.cxx, PWGPP/EVCHAR/FlowVectorCorrections/QnCorrections/AliQnCorrectionsProfileCorrelationComponentsHarmonics.cxx, PWGPP/EVCHAR/FlowVectorCorrections/QnCorrections/AliQnCorrectionsQnVectorAlignment.cxx, PWGPP/EVCHAR/FlowVectorCorrections/QnCorrections/AliQnCorrectionsQnVectorRecentering.cxx, PWGPP/EVCHAR/FlowVectorCorrections/QnCorrections/AliQnCorrectionsQnVectorTwistAndRescale.cxx, PWGPP/EVCHAR/FlowVectorCorrections/QnCorrectionsInterface/AliAnalysisTaskFlowVectorCorrections.cxx
The behavior of "Form" in nested calls is unexpected, outer values are overwritten by the nested ones.
=> Fix for the erratic behavior of ROOT "Form" service

PWGGA/CaloTrackCorrelations/macros/AddTaskIsoPhoton.C
adding functionality to swith iso method
=> adding iso method switch

PWG/FLOW/Tasks/AliAnalysisTaskCMEV0.cxx, PWG/FLOW/Tasks/AliAnalysisTaskCMEV0.h, PWG/FLOW/Tasks/AliAnalysisTaskCMEV0PID.cxx, PWG/FLOW/Tasks/AliAnalysisTaskCMEV0PID.h, PWGCF/FLOW/macros/AddTaskCMEV0.C, PWGCF/FLOW/macros/AddTaskCMEV0PID.C
Add Qn Recenter Hists for PID, change PID cuts, add Psi3,Psi4
=> Add Qn Recenter Hists for PID, change PID cuts, add Psi3,Psi4

PWGCF/FEMTOSCOPY/FemtoDream/AliAnalysisTaskFemtoDream.cxx, PWGCF/FEMTOSCOPY/FemtoDream/AliFemtoDreamAnalysis.cxx, PWGCF/FEMTOSCOPY/FemtoDream/AliFemtoDreamAnalysis.h, PWGCF/FEMTOSCOPY/FemtoDream/AliFemtoDreamEvent.cxx, PWGCF/FEMTOSCOPY/FemtoDream/AliFemtoDreamEvent.h, PWGCF/FEMTOSCOPY/macros/AddTaskFemtoContributionSplitting.C, PWGCF/FEMTOSCOPY/macros/AddTaskFemtoDream.C, PWGCF/FEMTOSCOPY/macros/AddTaskFemtoDreamSysVar.C
=> Removal of include guards in the add task, Addition of PIDTask Check and Setters to configure HM Event Cuts

PWGCF/FEMTOSCOPY/macros/Train/pPbKKfemto/exp/addtask/3/AddTaskFemto.C, PWGCF/FEMTOSCOPY/macros/Train/pPbKKfemto/exp/conf_run2/ConfigFemtoAnalysis.C
=> Lego: Configuration for Elena pPb March 8, 2018

PWG/EMCAL/EMCALtrigger/AliEmcalTriggerDecision.h, PWG/EMCAL/EMCALtrigger/AliEmcalTriggerDecisionContainer.h
In addion some tiny fixes in the documentation of
AliEmcalTriggerDecisionContainer.
=> [doxygen] Document AliEmcalTriggerDecision

PWGLF/SPECTRA/PiKaPr/TOF/PbPb502/macros/UtilHisto.cxx, PWGLF/SPECTRA/PiKaPr/TOF/PbPb502/macros/UtilHisto.h, PWGLF/SPECTRA/PiKaPr/TOF/PbPb502/task/AddTaskTOFSpectra.C, PWGLF/SPECTRA/PiKaPr/TOF/PbPb502/task/AliAnTOFtrack.h, PWGLF/SPECTRA/PiKaPr/TOF/PbPb502/task/AliAnalysisTaskTOFSpectra.cxx, PWGLF/SPECTRA/PiKaPr/TOF/PbPb502/task/AliAnalysisTaskTOFSpectra.h, PWGLF/SPECTRA/PiKaPr/TOF/PbPb502/task/AliUtilTOFParams.h
- added T0 resolution to the container
- Minor changes to add task and task constructor
- minor changes in macro structure
=> Updated PiKaPr task and helper macros

PWGGA/GammaConv/AliDalitzElectronCuts.cxx
Add case 6 which set Pt min  = 0.05 MeV for primary electron selection
=> Add a new Pt min cut   < 0.05 MeV

PWGUD/DIFFRACTIVE/CEPdevel/AliAnalysisTaskCEP.cxx, PWGUD/DIFFRACTIVE/CEPdevel/CEPTrackBuffer.cxx, PWGUD/DIFFRACTIVE/CEPdevel/CEPTrackBuffer.h
. In addition to TPC and TOF the PID relevant information for the ITS is added to the CEPTrackBuffer
. Bayesian PID is setup to use all three detectors
=> Added ITS PID information to CEPTrackBuffer

PWG/EMCAL/EMCALtasks/AliEmcalClusterMaker.cxx, PWG/EMCAL/EMCALtasks/AliEmcalCorrectionClusterNonLinearity.cxx
Old framework is also updated, only for the sake of making automatic comparison script still agree.
@raymondEhlers
=> extend cluster time plot to negative values

PWG/FLOW/Tasks/AliAnalysisTaskCMEV0.cxx
pileUp bug fix and change Hist Bin for pPb
=> pileUp bug fix and change Hist Bin for pPb

PWGDQ/dielectron/core/AliDielectronVarManager.cxx, PWGDQ/dielectron/core/AliDielectronVarManager.h
Added the v2 calculation with the scalar product method
=> PWGDQ VarManager added ScalarProduct for flow calc

PWGHF/vertexingHF/AliAnalysisTaskSELc2V0bachelor.cxx, PWGHF/vertexingHF/AliRDHFCutsLctoV0.cxx, PWGHF/vertexingHF/AliRDHFCutsLctoV0.h, PWGHF/vertexingHF/macros/makeTFile4CutsLctoV0bachelor.C
Improved PID bachelor selection in case of combined probability used (fPidSelectionFlag==9)
Combined probability cut variable according to the bachelor momentum
=> Improved PID bachelor selection in case of combined probability

PWG/FLOW/Tasks/AliAnalysisTaskCMEV0PID.cxx, PWG/FLOW/Tasks/AliAnalysisTaskCMEV0PID.h, PWG/FLOW/Tasks/AliAnalysisTaskMixedHarmonics.cxx, PWGCF/FLOW/macros/AddTaskCMEV0PID.C, PWGCF/FLOW/macros/parity/AddTaskCMEAnalysis.C
Store Qn/Mult for Recenter, Changes in AddTask to run Multiple wagon
=> Store Qn/Mult for Recenter, Changes in AddTask to run Multiple wagon

PWGCF/FEMTOSCOPY/FemtoDream/AliFemtoDreamEvent.cxx
=> Event Cuts for HM 

PWG/EMCAL/READMEemcEmbedding.txt, PWGJE/EMCALJetTasks/macros/EMCalCorrectionTaskEmbeddingExample.yaml, PWGJE/EMCALJetTasks/macros/runEmbeddingAnalysis.C
The example run macro supports both full and charged jets.
=> EMCal Embed: Example run macro and update docs

PWGGA/PHOSTasks/CaloCellQA/macros/AddTaskCaloCellsQA.C, PWGGA/PHOSTasks/PHOS_TriggerQA/macros/AddTaskPHOSTriggerQA.C, PWGPP/CalibMacros/CPass1/QAtrain_duo.C
After the changes for ROOT6, some things didn't work anymore in ROOT5. This should fix it.
=> Fixes needed to work with both ROOT6 and ROOT5

PWGCF/Correlations/macros/PIDBFDptDpt/AddTaskPIDBFDptDpt.C
=> put ptMax as a variable

PWG/EMCAL/macros/runEMCalSampleTask.C, PWG/EMCAL/macros/runEMCalTriggerQA.C, PWGJE/EMCALJetTasks/macros/runEMCalJetSampleTask.C
Tested that all run on ROOT 6, but additional testing on ROOT 5 would be
helpful.
@aiola , @mfasDa, @jdmulligan  - I received a request to update these for ROOT 6, so I gave it a quick shot. Seems to work fine on ROOT 6, but testing on ROOT 5 or general comments are welcome. I updated the trigger QA run macro because I ran across it, but I could remove the changes if desired
=> Update EMCal, EMCal-Jet run macros for ROOT 6

OADB/EMCAL/READMEoadb.txt
Small pull request for bookkeeping file update.
=> OADB/EMCAL: Bookkeeping file update, TC for LHC17kmhopq

PWGCF/FEMTOSCOPY/macros/Train/pPbKKfemto/exp/conf_run2/1/ConfigFemtoAnalysis.C
=> Lego train: Lena added new ConfigFemtoAnalysis.C

PWGCF/Correlations/DPhi/AliAnalysisTaskCorPIDTOFQA.cxx, PWGCF/Correlations/DPhi/AliAnalysisTaskCorPIDTOFQA.h
=> histogram binning changed, extra histos added for AN explanation plots

PWG/FLOW/Tasks/AliAnalysisTaskCMEV0PID.cxx, PWG/FLOW/Tasks/AliAnalysisTaskCMEV0PID.h, PWGCF/FLOW/macros/AddTaskCMEV0PID.C
Add CME calculation for pi,K,p
=> Add CME calculation for pi,K,p

PWGJE/EMCALJetTasks/UserTasks/AliAnalysisTaskEmcalJetPerformance.cxx
=> minor binning updates

PWGGA/PHOSTasks/CMakeLists.txt, PWGGA/PHOSTasks/CaloCellQA/phys/AliAnalysisTaskCaloCellsPhysQA.cxx, PWGGA/PHOSTasks/CaloCellQA/phys/AliAnalysisTaskCaloCellsPhysQA.h, PWGGA/PHOSTasks/CaloCellQA/phys/AliCaloCellsPhysQA.cxx, PWGGA/PHOSTasks/CaloCellQA/phys/AliCaloCellsPhysQA.h, PWGGA/PHOSTasks/CaloCellQA/phys/README.md, PWGGA/PHOSTasks/CaloCellQA/phys/macros/AddTaskCaloCellsPhysQA.C, PWGGA/PHOSTasks/CaloCellQA/phys/macros/AddTaskPhysPHOSQA.C, PWGGA/PHOSTasks/PWGGAPHOSTasksLinkDef.h
Add QA task with standard PHOS cuts on clusters.
=> Add CaloCellsQA for physics clusters

PWGGA/EMCALTasks/AliAnalysisTaskGammaHadron.cxx, PWGGA/EMCALTasks/AliAnalysisTaskGammaHadron.h
Adds histogram for examining mass vs pt in different centrality bins.
Changes the final centrality bins.
=> Add pT vs Mass vs Cent Histos to AliAnalysisTaskGammaHadron

PWGCF/EBYE/NetLambda/AliAnalysisTaskNetLambdaIdent.cxx, PWGCF/EBYE/NetLambda/AliAnalysisTaskNetLambdaIdent.h
also added additional class members for gen-reco correspondence
=> fix bug in setters/getters of helper classes

PWGCF/FEMTOSCOPY/macros/Train/KpmHBT19/0010/AddTaskFemtoKchHBT0010.C, PWGCF/FEMTOSCOPY/macros/Train/KpmHBT19/0010/ConfigFemtoAnalysis.C, PWGCF/FEMTOSCOPY/macros/Train/KpmHBT19/1090/AddTaskFemtoKchHBT1090.C, PWGCF/FEMTOSCOPY/macros/Train/KpmHBT19/1090/ConfigFemtoAnalysis.C
=> Lego train: K+K- 0.4<p<0.45 cut, 5 mev/c bin on q 13Mar2018

PWGGA/EMCALTasks/AliAnalysisTaskGammaHadron.cxx, PWGGA/EMCALTasks/AliAnalysisTaskGammaHadron.h
Adds opening angle minimum cut.
Update Pi0 Windows.
Update default cuts.
=> Adds opening angle cut and update windows, cuts

PWGGA/PHOSTasks/PHOS_Run2/AliPHOSJetJetMC.cxx, PWGGA/PHOSTasks/PHOS_Run2/macros/AddTaskPHOSPi0EtaToGammaGamma_PbPb_5TeV.C, PWGGA/PHOSTasks/PHOS_Run2/macros/AddTaskPHOSPi0EtaToGammaGamma_pp_5TeV.C, PWGGA/PHOSTasks/PHOS_Run2/macros/AddTaskPHOSPi0EtaToGammaGamma_pp_5TeV_LHC17pq.C
update PHOS L0 trigger efficiency
=> update PHOS trigger efficiency in LHC15n and LHC17pq

PWGCF/EBYE/Fluctuations/AliEbyEPidEfficiencyContamination.cxx, PWGCF/EBYE/Fluctuations/AliEbyEPidEfficiencyContamination.h, PWGCF/EBYE/macros/AddAliEbyEPidEfficiencyContamination.C
Options for different run period are added. AliEventCuts only to be used for Run2.
=> options for different run period are added

PWG/FLOW/Tasks/AliAnalysisTaskCMEV0PID.cxx, PWG/FLOW/Tasks/AliAnalysisTaskCMEV0PID.h, PWGCF/FLOW/macros/AddTaskCMEV0PID.C
PID bufix and added Flags to set harmonics for 3-particle correlator
=> PID bufix and added Flags to set harmonics for 3-particle correlator

PWGHF/vertexingHF/charmFlow/AddTaskHFvn.C, PWGHF/vertexingHF/charmFlow/AliAnalysisTaskSEHFvn.cxx, PWGHF/vertexingHF/charmFlow/AliAnalysisTaskSEHFvn.h
Added:
1) possibility to enable downsampling of tracks from q2 and daughter-removal from q2 at the same time
2) q2TPC vs. q2V0C histo to get correlation between the two q2
3) possibility to analyse only D0 coming from Dstar
=>  Added downsampling + daughter-removal from q2, q2TPC vs. q2V0C histos and D0 from Dstar analysis

PWGDQ/dielectron/core/AliAnalysisTaskElectronEfficiencyV2.cxx, PWGDQ/dielectron/core/AliAnalysisTaskElectronEfficiencyV2.h
- Adds the possibility to separate different generators from each other
- Bugfix for filling of support histograms
=> PWGDQ: effi task v2: added generator separation functionality

PWGJE/EMCALJetTasks/UserTasks/AliAnalysisTaskEmcalJetPerformance.cxx, PWGJE/EMCALJetTasks/UserTasks/AliAnalysisTaskEmcalJetPerformance.h
=> select matched jet using jet-tagger-based approach

PWGCF/FEMTOSCOPY/macros/Train/KchKchRun2/KK_13TeV_dist/AddTaskFemtoKchHBT1090.C, PWGCF/FEMTOSCOPY/macros/Train/KchKchRun2/KK_13TeV_dist/ConfigFemtoAnalysis.C, PWGCF/FEMTOSCOPY/macros/Train/KchKchRun2/pipi_13TeV_dist/AddTaskFemtoKchHBT1090.C, PWGCF/FEMTOSCOPY/macros/Train/KchKchRun2/pipi_13TeV_dist/ConfigFemtoAnalysis.C
=> Lego train: KK_13TeV_dist and pipi_13TeV_dist for Ludmila

PWG/FLOW/Tasks/AliAnalysisTaskCMEV0PID.cxx
Fix periodicity of Psi_3, Psi_4
=> Fix periodicity of Psi_3, Psi_4

PWGUD/DIFFRACTIVE/CEPdevel/RawBuffers/CEPRawADBuffer.cxx, PWGUD/DIFFRACTIVE/CEPdevel/RawBuffers/CEPRawTrackBuffer.cxx, PWGUD/DIFFRACTIVE/CEPdevel/RawBuffers/CEPRawTrackBuffer.h, PWGUD/DIFFRACTIVE/CEPdevel/RawBuffers/CEPRawV0Buffer.cxx
added additional information in CEPRawBuffers
=> Updated information contained in CEPRawBuffers

PWGCF/FEMTOSCOPY/macros/Train/KchKchRun2_Mar2018/KK_13TeV_dist/AddTaskFemtoKchHBT1090.C, PWGCF/FEMTOSCOPY/macros/Train/KchKchRun2_Mar2018/KK_13TeV_dist/ConfigFemtoAnalysis.C, PWGCF/FEMTOSCOPY/macros/Train/KchKchRun2_Mar2018/pipi_13TeV_dist/AddTaskFemtoKchHBT1090.C, PWGCF/FEMTOSCOPY/macros/Train/KchKchRun2_Mar2018/pipi_13TeV_dist/ConfigFemtoAnalysis.C, PWGCF/FEMTOSCOPY/macros/Train/pPbKKfemto/exp/conf_run2/2/ConfigFemtoAnalysis.C
=> Lego train: KchKchRun2_Mar2018 and pPbKKfemto/exp/conf_run2/2

PWGCF/FEMTOSCOPY/macros/Train/pPbKKfemto/MC/addtask/Any/AddTaskFemto.C, PWGCF/FEMTOSCOPY/macros/Train/pPbKKfemto/MC/addtask/INT7/AddTaskFemto.C
=> Train for Elena 17 mar 2018

PWGCF/FEMTOSCOPY/macros/Train/pPbKKfemto/MC/conf_2016/1/ConfigFemtoAnalysis.C
=> Lego train: Elena ask to add ConfigFemtoAnalysis.C

PWGGA/CaloTrackCorrelations/AliAnaClusterShapeCorrelStudies.cxx, PWGGA/CaloTrackCorrelations/AliAnaClusterShapeCorrelStudies.h, PWGGA/CaloTrackCorrelations/AliAnaParticleHadronCorrelation.cxx, PWGGA/CaloTrackCorrelations/AliAnaParticleHadronCorrelation.h, PWGGA/CaloTrackCorrelations/AliAnaParticleIsolation.cxx, PWGGA/CaloTrackCorrelations/AliAnaParticleIsolation.h, PWGGA/CaloTrackCorrelations/macros/AddTaskGammaHadronCorrelationSelectAnalysis.C
Add possibility to execute cluster shape analysis also in the general isolation-correlation configuration
=> Add T-Card cell index histograms in different tasks

PWG/FLOW/Tasks/AliAnalysisTaskCMEV0PID.cxx, PWG/FLOW/Tasks/AliAnalysisTaskCMEV0PID.h, PWGCF/FLOW/macros/AddTaskCMEV0PID.C
Add Track cuts, decrease cpu usuage using Arrays for nSigma
=> Add Track cuts, decrease cpu usuage using Arrays for nSigma

PWG/DevNanoAOD/AliAnalysisNanoAODCutsJet.cxx
bug fix for the custom variable generation in the NanoAOD generation for a jet analysis
=> bug fix NanoAOD custom variable generation

PWG/FLOW/Tasks/AliAnalysisTaskCMEV0PID.cxx
change vector (ROOT6 doesn't support) to arrays
=> change <vector> (ROOT6 doesn't support) to arrays

PWGJE/EMCALJetTasks/UserTasks/AliAnalysisTaskJetCoreEmcal.h
change member variable THnSparseF -> THnSparse to be compatible with classdef
=> fix THnSparseF definition

PWGUD/DIFFRACTIVE/CEPdevel/AliAnalysisTaskCEP.cxx, PWGUD/DIFFRACTIVE/CEPdevel/CEPEventBuffer.h, PWGUD/DIFFRACTIVE/CEPdevel/RawBuffers/CEPRawADBuffer.h, PWGUD/DIFFRACTIVE/CEPdevel/RawBuffers/CEPRawCaloClusterTrack.h, PWGUD/DIFFRACTIVE/CEPdevel/RawBuffers/CEPRawEventBuffer.h, PWGUD/DIFFRACTIVE/CEPdevel/RawBuffers/CEPRawFMDBuffer.h, PWGUD/DIFFRACTIVE/CEPdevel/RawBuffers/CEPRawTrackBuffer.h, PWGUD/DIFFRACTIVE/CEPdevel/RawBuffers/CEPRawV0Buffer.h
. FastOrMap and FiredChipMap was included in the CEPEventBuffer
. additional changes to make task run under root6
=> added SPD trigger maps to CEPEventBuffer

PWGCF/FEMTOSCOPY/PLamAnalysisPP/AliAnalysisTaskPLFemto.cxx, PWGCF/FEMTOSCOPY/macros/AddTaskFemtoDreamPileUpCheck.C
o AddTask macro
o Use RefMult08 for Run2 multiplicity determination
=> Investigate V0 pile-up

PWG/FLOW/Tasks/AliAnalysisTaskCMEV0PID.cxx, PWGCF/FLOW/macros/AddTaskCMEV0.C
Added "using namespace std;"   to get rid of std::
=> Added using namespace std;

PWGCF/FEMTOSCOPY/AliFemto/AliFemtoConfigObject.cxx, PWGCF/FEMTOSCOPY/AliFemto/AliFemtoConfigObject.h, PWGCF/FEMTOSCOPY/AliFemto/CMakeLists.txt, PWGCF/FEMTOSCOPY/AliFemto/PWGCFfemtoscopyLinkDef.h, PWGCF/FEMTOSCOPY/AliFemtoUser/CMakeLists.txt, PWGCF/FEMTOSCOPY/AliFemtoUser/PWGCFfemtoscopyUserLinkDef.h
* Moved from AliFemtoUser/ to AliFemto/
* Added more `pop_*` methods
* Implemented new `find()` method
=> PWGCF: AliFemtoConfigObject - Moved to AliFemto/

PWGCF/Correlations/DPhi/CMakeLists.txt, PWGCF/Correlations/DPhi/EPCorr/AliAnalysisTaskJetLikeCorrelation.cxx, PWGCF/Correlations/DPhi/EPCorr/AliAnalysisTaskJetLikeCorrelation.h, PWGCF/Correlations/DPhi/PWGCFCorrelationsDPhiLinkDef.h, PWGCF/Correlations/macros/epcorr/AddTaskJetLikeCorrelation.C
Di-hadron correlation w.r.t event-plane analysis code.
CMakeLists and LinkHeader are modified.
=> Di-hadron correlation analysis w.r.t event-plane

PWGCF/FEMTOSCOPY/macros/Train/KchKchRun2_noVerbose/KK_13TeV_dist/AddTaskFemtoKchHBT1090.C, PWGCF/FEMTOSCOPY/macros/Train/KchKchRun2_noVerbose/KK_13TeV_dist/ConfigFemtoAnalysis.C, PWGCF/FEMTOSCOPY/macros/Train/KchKchRun2_noVerbose/pipi_13TeV_dist/AddTaskFemtoKchHBT1090.C, PWGCF/FEMTOSCOPY/macros/Train/KchKchRun2_noVerbose/pipi_13TeV_dist/ConfigFemtoAnalysis.C
=> Lego train for Ludmila noVerbose

PWGCF/FEMTOSCOPY/FemtoDream/AliFemtoDreamCollConfig.h, PWGCF/FEMTOSCOPY/macros/AddTaskFemtoDreamSysVar.C
=> update of ClassDef number in the CollConfig

PWG/FLOW/Tasks/AliAnalysisTaskCMEV0PID.cxx, PWG/FLOW/Tasks/AliAnalysisTaskCMEV0PID.h, PWGCF/FLOW/macros/AddTaskCMEV0PID.C
Bugfix: remove delete statement from destructor, Add Differential Histograms.
=> Bugfix: remove delete statement from destructor, Add Differential Hist

PWGCF/Correlations/Base/AliUEHistograms.cxx, PWGCF/Correlations/Base/AliUEHistograms.h
Added new control histogram to the dphi-deta correlations analysis.
=> New histogram in AliUEHistograms

PWG/FLOW/Tasks/AliAnalysisTaskCMEV0.cxx, PWG/FLOW/Tasks/AliAnalysisTaskCMEV0PID.cxx, PWG/FLOW/Tasks/AliAnalysisTaskCMEV0PID.h, PWGCF/FLOW/macros/AddTaskCMEV0PID.C
BugFix to AliAnalysisTaskCMEV0PID
=> BugFix to AliAnalysisTaskCMEV0PID

PWG/EMCAL/EMCALbase/AliAnalysisTaskEmcalEmbeddingHelper.cxx, PWG/EMCAL/EMCALbase/AliAnalysisTaskEmcalEmbeddingHelper.h
Please do not approve yet!
@raymondEhlers , when you have a moment please take a look. I still don't know where to write to so I just printed to stdout and histogram (as you pointed out, from the successful jobs it will at least be interesting to see the distribution). I think the commit is harmless, but best for you to take a look and then approve :)
=> Print and plot time to execute InitTree()

PWGGA/PHOSTasks/PHOS_Run2/AliAnalysisTaskPHOSPi0EtaToGammaGamma.cxx, PWGGA/PHOSTasks/PHOS_Run2/macros/AddTaskPHOSObjectCreator.C, PWGGA/PHOSTasks/PHOS_Run2/macros/AddTaskPHOSPi0EtaToGammaGamma_PbPb_5TeV.C, PWGGA/PHOSTasks/PHOS_Run2/macros/AddTaskPHOSPi0EtaToGammaGamma_pp_5TeV_LHC17pq.C
add L1H PHOS trigger efficiency in LHC15o
=> update PHOS trigger efficiency in LHC15o

PWGGA/EMCALTasks/AliAnalysisTaskGammaHadron.cxx, PWGGA/EMCALTasks/AliAnalysisTaskGammaHadron.h
Adds Mixed Event cluster pairs for Pi0Cand (not correlation) mode.
=> Adds Mixed Event cluster pairs for Pi0Cand (not correlation) mode.

PWGLF/CommonUtils/MConthefly/AliAnalysisTaskSimSpectraLF.cxx, PWGLF/CommonUtils/MConthefly/macros/AddMCGenPythia6.C
K*(892)+- particle has been added. Sigma0 particle was absent in the previous pull request.
=> New particle K*(892)+- added

PWGHF/vertexingHF/charmFlow/AliAnalysisTaskSEHFvn.cxx
1) Modified invariant-mass range of Dstar candidates used to select D0 from Dstar (from 5 to 3 sigma)  
2) Modified control of not double counting D0 candidates (one D0 can build different Dstars)
3) Added histogram to monitor number of Dstar candidates built using the same D0 candidate
=> Minor modifications in D0 from Dstar analysis

PWG/FLOW/Tasks/AliAnalysisTaskCMEV0PID.cxx, PWG/FLOW/Tasks/AliAnalysisTaskCMEV0PID.h
Bugfix: remove variable from array size, use number
=> Bugfix: remove variable from array, use number

PWGCF/FEMTOSCOPY/macros/Train/pPbKKfemto/exp/conf_run2/3/ConfigFemtoAnalysis.C
=> Elena added pPbKKfemto/exp/conf_run2/3/ConfigFemtoAnalysis.C

PWGHF/hfe/AliAnalysisTaskTPCCalBeauty.cxx, PWGHF/hfe/AliAnalysisTaskTPCCalBeauty.h
Added cluster E histograms and took out line that double-counts in existing cluster E histos.
=> Cluster E: added histos and bug fix. 

PWG/FLOW/Tasks/AliAnalysisTaskCMEV0PID.cxx, PWG/FLOW/Tasks/AliAnalysisTaskCMEV0PID.h
Add Weights for non-flat Centrality distribution.
=> Add Weights for non-flat Centrality distribution.

PWGLF/CommonUtils/MConthefly/AliAnalysisTaskSimSpectraLF.cxx
Pseudorapidity cut has been removed from event selection.
=> Bug fix: pseudorapidity cut removed from event selection

PWGCF/FEMTOSCOPY/macros/Train/pPbKKfemto/exp/conf_run2/3/ConfigFemtoAnalysis.C
=> Elena change pPbKKfemto/exp/conf_run2/3/ConfigFemtoAnalysis.C

PWGCF/EBYE/BalanceFunctions/AliAnalysisTaskBFPsi.cxx, PWGCF/EBYE/BalanceFunctions/AliAnalysisTaskBFPsi.h
=> Additions about pid (Davide)

PWG/FLOW/Tasks/AliAnalysisTaskCMEV0PID.cxx, PWG/FLOW/Tasks/AliAnalysisTaskCMEV0PID.h
Add 2p correlator, PID effiicency corr. framework, bugfix for TPC-sub event planes
=> Add 2p correlator, PID effiicency corr. framework, bugfix for TPC-sub EP

PWGGA/PHOSTasks/PHOS_Run2/AliAnalysisTaskPHOSPi0EtaToGammaGamma.cxx, PWGGA/PHOSTasks/PHOS_Run2/AliAnalysisTaskPHOSPi0EtaToGammaGamma.h, PWGGA/PHOSTasks/PHOS_Run2/AliAnalysisTaskPHOSSingleSim.cxx, PWGGA/PHOSTasks/PHOS_Run2/AliPHOSTriggerHelper.cxx, PWGGA/PHOSTasks/PHOS_Run2/AliPHOSTriggerHelper.h, PWGGA/PHOSTasks/PHOS_Run2/macros/AddTaskPHOSPi0EtaToGammaGamma_PbPb_5TeV.C
this contains two commits (update PHOS L1 trigger analysis and pi0 weighting in HIJING)
=> update PHOS L1 trigger analysis

PWGHF/hfe/AliAnalysisTaskTPCCalBeauty.cxx
Comment out cout statement and line that rejects non-MC.
=> Comment out cout statement and line that rejects non-MC.

PWGGA/EMCALTasks/AliAnalysisTaskGammaHadron.cxx, PWGGA/EMCALTasks/AliAnalysisTaskGammaHadron.h, PWGPP/EMCAL/BCMacros/helperMacrosOADBBC.C, PWGPP/EMCAL/BCMacros/helperMacrosRunByRunBC.C
and changed fGammaOrPi0 from a Bool_t to an Int_t
=>  added SideBand window for pi0 analysis

PWGJE/EMCALJetTasks/UserTasks/AliEmcalJetTaggerTaskFast.h
@mfasDa @raymondEhlers 
Hi Markus,
I propose to update the streaming syntax of a couple members -- do you see any problem? To be honest I don't understand quite what the difference between "//!" and "//!<!" is, but my impression is that "//!<!" is more encouraged. I am experiencing some strange train issues when running this task, which may be due to streaming problems -- so I wonder if this can somehow be the cause.
Best,
James
=> modify streaming syntax of several members

PWGCF/FEMTOSCOPY/AliFemtoUser/AliFemtoAnalysisPionPion.cxx
* Correct error messages when constructing from configobject
=> PWGCF: AliFemtoAnalysisPionPion - Improved logs and more accurate cutclass names

PWGHF/vertexingHF/AliHFSystErr.cxx, PWGHF/vertexingHF/AliHFSystErr.h, PWGHF/vertexingHF/macros/HFPtSpectrum.C
Update for D0 systematics in pp@5TeV 2017
=> Update: D0 in pp@5TeV 2017

PWGCF/Correlations/macros/PIDBFDptDpt/AddTaskPIDBFDptDpt.C
=> added two centrality groups

PWG/FLOW/Tasks/AliAnalysisTaskCMEV0PID.cxx, PWG/FLOW/Tasks/AliAnalysisTaskCMEV0PID.h
Make Clones of external TList and set Flags, add QA after NUA
=> Make Clones of external TList and set Flags, add QA after NUA

PWGCF/FEMTOSCOPY/FemtoDream/AliFemtoDreamTrack.cxx, PWGCF/FEMTOSCOPY/FemtoDream/AliFemtoDreamTrack.h, PWGCF/FEMTOSCOPY/FemtoDream/AliFemtoDreamTrackCuts.cxx, PWGCF/FEMTOSCOPY/FemtoDream/AliFemtoDreamTrackCuts.h, PWGCF/FEMTOSCOPY/FemtoDream/AliFemtoDreamTrackHist.cxx, PWGCF/FEMTOSCOPY/FemtoDream/AliFemtoDreamTrackHist.h, PWGCF/FEMTOSCOPY/macros/AddTaskFemtoDreamPileUpCheck.C, PWGCF/FEMTOSCOPY/macros/AddTaskFemtoDreamSysVar.C
o Further tests to enhance the number of v0 and cascade candidates by relaxing cuts and decreasing the purity
o Tests of the pile-up phenomenon by cutting on the tracks' chi2.
o The previously tested pT cut variations had no impact whatsoever
=> Implementation of different cut variations

PWG/FLOW/Tasks/AliAnalysisTaskCMEV0PID.cxx, PWG/FLOW/Tasks/AliAnalysisTaskCMEV0PID.h, PWGCF/FLOW/macros/AddTaskCMEV0PID.C
Add functionality to run on 2010 data. TPC event plane bug fix
=> Add functionality to run on 2010 data. TPC event plane bug fix

PWGCF/Correlations/DPhi/Unfoldedhistos/AliCSEventCuts.cxx, PWGCF/FEMTOSCOPY/AliFemto/AliFemtoConfigObject.cxx
=> Fix for std=c++14 not supported error

PWGCF/FEMTOSCOPY/macros/Train/KchKchRun2_Apr2018/KK_13TeV_dist/AddTaskFemtoKchHBT1090.C, PWGCF/FEMTOSCOPY/macros/Train/KchKchRun2_Apr2018/KK_13TeV_dist/ConfigFemtoAnalysis.C, PWGCF/FEMTOSCOPY/macros/Train/KchKchRun2_Apr2018/pipi_13TeV_dist/AddTaskFemtoKchHBT1090.C, PWGCF/FEMTOSCOPY/macros/Train/KchKchRun2_Apr2018/pipi_13TeV_dist/ConfigFemtoAnalysis.C
=> Ludmila: Train with Toms PID etc:KchKchRun2_Apr2018

PWGCF/FEMTOSCOPY/FemtoDream/AliFemtoDreamTrackCuts.cxx, PWGCF/FEMTOSCOPY/FemtoDream/AliFemtoDreamTrackCuts.h, PWGCF/FEMTOSCOPY/FemtoDream/AliFemtoDreamTrackHist.cxx, PWGCF/FEMTOSCOPY/macros/AddTaskFemtoDreamPileUpCheck.C
o For very small track chi2 (smaller than 1), the Lambda purity massively decreases (problems with TPC cluster uncertainties?)
o Cut optimization of the ideal track chi2
=> Test track chi2 dependence on fluctuating purity

PWGCF/FEMTOSCOPY/AliFemtoUser/AliFemtoKKTrackCutTest.cxx, PWGCF/FEMTOSCOPY/AliFemtoUser/AliFemtoKKTrackCutTest.h
=> Ludmila: new class AliFemtoKKTrackCutTest

PWGCF/FEMTOSCOPY/AliFemtoUser/CMakeLists.txt, PWGCF/FEMTOSCOPY/AliFemtoUser/PWGCFfemtoscopyUserLinkDef.h
=> For Ludmila new class CMakeLists.txt PWGCFfemtoscopyUserLinkDef.h

PWG/CaloTrackCorrBase/CMakeLists.txt, PWG/EMCAL/EMCALbase/AliEMCALRecoUtils.cxx, PWG/EMCAL/EMCALbase/AliEMCALRecoUtils.h, PWG/EMCAL/EMCALbase/CMakeLists.txt, PWG/EMCAL/EMCALbase/PWGEMCALbaseLinkDef.h, PWGPP/EMCAL/OADBMacros/AliEMCALOCDBTenderConverter.cxx, PWGPP/EMCAL/OADBMacros/CompareOADB_OCDB.C, PWGPP/EMCAL/OADBMacros/CreateEMCAL_BadChannelsHistos.C, PWGPP/EMCAL/OADBMacros/CreateEMCAL_OADB_BadChannels.C, PWGPP/EMCAL/OADBMacros/CreateEMCAL_OADB_CalibReference.C, PWGPP/EMCAL/OADBMacros/CreateEMCAL_OADB_Recalib.C, PWGPP/EMCAL/OADBMacros/CreateEMCAL_OADB_RunByRunTemperatureECalibCorrection.C, PWGPP/EMCAL/OADBMacros/CreateEMCAL_OADB_RunByRunTimeCalib.C, PWGPP/EMCAL/OADBMacros/CreateEMCAL_OCDB_TimeCalib_FromOADB.C, PWGPP/EMCAL/OADBMacros/CreateHistoFile.sh, PWGPP/EMCAL/OADBMacros/RemovePeriodEMCAL_OADB_TimeCalib.C, PWGPP/EMCAL/OADBMacros/UpdateEMCAL_OADB_BadChannels.C, PWGPP/EMCAL/OADBMacros/UpdateEMCAL_OADB_Recalib.C, PWGPP/EMCAL/OADBMacros/UpdateEMCAL_OADB_Recalib11hMC.C, PWGPP/EMCAL/OADBMacros/UpdateEMCAL_OADB_Recalib_Run2.C, PWGPP/EMCAL/OADBMacros/UpdateEMCAL_OADB_RunByRunTimeCalib.C, PWGPP/EMCAL/OADBMacros/UpdateEMCAL_OADB_TimeCalib.C, PWGPP/EMCAL/OADBMacros/testContainerOrig.C, PWGPP/EMCAL/doxymodules.h, TENDER/TenderSupplies/CMakeLists.txt
=> Restore EMCAL changes

PWG/FLOW/Tasks/AliAnalysisTaskCMEV0PID.cxx, PWGCF/FLOW/macros/AddTaskCMEV0PID.C
Use Qn = Qn/SumWgt for TPC EP, fix NUA,MC correction Paths
=> Use Qn = Qn/SumWgt for TPC EP, fix NUA,MC correction Paths

PWG/EMCAL/READMEemcCorrections.txt
Added notes about the use of CDBconnect
@gconesab  , @jdmulligan
=> EMCal CorrFW: Update docs

PWGGA/CaloTrackCorrelations/AliAnaPi0.cxx, PWGGA/CaloTrackCorrelations/AliAnaPi0.h
rename this histogram to something more meaningful
Fix needed to prevent analysis QA train to crash
=> fix, new histogram fhPrimPt only created when fFillOriginHisto is true

PWGPP/macros/AddTaskTrackingUncertAOT.C
Changed default value for the new data member
=> default TPConly=kFALSE

PWG/EMCAL/EMCALbase/AliEmcalTrackSelectionAOD.cxx, PWGJE/EMCALJetTasks/CMakeLists.txt, PWGJE/EMCALJetTasks/PWGJEEMCALJetTasksLinkDef.h, PWGJE/EMCALJetTasks/Tracks/AliAnalysisTaskEmcalClusterNoiseTriggers.cxx, PWGJE/EMCALJetTasks/Tracks/AliAnalysisTaskEmcalClusterNoiseTriggers.h, PWGJE/EMCALJetTasks/macros/AddTaskEmcalClusterNoiseTriggers.C, PWGJE/macros/AddTaskPWG4HighPtTrackQA.C
- Study the cluster energy spectrum for different EMCAL
trigger patch multiplicities
- Add LHC16c2 to the virtual track selection and the PWG4
high-pt tracking task
=> Adding correlation task clusters-patches

PWG/FLOW/Tasks/AliAnalysisTaskCMEV0PID.cxx, PWG/FLOW/Tasks/AliAnalysisTaskCMEV0PID.h, PWGCF/FLOW/macros/AddTaskCMEV0PID.C
Add 2p correlator, Userdefined Cent Estimator, Userdefined Vz cut
=> Add 2p correlator, Userdefined Cent Estimator, Userdefined Vz cut

PWGHF/hfe/AliHFEreducedEvent.cxx, PWGHF/hfe/AliHFEreducedEvent.h, PWGHF/hfe/AliHFEreducedEventCreatorESD.cxx, PWGHF/hfe/AliHFEreducedEventCreatorESD.h, PWGHF/hfe/AliHFEreducedTrack.cxx, PWGHF/hfe/AliHFEreducedTrack.h
The heavy-flavour electron reduced event trees are updated to include more information and the event plane correction.
=> "HFE tree creation updated to include field, event plane, etc"

PWGDQ/dielectron/LMEE/AliAnalysisTaskSimpleTreeMaker.cxx, PWGDQ/dielectron/macrosLMEE/Config_acapon.C, PWGDQ/dielectron/macrosLMEE/LMEECutLib_acapon.C
SimpleTreeMaker cut reproduced in cut library enabling direct cross checks down to the track level
=> Cut alignment b/w SimpleTreeMaker and acapon LMEE cut library

PWGJE/EMCALJetTasks/UserTasks/AliAnalysisTaskEmcalJetPerformance.cxx, PWGJE/EMCALJetTasks/UserTasks/AliAnalysisTaskEmcalJetPerformance.h
=> implement 15o pileup cuts, check +/- eta, and require mc matched jet acc

PWGHF/correlationHF/AliAnalysisHFCorrOnFlySim.cxx
(but for now, this approach is just switched off before having a better understanding of the generators themselves)
=> §Updated approach to tag multi-HQpair events in D-h template class

PWG/FLOW/Tasks/AliAnalysisTaskCMEV0PID.cxx
change PID cut for kaon, comment unused histograms
=> change PID cut for kaon, comment unused histograms

PWGJE/EMCALJetTasks/UserTasks/AliAnalysisTaskEmcalJetSpectra8TeVTriggerQA.cxx
Fixed typos with Pt plots and added plots to start to look into z_leading and JES cuts in spectra
=> Fixed Typos, Added plots to start to look at NEF and z_leading

PWGHF/jetsHF/AliAnalysisTaskJetExtractorHF.cxx, PWGJE/EMCALJetTasks/UserTasks/AliAnalysisTaskChargedJetsHadronToy.cxx
Changes to allow running the jet extractor on toy data. Used in jet background study.
=> Jet bgrd. toy, extractor refinements

PWG/EMCAL/EMCALtasks/AliAodSkimTask.cxx, PWG/EMCAL/EMCALtasks/AliAodSkimTask.h, PWG/EMCAL/macros/AddTaskAodSkim.C
Added ZDC, dimuon branches
Versioning of aliphysics and settings for task
version 1.0
=> added zdc, dimuons, and versioning info

PWGCF/FEMTOSCOPY/macros/Train/KchKchRun2_Apr2018/pipi_13TeV_dist/ConfigFemtoAnalysis.C
=> For Ludmila: 18 apr 2018

PWGGA/GammaConv/macros/AddTask_GammaConvDalitzV1_pp.C
Changes in AddTask_GammaConvDalitzV1_pp.C
* Parameters for Meson QA included.
* Parameters for the V0Reader initialization included
=> Add MesonQA option to the AddTask for dalitz analysis in pp colisions

PWGHF/vertexingHF/AliHFSystErr.cxx, PWGHF/vertexingHF/AliHFSystErr.h
Final Lc systematics for the 3 analyses aiming for QM approval
=> Lc systematics updates for run 2

PWGHF/vertexingHF/AliHFSystErr.cxx
Update for RawYield, Cut Variation, MCPtShape. 
PID and Tracking not final ones
=> Updated D0 errors for pp 2017

PWGGA/PHOSTasks/PHOS_LHC16_pp/AliPP13EfficiencySelectionMC.cxx, PWGGA/PHOSTasks/PHOS_LHC16_pp/AliPP13SelectionWeights.cxx
For neutral meson analysis @ 13 TeV
=> Update the single particle spectra normalization in PHOS 

PWGJE/EMCALJetTasks/UserTasks/AliAnalysisTaskEmcalJetPerformance.cxx
=> add compatibility for pp

PWGHF/vertexingHF/AliAnalysisTaskSEB0toDStarPi.cxx, PWGHF/vertexingHF/AliAnalysisTaskSEB0toDStarPi.h, PWGHF/vertexingHF/AliRDHFCutsB0toDStarPi.cxx, PWGHF/vertexingHF/AliRDHFCutsB0toDStarPi.h
=> Update for B0 to DStar pi code

PWGHF/jetsHF/AliAnalysisTaskHFJetIPQA.cxx
Important correlation cross check (please approve fast)
=> Important: Correlation cross check

PWG/CALO/AliCaloNonLinearity.cxx, PWG/CALO/AliCaloNonLinearity.h
Cluster energy fine tuning parameters have been updated with the ones used in PWGGA/GammaConv/AliCaloPhotonCuts.cxx.
=> PWG/CALO: Update of MC finetuning parameters for several productions

PWG/EMCAL/macros/AddTaskAodSkim.C
changes to allow setting the output handler in the train config
=> only add output handler when not yet there

PWGJE/EMCALJetTasks/UserTasks/AliAnalysisTaskJetPP.cxx, PWGJE/EMCALJetTasks/UserTasks/AliAnalysisTaskJetPP.h
Changed the rejection of pileup events.
=> Changed pileup rejection.

PWG/FLOW/Tasks/AliAnalysisTaskCMEV0PID.cxx
update PID pi,k,p nSigTPC=3 lowPt, nSigTOF=2 highpT
=> update PID pi,k,p nSigTPC=3 lowPt, nSigTOF=2 highpT

PWGJE/EMCALJetTasks/Tracks/AliAnalysisTaskEmcalJetEnergySpectrum.cxx, PWGJE/EMCALJetTasks/Tracks/AliAnalysisTaskEmcalJetSubstructureTree.cxx
Add trigger selection of the EMCAL gamma triggers to the
jet substructure tree and the jet spectrum task.
=> Add support for EMCAL gamma trigger

PWGCF/EBYE/Fluctuations/AliEbyEPidEfficiencyContamination.cxx
Tighter nsigma cut for proton- for temp check
=> Tighter nsigma cut for proton- for temp check

PWGHF/jetsHF/AliAnalysisTaskJetExtractorHF.cxx
In particular interesting for PbPb.
=> Allow extraction of jets below 0 GeV/c

PWG/FLOW/Tasks/AliAnalysisTaskCMEV0PID.cxx, PWG/FLOW/Tasks/AliAnalysisTaskCMEV0PID.h
Read MCeffi of proton separately for +ve and -ve
=> Read MCeffi of proton separately for +ve and -ve

PWGCF/FEMTOSCOPY/AliFemto/AliFemtoConfigObject.h
=> AliFemtoConfigObject - Removed invalid operator>> functions (may not read into pointers)

PWGLF/STRANGENESS/Cascades/Run2/AliAnalysisTaskStrangenessVsMultiplicityMCRun2pPb.cxx, PWGLF/STRANGENESS/Cascades/Run2/AliAnalysisTaskStrangenessVsMultiplicityMCRun2pPb.h, PWGLF/STRANGENESS/Cascades/Run2/AliAnalysisTaskStrangenessVsMultiplicityRun2pPb.cxx, PWGLF/STRANGENESS/Cascades/Run2/AliAnalysisTaskStrangenessVsMultiplicityRun2pPb.h
Include all V0 centrality estimators in the tree outputs for comparisons
=> Centrality output now includes V0A, V0C and V0M

PWGHF/hfe/AliAnalysisTaskTPCCalBeauty.cxx, PWGHF/hfe/AliAnalysisTaskTPCCalBeauty.h
merge conflict text left in macro somehow. taken out.
=> Weird merge bug fix.

PWGHF/hfe/AliAnalysisTaskTPCCalBeauty.cxx
Added Abs() to MC label, put inv. mass calc in data after eID cuts again.
=> Added Abs() to MC label, put inv. mass calc after eID cuts again

PWGJE/EMCALJetTasks/Tracks/AliAnalysisTaskEmcalClustersRef.cxx
- Move DCAL clusters in phi range from 0 to 2 pi
- Do not fill event counters for exclusive classes
in case exclusive classes are not selected
=> [EMCAL-180] Fixes for phi range and non-exclusive triggers

PWGUD/DIFFRACTIVE/CEPdevel/RawBuffers/CEPRawADBuffer.cxx, PWGUD/DIFFRACTIVE/CEPdevel/RawBuffers/CEPRawADBuffer.h, PWGUD/DIFFRACTIVE/CEPdevel/RawBuffers/CEPRawCaloClusterTrack.cxx, PWGUD/DIFFRACTIVE/CEPdevel/RawBuffers/CEPRawCaloClusterTrack.h, PWGUD/DIFFRACTIVE/CEPdevel/RawBuffers/CEPRawEventBuffer.cxx, PWGUD/DIFFRACTIVE/CEPdevel/RawBuffers/CEPRawEventBuffer.h, PWGUD/DIFFRACTIVE/CEPdevel/RawBuffers/CEPRawFMDBuffer.h, PWGUD/DIFFRACTIVE/CEPdevel/RawBuffers/CEPRawTrackBuffer.cxx, PWGUD/DIFFRACTIVE/CEPdevel/RawBuffers/CEPRawTrackBuffer.h, PWGUD/DIFFRACTIVE/CEPdevel/RawBuffers/CEPRawV0Buffer.cxx, PWGUD/DIFFRACTIVE/CEPdevel/RawBuffers/CEPRawV0Buffer.h
need to include latest revision of CEPRawBuffers in AliPhysics
=> lates revision of CEPRawBuffers

PWGDQ/dielectron/macrosJPSI/AddTask_xbai_pp_QA.C, PWGDQ/dielectron/macrosJPSI/ConfigJpsi_xbai_pp_QA_Final_Trendingbis3.C
Xiaozhi created a macros to add PWGDQ/dielectron/macrosJPSI/AddTask_xbai_pp_QA.C for the pp QA.
=> Add a new macro to make the pp QA  

PWGLF/CommonUtils/MConthefly/AliAnalysisTaskSimSpectraLF.cxx, PWGLF/CommonUtils/MConthefly/AliAnalysisTaskSimSpectraLF.h, PWGLF/CommonUtils/MConthefly/macros/AddTaskSimSpectraLF.C
=> Clean-up of unused objects

PWGCF/EBYE/KaonIsospinFluctuations/AliAnalysisTaskKaonIsospinFluct.cxx, PWGCF/EBYE/KaonIsospinFluctuations/AliAnalysisTaskKaonIsospinFluct.h
Committer: Ranjit Nayak <ranjit.nayak@cern.ch>
new file:   PWGCF/EBYE/KaonIsospinFluctuations/AliAnalysisTaskKaonIsospinFluct.cxx
new file:   PWGCF/EBYE/KaonIsospinFluctuations/AliAnalysisTaskKaonIsospinFluct.h
Commiting the task class and header file for kaon isospin fluctuations analysis
=> git push rknayak

PWGCF/FEMTOSCOPY/macros/Train/pPbKKfemto/exp/conf_run2/2/ConfigFemtoAnalysis.C
=> Lego train: Config file for Lena 10 may 2018

PWGCF/FLOW/GF/AliAnalysisTaskChargedFlow.cxx, PWGCF/FLOW/GF/AliAnalysisTaskChargedFlow.h, PWGCF/FLOW/macros/AddTaskChargedFlow.C
edited 1D TProfiles to 2D TProfiles
=> edited Generic Framework task that is used to run over MC trains

PWGJE/EMCALJetTasks/Tracks/AliAnalysisTaskEmcalJetEnergySpectrum.cxx
Separately monitoring the maximum jet in the event
=> Adding histogram for maximum jet in the event

PWGCF/FEMTOSCOPY/macros/Train/KchKchRun2_May2018/KK_13TeV_dist/AddTaskFemtoKchHBT1090.C, PWGCF/FEMTOSCOPY/macros/Train/KchKchRun2_May2018/KK_13TeV_dist/ConfigFemtoAnalysis.C
=> Lego Train: Ludmila 14 May 2018

PWGCF/FEMTOSCOPY/macros/Train/pPbKKfemto/exp/conf_run2/2/ConfigFemtoAnalysis.C
=> Lego Train: for Elena 15 May 2018

PWGPP/TPC/macros/README2.md, PWGPP/TPC/macros/TPCQAWebpage/tpcCalibValidation.C, PWGPP/TPC/macros/tpcMCValidation.C, PWGPP/TPC/macros/tpcQAValidation.C
*  QA for the calibration (used eg. for the PID performance studies)
*  prototype of more advanced standard QA
=> Qa development

PWGJE/EMCALJetTasks/Tracks/AliAnalysisTaskEmcalJetEnergySpectrum.cxx
- Fix binning
- Add cluster ANY as default cluster
=> Fix binning in trigger cluster counting

PWGCF/FEMTOSCOPY/macros/Train/pPbKKfemto/exp/conf_run2/2/ConfigFemtoAnalysis.C
=> Lego train: Elena 17 may 2018

PWGJE/EMCALJetTasks/CMakeLists.txt, PWGJE/EMCALJetTasks/PWGJEEMCALJetTasksLinkDef.h, PWGJE/EMCALJetTasks/Tracks/AliAnalysisTaskEmcalTriggerCorrelationMC.cxx, PWGJE/EMCALJetTasks/Tracks/AliAnalysisTaskEmcalTriggerCorrelationMC.h, PWGJE/EMCALJetTasks/macros/AddTaskEmcalTriggerCorrelationMC.C
New task studying the correlation of EMCAL
triggers from offline patches (for MC).
=> [EMCAL-209] Trigger correlation in MC

PWGLF/SPECTRA/IdentifiedHighPt/train/AliAnalysisTaskHighPtDeDx.cxx, PWGLF/SPECTRA/IdentifiedHighPt/train/macros/AddTask.C
=> debug ok: zvtx looks good

PWGGA/PHOSTasks/PHOS_Run2/AliAnalysisTaskPHOSPi0EtaToGammaGamma.cxx, PWGGA/PHOSTasks/PHOS_Run2/AliAnalysisTaskPHOSPi0EtaToGammaGamma.h, PWGGA/PHOSTasks/PHOS_Run2/AliAnalysisTaskPHOSSingleSim.cxx, PWGGA/PHOSTasks/PHOS_Run2/macros/AddTaskPHOSSingleSim.C
introduce opening angle cut study for high pT pi0 in PHOS. (pT > 30 GeV/c)
=> introduce opening angle cut

PWGGA/PHOSTasks/PHOS_Run2/AliAnalysisTaskPHOSPi0EtaToGammaGamma.cxx
add opening cut for both same and mixed event
=> update opening angle cut study

PWGGA/GammaConv/AliAnalysisTaskGammaConvDalitzV1.cxx, PWGGA/GammaConv/AliAnalysisTaskGammaConvDalitzV1.h, PWGGA/GammaConv/macros/AddTask_GammaConvDalitzV1_PbPb.C
New histograms for Chic analysis and updated AddTask for PbPb of the Dalitz anaylsis
=> Update AddTask for PbPb and Chic option

PWG/CaloTrackCorrBase/AliAnaCaloTrackCorrMaker.cxx, PWG/CaloTrackCorrBase/AliMCAnalysisUtils.cxx
add fix in case no cocktail is available but there is a main header
=> When getting pT hard value, get Pythia header from common method 

PWGGA/PHOSTasks/PHOS_Run2/AliAnalysisTaskPHOSPi0EtaToGammaGamma.cxx, PWGGA/PHOSTasks/PHOS_Run2/AliAnalysisTaskPHOSPi0EtaToGammaGamma.h
add omega(782) meson analysis via 3pions decay channel.
=> add omega(782) meson analysis

PWGGA/PHOSTasks/PHOS_Run2/AliAnalysisTaskPHOSPi0EtaToGammaGamma.cxx
remove unnecessary histogram definitions.
=> remove unnecessary lines

PWGGA/PHOSTasks/PHOS_Run2/AliAnalysisTaskPHOSPi0EtaToGammaGamma.cxx
=> fix mass range for pi0

PWGGA/PHOSTasks/PHOS_Run2/AliAnalysisTaskPHOSSingleSim.cxx
remove unnecessary lines in single sim.
=> remove unnecessary lines in single sim

PWG/FLOW/Tasks/AliAnalysisTaskCMEV0PID.cxx, PWG/FLOW/Tasks/AliAnalysisTaskCMEV0PID.h
comment out PID differential histograms (and remove unused histograms)
=> comment out PID differential histograms (and remove unused histograms)

PWGGA/EMCALTasks/AliAnalysisTaskGammaHadron.cxx, PWGGA/EMCALTasks/AliAnalysisTaskGammaHadron.h
Replace MC SharedGrandMother with MC SharedAncestor approach.
Add Single MC Particle match category.
=> Update MC information methods

PWGGA/PHOSTasks/PHOS_Run2/AliAnalysisTaskPHOSPi0EtaToGammaGamma.cxx, PWGGA/PHOSTasks/PHOS_Run2/AliAnalysisTaskPHOSPi0EtaToGammaGamma.h
introduce minimum pT cut for omega(782)->3pi
=> introduce minimum pT cut for omega->3pi

PWGCF/Correlations/DPhi/AliAnalysisTaskGeneralBF.cxx, PWGCF/Correlations/DPhi/AliAnalysisTaskGeneralBF.h, PWGCF/Correlations/macros/PIDBFDptDpt/AddTaskGeneralBF.C
Create generalized balance function code
=> Create generalized balance function code

PWGCF/Correlations/DPhi/CMakeLists.txt, PWGCF/Correlations/DPhi/PWGCFCorrelationsDPhiLinkDef.h
add AliAnalysisTaskGeneralBF.cxx
=> add AliAnalysisTaskGeneralBF.cxx

PWGGA/PHOSTasks/PHOS_Run2/AliAnalysisTaskPHOSPi0EtaToGammaGamma.cxx, PWGGA/PHOSTasks/PHOS_Run2/AliAnalysisTaskPHOSPi0EtaToGammaGamma.h, PWGGA/PHOSTasks/PHOS_Run2/AliPHOSClusterCuts.h, PWGGA/PHOSTasks/PHOS_Run2/macros/AddTaskPHOSPi0EtaToGammaGamma_pp_5TeV_LHC17pq.C
update data driven approach for photon purity
=> update DDA for photon purity

PWG/EMCAL/config/AliEmcalCorrectionConfiguration.yaml, PWGGA/CaloTrackCorrelations/CMakeLists.txt, PWGGA/CaloTrackCorrelations/yaml/EMCalCorrConfig_Data_ClV1.yaml, PWGGA/CaloTrackCorrelations/yaml/EMCalCorrConfig_MC_Run1_ClV1.yaml, PWGGA/CaloTrackCorrelations/yaml/EMCalCorrConfig_MC_Run1_ClV1_xTalk.yaml
and add example yaml for data and MC in PWGGA/CaloTrackCorrelations
=> Update default xTalk parametrization 

PWGGA/PHOSTasks/PHOS_Run2/AliAnalysisTaskPHOSPi0EtaToGammaGamma.cxx, PWGGA/PHOSTasks/PHOS_Run2/AliAnalysisTaskPHOSPi0EtaToGammaGamma.h
implement track matching in mixed event to estimate photon purity
=> implement track matching in mixed event

CMakeLists.txt
Ciao @dberzano ,
this is on the same line of what you did for o2. It does need a scrutiny before merging.
Cheers,
Max
=> Improve install speed on macOS (see O2)

PWGCF/EBYE/Fluctuations/AliEbyEPidEfficiencyContamination.cxx
Proton pid reverted to previous version. Some extra pid strategies are added for pion.
=> modification to pid for pion and proton

PWGCF/FEMTOSCOPY/macros/Train/KchKchRun2_May2018_2/KK_13TeV_dist/AddTaskFemtoKchHBT1090.C, PWGCF/FEMTOSCOPY/macros/Train/KchKchRun2_May2018_2/KK_13TeV_dist/ConfigFemtoAnalysis.C, PWGCF/FEMTOSCOPY/macros/Train/KchKchRun2_May2018_2/pipi_13TeV_dist/AddTaskFemtoKchHBT1090.C, PWGCF/FEMTOSCOPY/macros/Train/KchKchRun2_May2018_2/pipi_13TeV_dist/ConfigFemtoAnalysis.C
=> LegoTrain:For Ludmila, May 28, 2018

PWGGA/PHOSTasks/PHOS_Run2/AliAnalysisTaskPHOSPi0EtaToGammaGamma.cxx
update track matching in mixed event
=> update track matching in mixed event

PWGGA/PHOSTasks/PHOS_Run2/AliAnalysisTaskPHOSPi0EtaToGammaGamma.cxx, PWGGA/PHOSTasks/PHOS_Run2/AliAnalysisTaskPHOSPi0EtaToGammaGamma.h
fix track matching in mixed event.
Track matching fully relies on PHOSTender.
=> fix track matching in mixed event

PWG/EMCAL/EMCALtasks/AliAodSkimTask.cxx, PWG/EMCAL/EMCALtasks/AliAodSkimTask.h
v1.1 of AOD skimmer (locally tested by Nico and found to work)
=> include tracklets

PWGGA/PHOSTasks/PHOS_Run2/AliAnalysisTaskPHOSPi0EtaToGammaGamma.cxx, PWGGA/PHOSTasks/PHOS_Run2/AliAnalysisTaskPHOSPi0EtaToGammaGamma.h
introduce kinematic cut for omega 782 -> 3pi
=> introduce kinematic cut for omega

PWGJE/EMCALJetTasks/Tracks/AliAnalysisTaskChargedParticlesRef.cxx, PWGJE/EMCALJetTasks/Tracks/AliAnalysisTaskChargedParticlesRef.h, PWGJE/EMCALJetTasks/Tracks/AliAnalysisTaskEmcalClustersRef.cxx, PWGJE/EMCALJetTasks/Tracks/AliAnalysisTaskEmcalClustersRef.h, PWGJE/EMCALJetTasks/Tracks/AliAnalysisTaskEmcalRecalcPatchesRef.cxx, PWGJE/EMCALJetTasks/Tracks/AliAnalysisTaskEmcalTriggerBase.cxx, PWGJE/EMCALJetTasks/Tracks/AliEmcalAnalysisFactory.cxx
- Fix filter bits for global tracks
- Release default dependency on trigger patch container
- Make matched cluster histograms optional
=> Fixes in track spectrum task

PWGGA/CaloTrackCorrelations/macros/QA/InvMassFit.C
improved handling  and comparison
=> cleaning and refactoring, pairs in same SM/sector/side 

PWGHF/hfe/AliAnalysisTaskHFEemcQA.cxx, PWGHF/hfe/AliAnalysisTaskHFEemcQA.h
Adding histograms to compare with TPC analysis at low pT.
=> Add histos to compare with TPC analysis

PWGPP/ITS/QA/DrawTrendingITSQA.C
Changes in y-axis size of vertex coordinates histograms for visualization purpose
=> Change in y-axis size for visualization purpose

PWGGA/CaloTrackCorrelations/macros/QA/InvMassFit.C
add individual switches to SM/Side/Sector invariant mass checks
=> fix error calculation, add graph results division to sum of combinations

PWGGA/PHOSTasks/PHOS_Run2/AliAnalysisTaskPHOSPi0EtaToGammaGamma.cxx, PWGGA/PHOSTasks/PHOS_Run2/AliAnalysisTaskPHOSPi0EtaToGammaGamma.h
update track selection for charged pion (omega 782->3pi)
=> update track selection for charged pion

PWGGA/PHOSTasks/PHOS_LHC16_pp/AliPP13NonlinearityScanSelection.h, PWGGA/PHOSTasks/PHOS_LHC16_pp/AliPP13NonlinearitySelection.cxx, PWGGA/PHOSTasks/PHOS_LHC16_pp/AliPP13PhotonSelection.cxx, PWGGA/PHOSTasks/PHOS_LHC16_pp/AliPP13PhotonSelectionMC.h, PWGGA/PHOSTasks/PHOS_LHC16_pp/AliPP13SelectionWeights.cxx, PWGGA/PHOSTasks/PHOS_LHC16_pp/AliPP13SelectionWeights.h, PWGGA/PHOSTasks/PHOS_LHC16_pp/macros/AddAnalysisTaskPP.C
Add histogram names and the parameter values to the logs.
=> Update the nonlinearity parametrization for all productions. 

PWGLF/STRANGENESS/Cascades/Run2/AliAnalysisTaskStrangenessVsMultiplicityMCRun2.cxx, PWGLF/STRANGENESS/Cascades/Run2/AliAnalysisTaskStrangenessVsMultiplicityMCRun2.h, PWGLF/STRANGENESS/Cascades/Run2/AliAnalysisTaskStrangenessVsMultiplicityRun2.cxx, PWGLF/STRANGENESS/Cascades/Run2/AliAnalysisTaskStrangenessVsMultiplicityRun2.h
Adding branches to keep the information of TOF bunch crossing id for each daughter track
=> Added branch to store TOF bunch crossing id

PWGJE/EMCALJetTasks/UserTasks/AliAnalysisTaskJetCoreEmcal.cxx, PWGJE/EMCALJetTasks/UserTasks/AliAnalysisTaskJetCoreEmcal.h
needed for 2d unfolding of pt-DeltaPhi distributions
=> combine analysis output into 1 THnSparse, plus some tidying

PWGPP/EMCAL/AliAnalysisTaskEMCALClusterize.cxx, PWGPP/EMCAL/AliAnalysisTaskEMCALClusterize.h
and compress the cell energy induce calculation for better understanding
=> add addictional cut on minimum induced energy to avoid strong non linearity

PWG/muon/AliAnalysisTaskLMREventFilter.cxx
Remove autosave due to some problem at the merging stage.
=> Small modification for remove autosave

PWGGA/EMCALTasks/AliAnalysisTaskGammaHadron.cxx
Removes unused variables.
Attempts to fix root 6 compilation issue
=> Removes unused variables and fix root6 compilation issue

PWGDQ/dielectron/core/AliAnalysisTaskElectronEfficiencyV2.cxx
=> PWGDQ: Enhance resolution histograms

PWGGA/GammaConv/AliCaloPhotonCuts.cxx
=> PWGGA/GammaConv MC E cluster calib DCal 5 Tev 2017

PWGHF/hfe/AliAnalysisTaskHFEemcQA.cxx, PWGHF/hfe/AliAnalysisTaskHFEemcQA.h, PWGHF/hfe/macros/AddTaskHFEemcQA.C
Adding option to choose track filter bit - ITSconstrianed
Change binning of histograms for comparison
=> Add option to change track filter bit

PWGGA/PHOSTasks/PHOS_Run2/AliAnalysisTaskPHOSPi0EtaToGammaGamma.cxx
change histogram binnings for SP method.
=> change histogram binning

PWG/MCLEGO/CRMC/gen_eposlhc_lf_pp_5TeV.sh
Configuration file for on-the-fly generation (MCGen_pp train)
=> Macro to run EPOS-LHC at 5.02 TeV in pp

PWGGA/CaloTrackCorrelations/macros/AddTaskCaloTrackCorrBase.C, PWGGA/CaloTrackCorrelations/macros/AddTaskGammaHadronCorrelationSelectAnalysis.C, PWGGA/CaloTrackCorrelations/macros/AddTaskMultipleTrackCutIsoConeAnalysis.C, PWGGA/CaloTrackCorrelations/macros/ConfigureCaloTrackCorrAnalysis.C, PWGGA/CaloTrackCorrelations/macros/GetAlienGlobalProductionVariables.C, PWGPP/EMCAL/macros/AddTaskEMCALClusterize.C
for new MC and periods and fixes for DCal
=> Several updates to make the analysis more automatic

PWGCF/FEMTOSCOPY/macros/Train/pPbKKfemto/MC/conf_2016/1/ConfigFemtoAnalysis.C
=> Elena changed /pPbKKfemto/MC/conf_2016/1/ConfigFemtoAnalysis.C

PWGGA/PHOSTasks/PHOS_Run2/AliAnalysisTaskPHOSPi0EtaToGammaGamma.cxx, PWGGA/PHOSTasks/PHOS_Run2/AliAnalysisTaskPHOSPi0EtaToGammaGamma.h
change histogram binning for SP
=> change histogram binning for SP

PWGGA/PHOSTasks/PHOS_Run2/AliAnalysisTaskPHOSPi0EtaToGammaGamma.cxx
=> update histograms for PID

PWGCF/Correlations/JCORRAN/Pro/AliJCDijetHistos.cxx, PWGCF/Correlations/JCORRAN/Pro/AliJCDijetHistos.h, PWGCF/Correlations/JCORRAN/Pro/AliJCDijetTask.cxx, PWGCF/Correlations/JCORRAN/Pro/AliJCDijetTask.h, PWGCF/Correlations/JCORRAN/Pro/CMakeLists.txt, PWGCF/Correlations/JCORRAN/Pro/PWGCFCorrelationsJCORRANProLinkDef.h, PWGCF/Correlations/macros/jcorran/AddTaskJCDijetTask.C
I have started a dijet analysis, where I reconstruct the jets using fastjet in the code.
=> A start of a dijet analysis AliJCDijet.

PWGCF/FEMTOSCOPY/macros/Train/pPbKKfemto/exp/conf_run2/ConfigFemtoAnalysis.C
=> Elena: Lego Train Config for purity

PWGPP/TPC/macros/drawPerformanceTPCQAMatch.C
* Set fit start values and limits
* scope single canvases for cleaner separation
=> Fix crashes in the QA

PWGDQ/dielectron/LMEE/AliAnalysisTaskMLTreeMaker.cxx, PWGDQ/dielectron/macrosLMEE/AddTaskMLTreeMakerwCutLib.C, PWGDQ/dielectron/macrosLMEE/AddTask_miweber_LMEE_PbPb_woCutLib.C, PWGDQ/dielectron/macrosLMEE/Config_miweber_LMEE_PbPb_woCutLib.C, PWGDQ/dielectron/macrosLMEE/LMEECutLib_slehner.C
-fix bugs in implementation of TPC recalibration for electrons in MLTreeMaker and Config_miweber_LMEE_PbPb_woCutLib
-was tested to give compatible results for dieleFW and MLTreeMaker
=> fix problems in implementation of TPC recalibration 

PWGGA/PHOSTasks/PHOS_Run2/AliAnalysisTaskPHOSPi0EtaToGammaGamma.cxx
=> add histograms for purity

PWGGA/GammaConv/macros/AddTask_GammaConvNeutralMesonPiPlPiMiPiZero_CaloMode_pp.C, PWGGA/GammaConv/macros/AddTask_GammaConvNeutralMesonPiPlPiMiPiZero_ConvMode_pp.C, PWGGA/GammaConv/macros/AddTask_GammaConvNeutralMesonPiPlPiMiPiZero_MixedMode_pp.C, PWGGA/GammaConv/macros/AddTask_OmegaToPiZeroGamma_pp.C
MB for 3 pi,
added 13TeV for pi0gamma
=> PWGGA: Added 13 TeV Cut Numbers for Omega

PWGPP/ITS/AliAnalysisTaskITSsaTracks.cxx, PWGPP/global/AliAnalysisTaskCheckESDTracks.cxx
To address issues of https://alice.its.cern.ch/jira/browse/ALIROOT-7743?focusedCommentId=215805&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-215805
=> Fix: query MC with abs(label), check return result

PWGCF/FEMTOSCOPY/macros/Train/KchKchRun2_Jun2018/KK_13TeV_dist/AddTaskFemtoKchHBT1090.C, PWGCF/FEMTOSCOPY/macros/Train/KchKchRun2_Jun2018/KK_13TeV_dist/ConfigFemtoAnalysis.C, PWGCF/FEMTOSCOPY/macros/Train/KchKchRun2_Jun2018/pipi_13TeV_dist/AddTaskFemtoKchHBT1090.C, PWGCF/FEMTOSCOPY/macros/Train/KchKchRun2_Jun2018/pipi_13TeV_dist/ConfigFemtoAnalysis.C
=> Ludmila: June K and pi trains

PWGLF/CommonUtils/MConthefly/AliAnalysisTaskSimSpectraLF.cxx
Adding Sigma 0 to particle list in .cxx
=> Adding Sigma 0 to particle list

PWGJE/EMCALJetTasks/macros/JetQA/plotPWGJEQA.py, PWGJE/EMCALJetTasks/macros/JetQA/plotPowerpoint.py, PWGJE/EMCALJetTasks/macros/JetQA/runJetQA.sh
@jdmulligan  please have a look.
=> added cell time QA histogram

PWGGA/GammaConv/AliConversionPhotonCuts.cxx, PWGGA/GammaConv/macros/AddTask_GammaConvV1_pp2.C
=> PWGGA/GammaConv added configs for cosPA & dca scan

PWGGA/GammaConv/AliAnalysisTaskGammaConvV1.cxx
QA binning and standard pT binning was mixed in some places
=> PWGGA/GammaConv: further fixes for pT binning for MC histograms in GammaConv task

PWGCF/FEMTOSCOPY/macros/Train/pPbKKfemto/MC/conf_2016/1/ConfigFemtoAnalysis.C
=> Elena: train 14 June 2018

PWGCF/FEMTOSCOPY/macros/Train/KchKchRun2_Jun2018_2/KK_13TeV_dist/AddTaskFemtoKchHBT1090.C, PWGCF/FEMTOSCOPY/macros/Train/KchKchRun2_Jun2018_2/KK_13TeV_dist/ConfigFemtoAnalysis.C, PWGCF/FEMTOSCOPY/macros/Train/KchKchRun2_Jun2018_2/KpKm_13TeV/AddTaskFemtoKchHBT1090.C, PWGCF/FEMTOSCOPY/macros/Train/KchKchRun2_Jun2018_2/KpKm_13TeV/ConfigFemtoAnalysis.C, PWGCF/FEMTOSCOPY/macros/Train/KchKchRun2_Jun2018_2/pipi_13TeV_dist/AddTaskFemtoKchHBT1090.C, PWGCF/FEMTOSCOPY/macros/Train/KchKchRun2_Jun2018_2/pipi_13TeV_dist/ConfigFemtoAnalysis.C, PWGCF/FEMTOSCOPY/macros/Train/KchKchRun2_Jun2018_2/pippim_13TeV/AddTaskFemtoKchHBT1090.C, PWGCF/FEMTOSCOPY/macros/Train/KchKchRun2_Jun2018_2/pippim_13TeV/ConfigFemtoAnalysis.C
=> Ludmila: Train new mixied distr

PWGHF/hfe/AliAnalysisTaskTPCCalBeauty.cxx, PWGHF/hfe/AliAnalysisTaskTPCCalBeauty.h
Added E/p vs. pT plot before applying TPC nsigma cut.
=> Added histo for TPC eff calc

PWGCF/Correlations/JCORRAN/Pro/AliBSDiJetTask.cxx
In AliBSDijetTask, Hybrid track selection is updated.
=> Hybrid track selection updated

PWGCF/FEMTOSCOPY/macros/Train/KpmHBT20/0010/AddTaskFemtoKchHBT0010.C, PWGCF/FEMTOSCOPY/macros/Train/KpmHBT20/0010/ConfigFemtoAnalysis.C, PWGCF/FEMTOSCOPY/macros/Train/KpmHBT20/1090/AddTaskFemtoKchHBT1090.C, PWGCF/FEMTOSCOPY/macros/Train/KpmHBT20/1090/ConfigFemtoAnalysis.C
=> Lego Train: K+K- NsigmaTPC=2 0.4<p<0.45 GeV/c

PWGCF/FEMTOSCOPY/FemtoDream/AliFemtoDreamAnalysis.cxx, PWGCF/FEMTOSCOPY/FemtoDream/AliFemtoDreamEvent.cxx, PWGCF/FEMTOSCOPY/FemtoDream/AliFemtoDreamTrack.cxx
Memory leak from creating ESD TPC only tracks, are now properly deleted
=> Memory Leak fix 

PWGCF/FEMTOSCOPY/FemtoDream/AliFemtoDreamAnalysis.cxx, PWGCF/FEMTOSCOPY/macros/AddTaskFemtoDream.C
for pp, pXi pairs and their respective antiparticles. 
Dummy container for the Lambda candidates since ESD support is still missing there.
=> Full implementation of the CF calculation 

PWGCF/Correlations/JCORRAN/Pro/AliJCDijetHistos.cxx, PWGCF/Correlations/JCORRAN/Pro/AliJCDijetHistos.h, PWGCF/Correlations/JCORRAN/Pro/AliJCDijetTask.cxx, PWGCF/Correlations/JCORRAN/Pro/AliJCDijetTask.h, PWGCF/Correlations/macros/jcorran/AddTaskJCDijetTask.C
In addition I streamlined the different jets and dijets in a single table.
=> Added constituent cut for jets and macro arguments.

PWGCF/Correlations/DPhi/AliAnalysisTaskGeneralBF.cxx, PWGCF/Correlations/DPhi/AliAnalysisTaskGeneralBF.h, PWGCF/Correlations/macros/PIDBFDptDpt/AddTaskGeneralBF.C
allow particle 1 & 2 to do PID separately
=> allow particle 1 & 2 to do PID separately

PWGLF/SPECTRA/MultEvShape/AliMESpidTask.cxx
Request dirPlus and dirMinus to be closer than 0.2
=> Changing the directivity definition

PWGLF/SPECTRA/PiKaPr/TPC/XeXe544/macros/ChangeErrors.C, PWGLF/SPECTRA/PiKaPr/TPC/XeXe544/macros/DrawPrimFrac.C, PWGLF/SPECTRA/PiKaPr/TPC/XeXe544/macros/DrawRatio.C, PWGLF/SPECTRA/PiKaPr/TPC/XeXe544/macros/DrawRatioEfficiency.C, PWGLF/SPECTRA/PiKaPr/TPC/XeXe544/macros/DrawSystematics.C, PWGLF/SPECTRA/PiKaPr/TPC/XeXe544/macros/PiKp_CorrectedSpectra_PPbarOnly.C, PWGLF/SPECTRA/PiKaPr/TPC/XeXe544/macros/PiKp_CorrectedSpectra_Pik.C, PWGLF/SPECTRA/PiKaPr/TPC/XeXe544/macros/PiKp_FixCutSpectra_2018_04.C, PWGLF/SPECTRA/PiKaPr/TPC/XeXe544/macros/PlotFeedDown.C, PWGLF/SPECTRA/PiKaPr/TPC/XeXe544/macros/XeXeBetheBloch.C, PWGLF/SPECTRA/PiKaPr/TPC/XeXe544/task/AliAnalysisTaskTpcSpectra.cxx, PWGLF/SPECTRA/PiKaPr/TPC/XeXe544/task/AliAnalysisTaskTpcSpectra.h, PWGLF/SPECTRA/PiKaPr/TPC/XeXe544/task/CreateAlienHandler.C, PWGLF/SPECTRA/PiKaPr/TPC/XeXe544/task/runGrid.C
- Created new directory with all the macros and the task used for the measurement of the PiKaPr spectra in XeXe collisions at 5.44 TeV for the preliminary stage approved for QM2018
=> Added new files for the TPC PiKaPr analysis in XeXe

PWG/CaloTrackCorrBase/AliCaloTrackReader.cxx, PWG/CaloTrackCorrBase/AliCaloTrackReader.h
move the recovery of the SM number or the absIdMax to a single place in the same method
=> add possibility to scale the cluster energy with a global factor per SM

PWGGA/PHOSTasks/PHOS_Run2/AliAnalysisTaskPHOSPi0EtaToGammaGamma.cxx
add histograms for PID cut study
=> add histogram for PID cut study

PWGCF/FEMTOSCOPY/AliFemtoUser/AliFemtoModelCorrFctnTrueQ6D.cxx
=> PWGCF: AliFemtoModelCorrFctnTrueQ6D - Add 'safer' histogram layout mechanism

PWGGA/PHOSTasks/PHOS_Run2/AliAnalysisTaskPHOSPi0EtaToGammaGamma.cxx
change criterion to tagged photon for PID study
=> change criterion to tagged photon for PID study

PWGJE/EMCALJetTasks/UserTasks/AliAnalysisTaskV0sInJetsEmcal.cxx
Fixed number of bins in fh2QAV0NClRows.
Added loading AOD using AODEvent() in case InputEvent() fails.
=> Fixed binning, load AOD using AODEvent().

PWG/CaloTrackCorrBase/AliAnaCaloTrackCorrBaseClass.cxx, PWG/CaloTrackCorrBase/AliAnaCaloTrackCorrBaseClass.h, PWG/CaloTrackCorrBase/AliAnalysisTaskCaloTrackCorrelation.h, PWG/CaloTrackCorrBase/AliAnalysisTaskCaloTrackCorrelationM.h, PWG/CaloTrackCorrBase/AliCaloTrackReader.h, PWGGA/CaloTrackCorrelations/AliAnaEMCALTriggerClusters.h, PWGGA/CaloTrackCorrelations/AliAnaGeneratorKine.cxx, PWGGA/CaloTrackCorrelations/AliAnaGeneratorKine.h, PWGGA/CaloTrackCorrelations/AliAnaOmegaToPi0Gamma.h, PWGGA/CaloTrackCorrelations/AliAnaParticleIsolation.cxx, PWGGA/CaloTrackCorrelations/AliAnaParticleIsolation.h, PWGGA/CaloTrackCorrelations/AliAnaPhotonConvInCalo.h, PWGGA/CaloTrackCorrelations/AliAnaRandomTrigger.cxx, PWGGA/CaloTrackCorrelations/AliAnaRandomTrigger.h, PWGPP/EMCAL/AliAnalysisTaskEMCALClusterize.h
=> remove unneeded -TString &- in simple setters

PWGDQ/dielectron/core/AliAnalysisTaskElectronEfficiencyV2.cxx, PWGDQ/dielectron/core/AliAnalysisTaskElectronEfficiencyV2.h, PWGDQ/dielectron/macrosLMEE/AddTask_caklein_efficiency.C
Adds histogram to compare reconstructed pT spectra with generated+smeared spectra
=> PWGDQ: added histo with gen+smeared from rec tracks

PWGLF/RESONANCES/extra/AliXiStarpp13TeV.cxx
Add PID cuts and change mass bin from 2MeV/bin to 1MeV/bin
=> Change analysis setup(PID, Mass re-bin)

PWGJE/FlavourJetTasks/AliAnalysisTaskFlavourJetCorrelations.cxx, PWGJE/FlavourJetTasks/AliAnalysisTaskFlavourJetCorrelations.h
Invariant mass distributions for D0 reflections added.
=> Reflections for D0

PWGGA/PHOSTasks/PHOS_Run2/AliAnalysisTaskPHOSPi0EtaToGammaGamma.cxx, PWGGA/PHOSTasks/PHOS_Run2/macros/AddTaskPHOSPi0EtaToGammaGamma_PbPb_5TeV.C, PWGGA/PHOSTasks/PHOS_Run2/macros/AddTaskPHOSPi0EtaToGammaGamma_pp_5TeV.C, PWGGA/PHOSTasks/PHOS_Run2/macros/AddTaskPHOSPi0EtaToGammaGamma_pp_5TeV_LHC17pq.C
support AliVEvent::kMuonCalo for PHI7 in [CALO|CALOFAST].
=> support kMuonCalo

PWGCF/Correlations/JCORRAN/Pro/AliJCDijetHistos.cxx, PWGCF/Correlations/JCORRAN/Pro/AliJCDijetHistos.h, PWGCF/Correlations/JCORRAN/Pro/AliJCDijetTask.cxx, PWGCF/Correlations/JCORRAN/Pro/AliJCDijetTask.h
Made CalculateJetsDijets function so that it is easier to use as a stand
alone function. In addition, centrality and z-vertex histograms were
added.
=> Minor update to task, also new cent & zvtx histo.

PWGPP/TPC/macros/TPCQAWebpage/tpcCalibValidation.C
* AliTMinuitToolkit sometimes failing in ROOT6
* disable default fits for the moment
=> ATO-410- make fits as an option

PWGCF/Correlations/macros/dphicorrelations/correct.C, PWGCF/Correlations/macros/dphicorrelations/fit.C
The fitting and plotting macros are changed to represent the version used for the publication of the 2.76 TeV data and the preliminary status of the 5.02 TeV data.
=> Bringing the fitting and plotting macros up to date

PWGCF/FEMTOSCOPY/macros/Train/pPbKKfemto/exp/conf_run2/1/ConfigFemtoAnalysis.C, PWGCF/FEMTOSCOPY/macros/Train/pPbKKfemto/exp/conf_run2/2/ConfigFemtoAnalysis.C, PWGCF/FEMTOSCOPY/macros/Train/pPbKKfemto/exp/conf_run2/ConfigFemtoAnalysis.C
=> Elena:  files for train 30 June 2018

PWGHF/jetsHF/AliAnalysisTaskBJetTC.cxx, PWGHF/jetsHF/AliAnalysisTaskBJetTC.h, PWGHF/jetsHF/macros/AddTaskBJetTC.C
Change the range of -ln(JP) used for life time reference tagger
=> Changing the -ln(JP) range

PWGPP/TOF/AliAnalysisTaskTOFqaID.cxx, PWGPP/TOF/AliAnalysisTaskTOFqaID.h, PWGPP/TOF/trending/DrawTrendingTOFQA.C, PWGPP/TOF/trending/MakeTrendingTOFQAv2.C
Modified task, trending maker and trending drawer to fix minor issues such as the label of the T0AC in the resolution plot
- Other minor fixes
- Formatted document
- Some simplifications
- To test the consistency of the old and new QA chains the output of the trending obtained with the two versions were checked on run  276551 of LHC17l cpass1_pass1
=> TOF QA trending update

PWGCF/EBYE/Fluctuations/AliEbyEPidEfficiencyContamination.cxx
Total momentum cut used for C2 paper
=> total mom cut used

PWGHF/hfe/AliAnalysisTaskTPCCalBeauty.cxx, PWGHF/hfe/AliAnalysisTaskTPCCalBeauty.h, PWGHF/hfe/macros/AddTaskTPCCalBeauty.C
Reduced size of sparse, added booleans to do systematics. Added MC boolean to reduce output file size.
=> Changes to reduce output file size; booleans to help with systematics

PWGHF/vertexingHF/AliAnalysisTaskSEDStarCharmFraction.cxx, PWGHF/vertexingHF/AliAnalysisTaskSEDStarSpectra.cxx
Two issues found in Dstar code:
- Removal hardcoded fD0window selection in DstarSpectra task
- Removal of recalculation of primary vertex after deleting Dstar daughters in DstarCharmFraction task
=> Update Dstar code after d2h discussion

PWGPP/QA/detectorQAscripts/TOF.sh, PWGPP/TOF/trending/MakeTrendingTOFQAv2.C
- Fixed the MakeTrendingTOFQAv2 to avoid using histograms after closing the file on which they are based
- Formatted whole MakeTrendingTOFQAv2
- Updated TOFqa script to remove .so and .d files after the trending is done
=> Fix in TOF QA trending

PWGCF/FEMTOSCOPY/AliFemto/AliFemtoConfigObject.h
Add missing copy-constructors and variables in initialization lists, removing compiler warnings
=> PWGCF: AliFemtoConfigObject - Fix all warnings reported by gcc

PWGCF/EBYE/Fluctuations/AliEbyEPidEfficiencyContamination.cxx
=> minor code cleanup

PWGCF/FEMTOSCOPY/macros/Train/pPbKKfemto/MC/conf_2016/2/ConfigFemtoAnalysis.C
=> Elena: MR MTX config

PWGGA/EMCALTasks/AliAnalysisTaskGammaHadron.cxx, PWGGA/EMCALTasks/AliAnalysisTaskGammaHadron.h
Adds parametrized track matching cuts.
Fixes a line preventing track matching from occurring in Data.
=> Parametrized track matching cuts and important track matching fix

PWGJE/FlavourJetTasks/AliAnalysisTaskFlavourJetCorrelations.cxx
Distributions for momentum and z resolutions added + fix for a bug in the reflection part.
=> distributions for mom. and z resolution+fix for refl. bug

PWGGA/CaloTrackCorrelations/AliAnaParticleHadronCorrelation.cxx, PWGGA/CaloTrackCorrelations/AliAnaParticleHadronCorrelation.h, PWGGA/CaloTrackCorrelations/macros/AddTaskGammaHadronCorrelation.C, PWGGA/CaloTrackCorrelations/macros/ConfigureCaloTrackCorrAnalysis.C
reduce size; 
activate option in hadron correlation AddTasks
=> Fill TH3 or TH2 DeltaPhi DeltaEta histograms depending on switch

PWGHF/jetsHF/AliAnalysisTaskBJetTC.cxx, PWGHF/jetsHF/AliAnalysisTaskBJetTC.h
I added the new improved DCA cut, because I noticed that it wasn't used.
=> Updating the Improved DCA

PWGHF/correlationHF/AliAnalysisTaskSED0Correlations.cxx, PWGHF/correlationHF/macros/ExtractPurityPlots.C
New pT ranges + different treatment of non-pi/K/p/e/mu
=> Updated purity studies for D0-h correlation main task

OADB/EMCAL/READMEoadb.txt, PWGGA/GammaConv/AliAnalysisTaskGammaCalo.cxx, PWGGA/GammaConv/AliAnalysisTaskGammaCaloMerged.cxx, PWGGA/GammaConv/AliConvEventCuts.cxx, PWGGA/GammaConv/macros/AddTask_GammaCalo_pPb.C
The updates were provided by Joshua and Justin. Fot the time calibration, the corresponding JIRA ticket is [EMCAL-63].
=> OADB/EMCAL & PWGGA/GammaConv: Updated bad channel maps for 16p and time calib for 17o + JJ weight fix for mEMC

PWGGA/PHOSTasks/PHOS_Run2/AliAnalysisTaskPHOSPi0EtaToGammaGamma.cxx, PWGGA/PHOSTasks/PHOS_Run2/AliAnalysisTaskPHOSPi0EtaToGammaGamma.h, PWGGA/PHOSTasks/PHOS_Run2/AliPHOSClusterCuts.cxx, PWGGA/PHOSTasks/PHOS_Run2/AliPHOSClusterCuts.h, PWGGA/PHOSTasks/PHOS_Run2/macros/AddTaskPHOSEmbeddingEfficiency.C, PWGGA/PHOSTasks/PHOS_Run2/macros/AddTaskPHOSPi0EtaToGammaGamma_PbPb_5TeV.C, PWGGA/PHOSTasks/PHOS_Run2/macros/AddTaskPHOSPi0EtaToGammaGamma_pp_5TeV.C, PWGGA/PHOSTasks/PHOS_Run2/macros/AddTaskPHOSPi0EtaToGammaGamma_pp_5TeV_LHC17pq.C, PWGGA/PHOSTasks/PHOS_Run2/macros/AddTaskPHOSSingleSim.C
=> update tagged photon criteria

PWGGA/PHOSTasks/PHOS_Run2/AliAnalysisTaskPHOSEmbeddedDiffObjectCreator.cxx, PWGGA/PHOSTasks/PHOS_Run2/AliAnalysisTaskPHOSEmbeddingEfficiency.cxx, PWGGA/PHOSTasks/PHOS_Run2/AliAnalysisTaskPHOSSingleSim.cxx
update criteria to tagged photon in embedding
=> update tagged photon criteria in embedding

PWGJE/EMCALJetTasks/UserTasks/AliAnalysisTaskEmcalJetSpectra8TeVTriggerQA.cxx, PWGJE/EMCALJetTasks/UserTasks/AliAnalysisTaskEmcalJetSpectra8TeVTriggerQA.h
This is for debugging and might not conform to best c++ standards, my code is crashing on the lego train yet runs fine locally with Root5 and Root6.  The changes made in this PR will only be temporary
=> This is for debugging and might not conform to best c++ standards

PWGGA/PHOSTasks/PHOS_Run2/AliAnalysisTaskPHOSPi0EtaToGammaGamma.cxx, PWGGA/PHOSTasks/PHOS_Run2/AliPHOSClusterCuts.cxx
change order of PID cut and put histogram title
=> change order of PID cut

PWGJE/EMCALJetTasks/Tracks/AliAnalysisTaskEmcalJetConstituentQA.cxx, PWGJE/EMCALJetTasks/Tracks/AliAnalysisTaskEmcalJetConstituentQA.h
=> Move trigger selection to virtual custom IsTriggerSelected method

PWGHF/vertexingHF/AliHFSystErr.cxx
Update of the QM18 preliminary systematics for Dstar analysis in pp@5TeV, discussed in D2H 10/07
=> Update syst Dstar pp@5TeV

PWGLF/NUCLEX/Hypernuclei/Hyp2Body/AliAnalysisTaskHypTritEventTree.cxx
Adding selection fPeriod==2017 for pp analysis purposes.
=> Add period 2017 selection for pp

PWGHF/correlationHF/AliAnalysisTaskSED0Correlations.cxx
=> D-h correl: Updated pT(assoc) ranges for purity, in view of pp@5 TeV studies

PWGCF/FEMTOSCOPY/macros/Train/DEtaDPhi_GM/ConfigFemtoAnalysis.C
Testing a pull request to the AliFemto code
=> G. Moryc: adding config femto file for DEtaDPhi

TENDER/TenderSupplies/AliPHOSTenderSupply.cxx
added "Run2MC" parameterization
=> Non-linearity parameterization for Run2 implemented

PWGCF/Correlations/DPhi/AliAnalysisTaskGeneralBF.cxx, PWGCF/Correlations/macros/PIDBFDptDpt/AddTaskGeneralBF.C
Bug fixed for selecting PID particle #1 & #2
=> Bug fixed for selecting PID particle #1 & #2

PWGCF/Correlations/JCORRAN/Pro/AliJCDijetHistos.cxx, PWGCF/Correlations/JCORRAN/Pro/AliJCDijetHistos.h, PWGCF/Correlations/JCORRAN/Pro/AliJCDijetTask.cxx, PWGCF/Correlations/JCORRAN/Pro/AliJCDijetTask.h, PWGCF/Correlations/macros/jcorran/AddTaskJCDijetTask.C
Added macro arguments for testing different background subtraction
settings. Histograms for kt-jets and raw constituent cut jets also
added.
=> Added more macro arguments and a couple of histos.

PWGJE/EMCALJetTasks/UserTasks/AliAnalysisTaskJetCoreEmcal.cxx, PWGJE/EMCALJetTasks/UserTasks/AliAnalysisTaskJetCoreEmcal.h
=> added option of rejection factor when filling inclusive jets from tree

PWGHF/hfe/AliAnalysisTaskTPCCalBeauty.cxx
=> Typo in fvalueElectron array initialization.

PWG/FLOW/Tasks/AliAnalysisTaskCMEV0PID.cxx
change TProfile Binning of Int. 3-p correlators
=> change TProfile Binning of Int. 3-p correlators

PWGCF/Correlations/DPhi/AliAnalysisTaskSEpPbCorrelationsMCYS.cxx, PWGCF/Correlations/DPhi/AliAnalysisTaskSEpPbCorrelationsMCYS.h, PWGCF/Correlations/macros/pPbCorrelations/AddTaskpPbCorrelationsMCYS.C
MC analysis to measure secondary correction of FMD and ITS
=> MC analysis

PWGHF/correlationHF/AliDhCorrelationExtraction.cxx, PWGHF/correlationHF/AliDhCorrelationExtraction.h, PWGHF/correlationHF/macros/ExtractOutput_Dplus.C, PWGHF/correlationHF/macros/ExtractOutput_Dstar.C, PWGHF/correlationHF/macros/ExtractOutput_Dzero.C
=> Updated D-h correlation extraction code (integrate ME pools if very low stat)

PWGHF/hfe/AliAnalysisHFETPCTOFBeauty.cxx, PWGHF/hfe/AliAnalysisHFETPCTOFBeauty.h, PWGHF/hfe/macros/AddTaskHFETPCTOFBeauty.C
Cleaning task and adding smaller DCA bins to check fit instability
=> beauty at low pT - smaller DCA bins to test instability

PWGHF/hfe/AliAnalysisHFETPCTOFBeauty.cxx
=> beauty electrons at low pt - update small dca bins

PWGCF/FEMTOSCOPY/macros/Train/pPbKKfemto/MC/conf_2016/2/ConfigFemtoAnalysis.C
=> Train for Elena 23-07-2018

PWGDQ/dielectron/macrosLMEE/AddTask_acapon.C, PWGDQ/dielectron/macrosLMEE/Config_acapon.C, PWGDQ/dielectron/macrosLMEE/LMEECutLib_acapon.C
Cut choices can now be passed from AddTask to Config file.
=> V0 cuts added to LMEECutLib

PWGJE/EMCALJetTasks/UserTasks/AliAnalysisTaskEmcalJetShapesMC.cxx, PWGJE/EMCALJetTasks/UserTasks/AliAnalysisTaskEmcalJetShapesMC.h
Modified soft toy model using LorentzVectors and rotating to to jet axis.
=> updated soft toy model

PWGLF/SPECTRA/PiKaPr/TPC/rTPC/AliAnalysisTaskQAHighPtDeDxTest.cxx, PWGLF/SPECTRA/PiKaPr/TPC/rTPC/AliAnalysisTaskQAHighPtDeDxTest.h
1.- Contains the updated calibration parameters obtained from using all the HIR runs.
2.- PID histograms for the low pT are included
3.- The MC part is also included
=> QATask for 4TPC analysis

PWGHF/jetsHF/AliAnalysisTaskEmcalJetBtagSV.cxx, PWGHF/jetsHF/AliAnalysisTaskEmcalJetBtagSV.h
Implementation of IsOutlier function which removes from MC events where pTjet is much larger than pT hard
=> Implementation of IsOutlier function to remove pt hard outliers

PWGJE/FlavourJetTasks/AliAnalysisTaskFlavourJetCorrelations.cxx
Extend the range of the invariant mass histograms in THnSparse.
=> extended inv. mass range

PWGLF/SPECTRA/PiKaPr/TPC/rTPC/AliAnalysisTaskQAHighPtDeDxTest.cxx
Selection on rapidity for reconstructed MC fixed
=> Fix selection on rapidity for MC

PWGGA/PHOSTasks/PHOS_Run2/AliAnalysisTaskPHOSPi0EtaToGammaGamma.cxx, PWGGA/PHOSTasks/PHOS_Run2/AliAnalysisTaskPHOSPi0EtaToGammaGamma.h, PWGGA/PHOSTasks/PHOS_Run2/AliPHOSTriggerHelper.h
add possibility to set private TRU BCM for L1 study
=> add possibility to set TRU BCM

PWGHF/vertexingHF/AliAnalysisTaskSELc2V0bachelor.cxx
Modified analysis task, in order to reduce the size of the tree created.
=> Add AliAnalysisTaskSELc2V0bachelor.cxx

PWGJE/EMCALJetTasks/CMakeLists.txt, PWGJE/EMCALJetTasks/PWGJEEMCALJetTasksLinkDef.h, PWGJE/EMCALJetTasks/UserTasks/AliAnalysisTaskJetExtractor.cxx, PWGJE/EMCALJetTasks/UserTasks/AliAnalysisTaskJetExtractor.h
Implementation of jet extractor task and wrapper class for flat trees for jet properties.
=> Added jet extractor task based on flat trees

PWGGA/PHOSTasks/PHOS_Run2/AliAnalysisTaskPHOSPi0EtaToGammaGamma.cxx, PWGGA/PHOSTasks/PHOS_Run2/macros/AddTaskPHOSPi0EtaToGammaGamma_PbPb_5TeV.C
update L1 trigger efficiency and add histograms for converted electrons
=> update L1 trigger efficiency

PWG/FLOW/Tasks/AliAnalysisTaskCMEV0PID.cxx
Revert old binning of TProfiles
=> Revert old binning of TProfiles

PWGCF/FEMTOSCOPY/macros/Train/KchKchRun2_Aug2018/KK_13TeV_dist/AddTaskFemtoKchHBT1090.C, PWGCF/FEMTOSCOPY/macros/Train/KchKchRun2_Aug2018/KK_13TeV_dist/ConfigFemtoAnalysis.C, PWGCF/FEMTOSCOPY/macros/Train/KchKchRun2_Aug2018/pipi_13TeV_dist/AddTaskFemtoKchHBT1090.C, PWGCF/FEMTOSCOPY/macros/Train/KchKchRun2_Aug2018/pipi_13TeV_dist/ConfigFemtoAnalysis.C
=> Lego Train: Malinina 31 July 2018

PWGCF/Correlations/JCORRAN/Pro/AliJCDijetHistos.cxx, PWGCF/Correlations/JCORRAN/Pro/AliJCDijetHistos.h, PWGCF/Correlations/JCORRAN/Pro/AliJCDijetTask.cxx
New histogram saves information about the run so that the settings used
can be checked easily later. Also changed fh_events histogram to have
alphanumeric bin labels.
=> Added a new run info histogram.

PWGPP/TOF/trending/MakeTrendingTOFQAv2.C
=> Added safety for eventual missing QAfile

PWGJE/EMCALJetTasks/UserTasks/AliAnalysisTaskJetExtractor.cxx, PWGJE/EMCALJetTasks/macros/AddTaskJetExtractor.C
=> Write trees without directory in file

PWGPP/ITS/AliAlignmentDataFilterITS.cxx
Similar changes to these implemented by @davidrohr in AliRoot.
=> Fixes for Root 6.14.2

PWGCF/FEMTOSCOPY/macros/Train/DEtaDPhi/2018/Xi/MCtruth/ConfigFemtoAnalysis.C, PWGCF/FEMTOSCOPY/macros/Train/DEtaDPhi/2018/Xi/MCtruth/noMesons/ConfigFemtoAnalysis.C
AliFemto configs for LEGO trains. One with all particles and second without mesons.
=> Config for Xi analysis

PWGDQ/dielectron/macrosLMEE/AddTask_acapon.C, PWGDQ/dielectron/macrosLMEE/Config_acapon.C, PWGDQ/dielectron/macrosLMEE/LMEECutLib_acapon.C
Cut setting added for selection of pure sample of V0 particles via ITS and TPC
=> Added V0_TOF cut option

PWGDQ/dielectron/core/AliAnalysisTaskElectronEfficiencyV2.cxx
=> PWGDQ: fixed bug in application of pid recalibration

PWGJE/EMCALJetTasks/Tracks/AliAnalysisTaskEmcalJetSubstructureTree.cxx
As the clusters CENT and CENTNOTRD have a certain
overlap the indexing must reflect the overlap rather
than the absolute trigger name.
=> Restruction trigger cluster indexing

PWGCF/Correlations/DPhi/AliAnalysisTaskGeneralBF.cxx, PWGCF/Correlations/DPhi/AliAnalysisTaskGeneralBF.h, PWGCF/Correlations/macros/PIDBFDptDpt/AddTaskGeneralBF.C
make particle 1 & 2 choose pT separately
=> make particle 1 & 2 choose pT separately

PWGCF/Correlations/macros/PIDBFDptDpt/AddTaskGeneralBF.C
=> small bug fix

PWGJE/EMCALJetTasks/UserTasks/AliAnalysisTaskEmcalJetPerformance.cxx, PWGJE/EMCALJetTasks/UserTasks/AliAnalysisTaskEmcalJetPerformance.h
(update to my user task)
@mfasDa I would appreciate if you take a look
=> JetPerformance: Add option to plot a couple trigger response histos in MC

PWGHF/vertexingHF/macros/makeTFile4CutsLctoV0bachelor.C
Dear all,
this is just to update the macro to create the cut object for Lc2pK0S analysis.
Thanks and cheers
Annalisa
=> Macro to create Lc2pK0S cut object updated

PWGHF/vertexingHF/AliHFSystErr.cxx
Updated values for Dstar tracking systematic after implementation/fixes strategy for soft pion
=> Update Dstar tracking syst pp5TeV 2017

PWGGA/PHOSTasks/PHOS_Run2/AliAnalysisTaskPHOSPi0EtaToGammaGamma.cxx
change histogram binning for SP norm
=> change histogram binning for SP norm

PWGHF/vertexingHF/AliRDHFCuts.cxx, PWGHF/vertexingHF/AliRDHFCuts.h
1) swapped order of Zvtx and SPD-vertex-based cuts
2) set default of flag fCutOnzVertexSPD=3
3) added flag to apply |Zvtx|>X cm cut on SPD vertex
=> Implemented changes in Zvtx and SPD-vertex-based cuts in IsEventSelected

PWGGA/GammaConv/AliAnalysisTaskClusterQA.cxx, PWGGA/GammaConv/AliAnalysisTaskClusterQA.h, PWGGA/GammaConv/AliAnalysisTaskConversionQA.cxx, PWGGA/GammaConv/CMakeLists.txt, PWGGA/GammaConv/PWGGAGammaConvLinkDef.h, PWGGA/GammaConv/macros/AddTask_ClusterQA.C
This new task can write out a TTree with several cluster informations. This tree will be used for machine learning with the purpose of improving merged cluster analyses.
=>  PWGGA/GammaConv: Added new task for Cluster QA Tree 

PWGGA/Hyperon/AliAnalysisTaskSigma0Run2.cxx, PWGGA/Hyperon/AliSigma0PhotonMotherCuts.cxx, PWGGA/Hyperon/AliSigma0PhotonMotherCuts.h, PWGGA/Hyperon/AliSigma0V0Cuts.cxx, PWGGA/Hyperon/AliSigma0V0Cuts.h, PWGGA/Hyperon/macros/AddTaskSigma0Run2syst.C
o Further optimize memory footprint
o Multiplicity and z-vertex binning for the mixed events
o Work towards efficiency correction in HighMult events
o Test further selection criteria
o Minor bug fixes
=> PWGGA/Hyperon: Improvements for Run2 Sigma0 analysis

PWGCF/FEMTOSCOPY/macros/Train/AddMCGen/Add_MCGenPythia8_TuneX.C
Adding to AliFemto a config macro file to generate Pythia 8 events
=> AliFemto: adding Pythia 8 generation macro

PWGGA/GammaConv/AliAnalysisTaskClusterQA.cxx
Also removed unwanted inclusion of PHOS and CPV clusters.
=> PWGGA/GammaConv: Fix for ClusterQA task tree (now fixed entry size)

PWGCF/FEMTOSCOPY/macros/Train/DEtaDPhi/2018/Xi/nocorr/11bins/MunichCuts/WithoutMinvCuts/ConfigFemtoAnalysis.C
Add new folder without invariant mass cut and add in Config fail hisogram
=> New Histogram plus new Config

PWGGA/PHOSTasks/PHOS_Run2/AliAnalysisTaskPHOSPi0EtaToGammaGamma.cxx
add sin(n(delta Psi)) histogram for EP
=> add sin histogram for EP

PWGJE/EMCALJetTasks/UserTasks/AliAnalysisTaskEmcalJetPerformance.cxx, PWGJE/EMCALJetTasks/UserTasks/AliAnalysisTaskEmcalJetPerformance.h
=> JetPerformance: Allow to fill EMCal response when trigger patches are missing, and update jet matching

PWGJE/EMCALJetTasks/UserTasks/AliAnalysisTaskChargedJetsHadronToy.cxx, PWGJE/EMCALJetTasks/UserTasks/AliAnalysisTaskChargedJetsHadronToy.h
This allows to embed tracks from flat trees stored on alien.
=> Option to use toy events from flat trees

PWGHF/jetsHF/AliAnalysisTaskBJetTC.cxx, PWGHF/jetsHF/AliAnalysisTaskBJetTC.h
I updated the DeltaPt response, and I also made few changes 😐.
=> I made few changes on my code.

PWGJE/EMCALJetTasks/UserTasks/AliAnalysisTaskChargedJetsHadronToy.cxx
Small bugfix to open correct event in file
=> Reset ME file counter in toy task

PWGJE/EMCALJetTasks/UserTasks/AliAnalysisTaskChargedJetsHadronToy.cxx
AliAODMCParticles cannot simply be copied, they need to be wrapped to AliAODtracks.
=> Allow running on AOD MC particles

PWGDQ/reducedTree/AliAnalysisTaskReducedTreeMaker.cxx, PWGDQ/reducedTree/AliReducedAnalysisFilterTrees.cxx, PWGDQ/reducedTree/AliReducedAnalysisFilterTrees.h, PWGDQ/reducedTree/AliReducedPairInfo.cxx, PWGDQ/reducedTree/AliReducedPairInfo.h, PWGDQ/reducedTree/AliReducedVarManager.cxx, PWGDQ/reducedTree/AliReducedVarManager.h
Updates:
– AliDielectronVarManager: kPairTypeSPD and kPseudoProperDecayTimeMC variables added 
– AliReducedAnalysisFilterTrees: MC running enabled (main methods taken from AliReducedAnalysisJpsi2ee.cxx)
– AliReducedPairInfo: data members for PseudoProperDL and PairTypeSPD added
– AliAnalysisTaskReducedTreeMaker: MCFreezeout[] variables updated for MC-truth tracks
=> small updates

PWGJE/EMCALJetTasks/UserTasks/AliAnalysisTaskJetExtractor.cxx, PWGJE/EMCALJetTasks/UserTasks/AliAnalysisTaskJetExtractor.h
Extract jet type from AliEmcalPythiaInfo object for MC data
=> Extract parton type from AliEmcalPythiaInfo object

PWGDQ/dielectron/LMEE/AliAnalysisTaskSimpleTreeMaker.cxx, PWGDQ/dielectron/LMEE/AliAnalysisTaskSimpleTreeMaker.h
Firstmother (initial particle in decay chain) pdg and label information added to MC TTrees.
=> TreeMaker: firstMother information added to MCtree

PWGHF/jetsHF/AliAnalysisTaskBJetTC.cxx, PWGHF/jetsHF/AliAnalysisTaskBJetTC.h
I improved the outlier rejection by rejecting reconstructed track with a certain Pt
=> Improving the outlier rejection

PWGGA/GammaConv/AliAnalysisTaskClusterQA.cxx, PWGGA/GammaConv/AliAnalysisTaskClusterQA.h, PWGGA/GammaConv/macros/AddTask_ClusterQA.C
The cluster Tree is now being saved outside of the TList to avoid a strange compression issue.
=> PWGGA/GammaConv: Modified the ClusterQA task and moved tree in file

PWGJE/EMCALJetTasks/UserTasks/AliAnalysisTaskEmcalJetPerformance.cxx, PWGJE/EMCALJetTasks/UserTasks/AliAnalysisTaskEmcalJetPerformance.h
(Update to my user task)
FYI: @efranzis
=> JetPerformance: Implement both geometrical and MC-fraction based jet matching

PWGHF/vertexingHF/charmFlow/AddTaskHFv1.C
=> Added possibility to load TF1 for efficiency reweighting from external file

PWGCF/FEMTOSCOPY/AliFemtoUser/AliFemtoCorrFctnInvMass.cxx, PWGCF/FEMTOSCOPY/AliFemtoUser/AliFemtoCorrFctnInvMass.h, PWGCF/FEMTOSCOPY/AliFemtoUser/CMakeLists.txt, PWGCF/FEMTOSCOPY/AliFemtoUser/PWGCFfemtoscopyUserLinkDef.h
invariant mass distribution for baryonia searches
=> AliFemto: adding invariant mass distribution

PWGCF/FEMTOSCOPY/macros/Train/ProtonLambdaFemto/ProtonLambda/FB768/ConfigAvgsepAnalysis.C, PWGCF/FEMTOSCOPY/macros/Train/ProtonLambdaFemto/ProtonLambda/FB96/ConfigAvgsepAnalysis.C
adding config files for baryon-antibaryon femto analysis on global and hybrid tracks
=> AliFemto: adding config files for global and hybrid tracks

PWGCF/FEMTOSCOPY/macros/Train/ProtonLambdaFemto/ProtonLambda/FB128/ConfigAvgsepAnalysis.C
new config file for TPC only tracks
=> AliFemto: adding config file for TPC only tracks

PWGHF/vertexingHF/AliAnalysisTaskSEB0toDStarPi.cxx, PWGHF/vertexingHF/AliAnalysisTaskSEB0toDStarPi.h, PWGHF/vertexingHF/macros/AddTaskB0toDStarPi.C
Added rotation background code for B0 to DStar pi
=> Added rotation background code

PWGCF/FEMTOSCOPY/macros/Train/ProtonLambdaFemto/ProtonLambda/Xi/FB96/ConfigAvgsepAnalysis.C
=> AliFemto: adding Xi analysis

PWGCF/FEMTOSCOPY/macros/Train/ProtonLambdaFemto/ProtonLambda/Xi/FB128/ConfigAvgsepAnalysis.C, PWGCF/FEMTOSCOPY/macros/Train/ProtonLambdaFemto/ProtonLambda/Xi/FB768/ConfigAvgsepAnalysis.C, PWGCF/FEMTOSCOPY/macros/Train/ProtonLambdaFemto/ProtonLambda/Xi/FB96/ConfigAvgsepAnalysis.C
=> AliFemto: changes to Xis config file for baryon femto

PWGPP/EMCAL/TeCMacros/LInfo.cxx, PWGPP/EMCAL/TeCMacros/LInfo.h, PWGPP/EMCAL/TeCMacros/TInfo.cxx, PWGPP/EMCAL/TeCMacros/TInfo.h, PWGPP/EMCAL/TeCMacros/createTree.C, PWGPP/EMCAL/TeCMacros/plotOCDB_LED.C, PWGPP/EMCAL/TeCMacros/plotOCDB_Temperature.C, PWGPP/EMCAL/TeCMacros/readOCDB_LED.C, PWGPP/EMCAL/TeCMacros/readOCDB_Temperature.C
Most important changes
a) Led and LedMon tree now properly read
b) Online-offline index conversion in create tree
=> Numerous fixes for Temp and Led readout and processing

PWGJE/EMCALJetTasks/UserTasks/AliAnalysisTaskEmcalJetPerformance.cxx, PWGJE/EMCALJetTasks/UserTasks/AliAnalysisTaskEmcalJetPerformance.h
=> JetPerformance: adapt task for thermal model closure test

PWGHF/jetsHF/AliAnalysisTaskBJetTC.cxx, PWGHF/jetsHF/AliAnalysisTaskBJetTC.h
I made changes on the code in order to consume less memory.
=> Optimizations for the code to consume much less memory

PWGJE/EMCALJetTasks/UserTasks/AliAnalysisTaskEmcalJetPerformance.cxx, PWGJE/EMCALJetTasks/UserTasks/AliAnalysisTaskEmcalJetPerformance.h
=> JetPerformance: allow user to set whether to apply truth-jet container criteria

PWGCF/FEMTOSCOPY/macros/Train/pPbKKfemto/MC/conf_2016/1/ConfigFemtoAnalysis.C, PWGCF/FEMTOSCOPY/macros/Train/pPbKKfemto/MC/conf_2016/2/ConfigFemtoAnalysis.C
=> Configures for Elena pPbKKfemto/MC/conf_2016

PWGCF/FEMTOSCOPY/macros/Train/KchKchRun2_Aug2018_3/KK_13TeV_dist/AddTaskFemtoKchHBT1090.C, PWGCF/FEMTOSCOPY/macros/Train/KchKchRun2_Aug2018_3/KK_13TeV_dist/ConfigFemtoAnalysis.C, PWGCF/FEMTOSCOPY/macros/Train/KchKchRun2_Aug2018_3/pipi_13TeV_dist/AddTaskFemtoKchHBT1090.C, PWGCF/FEMTOSCOPY/macros/Train/KchKchRun2_Aug2018_3/pipi_13TeV_dist/ConfigFemtoAnalysis.C
=> Train files for Ludmila KchKchRun2_Aug2018_3

PWGCF/FEMTOSCOPY/FemtoDream/AliAnalysisTaskSigma0Femto.cxx, PWGCF/FEMTOSCOPY/FemtoDream/AliAnalysisTaskSigma0Femto.h, PWGCF/FEMTOSCOPY/macros/AddTaskSigma0Femto.C
o Adding systematic cut variations
- Disable rotated sample
- Clean up options of the femto config
=> Fix folder problem with multiple wagons & syst. cut vars.

PWGCF/EBYE/NetLambda/AliAnalysisTaskNetLambdaIdent.cxx, PWGCF/EBYE/NetLambda/AliAnalysisTaskNetLambdaIdent.h, PWGCF/EBYE/PWGCFebyeLinkDef.h
-- add AliLightV0track class, V0 and daughter selection functions
-- remove variables from trees, K0S tree option
=> implement event mixing

PWGGA/PHOSTasks/PHOS_Run2/AliAnalysisTaskPHOSPi0EtaToGammaGamma.cxx, PWGGA/PHOSTasks/PHOS_Run2/macros/AddTaskPHOSEmbeddingEfficiency.C
fix task name of embedding with EP
=> fix task name of embedding with EP

PWGHF/jetsHF/AliAnalysisTaskBJetTC.cxx
I fixed a problem with filling the DeltaPt response.
=> fixing a problem with the DeltaPt response

PWGJE/EMCALJetTasks/UserTasks/AliAnalysisTaskEmcalJetPerformance.cxx
and allow geom matching to use accepted jets.
(update to my user task)
=> JetPerformance: require mc matching to impose deltaR cut on truth jet

PWGHF/hfe/AliAnalysisHFETPCTOFBeauty.cxx
There are two new commits (update beauty analysis August and update beauty analysis August2), but just one of them (any of the two) are necessary. Sorry for the confusion.
=> Update on beauty analysis

OADB/COMMON/MULTIPLICITY/macros/calibration/DetermineAnchorsPP.C
Modification in the code to allow to run the macro on merged output files instead of a list of per-run files.
=> Fixing bug in determination of AP + change in the code to read merged files

PWG/EMCAL/EMCALtasks/AliEmcalCorrectionClusterizer.cxx
This commit allows usage of EMCal clusterizer v3 when using the EMCal correction task.
=> Added option to use clusterizer v3 in EMCal correction task

PWGCF/Correlations/DPhi/AliAnalysisTaskCorPIDTOFQA.cxx, PWGCF/Correlations/DPhi/AliAnalysisTaskCorPIDTOFQA.h
also, removed sideband study histos
=> event multiplicity studies added to event mixing code

PWGGA/PHOSTasks/PHOS_Run2/AliAnalysisTaskPHOSPi0EtaToGammaGamma.cxx
=> fix purity histograms by MC label

PWGGA/PHOSTasks/PHOS_Run2/AliAnalysisTaskPHOSEmbedding.cxx, PWGGA/PHOSTasks/PHOS_Run2/AliAnalysisTaskPHOSEmbedding.h
=> clean up warning messages

PWGPP/TOF/AliAnalysisTaskTOFqaID.cxx, PWGPP/TOF/AliAnalysisTaskTOFqaID.h
- Updated bin labelling for T0 mask plot, minor modification (first commit)
- Formatted task with clang-format (second commit)
=> Updated bin label for TOF QA

PWGGA/PHOSTasks/PHOS_Run2/AliAnalysisTaskPHOSPi0EtaToGammaGamma.cxx
update histograms for purity estimation in MC
=> update purity estimation

PWGHF/jetsHF/AliAnalysisTaskBJetTC.cxx
I fixed a problem with pointers.
=> Fixing a problem with pointers

PWGCF/EBYE/Fluctuations/AliEbyEPidEfficiencyContamination.cxx, PWGCF/EBYE/Fluctuations/AliEbyEPidEfficiencyContamination.h, PWGCF/EBYE/macros/AddAliEbyEPidEfficiencyContamination.C
Major task modification is done to support p and pT options. Differential pt and eta analysis can be done in one go.
=> Major task modification: support for pt and eta bin-wise analysis.

PWGCF/FEMTOSCOPY/AliFemto/AliFemtoEventReaderAOD.cxx
adding a second condition to if to avoid floating point exception
=> AliFemto: bug fix in AOD reader

PWG/MCLEGO/AMPT/gen_ampt.sh
bump AMPT to latest version that's available through AliGenerators
=>  bump AMPT version to latest

PWGHF/hfe/AliAnalysisHFETPCTOFBeauty.cxx
=> beauty in PbPb- testing smaller dca bin size

PWGJE/FlavourJetTasks/AliAnalysisTaskSEDmesonsFilterCJ.cxx
Fix for a bug in the evaluation of the sys. unc. for the JES, track rejection was in a wrong place.
=>  fix of a bug in the JES syst. evaluation

PWGCF/FEMTOSCOPY/FemtoDream/AliFemtoDreamBasePart.cxx, PWGCF/FEMTOSCOPY/macros/AddTaskSigma0Femto.C, PWGGA/Hyperon/AliSigma0ParticleBase.cxx, PWGGA/Hyperon/AliSigma0ParticleBase.h, PWGGA/Hyperon/AliSigma0ParticlePhotonMother.cxx, PWGGA/Hyperon/AliSigma0ParticlePhotonMother.h, PWGGA/Hyperon/AliSigma0PhotonMotherCuts.cxx, PWGGA/Hyperon/AliSigma0PhotonMotherCuts.h, PWGGA/Hyperon/AliSigma0V0Cuts.cxx
o Cut variations have converged
o Pass more information to the BaseParticle
o Systematic study of the correlation in the sidebands
=> Improvements for Sigma0-p femtoscopy

PWGGA/EMCALTasks/AliAnalysisTaskGammaHadron.cxx
remove a print statement that prints every event
=> remove a print statement that prints every event

PWGCF/FEMTOSCOPY/AliFemto/AliFemtoTrioDEtaDPhiFctn.cxx, PWGCF/FEMTOSCOPY/AliFemto/AliFemtoTrioDEtaDPhiFctn.h, PWGCF/FEMTOSCOPY/AliFemto/CMakeLists.txt, PWGCF/FEMTOSCOPY/AliFemto/PWGCFfemtoscopyLinkDef.h
adding possibility to run 3-particle correlations
=> AliFemto: adding 3-particle DEtaDPhi correlations

PWGGA/PHOSTasks/PHOS_Run2/AliAnalysisTaskPHOSEmbeddingEfficiency.cxx
=> quick fix to restore array

PWGLF/NUCLEX/Nuclei/NucleiKine/AddMCGenLightNuclei.C, PWGLF/NUCLEX/Nuclei/NucleiKine/AddTaskNucleiKineCor.C, PWGLF/NUCLEX/Nuclei/NucleiKine/AliAnalysisTaskNucleiKineCor.cxx, PWGLF/NUCLEX/Nuclei/NucleiKine/AliAnalysisTaskNucleiKineCor.h
this allows to run with several settings of coalescence parameters
=> make it possible to run the generate inside the task 

PWGLF/NUCLEX/Nuclei/NucleiKine/AliAnalysisTaskNucleiKineCor.cxx, PWGLF/STRANGENESS/Lifetimes/AliAnalysisTaskStrangenessLifetimes.cxx
Fixing compilation issue introduced in #6581
=> Fix K0s MC tree filling and ROOT6 compilation

PWGCF/FEMTOSCOPY/AliFemto/AliFemtoTrioAnalysis.cxx, PWGCF/FEMTOSCOPY/AliFemto/AliFemtoTrioAnalysis.h
bug  fix in particle collection filling
=> AliFemto: bug fix in 3-part analysis

PWGPP/TPC/AliTPCPerformanceSummary.cxx
* Keep only one online QA histogram
* Add separate dead channel map contributions from
- high voltage
- DDL list
- Altro channel map
- space-charge distortions
=> Extend active channel map plot

PWGCF/Correlations/JCORRAN/Pro/AliJCDijetTask.cxx, PWGCF/Correlations/JCORRAN/Pro/AliJCDijetTask.h, PWGCF/Correlations/macros/jcorran/AddTaskJCDijetTask.C
This way the DeltaPhi cut will be taken into account when choosing what
kt-jets will be used in the rho estimation. In addition  I did some
minor bug fixes.
=> Added another way to choose kt-jets for background

PWGCF/FEMTOSCOPY/AliFemto/AliFemtoTrioAnalysis.cxx, PWGCF/FEMTOSCOPY/AliFemto/AliFemtoTrioAnalysis.h, PWGCF/FEMTOSCOPY/AliFemto/AliFemtoTrioDEtaDPhiFctn.cxx
some bug fixes in buffers for correlating 3 particles
=> AliFemto: bug fixes in 3-particle correlations

PWGCF/FEMTOSCOPY/macros/Train/DEtaDPhi/2018/TrioAnalysis/PI_P_FB96/ConfigFemtoAnalysis.C
previously wrong version committed
=> AliFemto: correct version of config file for 3-particle DEtaDPhi analysis (pions, protons)

PWGLF/SPECTRA/CMakeLists.txt, PWGLF/SPECTRA/PWGLFspectraLinkDef.h, PWGLF/SPECTRA/Spherocity/AliSpherocityUtils.cxx, PWGLF/SPECTRA/Spherocity/AliSpherocityUtils.h
I have implemented a class which calculate spherocity using a set of optimized track-cuts.
=> New class to calculate spherocity

PWGCF/FEMTOSCOPY/macros/Train/DEtaDPhi/2018/TrioAnalysis/PI_K_P_FB96/ConfigFemtoAnalysis.C
adding kaons to previous config
=> AliFemto: adding kaons to 3-particle analysis

PWGGA/EMCALTasks/AliAnalysisTaskGammaHadron.cxx
Changes number of dphi bins for correlations.
dphi=0 bin now centered at 0 :)
=> Changes number of dphi bins

PWGCF/FEMTOSCOPY/macros/Train/DEtaDPhi/2018/TrioAnalysis/PI_K_P_FB96/ConfigFemtoAnalysis.C
adding kaon-pion-pion analysis and requirements for collection size
=> AliFemto: replacing 3-particle correlation config file

PWGGA/PHOSTasks/PHOS_Run2/AliAnalysisTaskPHOSEmbedding.cxx, PWGGA/PHOSTasks/PHOS_Run2/AliAnalysisTaskPHOSEmbedding.h, PWGGA/PHOSTasks/PHOS_Run2/macros/AddTaskPHOSEmbedding.C
=> improve speed of embedding

PWGCF/FEMTOSCOPY/AliFemto/AliFemtoSimpleAnalysis.cxx, PWGCF/FEMTOSCOPY/AliFemto/AliFemtoTrioAnalysis.cxx, PWGCF/FEMTOSCOPY/AliFemto/AliFemtoTrioAnalysis.h, PWGCF/FEMTOSCOPY/AliFemto/AliFemtoTrioCut.cxx
adding swaping of particles in the trio analysis
=> AliFemto: swaping particles for 3-particle analysis

PWGCF/FEMTOSCOPY/AliFemtoUser/AliFemtoModelCorrFctnKpKp.cxx
=> Elena: Update AliFemtoModelCorrFctnKpKp class

PWGJE/FlavourJetTasks/AliAnalysisTaskSEDmesonsFilterCJ.cxx, PWGJE/FlavourJetTasks/AliAnalysisTaskSEDmesonsFilterCJ.h, PWGJE/FlavourJetTasks/macros/AddTaskSEDmesonsFilterCJ.C
=> AliNormalizationCounter added

PWG/EMCAL/EMCALtasks/AliEmcalCorrectionCellEnergy.cxx, TENDER/TenderSupplies/AliEMCALTenderSupply.cxx
Small fix:
The inversion of the correction factor was missing for the Run2 correction.
=> [EMCAL-191] TENDER+PWG/EMCAL: Correction of temperature calibration factor Run2

PWGHF/hfe/AliAnalysisTaskTPCCalBeauty.cxx, PWGHF/hfe/AliAnalysisTaskTPCCalBeauty.h, PWGHF/hfe/macros/AddTaskTPCCalBeauty.C
Also added ability to specify cluster matching distance in the addtask call.
=> Added template sparses for varied D meson weight (for systematics).

PWGDQ/dielectron/core/AliDielectronTMVACuts.cxx, PWGDQ/dielectron/core/AliDielectronTMVACuts.h, PWGDQ/dielectron/macrosLMEE/Config_miweber_LMEE_TMVA.C
- initialization: separate path and file name string
- copy from alien location to local folder: do in initialization not in config (otherwise not copied to worker node)
=> Fix TMVA weight file handling

PWGLF/RESONANCES/extra/AddTaskXiStarpp13TeV.C, PWGLF/RESONANCES/extra/AliXiStarpp13TeV.cxx, PWGLF/RESONANCES/extra/AliXiStarpp13TeV.h
Add PID option for each daughter particles
Add HM Trigger option for pp HM event
Add Non-Systematic option for memory issue
=> Add PID/HM Trigger/Non-Systematic option to AddTask macro

PWGCF/FEMTOSCOPY/macros/Train/DEtaDPhi/2018/NonIdDEtaDPhi/ConfigFemtoAnalysis.C
new config file to perform non-identical particle analysis od DEtaDPhi correlations
=> AliFemto: adding non-identical particles DEtaDPhi config file

PWGUD/DIFFRACTIVE/CEPdevel/AliAnalysisTaskCEP.cxx, PWGUD/DIFFRACTIVE/CEPdevel/AliAnalysisTaskCEP.h, PWGUD/DIFFRACTIVE/CEPdevel/AliCEPUtils.cxx, PWGUD/DIFFRACTIVE/CEPdevel/AliCEPUtils.h, PWGUD/DIFFRACTIVE/CEPdevel/CEPEventBuffer.cxx, PWGUD/DIFFRACTIVE/CEPdevel/CEPEventBuffer.h, PWGUD/DIFFRACTIVE/CEPdevel/RawBuffers/CEPRawCaloClusterTrack.cxx
included test for gamma detection in EMCal - AliCEPUtils::CaloClusterTrackdmax
=> included test for gamma detection in EMCal

PWGHF/jetsHF/AliAnalysisTaskBJetTC.cxx, PWGHF/jetsHF/AliAnalysisTaskBJetTC.h
Changing the default tagger working point, and also allows to change it from the outside.
=> Changing the default tagger working point

PWGGA/PHOSTasks/PHOS_Run2/AliAnalysisTaskPHOSEmbedding.cxx, PWGGA/PHOSTasks/PHOS_Run2/AliAnalysisTaskPHOSEmbedding.h, PWGGA/PHOSTasks/PHOS_Run2/AliAnalysisTaskPHOSEmbeddingEfficiency.cxx, PWGGA/PHOSTasks/PHOS_Run2/AliAnalysisTaskPHOSEmbeddingEfficiency.h, PWGGA/PHOSTasks/PHOS_Run2/AliAnalysisTaskPHOSPi0EtaToGammaGamma.cxx, PWGGA/PHOSTasks/PHOS_Run2/AliAnalysisTaskPHOSPi0EtaToGammaGamma.h, PWGGA/PHOSTasks/PHOS_Run2/AliAnalysisTaskPHOSSingleSim.cxx, PWGGA/PHOSTasks/PHOS_Run2/AliAnalysisTaskPHOSSingleSim.h
update single sim and embedding task
=> update single sim and embedding

PWGDQ/dielectron/macrosLMEE/AddTask_acapon_LMEE_TMVA.C, PWGDQ/dielectron/macrosLMEE/Config_acapon_LMEE_TMVA.C
Files coped from miweber for initial testing on the GRID.
=> acapon: Added AddTask and config for LMEE_MVA task

PWGGA/PHOSTasks/PHOS_Run2/AliAnalysisTaskPHOSPi0EtaToGammaGamma.cxx, PWGGA/PHOSTasks/PHOS_Run2/AliAnalysisTaskPHOSPi0EtaToGammaGamma.h
=> reduce warning message

PWGCF/FEMTOSCOPY/macros/Train/KchKchRun2_Sep2018/KK_13TeV_dist/AddTaskFemtoKchHBT1090.C, PWGCF/FEMTOSCOPY/macros/Train/KchKchRun2_Sep2018/KK_13TeV_dist/ConfigFemtoAnalysis.C, PWGCF/FEMTOSCOPY/macros/Train/KchKchRun2_Sep2018/KpKm_13TeV/AddTaskFemtoKchHBT1090.C, PWGCF/FEMTOSCOPY/macros/Train/KchKchRun2_Sep2018/KpKm_13TeV/ConfigFemtoAnalysis.C
=> Ludmila: new configurations for L-Train Sep 5, 2018

PWGGA/Hyperon/AliSigma0PhotonMotherCuts.h
o Further debugging why this fails sometimes
=> Revert mc truth tree

PWGLF/NUCLEX/Nuclei/Absorption/AddTaskDeuteronAbsorption.C, PWGLF/NUCLEX/Nuclei/Absorption/AliAnalysisTaskDeuteronAbsorption.cxx, PWGLF/NUCLEX/Nuclei/Absorption/AliAnalysisTaskDeuteronAbsorption.h
Now the task should be ready to run on trains with tunable cuts for the
systematics checks. Unused header files have been removed and some
little code optimisations were done.
=> Fix TOF mass binning + add tunable cuts

PWGGA/PHOSTasks/PHOS_Run2/AliAnalysisTaskPHOSEmbedding.cxx, PWGGA/PHOSTasks/PHOS_Run2/AliAnalysisTaskPHOSPi0EtaToGammaGamma.h
=> fix histogram binning

PWGHF/hfe/AliAnalysisTaskTPCCalBeauty.cxx, PWGHF/hfe/AliAnalysisTaskTPCCalBeauty.h
Also moved where the centrality histogram is filled.
=> Add B meson spectra for other experiment's rapidity ranges. 

PWGCF/Correlations/JCORRAN/Base/iaaAnalysis/AliJIaaAna.cxx
Adding condition for ESD MC Kine analysis
=> Commit for ESD MC KINE Analysis

PWGLF/RESONANCES/extra/AliXiStarpp13TeV.cxx, PWGLF/RESONANCES/extra/AliXiStarpp13TeV.h
increase ClassDef version from 1 to 2;
remove unused variables(MCxiY,MCxiYout, MCxiStarYout)
=> increase ClassDef version, remove unused variables

PWGGA/PHOSTasks/PHOS_Run2/AliAnalysisTaskPHOSEmbedding.cxx, PWGGA/PHOSTasks/PHOS_Run2/AliAnalysisTaskPHOSEmbedding.h
add basic histograms for embedding
=> add basic histograms for embedding

PWGGA/PHOSTasks/PHOS_Run2/AliAnalysisTaskPHOSEmbedding.cxx, PWGGA/PHOSTasks/PHOS_Run2/AliAnalysisTaskPHOSEmbedding.h
extend upper limit of Ncluster and add one more basic histogram in embedding
=> extend uppper limit of Ncluster

PWGCF/FEMTOSCOPY/macros/Train/KpmHBT21/0010/AddTaskFemtoKchHBT0010.C, PWGCF/FEMTOSCOPY/macros/Train/KpmHBT21/0010/ConfigFemtoAnalysis.C, PWGCF/FEMTOSCOPY/macros/Train/KpmHBT21/1090/AddTaskFemtoKchHBT1090.C, PWGCF/FEMTOSCOPY/macros/Train/KpmHBT21/1090/ConfigFemtoAnalysis.C
=> LEGO Train configuration file KpmHBT21 (Purity) 10 Sep 2018

PWGLF/RESONANCES/extra/AddTaskXiStarpp13TeV.C
Just removed one spacing between function and "{"
=> Remove spacing after function name

PWGDQ/dielectron/macrosLMEE/AddTask_acapon_Efficiency.C, PWGDQ/dielectron/macrosLMEE/Config_acapon.C, PWGDQ/dielectron/macrosLMEE/Config_acapon_Efficiency.C, PWGDQ/dielectron/macrosLMEE/LMEECutLib_acapon.C
Single cut setting using TMVA (BDT's) implemented in Config and Config_Efficiency.
=> acapon_LMEE: implemented a TMVA cut setting

PWGPP/macros/DrawTrendingPIDQA.C
- Changes affect only PID for TOF only plots
- Added missing return if function is completed successfully
- Improved labelling and range in TOF plots
- For TOF plot showing if the data point is higher or lower than the plotting range
- Added new function for single detector customization
=> Updated DrawTrendingPIDQA.C for TOF plots

PWGGA/GammaConv/macros/AddTask_GammaConvNeutralMesonPiPlPiMiNeutralMeson_CaloMode_pPb.C, PWGGA/GammaConv/macros/AddTask_GammaConvNeutralMesonPiPlPiMiNeutralMeson_ConvMode_pPb.C, PWGGA/GammaConv/macros/AddTask_GammaConvNeutralMesonPiPlPiMiNeutralMeson_MixedMode_pPb.C
Set `isHeavyIon` and `cutnumberEvent` so that it can handle p-Pb
=> PWGGA/GammaConv: changed isHeavyIon and cutnumberEvent for pPb

PWGPP/macros/DrawTrendingPIDQA.C
- Fixed interpreter getting stuck on nullptr
=> Fixed nullptr assignment in DrawTrendingPIDQA

PWGCF/FEMTOSCOPY/macros/Train/KpmHBT21/0010/ConfigFemtoAnalysis.C, PWGCF/FEMTOSCOPY/macros/Train/KpmHBT21/1090/ConfigFemtoAnalysis.C
=> Lego train for purity apdate

PWGCF/FEMTOSCOPY/FemtoDream/AliAnalysisTaskGrandma.cxx, PWGCF/FEMTOSCOPY/FemtoDream/AliAnalysisTaskGrandma.h, PWGCF/FEMTOSCOPY/FemtoDream/AliFemtoDreamTrackCuts.h, PWGCF/FEMTOSCOPY/macros/AddTaskFemtoGranma.C
of proton and antiproton selection for the baryon anti baryon task
=> track cuts change to return nullptr in case there is no mc histogram and impelmentation  

PWG/EMCAL/EMCALtasks/AliEmcalCorrectionCellEnergy.cxx, TENDER/TenderSupplies/AliEMCALTenderSupply.cxx
The existing calibration factor is now being loaded and the temperature calibration factor is being multiplied to it.
=> PWG/EMCAL + TENDER: Fix for temperature calibration factor EMCal in CF and Tender

PWGGA/PHOSTasks/PHOS_Run2/AliAnalysisTaskPHOSEmbeddingEfficiency.cxx, PWGGA/PHOSTasks/PHOS_Run2/AliAnalysisTaskPHOSEmbeddingEfficiency.h, PWGGA/PHOSTasks/PHOS_Run2/AliAnalysisTaskPHOSSingleSim.cxx, PWGGA/PHOSTasks/PHOS_Run2/AliAnalysisTaskPHOSSingleSim.h, PWGGA/PHOSTasks/PHOS_Run2/macros/AddTaskPHOSSingleSim.C
update single and embedding MC for gamma
=> update single and embedding MC for gamma

PWGLF/RESONANCES/extra/AddTaskXiStarpp13TeV.C
changed the output container name with HM trigger mode
=> Change the output container name with input

OADB/AliEventCuts.cxx, OADB/AliEventCuts.h, PWGLF/NUCLEX/Exotica/Ps/AliAnalysisTaskPsEfficiency.cxx, PWGLF/NUCLEX/Exotica/dStar/AliAnalysisTaskdStar.cxx, PWGLF/NUCLEX/Nuclei/NucleiPbPb/AliAnalysisTaskNucleiYield.cxx, PWGLF/NUCLEX/Utils/CODEX/AliAnalysisCODEX.h, PWGLF/NUCLEX/Utils/CODEX/AliAnalysisCODEXtask.cxx
@bdoenigu , this is the feature I told you before.
=> Support trigger classes in AliEventCuts

PWGGA/PHOSTasks/PHOS_Run2/AliAnalysisTaskPHOSEmbedding.cxx, PWGGA/PHOSTasks/PHOS_Run2/AliAnalysisTaskPHOSEmbedding.h
=> speed up embedding

OADB/COMMON/MULTIPLICITY/AliMultSelectionTask.h
Hi @ddobrigk ,
this anyway should be done, now I check if indeed that was the issue!
Thanks!
Max
=> Update ClassDef after yesterday PR

PWGDQ/dielectron/macrosLMEE/AddTaskMLTreeMakerwCutLib.C, PWGDQ/dielectron/macrosLMEE/AddTask_slehner_ElectronEfficiency.C, PWGDQ/dielectron/macrosLMEE/Config_slehner_Efficiency.C, PWGDQ/dielectron/macrosLMEE/LMEECutLib_slehner.C
adapt interfaces to the implementation of the dielectron efficiency task
=> adapt interfaces to the implementation of the dielectron efficiency task

PWGDQ/dielectron/LMEE/AliAnalysisTaskMLTreeMaker.cxx, PWGDQ/dielectron/macrosLMEE/AddTaskMLTreeMakerwCutLib.C, PWGDQ/dielectron/macrosLMEE/AddTask_slehner_ElectronEfficiency.C
adapt trigger selection in efficiency task to the one used in the ML tree maker
=> adapt trigger selection 

PWGJE/EMCALJetTasks/UserTasks/AliAnalysisTaskChargedJetsHadronToy.cxx, PWGJE/EMCALJetTasks/UserTasks/AliAnalysisTaskChargedJetsHadronToy.h
Optional filtering of physical primaries in the input array (when running on MC)
=> Allow to filter physical primaries in MC

PWGCF/Correlations/DPhi/AliAnalysisTaskHadronPhiCorr.cxx, PWGCF/Correlations/DPhi/AliAnalysisTaskHadronPhiCorr.h
Set functions for filter bits of Kaon tracks, associated hadrons, and trigger hadrons. Kaon PID and distribution histos added for systematic & efficiency checks.
=> Adding Set function for track filter bits, new histos for Kaon PID

PWGUD/DIFFRACTIVE/CEPdevel/AliCEPUtils.cxx
. checks if every EMC cluster has a matching track
=> updated version of AliCEPUtils::CaloClusterTrackdmax

PWG/EMCAL/EMCALbase/AliAnalysisTaskEmcalEmbeddingHelper.cxx, PWG/EMCAL/EMCALbase/AliAnalysisTaskEmcalEmbeddingHelper.h, PWG/EMCAL/READMEemcEmbedding.txt
adding a flag to switch on random rejection, and a factor by which to reject events randomly.
=> random rejection of events functionality added in embedding

PWGUD/DIFFRACTIVE/CEPdevel/AliCEPUtils.cxx
introduced time cut for EMC cluster to remove out-of-bunch clusters
=> update of AliCEPUtils::CaloClusterTrackdmax

PWGCF/Correlations/DPhi/AliAnalysisTaskGeneralBF.cxx, PWGCF/Correlations/DPhi/AliAnalysisTaskGeneralBF.h, PWGCF/Correlations/macros/PIDBFDptDpt/AddTaskGeneralBF.C
generalize DCA options for both particles
=> generalize DCA options for both particles 

PWGUD/DIFFRACTIVE/CEPdevel/AliCEPUtils.cxx
introduced cut of minimum 2 cells per accepted EMC cluster
=> modified AliCEPUtils::CaloClusterTrackdmax

PWGLF/RESONANCES/extra/AliXiStarpp13TeV.cxx
Change a histogram Axis of MC input from Y to multiplicity
=> Change Histogram axis

PWGGA/PHOSTasks/PHOS_Run2/AliAnalysisTaskPHOSObjectCreator.cxx
=> change primary MC label

PWGCF/FEMTOSCOPY/macros/Train/pPbKKfemto/exp/conf_run2/1/ConfigFemtoAnalysis.C, PWGCF/FEMTOSCOPY/macros/Train/pPbKKfemto/exp/conf_run2/2/ConfigFemtoAnalysis.C, PWGCF/FEMTOSCOPY/macros/Train/pPbKKfemto/exp/conf_run2/3/ConfigFemtoAnalysis.C
=> Lego train ConfigFemtoAnalysis.C for Elena

PWG/EMCAL/EMCALbase/AliEMCALRecoUtils.cxx, PWG/EMCAL/EMCALbase/AliEMCALRecoUtils.h
constraining better energies larger than 100 GeV - P. Ganoti
=> [EMCAL-190] New beam test data parametrization v4

PWGHF/jetsHF/AliAnalysisTaskBJetTC.cxx, PWGHF/jetsHF/AliAnalysisTaskBJetTC.h
Changing the PtRel selection method plus other changes.
=> Change the PtRel selection method plus other changes

PWGUD/UPC/AliAnalysisTaskUpcRho0.cxx
number of triggered events are ok now, some variables added to tree
=> number of triggered events fixed

OADB/AliTriggerAnalysis.cxx
=> Fix AliTriggerAnalysis: TPC HV dip detection

PWGGA/PHOSTasks/PHOS_Run2/AliAnalysisTaskPHOSPi0EtaToGammaGamma.cxx, PWGGA/PHOSTasks/PHOS_Run2/AliAnalysisTaskPHOSPi0EtaToGammaGamma.h, PWGGA/PHOSTasks/PHOS_Run2/AliPHOSTriggerHelper.h, PWGGA/PHOSTasks/PHOS_Run2/macros/AddTaskPHOSPi0EtaToGammaGamma_PbPb_5TeV.C, PWGGA/PHOSTasks/PHOS_Run2/macros/AddTaskPHOSPi0EtaToGammaGamma_pp_5TeV.C, PWGGA/PHOSTasks/PHOS_Run2/macros/AddTaskPHOSPi0EtaToGammaGamma_pp_5TeV_LHC17pq.C
add possibility to use private TRU bad map for QA
=> add possibility to use private TRU bad map

PWGCF/FEMTOSCOPY/macros/Train/pPbKKfemto/exp/conf_run2/1/ConfigFemtoAnalysis.C, PWGCF/FEMTOSCOPY/macros/Train/pPbKKfemto/exp/conf_run2/2/ConfigFemtoAnalysis.C, PWGCF/FEMTOSCOPY/macros/Train/pPbKKfemto/exp/conf_run2/3/ConfigFemtoAnalysis.C
=> Lego Train for Elena pPbKKfemto/exp/config_run2/1,2,3

PWGJE/EMCALJetTasks/UserTasks/AliAnalysisTaskChargedJetsHadronToy.cxx
Bugfix: Don't add neutral particles
=> Add correct particles in toy model

PWG/FLOW/Tasks/AliAnalysisTaskCMEV0PID.cxx, PWG/FLOW/Tasks/AliAnalysisTaskCMEV0PID.h
Change TH3F to TH2F for ZN,ZP calibration (and code clean-up)
=> Change TH3F to TH2F for ZN,ZP calibration

PWGDQ/dielectron/LMEE/AliAnalysisTaskMLTreeMaker.cxx, PWGDQ/dielectron/macrosLMEE/AddTaskMLTreeMakerwCutLib.C, PWGDQ/dielectron/macrosLMEE/AddTask_slehner_ElectronEfficiency.C, PWGDQ/dielectron/macrosLMEE/AddTask_slehner_diele_TMVA.C, PWGDQ/dielectron/macrosLMEE/Config_slehner_diele_TMVA.C, PWGDQ/dielectron/macrosLMEE/LMEECutLib_slehner.C
use only one MVA cut at a time for MLTreeMaker, add some additional QA histo bins
=> use only one MVA cut at a time for MLTreeMaker

PWGDQ/dielectron/macrosLMEE/AddTask_slehner_diele_TMVA.C, PWGDQ/dielectron/macrosLMEE/Config_slehner_diele_TMVA.C, PWGDQ/dielectron/macrosLMEE/LMEECutLib_slehner.C
=> fix pair histogram binning

PWGCF/FEMTOSCOPY/macros/Train/KchKchRun2_Oct2018/KK_13TeV_dist/AddTaskFemtoKchHBT1090.C, PWGCF/FEMTOSCOPY/macros/Train/KchKchRun2_Oct2018/KK_13TeV_dist/ConfigFemtoAnalysis.C, PWGCF/FEMTOSCOPY/macros/Train/KchKchRun2_Oct2018/KpKm_13TeV/AddTaskFemtoKchHBT1090.C, PWGCF/FEMTOSCOPY/macros/Train/KchKchRun2_Oct2018/KpKm_13TeV/ConfigFemtoAnalysis.C
=> Lego train config files for Ludmila KchKchRun2_Oct2018

PWGCF/Correlations/DPhi/AliAnalysisTaskCorPIDTOFdiprot.cxx, PWGCF/Correlations/DPhi/AliAnalysisTaskCorPIDTOFdiprot.h
histos at 0.4 and 0.2, Sdphi from di-proton to trigger, also changed eta range from 0.8 to 0.9
=> added di-proton radius cut 

PWGDQ/dielectron/LMEE/AliAnalysisTaskMLTreeMaker.cxx, PWGDQ/dielectron/LMEE/AliAnalysisTaskMLTreeMaker.h, PWGDQ/dielectron/macrosLMEE/AddTaskMLTreeMakerwCutLib.C, PWGDQ/dielectron/macrosLMEE/AddTask_slehner_ElectronEfficiency.C, PWGDQ/dielectron/macrosLMEE/AddTask_slehner_diele_TMVA.C, PWGDQ/dielectron/macrosLMEE/Config_slehner_Efficiency.C
task outputs checked to consistency
=> reduce number of cuts in efficiency task and test MLTreeMaker, 

PWGJE/EMCALJetTasks/UserTasks/AliAnalysisTaskChargedJetsHadronToy.cxx, PWGJE/EMCALJetTasks/UserTasks/AliAnalysisTaskChargedJetsHadronToy.h, PWGJE/EMCALJetTasks/UserTasks/AliAnalysisTaskJetExtractor.cxx, PWGJE/EMCALJetTasks/UserTasks/AliAnalysisTaskJetExtractor.h, PWGJE/EMCALJetTasks/macros/AddTaskChargedJetsHadronToy.C
Update toy to allow merging of different events
=> Update toy to allow merging of different events

PWGGA/CaloTrackCorrelations/AliAnaPi0.cxx, PWGGA/CaloTrackCorrelations/AliAnaPi0.h
Switch added: one cell separation between clusters.
Removed empty space after histogram name "hPrimChHadronPt " ->"hPrimChHadronPt"
=>  Switch added: one cell separation between clusters 

PWGHF/vertexingHF/AliAnalysisTaskSEHFTreeCreator.cxx, PWGHF/vertexingHF/AliAnalysisTaskSEHFTreeCreator.h, PWGHF/vertexingHF/AliHFCutOptTreeHandler.cxx, PWGHF/vertexingHF/AliHFCutOptTreeHandler.h, PWGHF/vertexingHF/CMakeLists.txt, PWGHF/vertexingHF/PWGHFvertexingHFLinkDef.h, PWGHF/vertexingHF/macros/AddTaskHFTreeCreator.C
Adding task to fill trees with candidates info, the tree handler class and update of CMakeLists.txt and PWGHFvertexingHFLinkDef.h
=> Adding task to fill trees with candidates info and tree handler class

PWG/CaloTrackCorrBase/AliCaloTrackParticle.cxx, PWG/CaloTrackCorrBase/AliCaloTrackParticle.h, PWGGA/CaloTrackCorrelations/AliAnaPhoton.cxx, PWGGA/CaloTrackCorrelations/AliAnaPi0.cxx, PWGGA/CaloTrackCorrelations/AliAnaPi0.h
1. New data member fCellAbsIdMax to store max energy cell AbsID added to AliCaloTrackParticle class and corresponding setter and getter. 
2. Setting AbsId for max energy cell in cluster (in class AliAnaPhoton.cxx).
3. Changes in AliAnaPi0 related to above.
=> New data member to store max energy cell AbsID added

PWGGA/PHOSTasks/PHOS_Run2/AliAnalysisTaskPHOSPi0EtaToGammaGamma.cxx
check feed down from Lambda and Sigma0 to gamma
=> check feed down from Lambda,Sigma0 to gamma

PWGJE/EMCALJetTasks/Tracks/AliAnalysisTaskEmcalClustersRef.cxx, PWGJE/EMCALJetTasks/Tracks/AliAnalysisTaskEmcalClustersRef.h
Add histograms for the maximum cluster
in  order to get estimates for centrality-
dependent rejection curves. ET-
dimension is removed, trigger cluster
dimension made optional.
=> [EMCAL-403] Add histograms for the maximum cluster

PWGGA/GammaConv/AliAnalysisTaskGammaCalo.cxx, PWGGA/GammaConv/AliAnalysisTaskGammaCalo.h
Added three new histograms for pi0-jet correlation studies
=> Added additional jet pi0 correlation plots

PWGGA/GammaConv/AliAnalysisTaskConvJet.h
https://github.com/alisw/AliPhysics/pull/7031 was initially not tested against ROOT6
=> PWGGA/GammaConv: ROOT6 fix for GammaJetTask

PWG/EMCAL/READMEemcCorrections.txt, PWG/EMCAL/config/AliEmcalCorrectionConfiguration.yaml
Adds documentation developed for #7037. We decided not to merge the code changes for now, but the documentation is still useful
=> EMCal CorrFW: Improve shared parameters docs

PWGLF/RESONANCES/extra/AliAnalysisTaskXi1530.cxx, PWGLF/RESONANCES/extra/AliAnalysisTaskXi1530.h
Add Set functions to the header file.
Add cut parameter variables to change them using AddTask macro.
=> Add Set function to modify Cut parameters

PWGJE/EMCALJetTasks/macros/JetQA/scalePtHardHistos.py
@jdmulligan, I fixed the broken .pdf creation. And I think outlier removal should be on by default
=> fixed the outlier removal .pdf creation

PWG/EMCAL/EMCALtasks/AliAodSkimTask.cxx, PWG/EMCAL/EMCALtasks/AliAodSkimTask.h, PWG/EMCAL/macros/AddTaskAodSkim.C
deals with conversions (as well as trd tracks, v0 and cascades).
=> New version 1.2

PWGGA/PHOSTasks/PHOS_Run2/AliAnalysisTaskPHOSPi0EtaToGammaGamma.cxx
extend mass range in histograms for Mgg vs. pT on module by module
=> extend mass range

PWGCF/Correlations/DPhi/Unfoldedhistos/AliCSAnalysisCutsBase.cxx, PWGCF/Correlations/DPhi/Unfoldedhistos/AliCSAnalysisCutsBase.h, PWGCF/Correlations/DPhi/Unfoldedhistos/AliCSEventCuts.cxx, PWGCF/Correlations/DPhi/Unfoldedhistos/AliCSEventCuts.h, PWGCF/Correlations/macros/Unfoldedhistos/runCorrelationsStudiesConfigMacro.C
Also
- multiplicty histograms binning according to analyzed system
- configuration activated p-Pb pile-up cut (for discarding it when MC)
=> Incorporated support for MC p-Pb

PWGPP/EMCAL/OADBMacros/UpdateEMCAL_OADB_Recalib_Run2_2018Final.C
=> [EMCAL-404] macro used to create OADB file with energy calibrations from 2018 

PWGHF/vertexingHF/AliHFSystErr.cxx, PWGHF/vertexingHF/AliHFSystErr.h
Systematics for D0 in finer pt bins (pp@5TeV). Flag to standard bins set to kFALSE.
=> D0 in finer pt bins for pp@5TeV

OADB/AliEventCuts.cxx, OADB/AliEventCuts.h
Hi @fprino, @iarsene , @chiarazampolli ,
this PR implements the cut we discussed via email. This is still work in progress, I have to check that I did all the relevant cleanups in the code before merging.
Cheers,
Max
=> [WIP] New combined pile-up cut SPDvsMult and MV

PWGCF/FEMTOSCOPY/macros/Train/KchKchRun2_Oct2018Sp/KK_13TeV_dist/AddTaskFemtoKchHBT1090.C, PWGCF/FEMTOSCOPY/macros/Train/KchKchRun2_Oct2018Sp/KK_13TeV_dist/ConfigFemtoAnalysis.C, PWGCF/FEMTOSCOPY/macros/Train/KchKchRun2_Oct2018Sp/KpKm_13TeV/AddTaskFemtoKchHBT1090.C, PWGCF/FEMTOSCOPY/macros/Train/KchKchRun2_Oct2018Sp/KpKm_13TeV/ConfigFemtoAnalysis.C, PWGCF/FEMTOSCOPY/macros/Train/KchKchRun2_Oct2018Sp/pipi_13TeV_dist/AddTaskFemtoKchHBT1090.C, PWGCF/FEMTOSCOPY/macros/Train/KchKchRun2_Oct2018Sp/pipi_13TeV_dist/ConfigFemtoAnalysis.C, PWGCF/FEMTOSCOPY/macros/Train/KchKchRun2_Oct2018Sp/pippim_13TeV/AddTaskFemtoKchHBT1090.C, PWGCF/FEMTOSCOPY/macros/Train/KchKchRun2_Oct2018Sp/pippim_13TeV/ConfigFemtoAnalysis.C
=> Lego Train with sphericity for Ludmila 10-Oct-2018

PWG/EMCAL/EMCALtasks/AliEsdSkimTask.cxx, PWG/EMCAL/EMCALtasks/AliEsdSkimTask.h, PWG/EMCAL/macros/AddTaskEsdSkim.C
Add switch on by default that the standard tracks are stored no extra stuff
=> Add v0s, and other branches.

PWGCF/FEMTOSCOPY/macros/AddTaskFemtoGranma.C
Added TString in the output container in AddTaskFemtoGranma.C in order to run in MC Lego trains.
=> Adding TString for Output MC

PWG/FLOW/Tasks/AliAnalysisTaskTwoMultiCorrelations.cxx, PWG/FLOW/Tasks/AliAnalysisTaskTwoMultiCorrelations.h
Modify the computation of the Q-vectors using arrays and the functions using them accordingly. Add the computation of an alternative method to get the 2-harmonics symmetric cumulants.
=> Modification of the gestion of the Q-vectors

PWGCF/Correlations/DPhi/AliAnalysisTaskPIDBFDptDpt.cxx, PWGCF/Correlations/DPhi/AliAnalysisTaskPIDBFDptDpt.h, PWGCF/Correlations/macros/PIDBFDptDpt/AddTaskPIDBFDptDpt.C
optimized purity estimation plots
=> optimized purity estimation plots

PWGLF/RESONANCES/extra/AliAnalysisTaskXi1530.cxx, PWGLF/RESONANCES/extra/AliAnalysisTaskXi1530.h, PWGLF/RESONANCES/extra/CMakeLists.txt
Change the cmake list to fix the dependency problem.
Especially, Add "PWGTools" to LIBDEPS.
Add QA histograms of Trigger Efficiency histogram in the code.
=> Fix "THistManager" dependency error

PWGGA/PHOSTasks/PHOS_Run2/AliAnalysisTaskPHOSPi0EtaToGammaGamma.cxx, PWGGA/PHOSTasks/PHOS_Run2/AliPHOSTriggerHelper.cxx
add histograms for trigger analysis
=> add histograms for trigger

PWG/EMCAL/EMCALtasks/AliEmcalCorrectionCellEnergy.cxx
This is a simple fix but needs to be discussed to do this properly.
I will approve this to be able to work, but it can be rejected as soon as it is available at least in 1 tag.
=> init TGrid::Connect when external file provided

PWGLF/RESONANCES/extra/AliAnalysisTaskXi1530.cxx, PWGLF/RESONANCES/extra/AliAnalysisTaskXi1530.h
Include AliAnalysisTaskSE.h in header file to avoid unexpected compile issue
Remove not-using couts
=> Fix failing on compile issue in some environment, remove useless cout

PWGCF/FEMTOSCOPY/FemtoDream/AliFemtoDreamAnalysis.cxx, PWGCF/FEMTOSCOPY/FemtoDream/AliFemtoDreamCascade.cxx, PWGCF/FEMTOSCOPY/FemtoDream/AliFemtoDreamTrack.cxx, PWGCF/FEMTOSCOPY/FemtoDream/AliFemtoDreamTrack.h
o Set phi at TPC radii also for ESDs case
o Set up skeleton for ESD v0
=> Minor improvements for ESD analysis

PWGCF/FLOW/macros/AddTaskAMPTTest.C
moves around a lot of variables that were out of scope .... and references to classes that no longer exist
=>  prepare flow addtask macro for root6

PWGGA/PHOSTasks/PHOS_Run2/AliAnalysisTaskPHOSPi0EtaToGammaGamma.cxx
quick fix of my previous commit.
=> quick fix of the previous commit

PWGCF/Correlations/DPhi/AliAnalysisTaskHadronPhiCorr.cxx
distribution as well as PID cuts
=> adding new track filter setting functions, new hist for kaon track

PWGDQ/dielectron/macrosLMEE/AddTask_acapon_Efficiency.C, PWGDQ/dielectron/macrosLMEE/Config_acapon.C, PWGDQ/dielectron/macrosLMEE/Config_acapon_Efficiency.C, PWGDQ/dielectron/macrosLMEE/LMEECutLib_acapon.C
Lower pt cut for obtaining resolution plots.
Turn on QA plots for analysis task
=> New resolution plot settings

PWG/FLOW/Tasks/AliFlowEventCuts.cxx, PWG/FLOW/Tasks/AliFlowEventCuts.h, PWGCF/FLOW/macros/AddTaskESEFlowQC.C
=> Adding sphericity as a cut to flow event (it can be done better)

PWGCF/FEMTOSCOPY/macros/Train/pPbKKfemto/exp/conf_run2/2/ConfigFemtoAnalysis.C
=> ConfigFemtoAnalysis.C for Elena

PWGHF/jetsHF/AliAnalysisTaskBJetTC.cxx, PWGHF/jetsHF/AliAnalysisTaskBJetTC.h
PWGHF/jetsHF: few changes on the code.
=> PWGHF/jetsHF: Adding Tagged jets Response Matrix

PWGGA/PHOSTasks/PHOS_Run2/AliAnalysisTaskPHOSPi0EtaToGammaGamma.cxx, PWGGA/PHOSTasks/PHOS_Run2/AliAnalysisTaskPHOSPi0EtaToGammaGamma.h, PWGGA/PHOSTasks/PHOS_Run2/macros/AddTaskPHOSPi0EtaToGammaGamma_PbPb_5TeV.C, PWGGA/PHOSTasks/PHOS_Run2/macros/AddTaskPHOSPi0EtaToGammaGamma_pp_5TeV.C, PWGGA/PHOSTasks/PHOS_Run2/macros/AddTaskPHOSPi0EtaToGammaGamma_pp_5TeV_LHC17pq.C
=> revert trigger analysis

PWGCF/FEMTOSCOPY/FemtoDream/AliAnalysisTaskSigma0Femto.cxx, PWGCF/FEMTOSCOPY/FemtoDream/AliAnalysisTaskSigma0Femto.h, PWGCF/FEMTOSCOPY/FemtoDream/AliFemtoDreamBasePart.cxx, PWGCF/FEMTOSCOPY/FemtoDream/AliFemtoDreamBasePart.h, PWGCF/FEMTOSCOPY/macros/AddTaskSigma0Femto.C, PWGGA/Hyperon/AliSigma0ParticleBase.h, PWGGA/Hyperon/AliSigma0ParticlePhotonMother.h, PWGGA/Hyperon/AliSigma0ParticleV0.h, PWGGA/Hyperon/AliSigma0PhotonMotherCuts.cxx, PWGGA/Hyperon/AliSigma0PhotonMotherCuts.h
o Also look at the corresponding Lambda_Sigma - p and photon_Sigma - p correlation function
=> Study correlation between the Sigma0 and its daughters

PWGHF/hfe/AliAnalysisTaskHFEemcQA.cxx, PWGHF/hfe/macros/AddTaskHFEemcQA.C
Make AddTaskHFEemcQA.C macro ROOT6 compatible.
Comment cout statements in AliAnalysisTaskHFEemcQA.cxx task
=> Make AddTask macro ROOT6 compatible, remove couts

PWGDQ/reducedTree/AliReducedAnalysisFilterTrees.cxx, PWGDQ/reducedTree/AliReducedAnalysisFilterTrees.h
Adding possibility to reject randomly signal events according to pT-dependent weights 
(same procedure as implemented in AliReducedAnalysisJpsi2ee)
=> small update

PWGCF/FEMTOSCOPY/macros/Train/Oct2018Sp2/KK_13TeV_dist/AddTaskFemtoKchHBT1090.C, PWGCF/FEMTOSCOPY/macros/Train/Oct2018Sp2/KK_13TeV_dist/ConfigFemtoAnalysis.C, PWGCF/FEMTOSCOPY/macros/Train/Oct2018Sp2/pipi_13TeV_dist/AddTaskFemtoKchHBT1090.C, PWGCF/FEMTOSCOPY/macros/Train/Oct2018Sp2/pipi_13TeV_dist/ConfigFemtoAnalysis.C
=> For Ludmila Oct2018Sp2

PWGLF/NUCLEX/Exotica/LambdaNN/AliAnalysisTaskLNNntuple.cxx, PWGLF/NUCLEX/Exotica/LambdaNN/Getoutput.cxx, PWGLF/NUCLEX/Exotica/LambdaNN/Getoutput.h
Bug fixes and analysis macro updated.
=> updates after checks

PWGCF/FEMTOSCOPY/macros/Train/pPbKKfemto/exp/conf_run2/2/ConfigFemtoAnalysis.C
=> Train macros for Elena pPbKKfemto/exp/conf_run2/2/ConfigFemtoAnalysis.C

PWGCF/FEMTOSCOPY/macros/Train/pPbKKfemto/MC/conf_2016/FB8/wLed/ConfigFemtoAnalysis.C, PWGCF/FEMTOSCOPY/macros/Train/pPbKKfemto/MC/conf_2016/FB8/woLed/ConfigFemtoAnalysis.C
=> Train macros for Elena: pPbKKfemto/MC/conf_2016/FB8

PWGGA/GammaConv/macros/AddTask_GammaConvV1_pp.C
=> PWGGA: Adding similar Config, to be able to run with different QA Settings

PWGGA/GammaConv/AliCutHandlerPCM.cxx, PWGGA/GammaConv/macros/AddTask_GammaConvNeutralMesonPiPlPiMiNeutralMeson_CaloMode_pp.C
In addition: Fix AliCutHandlerPCM for compilation on mac
=> D0 channel: Open invariant mass cut on charged pion pair

PWGGA/GammaConv/AliAnalysisTaskNeutralMesonToPiPlPiMiNeutralMeson.cxx
Might be relevant when looking into triggered data.
=> Increase pt-range for D0 mode

PWGCF/FEMTOSCOPY/macros/Train/pPbKKfemto/MC/conf_2016/FB8/pions/ConfigFemtoAnalysis.C
=> Train macro pPbKKfemto/MC/conf_2016/FB8/pions/ConfigFemtoAnalysis.C

PWGDQ/dielectron/macrosLMEE/AddTask_acapon.C, PWGDQ/dielectron/macrosLMEE/Config_acapon.C, PWGDQ/dielectron/macrosLMEE/LMEECutLib_acapon.C
MCtruthHandler was not being automatically detected, and data corrections were being applied to MC. Added an argument to make case explicit.
Additionally, added all options from Config file to AddTask arguments enabling easier usage.
=> acapon_LMEE: Fixes bug so PIDcorr is correctly applied to MC

PWGGA/GammaConv/AliAnalysisTaskGammaConvV1.cxx
enableQAPhotonTask option 2 and option 4 are both called, when option 5 is chosen.
=> PWGGA: add Option 5 for enableQAPhotonTask

PWGJE/EMCALJetTasks/UserTasks/AliAnalysisTaskJetExtractor.cxx, PWGJE/EMCALJetTasks/UserTasks/AliAnalysisTaskJetExtractor.h
=> Changed track to particle container

PWGHF/jetsHF/AliAnalysisTaskBJetTC.cxx, PWGHF/jetsHF/AliAnalysisTaskBJetTC.h
A threshold parameter was added to control the pThard.
=> PWGHF/jetsHF: Adding a threshold parameter for the pThard

PWGGA/GammaConv/AliAnalysisTaskConvJet.cxx, PWGGA/GammaConv/AliAnalysisTaskConvJet.h, PWGGA/GammaConv/AliAnalysisTaskGammaCalo.cxx, PWGGA/GammaConv/AliAnalysisTaskGammaCalo.h
Added MC true pi0/eta in jet histograms and MC true jet pt vs rec jet pt histograms in AliAnalysisTaskGammaCalo. Changed AliAnalysisTaskConvJet to be able to obtain MC true jet results from a MC true jet finder.
=> PWGGA Adding Unfolding and true meson jet histograms ROOT5

PWGJE/EMCALJetTasks/UserTasks/AliAnalysisTaskJetCoreEmcal.cxx, PWGJE/EMCALJetTasks/UserTasks/AliAnalysisTaskJetCoreEmcal.h, PWGJE/EMCALJetTasks/macros/AddTaskJetCoreEmcal.C
Remove obsolete histograms and fix error messages when running on pp
=> some cleanup for running with pp

PWGCF/FEMTOSCOPY/AliFemtoUser/AliFemtoModelCorrFctnTrueQ3DByParent.cxx, PWGCF/FEMTOSCOPY/macros/Train/PionPionFemto/ConfigNuFemtoAnalysis.C
Change output directory name in analysis macro
=> PWGCF: AliFemtoModelCorrFctnTrueQ3DByParent - Fix denominator title

PWGCF/FEMTOSCOPY/macros/Train/pPbKKfemto/exp/conf_run2/2/ConfigFemtoAnalysis.C
=> Train macros: pPbKKfemto/exp/conf_run2/2/ConfigFemtoAnalysis.C

PWG/EMCAL/EMCALtasks/AliAodSkimTask.cxx, PWG/EMCAL/EMCALtasks/AliAodSkimTask.h, PWG/EMCAL/macros/AddTaskAodSkim.C
=> Adapted for pbpb with track removal/cleanup settings

PWGGA/GammaConv/AliAnalysisTaskGammaConvDtrue.cxx, PWGGA/GammaConv/AliAnalysisTaskGammaConvDtrue.h, PWGGA/GammaConv/CMakeLists.txt, PWGGA/GammaConv/PWGGAGammaConvLinkDef.h, PWGGA/GammaConv/macros/AddTaskGammaConvDtrue.C
- Absolute counts in acceptance
- Decay kinematics
=> Adding task for D0->pi0piplpimi looking at MC truth

PWGGA/PHOSTasks/PHOS_Run2/AliAnalysisTaskPHOSPi0EtaToGammaGamma.cxx, PWGGA/PHOSTasks/PHOS_Run2/AliPHOSEventCuts.cxx, PWGGA/PHOSTasks/PHOS_Run2/macros/AddTaskPHOSPi0EtaToGammaGamma_pp_5TeV_LHC17pq.C
update trigger efficiency in LHC17pq
=> update trigger efficiency in LHC17pq

PWGDQ/dielectron/LMEE/AliAnalysisTaskMLTreeMaker.cxx
attempt to fix centrality selection issue (cannot be reproduced locally)
=> attempt to fix centrality selection issue

PWGCF/FEMTOSCOPY/macros/Train/KpmHBT_MC/Feb2018/ConfigFemtoAnalysis.C
=> MC PbPb Train macro: KpmHBT_MC/Feb2018/ConfigFemtoAnalysis.C

PWGCF/Correlations/JCORRAN/Pro/AliJJetJtAnalysis.cxx, PWGCF/Correlations/JCORRAN/Pro/AliJJetJtAnalysis.h
Add a cut to leading track reference jT. The pT of leading track is
required to be 20% of the jet pT.
=> Adds leading track pT cut

PWGCF/FEMTOSCOPY/macros/Train/pPbKKfemto/MC/conf_2016/FB8/pions/ConfigFemtoAnalysis.C
=> macro Train pPbKKfemto/MC/conf_2016/FB8/pions/ConfigFemtoAnalysis.C

PWGJE/EMCALJetTasks/UserTasks/AliAnalysisTaskJetExtractor.cxx, PWGJE/EMCALJetTasks/UserTasks/AliAnalysisTaskJetExtractor.h
=> Added new MC histograms

PWGHF/jetsHF/AliAnalysisTaskBJetTC.cxx
Fixing a problem in the generator level jets.
=> PWGHF/jetsHF: Fixing a problem in the generator level jets

PWGGA/PHOSTasks/PHOS_Run2/AliAnalysisTaskPHOSPi0EtaToGammaGamma.cxx
update photon purity estimation
=> update photon purity estimation

PWGLF/SPECTRA/PiKaPr/TPCTOFfits/AliAnalysisPIDTrack.cxx
(not sure why the latest MC does not contain it?)
=> Added AliTrackRef check to AliAnalysisPIDTrack 

PWGGA/GammaConv/AliAnalysisTaskNeutralMesonToPiPlPiMiNeutralMeson.cxx
- Consequently put objects which are used only locally within a function on the stack
- Fix indentation of the function CalculateBackground
- Increase invariant mass range for the D0 reconstruction mode
=> Fixes for D0 analysis

PWGGA/EMCALTasks/AliAnalysisTaskGammaHadron.cxx, PWGGA/EMCALTasks/AliAnalysisTaskGammaHadron.h
Adds new cluster-track matching histograms.
Adds accepted pion eta phi hist.
Allows change to pool size.
=> new histograms and pool size function

PWGDQ/dielectron/macrosLMEE/AddTask_acapon.C, PWGDQ/dielectron/macrosLMEE/AddTask_acapon_Efficiency.C, PWGDQ/dielectron/macrosLMEE/Config_acapon_Efficiency.C, PWGDQ/dielectron/macrosLMEE/LMEECutLib_acapon.C
MC PID correction maps now stored in individual files corresponding to production name. Move to main folder to use during analysis.
Formatting of two AddTask files also included in commit.
=> Enables use of diff. MC PID correction maps

PWGJE/EMCALJetTasks/CMakeLists.txt, PWGJE/EMCALJetTasks/PWGJEEMCALJetTasksLinkDef.h, PWGJE/EMCALJetTasks/UserTasks/AliAnalysisTaskSVtaskMCFilter.cxx, PWGJE/EMCALJetTasks/UserTasks/AliAnalysisTaskSVtaskMCFilter.h, PWGJE/EMCALJetTasks/macros/AddTaskSVtaskMCFilter.C
Line GetTrackContainer(0)->ResetCurrentID(); was removed
=> Filter task

PWG/MCLEGO/AddMCGenRELDIS.C
=>  remove sprurious headers for interpreted code ( this is not root6 ready)

PWGHF/vertexingHF/AliHFSystErr.cxx, PWGHF/vertexingHF/AliHFSystErr.h
Systematics for Dstar pp@5TeV in fine bins
=> PWGHF: Dstar pp5TeV syst fine bins

PWGJE/EMCALJetTasks/UserTasks/AliAnalysisTaskJetExtractor.cxx, PWGJE/EMCALJetTasks/UserTasks/AliAnalysisTaskJetExtractor.h
Affects only private analysis task
=> Add label property for MC

PWGDQ/dielectron/macrosLMEE/AddTask_acapon_Efficiency.C, PWGDQ/dielectron/macrosLMEE/Config_acapon_Efficiency.C, PWGDQ/dielectron/macrosLMEE/LMEECutLib_acapon.C
Introduces a cut setting designed for resolution studies
=> Creates a "resolution" cut setting (acapon_LMEE)

PWGDQ/dielectron/macrosLMEE/Config_acapon_Efficiency.C
Temporary for resolution production
=> Switches smearing off in efficiency task

PWGGA/CaloTrackCorrelations/macros/ana.C
=> fix macro to run analysis with Root6 from alien shell 

PWGLF/STRANGENESS/Lifetimes/AliAnalysisTaskStrangenessLifetimes.cxx, PWGLF/STRANGENESS/Lifetimes/AliAnalysisTaskStrangenessLifetimes.h, PWGLF/STRANGENESS/Lifetimes/MCparticle.h, PWGLF/STRANGENESS/Lifetimes/selectors/MiniV0efficiency.cxx, PWGLF/STRANGENESS/Lifetimes/selectors/MiniV0efficiency.h
Add selector for efficiency analysis and fix task of strangeness and hypertriton compatibility
=> Add selector for lifetimes and fix hypertriton compatibility

PWGCF/FEMTOSCOPY/macros/Train/AK/ConfigFemtoAnalysis.C, PWGCF/FEMTOSCOPY/macros/Train/JZ/ConfigFemtoAnalysis.C, PWGCF/FEMTOSCOPY/macros/Train/KG/ConfigFemtoAnalysis.C
adding config files from students in the AliFemto
=> AliFemto: adding student config files

PWGGA/PHOSTasks/PHOS_Run2/AliAnalysisTaskPHOSEmbeddingEfficiency.cxx, PWGGA/PHOSTasks/PHOS_Run2/AliAnalysisTaskPHOSPi0EtaToGammaGamma.cxx, PWGGA/PHOSTasks/PHOS_Run2/macros/AddTaskPHOSEmbeddingEfficiency.C
revert photon purity estimation
=> revert photon purity estimation

PWGGA/EMCALTasks/AliAnalysisTaskGammaHadron.cxx, PWGGA/EMCALTasks/AliAnalysisTaskGammaHadron.h
Fixes an error in the track-cluster matching.
Adds two more track-cluster matching histograms.
=> Fixes an error in the track-cluster matching.

PWGGA/CaloTrackCorrelations/macros/ana.C
in pT hard binned productions before analysis on demand
=> switch off on demand the checking of the cross section 

PWGCF/FEMTOSCOPY/FemtoDream/AliAnalysisTaskSigma0Femto.cxx, PWGCF/FEMTOSCOPY/FemtoDream/AliAnalysisTaskSigma0Femto.h, PWGCF/FEMTOSCOPY/FemtoDream/AliFemtoDreamBasePart.cxx, PWGCF/FEMTOSCOPY/FemtoDream/AliFemtoDreamBasePart.h, PWGCF/FEMTOSCOPY/FemtoDream/AliFemtoDreamCascadeCuts.cxx, PWGCF/FEMTOSCOPY/macros/AddTaskFemtoDreamSysVar.C, PWGCF/FEMTOSCOPY/macros/AddTaskOmegaFemtoSysVar.C, PWGCF/FEMTOSCOPY/macros/AddTaskSigma0DebugTest.C, PWGCF/FEMTOSCOPY/macros/AddTaskSigma0Femto.C, PWGGA/Hyperon/AliSigma0ParticlePhotonMother.cxx, PWGGA/Hyperon/AliSigma0ParticlePhotonMother.h, PWGGA/Hyperon/AliSigma0PhotonMotherCuts.cxx, PWGGA/Hyperon/AliSigma0PhotonMotherCuts.h, PWGGA/Hyperon/AliSigma0V0Cuts.cxx, PWGGA/Hyperon/AliSigma0V0Cuts.h
o Sigma0
o Dedicated photon QA
o Count number of events in the multiplicity bins for normalisation
o Correlation correlator correlating correlated pairs to check for daughter correlation effects
o FemtoDream
o Further expand the MC handling
o Fix small bug in Omega/Xi rejection
o Decrease the range of the femto histograms in the case of systematic variations
=> Improvements for the Sigma0 and femto analyses

PWGLF/SPECTRA/ChargedHadrons/dNdPt/macros/AddTask_dNdPtpp_TPCITS.C
Changing the second argument of CreatedNdPCuts, before it was Bool, now it is a string.
=> Update in AddTask

PWGCF/FEMTOSCOPY/macros/Train/GR_Nov2018/kk_502_0_50/AddTaskFemtoKchHBT1090.C, PWGCF/FEMTOSCOPY/macros/Train/GR_Nov2018/kk_502_0_50/ConfigFemtoAnalysis.C, PWGCF/FEMTOSCOPY/macros/Train/GR_Nov2018/kk_502_50_90/AddTaskFemtoKchHBT1090.C, PWGCF/FEMTOSCOPY/macros/Train/GR_Nov2018/kk_502_50_90/ConfigFemtoAnalysis.C, PWGCF/FEMTOSCOPY/macros/Train/GR_Nov2018/pipi_502_0_50/AddTaskFemtoKchHBT1090.C, PWGCF/FEMTOSCOPY/macros/Train/GR_Nov2018/pipi_502_0_50/ConfigFemtoAnalysis.C
=> PWGCF/FEMTOSCOPY/macros/Train/GR_Nov2018 PbPb5.02

PWGGA/PHOSTasks/PHOS_Run2/macros/AddTaskPHOSEmbeddingEfficiency.C, PWGGA/PHOSTasks/PHOS_Run2/macros/AddTaskPHOSPi0EtaToGammaGamma_PbPb_5TeV.C, PWGGA/PHOSTasks/PHOS_Run2/macros/AddTaskPHOSPi0EtaToGammaGamma_pp_5TeV.C, PWGGA/PHOSTasks/PHOS_Run2/macros/AddTaskPHOSPi0EtaToGammaGamma_pp_5TeV_LHC17pq.C, PWGGA/PHOSTasks/PHOS_Run2/macros/AddTaskPHOSSingleSim.C
=> support ROOT6

PWGCF/FEMTOSCOPY/macros/Train/pPbKKfemto/MC/addtask/Any/AddTaskFemto.C
=> Elena: pPbKKfemto/MC/addtask/Any/AddTaskFemto.C

PWGLF/RESONANCES/extra/AliAnalysisTaskXi1530.cxx
Remove "IsEventSelected" cut in HighMultiplicity Trigger event.
Adjust bin setup and get multiplicity function for HM mode.
=> PWGLF: Change setup for the HM trigger mode

PWGDQ/dielectron/macrosLMEE/AddTask_rbailhac_ElectronEfficiencyV2.C, PWGDQ/dielectron/macrosLMEE/Config_rbailhac_ElectronEfficiencyV2.C
Update Add task and Config for Root5 and Root6
=> Efficiency Task AOD

PWGGA/GammaConv/AliAODConversionPhoton.cxx, PWGGA/GammaConv/AliAnalysisTaskClusterQA.cxx, PWGGA/GammaConv/AliAnalysisTaskClusterQA.h, PWGGA/GammaConv/AliCaloPhotonCuts.cxx, PWGGA/GammaConv/AliCaloPhotonCuts.h, PWGGA/GammaConv/AliConvEventCuts.cxx, PWGGA/GammaConv/AliConvEventCuts.h
- added MC flags for isolated photon analysis
- added enum for upcoming gamma-Jet MC production (LHC18b11c)
- fixed electron from frac photon loop in AliAODConversionPhoton.cxx
=> PWGGA/GammaConv: added new MC flags for isolated photons & more

PWGJE/EMCALJetTasks/UserTasks/AliAnalysisTaskJetExtractor.cxx, PWGJE/EMCALJetTasks/UserTasks/AliAnalysisTaskJetExtractor.h, PWGJE/EMCALJetTasks/macros/AddTaskJetExtractor.C
+ unified random number generator
=> Mass background correction

PWGHF/vertexingHF/AliHFSystErr.cxx
Update normalisation systematic D-meson analyses pp@5TeV after new VdM scan
=> PWGHF: Update norm systs pp5TeV

PWGJE/EMCALJetTasks/AliPWGJETrainHelpers.cxx
Try number 3 for the train helpers: `std::string` cannot be assigned to a nullptr, so we assign the
environment variable to a `const char *` and then assign that to a
string if it is not null.
The `nullptr` occurred up if the environment variable didn't exist. I don't t know I missed this in testing, but apparently I did. It is now testing and works regardless of whether environment variables are defined.
@jdmulligan , @mfasDa Could one of you please give a quick code review? The code is not quite so clean now, but I don't see a super convenient way around it.
=> Fix handling of Getenv

PWGCF/Correlations/DPhi/AliAnalysisTaskSEpPbCorrelationsYS.cxx
add TPC eta bin in container of correlation results
=> add TPC eta bin

PWGCF/FEMTOSCOPY/macros/Train/KK_Run2_NovSp/KK_13TeV_dist_03/AddTaskFemtoKchHBT1090.C, PWGCF/FEMTOSCOPY/macros/Train/KK_Run2_NovSp/KK_13TeV_dist_03/ConfigFemtoAnalysis.C, PWGCF/FEMTOSCOPY/macros/Train/KK_Run2_NovSp/KK_13TeV_dist_07/AddTaskFemtoKchHBT1090.C, PWGCF/FEMTOSCOPY/macros/Train/KK_Run2_NovSp/KK_13TeV_dist_07/ConfigFemtoAnalysis.C, PWGCF/FEMTOSCOPY/macros/Train/KK_Run2_NovSp/pipi_13TeV_dist_03/AddTaskFemtoKchHBT1090.C, PWGCF/FEMTOSCOPY/macros/Train/KK_Run2_NovSp/pipi_13TeV_dist_03/ConfigFemtoAnalysis.C, PWGCF/FEMTOSCOPY/macros/Train/KK_Run2_NovSp/pipi_13TeV_dist_07/AddTaskFemtoKchHBT1090.C, PWGCF/FEMTOSCOPY/macros/Train/KK_Run2_NovSp/pipi_13TeV_dist_07/ConfigFemtoAnalysis.C
=> Train macro for sphericity: KK_Run2_NovSp

PWGHF/vertexingHF/AliHFSystErr.cxx
tracking systematics for D0 in finer pt bins updated
=> fix in tracking syst for D0 in pp5TeV

PWGHF/vertexingHF/AliAnalysisTaskSELambdacTMVA.cxx, PWGHF/vertexingHF/macros/AddTaskLambdacTMVA.C
Some small fixes to check whether PID is set in the cut file to be able to run with no PID, and fix to add task to be able to run with root6.
=> fix task to run with no PID and allow root6 running

PWGHF/vertexingHF/AliHFSystErr.cxx
Fix on Systematics for D0 in finer pt bins: raw yield extraction
=> fix Syst Raw Yield D0

PWGHF/vertexingHF/AliAnalysisTaskSEBPlustoD0Pi.cxx, PWGHF/vertexingHF/AliRDHFCutsBPlustoD0Pi.cxx, PWGHF/vertexingHF/AliRDHFCutsBPlustoD0Pi.h
- Some small bug / warning fixes Bplus code
- Adding all the cuts in the AliRDHFCutsBplustoD0Pi class (several were done in the AnalysisTask), so the MVA task can access them. For now made new *IsSelectedMVA() functions, will soon get merged with the already existing *IsSelected() functions.
=> PWGHF: Update Bplus code for MVA studies

PWGCF/Correlations/DPhi/AliAnalysisTaskDiHadCorrelHighPt.cxx, PWGCF/Correlations/DPhi/AliAnalysisTaskDiHadCorrelHighPt.h, PWGCF/Correlations/macros/AddTaskDiHadCorrelHighPt.C
finer binning in Delta Eta, Delta Phi; add mass info in correlation histograms; 
add Purity check; 
add MC Pt hard for jet events info; 
Change the way of assignment of MC reconstructed to generated
=> Changes in AliAnalysisTaskDiHadCorrelHighPt

PWGCF/Correlations/DPhi/Unfoldedhistos/AliCSEventCuts.cxx, PWGCF/Correlations/macros/Unfoldedhistos/runCorrelationsStudiesConfigMacro.C, PWGCF/Correlations/macros/Unfoldedhistos/runCorrelationsStudiesConfigMacro.H, PWGCF/Correlations/macros/Unfoldedhistos/runCorrelationsStudiesTask.C
Also incorporated tentative pp pile-up removal cut
=> Adaptation to ROOT6

PWGCF/FEMTOSCOPY/macros/Train/JZ/ProtonLambda/ConfigAvgsepAnalysis.C
Adding Config file to AliFemto
=> Adding Config file to AliFemto

PWGCF/Correlations/DPhi/AliAnalysisTaskPIDBFDptDpt.cxx, PWGCF/Correlations/DPhi/AliAnalysisTaskPIDBFDptDpt.h
added purity histograms for particle 2 in MCAODreco
=> added purity histograms

PWGDQ/reducedTree/AliCorrelationExtraction.cxx, PWGDQ/reducedTree/AliCorrelationExtraction.h, PWGDQ/reducedTree/AliReducedVarManager.cxx
- bugfix when using 3D hadron efficiency map
- new method to correct for hadron efficiency after correlation signal extraction
=> Updates for correlation analysis

PWGGA/PHOSTasks/PHOS_Run2/AliAnalysisTaskPHOSEmbeddedDiffObjectCreator.cxx, PWGGA/PHOSTasks/PHOS_Run2/AliAnalysisTaskPHOSObjectCreator.cxx, PWGGA/PHOSTasks/PHOS_Run2/AliAnalysisTaskPHOSObjectCreator.h, PWGGA/PHOSTasks/PHOS_Run2/macros/AddTaskPHOSEmbeddedDiffObjectCreator.C
add missing files in my previous commit
=> add missing files

PWGCF/FEMTOSCOPY/macros/Train/pPbKKfemto/MC/conf_2016/FB8/pions/ConfigFemtoAnalysis.C
=> Elena: pPbKKfemto/MC/conf_2016/FB8/pions/ConfigFemtoAnalysis.C

PWGCF/FEMTOSCOPY/macros/Train/pPbKKfemto/MC/conf_2016/FB8/pions/nDCA/ConfigFemtoAnalysis.C
=>  pPbKKfemto/MC/conf_2016/FB8/pions/nDCA/ConfigFemtoAnalysis.C

PWG/EMCAL/EMCALtrigger/AliEmcalTriggerMakerKernel.cxx
In addition few info/debug streams
=> [EMCAL-411] Automatically enable background subtraction for PbPb

PWGGA/CaloTrackCorrelations/AliAnaElectron.cxx, PWGGA/CaloTrackCorrelations/AliAnaElectron.h
and change some histogram names
=> fill MC histograms for the proper PID index, hadd short axis MC histograms

PWGDQ/dielectron/core/AliDielectronSignalMC.cxx
Added the kFinalState defintion for the legs of an incl. JPSI
=> PWGDQ AliDielectronSignalMC small change in default signal source

PWGCF/FEMTOSCOPY/AliFemto/AliFemtoEventReaderAOD.cxx, PWGCF/FEMTOSCOPY/AliFemto/AliFemtoEventReaderAODChain.cxx, PWGCF/FEMTOSCOPY/AliFemtoUser/AliFemtoAnalysisPionPion.cxx, PWGCF/FEMTOSCOPY/AliFemtoUser/AliFemtoCorrFctnDEtaDPhiSimple.cxx, PWGCF/FEMTOSCOPY/AliFemtoUser/AliFemtoCorrFctnDEtaDPhiSimple.h, PWGCF/FEMTOSCOPY/AliFemtoUser/AliFemtoModelCorrFctnDEtaDPhiAK.cxx, PWGCF/FEMTOSCOPY/AliFemtoUser/AliFemtoModelCorrFctnDEtaDPhiAK.h, PWGCF/FEMTOSCOPY/AliFemtoUser/CMakeLists.txt, PWGCF/FEMTOSCOPY/AliFemtoUser/PWGCFfemtoscopyUserLinkDef.h
- Standardize indentation formatting of AliFemtoEventReaderAOD
- Add correlation function AliFemtoModelCorrFctnDEtaDPhiAK
- Simplify implementation of AliFemtoCorrFctnDEtaDPhiSimple
=> PWGCF: New Correlation function + Formatting Fixes 

PWGDQ/dielectron/LMEE/AliAnalysisTaskMLTreeMaker.cxx, PWGDQ/dielectron/LMEE/AliAnalysisTaskMLTreeMaker.h, PWGDQ/dielectron/macrosLMEE/AddTaskMLTreeMakerwCutLib.C, PWGDQ/dielectron/macrosLMEE/AddTask_slehner_ElectronEfficiency.C, PWGDQ/dielectron/macrosLMEE/AddTask_slehner_diele_TMVA.C, PWGDQ/dielectron/macrosLMEE/Config_slehner_Efficiency.C, PWGDQ/dielectron/macrosLMEE/Config_slehner_diele_TMVA.C, PWGDQ/dielectron/macrosLMEE/LMEECutLib_slehner.C
- passed consistency check for tree vs. dieleFW
=> implement PID correction for ITS, TPC, TOF in MC and RD

PWGGA/PHOSTasks/PHOS_Run2/AliAnalysisTaskPHOSObjectCreator.cxx
revert exotic cluster rejection
=> revert exotic cluster rejection

PWGCF/Correlations/JCORRAN/Pro/AliAnalysisTaskBSEmbedding.cxx, PWGCF/Correlations/JCORRAN/Pro/AliAnalysisTaskBSEmbedding.h, PWGCF/Correlations/JCORRAN/Pro/AliBSDiJetTask.cxx, PWGCF/Correlations/JCORRAN/Pro/CMakeLists.txt, PWGCF/Correlations/JCORRAN/Pro/PWGCFCorrelationsJCORRANProLinkDef.h, PWGCF/Correlations/macros/jcorran/AddTaskBSDiJet.C
Dear all, 
I have added new files to connect embedding AOD containers to embedded AliVEvent and updated existing files to be compatible with the new files. This is needed to make a response matrix between MC particle-level jet and Heavy-ion data embedded recon-level MC jet. 
Cheers,
Beomkyu
=> Update of Correlation/JCORRAN/PRO/AliBSDiJetTask

PWGHF/vertexingHF/AliRDHFCutsBPlustoD0Pi.cxx
Fix a copy-paste mistake that introduced a bug in the Bplus code (which only popped up during merging)
=> PWGHF: Fix merging failure Bplus

PWGHF/vertexingHF/AliAnalysisTaskSEDvsMultiplicity.cxx, PWGHF/vertexingHF/AliAnalysisTaskSEDvsMultiplicity.h, PWGHF/vertexingHF/macros/AddTaskDvsMultiplicity.C
Code implemented for the analysis of Lc-> pKpi vs multiplicity
=> Lc in pKpi added

PWG/FLOW/Tasks/AliAnalysisTaskTwoMultiCorrelations.cxx, PWG/FLOW/Tasks/AliAnalysisTaskTwoMultiCorrelations.h
+ Rewritting of the full analysis method and gestion of the TProfiles for the various correlations in order to remove some errors in their values.
=> Addition of the gestion of MC events.

PWGLF/STRANGENESS/Lifetimes/AliAnalysisTaskStrangenessLifetimes.cxx, PWGLF/STRANGENESS/Lifetimes/MCparticle.h, PWGLF/STRANGENESS/Lifetimes/selectors/MiniV0efficiency.cxx, PWGLF/STRANGENESS/Lifetimes/selectors/MiniV0efficiency.h, PWGLF/STRANGENESS/PWGLFSTRANGENESSLinkDef.h
Add a flag in order to recognize hypertriton out of 5sigma signal in TPC.
=> Fix compatibility of selector for the latest task version

PWGGA/GammaConv/AliAODConversionPhoton.cxx, PWGGA/GammaConv/AliAnalysisTaskClusterQA.cxx, PWGGA/GammaConv/AliAnalysisTaskClusterQA.h
-- AliAnalysisTaskClusterQA now compatible with AODs
-- fixed warnings
=> PWGGA/GammaConv: AOD modifictaions of AliAnalysisTaskClusterQA

PWGCF/Correlations/macros/AddTaskDiHadCorrelHighPt.C
new parameters to anable to change the names of output file and output container
=> Canges in AddTaskDiHadCorrelHighPt.C

OADB/EMCAL/READMEoadb.txt, PWGGA/GammaConv/AliCaloPhotonCuts.cxx
=> [EMCAL-127,EMCAL-126,EMCAL-191] OADB/EMCAL: Upload of BC for LHC17f + PWGGA/GammaConv: New nonlin EMC pp 5 TeV

PWGCF/FEMTOSCOPY/macros/Train/AddTaskFemtoSubtrains.C
`AddTaskFemtoSubtrains` forwards subtrain parameters to config macros
=> PWGCF: Add macro for train tasks with auto-configured subtrains

PWGCF/FEMTOSCOPY/macros/Train/AddTaskFemtoCommands.C, PWGCF/FEMTOSCOPY/macros/Train/AddTaskFemtoNu.C
* Add macro supporting arbitrary commands 
* Add macro for creating an AliFemtoAnalysisTaskNu analysis
=> PWGCF: Add new LEGO Train "AddTask" macros

PWGUD/DIFFRACTIVE/CEPdevel/AliAnalysisTaskCEP.cxx, PWGUD/DIFFRACTIVE/CEPdevel/CEPTrackBuffer.h
CEPTrackBuffer: updated DCA information and added buffer with ITS modules crossed by the track
=> update of CEPTrackBufferr

PWGDQ/dielectron/LMEE/AliAnalysisTaskSimpleTreeMaker.cxx, PWGDQ/dielectron/macrosLMEE/AddTaskSimpleTreeMaker.C
Minor formatting updates included.
=> Fixes PID correction bug in SimpleTreeMaker AddTask

PWGDQ/reducedTree/AliAnalysisTaskReducedTreeMaker.cxx, PWGDQ/reducedTree/AliReducedAnalysisJpsi2ee.cxx, PWGDQ/reducedTree/AliReducedAnalysisJpsi2ee.h, PWGDQ/reducedTree/AliReducedEventCut.cxx, PWGDQ/reducedTree/AliReducedEventCut.h, PWGDQ/reducedTree/AliReducedEventInfo.cxx, PWGDQ/reducedTree/AliReducedEventInfo.h
and possibility to select on it in AliReducedEventCut
=> PWGDQ/reducedTree: implemented trigger class name to AliReducedEventInfo

PWGCF/Correlations/DPhi/AliAnalysisTaskCorPIDTOFQA.cxx, PWGCF/Correlations/DPhi/AliAnalysisTaskCorPIDTOFQA.h
minimum threshold is 10 GeV cluster, clusterization is from neutral meson standard
=> added new sub-task code, correlates deuterons to EMCal clusters

PWGGA/GammaConv/AliAnalysisTaskGammaCalo.cxx, PWGGA/GammaConv/AliAnalysisTaskGammaCalo.h
Added a MC generated in jets histogram to determine correct acceptance for neutral mesons in jets
=> PWGGA/GammaConv Added a MC generated in jets histogram

PWGHF/treeHF/AliAnalysisTaskSEHFTreeCreator.cxx, PWGHF/treeHF/AliAnalysisTaskSEHFTreeCreator.h, PWGHF/treeHF/AliHFTreeHandlerBplustoD0pi.cxx, PWGHF/treeHF/AliHFTreeHandlerBplustoD0pi.h, PWGHF/treeHF/AliHFTreeHandlerLctopKpi.cxx, PWGHF/treeHF/AliHFTreeHandlerLctopKpi.h, PWGHF/treeHF/CMakeLists.txt, PWGHF/treeHF/PWGHFtreeHFLinkDef.h, PWGHF/treeHF/macros/AddTaskHFTreeCreator.C
- Adding validated Lambdac and Bplus TTreeCreator classes
- Fix error in "run_number" TBranch
=> PWGHF: Add Lc and Bplus + fix TBranch

PWGHF/treeHF/AliAnalysisTaskSEHFTreeCreator.cxx
To fill ntuple with Lc passing filter cuts instead of analysis cuts
=> identify Lc candidates from filtering cuts

PWGHF/vertexingHF/AliAnalysisTaskSELc2V0bachelorTMVAApp.cxx
The changes were mainly done by A. Alici.
=> Removing printout.

CMakeLists.txt, PWGLF/RESONANCES/extra/AliAnalysisTaskXi1530.cxx, PWGLF/RESONANCES/extra/AliAnalysisTaskXi1530.h
Fix MC issue:
- Add Y cut for both injected/reconstructed particle
- Add IsPrimary() check for both MC particles
- Fix CPA default value issue
=> [PWGLF] Fix MC issues: Add Y cut, Add primary cut

PWG/muon/AliPicoDQ.cxx, PWG/muon/AliPicoDQ.h, PWG/muon/AliPicoDQheader.cxx, PWG/muon/AliPicoDQheader.h
Adding files for the Upsilon->2mu analysis
=> Adding files for the Upsilon->2mu analysis

PWGCF/FEMTOSCOPY/AliFemto/AliFemtoModelWeightGeneratorLednicky.cxx, PWGCF/FEMTOSCOPY/AliFemto/AliFemtoModelWeightGeneratorLednicky.h
This refactor increases readability and fixes some bugs in the memory handling of cstring arrays. The behavior should be identical.
=> PWGCF: AliFemtoModelWeightGeneratorLednicky - Refactor for readability

PWGDQ/dielectron/macrosLMEE/AddTask_acapon_Efficiency.C, PWGDQ/dielectron/macrosLMEE/Config_acapon_Efficiency.C, PWGDQ/dielectron/macrosLMEE/LMEECutLib_acaponROOT6.C
Move all analysis options to AddTask arguments for easy toggling.
=> Updates acapon eff. corr. files

PWG/muon/AddTaskMultDQdev.C, PWG/muon/AliAnalysisTaskSEMultDQdev.cxx, PWG/muon/AliAnalysisTaskSEMultDQdev.h
Add task for Upsilon->2mu analysis
=> Add task for Upsilon->2mu analysis

PWGCF/Correlations/JCORRAN/Pro/AliBSDiJetTask.cxx, PWGCF/Correlations/macros/jcorran/AddTaskBSDiJet.C
Randomising of the embedding method improved. Some redundant parts removed.
=> PWGCF/JCORRAN/Pro/AliBSDDijet.*:Randomising of the embedding method improved

PWGHF/vertexingHF/CMakeLists.txt, PWGHF/vertexingHF/ConfigVertexingHF_Pb_AllCent_NoLS_PIDLc_PtDepSel_LcMinpt1_DsMinPt15_2018opt.C, PWGHF/vertexingHF/macros/AddTaskVertexingHF.C
Revisiting filtering cuts for 2018 Pb-Pb data.
=> Revisiting filtering cuts for 2018 Pb-Pb data.

PWGDQ/dielectron/macrosLMEE/Config_acapon_Efficiency.C
MCsignal definition updated to reject conversion electrons.
Additionally, minor changes to histograms bins.
=> Updates acapon eff. calc. signal definition

PWGLF/STRANGENESS/CMakeLists.txt, PWGLF/STRANGENESS/Lifetimes/AliAnalysisTaskFindableHyperTriton.cxx, PWGLF/STRANGENESS/Lifetimes/AliAnalysisTaskFindableHyperTriton.h, PWGLF/STRANGENESS/Lifetimes/macros/AddTaskFindableHyperTriton.cc, PWGLF/STRANGENESS/PWGLFSTRANGENESSLinkDef.h
To be merged in the centralised "findable" framework
=> Draft of findable hypertriton in 3 body task

PWG/EMCAL/EMCALtrigger/AliEmcalTriggerSimQATask.cxx, PWG/EMCAL/EMCALtrigger/AliEmcalTriggerSimQATask.h, PWG/EMCAL/EMCALtrigger/CMakeLists.txt, PWG/EMCAL/EMCALtrigger/PWGEMCALtriggerLinkDef.h, PWG/EMCAL/macros/AddTaskEmcalTriggerSimQA.C
Adds a bare-bones QA task for the trigger simulation, to be improved.
This includes a fix for a compilation error in the previous PR with root 5.
=> Initial EmcalTriggerSimQA task

PWGHF/treeHF/AliAnalysisTaskSEHFTreeCreator.cxx, PWGHF/treeHF/AliAnalysisTaskSEHFTreeCreator.h, PWGHF/treeHF/AliHFTreeHandler.cxx, PWGHF/treeHF/AliHFTreeHandler.h, PWGHF/treeHF/AliHFTreeHandlerBplustoD0pi.cxx, PWGHF/treeHF/AliHFTreeHandlerBplustoD0pi.h, PWGHF/treeHF/AliHFTreeHandlerD0toKpi.cxx, PWGHF/treeHF/AliHFTreeHandlerD0toKpi.h, PWGHF/treeHF/AliHFTreeHandlerDplustoKpipi.cxx, PWGHF/treeHF/AliHFTreeHandlerDplustoKpipi.h, PWGHF/treeHF/AliHFTreeHandlerDstartoKpipi.cxx, PWGHF/treeHF/AliHFTreeHandlerDstartoKpipi.h, PWGHF/treeHF/AliHFTreeHandlerDstoKKpi.cxx, PWGHF/treeHF/AliHFTreeHandlerDstoKKpi.h, PWGHF/treeHF/AliHFTreeHandlerLctopKpi.cxx, PWGHF/treeHF/CMakeLists.txt, PWGHF/treeHF/PWGHFtreeHFLinkDef.h, PWGHF/treeHF/macros/AddTaskHFTreeCreator.C
+ warning fixes
+ updating authors
=> PWGHF: Adding Dstar TTreeCreator

PWGLF/STRANGENESS/Cascades/Run2/AliAnalysisTaskStrEffStudy.cxx, PWGLF/STRANGENESS/Cascades/Run2/AliAnalysisTaskStrEffStudy.h, PWGLF/STRANGENESS/Cascades/Run2/macros/AddTaskStrEffStudy.C
=> Add hypertriton 3 body decay to the common findable trees

RUN3/AliAnalysisTaskAO2Dconverter.cxx, RUN3/AliAnalysisTaskAO2Dconverter.h, RUN3/read.C
- Added example macro to read TTrees (TOF beta vs TPC momentum)
- Added MC information of the track
=> Updated Run3 trees prototype

PWGGA/EMCALTasks/AliAnalysisTaskGammaHadron.cxx, PWGGA/EMCALTasks/AliAnalysisTaskGammaHadron.h, PWGGA/EMCALTasks/macros/AddTaskGammaHadron.C
Adds new Mixed Triggers mode, and trigger pool saving mode.
Small style edits
=> Adds new Mixed Triggers mode, and trigger pool saving mode

PWG/FLOW/Tasks/AliAnalysisTaskCMEV0PID.cxx, PWG/FLOW/Tasks/AliAnalysisTaskCMEV0PID.h
Save Differential Histigrams w.r.t TPC EP
=> Save Differential Histigrams w.r.t TPC EP

PWGJE/EMCALJetTasks/UserTasks/AliAnalysisTaskEmcalJetPerformance.cxx
=> JetPerformance: Determine cell non-linearity for leading cell

PWGJE/FlavourJetTasks/AliAnalysisTaskHFSubstructure.cxx
Not sure why my name appears twice under the commit authors and if this changes anything
=> Fixed AOD Selection Bug

PWGCF/FEMTOSCOPY/AliFemtoUser/AliFemtoCorrFctnQ3D.h, PWGCF/FEMTOSCOPY/macros/Train/PionPionFemto/ConfigNuFemtoAnalysisR6.C
For c++11 supported compilers, enable std::tuple
=> PWGCF: AliFemtoCorrFctnQ3D - Add std::tuple support 

PWG/EMCAL/EMCALbase/AliAnalysisTaskEmcalEmbeddingHelper.cxx, PWG/EMCAL/READMEemcEmbedding.txt, PWGJE/EMCALJetTasks/UserTasks/AliAnalysisTaskEmcalJetHCorrelations.cxx, PWGJE/EMCALJetTasks/UserTasks/AliAnalysisTaskEmcalJetHCorrelations.h, PWGJE/EMCALJetTasks/UserTasks/AliAnalysisTaskEmcalJetHPerformance.cxx, PWGJE/EMCALJetTasks/UserTasks/AliAnalysisTaskEmcalJetHPerformance.h, PWGJE/EMCALJetTasks/UserTasks/AliAnalysisTaskEmcalJetHUtils.cxx, PWGJE/EMCALJetTasks/UserTasks/AliAnalysisTaskEmcalJetHUtils.h
Variety of changes accumulated over late last year
=> Jet-hadron updates, other minor docs improvements

TENDER/TenderSupplies/AliPHOSTenderSupply.cxx
Another parameterization for Run2 data
=> Run2Tune parameterization added

PWGJE/EMCALJetTasks/UserTasks/AliAnalysisTaskEmcalJetHCorrelations.cxx, PWGJE/EMCALJetTasks/UserTasks/AliAnalysisTaskEmcalJetHCorrelations.h, PWGJE/EMCALJetTasks/UserTasks/AliAnalysisTaskEmcalJetHPerformance.cxx, PWGJE/EMCALJetTasks/UserTasks/AliAnalysisTaskEmcalJetHUtils.cxx
Also add some utility functions
=> Bug fixes for event selection

PWGJE/EMCALJetTasks/UserTasks/AliAnalysisTaskEmcalJetHUtils.cxx
=> Fix typo in configuration

PWGLF/STRANGENESS/Lifetimes/AliAnalysisTaskStrangenessLifetimes.cxx, PWGLF/STRANGENESS/Lifetimes/AliAnalysisTaskStrangenessLifetimes.h, PWGLF/STRANGENESS/Lifetimes/HyperTriton2Body.h, PWGLF/STRANGENESS/Lifetimes/MiniEvent.h, PWGLF/STRANGENESS/PWGLFSTRANGENESSLinkDef.h
Add new structure in AliAnalysisStrangenessLifetimes in order to recognize each event
=> Add new structure to Task of Strangeness

PWGCF/FEMTOSCOPY/AliFemto/AliFemtoConfigObject.h, PWGCF/FEMTOSCOPY/AliFemto/AliFemtoEventReaderESD.cxx, PWGCF/FEMTOSCOPY/AliFemto/AliFemtoEventReaderESD.h, PWGCF/FEMTOSCOPY/AliFemto/AliFemtoEventReaderESDChain.cxx, PWGCF/FEMTOSCOPY/AliFemto/AliFemtoEventReaderESDChain.h, PWGCF/FEMTOSCOPY/AliFemtoUser/AliFemtoCorrFctnDirectYlm.cxx, PWGCF/FEMTOSCOPY/AliFemtoUser/AliFemtoCorrFctnDirectYlm.h
Update formatting & fix some potential memory leaks
=> PWGCF: Add miscellaneous improvements

PWGCF/Correlations/DPhi/AliAnalysisTaskDiHadCorrelHighPt.cxx
changed deleteting a TClonesArray in a proper way
=> Change in AliAnalysisTaskDiHadCorrelHighPt.cxx

PWGJE/EMCALJetTasks/AliAnalysisTaskRhoSparse.cxx
@fkrizek that should fix the problem
=> Fix error in TotalAreaCovered calculation

PWGHF/jetsHF/AliAnalysisTaskBJetTC.cxx
Changing the DeltaPt binnings and range.
=> Changing the binnings of the DeltaPt

PWGGA/GammaConv/macros/AddTask_GammaConvV1_pp.C
adding new config to compare yields
=> PWGGA: Add PCM Cfg 302 with same cuts as in PCM-PHOS for 13TeV

PWGLF/STRANGENESS/Lifetimes/AliAnalysisTaskStrangenessLifetimes.cxx, PWGLF/STRANGENESS/Lifetimes/AliAnalysisTaskStrangenessLifetimes.h, PWGLF/STRANGENESS/Lifetimes/HyperTriton2Body.h, PWGLF/STRANGENESS/Lifetimes/MiniV0.h
Add boolean in order to separate signal from background for Hypertriton
=> Add boolean for background analysis

PWG/EMCAL/EMCALbase/AliAnalysisTaskEmcal.cxx
These messages are overwhelming other debug messages, so we set them to
a lower priority.
@mfasDa Are you okay with this minor change? At the current level, I'm finding it rather difficult to debug my task
=> Quiet down debug messages

PWGJE/EMCALJetTasks/UserTasks/AliAnalysisTaskEmcalJetHPerformance.cxx
Only add the cell QA when embedding
=> Be more selective when to add histogram

PWGCF/FEMTOSCOPY/AliFemtoUser/AliFemtoModelCorrFctnTrueQ3D.cxx, PWGCF/FEMTOSCOPY/AliFemtoUser/AliFemtoModelCorrFctnTrueQ3D.h
Add histograms with alternative weights for better statistics
=> AliFemtoModelCorrFctnTrueQ3D - Add alt-weighted histograms

PWGJE/EMCALJetTasks/macros/EmbeddingConfigurationExample.yaml, PWGJE/EMCALJetTasks/macros/runEmbeddingAnalysis.C
Update to include some of the newer features
=> Updates to the embedding sample run macro

PWGCF/FEMTOSCOPY/macros/AddTaskSigma0Femto.C, PWGGA/Hyperon/AliSigma0PhotonMotherCuts.cxx, PWGGA/Hyperon/AliSigma0PhotonMotherCuts.h
o Reduce amount of allocated histograms
o Reduce systematic variations
=> Optimization of the systematics

PWGDQ/dielectron/CMakeLists.txt, PWGDQ/dielectron/LMEE/AliAnalysisTaskBeauty.cxx, PWGDQ/dielectron/LMEE/AliAnalysisTaskBeauty.h, PWGDQ/dielectron/LMEE/AliAnalysisTaskCharm.cxx, PWGDQ/dielectron/LMEE/AliAnalysisTaskCharm.h, PWGDQ/dielectron/LMEE/AliCocktailSmearing.cxx, PWGDQ/dielectron/LMEE/AliCocktailSmearing.h, PWGDQ/dielectron/PWGDQdielectronLinkDef.h, PWGDQ/dielectron/macrosLMEE/AddTaskBeauty.C, PWGDQ/dielectron/macrosLMEE/AddTaskCharm.C
First porting of the analysis task for heavy-flavour dielectron cocktail
=> Analysis task for Heavy-flavour cocktail

PWGCF/FEMTOSCOPY/AliFemtoUser/AliFemtoCorrFctnQ3D.h, PWGCF/FEMTOSCOPY/AliFemtoUser/AliFemtoModelCorrFctnTrueQ3D.cxx
* Minor updates to reduce output file size (after compression)
=> PWGCF: AnalysisFemtoPionPion

PWGHF/vertexingHF/AliAnalysisTaskSEDStarSpectra.cxx, PWGHF/vertexingHF/AliAnalysisVertexingHF.cxx, PWGHF/vertexingHF/AliAnalysisVertexingHF.h, PWGHF/vertexingHF/AliRDHFCutsDStartoKpipi.cxx, PWGHF/vertexingHF/AliRDHFCutsDStartoKpipi.h, PWGHF/vertexingHF/AliRDHFCutsDstoKKpi.cxx
The GetProngDstar() function in AliAnalysisVertexingHF might get merged with the GetProng() at a later stage
=> PWGHF: Add PreSelect function for PbPb2018 for Dstar

PWGHF/hfe/macros/configs/PbPb/userConfigurationEMCele_PbPb_MC.yaml, PWGHF/hfe/macros/configs/pp/userConfigurationEMCele_pp_pPb_MC.yaml
example yaml file for configuring EMCal correction tasks for MC
=> yaml file for EMCal electron analysis, MC 

PWGJE/EMCALJetTasks/macros/JetQA/scalePtHardHistos.py
@jdmulligan this should fix the PYTHIA error.
=> fix correct bin for event normalization

PWGGA/GammaConv/AliAnalysisTaskConvJet.cxx, PWGGA/GammaConv/AliAnalysisTaskConvJet.h
Improved the class so that the number of true jet containers is a global variable instead of going over the total number of containers which is a combination of rec and true containers in MC
Furthermore improved it that two Trainconfigs with the same jetfinder can also run alongside now
=> PWGGA/GammaConv Improvement of ConvJet class

PWGJE/EMCALJetTasks/Tracks/AliAnalysisTaskEmcalJetEnergyScale.cxx
Allowing for feed down to lower det-level jet pt
in the range covered by the jet trigger.
=> Increase jet pt range to 300 GeV/c

PWGDQ/dielectron/macrosLMEE/AddTask_acapon_Efficiency.C, PWGDQ/dielectron/macrosLMEE/Config_acapon.C, PWGDQ/dielectron/macrosLMEE/Config_acapon_Efficiency.C, PWGDQ/dielectron/macrosLMEE/LMEECutLib_acapon.C
Cut set to mimic the traditional cuts used in Run 1.
Also, MVA PID cut variation (20 cuts) finally implemented.
=> Implement standard PID cuts (acapon_LMEE)

PWGJE/EMCALJetTasks/UserTasks/AliAnalysisTaskJetCoreEmcal.cxx, PWGJE/EMCALJetTasks/UserTasks/AliAnalysisTaskJetCoreEmcal.h, PWGJE/EMCALJetTasks/macros/AddTaskJetCoreEmcal.C
add option to run h+jet analysis using both Pb-Pb and embedded particle containers
=> update to run embedded correlation

PWGCF/EBYE/IdentityMethodEbyeFluctuations/macros/AddTask_marsland_EbyeIterPID.C, PWGCF/EBYE/IdentityMethodEbyeFluctuations/macros/Config_marsland_EbyeIterPID.C, PWGCF/EBYE/IdentityMethodEbyeFluctuations/tasks/AliAnalysisTaskEbyeIterPID.cxx, PWGCF/EBYE/IdentityMethodEbyeFluctuations/tasks/AliAnalysisTaskEbyeIterPID.h
=> PWGCF-110: Major change which includes net particle calculations

PWGDQ/dielectron/macrosLMEE/AddTask_acapon_Efficiency.C, PWGDQ/dielectron/macrosLMEE/LMEECutLib_acapon.C
New classifier uses pion nSigma from the TPC.
Increased classifier cut from 0.1 to 0.15
=> Switch to new classifier (acapon_LMEE)

PWGCF/FEMTOSCOPY/FemtoDream/AliAnalysisTaskSigma0Femto.cxx, PWGCF/FEMTOSCOPY/FemtoDream/AliAnalysisTaskSigma0Femto.h, PWGCF/FEMTOSCOPY/macros/AddTaskSigma0DebugTest.C, PWGCF/FEMTOSCOPY/macros/AddTaskSigma0Femto.C
o Use global tracks instead of TPConly for the protons
o Further improvements for memory handling
o Further tests
=> Update for p-Sigma0 femto
