- PWGGA/EMCALTasks/AliAnalysisTaskGammaHadron.cxx
- PWGGA/EMCALTasks/AliAnalysisTaskGammaHadron.h
Modifies MC Status information to use a better classification method involving the Lowest Common Ancestor of the two clusters.
Also adds flag to select only main EMCal or only DCal.
> MCStatus with LCA and EMCal/DCal flag

- PWGPP/ITS/AliAnalysisTaskITSTrackingCheck.cxx
- PWGPP/ITS/AliAnalysisTaskITSsaTracks.cxx
- PWGPP/TRD/AliTRDinfoGen.cxx
In case a MC track for dummy label (3151493) was requested, the
AliMCEvent will return 0 pointer. Protection is added for this case
> Allow NULL pointer for MCEvent->GetTrack()/Particle()

- PWGPP/EMCAL/AliAnalysisTaskEMCALClusterize.cxx
- PWGPP/EMCAL/AliAnalysisTaskEMCALClusterize.h
> allow very low cell energies to leak in order to try to match beam

- PWGGA/GammaConv/AliAnalysisTaskGammaCaloMerged.cxx
- PWGGA/GammaConv/AliCaloPhotonCuts.cxx
- PWGGA/GammaConv/AliCaloPhotonCuts.h
- PWGGA/GammaConv/macros/AddTask_GammaCaloMerged_pp.C
new: CaloMerged task gives JJ weights & mcEvent to MatchTracksToCluster
introducing EOverP veto in track matching, so that jets (charged tracks with large E/p) are not matched away
new histos for data & mc:
- TH2 trackP vs clusterE for track matches
- TH2 trackP vs clusterE for track matches after EOverP veto
for mc only:
- TH1 true pi0 cluster spectrum before/after track matching
- TH2 trackP vs clusterE for track matches in case of cluster = true pi0 cluster
TM cuts ("c",...,"h") for different values of allowed maxEOverP(999.9, 3., 2., 1.75, 1.5, 1.25); took dEta,dPhi cuts from default case "7"
mEMC addtask: took configs "17x" for EOverP cut studies in 8TeV pp
modified: only one eta-phi map of electron clusters before/after TM, instead of three and now only for high pt, for less memory …
> PWGGA/GammaConv introducing EOverP cut in TM

- PWG/Cocktail/macros/AddMCEMCocktailV2.C
- PWGGA/GammaConv/AliAnalysisTaskGammaCocktailMC.cxx
- PWGGA/GammaConv/AliAnalysisTaskGammaCocktailMC.h
- PWGGA/GammaConv/AliAnalysisTaskHadronicCocktailMC.cxx
- PWGGA/GammaConv/AliAnalysisTaskHadronicCocktailMC.h
- PWGGA/GammaConv/macros/AddTask_GammaCocktailMC.C
- PWGGA/GammaConv/macros/AddTask_HadronicCocktailMC.C
Added the possibility to generate the cocktail particles in user defined rapidity range (default is still |y|<1)
Added the possibility to cut differently on photons and hadrons. For this, an eta cut has been added which is applied when it is set via the last argument of the AddTask. 
For example, AddTask_GammaCocktailMC(kFALSE,"80_90"); will apply a cut of  |y|<0.8 on hadrons and |eta|<0.9 on photons. This feature is now implemented for GammaCocktail and HadronicCocktail.
If the same cut on photons and hadrons should be used, then for example "80_80" and "80" would result in the same output.
> PWG/Cocktail: added cocktail feature for wider y range and eta gamma cut

- PWG/EMCAL/EMCALtasks/AliEmcalCorrectionTask.cxx
- PWG/Tools/AliYAMLConfiguration.h
If values are retrieved in the order that the configuration files are
added, then it is impossible to override a value after a file has been
added. Instead, we now look in reverse order of the way they were added,
so a value can be overridden just be adding a new config file.
It's been tested and validated with some unit tests and the EMCal Correction Framework.
> Reverse order of retrieving values from config

- PWGHF/vertexingHF/AliAnalysisTaskSELambdac.cxx
Function used to ID Lc->pKpi was missing a small fraction of Lc when running over MC. Changed to be compatible with correct implementation in CF task and TMVA task.
> fix Lc MC ID

- PWGGA/GammaConv/AliCaloTrackMatcher.cxx
This fixes a strange situation where for the first event the trackmatcher cannot find the calocluster container.
Running with this fix or alternatively the tender results in the same cluster candidates. Therefore this small addition does not have negative impact on the result.
> PWGGA/GammaConv: Fix for trackmatcher when using correction framework

- PWGCF/Correlations/JCORRAN/Pro/AliBSDiJetTask.cxx
Hi,
this PR is needed to avoind that the AliPhyssics compilation fails in AliBSDiJetTask.cxx after this commit:
https://github.com/alisw/AliPhysics/commit/b024292e81927dae2cfdc988415dc023b30a0f41
I just added const in front of the TLorentzVectors passed to std::sort, to prevent this compilation error:
/home/prino/AliSoft/sw/SOURCES/AliPhysics/0/0/PWGCF/Correlations/JCORRAN/Pro/AliBSDiJetTask.cxx:510:93: note:   no known conversion for argument 2 from ‘const TLorentzVector’ to ‘TLorentzVector&’
Best regards, Francesco
> Fix compilation error

- PWGCF/Correlations/JCORRAN/Pro/PWGCFCorrelationsJCORRANProLinkDef.h
A compilation error occurs when building with root5 but without the Fastjet package. This fix solves the problem.
> Fixed a compilation error related to Fastjet.

- PWG/CaloTrackCorrBase/AliAnaCaloTrackCorrBaseClass.cxx
- PWG/CaloTrackCorrBase/AliAnaCaloTrackCorrBaseClass.h
- PWG/CaloTrackCorrBase/AliAnaCaloTrackCorrMaker.cxx
- PWG/CaloTrackCorrBase/AliCaloTrackReader.cxx
- PWG/CaloTrackCorrBase/AliCaloTrackReader.h
- PWGGA/CaloTrackCorrelations/macros/AddTaskCaloTrackCorr.C
- PWGGA/CaloTrackCorrelations/macros/AddTaskCaloTrackCorrBase.C
- PWGGA/CaloTrackCorrelations/macros/AddTaskClusterShape.C
- PWGGA/CaloTrackCorrelations/macros/AddTaskGammaHadronCorrelation.C
- PWGGA/CaloTrackCorrelations/macros/AddTaskGammaJetCorrelation.C
- PWGGA/CaloTrackCorrelations/macros/AddTaskIsoPhoton.C
- PWGGA/CaloTrackCorrelations/macros/AddTaskMergedPi0Selection.C
- PWGGA/CaloTrackCorrelations/macros/AddTaskPi0.C
- PWGGA/CaloTrackCorrelations/macros/ConfigureCaloTrackCorrAnalysis.C
Move the initialization of this object from the sub-tasks base class to the reader class so that it can be accessed by all subtasks
> Create the AliMCAnalysisUtils only once for all sub-tasks

- OADB/EMCAL/READMEoadb.txt
The following runs are now also covered by the LHC17l time calibration:
277079, 277076, 277073, 277037, 277017, 277016, 277015, 276972, 276971, 276970, 276969, 276967, 276920, 276917, 276916, 276762, 276675, 276674, 276672, 276671, 276670, 276644, 276608, 276557, 276556, 276553, 276552
> [EMCAL-103] OADB/EMCAL: Update of LHC17l time calibration with increased run range

- PWG/EMCAL/EMCALtasks/AliEmcalCorrectionCellEmulateCrosstalk.cxx
- PWG/EMCAL/EMCALtasks/AliEmcalCorrectionCellEmulateCrosstalk.h
- PWG/EMCAL/config/AliEmcalCorrectionConfiguration.yaml
- PWGGA/CaloTrackCorrelations/yaml/EMCalCorrConfig_MC_Run1_ClV1_xTalk_ECellCut.yaml
- PWGGA/CaloTrackCorrelations/yaml/EMCalCorrConfig_MC_Run1_ClV1_xTalk_ECellCut_Leak5MeV.yaml
set as default the limit on the induced leak at 50 MeV, like the default clusterization cut.
If one uses higher clusterization cuts, it has to be changed.
The calculation of the induced energy has been simplified, all is done by a single method for each of the correlated cells instead of replicating the lines for each correlated cell.
Update also the yaml files for the new cuts. In the PWGGA/CaloTrackCorrelations/yaml directory 3 yaml files with the cases: same as before, with the limit at the clusterization cell E cut, and adding the low energy leaks. For the particular case of V1 clusters and 100 MeV cell energy cut.
> introduce new cuts to restrict or open the induced energy leaks

- PWGJE/EMCALJetTasks/AliEmcalJetTask.cxx
- PWGJE/EMCALJetTasks/AliEmcalJetTask.h
See PR #5541 and #5584. This commit fixes the ROOT5 issue by switching the TF1 back to using pointers. It was tested in both ROOT5 and ROOT6, and verified to agree in all cases. As before the feature is off by default.
The use of gRandom was also discontinued here, as discussed in 5541.
> Fix ROOT5 issue with pT-depedent artificial tracking efficiency

- PWGHF/vertexingHF/AliCFTaskVertexingHF.cxx
- PWGHF/vertexingHF/AliCFTaskVertexingHF.h
- PWGHF/vertexingHF/AliCFVertexingHF.cxx
- PWGHF/vertexingHF/AliCFVertexingHF.h
- PWGHF/vertexingHF/AliCFVertexingHF2Prong.cxx
- PWGHF/vertexingHF/AliCFVertexingHF3Prong.cxx
- PWGHF/vertexingHF/AliCFVertexingHFCascade.cxx
- PWGHF/vertexingHF/macros/AddTaskCFVertexingHF.C
- PWGHF/vertexingHF/macros/AddTaskCFVertexingHF3Prong.C
- PWGHF/vertexingHF/macros/AddTaskCFVertexingHFCascade.C
Added configuration to CF for D0, D+ and D*+ for the ESE analysis, with pt, y, centrality, multiplicity, local multiplicity and q2 axes. The local multiplicity is defined as the number of tracks passing FilterBit 8||9 with DeltaEta<0.1 and DeltaPhi<0.1 wrt the D meson. The q2 is computed using TPC tracks with 0.2<pt<5 GeV/c, |eta|<0.8 and FilterBit 8||9.
> Added configuration to CF for D0, D+ and D*+ ESE analysis

- PWGGA/GammaConv/AliConvEventCuts.cxx
- PWGGA/GammaConv/AliConvEventCuts.h
- PWGGA/GammaConv/macros/AddTask_GammaConvV1_PbPb.C
add possibility for PbPb to apply V0M-TPC pileup cut without applying pp pileup cuts using SPD
change range of spd plot according to values in AliAnalysisTaskGammaConvV1
> AliConvEventCuts: modify pileup cuts and spd plot

- OADB/EMCAL/READMEoadb.txt
The following runs are now covered by individual bc maps:
285978, 285979, 285980, 286014, 286018, 286025, 286026, 286027, 286030, 286064, 286124, 286127, 286129, 286130, 286154, 286157, 286159, 286198, 286201, 286202, 286203, 286229, 286230, 286231, 286254, 286255, 286256, 286257, 286258, 286261, 286263, 286282, 286284, 286287, 286288, 286289, 286308, 286309, 286310, 286311, 286312, 286313, 286314, 286336, 286337, 286340, 286341, 286345, 286348, 286349, 286350
> [EMCAL-205] OADB/EMCAL: Upload of runwise bad channel maps for LHC18d

- PWGPP/TRD/TRDPID/AliTRDPIDTree.cxx
- PWGPP/TRD/TRDPID/AliTRDPIDTree.h
Test pile-up cut taken from AliAnalysisTaskBFPsi.cxx on correlation of multiplicity of VZERO detector and the number of TPCout tracks.
> PWGPP/TRDPID: AliTRDPIDTree: add further pile-up cut

- PWG/EMCAL/config/AliEmcalCorrectionConfiguration.yaml
- PWGGA/CaloTrackCorrelations/yaml/EMCalCorrConfig_MC_Run1_ClV1_xTalk.yaml
- PWGGA/CaloTrackCorrelations/yaml/EMCalCorrConfig_MC_Run1_ClV1_xTalk_ECellCut.yaml
- PWGGA/CaloTrackCorrelations/yaml/EMCalCorrConfig_MC_Run1_ClV1_xTalk_ECellCut_Leak5MeV.yaml
After observations in presentation at
[EMCal meeting 21/06/2017](https://indico.cern.ch/event/725637/contributions/3048520/attachments/1671746/2682062/CrossTalkUpdate_Linearity_InvMass_pp7TeV_EMCALMeeting210618.pdf)
slides 38 and 42
> change xTalk parameters for SM10 and SM11, they behave quite like SM1

- PWGDQ/reducedTree/AliAnalysisTaskReducedTreeMaker.cxx
- PWGDQ/reducedTree/AliAnalysisTaskReducedTreeMaker.h
- PWGDQ/reducedTree/AliReducedEventCut.h
- PWGDQ/reducedTree/AliReducedEventInfo.cxx
- PWGDQ/reducedTree/AliReducedEventInfo.h
- PWGHF/correlationHF/macros/DrawDhCorr_STE_3DEfficiency_in_pTEtaZvtx_AllSpeciesInOne.C
1) In AliReducedEventInfo i added 2 data members for the online trigger mask and trigger mask Next50
2) The tree maker was updated to make more user friendly the way we select events for writing in the trees. Insted of 
treeMaker->SetWriteEventsWithNoSelectedTracks(Bool_t, scaleDown, minTracks);
treeMaker->SetWriteEventsWithNoSelectedTracksAndNoSelectedAssociatedTracks(Bool_t);
now the user can specify just:
treeMaker->SetEventWritingRequirement(minTracks,minTracks2,scale down);
where the minimum numbers of tracks in both tracks arrays need to be specified together with a scale down factor in case one wants to write also a sample of unbiased events.
> New data members in the event definition and an update in the tree maker

- PWGJE/EMCALJetTasks/UserTasks/AliAnalysisTaskJetCoreEmcal.cxx
- PWGJE/EMCALJetTasks/UserTasks/AliAnalysisTaskJetCoreEmcal.h
- PWGJE/EMCALJetTasks/macros/AddTaskJetCoreEmcal.C
MC and embedding functionality. Running with the embedding framework allows to match detector level embedded and true jets, and fill response (histograms and trees) for both recoil and inclusive jets. Aim is to 2d unfold the pT/DeltaPhi distribution
> MC and Embedding functionality added, for inclusive and recoil response

- PWGCF/Correlations/macros/jcorran/AddTaskJCDijetTask.C
Giving a vector as an argument had troubles with root5 so I changed the argument to a TString which is then parsed to a vector. Also added checks for the centrality bin vector so that it is properly set.
> Fixed a compatibility problem with root5 in macro.

- PWG/EMCAL/EMCALbase/AliAnalysisTaskEmcal.cxx
- PWG/EMCAL/EMCALbase/AliAnalysisTaskEmcal.h
Tasks inheriting from AliAnalysisTaskEmcal can
reimplement the function IsTriggerSelected to have a
custom trigger selection applied during the event
selection. The default implementation of the function
is identical to the previous trigger selection part in the
IsEventSelected function in order to guarantee backward
compatibility. Custom trigger selection is in particular
necessary for the EMCAL triggers when calculating the
vertex efficiency.
> Add support for virtual trigger selection

- PWGCF/FEMTOSCOPY/AliFemtoUser/AliFemtoModelCorrFctnTrueQ6D.h
- PWGCF/FEMTOSCOPY/AliFemtoUser/PWGCFfemtoscopyUserLinkDef.h
* AliFemtoModelCorrFctnTrueQ6D::Builder added to the LinkDef.h
* Builder can now set Q{out,side,long}Range values with a double[2] paramter.
* Change default binning method to kGenLSORecOSL
> PWGCF: Link AliFemtoModelCorrFctnTrueQ6D::Builder & change a default

- PWGDQ/reducedTree/macros/attic/XeXe2017/AddTask_iarsene_dst.C
- PWGDQ/reducedTree/macros/attic/XeXe2017/AddTask_iarsene_jpsi2ee_XeXe.C
- PWGDQ/reducedTree/macros/attic/XeXe2017/AddTask_iarsene_testTask.C
- PWGDQ/reducedTree/macros/attic/XeXe2017/JpsiRaa_XeXe_sigExtr.C
A new directory was created in PWGDQ/reducedTree/attic which will hold macros used for past analyses.
The directory PWGDQ/reducedTree/attic/XeXe2017/ contains the analysis macros used in the J/psi Raa analysis of the XeXe 2017 data. This directory is referenced in the corresponding analysis note.
> Added macros used for the Jpsi Raa analysis of the 2017 Xe-Xe data

- PWGJE/EMCALJetTasks/UserTasks/AliAnalysisTaskEmcalJetPerformance.cxx
- PWGJE/EMCALJetTasks/UserTasks/AliAnalysisTaskEmcalJetPerformance.h
Update to my user task.
The purpose is to allow the jet pT to go negative due to background fluctuation, since we may want to consider these jets in the unfolding.
> JetPerformance: Let min pT in jet histograms be configurable

- PWG/FLOW/Tasks/AliAnalysisTaskTwoMultiCorrelations.cxx
Coding mistakes introduced in #5874:
a) Usage of int and double in complex multiplication raising
ambiguity in the operator * from TComplex due to implicit
casting of int, an explicit cast to double is necessary in
order to force double precision calculation.
b) C-array must not be used with non-constant array sizes, this
introduces undefined behavior and several modern compilers
treat this as error. std::vector is the appropriate structure
for dynamic arrays.
> Fix coding mistakes preventing compilation under ROOT6/clang

- PWG/EMCAL/EMCALtasks/AliEmcalTrackingQATask.cxx
- PWG/EMCAL/EMCALtasks/AliEmcalTrackingQATask.h
- PWG/EMCAL/macros/AddTaskTrackingQA.C
This is in particular of relevance for running the tracking
QA task on EMCAL triggered events where one wants
to study the 4 EMCAL triggers in parallel.
> [PWGPP-429] Prepare PWGJE tracking QA task for subwagons

- PWGPP/macros/MakeTrendingPIDQA.C
Using ROOT6, the macro MakeTrendingPIDQA.C gave some errors related to the output tree:
`Error in <TBranch::TBranch::WriteBasketImpl>: basket's WriteBuffer failed`.
Creating the output file before the output tree solved the problem.
> Make PIDqa macro compatible with ROOT6

- PWGUD/DIFFRACTIVE/CEPdevel/AliAnalysisTaskCEP.cxx
- PWGUD/DIFFRACTIVE/CEPdevel/RawBuffers/CEPRawCaloClusterTrack.cxx
- PWGUD/DIFFRACTIVE/CEPdevel/RawBuffers/CEPRawCaloClusterTrack.h
- PWGUD/DIFFRACTIVE/CEPdevel/RawBuffers/CEPRawEventBuffer.cxx
- PWGUD/DIFFRACTIVE/CEPdevel/RawBuffers/CEPRawEventBuffer.h
CEPRawBuffer was updadet with EMCal informtion which allows to veto on events with a gamma measured in the EMCal and thus to refine the DoubleGap event selection.
> Updated CEPRawBuffers with veto information based on EMCal data

- PWG/EMCAL/EMCALbase/AliAnalysisTaskEmcalLight.cxx
If EXACT is found in the trigger string then the full trigger
string must be equal to the requested trigger string, and
not only a substring (find). This is in particular necessry
to reject events which triggers only CENTNOTRD and
not CENT.
> Allow checking the exact trigger string

- PWGHF/vertexingHF/AliAnalysisTaskSEDStarCharmFraction.cxx
Pointer was empty with cand->GetOwnPrimaryVtx(), so didn't pass if statement. Now getting primary vertex from AOD
> Fix empty pointer PrimaryVertex

- OADB/EMCAL/READMEoadb.txt
The following runs now have new or updated maps:
286129, 286130, 286254, 286261, 286284, 286287, 286288, 286289, 286309, 286310, 286311, 286313, 286314, 286341, 286349, 286350
> [EMCAL-204] OADB/EMCAL: Uploaded missing bad channel calibs for LHC18d

- PWG/EMCAL/EMCALbase/AliAnalysisTaskEmcalLight.cxx
- PWG/EMCAL/EMCALbase/AliAnalysisTaskEmcalLight.h
PythiaInfoFromFile was modified in AliAnalysisTaskEmcal
in order to add support for new Jet-Jet Monte-Carlos,
while AliAnalysisTaskEmcalLight still kept the old version.
Modifications contain:
-  Proper determination of  the pt-hard bin for new
dataset:
+ Old version: Fixed position in string
+ New version: Pattern matching
- Use cross section from header in case it was not found
in the pythia file
- Add support for lego train test:  Name of the test
directory file directory encodes the full path on alien
of the test file. This string, if present, is taken as
virtual file name (default regular file name), and the
virtual file name is always used for the determination of
the pt-hard bin.
> Back-port PythiaInfoFromFile from AliAnalysisTaskEmcal

- PWGUD/UPC/AliAnalysisTaskUpcEtaC.cxx
Simple logic change for requiring one ZDC with Energy <= 1500 and other with 1500 < Energy <=11500.
> Changed to logic for 0nXn + Xn0n for ZDC study

- PWGDQ/dielectron/LMEE/AliAnalysisTaskSimpleTreeMaker.cxx
- PWGDQ/dielectron/LMEE/AliAnalysisTaskSimpleTreeMaker.h
- PWGDQ/dielectron/macrosLMEE/Config_acapon.C
- PWGDQ/dielectron/macrosLMEE/LMEECutLib_acapon.C
SimpleTreeMaker class updated to use LMEEcutLib files when implementing cuts.
Additional changes: 
-One now specifies both the desired track and PID cuts when calling GetTrackCuts(trackCuts, PIDcuts).  This function now implements or loads all necessary track+PID cuts, so only one function call is needed in the AddTask.
- The generator TTreeMaker implementation has been removed (redundant)
- Minor formatting and spelling corrections
> TTreeMaker to now uses Dielectron Cut Libraries

- PWGDQ/dielectron/LMEE/AliAnalysisTaskSimpleTreeMaker.cxx
- PWGDQ/dielectron/LMEE/AliAnalysisTaskSimpleTreeMaker.h
- PWGDQ/dielectron/macrosLMEE/AddTaskSimpleTreeMaker.C
- PWGDQ/dielectron/macrosLMEE/AddTask_acapon.C
- PWGDQ/dielectron/macrosLMEE/Config_acapon.C
- PWGDQ/dielectron/macrosLMEE/LMEECutLib_acapon.C
The ability to use the TPC post calibration is now implemented for both the SimpleTreeMaker, as
well as for the attached Config file. 
All necessary AddTask files were also updated to accommodate the changes.
> TPC post calibration for TTreeMaker and Dielectron config implemented

- PWGHF/vertexingHF/AliAnalysisTaskTrackingSysPropagation.cxx
- PWGHF/vertexingHF/AliRDHFCuts.cxx
- PWGHF/vertexingHF/AliRDHFCuts.h
- PWGHF/vertexingHF/AliRDHFCutsDStartoKpipi.cxx
- PWGHF/vertexingHF/AliRDHFCutsDStartoKpipi.h
As discussed in the D2H of 10/07/18, the implementation of the new strategies to estimate the tracking efficiency systematic for Dstar.
1) ITS-TPC matching: Deleted the contribution from the soft pion, as it is not prolonged from TPC to ITS.
2) Track quality: Added a flag to be able to estimate the effect of TPC track quality variations separately for the soft pion and the D0 daughters.
> PWGHF: Updated strategy for tracking eff systematic for Dstar

- PWG/DevNanoAOD/AliNanoAODTrack.h
- PWG/EMCAL/EMCALbase/AliPicoTrack.h
- PWGCF/Correlations/DPhi/DiHadronPID/AliTrackDiHadronPID.h
- PWGCF/Correlations/JCORRAN/Base/AliJBaseTrack.h
- PWGCF/Correlations/ThreePart/AliFilteredTrack.h
- PWGCF/FEMTOSCOPY/AliFemtoUser/AliFemtoESDTrackCut.h
- PWGHF/correlationHF/AliAnalysisTaskSEHFCJqa.cxx
- PWGHF/jetsHF/AliAnalysisTaskEmcalHFCJQA.cxx
- PWGLF/SPECTRA/PiKaPr/TOF/PbPb276/libs/AliAnalysisTrack.h
- PWGLF/SPECTRA/PiKaPr/TPCTOFfits/AliAnalysisPIDTrack.h
Since the bit mask of AliESDtrack needs to use >32 bits, all getters and setters of Alice track type
(starting from AliVParticle) status (GetStatus, SetStatus) are returning/acceptring ULong64_t instead
of ULong_t
> All track types status getters/setters use ULong64_t

- PWGJE/EMCALJetTasks/UserTasks/AliAnalysisTaskEmcalJetPerformance.cxx
- PWGJE/EMCALJetTasks/UserTasks/AliAnalysisTaskEmcalJetPerformance.h
(without mc fraction requirement)
Update to my user task.
> JetPerformance: allow to use jettagger for geometrical matching

- PWGCF/EBYE/PWGCFebyeLinkDef.h
- PWGCF/FEMTOSCOPY/AliFemto/PWGCFfemtoscopyLinkDef.h
- PWGCF/FEMTOSCOPY/UNICOR/PWGCFunicorLinkDef.h
- PWGCF/FEMTOSCOPYAOD/PWGCFFEMTOSCOPYAODLinkDef.h
- PWGLF/NUCLEX/PWGLFnuclexLinkDef.h
- PWGLF/QATasks/PWGLFQATasksLinkDef.h
- PWGLF/STRANGENESS/PWGLFSTRANGENESSLinkDef.h
- PWGPP/EVCHAR/FlowVectorCorrections/QnCorrectionsInterface/PWGPPevcharQnInterfaceLinkDef.h
- PWGPP/EVCHAR/PWGPPevcharLinkDef.h
- PWGPP/MUON/dep/PWGPPMUONdepLinkDef.h
- PWGPP/MUON/lite/PWGPPMUONliteLinkDef.h
- PWGPP/PWGPPLinkDef.h
- PWGPP/pid/PWGPPpidLinkDef.h
- PWGUD/DIFFRACTIVE/PWGUDdiffractiveLinkDef.h
- PWGUD/UPC/PWGUDupcLinkDef.h
Apparently by copy and pasting from the PWGPPLinkDef many PWG in their
LinkDef have a typo. "glols" is not a supported keyword in the
LinkDef.h, see for reference https://root.cern.ch/root/html534/guides/users-guide/AddingaClass.html
> Fix global globals typo

- PWGPP/ITS/AliMeanVertexPreprocessorOffline.cxx
Introducing per run estimate of the mean multiplicity used in low multiplicity pp collisions to extract the luminous region parameters from the fits to the vertex coordinates distributions (x and y).
> introducing usage of run dependent mean multiplicity

- PWG/CaloTrackCorrBase/AliCalorimeterUtils.cxx
- PWG/CaloTrackCorrBase/AliCalorimeterUtils.h
- PWG/CaloTrackCorrBase/AliIsolationCut.cxx
- PWG/EMCAL/EMCALbase/AliEMCALRecoUtils.cxx
- PWG/EMCAL/EMCALbase/AliEMCALRecoUtils.h
- PWG/EMCAL/EMCALtasks/AliEmcalCorrectionCellBadChannel.cxx
- PWG/EMCAL/config/AliEmcalCorrectionConfiguration.yaml
- PWGGA/CaloTrackCorrelations/AliAnaCalorimeterQA.cxx
- PWGGA/CaloTrackCorrelations/AliAnaRandomTrigger.cxx
- PWGGA/GammaConv/AliCaloPhotonCuts.cxx
- PWGPP/EMCAL/AliAnalysisTaskCaloFilter.cxx
- PWGPP/EMCAL/AliAnalysisTaskEMCALClusterize.cxx
For calibration analysis it is important to try to understand if some channels declared as bad can be recovered, in particular those declared as "warm". 
With this commit, I changed the method AliEMCALRecoUtils::GetEMCALChannelStatus() that so far returned the status and in most of the code where it is used, if it was non 0 (good channel) this channel was rejected. Now instead, it returns true or false depending on internal conditions to select or not a bad channel depending its status but also the status is recoverable as one of the parameters.
The EMCal correction framework component dealing with bad channels is updated to consider this possibility, in the yaml file one should add the property
acceptWarm: true
in the part related to bad channels.
In other frames or codes, one should …
> Add possibility to accept declared as warm/dead/hot channels 

- PWGJE/EMCALJetTasks/UserTasks/AliAnalysisTaskJetExtractor.cxx
Simple protection for the case that AOD PID object does not exist.
> Protect against case of no PID

- PWGDQ/dielectron/macrosLMEE/AddTask_acapon.C
Running multiple wagons caused output clashes. Simple fix: append a number to output.
> AddTask_acapon: Unique outputs for train runs

- PWG/EMCAL/CMakeLists.txt
- PWG/EMCAL/EMCALtriggerPart/AliEmcalTriggerMakerPart.cxx
- PWG/EMCAL/EMCALtriggerPart/AliEmcalTriggerMakerPart.h
- PWG/EMCAL/EMCALtriggerPart/AliEmcalTriggerPartAlgorithm.cxx
- PWG/EMCAL/EMCALtriggerPart/AliEmcalTriggerPartAlgorithm.h
- PWG/EMCAL/EMCALtriggerPart/AliEmcalTriggerPartBadChannelContainer.cxx
- PWG/EMCAL/EMCALtriggerPart/AliEmcalTriggerPartBadChannelContainer.h
- PWG/EMCAL/EMCALtriggerPart/AliEmcalTriggerPartBitConfig.cxx
- PWG/EMCAL/EMCALtriggerPart/AliEmcalTriggerPartBitConfig.h
- PWG/EMCAL/EMCALtriggerPart/AliEmcalTriggerPartChannelMap.cxx
- PWG/EMCAL/EMCALtriggerPart/AliEmcalTriggerPartChannelMap.h
- PWG/EMCAL/EMCALtriggerPart/AliEmcalTriggerPartGammaAlgorithm.cxx
- PWG/EMCAL/EMCALtriggerPart/AliEmcalTriggerPartGammaAlgorithm.h
- PWG/EMCAL/EMCALtriggerPart/AliEmcalTriggerPartJetAlgorithm.cxx
- PWG/EMCAL/EMCALtriggerPart/AliEmcalTriggerPartJetAlgorithm.h
- PWG/EMCAL/EMCALtriggerPart/AliEmcalTriggerPartMapping.cxx
- PWG/EMCAL/EMCALtriggerPart/AliEmcalTriggerPartMapping.h
- PWG/EMCAL/EMCALtriggerPart/AliEmcalTriggerPartSetup.cxx
- PWG/EMCAL/EMCALtriggerPart/AliEmcalTriggerPartSetup.h
- PWG/EMCAL/EMCALtriggerPart/CMakeLists.txt
- PWG/EMCAL/EMCALtriggerPart/PWGEMCALtriggerPartLinkDef.h
Incoporate fast trigger maker from
https://github.com/mfasDa/EmcalTriggerFast, for trigger
studies at particle level. In order to run on the grid the
stand alone c++ program must be part of AliPhysics and
classes must inherit from TObject as most of the
configurations will probably happen in the asynchronous
stage.
> Incoporate fast trigger maker

- PWGCF/FEMTOSCOPY/macros/Train/PionPionFemto/AddTaskPionPion.C
instead of implicitly casting to bool, this uses the IsWhitespace to check if there is content in a parameter
> PWGCF: PionPionAnalysis - Correct check for string "emptiness"

- PWGCF/Correlations/macros/jcorran/AddTaskJCDijetTask.C
The goodbit for stringstream is not true for the last instance of the
list so instead !fail has to be used.
> A small bugfix for the task macro.

- PWGJE/EMCALJetTasks/macros/JetQA/plotPowerpoint.py
Added a destructor for the QA histogram list object and closed the QA AnalysisResults file to save memory on large datasets.
@efranzis @jdmulligan
> Fixing memory leaks in QA scripts

- PWGDQ/reducedTree/AliHistogramManager.h
- PWGDQ/reducedTree/AliReducedAnalysisJpsi2ee.cxx
- PWGDQ/reducedTree/AliReducedAnalysisJpsi2ee.h
- PWGDQ/reducedTree/AliReducedTrackCut.cxx
- PWGDQ/reducedTree/AliReducedTrackCut.h
- PWGDQ/reducedTree/AliReducedVarManager.cxx
- PWGDQ/reducedTree/AliReducedVarManager.h
- PWGDQ/reducedTree/AliResonanceFits.cxx
- PWGDQ/reducedTree/AliResonanceFits.h
1) AliHistogramManager
A setter for the object name was added
2) AliReducedAnalysisJpsi2ee
a) Added the posibility to fill hit maps for ITS shared clusters
b) In the MC part, the possibility to select the MC events to be used based on a jpsi pt dependent 
weight provided by the user in the AddTask. This can be used when one wants to re-weight efficiency 
calculations using realistic pt distributions.
3) AliReducedTrackCut
Added functionality to cut on the ITS shared cluster map. Similar to the functionality for the ITS cluster map.
4) AliReducedVarManager
Functionality to fill ITS hit layers from the shared cluster map
5) AliResonanceFits
A few bug fixes, optimization/clarification of the code; functionality to add more than one mass exclusion region (which might be needed when adding …
> Various updates

- PWGGA/GammaConv/AliAnalysisTaskNeutralMesonToPiPlPiMiNeutralMeson.cxx
- PWGGA/GammaConv/AliAnalysisTaskNeutralMesonToPiPlPiMiNeutralMeson.h
- PWGGA/GammaConv/AliConversionMesonCuts.cxx
- PWGGA/GammaConv/AliConversionMesonCuts.h
- PWGGA/GammaConv/AliPrimaryPionCuts.cxx
- PWGGA/GammaConv/CMakeLists.txt
- PWGGA/GammaConv/PWGGAGammaConvLinkDef.h
- PWGGA/GammaConv/macros/AddTask_GammaConvNeutralMesonPiPlPiMiNeutralMeson_CaloMode_pp.C
- PWGGA/GammaConv/macros/AddTask_GammaConvNeutralMesonPiPlPiMiNeutralMeson_ConvMode_pp.C
- PWGGA/GammaConv/macros/AddTask_GammaConvNeutralMesonPiPlPiMiNeutralMeson_MixedMode_pp.C
This analysis task is derived from AliAnalysisTaskNeutralMesonToPiPlPiMiPiZero but now also supports the pi+pi-eta decay channel (or any other neutral meson in the dacay).
It will be developed in parallel to the existing omega/eta analysis task and at some point take over its place.
> PWGGA/GammaConv: Upload of new AnalysisTask for heavy neutral mesons with three particle decay

- PWGCF/FEMTOSCOPY/AliFemtoUser/AliFemtoAnalysisPionPion.cxx
- PWGCF/FEMTOSCOPY/AliFemtoUser/AliFemtoAnalysisPionPion.h
- PWGCF/FEMTOSCOPY/AliFemtoUser/AliFemtoShareQualityPairCut.cxx
- PWGCF/FEMTOSCOPY/AliFemtoUser/AliFemtoShareQualityPairCut.h
This is an experimental feature to check performance of various bit-wise operations when calculating track quality in femtoscopic pairs (disabled by default)
> PWGCF: Add alternative implementations of share-quality algorithm

- PWGJE/EMCALJetTasks/AliEmcalJetTask.cxx
- PWGJE/EMCALJetTasks/AliEmcalJetTask.h
This change is needed for closure test studies, in which one creates a toy thermal model of AliBasicParticles and wants to cluster them with the jet finder. The feature is of course turned off by default.
> Allow AliEmcalJetTask to be compatible with AliBasicParticle

- PWG/EMCAL/EMCALtasks/AliAnalysisTaskEMCALClusterizeFast.cxx
This commit allows to use the old analysis framework with the new clusterizer v3.
NB: AliEMCALClusterizerv3.h is in the most recent AliRoot tag.
> Added option to use EMCAL clusterizer v3 within old analysis framework

- PWGGA/GammaConv/AliAnalysisTaskGammaConvV1.cxx
- PWGGA/GammaConv/AliConvEventCuts.cxx
check IsParticleFromBGEvent within GetWeightForMeson, just for added particle MCs, instead of outside and before for all MCs
> PWGGA/GammaConv: add more MCs for pT weighting

- PWGGA/GammaConv/macros/AddTask_ConversionAODProduction.C
- PWGHF/vertexingHF/macros/AddTaskDmesonMCPerform.C
- PWGPP/CMakeLists.txt
- PWGPP/EvTrkSelection/macros/AddSingleTrackEfficiencyTaskForAutomaticQA.C
- PWGPP/EvTrkSelection/macros/main_AddSingleTrackEfficiencyTaskForAutomaticQA.C
cannot include macro with $ALICE_PHYSICS in #include directory, and le is not in $ROOT_INCLUDE_PATH.
As discussed with @dberzano , this is a better fix as compared to alisw/alidist#1246, as it does not pollute the global include space.
> Fix for ROOT6

- PWG/EMCAL/EMCALtasks/AliEmcalCorrectionCellEnergy.cxx
- PWG/EMCAL/EMCALtasks/AliEmcalCorrectionCellEnergy.h
- PWG/EMCAL/config/AliEmcalCorrectionConfiguration.yaml
- PWG/EMCAL/macros/AddTaskEMCALTender.C
- PWGGA/GammaConv/config/PWGGA_CF_config_p1.yaml
- TENDER/TenderSupplies/AliEMCALTenderSupply.cxx
- TENDER/TenderSupplies/AliEMCALTenderSupply.h
The interface for the new temperature calibrations for Run2 is now available!
As soon as the calibration files are available on EOS (EMCALTemperatureCalibSM.root and EMCALTemperatureCalibParam.root) one can activate the temperature calibration in one of two ways:
1. Using the Tender: Set the last argument of AddTaskEMCALTender.C to kTRUE
2. Using the correction framework: Set doTempCalibRun2: true in the CellEnergy category.
The standard settig in both, tender and CF, is that no temperature correction is applied for Run2. Therefore nothing changes for run2 analyzers at the moment (except if they themselves activate it).
In both calibration tools, the implementation first checks the runnumber to be greater than 197692 to be certain that Run2 data is being handled. Then for Run2, two OADB …
> [EMCAL-191] PWG/EMCAL & TENDER: Implementation of Run2 EMCal/DCal temperature calib in OADB

- PWGCF/EBYE/NetLambda/AliAnalysisTaskNetLambdaIdent.cxx
- PWGCF/EBYE/NetLambda/AliAnalysisTaskNetLambdaIdent.h
also: enable translation of vertices for mixed events, add additional histograms for PID checks, add K0S inv mass to tree, enable switch for producing V0 tree, fix Armenteros-Podolanski calculation for swapped charges
> unify mixed v0 cuts with cuts on v0s in esd production

- PWGGA/GammaConv/AliConvEventCuts.cxx
GetUseNewMultiplicityFramework was not setting kTRUE for LHC18f3 MCs
> PWGGA/GammaConv: Added missing centrality switch for new pPb5TeV MC

- PWGCF/Correlations/DPhi/AliAnalysisTaskHadronPhiCorr.cxx
- PWGCF/Correlations/DPhi/AliAnalysisTaskHadronPhiCorr.h
In-line set functions and new variables added to header to allow for systematic checks on Kaon PID and tracking cuts.
> Adding Set functions for tracking and PID cuts for systematics

- PWGGA/GammaConv/AliAnalysisTaskConversionQA.cxx
- PWGGA/GammaConv/AliAnalysisTaskConversionQA.h
- PWGGA/GammaConv/AliAnalysisTaskGammaConvCalo.cxx
- PWGGA/GammaConv/AliAnalysisTaskGammaConvCalo.h
- PWGGA/GammaConv/AliAnalysisTaskGammaConvV1.cxx
- PWGGA/GammaConv/AliAnalysisTaskGammaConvV1.h
- PWGGA/GammaConv/macros/AddTask_GammaConvCalo_PbPb.C
- PWGGA/GammaConv/macros/AddTask_GammaConvCalo_pPb.C
- PWGGA/GammaConv/macros/AddTask_GammaConvCalo_pp.C
- PWGGA/GammaConv/macros/AddTask_GammaConvV1_PbPb.C
- PWGGA/GammaConv/macros/AddTask_GammaConvV1_PbPb2.C
- PWGGA/GammaConv/macros/AddTask_GammaConvV1_pPb.C
- PWGGA/GammaConv/macros/AddTask_GammaConvV1_pPb2.C
- PWGGA/GammaConv/macros/AddTask_GammaConvV1_pPb3.C
- PWGGA/GammaConv/macros/AddTask_GammaConvV1_pp.C
- PWGGA/GammaConv/macros/AddTask_GammaConvV1_pp2.C
- PWGGA/GammaConv/macros/AddTask_PhotonQA.C
As the increasing amount of statistics in our data sets lead to the outputfiles no longer merging, i have implemented a change to the tasks that the TTrees are being saved outside of the TList. This allows for ROOT files greater than 1GB. With this change, all future train outputs should be able to merge without problems.
The Afterburners have been adjusted accordingly, too. They can now handle both formats (TTree in TList and TTree outside of TList).
> PWGGA/GammaConv: Massive improvement for DCA trees in all tasks - now saved outside of TList

- PWGGA/GammaConv/AliAnalysisTaskHeavyNeutralMesonToGG.cxx
Removed 5 occurrences of `TMath::Abs` in `Fill` calls in `AliAnalysisTaskHeavyNeutralMesonToGG.cxx`. This is to solve a bug where negative \alpha values projected in the positive plane.
> PWGGA/GammaConv: removed absolute value over alpha in HeavyMesonTask

- PWGGA/GammaConv/macros/AddTask_GammaHeavyMeson_CaloMode_pPb.C
- PWGGA/GammaConv/macros/AddTask_GammaHeavyMeson_ConvMode_pPb.C
- PWGGA/GammaConv/macros/AddTask_GammaHeavyMeson_MixedMode_pPb.C
Created 'thinner' copies of p-Pb GammaHeavymeson trainconfigs (all three methods) that contain only 0-100% centrality
> PWGGA/GammaConv: added pPb GammaHeavyMeson trainconfigs without 0-20% centrality

- PWGGA/GammaConv/macros/AddTask_GammaConvNeutralMesonPiPlPiMiNeutralMeson_CaloMode_pPb.C
- PWGGA/GammaConv/macros/AddTask_GammaConvNeutralMesonPiPlPiMiNeutralMeson_ConvMode_pPb.C
- PWGGA/GammaConv/macros/AddTask_GammaConvNeutralMesonPiPlPiMiNeutralMeson_MixedMode_pPb.C
Added 3 `AddTask`s for `NeutralMesonPiPlPiMiNeutralMeson` **p-Pb** analysis (`ConvMode`, `MixedMode`, and `CaloMode`). The tasks and their train configs are derived from the tasks for pp analysis (only MinBias retained and `000` -> `800` in event cut numbers).
> PWGGA/GammaConv: added  addtasks for pPb NeutralMesonPiPlPiMiNeutralMes

- PWGCF/Correlations/DPhi/AliAnalysisTaskHadronPhiCorr.cxx
- PWGCF/Correlations/DPhi/AliAnalysisTaskHadronPhiCorr.h
changing handling of zvertex (move from being a sparse axis to being separate histograms), as well as reducing number of bins per axis due to memory issues when merging.
> modifying correlation THnSparse axes in hadron-phi analysis

- PWGCF/FEMTOSCOPY/macros/Train/ProtonLambdaFemto/ProtonLambda/Xi/FB96/ConfigAvgsepAnalysis.C
removing cut on on-the-fly status for cascades and adding out-of-bunch pile-up rejection track based cuts
> AliFemto: removing checking onfly status for Xis and adding pile-up

- PWG/EMCAL/EMCALtrigger/AliEmcalTriggerMakerKernel.cxx
- PWG/EMCAL/EMCALtrigger/AliEmcalTriggerMakerKernel.h
- PWGJE/EMCALJetTasks/Tracks/AliAnalysisTaskEmcalJetSubstructureTree.cxx
A constant scale shift (in GeV) is added to each cell
when filling the offline simple ADC data grid. The scale
shift is applied before conversion to FastOR ADC values.
> Simulation of the EMCAL energy scale shift in the trigger electronics

- PWGGA/GammaConv/macros/AddTask_GammaConvCalo_PbPb.C
- PWGGA/GammaConv/macros/AddTask_GammaConvCalo_pPb.C
- PWGGA/GammaConv/macros/AddTask_GammaConvCalo_pp.C
The output objects were so far created even when no gamma DCA tree was requested via enableQAPhotonTask=1.
This has been fixed and the task will now properly create or not create the additional outputs.
> PWGGA/GammaConv: Fixed GammaConvCalo for running without gamma DCA tree

- PWG/EMCAL/EMCALtasks/AliEmcalCorrectionClusterNonLinearity.cxx
Each enum value needs to be explicitly added to the string map to allow the value to be set from the YAML config. Adds `kBeamTestCorrectedv4` (from #6912) and some PCM parameterizations.
> EMCal CorrFW: Add additional non-linearity enums

- PWGPP/TRD/AliTRDcheckESD.cxx
This makes the TRD QA trending parameters for the Landau fit more stable (as was observed for a few runs in LHC18l pass1).
> Remove par. limits for Landau fit in TRD PID QA

- PWGJE/EMCALJetTasks/UserTasks/AliAnalysisTaskJetExtractor.cxx
- PWGJE/EMCALJetTasks/UserTasks/AliAnalysisTaskJetExtractor.h
- PWGJE/EMCALJetTasks/UserTasks/AliAnalysisTaskParticleRandomizer.cxx
New option: Trigger track in extractor will only be used if it has a label above a value (e.g. when from MC/embedding)
> Allow trigger track label selection

- PWGDQ/dielectron/LMEE/AliAnalysisTaskSimpleTreeMaker.cxx
Spelling mistake in generator list. Injected non-prompt JPsi tracks were not being labelled
as injected.
> TreeMaker isInjected bug fix

- PWGLF/RESONANCES/extra/AddTaskXi1530.C
- PWGLF/RESONANCES/extra/AliAnalysisTaskXi1530.cxx
- PWGLF/RESONANCES/extra/AliAnalysisTaskXi1530.h
Add "FillTrackToEventPool" function to make mixing pool.
It was done in GoodTracksSelection() before, but it has filled 'current' event track list to the mixing pool. As a result, mixed background contains "real" signal, so that I changed order of making mixing pool after use it.
> Add fill function for the event mixing pool

- PWGGA/GammaConv/AliAnalysisTaskConvJet.cxx
- PWGGA/GammaConv/AliAnalysisTaskConvJet.h
- PWGGA/GammaConv/AliAnalysisTaskGammaCalo.cxx
- PWGGA/GammaConv/AliAnalysisTaskGammaCalo.h
- PWGGA/GammaConv/CMakeLists.txt
- PWGGA/GammaConv/PWGGAGammaConvLinkDef.h
- PWGGA/GammaConv/macros/AddTask_GammaCalo_pp.C
- PWGGA/GammaConv/macros/AddTask_GammaConvJet.C
Added a ConvJet class that reads in the jet results from AliEmcalJetTask. The changes in AliAnalysisTaskGammaCalo read in the results retrieved from the ConvJet class to make jet histograms for every cut number (if fDoJetAnalysis ik kTRUE, which is only the case if TrainConfig 900 is used). The changes in AddTask_GammaCalo_pp are to add this TrainConfig and the case that if this TrainConfig is used the jet analysis will be used.
> PWGGA added code to handle jets

- PWGJE/EMCALJetTasks/UserTasks/AliAnalysisTaskEmcalJetSpectra8TeVTriggerQA.h
Headers are installed in global include directory and
have to be taken from the global include dir. Incorrect
include paths show up as problems with symbols from the
dictionary in train tests using the ROOT6-based versions.
> Fix including headers from global include path (needed for ROOT6)

- PWGJE/EMCALJetTasks/AliAnalysisTaskRhoSparse.cxx
- PWGJE/EMCALJetTasks/AliAnalysisTaskRhoSparse.h
Changed the way to check for ghost jets (was pT>0.1 now nTracks>0)
Changed the way the total covered area is determined (was sum of all jet areas (excluding two leading jets) now Area of the TPC)
Changed the way the total jet area that is used for the correction factor is used (was use all non-ghost jets w/o leading jets now use all jets that actually contribute to the rho calculation)
> few minor improvements to the rho task to analyze the 2016 data

- PWGDQ/dielectron/macrosLMEE/AddTask_acapon_Efficiency.C
- PWGDQ/dielectron/macrosLMEE/Config_acapon_Efficiency.C
No electron tracks are found in the general purpose (EPOS-LHC) MC production if the
generator is specified. Leaving the strings blank means all present generators will be used.
> acapon_LMEE_effCorr: turned off gen. naming

- PWG/EMCAL/EMCALtasks/AliEmcalCorrectionCellBadChannel.cxx
- PWG/EMCAL/EMCALtasks/AliEmcalCorrectionCellEnergy.cxx
- PWG/EMCAL/EMCALtasks/AliEmcalCorrectionCellEnergy.h
- PWG/EMCAL/EMCALtasks/AliEmcalCorrectionComponent.cxx
- PWG/EMCAL/EMCALtasks/AliEmcalCorrectionComponent.h
- PWG/EMCAL/config/AliEmcalCorrectionConfiguration.yaml
Due to a request by @loizides, @gconesab  and @FriederikeBock we now have the possibility to set custom OADB objects for the recalibration as well as bad channel maps. For this, simply set  one or both of the following values in the .yaml configuration:
```
CellEnergy:
customRecalibFilePath: "" 
CellBadChannel: 
customBadChannelFilePath: ""
```
In both cases, the full path including the .root filename must be provided. This allows also for custom names of the .root files.
>  PWG/EMCAL: Added possibilty to load custom Recalib and BadChannel OADB 

- CMakeLists.txt
- cmake/FindRooUnfold.cmake
Modern CMake is used: target `RooUnfold::RooUnfold` is exported if found
> Add optional RooUnfold dependency

- PWGJE/EMCALJetTasks/Tracks/AliAnalysisTaskEmcalClustersRef.cxx
> Do not use event selection from mulitplicity selection

- cmake/FindRooUnfold.cmake
When a library links to the `RooUnfold::RooUnfold` CMake target, the compiler is
invoked with `-DWITH_ROOUNFOLD`, allowing source code to have conditional
sections:
#ifdef WITH_ROOUNFOLD
...
#endif
Note: it has to be verified whether `rootcling` is automatically getting those
definitions as well.
> RooUnfold: add `WITH_ROOUNFOLD` definition

- PWGCF/FEMTOSCOPY/AliFemtoUser/AliFemtoModelCorrFctnTrueQ3DByParent.cxx
Error: PWGCF/FEMTOSCOPY/AliFemtoUser/AliFemtoModelCorrFctnTrueQ3DByParent.cxx:85:24: error: 
implicit instantiation of undefined template 'std::__1::array<int, 4>'
std::array<Int_t, 4> nbins_v = {static_cast<int>(par_nbins * 2 + 1), nbins, nbins, nbins};
Fixed by including array
> Fixes issue of this class with standard macos compiler

- PWG/Tools/AliYAMLConfiguration.cxx
- PWG/Tools/AliYAMLConfiguration.h
Automatically reinitialize the YAML nodes when printing if they are not
initialized to ensure that configurations will be printed after
streaming to the grid.
As a future possible improvement, this approach could be added to
GetProperty() and WriteProperty(), which may avoid the need to call
Reinitialize(). However, such a change would require some careful
thinking and testing, so it won't be done now.
@jdmulligan
> Improve AliYAMLConfiguration docs and printing

- PWGCF/FEMTOSCOPY/FemtoDream/AliAnalysisTaskSigma0Femto.cxx
- PWGCF/FEMTOSCOPY/FemtoDream/AliFemtoDreamAnalysis.cxx
- PWGCF/FEMTOSCOPY/FemtoDream/AliFemtoDreamCascade.cxx
- PWGCF/FEMTOSCOPY/FemtoDream/AliFemtoDreamCascade.h
- PWGCF/FEMTOSCOPY/FemtoDream/AliFemtoDreamCascadeHist.cxx
- PWGCF/FEMTOSCOPY/FemtoDream/AliFemtoDreamCorrHists.cxx
- PWGCF/FEMTOSCOPY/FemtoDream/AliFemtoDreamEventHist.cxx
- PWGCF/FEMTOSCOPY/FemtoDream/AliFemtoDreamPairCleanerHists.cxx
- PWGCF/FEMTOSCOPY/FemtoDream/AliFemtoDreamTrack.cxx
- PWGCF/FEMTOSCOPY/FemtoDream/AliFemtoDreamTrackCuts.cxx
- PWGCF/FEMTOSCOPY/FemtoDream/AliFemtoDreamTrackCuts.h
- PWGCF/FEMTOSCOPY/FemtoDream/AliFemtoDreamTrackHist.cxx
- PWGCF/FEMTOSCOPY/FemtoDream/AliFemtoDreamTrackMCHist.cxx
- PWGCF/FEMTOSCOPY/FemtoDream/AliFemtoDreamTrackMCHist.h
- PWGCF/FEMTOSCOPY/FemtoDream/AliFemtoDreamv0.cxx
- PWGCF/FEMTOSCOPY/FemtoDream/AliFemtoDreamv0.h
- PWGCF/FEMTOSCOPY/FemtoDream/AliFemtoDreamv0Cuts.cxx
- PWGCF/FEMTOSCOPY/FemtoDream/AliFemtoDreamv0Cuts.h
- PWGCF/FEMTOSCOPY/FemtoDream/AliFemtoDreamv0Hist.cxx
- PWGCF/FEMTOSCOPY/FemtoDream/AliFemtoDreamv0MCHist.cxx
- PWGCF/FEMTOSCOPY/FemtoDream/AliFemtoDreamv0MCHist.h
- PWGCF/FEMTOSCOPY/macros/AddTaskSigma0Femto.C
- PWGGA/Hyperon/AliSigma0PhotonMotherCuts.cxx
- PWGGA/Hyperon/AliSigma0PhotonMotherCuts.h
- PWGGA/Hyperon/AliSigma0V0Cuts.cxx
- PWGGA/Hyperon/AliSigma0V0Cuts.h
- PWGGA/Hyperon/macros/AddTaskSigma0Run2syst.C
- FemtoDream
- Propagate MC information in ESD case for tracks
- Remove Sumw2() for track, V0 and cascade histos
- By default the proton/V0 origin histograms vs. multiplicity are not initialized
- Sigma0 Analysis
- Introducing systematic cut variations (62)
- Multiplicity-binned analysis
- Histogram improvements
- Minor cleaning of the selection criteria
> Major update of the FemtoDream and the Sigma0 analysis

- PWGPP/EMCAL/AliAnalysisTaskEMCALTimeCalib.cxx
- PWGPP/EMCAL/AliAnalysisTaskEMCALTimeCalib.h
Removed AliTOFTOFmaker.h and AliTOFcalib.h dependency from EMCal time calibration. 
Removed couts. Added TF1 header.
> Removed TOF dependency from EMCal time calibration

- PWG/JETFW/AliJetContainer.cxx
- PWG/JETFW/AliJetContainer.h
Jet definition (algorithm, jet type, recombination scheme)
enum values are cached in the jet container, and getters
are provided. No setters are provided as the jet definition
is not supposed to change after the container is constructed.
In addition adding doxygen tag (///<) to persistent attributes
where missing.
> Provide read access to jet definition at runtime

- PWGGA/CaloTrackCorrelations/macros/CheckActiveEMCalTriggerPerPeriod.C
- PWGGA/CaloTrackCorrelations/macros/ConfigureAndGetEventTriggerMaskAndCaloTriggerString.C
instead of the usual kEMC*. This applies right now to LHC15n and LHC17pq.
> For periods with EMCal triggers but no TPC load the kCaloOnly bit 

- PWGHF/vertexingHF/AliAnalysisTaskSEImproveITS.cxx
- PWGHF/vertexingHF/macros/AddTaskB0Dminuspi.C
- PWGHF/vertexingHF/macros/AddTaskCFVertexingHF.C
- PWGHF/vertexingHF/macros/AddTaskCFVertexingHF3Prong.C
- PWGHF/vertexingHF/macros/AddTaskCFVertexingHF3ProngDs.C
- PWGHF/vertexingHF/macros/AddTaskCFVertexingHF3ProngLc.C
- PWGHF/vertexingHF/macros/AddTaskCFVertexingHFCascade.C
- PWGHF/vertexingHF/macros/AddTaskCFVertexingHFLctoV0bachelor.C
- PWGHF/vertexingHF/macros/AddTaskCFVertexingHFLctoV0bachelorTMVA.C
- PWGHF/vertexingHF/macros/AddTaskCombinHF.C
- PWGHF/vertexingHF/macros/AddTaskImproveITS.C
- PWGHF/vertexingHF/macros/AddTaskLambdac.C
fixes ROOT6 compilation errors for multiple PWGHFvertexingHF AddTask macros, and a segfault in the AliAnalysisTaskSEImproveITS task that appeared under ROOT6 due to the streaming of some TGraph objects [now uses TObject::Clone method instead of TGraph's copy constructor].
> [ALIROOT-7981]: Fixes to D2H macros for ROOT6 compatibility

- PWG/MCLEGO/JEWEL/gen_jewel_user.sh
- PWG/MCLEGO/JEWEL/gen_jewel_vacuum_user.sh
The commit add external MC generator shell scripts to run JEWEL (medium & vacuum mode). The configuration files can be given as parameters to the shell script.
The code was tested locally and worked fine.
This PR is connected to a PR in AliRoot: https://github.com/alisw/AliRoot/pull/818
> Added JEWEL generator scripts, taking configuration as input

- PWGHF/jetsHF/AliAnalysisTaskHFJetIPQA.cxx
- PWGHF/jetsHF/AliAnalysisTaskHFJetIPQA.h
- PWGHF/jetsHF/macros/AddTaskHFJetIPQA.C
- adding new QA histograms (fh1dJetArea, fh1dParticlesPerJet, fh2dNoAcceptedTracksvsJetArea, fh1dTrackPt_n_%i_all_Accepted, fh1dNoParticlesPerEvent, fh1dNoJetsPerEvent )
- expand struct SjetIpPati to contain also track pt
- go from fixed radius R=0.4 to flexible radius via new function SetJetRadius
- tidy up histogram generation in UserCreateOutputObjects
> PWGHF/jetsHF/AliAnalysisTaskHFJetIPQA: adding new histograms

- PWG/EMCAL/EMCALtasks/AliEmcalCorrectionClusterEnergyVariation.cxx
- PWG/EMCAL/EMCALtasks/AliEmcalCorrectionClusterEnergyVariation.h
- PWG/EMCAL/EMCALtasks/AliEmcalCorrectionTask.cxx
- PWG/EMCAL/EMCALtasks/CMakeLists.txt
- PWG/EMCAL/EMCALtasks/PWGEMCALtasksLinkDef.h
- PWG/EMCAL/READMEemcCorrections.txt
- PWG/EMCAL/config/AliEmcalCorrectionConfiguration.yaml
Please do not approve yet.
This is a draft of how we could implement scaling/smearing of the cluster energy in order to evaluate systematics, e.g. in jet analyses, but also available for everyone.
@efranzis @raymondEhlers please let me know what you think.
> EMCal CorrFW: Implement cluster energy scaling/smearing component

- PWGCF/Correlations/DPhi/Unfoldedhistos/AliDptDptCorrelations.cxx
The latest modification, for re-using weights when shortening the pT or
zvtx ranges, was wrongly implemented
> Fix for a wrong index assignment storing NUA and NUE corrections

- PWG/EMCAL/EMCALbase/AliEmcalTrackSelection.cxx
- PWG/EMCAL/EMCALbase/AliTrackContainer.cxx
In case only cuts on the AOD filter bit are applied, and
no additional track cuts, the cut array typically is a
nullptr, leading to a segfault dereferencing the array.
The function AddTrackCuts is only called in case the
array is not null. Furthermore the function checks itself
that the array is not null.
> Add missing protection for nullptr in cut array

- PWGDQ/dielectron/core/AliDielectronTrackCuts.cxx
- PWGDQ/dielectron/core/AliDielectronTrackCuts.h
There was no possibility to select all global tracks from an esd event converted into an aod event. The added cut selects these tracks and excludes hybrid and tpconly tracks from the sample to protect against double counting, without adding any other quality cuts.
> PWGDQ added a track cut option to select global tracks

- PWG/EMCAL/config/EMCalSampleConfigMC.yaml
- PWG/EMCAL/config/PWGJESampleConfigMC.yaml
The non-linearity function must be specified explicitly for simulation,
otherwise the default function kTestbeamCorrectedv3 is used, which is
not the correct one for simulations
> Use proper non-linearity function for MC

- PWGGA/EMCALTasks/AliAnalysisTaskGammaHadron.cxx
- PWGGA/EMCALTasks/AliAnalysisTaskGammaHadron.h
Fixes a divide-by-zero error causing crashes in root 6.
Fixes a variable mix up.
Fixes a type error affecting minimum cluster energy.
> Fixes some errors in AliAnalysisTaskGammaHadron

- PWGDQ/dielectron/LMEE/AliAnalysisTaskSimpleTreeMaker.cxx
- PWGDQ/dielectron/LMEE/AliAnalysisTaskSimpleTreeMaker.h
- PWGDQ/dielectron/macrosLMEE/AddTaskSimpleTreeMaker.C
- PWGDQ/dielectron/macrosLMEE/Config_acapon.C
- PWGDQ/dielectron/macrosLMEE/LMEECutLib_acapon.C
- Using doubles was uncessary, and caused the TTrees to be quite large.
- The exact generator of each track is now encoded into the isInj
branch as an integer.
> Converts all doubles to floats for SimpleTreeMaker

- PWG/EMCAL/EMCALtasks/AliEmcalCorrectionClusterHadronicCorrection.cxx
- PWG/EMCAL/EMCALtasks/AliEmcalCorrectionClusterHadronicCorrection.h
- PWG/EMCAL/config/AliEmcalCorrectionConfiguration.yaml
This addition includes the pT dependent track matching as preformed in 
https://alice-notes.web.cern.ch/system/files/notes/analysis/411/ Fig. 46
It can be switched on and off with doMomDepMatching in the ClusterHadronicCorrection section.
It is disabled by defualt.
@jdmulligan and @raymondEhlers please have a look and add your suggestions for improvements.
Thank you!
Kind Regards
efranzis
> Add a momentum dependent track matching to the hadcorr

- PWGJE/EMCALJetTasks/AliPWGJETrainHelpers.cxx
- PWGJE/EMCALJetTasks/AliPWGJETrainHelpers.h
- PWGJE/EMCALJetTasks/CMakeLists.txt
- PWGJE/EMCALJetTasks/PWGJEEMCALJetTasksLinkDef.h
This allows for the extraction of AliEn production variables in the
LEGO train global variables. Control statements such as for loops are
not allowed in the global variables, so this function allows more
complicated extraction and assignment of variables.
Note that a class with static methods is used instead of a namespace
because the are easier to use with rootmaps.
@mfasDa , @jdmulligan
> Add JE train helpers for LEGO train configuration

- PWG/EMCAL/EMCALbase/AliEMCALRecoUtils.cxx
- PWG/EMCAL/EMCALbase/AliEMCALRecoUtils.h
to extrapolate ESD tracks to EMCal.
Note that:
- This only works for ESDs
- This is not enough to run with the correction framework since it makes use of a method in AliEMCALRecoUtilsBase in AliRoot and I have prefered for the moment not to touch aliroot and wait for new tags with now the Pb-Pb rush
- It can be used with the standalone clusterization task and possibly with the tender, not checked in the last case.
> [EMCAL-406] Option to use ESD track Outer Param instead of Inner Param 

- PWG/EMCAL/EMCALtrigger/AliEmcalTriggerMakerKernel.cxx
- PWG/EMCAL/EMCALtrigger/AliEmcalTriggerMakerKernel.h
Online background estimated using the median mode
subtracted from the online ADC values. An area
of 1 subregion (4 TRUs per direction) is assumed
as area unit for the rho calculation. The background
estimate is only applied on request, and switched on
automatically in the PbPb2015 mode (covering all run2
PbPb).
> [EMCAL-411] Subtraction of online background estimate

- PWGJE/EMCALJetTasks/AliPWGJETrainHelpers.cxx
- PWGJE/EMCALJetTasks/AliPWGJETrainHelpers.h
It appears that we're not allowed to reassign global variables, so we
can't pass variables by reference (See [this test train stdout](http://alitrain.cern.ch/train-workdir/PWGJE/Jets_EMC_pPb/1683_20181112-1624/test/__BASELINE__/stdout)). To avoid this issue, we return a
std::vector from which we can assign the extracted values.
Local tests appear to work
@mfasDa , @jdmulligan
> Address assignment issues on the LEGO train

- PWGGA/GammaConv/AliAnalysisTaskGammaConvDtrue.cxx
Needed for the container and the weight histograms
for the jet-jet Monte-Carlo.
> D0 to 3-pion: Enable general histograms

- PWGGA/GammaConv/AliAnalysisTaskGammaCalo.cxx
Fix for "terminate called after throwing an instance of 'std::out_of_range'" train error
> PWGGA/GammaConv Jet vector out of range fix

- PWGGA/GammaConv/AliConversionMesonCuts.cxx
Fix to ensure that a MesonKind with 2 will not also set fDoJetQA to kTRUE
> PWGGA/GammaConv fDoJetQA bool fix

- PWGPP/QA/detectorQAscripts/ZDC.sh
- PWGPP/ZDC/macros/DrawPerformanceZDCQAMatch.C
- PWGPP/ZDC/macros/DrawPerformanceZDCQAMatchTrends.C
- PWGPP/ZDC/macros/MakeTrendZDC.C
These changes are needed in order to update the QA trending macros to use the QA classes.
> Fixes needed for ZDC QA trending

- PWGHF/vertexingHF/AliAODRecoDecayHF2Prong.cxx
- PWGHF/vertexingHF/AliAODRecoDecayHF2Prong.h
- PWGHF/vertexingHF/AliVertexingHFUtils.cxx
- PWGHF/vertexingHF/AliVertexingHFUtils.h
- Added Bplus decay in HFUtils
- Added MatchToMC for non-resonant 2prong -> daughter + 2prong decays (coming from Bplus analysis task). So it can be accessed in MVA task
> PWGHF: Adding Bplus decay in standard HF functions

- PWGGA/PHOSTasks/PHOS_EpRatio/AliAnalysisTaskEpRatio.cxx
It seems that additional check is necessary for the matched tracks, otherwise this task fails.
Here is an example of the stack trace:
https://alimonitor.cern.ch/jobs/stackAnalysis.jsp?path=PWGGA%2FGA_pp_AOD%2F543_20181105-0923
> Handle missing matched tracks in EpRatio task

- PWGHF/vertexingHF/AliRDHFCutsBPlustoD0Pi.cxx
- PWGHF/vertexingHF/AliRDHFCutsBPlustoD0Pi.h
Added a function to cut on PID D0 daughters and a D0 + Bplus invariant mass window before the reconstruction of the Bplus vertex to save CPU time. 
Needed to speed up task for MVA studies Bplus (will probably also replace similar hardcoded selections in AnalysisTask)
> PWGHF: Update Bplus for MVA studies

- PWGGA/GammaConv/AliAnalysisTaskGammaCalo.cxx
- PWGGA/GammaConv/AliAnalysisTaskGammaConvCalo.cxx
The first method to initialize the jet vectors was to initialize them in the ProcessJets function and then only clear them if the number of jets in the event was zero. On a very rare occasion however, the True vectors somehow end up being empty even though they shouldn't. To fix this, the vectors are now initialized only when they are used en they are cleared there shortly after
> PWGGA/GammaConv Jet Vector out of range second fix

- PWG/EMCAL/EMCALtasks/AliEmcalCorrectionTask.cxx
A fatal error is raised early if the user config is missing (either
because it wasn't set or because it couldn't be found due to typo,
not existing, etc). Previously, this generated a warning and there would
be not histogram output, but it is better to explicitly make it a fatal
error.
cc: @jdmulligan , @mfasDa
> EMCal CorrFW: Fatal if the user config is missing

- PWGDQ/dielectron/macrosLMEE/AddTask_acapon.C
- PWGDQ/dielectron/macrosLMEE/Config_acapon.C
- PWGDQ/dielectron/macrosLMEE/LMEECutLib_acapon.C
Cleans up PID correction functions readability. E.g. V0 track cuts merged into one setting (switch case).
Adds 20 linearly increasing PID cuts (on TMVA output).
Removes many unnecessary 2-3D histograms so as to avoid ByteCount issues. Also moves all single track plots into trackVar group. The creation of all histogram groups are now controlled by input arguments in the AddTask for flexibility.
Partial steps towards making Config, AddTask and CutLib C++11 compliant.
> Updates acapon_LMEE PID correction settings 

- PWGPP/ZDC/AliAnalysisTaskZDCPbPb.cxx
Use simplified centroid calculation for Pb_Pb to avoid the beam energy dependence.
> ZDC ESD: Using standard pp centroid also for Pb-Pb

- PWG/EMCAL/EMCALtasks/AliEmcalTrackingQATask.cxx
- PWG/EMCAL/EMCALtasks/AliEmcalTrackingQATask.h
Usage of kTRDUpdate flag default but made optional. If
it is off, then fall back to old method (at least 3 tracklets)
> [ALIROOT-7874] Separate refit and non-refit tracks using kTRDUpdate flag

- PWGPP/CalibMacros/AliOCDBtoolkit.sh
* param1: Input OCDB snapshot
* param2: Input object
* param3: Output XML path
* dump object TPC*Calib*RecoParam  from OCDB snapshot
````
dumpOCDBXML  OCDB/OCDBrec.root TPC*Calib*RecoParam TPC_Calib_RecoParam.xml
````
modification macro lambdaOCDB.C created
lambdaOCD  param1 [param2]
* param1: Input OCDB path
* param2: Output file name
* param3: object name
* param4: Object lambda
* print ocdb content
````
lambdaOCDB /cvmfs/alice-ocdb.cern.ch/calibration/data/2015/OCDB/TPC/Calib/RecoParam/Run0_244339_v18_s0.root Run0_244339_v18_s0.xml AliCDBEntry  o.Print\(\"all\"\)\; ; root -b -q lambdaOCDB.C
````
````
lambdaCode='AliTPCRecoParam*p=o;p->Dump();'
lambdaOCDB /cvmfs/alice-ocdb.cern.ch/calibration/data/2015/OCDB/TPC/Calib/RecoParam/Run0_244339_v18_s0.root Run0_244339_v18_s0.xml  AliCDBEntry …
```
> ATO-452, ATO-265: adding lambdaOCDB and dumpOCDBXML function

- PWGPP/CalibMacros/AliOCDBtoolkit.sh
Original sysntax explained in  https://github.com/alisw/AliPhysics/pull/7709
In new version not need to run root
````
[AliPhysics/latest] /lustre/nyx/alice/users/miranov/NOTESData/alice-tpc-notes/JIRA/ATO-452/tailScan1/OCDB/MC10_10Rec10_10 $> lambdaOCDB  
lambdaOCDB /cvmfs/alice-ocdb.cern.ch/calibration/data/2015/OCDB/TPC/Calib/RecoParam/Run0_244339_v18_s0.root Run0_244339_v18_s0.xml AliCDBEntry  o.Print\(\"all\"\)\;
lambdaCode='AliTPCRecoParam*p=o;p->Dump();'
lambdaOCDB /cvmfs/alice-ocdb.cern.ch/calibration/data/2015/OCDB/TPC/Calib/RecoParam/Run0_244339_v18_s0.root Run0_244339_v18_s0.xml  AliCDBEntry $lambdaCode;
lambdaCode='TObjArray*p=(TObjArray*)o;for(i=0;i<4;i++)((AliTPCRecoParam*)p->At(i))->SetCrosstalkCorrection(1.5);'
lambdaOCDB …
```
> Pull-7709: lambaOCDB  - updated syntax

- PWGJE/EMCALJetTasks/AliAnalysisTaskRho.cxx
- PWGJE/EMCALJetTasks/AliAnalysisTaskRho.h
- PWGJE/EMCALJetTasks/macros/AddTaskRhoNew.C
Conversion of AddTask macros to compile code allow easier usage
and greater compatibility with ROOT6.
The AddTaskRhoNew.C is kept for compatibility.
> Convert AddTaskRhoNew to static method

- PWGLF/SPECTRA/PiKaPr/TPC/rTPC/AliAnalysisTaskPPvsMult.cxx
The calibration of dE/dx vs Eta for the different multiplicity classes is done using two sets of calibration parameters from the different periods of Data that will be analyzed.
> New set of parameters to calibrate the dE/dx vs Eta

- PWGLF/CMakeLists.txt
- PWGLF/ML/AliExternalBDT.cxx
- PWGLF/ML/AliExternalBDT.h
- PWGLF/ML/CMakeLists.txt
- PWGLF/ML/MLLinkDef.h
This commit, prepared with @pfecchio, introduces an interface to the
treelite library. Treelite takes serialised models created by xgboost,
lightgbm and scikit-learn and turns them in C code.
The C code can then be compiled into a library that is used for
inference.
For the time being the interface allows the user to load a serialised
model from LightGBM, xgboost or a compiled library generated locally.
Local tests on a small dataset show that the inference with this
interface and with xgboost (in python) gives exactly the same results.
> Interface for generic BDT models in AliPhysics

- PWG/JETFW/AliAnalysisTaskEmcalJet.cxx
- PWG/JETFW/AliAnalysisTaskEmcalJet.h
- PWG/JETFW/AliJetContainer.cxx
- PWG/JETFW/AliJetContainer.h
To use the JetType information in your task you have to call the AddJetContainer version with
AliAnalysisTaskEmcalJet::AddJetContainer(EJetType_t jetType, ….
or set the jet type by hand after you added the jet container to the task in another way.
@mfasDa added this setter as discussed.
> Make jetType settable in the jet container and AliAnalysisTaskEmcalJet

- PWGLF/ML/AliExternalBDTTest.cc
AliExternalBDTTest.cc macro introduced with this commit tests the correctness of the prediction provided by the model loaded and compiled by the AliExternalBDT class.
> Add AliExternalBDTTest.cc macro to test AliExternalBDT class

- PWGDQ/dielectron/LMEE/AliAnalysisTaskSimpleTreeMaker.cxx
- PWGDQ/dielectron/LMEE/AliAnalysisTaskSimpleTreeMaker.h
Fixes issue where large pt tracks were being scaled by 0, resulting in inf values.
Function to set max pt for PID correction (default now at 9 Gev/c).
Additionally:
-A lot of unused variables either deleted, or now by default not written to TTree.
-Much formatting....
> Fixes acapon_TTree PID correction application issue

- PWGLF/ML/CMakeLists.txt
The default extension of the shared libraries on MacOSX is dylib, so we should not give full names (with extension like .so) in the CMakeLists.txt.
> Fix the compilation on Mac, do not set full name of the libraries

- PWGPP/TRD/TRDPID/AliTRDPIDTree.cxx
- PWGPP/TRD/TRDPID/AliTRDPIDTree.h
- PWGPP/TRD/TRDPID/macros/AddTaskTRDPIDTree.C
- add combination of enumerate and switch-case environment to make it possible to switch between pile-up cuts for different PbPb periods
> PWGPP/TRD/TRDPID: add pile-up cut for LHC18q

- PWGPP/EMCAL/AliAnalysisTaskEMCALTimeCalib.cxx
- PWGPP/EMCAL/AliAnalysisTaskEMCALTimeCalib.h
- PWGPP/EMCAL/macros/AddTaskEMCALTimeCalibration.C
Time Calib code is modified to handle runs with PAR/L1 phase splitting.   Modification happened on two levels:
* **AddTaskEMCALTimeCalib** - Addtask now loads in text file containing PAR information (with workaround to locally copy any remote alien:// path to the local working directory, due to .txt file not being a root file - this is similar to how YAML files are dealt with in EMCAL Correction Framework).
* **AliAnalysisTaskEMCALTimeCalib** - step 1 now produces N+1 time vs. cellAbsID histograms, with N being the number of PARs in the event (which is set by the above txt file). Step 2 and Step 3 now look for multiple L1 phase histograms for an affected run and choose the correct histogram for a given event by calculating the event global BC (calculated as: *eventBC + 3564\*eventOrbit + …
> modify Time Calib code to handle runs with PAR/L1 splitting

- PWGDQ/dielectron/LMEE/AliAnalysisTaskSimpleTreeMaker.cxx
- PWGDQ/dielectron/LMEE/AliAnalysisTaskSimpleTreeMaker.h
Get first (initial) mother particle loop fails for DPMJET productions. 
Set up a flag to stop search if looking at DPMJET MC production.....
> Fix getMCmother loop in TreeMaker

- PWGJE/EMCALJetTasks/Tracks/AliAnalysisTaskEmcalJetEnergySpectrum.cxx
- PWGJE/EMCALJetTasks/Tracks/AliAnalysisTaskEmcalJetEnergySpectrum.h
With this option the AliEventCuts are used
instead of the event selection implemented
in AliAnalysisTaskEmcal. The trigger selection
from the AliEventCuts is disabled and still
done manually in the task before the event
selection.
> Adding option to use AliEventCuts

- PWGHF/vertexingHF/AliAnalysisTaskSED0Mass.cxx
- PWGHF/vertexingHF/AliAnalysisVertexingHF.cxx
- PWGHF/vertexingHF/AliAnalysisVertexingHF.h
- PWGHF/vertexingHF/AliRDHFCuts.cxx
- PWGHF/vertexingHF/AliRDHFCuts.h
- PWGHF/vertexingHF/AliRDHFCutsD0toKpi.cxx
- PWGHF/vertexingHF/AliRDHFCutsD0toKpi.h
Introduction of PreSelect method that allows to skip filling of candidates at analysis level if they do not pass selections that can be evaluated w/o secondary vtx.
> Introduction of PreSelect method that allows to select candidates before filling them

- PWGCF/Correlations/JCORRAN/Base/AliJHistManager.cxx
Change formatting of instructions from:
```
for(...) a(); b();
```
to explicit but equivalent
```
for(...) {
a();
}
b();
```
Silencing compiler warnings.
> PWGCF: AliJBin - Fix compiler warnings of "non-guarding for clause"

- PWGJE/EMCALJetTasks/Tracks/AliAnalysisTaskEmcalJetEnergySpectrum.cxx
- PWGJE/EMCALJetTasks/Tracks/AliAnalysisTaskEmcalJetEnergySpectrum.h
Downscale weight always taken from the CENT cluster
(weights same for the CENTNOTRD cluster for EMCAL
triggers) - CALOFAST/PLUS clusters currently not
supported.
> Add downscale weight to spectrum task

- PWG/EMCAL/EMCALbase/AliEMCALRecoUtils.cxx
- PWG/EMCAL/EMCALbase/AliEMCALRecoUtils.h
- PWGGA/CaloTrackCorrelations/macros/ana.C
In case of matching of TPC only tracks and old MCs/Data (not checked in new) the use of track DCA gives large eta residual.
> Add option to use Track DCA cut also on FindMatches like in base class extrapolation method

- PWGHF/vertexingHF/AliAnalysisTaskSELc2V0bachelorTMVAApp.cxx
Deletion of secondary vtx within task caused segfault when trying to run multiple wagons of the task on the same train; removing these two lines.
The memory leak these lines were meant to fix can be fixed instead using AliAnalysisTaskSECleanupVertexingHF as the final wagon on the train.
> fix to pointer handling in Lc TMVAApp task

- PWG/EMCAL/EMCALbase/AliAnalysisTaskEmcal.cxx
- PWG/EMCAL/EMCALbase/AliAnalysisTaskEmcal.h
Old builtin event selection is moved to
IsEventSelectedInternal and needs to be
enabled explicitly. Event selection contains
- Trigger selection (in AliAnalysisTaskEmcal
or inheriting - not handled by AliEventCuts)
- MC outlier removal
- Event selection by the AliEventCuts
Old optional event cuts (number of tracks in
acceptance, event plane orientation) are
only accessible in the old event selection
and are not (yet) ported to the new one based
on AliEventCuts.
> Use AliEventCuts object by default in IsEventSelected

- PWGJE/EMCALJetTasks/UserTasks/AliAnalysisTaskEmcalJetPerformance.cxx
> JetPerformance: Include only EMCal in cell nonlinearity determination

- PWG/EMCAL/EMCALbase/AliAnalysisTaskEmcal.cxx
Adding the event cut object introduced a segfault
in the merging in the destructor of AliEventCuts
for several EMCAL framework users. In order to
circumvent this the histograms are stored directly
in the EMCAL list. This also restores the behaviour
of the internal event selection in which the cut
histograms are stored directly in the EMCAL list.
> Adding event cut historgrams directly to EMCAL list

- PWGGA/GammaConv/AliAnalysisTaskConvJet.cxx
Changed name of output container so more jetfinders can be run alongside in a train
> PWGGA/GammaConv Changed name of output container

- PWG/EMCAL/EMCALbase/AliAnalysisTaskEmcal.cxx
- PWG/EMCAL/EMCALbase/AliAnalysisTaskEmcal.h
- PWG/JETFW/CMakeLists.txt
- PWGJE/EMCALJetTasks/UserTasks/AliAnalysisTaskEmcalJetHCorrelations.cxx
- PWGJE/EMCALJetTasks/UserTasks/AliAnalysisTaskEmcalJetHPerformance.cxx
- PWGJE/FlavourJetTasks/CMakeLists.txt
In order to allow for user-configured event cuts
objects (in the AddTask) an option to set the
event cut object is added. In case of a valid event
cuts object the object is not constructed any
more in the ExecOnce part but only the histograms
are added to the output list. Option sets usage
of internal event selection to false.
> Add option to set a user-configured event cuts object

- PWGHF/jetsHF/AliAnalysisTaskHFJetIPQA.cxx
- PWGHF/jetsHF/AliAnalysisTaskHFJetIPQA.h
- PWGHF/jetsHF/macros/AddTaskHFJetIPQA.C
- add TCanvas which documents cut and correction setup
- add switches for corrections (fDoMCCorrection, fDoUnderlyingEventSub)
- assign second output slot to setup canvas
- combine all cuts in array fAnalysisCuts
- comment out functions which are not in use (GetMonteCarloCorrectionFactor, FillParticleCompositionEvent, GetOutOfJetParticleComposition)
> AnalysisTaskHFJetIPQA: Add Setup Canvas

- PWGHF/jetsHF/CMakeLists.txt
AliAnalysisTaskLocalRho.h was missing from PWGHF/jetsHF/AliAnalysisTaskDJetCorrelations.cxx for some. Path included in PWGHF/jetsHF/CMakeLists.txt
> jira:ALPHY-89. Missing path included in jetsHF/CMakeLists 

- PWGDQ/dielectron/core/AliDielectronVarManager.h
- PWGDQ/reducedTree/AliAnalysisTaskReducedTreeMaker.cxx
- PWGDQ/reducedTree/AliAnalysisTaskReducedTreeMaker.h
- PWGDQ/reducedTree/AliReducedEventInfo.h
- PWGDQ/reducedTree/AliReducedEventPlaneInfo.cxx
- PWGDQ/reducedTree/AliReducedVarManager.cxx
- PWGDQ/reducedTree/AliReducedVarManager.h
Changes:
1) Added support such that V0 candidates from AODs are also written to trees.
K0s and conversions were tested ok. Lambda and anti-Lambda candidates still problematic.
2) Q-vector from the TPC for the 1st,2nd and 3rd harmonics are precomputed in the tree maker using user specified track selection. The Q vector is written in the event plane object stored in the event class.
3) Instantaneous luminosity as extracted from OCDB is implemented in the VarManager and can be plotted optionally.
4) Small fixes
> Main changes: support for V0 candidates in AOD; compute TPC event plane;

- PWGPP/ITS/AliAnalysisTaskSEImpParResSparse.cxx
- PWGPP/ITS/AliAnalysisTaskSEImpParResSparse.h
- PWGPP/macros/AddTaskImpParResSparse.C
When the ith flag is switched off, the ith THnSparse is neither created nor filled.
To guarantee backward compatibility, the default values for all these flags is kTRUE, namely the THnSparses are all created and filled
> Flags for THnSparse creation and filling implemented

- PWGCF/FEMTOSCOPY/FemtoDream/AliAnalysisTaskOtonOmega.cxx
- PWGCF/FEMTOSCOPY/FemtoDream/AliAnalysisTaskOtonOmega.h
- PWGCF/FEMTOSCOPY/FemtoDream/AliOtonOmegaAnalysis.cxx
- PWGCF/FEMTOSCOPY/FemtoDream/AliOtonOmegaAnalysis.h
- PWGCF/FEMTOSCOPY/FemtoDream/AliOtonOmegaCascade.cxx
- PWGCF/FEMTOSCOPY/FemtoDream/AliOtonOmegaCascade.h
- PWGCF/FEMTOSCOPY/FemtoDream/AliOtonOmegaCascadeCuts.cxx
- PWGCF/FEMTOSCOPY/FemtoDream/AliOtonOmegaCascadeCuts.h
- PWGCF/FEMTOSCOPY/FemtoDream/CMakeLists.txt
- PWGCF/FEMTOSCOPY/FemtoDream/PWGCFFemtoDreamLinkDef.h
- PWGCF/FEMTOSCOPY/macros/AddTaskOtonOmega.C
- PWGCF/FEMTOSCOPY/macros/ConfigOtonOmega.C
-Added tasks and classes based in the FemtoDream code.
-Now Xi and Omega are treated independently and can be directed into the otuput.
-Config File added so the AddTask can be set via alien.
-Tree for Xi and Omega selection added as additional output.
> New Tasks and Classes for proton-Omega femto analysis.

- PWGCF/FEMTOSCOPY/AliFemtoUser/AliFemtoModelCorrFctnTrueQ3DByParent.cxx
Hi,
This fix a compilation error on MacOS Mojave (see below). If the fix is done in the right direction, can you merge it please?
@dberzano, I thought there were a continuous integration also done on macOS platform? Or maybe this is only for O2? Just wondering why this error didn't get catch when introduced (PR #8244).
Cheers,
Philippe
---
DEBUG:AliPhysics:AliPhysics:devphys: /Users/PILLOT/Work/Alice/sw/SOURCES/AliPhysics/devphys/0/PWGCF/FEMTOSCOPY/AliFemtoUser/AliFemtoModelCorrFctnTrueQ3DByParent.cxx:65:35: error: non-constant-expression cannot be narrowed from type 'UInt_t' (aka 'unsigned int') to 'std::__1::array<int, 4>::value_type' (aka 'int') in initializer list [-Wc++11-narrowing]
DEBUG:AliPhysics:AliPhysics:devphys:   std::array<Int_t, 4> nbins_v = {static_cast<UInt_t>(par_nbins * …
> fix incorrect cast from UInt_t to Int_t

- PWGHF/vertexingHF/macros/AddTaskDs.C
[minor] Adds check in D_s AddTask that makes sure cut object is pulled from ROOT file correctly before constructing.
Without this, constructor segfaults without a useful error due to the cut object being a null pointer, if the file exists but doesn't contain the right cut object.
> add graceful check for cut object in Ds addtask

- PWG/EMCAL/EMCALbase/AliEmcalList.cxx
- PWG/EMCAL/EMCALbase/CMakeLists.txt
When built with RooUnfold support AliEmcalList
support scaled merging of the RooUnfoldResponse
objects it contains. In absense of a Scale
function in RooUnfoldResponse the internal
histograms need to be scaled manually.
> Addig RooUnfold support to AliEmcalList

- PWGHF/vertexingHF/AliAnalysisTaskSEDStarSpectra.cxx
The commit o f the PreSelect function for Dstar, broke the code for pp and pPb. Added two possibilities now to get the D0 candidate, for when candidate is filled vs not filled. Tested for all three systems
> PWGHF: Fix pp/pPb bug for Dstar introduced by PreSelect

- PWGJE/EMCALJetTasks/Tracks/AliAnalysisTaskEmcalJetSubstructureTree.cxx
- PWGJE/EMCALJetTasks/Tracks/AliAnalysisTaskEmcalSoftDropResponse.cxx
- PWGJE/EMCALJetTasks/UserTasks/AliAnalysisTaskEmcalJetShapesMC.cxx
- PWGJE/EMCALJetTasks/UserTasks/AliAnalysisTaskRecoilJetYield.cxx
Interface change in Recluster for the new fastjet
version, which moved from the namespace fastjet::contrib
to the namespace fastjet. Affected are only classes
directly accessing the SoftDrop.
> Adapt build cases for Fastjet 3.3.2 and 3.2.1

- PWGGA/GammaConv/AliAnalysisTaskNeutralMesonToPiPlPiMiNeutralMeson.cxx
- PWGGA/GammaConv/AliAnalysisTaskNeutralMesonToPiPlPiMiNeutralMeson.h
- Adding more kinematic histograms (pt, eta, phi) for the
heavy meson and its decay products at various steps
(all, in channel, reconstrutible, reconstructed)
- Fix indentation in various places
- Modernize: Use nullptr instead of NULL
> PWGGA/GammaConv: Adding more kinenmatic histograms for MC truth

- PWGLF/SPECTRA/CMakeLists.txt
- PWGLF/SPECTRA/PWGLFspectraLinkDef.h
- PWGLF/SPECTRA/PiKaPr/TPCTOFCascades/AddAnalysisTaskTPCTOFCascade.C
- PWGLF/SPECTRA/PiKaPr/TPCTOFCascades/AliAnalysisPIDCascade.cxx
- PWGLF/SPECTRA/PiKaPr/TPCTOFCascades/AliAnalysisPIDCascade.h
- PWGLF/SPECTRA/PiKaPr/TPCTOFCascades/AliAnalysisTaskTPCTOFCascade.cxx
- PWGLF/SPECTRA/PiKaPr/TPCTOFCascades/AliAnalysisTaskTPCTOFCascade.h
Implementation for a new analysis task that handles Cascade particles (Xi & Omega) for the analysis of identified charged particles Vs multiplicity and spherocity.
The pathway for the new analysis task i preliminary set as: "AliPhysics/PWGLF/SPECTRA/PiKaPr/TPCTOFCascades". 
The code works as an extension, with additional corrections & minor bug fixes, to the analysis task found in "AliPhysics/PWGLF/SPECTRA/PiKaPr/TPCTOFfits"
The output is stored into  trees that are later used for more precise post-processing.
I've as of posting this managed to compile AliPhysics successfully, as well as a successful local train test.
> New Analysis Task for including Cascades for the PID Hadrons Vs Spherocity & Multiplicity

- PWGCF/FEMTOSCOPY/FemtoDream/AliFemtoDreamCollConfig.cxx
Sets default to false for all pairs in order not to cause a segmentation violation
> Changed default to false in AliFemtoDreamCollection

- PWGHF/treeHF/AliAnalysisTaskSEHFTreeCreator.cxx
Fixing two bugs:
* When no particle TTrees were enabled, the task crashed because the event selection cuts were not initialised.
* Because of a copy-paste mistake, the Ds, D+, and Dstar couldn't be run standalone.
> PWGHF: MVA, Fix for running mesons separate

- PWGHF/treeHF/AliAnalysisTaskSEHFTreeCreator.cxx
Change PID selection check to use the IsSelected function , rather than the more specific IsSelectedPID which incorrectly uses Nsigma PID
Switch off PID before checking topological cuts
> fix PID selection bugs

- PWG/EMCAL/EMCALbase/AliEmcalList.cxx
- PWG/EMCAL/EMCALbase/AliEmcalList.h
Check for scale object support outsourced to new function.
This allows to add RooUnfoldResponse to the supported
object types including the check whether AliPhysics was
built with RooUnfold support.
> [RooUnfold] Improve check for scale object support

- PWGHF/treeHF/AliAnalysisTaskSEHFTreeCreator.cxx
- PWGHF/treeHF/AliAnalysisTaskSEHFTreeCreator.h
Full fix of the memory leak. Just adding 'delete evCuts' was not enough, as some of the destructors in the AliRDHFCuts derived classes are missing
> PWGHF: MVA, Adding evCuts as class variable

- PWG/EMCAL/EMCALtasks/AliEmcalFastOrMonitorTask.cxx
- PWG/EMCAL/EMCALtasks/AliEmcalFastOrMonitorTask.h
Event selection and event loop ported to IsEventSelected
and Run methods of AliAnalysisTaskEmcal, so the logics
doesn't change. Output object changes from TList to
AliEmcalList. Adds filling the weighting histograms
and therefore allows running on jet-jet Monte-Carlos.
> Make AliEmcalFastOrMonitor inheriting from AliAnalysisTaskEmcal

- PWGJE/EMCALJetTasks/UserTasks/AliAnalysisTaskEmcalJetPerformance.cxx
- PWGJE/EMCALJetTasks/UserTasks/AliAnalysisTaskEmcalJetPerformance.h
@jdmulligan these are the proposed changes
> Add possibility to cut on det-lvl jet pT to clean up false matches in RM

- PWGPP/AliPIDtools.cxx
- PWGPP/AliPIDtools.h
- PWGPP/CMakeLists.txt
- PWGPP/PWGPPLinkDef.h
* Register PID object for given production
````
Int_t hash= AliPIDtools::LoadPID(246751,1,"pass1",0);
````
* Use function in TFormula
````
TF1 * fbb = new TF1("fbb",Form("AliPIDtools::BetheBlochAleph(%d,x)",hash),1,100);
fbb->SetNpx(1000); fbb->Draw();
````
* Or TTreeFormula
esdTree->SetAlias("dEdxExpPion",Form("AliPIDtools::BetheBlochAleph(%d,Tracks[].fIp.P()/%f)",hash,massPion))
esdTree->Draw("Tracks[].fTPCsignal:dEdxExpPion");
````
> #ATO-452 - add AliPIDtools to enable AliPID in TFormula and TTreeFormula

- PWGHF/vertexingHF/AliAnalysisTaskSELc2V0bachelorTMVAApp.cxx
- PWGHF/vertexingHF/AliAnalysisTaskSELc2V0bachelorTMVAApp.h
The concerned histograms are the 2D with the BDT variables vs BDT response.
They are needed for debugging purposes, and take a lot of memory.
In this commit, also the number of bins was decreased.
> Some histograms are not optional (debug mode)

- PWG/EMCAL/EMCALbase/AliEmcalTrackSelResultCombined.cxx
- PWG/EMCAL/EMCALbase/AliEmcalTrackSelResultCombined.h
- PWG/EMCAL/EMCALbase/AliEmcalTrackSelectionAOD.cxx
- PWG/EMCAL/EMCALbase/PWGEMCALbaseLinkDef.h
TClonesArray is a very inefficient object for the underlying
user storage. Usage of std::vector improves performance by almost
factor 2.
> Use vector as internal storage for combined track selection results

- PWG/EMCAL/EMCALbase/AliAnalysisTaskEmcalLight.cxx
- PWG/EMCAL/EMCALbase/AliAnalysisTaskEmcalLight.h
- PWG/EMCAL/EMCALbase/AliEmcalList.cxx
- PWG/EMCAL/EMCALbase/AliEmcalList.h
Adding option to use the AliEmcalList in AliAnalysisTaskEmcalLight
instead of TList. Usage of the AliEmcalList allows for automatic
scaling in the last merging level. AliAnalysisTaskEmcalLight forwards
its scaling histograms, named slightly different than the ones in
AliAnalysisTaskEmcal, to the AliEmcalList.
The option can be switched in via SetUseAliEmcalList.
> Allow usage of AliEmcalList in AliAnalysisTaskEmcalLight

- PWGJE/EMCALJetTasks/Tracks/AliAnalysisTaskEmcalJetEnergyScale.cxx
- PWGJE/EMCALJetTasks/Tracks/AliAnalysisTaskEmcalJetEnergyScale.h
Splitting done as additional dimension in the THnSparse
filled with 0 or 1,  where the tag is assigned based on
uniform random sampling. By default 80% of the jets
are used for the response matrix and 20% for the prior
spectrum.
> Add splitting of the response matrix for MC closure test

- PWG/EMCAL/EMCALtasks/AliEmcalCorrectionCellEnergy.cxx
- PWG/EMCAL/EMCALtasks/AliEmcalCorrectionCellEnergy.h
- PWG/EMCAL/config/AliEmcalCorrectionConfiguration.yaml
- PWG/EMCAL/macros/AddTaskEMCALTender.C
- PWGGA/CaloTrackCorrelations/yaml/EMCalCorrConfig_Data_ClV1_Run2TCalib.yaml
- PWGGA/CaloTrackCorrelations/yaml/EMCalCorrConfig_Data_ClV2_Run2TCalib.yaml
- TENDER/TenderSupplies/AliEMCALTenderSupply.cxx
- TENDER/TenderSupplies/AliEMCALTenderSupply.h
The new temperature calibration parameters are also available for Run1 data. The previously implemented switch only allowed for these parameters to be used in Run2.
The switch has therefore now been renamed to "enableNewTempCalib" in the YAML file and "useNewRWTempCalib" in the AddTaskEMCALTender.
Once these changes are approved, it will also be announced via mail that any existing yaml configuration files should be adjusted for the renamed parameter (otherwise the traintests will crash).
> PWG/EMCAL: Added switch for new temperature calibration to also be used in Run1 data

- PWG/EMCAL/EMCALbase/AliEmcalContainer.cxx
- PWG/EMCAL/EMCALbase/AliEmcalContainer.h
- PWG/EMCAL/EMCALbase/AliEmcalContainerUtils.h
- PWG/EMCAL/EMCALbase/AliEmcalESDHybridTrackCuts.cxx
- PWG/EMCAL/EMCALbase/AliEmcalESDHybridTrackCuts.h
- PWG/Tools/THistManager.h
Obviously the include of AliEmcalIterableContainer.h
in the AliEmcalContainer header file confused doxygen
and prevented the documentation of this class from
being created. The `\cond CLASSIMP` block around
forced doxygen to ignore the include and fixed the
documentation.
In addition
- Move consistently the documentation of AliEmcalContainer
from the cxx file to the header file
- Add documentation for Set/GetIsEmbedding
- Fix @class/@namespace tag in AliEmcalContainerUtils
- Fix title for @defgroup Histmanager
> [Doxygen] Fix handling of AliEmcalContainer in doxygen

- PWGCF/FEMTOSCOPY/FemtoDream/AliFemtoDreamZVtxMultContainer.cxx
Fixes a bug. Instead of using ((dPhiMin)^2 + (dEtaMin)^2)^2 it uses as intended (dPhiMin)^2 + (dEtaMin)^2
> changes the close pair rejection criterium to the radius

- PWGGA/GammaConv/AliAnalysisTaskNeutralMesonToPiPlPiMiNeutralMeson.cxx
Exlcusion was formulated in a postive way, so
operator must be "==" instead of "!="
> Fix exclusion of Dalitz decays

- PWGJE/EMCALJetTasks/macros/JetQA/scalePtHardHistos.py
(update to post-processing script)
@efranzis With this change I am able to successfully scale pt-hard bins in alidock
> JetQA: Fix memory leak in pt-hard scaling script

- PWG/EMCAL/EMCALbase/AliAnalysisTaskEmcal.cxx
Regardless of the state of the builtin event selection, we need to be able to track when embedded events are recycled. Therefore, the rejection histogram must always be defined.
@mfasDa - Are you okay with this modification?
> Fix crash when recycling embedded events

- PWGCF/FEMTOSCOPY/FemtoDream/AliFemtoDreamCollConfig.cxx
- PWGCF/FEMTOSCOPY/macros/AddTaskFemtoDreamSysVar.C
Before fWhichQA was wrongly used to do so. Additionally removes unnecessary  arguments from the Systematics task
> Uses the correct number of pairs for Close pair rejection

- PWG/JETFW/AliJetContainer.h
- PWGJE/EMCALJetTasks/Tracks/AliAnalysisTaskEmcalJetEnergyScale.cxx
- One histogram with ptpart, ptdet and status code
(0 - all, 1 - tagged, 2 - accepted)
- Loop over all part. jets in acceptance
Adding also the information whether the particle
level jet was in the fiducial acceptance of the
detector level jet to the response matrix.
> Change histogram for jet finding efficiency

- PWGDQ/dielectron/macrosLMEE/AddTaskSimpleTreeMaker.C
All cut sets use the same event cuts, so, for clarity, now the event cut function doesn't take an argument.
> Update SimpleTree AddTask

- PWG/EMCAL/EMCALtasks/AliEmcalMCTrackSelector.cxx
- PWG/EMCAL/EMCALtasks/AliEmcalMCTrackSelector.h
- PWGJE/EMCALJetTasks/Tracks/AliAnalysisTaskEmcalOutliersGen.cxx
Use AliEmcalMCTrackSelector in order to reject photons
that are the mothers of other photons. The track selector
task needs to run in this case also for AOD analyses
as otherwise it cannot be guaranteed that the mother
photons are removed before.
> [WIP] Workaround for photon double counting issue in PYTHIA8

- PWG/EMCAL/EMCALbase/AliAnalysisTaskEmcalEmbeddingHelper.cxx
- PWG/EMCAL/EMCALbase/AliAnalysisTaskEmcalEmbeddingHelper.h
- PWG/EMCAL/READMEemcEmbedding.txt
If other analysis tasks have broader physics selections than the embedding helper, then those other tasks can access an already used embedding event when the task is selected and the embedding helper isn't. To address this, the embedding helper will checks the other tasks connected to the analysis manager and throws an error if:
- The internal physics selection is broader than the embedding helper physics selection.
- Any other task has a broader physics selection than the embedding helper.
This should ensure that the are no events should are selected for other tasks, but not the embedding helper. It will now also require explicit configuration of the internal physics selection if not using the automatic physics selection from AliEventCuts. This will ensure that it isn't changed …
> EMCal Embed: Validate physics selection

- PWGHF/treeHF/AliAnalysisTaskSEHFTreeCreator.cxx
- PWGHF/treeHF/AliAnalysisTaskSEHFTreeCreator.h
- PWGHF/treeHF/AliJetTreeHandler.cxx
- PWGHF/treeHF/AliJetTreeHandler.h
- PWGHF/treeHF/CMakeLists.txt
- PWGHF/treeHF/PWGHFtreeHFLinkDef.h
- PWGHF/treeHF/macros/AddTaskHFTreeCreator.C
WIP: Please do not approve yet.
@ginnocen, @nzardosh, @fgrosa, @lvermunt,
Please have a look at this first draft of the jet tree. The jet info itself is minimal at this point (pT, eta, phi, etc.), but the infrastructure is there to easily add more.
The basic idea is as follows: One should run a `JetFinder` task before the `TreeCreator` task (which will write a jet array to the InputEvent), and then in `TreeCreator::AddTask` one should add a line to attach a jet container corresponding to that jet array. This mimics the standard workflow in ALICE jet framework -- the idea of the jet container is to automatically handle access to the jet array, and to provide a configurable set of cuts. The `JetTreeHandler` will then construct a std::vector of all of the jets (subject to whatever criteria …
> Initial draft of jet tree for HFtree framework

- PWGGA/GammaConv/AliAnalysisTaskGammaCalo.cxx
- PWGGA/GammaConv/AliAnalysisTaskGammaCalo.h
- PWGGA/GammaConv/AliAnalysisTaskGammaConvCalo.cxx
- PWGGA/GammaConv/macros/AddTask_GammaCalo_pp.C
this allows for a Pi0 only analysis with reduced memory consumption compared to the normal pi0+eta analysis.
> PWGGA/GammaConv: Introduced Pi0Only mode in GammaCalo task

- PWG/EMCAL/EMCALtasks/AliEmcalFastOrMonitorTask.cxx
Correlation plot done vs. FastOR Abs ID. Plot is sensitive
to bitflips in the communication between STU and TRU.
> Adding correlation betwen L0 and L1 amplitude

- PWGUD/UPC/AliAnalysisTaskUPCforwardMC.cxx
- PWGUD/UPC/AliAnalysisTaskUPCforwardMC.h
Added bin migration matrix and code for the helicity analysis of J/Psi. The concerned files are those of the MC study, hence AliAnalysisTaskUPCforwardMC.{h, cxx}. 
IMPORTANT: the code has been tested on local. The bin migration trend is linear as expected, possibly very mild bin migration effect in Coherent J/Psi to dimuon.
> PWGUD/UPC: Added bin migration matrix and code for the helicity analysis of J/Psi.

- PWGLF/RESONANCES/Xi1530/AliAnalysisTaskXi1530.cxx
- PWGLF/RESONANCES/Xi1530/AliAnalysisTaskXi1530.h
When fill multiplicity(centrality) to the THnSparse, it looks it has a bug to find the bin.
It has been affected to study HM data.
Now, adding (double) to each fCent will prevent the issue.
Code reformed by "Chromium" style
> Explicitly declare fCent as a Double/Code reform

- PWGJE/EMCALJetTasks/UserTasks/AliAnalysisTaskEmcalJetHPerformance.cxx
- PWGJE/EMCALJetTasks/UserTasks/AliAnalysisTaskEmcalJetHPerformance.h
Allows us to keep track of rare doubly corrected embedded events
> Store previous event selection and embedded status

- PWGJE/EMCALJetTasks/UserTasks/AliAnalysisTaskEmcalJetTagger.cxx
- PWGJE/EMCALJetTasks/UserTasks/AliAnalysisTaskEmcalJetTagger.h
Acceptance margins are added to the acceptance
cuts in eta and phi to the jet containers depending
on the acceptance types (default: 0.1)
> Add option for defining acceptance margins

- PWGPP/TPC/AliTPCcalibResidualPID.cxx
- PWGPP/TPC/AliTPCcalibResidualPID.h
Fixing warnings (wrong initialisation order, non-explicit conversion from Int_t to Double_t)
> Fixing warnings breaking compilation on macOS

- PWGUD/UPC/AliAnalysisTaskUPCforward.cxx
- PWGUD/UPC/AliAnalysisTaskUPCforward.h
- PWGUD/UPC/AliAnalysisTaskUPCforwardMC.cxx
- PWGUD/UPC/AliAnalysisTaskUPCforwardMC.h
Changes involve my analysis tasks, so AliAnalysisTaskUPCforward{MC}.{ h. cxx }. Added the rapidity study for the helicity of the J/Psi. This is to check whether there are scarcely populated regions in acceptance and potentially exclude them for the analysis. Preliminary studies on a small sample on local actually show that this is the case... Added the properly set code enabling the creation of the templates for the Pt-distribution fits.
IMPORTANT: the code has been tested on local, both tasks compile and yield the expected results. The entries for the rapidity study properly add up to the rapidity integrated case...
> PWGUD/UPC: Added rapidity study for helicity J/Psi and templates for Pt-fit.

- PWGHF/jetsHF/AliAnalysisTaskHFJetIPQA.cxx
- PWGHF/jetsHF/AliAnalysisTaskHFJetIPQA.h
- PWGHF/jetsHF/macros/AddTaskHFJetIPQA.C
…our definition:
- ROOT6 compatibility
- add possibility to ask for matching of flavour that defines the jet with mother of particles that have been clustered by the jet finder
* save all jet constitutens in  fJetCont
* loop over MC particles, and ask whether daughters correspond to jet constituents
* if not store daughter label and original flavour in map daughtermothers and compare all following particles
* if matching found, continue as with former method
- add flags for setting minimal numbers of jet constituents (fNoJetConstituents), cut on difference between daughter particle and jet axis (fDaughtersRadius), use matching of flavour to particles within jet cluster (fDoFlavourMatching)
- consider IP distributions seperately for strangeness and u-/d- quarks, add corresponding …
>  AliAnalysisTaskHFJetIPQA: open up different probabilities of jet flavour definitions 

- PWGUD/UPC/AliAnalysisTaskUPCforward.h
- PWGUD/UPC/AliAnalysisTaskUPCforwardMC.cxx
- PWGUD/UPC/AliAnalysisTaskUPCforwardMC.h
Due to issues with the LEGO trains, increased all the streamers, and eliminated the usage of the incriminated vectors. Only kept those related to good quality runs, considering their modest size (vectors of ~200 doubles). 
IMPORTANT: this code has been tested on local. The MC class has the exact same output as the version before on the small data sample I am using for tests. It is possible that the issues were due to the massive size of the vectors when analysing MC, considering that ~10^7 reconstructed UPC events are expected each time on the full LHC18l7 simulations...
> PWGUD/UPC: Increased streamers. Eliminated the usage of problematic vectors.

- PWGCF/Correlations/DPhi/AliAnalysisTaskDiHadCorrelHighPt.cxx
- PWGCF/Correlations/DPhi/AliAnalysisTaskDiHadCorrelHighPt.h
add variables which enable to run hh, V0h, hV0 analyses separately,
remove the aucorrelations in hh coming from the same V0 and by Lam-h coming the same cascade, new variable with possibility to change the filterbit
> Changes in AliAnalysisTaskDiHadCorrelHighPt

- PWGUD/UPC/AliAnalysisTaskUPCforward.cxx
- PWGUD/UPC/AliAnalysisTaskUPCforward.h
- PWGUD/UPC/AliAnalysisTaskUPCforwardMC.cxx
- PWGUD/UPC/AliAnalysisTaskUPCforwardMC.h
Now both the Collins-Soper and the Helicity Frame are added together, both cos(theta) and phi. This way we could possibly investigate changes for the two different parametrizations...
In addition, added calibration for the ZDC energies for the LHC15O period. Getting ready to analyze even the 2015 data! This way it would be possible to verify the pedestal peak in the ZNC/A energy plots... Incremented streamers in both analyses tasks.
IMPORTANT: this code has been tested on local. Results as expected. No vectors this time, so it should work on the first try even in the LEGO trains...
Thanks.
Regards.
> PWGUD/UPC: Added Collins-Soper and Helicity Frames for helicity J/Psi.

- PWGHF/vertexingHF/charmFlow/AliAnalysisTaskSECharmHadronvn.cxx
- PWGHF/vertexingHF/charmFlow/AliAnalysisTaskSECharmHadronvn.h
- PWGHF/vertexingHF/charmFlow/AliHFQnVectorHandler.cxx
- PWGHF/vertexingHF/charmFlow/AliHFQnVectorHandler.h
1) add method to introduce eta gap between resolution sub-events
2) add method to remove daughter tracks from qn (1: remove daughter tracks of selected candidate, 2: remove daughter tracks of all the candidates in the selected event)
3) add method to perform random downsampling of tracks from qn
The three methods can be called together.
>  Add methods to introduce eta gaps, and remove tracks from qn

- PWGHF/vertexingHF/charmFlow/CharmHadronVnAnalysis.C
- PWGHF/vertexingHF/charmFlow/config_Dplus_v2_unbiased.yml
1) add variable-width mass binning for vn vs. mass
2) add parameters in config file for vn vs. mass:
- flag to fix mean in vn vs. mass
- flag to fix sigma in vn vs. mass
- limits of the variable mass binning for vn vs. mass
> Add variable-width mass binning for vn vs. mass

- PWGUD/UPC/AliAnalysisTaskUPCforward.cxx
- PWGUD/UPC/AliAnalysisTaskUPCforward.h
- PWGUD/UPC/AliAnalysisTaskUPCforwardMC.h
As asked by the UPC PAG, I am getting ready to analyze 2015 data too. The run selection for 2015 data has been taken from the analysis note of the coherent J/Psi. 
Given the great concern related to the ZDC plots, histograms related to the ZDC energy without the timing selection have been applied. These changes involve only the AliAnalysisTaskUPCforward.{h, cxx}.
IMPORTANT: this code has been tested on local. It works fine but now the vector containing the run numbers is starting to be big (~400 integers). Hopefully this won't be a problem on the LEGO trains. This is not scalable but again, it is not like I am expecting to add more runs...
> PWGUD/UPC: Added run selection for 2015 data. Added ZDC plots before timing selec.

- PWGHF/vertexingHF/AliAnalysisTaskSED0Mass.cxx
- PWGHF/vertexingHF/AliAnalysisTaskSED0Mass.h
Add flag to select out-of-bunch pile-up events only. This flag will be used to cross-check the pile-up events for the D-meson analyses.
> Add flag to select pile-up events only

- PWGGA/GammaConv/AliAODConversionPhoton.cxx
- PWGGA/GammaConv/AliAODConversionPhoton.h
- PWGGA/GammaConv/AliAnalysisTaskGammaCaloMerged.cxx
- PWGGA/GammaConv/AliAnalysisTaskGammaCaloMerged.h
As multiple true pi0 can be in a merged cluster, an additional counter and histogram are introduced for the merged cluster analysis.
The histogram is filled with the additional true pi0 that are found in the cluster.
Furthermore, the ESD part of SetCaloPhotonMCFlags was optimized for readability.
> PWGGA/GammaConv: Added pi0 in cluster counter for mEDC and beautified SetCaloPhotonMCFlags

- PWGHF/treeHF/AliAnalysisTaskSEHFTreeCreator.cxx
- PWGHF/treeHF/AliAnalysisTaskSEHFTreeCreator.h
- PWGHF/treeHF/AliJetTreeHandler.cxx
- PWGHF/treeHF/AliJetTreeHandler.h
Implement option in JetTree to store info for all track constituents within the jet. The structure is to store flat std::vector for all track variables per event (i.e. trackPt, trackEta, trackPhi), as well as a flat std::vector of the number of tracks per jet.
I also implement in this PR an optional cut to require minPt on background-subtracted jet pT (useful for PbPb). 
@ginnocen, @nzardosh, @fgrosa, @lvermunt
> treeHF/JetTree: Allow to store all tracks in jet

- PWGGA/GammaConv/AliAnalysisTaskGammaCaloMerged.cxx
- PWGGA/GammaConv/AliAnalysisTaskGammaCaloMerged.h
Double counting has been optimized for the multiple pi0 in a single cluster treatment.
In addition a crash protection in case mother pT = 0 has been added.
> PWGGA/GammaConv: Better mEDC treatment for multiple pi0 in cluster 

- PWGLF/SPECTRA/Spherocity/AliSpherocityEstimator.cxx
- PWGLF/SPECTRA/Spherocity/AliSpherocityEstimator.h
AliSpherocityEstimator now works with AOD tracks too (note one has to set the filterbit manually to enable the AOD flag). Added default value for fMinPt cut in the default constructor.
> Addind AOD compatibility to AliSpherocotyEstimator

- OADB/COMMON/MULTIPLICITY/AliMultSelectionCalibratorMC.cxx
- PWGLF/STRANGENESS/Cascades/Run2/AliAnalysisTaskWeakDecayVertexer.cxx
- Supercalib fix applied to MultSelection MC calibrator task (mundane bug) 
- Changed defaults for weak decay finding - these were set to loose after a PWG-LF discussion but if this finder is used systematically then better set to a compromise between loose and (too) tight to conserve computing power
> Cent supercalib fix, better defaults for weak dec finder

- PWGUD/UPC/AliAnalysisTaskUPCforward.cxx
- PWGUD/UPC/AliAnalysisTaskUPCforward.h
- PWGUD/UPC/AliAnalysisTaskUPCforwardMC.cxx
- PWGUD/UPC/AliAnalysisTaskUPCforwardMC.h
Added the Y-dependent helicity analysis both for the Helicity frame and the Colin-Soper helicity frame. Changed the ZNC and ZNA energy threshold values for the differential neutron emission analysis. This way the 0N0N, XN0N, 0NXN, XNXN invariant mass plots would become available.
TESTED
> PWGUD/UPC: Y-dependent helicity analysis + neutron emission analysis

- PWGGA/CaloTrackCorrelations/macros/AddTaskIsoPhoton.C
remove compilation warnings due to unused parameters
> fix eOverP cut not passed to isolation in cone tracks

- TENDER/TenderSupplies/AliEMCALTenderSupply.cxx
Some time ago, there was a commit that removed the MC energy fractions from the standard output of the Tender, see https://github.com/alisw/AliPhysics/commit/2f73f2c9d567be9d01552e3c6c52090622fa8f22#diff-ce4c5e3ee3cdb974ac13f17ca80cbf21 
As this is rather crucial information and the boolean fSetCellMCLabelFromEdepFrac also modifies the information stored in these fractions, i would highly recommend to add the fractions back to the output.
Maybe @gconesab knows why this was put behind the if() condition.
> TENDER/TenderSupplies: Re-added the MC energy fractions per label to the output

- PWGGA/GammaConv/AliAODConversionPhoton.cxx
- PWGGA/GammaConv/AliAODConversionPhoton.h
- PWGGA/GammaConv/AliAnalysisTaskGammaCaloMerged.cxx
- PWGGA/GammaConv/AliAnalysisTaskGammaCaloMerged.h
- PWGGA/GammaConv/macros/AddTask_ClusterQA.C
This PR provides a better MC treatment for the merged cluster analysis. 
The main change is that one now has access to all MC pi0s that contributed to a cluster as well as the leading pi0 whose daughters deposited the most energy. Everything that was added is well protected by the "mergedAnalysis" boolean which is only set in the merged analysis task.
The changes to the merged analysis task involve the treatment of multiple pi0s in one cluster where a new histogram is filled with all true MC pi0s that could never be reconstructed due to overlap in a cluster. Extensive comments in the code were added to ensure proper documentation of the changes.
> PWGGA/GammaConv: Added mult. pi0 treatment and cluster energy fraction per MC label for mEDC

- PWGLF/SPECTRA/ChargedHadrons/dNdPt/AlidNdPtAnalysis.cxx
- PWGLF/SPECTRA/ChargedHadrons/dNdPt/AlidNdPtAnalysispPb.cxx
Cast conversion to avoid narrowing conversion error while compiling in new MacOS (10.14.4) and Xcode (10.2)
> Fix narrowing conversion error in new  MacOS

- OADB/COMMON/MULTIPLICITY/AliMultSelectionCalibratorMC.cxx
- OADB/COMMON/MULTIPLICITY/AliMultSelectionCalibratorMC.h
Implements a map that allows the MC calibrator steering macro to define a highest-threshold for the V0M amplitudes so that one can reject too-high-multiplicity events roughly. This is not a replacement for generating tuned MC but will serve as a stopgap solution that allows us to use older, already generated MC using the same supercalibration used in 2018 MC to almost the same effect in terms of <Ntracklets> vs V0M matchup.
> Provisions to supercalibrate old datasets

- PWGCF/FEMTOSCOPY/AliFemtoUser/AliFemtoKKTrackCutFull.cxx
AliFemtoKKTrackCutFull bug fix.
NSigmaTOF for 450_500 never used regardless of settings.
There was a setter "fUseNsigmaTOF450" but was used in the non-reachable code, since earlier  if(mom>=0.45 && mom<0.5) returned already true or false basing on TPC Nsigma alone.
> AliFemtoKKTrackCutFull bug fix - NSigmaTOF for 450_500 never used

- PWGGA/GammaConv/AliAnalysisTaskGammaConvDalitzV1.cxx
- PWGGA/GammaConv/AliAnalysisTaskGammaConvDalitzV1.h
- PWGGA/GammaConv/AliConversionMesonCuts.cxx
- PWGGA/GammaConv/AliConversionMesonCuts.h
- PWGGA/GammaConv/AliConversionPhotonCuts.cxx
- PWGGA/GammaConv/AliConversionPhotonCuts.h
- PWGGA/GammaConv/AliDalitzAODESD.h
- PWGGA/GammaConv/AliDalitzData.cxx
- PWGGA/GammaConv/AliDalitzData.h
- PWGGA/GammaConv/AliDalitzElectronCuts.cxx
- PWGGA/GammaConv/AliDalitzEventMC.h
Dear AliPhysics experts,
On the next commit, I implement the change of new* classes for auto_ptr, this works like 2 on 1, using new* on the beginning and after closing the cycle where the class lives use the delete*. I recheck my systematics and the need some changes plus new cases.
Regards Edgar
> Improves on memory leak on Dalitz

- OADB/AliEventCuts.cxx
- OADB/AliEventCuts.h
@fprino this changes should be transparent for the everyday use of AliEventCuts.
MCGEN trains and Kine only production have run number equal -1, however I wonder if there are some other corner cases in MC that can hurt us badly...
@mfasDa @jgrosseo fyi
> AliAnalysisCuts interface + MCGEN train support

- PWGUD/UPC/AliAnalysisTaskUPCforward.cxx
- PWGUD/UPC/AliAnalysisTaskUPCforward.h
Added the trigger conditions for 2015 data. This means CMUP10, CMUP11, and CMUP13. CMUP11 is in common with 2018 data. This explains why this code could partially analyse 2015 data too...
TESTED.
> PWGUD/UPC: Added the trigger conditions for 2015 data.

- PWG/EMCAL/EMCALtasks/AliAnalysisTaskEMCALClusterizeFast.cxx
- PWG/EMCAL/EMCALtasks/AliEmcalCorrectionClusterizer.cxx
- PWGPP/EMCAL/AliAnalysisTaskEMCALClusterize.cxx
As already re-added for the Tender, i also propose to re-add the cluster energy fraction per MC label back to the clusters per default. (see https://github.com/alisw/AliPhysics/pull/9265 for the Tender PR.)
This is necessary as the boolean "fSetCellMCLabelFromEdepFrac" also modifies and limits the MC cluster label list to 4 labels, which is way too little.
Let me know if you have any objections. If not, then please give it a +1 as this additional cluster information is crucial for ongoing analyses.
> PWG/EMCAL: Re-addition of stored MC label energy fraction to cluster

- PWGUD/UPC/AddTaskCTrue.C
- PWGUD/UPC/AliAnalysisTaskCTrue.cxx
- PWGUD/UPC/AliAnalysisTaskCTrue.h
- PWGUD/UPC/CMakeLists.txt
- PWGUD/UPC/PWGUDupcLinkDef.h
Added the AliAnalysisTaskCTrue.{h, cxx} with the steering macro AddTaskCTrue.C, plus the task has been added to the UPC library. It runs on the same dataset as AliAnalysisTaskUPCforward, so it should lower my consumption on resources... This task is actually the initial merging of other code of the UPC group. The hope for the future is to develop it further, analysing CTRUE B/E/A/C at the same time.
IMPORTANT: while this is more like a initial commit, the code has been tested on local and this seems to work. Now just a consistency check is required...
> PWGUD/UPC: Added AliAnalysisTaskCTrue.

- PWGUD/UPC/AliAnalysisTaskUPCforward.cxx
- PWGUD/UPC/AliAnalysisTaskUPCforward.h
- PWGUD/UPC/AliAnalysisTaskUPCforwardMC.cxx
- PWGUD/UPC/AliAnalysisTaskUPCforwardMC.h
This pull request is divided in many parts. On one hand, I have added a new part for the helicity analysis. In this new piece of code I try to obtain the relative abundance of GammaGamma and J/Psi to the decay angular distribution, simply by obtaining the invariant mass distribution in a specific CosTheta bin. On the other hand, I have noticed a possible bug that was not easy to spot. When trying to fill, it seems like the program implicitly converted Double_t to Int_t. This could possibly the reason why the acceptance distributions for the angular distributions showed such a strange shape... Now an explicit conversion to Double_t is requested every time. In addition, I have added the streamer indicators for the private class members that I had previously missed...
IMPORTANT: all these …
> PWGUD/UPC: New part of helicity analysis. Possible bug fix too. Streamers indicators.

- PWGLF/STRANGENESS/Cascades/Run2/AliAnalysisTaskStrangeCascadesDiscrete.cxx
- PWGLF/STRANGENESS/Cascades/Run2/AliAnalysisTaskStrangeCascadesDiscrete.h
- PWGLF/STRANGENESS/Cascades/Run2/macros/AddTaskStrangeCascadesDiscrete.C
For the analysis of the background shape and further precise signal extraction: combinatorial backgrounds of the cascade invariant mass spectra are determined and implemented.
The parameters needed to rerun cascade vertexer can be now set as variables in the addtask macro.
The output of the addtask macro is set to default 'AnalysisResults.root'
> Determine combinatorial backgrounds

- PWGLF/RESONANCES/PostProcessing/Xi1530/AliAnalysisTaskXi1530.cxx
Change vertex cut configuration from 2015 to 2016 so that it can match with AliMultSelection.
Change the order in a number of event Histogram.
> Correct vertex cut from 2015 to 2016

- PWGHF/vertexingHF/AliAnalysisTaskSEDs.cxx
This cut is already in FillMCGenAccHistos for the gen Ds selection, but if applied also outside the function it is also applied to the reco Ds
> Remove wrong cut on gen Zvtx in case of MC

- OADB/AliEventCuts.cxx
- OADB/AliEventCuts.h
Event selection extended to pp run1 data 
- only run ranges from LHC10d, LHC11are active for now
- since cut on SPD vertex dispersion does not work with AOD, this cut only works for ESD
> AliEventCuts for pp run1 data

- PWGCF/Correlations/DPhi/AliAnalysisTaskMinijetV2.cxx
- PWGCF/Correlations/DPhi/AliAnalysisTaskMinijetV2.h
- PWGCF/Correlations/DPhi/CMakeLists.txt
- PWGCF/Correlations/DPhi/PWGCFCorrelationsDPhiLinkDef.h
- PWGCF/Correlations/macros/minijet/AddTaskMinijetV2.C
This branch clones AliAnalysisTaskMinijet, using AliDirList instead of TList for the list of outputs. This is temporary in order to compare the use of memory in merging for the two approaches.
> New version of AliAnalysisTaskMinijet using AliDirList instead of TList.

- OADB/EMCAL/READMEoadb.txt
Analysis QA level bad channel map updates were provided for LHC18befhim.
In addition, a default 600ns has been applied for the time calibration of LHC18gn where especially the low gain could not be calibrated properly.
> [EMCAL-315,EMCAL-318,EMCAL-319,EMCAL-321,EMCAL-322,EMCAL-442] OADB/EMCAL: Updated BC maps LHC18befhim and TC for LHC18gn with default 600ns shift

- PWGHF/vertexingHF/AliAnalysisTaskSEImproveITS.cxx
- PWGHF/vertexingHF/AliAnalysisTaskSEImproveITS.h
----------------------------------------
- correction templates for dca sigma, mean and ratio pulls developed separately for tracks requiring kFirst or kOnlySecond condition in the SPD
- correction templates for dca mean developed in 24 bins of phi, instead of 4
The correction is performed in this way only for PbPb2018 period. This is ruled by a boolean variable (fIsPbPb2018), which is switched to the kTRUE value only
wheter the files, containing the correction templates, called from the AddTask are stored in a path including a "LHC18r" or "LHC18q" directory.
Backward compatibility tested on a LHC18d period (pp collisions)
> Improver ask update for LHC18q,r periods

- PWGLF/STRANGENESS/Cascades/Run2/AliAnalysisTaskStrangeCascadesDiscrete.cxx
- PWGLF/STRANGENESS/Cascades/Run2/macros/AddTaskStrangeCascadesDiscrete.C
The parameters of the constructor are now provided in Addtask macro when creating an instance.
Names of variables are consistent now.
> Fix in AddTask

- PWGHF/vertexingHF/macros/AddTaskHFSystPID.C
Modification that allows the selection of more trigger masks at the same time (i.e. kINT7 | kCentral)
> Change AliVEvent::EOfflineTriggerTypes to ULong64 

- PWGUD/UPC/AliAnalysisTaskUPCforward.cxx
It is more comfortable to have CosTheta in the x-axis and Phi as the y-axis...
> PWGUD/UPC: Fixed binning heat map helicity (now CosTheta=x, Phi=y).

- PWGPP/TOF/trending/MakeTrendingTOFQAv2.C
- Fixed protection against non existing histograms (e.g. in older QA output)
- Simplified code with centralized functions: added functions to get TH1/TH2/TProfile
- Tested on LHC13f pass4 QAresults
> Fixes to safeties in the TOF QA trending

- PWGHF/treeHF/AliAnalysisTaskSEHFTreeCreator.cxx
- PWGHF/treeHF/AliAnalysisTaskSEHFTreeCreator.h
- PWGHF/treeHF/AliHFTreeHandler.cxx
- PWGHF/treeHF/AliHFTreeHandler.h
- PWGHF/vertexingHF/AliAODPidHF.cxx
- PWGHF/vertexingHF/AliAODPidHF.h
- PWGHF/vertexingHF/AliAnalysisTaskSEHFSystPID.cxx
- PWGHF/vertexingHF/AliAnalysisTaskSEHFSystPID.h
- PWGHF/vertexingHF/AliRDHFCuts.cxx
- PWGHF/vertexingHF/AliRDHFCuts.h
- PWGHF/vertexingHF/macros/AddTaskHFSystPID.C
Implement a method to apply a correction to the NsigmaTPC for pion, kaon and proton (independently) in LHC18q and LHC18r data. The correction is implemented as:
NsigmaCorr = (Nsigma - mean(Nsigma)) / sigma(Nsigma)
where mean(Nsigma) and sigma(Nsigma) are the mean and sigma values of the Nsigma distributions extracted from the data using tagged samples of pions, kaons and protons
>  Implement method to set NsigmaTPC correction for LHC18qr

- PWGDQ/dielectron/CMakeLists.txt
- PWGDQ/dielectron/PWGDQdielectronLinkDef.h
- PWGDQ/dielectron/core/AliDielectronClusterCuts.cxx
- PWGDQ/dielectron/core/AliDielectronClusterCuts.h
- PWGDQ/dielectron/core/AliDielectronTrackCuts.cxx
- PWGDQ/dielectron/core/AliDielectronTrackCuts.h
- PWGDQ/reducedTree/AliAnalysisTaskReducedTreeMaker.cxx
- PWGDQ/reducedTree/AliAnalysisTaskReducedTreeMaker.h
- PWGDQ/reducedTree/AliReducedAnalysisJpsi2ee.cxx
- PWGDQ/reducedTree/AliReducedAnalysisSingleTrack.cxx
- PWGDQ/reducedTree/AliReducedAnalysisSingleTrack.h
- PWGDQ/reducedTree/AliReducedCaloClusterCut.cxx
- PWGDQ/reducedTree/AliReducedCaloClusterCut.h
- PWGDQ/reducedTree/AliReducedCaloClusterInfo.cxx
- PWGDQ/reducedTree/AliReducedCaloClusterInfo.h
- PWGDQ/reducedTree/AliReducedEventInfo.cxx
- PWGDQ/reducedTree/AliReducedEventInfo.h
- PWGDQ/reducedTree/AliReducedVarManager.cxx
- PWGDQ/reducedTree/AliReducedVarManager.h
- PWGDQ/reducedTree/CMakeLists.txt
- PWGDQ/reducedTree/PWGDQreducedTreeLinkDef.h
- introduced calorimeter cluster cut classes to dielectron and reducedTree frameworks
- added possibility to select on cluster-track matches in  dielectron/core/AliDielectronTrackCuts
- added possibility to select on calorimeter clusters in AliAnalysisTaskReducedTreeMaker
- updated AliReducedAnalysisSingleTrack with calorimeter cluster selection and histograms
> PWGDQ: Updates for calorimeter cluster handling in dielectron and reducedTree frameworks

- PWGHF/vertexingHF/AliAnalysisTaskSEDmesonPIDSysProp.cxx
- PWGHF/vertexingHF/AliAnalysisTaskSEDmesonPIDSysProp.h
- PWGHF/vertexingHF/AliAnalysisTaskSEHFSystPID.cxx
- PWGHF/vertexingHF/AliAnalysisTaskSEHFSystPID.h
1) add possibility to use daughter-track p instead of daughter-track pT for systematic propagation to the D mesons
2) add additional option for track downsampling in order to have independent samples (e.g. one for the calibration of Nsigma and another one to estimate the residual systematic uncertainty)
> Update code for HF PID syst

- PWGUD/UPC/AliAnalysisTaskUPCforwardMC.cxx
The LEGO train results showed that I had set the binning wrongly.
Now Phi is ~-4 to 4 and CosTheta ~-1 to 1.
> PWGUD/UPC: Changed binning of 2D distributions for helicity analysis in the MC.

- PWGHF/vertexingHF/AliHFSystErr.cxx
- PWGHF/vertexingHF/AliHFSystErr.h
Update AliHFSystErr with two methods for systematic uncertainties of D0 analysis in 0-10 and 30-50 centrality classes.
> Update: add method for D0 2018 Pb-Pb syst. unc.

- PWGCF/FEMTOSCOPY/FemtoDream/AliAnalysisTaskFemtoDreamPhi.cxx
- PWGCF/FEMTOSCOPY/FemtoDream/AliAnalysisTaskGrandma.h
- PWGCF/FEMTOSCOPY/FemtoDream/AliAnalysisTaskNanoAODSigma0Femto.cxx
- PWGCF/FEMTOSCOPY/FemtoDream/AliAnalysisTaskNanoAODSigma0Femto.h
- PWGCF/FEMTOSCOPY/FemtoDream/AliAnalysisTaskSigma0Femto.cxx
- PWGCF/FEMTOSCOPY/FemtoDream/AliFemtoDreamBasePart.cxx
- PWGCF/FEMTOSCOPY/FemtoDream/AliFemtoDreamBasePart.h
- PWGCF/FEMTOSCOPY/FemtoDream/AliFemtoDreamEvent.cxx
- PWGCF/FEMTOSCOPY/FemtoDream/AliFemtoDreamEvent.h
- PWGCF/FEMTOSCOPY/FemtoDream/AliFemtoDreamTrack.cxx
- PWGCF/FEMTOSCOPY/FemtoDream/AliFemtoDreamTrack.h
- PWGCF/FEMTOSCOPY/FemtoDream/AliFemtoDreamTrackCuts.cxx
- PWGCF/FEMTOSCOPY/FemtoDream/AliFemtoDreamv0.cxx
- PWGCF/FEMTOSCOPY/FemtoDream/AliFemtoDreamv0.h
- PWGCF/FEMTOSCOPY/FemtoDream/CMakeLists.txt
- PWGCF/FEMTOSCOPY/FemtoDream/PWGCFFemtoDreamLinkDef.h
- PWGCF/FEMTOSCOPY/macros/AddTaskSigma0FemtoNanoAOD.C
- PWGGA/Hyperon/AliAnalysisTaskSigma0Run2.cxx
- PWGGA/Hyperon/AliSigma0AODPhotonMotherCuts.cxx
o NanoFemto!
o Example task: AliAnalysisTaskNanoAODSigma0Femto, called from PWGCF/FEMTOSCOPY/macros/AddTaskSigma0FemtoNanoAOD.C
o Minor feature fixes
- Obtain the daughter mass from the DreamTrack when constructing the V0 
- Properly set the trigger selection for the AliEventCuts 
- Silence a few compiler warnings
> Get the FemtoDream ready for NanoAODs

- PWGJE/EMCALJetTasks/macros/EMCalCorrectionTaskEmbeddingExample.yaml
Due to modifications in the clusterizerv3 algorithm, it won't properly
clusterize embedded cells. So we use clusterizerv2 for embedding. Note
that the clusterization computation time is quite small compared to
cluster-track matching, so the speed up if clusterizerv3 was made
compatible won't make much difference.
> Use clusterizerv2 for embedding

- PWGLF/RESONANCES/AliRsnCutSetDaughterParticle.cxx
- PWGLF/RESONANCES/AliRsnCutSetDaughterParticle.h
This commits adds a new set of PID cuts for 2018 PbPb analysis, used for Lambda1520 analysis. The cut is selected as " kTPCTOFpidTunedPbPbTOFneed_2018"
> Added PID cuts for 2018 PbPb (Lambda1520)

- PWGCF/FLOW/GF/AliUniFlowCorrTask.h
This fixes the error with the new mac clang
> Use ClassDefNV for non virtual classes

- PWG/EMCAL/READMEemcCorrections.txt
- PWG/EMCAL/config/EMCalSampleConfig.yaml
- PWG/EMCAL/config/EMCalSampleConfigMC.yaml
- PWG/EMCAL/config/PWGJESampleConfig.yaml
- PWG/EMCAL/config/PWGJESampleConfigMC.yaml
Update examples, samples to use clusterizerv3, as this is the new standard
> Use clusterizerv3 in examples, samples

- PWG/EMCAL/EMCALbase/AliEmcalTrackSelectionAOD.cxx
@mfasDa - I don't modify the track selection very often, but I think this is what's appropriate for supporting the 2018 data (I'm not sure if we need a corresponding modification for ESDs). Can you confirm?
> Add support for data from 2018

- PWGHF/vertexingHF/AliAnalysisTaskSELc2V0bachelorTMVAApp.cxx
- PWGHF/vertexingHF/AliAnalysisTaskSELc2V0bachelorTMVAApp.h
- in extended mode: added nSigmaTPCpi, nSigmaTPCka, momentum of the bachelor
at the inner wall of the TPC;
- in reduced more: added nSigmaTPCpi, nSigmaTPCka, momentum of the bachelor
at the inner wall of the TPC, momentum of the bachelor; removed (to compensate):
alphaArm, ptArm, V0negativeEta, massGamma (all not used)
Additionally, now the nSigmaTPC and nSigmaTOF are taken from the AliAODPidHF,
so that we can use the recentered value (there is actually a flag to decide
whether to use AliAODPidHF, or the PIDresponse).
> Changing variables to be stored in the tree for ML training

- PWGUD/UPC/AliAnalysisTaskUPCforward.cxx
- PWGUD/UPC/AliAnalysisTaskUPCforward.h
- PWGUD/UPC/AliAnalysisTaskUPCforwardMC.cxx
- PWGUD/UPC/AliAnalysisTaskUPCforwardMC.h
Added new binning for helicity analysis.
This is the same binning as the inclusive people's, apart from the difference in the handling if Phi (this commit has  ~-3.14 to ~3.14).
Implemented both in data and MC.
> PWGUD/UPC: Binning for Helicity analysis.

- PWGHF/vertexingHF/AliRDHFCutsLctoV0.cxx
- case 13: use TOF only when available, and apply a 3 sigma cut on both TOF
and TPC
- case 14: 3 sigma cut on both TOF and TPCm with TOF always required but
only up to low momentum
> Two new PID cases for Lc --> pK0s (A. Alici)

- PWG/EMCAL/EMCALbase/AliAnalysisTaskEmcalLight.cxx
- PWG/EMCAL/EMCALbase/AliAnalysisTaskEmcalLight.h
- Same code handling as for AliAnalysisTaskEmcal:
+ Standard event selection: AliEventCuts
+ Bypass: Builtin event selection (for run1 or MCgen train)
- Object constructed in the constructor and can be accessed
by a getter returning a reference to the event cuts object
In addition:
- Move doxygen documentation from the cxx to the header file
- Introduce EMCAL_STRINGVIEW macro using std::string_view
in case of ROOT6 builds from ROOT for non-owning strings
and const std::string & in case of ROO5 builds
> Introduce AliEventCuts in AliAnalysisTaskEmcalLight

- PWG/EMCAL/EMCALbase/AliAnalysisTaskEmcal.h
Allows transparent usage of std::string_view from ROOT in case of ROOT6 builds for non-owning strings (i.e. in interfaces).
> Porting EMCAL_STRINGVIEW also to AliAnalysisTaskEmcal

- PWGCF/Correlations/DPhi/AliAnalysisTaskDiHadCorrelHighPt.cxx
- PWGCF/Correlations/DPhi/AliAnalysisTaskDiHadCorrelHighPt.h
enable to run only primary V0 for closure test, 
enable to accept/reject lambdas from cascades in MC, 
add pseudorapidity cut for generated V0 daughters
> Changes in AliAnalysisTaskDiHadCorrelHighPt 

- PWGHF/jetsHF/CMakeLists.txt
- PWGHF/jetsHF/PWGHFjetsHFLinkDef.h
- PWGJE/FlavourJetTasks/AliAnalysisTaskHFJetIPQA.cxx
- PWGJE/FlavourJetTasks/AliAnalysisTaskHFJetIPQA.h
- PWGJE/FlavourJetTasks/CMakeLists.txt
- PWGJE/FlavourJetTasks/PWGJEFlavourJetTasksLinkDef.h
- PWGJE/FlavourJetTasks/macros/AddTaskHFJetIPQA.C
- move PWGHF/jetsHF/AliAnalysisTaskHFJetIPQA to PWGJE/FlavourJetTasks for easy use of fastjet
- add routines for investigating the inclusive Lund Plane
- change flavour assignment (Pythia8: select particles outgoing from hardest process+MPI and do geometrical matching. Matching in terms of jet constituents can be turned on via fDoFlavourMatching)
- split routine for flavour assignment in subroutines for better overview
- add further monitoring histograms for flavour assignment
- delete Canvas monitoring cut settings and replace by histogram with cuts encoded in title and axis labels
> Move AliAnalysisTaskHFJetIPQA to PWGJE/FlavourJetTasks

- PWGCF/Correlations/DPhi/AliAnalysisTaskHadronPhiCorr.cxx
Fixed crash when running with no efficiency file loaded in AddTask/train. Instead, code now correctly runs with no efficiencies applied.
> fixed handling of case when no efficiency file is loaded/applied

- PWGGA/EMCALTasks/AliAnalysisTaskGammaHadron.cxx
- PWGGA/EMCALTasks/AliAnalysisTaskGammaHadron.h
Makes Centrality Cut apply
Adds Event plane axis to pi0 candidate
Improves tracking of MC pi0s and etas in Pos Swap
Adds histograms to correct position swapping method
> Centrality and EventPlane for Pi0Cands, PosSwap fixes

- PWGGA/GammaConv/AliAnalysisTaskGammaCalo.cxx
- PWGGA/GammaConv/AliAnalysisTaskGammaConvCalo.cxx
Somehow it was not protected that the photon could have as mother -1 in the cases below.
> PWGGA/GammaConv: Added crash protection Gamma(Conv)Calo when accessing Mother particle

- PWGUD/UPC/AliAnalysisTaskUPCforward.cxx
- PWGUD/UPC/AliAnalysisTaskUPCforward.h
Added code to obtain the invariant mass distributions in bins of CosTheta and Phi in the helicity frame of the J/Psi to extract the signal before computing the polarisation parameters.
The histograms have been created as a TH1F***, possibly not the best option, but solid enough.
IMPORTANT: tested on local, there doesn't seem to be any problem at all. The logic seems to be solid enough. On the small test run there is not enough statistics to see results... I can only see there are a few entries where the J/Psi's peak is supposed to be.
> PWGUD/UPC: Added code for Invariant Mass distr J/Psi polarisation 2D.

- PWGGA/GammaConv/AliAnalysisTaskOmegaMCStudies.cxx
- PWGGA/GammaConv/AliAnalysisTaskOmegaMCStudies.h
- PWGGA/GammaConv/CMakeLists.txt
- PWGGA/GammaConv/PWGGAGammaConvLinkDef.h
- PWGGA/GammaConv/macros/AddTask_OmegaMCStudies.C
introduced OmegaMCStudies task that in the future can be used to study various omega properties with MCGen trains on the GRID. For now, it will be only used to study pT of pi0 in dependence of pT of omega
> PWGGA/GammaConv: added OmegaMCStudies task

- PWGDQ/dielectron/macrosLMEE/Config_acapon.C
- PWGDQ/dielectron/macrosLMEE/LMEECutLib_acapon.C
Add cut settings to obtain a selection of V0 electrons with and without ePID. 
The "without PID" selection applies very loose eSigTPC cuts to mimic those used in the analysis.
> Add PID cut for V0 particles

- PWGPP/AliESDtools.cxx
seems to be ESD container is not compact anymore
> ATO-465 - check ESD track pointer - Fix Crash/Warning remained

- PWGUD/UPC/AliAnalysisTaskUPCforward.cxx
- PWGUD/UPC/AliAnalysisTaskUPCforward.h
Added the analysis of the pt-distribution divided for neutron emission classes.
IMPORTANT: still using vectors... Awaiting tests to switch to new code.
> PWGUD/UPC: Added pt-distr analysis for neutron emission classes.

- PWGDQ/dielectron/core/AliAnalysisTaskElectronEfficiencyV2.cxx
- PWGDQ/dielectron/core/AliAnalysisTaskElectronEfficiencyV2.h
- PWGDQ/dielectron/macrosLMEE/AddTask_acapon_Efficiency.C
- PWGDQ/dielectron/macrosLMEE/Config_acapon_Efficiency.C
Access to centrality information changed between run 1 and run 2. Switch
off centrality dependence when looking at run 1 data.
Also includes necessary changes to AddTask and Config file if wanting to look at run 1.
> Adds flag to remove centrality checks for run 1

- PWGCF/FLOW/GF/AliAnalysisTaskGFWFlow.cxx
- PWGCF/FLOW/GF/AliGFWFlowContainer.cxx
- PWGCF/FLOW/GF/AliGFWFlowContainer.h
- PWGLF/SPECTRA/PiKaPr/TPCTOFfits/AliAnalysisPIDTrack.h
1) fgTOFPIDResponse in AliAnalysisPIDtrack.h is now public static
2) AliGFWFlowContainers now also store the pT-axis of the preset binning I also add the default pT binning, in case older files are used
> Maintenance on AliAnalysisPIDtrack and AliGFWFlowContainers

- PWGPP/AliAnalysisTaskFilteredTree.cxx
- PWGPP/AliESDtools.cxx
* including Ruben explanation why needed 
- GetNumberOfESDTracks returns the persistent data member fNumberOfESDTracks for the number of found tracks.
- It is filled before the filtering and used as an observed multiplicity measure.
- For the stored tracks count one should use GetNumberOfTracks().
3 time stamps stamp stored
* gid            - based on LHC clock - - as always
* evtTimeStamp   - time of event build   - as always
* timeStamp      - real time stamp of collision - NEW
- before i calculated "real time based of GID - new we
use newly introduced getter
> ATO-465 - Fix warning in track loop + adding precise time estimator

- PWG/EMCAL/EMCALbase/AliClusterContainer.h
- PWGJE/EMCALJetTasks/AliEmcalJetTask.h
Issues were identified with test trains 4604, 4606 in Jets_EMC_PbPb.
The streamer updates are needed due to changes in #9976 and #10005
cc: @lhavener , @hjbossi
> Fix streamers issues

- PWGHF/vertexingHF/AliRDHFCuts.cxx
- PWGHF/vertexingHF/AliRDHFCuts.h
Add the flag and the method to use the same SPD acceptance in 2015 and 2018 Pb-Pb analysis.
The two regions excluded are defined in order to avoid to use candidates which could have passed in SPD HSs 1A0 or 5C0, which were out during 2018 Pb-Pb data taking period.
> Use same SPD acceptance in 2015-2018 Pb-Pb

- PWGJE/FlavourJetTasks/CMakeLists.txt
The class AliAnalysisTaskHFJetIPQA.cxx was added twice in the SRCS of the CMakeLists.txt:
once in the SRCS that are always compilend and another time in the SRCS that are compiled only when fastjet is found.
Since the task depends on fastjet, it has to be added only in the second case.
> Fix compilation issue when fastjet is disabled

- PWGHF/vertexingHF/AliAnalysisTaskSEHFSystPID.cxx
Modify code to fill tree only when track is tagged from V0 / kinks / tight selection on TOF or TPC (for kaons), otherwise now filled always because of introduction of charge in bit map
> Recover filling of the tree only when track is tagged

- PWGHF/vertexingHF/AliAnalysisTaskSEImproveITSCVMFS.cxx
- PWGHF/vertexingHF/AliAnalysisTaskSEImproveITSCVMFS.h
- PWGHF/vertexingHF/CMakeLists.txt
- PWGHF/vertexingHF/PWGHFvertexingHFLinkDef.h
- PWGHF/vertexingHF/macros/AddTaskImproveITSCVMFS.C
Adds new instance of ITS Improver task with calibration files taken from CVMFS at runtime based on run number of input. This new task is temporary until after SQM, to avoid possible disruption to ongoing analysis; the CVMFS functionality is planned to be ported into the main ITS improver after this and the new task will be removed at that time.
This commit does not alter the existing "standard" ITS improver.
> Add "CVMFS" version of ITS improver task

- PWGGA/GammaConv/macros/AddTask_GammaConvNeutralMesonPiPlPiMiNeutralMeson_CaloMode_pp.C
- PWGGA/GammaConv/macros/AddTask_GammaConvNeutralMesonPiPlPiMiNeutralMeson_ConvMode_pp.C
- PWGGA/GammaConv/macros/AddTask_GammaConvNeutralMesonPiPlPiMiNeutralMeson_MixedMode_pp.C
change of DCA track cut. It was found that pT dependent DCA cut causes non-uniform phi distribution for tracks for LHC10
> PWGGA/GammaConv: omega cut config changes

- PWGCF/FEMTOSCOPY/FemtoDream/AliAnalysisTaskNanoXioton.cxx
- PWGCF/FEMTOSCOPY/FemtoDream/AliFemtoDreamTrack.cxx
- PWGCF/FEMTOSCOPY/macros/AddTaskFemtoDream.C
- PWGCF/FEMTOSCOPY/macros/AddTaskFemtoDreamRun1.C
- PWGCF/FEMTOSCOPY/macros/AddTaskFemtoDreamTrackSplit.C
- PWGCF/FEMTOSCOPY/macros/AddTaskFemtoGranma.C
- PWGCF/FEMTOSCOPY/macros/AddTaskFemtoGranma_systcuts.C
- PWGCF/FEMTOSCOPY/macros/AddTaskFemtoXoton.C
Invariant mass of pairs was used for a short investigation, however it is not used anymore and just lingers around. 
Additionally a redifinition of the VEvent was removed, which was already a member of the analysis task. Further pile up rejection & dcas were taken from the 128 track rather than the global track - fixed.
> Removes unnessessary function and equalizes to nano to AODs

- PWGLF/RESONANCES/AliRsnCutCascade.cxx
- PWGLF/RESONANCES/AliRsnValueDaughter.cxx
- PWGLF/RESONANCES/AliRsnValueDaughter.h
AliRsnCutCascade:
- implemented the Cascade DCA cut for AODs
AliRsnValueDaughter: 
- kV0Mass: for AODs: used to return only the mass for the Lambda hypothesis; now returns the best of the three mass hypotheses (K0S, Lambda, or anti-Lambda)
- kV0P: returned p^2 for AODs; I fixed this.
- kV0Pt: returned pT^2 for AODs; I fixed this.
- kV0NPt and kV0PPt: implemented for AODs
- kV0DCAXY: implemented for AODs
- kV0Lifetime: implemented for AODs
> Update AOD cascade DCA cut and AliRsnValueDaughter type

- PWGHF/vertexingHF/AliHFSystErr.cxx
Updating the binnings for 2018 Pb-Pb systematic uncertainties for the Dzero in 0-10 and 30-50. The values reported are still those of 2015 analysis and will be updated with the finals as soon as they will be finalized.
> Update Dzero systematics binnings for 2018 Pb-Pb

- PWG/DevNanoAOD/macros/AddTask_ConversionsForNano.C
- PWGGA/Hyperon/AliSigma0AODPhotonMotherCuts.cxx
- PWGGA/Hyperon/AliSigma0AODPhotonMotherCuts.h
- PWGGA/Hyperon/AliSigma0PhotonCuts.cxx
- PWGGA/Hyperon/AliSigma0PhotonMotherCuts.cxx
- PWGGA/Hyperon/AliSigma0PhotonMotherCuts.h
- The v0 of the photons is not saved in the NanoAOD -> protection implemented
- Enable Addv0InESDs for the photons
- Check gamma+K0 inv. mass for weird structures (that hopefully won't show up)
> Minor improvements for Sigma0 and NanoAOD analysis

- PWGHF/vertexingHF/macros/ComputeDmesonYield.C
@arossi81 @strogolo @RenuBala123 @syaefudinjaelani note that the variable hypo is needed also for the yield. Could you please double check that it is consistent with what is done in HFPtSpectrumRAA.C? Thanks!
> Implement variable FD hypo to be consistent with RAA

- PWGHF/vertexingHF/AliHFSystErr.cxx
Updating _InitD0toKpi2018PbPb010_ and _InitD0toKpi2018PbPb3050_ with the systematic uncertainty values from the following sources:
- Signal extraction
- Tracking efficiency 
- PID
In addition I have fixed some issues with the binning for the _Cut variation_ and BR sources histogram.
> Update D0 systematics Pb-Pb 2018

- PWGHF/vertexingHF/AliAnalysisTaskSEHFSystPID.cxx
- PWGHF/vertexingHF/AliAnalysisTaskSEHFSystPID.h
- PWGHF/vertexingHF/macros/AddTaskHFSystPID.C
- PWGHF/vertexingHF/macros/EstimateSingleTrackPIDsyst.C
Add bit map to store SPD information (kFirst, kAny), ITS refit, TPC refit, and geometrical cut in output tree
>  Add bit map for track quality info in ttree 

- OADB/PWGGA/ReadmeRecalibOADB.txt
- PWGGA/GammaConv/AliAnalysisTaskConversionQA.cxx
- PWGGA/GammaConv/AliAnalysisTaskConversionQA.h
- PWGGA/GammaConv/AliAnalysisTaskGammaConvCalo.cxx
- PWGGA/GammaConv/AliAnalysisTaskGammaConvV1.cxx
- PWGGA/GammaConv/AliAnalysisTaskHeavyNeutralMesonToGG.cxx
- PWGGA/GammaConv/AliAnalysisTaskMaterialHistos.cxx
- PWGGA/GammaConv/macros/AddTask_GammaConvCalo_PbPb.C
- PWGGA/GammaConv/macros/AddTask_GammaConvCalo_pPb.C
- PWGGA/GammaConv/macros/AddTask_GammaConvCalo_pp.C
- PWGGA/GammaConv/macros/AddTask_GammaConvV1_PbPb.C
- PWGGA/GammaConv/macros/AddTask_GammaConvV1_pPb.C
- PWGGA/GammaConv/macros/AddTask_GammaConvV1_pp.C
- PWGGA/GammaConv/macros/AddTask_GammaHeavyMeson_ConvMode_pPb.C
- PWGGA/GammaConv/macros/AddTask_GammaHeavyMeson_ConvMode_pp.C
- PWGGA/GammaConv/macros/AddTask_GammaHeavyMeson_MixedMode_pPb.C
- PWGGA/GammaConv/macros/AddTask_GammaHeavyMeson_MixedMode_pp.C
- PWGGA/GammaConv/macros/AddTask_MaterialHistos_pPb.C
- PWGGA/GammaConv/macros/AddTask_MaterialHistos_pp.C
- PWGGA/GammaConv/macros/AddTask_PhotonQA.C
- PWGGA/GammaConvBase/AliConversionPhotonCuts.cxx
- PWGGA/GammaConvBase/AliConversionPhotonCuts.h
By using "enableElecDeDxPostCalibration = kTRUE" and not setting a dEdx recalib file name one can now acess the OADB file stored in OADB/PWGGA which contains period-dependent recalibrations.
If one also sets a filename, then the recalibration parameters will be loaded from the file instead of the OADB (this is the old standard procedure).
>  PWGGA/GammaConv: Implemented TPC dE/dx recalibration OADB for conversion tasks

- PWGHF/vertexingHF/AliHFSystErr.cxx
Added systematic uncertainty from geometrical cut correction for Ds and D+ summed in quadrature to tracking and ME systematic uncertainty:
4% in 30-50% centrality class
6% in 0-10% centrality class
> Add systematic uncertainty from geom cut correction for Ds and D+

- PWGJE/EMCALJetTasks/Tracks/AliAnalysisTaskEmcalJetEnergySpectrum.cxx
- PWGJE/EMCALJetTasks/Tracks/AliAnalysisTaskEmcalJetEnergySpectrum.h
For CALOFAST cluster the event selection must
change from kINT7/kEMCEJE to kMuonCalo. In addition
the downscale factors must be used from the CALO cluster.
> Adapt event selection to CALOFAST cluster

- PWG/EMCAL/EMCALbase/AliEMCALRecoUtils.cxx
- PWG/EMCAL/EMCALbase/AliEMCALRecoUtils.h
- PWG/EMCAL/EMCALtasks/AliEmcalCorrectionClusterNonLinearity.cxx
- PWGGA/GammaConvBase/AliV0ReaderV1.cxx
[nonlin_Evi_Nico_NewhotonPoints.pdf](https://github.com/alisw/AliPhysics/files/3252080/nonlin_Evi_Nico_NewhotonPoints.pdf)
The new parametrizations correspond to the blue (kBeamTestNS) and the green (kPi0MCNS) curves in the attached plot. The most important difference to the existing nonlinearity parametrizations is the strongly reduced drop of the MC parametrization.
> PWG/EMCAL: Added improved high energy nonlinearity parametrizations (kBeamTestNS,kPi0MCNS)

- PWGUD/UPC/AliAnalysisTaskUPCforward.cxx
- PWGUD/UPC/AliAnalysisTaskUPCforward.h
Added two arrays of histograms to do Signal Extraction on CosTheta and Phi for J/Psi's polarisation in UPC. This is due to the possible lack of statistics for a full 2D analysis...
> PWGUD/UPC: Helicity update: two 1D aanlysis for CosTheta and Phi for Signal Ex.

- PWGJE/EMCALJetTasks/AliLundPlaneHelper.cxx
- PWGJE/EMCALJetTasks/AliLundPlaneHelper.h
- PWGJE/EMCALJetTasks/CMakeLists.txt
- PWGJE/EMCALJetTasks/PWGJEEMCALJetTasksLinkDef.h
3 classes added for the lund plane evaluation:
- AliLundPlaneHelpers evaluates the lund plane for a
single jet
- AliLundPlaneData is a container for all splittings
- AliLundPlaneParameters contains the lund plane
parameters for a single splitting
AliLundPlaneHelper and AliLundPlaneParameters can
throw AliLundPlaneException in case fastjet fails or
there is access to uninitialized parameters
> [WIP] Add helper class for the evaluation of the lund plane parameters

- PWGGA/GammaConv/AliAnalysisTaskConversionQA.cxx
Dear all,
indeed without the change the TOF values were not filled in for the PhotonQA.
now they are.
The condition I am using to select causes were TOF signal is there , I have seen for example in dielectrons.
Ana
> fixing the filling of TOF values

- PWGJE/EMCALJetTasks/AliAnalysisTaskEmcalJetTagger.cxx
Histogram arrays no longer created in the constructor
but in the UserCreateOutputObjects as they are non-streamable,
and memory allocation in the dummy constructor should be
prevented.
> Fix initialization of histogram containers

- PWG/EMCAL/EMCALbase/AliAnalysisTaskEmcal.h
- PWG/EMCAL/EMCALbase/AliAnalysisTaskEmcalLight.h
- PWG/EMCAL/EMCALbase/AliEmcalStringView.h
- PWGJE/EMCALJetTasks/CMakeLists.txt
- PWGJE/EMCALJetTasks/PWGJEEMCALJetTasksLinkDef.h
- PWGJE/EMCALJetTasks/Tracks/AliAnalysisEmcalTriggerSelectionHelper.cxx
- PWGJE/EMCALJetTasks/Tracks/AliAnalysisEmcalTriggerSelectionHelper.h
- PWGJE/EMCALJetTasks/Tracks/AliAnalysisTaskEmcalJetEnergySpectrum.cxx
- PWGJE/EMCALJetTasks/Tracks/AliAnalysisTaskEmcalJetEnergySpectrum.h
Use multiple inheritance in order to share common code
for trigger section among several classes: The implementation
code is extracted into an implementation class
(AliAnalysisEmcalTriggerSelectionHelperImp) which can be
derived from in analysis tasks (no inheritance from TObject).
For classes which need streamer functionality from TObject
i.e. for encapsulation the interface class
AliAnalysisEmcalTriggerSelectionHelper should be used.
> Extract trigger selection tools to new class

- OADB/AliEventCuts.cxx
Fixing alisw/AliPhysics#10350: In case the time cut is not
applied the flag has to be set, otherwise all events
are rejected.
> Set default flag in case time cut is not applied

- PWGGA/GammaConv/AliAnalysisTaskGammaConvDalitzV1.cxx
- PWGGA/GammaConv/AliAnalysisTaskGammaConvDalitzV1.h
- PWGGA/GammaConv/macros/AddTask_GammaConvDalitzV1_pp.C
Remove extra variables to propagate the momentum like dielectrons, and adding a TH3F for extra study on PsiPair and theta in terms of the momentum. Plus an extra train ID for the study of ITS.
> PsiPair correction with a new train to test ITS option kBoth

- PWG/EMCAL/EMCALbase/AliAnalysisTaskEmcal.cxx
- PWG/EMCAL/EMCALtrigger/AliEmcalTriggerStringDecoder.cxx
- PWG/EMCAL/EMCALtrigger/AliEmcalTriggerStringDecoder.h
- PWGJE/EMCALJetTasks/CMakeLists.txt
- PWGJE/EMCALJetTasks/PWGJEEMCALJetTasksLinkDef.h
- PWGJE/EMCALJetTasks/Tracks/AliAnalysisTaskEmcalTriggerNormalization.cxx
- PWGJE/EMCALJetTasks/Tracks/AliAnalysisTaskEmcalTriggerNormalization.h
- PWGJE/EMCALJetTasks/macros/AddTaskEmcalTriggerNormalization.C
Calculate the donnscale-corrected number of min. bias events
(cluster luminosity) and the corrected number of events for
the various EMCAL triggers. The event counts are organized in
centrality percentiles.
> Add task for EMCAL trigger normalization based on downscale method

- PWGJE/EMCALJetTasks/Tracks/AliAnalysisTaskEmcalTriggerNormalization.cxx
- PWGJE/EMCALJetTasks/Tracks/AliAnalysisTaskEmcalTriggerNormalization.h
In order to differenciate between the different L0
triggers used for EMCAL L1 (i.e. INT7 and 0TVX) the
L0 trigger is required when matching the trigger
class for the determination of the downscale weight.
In addition: Couple of trivial bug fixes (forgotten
exit condition, missing general histograms)
> Require L0 trigger used for L1 in trigger string

- PWGHF/treeHF/AliAnalysisTaskSEHFTreeCreator.cxx
Make the destructor more coherent by also deleting the dynamically allocated AliJetTreeHandler objects.
> Update AliAnalysisTaskSEHFTreeCreator destr

- PWGHF/vertexingHF/AliAnalysisTaskSEDvsMultiplicity.cxx
Edit to run number definitions for determining LHC16-18 pp periods in AliAnalysisTaskSEDvsMultiplicity.cxx. Definitions now match those in OADB MultSelection task.
> update to run ranges in multiplicity task

- PWG/CaloTrackCorrBase/AliIsolationCut.cxx
- PWG/CaloTrackCorrBase/AliIsolationCut.h
- PWGGA/CaloTrackCorrelations/AliAnaParticleIsolation.cxx
- PWGGA/CaloTrackCorrelations/AliAnaParticleIsolation.h
Attempt to simplify the classes. Move basic cone isolation content histograms where the isolation cut is applied in AliIsolationCut
Activate the re-reading of the particles in cone when additional studies are needed.
> move basic histograms from AliAnaParticleIsolation to AliIsolationCut

- PWGHF/jetsHF/AliAnalysisTaskBJetTC.cxx
- PWGHF/jetsHF/AliAnalysisTaskBJetTC.h
The SV fE shape was not so discriminative between the different jet flavors, so we reconstructed SVs with more prongs to a shape which similar to the one for the ATLAS.
> PWGHF/jetsHF: Reconstructing 4,5,6 prong SV for templates

- PWGHF/treeHF/AliAnalysisTaskSEHFTreeCreator.cxx
Generated MC TTree was not filled for Lc->pK0s when both Lc decays were enabled. Fixed.
> PWGHF: Fix TreeCreator

- PWGHF/treeHF/AliAnalysisTaskSEHFTreeCreator.cxx
Continuation of PR10542, where I forgot to take care of a continue
(Generated MC TTree was not filled for Lc->pK0s when both Lc decays were enabled. Fixed.)
> PWGHF: Fix TreeCreator part2

- PWGUD/UPC/AliAnalysisTaskUPCforward.cxx
- PWGUD/UPC/AliAnalysisTaskUPCforward.h
Added a new 2D variable binning for the 2D polarisation analysis.
Added a new stricter invariant mass distr in terms of pt.
Looking at 0.4<pt<0.6 in hopes of suppressing bkg.
> PWGUD/UPC: My variable binning for 2D polarisation. Strict-pt invariant mass distr.

- OADB/COMMON/MULTIPLICITY/AliMultSelectionTask.cxx
- OADB/COMMON/MULTIPLICITY/AliMultSelectionTask.h
- PWGLF/STRANGENESS/CMakeLists.txt
- PWGLF/STRANGENESS/Correlations/AliAnalysisTaskhStrCorr.cxx
- PWGLF/STRANGENESS/Correlations/AliAnalysisTaskhStrCorr.h
- PWGLF/STRANGENESS/Correlations/macros/AddTaskhStrCorr.C
- PWGLF/STRANGENESS/PWGLFSTRANGENESSLinkDef.h
This feature is meant to cover a specific use case in which event losses due to vertex-Z selections are studied. It does not change the default behavior of the task - it only introduces a switch so that, if that switch is enabled, the EvSelCode from the framework will reflect all event selections used at calibration time except the vertex-Z position check.
> Add vertex-Z selection skipper for EvSelCode

- cmake/FindROOT.cmake
FATAL condition makes it impossible to compile AliPhysics
with the o2 defaults which deactivate alien. Configuration
of ALIEN should be handled by the build recipe.
> Remove FATAL condition in case ALIEN is not set

- PWGDQ/dielectron/LMEE/AliAnalysisTaskSimpleTreeMaker.cxx
- PWGDQ/dielectron/LMEE/AliAnalysisTaskSimpleTreeMaker.h
Enforce that DCA covariance is checked before calculating normalised DCA values.
Also, removed redundant AOD/ESD checking during DCA calculation
> Implement DCAcov check in TreeMaker

- PWGDQ/dielectron/macrosLMEE/AddTask_acapon.C
- PWGDQ/dielectron/macrosLMEE/AddTask_acapon_Efficiency.C
- PWGDQ/dielectron/macrosLMEE/Config_acapon_Efficiency.C
- PWGDQ/dielectron/macrosLMEE/Config_acapon_noCutLib.C
Updated Config_acapon_noCutLib to now have four cut settings which select MC tracks based on MCtruth information. Two for dielectrons from pions, and two for HF (one for charm and one for beauty). 
All other files that were changed only had trailing white spaces removed from any lines.
> Add HF/LF MCsignal definitions to config

- PWG/EMCAL/EMCALtasks/AliAnalysisTaskEmcalTriggerNormalization.cxx
- PWG/EMCAL/EMCALtasks/AliAnalysisTaskEmcalTriggerNormalization.h
If requested normalization histograms are filled as function
of centrality. Must be enabled explicitly by the user as
the task will crash in case the AliMultiplicitySelection is
not found.
> Add option for multiplicity-dependent normalization in p-Pb

- PWG/EMCAL/EMCALtasks/AliEmcalCorrectionTask.cxx
This wasn't possible previously due to a typo. This isn't super common,
but it should be working
> EMCal CorrFW: Allow asymmetric eta, phi limits

- PWGLF/RESONANCES/PostProcessing/Xi1530/AliAnalysisTaskXi1530.cxx
In EventCuts -> ! is not needed
> Fix PS selection issue in QA plot

- PWGDQ/dielectron/macrosLMEE/Config_acapon.C
- PWGDQ/dielectron/macrosLMEE/Config_acapon_noCutLib.C
- PWGDQ/dielectron/macrosLMEE/LMEECutLib_acapon.C
V0 histograms added to a new cut setting "kV0_allAcc" which finds all V0 candidates but does not apply cuts. 
HF particle correlation check now switched on in no cut lib config file.
Passing of default arguments removed from a cut setting in my CutLib to avoid confusion.
> Add V0 feature histograms/switch on HF corr. check

- PWGHF/treeHF/AliAnalysisTaskSEHFTreeCreator.cxx
- PWGHF/treeHF/AliHFTreeHandlerLctopKpi.cxx
- PWGHF/treeHF/AliHFTreeHandlerLctopKpi.h
in Lc tree handler:
- added branches to reco and gen ttrees to store resonant decay info
- added bitmap for 4 different decays
- added function to ID resonant decay (based on AliCFVertexingHF3Prong::CheckLc3Prong() )
In tree creator analysis task:
- added id and setting of resonant decays
> add LctopKpi resonant decay ID at reco and gen level when running on MC

- PWG/muondep/AliAnalysisTaskMuonRefit.cxx
- PWG/muondep/AliAnalysisTaskMuonRefit.h
Added ::ReAlignFromDefaultStorage to use CDB settings from the ESD as old alignment storage and latest entry in OCDB for new alignment storage
> Automatic storage selection for muon track refit

- PWGUD/UPC/AliAnalysisTaskUPCforward.cxx
- PWGUD/UPC/AliAnalysisTaskUPCforward.h
- PWGUD/UPC/AliAnalysisTaskUPCforwardMC.cxx
- PWGUD/UPC/AliAnalysisTaskUPCforwardMC.h
Added systematics plots for the neutron emission analysis. 
The plan is the following:
- Coh   Inv Mass Spectra 
- Coh   Inv Mass Spectra XNXN
- Incoh Inv Mass Spectra 
- Incoh Inv Mass Spectra XNXN
x5 due to the different Pt-thresholds (0.200, 0.225, 0.250, 0.275, 0.300). In addition, 
- Pt-distr (normal + XNXN) with 20 MeV/c shift
Furthermore, new binning for 1D pol + 1D acceptance.
> PWGUD/UPC: XNXN systematics + new binning 1D.

- PWG/EMCAL/EMCALbase/AliAnalysisTaskEmcalLight.cxx
- PWG/EMCAL/EMCALbase/AliAnalysisTaskEmcalLight.h
- PWG/EMCAL/EMCALtrigger/AliEmcalTriggerQATask.cxx
Print warning in case centrality is missing only when requested.
Default: Always print warnings. Disabled for EMCAL trigger QA
in the QA train.
> [ALIROOT-8287] Reduce verbosity related to missing centrality

- PWGCF/Correlations/JCORRAN/Pro/AliJJetJtAnalysis.cxx
- PWGCF/Correlations/JCORRAN/Pro/AliJJetJtAnalysis.h
- PWGCF/Correlations/JCORRAN/Pro/AliJJetJtTask.cxx
- PWGCF/Correlations/JCORRAN/Pro/AliJJetJtTask.h
- PWGCF/Correlations/macros/jcorran/AddTaskJJetJt.C
The detector level leading and subleading jets are compared to MC truth
counterparts in phi-eta plane. The maximum was added as an argument in
the macro.
> Added a DeltaR matching check for dijet components

- PWGPP/AliESDtools.cxx
When using the OCDB from CVMFS, the default storage is set to `raw://` and an
environment variable is set too (`OCDB_PATH`). In case the variable is set, we
should not attempt to connect to AliEn as we will not need it.
This covers the cases where AliEn access is deliberately disabled (e.g. the
release validation).
The fix is the same adopted in alisw/AliDPG#31.
> Fix OCDB access with no AliEn (ALIROOT-8290)

- PWGHF/vertexingHF/AliAnalysisTaskSEImproveITSCVMFS.cxx
Adds missing run 255469 to definition in ITSimprover task for 16h (was blocking merging on trains using LHC17h8a production when incompleteTPC runs were included in the analysis)
> add missing run to ITSimprover task definition for 16h

- PWG/EMCAL/EMCALbase/AliAnalysisTaskEmcalLight.cxx
For AliAnalysisTaskEmcalLight the trigger selection
is not called within the internal event selection,
consequently it has to be called before. Otherwise
the trigger selection is not applied.
> [ALIROOT-8287] Swap order of internal event- and triggerselection

- PWGLF/SPECTRA/PiKaPr/TPC/rTPC/AliAnalysisTaskPPvsRT.cxx
- PWGLF/SPECTRA/PiKaPr/TPC/rTPC/AliAnalysisTaskPPvsRT.h
Parameters to calibrate MIP dE/dx vs Eta are included for the periods; LHC16h,i,k,l are included. Ready to produce the correlation dE/dx vs p to get pi/k/p spectra
> Parameters to calibrate MIP dE/dx vs Eta are included 

- PWGHF/correlationHF/AliAnalysisTaskDHFeCorr.cxx
- PWGHF/correlationHF/AliAnalysisTaskDHFeCorr.h
- PWGHF/correlationHF/CMakeLists.txt
- PWGHF/correlationHF/PWGHFcorrelationHFLinkDef.h
- PWGHF/correlationHF/macros/AddTaskDHFeCorr.C
- PWGHF/correlationHF/macros/default_config_d_hfe.yaml
Hi all,
I have corrected the previous pull request (#10867). The main problem is that I have used some C++11 features that ROOT5 cannot handle. I tried to port the conflicting parts, but this would involve doing quite some changes to the code. So I have preferred to keep the C++11 and disable the build for ROOT 5. The task works with no problem in ROOT 6. This is done by some changes in the PWGHFcorrelationHFLinkDef.h and CMakeLists.txt and it does not affect other tasks.
Please let me know if you have any comments.
Best,
Henrique
> D-meson -- HFe correlations task

- PWGGA/GammaConvBase/AliConvEventCuts.cxx
For some reason in https://github.com/alisw/AliPhysics/commit/55ed2880fe01cbc8124ae26fb15a53cad22c3537 the array entries were shuffled which lead to the wrong width being loaded for all Run2 datasets.
> PWGGA/GammaConv: Fixed trigger mimicking width for Run2 datasets (EG1)

- PWGJE/EMCALJetTasks/AliLundPlaneHelper.cxx
- PWGJE/EMCALJetTasks/AliLundPlaneHelper.h
- PWGJE/EMCALJetTasks/Tracks/AliAnalysisTaskEmcalJetIterativeDeclustering.cxx
- Don't apply hard cutoff, with current settings
will reject all subjets
- Correctly use pt of the lower subjet
- Fix constructor of the splitting structure
- Fix iteration over histograms in manager
when filling the output list
> Fixes in obtaining lund map parameters

- PWGJE/EMCALJetTasks/AliEmcalJetTask.cxx
- PWGJE/EMCALJetTasks/AliEmcalJetTask.h
- PWGJE/EMCALJetTasks/macros/AddTaskEmcalJet.C
Add necessary suffix parameter required for
the usage as subwagon. Attention: Suffix
parameter not yet added to the jets collection
name - this currently prevents to run more
than one jetfinder with the same jet definition
at the time.
> Allow usage of the jet task in subwagons

- PWGLF/RESONANCES/PostProcessing/f0980/AliAnalysisTaskInclusivef0f2.cxx
Fixing c++11 narrowing error breaking
compilation under macOS
> Fix compilation under macOS

- PWG/CaloTrackCorrBase/AliCalorimeterUtils.cxx
- PWG/CaloTrackCorrBase/AliCalorimeterUtils.h
- PWG/EMCAL/EMCALbase/AliEMCALRecoUtils.cxx
- PWG/EMCAL/EMCALbase/AliEMCALRecoUtils.h
- PWG/EMCAL/EMCALtasks/AliEmcalCorrectionCellTimeCalib.cxx
- PWG/EMCAL/EMCALtasks/AliEmcalCorrectionComponent.cxx
- PWG/EMCAL/EMCALtasks/AliEmcalCorrectionComponent.h
- PWG/EMCAL/EMCALtasks/AliEmcalCorrectionTask.cxx
- PWG/EMCAL/EMCALtasks/AliEmcalCorrectionTask.h
- PWG/EMCAL/macros/AddTaskEMCALTender.C
- PWGPP/EMCAL/AliAnalysisTaskEMCALClusterize.cxx
- PWGPP/EMCAL/AliAnalysisTaskEMCALClusterize.h
- PWGPP/EMCAL/AliAnalysisTaskEMCALTimeCalib.cxx
- PWGPP/EMCAL/AliAnalysisTaskEMCALTimeCalib.h
- PWGPP/EMCAL/macros/AddTaskEMCALTimeCalibration.C
- TENDER/TenderSupplies/AliEMCALTenderSupply.cxx
- TENDER/TenderSupplies/AliEMCALTenderSupply.h
The correction framework was modified by adding a switch whether someone want to use one histogram for the time calibration instead of four for all the BCs. Also in case it is one histogram, this histogram will be TH1S and not TH1F.
> Modifying the correction framework so it takes one histogram instead of four for all BCs

- PWG/EMCAL/EMCALbase/AliAnalysisTaskEmcalLight.cxx
AliAnalysisTaskEmcalLight stores containers in associative arrays,
access via index meaningless. The default implementation of
CheckMCOutliers takes each the first container it finds in the
container map, but it is not guaranteed that this is indeed the
first container inserted by the user. Users should better
overwrite the function.
> Fix container access in case of AliAnalysisTaskEmcalLight

- PWGLF/RESONANCES/PostProcessing/Xi1530/AliAnalysisTaskXi1530.cxx
Found from a discrepancy between ESD and AOD.
V0 CPA must be calculated from Xi vertex
> Fix ESD CPA cut issue

- PWGLF/RESONANCES/macros/mini/AddTaskXi1820.C
Minor change for ROOT6 env.
1. Consider "AddMonitorOutput.C" macro to work both env.
2. Move default parameters above
> Modify for ROOT6 env

- PWGPP/AliESDtools.cxx
ATO-538, ATO-529 - improve pileup vertex finder and add mult estimators￼…
* Pile-up finder
* Reject tracks with ITS pixels = most probably not pileup
* Reject tracks "crossing CE"
if (param->GetTgl()*param->GetZ()<0) continue;
* New multiplicity estimators. TOF and Calorimeter should be more sensitive o neutral energy
* calo clusters
* tof (clusters/hits/matches)
>  ATO-538, ATO-529 - improve pileup vertex finder and add mult. estimators

- PWGUD/UPC/AliAnalysisTaskUPCforward.cxx
- PWGUD/UPC/AliAnalysisTaskUPCforward.h
- PWGUD/UPC/AliAnalysisTaskUPCforwardMC.cxx
- PWGUD/UPC/AliAnalysisTaskUPCforwardMC.h
Added the supposedly final binning for the 1D polarisation analysis. Things seem to work pretty nicely...
Added a further check on the muoncalo_pass3 => Invariant Mass Distributions in rapidity bins, to check if the fraction of PsiPrime to J/Psi changes at all.
> PWGUD/UPC: Polarisation update + check for muoncalo_pass3

- PWGHF/treeHF/AliAnalysisTaskSEHFTreeCreator.cxx
TreeCreator was combining both offline and on-the-fly v0's for pp. Fixed, now only selecting offline ones as is done for Lc analyses.
(Didn't show up in validation TreeCreator with PbPb because there are no on-the-fly v0's. SQM '19 preliminaries not affected)
> PWGHF: Fix TreeCreator Lc->pK0s

- PWGCF/FEMTOSCOPY/AliFemto/AliFemtoEventReaderAOD.cxx
Delete an "AliFemtoTrack" object before the "continue" function in a loop if a cut rejects this track. In femtoscopic analysis (heavy ions collisions) such objects which are not deleted when we are going back to the beginning of the loop lead to a large memory leak.
> Changes in a readerAOD class.

- PWG/EMCAL/EMCALbase/AliEmcalStringView.h
The compilation of AliPhysics with ROOT6-10-08 is broken due to below error.
>/localone/alice/sw/SOURCES/AliPhysics/aliroot6/0/PWGJE/EMCALJetTasks/Tracks/AliAnalysisTaskEmcalJetIterativeDeclustering.cxx:201:14: error: ambiguous overload for 'operator==' (operand types are 'const string_view {aka const std::experimental::__ROOT::basic_string_view<char>}' and 'const char [5]')
>    if(trigger == "INT7") triggerbits = AliVEvent::kINT7;
>       ~~~~~~~~^~~~~~~~~
The failed production was ordered on today's tag for alidist, AliPhysics and AliRoot with
> aliBuild build AliPhysics --defaults user-root6 -z aliroot6
with the same today's tags the productions with ROOT5 and with ROOT6-16-00
> aliBuild build AliPhysics --defaults user -z aliroot5
> aliBuild build AliPhysics --defaults …
> Fix for broken compilation with ROOT6-10-8

- PWGDQ/dielectron/macrosLMEE/Config_acapon.C
- PWGDQ/dielectron/macrosLMEE/LMEECutLib_acapon.C
Needed for run1 vs run2 comparisons to enable ~direct comparisons
between regions that were operating in similar states. The selected
regions in eta/phi are somewhat consistent between run1 and run2 for
the ITS.
> Add cut setting for eta/phi region selection

- PWGCF/FEMTOSCOPY/AliFemtoUser/AliFemtoPairCutMergedFraction.cxx
- PWGCF/FEMTOSCOPY/AliFemtoUser/AliFemtoPairCutMergedFraction.h
(0.5 T is default but in some runs, for example Xe-Xe run we have 0.2 T)
> Changes that allow to change magnetic field value 

- PWGLF/RESONANCES/AliRsnCutV0.cxx
- PWGLF/RESONANCES/macros/mini/ConfigSigPM.C
1. dca to be in abs in the custom dca of V0 daughters
2. minor change in sigma star config macro for PbPb 2018
> dca to be in abs in the custom dca of V0 daughters

- PWGGA/GammaConvBase/AliConvEventCuts.cxx
AliAODBContainer was never deleted and therefore created for every event
> PWGGA/GammaConv: fixed mem leak in trigger mimicking

- PWGPP/EMCAL/AliAnalysisTaskEMCALTimeCalib.cxx
The code crashing when setting fFillHeavyHisto to kFALSE due to a mistake. Now it is fixed.
> Fixing a problem with the code

- PWGGA/GammaConv/AliAnalysisTaskNeutralMesonToPiPlPiMiNeutralMeson.cxx
- PWGGA/GammaConv/AliAnalysisTaskNeutralMesonToPiPlPiMiNeutralMeson.h
- PWGGA/GammaConv/AliGammaConversionAODBGHandler.cxx
- PWGGA/GammaConvBase/AliConversionMesonCuts.cxx
- PWGGA/GammaConvBase/AliConversionMesonCuts.h
in this PR the event mixing for heavy mesons was rewritten to increase speed. Furthermore, instead of calculating four individual background histograms depending on which pions are allowed to be from the same even, only a single event mixing background is calculated, where the user can specify in AliConversionMesonCuts a mode from 1 to 4, where 4 is no pions coming from the same event (default).
Furthermore a bug in the BGHandler was fixed, that caused only every second event mixing pool to be filled.
> PWGGA/GammaConv: major change in heavy meson back calc

- PWGHF/treeHF/AliAnalysisTaskSEHFTreeCreator.cxx
Fix in RemovalDaughtersPV in PR #11131 was only needed for Lc's. For the D's it was correct, and the reposition actually introduced a small inconsistency. Reverted + a fix for Dstar (not removing soft pion as is done in AliRDHFCutsDStartoKpipi)
> PWGHF: Fix TTreeCreator

- PWGDQ/dielectron/macrosLMEE/AddTask_acapon_Efficiency.C
- PWGDQ/dielectron/macrosLMEE/Config_acapon.C
- PWGDQ/dielectron/macrosLMEE/LMEECutLib_acapon.C
Fix event selection in efficiency task. Arguments were not updated during last update.
Adds a cut selection which is inverse to "kGoodEtaPhi" in its eta/phi selection. All other track and PID cuts are identical.
> Add inverse good phi/eta cut & fix event sel. bug

- PWGHF/vertexingHF/AliRDHFCutsLctopKpi.cxx
Bug found when validating HFTreeCreator for the nSigma and nSigmaMin PID options (the default case). Fix reduces the number of selected candidates with ~30%, using filtering cuts + 3sigma TPC+TOF.
NB: For our published Lc physics papers, more advanced PID selection strategies were used that are not affected by this bug.
> PWGHF: Fix Lc->pKpi nSigma PID selection

- PWGJE/EMCALJetTasks/UserTasks/AliAnalysisTaskEmcalJetHUtils.cxx
- PWGJE/EMCALJetTasks/UserTasks/AliAnalysisTaskEmcalJetHUtils.h
- PWGJE/EMCALJetTasks/macros/AddTaskFlowQnVectorCorrections.C
The AddTask doesn't allow for configuration of the calibration output,
which is large enough to cause merging issues. Unfortunately, to make
this configurable, I had to copy almost all of the code from the existing
AddTask (located at PWGPP/EVCHAR/FlowVectorCorrections/QnCorrectionsInterface/macros/AddTaskFlowQnVectorCorr ectionsNewDetConfig.C).
The benefits are that the AddTask is more configurable, including the
outputs (I switched to using YAML for the config because it's familiar),
and the code is compiled instead of interpreted.
> Add Qn Corrections AddTask with configurable outputs

- PWGGA/GammaConv/macros/AddTask_GammaCalo_pPb.C
- PWGGA/GammaConv/macros/AddTask_GammaCalo_pp.C
- PWGGA/GammaConv/macros/AddTask_GammaConvCalo_pPb.C
- PWGGA/GammaConv/macros/AddTask_GammaConvCalo_pp.C
- PWGGA/GammaConvBase/AliCaloPhotonCuts.cxx
- PWGGA/GammaConvBase/AliCaloPhotonCuts.h
The datapoints and fits for the TB NL can be found in the following plots.
[nonlin_Martin_50MeV.pdf](https://github.com/alisw/AliPhysics/files/3505005/nonlin_Martin_50MeV.pdf)
[nonlin_Martin_100MeV.pdf](https://github.com/alisw/AliPhysics/files/3505006/nonlin_Martin_100MeV.pdf)
[nonlin_Martin_150MeV.pdf](https://github.com/alisw/AliPhysics/files/3505007/nonlin_Martin_150MeV.pdf)
[nonlin_Martin_300MeV.pdf](https://github.com/alisw/AliPhysics/files/3505008/nonlin_Martin_300MeV.pdf)
> PWGGA/GammaConv: Added TB NL params for 50,150,300 MeV thresholds + configs pp,pPb

- OADB/COMMON/MULTIPLICITY/AliMultSelectionCalibratorMC.cxx
- OADB/COMMON/MULTIPLICITY/AliMultSelectionCalibratorMC.h
- OADB/COMMON/MULTIPLICITY/macros/calibration/CalibratePeriodMC.C
- OADB/COMMON/MULTIPLICITY/macros/calibration/CalibratePeriodpPb.C
- OADB/COMMON/MULTIPLICITY/macros/calibration/CompareVtxPositionDifferentPeriods.C
- bug fix for the OADB creation macro in pPb to correctly read the parameters of the Z-vertex correction from the root-input file
- inverting axis of the debug output per run for the MC calibration in order to ease comparisons for the supercalib
> OADB/COMMON/MULTIPLICITY: bug-fix in macro OADB-creation for pPb

- PWGCF/Correlations/JCORRAN/Pro/AliJJetJtAnalysis.cxx
- PWGCF/Correlations/JCORRAN/Pro/AliJJetJtTask.cxx
Correct crash when using other than V0 for centrality
Remove unnecessary warnings from vector indices
> Bug fixes to jT analysis

- PWG/EMCAL/EMCALtasks/AliEmcalCorrectionCellTimeCalib.cxx
The OADB file that has merged BCs has a different name from the one with 4 BCs. The correction frame was changed such that in case of running on merged BCs the OADB file "EMCALTimeCalibMergedBCs.root" will be read.
> Changing the name of the OADB file in case of running on Merged BCs

- PWGJE/EMCALJetTasks/CMakeLists.txt
- PWGJE/EMCALJetTasks/PWGJEEMCALJetTasksLinkDef.h
- PWGJE/EMCALJetTasks/Tracks/AliAnalysisTaskEmcalFastorMultiplicity.cxx
- PWGJE/EMCALJetTasks/Tracks/AliAnalysisTaskEmcalFastorMultiplicity.h
- PWGJE/EMCALJetTasks/macros/AddTaskEmcalFastorMultiplicity.C
Determining the FastOR mulitplicity as function of the
event centrality for different thresholds at ADC level.
Event selection is always min. bias to get unbiased
distributions, might accept also EMCAL triggers in the
future.
> [EMCAL-589] Determine FastOR multiplicity above threhold

- PWGGA/GammaConvBase/AliConvEventCuts.cxx
If the trigger specified in the cutstring does not match any trigger specified in the trigger mimicking function, return true. This avoids reloading the OADB root file for every event where the trigger values are stored
> PWGGA/GammaConv: fixed rising memory in trigger mimicing.

- PWGHF/hfe/AliHFEextraCuts.cxx
Comparison of non-zero value with constant in operator&&
always returns true, bitwise operator& expected.
> Fix compiler warnings

- PWG/CaloTrackCorrBase/AliCalorimeterUtils.cxx
- PWG/CaloTrackCorrBase/AliCalorimeterUtils.h
- PWG/EMCAL/EMCALbase/AliEMCALRecoUtils.cxx
- PWG/EMCAL/EMCALbase/AliEMCALRecoUtils.h
- PWG/EMCAL/EMCALtasks/AliEmcalCorrectionCellBadChannel.cxx
- PWG/EMCAL/EMCALtasks/AliEmcalCorrectionClusterizer.cxx
- PWG/EMCAL/EMCALtasks/AliEmcalCorrectionComponent.cxx
- PWG/EMCAL/EMCALtasks/AliEmcalCorrectionComponent.h
- PWG/EMCAL/config/AliEmcalCorrectionConfiguration.yaml
- PWG/EMCAL/macros/AddTaskEMCALTender.C
- TENDER/TenderSupplies/AliEMCALTenderSupply.cxx
- TENDER/TenderSupplies/AliEMCALTenderSupply.h
The correction framework was changed so that it loads one dimensional Bad Channel Map.
In order to use it you have to set the flag "load1DBadChMap" to true in the yaml configuration file.
> Changing the correction framwork and Tedner task to load 1D BC map

- PWGUD/UPC/AliAnalysisTaskUPCforward.cxx
- PWGUD/UPC/AliAnalysisTaskUPCforward.h
Fixed construction list a bit.
Added v2 of the neutron emission analysis. This time I am using the inherent ZDC activity through the isZNAfired() method and the corresponding ZNC method, instead of the energy threshold...
> PWGUD/UPC: Fix construction list. Add v2 ZDC analysis.

- PWGHF/treeHF/macros/AddTaskHFTreeCreator.C
- PWGHF/vertexingHF/AliVertexingHFUtils.cxx
* Fix in TTreeCreator to run the task twice in same train (needed for TTree and TTree+ITS3 improver comparison)
* Temporary fixes for the no-momentum conservation in the upgrade productions for beauty particles (per mille difference between sum daughters and mother, but big enough to get rejected)
* Temporary fix for the "unphysical" Bs and Lb decays in terms of charge of Ds/Lc and pi
> PWGHF: Fixes for Lb and Bs for ITS3 productions

- PWGJE/FlavourJetTasks/AliAnalysisTaskHFJetIPQA.cxx
- PWGJE/FlavourJetTasks/AliAnalysisTaskHFJetIPQA.h
- PWGJE/FlavourJetTasks/macros/AddTaskHFJetIPQA.C
- read in histograms with jetpt dependent threshold variables
- perform tagging on basis of single track, two or three tracks; add switch to exclude tagging via a single or two tracks
- fill histograms with number of correctly and falsely tagged jets for each method
-added switch to turn on and off Lund Plane investigations
-changed printf error outputs to AliError
> AliAnalysisTaskHFJetIPQA: Add IP based track counting tagger

- PWGHF/vertexingHF/AliAODRecoDecayHF2Prong.cxx
The not-conserving of momentum in ITS upgrade productions for B-decays is also rejecting signal candidates due to the mom. conservation in the general MatchToMC function (see also #11403). Added the function in the dedicated MatchToMCB3Prong, loosening the momentum check from 0.001% to 0.5%.
> PWGHF: Fix for Lb&Bs in ITS upgrade prods part2

- PWGHF/vertexingHF/AliAnalysisTaskSEXicTopKpi.cxx
- PWGHF/vertexingHF/AliRDHFCutsXictopKpi.cxx
1. info about pKpi or piKp case for generated Lc (Xic) added
2. tree filling only with generated particles implemented (when running on MC)
3. bug fix in AliRDHFCutsXictopKpi in the mass cut
> Xic->pKpi task updated

- PWGCF/Correlations/JCORRAN/Pro/AliJJetJtTask.cxx
LHC13 b c d e now calls MultSelection to get multiplicity information. The old method GetCentrality was removed.
> Multiplicity class compatible only to MultSelection

- PWGJE/EMCALJetTasks/macros/AddTaskSDKL.C
- PWGJE/EMCALJetTasks/macros/AddTaskSDKLResponse.C
apparently the absence of a newline at the end of an AddTask macro yields an interpreter mistake
> AddTask-s amended

- PWGUD/UPC/AliAnalysisTaskUPCforward.cxx
- PWGUD/UPC/AliAnalysisTaskUPCforward.h
- PWGUD/UPC/AliAnalysisTaskUPCforwardMC.cxx
Fix run selection. XNXN rapidity-wise (both invariant mass spectra and pt-distributions!).
IMPORTANT: tested (and checked code by hand by seeing how many entries are there in each case...);
> PWGUD/UPC: Fix run selection. XNXN rapidity-wise.

- PWGCF/FEMTOSCOPY/AliFemto/AliAnalysisTaskFemto.cxx
alien-token-init cannot be called since it causes problems with the services
> AliFemto: removing calling alien-token-init

- PWGHF/vertexingHF/AliAnalysisTaskSEDs.cxx
- PWGHF/vertexingHF/AliAnalysisTaskSEDs.h
- PWGHF/vertexingHF/CMakeLists.txt
- PWGHF/vertexingHF/PWGHFvertexingHFLinkDef.h
- PWGHF/vertexingHF/macros/AddTaskDs.C
First implementation of the application of a BDT model trained in python to the Ds candidate selection.
At the moment treelite is present only in the builds with ROOT6 so the Ds task is constrained to this ROOT version.
Hopefully a temporary fix.
> Add ML application in Ds task

- PWGPP/TRD/AliTRDdigitsFilter.cxx
- PWGPP/TRD/AliTRDdigitsFilter.h
- PWGPP/TRD/AliTRDdigitsTask.cxx
- PWGPP/TRD/AliTRDdigitsTask.h
- PWGPP/TRD/macros/AddTRDdigitsFilter.C
The classes to filter a small subset of the TRD digits during 
reconstruction for later studies of electron PID and high-pT tracks have 
been revised in preparation for the Pb-Pb production.
The AliTRDdigitsFilter class now inherits from the AliTRDdigitsTask 
class. The selection criteria were made more flexible, and selecting a 
small section of events based on centrality is supported.
The selection criteria still need some tuning.
> Revise TRD digits filtering

- PWGHF/vertexingHF/upgrade/AliAnalysisTaskSEImproveITS3.cxx
ITS3Improver crashes when trying to run over standard PbPb MC's (for example GP PbPb '18). Candidates needs to be filled first.
> PWGHF: Add filling cand in ITS3Improver

- PWGUD/UPC/AliAnalysisTaskUPCforward.cxx
Introducing fV0CDecision for empty decision and beam timing.
> PWGUD/UPC: Introducing fV0CDecision.

- PWGHF/treeHF/AliAnalysisTaskSEHFTreeCreator.cxx
- PWGHF/treeHF/AliAnalysisTaskSEHFTreeCreator.h
1) add flag to apply physics selection at the task level to avoid the storage of unwanted events (false by default, so nothing changed unless enabled explicitly)
2) add flag to enable random event downsampling (false by default, so nothing changed unless enabled explicitly). Needed in case of a necessity of a homogeneous fraction of the data sample
> Add flags to apply physics selection and event downsampling

- PWGJE/EMCALJetTasks/UserTasks/AliAnalysisTaskEmcalJetHPerformance.cxx
- PWGJE/EMCALJetTasks/UserTasks/AliAnalysisTaskEmcalJetHPerformance.h
- PWGJE/EMCALJetTasks/UserTasks/AliAnalysisTaskEmcalJetHUtils.cxx
- PWGJE/EMCALJetTasks/UserTasks/AliAnalysisTaskEmcalJetHUtils.h
Moving the matching to the user task is a work around for issues with LHC15o embedding when using full jets
> Implement jet matching in user task

- PWGGA/GammaConv/AliAnalysisTaskGammaConvDalitzV1.cxx
- PWGGA/GammaConv/AliAnalysisTaskGammaConvDalitzV1.h
- PWGGA/GammaConv/macros/AddTask_GammaConvDalitzV1_pp.C
Systematics trains for MC were too heavy, so I believe that splitting them and remove one TH3F histogram will do the job.
Regards
Ed
> Comment of TH3F and splitting trains

- OADB/COMMON/MULTIPLICITY/AliMultSelectionTask.h
(This isn't relevant for the vast majority of people, but sometimes, under specific circumstances, people use stored copies of AliMultSelectionTask - in which case this of course matters!)
> Forgot to increment classdef

- PWG/EMCAL/EMCALbase/AliAnalysisTaskEmcal.cxx
- PWG/EMCAL/EMCALbase/AliAnalysisTaskEmcal.h
- PWG/EMCAL/EMCALbase/AliAnalysisTaskEmcalEmbeddingHelper.cxx
- PWG/EMCAL/EMCALtasks/AliEmcalCorrectionTask.cxx
- PWG/EMCAL/EMCALtasks/AliEmcalCorrectionTask.h
- PWG/EMCAL/config/AliEmcalCorrectionConfiguration.yaml
- PWGJE/EMCALJetTasks/UserTasks/AliAnalysisTaskEmcalJetHCorrelations.cxx
- PWGJE/EMCALJetTasks/UserTasks/AliAnalysisTaskEmcalJetHPerformance.cxx
This takes advantage of a new feature in `AliAnalysisManager`. This way,
the users don't need to enable embedded event recycling. However, this
does slightly change procedure because the later user task internal event
counting won't be accurate - the user task won't be executed.
> Early execution break when recycling an external event

- PWGJE/EMCALJetTasks/UserTasks/AliAnalysisTaskEmcalJetHCorrelations.cxx
Allows for the possibility of expanding the background dominated region.
Note that to take advantage and fully fill out to +/- 1.4, the user must
extend the eta acceptance out to +/-0.9. Otherwise, it can't populate
the correlations out to +/-1.4.
> Expand delta eta range

- PWGLF/STRANGENESS/Cascades/Run2/AliAnalysisTaskStrangeCascadesDiscrete.cxx
- PWGLF/STRANGENESS/Cascades/Run2/AliAnalysisTaskStrangeCascadesDiscrete.h
- PWGLF/STRANGENESS/Cascades/Run2/macros/AddTaskStrangeCascadesDiscrete.C
- The information about the prompt V0 is not included in the output file anymore.
- Tighter topological cuts are used for the analysed tracks, thus making the output lighter.
- The structure of the output file (TTree) is changed (nested now).
- As a result the output file is of order 200(!) lighter than in the previous version.
> Change the structure of the output files and their size

- PWGGA/CaloTrackCorrelations/macros/ConfigureCaloTrackCorrAnalysis.C
to avoid high pT cluster suppression above 80 GeV, increase low energy cluster cut to 0.7 GeV and increase histograms energy rage to 200 GeV
> Increase cluster maximum energy cut to 300 GeV 

- PWGDQ/dielectron/core/AliAnalysisTaskElectronEfficiencyV2.cxx
- PWGDQ/dielectron/core/AliAnalysisTaskElectronEfficiencyV2.h
- Add Setter so multiplicity estimator can be chosen. Defaults to V0M.
- Remove unused SetRun1Analysis() function for clarity.
- Reordered and formatted initialisation list.
> Add setter for mult. estimator (LMEE effV2)

- PWGUD/UPC/AliAnalysisTaskUPCforward.cxx
Imposed the invariant mass selection on the ZDC energy spectra to produce the famous performance plots for the ZNC and the ZNA.
> PWGUD/UPC: Invariant mass selection ZDC energy spectra.

- PWGCF/FEMTOSCOPY/AliFemtoUser/AliFemtoAnalysisPionPion.cxx
The error was:
/home/zampolli/SOFT/alibuild/ali-master/sw/SOURCES/AliPhysics/master/0/PWGCF/FEMTOSCOPY/AliFemtoUser/AliFemtoAnalysisPionPion.cxx:463:27: error: no match for 'operator==' (operand types are 'std::pair<double, double>' and 'const RangeF_t {aka const std::pair<float, float>}')
assert(params.pion_1_pt == default_pion.pt);
The two pairs are made one of doubles and one of floats. The comparison operator
does not know how to resolve this.
Thanks also to @shahor02 for the hints.
> Fix for compilation in DEBUG mode.

- PWGUD/UPC/AliAnalysisTaskUPCforwardMC.cxx
The code for the template was using an invariant mass selection a priori...
I had not realised this when running on the CohJPsi MC because they are already in that range.
Considering that I am dealing with rapidity integrated invariant mass plots, I can use them for the fits, but this has to be amended...
> PWGUD/UPC: Fix invariant mass range in templates pol.

- PWGHF/vertexingHF/upgrade/AddTaskLbUPG.C
- PWGHF/vertexingHF/upgrade/AliAnalysisTaskSELbtoLcpi4.cxx
- PWGHF/vertexingHF/upgrade/AliAnalysisTaskSELbtoLcpi4.h
* Added temporary "fix-flags" (related to selected background) to compare old ITS2 analysis with  new ITS3 one. Fixes to be made final after checks+discussions.
* Fixed some memory leaks.
* Only require PID for pion track when PID is also required for the Lc candidate.
* Added possibility to skip the rotational background part, so task is less heavy for running tests.
> PWGHF: Temporary fixes for ITS3 Lb analysis

- PWGHF/treeHF/AliAnalysisTaskSEHFTreeCreator.cxx
- PWGHF/vertexingHF/AliAODRecoDecayHF2Prong.cxx
- PWGHF/vertexingHF/AliVertexingHFUtils.cxx
* Several correct beauty candidates in the ITS Upgrade MC's were still rejected by the momentum conservation check. Loosened the check further, and added a strategy to tag and use them add task level (with negative labels).
* Store the still rejected decays in TTreeCreator for offline study (tagging them as "feed-down", as this flag wasn't used for beauty decays)
* Removed resonance check in MatchToMCB3Prong, didn't work as expected
> PWGHF: Loosen mom. consv. check for beauty ITS upgrade studies

- PWGUD/UPC/AliAnalysisTaskUPCforward.cxx
- PWGUD/UPC/AliAnalysisTaskUPCforward.h
I am doing now the polarisation analysis both in 1D and 2D, both with HE and CS frames, with the 0N0N neutron emission class. This suppresses completely the incoherent component and the feed-down contribution, e.g. the pt-distributions!! This means that once the values are extracted, this different analysis would be able to switch immediately to the systematics...
> PWGUD/UPC: Pol 1D and 2D with 0N0N class.

- PWGHF/vertexingHF/upgrade/AliAnalysisTaskSELbtoLcpi4.cxx
- PWGHF/vertexingHF/upgrade/AliAnalysisTaskSELbtoLcpi4.h
* Fixed the biggest and most obvious memory leak in the Lb rotation procedure by merging the rotate function (that returned an array full off "hidden" pointers) and the histogram filling function (that used the array).
* Cleaned the code
Tested on 1 AOD locally: exact same result as before fix+cleaning.
> PWGHF, Lb: Memory leak fix + cleaning code

- PWGJE/EMCALJetTasks/AliEmcalJetTaggerTaskFast.cxx
If NcentBins was set after constructing the object to anything greater
than 4, it would write the histogram out of bounds.
Also added a warning that the task isn't yet validated and that the
standard tagger should be used.
> Fix out-of-bounds write, add validation warning

- PWGDQ/dielectron/CMakeLists.txt
- PWGDQ/dielectron/PWGDQdielectronLinkDef.h
- PWGDQ/dielectron/core/AliAnalysisTaskJpsiJet.cxx
- PWGDQ/dielectron/core/AliAnalysisTaskJpsiJet.h
- PWGDQ/dielectron/macrosJPSI/AddTaskJpsiJet_pp.C
In this pull request, the new analysis task and corresponding AddTask macro have been created for J/psi in jets analysis. Since the task utilizes the existed EMCal jet framework, related dependencies were imported by CMake.
Here is the change log:
* PWGDQ/dielectron/core/AliAnalysisTaskJpsiJet.h/cxx - main task for this analysis, including dielectron pairing (by AliDielectron), jet finding (AliEmcalJetTask) and histogram manager (THistManager).
* PWGDQ/dielectron/macrosJPSI/AddTaskJpsiJet_pp.C - macro for LEGO train.
* CMakeLists.txt - import external package __fastjet__, add dependency on PWGJETFW and include path for PWG/EMCAL/EMCALbase, PWG/JETFW, PWGJE/EMCALJetTasks, PWG/Tools. This change refers to PWGHF/jetsHF.
* PWGDQ/dielectron/PWGDQdielectronLinkDef.h - add .cxx of this task. …
> DQ/JpsiJet - NEW task and macro for J/psi in jets analysis

- PWGDQ/dielectron/CMakeLists.txt
- PWGDQ/dielectron/PWGDQdielectronLinkDef.h
- PWGDQ/dielectron/core/AliAnalysisTaskJpsiJetFilter.cxx
- PWGDQ/dielectron/core/AliAnalysisTaskJpsiJetFilter.h
- PWGDQ/dielectron/macrosJPSI/AddTaskJpsiJetFilter_pp.C
- PWGDQ/dielectron/macrosJPSI/AddTaskJpsiJet_pp.C
- PWGDQ/reducedTree/CMakeLists.txt
This PR contains bug fix for https://github.com/alisw/AliPhysics/pull/11766 and new AOD filter task.
* CMakeLists.txt - PWGJEEMCALJetTasks is used in JpsiJet task. To fix the linking error, path and dictionary of __fastjet__ should be added for __reducedTree__ as well (but no more dependencies).
* JpsiJetFilter - similar with DielectronFilter, but stores all tracks and fill a jet branch.
Regards,
Yitao
> DQ/JpsiJet - Updates from grid test on vAN-20190923

- PWGHF/vertexingHF/AliAnalysisTaskSEXicTopKpi.cxx
- PWGHF/vertexingHF/AliRDHFCutsXictopKpi.cxx
- PWGHF/vertexingHF/macros/AddTaskSEXicTopKpi.C
1) AddTask modified - container name can be set by the user
2) fix in AliRDHFCutsXictopKpi::IsSelectedPID about the kaon PID
3) in AliAnalysisTaskSEXicTopKpi::UserExec() the fCutsXic->IsEventSelected has been added
---> mandatory to correctly set the Bayes PID
---> we'll remove the AliRDHFCutsDtoKpi object soon (still temporary solution)
> Important fixes for Xic->pKpi task

- PWGGA/Hyperon/macros/AddTaskSigma0LowBtest.C
In file included from input_line_79:1:
In file included from /home/alitrain/train-workdir/PWGCF/CF_pp_MC_ESD/247_20190925-2122/config/handlers.C:5:
/cvmfs/alice.cern.ch/el6-x86_64/Packages/AliRoot/v5-09-50_ROOT6-1/ANALYSIS/macros/train/AddMCHandler.C:1:20: error: definition with same mangled name as another definition
AliMCEventHandler* AddMCHandler(Bool_t readTrackRef = kFALSE)
^
/cvmfs/alice.cern.ch/el6-x86_64/Packages/AliRoot/v5-09-50_ROOT6-1/ANALYSIS/macros/train/AddMCHandler.C:1:20: note: previous definition is here
AliMCEventHandler* AddMCHandler(Bool_t readTrackRef = kFALSE)
> Remove includes since ESD MC trains cannot run with Root 6

- PWG/CaloTrackCorrBase/AliCalorimeterUtils.cxx
- PWG/CaloTrackCorrBase/AliCalorimeterUtils.h
- PWG/EMCAL/EMCALbase/AliEMCALRecoUtils.cxx
- PWG/EMCAL/EMCALbase/AliEMCALRecoUtils.h
- PWG/EMCAL/EMCALtasks/AliEmcalCorrectionCellBadChannel.cxx
- PWG/EMCAL/EMCALtasks/AliEmcalCorrectionCellEnergy.cxx
- PWG/EMCAL/EMCALtasks/AliEmcalCorrectionCellEnergy.h
- PWG/EMCAL/EMCALtasks/AliEmcalCorrectionClusterizer.cxx
- PWG/EMCAL/config/AliEmcalCorrectionConfiguration.yaml
- PWGPP/EMCAL/AliAnalysisTaskEMCALClusterize.cxx
- PWGPP/EMCAL/AliAnalysisTaskEMCALClusterize.h
- TENDER/TenderSupplies/AliEMCALTenderSupply.cxx
- TENDER/TenderSupplies/AliEMCALTenderSupply.h
We converted the 2D histogram of the energy recalibration into a 1D histogram. Also the correction framework has been modified so it can read 1D histogram. By default this option is disabled and it be enabled in the yaml file by setting "load1DRecalibFactors" to "true".
> Converting the Energy Recalib histogram to 1D histogram

- PWG/CaloTrackCorrBase/AliCalorimeterUtils.cxx
- PWG/CaloTrackCorrBase/AliCalorimeterUtils.h
- PWG/EMCAL/EMCALbase/AliEMCALRecoUtils.cxx
- PWG/EMCAL/EMCALbase/AliEMCALRecoUtils.h
- PWGPP/EMCAL/AliAnalysisTaskEMCALTimeCalib.cxx
L1 phase in EMCal time calibration macro modified to store object with PAR Global IDs.
AliCalorimeterUtils modified to read OADB object with PAR Global IDs for EMCal.
AliEMCALRecoUtils modified to access L1 phases for PAR runs.
Default is still like for the run without PAR.
> Read and access L1 phases for PAR runs in EMCal

- PWGDQ/dielectron/PWGDQdielectronLinkDef.h
AliAnalysisTaskJpsiJet depends on fastjet. The class is correctly compiled only when fastjet is found, but the dictionary creation does not have any protection.
This PR fixes it.
> Fix compilation when fastjet is disabled

- PWGGA/GammaConvBase/AliCaloPhotonCuts.cxx
PWGGA/GammaConvBase: Added non-linearity corrections for MC periods LHC19g7a, LHC19g7b, LHC19g7c
> Non-linearity corrections for 3 new MC productions

- PWG/DevNanoAOD/AliAnalysisNanoAODCuts.cxx
- PWG/DevNanoAOD/AliAnalysisNanoAODCuts.h
- PWG/DevNanoAOD/AliAnalysisTaskNanoAODFilter.h
- PWG/DevNanoAOD/AliNanoAODReplicator.cxx
- PWG/DevNanoAOD/AliNanoAODReplicator.h
- PWG/DevNanoAOD/PWGDevNanoAODLinkDef.h
o implementation of a AliAnalysisCut class for the MC stack
o matchig of the photons and v0
o to be done: cascades
The filtering can be steered from the AddTask e.g.
AliAnalysisNanoAODMCParticleCuts* mcCuts = new AliAnalysisNanoAODMCParticleCuts;
mcCuts->SetMinPt(0.1);
mcCuts->SetMaxEta(2);
mcCuts->SetKeepParticles( {333, 3212} );
mcCuts->SetKeepV0s( {3122} );
filterTask->FilterMCStack(mcCuts);
> Filtering for the MC truth of V0, photons and cascades for the Nano

- PWG/EMCAL/EMCALtasks/AliEmcalCorrectionCellTimeCalib.cxx
- PWG/EMCAL/EMCALtasks/AliEmcalCorrectionCellTimeCalib.h
- PWG/EMCAL/config/AliEmcalCorrectionConfiguration.yaml
I modified the correction framework so it calibrates the LG cells. The correction framework reads from OADB a file "EMCALTimeCalibMergedBCLG.root" which contains the histograms containing the LG time calibration coefficients for all the periods merged in one histogram.
> EMCal low gain cells calibration

- PWGDQ/dielectron/core/AliDielectronMixingHandler.cxx
- For AODs PR8329 was effective (since the default ID did not appear for AOD tracks apparently)
- For ESDs it seems that tracks have ID 0 by default, which then causes double assignments again
- quick solution: use 1 instead of 0 (helped at least in the test case, where it was observed, and didn't lead to returning of NULL pointers)
> Fix PR8329 for ESDs: initialization to 1 (instead of 0)

- PWGGA/GammaConv/AliAnalysisTaskNeutralMesonToPiPlPiMiNeutralMeson.cxx
- PWGGA/GammaConv/macros/AddTask_GammaConvNeutralMesonPiPlPiMiNeutralMeson_CaloMode_pp.C
- PWGGA/GammaConvBase/AliConversionMesonCuts.cxx
- PWGGA/GammaConvBase/AliConversionMesonCuts.h
Implemented new cut that allows to select only neutral meson candidates where at least one (or two) gammas from neutral meson fulfill energy threshold. 
Can be set via minPt cut in AliConversionMeson, but has to be treated properly in analysis task itself.
> PWGGA/GammaConv: implementation of gamma from pi0 energy cut

- PWGPP/EMCAL/AliAnalysisTaskEMCALTimeCalib.cxx
Main changes: 
- fCurrentPARIndex=0 means events before any PAR. Changed histogram filling according to this scheme. 
- when low number of entries after PAR for some SM -> this SM is not treated as empty if before PAR it was filled
- added clearer printouts in case of problems
> Tuning of L1 phase extraction for PAR runs in EMCal

- PWGCF/FEMTOSCOPY/AliFemtoUser/AliFemtoWRzTrackCut.cxx
- PWGCF/FEMTOSCOPY/AliFemtoUser/AliFemtoWRzTrackCut.h
- PWGCF/FEMTOSCOPY/AliFemtoUser/CMakeLists.txt
- PWGCF/FEMTOSCOPY/AliFemtoUser/PWGCFfemtoscopyUserLinkDef.h
A new class that allows you to set in a config file different cuts on DCA for different ranges of pt -- to kanon-proton femto analysis. This class is an extension of AliFemtoMJTrackCut.
> A new class that allows you to set different cuts on DCA for different ranges of pt

- RUN3/AliAnalysisTaskAO2Dconverter.cxx
- RUN3/AliAnalysisTaskAO2Dconverter.h
- RUN3/convertAO2D.C
- The use of event cuts is optional
- The collision time is used from the best method without momentium dependency
- MUON, MUON clusters, ZDC, VZERO as proxy for FIT added
- V0s and cascades added as pairs of indexes
- MC information excluded for the moment, to be replaced
- TOF clusters excluded for the moment, to be clarified
> Updated version of the Run3 convertor.

- PWGPP/macros/AddTaskFilteredTree.C
The previous settings were affecting all tasks in the QA and AOD
trains.
> Use kError for the log level only for the filteredTrees task.

- PWGHF/hfe/AliAnalysisTaskFlowTPCEMCalRun2.cxx
- PWGHF/vertexingHF/AliAnalysisTaskSEDplus.cxx
- PWGHF/vertexingHF/AliAnalysisTaskSEDplus.h
- PWGHF/vertexingHF/AliAnalysisTaskSEDs.cxx
- PWGHF/vertexingHF/AliAnalysisTaskSEDs.h
- PWGHF/vertexingHF/CMakeLists.txt
- PWGHF/vertexingHF/PWGHFvertexingHFLinkDef.h
- PWGHF/vertexingHF/charmFlow/AliAnalysisTaskSECharmHadronvn.cxx
- PWGHF/vertexingHF/charmFlow/AliAnalysisTaskSECharmHadronvn.h
- PWGHF/vertexingHF/vHFML/AliHFMLResponse.cxx
- PWGHF/vertexingHF/vHFML/AliHFMLResponse.h
- PWGHF/vertexingHF/vHFML/AliHFMLResponseDplustoKpipi.cxx
- PWGHF/vertexingHF/vHFML/AliHFMLResponseDplustoKpipi.h
- PWGHF/vertexingHF/vHFML/AliHFMLResponseDstoKKpi.cxx
- PWGHF/vertexingHF/vHFML/AliHFMLResponseDstoKKpi.h
Co-authored-by: fcatalan92 <fabio.catalano@cern.ch>
1) add mother class for application of ML models trained offline with python on the grid for a generic HF particle that loads the inputs (model paths, pt bins, preselection, list of features on ML output) from a yaml configuration file
2) add classes for Ds and D+ mesons
3) update ML application in Ds task using the object
4) implement application of ML models in D+ and vn (for Ds and D+) tasks
> Add HF cut-object like classes for application of ML python models

- PWGHF/correlationHF/AliAnalysisTaskDHFeCorr.cxx
- PWGHF/correlationHF/AliAnalysisTaskDHFeCorr.h
Dear all,
I have solved a bugs in the code, it affected the cases where the AOD information for the D mesons needed to be filled on the fly (Pb-Pb). It does not affect pp or p-Pb.
Best,
Henrique
> Remove hardcoded mult. estimators and recalculate missing info for D

- PWGHF/vertexingHF/AliAnalysisVertexingHF.cxx
- PWGHF/vertexingHF/AliAnalysisVertexingHF.h
Skip second calculation of V0+bachelor invariant mass
Recompute primary vertex for 2prong candidates only when needed
Do not propagate neutral tracks to DCA
> Updates in Make2Prong for V0+bachelor treatement

- ML/CMakeLists.txt
Investigating some problems related to the number of libraries loaded in some PWGHF trains I founded that the ML library has unneeded dependencies. 
In my opinion this package should be as lightweight as possible, therefore I removed all the dependencies that seemed not necessary.
> Clean dependencies of ML package

- PWGUD/UPC/AliAnalysisTaskForMCpPb.cxx
- PWGUD/UPC/AliAnalysisTaskForMCpPb.h
- PWGUD/UPC/AliAnalysisTaskUPCforwardpPb.cxx
- PWGUD/UPC/AliAnalysisTaskUPCforwardpPb.h
Strict eta requirement per muon track both in data and MC.
Rapidity-wise analysis in data for -3.6 < y < -2.6.
> PWGUD/UPC: Pb-p analysis update.

- PWGJE/FlavourJetTasks/AliAnalysisTaskHFJetIPQA.cxx
- PWGJE/FlavourJetTasks/AliAnalysisTaskHFJetIPQA.h
- PWGJE/FlavourJetTasks/macros/AddTaskHFJetIPQA.C
- enable reading of track probability threshold histograms
- move setting of thresholds to dedicated function ReadThresholdHists 
- introduce DoProbTagging for track probability tagging, same efficiency histograms as for TC tagging are utilised
> AliAnalysisTaskHFJetIPQA: add probability tagging

- PWGDQ/dielectron/core/AliDielectronEventCuts.cxx
- PWGDQ/dielectron/core/AliDielectronEventCuts.h
Adds TimeRangeCut to AliEventCuts object for recovering statistics in LHC18r period. Should not change default behaviour.
> PWGDQ: Added TimeRangeCut

- PWGHF/vertexingHF/AliAODRecoDecayHF3Prong.h
- PWGHF/vertexingHF/AliAnalysisTaskSEXicTopKpi.cxx
- PWGHF/vertexingHF/AliAnalysisTaskSEXicTopKpi.h
- PWGHF/vertexingHF/AliRDHFCutsCdeuterontodKpi.cxx
- PWGHF/vertexingHF/AliRDHFCutsCdeuterontodKpi.h
- PWGHF/vertexingHF/AliRDHFCutsXictopKpi.h
- PWGHF/vertexingHF/CMakeLists.txt
- PWGHF/vertexingHF/PWGHFvertexingHFLinkDef.h
C-deuteron reconstruction from AOD tracks using the XiC->pKpi class
- Implement option in AliAnalysisTaskSEXicTopKpi to run c-deuteron analysis, with c-deuteron MC ID and matching, deuteron ID and invariant mass window change
- new cuts class for c-deuteron, AliRDHFCutsCdeuterontodKpi, inheriting from AliRDHFCutsXictopKpi. Contains first function for 3sigma PID, and modifications in IsSelected for deuteron ID and invariant mass window
- Add function in AliAODRecoDecayHF3Prong to calculate c-deuteron mass from 3 prong decay
- change inheritence of member variables in AliRDHFCutsXictopKpi to allow for inheritence
> first implementation of c-deuteron reconstruction

- PWG/EMCAL/EMCALtasks/AliEmcalCorrectionCellTimeCalib.cxx
- PWG/EMCAL/config/AliEmcalCorrectionConfiguration.yaml
As we discussed in the EMCal meeting, we changed the correction framework to read by default the 1D bad channel maps and the 1D recalibration factors. Also now by default it will read the merged the BC histograms. Later, we will change the correction framework to calibrate the LG cells by default.
> Changing the correction framewrok to read by default the 1D OADB objects

- PWGPP/AliAnalysisTaskFilteredTree.cxx
Allow relative change of momenta between vertex and TPC - 60 % (was 30 %before)
> PWGPP-485- open cut pTPC/pvertex - to reduce Nuclei selection bias

- PWGLF/RESONANCES/macros/mini/AddTaskLambdaStarWithKinks.C
- PWGLF/RESONANCES/macros/mini/ConfigLambdaStarWithKinks.C
Update Lstar macros for PbPb 2018 data to include asymmetry cuts
> Update Lstar macros for PbPb 2018 data to include asymmetry cuts

- PWGUD/UPC/AliAnalysisTaskForMCpPb.h
- PWGUD/UPC/AliAnalysisTaskUPCforwardpPb.cxx
- PWGUD/UPC/AliAnalysisTaskUPCforwardpPb.h
Pb-p analysis:
- fixed run list
- fixed pt-distr (missing inv mass sel)
- Increased streamer in MC as a possible solution to the LEGO problem (not observed on GRID)...
IMPORTANT: tested a.d already fully run on GRID.
> PWGUD/UPC: several bug fixes + tentative solution to MC problem...?

- PWGPP/EvTrkSelection/AliAnalysisTrackingUncertaintiesAOT.cxx
- PWGPP/EvTrkSelection/AliAnalysisTrackingUncertaintiesAOT.h
The default setting is kDefault (compatibility with previous versions)
fESDtrackCuts = AliESDtrackCuts::GetStandardITSTPCTrackCuts2010(kFALSE,0);
fESDtrackCuts->SetMinRatioCrossedRowsOverFindableClustersTPC(fCrossRowsOverFndCltTPC);
Now, the fESDtrackCuts object can be set to one of the standard configurations through the function SetStandardESDtrkCuts
> Standard ESD track cuts configuration set from outside

- PWGJE/EMCALJetTasks/Tracks/AliAnalysisTaskEmcalJetEnergySpectrum.cxx
- PWGJE/EMCALJetTasks/Tracks/AliAnalysisTaskEmcalSoftDropData.cxx
Observables were part of the THnSparse, but when
moving back to ND-histograms in order to reduce
the memory consumption for the large datasets (pp
triggered and jj anchored to pp 13 TeV) they were
dropped. Added as 2D plots (always versus jet pt)
as QA plots always running.
> Re-introduce basic jet QA plots running all the time

- PWGHF/treeHF/AliAnalysisTaskSEHFTreeCreator.cxx
- PWGHF/vertexingHF/AliVertexingHFUtils.cxx
- PWGHF/vertexingHF/AliVertexingHFUtils.h
Phi meson not written in MC stack in new ITS2 production, so decay is read as non-resonant. Checking also invariant mass of KK-pair to tag now
> PWGHF: Fix for missing phi in Bs decay (ITS2 MC)

- PWGGA/GammaConv/AliAnalysisTaskGammaCalo.cxx
Threshold for jet unfolding process in neutral meson measurement inside jets has been changed from 5 GeV/c to 10 GeV/c.
5 GeV/c was for temporary test use, so it's been back to the original value.
> Jet unfolding threshold changed

- PWG/FLOW/Base/AliAnalysisTaskZDCEP.cxx
- PWG/FLOW/Base/AliAnalysisTaskZDCEP.h
- PWG/FLOW/Base/CMakeLists.txt
- PWG/FLOW/Base/PWGflowBaseLinkDef.h
- PWG/FLOW/Tasks/CMakeLists.txt
- PWG/FLOW/Tasks/PWGflowTasksLinkDef.h
- PWGHF/vertexingHF/CMakeLists.txt
- PWGHF/vertexingHF/charmFlow/AliAnalysisTaskHFv1.cxx
Remove dependency on PWGflowTasks from PWGHFvertexingHF for an issue on the LEGO trains.
For this purpose move AliAnalysisTaskZDCEP from PWGflowTasks to PWGflowBase since it is needed for the ZDC calibrations in the AliAnalysisTaskHFv1 task.
> Remove dependency on PWGflowTasks from PWGHFvertexingHF

- PWGDQ/dielectron/LMEE/AliAnalysisTaskSimpleTreeMaker.cxx
- PWGDQ/dielectron/LMEE/AliAnalysisTaskSimpleTreeMaker.h
Setter function added to enable storage of proton nSigma values for the
ITS, TPC and TOF (same manner as for Kaons). Default storage setting for
protons set to kFALSE.
> Add flag to store proton nSig values

- PWGLF/RESONANCES/AliRsnCutCascade.cxx
- PWGLF/RESONANCES/AliRsnCutCascade.h
- PWGLF/RESONANCES/AliRsnCutMiniPair.cxx
- PWGLF/RESONANCES/AliRsnCutMiniPair.h
- PWGLF/RESONANCES/AliRsnCutV0.cxx
- PWGLF/RESONANCES/AliRsnCutV0.h
- PWGLF/RESONANCES/AliRsnMiniAnalysisTask.cxx
- PWGLF/RESONANCES/AliRsnMiniOutput.cxx
- PWGLF/RESONANCES/AliRsnMiniOutput.h
Introduction of Pseudorapidity cuts on resonance daughters, method for extracting generated long-lived particles (pi±, K±, p) from MC, modification for Lambda+Lambda analysis
> modifications for analyses of rare resonances

- PWGGA/GammaConv/AliAnalysisTaskClusterQA.cxx
- PWGGA/GammaConv/AliAnalysisTaskConvCaloCalibration.cxx
- PWGGA/GammaConv/AliAnalysisTaskGammaCalo.cxx
- PWGGA/GammaConv/AliAnalysisTaskGammaCalo.h
- PWGGA/GammaConv/AliAnalysisTaskGammaCalo2.cxx
- PWGGA/GammaConv/AliAnalysisTaskGammaCaloIso.cxx
- PWGGA/GammaConv/AliAnalysisTaskGammaCaloMerged.cxx
- PWGGA/GammaConv/AliAnalysisTaskGammaConvCalo.cxx
- PWGGA/GammaConv/AliAnalysisTaskGammaConvCaloIso.cxx
- PWGGA/GammaConv/AliAnalysisTaskGammaConvV1.cxx
- PWGGA/GammaConv/AliAnalysisTaskGammaTriggerQA.cxx
- PWGGA/GammaConv/AliAnalysisTaskHeavyNeutralMesonToGG.cxx
- PWGGA/GammaConv/AliAnalysisTaskNeutralMesonToPiPlPiMiNeutralMeson.cxx
- PWGGA/GammaConv/AliAnalysisTaskOmegaToPiZeroGamma.cxx
- PWGGA/GammaConv/macros/AddTask_GammaCaloMerged_PbPb.C
- PWGGA/GammaConv/macros/AddTask_GammaCaloMerged_pPb.C
- PWGGA/GammaConv/macros/AddTask_GammaCaloMerged_pp.C
- PWGGA/GammaConv/macros/AddTask_GammaCalo_PbPb.C
- PWGGA/GammaConv/macros/AddTask_GammaCalo_pPb.C
- PWGGA/GammaConv/macros/AddTask_GammaCalo_pp.C
- PWGGA/GammaConv/macros/AddTask_GammaConvCalo_PbPb.C
- PWGGA/GammaConv/macros/AddTask_GammaConvCalo_pPb.C
- PWGGA/GammaConv/macros/AddTask_GammaConvCalo_pp.C
- PWGGA/GammaConv/macros/AddTask_GammaConvNeutralMesonPiPlPiMiNeutralMeson_CaloMode_pp.C
- PWGGA/GammaConv/macros/AddTask_GammaConvV1_PbPb.C
- PWGGA/GammaConv/macros/AddTask_GammaConvV1_pPb.C
- PWGGA/GammaConv/macros/AddTask_GammaConvV1_pp.C
- PWGGA/GammaConvBase/AliConvEventCuts.cxx
- PWGGA/GammaConvBase/AliConvEventCuts.h
By setting "PTHFROMFILE:1" in the same field as the maximum pthard fraction, one can now run with a possible fix for a problem in JJ MCs where events with lower pthard than intended are included.
> PWGGA/GammaConv: Added pthard bin detection from filepath

- PWGGA/GammaConv/macros/AddTask_GammaCaloMerged_PbPb.C
- PWGGA/GammaConv/macros/AddTask_GammaCaloMerged_pPb.C
- PWGGA/GammaConv/macros/AddTask_GammaCaloMerged_pp.C
- PWGGA/GammaConv/macros/AddTask_GammaCalo_PbPb.C
- PWGGA/GammaConv/macros/AddTask_GammaCalo_pPb.C
- PWGGA/GammaConv/macros/AddTask_GammaCalo_pp.C
- PWGGA/GammaConv/macros/AddTask_GammaConvCalo_PbPb.C
- PWGGA/GammaConv/macros/AddTask_GammaConvCalo_pPb.C
- PWGGA/GammaConv/macros/AddTask_GammaConvCalo_pp.C
- PWGGA/GammaConv/macros/AddTask_GammaConvNeutralMesonPiPlPiMiNeutralMeson_CaloMode_pp.C
- PWGGA/GammaConv/macros/AddTask_GammaConvV1_PbPb.C
- PWGGA/GammaConv/macros/AddTask_GammaConvV1_pPb.C
- PWGGA/GammaConv/macros/AddTask_GammaConvV1_pp.C
- PWGGA/GammaConvBase/AliConvEventCuts.cxx
- PWGGA/GammaConvBase/AliConvEventCuts.h
Using "ADDOUTLIERREJ:1" in the same string as the max fraction of pthard setting in the AddTask will now use the pthardbin from the filepath and reject events that lie outside of their originally generated range.
> PWGGA/GammaConv: Added additional outlier rejection based on pthard from path

- PWGHF/vertexingHF/upgrade/AliAnalysisTaskSEImproveITS3.cxx
- PWGHF/vertexingHF/upgrade/AliAnalysisTaskSEImproveITS3.h
ITS3Improver takes too long because it fills all HF candidates by default, flag to only process already filled ones
> PWGHF: Option to only process already filled candidates in ITS3Improver

- PWGHF/vertexingHF/upgrade/AliAnalysisTaskSEImproveITS3.cxx
ITS3ImproverTask was very slow due to GetEntries() call in loop (in combination with the huge amount of 3prongs stored in the new ITS Upgrade MC)
Processing 1 event: 5 minutes -> few seconds
> PWGHF: Speed up ITS3Improver

- PWGLF/RESONANCES/AliRsnCutMiniPair.cxx
- PWGLF/RESONANCES/AliRsnCutMiniPair.h
- PWGLF/RESONANCES/AliRsnMiniPair.cxx
- PWGLF/RESONANCES/AliRsnMiniPair.h
- PWGLF/RESONANCES/AliRsnMiniParticle.cxx
- PWGLF/RESONANCES/AliRsnMiniParticle.h
Introduced out-of-bunch pileup cut for resonance analyses. At least one final-state decay product of the resonance must have an ITS or TOF hit.
> Out-of-Bunch Pileup cut for resonances

- PWGHF/treeHF/AliAnalysisTaskSEHFTreeCreator.cxx
- PWGHF/vertexingHF/AliRDHFCutsLctoV0.cxx
- PWGHF/vertexingHF/AliRDHFCutsLctoV0.h
Attempt to speed-up running the Lc->pK0s analyses in Pb-Pb 2018 by adding a similar PreSelect function as used for the D mesons.
Note that we don't call the ReconstructSecondaryVertex() for the pK0s candidate, so the FillRecoCasc function is not as heavy as for the D mesons.
> PWGHF: Adding PreSelect for pK0s for Pb-Pb

- PWGCF/FEMTOSCOPY/FemtoDream/AliFemtoDreamPairCleaner.cxx
In CleanDecayAndDecay the UseParticle check was done twice on particle1 instead of both
> corrected paircleaner loop

- PWGLF/RESONANCES/AliRsnCutV0.cxx
- PWGLF/RESONANCES/AliRsnCutV0.h
- PWGLF/RESONANCES/macros/mini/AddTaskRare_pp13.C
Introduce alternate way to apply out-of-bunch pileup cut to v0s within resonance package.
> Out-of-Bunch Pileup cut for v0s

- PWG/FLOW/Tasks/AliAnalysisTaskTwoMultiCorrelations.cxx
- PWG/FLOW/Tasks/AliAnalysisTaskTwoMultiCorrelations.h
Major cleaning of the code with:
* Changed the Double_t and TH1D into Float_t and TH1F where it was possible
* Gathered the TH1 into different arrays to ease maintenance and future possible additions of control histograms
* Added support to compute correlators with v7 and v8 (previously up to v6)
* Removed unnecessary methods like nested loops to ease the readability
> PWGCF: Remove uncessary methods

- PWGJE/EMCALJetTasks/Tracks/AliAnalysisTaskEmcalJetEnergyScale.cxx
@mfasDa Whether the hist is a closure is currently applied as a weight for the sparse. I think this should be an axis (I think this was your intent based on how you define the binning). I'll leave this to you to approve or close
> Fix sparse binning

- PWGGA/GammaConv/AliAnalysisTaskNeutralMesonToPiPlPiMiNeutralMeson.cxx
- PWGGA/GammaConv/AliAnalysisTaskNeutralMesonToPiPlPiMiNeutralMeson.h
- PWGGA/GammaConv/macros/AddTask_GammaConvNeutralMesonPiPlPiMiNeutralMeson_CaloMode_pp.C
- PWGGA/GammaConvBase/AliConversionMesonCuts.cxx
Changes fix wrong efficiency and acceptance when using trigger mimicking with MC and the heavy meson task. Before, MC particles on generator lever were never processed for a rejected event, however, this is needed in order to account correctly for trigger efficiency which is not 100% near threshold.
> PWGGA/GammaConv: omega task, implemented correct trigger handling for MC

- PWG/EMCAL/EMCALtrigger/AliEmcalTriggerMakerKernel.h
- PWG/EMCAL/EMCALtrigger/AliEmcalTriggerMakerTask.cxx
- PWG/EMCAL/EMCALtrigger/AliEmcalTriggerMakerTask.h
Users no longer need to configure a smear model
by hand if they want to use a smeared patch energy
calculated from the FEE energy with the same
resolution as in data. The smearing is automatically
activated in data and MC. Currently the default
smearing is used - custom smear models would still
work.
> Automatic configuration of the energy smearing

- PWGHF/jetsHF/AliAnalysisTaskBJetTC.cxx
- PWGHF/jetsHF/AliAnalysisTaskBJetTC.h
I added jet probability templates for charm fractions (D0, Dplus, Ds, Lambda_c) to be reweighted with the correct fractions.
> Adding templates for D0 Dp Ds Lc to be reweighted

- PWGHF/vertexingHF/macros/AddTaskHFTreeCreatorApply.C
- PWGHF/vertexingHF/vHFML/AliAnalysisTaskSEHFTreeCreatorApply.cxx
- PWGHF/vertexingHF/vHFML/AliAnalysisTaskSEHFTreeCreatorApply.h
- PWGHF/vertexingHF/vHFML/AliHFMLResponseLctoV0bachelor.cxx
- PWGHF/vertexingHF/vHFML/AliHFMLResponseLctoV0bachelor.h
- PWGHF/vertexingHF/vHFML/AliHFTreeHandlerApply.cxx
- PWGHF/vertexingHF/vHFML/AliHFTreeHandlerApply.h
- PWGHF/vertexingHF/vHFML/AliHFTreeHandlerApplyDstoKKpi.cxx
- PWGHF/vertexingHF/vHFML/AliHFTreeHandlerApplyDstoKKpi.h
- PWGHF/vertexingHF/vHFML/AliHFTreeHandlerApplyLc2V0bachelor.cxx
- PWGHF/vertexingHF/vHFML/AliHFTreeHandlerApplyLc2V0bachelor.h
- PWGHF/vertexingHF/vHFML/CMakeLists.txt
- PWGHF/vertexingHF/vHFML/PWGHFvertexingHFMLLinkDef.h
Using the newly developed tools in the vHFML directory to apply a filtering XGBoost probability cut on the GRID before filling the TTrees.
**Note:**
Because of the treelite dependency of PWGHF/vertexingHF/vHFML dir, and the fastjet and EMCALjet dependencies of the PWGHF/treeHF dir, it was not (easily) possible to integrate the AliHFMLResponse class in the existing TTreeCreator task. I therefore made a stripped version of the TTreeCreator and TTreeHandler tasks and located them in the vHFML directory. Hopefully this is a temporary solution, as this duplicates code.
> PWGHF: Apply ML decision on GRID for TTreeCreator

- PWGGA/GammaConv/AliAnalysisTaskOmegaToPiZeroGamma.cxx
- PWGGA/GammaConv/AliAnalysisTaskOmegaToPiZeroGamma.h
- PWGGA/GammaConv/macros/AddTask_OmegaToPiZeroGamma_pp.C
I made the AliAnalysisTaskOmegaToPiZeroGamma compatible with the current correction task and updated the pp 13 TeV train config for EMCal to now use EMCal + DCal.
The second commit is for removing some couts which I forgot to delete in the first commit.
> AliAnalysisTaskOmegaToPiZeroGamma compatible with correction task

- PWGGA/GammaConv/macros/AddTask_GammaConvV1_pPb.C
train config 1600 with 3 set of cut numbers has been added for injet analysis.
1 for MB analysis
2 for injet analysis without jetQA
3 for injet analysis with jetQA
> New train config for injet analysis in pPb at 5 TeV added

- PWGGA/GammaConvBase/AliConversionMesonCuts.cxx
after a closer look by @jluehder it was discovered that not the FWHM of the pi0 has been used to determine the mass cut parametrisations but instead sigma. Therefore the additional conversion from FWHM to sigma in the task is wrong
> PWGGA/GammaConv: pt dep mass cut fix FWHM to sigma

- PWGDQ/dielectron/core/AliDielectronEventCuts.cxx
- PWGDQ/dielectron/core/AliDielectronEventCuts.h
PWGDQ/LMEE: add flexibility for centrality estimator in AliDielectronEventCuts
> PWGDQ/LMEE: add flexibility for centrality estimator in AliDielectronEventCuts

- ML/AliMLModelHandler.cxx
- ML/AliMLModelHandler.h
- ML/AliMLResponse.cxx
- ML/AliMLResponse.h
- ML/CMakeLists.txt
- ML/MLLinkDef.h
- PWGHF/vertexingHF/vHFML/CMakeLists.txt
This PR introduces some improvements to the treelite interface:
- it is no more needed to add the treelite and yaml-cpp include path in the makefile of the package that use AliMLResponse
- it is possible to pass directly a vector of variables to the model predict (can be useful to debug)
- the case in which the config file is in the current directory is now supported
@mpuccio @pfecchio What do you think?
> Some development of treelite ML interface 

- PWGLF/STRANGENESS/Cascades/Run2/AliAnalysisTaskStrangeCascadesDiscrete.cxx
- PWGLF/STRANGENESS/Cascades/Run2/AliAnalysisTaskStrangeCascadesDiscrete.h
- PWGLF/STRANGENESS/Cascades/Run2/macros/AddTaskStrangeCascadesDiscrete.C
- PWGLF/STRANGENESS/PWGLFSTRANGENESSLinkDef.h
1. Complementary classes (AliRunningCascadeEvent & AliRunningCascadeCandidate) are added to the PWGLFSTRANGENESSLinkDef.h
2. The Cascade z-component of DCA to the primary vertex is not saved any longer. Transverse component is enough.
3. TOF signal is stored as a float variable.
4. Cascade selection "clean up" (mass window) is added, this will reduce the output.
> Bugs fixed

- PWGGA/GammaConv/AliConversionAodSkimTask.cxx
- PWGGA/GammaConv/AliConversionAodSkimTask.h
- PWGGA/GammaConv/CMakeLists.txt
- PWGGA/GammaConv/PWGGAGammaConvLinkDef.h
- PWGGA/GammaConv/macros/AddTask_AodSkim.C
added AodSkimTask to GammaConv which is based on AliAodSkimTask and offers new functionality to skim for events with conversion photons with minPt and in given acceptance. I decided to create this "new" version in the GammaConv directory due to library linking issues when trying to access conversion photons from within the EMCal libraries. I think in the long run it would be best to use this macro by default.
> PWGGA/GammaConv: added AliConversionAodSkimTask

- PWGDQ/dielectron/macrosLMEE/Config_acapon.C
- PWGDQ/dielectron/macrosLMEE/Config_acapon_Efficiency.C
- PWGDQ/dielectron/macrosLMEE/LMEECutLib_acapon.C
- Addition of four new track cut settings designed to vary the
restriction on the number of shared hits in the ITS.
- Cut label: "ITSshared<X>" where <X> is the number of allowed shared hits in the ITS
- The new cut settings are identical to kScheidCuts apart from fITSshared cut
> Add varied cuts for ITS shared hits (acapon, LMEE)

- PWG/EMCAL/EMCALtasks/AliAnalysisTaskEmcalTriggerSelection.cxx
- PWG/EMCAL/EMCALtrigger/AliEmcalTriggerAlias.cxx
- PWG/EMCAL/EMCALtrigger/AliEmcalTriggerAlias.h
- PWG/EMCAL/EMCALtrigger/AliEmcalTriggerDecision.cxx
- PWG/EMCAL/EMCALtrigger/AliEmcalTriggerDecision.h
- PWG/EMCAL/EMCALtrigger/AliEmcalTriggerDecisionContainer.cxx
- PWG/EMCAL/EMCALtrigger/AliEmcalTriggerSelection.cxx
- PWG/EMCAL/EMCALtrigger/AliEmcalTriggerSelection.h
- PWG/EMCAL/EMCALtrigger/CMakeLists.txt
- PWG/EMCAL/EMCALtrigger/PWGEMCALtriggerLinkDef.h
Trigger aliases allow to have multiple names for the
same trigger condition. This is of relevance for the
Data period from 2012: The trigger classes were called
EGA and EJE, however in order to port code adapted to
data periods with EG1/EG2 and EJ1/EJ2, it is easier
to identify the trigger with either of the names (EGA/EJE
for backward compatibility, EG1/EG2/EJ1/EJ2 for new
code)
> Add option for Trigger Alias

- PWGHF/correlationHF/AliAnalysisTaskDHFeCorr.cxx
- PWGHF/correlationHF/AliAnalysisTaskDHFeCorr.h
- PWGHF/correlationHF/macros/AddTaskDHFeCorr.C
- PWGHF/correlationHF/macros/default_config_d_hfe.yaml
The following things were included:
- Save MC information at generated level for HFe and D mesons.
- Added possibility to turn on/off the processing of D, electrons and events
- Added more information for the Events
- Removed TPC N clusters in favor of TPC crossed rows for electrons
- Change event selection to use AliEventCuts
- Added variables for systematics of NHFe subtraction
- Optimised some of the default values to reduce size
> Include MC information and minor updates

- PWGJE/EMCALJetTasks/Tracks/AliAnalysisTaskEmcalSoftDropData.cxx
- PWGJE/EMCALJetTasks/Tracks/AliAnalysisTaskEmcalSoftDropData.h
Use fine pt-binning for data and do not truncate in pt-dimension.
Apply realistic binning and tructation offline. This is of
relevance in order to combine triggers at data level and unfold
the over the combined pt range.
> Use fine pt binning for data

- PWGCF/FLOW/GF/AliAnalysisTaskGFWFlow.cxx
Moved trigger/V0M check before event cuts so that event selection QA gets properly filled
> Moved trigger/V0M check before event cuts

- RUN3/AliAnalysisTaskAO2Dconverter.cxx
- RUN3/AliAnalysisTaskAO2Dconverter.h
To use AO2D format in current analysis tasks, the event data needs to be aggregated from separate arrays. Now there is no connection allowing to see which segment of the arrays belong to a given event. The PR adds 2 arrays of indices to the O2events tree for each entry. The first array contains the start indices of the event data in the trees of tracks, v0s, cascades, ..., while the second array contains the number of entries to be read. Adding these arrays only increase the total file size by 0.015%.
> AO2d links from event array to lower hierarchy arrays

- PWGDQ/dielectron/macrosLMEE/Config_acapon.C
- PWGDQ/dielectron/macrosLMEE/Config_acapon_Efficiency.C
- PWGDQ/dielectron/macrosLMEE/LMEECutLib_acapon.C
- Cut setting added which uses standard kCutSet1 track cuts, but implements hadron band rejection ePID scheme.
- Local PID correction map paths updated
> Add hadRej PID for withSDD data sets

- OADB/AliEventCuts.cxx
Since anyway in unaffected periods it does not hurt.
> Always use time range cut in 2018 Pb-Pb

- PWGHF/treeHF/macros/AddTaskHFTreeCreator.C
The TTreeCreator -> ITS3Improver -> TTreeCreator setup we use on trains only worked for beauty hadrons. Added an extra argument in AddTask, so we can use same setup also for the other particles.
> PWGHF: Container name fix for ITS2-ITS3 setup

- PWG/EMCAL/EMCALbase/AliEMCALRecoUtils.cxx
- PWG/EMCAL/EMCALbase/AliEMCALRecoUtils.h
- PWG/EMCAL/EMCALtasks/AliEmcalCorrectionCellBadChannel.cxx
- PWG/EMCAL/EMCALtasks/AliEmcalCorrectionCellEmulateCrosstalk.cxx
- PWG/EMCAL/EMCALtasks/AliEmcalCorrectionCellEnergy.cxx
- PWG/EMCAL/EMCALtasks/AliEmcalCorrectionCellEnergy.h
- PWG/EMCAL/config/AliEmcalCorrectionConfiguration.yaml
This PR adds the possibility to correct low gain cells for the shaper nonlinearity. The pol6 for this correction was obtained by Martin in the EMCal lab and was presented here: https://indico.cern.ch/event/885500/contributions/3732586/attachments/1980636/3298179/TB_20200203.pdf
In a later commit, also the nonlinearity function that has to be applied on cluster level will be made available.
> PWG/EMCAL: Implemented shaper nonlinearity correction

- PWGDQ/dielectron/core/AliAnalysisTask_JPsi_EMCal.cxx
Fixing reference for V0 correction (was accidentally changed in a previous commit).
>  fixing reference for V0 correction in EMCal analysis 

- PWGHF/vertexingHF/vHFML/AliAnalysisTaskSEDplus.cxx
- PWGHF/vertexingHF/vHFML/AliAnalysisTaskSEDs.cxx
This is to avoid the storage of injected background candidates in TTree in case of PbPb MC samples
> In case of MC Do not fill in TTree not flagged candidates

- PWGGA/GammaConv/AliAnalysisTaskOmegaToPiZeroGamma.cxx
- PWGGA/GammaConv/AliAnalysisTaskOmegaToPiZeroGamma.h
- PWGGA/GammaConv/macros/AddTask_OmegaToPiZeroGamma_pp.C
+Added some QA plots to check possible cut variables (in callable function)
+Added trainconfig for all reco methods for 13TeV with EDC instead of EMCal only
+Added histograms that were previously only filled for ESDs in ProcessTrueMesonCandidatesAOD
+Adapted recently changed AliAODConversionPhoton::SetIsCaloPhoton() call
> Added QA Plots and EDC Trainconfig for OmegaToPi0Gamma

- PWGLF/SPECTRA/CMakeLists.txt
- PWGLF/SPECTRA/PWGLFspectraLinkDef.h
- PWGLF/SPECTRA/PiKaPr/TPCTOFCascades/AliAnalysisPIDCascade.cxx
- PWGLF/SPECTRA/PiKaPr/TPCTOFCascades/AliAnalysisPIDCascade.h
- PWGLF/SPECTRA/PiKaPr/TPCTOFCascades/AliAnalysisPIDCascadeEvent.cxx
- PWGLF/SPECTRA/PiKaPr/TPCTOFCascades/AliAnalysisPIDCascadeEvent.h
- PWGLF/SPECTRA/PiKaPr/TPCTOFCascades/AliAnalysisPIDCascadeParticle.cxx
- PWGLF/SPECTRA/PiKaPr/TPCTOFCascades/AliAnalysisPIDCascadeParticle.h
- PWGLF/SPECTRA/PiKaPr/TPCTOFCascades/AliAnalysisPIDCascadeTrack.cxx
- PWGLF/SPECTRA/PiKaPr/TPCTOFCascades/AliAnalysisPIDCascadeTrack.h
- PWGLF/SPECTRA/PiKaPr/TPCTOFCascades/AliAnalysisPIDCascadeV0.cxx
- PWGLF/SPECTRA/PiKaPr/TPCTOFCascades/AliAnalysisPIDCascadeV0.h
- PWGLF/SPECTRA/PiKaPr/TPCTOFCascades/AliAnalysisTaskTPCTOFCascade.cxx
- PWGLF/SPECTRA/PiKaPr/TPCTOFCascades/AliAnalysisTaskTPCTOFCascade.h
Major changes to the Lund Trees used in the pp@13 TeV S0/RT analyses.
New classes are added (modifications from old classes) that contain only the relevant information needed for these analyses. More complete trees can be found at TPCTOFfits (albeit without cascades).
An alternative version of the AT will be created in the near future that contains all of the previous capabilities.
THIS IS AN UPDATED PULL REQUEST!
I had to close the previous one due to a bug.
This should hopefully work.
> Major overhaul of tree creation for S0/RT Analyses

- PWGHF/vertexingHF/AliAnalysisTaskSEXicTopKpi.cxx
- PWGHF/vertexingHF/AliAnalysisTaskSEXicTopKpi.h
Modifications:
1. TH3 transformed in THn objects, with n=4
2. Axis added in THnSparse at reco level
3. Axis added in THnSparse for Lc(<-Sc) at gen level
These new axes store the return value of
- AliAnalysisTaskSEXicTopKpi::CheckXicpKpiDecay for Xic
- AliVertexingUtils::CheckLcpKpiDecay                   for Lc
(4. cosThetaStar calculation fixed, using the fPdgFiducialYreco mass hypothesis)
> Possibility to separate direct decays from resonant ones in MC

- PWG/Tools/AliMCSpectraWeights.cxx
Compilation breaks on macOS without explicit cast to float
> Add cast to float

- PWGCF/FLOW/GF/AliAnalysisTaskGFWFlow.cxx
- PWGCF/FLOW/GF/AliAnalysisTaskGFWFlow.h
Adding a flag to bypass all the calculations (and so only the QA is done)
> AliAnalysisTaskGFWFlow bypassing calculations

- PWGCF/FLOW/GF/AliAnalysisTaskGFWFlow.cxx
Hardcoded trigger selection for now, because external setter somewhat misbehaves (I suspect it's type conflict)
> Hardcoded trigger selection in AliGFW task

- PWGJE/EMCALJetTasks/UserTasks/AliAnalysisTaskJetDynamicalGrooming.cxx
Apparently emplace_back isn't supported for std::bool until c++14
> Fix for compilation issue with emplace_back

- PWGJE/EMCALJetTasks/UserTasks/AliAnalysisTaskJetDynamicalGrooming.cxx
This should just affect the ordering of the subjets output - not
the actual stored information.
> Keep subjects from the same splitting together

- PWGHF/hfe/AliAnalysisTaskHFEBESpectraEMC.cxx
- PWGHF/hfe/AliAnalysisTaskHFEBESpectraEMC.h
- Changing the method of selecting b->e and c->e for MC DCA templates by going back to the first B hadron
- Extending the electron THnsparse to 60 GeV/c
> Changing the method of selecting b->e for MC DCA

- PWGGA/EMCALTasks/AliAnalysisTaskGammaHadron.cxx
- PWGGA/EMCALTasks/AliAnalysisTaskGammaHadron.h
Increased dphi bins from 50 to 54
Enables track pt axis, replacing xi axis
Adds latest MB mass, sigma values
Option to reweight by centrality
> Bins and axis adjustment, latest mass cuts

- PWGJE/EMCALJetTasks/Tracks/AliAnalysisTaskEmcalSoftDropData.cxx
- PWGJE/EMCALJetTasks/Tracks/AliAnalysisTaskEmcalSoftDropResponse.cxx
For untagged jets (zg < zcut) the values for Rg,
Thetag and Nsd are set to negative values ~0.
Dedicated bins in the histograms for the observables
handle untagged jets.
> Fix for untagged jets for Rg, Thetag and Nsd

- PWG/EMCAL/EMCALtasks/AliAnalysisTaskEmcalTriggerSelection.cxx
We have observed that the thresholds need to be lowered slightly for a better agreement between data and MC.
> PWG/EMCAL: optimized pPb5TeV Run1 trigger thresholds

- PWGJE/EMCALJetTasks/UserTasks/AliAnalysisTaskJetDynamicalGrooming.cxx
- PWGJE/EMCALJetTasks/UserTasks/AliAnalysisTaskJetDynamicalGrooming.h
The jagged indices workaround worked fine, but introduced additional
complexity and didn't actually provide any benefit over this approach
> Simplify storing subjet constituents

- PWGHF/jetsHF/AliAnalysisTaskBJetTC.cxx
- PWGHF/jetsHF/AliAnalysisTaskBJetTC.h
I changed the analysis code so the track counting tagger can the b-jet candidates using the IP significance instead of the IP. I added a flag to turn off/on this feature.
> Changing the Track Counting Tagger to tag on the IP significance

- PWG/DevNanoAOD/AliAnalysisNanoAODCuts.cxx
- PWGLF/RESONANCES/PostProcessing/Sigma1385/AliAnalysisTaskSigma1385PM.cxx
Previously, if we put the V0CPA cut, it returned always false.
> Allow Individual V0RadiusMin/Max cut and V0CPA cut

- PWGHF/vertexingHF/macros/AnalyzeScOutput.C
- explicit selection of prompt reconstructed Lc(<-Sc) or Sc
- fixed the DeltapT normalization in cross section calculation
- add the possibility to perform the Sc analysis (ie: as a function of Sc pT)
- correct branching ratio values of Lc decay channels inserted
> Updates on AnalyzeScOutput.C macro

- PWGGA/EMCALTasks/AliAnalysisTaskGammaHadron.cxx
- PWGGA/EMCALTasks/AliAnalysisTaskGammaHadron.h
Adds additional odd vs even axis to event pool for mixed trigger
Should avoid autocorrelating event by mixing odd with even, even with odd
> Add event hash to mixed triggers

- PWGDQ/dielectron/core/AliDielectronEventCuts.cxx
activate correlation cuts also in ESD related to pileup
> PWGDQ/LMEE: activate correlation cuts also in ESD

- JETAN/FASTJETAN/CMakeLists.txt
- PWGCF/Correlations/JCORRAN/Pro/CMakeLists.txt
- PWGDQ/dielectronJet/CMakeLists.txt
- PWGDQ/reducedTree/CMakeLists.txt
- PWGHF/jetsHF/CMakeLists.txt
- PWGJE/EMCALJetTasks/CMakeLists.txt
- PWGJE/FlavourJetTasks/CMakeLists.txt
- cmake/FindFASTJET.cmake
- link properly against fastjet instead of using ROOT auto-loading
- ensures correct loading of dependencies by linker, not depending on LD_LIBRARY_PATH
NB: still testing ..
> Link against fastjet

- PWGCF/FEMTOSCOPY/FemtoDream/AliFemtoDreamCollConfig.cxx
- PWGCF/FEMTOSCOPY/FemtoDream/AliFemtoDreamCollConfig.h
- PWGCF/FEMTOSCOPY/FemtoDream/AliFemtoDreamCorrHists.cxx
- PWGCF/FEMTOSCOPY/FemtoDream/AliFemtoDreamCorrHists.h
- PWGCF/FEMTOSCOPY/FemtoDream/AliFemtoDreamHigherPairMath.cxx
- PWGCF/FEMTOSCOPY/FemtoDream/AliFemtoDreamZVtxMultContainer.cxx
- PWGCF/FEMTOSCOPY/macros/AddTaskFemtoLoton.C
Adds the distribution of multiplicity and kstar for several mT bins. Can be activated via the event collection config with SetDomTMultBinning. The bins can be defined in a std::vector<float> via SetmTBins.
> Mt mult binning

- PWGGA/GammaConv/AliConversionAodSkimTask.cxx
- PWGGA/GammaConv/AliConversionAodSkimTask.h
- AliConversionAodSkimTask is now properly derived from the original AliAodSkimTask, including the user exec. From now on, tasks can override the SelectEvent() to influence the selection of events selected for the skim and all copying is handeled by AliAodSkimTask
- intorduced a check that ensures that the V0Reader is not running in the analysis manager during skimming by accident. When relabelling by default with the V0Reader while skimming, the trains running on the skimmed dataset will fail to read the V0 candidates when attempting to relabel again.
> PWGGA/GammaConv: properly derived AliConversionAodSkimTask 

- PWG/DevNanoAOD/AliAnalysisTaskNanoAODFilter.cxx
The event will be selected by using the built-in AliEventCuts if we turn on "fUseAliEventCuts" flag as true.
> Activate the built-in AliEventcuts event selection

- PWGMM/UE/UeKNO/AddTaskMcKno.C
Fix for memory issue has been included for the run of multiple wagons in a single lego train.
> Fix for memory issue for NchTS analysis

- PWGGA/GammaConv/AliAnalysisTaskOmegaToPiZeroGamma.cxx
- PWGGA/GammaConv/AliAnalysisTaskOmegaToPiZeroGamma.h
- PWGGA/GammaConv/macros/AddTask_OmegaToPiZeroGamma_pp.C
+Added new background scheme (swapping method by Joshua)
+Added new train configs for 13 TeV
+Reordered and redone the 13 TeV train configs
+Fixed mass calculation for a rare case for neutral pions
+Added and reordered some deletes to be in the proper position
+Added lightweight option (still needs work, currently only used in the new background scheme)
> New background scheme (swapping method)

- PWGHF/treeHF/AliAnalysisTaskSEHFTreeCreator.cxx
- PWGHF/vertexingHF/AliAnalysisTaskSED0Mass.cxx
- PWGHF/vertexingHF/AliAnalysisTaskSEDStarSpectra.cxx
- PWGHF/vertexingHF/AliAnalysisTaskSEDvsMultiplicity.cxx
- PWGHF/vertexingHF/AliAnalysisTaskSELambdac.cxx
- PWGHF/vertexingHF/AliAnalysisTaskSELambdacTMVA.cxx
- PWGHF/vertexingHF/AliAnalysisTaskSELc2V0bachelor.cxx
- PWGHF/vertexingHF/AliAnalysisTaskSELc2V0bachelor.h
- PWGHF/vertexingHF/AliAnalysisTaskSELc2V0bachelorTMVA.cxx
- PWGHF/vertexingHF/AliAnalysisTaskSELc2V0bachelorTMVA.h
- PWGHF/vertexingHF/AliAnalysisTaskSELc2V0bachelorTMVAApp.cxx
- PWGHF/vertexingHF/AliAnalysisTaskSELc2V0bachelorTMVAApp.h
- PWGHF/vertexingHF/AliRDHFCutsLctoV0.cxx
- PWGHF/vertexingHF/AliRDHFCutsLctoV0.h
- PWGHF/vertexingHF/AliRDHFCutsLctopKpi.cxx
- PWGHF/vertexingHF/macros/AddTaskDStarSpectra.C
- PWGHF/vertexingHF/macros/AddTaskLambdac.C
- PWGHF/vertexingHF/vHFML/AliAnalysisTaskSEDplus.cxx
Small fixes to several HF tasks after a direct comparison of the output between the dedicated task, the DvsMultiplicity task, and HFTTreeCreator task. 
Should have no, or a negligible, impact on the ongoing/published analyses. Only when certain flags are enabled in cutobject (fRemoveDaughtersFromPrimary, fUseCutGeoNcrNcl) for Lc tasks, but these are disabled by default.
> PWGHF: Several small fixes + improvements

- PWGDQ/dielectron/core/AliAnalysisTaskEtaReconstruction.cxx
- PWGDQ/dielectron/core/AliAnalysisTaskEtaReconstruction.h
- PWGDQ/dielectron/macrosLMEE/AddTask_feisenhut_EtaReconstruction.C
- PWGDQ/dielectron/macrosLMEE/Config_feisenhut_EtaReconstruction.C
- PWGDQ/dielectron/macrosLMEE/LMEECutLib_feisenhut.C
I added a new cutsetting that can be used before the PreFilter in order to select more particles that can be paired in the PreFilter and reject false identified particles afterwards with an other cutsetting.
>   PWGDQ EtaReconstruction Implemented looser primary track cuts before PreFilter

- PWGDQ/reducedTree/AliReducedAnalysisJpsi2ee.h
- PWGDQ/reducedTree/AliReducedCompositeCut.cxx
- PWGDQ/reducedTree/AliReducedCompositeCut.h
- PWGDQ/reducedTree/AliReducedTrackInfo.cxx
- PWGDQ/reducedTree/AliReducedTrackInfo.h
- PWGDQ/reducedTree/AliReducedVarManager.cxx
- PWGDQ/reducedTree/AliReducedVarManager.h
- AliReducedCompositeCut: new method using values (like other cut classes)
- AliReducedAnalysisJpsi2ee: methods to return cuts (e.g. useful when setting up mixing handler)
- AliReducedTrackInfo: new data member to hold EMCal cluster energy and corresponding setters/getters
- AliReducedVarManager: assigning EMCal cluster energy to track after cluster-track matching, new variable to store EMCal cluster energy per leg for pair
> PWGDQ/reducedTree: updates for EMCal triggered analysis

- RUN3/AliAnalysisTaskAO2Dconverter.cxx
Please do not merge this yet because it is still being tested. 
@pzhristov @jgrosseo. This PR should include the event id calculation for MC where the BC information are not stored and reject the events with only SPD vertex, which as we discuss should not be converted given that they will not be present in Run3. 
I will do a few checks and then remove the WIP. Please let me know if you have any suggestions. 
Thanks Cheers GM
> Add fix for eventid in the Run2->Run3 converter for MC and add rejection of spd vertices

- PWGHF/correlationHF/AliAnalysisTaskDHFeCorr.cxx
- PWGHF/correlationHF/AliAnalysisTaskDHFeCorr.h
In some cases (~3% of data), the old scheme to generate the unique event numbers was not working, because there were too many events in the AOD. To fix that, I have added the number of the directory as a separate variable, and then the unique ID can be generated by combining the RunNumber + Directory + Event Number.
> Add dir to make unique IDs

- PWGHF/vertexingHF/AliAnalysisTaskSEDvsRT.cxx
- PWGHF/vertexingHF/macros/AddTaskDvsRT.C
updates following D2H of 27/03/2020:
- add customisation of pTLeadMin to AddTask
- finer binning of RT in analysis + QA histos
- default track filter for RT -> TPC-only
- fixes to event counter
> Updates to DvsRT analysis task

- PWGHF/jetsHF/AliAnalysisTaskDJetCorrelations.cxx
- PWGHF/jetsHF/AliAnalysisTaskDmesonsFilterCJ.cxx
- PWGHF/jetsHF/AliAnalysisTaskDmesonsFilterCJ.h
Hi all,
"fArrayDStartoD0pi" was renamed recently in DFilter task to check how it affected. And this affected the Container input provided to AliEmcalJetTask. So fixing this mistake I did few days back. Another renaming in Correlations task is also reverted just to be safe.
Best, Auro
> fix-Reverting the "fArrayDStartoD0pi"-renaming in DFilter task

- PWGCF/FEMTOSCOPY/macros/AddTaskGeorgiosNTuple.C
Opening the Cuts to include the background of the Lambdas Xis. Also correct renaming of some variables to avoid overwriting.
> Including the background for the analysis

- PWGPP/AliAnalysisTaskFilteredTree.cxx
- PWGPP/AliESDtools.cxx
- PWGPP/AliESDtools.h
- PWGPP/macros/AddTaskFilteredTree.C
Enable to replay event selection
Updating event information for skimmed data.
More to be added in following commits related to the sphericity estimators and multiplicity QA https://alice.its.cern.ch/jira/browse/PWGPP-550
See more details in https://alice.its.cern.ch/jira/browse/PWGPP-584
* PWGPP-584 - pileup information as calculated in ESD before cleaning
* commit acd652163ac9d19b570544f357f885d2781a9a02
* AliTriggerAnalysis::IsSPDOnVsOfPileup - Variables added
*commitd 4ab6d67be6e8f9b61bf4bccb0a6535bcec7f159
* AliTriggerAnalysis::T0Decision AliTriggerAnalysis::T0Trigger  AliTriggerAnalysis::V0Trigger​_
* commit 73e9e76e158b784b81dcae1fde25688975c0e055
* ZDC information to store raw time and Energy
* commit c1a161a50ef2a06c7611a1e265442963d02887e2
* Adding subset of Boolen variables from …
> PWGPP-584, ATO-465 - Update of event selection information for skimmed data

- PWGPP/AliAnalysisTaskFilteredTree.cxx
- PWGPP/AliESDtools.cxx
- PWGPP/AliESDtools.h
```
"hist2DTrackletsCounter.=" <<fHist2DTrackletsCounter<<    // 2D tracklet Phi x tgl norm histogram
"hist2DTrackCounter.="   << fHist2DTrackCounter<<        // 2D track Phi x tgl histogram
"hist2DTrackSumPt.="     << fHist2DTrackSumPt<<          // 2D track Phi x tgl sum pt histogram
````
> PWGPP-550, ATO-465 - adding barrel multiplicty and sum pt counters

- PWGPP/AliESDtools.cxx
phi and tgl were switched in commits before
> PWGPP-550, ATO-465 - phi,tgl switch - BUG FIX

- PWGGA/GammaConv/AliAnalysisTaskNeutralMesonToPiPlPiMiNeutralMeson.cxx
- PWGGA/GammaConv/AliAnalysisTaskOmegaToPiZeroGamma.cxx
- PWGGA/GammaConv/AliAnalysisTaskOmegaToPiZeroGamma.h
- The QA plots should now all be filled within two extra functions, to make the code more readable and less repetitive. Also since all the histograms are known inside the whole task, the functions no longer have the histograms as arguments.
- Removed new and delete for pi0candidates in ProcessTrueMesonCandidates and ProcessTrueMesonCandidatesAOD.
- The changes in AliAnalysisTaskNeutralMesonToPiPlPiMiNeutralMeson.cxx are purely blankets and happened by accident. So no real changes there.
> QA Plots are now filled within extra function

- PWGLF/SPECTRA/MultEvShape/AliMESpidTask.cxx
- Modified LP definition for Missed: Reconstructed LP -> Generated LP 
- extended the pT range up to 5 GeV
> Modified LP definition for Missed

- PWGJE/EMCALJetTasks/Tracks/AliAnalysisTaskEmcalSoftDropResponse.cxx
Add THnSparse in order to be able to get the truth level
distribution with detector level cuts. Necessary to
distinguish between effects of unfolding and kinematic
efficiency in the MC closure test
> Add THnSparse also for Pseudodata

- PWGPP/AliAnalysisTaskFilteredTree.cxx
- PWGPP/AliESDtools.cxx
- PWGPP/AliESDtools.h
```
fHist2DMCCounter    = new TH2S("fHist2DMCCounter"," 2D MC particle Phi x tgl histogram", 18,0,TMath::TwoPi(),32,-4,4);
fHist2DMCSumPt      = new TH2F("fHist2DMCSumPt","2D MC particle Phi x tgl sum pt histogram", 36,0,TMath::TwoPi(),32,-4,4);
```
```
Int_t theGen = mcPart->GetGeneratorIndex();
AliGenEventHeader *gh = (AliGenEventHeader *) lgen->At(theGen);
Double_t timeNs = gh->InteractionTime() * 1e9;
if (TMath::Abs(timeNs) > kPileUpCut) return kTRUE;
```
> PWGPP-584,ATO-465: MC histogram counters/sumPt and IsPileup

- PWGPP/AliESDtools.cxx
MC true information summary dumped to the event trees as a matrix:
* columns (X,Y,Z, time, mult)
* row - per generator in cocktail
See details and example queries in JIRA:  https://alice.its.cern.ch/jira/browse/PWGPP-584?focusedCommentId=245972&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-245972
> PWGPP-584,ATO-465: adding MC true event information vertex+event times

- PWGPP/AliAnalysisTaskFilteredTree.cxx
- PWGPP/macros/AddTaskFilteredTree.C
* replacing kdEdxCut=11.3 (was 11.2)
* adding lower band around the deuteron
* changing DCA z cut to 10 cm (ws 15 cm)
1de4f5a
* Gamma candidates needed for the dEdx calibration.
* At high flux (central event trigger) too many combinatortial Gamma fakes
* Additional factor which we used for the gamma (in respect to K0, Lambda)
gamma candidates > 70 % of V0s
```
const Double_t upsampleGammaPt=4;  // was 10
const Double_t upsampleGamma1Pt=2; // was 10
```
*  task->SetLowPtTrackDownscaligF(2.e4); // was 5.e3
*  task->SetLowPtV0DownscaligF(2.e3);    // was 5.e2
> ATO-465, ALIROOT-8430 - decreasing size of simmed data reducing fakes + doensampling

- PWGJE/EMCALJetTasks/AliFJWrapper.h
- PWGJE/EMCALJetTasks/PWGJEEMCALJetTasksLinkDef.h
It would be good to check these changes on root5, they should keep root 5 unaffected but allow the improvements in root 6.
> fix wrapper to be used in root 6 aclic and interpreted mode

- PWG/EMCAL/EMCALbase/AliEMCALRecoUtils.cxx
- PWG/EMCAL/EMCALbase/AliEMCALRecoUtils.h
- PWG/EMCAL/EMCALtasks/AliEmcalCorrectionClusterNonLinearity.cxx
- PWG/EMCAL/EMCALtasks/AliEmcalCorrectionClusterNonLinearityMCAfterburner.cxx
This PR introduces the final testbeam nonlinearity to the correction framework.
The following settings need to be selected in order to correctly activate it:
Settings for Data:
CellEnergy:
enableShaperCorrection: true 
ClusterNonLinearity:
enabled: true
nonLinFunct: kTestBeamShaper
Settings for MC:
ClusterNonLinearity:
enabled: true
nonLinFunct: kTestBeamFinalMC
ClusterNonLinearityMCAfterburner:
enabled: true
afterburnerVersion: kPCM_EMCal
setMCPeriod: "kTestBeamFinalMCRun2" # for Run1 choose kTestBeamFinalMCRun1
> PWG/EMCAL: Added final shaper + testbeam correction to correction framework

- PWGGA/GammaConv/AliAnalysisTaskOmegaToPiZeroGamma.cxx
- PWGGA/GammaConv/AliAnalysisTaskOmegaToPiZeroGamma.h
- PWGGA/GammaConv/macros/AddTask_OmegaToPiZeroGamma_pp.C
- Split rotation background method up into Calo and PCM part
so it should work with both properly now
- Added photon selection to the background calculation
Therefore the sets which contained the preselected gamma indices
are now a variable of the AliAnalysisTask.
- Added more trainconfig to now be able to run EMCal or DCal alone
- Added one more trainconfig to be able to run normal and strong photon
selection for EDC-EDC at once
> Modified Rotation Background Method for OmegaToPiZeroGamma

- PWGPP/macros/pcalimonitorCSV.sh
JIRA printing of the production summary 
* adding where  and sorting option
```
source $AliPhysics_SRC/PWGPP/macros/pcalimonitorCSV.sh
dumpCSV https://alimonitor.cern.ch/prod/jobs.jsp?t=20831 table.csv
printSummary JobID,RunNo,input_events,wall_time,outputsize,outputsize/input_events table "where input_events>40000 ORDER BY input_events DESC"
```
| line_numbers |         JobID |   RunNo | input_events |  wall_time |      outputsize | outputsize/input_events |
| ------------ | ------------- | ------- | ------------ | ---------- | --------------- | ----------------------- |
|            1 | 1.839.914.830 | 296.749 |   15.653.367 | 5.485,344… | 306.018.845.625 |             19.549,714… |
|            2 | 1.839.994.665 | 296.750 |   14.899.729 | 2.658,789… | 256.676.483.677 | …
> ATO-465 - adding SQL query options and example usage using csvkit

- PWGHF/vertexingHF/AliCFTaskVertexingHF.cxx
- PWGHF/vertexingHF/AliCFTaskVertexingHF.h
- PWGHF/vertexingHF/macros/AddTaskCFVertexingHF.C
Code is backward compatible to preserve standard usage.
Two new arguments are added at the end of the AddTask args list to enable new functionalities
> Update to HF CF to allow online trkl mult equalization & event mult reweigting for pp@13 TeV samples

- PWGJE/EMCALJetTasks/Tracks/AliAnalysisTaskEmcalJetEnergyScale.cxx
- PWGJE/EMCALJetTasks/Tracks/AliAnalysisTaskEmcalJetEnergySpectrum.cxx
- PWGJE/EMCALJetTasks/Tracks/AliAnalysisTaskEmcalSoftDropData.cxx
- PWGJE/EMCALJetTasks/Tracks/AliAnalysisTaskEmcalSoftDropResponse.cxx
- Jet area (vs. pt, NEF, Nconst)
- (Max.) constituent Eta-phi
- (Max.) constituent distance to the main jet axis
In case of response tasks:
- Histograms for both part. and det. level jets
- Histograms for Matching deltaR between part.
level jet and det. level jet
> Adding QA histograms to SD and Spectrum tasks

- PWG/EMCAL/EMCALbase/AliEMCALRecoUtils.cxx
- PWG/EMCAL/EMCALbase/AliEMCALRecoUtils.h
- PWG/EMCAL/EMCALtasks/AliEmcalCorrectionCellSingleChannelCalibration.cxx
- PWG/EMCAL/EMCALtasks/AliEmcalCorrectionCellSingleChannelCalibration.h
- PWG/EMCAL/EMCALtasks/CMakeLists.txt
- PWG/EMCAL/EMCALtasks/PWGEMCALtasksLinkDef.h
- PWG/EMCAL/config/AliEmcalCorrectionConfiguration.yaml
A new task was written for the single channel calibration and it has been added to the EMCal Correction Framework. By default, the task is disabled and currently only calibrates runs from LHC15o. Merge is needed so that the version is available on the grid for testing.
> EMCal Single Channel Calibration

- PWGHF/jetsHF/AliAnalysisTaskDmesonsFilterCJ.h
as they were mistakenly changed to transient types (//!) in a previous PR
> bug fix: bringing persistent members (//) back 

- PWGCF/FEMTOSCOPY/FemtoDream/AliAnalysisTaskNanoLD.cxx
- PWGCF/FEMTOSCOPY/macros/AddTaskFemtoNanoLD.C
o Fix binning of mass squared hist for deuterons
o Change cuts for (anti-)deuterons
o FB 128/256, PID w/ w/o TOF, open DCAs
> FemtoNanoLD: deuterons: fix mass sq, change cuts

- RUN3/AliAnalysisTaskAO2Dconverter.cxx
- RUN3/AliAnalysisTaskAO2Dconverter.h
- One label with the usual nomenclature:
positive - no mismatch, negative - mismatch;
- In addition a bit mask which encodes in the folllowing way which detector
has the mismatch:
a) ITS: 7 bits (one per layer)
b) TPC: 3 bits to count number of mismatch clusters encoding
the ranges: 0, 1, 2-3, 4-7, 8-15, 16-31, 31-63, >64
c) TRD: 1 bit (possibility to use 6 bits in the future)
d) TOF: 1 bit
> Updated Run3 labels:

- PWGJE/EMCALJetTasks/UserTasks/AliAnalysisTaskJetDynamicalGrooming.cxx
- PWGJE/EMCALJetTasks/UserTasks/AliAnalysisTaskJetDynamicalGrooming.h
The JetConstituent classes do not store subtracted constituents. So
instead we have to access them via `Track(int)`.
> Fix track extraction

- PWGGA/GammaConv/AliAnalysisTaskGammaIsoTree.cxx
- PWGGA/GammaConv/AliAnalysisTaskGammaIsoTree.h
- PWGGA/GammaConv/macros/AddTask_GammaIsoTree.C
- PWGGA/GammaConvBase/AliCaloPhotonCuts.cxx
- PWGGA/GammaConvBase/AliCaloPhotonCuts.h
- PWGGA/GammaConvBase/AliConvEventCuts.cxx
- PWGGA/GammaConvBase/AliConvEventCuts.h
- added cell experimental cell based isolation to GammaIsoTree
- added functionality to set cluster cuts separetly for signal clusters and background clusters (those use for isolation and taggin
- added functionality to calculate isolation for multiple radii on the fly
- added weighte for LHC17g5a1 GJ MC pp 8 TeV
> PWGGA/GammaConv: GammaIsoTree added cell based iso & GJ weights

- PWGLF/NUCLEX/Utils/O2vertexer/DCAFitterN.h
By @galocco see AliceO2Group/AliceO2#3583
> Fix copy/paste typo in starting point definition

- PWGJE/EMCALJetTasks/Tracks/AliAnalysisTaskEmcalJetEnergyScale.cxx
- PWGJE/EMCALJetTasks/Tracks/AliAnalysisTaskEmcalJetEnergyScale.h
- PWGJE/EMCALJetTasks/Tracks/AliAnalysisTaskEmcalJetEnergySpectrum.cxx
- PWGJE/EMCALJetTasks/Tracks/AliAnalysisTaskEmcalJetEnergySpectrum.h
- PWGJE/EMCALJetTasks/Tracks/AliAnalysisTaskEmcalSoftDropResponse.cxx
- PWGJE/EMCALJetTasks/Tracks/AliAnalysisTaskEmcalSoftDropResponse.h
- Cross check whether std::max_element gives the same
result as trivial iteration over the accepted jets
by hand (debug mode - energy scale task only)
- Add switch performing the outlier cut either on
part. level jets or det. level jets (all tasks running
on MC), default: part. level jets
> Additional options for outlier cut

- PWGHF/vertexingHF/AliAnalysisTaskSEXicTopKpi.cxx
- PWGHF/vertexingHF/AliAnalysisTaskSEXicTopKpi.h
- add vertex histograms and fill if running c-deuteron analysis
- add option, if running c-deuteron analysis, to only use tracks that come from signal (saves a lot of CPU time), and to remove injected particles
> add vertex histograms for c deuteron

- PWGGA/GammaConv/AliAnalysisTaskGammaIsoTree.cxx
- PWGGA/GammaConv/AliAnalysisTaskGammaIsoTree.h
- PWGGA/GammaConv/macros/AddTask_GammaIsoTree.C
- switched from std::vector storage to TClonesArray in order to achieve proper splitting and compression in stored tree and proper viewing with tbrowser
- switched structs that store additional infos for particles to a little helper class that inherit from TObject and are easier to maintain and upgrade
- fixed a bug that caused the buffer of theTTree to not be properly flushed to disk and overflow when running over too many events
> PWGGA/GammaConv: IsoTree switched to TClonesArrays and fixed flush

- PWGHF/vertexingHF/AliHFPtSpectrum.cxx
Adding the relative statistical uncertainty of the prompt efficiency to the total systematic TGraph (gSigmaCorr). For most D meson analyses minor contribution (~1%), but can go up to ~5% for Lc in a D2H MC or in special HM MCs.
Now pp is also consistent with PbPb, where it is done here: https://github.com/alisw/AliPhysics/blob/66cc83e/PWGHF/vertexingHF/macros/ComputeDmesonYield.C#L996-L1007
> PWGHF: Add unc. efficiency to total systematic

- PWGDQ/dielectron/core/AliAnalysisTaskEtaReconstruction.cxx
- PWGDQ/dielectron/core/AliAnalysisTaskEtaReconstruction.h
- PWGDQ/dielectron/macrosLMEE/AddTask_feisenhut_EtaReconstruction.C
- PWGDQ/dielectron/macrosLMEE/Config_feisenhut_EtaReconstruction.C
In the new commit an additional method is implemented in order to measure and reconstruct two photo conversions from an decayed eta meson.
>  PWGDQ EtaReconstruction Implemented methode to reconstruct etas from two gamma conversions

- PWGGA/GammaConv/AliAnalysisTaskOmegaToPiZeroGamma.cxx
- PWGGA/GammaConv/AliAnalysisTaskOmegaToPiZeroGamma.h
- Added AODMCTrackArray as a member variable to the OmegaToPiZeroGamma task
- Changed MC True binning to match the normal same event binning
- AP like Plots now only get filled once per decay as they should
> OmegaToPiZeroGamma: AODMCTrackArray member variable

- PWGPP/CalibMacros/AliOCDBtoolkit.sh
For details see:
https://alice.its.cern.ch/jira/browse/PWGPP-592?focusedCommentId=248872&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-248872
```
recoParamDiff(){
#Singularity> alien_find    /alice/sim/2020/LHC120c1/OCDB/297479/ OCDBsim.root
source $AliPhysics_SRC/PWGPP/CalibMacros/AliOCDBtoolkit.sh
dumpObject alien:///alice/sim/2020/LHC120c1/OCDB/297479/iontail1.0crosstalk0.0/OCDBsim.root "TPC*Calib*RecoParam" "XML" iontail1.0crosstalk0.0.xml
dumpObject alien:///alice/sim/2020/LHC120c1/OCDB/297479/iontail0.8crosstalk0.2/OCDBsim.root "TPC*Calib*RecoParam" "XML" iontail0.8crosstalk0.2.xml
diff --suppress-common-lines -y iontail1.0crosstalk0.0.xml  iontail0.8crosstalk0.2.xml
}
```
```
<XmlKey name="AliCDBEntry" cycle="4" created="2020-05-31 11 |   <XmlKey …
```
> PWGPP-592- OCDB dump and diff working also with the OCDB snapshot

- PWGJE/EMCALJetTasks/Tracks/AliAnalysisTaskEmcalJetSubstructureTree.cxx
- PWGJE/EMCALJetTasks/Tracks/AliAnalysisTaskEmcalJetSubstructureTree.h
- PWGJE/EMCALJetTasks/Tracks/AliAnalysisTaskEmcalSoftDropData.cxx
- PWGJE/EMCALJetTasks/Tracks/AliAnalysisTaskEmcalSoftDropResponse.cxx
This has only consequences for beta not equal
to 0 (never used up to now)
> Set R0 to the jet radius

- PWGPP/AliAnalysisTaskFilteredTree.cxx
* increase statistics for the low pt protons for dEdx calibration
* store assumed mass and sqrt(s) used for Tsalis down-sampling
> ATO-465 - use proton mass assumption for V0 and track pt down-sampling

- PWGJE/EMCALJetTasks/Tracks/AliAnalysisTaskEmcalPatchesRef.cxx
- PWGJE/EMCALJetTasks/Tracks/AliAnalysisTaskEmcalPatchesRef.h
Internally using a data grid with the fake FastOR
data filled for all cells with a cell time cut.
Number of contributing FastORs calculated from
looping over the data grid within the patch ranges.
> Add option to cut on the number of non-0 FastORs

- RUN3/AliAnalysisTaskAO2Dconverter.cxx
- RUN3/AliAnalysisTaskAO2Dconverter.h
* AD (FDD) table with ADA and ADC timing
* Bypass of vertex cuts for muon UPC triggers with at least one muon track
* Selected trigger classes with index>50 added in bits 50-58 of fTriggerMask
> Added AD timing and muon UPC triggers

- PWGGA/GammaConv/AliAnalysisTaskClusterQA.cxx
- PWGGA/GammaConv/AliAnalysisTaskGammaIsoTree.cxx
- PWGGA/GammaConv/AliAnalysisTaskGammaIsoTree.h
- PWGGA/GammaConv/macros/AddTask_GammaIsoTree.C
- for charged isolation, tracks originating from conversions are now properly detected. I noticed the same problem in the ClusterQA task and fixed it
- implemented a mode that allows to use the default track matching
- implemented track matching for secondaries
> PWGGA/GammaConv: IsoTree track matching additions and fixes

- PWGDQ/dielectron/LMEE/AliAnalysisTaskeeCor.cxx
- PWGDQ/dielectron/LMEE/AliAnalysisTaskeeCor.h
- PWGDQ/dielectron/macrosLMEE/AddTask_hdegenhardt_eeCorMC.C
Before:
AliGenEventHeader* gh=(AliGenEventHeader*)l->At(0); //works fine for 2017&2018
Now:
AliGenEventHeader* gh=(AliGenEventHeader*)l->At(fPyHeader); //2016: At(1), 2017&2018: At(0)
> Fixing pythia header info for 2016 MC data analysis
