alisw/AliPhysics

PWGMM/CMakeLists.txt, PWGMM/Mult/AliAnalysisPseudoRapidityDensity.cxx, PWGMM/Mult/AliAnalysisPseudoRapidityDensity.h, PWGMM/Mult/CMakeLists.txt, PWGMM/Mult/PWGMMMultLinkDef.h
=> Add task AliAnalysisPseudoRapidityDensity

PWGHF/hfe/AliAnalysisHFETPCTOFBeauty.cxx, PWGHF/hfe/AliAnalysisHFETPCTOFBeauty.h, PWGHF/hfe/macros/AddTaskHFETPCTOFBeauty.C
=> Beauty electrons low pt central Pb-Pb - updatind DCA calculation

PWGHF/treeHF/AliHFTreeHandlerDstartoKpipi.cxx, PWGHF/treeHF/AliHFTreeHandlerDstartoKpipi.h
Soft pion pT is already stored in general pT_prong0 branch
=> PWGHF: Delete double occurrence soft pion pT in TTree

PWGPP/EMCAL/AliAnalysisTaskEMCALTimeCalib.cxx, PWGPP/EMCAL/AliAnalysisTaskEMCALTimeCalib.h
Cleaned now no warning is left, all ptrs are set properly to zero.
Memory leak should be fixed as well.
=> cleanup and mem leak fixes

PWG/EMCAL/EMCALtasks/AliAodSkimTask.cxx
=> enable rem track filter

PWGGA/EMCALTasks/macros/AddTaskEMCALPhotonIsolation.C, PWGGA/EMCALTasks/macros/config_PhotonIsolation.C
To achieve root6 support the option for individual config files is
removed for root5 and root6.
=> Fixing root6 support for PhotonIsolation task.

PWGHF/jetsHF/AliAnalysisTaskDJetCorrelationsQA.cxx, PWGHF/jetsHF/AliAnalysisTaskDJetCorrelationsQA.h, PWGHF/jetsHF/CMakeLists.txt, PWGHF/jetsHF/PWGHFjetsHFLinkDef.h, PWGHF/jetsHF/macros/AddTaskDJetCorrelationsQA.C
Added QA files for HF D-jets analysis (MC and data runs), both AliAnalysis and AddTask
=> Added QA task for D-jets

PWGCF/FEMTOSCOPY/FemtoDream/AliFemtoDreamEventCuts.cxx, PWGCF/FEMTOSCOPY/FemtoDream/AliFemtoDreamEventCuts.h, PWGCF/FEMTOSCOPY/FemtoDream/AliFemtoDreamEventHist.cxx, PWGCF/FEMTOSCOPY/macros/AddTaskFemtoDreamSysVar.C, PWGGA/Hyperon/AliSigma0PhotonMotherCuts.cxx, PWGGA/Hyperon/AliSigma0PhotonMotherCuts.h
o Track splitting/merging at high multiplicities
o Do we see Lambda or photon clones?
=> Several cross-checks for Femto

PWGCF/FEMTOSCOPY/AliFemtoUser/AliFemtoCutMonitorEventSphericity.cxx, PWGCF/FEMTOSCOPY/AliFemtoUser/AliFemtoCutMonitorEventSphericity.h, PWGCF/FEMTOSCOPY/AliFemtoUser/CMakeLists.txt, PWGCF/FEMTOSCOPY/AliFemtoUser/PWGCFfemtoscopyUserLinkDef.h
=> Sphericity monitor class (L.Malinina) 23-Jan-2019

PWGHF/jetsHF/AliAnalysisTaskBJetTC.cxx, PWGHF/jetsHF/AliAnalysisTaskBJetTC.h, PWGHF/jetsHF/macros/AddTaskBJetTC.C
I created a resolution function for each jet flavor, to better describe the data JP distribution.
=> Changing the definition of the resolution function in MC

OADB/AliEventCuts.cxx
Ciao @ddobrigk, this are the changes you were asking for!
=> Add Ionut's cut for 2011 periods

PWGHF/jetsHF/AliAnalysisTaskHFJetIPQA.cxx, PWGHF/jetsHF/AliAnalysisTaskHFJetIPQA.h
- Generation of setup canvas in UserCreateOutputObjects() via PrintSettings() not in Terminate()
=> AliAnalysisTaskIPQA: add function PrintSettings

PWGJE/EMCALJetTasks/CMakeLists.txt, PWGJE/EMCALJetTasks/PWGJEEMCALJetTasksLinkDef.h, PWGJE/EMCALJetTasks/Tracks/AliAnalysisTaskEmcalSoftDropResponse.cxx, PWGJE/EMCALJetTasks/Tracks/AliAnalysisTaskEmcalSoftDropResponse.h, PWGJE/EMCALJetTasks/macros/AddTaskEmcalSoftdropResponse.C
The task relies on functionality from RooUnfold. It will be
built only in case RooUnfold is available.
=> Adding task filling softdrop response

PWGGA/GammaConv/AliAnalysisTaskConvJet.cxx, PWGGA/GammaConv/AliAnalysisTaskConvJet.h
Added public constructor without arguments to hopefully make it able to work on the grid
=> PWGGA/GammaConv Added public constructor without arguments

PWGLF/SPECTRA/CMakeLists.txt, PWGLF/SPECTRA/PWGLFspectraLinkDef.h, PWGLF/SPECTRA/Spherocity/AliSpherocityEstimator.cxx, PWGLF/SPECTRA/Spherocity/AliSpherocityEstimator.h
Adding spherocity estimator class used for 13 TeV pp studies
=> Adding spherocity estimator class

PWGPP/TPC/macros/PIDCalib/MakeTPCPIDResponseOADB.C
The update for 17p.pass1 is trying to improve the electron splines at
high momenta, this may influence all analyses. Analysers using the splines of this period before are asked to check the influence on their analysis.
=> Add TPC splines and maps for 16l.2, 17k.1, 18b.1, 18d.1, update 17p.1

PWGGA/GammaConv/AliAnalysisTaskNeutralMesonToPiPlPiMiNeutralMeson.cxx, PWGGA/GammaConv/AliAnalysisTaskNeutralMesonToPiPlPiMiNeutralMeson.h
- added correct handling of true pure- and mixed calo information
- added relabeling of true AOD conversion photons
=> PWGGA/GammaConv: further fixes for heavy meson task on AODs

PWGCF/FEMTOSCOPY/macros/AddTaskSigma0Femto.C, PWGGA/Hyperon/AliSigma0PhotonMotherCuts.cxx, PWGGA/Hyperon/AliSigma0PhotonMotherCuts.h
o Fantastic CINT needs NULL instead of nullptr
o Additional debug histos for the track clones in ESDs
=> Small improvements for Sigma0 analysis

PWGHF/treeHF/AliAnalysisTaskSEHFTreeCreator.h
Fixing small bug introduced in PR 8351
=> PWGHF: MVA. Fix setter for option SingleTrackVars

PWGHF/vertexingHF/macros/AddTaskLc2V0bachelor_TMVAApp.C
Patch for AddTaskLc2V0bachelor_TMVAApp.C to work correctly under ROOT6
=> ROOT6 compatibility fix for Lc2pK0 TMVAApp task

PWGGA/GammaConv/AliAnalysisTaskConvJet.cxx, PWGGA/GammaConv/AliAnalysisTaskConvJet.h
Added more includes and removed using namespace std; and added std::vector everywhere in the hope that that will fix the grid problems.
Furthermore, I do not actually want to push the root streamers commit but I can't find how to delete it. I am hoping that by my second commit that discards those changes
=> PWGGA/GammaConv Adjusted includes for ConvJetTask

PWG/FLOW/Tasks/AliAnalysisTaskCMEV0PID.cxx
use proper wgts for centrality dist
=> use proper wgts for centrality dist

PWGCF/FLOW/GF/AliAnalysisTaskUniFlow.cxx, PWGCF/FLOW/GF/AliAnalysisTaskUniFlow.h, PWGCF/FLOW/GF/CMakeLists.txt, PWGCF/FLOW/GF/PWGCFFLOWGFLinkDef.h, PWGCF/FLOW/macros/AddTaskUniFlow.C
AnalysisTaskUniFlow: PID vn cumulants with Generic Framework
=> PWGCF: PID vn cumulants

PWGCF/FEMTOSCOPY/macros/Train/KpmRun2_00/0010/AddTaskFemtoKchHBT0010.C, PWGCF/FEMTOSCOPY/macros/Train/KpmRun2_00/0010/ConfigFemtoAnalysis.C, PWGCF/FEMTOSCOPY/macros/Train/KpmRun2_00/1090/AddTaskFemtoKchHBT1090.C, PWGCF/FEMTOSCOPY/macros/Train/KpmRun2_00/1090/ConfigFemtoAnalysis.C
=> Configs for K+K- PbPb 5.02 Run2

PWGCF/FEMTOSCOPY/FemtoDream/AliFemtoDreamBasePart.cxx, PWGCF/FEMTOSCOPY/FemtoDream/AliFemtoDreamBasePart.h, PWGCF/FEMTOSCOPY/FemtoDream/AliFemtoDreamCascade.cxx, PWGCF/FEMTOSCOPY/FemtoDream/AliFemtoDreamPairCleaner.cxx, PWGCF/FEMTOSCOPY/FemtoDream/AliFemtoDreamTrack.cxx, PWGCF/FEMTOSCOPY/FemtoDream/AliFemtoDreamTrack.h, PWGCF/FEMTOSCOPY/FemtoDream/AliFemtoDreamTrackMCHist.cxx, PWGCF/FEMTOSCOPY/FemtoDream/AliFemtoDreamv0.cxx, PWGCF/FEMTOSCOPY/FemtoDream/AliFemtoDreamv0MCHist.cxx
Fixes some compiler warnings and adds methods to obtain the xyz position at different radii in the TPC for tracks.
=> Xyz at radii

PWGHF/treeHF/AliHFTreeHandlerLc2V0bachelor.cxx, PWGHF/treeHF/AliHFTreeHandlerLc2V0bachelor.h
This is the first version of the tree handler for the Lc --> K0S + p
=> Tree handler for Lc --> K0S+p

PWGDQ/dielectron/macrosLMEE/AddTask_sscheid_lowmass.C
Modified AddTask to run with ROOT6 and ROOT5
=> Update AddTask: ROOT6

PWGCF/FEMTOSCOPY/FemtoDream/AliAnalysisTaskSigma0Femto.cxx, PWGCF/FEMTOSCOPY/FemtoDream/AliFemtoDreamBasePart.cxx, PWGCF/FEMTOSCOPY/macros/AddTaskFemtoDreamTrackSplit.C, PWGCF/FEMTOSCOPY/macros/AddTaskSigma0DebugTest.C, PWGCF/FEMTOSCOPY/macros/AddTaskSigma0Femto.C, PWGGA/Hyperon/AliAnalysisTaskSigma0Run2.cxx, PWGGA/Hyperon/AliSigma0ParticleBase.cxx, PWGGA/Hyperon/AliSigma0ParticleBase.h, PWGGA/Hyperon/AliSigma0ParticlePhotonMother.cxx, PWGGA/Hyperon/AliSigma0ParticleV0.cxx, PWGGA/Hyperon/AliSigma0ParticleV0.h, PWGGA/Hyperon/AliSigma0PhotonMotherCuts.cxx, PWGGA/Hyperon/AliSigma0PhotonMotherCuts.h
o keep up with the changes in https://github.com/alisw/AliPhysics/pull/8398
o keep track of possible V0 clones (track labels & momentum check)
=> Improvements for Sigma0 femto

PWGHF/vertexingHF/AliHFSystErr.cxx, PWGHF/vertexingHF/AliHFSystErr.h
cuts for D0 in finer pt bins in pPb 0-100  and for centrality ranges 1020, 2040, 4060.
=> D0 in pPb for 1020,2040,4060 added

PWGDQ/dielectron/LMEE/AliAnalysisTaskLMeeCocktailMC.cxx, PWGDQ/dielectron/macrosLMEE/AddTask_LMeeCocktailMC.C
(no GRID connection in UserCreateOutputObjects)
=> Update way to obtain files from GRID 

PWGHF/treeHF/AliAnalysisTaskSEHFTreeCreator.cxx
* Fixing memory leak of event cuts (mainly) in centrality selection
* Moving filling of 'IsEventRejectedDueTo...' to correct position (after first call IsEventSelected(aod))
=> PWGHF: MVA, Fix memory leak event cuts

PWGGA/EMCALTasks/AliAnalysisTaskEMCALPhotonIsolation.cxx, PWGGA/EMCALTasks/macros/AddTaskEMCALPhotonIsolation.C
Multiple bugs with MC and output 1 fixed
QA flag replaced by option to add output to listname
Histograms moved to common output
=> Fix bugs for MC output and adding output flag

PWGCF/FEMTOSCOPY/macros/Train/KK_Run2_FebSp/KK_13TeV_dist_03/AddTaskFemtoKchHBT1090.C, PWGCF/FEMTOSCOPY/macros/Train/KK_Run2_FebSp/KK_13TeV_dist_03/ConfigFemtoAnalysis.C, PWGCF/FEMTOSCOPY/macros/Train/KK_Run2_FebSp/KK_13TeV_dist_07/AddTaskFemtoKchHBT1090.C, PWGCF/FEMTOSCOPY/macros/Train/KK_Run2_FebSp/KK_13TeV_dist_07/ConfigFemtoAnalysis.C, PWGCF/FEMTOSCOPY/macros/Train/KK_Run2_FebSp/pipi_13TeV_dist_03/AddTaskFemtoKchHBT1090.C, PWGCF/FEMTOSCOPY/macros/Train/KK_Run2_FebSp/pipi_13TeV_dist_03/ConfigFemtoAnalysis.C, PWGCF/FEMTOSCOPY/macros/Train/KK_Run2_FebSp/pipi_13TeV_dist_07/AddTaskFemtoKchHBT1090.C, PWGCF/FEMTOSCOPY/macros/Train/KK_Run2_FebSp/pipi_13TeV_dist_07/ConfigFemtoAnalysis.C
=> KK_Run2_FebSp train macros for Ludmila

PWGDQ/dielectron/macrosLMEE/AddTask_LMeeCocktailMC.C
(no GRID connection in UserCreateOutputObjects)
=> Adding debug printouts

PWGHF/vertexingHF/AliAnalysisTaskSEXicZero2XiPifromAODtracks.cxx, PWGHF/vertexingHF/AliAnalysisTaskSEXicZero2XiPifromAODtracks.h, PWGHF/vertexingHF/AliRDHFCutsXicZerotoXiPifromAODtracks.cxx, PWGHF/vertexingHF/AliRDHFCutsXicZerotoXiPifromAODtracks.h, PWGHF/vertexingHF/CMakeLists.txt, PWGHF/vertexingHF/PWGHFvertexingHFLinkDef.h, PWGHF/vertexingHF/macros/AddTaskXicZero2XiPifromAODtracks.C
Add task and cut class for the analysis of the Xic -> Xi pi analysis
=> Add code for the Xic -> Xi pi 

PWGDQ/dielectron/LMEE/AliAnalysisTaskLMeeCocktailMC.cxx, PWGDQ/dielectron/macrosLMEE/AddTask_LMeeCocktailMC.C
(no GRID connection in UserCreateOutputObjects)
=>  change copying directory 

PWGCF/FEMTOSCOPY/AliFemto/AliFemtoBasicEventCut.cxx, PWGCF/FEMTOSCOPY/AliFemto/AliFemtoBasicEventCut.h, PWGCF/FEMTOSCOPY/AliFemtoUser/AliFemtoAnalysisPionPion.cxx, PWGCF/FEMTOSCOPY/AliFemtoUser/AliFemtoAnalysisPionPionObjectConstructor.h
Now determine subclasses and fixes some data
=> PWGCF: Add functionality to AliFemtoAnalysisPionPionConfigurationObject

PWGHF/treeHF/AliHFTreeHandlerLctopKpi.cxx, PWGHF/treeHF/AliHFTreeHandlerLctopKpi.h
to allow for consistent variable use as standard analysis
=> added dist12 and dist23 to tree handler

PWGDQ/dielectron/macrosLMEE/AddTask_acapon.C, PWGDQ/dielectron/macrosLMEE/AddTask_acapon_Efficiency.C, PWGDQ/dielectron/macrosLMEE/Config_acapon.C, PWGDQ/dielectron/macrosLMEE/Config_acapon_Efficiency.C, PWGDQ/dielectron/macrosLMEE/LMEECutLib_acapon.C
The woSDD flag is now passed to all relevant functions, PID calibration,
PID cuts etc
=> Adds woSDD option to all functions (acapon_LMEE)

PWGCF/FEMTOSCOPY/FemtoDream/AliOtonOmegaAnalysis.cxx, PWGCF/FEMTOSCOPY/FemtoDream/AliOtonOmegaAnalysis.h, PWGCF/FEMTOSCOPY/FemtoDream/AliOtonOmegaCascadeCuts.cxx, PWGCF/FEMTOSCOPY/FemtoDream/AliOtonOmegaCascadeCuts.h, PWGCF/FEMTOSCOPY/macros/AddTaskOtonOmega.C, PWGCF/FEMTOSCOPY/macros/ConfigOtonOmega.C
=> Commit for Oton

PWGGA/PHOSTasks/PHOS_Run2/AliAnalysisTaskPHOSObjectCreator.cxx, PWGGA/PHOSTasks/PHOS_Run2/AliAnalysisTaskPHOSPi0EtaToGammaGamma.cxx, PWGGA/PHOSTasks/PHOS_Run2/AliPHOSTriggerHelper.cxx, PWGGA/PHOSTasks/PHOS_Run2/macros/AddTaskPHOSObjectCreator.C, PWGGA/PHOSTasks/PHOS_Run2/macros/AddTaskPHOSPi0EtaToGammaGamma_PbPb_5TeV.C, PWGGA/PHOSTasks/PHOS_Run2/macros/AddTaskPHOSSingleSim.C
=> update L1 trigger scanning window on M1 (shift along Z)

PWGGA/EMCALTasks/AliAnalysisTaskGammaHadron.cxx, PWGGA/EMCALTasks/AliAnalysisTaskGammaHadron.h
Disables track pt THnSparse axis. Makes merging failure less likely.
=> Disables track pt THnSparse axis

PWGGA/GammaConv/AliAnalysisTaskNeutralMesonToPiPlPiMiNeutralMeson.cxx, PWGGA/GammaConv/AliAnalysisTaskdPhi.cxx, PWGGA/GammaConv/AliCaloPhotonCuts.cxx, PWGGA/GammaConv/AliConvEventCuts.cxx, PWGGA/GammaConv/AliConversionPhotonCuts.cxx, PWGGA/GammaConv/AliConversionTrackCuts.cxx, PWGGA/GammaConv/AliConversionTrackCuts.h
AliVCluster pointer handled by std::unique_ptr. In addition
remove background handlers and not just the array containing
them in the destructor.
=> PWGGA/GammaConv: Fixing small memory leaks

PWGHF/jetsHF/AliEmbeddingEventForHFTask.cxx, PWGHF/jetsHF/AliEmbeddingEventForHFTask.h, PWGHF/jetsHF/CMakeLists.txt, PWGHF/jetsHF/PWGHFjetsHFLinkDef.h, PWGHF/jetsHF/macros/AddEmbeddingEventForHF.C
Antonio's task to embedd data events to Monte-Carlo.
=> Antonio's embedding task

PWGCF/FEMTOSCOPY/AliFemtoUser/AliFemtoAnalysisPionPionObjectConstructor.cxx, PWGCF/FEMTOSCOPY/AliFemtoUser/AliFemtoAnalysisPionPionObjectConstructor.h, PWGCF/FEMTOSCOPY/AliFemtoUser/CMakeLists.txt, PWGCF/FEMTOSCOPY/AliFemtoUser/PWGCFfemtoscopyUserLinkDef.h
Implement `From` and `Into` for some select AliFemto types
=> PWGCF: ConfigObject - Add implementation of "constructor objects"

PWGHF/jetsHF/AliEmbeddingEventForHFTask.cxx
Fix for the bug of a wrong pointer comparison.
=> fix for the bug of a wrong pointer comparison

PWGLF/RESONANCES/extra/AliAnalysisTaskXi1530.cxx, PWGLF/RESONANCES/extra/AliAnalysisTaskXi1530.h
+ Resolve trigger efficiency function
+ Code reformatting
+ Multiplicity QA plot for HighMultV0 triggered event.
=> [PWGLF] Resolve trigger efficiency function/Code reformatting

PWGCF/FEMTOSCOPY/macros/Train/KK_Run2_MC_FebSp/KK_13TeV_dist_03/AddTaskFemtoKchHBT1090.C, PWGCF/FEMTOSCOPY/macros/Train/KK_Run2_MC_FebSp/KK_13TeV_dist_03/ConfigFemtoAnalysis.C, PWGCF/FEMTOSCOPY/macros/Train/KK_Run2_MC_FebSp/KK_13TeV_dist_07/AddTaskFemtoKchHBT1090.C, PWGCF/FEMTOSCOPY/macros/Train/KK_Run2_MC_FebSp/KK_13TeV_dist_07/ConfigFemtoAnalysis.C, PWGCF/FEMTOSCOPY/macros/Train/KK_Run2_MC_FebSp/pipi_13TeV_dist_03/AddTaskFemtoKchHBT1090.C, PWGCF/FEMTOSCOPY/macros/Train/KK_Run2_MC_FebSp/pipi_13TeV_dist_03/ConfigFemtoAnalysis.C, PWGCF/FEMTOSCOPY/macros/Train/KK_Run2_MC_FebSp/pipi_13TeV_dist_07/AddTaskFemtoKchHBT1090.C, PWGCF/FEMTOSCOPY/macros/Train/KK_Run2_MC_FebSp/pipi_13TeV_dist_07/ConfigFemtoAnalysis.C
=> Train macros for Ludmila KK_Run2_MC_FebSp

PWGDQ/dielectron/macrosLMEE/AddTask_sscheid_efficiencyV2.C, PWGDQ/dielectron/macrosLMEE/AddTask_sscheid_lowmass.C
Fixed typo in the alien_cp path of efficiency task
=> AddTask Efficiency: Fixed typo

PWGHF/vertexingHF/AliAnalysisTaskSEXicPlus2XiPiPifromAODtracks.cxx, PWGHF/vertexingHF/AliAnalysisTaskSEXicPlus2XiPiPifromAODtracks.h, PWGHF/vertexingHF/macros/AddTaskXicPlus2XiPiPifromAODtracks.C
Add possibility to separate signal and bkg in MC for XiC+ -> Xi pi pi and minor modification of the AddTask
=> Add separation of signal and bkg in MC for  XiC+ -> Xi pi pi 

PWG/JETFW/AliEmcalJetConstituent.cxx, PWG/JETFW/AliEmcalJetConstituent.h, PWG/JETFW/AliEmcalParticleJetConstituent.cxx
- Call Copy constructor of AliEmcalJetConstituent
- Fix unitialized values
=> Fix copy constructor in AliEmcalParticleConstituents

PWGHF/correlationHF/macros/CompareFitResults_pPbVsCentrality_Paper.C, PWGHF/correlationHF/macros/CompareFitResults_ppVspPb_2.C, PWGHF/correlationHF/macros/CompareFitResults_ppVspPb_vsPtAss.C, PWGHF/correlationHF/macros/CompareFitResultspPb2016.C, PWGHF/correlationHF/macros/CompareFitResultspp2017.C, PWGHF/correlationHF/macros/CompareFitResultspp2017_vsPtAss.C, PWGHF/correlationHF/macros/DoComparison_pPbVsCentrality_Distributions_Paper.C
Also, sigma->width renaming in final plots
=> New macros to plot D-h corr in pPb vs centrality (final style)

PWGJE/EMCALJetTasks/UserTasks/AliAnalysisTaskEmcalJetTagger.cxx, PWGJE/EMCALJetTasks/UserTasks/AliAnalysisTaskEmcalJetTagger.h
- Move existing documentation from cxx file to header file
- Add missing documentation or improve where needed
=> [Doxygen] Document jet tagger

PWGHF/vertexingHF/macros/AddTaskLc2V0bachelor_TMVAApp.C
...and also setting the default value of the argument to decide
whether to store or not the debug histograms
=> Removing hardcoded setting for centrality selection (leftover...)

PWGLF/RESONANCES/extra/AddTaskXi1530.C
Add suffix option in AddTask macro
=> PWGLF: Add suffix option for subwagon setup

PWGCF/FLOW/CME/CMakeLists.txt
... which is in library OADB. ALICEanalysis can be removed from dependencies
=>  fix library dependencies to correctly include AliAnalysisUtils

PWGDQ/dielectron/macrosLMEE/AddTask_acapon_Efficiency.C, PWGDQ/dielectron/macrosLMEE/Config_acapon_Efficiency.C
Also, update comments and formatting so it's readable..
=> Require final_state for pair efficiency correction (acapon_LMEE)

PWGJE/EMCALJetTasks/UserTasks/AliAnalysisTaskEmcalJetPerformance.cxx
@mfasDa or @raymondEhlers could you please approve it for today's tag? @jdmulligan is informed but still sleeping ;-)
=> changes bins of matching histo so that it can be used as a flexible RM

PWG/EMCAL/EMCALtrigger/AliEmcalTriggerSimQATask.cxx, PWG/EMCAL/EMCALtrigger/AliEmcalTriggerSimQATask.h
Separates event trigger into EMCal and DCal triggers.
Corrects a swap between EG1 and EG2, etc
=> Separates event trigger into EMCal and DCal triggers.

PWGMM/UE/CMakeLists.txt, PWGMM/UE/PWGMMueLinkDef.h, PWGMM/UE/UePid/AddTaskUePid.C, PWGMM/UE/UePid/AliAnalysisTaskUePid.cxx, PWGMM/UE/UePid/AliAnalysisTaskUePid.h
I have added one analysis task which performs the UE analysis as a function of TPC-dE/dx and momentum of charged particles (pT>2 GeV/c)
=> UE observables as a function of leading ID pT

PWGHF/vertexingHF/AliHFSystErr.cxx, PWGHF/vertexingHF/AliHFSystErr.h
Sorry it calls it 3 commits it is just the adding of the fine binning systematics for the D*
=>  Include Dstar 0100pPb 2016 Fine binning 

PWG/EMCAL/EMCALbase/AliAnalysisTaskEmcal.cxx, PWG/EMCAL/EMCALbase/AliEmcalIterableContainer.h, PWGJE/EMCALJetTasks/Tracks/AliAnalysisTaskEmcalJetEnergyScale.cxx, PWGJE/EMCALJetTasks/Tracks/AliAnalysisTaskEmcalJetEnergyScale.h, PWGJE/EMCALJetTasks/Tracks/AliAnalysisTaskEmcalJetEnergySpectrum.cxx, PWGJE/EMCALJetTasks/Tracks/AliAnalysisTaskEmcalJetEnergySpectrum.h, PWGJE/EMCALJetTasks/Tracks/AliAnalysisTaskEmcalSoftDropResponse.cxx, PWGJE/EMCALJetTasks/Tracks/AliAnalysisTaskEmcalSoftDropResponse.h
Outlier rejection is based on the maximum particle level
jet identified by fastjet to be > n * the event pt-hard
=> Implement custom outlier rejection

PWGJE/EMCALJetTasks/Tracks/AliAnalysisTaskEmcalJetEnergyScale.cxx, PWGJE/EMCALJetTasks/Tracks/AliAnalysisTaskEmcalJetEnergySpectrum.cxx, PWGJE/EMCALJetTasks/Tracks/AliAnalysisTaskEmcalSoftDropResponse.cxx
Function defined (in framework) as selecting events
without outliers, while its name implies the opposite.
=> Swap return values for outlier cut

PWGLF/RESONANCES/extra/AddTaskInclusivef0f2.C, PWGLF/RESONANCES/extra/AliAnalysisTaskInclusivef0f2.cxx, PWGLF/RESONANCES/extra/AliAnalysisTaskInclusivef0f2.h, PWGLF/RESONANCES/extra/CMakeLists.txt, PWGLF/RESONANCES/extra/PWGLFrsnextraLinkDef.h
New code;
AliAnalysisTaskInclusivef0f2.cxx
AliAnalysisTaskInclusivef0f2.h
AddTaskInclusivef0f2.C
first commit of inclusive f0 f2 analysis
=> PWGLF: Add new code for inclusive f0 f2 analysis

PWG/FLOW/Tasks/AliAnalysisTaskTwoMultiCorrelations.cxx, PWG/FLOW/Tasks/AliAnalysisTaskTwoMultiCorrelations.h
* Add variables for the event and the track selections.
* Add their control histograms before and after the selections.
=> Add options for the selection.

PWGHF/jetsHF/AliAnalysisTaskDJetCorrelationsQA.cxx, PWGHF/jetsHF/AliAnalysisTaskDJetCorrelationsQA.h, PWGHF/jetsHF/macros/AddTaskDJetCorrelationsQA.C
Added more QA plots
Renamed existing histograms to better reflect the content 
Fixed minor bugs
Changed nullptr -> NULL to be compatible with Root 5
Removed ghost jets from MC-QA plots
=> PWG-HF: D-jets: Added more QA plots, ROOT5 compatibility, bugfixes

PWGCF/Correlations/JCORRAN/Pro/AliAnalysisTaskRidge.cxx, PWGCF/Correlations/JCORRAN/Pro/AliAnalysisTaskRidge.h, PWGCF/Correlations/JCORRAN/Pro/CMakeLists.txt, PWGCF/Correlations/JCORRAN/Pro/PWGCFCorrelationsJCORRANProLinkDef.h, PWGCF/Correlations/macros/jcorran/AddTaskRidge.C
PWGCF/Correlations/JCORRAN/Pro/AliAnalysisTaskRidge.cxx
PWGCF/Correlations/JCORRAN/Pro/AliAnalysisTaskRidge.h
PWGCF/Correlations/macros/jcorran/AddTaskRidge.C
Ridge analysis code in pp at 13 TeV
changed files
PWGCF/Correlations/JCORRAN/Pro/CMakeLists.txt
PWGCF/Correlations/JCORRAN/Pro/PWGCFCorrelationsJCORRANProLinkDef.h
=> Ridge analysis code in pp at 13 TeV

PWGJE/EMCALJetTasks/CMakeLists.txt, PWGJE/EMCALJetTasks/PWGJEEMCALJetTasksLinkDef.h, PWGJE/EMCALJetTasks/Tracks/AliAnalysisTaskEmcalResponseOutliers.cxx, PWGJE/EMCALJetTasks/Tracks/AliAnalysisTaskEmcalResponseOutliers.h, PWGJE/EMCALJetTasks/macros/AddTaskResponseOutliers.C
Outliers are defined as part jets with pt >> event
pt-hard and small det jet pt.
=> Add task investigating outliers in the response matrix

PWGHF/vertexingHF/AliHFInvMassFitter.cxx
Add gaussian fit to the ResidualTrend distribution after background subtraction.
=> Add gaussian fit to hResidualTrend

PWGDQ/reducedTree/AliAnalysisTaskReducedTreeMaker.cxx, PWGDQ/reducedTree/AliReducedVarManager.cxx, PWGDQ/reducedTree/AliReducedVarManager.h
- momentum on calo for AOD tracks (forgot to add in previous commit)
- momentum on calo for E/p if available
- calo M02 for matched tracks
=> PWGDQ/reducedTree: updates for EMCal triggered analysis

PWGUD/UPC/AddTaskUPCforward.C, PWGUD/UPC/AliAnalysisTaskUPCforward.cxx, PWGUD/UPC/AliAnalysisTaskUPCforward.h, PWGUD/UPC/CMakeLists.txt, PWGUD/UPC/PWGUDupcLinkDef.h
Added a new class for the analysis of charmonium states decaying to opposite sign dimuon for the forward region. Added $Class.{h, cxx} and the Add{$Class}.C macro. Added the source file to the CMakeLists.txt and added the pragma statement for the linker (with the corresponding +). INITIAL COMMIT.
=> Added AliAnalysisTaskUPCforward and changed CMakeLists and LinkDef.

PWGDQ/dielectron/LMEE/AliAnalysisTaskSimpleTreeMaker.cxx, PWGDQ/dielectron/LMEE/AliAnalysisTaskSimpleTreeMaker.h, PWGDQ/dielectron/macrosLMEE/AddTaskSimpleTreeMaker.C
=> Add extra DCA features to simpleTreeMaker

PWGJE/EMCALJetTasks/Tracks/AliAnalysisTaskEmcalResponseOutliers.cxx, PWGJE/EMCALJetTasks/Tracks/AliAnalysisTaskEmcalResponseOutliers.h
- Connect proper jet container (full jets) at det level
- Fix several variables in jet tree
- Add control histograms for outliers and normal jets
- Add couple of AliDebugStreams
- Fix compiler warnings
=> Fix filling of outlier tree

PWGCF/Correlations/DPhi/AliAnalysisTaskGeneralBF.cxx, PWGCF/Correlations/DPhi/AliAnalysisTaskGeneralBF.h, PWGCF/Correlations/macros/PIDBFDptDpt/AddTaskGeneralBF.C
=> added lambda cut

PWGJE/EMCALJetTasks/UserTasks/AliAnalysisTaskEmcalJetHCorrelations.cxx, PWGJE/EMCALJetTasks/UserTasks/AliAnalysisTaskEmcalJetHCorrelations.h, PWGJE/EMCALJetTasks/UserTasks/AliAnalysisTaskEmcalJetHPerformance.cxx, PWGJE/EMCALJetTasks/UserTasks/AliAnalysisTaskEmcalJetHPerformance.h
Move from my custom implemented version to the centralized version in
`AliAnalysisTaskEmcal`
=> Use built in AliEventCuts

PWGHF/jetsHF/AliEmbeddingEventForHFTask.cxx
Fix for AOD path string, and fixing order of variable initialization in constructors.
=> fix for AOD path, and fixing order of initialization

PWGDQ/dielectron/macrosLMEE/Config_acapon.C, PWGDQ/dielectron/macrosLMEE/LMEECutLib_acapon.C
Simple TOFreq PID cut setting added for comparisons.
=> Add TOFreq PID cut setting (acapon_LMEE)

PWGCF/Correlations/DPhi/AliAnalysisTaskGeneralBF.cxx, PWGCF/Correlations/DPhi/AliAnalysisTaskGeneralBF.h, PWGCF/Correlations/macros/PIDBFDptDpt/AddTaskGeneralBF.C
=> added lambda sideband cut

PWGCF/Correlations/DPhi/AliAnalysisTaskGeneralBF.cxx
=> optimized lambda cut

PWGCF/FEMTOSCOPY/macros/AddTaskSigma0DebugTest.C, PWGGA/Hyperon/AliSigma0PhotonMotherCuts.cxx
o Plus some systematic variations to check the effect on the purity
=> By default use the Armenteros-Podolandski cut for the Sigma0

PWGHF/jetsHF/AliAnalysisTaskDJetCorrelationsQA.cxx, PWGHF/jetsHF/AliAnalysisTaskDJetCorrelationsQA.h
Modified QA filling scheme for data
=> PWGHF: Djets: Modified QA filling scheme for data

PWGCF/FEMTOSCOPY/macros/Train/KK_Run2_MC_FebSp1/KK_13TeV_dist_03/ConfigFemtoAnalysis.C, PWGCF/FEMTOSCOPY/macros/Train/KK_Run2_MC_FebSp1/KK_13TeV_dist_07/ConfigFemtoAnalysis.C, PWGCF/FEMTOSCOPY/macros/Train/KK_Run2_MC_FebSp1/add/AddTaskFemto.C, PWGCF/FEMTOSCOPY/macros/Train/KK_Run2_MC_FebSp1/pipi_13TeV_dist_03/ConfigFemtoAnalysis.C, PWGCF/FEMTOSCOPY/macros/Train/KK_Run2_MC_FebSp1/pipi_13TeV_dist_07/ConfigFemtoAnalysis.C
=> Train macros for Ludmila

PWGGA/GammaConv/AliAnalysisTaskGammaCalo.cxx
Added a delete Cluster0 and delete Cluster1 to fix memory leak
Changed IsSignal boolean in IsMesonSelected to stop "undefined rapidity" cout
=> PWGGA/GammaConv Fixed memory leak and undefined rapidity cout

PWGPP/TOF/AliAnalysisTaskTOFqaID.cxx, PWGPP/TOF/AliAnalysisTaskTOFqaID.h, PWGPP/TOF/trending/DrawTrendingTOFQA.C, PWGPP/TOF/trending/MakeTrendingTOFQAv2.C
- Fixed axis title of single run QA histograms
- Filling the error on integrated matching efficiency in the output tree
- Removed non used option: 'SetDrawOption'
=> Minor fixes for TOF QA

PWG/EMCAL/EMCALbase/AliEmcalContainerUtils.cxx
We clearly report the problematic key if an invalid key is passed.
=> Improve debug information for physics selection

PWGUD/UPC/AliAnalysisTaskUPCforwardMC.cxx, PWGUD/UPC/AliAnalysisTaskUPCforwardMC.h, PWGUD/UPC/CMakeLists.txt, PWGUD/UPC/PWGUDupcLinkDef.h
Created a new AnalysisTask, AliAnalysisTaskUPCforwardMC, with the sole purpose to analyze the MC for the PbPb AODs. The class is more or less based on AliAnalysisTaskUPCforward but the large difference in histogram content and code in the UserExec() justifies the need for a new class... The CMakeLists.txt and Linker Definitions have been changed consistently. New histograms have been added to the AliAnalysisTaskUPCforward reflecting the need to investigate new properties of the J/Psi (plus the indentation has been changed here and there). 
IMPORTANT: the two codes have been tested on local and they can analyse data properly. They both should be pretty safe to merge... 
Many thanks. 
Regards.
=> Added AliAnalysisTaskUPCforwardMC. Added histos to AliAnalysisTaskUPCf*.

PWGJE/EMCALJetTasks/Tracks/AliAnalysisTaskEmcalJetEnergyScale.cxx, PWGJE/EMCALJetTasks/Tracks/AliAnalysisTaskEmcalJetEnergyScale.h, PWGJE/EMCALJetTasks/Tracks/AliAnalysisTaskEmcalJetEnergySpectrum.cxx, PWGJE/EMCALJetTasks/Tracks/AliAnalysisTaskEmcalJetEnergySpectrum.h, PWGJE/EMCALJetTasks/Tracks/AliAnalysisTaskEmcalSoftDropResponse.cxx, PWGJE/EMCALJetTasks/Tracks/AliAnalysisTaskEmcalSoftDropResponse.h, PWGJE/EMCALJetTasks/macros/AddTaskEmcalJetEnergyScale.C, PWGJE/EMCALJetTasks/macros/AddTaskEmcalJetEnergySpectrum.C, PWGJE/EMCALJetTasks/macros/AddTaskEmcalSoftdropResponse.C
Needed when running with MC track selector
task in order to remove double counting
of photons
=> Add non-standard MC particle container

PWGLF/RESONANCES/Xi1530/AddTaskXi1530.C, PWGLF/RESONANCES/Xi1530/AliAnalysisTaskXi1530.cxx, PWGLF/RESONANCES/Xi1530/AliAnalysisTaskXi1530.h
Add Systematic option.
Modify AddTaskMacro to configure by using text input
=> PWGLF: Update analysis code for systematic study

PWGJE/EMCALJetTasks/UserTasks/AliAnalysisTaskEmcalJetHPerformance.cxx, PWGJE/EMCALJetTasks/UserTasks/AliAnalysisTaskEmcalJetHPerformance.h
=> Additional cell QA for internal, external event

PWGCF/Correlations/JCORRAN/Pro/AliAnalysisTaskRidge.cxx, PWGCF/Correlations/JCORRAN/Pro/AliAnalysisTaskRidge.h
Loading efficiency histograms for each period by checking run number
=> PWGCF : Loading efficiency histograms for each period by checking run number

PWGUD/UPC/AddTaskUPCforwardMC.C
Added AddTaskUPCforwardMC, the steering macro for the analysis task. This contribution is the last step required to ultimately analyze the PbPb AOD MC....
=> PWGUD/UPC: Added AddTaskUPCforwardMC. Last step in the new analysis implementation.

PWG/FLOW/Tasks/AliAnalysisTaskTwoMultiCorrelations.cxx, PWG/FLOW/Tasks/AliAnalysisTaskTwoMultiCorrelations.h
* Made the code able to compute all 2-p and 4-p correlations and the needed 6-p correlations between the harmonics v1 to v6 without input of the harmonics from the user.
* Add a new cut for the track selection.
* Remove old computations of 3-p correlations, now useless.
=> Modified the computation of the multiparticle correlations.

PWGHF/treeHF/AliAnalysisTaskSEHFTreeCreator.cxx, PWGHF/treeHF/AliAnalysisTaskSEHFTreeCreator.h
V0A and nTracklets added in Tree, as multiplicity estimators
=> adding V0A, nTracklets

PWGCF/FEMTOSCOPY/FemtoDream/AliAnalysisTaskSigma0Femto.cxx, PWGCF/FEMTOSCOPY/FemtoDream/AliAnalysisTaskSigma0Femto.h, PWGCF/FEMTOSCOPY/FemtoDream/AliFemtoDreamCollConfig.cxx, PWGCF/FEMTOSCOPY/FemtoDream/AliFemtoDreamCollConfig.h, PWGCF/FEMTOSCOPY/FemtoDream/AliFemtoDreamCorrHists.cxx, PWGCF/FEMTOSCOPY/FemtoDream/AliFemtoDreamCorrHists.h, PWGCF/FEMTOSCOPY/macros/AddTaskSigma0DebugTest.C, PWGCF/FEMTOSCOPY/macros/AddTaskSigma0Femto.C, PWGGA/Hyperon/AliSigma0PhotonMotherCuts.cxx, PWGGA/Hyperon/AliSigma0PhotonMotherCuts.h, PWGGA/Hyperon/AliSigma0V0Cuts.cxx
o Fixes a memory problem
o Add lower boundary for the Sigma0 pT
o Restructures the output
=> Improvements for p-Sigma0 femto

PWGJE/EMCALJetTasks/macros/JetQA/scalePtHardHistos.py
@jdmulligan, here is the commit that adds the scaling of the hMatchingDistance histogram and adds the possibility to only scale certain pT hard bins
=> Added way to scale hMatching distance histogram and min/max pT hard bin

PWGHF/treeHF/AliAnalysisTaskSEHFTreeCreator.cxx, PWGHF/treeHF/AliAnalysisTaskSEHFTreeCreator.h, PWGHF/treeHF/AliHFTreeHandler.cxx, PWGHF/treeHF/AliHFTreeHandler.h, PWGHF/treeHF/AliHFTreeHandlerBplustoD0pi.cxx, PWGHF/treeHF/AliHFTreeHandlerBplustoD0pi.h, PWGHF/treeHF/AliHFTreeHandlerD0toKpi.cxx, PWGHF/treeHF/AliHFTreeHandlerD0toKpi.h, PWGHF/treeHF/AliHFTreeHandlerDplustoKpipi.cxx, PWGHF/treeHF/AliHFTreeHandlerDplustoKpipi.h, PWGHF/treeHF/AliHFTreeHandlerDstartoKpipi.cxx, PWGHF/treeHF/AliHFTreeHandlerDstartoKpipi.h, PWGHF/treeHF/AliHFTreeHandlerDstoKKpi.cxx, PWGHF/treeHF/AliHFTreeHandlerDstoKKpi.h, PWGHF/treeHF/AliHFTreeHandlerLc2V0bachelor.cxx, PWGHF/treeHF/AliHFTreeHandlerLc2V0bachelor.h, PWGHF/treeHF/AliHFTreeHandlerLctopKpi.cxx, PWGHF/treeHF/AliHFTreeHandlerLctopKpi.h
Adding event id variables (ev index in a file + file number + run number) to the tree for event characterization and to the candidates' trees
=> Adding event id

PWGDQ/dielectron/core/AliDielectronMC.cxx, PWGDQ/dielectron/core/AliDielectronMC.h, PWGDQ/dielectron/core/AliDielectronSignalMC.cxx, PWGDQ/dielectron/core/AliDielectronSignalMC.h
Add possibility via SetCheckCorrelatedHF to select correlated charm/beauty in Hijing to check the prefilter efficiency for Zafar (Run-3)
=> Add possibility to select correlated charm/beauty in Hijing

PWGUD/UPC/AliAnalysisTaskUPCforward.cxx, PWGUD/UPC/AliAnalysisTaskUPCforward.h, PWGUD/UPC/AliAnalysisTaskUPCforwardMC.cxx, PWGUD/UPC/AliAnalysisTaskUPCforwardMC.h
Following the UPC meeting of 5/3/2019, accordingly changed the ZDC part of AliAnalysisTaskUPCforward to check in inconsistencies for the fZNAenergyH and fZNCenergyH. Based on these changes, the differential neutron emission part of the analysis has seen new changes. The AliAnalysisTaskUPCforwardMC has seen changes too, with the addition of the Pt plot for the Dimuon pairs at Generation level.
IMPORTANT: both changes have been checked on local. 
Regards.
=> PWGUD/UPC: Updated the MC macro and changed the ZDC part of the AliAnalysisTaskUPCforward.

PWGDQ/dielectron/LMEE/AliAnalysisTaskCharm.cxx, PWGDQ/dielectron/LMEE/AliAnalysisTaskCharm.h, PWGDQ/dielectron/macrosLMEE/AddTaskCharm.C
Update the CNM implementation to be able to use also pt of D mesons + update add task to take file from alien.
=> Update CNM + file from alien

PWGMM/UE/UePid/AliAnalysisTaskUePid.cxx, PWGMM/UE/UePid/AliAnalysisTaskUePid.h
- dE/dx range was extended
- Selection on momentum for pion MIP was added. dE/dx vs eta histos before recalibration were added
- Sum pT density has been added
=> adding the histograms to extract the sum pT density 

PWGCF/Correlations/JCORRAN/Pro/AliAnalysisTaskRidge.cxx, PWGCF/Correlations/JCORRAN/Pro/AliAnalysisTaskRidge.h, PWGCF/Correlations/macros/jcorran/AddTaskRidge.C
How to load efficiency files changed
=> How to load efficiency files changed

PWGLF/RESONANCES/Xi1530/AliAnalysisTaskXi1530.cxx
for HighMult bins, from <100,0,0.1> to <0,0.01,0.03,0.05,0.07,0.1> (84% reduced)
for MC bins, from <1000,0,100> to <0,0.01,0.03,0.05,0.07,0.01,1,5,10,15,20,30,40,50,70,100> (65% reduced)
=> PWGLF: optimize centrality bin, change coding style

PWGHF/jetsHF/macros/AddTaskDFilterCorrelations.C
Fix for the type of the first argument, was old class from JE.
=> Fix for the type of the first argument.

PWGJE/EMCALJetTasks/UserTasks/AliAnalysisTaskEmcalJetHPerformance.cxx
=> Add QA info to identify double corrected embedded events

PWGDQ/dielectron/core/AliDielectronVarManager.h
Change the definition of DCA_{z} sigma according to Ruben's mail
=> DCA_{z} in sigma 

PWGCF/FEMTOSCOPY/macros/Train/GK/test/ConfigFemtoAnalysis.C
Adding a baryon-antibaryon config file
=> AliFemto: adding bb femto config file

PWGDQ/dielectron/macrosLMEE/LMEECutLib_acapon.C
Removed for clarity. No functionality change.
=> Remove woSDD ITS PID cal. option (acapon_LMEE)

PWGJE/EMCALJetTasks/UserTasks/AliAnalysisTaskEmcalJetHPerformance.cxx
=> Exclude cell times which are outliers

PWGCF/Correlations/macros/jcorran/AddTaskRidge.C
Add one input for subwagon of Legotrain
=> Add one input for subwagon

PWGHF/jetsHF/macros/AddTaskDFilterCorrelations.C
Removing functionality for the old kResponseMatrix correlation method.
=> Removing functionality for kResponseMatrix

PWGPP/TOF/AliAnalysisTaskTOFqaID.cxx, PWGPP/TOF/AliAnalysisTaskTOFqaID.h
- Computing TOF-T0 once per event -> CPU performance improved
- Added T0 mask vs TOF hit multiplicity TH2
- Added feature to used AliTOFT0v1 in calib. mode and fill the corresponding histograms
=> Updated TOF QA

PWGPP/TPC/AliTPCPIDEtaQA.cxx, PWGPP/TPC/AliTPCPIDEtaTree.cxx, PWGPP/TPC/AliTPCcalibResidualPID.cxx, PWGPP/TPC/AliTPCcalibResidualPID.h
Adding several funktionalities:
* Function for ALEPH in AliTPCcalibResidualPID
* Output of AliTPCcalibResidualPID will be adjusted in maxMultiplicity according to the collision system
* Adding Pile-Up rejection of events in AliTPCcalibResidualPID, TPCPIDEtaTree and TPCPIDEtaQA
=> Functionalities for Spline production

PWGJE/EMCALJetTasks/Tracks/AliAnalysisTaskEmcalJetEnergyScale.cxx, PWGJE/EMCALJetTasks/Tracks/AliAnalysisTaskEmcalJetEnergySpectrum.cxx
Needs increase of the pt-range at particle level up to
600 GeV as well.
=> Increase pt-range at detector level up to 300 GeV

PWG/FLOW/Tasks/AliAnalysisTaskCMEMC.cxx, PWG/FLOW/Tasks/AliAnalysisTaskCMEMC.h, PWG/FLOW/Tasks/CMakeLists.txt, PWG/FLOW/Tasks/PWGflowTasksLinkDef.h, PWGCF/FLOW/macros/AddTaskCMEMC.C
Added Analysis Task for CME analysis in MC sample
=> Added Analysis Task for CME analysis in MC sample

PWGCF/FEMTOSCOPY/EfficiencyTask/AliAnalysisTaskParticleEff.cxx
Without double counting PID method corrected
=> Bug fix in EfficiencyTask #2

PWG/EMCAL/EMCALtrigger/AliEmcalTriggerSimQATask.cxx, PWG/EMCAL/EMCALtrigger/AliEmcalTriggerSimQATask.h
Adds histograms comparing distances between patches and clusters
Adds histograms for matched patches and clusters
=> Patch and Cluster Matching

PWGLF/RESONANCES/Xi1530/AddTaskXi1530.C, PWGLF/RESONANCES/Xi1530/AliAnalysisTaskXi1530.cxx, PWGLF/RESONANCES/Xi1530/AliAnalysisTaskXi1530.h
Add new option "NoQA" so that it can avoid to save too much histogram.
=> noQA option added

PWGLF/RESONANCES/Xi1530/AliAnalysisTaskXi1530.cxx
One missing point when using "noQA" option.
=> fix missing point in MC

PWGHF/vertexingHF/charmFlow/AliAnalysisTaskSECharmHadronvn.cxx, PWGHF/vertexingHF/charmFlow/CharmHadronVnAnalysis.C, PWGHF/vertexingHF/charmFlow/CharmHadronVnFitSystematics.C, PWGHF/vertexingHF/charmFlow/config_Dplus_v2_unbiased.yml
Task: implement preselection to speed up task execution and fix code to run task w/o tender 
Macros: add output dir path as parameter
=> Update D-meson flow code

PWGJE/EMCALJetTasks/UserTasks/AliAnalysisTaskEmcalJetPerformance.cxx, PWGJE/EMCALJetTasks/UserTasks/AliAnalysisTaskEmcalJetPerformance.h
@jdmulligan these are the changes for the fragmentation bias test
=> Add RM THnSparse with angularity axis for frag bias test

OADB/COMMON/MULTIPLICITY/AliMultSelectionCalibratorMC.cxx, OADB/COMMON/MULTIPLICITY/AliMultSelectionCalibratorMC.h
Calibrator changes to enable an advanced MC centrality calibration
=> MC supercalibration option (nonlinear, etc) added

PWG/FLOW/Base/AliFlowEventSimple.cxx, PWGCF/Correlations/DPhi/TriggerPID/AliTwoParticlePIDCorr.cxx, PWGCF/Correlations/JCORRAN/Pro/AliAnalysisTaskRidge.cxx, PWGCF/EBYE/BalanceFunctions/AliAnalysisTaskBF.cxx, PWGCF/EBYE/BalanceFunctions/AliAnalysisTaskBFPsi.cxx, PWGCF/EBYE/BalanceFunctions/AliAnalysisTaskTriggeredBF.cxx, PWGHF/correlationHF/AliAnalysisTaskDxHFECorrelation.cxx, PWGHF/correlationHF/AliAnalysisTaskDxHFEParticleSelection.cxx, PWGHF/correlationHF/AliDxHFECorrelation.cxx, PWGHF/correlationHF/AliDxHFECorrelationMC.cxx, PWGHF/correlationHF/AliDxHFEParticleSelection.cxx, PWGHF/correlationHF/AliDxHFEParticleSelectionD0.cxx, PWGHF/correlationHF/AliDxHFEParticleSelectionEl.cxx, PWGHF/correlationHF/AliDxHFEParticleSelectionMCD0.cxx, PWGHF/correlationHF/AliDxHFEParticleSelectionMCEl.cxx, PWGHF/correlationHF/AliDxHFEToolsMC.cxx
These are in fact only two changes:
- replacing std::random_shuffle by std::shuffle
- replacing auto_ptr by unique_ptr
=> Possibility to compile with C++17

PWGLF/RESONANCES/Xi1530/AliAnalysisTaskXi1530.cxx, PWGLF/RESONANCES/Xi1530/AliAnalysisTaskXi1530.h
Change of the handling MCEvent.
Previously, it was handled by AliStack,
Now, it is using AliMCEvent and AliMCParticle
=> Not using alistack as informed

PWGCF/Correlations/DPhi/Unfoldedhistos/AliAnalysisTaskCorrelationsStudies.cxx, PWGCF/Correlations/DPhi/Unfoldedhistos/AliCSPIDCuts.cxx, PWGCF/Correlations/DPhi/Unfoldedhistos/AliCSPIDCuts.h, PWGCF/Correlations/DPhi/Unfoldedhistos/AliCSPairAnalysis.cxx, PWGCF/Correlations/DPhi/Unfoldedhistos/AliCSPairAnalysis.h, PWGCF/Correlations/DPhi/Unfoldedhistos/AliCSTrackCuts.cxx, PWGCF/Correlations/DPhi/Unfoldedhistos/AliCSTrackCuts.h, PWGCF/Correlations/DPhi/Unfoldedhistos/AliCSTrackSelection.cxx, PWGCF/Correlations/DPhi/Unfoldedhistos/AliCSTrackSelection.h, PWGCF/Correlations/DPhi/Unfoldedhistos/AliDptDptCorrelations.cxx, PWGCF/Correlations/DPhi/Unfoldedhistos/AliDptDptCorrelations.h, PWGCF/Correlations/macros/Unfoldedhistos/runCorrelationsStudiesConfigMacro.C
According to the recommendation of not using neither ``Stack`` nor ``TParticle``
=> Proper access to MC particle

PWGCF/Correlations/macros/PIDBFDptDpt/AddTaskGeneralBF.C
added one centrality group option
=> added one centrality group option

PWGHF/vertexingHF/AliAnalysisTaskSED0Mass.h
fixing issues spotted by @arossi81
=> Fixing ClassDef and data member issue

PWGMM/UE/CMakeLists.txt, PWGMM/UE/PWGMMueLinkDef.h, PWGMM/UE/UeMultDep/AddTaskUeMultDep.C, PWGMM/UE/UeMultDep/AliAnalysisTaskUeMultDep.cxx, PWGMM/UE/UeMultDep/AliAnalysisTaskUeMultDep.h
New Analysis task to study leading hadron angular correlation for different multiplicity classes
=> New Analysis task to study leading hadron angular correlation

PWGPP/TPC/AliTPCcalibResidualPID.cxx
=> Fix bug: ProcessEvent breaks if fAnaUtils present

PWGHF/vertexingHF/AliAnalysisTaskSELc2V0bachelorTMVAApp.cxx, PWGHF/vertexingHF/AliAnalysisTaskSELc2V0bachelorTMVAApp.h, PWGHF/vertexingHF/macros/AddTaskLc2V0bachelor_TMVAApp.C
The existing variable was counting in [-1, 1], now we have also
the info in [-999, 999].
Additionally, some formatting was changed, and some compilation
warnings were removed (some are left on unused variables, kept there
in case we will ever use them).
The AddTask was fixed for the output slot n. 7
=> Adding information (and histograms) on number of tracklets

PWGGA/GammaConv/macros/AddTask_GammaCalo_pp.C
=> PWGGA/GammaConv Seperating PHOS and EDC in same TrainConfig

PWG/FLOW/Tasks/AliAnalysisTaskCMEMC.cxx
=> bug fix and fill Multiplicity

PWGCF/FEMTOSCOPY/macros/Train/GK/KPKD/pp/ConfigFemtoAnalysis.C
ConfigFemtoAnalysis file for Kp and KD CF
=> New ConfigFemtoAnalysis file for Kp and KD CF

PWGHF/treeHF/AliAnalysisTaskSEHFTreeCreator.cxx, PWGHF/treeHF/AliHFTreeHandler.cxx, PWGHF/treeHF/AliHFTreeHandler.h, PWGHF/treeHF/AliHFTreeHandlerBplustoD0pi.cxx, PWGHF/treeHF/AliHFTreeHandlerBplustoD0pi.h, PWGHF/treeHF/AliHFTreeHandlerD0toKpi.cxx, PWGHF/treeHF/AliHFTreeHandlerD0toKpi.h, PWGHF/treeHF/AliHFTreeHandlerDplustoKpipi.cxx, PWGHF/treeHF/AliHFTreeHandlerDplustoKpipi.h, PWGHF/treeHF/AliHFTreeHandlerDstartoKpipi.cxx, PWGHF/treeHF/AliHFTreeHandlerDstartoKpipi.h, PWGHF/treeHF/AliHFTreeHandlerDstoKKpi.cxx, PWGHF/treeHF/AliHFTreeHandlerDstoKKpi.h, PWGHF/treeHF/AliHFTreeHandlerLc2V0bachelor.cxx, PWGHF/treeHF/AliHFTreeHandlerLc2V0bachelor.h, PWGHF/treeHF/AliHFTreeHandlerLctopKpi.cxx, PWGHF/treeHF/AliHFTreeHandlerLctopKpi.h
- restore flat tree structure for HF particles trees (not jet)
- fix rapidity of Lc (using correct mass)
=> Modify structure of trees for HF particles to flat trees

PWGDQ/dielectron/core/AliDielectronMC.cxx, PWGDQ/dielectron/core/AliDielectronSignalMC.cxx
Default should be not correlated
=> Fix for correlated heavy-flavour

PWGHF/vertexingHF/AliAnalysisTaskSELc2V0bachelorTMVAApp.cxx
And a minor fix (float to int in number of bins of a histogram)
=> Creating BDT reader only when needed.

PWGDQ/dielectron/LMEE/AliAnalysisTaskBeauty.cxx, PWGDQ/dielectron/LMEE/AliAnalysisTaskCharm.cxx, PWGDQ/dielectron/LMEE/AliAnalysisTaskJpsi.cxx, PWGDQ/dielectron/LMEE/AliAnalysisTaskJpsi.h, PWGDQ/dielectron/LMEE/AliCocktailSmearing.cxx, PWGDQ/dielectron/LMEE/AliCocktailSmearing.h, PWGDQ/dielectron/LMEE/AlimakeJPsiTree.cxx, PWGDQ/dielectron/LMEE/AlimakeJPsiTree.h
Update the class according to the email
=> Update in accessing the MC information

PWGHF/hfe/AliAnalysisTaskHFEBESpectraEMC.cxx, PWGHF/hfe/AliAnalysisTaskHFEBESpectraEMC.h, PWGHF/hfe/CMakeLists.txt, PWGHF/hfe/PWGHFhfeLinkDef.h, PWGHF/hfe/macros/AddTaskHFEBESpectraEMC.C
New task for b->e spectra analysis using TPC+EMCal in pp collisions
=> Adding new task for b->e spectra with TPC+EMCal

PWGLF/STRANGENESS/Cascades/Run2/AliAnalysisTaskStrangenessVsMultiplicityMCRun2pPb.cxx, PWGLF/STRANGENESS/Cascades/Run2/AliAnalysisTaskStrangenessVsMultiplicityMCRun2pPb.h, PWGLF/STRANGENESS/Cascades/Run2/AliAnalysisTaskStrangenessVsMultiplicityRun2pPb.cxx, PWGLF/STRANGENESS/Cascades/Run2/AliAnalysisTaskStrangenessVsMultiplicityRun2pPb.h
- FMD info that required AOD handler has been removed from output
- Additional ITS/TOF info has been added to output
=>  Removed FMD info from output and added ITS/TOF info to output

PWGUD/UPC/AliAnalysisTaskUPCforward.cxx, PWGUD/UPC/AliAnalysisTaskUPCforward.h
IMPORTANT: due to possible problems with the integration of the previous (already closed without merging) pull request, my previous fork of AliPhysics has been DELETED. This is a fresh fork. Pulled from it to reset my local repository, rebased against master and pushed the few mods. The code had been checked.
SUMMARY: ZDC checks have been implemented both for timing and spectra. Removed faulty good runs for the ZDC.
=> PWGUD/UPC: ZDC fix: 2 runs eliminated + new checks

PWGLF/RESONANCES/PostProcessing/Xi1530/AliAnalysisTaskXi1530.cxx
Issue: The tight cut was applied always.
Additionally, some of QA plots are added(not applied)
=> Fix bug: PID cut was tightly applied

PWGPP/TOF/AliAnalysisTaskTOFqaID.cxx
Fixed bin counting for histo labelling
=> Fix to TOF QA 

PWG/FLOW/Tasks/AliAnalysisTaskCMEMC.cxx
bug fix in AliAnalysisTaskCMEMC.cxx (2nd)
=> bug fix in AliAnalysisTaskCMEMC.cxx (2nd)

PWGLF/RESONANCES/PostProcessing/Xi1530/AddTaskXi1530.C, PWGLF/RESONANCES/PostProcessing/Xi1530/AliAnalysisTaskXi1530.cxx
Add several QA Histograms to check the status of cut variations
=> Add QA plots to check Systematics / Fix bug

PWGJE/EMCALJetTasks/Tracks/AliAnalysisTaskEmcalJetEnergySpectrum.cxx, PWGJE/EMCALJetTasks/Tracks/AliAnalysisTaskEmcalJetEnergySpectrum.h
In particular needed when filling spectra with downscale weight
=> Make sumw2 optional

PWG/EMCAL/EMCALtrigger/AliEmcalTriggerSimQATask.cxx
delta (eta,phi) vs (eta,phi)
patch (energy,adc) vs (row,col)
=> Adds more QA plots

PWGLF/RESONANCES/PostProcessing/Xi1530/AliAnalysisTaskXi1530.cxx, PWGLF/RESONANCES/PostProcessing/Xi1530/AliAnalysisTaskXi1530.h
Remove duplicated cascade QA Histograms.
Add Xi1530pion PVDCA QA histogram
Adjust PVcut
=> Remove duplicated QA Histos

PWGGA/EMCALTasks/AliAnalysisTaskEMCALPhotonIsolation.cxx, PWGGA/EMCALTasks/AliAnalysisTaskEMCALPhotonIsolation.h
In fact, muting three histograms (which are never produced together).
=> Muting one histogram and lightening the binning of some others

PWGHF/treeHF/AliAnalysisTaskSEHFTreeCreator.cxx, PWGHF/treeHF/AliAnalysisTaskSEHFTreeCreator.h, PWGHF/treeHF/AliJetTreeHandler.cxx, PWGHF/treeHF/AliJetTreeHandler.h, PWGHF/treeHF/macros/AddTaskHFTreeCreator.C
After discussions with @ginnocen, re-organize a bit the jet tree structure. 
@fgrosa @lvermunt
=> treeHF/JetTree: Implement separate flat trees for jets and constituents

PWG/FLOW/Tasks/AliAnalysisTaskTwoMultiCorrelations.cxx, PWG/FLOW/Tasks/AliAnalysisTaskTwoMultiCorrelations.h
* Add selection on the charge of the tracks.
* Add Bool_t to select if a cut on a variable is applied or not for every cut in the track selection.
=> [PWGCF] Modify gestion of the track selection.

PWG/DevNanoAOD/AddTaskNanoAODFilter.C, PWG/DevNanoAOD/README, PWG/DevNanoAOD/tutorial/README, PWG/DevNanoAOD/tutorial/filterESD_Tracks.C
number of events in one tutorial
README
=> removing includes from AddTask

PWGUD/UPC/AliAnalysisTaskUPCforward.cxx, PWGUD/UPC/AliAnalysisTaskUPCforward.h
Added further checks for the separation main-satellites collisions in UPC. 
IMPORTANT: the code has been tested, and an abort due to too large of a binning has already been solved on local.
=> PWGUD/UPC: Added further checks for the timing.

PWG/DevNanoAOD/AliAnalysisNanoAODCuts.cxx, PWG/DevNanoAOD/AliAnalysisTaskNanoAODFilter.cxx, PWG/DevNanoAOD/AliAnalysisTaskNanoAODFilter.h, PWG/DevNanoAOD/AliNanoAODReplicator.cxx, PWG/DevNanoAOD/AliNanoAODReplicator.h, PWG/DevNanoAOD/runGridESE.C, PWG/DevNanoAOD/runLocalCorrelations.C, PWG/DevNanoAOD/runLocalESE.C, PWG/DevNanoAOD/tutorial/filterAOD_PID.C, PWG/DevNanoAOD/tutorial/filterAOD_Tracks.C, PWG/DevNanoAOD/tutorial/filterAOD_V0s.C, PWG/DevNanoAOD/tutorial/filterESD_PID.C, PWG/DevNanoAOD/tutorial/filterESD_Tracks.C, PWG/DevNanoAOD/tutorial/filterESD_V0s.C
WARNING some change in setter names in the task
=> streamlining of replicator access

PWGLF/NUCLEX/CMakeLists.txt, PWGLF/NUCLEX/Nuclei/AbsorptionRatios/AliAnalysisTaskLightN.cxx, PWGLF/NUCLEX/Nuclei/AbsorptionRatios/AliAnalysisTaskLightN.h, PWGLF/NUCLEX/Nuclei/AbsorptionRatios/AliLightNAnalysis.cxx, PWGLF/NUCLEX/Nuclei/AbsorptionRatios/AliLightNAnalysis.h, PWGLF/NUCLEX/Nuclei/AbsorptionRatios/AliLightNBasePart.cxx, PWGLF/NUCLEX/Nuclei/AbsorptionRatios/AliLightNBasePart.h, PWGLF/NUCLEX/Nuclei/AbsorptionRatios/AliLightNEvent.cxx, PWGLF/NUCLEX/Nuclei/AbsorptionRatios/AliLightNEvent.h, PWGLF/NUCLEX/Nuclei/AbsorptionRatios/AliLightNEventCuts.cxx, PWGLF/NUCLEX/Nuclei/AbsorptionRatios/AliLightNEventCuts.h, PWGLF/NUCLEX/Nuclei/AbsorptionRatios/AliLightNEventHist.cxx, PWGLF/NUCLEX/Nuclei/AbsorptionRatios/AliLightNEventHist.h, PWGLF/NUCLEX/Nuclei/AbsorptionRatios/AliLightNTrack.cxx, PWGLF/NUCLEX/Nuclei/AbsorptionRatios/AliLightNTrack.h, PWGLF/NUCLEX/Nuclei/AbsorptionRatios/AliLightNTrackCuts.cxx, PWGLF/NUCLEX/Nuclei/AbsorptionRatios/AliLightNTrackCuts.h, PWGLF/NUCLEX/Nuclei/AbsorptionRatios/AliLightNTrackHist.cxx, PWGLF/NUCLEX/Nuclei/AbsorptionRatios/AliLightNTrackHist.h, PWGLF/NUCLEX/Nuclei/AbsorptionRatios/AliLightNTrackMCHist.cxx, PWGLF/NUCLEX/Nuclei/AbsorptionRatios/AliLightNTrackMCHist.h, PWGLF/NUCLEX/Nuclei/AbsorptionRatios/macros/AddTaskLightN.C, PWGLF/NUCLEX/PWGLFnuclexLinkDef.h
Add task for antiproton and antideuteron analysis in p-Pb
=> Add AbsorptionRatio classes

PWGHF/hfe/AliAnalysisTaskHFEBESpectraEMC.cxx, PWGHF/hfe/AliAnalysisTaskHFEBESpectraEMC.h
Adding DCA histograms for inclusive electrons, hadrons, ULS and LS electrons
=> Adding DCA histograms

PWGJE/EMCALJetTasks/Tracks/AliAnalysisTaskEmcalJetEnergyScale.cxx, PWGJE/EMCALJetTasks/Tracks/AliAnalysisTaskEmcalJetEnergyScale.h, PWGJE/EMCALJetTasks/Tracks/AliAnalysisTaskEmcalJetEnergySpectrum.cxx, PWGJE/EMCALJetTasks/Tracks/AliAnalysisTaskEmcalJetEnergySpectrum.h
Fill THnSparse only when selected (for
debugging), otherwise use TH1/2 for spectrum,
response matrix, energy scale and resolution.
Needed for ultra high pt studies
=> Create lightweight output for normal running

PWGUD/UPC/AliAnalysisTaskUPCforward.cxx, PWGUD/UPC/AliAnalysisTaskUPCforward.h, PWGUD/UPC/AliAnalysisTaskUPCforwardMC.cxx, PWGUD/UPC/AliAnalysisTaskUPCforwardMC.h
Added analysis in 10 rapidity bins for both data and MC. Fixed some nasty bugs in the MC code, that were not so easy to find... Eliminated unused code chunks, that had been just commented out.
IMPORTANT: the code has been tested. Processes were killed on local due to bugs while instantiating the histograms. Now this has been fixed.
=> PWGUD/UPC: Added analysis in 10 rapidity bins. Fixed bugs.

PWGLF/NUCLEX/Exotica/LambdaNN/AddTask_LNNv0Bkg.C, PWGLF/NUCLEX/Exotica/LambdaNN/AliAnalysisTaskLNNv0Bkg.cxx, PWGLF/NUCLEX/Exotica/LambdaNN/AliAnalysisTaskLNNv0Bkg.h, PWGLF/NUCLEX/Exotica/LambdaNN/Getoutput.cxx, PWGLF/NUCLEX/Exotica/LambdaNN/Getoutput.h
The class can create v0s according to 3 different cases: opposite sign pairs, like sign pairs and creating a pair having the pion track rotated by pi. The class is necessary to compute the LNN background from data.
=> Revised code + new class added  

PWGDQ/dielectron/core/AliAnalysisTaskElectronEfficiency.cxx, PWGDQ/dielectron/core/AliDielectronMC.cxx, PWGDQ/dielectron/core/AliDielectronMC.h, PWGDQ/dielectron/core/AliDielectronVarManager.h
Fix for DCA_{xyz} and stack/TParticle removing
=> Fix for DCA_{xyz} + stack/TParticle removing

PWGHF/vertexingHF/AliHFSystErr.cxx
Setting the final systematic uncertainties values for the Ds pPb 5.02 TeV 0100 analysis
=> Update to the final values by A. Gal

PWGCF/Correlations/JCORRAN/Pro/AliAnalysisTaskRidge.cxx, PWGCF/Correlations/JCORRAN/Pro/AliAnalysisTaskRidge.h, PWGCF/Correlations/macros/jcorran/AddTaskRidge.C
Add 3D efficiency correction method
=> Add 3D efficiency correction

PWGDQ/dielectron/macrosLMEE/AddTask_rbailhac_lowmass.C
Fix to run more than one task at the same time
=> Fix to run one than one task at the same time

PWGCF/FLOW/GF/AliAnalysisTaskUniFlow.cxx, PWGCF/FLOW/GF/AliAnalysisTaskUniFlow.h
* fVector[species] are sorted by pt
* used for CPU optimalisation: skipping "empty" bins
=> Selected candidates pt sorting + CPU optimalisation

PWG/DevNanoAOD/AliAnalysisNanoAODCuts.cxx, PWG/DevNanoAOD/AliNanoAODTrack.cxx, PWG/DevNanoAOD/AliNanoAODTrack.h, PWG/DevNanoAOD/tutorial/AliAnalysisTaskNanoSimple.cxx, PWG/DevNanoAOD/tutorial/filterAOD_Tracks.C
HasTOFPID
ITS Cluster Map
Charge
adding storage of TOF BC ID
=> adding flags in nano AOD for

PWGHF/treeHF/AliAnalysisTaskSEHFTreeCreator.cxx, PWGHF/treeHF/AliAnalysisTaskSEHFTreeCreator.h, PWGHF/treeHF/AliJetTreeHandler.cxx, PWGHF/treeHF/AliJetTreeHandler.h
=> treeHF/JetTree: Add run number to trees

PWGHF/vertexingHF/AliAnalysisTaskSEDvsMultiplicity.cxx, PWGHF/vertexingHF/AliAnalysisTaskSEDvsMultiplicity.h, PWGHF/vertexingHF/macros/AddTaskDvsMultiplicity.C, PWGLF/SPECTRA/ChargedHadrons/dNdPt/macros/AddTaskDCArStudy.C
Weight Functions added for the Ntracklets distribution corrections of pp@13TeV data in 2016, 17, 18
=> Ntracklets weight files for pp@13TeV 2016,17,18

PWGUD/UPC/AliAnalysisTaskCTrue.cxx, PWGUD/UPC/AliAnalysisTaskCTrue.h
The merging between the original TTree producing analysis task and the offline macros is almost complete. It has now reached the stage where the two versions have to differ greatly due to the different methodology... I reckon that by the end of the week the whole code will be completely merged and fully functioning online.
I have now added the histograms for the VETO counting and I am about to fill them so as to finally compute the required efficiencies for the CTRUE analysis.
IMPORTANT: this has been tested locally.
=> PWGUD/UPC: Merging almost complete. Adding histos for veto counting.

PWGDQ/dielectron/core/AliDielectronVarManager.h
Check if ZDC event plane task running before trying to fill
=> Remove unnecessary printouts: 

PWG/EMCAL/EMCALtasks/AliAnalysisTaskEmcalTriggerSelection.cxx
- LHC18g2 (PYTHIA8 JJ TRD test, anchored to LHC17o)
- LHC19a1x (PYTHIA8 JJ, anchored to LHC16x)
=> Adding support for new jet-jet Monte-Carlos

PWGLF/RESONANCES/PostProcessing/Xi1530/AliAnalysisTaskXi1530.cxx
=> trigeffi correction for INELgt0

PWGLF/SPECTRA/MultEvShape/AliMESeventInfo.cxx, PWGLF/SPECTRA/MultEvShape/AliMESpidTask.cxx, PWGLF/SPECTRA/MultEvShape/AliMEStender.cxx
=> Changed the directivity definition

PWGHF/vertexingHF/AliAnalysisTaskSEDplus.cxx, PWGHF/vertexingHF/AliAnalysisTaskSEDplus.h, PWGHF/vertexingHF/AliAnalysisTaskSEDs.cxx, PWGHF/vertexingHF/AliAnalysisTaskSEDs.h
Method mainly useful for offline pT weights application (only in case of few candidates, i.e. signal only)
=>  Add flag to set fine pT bins in sparses 

PWGUD/UPC/AliAnalysisTaskUPCforward.cxx, PWGUD/UPC/AliAnalysisTaskUPCforward.h
Changed the binning for all the plots involving the Phi angle of the Helicity analysis. It is a waste of resources to push further than (-4, 4)...
=> PWGUD/UPC: Changed binning for the Phi Helicity.

PWGCF/FEMTOSCOPY/macros/Train/JZ/ProtonLambda/ConfigAvgsepAnalysis.C
=> AliFemto adding new Config

PWGHF/vertexingHF/AliAnalysisTaskSEXic2eleXifromAODtracks.cxx
MassXi, MassLambda, CosPointingAngleXi,  CosPointingAngleV0
=> Add new 4 branches

PWGHF/hfe/AliAnalysisTaskHFEBESpectraEMC.cxx, PWGHF/hfe/AliAnalysisTaskHFEBESpectraEMC.h, PWGHF/hfe/macros/AddTaskHFEBESpectraEMC.C
Adding reconstruction efficiency, MC DCA templates, Eta cut
=> Adding MC DCA templates, setters and eta cut

PWGCF/Correlations/DPhi/AliAnalysisTaskPIDBFDptDpt.cxx, PWGCF/Correlations/DPhi/AliAnalysisTaskPIDBFDptDpt.h, PWGCF/Correlations/macros/PIDBFDptDpt/AddTaskPIDBFDptDpt.C
1. added cluster sharing QA histograms
2. added a cluster sharing QA function
3. fixed a couple of ROOT6 associated bugs
=> Added cluster sharing QA

PWGHF/treeHF/AliJetTreeHandler.cxx
(trivial update to allow easier merging of event tree with jet tree)
=> treeHF/JetTree: uniformize evt variable names

PWGHF/treeHF/AliAnalysisTaskSEHFTreeCreator.cxx, PWGHF/vertexingHF/AliCFTaskVertexingHF.cxx, PWGHF/vertexingHF/AliCFTaskVertexingHF.h
adding protection AOD/dAOD mismatch in the correction framework task
small fixes in the TreeCreator
=> adding protection AOD/dAOD mismatch in the correction framework task

PWGCF/FEMTOSCOPY/macros/Train/KK_Run2_Apr/pipi_13TeV_dist_03/AddTaskFemtoKchHBT1090.C, PWGCF/FEMTOSCOPY/macros/Train/KK_Run2_Apr/pipi_13TeV_dist_03/ConfigFemtoAnalysis.C, PWGCF/FEMTOSCOPY/macros/Train/KK_Run2_Apr/pipi_13TeV_dist_07/AddTaskFemtoKchHBT1090.C, PWGCF/FEMTOSCOPY/macros/Train/KK_Run2_Apr/pipi_13TeV_dist_07/ConfigFemtoAnalysis.C
=> For Ludmila PWGCF/FEMTOSCOPY/macros/Train/KK_Run2_Apr

PWGLF/SPECTRA/ChargedHadrons/dNdPt/AliAnalysisTaskPtResStudy.cxx
=> bug fix in initalizer list

PWGDQ/dielectron/core/AliDielectronVarManager.h
Fix the definition of DCA_{xyz}
=> Fix the definition of DCA_{xyz}

PWGUD/UPC/AliAnalysisTaskUPCforward.cxx, PWGUD/UPC/AliAnalysisTaskUPCforward.h, PWGUD/UPC/AliAnalysisTaskUPCforwardMC.cxx, PWGUD/UPC/AliAnalysisTaskUPCforwardMC.h
Added heat map for the helicity analysis.
This would show CosThetaHelicityFrame VS PhiHelicityFrame.
=> PWGUD/UPC: Added heat map helicity analysis.

PWGLF/SPECTRA/CMakeLists.txt, PWGLF/SPECTRA/ChargedHadrons/dNdPt/AliAnalysisTaskEffContStudy.cxx, PWGLF/SPECTRA/ChargedHadrons/dNdPt/AliAnalysisTaskEffContStudy.h, PWGLF/SPECTRA/ChargedHadrons/dNdPt/AliAnalysisTaskMKBase.cxx, PWGLF/SPECTRA/ChargedHadrons/dNdPt/AliAnalysisTaskMKBase.h, PWGLF/SPECTRA/ChargedHadrons/dNdPt/AlidNdPtTools.cxx, PWGLF/SPECTRA/ChargedHadrons/dNdPt/AlidNdPtTools.h, PWGLF/SPECTRA/ChargedHadrons/dNdPt/macros/AddTaskEffContStudy.C, PWGLF/SPECTRA/PWGLFspectraLinkDef.h
test implementation of efficiency/contamination rescaling
=>  test implementation of efficiency/contamination rescaling 

PWGGA/EMCALTasks/AliAnalysisTaskGammaHadron.cxx
Optimize Pi0Cand bins
Fixes a part of pos-swap bkg method
Fixes a small eta phi error
=> Pos Swap Fix

PWGHF/hfe/AliAnalysisTaskHFEBESpectraEMC.cxx, PWGHF/hfe/AliAnalysisTaskHFEBESpectraEMC.h
Adding THnsparse for MC DCA templates with D and B pT weights applied.
=> Adding MC DCA templates with weight

PWGLF/RESONANCES/PostProcessing/Xi1530/AliAnalysisTaskXi1530.cxx
Add correction factor for event loss correction: INELg0 && |Vz|<10
=> Add correction factor

PWGLF/RESONANCES/PostProcessing/Xi1530/AliAnalysisTaskXi1530.cxx
Add full options to investigate normalisation factors
=> Full selection for the MC Normalisation

PWGLF/RESONANCES/PostProcessing/Xi1530/macros_pp13TeV/DrawXi1530.C, PWGLF/RESONANCES/PostProcessing/Xi1530/macros_pp13TeV/DrawXi1530forXi1820.C, PWGLF/RESONANCES/PostProcessing/Xi1530/macros_pp13TeV/FitParticle.C, PWGLF/RESONANCES/PostProcessing/Xi1530/macros_pp13TeV/PlotXi1530.C, PWGLF/RESONANCES/PostProcessing/Xi1530/macros_pp13TeV/Xi1530ExtractYieldMean.C, PWGLF/RESONANCES/PostProcessing/Xi1530/macros_pp13TeV/Xi1530PlotSystematics.C, PWGLF/RESONANCES/PostProcessing/Xi1530/macros_pp13TeV/YieldMean.C, PWGLF/RESONANCES/PostProcessing/Xi1530/macros_pp13TeV/grid.py
Fisr commit.
It's definitely needed to update!
=> First commit of postprocessing macro

PWGLF/RESONANCES/PostProcessing/Xi1530/macros_pp13TeV/README.md, PWGLF/RESONANCES/PostProcessing/Xi1530/macros_pp13TeV/extract.jdl, PWGLF/RESONANCES/PostProcessing/Xi1530/macros_pp13TeV/extract.sh
=> Add grid macro update readme file

PWGHF/hfe/AliAnalysisTaskHFEBESpectraEMC.cxx, PWGHF/hfe/AliAnalysisTaskHFEBESpectraEMC.h, PWGHF/hfe/macros/AddTaskHFEBESpectraEMC.C
=> Fix reading root files from grid

PWGUD/UPC/AliAnalysisTaskCTrue.cxx, PWGUD/UPC/AliAnalysisTaskCTrue.h
Added the first steps for the OCDB implementation. In the future it should be possible to retrieve at runtime level the position in the L0 bit string of each trigger. It is still commented out as of yet. I still have to understand exactly how to work it out, but it is a huge step compared to before...
=> PWGUD/UPC: Added first steps towards OCDB implementation. Still commented though.

PWGHF/vertexingHF/AliAnalysisTaskSEXicZero2XiPifromAODtracks.cxx, PWGHF/vertexingHF/AliAnalysisTaskSEXicZero2XiPifromAODtracks.h, PWGHF/vertexingHF/AliRDHFCutsXicZerotoXiPifromAODtracks.cxx, PWGHF/vertexingHF/AliRDHFCutsXicZerotoXiPifromAODtracks.h, PWGHF/vertexingHF/macros/AddTaskXicZero2XiPifromAODtracks.C
Add option to analysis OmegacZero, add function CosThetaStar and add Kaon PID in cascade. Release cuts before filling the tree.
=> Add option to analysis OmegacZero

PWGHF/vertexingHF/macros/AddTaskImproveITS.C
Improver task output stored in a dedicated file
=> AddTaskImproveITS.C modified

PWGGA/EMCALTasks/AliAnalysisTaskGammaHadron.cxx
Makes the Cluster Min energy apply in more of the task
Enables run-time to be improved with tighter cuts
=> Makes the Cluster Min energy apply in more of the task

PWGHF/vertexingHF/macros/AddTaskXicZero2XiPifromAODtracks.C
Fix a bug for path of input cut object.
=> Fix a bug for path of input cut object.

PWGLF/NUCLEX/Hypernuclei/Hyp2Body/AliAnalysisTaskHyperTriton2He3piML.cxx, PWGLF/NUCLEX/Hypernuclei/Hyp2Body/AliAnalysisTaskHyperTriton2He3piML.h
=> Add tracklet matching for hypertriton

PWGDQ/dielectron/macrosLMEE/AddTask_jjung_efficiency.C
LMEE change of personal AddTask
=> LMEE: personal Addtask: allow different binning of single efficiency

PWG/DevNanoAOD/AliNanoAODTrack.cxx, PWG/DevNanoAOD/AliNanoAODTrack.h, PWG/DevNanoAOD/AliNanoAODTrackMapping.cxx, PWG/DevNanoAOD/AliNanoAODTrackMapping.h, PWG/DevNanoAOD/validation/filter.C, PWG/DevNanoAOD/validation/validateNano.C, PWGCF/Correlations/DPhi/AliAnalysisTaskMinijet.cxx, PWGCF/Correlations/DPhi/CMakeLists.txt
plus small change in minijet task
=> Introducing int variables for nano track

PWGCF/FEMTOSCOPY/FemtoDream/AliAnalysisTaskSigma0Femto.cxx, PWGCF/FEMTOSCOPY/macros/AddTaskSigma0Femto.C
o and revert the order of execution in the AnalysisTask
=> Introducing random cut variations

PWGCF/FLOW/GF/AliAnalysisTaskUniFlow.cxx, PWGCF/FLOW/GF/AliAnalysisTaskUniFlow.h, PWGCF/FLOW/GF/AliUniFlowCorrTask.cxx, PWGCF/FLOW/GF/AliUniFlowCorrTask.h, PWGCF/FLOW/GF/CMakeLists.txt, PWGCF/FLOW/GF/PWGCFFLOWGFLinkDef.h
- bug fix for CENT estimator
- AniAnalysisUniFlow::CorrTask-> AliUniFlowCorrTask standalone class
- IsWithinPOIs()
- GetSpeciesLabel/Name overloaded
=> Task modification

PWGHF/vertexingHF/charmFlow/AliAnalysisTaskSECharmHadronvn.cxx, PWGHF/vertexingHF/charmFlow/AliHFQnVectorHandler.cxx, PWGHF/vertexingHF/charmFlow/AliHFQnVectorHandler.h
If TPC calibration factors found in the input file applied, otherwise not applied (but TPC Q-vector computed anyway)
=> Add possibility to calibrate TPC Q-vector

PWGCF/FEMTOSCOPY/macros/Train/KK_7TeV_Apr/pipi_13TeV_dist_03/AddTaskFemtoKchHBT1090.C, PWGCF/FEMTOSCOPY/macros/Train/KK_7TeV_Apr/pipi_13TeV_dist_03/ConfigFemtoAnalysis.C, PWGCF/FEMTOSCOPY/macros/Train/KK_7TeV_Apr/pipi_13TeV_dist_07/AddTaskFemtoKchHBT1090.C, PWGCF/FEMTOSCOPY/macros/Train/KK_7TeV_Apr/pipi_13TeV_dist_07/ConfigFemtoAnalysis.C
=> Train macros and AliFemtoSphericityEventCutKK.cxx update

PWGGA/GammaConv/AliAnalysisTaskGammaConvDalitzV1.cxx, PWGGA/GammaConv/AliAnalysisTaskGammaConvDalitzV1.h, PWGGA/GammaConv/macros/AddTask_GammaConvDalitzV1_pp.C, PWGGA/GammaConvBase/AliDalitzData.h
Dear AliPhysics,
On the next commit I work on the psi pair cut, trying to improve my statistics, I use this reference [link](https://twiki.cern.ch/twiki/bin/viewauth/ALICE/AliDPGtoolsTrackProperties) to understand better the constrained parameter of ESD and find a way to implement on AOD.
Regards
Edgar
=> Improves on PsiPairCuts, and new train to work

PWGHF/treeHF/AliHFTreeHandler.cxx, PWGHF/treeHF/AliHFTreeHandler.h, PWGHF/vertexingHF/AliAODPidHF.cxx, PWGHF/vertexingHF/AliAODPidHF.h, PWGHF/vertexingHF/AliAnalysisTaskSEHFSystPID.cxx, PWGHF/vertexingHF/AliAnalysisTaskSEHFSystPID.h, PWGHF/vertexingHF/macros/EstimateSingleTrackPIDsyst.C
1) implement NsigmaTPC corrections vs eta 
2) replace std::array with std::vectors to keep compatibility with root5
3) update mactro to add possibility to project vs p and to select eta interval
=> Update code for PID study with tagged samples of p/K/pi

PWGCF/FEMTOSCOPY/macros/AddTaskFemtoDreamPhi.C
=> suffix und addon

PWGCF/FLOW/GF/AliGFWFlowContainer.cxx
Added sign checks in sqrt's in AliGFWFlowContainer, fixed pT-rebinning (got broken in one of the commits)
=> Maintenance on AliGFWFlowContainers

PWGCF/FEMTOSCOPY/FemtoDream/AliAnalysisTaskAODSigma0Femto.cxx, PWGCF/FEMTOSCOPY/FemtoDream/AliAnalysisTaskAODSigma0Femto.h, PWGCF/FEMTOSCOPY/FemtoDream/AliAnalysisTaskNanoAODSigma0Femto.cxx, PWGCF/FEMTOSCOPY/FemtoDream/AliAnalysisTaskNanoAODSigma0Femto.h, PWGCF/FEMTOSCOPY/FemtoDream/AliFemtoDreamv0.cxx
=> Randomly select one Sigma0 for the AODs

PWGJE/EMCALJetTasks/UserTasks/AliAnalysisTaskJetCoreEmcal.cxx, PWGJE/EMCALJetTasks/UserTasks/AliAnalysisTaskJetCoreEmcal.h, PWGJE/EMCALJetTasks/macros/AddTaskJetCoreEmcal.C
Detector level to particle level jet matching implemented, needed for pp analysis
=> pp jet matching implemented

PWGHF/jetsHF/AliAnalysisTaskDJetCorrelations.cxx, PWGHF/jetsHF/AliAnalysisTaskDJetCorrelations.h, PWGHF/jetsHF/AliAnalysisTaskDJetCorrelationsQA.cxx, PWGHF/jetsHF/AliAnalysisTaskDJetCorrelationsQA.h, PWGHF/jetsHF/AliAnalysisTaskDmesonsFilterCJ.cxx, PWGHF/jetsHF/AliAnalysisTaskDmesonsFilterCJ.h, PWGHF/jetsHF/macros/AddTaskDFilterCorrelations.C, PWGHF/jetsHF/macros/AddTaskDJetCorrelationsQA.C
Multiplicity and centrality distributions added. Implementation of multi-Pythia headers in MC.
=> adding mult and cent distributions + multi-pythia headers flag

PWGHF/vertexingHF/AliAnalysisTaskSEDvsMultiplicity.cxx
Fix run number ordering for some periods
=> fix run numbers

PWGCF/FEMTOSCOPY/macros/AddTaskFemtoDreamSysVar.C
@bhohlweger we should revert this when you're back from vacation ;)
=> Enable the mT histograms (hardwired)

PWGHF/treeHF/AliJetTreeHandler.cxx
=> treeHF/JetTree: Reset all jet labels (for MC matching)

PWGCF/FEMTOSCOPY/AliFemto/AliFemtoEventReaderAODKinematicsChain.h, PWGCF/FEMTOSCOPY/AliFemtoUser/AliFemtoCutMonitorPairMomRes.cxx, PWGCF/FEMTOSCOPY/AliFemtoUser/AliFemtoCutMonitorPairMomRes.h, PWGCF/FEMTOSCOPY/AliFemtoUser/CMakeLists.txt, PWGCF/FEMTOSCOPY/AliFemtoUser/PWGCFfemtoscopyUserLinkDef.h
adding two-particle momentum resolution monitor
=> AliFemto: adding momentum resolution monitor

PWGJE/EMCALJetTasks/Tracks/AliAnalysisTaskEmcalJetConstituentQA.cxx, PWGJE/EMCALJetTasks/Tracks/AliAnalysisTaskEmcalJetConstituentQA.h
- Add max cell and fraction of the max cell to the leading cluster
THnSparses
- Add Setters to switch on/off histograms when not needed
- Remove request for analysis utils as the task is based on AliEventCuts
=> Options for cluster fractional energy

PWGJE/EMCALJetTasks/Tracks/AliAnalysisTaskEmcalJetConstituentQA.cxx
- Add R=0.6
- Use direct getter for EMCAL cells
=> Small fixes in constituent QA

PWGPP/EMCAL/AliAnalysisTaskEMCALTimeCalib.cxx
look for the list with various names
=> added search for correct hist name

PWGJE/EMCALJetTasks/Tracks/AliAnalysisTaskEmcalJetConstituentQA.cxx
Fraction of the cell amplitudes all set to 1,
therefore leading cell has to be obtained by
looping over all cells and finding the max
element.
=> Fix gettting EMCAL leading cell

PWGHF/vertexingHF/AliAnalysisTaskSEDs.cxx, PWGHF/vertexingHF/AliAnalysisTaskSEDs.h, PWGHF/vertexingHF/AliHFSystErr.cxx, PWGHF/vertexingHF/AliHFSystErr.h
1) Add TH2F with massKK(Kpi) vs massKKpi (for checks on phi resonant decay mainly)
2) Add first draft of Ds systematic uncertainties in PbPb 2018 0-10% cc
=> Update Ds code

PWGCF/FEMTOSCOPY/macros/AddTaskSigma0FemtoNanoAOD.C
Ciao @a-mathis ,
this is just to make your add task working with ROOT5
Cheers,
Max
=> Use NULL to make CINT happy

PWGCF/FEMTOSCOPY/AliFemtoUser/AliFemtoCutMonitorPairMomRes.cxx, PWGCF/FEMTOSCOPY/AliFemtoUser/AliFemtoCutMonitorPairMomRes.h
fixes in momentum resolution monitor
=> AliFemto: fixes in momentum resolution

PWGCF/FEMTOSCOPY/AliFemtoUser/AliFemtoCutMonitorPairMomRes.cxx
more bug fixes in momentum resolution monitor
=> AliFemto: more bug fixes

PWGHF/jetsHF/AliAnalysisTaskDJetCorrelationsQA.cxx, PWGHF/jetsHF/AliAnalysisTaskDmesonsFilterCJ.cxx, PWGHF/jetsHF/AliAnalysisTaskDmesonsFilterCJ.h
GetTrackPrimaryGenerator method for embedding MC.
=> changes for embedding MC

PWGGA/GammaConv/macros/AddTask_GammaConvNeutralMesonPiPlPiMiNeutralMeson_CaloMode_pp.C, PWGGA/GammaConv/macros/AddTask_GammaConvNeutralMesonPiPlPiMiNeutralMeson_ConvMode_pp.C, PWGGA/GammaConv/macros/AddTask_GammaConvNeutralMesonPiPlPiMiNeutralMeson_MixedMode_pp.C, PWGGA/GammaConvBase/AliConvEventCuts.cxx, PWGGA/GammaConvBase/AliConvEventCuts.h, PWGGA/GammaConvBase/AliV0ReaderV1.cxx
trigger mimicking for heavy meson task & preparations for running over LHC18l6b1 + c1
=> PWGGA/GammaConv: trigger mimicking for heavy meson task & more

PWGCF/Correlations/DPhi/AliAnalysisTaskDiHadCorrelHighPt.cxx
add a line to be sure there are no crashes
=> A change in AliAnalysisTaskDiHadCorrelHighPt.cxx

PWG/EMCAL/EMCALtasks/AliEmcalTrackingQATask.cxx, PWG/EMCAL/EMCALtasks/AliEmcalTrackingQATask.h
Add bins(<250 GeV - 5 GeV width, < 350 GeV - 10 GeV width)
in the pt-binning in order to address the tracking performance
in the ultra high pt region.
=> Increase pt-range of the tracking QA task up to 350 GeV

PWGGA/GammaConv/AliAnalysisTaskNeutralMesonToPiPlPiMiNeutralMeson.cxx, PWGGA/GammaConv/macros/AddTask_GammaConvNeutralMesonPiPlPiMiNeutralMeson_CaloMode_pp.C, PWGGA/GammaConv/macros/AddTask_GammaConvNeutralMesonPiPlPiMiNeutralMeson_MixedMode_pp.C, PWGGA/GammaConvBase/AliConvEventCuts.cxx
- fixed track matching of heavy meson task which wasn't applied correctly
- added weights for LHC18l6b1+c1
=> PWGGA/GammaConv: fixed heavy track matching & more

PWGDQ/dielectron/core/AliDielectronTrackCuts.cxx, PWGDQ/dielectron/core/AliDielectronTrackCuts.h, PWGDQ/reducedTree/AliReducedAnalysisJpsi2ee.cxx, PWGDQ/reducedTree/AliReducedAnalysisJpsi2ee.h, PWGDQ/reducedTree/AliReducedAnalysisSingleTrack.cxx, PWGDQ/reducedTree/AliReducedAnalysisSingleTrack.h
- AliReducedAnalysisSingleTrack: logic fixes and removed redundant code
- AliReducedAnalysisJpsi2ee: added possibility for cluster cuts and cluster-track matching
- AliDielectronTrackCuts: added possibility to cut on kTRDupdate flag
=> PWGDQ: updates for EMCal E/p analysis and cluster-track matching 

PWGHF/vertexingHF/AliHFSystErr.cxx
Modify systematic uncertainties from cut variation of Ds vs. mult in pPb to match those evaluated for the MB measurement @cbedda
=> Update Ds syst unc for cut variation in pPb vs mult

PWGMM/UE/UeSpectra/AliAnalysisTaskPPvsUE.cxx, PWGMM/UE/UeSpectra/AliAnalysisTaskPPvsUE.h, PWGMM/UE/UeSpectra/macros/AddTaskPPvsUE.C
First commit ever of code for spectra of charged particles versus Underlying Event activity classifier
=> Committing UE spectra code

PWGHF/vertexingHF/AliAnalysisTaskSEDvsMultiplicity.cxx
=> fix 18i run range

PWGCF/FEMTOSCOPY/AliFemtoUser/AliFemtoSphericityEventCutKK1.cxx, PWGCF/FEMTOSCOPY/AliFemtoUser/AliFemtoSphericityEventCutKK1.h, PWGCF/FEMTOSCOPY/AliFemtoUser/CMakeLists.txt, PWGCF/FEMTOSCOPY/AliFemtoUser/PWGCFfemtoscopyUserLinkDef.h
=> Update AliFemtoSphericityEventCutKK1 class for Ludmila 3may2019

PWGCF/FLOW/Forward/AliForwardFlowRun2Task.cxx, PWGCF/FLOW/Forward/AliForwardFlowUtil.cxx, PWGCF/FLOW/Forward/AliForwardGenericFramework.cxx, PWGCF/FLOW/Forward/AliForwardNUATask.cxx, PWGCF/FLOW/Forward/AliForwardQCumulantRun2.cxx, PWGCF/FLOW/Forward/AliForwardQCumulantRun2.h, PWGCF/FLOW/Forward/AliForwardSecondariesTask.cxx, PWGCF/FLOW/Forward/AliForwardSettings.cxx, PWGCF/FLOW/Forward/AliForwardSettings.h, PWGCF/FLOW/Forward/AliForwardTaskValidation.cxx, PWGCF/FLOW/Forward/AliForwardTaskValidation.h, PWGCF/FLOW/Forward/macros/AddTaskForwardFlowRun2.C, PWGCF/FLOW/Forward/macros/AddTaskForwardNUA.C, PWGCF/FLOW/Forward/macros/AddTaskForwardSecondaries.C, PWGCF/FLOW/Forward/macros/AddTaskForwardValidation.C
=> Forwardflow

PWGCF/FEMTOSCOPY/FemtoDream/AliFemtoDreamAnalysis.cxx, PWGCF/FEMTOSCOPY/FemtoDream/AliFemtoDreamEvent.cxx, PWGCF/FEMTOSCOPY/FemtoDream/AliFemtoDreamEvent.h, PWGCF/FEMTOSCOPY/FemtoDream/AliFemtoDreamEventCuts.h, PWGCF/FEMTOSCOPY/macros/AddTaskForLudmilla.C
Adapts changes to allow to reproduce the pp 7 TeV analysis from Gorian + Ludmilla.
=> Preparations for the opposite charged pion analysis

PWGCF/FLOW/GF/AliGFWFlowContainer.cxx, PWGCF/FLOW/GF/AliGFWFlowContainer.h
Single subsample, jackknife, proper bootstrapping
=> Adding different statistical methods to the AliGFWFlowContainer

PWG/DevNanoAOD/AliAnalysisTaskNanoAODFilter.cxx, PWG/DevNanoAOD/AliNanoAODTrack.cxx, PWG/DevNanoAOD/AliNanoAODTrack.h, PWG/DevNanoAOD/AliNanoAODTrackMapping.cxx, PWG/DevNanoAOD/AliNanoAODTrackMapping.h, PWG/DevNanoAOD/tutorial/AliAnalysisTaskNanoSimple.cxx, PWG/DevNanoAOD/tutorial/filterAOD_PIDResponse.C, PWG/DevNanoAOD/tutorial/runOnNano_PIDResponse.C, PWG/DevNanoAOD/validation/AliAnalysisTaskNanoValidator.cxx, PWG/DevNanoAOD/validation/filter.C
adding support for running PID response on nano (TPC works, not yet TOF)
=> adding GetStatus in nano aod track

PWGGA/EMCALTasks/AliAnalysisTaskGammaHadron.cxx, PWGGA/EMCALTasks/AliAnalysisTaskGammaHadron.h
Adds logarithmic histogram bins for PosSwap modification
Adds option to use linear bins
=> Logarithmic histogram bins for PosSwap modification

PWGCF/Correlations/JCORRAN/Pro/AliAnalysisTaskRidge.cxx
This is the third time I apply this fix, please do not revert it.
=> Once again: possibility to compile with C++17

PWGUD/UPC/AddTaskUPCforward2.C, PWGUD/UPC/AliAnalysisTaskUPCforward2.cxx, PWGUD/UPC/AliAnalysisTaskUPCforward2.h, PWGUD/UPC/CMakeLists.txt, PWGUD/UPC/PWGUDupcLinkDef.h
Dear @mbroz84, this macro is actually the same as version1, just I am commenting out the lines we discussed about to check if those very same lines were creating problems in there...
=> PWGUD/UPC: Trying to fix.

PWGLF/RESONANCES/PostProcessing/Sigma1385/AddTaskSigmaStar_pp13TeV.C
=> remove Redefinition of arguements

PWGLF/RESONANCES/PostProcessing/Sigma1385/AddTaskSigmaStar_pp13TeV.C
referenced AddTaskRare_pp13TeV.C
cuts will be modified later..
=> fix unfinished line issue

PWGHF/treeHF/AliAnalysisTaskSEHFTreeCreator.cxx, PWGHF/treeHF/AliHFTreeHandler.cxx, PWGHF/treeHF/AliHFTreeHandler.h, PWGHF/treeHF/AliHFTreeHandlerBplustoD0pi.cxx, PWGHF/treeHF/AliHFTreeHandlerBplustoD0pi.h, PWGHF/treeHF/AliHFTreeHandlerD0toKpi.cxx, PWGHF/treeHF/AliHFTreeHandlerD0toKpi.h, PWGHF/treeHF/AliHFTreeHandlerDplustoKpipi.cxx, PWGHF/treeHF/AliHFTreeHandlerDplustoKpipi.h, PWGHF/treeHF/AliHFTreeHandlerDstartoKpipi.cxx, PWGHF/treeHF/AliHFTreeHandlerDstartoKpipi.h, PWGHF/treeHF/AliHFTreeHandlerDstoKKpi.cxx, PWGHF/treeHF/AliHFTreeHandlerDstoKKpi.h, PWGHF/treeHF/AliHFTreeHandlerLc2V0bachelor.cxx, PWGHF/treeHF/AliHFTreeHandlerLc2V0bachelor.h, PWGHF/treeHF/AliHFTreeHandlerLctopKpi.cxx, PWGHF/treeHF/AliHFTreeHandlerLctopKpi.h
Add generated pT (matched to reco candidates) to evaluate MC pT shape systematic
=> PWGHF: MVA, add generated pT for reco cand

PWGLF/RESONANCES/PostProcessing/Sigma1385/AddTaskSigmaStar_pp13TeV.C
=> try to recover missing brace error by adding one empty line at the end

PWGJE/FlavourJetTasks/AliAnalysisTaskHFJetIPQA.cxx, PWGJE/FlavourJetTasks/AliAnalysisTaskHFJetIPQA.h, PWGJE/FlavourJetTasks/macros/AddTaskHFJetIPQA.C
=> AliAnalysisTaskHFJetIPQA: apply cuts on jet properties via AliJetContainer

PWGLF/NUCLEX/Hypernuclei/Hyp2Body/AddTask_HypTritEventTree.C, PWGLF/NUCLEX/Hypernuclei/Hyp2Body/AliAnalysisTaskHypTritEventTree.cxx
TRD trigger and Bethe Bloch parameters for 2017 and 2018  have been added
=> Hypertriton search in pp

PWGJE/EMCALJetTasks/AliEmcalJetTask.cxx, PWGJE/EMCALJetTasks/AliEmcalJetTask.h
Q/pt shift is added (meaning 1/pt shift added for positive charged particles and subtracted for negative charged particles)
=> Add option for the Q/pt

PWGCF/FEMTOSCOPY/AliFemto/AliFemtoCutMonitorParticlePID.cxx
=> Change TOFTime binning to be consistent with dE/dx

PWGCF/FEMTOSCOPY/macros/Train/KpmHBT22/0010/AddTaskFemtoKchHBT0010.C, PWGCF/FEMTOSCOPY/macros/Train/KpmHBT22/0010/ConfigFemtoAnalysis.C, PWGCF/FEMTOSCOPY/macros/Train/KpmHBT22/1090/AddTaskFemtoKchHBT1090.C, PWGCF/FEMTOSCOPY/macros/Train/KpmHBT22/1090/ConfigFemtoAnalysis.C
=> Lego Train configs for SetNumEventsToMix(5)

PWGUD/UPC/AliAnalysisTaskUPCforward2.cxx
Dear @mbroz84 , 
this commit is what we have just discussed... 
I have checked and it works fine on local. 
Best wishes,
Simone
=> PWGUD/UPC: Uncommented event selection in test macro.

PWGHF/treeHF/AliHFTreeHandler.cxx, PWGHF/treeHF/AliHFTreeHandler.h
Minor modifications to allow storing the TPC and TOF n_sigma together with their combination. 
@fgrosa Could you check if everything looks ok?
=> Complete implementation for combining n_sigma TPC and TOF

PWGLF/SPECTRA/CMakeLists.txt, PWGLF/SPECTRA/PWGLFspectraLinkDef.h, PWGLF/SPECTRA/Spherocity/macros/AddTaskSphericityAnalysis.C, PWGLF/SPECTRA/Spherocity/macros/AliAnalysisSphericityTask.cxx, PWGLF/SPECTRA/Spherocity/macros/AliAnalysisSphericityTask.h
Study of sphericity of events containing strange particles of purpose of first fast check.
=> Sphericity of events containing strange particles

PWGDQ/dielectron/CMakeLists.txt, PWGDQ/dielectron/LMEE/AliAnalysisTaskReducedTreeDS.cxx, PWGDQ/dielectron/LMEE/AliAnalysisTaskReducedTreeDS.h, PWGDQ/dielectron/PWGDQdielectronLinkDef.h, PWGDQ/dielectron/macrosLMEE/AddTask_dsekihat_LMeeTree.C
add an analysis task to produce reduced an event tree for LMee based on AOD and ROOT6.
=> add an analysis task for LMee

PWG/EMCAL/EMCALbase/AliClusterContainer.cxx, PWG/EMCAL/EMCALbase/AliClusterContainer.h, PWGJE/EMCALJetTasks/CMakeLists.txt, PWGJE/EMCALJetTasks/PWGJEEMCALJetTasksLinkDef.h, PWGJE/EMCALJetTasks/Tracks/AliAnalysisTaskEmcalHighEClusterTree.cxx, PWGJE/EMCALJetTasks/Tracks/AliAnalysisTaskEmcalHighEClusterTree.h, PWGJE/EMCALJetTasks/macros/AddTaskEmcalHighEClusterTree.C
- Task with N-tuple of high-E cluster
- Add cut on the fraction of Ecell,leading/Ecluster in AliClusterContainer
=> Studies of the impact of high-E clusters

PWGDQ/dielectron/LMEE/AliAnalysisTaskReducedTreeDS.cxx, PWGDQ/dielectron/LMEE/AliAnalysisTaskReducedTreeDS.h, PWGDQ/dielectron/macrosLMEE/AddTask_dsekihat_LMeeTree.C
add 6 variables for trigger bits(INT7, kCentral, kSemiCentral etc.)
=> add 6 variables for trigger bits

PWGJE/EMCALJetTasks/UserTasks/AliAnalysisTaskJetExtractor.h
=> Quick fix for backward compatibility

PWGUD/UPC/AliAnalysisTaskUPCforward.cxx
Increased the binning for all pt-distributions in data.
This is needed to get to the same binning as presented in the last paper...
=> PWGUD/UPC: Finer binning for pt-distributions.

PWGUD/UPC/AliAnalysisTaskUPCforwardMC.cxx, PWGUD/UPC/AliAnalysisTaskUPCforwardMC.h
Switched to arrays for the run selection even in the MC macro...
Fixed the binning of the pt-distributions to be able to reproduce the same results as the paper...
=> PWGUD/UPC: Fixed the run selection. Adjusted the binning of the pt-distributions.

PWGJE/EMCALJetTasks/UserTasks/AliAnalysisTaskJetExtractor.h
=> Fix class def for streamer

PWGGA/EMCALTasks/AliAnalysisTaskGammaHadron.cxx, PWGGA/EMCALTasks/AliAnalysisTaskGammaHadron.h
Adds an energy swap map for determining same-position PS distribution
Also cleans up a few couts.
=> Adds an energy swap map for determining same-position PS distribution

PWGLF/RESONANCES/PostProcessing/Xi1530/AliAnalysisTaskXi1530.cxx
Old: Eventmixing checked only rapidity and charge and loose cuts.
Now: Eventmixing checks all the same topological cut with default way.
=> Check if the Event mixing is done with same way

PWGCF/FEMTOSCOPY/macros/Train/KpmHBT21/0010/ConfigFemtoAnalysis.C, PWGCF/FEMTOSCOPY/macros/Train/KpmHBT21/1090/ConfigFemtoAnalysis.C
=> Update train macros for purity PbPb

PWGLF/RESONANCES/AliRsnCutCascade.cxx, PWGLF/RESONANCES/AliRsnCutCascade.h, PWGLF/RESONANCES/AliRsnMiniParticle.cxx, PWGLF/RESONANCES/CMakeLists.txt, PWGLF/RESONANCES/PWGLFresonancesLinkDef.h, PWGLF/RESONANCES/PostProcessing/Sigma1385/AddTaskSigmaStar_pp13TeV.C
Add AliRsnCutCascade class.
Modify AliRsnMiniParticle class for AOD cascade charge
=> Add RsnCutCascade function

PWG/FLOW/Tasks/AliAnalysisTaskTwoMultiCorrelations.cxx, PWG/FLOW/Tasks/AliAnalysisTaskTwoMultiCorrelations.h
* Rewriten the TLists inside the output file.
* Added a new cut and TH2I correlation plot to try and remove high multiplicity outliers.
* Modified a bit the already existing cuts.
=> Added gestion of eta gaps for the 2-p correlations

PWGDQ/dielectron/LMEE/AliAnalysisTaskReducedTreeDS.cxx, PWGDQ/dielectron/LMEE/AliAnalysisTaskReducedTreeDS.h
further reduction of data size by using float, instead of double.
=> further reduction of data size

PWGHF/jetsHF/AliAnalysisTaskBJetTC.cxx, PWGHF/jetsHF/AliAnalysisTaskBJetTC.h
We decided to add a new discriminator to be used as a template for the data-driven efficiency determination.
=> Adding a new descriminator for the templates

PWG/MCLEGO/CRMC/gen_eposlhc_pbpb_5TeV.sh
to support EPOS-LHC with PbPb @ 5 TeV
=> Add macro for on-the-fly train

PWGHF/vertexingHF/AliAnalysisTaskSEHFSystPID.cxx, PWGHF/vertexingHF/AliAnalysisTaskSEHFSystPID.h
- added option to add number of findable clusters and number of crossed rows to the tree
-fix phi naming of branch
=> add option of further TPC quality info for track uncertainty studies

PWGCF/FEMTOSCOPY/FemtoDream/AliAnalysisTaskAODSigma0Femto.cxx, PWGCF/FEMTOSCOPY/FemtoDream/AliAnalysisTaskAODSigma0Femto.h, PWGCF/FEMTOSCOPY/FemtoDream/AliAnalysisTaskNanoAODSigma0Femto.cxx, PWGCF/FEMTOSCOPY/FemtoDream/AliAnalysisTaskNanoAODSigma0Femto.h, PWGCF/FEMTOSCOPY/macros/AddTaskSigma0FemtoAOD.C, PWGCF/FEMTOSCOPY/macros/AddTaskSigma0FemtoNanoAOD.C, PWGGA/Hyperon/AliSigma0AODPhotonMotherCuts.cxx, PWGGA/Hyperon/AliSigma0PhotonCuts.cxx, PWGGA/Hyperon/AliSigma0PhotonCuts.h, PWGGA/Hyperon/AliSigma0PhotonMotherCuts.cxx, PWGGA/Hyperon/CMakeLists.txt, PWGGA/Hyperon/PWGGAHyperonLinkDef.h
+minor bug fix for the spectrum analysis
=> Photon cuts with NanoAODs

PWGCF/Correlations/JCORRAN/Pro/AliJCDijetAna.cxx, PWGCF/Correlations/JCORRAN/Pro/AliJCDijetAna.h, PWGCF/Correlations/JCORRAN/Pro/AliJCDijetTask.cxx, PWGCF/Correlations/JCORRAN/Pro/AliJCDijetTask.h, PWGCF/Correlations/JCORRAN/Pro/CMakeLists.txt, PWGCF/Correlations/JCORRAN/Pro/PWGCFCorrelationsJCORRANProLinkDef.h
This makes running the analysis also outside AliPhysics easier.
=> Separated analysis code for easier use.

PWGLF/STRANGENESS/Cascades/Run2/AliAnalysisTaskWeakDecayVertexer.cxx, PWGLF/STRANGENESS/Cascades/Run2/AliAnalysisTaskWeakDecayVertexer.h
This reverts commit c273724c4a0a1b2fb02e72190100479a5f24f3c3, until I figure out where is the bug.
=> Revert "Add trigger track logic to the weak decayer"

PWG/FLOW/Tasks/AliAnalysisTaskTwoMultiCorrelations.cxx, PWG/FLOW/Tasks/AliAnalysisTaskTwoMultiCorrelations.h
* Modified the filling of the TH2I for the correlations between types of tracks to see the HM outliers.
* Added a second TH2I after the cuts to see their effects on the correlations.
=> Added a correlation histogram

PWG/DevNanoAOD/AliNanoAODReplicator.cxx, PWG/DevNanoAOD/AliNanoAODReplicator.h, PWG/DevNanoAOD/tutorial/AliAnalysisTaskNanoSimple.cxx
adding cloning of AliAODVertex daugther of cascade xi vertex
=> keeping order in which daughter objects are stored in an AliAODVertex

PWGDQ/dielectron/LMEE/AliAnalysisTaskReducedTreeDS.cxx, PWGDQ/dielectron/LMEE/AliAnalysisTaskReducedTreeDS.h, PWGDQ/dielectron/macrosLMEE/AddTask_dsekihat_LMeeTree.C
add Q vector variables for event mixing.
=> add Q vector variables

PWGDQ/dielectron/LMEE/AliAnalysisTaskReducedTreeDS.cxx
apply looser Ncluster ITS cut.
=> decrease Ncluster ITS cut

PWGHF/vertexingHF/macros/ComputeDmesonYield.C
@arossi81 @strogolo @RenuBala123 @syaefudinjaelani note that the version of yesterday (PR #10152) does not work properly because it modifies the FD hypo in the full pT range
=> Fix option for variable FD hypothesis

PWGLF/RESONANCES/PostProcessing/Xi1530/AddTaskXi1530.C, PWGLF/RESONANCES/PostProcessing/Xi1530/AliAnalysisTaskXi1530.cxx, PWGLF/RESONANCES/PostProcessing/Xi1530/AliAnalysisTaskXi1530.h, PWGLF/RESONANCES/PostProcessing/Xi1530/macros_pp13TeV/DrawXi1530.C, PWGLF/RESONANCES/PostProcessing/Xi1530/macros_pp13TeV/DrawXi1530PhysicsPlots.C, PWGLF/RESONANCES/PostProcessing/Xi1530/macros_pp13TeV/DrawingHelper.C, PWGLF/RESONANCES/PostProcessing/Xi1530/macros_pp13TeV/PlotXi1530.C, PWGLF/RESONANCES/PostProcessing/Xi1530/macros_pp13TeV/PlotXi1530ApprovalFigure.C, PWGLF/RESONANCES/PostProcessing/Xi1530/macros_pp13TeV/SystematicHelper.cxx, PWGLF/RESONANCES/PostProcessing/Xi1530/macros_pp13TeV/Xi1530YieldMean.C, PWGLF/RESONANCES/PostProcessing/Xi1530/macros_pp13TeV/YieldMean.C
Add Systematic study helper class.
Add Drawing Helper
Modify analysis class so that it can change the Y range for the asymmetric system study.
=> Update post-processing macro, add function to class

PWGLF/RESONANCES/PostProcessing/Xi1530/AliAnalysisTaskXi1530.cxx, PWGLF/RESONANCES/PostProcessing/Xi1530/AliAnalysisTaskXi1530.h
The default option is still "V0M"
=> Add option: different multiplicity estimator

PWGGA/GammaConv/AliAnalysisTaskGammaConvDalitzV1.cxx
I add a new way to calculate PsiPair cut on Dalitz, with the propagation of the momentum on plane xy plus 50.
=> Last Test on PsiPairCut like Dieletrons like everyone else

PWGCF/FLOW/GF/AliAnalysisTaskGFWFlow.cxx, PWGCF/FLOW/GF/AliAnalysisTaskGFWFlow.h, PWGCF/FLOW/GF/AliGFW.cxx, PWGCF/FLOW/GF/AliGFW.h, PWGCF/FLOW/GF/AliGFWCumulant.cxx, PWGCF/FLOW/GF/AliGFWCumulant.h, PWGCF/FLOW/GF/AliGFWWeights.cxx, PWGCF/FLOW/GF/AliGFWWeights.h
Reduced Q-matrix size, removed event-by-event string processing
=> Heavy work on AliGFW

PWGGA/GammaConv/macros/AddTask_GammaConvCalo_pp.C
Additional CutOption for Low B, needed for weighting checks
=> PWGGA: Added LowB Options for PCMPHOS weighting checks

PWGDQ/dielectron/LMEE/AliAnalysisTaskReducedTreeDS.cxx, PWGDQ/dielectron/LMEE/AliAnalysisTaskReducedTreeDS.h
=> add BC number to branch

PWGHF/vertexingHF/AliHFSystErr.cxx, PWGHF/vertexingHF/AliHFSystErr.h
Co-authored-by: Renu Bala renu.bala@cern.ch
Co-authored by: Syaefudin Jaelani syaefudin@jaelani.cern.ch
@RenuBala123 @syaefudinjaelani
=> Add syst unc for D+ and D*+ in PbPb 2018

PWGHF/vertexingHF/AliHFSystErr.cxx, PWGHF/vertexingHF/AliHFSystErr.h
- TMVA (BDT) case already there;
- ML added
- default added (in case we want to do a "standard" analysis...
=> Adding dummy systematics for Lc --> K0s+p for PbPb 2018

PWGHF/vertexingHF/AliHFSystErr.cxx
First version for tracking systematic. Might still get updated for preliminary
=> PWGHF: Systematics Lc PbPb MLHEP

PWGHF/vertexingHF/AliHFSystErr.cxx
Update of D0 systematic uncertainties in 0-10 and 30-50:
- MC pt-shape (new)
- Cut efficiencies (new)
- Tracking efficiency (include syst. from correction factor)
Update of Dstar systematic uncertainties in 0-10 and 30-50:
- Tracking efficiency (include syst. from correction factor)
=> Update D0 and Dstar systematic uncertainties

PWGHF/hfe/AliAnalysisTaskTPCCalBeauty.cxx, PWGHF/hfe/AliAnalysisTaskTPCCalBeauty.h, PWGHF/hfe/macros/AddTaskTPCCalBeauty.C
No able to turn each cut on/off independently. Also added histograms to test effect of E/p shift in MC, event cuts on the nEvents, and cluster time cuts.
=> Added ability to test results with HFe paper cuts and settings

PWGLF/RESONANCES/PostProcessing/Xi1530/AliAnalysisTaskXi1530.cxx
=> Disable Xi mass window cut in pre-selection

PWGUD/UPC/AliAnalysisTaskUPCforward.cxx, PWGUD/UPC/AliAnalysisTaskUPCforward.h, PWGUD/UPC/AliAnalysisTaskUPCforwardMC.cxx, PWGUD/UPC/AliAnalysisTaskUPCforwardMC.h
Added triggers' histograms for luminosity computation.
Fixed run numbers for LHC15o.
=> PWGUD/UPC: Added triggers' histograms for luminosity computation.

PWGLF/RESONANCES/PostProcessing/Xi1530/AliAnalysisTaskXi1530.cxx, PWGLF/RESONANCES/PostProcessing/Xi1530/AliAnalysisTaskXi1530.h
Add function "SetUseSimpleEventCut()" to use only IsSelected of AliMultSelection
=> Add option to use only event cut from AliMutiSelection

PWGHF/vertexingHF/AliHFSystErr.cxx
=> PWGHF: Fix typo systematics

PWGDQ/dielectron/LMEE/AliAnalysisTaskReducedTreeDS.cxx, PWGDQ/dielectron/LMEE/AliAnalysisTaskReducedTreeDS.h
=> update for M.C.

PWGDQ/dielectron/macrosLMEE/AddTask_caklein_LMEEPbPb_AOD_2018.C, PWGDQ/dielectron/macrosLMEE/Config_caklein_LMEEPbPb_AOD_2018.C, PWGDQ/dielectron/macrosLMEE/LMEECutLib_caklein_2018.C
=> PWGDQ: new addtask for 2018 analysis

PWGCF/FEMTOSCOPY/FemtoDream/AliAnalysisTaskFemtoDreamDeuteron.cxx, PWGCF/FEMTOSCOPY/FemtoDream/AliAnalysisTaskFemtoDreamDeuteron.h, PWGCF/FEMTOSCOPY/FemtoDream/CMakeLists.txt, PWGCF/FEMTOSCOPY/FemtoDream/PWGCFFemtoDreamLinkDef.h, PWGCF/FEMTOSCOPY/macros/AddTaskFemtoDreamDeuteron.C
=> task for proton-deuteron femtoscopy, updated version

PWGHF/hfe/AliAnalysisTaskTPCCalBeauty.cxx
Was adding counts to the wrong bin and double counting.
=> Bug fix in new NEvents histogram

PWGJE/EMCALJetTasks/Tracks/AliAnalysisTaskEmcalJetEnergyScale.cxx, PWGJE/EMCALJetTasks/Tracks/AliAnalysisTaskEmcalJetEnergyScale.h, PWGJE/EMCALJetTasks/Tracks/AliAnalysisTaskEmcalJetEnergySpectrum.cxx, PWGJE/EMCALJetTasks/Tracks/AliAnalysisTaskEmcalJetEnergySpectrum.h
The scale shift if apply should be roughly compatible
to the observed scale shift in simulations. It is added
to the measured pt value.
=> Adding artificial scale shift to det. level pt

PWG/EMCAL/Doxymodules.h, PWG/EMCAL/EMCALtasks/AliEmcalCorrectionCellBadChannel.h, PWG/EMCAL/EMCALtasks/AliEmcalCorrectionCellCombineCollections.h, PWG/EMCAL/EMCALtasks/AliEmcalCorrectionCellEmulateCrosstalk.h, PWG/EMCAL/EMCALtasks/AliEmcalCorrectionCellEnergy.h, PWG/EMCAL/EMCALtasks/AliEmcalCorrectionCellEnergyVariation.h, PWG/EMCAL/EMCALtasks/AliEmcalCorrectionCellTimeCalib.h, PWG/EMCAL/EMCALtasks/AliEmcalCorrectionClusterEnergyVariation.h, PWG/EMCAL/EMCALtasks/AliEmcalCorrectionClusterExotics.h, PWG/EMCAL/EMCALtasks/AliEmcalCorrectionClusterHadronicCorrection.h, PWG/EMCAL/EMCALtasks/AliEmcalCorrectionClusterNonLinearity.h, PWG/EMCAL/EMCALtasks/AliEmcalCorrectionClusterNonLinearityMCAfterburner.h, PWG/EMCAL/EMCALtasks/AliEmcalCorrectionClusterTrackMatcher.h, PWG/EMCAL/EMCALtasks/AliEmcalCorrectionClusterizer.h, PWG/EMCAL/EMCALtasks/AliEmcalCorrectionComponent.h, PWG/EMCAL/EMCALtasks/AliEmcalCorrectionEventManager.h, PWG/EMCAL/EMCALtasks/AliEmcalCorrectionPHOSCorrections.h, PWG/EMCAL/EMCALtasks/AliEmcalCorrectionTask.h
For easier navigation move all classes related to the EMCAL correction
framework to a dedicated group EMCALCORRECTIONFW in doxygen.
=> [Doxygen] Add group for classes of the EMCAL correction framework

PWGLF/RESONANCES/PostProcessing/Xi1530/AliAnalysisTaskXi1530.cxx
Before: check only IsMultSelected
After: chek IsTriggerd together
=> Add Trigger check

PWGLF/RESONANCES/PostProcessing/Xi1530/AliAnalysisTaskXi1530.cxx, PWGLF/RESONANCES/PostProcessing/Xi1530/AliAnalysisTaskXi1530.h
=> Enable AOD functionality

PWGLF/RESONANCES/PostProcessing/Xi1530/AliAnalysisTaskXi1530.cxx, PWGLF/RESONANCES/PostProcessing/Xi1530/AliAnalysisTaskXi1530.h
Add default filterbit for pion -> 32
add pT cut for all particles -> gt0.15
=> Add Default trackcuts in AOD mode

PWGLF/RESONANCES/PostProcessing/Xi1530/AliAnalysisTaskXi1530.cxx
=> fix pT cut bug

PWGUD/UPC/AliAnalysisTaskUPCforwardMC.cxx, PWGUD/UPC/AliAnalysisTaskUPCforwardMC.h
=> PWGUD/UPC: 1D analysis proper binning.

PWG/DevNanoAOD/AliAnalysisTaskNanoAODnormalisation.cxx, PWG/DevNanoAOD/tools/printStat.C
minor fix in normalisation task
=> macro for printing stat from normalisation

PWGLF/RESONANCES/PostProcessing/Xi1530/AliAnalysisTaskXi1530.cxx
For V0M vs SPDnTrk in multiplicty study
=> Add SPD nTrk checker

PWGPP/AliESDtools.cxx
=> ALIROOT-8256: Bug fix - proper filling of track Z array

PWGHF/treeHF/AliAnalysisTaskSEHFTreeCreator.cxx, PWGHF/treeHF/AliAnalysisTaskSEHFTreeCreator.h, PWGHF/treeHF/AliParticleTreeHandler.cxx, PWGHF/treeHF/AliParticleTreeHandler.h, PWGHF/treeHF/CMakeLists.txt, PWGHF/treeHF/PWGHFtreeHFLinkDef.h, PWGHF/treeHF/macros/AddTaskHFTreeCreator.C
Implement this option for testing purposes.
@ginnocen, @nzardosh, @fgrosa, @lvermunt
=> treeHF/JetTree: Implement option to write all tracks in event

PWGUD/UPC/AliAnalysisTaskUPCforwardMC.cxx, PWGUD/UPC/AliAnalysisTaskUPCforwardMC.h
Added the efficiency plots on a run-by-run basis.
=> PWGUD/UPC: Added Efficiency plots.

PWGUD/UPC/AliAnalysisTaskUPCforwardMC.cxx, PWGUD/UPC/AliAnalysisTaskUPCforwardMC.h
Added Lumi code on a run-by-run basis.
=> PWGUD/UPC: Added LUMI cap code on a run-by-run basis.

PWGUD/UPC/AddTaskMatchTriggerForward.C, PWGUD/UPC/AliAnalysisTaskMatchTriggerForward.cxx, PWGUD/UPC/AliAnalysisTaskMatchTriggerForward.h, PWGUD/UPC/CMakeLists.txt, PWGUD/UPC/PWGUDupcLinkDef.h
New Analysis Task for Single Muon Match Trigger Efficiency.
IMPORTANT: still has to be rewritten in the core part...
=> PWGUD/UPC: New Analysis Task for Single Muon Match Trigger Efficiency.

PWGHF/vertexingHF/AliAnalysisTaskSEHFSystPID.cxx, PWGHF/vertexingHF/AliAnalysisTaskSEHFSystPID.h
- add tag with HMPID Nsigma for kaons 
- add possibility to activate branches for HMPID PID information
- move flags for no ITS/TPC/TOF from fTag to fTrackInfoMap 
- always activate fTrackInfoMap branch
=> Add possibility to enable PID with HMPID

PWGCF/FEMTOSCOPY/FemtoDream/AliAnalysisTaskNanoXioton1530.cxx, PWGCF/FEMTOSCOPY/FemtoDream/AliFemtoDreamv0Cuts.cxx
=> Fixes to the invariant mass caluclation

PWGDQ/dielectron/core/AliAnalysisTask_JPsi_EMCal.cxx, PWGDQ/dielectron/core/AliAnalysisTask_JPsi_EMCal.h, PWGDQ/dielectron/macrosJPsi/AddTask_JPsi_EMCal.C, PWGDQ/dielectron/macrosJPsi/Config_JPsi_EMCal.C
Task for the EMCal related things on JPsi analysis
=> task for JPsi analysis with EMCal

PWGGA/Hyperon/AliSigma0V0Cuts.cxx, PWGGA/Hyperon/macros/AddTaskSigma0Run2.C
Also fixing small formatting error.
=> Cleaning of AddTask macro.

PWGDQ/dielectron/LMEE/AliAnalysisTaskReducedTreeDS.cxx, PWGDQ/dielectron/LMEE/AliAnalysisTaskReducedTreeDS.h
add 2 more member variables (Number SPD clusters, TPConly track) to the event tree.
=> add 2 more member variables

PWG/CaloTrackCorrBase/AliIsolationCut.cxx, PWG/CaloTrackCorrBase/AliIsolationCut.h, PWGGA/CaloTrackCorrelations/AliAnaParticleHadronCorrelation.cxx, PWGGA/CaloTrackCorrelations/AliAnaParticleIsolation.cxx
Move the code checking the tracks or clusters in the cone, each one to separate methods.
=> code factorization, in view of further improvements

PWGUD/UPC/AliAnalysisTaskUPCforwardMC.cxx, PWGUD/UPC/AliAnalysisTaskUPCforwardMC.h
I have added ETA vs PHI maps on a run-by-run basis for MC.
=> PWGUD/UPC: Added dead zone check on a run-by-run basis (MC).

PWGUD/UPC/AliAnalysisTaskMatchTriggerForward.cxx, PWGUD/UPC/AliAnalysisTaskMatchTriggerForward.h
Added 2D maps in Eta vs Phi for single muons at forward rapidities. Single Efficiencies have been added too. The analysis is done with and without Single Muon Triggering.
=> PWGUD/UPC: Added maps 2D ETA-PHI with and without matching. Single Muon Triggering.

PWGLF/RESONANCES/CMakeLists.txt, PWGLF/RESONANCES/PostProcessing/Xi1530/AliAnalysisTaskXi1530.cxx, PWGLF/RESONANCES/PostProcessing/Xi1530/AliAnalysisTaskXi1530.h
CMakeList -> Add PWDDevNanoAOD as a dependency.
The others -> modify for the nanoAOD runs
=> Use AliEventCuts, Add functions for nanoAOD runs

PWGUD/UPC/AliAnalysisTaskUPCforward.cxx, PWGUD/UPC/AliAnalysisTaskUPCforward.h
This commit adds checks for the polarisation analysis.
It is basically a confirmation that the solid I had implemented was solid enough...
=> PWGUD/UPC: Added cross-check for polarisation.

PWGHF/hfe/AliAnalysisTaskTPCCalBeauty.cxx, PWGHF/hfe/AliAnalysisTaskTPCCalBeauty.h
(Explicitly name a few mother PID in the stack instead of giving a range of values.)
=> Added histos testing different mother PID for efficiency in the stack.

PWGDQ/dielectron/macrosJPSI/AddTask_JPsi_EMCal.C, PWGDQ/dielectron/macrosJPSI/Config_JPsi_EMCal.C
updating AddTask and Config files
=> updating AddTask and Config files

PWGUD/UPC/AddTaskMatchTriggerForward.C
=> PWGUD/UPC: Modified output dir.

PWGUD/UPC/AliAnalysisTaskUPCforwardMC.cxx, PWGUD/UPC/AliAnalysisTaskUPCforwardMC.h
Added acceptance plots for 2D polarisation with my variable binning.
=> PWGUD/UPC: Added acceptance plots for the 2D polarisation

PWGLF/RESONANCES/PostProcessing/Xi1530/AddTaskXi1530_RsnPack.C
Change the default order of Xi daughters
=> Modifiy PID cut for Xibar

PWGLF/NUCLEX/Exotica/LambdaNN/AddTask_LNNv0Bkg.C
Macro for Lego trains modified
=> task name wrong, now modified

PWG/FLOW/Tasks/AliAnalysisTaskTwoMultiCorrelations.cxx, PWG/FLOW/Tasks/AliAnalysisTaskTwoMultiCorrelations.h
* Add QA histograms for the multiplicity distribution to check its evolution with the application of the selection criteria.
* Update the methods to cut the outliers in the MC events.
* Increase the readability of the code by diving the selection criteria in two methods: one for the event selection, one for the track selection.
=> Update the methods to analyse AOD and MC events.

PWG/CaloTrackCorrBase/AliIsolationCut.cxx, PWG/CaloTrackCorrBase/AliIsolationCut.h, PWGGA/CaloTrackCorrelations/macros/AddTaskCaloTrackCorrBase.C, PWGGA/CaloTrackCorrelations/macros/ConfigureCaloTrackCorrAnalysis.C
=> allow correction of cone content when out of detector acceptance

PWGLF/RESONANCES/PostProcessing/Xi1530/AliAnalysisTaskXi1530.cxx
=> Update AliEventCuts info

PWGDQ/reducedTree/AliReducedCaloClusterTrackMatcher.cxx, PWGDQ/reducedTree/AliReducedCaloClusterTrackMatcher.h
added possibility for matching based on phi and eta separately
=> PWGDQ/reducedTree/AliReducedCaloClusterTrackMatcher: update

PWGLF/RESONANCES/PostProcessing/Xi1530/AddTaskXi1530_RsnPack.C, PWGLF/RESONANCES/PostProcessing/Xi1530/AliAnalysisTaskXi1530.cxx
Before: 
if (this->GoodTracksSelection() && this->GoodCascadeSelection())
Now: 
bool checkPionTrack = this->GoodTracksSelection();
bool checkCascade = this->GoodCascadeSelection();
if (checkPionTrack && checkCascade)
=> Fix track check for AOD(nanoAOD) run

PWGGA/GammaConv/AliAnalysisTaskClusterQA.cxx, PWGGA/GammaConv/AliAnalysisTaskClusterQA.h, PWGGA/GammaConv/AliAnalysisTaskConversionTree.cxx, PWGGA/GammaConv/AliAnalysisTaskConversionTree.h, PWGGA/GammaConv/CMakeLists.txt, PWGGA/GammaConv/PWGGAGammaConvLinkDef.h, PWGGA/GammaConv/macros/AddTask_PhotonTree.C
The output of this task is meant to be used for students to learn how an invariant mass analysis works in general.
The TTree contains all necessary information to calculate invariant mass, calculate mixed event backgrounds and even check (in case of MC) for MC truth.
=> PWGGA/GammaConv: Added photon analysis tree class (student tutorial input)

PWGMM/UE/UeSpectra/AliAnalysisTaskPPvsUE.cxx, PWGMM/UE/UeSpectra/AliAnalysisTaskPPvsUE.h, PWGMM/UE/UeSpectra/macros/AddTaskPPvsUE.C
Adding away region plus bug fixes
=> Adding away region plus bug fixes

PWGDQ/dielectron/macrosLMEE/AddTask_acapon.C, PWGDQ/dielectron/macrosLMEE/Config_acapon_noCutLib.C
AddTask altered so it now possible to use a simple Config file which is self contained with all analysis cuts. 
Simple config also added.
=> Update AddTask to work with and w/o cutLibrary

PWGLF/RESONANCES/PostProcessing/Xi1530/AddTaskXi1530.C, PWGLF/RESONANCES/PostProcessing/Xi1530/AliAnalysisTaskXi1530.cxx
binning has an error in HM mode.
=> Fix trivial binning error in MC, addtask modify for HM option.

PWGHF/hfe/AliAnalysisTaskTPCCalBeauty.cxx
(Trying again - last request failed with empty merge error.)
=> Moved stack loop after event cuts, added TPC+ITS refit.

PWGCF/FEMTOSCOPY/macros/AddTaskSigma0DebugTest.C
=> Try some photon pT variations

PWGMM/UE/CMakeLists.txt, PWGMM/UE/PWGMMueLinkDef.h, PWGMM/UE/UeSpectra/AliAnalysisTaskPPvsUE.cxx, PWGMM/UE/UeSpectra/AliAnalysisTaskPPvsUE.h
Forgot to add tasks to CMakeLists and PWGMM LinkDef
=> Adding tasks to CMakeLists and PWGMM LinkDef

PWGUD/UPC/AliAnalysisTaskMatchTriggerForward.cxx, PWGUD/UPC/AliAnalysisTaskMatchTriggerForward.h, PWGUD/UPC/AliAnalysisTaskUPCforward.cxx
Eliminated calibration for ZDC.
=> PWGUD/UPC: Eliminated calib for ZDC: muoncalo_pass3 incoming.

PWGDQ/dielectron/macrosLMEE/AddTask_acapon.C, PWGDQ/dielectron/macrosLMEE/Config_acapon_noCutLib.C
Also add possibility to switch off/on pairing and mixing when
using the simple config
=> Add extra event property histograms

PWGCF/FEMTOSCOPY/macros/Train/Femto_PS/Pileup/EventTrack/pt1/ConfigFemtoAnalysis.C
modifications in the config file for grid running
=> AliFemto: change in pp 13 TeV config file

PWGLF/RESONANCES/PostProcessing/Xi1530/AliAnalysisTaskXi1530.cxx
=> Add Rapidity cut for daughter Xi analysis

PWGCF/FEMTOSCOPY/macros/Train/ProtonLambdaFemto/ProtonLambda/Xi/FB128/ConfigAvgsepAnalysis.C
adding V0 monitor and excluding Xis
=> AliFemto: changes in baryon config file

PWGGA/GammaConv/AliAnalysisTaskGammaConvDalitzV1.cxx, PWGGA/GammaConv/AliAnalysisTaskGammaConvDalitzV1.h, PWGGA/GammaConv/macros/AddTask_GammaConvDalitzV1_pp.C
Dear AliPhysics,
On the next commit, I add a function for deltaPhi on terms of constrained param and the vertex selection for the events.
Regard
Ed
=> delthaPhi with constrained parameters and train for kAny and kBoth

PWGDQ/dielectron/LMEE/AliAnalysisTaskSimpleTreeMaker.cxx, PWGDQ/dielectron/LMEE/AliAnalysisTaskSimpleTreeMaker.h
Add flag indication whether a track is a physical primary track.
Defined via mcTrack->IsPhysicalPrimary()
All DCA branches now written as floats.
Also, general code clean up and formatting.
=> Add IsPhysPrimary to TreeMaker output

PWGUD/UPC/AliAnalysisTaskMatchTriggerForward.cxx
Increased dynamical range of the ZDC after having a look at the:
https://alice-notes.web.cern.ch/system/files/notes/analysis/481/2017-Jul-14-analysis_note-ALICE_analysis_note.pdf
This is needed for the XNXN analysis to check for the QA of the muoncalo_pass3.
=> PWGUD/UPC: Increased dynamical range of the ZDC.

PWGLF/RESONANCES/PostProcessing/Xi1530/AliAnalysisTaskXi1530.cxx
=> Revert Constant(XiMass)

PWGGA/CaloTrackCorrelations/macros/CheckActiveEMCalTriggerPerPeriod.C
and some trigger/period combination, no trigger available
=> Prevent analysis on trigger data for first LHC17/18 periods 

PWGMM/UE/UeSpectra/macros/AddTaskPPvsUE.C
Fixing trigger selection flag in AddTask
=> Fixing trigger flag

PWGMM/UE/UeSpectra/macros/AddTaskPPvsUE.C
=> Fixing MC flag

PWGCF/FEMTOSCOPY/FemtoDream/AliAnalysisTaskNanoAODSigma0Femto.cxx, PWGCF/FEMTOSCOPY/FemtoDream/AliAnalysisTaskNanoAODSigma0Femto.h, PWGCF/FEMTOSCOPY/macros/AddTaskSigma0DebugTest.C, PWGCF/FEMTOSCOPY/macros/AddTaskSigma0FemtoNanoAOD.C, PWGGA/Hyperon/AliSigma0PhotonCuts.cxx, PWGGA/Hyperon/AliSigma0PhotonCuts.h
- Check the impact of the track cleaner
- Run some checks for the transverse radius of the photon (a lot of background when 70 < r < 80 cm, which corresponds to the inner part of the TPC)
=> Further checks for p-Sigma0 femto

PWGUD/UPC/AliAnalysisTaskMatchTriggerForward.cxx, PWGUD/UPC/AliAnalysisTaskUPCforward.cxx, PWGUD/UPC/AliAnalysisTaskUPCforward.h, PWGUD/UPC/AliAnalysisTaskUPCforwardMC.cxx, PWGUD/UPC/AliAnalysisTaskUPCforwardMC.h
Improved the ZDC calibration stuff for MB by resetting each time the ZDC values and better default value. 
Added new variable binning analysis for 1D polarisation.
=> PWGUD/UPC: Improvement on ZDC for MB + new 1D variable binning pol analysis.

PWGHF/vertexingHF/AliHFSystErr.cxx, PWGHF/vertexingHF/AliHFSystErr.h
changes to Syst values for LctopKpi2016pPb and addition of LctopKpi2017pp values to AliHFSystErr
=> changes to LctopKpi Syst values for pPb 2016 and pp 2017

PWGCF/FEMTOSCOPY/macros/Train/NonIdParticleFemto/PionKaonFemto/syst_CorrFunc/70ncls/ConfigFemtoAnalysis.C, PWGCF/FEMTOSCOPY/macros/Train/NonIdParticleFemto/PionKaonFemto/syst_CorrFunc/DCA70ncls/ConfigFemtoAnalysis.C
systematic checks requested by IRC
=> Pion-kaon: Configs for the train

PWGUD/UPC/AliAnalysisTaskUPCforward.cxx, PWGUD/UPC/AliAnalysisTaskUPCforward.h
Reduced binning for 1D polarisation.
=> PWGUD/UPC: Reduced variable binning polarisation 1D.

PWGJE/EMCALJetTasks/PWGJEEMCALJetTasksLinkDef.h, PWGJE/EMCALJetTasks/UserTasks/AliAnalysisTaskEmcalJetHCorrelations.cxx, PWGJE/EMCALJetTasks/UserTasks/AliAnalysisTaskEmcalJetHCorrelations.h, PWGJE/EMCALJetTasks/UserTasks/AliAnalysisTaskEmcalJetHPerformance.cxx, PWGJE/EMCALJetTasks/UserTasks/AliAnalysisTaskEmcalJetHPerformance.h, PWGJE/EMCALJetTasks/UserTasks/AliAnalysisTaskEmcalJetHUtils.cxx, PWGJE/EMCALJetTasks/UserTasks/AliAnalysisTaskEmcalJetHUtils.h
Encompasses a number of changes over the last few months
=> Collection of jet-hadron updates

PWGCF/FEMTOSCOPY/FemtoDream/AliAnalysisTaskNanoLX.cxx, PWGCF/FEMTOSCOPY/FemtoDream/AliAnalysisTaskNanoLX.h, PWGCF/FEMTOSCOPY/macros/AddTaskFemtoLX.C
- Fix numbering of output containers
- Fill the global track array to use the daughter tracks
=> Minor fixes to get the Lambda-Xi analysis running

PWGUD/UPC/AliAnalysisTaskUPCforwardMC.cxx, PWGUD/UPC/AliAnalysisTaskUPCforwardMC.h
=> PWGUD/UPC: New binning for 1D polarisation.

PWGCF/FEMTOSCOPY/macros/AddTaskSigma0FemtoNanoAOD.C, PWGGA/Hyperon/AliSigma0PhotonCuts.cxx
- Minor bug fix for lightweight mode
=> Implement the systematic cut variations for the Nanos

PWGDQ/dielectron/LMEE/AliAnalysisTaskReducedTreeDS.cxx, PWGDQ/dielectron/LMEE/AliAnalysisTaskReducedTreeDS.h
support for AliTimeRangeCut to analyze 7 PID bad runs in LHC18r.
=> support for AliTimeRangeCut

PWGCF/FEMTOSCOPY/macros/Train/KK_13TeV_dist_03/AddTaskFemtoKchHBT1090.C, PWGCF/FEMTOSCOPY/macros/Train/KK_13TeV_dist_03/ConfigFemtoAnalysis.C, PWGCF/FEMTOSCOPY/macros/Train/KK_13TeV_dist_07/AddTaskFemtoKchHBT1090.C, PWGCF/FEMTOSCOPY/macros/Train/KK_13TeV_dist_07/ConfigFemtoAnalysis.C, PWGCF/FEMTOSCOPY/macros/Train/pipi_13TeV_dist_03/AddTaskFemtoKchHBT1090.C, PWGCF/FEMTOSCOPY/macros/Train/pipi_13TeV_dist_03/ConfigFemtoAnalysis.C, PWGCF/FEMTOSCOPY/macros/Train/pipi_13TeV_dist_07/AddTaskFemtoKchHBT1090.C, PWGCF/FEMTOSCOPY/macros/Train/pipi_13TeV_dist_07/ConfigFemtoAnalysis.C
=> Train files: Ludmila returned from vacation 2019

PWGCF/FEMTOSCOPY/AliFemto/AliAnalysisTaskFemto.cxx, PWGCF/FEMTOSCOPY/AliFemto/AliAnalysisTaskFemto.h, PWGCF/FEMTOSCOPY/AliFemto/AliFemtoEventReaderNanoAOD.cxx, PWGCF/FEMTOSCOPY/AliFemto/AliFemtoEventReaderNanoAOD.h, PWGCF/FEMTOSCOPY/AliFemto/AliFemtoEventReaderNanoAODChain.cxx, PWGCF/FEMTOSCOPY/AliFemto/AliFemtoEventReaderNanoAODChain.h, PWGCF/FEMTOSCOPY/AliFemto/AliFemtoTrack.cxx, PWGCF/FEMTOSCOPY/AliFemto/AliFemtoTrack.h, PWGCF/FEMTOSCOPY/AliFemto/CMakeLists.txt, PWGCF/FEMTOSCOPY/AliFemto/PWGCFfemtoscopyLinkDef.h
adding possibility to AliFemto to run on NanoAODs
=> AliFemto: adding functionality to run on NanoAOD

PWGCF/FEMTOSCOPY/macros/Train/KchKch_Run2_July/KpKm_13TeV_dist/AddTaskFemtoKchHBT1090.C, PWGCF/FEMTOSCOPY/macros/Train/KchKch_Run2_July/KpKm_13TeV_dist/ConfigFemtoAnalysis.C, PWGCF/FEMTOSCOPY/macros/Train/KchKch_Run2_July/pippim_13TeV_dist/AddTaskFemtoKchHBT1090.C, PWGCF/FEMTOSCOPY/macros/Train/KchKch_Run2_July/pippim_13TeV_dist/ConfigFemtoAnalysis.C, PWGCF/FEMTOSCOPY/macros/Train/KchKch_Run2_July/pippim_13TeV_jets/AddTaskFemtoKchHBT1090.C, PWGCF/FEMTOSCOPY/macros/Train/KchKch_Run2_July/pippim_13TeV_jets/ConfigFemtoAnalysis.C
=> Train files: Ludmila : KchKch_Run2_July pi+pi-

PWGMM/Mult/AliAnalysisPseudoRapidityDensity.cxx, PWGMM/Mult/AliAnalysisPseudoRapidityDensity.h, PWGMM/Mult/CMakeLists.txt, PWGMM/Mult/macros/AddTaskPseudoRapidityDensity.C
In order to run on the legotrain, some relevant parts have been updated!
=> update of RapidityDensity and a new macro

PWGJE/EMCALJetTasks/UserTasks/AliAnalysisTaskEmcalJetHCorrelations.cxx, PWGJE/EMCALJetTasks/UserTasks/AliAnalysisTaskEmcalJetHCorrelations.h, PWGJE/EMCALJetTasks/UserTasks/AliAnalysisTaskEmcalJetHPerformance.cxx, PWGJE/EMCALJetTasks/UserTasks/AliAnalysisTaskEmcalJetHPerformance.h, PWGJE/EMCALJetTasks/UserTasks/AliAnalysisTaskEmcalJetHUtils.cxx, PWGJE/EMCALJetTasks/UserTasks/AliAnalysisTaskEmcalJetHUtils.h, PWGJE/EMCALJetTasks/macros/AddTaskEmcalJetHCorrelations.C
=> Update tracking efficiency

PWGCF/FEMTOSCOPY/AliFemto/AliFemtoEventReaderNanoAOD.cxx
=> AliFemto: reading NanoAODS - bug fixes

PWGCF/FEMTOSCOPY/macros/Train/KK_Run2_MC_JulySp/KK_13TeV_dist_03/ConfigFemtoAnalysis.C, PWGCF/FEMTOSCOPY/macros/Train/KK_Run2_MC_JulySp/KK_13TeV_dist_07/ConfigFemtoAnalysis.C, PWGCF/FEMTOSCOPY/macros/Train/KK_Run2_MC_JulySp/add/AddTaskFemto.C, PWGCF/FEMTOSCOPY/macros/Train/KK_Run2_MC_JulySp/pipi_13TeV_dist_03/ConfigFemtoAnalysis.C, PWGCF/FEMTOSCOPY/macros/Train/KK_Run2_MC_JulySp/pipi_13TeV_dist_07/ConfigFemtoAnalysis.C, PWGCF/FEMTOSCOPY/macros/Train/KK_Run2_MC_JulySp/pippim_13TeV_dist/ConfigFemtoAnalysis.C, PWGCF/FEMTOSCOPY/macros/Train/KK_Run2_MC_JulySp/pippim_13TeV_jets/ConfigFemtoAnalysis.C
=> Train: Ludmila MC pp

PWGLF/RESONANCES/PostProcessing/Xi1530/AliAnalysisTaskXi1530.cxx, PWGLF/RESONANCES/PostProcessing/Xi1530/AliAnalysisTaskXi1530.h
For Xi1530 pion
and re-arrange the QA histos
=> Change default trackcuts

PWGMM/Lumi/vdM/CandRoot.h, PWGMM/Lumi/vdM/Create_BBD_separation_file.C, PWGMM/Lumi/vdM/Create_ODC_separation_file.C, PWGMM/Lumi/vdM/Create_bbd_file.C, PWGMM/Lumi/vdM/Create_beam_intensity_file.C, PWGMM/Lumi/vdM/Create_bkgd_corrected_rate_file.C, PWGMM/Lumi/vdM/Create_hxhy_file.C, PWGMM/Lumi/vdM/Create_intensity_corrected_rate_file.C, PWGMM/Lumi/vdM/Create_nominal_separation_file_Fill_7483.C, PWGMM/Lumi/vdM/Create_pileup_corrected_rate_file.C, PWGMM/Lumi/vdM/Create_raw_rate_file.C, PWGMM/Lumi/vdM/Create_xs_file.C, PWGMM/Lumi/vdM/FitUtils.h, PWGMM/Lumi/vdM/GlobalVariables.h, PWGMM/Lumi/vdM/InputFromUser.h, PWGMM/Lumi/vdM/QA_beam_intensity.C, PWGMM/Lumi/vdM/QA_corr_sep.C, PWGMM/Lumi/vdM/QA_get_intensities.C, PWGMM/Lumi/vdM/QA_normalisation_histograms.C, PWGMM/Lumi/vdM/QA_rate_vs_sep.C, PWGMM/Lumi/vdM/QA_xs.C, PWGMM/Lumi/vdM/Readme.html, PWGMM/Lumi/vdM/Readme_V0M_7483.txt, PWGMM/Lumi/vdM/vdmUtilities.h
Adding new macros up to correction for beam-beam deflection and several macros for QA
=> New version of vdM analysis macros

PWGCF/FEMTOSCOPY/AliFemto/AliFemtoEventReaderNanoAOD.cxx
=> AliFemto: more bug fixes in NanoAOD rader

PWGLF/RESONANCES/PostProcessing/Xi1530/AddTaskXi1530.C, PWGLF/RESONANCES/PostProcessing/Xi1530/AliAnalysisTaskXi1530.cxx
Prevent return the event when it has no track buffer
=> Fix event mixing loss

PWGLF/RESONANCES/PostProcessing/Xi1530/AliAnalysisTaskXi1530.cxx
=> Fix AOD PionZ issue

PWGDQ/dielectron/LMEE/AliAnalysisTaskReducedTreeDS.cxx, PWGDQ/dielectron/LMEE/AliAnalysisTaskReducedTreeDS.h
support for analyzing LF/HF injected M.C. production
=> support for LF/HF injected M.C. production

PWGLF/RESONANCES/PostProcessing/Xi1530/AliAnalysisTaskXi1530.cxx
Try to use GetImpactParameters()
Remove PropagateDCA cut because it doesn't work at all.
=> Fix DCA cut bug & Remove PropagateDCA cut

PWGDQ/dielectron/core/AliAnalysisTask_JPsi_EMCal.cxx, PWGDQ/dielectron/core/AliAnalysisTask_JPsi_EMCal.h, PWGDQ/dielectron/macrosJPSI/AddTask_JPsi_EMCal.C, PWGDQ/dielectron/macrosJPSI/Config_JPsi_EMCal.C
A flag was added to fill or not the THnSparse.
Few new histograms were added.
Some bins were changed, to reduce the size of the outputs.
=> adding option to not fill THnSparse, due to large output files

PWGCF/Correlations/DPhi/Unfoldedhistos/AliCSEventCuts.cxx, PWGCF/Correlations/macros/Unfoldedhistos/runCorrelationsStudiesConfigMacro.C
The usual copy and paste mistake
=> Fix for total number of TPC clusters wrong pointer when ESD events

PWGLF/RESONANCES/PostProcessing/Xi1530/AliAnalysisTaskXi1530.cxx
it made a crash in AOD train.
but not in local env.
=> Revert mixing trigger 

PWGJE/EMCALJetTasks/UserTasks/AliAnalysisTaskEmcalJetHUtils.cxx, PWGJE/EMCALJetTasks/UserTasks/AliAnalysisTaskEmcalJetHUtils.h
There was a bug in the eta parametrization, which required a
recalculation of the normalization
=> Fix efficiency implementation

PWGCF/FEMTOSCOPY/macros/Train/NonIdParticleFemto/PionKaonFemto/syst_CorrFunc/PID/StrictCut/NanoAOD/ConfigFemtoAnalysis.C
adding Config file for pion-kaon femto to run on NanoAODs in LHC11h data
=> AliFemto: config to run pi-K femto on NanoAODs

PWGLF/RESONANCES/PostProcessing/Xi1530/AliAnalysisTaskXi1530.cxx
=> Fix event mixing bug in AOD

PWGJE/EMCALJetTasks/CMakeLists.txt, PWGJE/EMCALJetTasks/PWGJEEMCALJetTasksLinkDef.h, PWGJE/EMCALJetTasks/Tracks/AliAnalysisTaskEmcalJetIterativeDeclustering.cxx, PWGJE/EMCALJetTasks/Tracks/AliAnalysisTaskEmcalJetIterativeDeclustering.h, PWGJE/EMCALJetTasks/Tracks/AliAnalysisTaskEmcalSoftDropData.cxx, PWGJE/EMCALJetTasks/Tracks/AliAnalysisTaskEmcalSoftDropData.h, PWGJE/EMCALJetTasks/macros/AddTaskEmcalJetIterativeDeclustering.C
New task for iterative declustering scanning
the lund map parameters for all splittings
in a jet and filling a THnSparse with the
paramters.
In addition fix trigger selection in SoftDrop
task on daa.
=> New task for iterative declustering

PWGDQ/dielectron/LMEE/AliAnalysisTaskReducedTreeDS.cxx, PWGDQ/dielectron/LMEE/AliAnalysisTaskReducedTreeDS.h
add variables to distinguish injected M.C. particles
=> add variables to distinguish injected M.C. particles

PWGLF/SPECTRA/PiKaPr/TPCTOFCascades/AliAnalysisTaskTPCTOFCascade.cxx
Minor debugging, as well as adding generated K' resonance particles.
=> Added MC functionality for K*s

PWGLF/RESONANCES/PostProcessing/f0980/AddTaskInclusivef0f2.C, PWGLF/RESONANCES/PostProcessing/f0980/AliAnalysisTaskInclusivef0f2.cxx, PWGLF/RESONANCES/PostProcessing/f0980/AliAnalysisTaskInclusivef0f2.h
Update some switches for different collision type.
PWGLF/RESONANCES/PostProcessing/f0980/AddTaskInclusivef0f2.C
PWGLF/RESONANCES/PostProcessing/f0980/AliAnalysisTaskInclusivef0f2.cxx
PWGLF/RESONANCES/PostProcessing/f0980/AliAnalysisTaskInclusivef0f2.h
=> [PWGLF] Update on options for pPb and PbPb

PWGCF/Correlations/JCORRAN/Pro/AliAnalysisTaskRidge.cxx, PWGCF/Correlations/JCORRAN/Pro/AliAnalysisTaskRidge.h, PWGCF/Correlations/macros/jcorran/AddTaskRidge.C
Add jet reconstruction into ridge analysis.
Replacement of TList with AliDirList.
PWGCF/Correlations/JCORRAN/Pro/AliAnalysisTaskRidge.cxx
PWGCF/Correlations/JCORRAN/Pro/AliAnalysisTaskRidge.h
PWGCF/Correlations/macros/jcorran/AddTaskRidge.C
=> [PWGCF] Add jet reconstruction

PWGJE/EMCALJetTasks/UserTasks/AliAnalysisTaskEmcalJetHUtils.cxx
=> Fix setting centrality

PWGHF/vertexingHF/CMakeLists.txt, PWGHF/vertexingHF/PWGHFvertexingHFLinkDef.h
New pull request to complete the previous one, following @fprino 's coment
=> Xic->pKpi task inserted in PWGHFvertexingHFLinkDef.h and in CMakeLists.txt files

PWGGA/GammaConv/macros/AddTask_GammaConvCalo_pp.C
adding testbeam nonlins for pp 13 TeV PCM-EDC
=> PWGGA/GammaConv/macros/AddTask_GammaConvCalo_pp.C 

PWGCF/Correlations/JCORRAN/Base/AliJRunTable.cxx
=> Runtable edited

PWGHF/correlationHF/AliAnalysisTaskDHFeCorr.cxx, PWGHF/correlationHF/AliAnalysisTaskDHFeCorr.h, PWGHF/correlationHF/macros/AddTaskDHFeCorr.C
Hi,
I have implemented minor changes to make it possible to run the analysis on trains. There was a small problem in the AddTrask file.
Best
Henrique
=> Fix AddTask (for trains) and minor changes in the variables

PWG/CaloTrackCorrBase/AliCalorimeterUtils.h, PWG/EMCAL/EMCALbase/AliEMCALRecoUtils.cxx, PWG/EMCAL/EMCALbase/AliEMCALRecoUtils.h, PWG/EMCAL/EMCALtasks/AliEmcalCorrectionCellTimeCalib.cxx, PWG/EMCAL/EMCALtasks/AliEmcalCorrectionCellTimeCalib.h, PWG/EMCAL/EMCALtasks/AliEmcalCorrectionComponent.cxx, PWG/EMCAL/EMCALtasks/AliEmcalCorrectionComponent.h, PWG/EMCAL/EMCALtasks/AliEmcalCorrectionTask.cxx, PWG/EMCAL/EMCALtasks/AliEmcalCorrectionTask.h, PWG/EMCAL/config/AliEmcalCorrectionConfiguration.yaml, PWGPP/EMCAL/AliAnalysisTaskEMCALClusterize.cxx, PWGPP/EMCAL/AliAnalysisTaskEMCALClusterize.h, TENDER/TenderSupplies/AliEMCALTenderSupply.cxx, TENDER/TenderSupplies/AliEMCALTenderSupply.h
I made few more modification on the correction framework to take one histogram instead of four for all BCs.
=> More modification on the correction framework to take one histo for all BCs

PWGCF/Correlations/JCORRAN/Pro/AliAnalysisTaskRidge.cxx
This is the third time I restore the C++17 fixes. Please make sure that you check the pull request before you approve it.
=> Restore again the possibility to compile with C++17

PWGDQ/dielectron/macrosLMEE/AddTask_acapon.C, PWGDQ/dielectron/macrosLMEE/Config_acapon_noCutLib.C
Conversion cuts added to mimic run 1 cuts.
Flag added to AddTask to toggle PileUpRejectio
=> Update Run1 cuts, and add RejPileUp flag

PWGDQ/dielectron/core/AliAnalysisTask_JPsi_EMCal.cxx, PWGDQ/dielectron/core/AliAnalysisTask_JPsi_EMCal.h
New histos for the vertex efficiency
Optimization of multiplicity bins for SPD and V0 analysis.
=> adding new histos for vertex efficiency (J/psi EMCal analysis)

PWGLF/RESONANCES/PostProcessing/Xi1530/AliAnalysisTaskXi1530.cxx
=> Fix Mixing issue

PWGCF/Correlations/DPhi/AliAnalysisTaskPIDBFDptDpt.cxx, PWGCF/Correlations/DPhi/AliAnalysisTaskPIDBFDptDpt.h, PWGCF/Correlations/macros/PIDBFDptDpt/AddTaskPIDBFDptDpt.C
added misID and secondary check in closure test
=> added misID and secondary check in closure test

PWGCF/FEMTOSCOPY/AliFemto/AliFemtoEventReaderNanoAOD.cxx, PWGCF/FEMTOSCOPY/AliFemto/AliFemtoEventReaderNanoAOD.h
changes to the NanoAOD reader - possibility to run if covariance matrix not set
=> AliFemto: modifications to NanoAOD reader

PWGCF/Correlations/JCORRAN/Pro/AliJCDijetAna.cxx, PWGCF/Correlations/JCORRAN/Pro/AliJCDijetAna.h, PWGCF/Correlations/JCORRAN/Pro/AliJCDijetHistos.cxx, PWGCF/Correlations/JCORRAN/Pro/AliJCDijetHistos.h, PWGCF/Correlations/JCORRAN/Pro/AliJCDijetTask.cxx, PWGCF/Correlations/JCORRAN/Pro/AliJCDijetTask.h, PWGCF/Correlations/macros/jcorran/AddTaskJCDijetTask.C
Later this will be used to create response matrices. The root5 compiling
error was fixed.
=> Det and true MC can be run during the same run.

PWGCF/FEMTOSCOPY/FemtoDream/AliFemtoDreamEvent.cxx
=> Optimize computation of spherocity

PWGMM/UE/CMakeLists.txt, PWGMM/UE/PWGMMueLinkDef.h, PWGMM/UE/UeSpherocity/AddTaskUeRSpherocity.C, PWGMM/UE/UeSpherocity/AliAnalysisTaskUeRSpherocity.cxx, PWGMM/UE/UeSpherocity/AliAnalysisTaskUeRSpherocity.h
An analysis task has been added to study UE and event shapes
=> ana task to study ue and event shapes

PWGPP/AliESDtools.cxx, PWGPP/AliESDtools.h
-  adding option to reset histogram
- make ITS filter more effective
- increase outlier cut
- adding LTM estimator + disable tgl cut
=> PWGPP-538, PWGPP-529 - updated pileup rejection algorithm

PWGJE/EMCALJetTasks/UserTasks/AliAnalysisTaskJetCoreEmcal.cxx, PWGJE/EMCALJetTasks/UserTasks/AliAnalysisTaskJetCoreEmcal.h, PWGJE/EMCALJetTasks/macros/AddTaskJetCoreEmcal.C
- add embedding option for embedding pp data
- fix cut on fraction of shared pt, and QA histogram for shared pt
=> add possibility to embed pp data events

PWGDQ/dielectron/LMEE/AliAnalysisTaskReducedTreeDS.cxx, PWGDQ/dielectron/LMEE/AliAnalysisTaskReducedTreeDS.h, PWGDQ/dielectron/macrosLMEE/AddTask_dsekihat_LMeeTree.C
update for pileup study : add more variables related to displaced Z vertex
=> update for pileup study

PWGDQ/dielectron/macros/AddTaskPtMothFromPtDaughBJpsi.C
AddTask macro to set-up AliAnalysisTaskPtMothFromPtDaugh task (which runs on kinematics only)  for B->J/psi analysis.
=> AddTask macro to set-up AliAnalysisTaskPtMothFromPtDaugh task

PWGDQ/dielectron/macrosLMEE/AddTask_acapon.C, PWGDQ/dielectron/macrosLMEE/Config_acapon.C, PWGDQ/dielectron/macrosLMEE/LMEECutLib_acapon.C
Ability to switch on and off pile up rejection techniques as well as the usage of the AliEventCut class.
=> Adds flags for different pileUpRej options 

PWGHF/treeHF/AliAnalysisTaskSEHFTreeCreator.cxx, PWGHF/treeHF/AliAnalysisTaskSEHFTreeCreator.h
Keep track of the triggers fired in an event to allow for more complex
post-processing
=> Add trigger masks in tree_event_char

PWGPP/AliESDtools.cxx, PWGPP/AliESDtools.h
=> PWGPP-531- correct path to test file

PWGJE/EMCALJetTasks/Tracks/AliAnalysisEmcalTriggerSelectionHelper.cxx, PWGJE/EMCALJetTasks/Tracks/AliAnalysisEmcalTriggerSelectionHelper.h, PWGJE/EMCALJetTasks/Tracks/AliAnalysisTaskEmcalJetEnergySpectrum.cxx
Trigger clusters were in case of data not propagated to the array trgclusters, therefore the relevant histogram was filled only with "ANY"
=> Fix selection of trigger clusters

PWGCF/FEMTOSCOPY/AliFemtoUser/AliFemtoPairCutAntiGamma.cxx
=> possible bug fix in AliFemto:AntiGamma cut

PWGLF/RESONANCES/PostProcessing/Xi1530/AliAnalysisTaskXi1530.cxx, PWGLF/RESONANCES/PostProcessing/Xi1530/AliAnalysisTaskXi1530.h
=> Add Study function for V0 CPA cut study.

PWGHF/treeHF/AliAnalysisTaskSEHFTreeCreator.cxx, PWGHF/treeHF/AliAnalysisTaskSEHFTreeCreator.h
mostly removing unnecessary code, more to come
=> Clean up of tree creator

PWGGA/GammaConv/AliAnalysisTaskNeutralMesonToPiPlPiMiNeutralMeson.cxx, PWGGA/GammaConv/AliAnalysisTaskNeutralMesonToPiPlPiMiNeutralMeson.h
* fixed two missing pointer deletions
* Cluster histos that are needed for calculation of rejection factors will now be filled even if light output is activated
=> PWGGA/GammaConv: fixed missing delete in heavy meson task

PWGPP/TRD/AliTRDdigitsFilter.cxx, PWGPP/TRD/AliTRDdigitsFilter.h, PWGPP/TRD/macros/AddTRDdigitsFilter.C
This pull request is in preparation for filtering the digits during the upcoming Pb-Pb production.
=>  Improve particle selection for TRD digits filter

PWGUD/UPC/AliAnalysisTaskUPCforward.cxx
Bug fix for TildePhi.
It doesn't really affect the parameter determination at all, it only affects the normalisation parameter, but it doesn't look pretty.
=> PWGUD/UPC: Bug fix.

PWGLF/RESONANCES/macros/mini/AddTaskKStarPlusMinusMult.C, PWGLF/RESONANCES/macros/mini/ConfigKStarPlusMinusMultiplicity.C
The two macros are an update of AddTaskKStarPlusMinusMult.C and ConfigKStarPlusMinusRun2.C,
the macros improve the binning of third component of the sparses (Centrality variable) and
will allow future study at higher multiplicity (centrality < 1) allowing to select the trigger mask kHighMultV0.
=> Improve the binning of Centrality and add high multiplicity mask option

PWGHF/treeHF/AliAnalysisTaskSEHFTreeCreator.cxx
=> Fix default constructor

PWGHF/vertexingHF/AliAnalysisTaskSEXic2eleXifromAODtracks.cxx, PWGHF/vertexingHF/AliAnalysisTaskSEXic2eleXifromAODtracks.h, PWGHF/vertexingHF/macros/AddTaskXic2eleXifromAODtracks.C
Checking the acceptance of electrons in data and MC is required, which is considered as a source of systematic uncertainties.
=> Check the acceptance

PWGLF/RESONANCES/PostProcessing/f0980/AliAnalysisTaskInclusivef0f2.cxx
Fix bug in pile up selection.
Analyze event even if the number of events for mixing is insufficient.
=> [PWGLF] Fix bug in switch

PWGLF/RESONANCES/AliRsnCutV0.cxx, PWGLF/RESONANCES/AliRsnCutV0.h, PWGLF/RESONANCES/AliRsnEventCuts.cxx, PWGLF/RESONANCES/AliRsnEventCuts.h
1. Add the MutlSelection object in the AliRsnEventCuts (the new class, still under development)
2. Add the possibility to apply different DCAxy cuts in the V0 daughters
=> Changes in PWGLF/RESONANCES, AliRsnEventCuts and AliRsnCutV0

PWGCF/Correlations/JCORRAN/Pro/AliJCDijetAna.cxx, PWGCF/Correlations/JCORRAN/Pro/AliJCDijetAna.h, PWGCF/Correlations/JCORRAN/Pro/AliJCDijetHistos.cxx, PWGCF/Correlations/JCORRAN/Pro/AliJCDijetHistos.h, PWGCF/Correlations/JCORRAN/Pro/AliJCDijetTask.cxx, PWGCF/Correlations/JCORRAN/Pro/AliJCDijetTask.h, PWGCF/Correlations/macros/jcorran/AddTaskJCDijetTask.C
Also arranged the dijet calculation to be more neat and easier to use
with response matrix calculations.
=> Added response matrices for jets and dijets.

PWGHF/hfe/AliAnalysisTaskHFEBESpectraEMC.cxx, PWGHF/hfe/AliAnalysisTaskHFEBESpectraEMC.h
E/p obtained with EMCal cluster energy calculated after non-linearity correction
=> Calculating E/p with non-linearity cluster energy

PWGHF/vertexingHF/CMakeLists.txt, PWGHF/vertexingHF/vHFBDT/AliRDHFBDT.cxx, PWGHF/vertexingHF/vHFBDT/AliRDHFBDT.h, PWGHF/vertexingHF/vHFBDT/AliRDHFDTNode.cxx, PWGHF/vertexingHF/vHFBDT/AliRDHFDTNode.h, PWGHF/vertexingHF/vHFBDT/AliRDHFDecisionTree.cxx, PWGHF/vertexingHF/vHFBDT/AliRDHFDecisionTree.h, PWGHF/vertexingHF/vHFBDT/CMakeLists.txt, PWGHF/vertexingHF/vHFBDT/vHFBDTLinkDef.h
Added integrated classes for implementing BDT in HF analysis.
For now the BDT can be input as Node->Tree->BDT flow.
A macro to convert TMVA BDT model(.xml) to AliRDHFBDT will be uploaded in days.
=> Add vHFBDT Integrated BDT

PWGLF/RESONANCES/macros/mini/AddTaskSigPM.C, PWGLF/RESONANCES/macros/mini/ConfigSigPM.C
Updated config macro and AddTask for Sigma star analysis in PbPb 2018
=> Updated config macro and AddTask for Sigma star analysis in PbPb 2018

PWGCF/FEMTOSCOPY/macros/Train/DEtaDPhi/2018/Sphericity/TrioAnalysis/NanoAOD/ConfigFemtoAnalysis.C
adding trio analysis on NanoAODs
=> AliFemto: adding trio analysis to NanoAODs

PWGCF/FEMTOSCOPY/AliFemto/AliAnalysisTaskFemto.cxx, PWGCF/FEMTOSCOPY/AliFemto/AliAnalysisTaskFemto.h, PWGCF/FEMTOSCOPY/macros/Train/AddTaskFemto.C
adding possibility to read config file stored on the GRID
=> AliFemto: adding possibility to read config file from grid

PWGCF/FEMTOSCOPY/AliFemto/AliAnalysisTaskFemto.cxx
removing a nasty way of loading a file
=> AliFemto: better way of loading a macro to interpreter

PWGHF/treeHF/AliAnalysisTaskSEHFTreeCreator.cxx, PWGHF/treeHF/AliAnalysisTaskSEHFTreeCreator.h, PWGHF/treeHF/AliHFTreeHandler.h, PWGHF/treeHF/AliHFTreeHandlerBstoDspi.cxx, PWGHF/treeHF/AliHFTreeHandlerBstoDspi.h, PWGHF/treeHF/CMakeLists.txt, PWGHF/treeHF/PWGHFtreeHFLinkDef.h, PWGHF/treeHF/macros/AddTaskHFTreeCreator.C, PWGHF/vertexingHF/AliVertexingHFUtils.cxx, PWGHF/vertexingHF/AliVertexingHFUtils.h
For ITS3 studies. Tested and works as expected.
=> PWGHF: Adding Bs->Ds pi in TreeCreator

PWGCF/Correlations/JCORRAN/Pro/AliAnalysisTaskRidge.cxx, PWGCF/Correlations/JCORRAN/Pro/AliAnalysisTaskRidge.h, PWGCF/Correlations/macros/jcorran/AddTaskRidge.C
Change the streamer of AliJJetTask for legotrain operation.
Stop copying efficiency file in the current directory
=> [PWGCF] Change the streamer of AliJJetTask

PWGDQ/dielectron/LMEE/AliAnalysisTaskReducedTreeDS.cxx, PWGDQ/dielectron/LMEE/AliAnalysisTaskReducedTreeDS.h
support ESD for pileup study by checking displaced track Z and the number of track from pileup vertex.
=> support ESD for pileup study

PWGHF/vertexingHF/AliAnalysisTaskSED0BDT.cxx, PWGHF/vertexingHF/AliAnalysisTaskSED0BDT.h, PWGHF/vertexingHF/CMakeLists.txt, PWGHF/vertexingHF/PWGHFvertexingHFLinkDef.h, PWGHF/vertexingHF/macros/AddTaskD0BDT.C, PWGHF/vertexingHF/macros/ReadTMVABDTxml.C
Added TaskSE for D0 BDT analysis
Added Macro for AddTask
Added a Macro for TMVA BDT -> AliRDHFBDT conversion
=> Add TaskSED0BDT/Macro to convert TMVA BDT model to RDHFBDT

PWGUD/UPC/AliAnalysisTaskUPCforward.cxx
=> PWGUD/UPC: Reinstated 2015 ZDC calibration.

PWGLF/NUCLEX/Hypernuclei/Hyp2Body/AddTaskReducedTreeHyperTritonBindingEnergy.C, PWGLF/NUCLEX/Hypernuclei/Hyp2Body/AliAnalysisTaskReducedTreeHypertritonBindingEnergy.cxx, PWGLF/NUCLEX/Hypernuclei/Hyp2Body/AliAnalysisTaskReducedTreeHypertritonBindingEnergy.h
Analysis task for the measurement of Hypertriton Binding energy
=> Hypertriton Binding energy

PWGUD/UPC/AliAnalysisTaskUPCforwardMC.cxx, PWGUD/UPC/AliAnalysisTaskUPCforwardMC.h
=> PWGUD/UPC: Added rapidity-wise MC templates.

PWGUD/UPC/AliAnalysisTaskUPCforward.cxx
This should fix the differences between the 0NXN and the XN0N classes...
Maybe.
=> PWGUD/UPC: Change ZNA energy threshold.

PWGUD/UPC/AliAnalysisTaskUPCforward.cxx
Discovered bug in the calibration.
Possibly fixed now...?
=> PWGUD/UPC: New calibration for 2015 data sample.

PWGHF/vertexingHF/macros/AddTaskD0BDT.C
=> Fixed possible container name duplication

PWGLF/NUCLEX/Hypernuclei/Hyp2Body/AddTaskReducedTreeHyperTritonBindingEnergy.C
=> AddTask: Fixed Output file name

PWGCF/Correlations/JCORRAN/Pro/AliJCDijetAna.cxx, PWGCF/Correlations/JCORRAN/Pro/AliJCDijetAna.h, PWGCF/Correlations/JCORRAN/Pro/AliJCDijetTask.cxx
This is for further analysis by different sets of jets.
=> Separated jet reconstruction and jet analysis.

PWGHF/vertexingHF/AliAnalysisTaskSEXicTopKpi.cxx, PWGHF/vertexingHF/AliAnalysisTaskSEXicTopKpi.h, PWGHF/vertexingHF/AliRDHFCutsXictopKpi.cxx, PWGHF/vertexingHF/AliRDHFCutsXictopKpi.h, PWGHF/vertexingHF/CMakeLists.txt, PWGHF/vertexingHF/PWGHFvertexingHFLinkDef.h, PWGHF/vertexingHF/macros/AddTaskSEXicTopKpi.C
Creation of a specific class to apply cuts on Xic candidates and TTree filling modified for PID studied
=>  Xic->pKpi task updated

PWGHF/vertexingHF/AliAnalysisTaskSEHFSystPID.cxx
1) add protection to check whether histos filled with MC truth are defined for each particle specie
2) add protection to always skip time-range cut when running on MC
=> Fix filling of histos with MC truth and always disable time range cut for MC

PWGHF/vertexingHF/charmFlow/CharmHadronVnAnalysis.C, PWGHF/vertexingHF/charmFlow/CharmHadronVnFitSystematics.C, PWGHF/vertexingHF/charmFlow/CharmHadronYieldRatioESE.C, PWGHF/vertexingHF/charmFlow/config_Dplus_v2_unbiased.yml
Add possibility to analyse unmerged files (input file name substituted by list of file names in yml config file)
@strogolo
=> Add possibility to analyse several input files together

PWGLF/RESONANCES/AliRsnCutPIDkink.cxx, PWGLF/RESONANCES/AliRsnCutPIDkink.h, PWGLF/RESONANCES/CMakeLists.txt, PWGLF/RESONANCES/PWGLFresonancesLinkDef.h, PWGLF/RESONANCES/macros/mini/AddTaskLambdaStarWithKinks.C, PWGLF/RESONANCES/macros/mini/ConfigLambdaStarWithKinks.C
-Add a class for kaon identification via kinks in the RSN package.
-Modified the CMakeLists.txt and PWGLFresonancesLinkDef.h (add the class)
-Add task and Config file for L star analysis with kaons ID via kinks
=> Add the possibility of kaon identification via kinks in the RSN package

PWGHF/treeHF/AliAnalysisTaskSEHFTreeCreator.cxx, PWGHF/treeHF/AliAnalysisTaskSEHFTreeCreator.h, PWGHF/treeHF/AliHFTreeHandlerBstoDspi.cxx, PWGHF/treeHF/AliHFTreeHandlerBstoDspi.h, PWGHF/treeHF/AliHFTreeHandlerLbtoLcpi.cxx, PWGHF/treeHF/AliHFTreeHandlerLbtoLcpi.h, PWGHF/treeHF/CMakeLists.txt, PWGHF/treeHF/PWGHFtreeHFLinkDef.h, PWGHF/treeHF/macros/AddTaskHFTreeCreator.C, PWGHF/vertexingHF/AliVertexingHFUtils.cxx, PWGHF/vertexingHF/AliVertexingHFUtils.h
* Adding Lb -> Lc pi decay to HF TTreeCreator.
Same stage as the Bs decay. Some developments to run over the Upgrade MC productions are still needed, but on its own the Lb (and Bs from PR #11185) part is finished.
=> PWGHF: TreeCreator, add Lb for ITS3 studies

PWGDQ/dielectron/macrosJPSI/AddTask_JPsi_EMCal.C, PWGDQ/dielectron/macrosJPSI/Config_JPsi_EMCal.C
- Config file modified to have several configuration cuts.
- AddTask modified to support several outputs, given a configuration cut.
=> added new cuts for the systematic studies of track selection and eID

PWGCF/FEMTOSCOPY/AliFemto/AliAnalysisTaskFemto.cxx, PWGCF/FEMTOSCOPY/AliFemto/AliAnalysisTaskFemto.h, PWGCF/FEMTOSCOPY/macros/Train/AddTaskFemto.C
=> AliFemto: adding again a possibility to run with GRID config file

PWGHF/vertexingHF/AliAnalysisTaskSED0BDT.h, PWGHF/vertexingHF/macros/AddTaskD0BDT.C
Fixed wrong class name in AddTaskD0BDT.C:
AliAnalysisTaskSED0BDT1 -> AliAnalysisTaskSED0BDT
=> Fixed wrong class name

PWGCF/FEMTOSCOPY/AliFemto/AliFemtoXiTrackCut.cxx, PWGCF/FEMTOSCOPY/AliFemto/AliFemtoXiTrackCut.h
=> AliFemto: adding possibility of sideband analysis for cascades

PWGPP/AliESDtoolTRDTOF.cxx, PWGPP/AliESDtoolTRDTOF.h, PWGPP/AliRootInteractive.h, PWGPP/AliRootInteractiveTest.C
Cevelopment version - currently it works only with RootInterctive master
In order to be able to use RootInteractive new Relase of RootInteractive to be used in aliBuild
=> PWGPP-485 - macros for interactive visualization of TTree data using RootInteractive + Tools

PWG/CaloTrackCorrBase/AliAnaCaloTrackCorrBaseClass.h, PWG/CaloTrackCorrBase/AliCaloTrackReader.cxx, PWG/CaloTrackCorrBase/AliCaloTrackReader.h, PWGGA/CaloTrackCorrelations/AliAnaParticleJetFinderCorrelation.cxx, PWGGA/CaloTrackCorrelations/AliAnaParticleJetFinderCorrelation.h, PWGGA/CaloTrackCorrelations/CMakeLists.txt
Changes in classesfrom PWG/CaloTrackCorrBase: AliAnaCaliTrackCorrBaseClass.h, AliCaloTrackReader.{h,cxx} to be able to handle AliEmcalJet branch. Changes in PWGGA/CaloTrackCorrelations/AliAnaParticleJetFinderCorrelation task are consequence of AliEmcalJet class include. Also CMakeLists.txt are changed to use Jet Framework classes.
=> Adjustment to run gamma-jet task

PWGGA/CaloTrackCorrelations/macros/ConfigureCaloTrackCorrAnalysis.C
Changes in configuration file to run gamma-jet analysis.
=> Changes in configuration file to run gamma-jet analysis

PWGGA/CaloTrackCorrelations/macros/ConfigureCaloTrackCorrAnalysis.C
Added missing #include "AliAnaParticleJetFinderCorrelation.h"
=> Added missing #include

PWGPP/AliAnalysisTaskFilteredTree.cxx, PWGPP/AliAnalysisTaskFilteredTree.h, PWGPP/AliRootInteractiveTest.C, PWGPP/test/testAliAnalysisTaskFiltered/AliAnalysisTaskFilteredTest.C
* Monte carlo trigger for charged particles - using MC true information (if exist)
* Monte calrlo trigger for nuclei - using MC information if exists 
* adding color code example use
=>  PWGPP-546: high mass trigger and charged trigger including MC trigger

PWGHF/treeHF/AliAnalysisTaskSEHFTreeCreator.cxx, PWGHF/treeHF/AliHFTreeHandlerLbtoLcpi.cxx, PWGHF/treeHF/AliHFTreeHandlerLbtoLcpi.h
* Fix memory leak Lb and Bs
* Improve Lb and Bs
* Small general fixes
=> PWGHF: TTreeCreator, update ITS3 particles

PWGCF/FEMTOSCOPY/AliFemto/AliFemtoV0TrackCut.cxx
Hi,
I imagine this is a leftover from a previous commit. I remove it as it makes the compilation fail on macos.
Cheers,
Philippe
=> remove duplicate functions

PWGMM/UE/CMakeLists.txt, PWGMM/UE/PWGMMueLinkDef.h, PWGMM/UE/UeSpectraRT/AliAnalysisTaskUeSpectraRT.cxx, PWGMM/UE/UeSpectraRT/AliAnalysisTaskUeSpectraRT.h, PWGMM/UE/UeSpectraRT/macros/AddTaskUeSpectraRT.C
Task for UE Spectra for higher RT
=> Task for UE Spectra for higher RT

PWGDQ/dielectron/core/AliAnalysisTaskEtaReconstruction.cxx, PWGDQ/dielectron/macrosLMEE/AddTask_feisenhut_EtaReconstruction.C, PWGDQ/dielectron/macrosLMEE/Config_feisenhut_EtaReconstruction.C
I made some changes to run the MC Simulation for pp
=> PWGDQ LMEE update for pp MC EtaReconstruction

PWGJE/FlavourJetTasks/AliAnalysisTaskDmesonJetsSub.cxx
=> check one by one

PWGCF/FEMTOSCOPY/macros/Train/GR_Aug2019/kk_502_0_40/AddTaskFemtoKchHBT1090.C, PWGCF/FEMTOSCOPY/macros/Train/GR_Aug2019/kk_502_0_40/ConfigFemtoAnalysis.C, PWGCF/FEMTOSCOPY/macros/Train/GR_Aug2019/kk_502_40_90/AddTaskFemtoKchHBT1090.C, PWGCF/FEMTOSCOPY/macros/Train/GR_Aug2019/kk_502_40_90/ConfigFemtoAnalysis.C, PWGCF/FEMTOSCOPY/macros/Train/GR_Aug2019/kk_502_70_90/AddTaskFemtoKchHBT1090.C, PWGCF/FEMTOSCOPY/macros/Train/GR_Aug2019/kk_502_70_90/ConfigFemtoAnalysis.C
=> Lego trian for Gleb 23 Aug 2019

PWGJE/EMCALJetTasks/CMakeLists.txt, PWGJE/EMCALJetTasks/PWGJEEMCALJetTasksLinkDef.h, PWGJE/EMCALJetTasks/UserTasks/AliAnalysisTaskSDKL.cxx, PWGJE/EMCALJetTasks/UserTasks/AliAnalysisTaskSDKL.h
The task works fine on the grid. Never tested the root5 compatibility, suspect it might fail.
=> Initial commit of a custom declustering task

PWGLF/RESONANCES/PostProcessing/Xi1530/AddTaskXi1530.C, PWGLF/RESONANCES/PostProcessing/Xi1530/AliAnalysisTaskXi1530.cxx, PWGLF/RESONANCES/PostProcessing/Xi1530/AliAnalysisTaskXi1530.h
Add function for inelastic study mode
It was worked before as well but couldn't use the mixed background.
=> Add INEL function

PWGCF/Correlations/JCORRAN/Pro/AliAnalysisTaskRidge.h
=> [PWGCF] Add Class

PWGUD/UPC/AliAnalysisTaskUPCforward.cxx, PWGUD/UPC/AliAnalysisTaskUPCforward.h
I have implemented stronger checks for the ZDC... 
This should help in seeing what happens towards the higher end of the spectrum!!
And possibly solving the XNXN puzzle too...
=> PWGUD/UPC: New checks for the ZDC.

PWGLF/SPECTRA/PiKaPr/TPCTOFCascades/AliAnalysisTaskTPCTOFCascade.cxx
Just a super quick edit where I removed the upper bound on the MC rapidity distribution (file size got too large).
=> Removal of the upper-bound of the monte-carlo rapidity cut.

PWGUD/UPC/AliAnalysisTaskUPCforward.cxx
=> PWGUD/UPC: Last ZDC check.

PWGUD/UPC/AliAnalysisTaskUPCforward.cxx
Fixed TildePhi. Now it wraps continuously.
This should help in keeping it flat without the previous step structure...
=> PWGUD/UPC: TildePhi fix.

PWGUD/UPC/AliAnalysisTaskUPCforward.cxx, PWGUD/UPC/AliAnalysisTaskUPCforwardMC.cxx
Fixed MC ACCxEFF to account for the recent change in the definition of TildePhi...
=> PWGUD/UPC: Fix MC TildePhi and tiniy fix data TildePhi.

PWGCF/Correlations/JCORRAN/Pro/AliAnalysisTaskRidge.cxx
Save AliDIrList instead of THistManager
=> [PWGCF] Change of the save method

PWGHF/treeHF/AliAnalysisTaskSEHFTreeCreator.cxx, PWGHF/treeHF/AliAnalysisTaskSEHFTreeCreator.h, PWGHF/treeHF/AliHFTreeHandlerBplustoD0pi.cxx, PWGHF/treeHF/AliHFTreeHandlerBplustoD0pi.h, PWGHF/treeHF/macros/AddTaskHFTreeCreator.C, PWGHF/vertexingHF/AliAODRecoDecayHF2Prong.cxx, PWGHF/vertexingHF/AliVertexingHFUtils.cxx
* Updated Bplus in TTreeCreator with recent developments for Bs and Lb
* Changed Bplus RDHF cutobject to D0 cutobject for convenience
* Included mom. consv. fix also in Bplus functions (for ITS Upgrade productions)
=> PWGHF: Update Bplus to same level as Bs and Lb

PWGHF/vertexingHF/AliAnalysisTaskSEHFSystPID.cxx, PWGHF/vertexingHF/AliAnalysisTaskSEHFSystPID.h
1) move pdg code from short to int for nuclei 
2) add data member for dE/dx conversion factor from float to short
=> Move pdg code from short to int and add data member for conversion factor

PWGDQ/dielectron/core/AliAnalysisTaskEtaReconstruction.cxx, PWGDQ/dielectron/core/AliAnalysisTaskEtaReconstruction.h, PWGDQ/dielectron/core/AliDielectronMC.cxx, PWGDQ/dielectron/core/AliDielectronMC.h, PWGDQ/dielectron/core/AliDielectronPair.h, PWGDQ/dielectron/macrosLMEE/AddTask_feisenhut_EtaReconstruction.C, PWGDQ/dielectron/macrosLMEE/Config_feisenhut_EtaReconstruction.C
I added smearing into the reconstruction and pairing of the task.
=> PWGDQ LMEE Added smearing for MC Eta Reconstruction Simulation

PWGCF/Correlations/JCORRAN/Pro/AliAnalysisTaskRidge.cxx
change of the location of event mixing
switch for systematic uncertainty study
=> [PWGCF] change of the location of event mixing

PWGHF/vertexingHF/AliAnalysisTaskSEBPlustoD0Pi.cxx, PWGHF/vertexingHF/AliAnalysisTaskSEBPlustoD0Pi.h, PWGHF/vertexingHF/AliRDHFCutsBPlustoD0Pi.cxx, PWGHF/vertexingHF/AliRDHFCutsBPlustoD0Pi.h, PWGHF/vertexingHF/macros/AddTaskBPlustoD0Pi.C
The update has a lot of small changes like adding histograms, replacing "FindObject" functions to speed up the code, and removing unused functions.
=> Update of BPlus code

PWGUD/UPC/AliAnalysisTaskUPCforward.cxx
Filling Pt-distributions for the neutron emission analysis only over the J/Psi peak...
=> PWGUD/UPC: Minor fix Pt-distributions.

PWGLF/SPECTRA/PiKaPr/TPCTOFCascades/AliAnalysisTaskTPCTOFCascade.cxx, PWGLF/SPECTRA/PiKaPr/TPCTOFCascades/AliAnalysisTaskTPCTOFCascade.h
Added track qualitiy cuts to get a more consistent MB spectra for Lambas and K0s
=> Commit to add track cuts for V0 candidates

PWGDQ/dielectron/LMEE/AliAnalysisTaskReducedTreeDS.cxx, PWGDQ/dielectron/LMEE/AliAnalysisTaskReducedTreeDS.h
remove unnecessary printf/AliInfo
=> remove unnecessary printing

PWGHF/vertexingHF/AliAnalysisTaskSEXicTopKpi.cxx, PWGHF/vertexingHF/AliAnalysisTaskSEXicTopKpi.h, PWGHF/vertexingHF/AliRDHFCutsXictopKpi.cxx, PWGHF/vertexingHF/AliRDHFCutsXictopKpi.h
CutObject PID strategy stored in bin centered around 0
=> Info about some PID standard cuts added to THnSparses

PWGLF/RESONANCES/macros/mini/AddTaskPhiPP13TeV_PID.C, PWGLF/RESONANCES/macros/mini/ConfigPhiPP13TeV_PID.C
- Update for ROOT6 env
- Update for temporal Signal loss extraction
=> Update for temporal Sinal loss setup

PWGUD/UPC/AliAnalysisTaskTransTask.cxx, PWGUD/UPC/AliAnalysisTaskTransTask.h
I added number of good TPC tracks to the ttree
=> added number of good TPC tracks

PWGHF/vertexingHF/AliAnalysisTaskSED0BDT.cxx, PWGHF/vertexingHF/AliAnalysisTaskSED0MassTMVA.cxx, PWGHF/vertexingHF/AliAnalysisTaskSED0MassTMVA.h, PWGHF/vertexingHF/macros/AddTaskD0BDT.C
Reduced TH3D bins to save memory usage
Added ptB-based weight
=> Reduced TH3D bins to save memory usage / Added ptB-based weight

PWGHF/vertexingHF/AliAnalysisTaskSEDs.cxx, PWGHF/vertexingHF/AliAnalysisTaskSEDs.h, PWGHF/vertexingHF/macros/AddTaskDs.C
1) add background sparse
2) remove unused ntracklets and centrality axes in sparses
3) add case of bin limits for upgrade studies
=>  Add bkg sparse, remove ntrkl and centr axes, and add bin limits for upgrade studies

PWGUD/UPC/AliAnalysisTaskUPCforward.cxx, PWGUD/UPC/AliAnalysisTaskUPCforward.h, PWGUD/UPC/AliAnalysisTaskUPCforwardMC.cxx, PWGUD/UPC/AliAnalysisTaskUPCforwardMC.h
Implemented Collins-Soper analysis too in Data only.
If I have time, I will write up the code for MC too...
=> PWGUD/UPC: Collins-Soper analysis in Data.

PWGHF/treeHF/AliHFTreeHandlerLbtoLcpi.cxx, PWGHF/treeHF/AliHFTreeHandlerLbtoLcpi.h
Fixes training variable Lb in TTree
* Primary -> Secondary vertex
* Chi2 -> Chi2overNDF
=> PWGHF: Fix Chi2 for Lb TTree

PWGJE/EMCALJetTasks/UserTasks/AliAnalysisTaskEmcalJetHPerformance.cxx
The indexing wasn't quite write in a number of places. Now it agrees
with the jet tagger
=> Fixes to jet matching

PWGLF/SPECTRA/Kinks/AliAnalysisKinkTaskPbPb2018.cxx, PWGLF/SPECTRA/Kinks/AliAnalysisKinkTaskPbPb2018.h, PWGLF/SPECTRA/Kinks/macros/AddTaskKinksPbPb2018.C
Analysis task for kink analysis in PbPb 2018 data to be used in L* studies
=> Analysis task for kink analysis in PbPb 2018 data to be used in L* studies

PWGHF/hfe/macros/configs/pp/userConfigurationEMCele_pp_pPb.yaml, PWGHF/hfe/macros/configs/pp/userConfigurationEMCele_pp_pPb_MC.yaml
Changing the EMCal clusterizer from v1 to v2 for pp data
=> Changing the EMCal clusterizer from v1 to v2

PWGHF/hfe/macros/configs/pPb/userConfigurationEMCele_pp_pPb_MC.yaml
- Adding yaml config file for MC for pPb data
- Changing the EMCal clusterizer from v1 to v2 for pPb data
=> Changing the EMCal clusterizer from v1 to v2-pPb

PWGMM/UE/CMakeLists.txt, PWGMM/UE/PWGMMueLinkDef.h, PWGMM/UE/UeSpherocity/AddTaskGenUeSpherocity.C, PWGMM/UE/UeSpherocity/AliAnalysisTaskGenUeSpherocity.cxx, PWGMM/UE/UeSpherocity/AliAnalysisTaskGenUeSpherocity.h, PWGMM/UE/macros/AddMCGenPythia8.C
The analysis task create pT spectra as a function of multiplicity and spherocity
=> additional task for MC studies

PWGHF/hfe/AliAnalysisTaskHFEBESpectraEMC.cxx, PWGHF/hfe/AliAnalysisTaskHFEBESpectraEMC.h, PWGHF/hfe/macros/AddTaskHFEBESpectraEMC.C
- Changing task to include Pb-Pb analysis
- Change cluster energy after non-linearity correction
=> Make task flexible for PbPb analysis

PWGHF/correlationHF/AliAnalysisTaskDHFeCorr.cxx, PWGHF/correlationHF/AliAnalysisTaskDHFeCorr.h, PWGHF/correlationHF/macros/default_config_d_hfe.yaml
Dear all,
I have included the ID of the electrons and D meson particles in the trees to perform some checks. I have also moved some code to make it more clear, separating the electron and the D meson part.   
Best,
Henrique
=> Include IDs in the trees

PWGLF/RESONANCES/PostProcessing/Xi1530/macros_pp13TeV/CheckReweightEfficiency.C, PWGLF/RESONANCES/PostProcessing/Xi1530/macros_pp13TeV/DrawQAPlots.C, PWGLF/RESONANCES/PostProcessing/Xi1530/macros_pp13TeV/DrawXi1530INEL.C, PWGLF/RESONANCES/PostProcessing/Xi1530/macros_pp13TeV/DrawXi1530PhysicsPlots.C, PWGLF/RESONANCES/PostProcessing/Xi1530/macros_pp13TeV/DrawingHelper.C, PWGLF/RESONANCES/PostProcessing/Xi1530/macros_pp13TeV/MCQAXi1530.C, PWGLF/RESONANCES/PostProcessing/Xi1530/macros_pp13TeV/PlotMiscXi1530.C, PWGLF/RESONANCES/PostProcessing/Xi1530/macros_pp13TeV/PlotXi1530ApprovalFigure.C, PWGLF/RESONANCES/PostProcessing/Xi1530/macros_pp13TeV/PlotXi1530INEL.C, PWGLF/RESONANCES/PostProcessing/Xi1530/macros_pp13TeV/Xi1530ANHelper.C, PWGLF/RESONANCES/PostProcessing/Xi1530/macros_pp13TeV/Xi1530PlotSystematics.C, PWGLF/RESONANCES/PostProcessing/Xi1530/macros_pp13TeV/Xi1530YieldMean.C
Contains many updates for the latest Analysis note
=> Updated macro

PWGLF/RESONANCES/PostProcessing/Xi1530/AliAnalysisTaskXi1530.cxx, PWGLF/RESONANCES/PostProcessing/Xi1530/AliAnalysisTaskXi1530.h
=> Add new functionality for the future analysis

PWGUD/UPC/AliAnalysisTaskUPCforward.cxx, PWGUD/UPC/AliAnalysisTaskUPCforward.h
Implemented Collins-Soper analysis in 2D to cross-check the Helicity Frame results.
=> PWGUD/UPC: Collins-Soper analysis in 2D.

PWGHF/hfe/macros/configs/PbPb/userConfigurationEMCele_PbPb.yaml, PWGHF/hfe/macros/configs/PbPb/userConfigurationEMCele_PbPb_MC.yaml, PWGHF/hfe/macros/configs/pPb/userConfigurationEMCele_pp_pPb.yaml, PWGHF/hfe/macros/configs/pPb/userConfigurationEMCele_pp_pPb_MC.yaml, PWGHF/hfe/macros/configs/pp/userConfigurationEMCele_pp_pPb.yaml, PWGHF/hfe/macros/configs/pp/userConfigurationEMCele_pp_pPb_MC.yaml
Adding setter to force correcting for nonlinearity of EMCal clusters
=> Adding setter to force correcting for nonlinearity

PWGLF/RESONANCES/PostProcessing/Xi1530/AliAnalysisTaskXi1530.cxx
=> Add mass window

PWGCF/Correlations/DPhi/AliAnalysisTaskV0ChCorrelation.cxx, PWGCF/Correlations/macros/AddTaskV0ChCorrelation.C
I have got new eff for tighter cut and i changed the path for eff  ,moreover change the cut for Data
=> tighter cut and eff

PWGUD/UPC/AliAnalysisTaskUPCforwardMC.cxx, PWGUD/UPC/AliAnalysisTaskUPCforwardMC.h
Added templates for yield extraction both Helicity and CS, both 1D and 2D.
=> PWGUD/UPC: Added templates for yield extraction both Helicity and CS, 1D and 2D

PWGLF/SPECTRA/CMakeLists.txt, PWGLF/SPECTRA/PWGLFspectraLinkDef.h
add the new kink class for PbPb 2018 analysis to the library
=> add the new kink class for PbPb 2018 analysis to the library

PWGHF/hfe/AliAnalysisTaskHFEBESpectraEMC.cxx, PWGHF/hfe/AliAnalysisTaskHFEBESpectraEMC.h, PWGHF/hfe/macros/AddTaskHFEBESpectraEMC.C
Adding charm and beauty weights to apply for Pb-Pb analysis
=> Add MC template weights for Pb-Pb analysis

PWGLF/RESONANCES/PostProcessing/Sigma1385/AliAnalysisTaskSigma1385PM.cxx
1 -> anti particle
0 -> ordinary
=> fix wrong antiparticle check

PWGCF/Correlations/JCORRAN/Pro/AliAnalysisTaskRidge.cxx
=> [PWGCF] Modify switch

PWGHF/hfe/AliAnalysisTaskHFEBESpectraEMC.cxx, PWGHF/hfe/AliAnalysisTaskHFEBESpectraEMC.h
Applying weight for Lc template
=> Applying weight for Lc template

PWGLF/RESONANCES/macros/mini/ConfigPhiPP13TeV_PID.C
- Disable cut for Lambda
- Check correct daughters
=> Update for the general signal loss

PWGUD/UPC/AliAnalysisTaskUpcRho0.cxx
OADB efficiency file can be loaded externaly from alien directory
=> implemented external efficiency file

PWGMM/UE/UeSpherocity/AddTaskGenUeSpherocity.C, PWGMM/UE/UeSpherocity/AliAnalysisTaskGenUeSpherocity.cxx, PWGMM/UE/UeSpherocity/AliAnalysisTaskGenUeSpherocity.h
Inclusion of pseudoefficiencies to study detector effects
=> Includig pseudo rec events

PWGCF/Correlations/DPhi/AliAnalysisTaskV0ChCorrelationpp.cxx, PWGCF/Correlations/DPhi/AliAnalysisTaskV0ChCorrelationpp.h, PWGCF/Correlations/DPhi/CMakeLists.txt, PWGCF/Correlations/DPhi/PWGCFCorrelationsDPhiLinkDef.h, PWGCF/Correlations/macros/AddTaskV0ChCorrelationpp.C
i have  been fixed  MC for Pb_Pb and first run for pp
=> Add run pp and fixed MC for Pb_Pb

PWGCF/Correlations/JCORRAN/Pro/AliJCDijetHistos.cxx
2nd try. Original commit was overwritten by mistake before pull request was accepted.
=> Changed histo binning for more general purposes.

PWGCF/Correlations/macros/AddTaskV0ChCorrelation.C
=> systematic

PWGUD/UPC/AliAnalysisTaskUPCforwardMC.cxx, PWGUD/UPC/AliAnalysisTaskUPCforwardMC.h
Implemented 2D plots to produce the ACCxEFF for 2D Collins-Soper analysis.
=> PWGUD/UPC: Missin ACCxEFF for 2D Collins-Soper.

PWGMM/UE/UeSpherocity/AliAnalysisTaskGenUeSpherocity.cxx, PWGMM/UE/UeSpherocity/AliAnalysisTaskGenUeSpherocity.h
This version of the macro includes the multiplicity classes which are compatible with those used in data
=> changes to reduce memory consumption

PWGGA/EMCALTasks/AliAnalysisTaskGammaHadron.cxx, PWGGA/EMCALTasks/AliAnalysisTaskGammaHadron.h, PWGGA/EMCALTasks/CMakeLists.txt
Integrated QnVectorCorrections for Event Plane angle and resolution
Fix compile warnings
Add hadronic correction, switch for PosSwap hists
Note: Adding the QnVectorCorrections required adding PWGPPevcharQn PWGPPevcharQnInterface to the dependencies in the CMakeList
=> Several updates for Pi0-Hadron task

PWGDQ/dimuons/AddTaskTree_Grid_MCut.C, PWGDQ/dimuons/AliAnalysisTaskTree_MCut.cxx, PWGDQ/dimuons/AliAnalysisTaskTree_MCut.h
Code allows the creation of trees containing information on the event and on dimuons. Dimuon information are stored only for masses larger than a given mass threshold.
The code refers to pp collisions at 13TeV
=> Files to create a tree containing dimuon information.

PWGLF/NUCLEX/Exotica/LambdaNN/AliAnalysisTaskLNNv0Bkg.cxx, PWGLF/NUCLEX/Exotica/LambdaNN/AliAnalysisTaskLNNv0Bkg.h, PWGLF/NUCLEX/Exotica/LambdaNN/Getoutput.cxx, PWGLF/NUCLEX/Exotica/LambdaNN/Getoutput.h
The analysis task to compute V0 combinations has been updated to include also MC information in the output. 
The class to analyze the output of the task has been also updated
=> changes to add MC information to the analysis

PWGCF/Correlations/DPhi/AliAnalysisTaskV0ChCorrelation.cxx
I have different Output ,Last time i have change for output list so i got problem for the output , Now i  fixed the problem .
=> Fix Problem for Output

PWGMM/UE/UeSpherocity/AliAnalysisTaskGenUeSpherocity.cxx
Change: Different way to get Y
=> minor change, different way to get Y

PWGHF/treeHF/AliAnalysisTaskSEHFTreeCreator.cxx, PWGHF/treeHF/AliHFTreeHandler.h
* Reflections were not stored in TTreeCreator (neither when storing signal only, nor signal+background). Needed for D0 invariant mass fit
=> PWGHF: Fix storing of reflections in TTree

PWGCF/FLOW/GF/AliAnalysisTaskGFWFlow.cxx
For some reason, I disabled it before
=> Adding an option to add QA in AliAnalysisTaskGFW

PWGLF/SPECTRA/PiKaPr/TPCTOFCascades/AliAnalysisPIDCascade.cxx, PWGLF/SPECTRA/PiKaPr/TPCTOFCascades/AliAnalysisPIDCascade.h, PWGLF/SPECTRA/PiKaPr/TPCTOFCascades/AliAnalysisTaskTPCTOFCascade.cxx, PWGLF/SPECTRA/PiKaPr/TPCTOFCascades/AliAnalysisTaskTPCTOFCascade.h
1. Change of cuts for both V0 and Cascade candidates
2. Added AliMultSelection for RefMult and SPDTracklets
3. Changed MC functionality.
4. Made changes for Cascades to check whether the associated V0s are primary or not.
=> Major Overhaul of TPCTOFCascade analysis task

PWGHF/vertexingHF/AliAnalysisTaskSEXic2eleXifromAODtracks.cxx, PWGHF/vertexingHF/AliAnalysisTaskSEXic2eleXifromAODtracks.h
To check the non prompt and promt reconstruction efficiency
=> The nonpromt and prompt efficiency check

PWGMM/UE/UeSpherocity/AddTaskGenUeSpherocity.C, PWGMM/UE/UeSpherocity/AliAnalysisTaskGenUeSpherocity.cxx, PWGMM/UE/UeSpherocity/AliAnalysisTaskGenUeSpherocity.h
Transverse momentum distributions of different particle species as a function of RT
=> implementation of RT analysis

PWGGA/GammaConv/AliAnalysisTaskGammaConvDalitzV1.cxx, PWGGA/GammaConvBase/AliConversionPhotonCuts.cxx
Correction on memory leak on declaration `new` for some histograms.
=> Memory leak on MC framework

PWGDQ/dimuons/macros/AddTaskTree_Grid_MCut.C
remove useless argument in the AddTask
=> remove useless argument in the AddTask

PWGGA/GammaConv/AliAnalysisTaskNeutralMesonToPiPlPiMiNeutralMeson.cxx, PWGGA/GammaConv/AliAnalysisTaskNeutralMesonToPiPlPiMiNeutralMeson.h, PWGGA/GammaConv/macros/AddTask_GammaConvNeutralMesonPiPlPiMiNeutralMeson_CaloMode_pp.C
- added MC histo to study pi0 momentum in dependence of omega momentum
- adapted configs for LHC11 7 TeV
=> PWGGA/GammaConv: HNM task:  added histo for MC studies

PWGHF/vertexingHF/AliAnalysisTaskSEXic2eleXifromAODtracks.cxx, PWGHF/vertexingHF/AliAnalysisTaskSEXic2eleXifromAODtracks.h, PWGHF/vertexingHF/macros/AddTaskXic2eleXifromAODtracks.C
After normalization, then update the new weighting parameters to get the new weight factor. At the same time, also using the new weight factor to reweight the reconstruction effciency.
=> Update weight factor, test reweighting efficiency

PWGCF/Correlations/DPhi/AliAnalysisTaskGeneralBF.cxx
generalized MCCT part for truth so that reference and associate particle could be selected separately.
=> PWGCF - generalized MCCT part

PWGDQ/dielectron/core/AliAnalysisTaskJpsiJet.cxx, PWGDQ/dielectron/macrosJPSI/AddTaskJpsiJet_pp.C
Other changes: update QA histograms with better binning.
=> DQ/JpsiJet - Support ITS improver task & subwagon in LEGO train

PWGCF/Correlations/DPhi/AliAnalysisTaskV0ChCorrelation.cxx
I have  been changed the right cut DCA for Lambdas
=> DCA cut for Lambdas

PWGMM/UE/UeSpherocity/AliAnalysisTaskGenUeSpherocity.cxx, PWGMM/UE/macros/AddMCGenPythia8.C
Minor change to include K*0 efficiency
=> inclusion of K*0 efficiency

PWGCF/Correlations/DPhi/AliAnalysisTaskGeneralBF.cxx, PWGCF/Correlations/macros/PIDBFDptDpt/AddTaskGeneralBF.C
added resonance decay settings in MC
=> added resonance decay settings in MC

PWGCF/Correlations/JCORRAN/Base/iaaAnalysis/AliJDiHadronIaaTask.cxx
JCard write commented out that heavily costs CPU while merging
=> Update on analysis code

PWGCF/FEMTOSCOPY/FemtoDream/AliAnalysisTaskNanoSigmaPlus.cxx, PWGCF/FEMTOSCOPY/FemtoDream/AliAnalysisTaskNanoSigmaPlus.h, PWGCF/FEMTOSCOPY/FemtoDream/CMakeLists.txt, PWGCF/FEMTOSCOPY/FemtoDream/PWGCFFemtoDreamLinkDef.h, PWGCF/FEMTOSCOPY/macros/AddTaskFemtoSigmaPlus.C
o At the moment only running on protons
=> Add task for SigmaPlus-Proton analysis

PWGHF/vertexingHF/macros/AddTaskXic2eleXifromAODtracks.C
=> new weight factor since efficiency correction

PWGCF/FEMTOSCOPY/macros/Train/DEtaDPhi/2019/MCTruth/ConfigFemtoAnalysis.C
=> AliFemto: vug fix in MC truth train

PWGMM/Mult/AliAnalysisPseudoRapidityDensity.cxx
Add 0.01-0.05 bins for HM study.
=> Multiplicity bin update

PWGLF/RESONANCES/PostProcessing/Sigma1385/AliAnalysisTaskSigma1385PM.cxx, PWGLF/RESONANCES/PostProcessing/Xi1530/NanoCheck/AliAnalysisTaskNanoCheck.cxx, PWGLF/RESONANCES/PostProcessing/Xi1530/NanoCheck/AliAnalysisTaskNanoCheck.h
This bug made a super less yield of V0
=> Fix bug: Return in for loop

PWG/EMCAL/EMCALtasks/AliEmcalCorrectionComponent.cxx
Apply L1 phase calibration for PAR runs in correction framework in AliEmcalCorrectionComponent.cxx.
=> Apply L1 phase calibration for PAR runs in correction framework

PWG/EMCAL/EMCALtasks/AliEmcalCorrectionCellTimeCalib.cxx, PWG/EMCAL/EMCALtasks/AliEmcalCorrectionCellTimeCalib.h, PWG/EMCAL/config/AliEmcalCorrectionConfiguration.yaml
The correction framework has been modified to it calibrates the low gain cells. As a first trial we will try the calibrate the low gain cells by reading the LG histogram for each period.
=> Calibrating the low gain cells

PWGLF/RESONANCES/PostProcessing/Xi1530/NanoCheck/AliAnalysisTaskNanoCheck.cxx
=> Update GetImpactParameters function for nano

PWGLF/RESONANCES/PostProcessing/Xi1530/NanoCheck/AliAnalysisTaskNanoCheck.cxx
=> Add QA functions after cut

PWGLF/RESONANCES/PostProcessing/Sigma1385/AliAnalysisTaskSigma1385PM.cxx
will affect to the nTuple information and mixed background.
=> Fix pion sign information

PWGHF/vertexingHF/TMVA/CMakeLists.txt
include XML files for TMVA mult analysis in installer directive for vertexingHF TMVA library
=> update CMakeLists for TMVA vs mult

PWGDQ/reducedTree/AliMixingHandler.cxx, PWGDQ/reducedTree/AliReducedAnalysisJpsi2eeCorrelations.cxx
required for EMCal triggered analysis
=> PWGDQ/reducedTree: updates for correlation event mixing

PWGCF/Correlations/JCORRAN/Pro/AliJCDijetAna.cxx, PWGCF/Correlations/JCORRAN/Pro/AliJCDijetAna.h, PWGCF/Correlations/JCORRAN/Pro/AliJCDijetHistos.cxx, PWGCF/Correlations/JCORRAN/Pro/AliJCDijetHistos.h, PWGCF/Correlations/JCORRAN/Pro/AliJCDijetTask.cxx
Added delta-pt and other histograms. Dijet invariant mass matching
improved so that a dijet is a match even if leading and subleading jets
change places.
=> New histos and dijet matching improved.

PWG/Tools/AliMCSpectraWeights.cxx, PWG/Tools/AliMCSpectraWeights.h, PWG/Tools/CMakeLists.txt, PWGLF/SPECTRA/ChargedHadrons/AliMCSpectraWeights/AliMCSpectraWeightsAnalysisTask.cxx, PWGLF/SPECTRA/ChargedHadrons/AliMCSpectraWeights/AliMCSpectraWeightsAnalysisTask.h, PWGLF/SPECTRA/ChargedHadrons/dNdPt/AliAnalysisTaskBaseWeights.cxx
update analysis task for particle composition correction to new interface
update AliAnalysisTaskBaseWeights for new pcc interface
Bug fix for ROOT5 compatibility
removed defaulting copy, move constructor/assignments
re-organising includes to get ROOT5 compatibility
Solve ROOT5 linking issue for AliMCSpectraWeights
=> Update particle composition: pPb, PbPb and XeXe

PWGCF/Correlations/JCORRAN/Pro/AliJCDijetAna.cxx, PWGCF/Correlations/JCORRAN/Pro/AliJCDijetAna.h, PWGCF/Correlations/JCORRAN/Pro/AliJCDijetTask.cxx, PWGCF/Correlations/JCORRAN/Pro/AliJCDijetTask.h, PWGCF/Correlations/macros/jcorran/AddTaskJCDijetTask.C
Added min jet pt as an argument. In addition changed the dijet matching
which was actually planned already for the previous commit.
=> Added min jet pt as an argument + fix

PWGLF/RESONANCES/PostProcessing/f0980/AliAnalysisTaskInclusivef0f2.cxx
Modified multiplicity binning 
Check signal loss for abundant particles
=> [PWGLF] Modified multiplicity binning

PWGHF/vertexingHF/AliHFVnVsMassFitter.h
=> Add getters to retrieve fit functions

PWGCF/Correlations/DPhi/AliAnalysisTaskV0ChCorrelation.cxx, PWGCF/Correlations/macros/AddTaskV0ChCorrelation.C
i  have implement the Bunch off pile up track by track and got eff for Peripherial .
=> Task Peripherial 

PWGUD/UPC/AddTaskUPCforwardpPb.C, PWGUD/UPC/AliAnalysisTaskUPCforwardpPb.cxx, PWGUD/UPC/AliAnalysisTaskUPCforwardpPb.h, PWGUD/UPC/CMakeLists.txt, PWGUD/UPC/PWGUDupcLinkDef.h
Added new analysis task for pPb with 2016 data.
Periods LHC16r and LHC16s.
IMPORTANT: tested only for compilation and minor bugs.
=> PWGUD/UPC: Added new analysis task for pPb with 2016 data.

PWGHF/hfe/AliAnalysisTaskTPCCalBeauty.cxx, PWGHF/hfe/AliAnalysisTaskTPCCalBeauty.h, PWGHF/hfe/macros/AddTaskTPCCalBeauty.C
and added ITS+TPC refit on partner electron in invariant mass.
=> Added ability to change DCA z cut

PWGHF/vertexingHF/AliAnalysisTaskSEXicPlus2XiPiPifromAODtracks.cxx, PWGHF/vertexingHF/AliAnalysisTaskSEXicPlus2XiPiPifromAODtracks.h
Task modified to reduce the size of the output
=> Adding some QA plots and reducing TTree size

PWGCF/Correlations/JCORRAN/Pro/AliAnalysisTaskRidge.cxx
Change the trigger of AliJJetTask when kHighMultV0 is used for analysis.
=> [PWGCF] Change the trigger of AliJJetTask

PWGMM/UE/UeSpherocity/AliAnalysisTaskGenUeSpherocity.cxx, PWGMM/UE/UeSpherocity/AliAnalysisTaskGenUeSpherocity.h
New multiplicity classes were added
=> The multiplicity bins were updated

PWG/FLOW/Tasks/AliAnalysisTaskCMEV0PID.cxx, PWG/FLOW/Tasks/AliAnalysisTaskCMEV0PID.h
Update my CME task for additional NUA+ Correction
=> Update my CME task for additional NUA+ Correction

PWGCF/FEMTOSCOPY/FemtoDream/AliAnalysisTaskFemtoDreamPion.cxx, PWGCF/FEMTOSCOPY/FemtoDream/AliAnalysisTaskFemtoDreamPion.h, PWGCF/FEMTOSCOPY/FemtoDream/CMakeLists.txt, PWGCF/FEMTOSCOPY/FemtoDream/PWGCFFemtoDreamLinkDef.h, PWGCF/FEMTOSCOPY/macros/AddTaskFemtoDreamPion.C
Not yet ready to be used on the grid for the intended purpose. Needs additional testing (most certainly contains some mistake) + tuning of some cuts.
=> Setting up the pion analysis.

PWGGA/GammaConv/AliAnalysisTaskGammaConvDalitzV1.cxx, PWGGA/GammaConvBase/AliDalitzAODESD.cxx, PWGGA/GammaConvBase/AliDalitzAODESD.h, PWGGA/GammaConvBase/AliDalitzElectronCuts.cxx
With this new commit only a few block are lost for part of AliV0reader, and Dalitz reaming constant.
Regards
Edgar
=> Better way to calculate the varibles on Constrained Param

PWGCF/FEMTOSCOPY/AliFemto/AliFemtoCutMonitorV0.cxx, PWGCF/FEMTOSCOPY/AliFemto/AliFemtoCutMonitorXi.cxx
reducing bin numbers in monitors of Minv and CPA vs pT for V0 and cascades
=> AliFemto: reducing number of bins in monitors

PWGCF/FEMTOSCOPY/macros/Train/DEtaDPhi/2019/CorrAOD/Xi/ConfigFemtoAnalysis.C
adding config to run Xi analysis on MC reconstructed AODs
=> AliFemto: adding Config for Xi MC Closure Test

PWGMM/UE/UeSpherocity/AliAnalysisTaskGenUeSpherocity.cxx, PWGMM/UE/UeSpherocity/AliAnalysisTaskGenUeSpherocity.h, PWGMM/UE/macros/AddMCGenPythia8.C
Minor change in the definition of the function AddMCGenPythia8
=> minor change applied to AddMCGenPythia8

PWGGA/GammaConvBase/AliDalitzAODESD.cxx
As the name said, return for GetParamG, thanks to Florian for the help and Nico as always.
Regards
Edgar
=> return statment on GetParamG

PWGDQ/reducedTree/AliReducedAnalysisJpsi2ee.cxx, PWGDQ/reducedTree/AliReducedVarCut.cxx, PWGDQ/reducedTree/AliReducedVarCut.h, PWGDQ/reducedTree/AliReducedVarManager.cxx, PWGDQ/reducedTree/AliReducedVarManager.h
- AliReducedVarManager : added trigger pair decay length and SPD pair type (also had to update AliReducedAnalysisJpsi2ee accordingly)
- AliReducedVarCut : added 2nd dependent variable to function cuts
- AliReducedVarManager: added flag for EMCal triggered event
=> PWGDQ/reducedTree: updates for correlation analysis

PWGUD/UPC/AddTaskADin2018.C, PWGUD/UPC/AliAnalysisTaskADin2018.cxx, PWGUD/UPC/AliAnalysisTaskADin2018.h, PWGUD/UPC/CMakeLists.txt, PWGUD/UPC/PWGUDupcLinkDef.h
New analysis task to check the status of the AD.
=> PWGUD/UPC: Analysis task to check the status of the AD.

PWGUD/UPC/AddTaskForMCpPb.C, PWGUD/UPC/AliAnalysisTaskForMCpPb.cxx, PWGUD/UPC/AliAnalysisTaskForMCpPb.h, PWGUD/UPC/CMakeLists.txt, PWGUD/UPC/PWGUDupcLinkDef.h
Very simple analysis task for the 2016 pPb MC.
No LUMI cap has been applied as of yet (missing lumi for the 2016 UPC dataset atm)...
=> PWGUD/UPC: Analysis task for MC pPb 2016. NO LUMI CAP.

PWGUD/UPC/AliAnalysisTaskUPCforwardpPb.cxx, PWGUD/UPC/AliAnalysisTaskUPCforwardpPb.h
Pt-integrated, rapidity-differential analysis in pPb.
=> PWGUD/UPC: Pt-integrated, rapidity-differential analysis in pPb.

PWGMM/UE/macros/AddMCGenPythia8.C
=> AddMCGenPythia8.C was slightly modified

PWGCF/FEMTOSCOPY/FemtoDream/AliAnalysisTaskNanoAODFemtoDreamPion.cxx, PWGCF/FEMTOSCOPY/FemtoDream/AliAnalysisTaskNanoAODFemtoDreamPion.h, PWGCF/FEMTOSCOPY/FemtoDream/CMakeLists.txt, PWGCF/FEMTOSCOPY/FemtoDream/PWGCFFemtoDreamLinkDef.h, PWGCF/FEMTOSCOPY/macros/AddTaskNanoAODFemtoDreamPion.C
Base cut in dPhi and dEta on previous ALICE results.
=> Introduce also Pion-Analysis for NanoAODs.

PWGHF/vertexingHF/AliAnalysisTaskTrackingSysPropagation.cxx, PWGHF/vertexingHF/AliAnalysisTaskTrackingSysPropagation.h, PWGHF/vertexingHF/macros/AddTaskTrackingSysPropagation.C
Changes to TrackingSysPropagation.cxx, .h and the corresponding AddTask macro to include Lc as an option.
=> Lc (pKpi and pK0s) added to SysPropagation

PWGGA/GammaConv/AliAnalysisTaskGammaConvDalitzV1.cxx
=> Delete that break everthing

PWGUD/UPC/AddTaskADin2018.C
IMPORTANT: it works, but I am not too sure if this is enough to access the subwagon feature...
=> PWGUD/UPC: Add subwagon feature.

PWGLF/STRANGENESS/Cascades/Run2/AliAnalysisTaskStrangeCascadesDiscrete.cxx, PWGLF/STRANGENESS/Cascades/Run2/AliAnalysisTaskStrangeCascadesDiscrete.h, PWGLF/STRANGENESS/Cascades/Run2/macros/AddTaskStrangeCascadesDiscrete.C
- all obsolete parts of the code, which made it unnecessarily heavy and unreadable, are removed.
- No cuts are made on number of ITS layers, crossed by selected tracks. ITS status is saved as UShort_t. ITS pid information is also saved in the output tree now. 
- TPC PID cuts can be now set in AddTask.
- TOF PID is saved in the output.
- No cuts on the Xi mass any more.
=> Unused parts are removed. New features added.

PWGDQ/dielectron/macrosLMEE/Config_acapon.C, PWGDQ/dielectron/macrosLMEE/Config_acapon_Efficiency.C, PWGDQ/dielectron/macrosLMEE/LMEECutLib_acapon.C
Bring single pt cut in line with pp dielectron analysis
=> Add pt<10 cut set (kCutSet3)

PWGLF/RESONANCES/PostProcessing/f0980/AliAnalysisTaskInclusivef0f2.cxx, PWGLF/RESONANCES/PostProcessing/f0980/AliAnalysisTaskInclusivef0f2.h
Implementation of AliEventCuts for 2018PbPb.
Making initial configuration work one time.
=> [PWGLF] Implementation of AliEventCuts for 2018PbPb

PWGCF/FEMTOSCOPY/macros/Train/trainOct2019/KK_13TeV_dist/AddTaskFemtoKchHBT1090.C, PWGCF/FEMTOSCOPY/macros/Train/trainOct2019/KK_13TeV_dist/ConfigFemtoAnalysis.C, PWGCF/FEMTOSCOPY/macros/Train/trainOct2019/KK_13TeV_jets/AddTaskFemtoKchHBT1090.C, PWGCF/FEMTOSCOPY/macros/Train/trainOct2019/KK_13TeV_jets/ConfigFemtoAnalysis.C, PWGCF/FEMTOSCOPY/macros/Train/trainOct2019/KpKm_13TeV_dist/AddTaskFemtoKchHBT1090.C, PWGCF/FEMTOSCOPY/macros/Train/trainOct2019/KpKm_13TeV_dist/ConfigFemtoAnalysis.C, PWGCF/FEMTOSCOPY/macros/Train/trainOct2019/KpKm_13TeV_jets/AddTaskFemtoKchHBT1090.C, PWGCF/FEMTOSCOPY/macros/Train/trainOct2019/KpKm_13TeV_jets/ConfigFemtoAnalysis.C, PWGCF/FEMTOSCOPY/macros/Train/trainOct2019/pipi_13TeV_dist/AddTaskFemtoKchHBT1090.C, PWGCF/FEMTOSCOPY/macros/Train/trainOct2019/pipi_13TeV_dist/ConfigFemtoAnalysis.C, PWGCF/FEMTOSCOPY/macros/Train/trainOct2019/pipi_13TeV_jets/AddTaskFemtoKchHBT1090.C, PWGCF/FEMTOSCOPY/macros/Train/trainOct2019/pipi_13TeV_jets/ConfigFemtoAnalysis.C, PWGCF/FEMTOSCOPY/macros/Train/trainOct2019/pippim_13TeV_dist/AddTaskFemtoKchHBT1090.C, PWGCF/FEMTOSCOPY/macros/Train/trainOct2019/pippim_13TeV_dist/ConfigFemtoAnalysis.C, PWGCF/FEMTOSCOPY/macros/Train/trainOct2019/pippim_13TeV_jets/AddTaskFemtoKchHBT1090.C, PWGCF/FEMTOSCOPY/macros/Train/trainOct2019/pippim_13TeV_jets/ConfigFemtoAnalysis.C
=> Lego Train macro by request Ludmila Malinina

PWGGA/CaloTrackCorrelations/AliAnaCaloExotics.cxx, PWGGA/CaloTrackCorrelations/AliAnaCaloExotics.h, PWGGA/CaloTrackCorrelations/macros/ConfigureCaloTrackCorrAnalysis.C
- Remove Low Gain cell histogram
- Add histograms m02 vs exo vs n cells for different energy bins
- Change cluster eta-phi by highest energy cell column-row and add E dependence
- Add switchs to include track matching histograms or single cell histograms
=> Remove unused and add new histograms and switchs

PWGHF/vertexingHF/AliHFSystErr.cxx, PWGHF/vertexingHF/AliHFSystErr.h
D0 and Lc systematics for 13TeV
=> D0 and Lc systematics for 13TeV

PWGGA/EMCALTasks/AliAnalysisTaskGammaHadron.cxx, PWGGA/EMCALTasks/AliAnalysisTaskGammaHadron.h
Fixes an error in when acceptance array is reset.
Adds 2 histograms
=> Fixes cluster acceptance check

PWGDQ/reducedTree/AliCorrelationExtraction.cxx
normalization was sensitive to equal/not equal bin sizes, it's not anymore
=> PWGDQ/reducedTree/AliCorrelationExtraction: bugfix in bin width norm

PWGLF/RESONANCES/PostProcessing/f0980/AliAnalysisTaskInclusivef0f2.cxx
Change boolean name for 2018 PbPb
=> [PWGLF] Change boolean name

PWGCF/Correlations/JCORRAN/Base/AliJCatalystTask.cxx, PWGCF/Correlations/JCORRAN/Base/AliJCatalystTask.h, PWGCF/Correlations/JCORRAN/Pro/AliJCDijetAna.cxx, PWGCF/Correlations/JCORRAN/Pro/AliJCDijetHistos.cxx, PWGCF/Correlations/JCORRAN/Pro/AliJCDijetHistos.h, PWGCF/Correlations/JCORRAN/Pro/AliJCDijetTask.cxx, PWGCF/Correlations/JCORRAN/Pro/AliJCDijetTask.h, PWGCF/Correlations/macros/jcorran/AddTaskJCDijetTask.C
Now only events which are accepted by aliJCatalystTask are counted. Also
added an argument which can be used to choose additional event rejection
criteria.
=> Fixed event counting bug + added more arguments.

PWGLF/RESONANCES/AliRsnCutMiniPair.cxx, PWGLF/RESONANCES/AliRsnCutMiniPair.h, PWGLF/RESONANCES/AliRsnMiniPair.cxx, PWGLF/RESONANCES/AliRsnMiniPair.h, PWGLF/RESONANCES/AliRsnMiniValue.cxx, PWGLF/RESONANCES/AliRsnMiniValue.h
Add pair asymmetry variable for pair asymmetry cut in resonance decays
=> Add pair asymmetry variable for pair asymmetry cut in resonance decays

PWGLF/RESONANCES/PostProcessing/f0980/AliAnalysisTaskInclusivef0f2.cxx
Allocation of initial values for event selection flag
=> [PWGLF] Allocation of initial values

PWGLF/RESONANCES/macros/mini/AddTaskSigPM.C, PWGLF/RESONANCES/macros/mini/ConfigSigPM.C
Add asymmetry cut in candidate resonance pairs for sigma star analysis
=> Add asymmetry cut in candidate resonance pairs for sigma star analysis 

PWGUD/UPC/nanoAOD/AliAnalysisTaskUpcNano_MB.cxx
Some branches are set to be used in MC case only
=> Changing TTree branches definition

PWGHF/vertexingHF/AliAnalysisVertexingHF.cxx, PWGHF/vertexingHF/AliAnalysisVertexingHF.h
2-prong vertex calculated only for 3-prong candidates passing other cuts
=> Speed up AOD vertexingHF (2-prong vertex calculation)

PWGCF/Correlations/JCORRAN/Pro/AliJCDijetAna.cxx, PWGCF/Correlations/JCORRAN/Pro/AliJCDijetAna.h, PWGCF/Correlations/JCORRAN/Pro/AliJCDijetTask.cxx, PWGCF/Correlations/JCORRAN/Pro/AliJCDijetTask.h, PWGCF/Correlations/macros/jcorran/AddTaskJCDijetTask.C
Added an argument for the AddTask macro.
=> Det MC can now be run with tracking ineff

PWGGA/CaloTrackCorrelations/AliAnaCaloExotics.cxx
=> fixes in histogram ranges, an exoticity inversed condition 

RUN3/AliAnalysisTaskAO2Dconverter.cxx, RUN3/AliAnalysisTaskAO2Dconverter.h, RUN3/CMakeLists.txt
- Add gain type to cell table
- Add table for calorimeter trigger information
=> [EMCAL-625] Adaptions of CALO tables for EMCAL

PWGGA/CaloTrackCorrelations/AliAnaCaloExotics.cxx, PWGGA/CaloTrackCorrelations/AliAnaCaloExotics.h
and clusters with cells in same T-Card
=> Add histograms to check high number of cells clusters, per SM, 

PWGUD/UPC/AliAnalysisTaskADin2018.cxx, PWGUD/UPC/AliAnalysisTaskADin2018.h
Check for CMUP6.
Using the AD HW trigger bits.
Comparison with SW decisions too.
IMPORTANT: commonly used on GRID. Updating it on the LEGO trains for bookkeeping and to allow 
others to check the code I am normally using on GRID.
=> PWGUD/UPC: Update with AD trigger bits.

PWGGA/GammaConv/AliAnalysisTaskGammaConvDalitzV1.cxx, PWGGA/GammaConvBase/AliDalitzAODESD.cxx, PWGGA/GammaConvBase/AliDalitzAODESD.h
PsiPair calculation, like previous commit.
Regards
Edgar
=> Calculation of PsiPair

PWGMM/UE/UeSpherocity/AliAnalysisTaskGenUeSpherocity.cxx, PWGMM/UE/UeSpherocity/AliAnalysisTaskGenUeSpherocity.h
Nch>10 was implemented for So calculation
=> minor changes to match the analysis conditions

PWG/FLOW/Tasks/AliAnalysisTaskTwoMultiCorrelations.cxx, PWG/FLOW/Tasks/AliAnalysisTaskTwoMultiCorrelations.h, PWG/FLOW/Tasks/CMakeLists.txt
* Correction hard-coded for TPC-only tracks and LHC10h datasets.
=> [PWGCF] Implementation of the pt efficiency correction.

PWGCF/Correlations/JCORRAN/Pro/AliAnalysisTaskRidge.cxx, PWGCF/Correlations/JCORRAN/Pro/AliAnalysisTaskRidge.h, PWGCF/Correlations/macros/jcorran/AddTaskRidge.C
Reduce memory usage by changing bin definitions and flag for M.C.
=> [PWGCF] Reduction of memory usage

PWGPP/AliAnalysisTaskFilteredTree.cxx, PWGPP/AliPIDtools.cxx, PWGPP/AliPIDtools.h
+ adding static interface to be able to query PID information in TTree anf TFormulas
+ adding nuclei PID infromation  - before only forts 5 PID species stored
=> PWGPP-538, PWGPP-565- enable ITS and TOF PID in queries +add nuclei PID info

PWGCF/FEMTOSCOPY/macros/AddTaskFemtoLoton.C, PWGCF/FEMTOSCOPY/macros/AddTaskFemtoXoton.C
=> calculated the mom resolution in case of mc

PWGGA/GammaConv/macros/AddTask_GammaConvDalitzV1_pp.C
Extra config, plus a correction on low Rejection cut and momentum cut for pions on primary vertex selection
=> Correction on configs

PWGGA/GammaConv/macros/AddTask_GammaConvDalitzV1_pp.C
New Standard cut on almost everything plus trains for material budget
Atte
Edgar
=> Implementation of New Standard cut

PWGCF/Correlations/JCORRAN/Pro/AliAnalysisTaskRidge.cxx
No check of events outside bin definition
=> [PWGCF] No check of events outside bin definition

PWGLF/NUCLEX/Nuclei/AbsorptionRatios/AliAnalysisTaskHe3.cxx, PWGLF/NUCLEX/Nuclei/AbsorptionRatios/AliAnalysisTaskHe3.h, PWGLF/NUCLEX/Nuclei/AbsorptionRatios/macros/AddHighMultHe3Task.C
Added an analysis task to extract raw (anti-) Helium 3 ratios.
=> Added High Multiplicity (anti-)He3 ratios Analysis Task.

PWGCF/Correlations/JCORRAN/Pro/AliAnalysisTaskRidge.cxx
Allocate init. value
Check bin number during mixing stage.
=> [PWGCF] Allocate init. value

PWGUD/UPC/AliAnalysisTaskUPCforwardpPb.cxx, PWGUD/UPC/AliAnalysisTaskUPCforwardpPb.h
IMPORTANT: tested. Just an update for the GRID.
=> PWGUD/UPC: ZDC analysis for pPb LHC16s.

PWGGA/EMCALTasks/AliAnalysisTaskGammaHadron.cxx, PWGGA/EMCALTasks/AliAnalysisTaskGammaHadron.h
Fixes errors in MC handling and in EP angle calculations
Adds histos monitoring tracks
=> Fix EP angle issues, MC issues

PWGHF/vertexingHF/AliAnalysisVertexingHF.cxx, PWGHF/vertexingHF/AliAnalysisVertexingHF.h
when the primary vertex is not recalculated
=> Skip track propagation to DCA to primary vertex when not needed

PWGJE/FlavourJetTasks/AliAnalysisTaskHFJetIPQA.cxx, PWGJE/FlavourJetTasks/AliAnalysisTaskHFJetIPQA.h, PWGJE/FlavourJetTasks/macros/AddTaskHFJetIPQA.C
- introduce individual functions for cutting on DCA, vertex/event, track
- adapt cut default values
- combine all cut values in fAnalysisCuts
=> AliAnalysisTaskHFJetIPQA: adapt cut settings
